libraries/AC_WPNav/AC_WPNav.cpp

The minimum radius became 5 cm in the following PR.
Change the value of configuration parameter.
https://github.com/ArduPilot/ardupilot/pull/11196

AP_WPNav: Change the value of the minimum effective radius

---

AntennaTracker/system.cpp

initialise battery library on tracker

tracker: initialise battery

---

AntennaTracker/system.cpp

back port of https://github.com/ArduPilot/ardupilot/pull/11208

tracker: initialise battery backport

---

Tools/scripts/build_binaries.py

The build target for Solo was changed from CubeBlack-solo to CubeSolo.  This updates the builder script.

Change auto build script from CubeBlack-solo to CubeSolo.

---

Tools/autotest/common.py

Will stop cascading failures from occuring

Tools: autotest: ensure reboot if dataflash-over-mavlink test fails

---

libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp

Allows them to be called by const functions...

GCS_MAVLink: make send_text and send_textv const

---

ArduPlane/mode.h
ArduPlane/mode_qautotune.cpp

this was lost in the onion changes

Plane: fixed qautotune exit

---

libraries/AP_AHRS/examples/AHRS_Test/AHRS_Test.cpp
libraries/AP_Compass/examples/AP_Compass_test/AP_Compass_test.cpp
libraries/AP_GPS/examples/GPS_AUTO_test/GPS_AUTO_test.cpp

Those test were segfaulting due to recent changes

Fix some tests

---

Tools/ardupilotwaf/boards.py
libraries/AP_HAL_SITL/sitl_gps.cpp
libraries/GCS_MAVLink/GCS_MAVLink.h

@lucasdemarchi pragma'ing away seems to work quite well.  There's only a couple of extra warnings thrown after this PR.

Fix/squelch aligned-members issues shown by g++-9

---

Tools/scripts/gen_stable.py
Tools/scripts/generate_manifest.py

this will ensure that all future stable releases are kept for users to
select with the GCS

Tools: keep old stable releases

---

Tools/scripts/generate_manifest.py

Tools: added mapping for brand name and manufacturer

---

libraries/AP_Common/Location.h
libraries/SITL/SIM_Precland.cpp

Sadly not all as one is not checked in Copter ATM.

Add WARN_IF_UNUSED to some Location methods

---

ArduCopter/mode_althold.cpp
ArduCopter/mode_flowhold.cpp
ArduCopter/mode_loiter.cpp
ArduCopter/mode_poshold.cpp
ArduCopter/mode_sport.cpp
ArduCopter/takeoff.cpp

The logic around the poshold changes is the most complicated to nut out.  But this seems to be correct and makes it look like the other modes.

Tidy user takeoff

---

ArduPlane/afs_plane.h
libraries/AP_LeakDetector/AP_LeakDetector_Analog.h
libraries/AP_LeakDetector/AP_LeakDetector_Digital.h

Discovered these as part of adding `-Wsuggest-overrides` for gcc

Add missing override keywords

---

Tools/scripts/playback_log_fg.py

allows for visualising flights using flightgear with onboard log

Tools: added playback tool for onboard logs

---

libraries/AP_HAL/Util.h
libraries/AP_HAL_ChibiOS/I2CDevice.cpp
libraries/AP_HAL_ChibiOS/SPIDevice.cpp
libraries/AP_HAL_ChibiOS/Scheduler.cpp
libraries/AP_Logger/LogStructure.h
libraries/AP_Scheduler/AP_Scheduler.cpp
libraries/GCS_MAVLink/GCS_Common.cpp

These are useful for seeing if a bus has failed

Watchdog: log SPI and I2C bus operation counters

---

Tools/ardupilotwaf/boards.py
Tools/autotest/sim_vehicle.py
libraries/AP_Notify/AP_Notify.cpp
libraries/AP_Notify/AP_Notify.h
libraries/AP_Notify/SITL_SFML_LED.cpp
libraries/AP_Notify/SITL_SFML_LED.h
libraries/AP_OSD/AP_OSD_SITL.cpp
wscript

.... kind of like the OSD but... somewhat simpler...

Add simulated SITL RGBLed using sf windowing

---

libraries/SITL/SIM_Gazebo.cpp

Corrected comment position, fixed spelling

SITL: Gazebo: Fixed comment, typos

---

libraries/AP_Common/Bitmask.h
libraries/AP_Common/tests/test_bitmask.cpp
libraries/AP_InternalError/AP_InternalError.h

Add sanity check to bitmask's get method

---

Tools/autotest/common.py

Sometimes you really just don't care what the data is.  We can save CPU time by just discarding it.

Tools: autotest: add drain_mav_unparsed and use it

---

libraries/AP_Logger/LogStructure.h
libraries/AP_Logger/README.md

... also sort information to the top in `LogStructure.h`

Create a README.md to hold logger information

---

libraries/AP_Button/AP_Button.cpp
libraries/GCS_MAVLink/GCS.cpp
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_MAVLink.cpp

Sadly (and a little surprisingly), this currently makes fmuv3 build 72 bytes larger for me :-(

Remove FOR_EACH_ACTIVE_CHANNEL macro

---

libraries/AP_InertialSensor/AP_InertialSensor.cpp
libraries/AP_InertialSensor/AP_InertialSensor.h
libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
libraries/AP_InertialSensor/BatchSampler.cpp
libraries/Filter/NotchFilter.cpp
libraries/Filter/NotchFilter.h

https://github.com/ArduPilot/ardupilot/issues/11346
Allocate a notch filter per-IMU.
Update the notch filters in the backend at the sensor sample rate.
Allow raw logging of post-filtered gyro and accel values.

Notch filter update to IMU sample rate and allow logging post-filtering

---

libraries/AC_Avoidance/AC_Avoid.cpp

Our actual behaviour is dictated by AVOID_BEHAVE - we may not stop

AC_Avoid: improve documentation of AVOID_ENABLE options

---

ArduPlane/AP_Arming.cpp
ArduPlane/Parameters.cpp
ArduPlane/Plane.h
ArduPlane/geofence.cpp

this enables the fence when arming. If the vehicle is outside the
fence or it can't be enabled then arming fails

Plane: added FENCE_AUTOENABLE=3 option

---

libraries/AP_Compass/Compass_learn.cpp
libraries/AP_Declination/AP_Declination.cpp
libraries/AP_Declination/AP_Declination.h
libraries/AP_NavEKF2/AP_NavEKF2.cpp
libraries/AP_NavEKF2/AP_NavEKF2.h
libraries/AP_NavEKF2/AP_NavEKF2_MagFusion.cpp
libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp
libraries/AP_NavEKF2/AP_NavEKF2_core.cpp
libraries/AP_NavEKF2/AP_NavEKF2_core.h

EKF: added EK2_MAG_EF_LIM

---

Tools/ardupilotwaf/boards.py
libraries/GCS_MAVLink/GCS_Common.cpp

This means we catch this compiler warning in CI.

Add -Wparenthesis

---

Tools/autotest/arduplane.py

Otherwise we breach the fence while loitering...

Tools: autotest: disable fence when RTLing to home

---

Tools/FilterTestTool/BiquadFilter.py
Tools/FilterTestTool/FilterTest.py
Tools/FilterTestTool/Readme.md
Tools/FilterTestTool/run_filter_test.py

Here's a tool to simulate IMU filtering to raw logs and see effects on simulated FFT graph.
More info here https://discuss.ardupilot.org/t/imu-filter-tool/43633

Tools: add IMU filter test tool

---

APMrover2/GCS_Mavlink.cpp
ArduCopter/GCS_Copter.h
ArduCopter/GCS_Mavlink.cpp
ArduPlane/GCS_Mavlink.cpp
ArduSub/GCS_Mavlink.cpp
ArduSub/GCS_Sub.h
libraries/GCS_MAVLink/GCS.cpp
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp

Fixes sensor error loop for Sub and Tracker.

Refactor out-of-time-to-send-messages

---

Tools/scripts/uploader.py

Add option to make it absolutely clear what the MCU revision is and
whether it is flawed

Tools: script: uploader.py: add --identify option

---

Tools/autotest/arduplane.py

Tools: autotest: loosen check for wait_circling_point_with_radius

---

libraries/SITL/SIM_Aircraft.cpp

SITL: fixed pitch constraint on fixed wing takeoff

---

libraries/AP_RCProtocol/AP_RCProtocol.h
libraries/AP_RCProtocol/AP_RCProtocol_SRXL.cpp

thanks to coverity 343308 and Peter for noticing

AP_RCProtocol: fixed a overflow in SRXL decoder

---

libraries/AP_Motors/AP_MotorsHeli.cpp
libraries/AP_Motors/AP_MotorsHeli.h

AP_Motors: fixed col max and min for dual heli

---

Tools/autotest/apmrover2.py
Tools/autotest/arducopter.py
Tools/autotest/common.py

W605 invalid escape sequence '\s'
F402 import 'time' from line 10 shadowed by loop variable
E101 indentation contains mixed spaces and tabs
E703 statement ends with a semicolon

Tools: update with flake8

---

libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp
libraries/AP_NavEKF2/AP_NavEKF2_PosVelFusion.cpp
libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp

These are two additional patches to origin handling suggested by @OXINARF during the recent discussions on the origin handling bug in plane
I missed these in the merge of #11676

EKF: origin fixes from Francisco

---

libraries/AP_Beacon/AP_Beacon_Marvelmind.cpp
libraries/AP_Beacon/AP_Beacon_Marvelmind.h
libraries/AP_Math/crc.cpp
libraries/AP_Math/crc.h
libraries/AP_RangeFinder/AP_RangeFinder_LeddarOne.cpp

I discovered that there are several modbus CRC calculation methods.
I made it a common method.

Libraries: Common modbus crc method

---

libraries/AP_HAL_ChibiOS/HAL_ChibiOS_Class.cpp

semline was being overwritten in the setup() call

HAL_ChibiOS: fixed SemLine data in WDOG msg

---

libraries/AP_Notify/ToneAlarm.cpp

This restores the tone we used with nuttx builds for booting with no microSD

AP_Notify: play error tone if we have no microSD at boot

---

ArduSub/Parameters.cpp

Sub: correct LOIT parameter documentation prefix

---

Tools/autotest/apmrover2.py
Tools/autotest/common.py
Tools/autotest/pysim/util.py

remove relay and log modules from default

Mavproxy removal1

---

libraries/AC_AttitudeControl/AC_PosControl.cpp
libraries/AC_AttitudeControl/AC_PosControl.h
libraries/AC_AttitudeControl/AC_PosControl_Sub.cpp

Addresses a problem where we don't initialise the acceleration PID properly when we switch from a manual mode in flight.

AC_AttitudeControl: Alt Hold init bug

---

libraries/AP_OSD/AP_OSD_Screen.cpp

recheck of final wiki doc after merge shows a few mistakes..

OSD: fixes missing param def for SATS_EN and typos

---

libraries/GCS_MAVLink/GCS_DeviceOp.cpp

useful for i2c devices such as LW20 lidar

GCS_MAVLink: allow non-register device access with devop

---

AntennaTracker/Parameters.cpp
AntennaTracker/Parameters.h
AntennaTracker/control_manual.cpp
AntennaTracker/defines.h
AntennaTracker/servos.cpp
AntennaTracker/tracking.cpp

This should fix https://github.com/ArduPilot/ardupilot/issues/11575

Tracker disarmed pwm bug fix

---

libraries/AP_OSD/AP_OSD_Screen.cpp

AP_OSD_Screen: fix param descriptions

---

AntennaTracker/Parameters.cpp
AntennaTracker/Parameters.h
AntennaTracker/control_manual.cpp
AntennaTracker/defines.h
AntennaTracker/servos.cpp
AntennaTracker/tracking.cpp

Backport of https://github.com/ArduPilot/ardupilot/pull/11578 . Builds but have not tested, cherry picked over cleanly so I don't foresee any issue

Tracker: add disarmed pwm param Backport

---

Tools/autotest/apmrover2.py
Tools/autotest/common.py

This was `stash@{50}` from 2017...

Tools: autotest: add test for Rover SmartRTL

---

libraries/AP_Scripting/generator/description/bindings.desc
libraries/AP_Scripting/generator/src/main.c
libraries/AP_Scripting/lua_generated_bindings.cpp

Also fixes small whitespace problem in generated code.
For @peterbarker

AP_Scripting: Protect send_text from reading the stack

---

libraries/AP_Logger/LogStructure.h

Small label change missed in the previous pull request.

AP_Logger: Missing label change

---

libraries/AP_Math/AP_Math.h
libraries/AP_Math/location.h
libraries/AP_Math/matrix3.h
libraries/AP_Math/polygon.h
libraries/AP_Math/quaternion.h
libraries/AP_Math/vector2.h
libraries/AP_Math/vector3.h

I've previously thought these wouldn't be useful.  And then <redacted> proved me wrong :-)

AP_Math: add WARN_IF_UNUSED to bool methods

---

libraries/AP_AccelCal/AP_AccelCal.cpp
libraries/AP_GPS/GPS_Backend.cpp
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp

.... and fix some problems found...

GCS_MAVLink: Add attributes to printf-like functions to get static analysis

---

ArduCopter/sensors.cpp

This PR reduces the chance of a single bad rangefinder reading triggering a Terrain Failsafe during auto missions by skipping sending of updates to AC_WPNav (if readings are bad) for up to 1 second.
This has already been successfully flown on a real vehicle but I will provide additional evidence from SITL in the coming days.
I somewhat wish that this solution was more integrated with the handling of glitches in more manual modes (Loiter, AltHold, PosHold) but in any case, it does use the same timeout and is an improvement over what we have in master.

Copter: avoid terrain failsafe from a single out-of-range rangefinder reading

---

ArduCopter/mode_auto.cpp

retract the landing gear automatically when takeoff finish.

Copter: mode_auto: retract the landing gear automatically

---

ArduCopter/mode.cpp
ArduCopter/mode_land.cpp

backport from https://github.com/ArduPilot/ardupilot/pull/8537 to copter 3.6
alternative at https://github.com/ArduPilot/ardupilot/pull/11528

Pr copter 3.6 yaw land from master

---

Tools/autotest/arducopter.py
libraries/SITL/SIM_Vicon.cpp

this is a more commonly used message

SITL: switch vicon simulation to use VISION_POSITION_ESTIMATE

---

ArduCopter/Attitude.cpp
ArduCopter/Copter.h
ArduCopter/Log.cpp
ArduCopter/mode.cpp
ArduCopter/mode_althold.cpp
ArduCopter/mode_circle.cpp
ArduCopter/mode_flowhold.cpp
ArduCopter/mode_loiter.cpp
ArduCopter/mode_poshold.cpp
ArduCopter/mode_sport.cpp
ArduCopter/mode_zigzag.cpp

Also, change the type passed in to be float.

Make surface tracking state a class, move functions to be methods on that class

---

AntennaTracker/AntennaTracker.cpp
AntennaTracker/Tracker.h

This makes things look just like Plane and Rover.

Tracker: tidy compass offset saving

---

AntennaTracker/AntennaTracker.cpp
AntennaTracker/GCS_Mavlink.cpp
AntennaTracker/Parameters.cpp
AntennaTracker/Parameters.h
AntennaTracker/Tracker.h
AntennaTracker/system.cpp
AntennaTracker/wscript
Tools/autotest/antennatracker.py
Tools/autotest/common.py

Primarily this is just to make the tests more reliable.  autotests pass for me after these patches.

Add AP_Stats to Tracker

---

libraries/GCS_MAVLink/GCS_Common.cpp
libraries/GCS_MAVLink/MissionItemProtocol.cpp
libraries/GCS_MAVLink/MissionItemProtocol.h
libraries/GCS_MAVLink/MissionItemProtocol_Rally.cpp
libraries/GCS_MAVLink/MissionItemProtocol_Rally.h
libraries/GCS_MAVLink/MissionItemProtocol_Waypoints.cpp
libraries/GCS_MAVLink/MissionItemProtocol_Waypoints.h

Also terminate uploads if any error occurs fetching items

GCS_MAVLink: allow complete() call on subclasses to fail

---

Tools/autotest/common.py

We may spend so much time parsing messages this deadline passes

Tools: autotest: increase timeout on mission_item_int

---

Tools/Vicon/vicon_mavlink.py
libraries/AP_GPS/AP_GPS_MAV.cpp

This adds support for a yaw field in GPS_INPUT which provides a way for external GPS sources to provide yaw information to EKF3
This PR depends on https://github.com/ArduPilot/mavlink/pull/105 and should wait on that PR being merged

Support YAW in GPS_INPUT for Vicon 

---

libraries/AP_HAL_ChibiOS/Scheduler.cpp

thanks to Tom for noticing this

HAL_ChibiOS: fixed reboot hold in bootloader

---

Tools/ardupilotwaf/chibios.py
libraries/AP_HAL_ChibiOS/CANClock.h
libraries/AP_HAL_ChibiOS/CANIface.h
libraries/AP_HAL_ChibiOS/Util.h
libraries/AP_UAVCAN/AP_UAVCAN_Servers.cpp
libraries/AP_UAVCAN/examples/UAVCAN_sniffer/UAVCAN_sniffer.cpp

.... and add `-Werror=suggested-overrides`

Add required UAVCAN override keywords

---

ArduPlane/GCS_Mavlink.cpp
ArduPlane/GCS_Mavlink.h

This is an NFC commit which just moves handling of DO_REPOSITION out into a function.
Merging this will simplify a PR which modifies this code.

Plane: factor out a handle_command_int_do_reposition

---

APMrover2/mode.h
APMrover2/mode_auto.cpp
libraries/AP_Mission/AP_Mission.cpp

This builds upon this existing PR: https://github.com/ArduPilot/ardupilot/pull/11999 but creates a new Auto submode called "Stop" which I think is more robust than trying to use the existing SpeedAndHeading submode which is meant for a very different purpose.

Rover: implement NAV_DELAY (attempt 2)

---

libraries/AP_Proximity/AP_Proximity_AirSimSITL.cpp
libraries/AP_Proximity/AP_Proximity_AirSimSITL.h
libraries/SITL/SIM_AirSim.cpp
libraries/SITL/SIM_AirSim.h
libraries/SITL/SIM_Scrimmage.cpp
libraries/SITL/SIM_Scrimmage.h

Just something which caught my eye, no functional changes

SITL: Add license info, remove extra include

---

libraries/AP_InertialSensor/AP_InertialSensor.cpp

Thanks to @peterbarker for noticing this

AP_InertialSensor: fixed watchdog on AHRS trim gyro wait

---

ArduSub/GCS_Sub.cpp

I've only tested this as far as making sure it compiles when terrain is enabled.

Sub: correct compilation when terrain is enabled

---

APMrover2/Parameters.cpp
APMrover2/afs_rover.cpp
APMrover2/afs_rover.h
APMrover2/failsafe.cpp

I have only tested compilation works after this, not that AFS does.

Rover: correct compilation when AFS enabled

---

ArduCopter/GCS_Mavlink.cpp
ArduCopter/config.h

I have only validated that this compiles.

Copter: Correct compilation when guided mode is disabled

---

libraries/AP_RangeFinder/AP_RangeFinder_BBB_PRU.cpp
libraries/AP_RangeFinder/AP_RangeFinder_Bebop.cpp
libraries/AP_RangeFinder/AP_RangeFinder_Benewake_TFMiniPlus.cpp
libraries/AP_RangeFinder/AP_RangeFinder_NMEA.cpp
libraries/AP_RangeFinder/AP_RangeFinder_VL53L0X.cpp
libraries/AP_RangeFinder/AP_RangeFinder_VL53L1X.cpp

I found code that was not in coding style.
I adapted to the coding style.

RangeFinder: Change to coding style (NFC)

---

libraries/AP_Mission/AP_Mission.cpp

This allows to run any commands following the last nav_waypoint
that may be required or change flight behavior for following wps

AP_Mission: Better AUTO watchdog restore

---

libraries/AP_Baro/AP_Baro.cpp

AP_Baro: Fix floating point exception with watchdog reset

---

Tools/scripts/apj_tool.py

py3 really is a major pain for simple string tools

Tools: fixed apj_tool for python3

---

ArduPlane/Plane.h
ArduPlane/radio.cpp
Tools/autotest/arduplane.py

this is a replacement for #12043
many thanks to @Jaaaky for finding this issue

Plane: fixed throttle failsafe for FS_SHORT_ACTN=3

---

libraries/AP_HAL_ChibiOS/stdio.cpp

This resolves the fact that ChibiOS builds were using an almost line for line duplication of the code we have in AP_HAL/Util.h. This lead to ChibiOS having a slightly different behaviour then other builds. We were actually using the code in the HAL as well, which means this shrinks the build a bit (236 bytes on CubeBlack)

AP_HAL_ChibiOS: Remove almost redundant code duplication from the HAL

---

Tools/autotest/arduplane.py

Currently this fails but should probably pass.
@Jaaaky - does this  new test look like your scenario?

Tools: autotest: add test for short failsafe triggering via low-throttle

---

libraries/AP_Notify/Display.cpp

We index into these arrays so ensuring their size is worthwhile

AP_Notify: add static asserts for array size

---

ArduPlane/servos.cpp

This updates the dspoiler auto trim to reflect https://github.com/ArduPilot/ardupilot/pull/10614

Plane: servos: update dspoiler auto trim

---

APMrover2/Parameters.cpp

causes wiki duplications ...already included elsewhere

Rover: remove duplicate parameter comments

---

libraries/AP_RangeFinder/AP_RangeFinder_Lanbao.cpp
libraries/AP_RangeFinder/AP_RangeFinder_Lanbao.h
libraries/AP_RangeFinder/RangeFinder.cpp
libraries/AP_RangeFinder/RangeFinder.h

AP_RangeFinder: added driver for Lanbao CM8JL65

---

APMrover2/config.h
ArduCopter/APM_Config.h
ArduCopter/config.h
ArduPlane/config.h
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp

This fixes a regression where we started to include this in fmuv2 builds.

Hide Devo behind !HAL_MINIMIZE_FEATURES

---

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py

throw an error on configure if there is a duplicate

HAL_ChibiOS: prevent duplicate sensors in hwdef.dat

---

libraries/AP_Compass/AP_Compass.cpp
libraries/AP_Compass/AP_Compass_BMM150.cpp
libraries/AP_Compass/AP_Compass_BMM150.h

this fixes skyviper-f412 build

AP_Compass: allow rotation of BMM150 compass

---

libraries/AP_RCProtocol/AP_RCProtocol_SUMD.cpp
libraries/AP_RCProtocol/examples/RCProtocolTest/RCProtocolTest.cpp

with 16 channels it is more than 3ms per frame

AP_RCProtocol: fixed SUMD with 16 channels

---

libraries/AP_Filesystem/AP_Filesystem_posix.cpp
libraries/AP_Filesystem/posix_compat.h

@tridge SITL build on macOS filas for me now without this

AP_Filesystem: build fixes for SITL on macOS

---

libraries/AP_LeakDetector/AP_LeakDetector.cpp

AP_LeakDetector: Mark leak detection pins with @RebootRequired

---

ArduPlane/quadplane.cpp

this probably is not coded correctly or variable not scaled correctly, but I thought I would give it a shot and maybe @tridge could fix it easily....
instead of a fixed -3 deg limit to pitch as the plane approaches landing which is based, and relieved, solely on distance from landing (which erroneously evokes it if a loiter is the preceding mode/waypoint, preventing movement in some cases to the landing), the pitch limiter max pitch can vary from -3deg, if the groundspeed is 3X or above the waypoint travel speed, to the max tilt if the speed is less than that speed....so if the vehicle is not making progress, it can use the full tilt
I do not know how to get this into the MP SITL model to test it since I dont have a SITL environment other than MP, so I cant test it....
hopefully, the …

Plane: fixed landing after VTOL loiters

---

libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp
libraries/GCS_MAVLink/GCS_MAVLink.cpp
libraries/GCS_MAVLink/GCS_MAVLink.h

available returns an unsigned integer, so this was just weird

GCS_MAVLink: remove comm_get_available

---

libraries/AP_Compass/AP_Compass_UAVCAN.cpp

This includes two key fixes needed for Copter-3.6

Copter 3.6 important fixes

---

ArduSub/Parameters.cpp

Sub: force cam pan and tilt inputs to channels 7 and 8

---

ArduSub/motors.cpp

Sub: Improve motor test message

---

APMrover2/GCS_Mavlink.cpp
APMrover2/GCS_Mavlink.h
AntennaTracker/GCS_Mavlink.cpp
ArduCopter/GCS_Mavlink.cpp
ArduCopter/GCS_Mavlink.h
ArduPlane/GCS_Mavlink.cpp
ArduPlane/GCS_Mavlink.h
ArduSub/GCS_Mavlink.cpp
Tools/Replay/Replay.cpp
Tools/autotest/arduplane.py
Tools/autotest/common.py
libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.cpp
libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.h
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp

@WickedShell expressed interest in this.
Added a few basic autotests tests for this.
Tested in SITL only.

Create and use AdvancedFailsafe singleton

---

.travis.yml
Tools/scripts/build_ci.sh

We can't keep breaking this accidentally.
Thanks to @EbinPhilip for fixing the recent regressions.

travis: run balancebot tests as part of CI

---

Tools/autotest/arducopter.py

This wasn't even close to right.

Tools: autotest: correct timeout on heli spline mission

---

libraries/APM_Control/AR_AttitudeControl.cpp

This adds descriptions for the new PID params for rover, old param descriptions remain for wiki

APM_Control: AR_AttitudeControl: add description for new PID params

---

libraries/AP_Motors/AP_Motors6DOF.cpp

Fix #9798 
Frame setup for reference:

APMotors6DOF: Add roll factor to SIMPLEROV4 and SIMPLEROV5

---

libraries/AP_Compass/AP_Compass_MMC3416.cpp
libraries/AP_Radio/AP_Radio_cypress.cpp

I change the direct value to the define name.

libraries: Change direct value to define name

---

.travis.yml
Tools/ardupilotwaf/boards.py
Tools/ardupilotwaf/gtest.py
Tools/scripts/build_ci.sh

This requires an update to the gtest module - there's a PR to make that our master here: https://github.com/ArduPilot/googletest/pull/1

Fix unit tests

---

Tools/autotest/common.py

postcondition of any test is that it leaves the vehicle disarmed

Tools: autotest: test for vehicle armed after test passes

---

Tools/autotest/autotest.py
Tools/autotest/common.py
Tools/autotest/pysim/util.py
Tools/autotest/sim_vehicle.py

lldb generally works much, much better than gdb on macOS

Tools: support lldb debugging for sim_vehicle and autotest

---

libraries/AP_Motors/AP_Motors6DOF.cpp

https://github.com/ArduPilot/ardupilot/pull/12331#issuecomment-534372020

AP_Motors_6DOF: Add missing 'break'

---

libraries/AP_Relay/AP_Relay.cpp
libraries/AP_Relay/AP_Relay.h

This was tested using both the existing autotest and by connecting a logic analyser to a PixRacer.

AP_Relay: tidy, reduce flash usage

---

ArduSub/system.cpp
libraries/AP_TemperatureSensor/TSYS01.cpp
libraries/AP_TemperatureSensor/TSYS01.h

AP_TemperatureSensor: Update TSYS01 for Pixhawk2

---

ArduSub/sensors.cpp

Sub: update calibration if reading is above water level

---

ArduSub/joystick.cpp

Sub: Issue 9801. Get Rid of Step Input on Engaging Input_Hold

---

ArduSub/ArduSub.cpp
ArduSub/Parameters.cpp
ArduSub/Sub.h
ArduSub/control_motordetect.cpp
ArduSub/defines.h
ArduSub/flight_mode.cpp
ArduSub/joystick.cpp
ArduSub/motors.cpp
ArduSub/sensors.cpp
ArduSub/system.cpp
libraries/AP_LeakDetector/AP_LeakDetector.cpp
libraries/AP_Motors/AP_Motors6DOF.cpp
libraries/AP_Motors/AP_Motors6DOF.h
libraries/AP_TemperatureSensor/TSYS01.cpp
libraries/AP_TemperatureSensor/TSYS01.h

https://github.com/ArduPilot/ardupilot/issues?q=is%3Aissue+milestone%3ASub-3.6.0+is%3Aclosed

Sub 3.6: backport of 3.6 changes in master

---

libraries/AP_AHRS/AP_AHRS.cpp

this fixes https://github.com/ArduPilot/ardupilot/issues/12000

AP_AHRS: fix custom rotation ToRad conversion

---

Tools/autotest/sim_vehicle.py

helps people debugging install

autotest: allow --moddebug to sim_vehicle.py

---

APMrover2/Parameters.cpp
APMrover2/Parameters.h
APMrover2/Rover.h
APMrover2/failsafe.cpp

This is a cut-down version of this existing PR: https://github.com/ArduPilot/ardupilot/pull/12313
This implements just the FS_OPTIONS portion and has been tested in SITL

Rover: FS_OPTIONS allows failsafe from hold mode

---

APMrover2/mode.h
APMrover2/mode_rtl.cpp
APMrover2/mode_smart_rtl.cpp

replacing other part of #12313....now that boat has loitering, change the RTL/SRTL end behavior to loitering within mode...no RTL options needed as I think this is the original goal before loiter was created...

Rover: change RTL/SRTL from circling to loitering for boats

---

Tools/AP_Periph/can.cpp
libraries/AP_HAL_ChibiOS/RCOutput.cpp

Fixed brightness and occasional color display errors

AP_Periph: fixed LED display errors in CUAV_GPS

---

libraries/AP_Vehicle/AP_Vehicle.cpp
libraries/AP_Vehicle/AP_Vehicle.h

Marked this as WIP as there is no current user of it in the ArduPilot codebase, but @yaapu wants access to it.

AP_Vehicle: add singleton

---

Tools/AP_Periph/Parameters.cpp
Tools/AP_Periph/Parameters.h
Tools/AP_Periph/can.cpp
libraries/AP_Compass/AP_Compass.cpp
libraries/AP_HAL_ChibiOS/hwdef/CUAV_GPS/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/f103-periph/hwdef.dat

and limit compass params when only one compass, to reduce CAN params

Added LED_BRIGHTNESS to AP_Periph

---

ArduCopter/APM_Config.h
ArduCopter/Copter.cpp
ArduCopter/Copter.h
ArduCopter/Log.cpp
ArduCopter/Parameters.cpp
ArduCopter/Parameters.h
ArduCopter/config.h
ArduCopter/defines.h
ArduCopter/mode.cpp
ArduCopter/mode.h
ArduCopter/mode_systemid.cpp
ArduCopter/tuning.cpp
libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
libraries/AC_AttitudeControl/AC_AttitudeControl.h
libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp
libraries/AP_Motors/AP_MotorsHeli.h
libraries/AP_Motors/AP_Motors_Class.h

This is a new mode that generates chirp waveforms and injects them into various parts of the aircrafts controllers. This may then be used to generate computational models of the aircraft. These models can then be used to do offline tuning.

System Identification Mode

---

ArduPlane/quadplane.cpp
ArduPlane/quadplane.h

Should we also reduce the RATE log freq?

Plane: reduce QTUN log rate to 25Hz

---

Tools/GIT_Test/GIT_Success.txt

I have added my name to GitTest, thanks!

Tools: update git success from Xiamen

---

libraries/AP_KDECAN/AP_KDECAN.cpp

Alternative to:
- https://github.com/ArduPilot/ardupilot/pull/12621
- https://github.com/ArduPilot/ardupilot/pull/12597

Copter: corrected undefined data member causing linking error

---

APMrover2/Log.cpp
AntennaTracker/Log.cpp
ArduCopter/Log.cpp
ArduPlane/Log.cpp
ArduSub/Log.cpp
Tools/Replay/Replay.cpp
libraries/AP_Logger/AP_Logger.h
libraries/AP_Logger/LogFile.cpp

@Jaaaky This is what I meant by my comment on #12594 
You'd use the singleton object to get the extra data to log.

Use ahrs singleton to log ATT, POS and AHRS2

---

libraries/AP_NMEA_Output/examples/NMEA_Output/nmea_output.cpp
libraries/AP_NMEA_Output/examples/NMEA_Output/wscript

This is tested as far as "working in Linux".
This includes the patch in #12644 as it doesn't work otherwise.

Add example for NMEA Output

---

libraries/SITL/SIM_Submarine.cpp

SITL: Add missing shove forces in SIM_Submarine

---

libraries/AP_Motors/AP_MotorsTri.cpp
libraries/AP_Motors/AP_MotorsTri.h

AP_Motors: switched tricopter to use rc_write_angle()

---

Tools/autotest/apmrover2.py
libraries/AP_Scripting/examples/scripting_test.lua
libraries/AP_Scripting/generator/description/bindings.desc
libraries/AP_Scripting/generator/src/main.c
libraries/AP_Scripting/lua_generated_bindings.cpp

This fixes a bug with the Location:offset() method, (also affected gcs:set_message_interval()). It introduces the methods for calculating offsets in NED and NE between locations, and starts us on a larger test suite for scripts.

AP_Scripting: Fix bug related to nil punning

---

libraries/AP_BLHeli/AP_BLHeli.cpp

AP_BLHeli: fixed critical errors caused by BLHeli code

---

APMrover2/Parameters.cpp
APMrover2/mode_loiter.cpp

This is https://github.com/ArduPilot/ardupilot/pull/12737 from @sahith22 , I atmepted to squash and broke his PR, sorry @sahith22, this is his PR from my backup

Rover: Added reversing loiter_type parameter

---

APMrover2/wscript
AntennaTracker/wscript
ArduCopter/wscript
ArduPlane/wscript
ArduSub/wscript
Tools/ardupilotwaf/ardupilotwaf.py
libraries/AC_PID/AC_PI.cpp
libraries/AC_PID/AC_PI.h
libraries/AP_BoardConfig/AP_BoardConfig.cpp
libraries/AP_BoardConfig/AP_BoardConfig.h
libraries/AP_BoardConfig/IMU_heater.cpp
libraries/AP_BoardConfig/board_drivers.cpp
libraries/AP_HAL_ChibiOS/Util.cpp
libraries/AP_HAL_ChibiOS/Util.h
libraries/AP_IOMCU/AP_IOMCU.cpp
libraries/AP_IOMCU/AP_IOMCU.h
libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp

This moves to using an AC_PI controller for heater, with user settable params and logging
ping @lthall

Added parameters and logging for IMU heater control

---

Tools/ardupilotwaf/ardupilotwaf.py
libraries/AP_HAL_SITL/RCOutput.cpp
libraries/AP_HAL_SITL/RCOutput.h
libraries/AP_Notify/SITL_SFML_LED.cpp
libraries/AP_Notify/SITL_SFML_LED.h
libraries/AP_Scripting/AP_Scripting.cpp
libraries/AP_Scripting/examples/LED_roll.lua
libraries/AP_Scripting/generator/description/bindings.desc
libraries/AP_Scripting/lua_generated_bindings.cpp
libraries/AP_Scripting/lua_generated_bindings.h
libraries/AP_SerialLED/AP_SerialLED.cpp
libraries/AP_SerialLED/AP_SerialLED.h
libraries/SITL/SITL.h
libraries/SRV_Channel/SRV_Channel.h

This includes an example that sets LEDs based on vehicle roll
This also adds support for displaying serial LEDs in SITL, which is great for developing nice LED scripts

Added support for controlling WS2812 LEDs from Lua scripts

---

Tools/ardupilotwaf/boards.py
libraries/AP_FlashStorage/examples/FlashTest/FlashTest.cpp
libraries/AP_HAL_Linux/SPIDevice.cpp
libraries/AP_HAL_Linux/Storage.cpp
libraries/AP_HAL_SITL/SITL_State.cpp
libraries/AP_KDECAN/examples/KDECAN_sniffer/KDECAN_sniffer.cpp
libraries/GCS_MAVLink/GCS_MAVLink.cpp
libraries/SITL/SIM_AirSim.cpp

The HAL-Linux change is the most contentious I think.

Correct format string warnings, make them fatal

---

APMrover2/Rover.h
ArduCopter/Copter.h
ArduPlane/Plane.h
ArduSub/Sub.h
Tools/autotest/arducopter.py
libraries/AP_Mount/AP_Mount.cpp
libraries/AP_Mount/AP_Mount.h
libraries/AP_Mount/AP_Mount_Alexmos.cpp
libraries/AP_Mount/AP_Mount_Backend.cpp
libraries/AP_Mount/AP_Mount_Backend.h
libraries/AP_Mount/AP_Mount_SToRM32.cpp
libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
libraries/AP_Mount/AP_Mount_Servo.cpp
libraries/AP_Mount/AP_Mount_SoloGimbal.cpp
libraries/GCS_MAVLink/GCS_Common.cpp

New tests added.
Tested by flashing onto my Solo and testing by hand.

Have Mount use AHRS singleton, use altitude frame

---

APMrover2/afs_rover.cpp
ArduCopter/Copter.h
ArduCopter/afs_copter.cpp
ArduCopter/ekf_check.cpp
ArduCopter/heli.cpp
ArduCopter/sensors.cpp
ArduCopter/surface_tracking.cpp
ArduCopter/system.cpp
ArduCopter/toy_mode.cpp
ArduCopter/toy_mode.h
ArduSub/Parameters.cpp
ArduSub/system.cpp
Tools/autotest/build-with-disabled-features.py

This includes the fixes that were in #12731 
There's a minor behavioural change in toy mode - where I squashed a mode reason into a pre-existing one.

Fix compilation issues for Helicopter and Sub

---

ArduSub/Sub.h

Sub: Remove unnecessary includes

---

Tools/completion/bash/_sim_vehicle
Tools/completion/bash/_waf
Tools/completion/completion.bash
Tools/completion/completion.zsh
Tools/completion/zsh/_sim_vehicle
Tools/completion/zsh/_waf

To use it, add in your .zshrc : 
source PATH_TO_ARDUPILOT/Tools/completion/completion.zsh 
And now you have basic TAB completion. Still uncomplete but most basic command are here.
I may add Bash support and the same for sim_vehicle.py

Tools: add initial cmdline completion

---

ArduCopter/defines.h
ArduCopter/system.cpp
ArduPlane/ArduPlane.cpp
ArduPlane/Plane.h
ArduPlane/system.cpp
libraries/AP_InertialSensor/AP_InertialSensor.h
libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
libraries/Filter/HarmonicNotchFilter.h

This allows plane to use the dynamic harmonic notch filter off RPM

Added dynamic harmonic notch for plane

---

libraries/SRV_Channel/SRV_Channel.h

SRV_Channel: remove old unused reversible-throttle concept

---

APMrover2/AP_MotorsUGV.cpp
AntennaTracker/system.cpp
ArduCopter/afs_copter.cpp
ArduPlane/afs_plane.cpp
ArduPlane/mode_fbwa.cpp
ArduPlane/radio.cpp
ArduPlane/servos.cpp
libraries/AC_Sprayer/AC_Sprayer.cpp
libraries/AP_LandingGear/AP_LandingGear.cpp
libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
libraries/AP_Motors/AP_MotorsHeli_Quad.cpp
libraries/AP_Motors/AP_MotorsHeli_Single.cpp
libraries/AP_Winch/AP_Winch_Servo.cpp
libraries/SRV_Channel/SRV_Channel.cpp
libraries/SRV_Channel/SRV_Channel.h
libraries/SRV_Channel/SRV_Channel_aux.cpp

Use enum-class in place of SRV_CHANNEL_LIMIT_ZERO_PWM and friends

---

libraries/AC_AttitudeControl/AC_PosControl.cpp

I believe what you guys actually want to do is just what I mean in this PR here.

AC_PosControl: fix minor bug for set_max_speed_z()

---

Tools/AP_Periph/Parameters.cpp
Tools/AP_Periph/Parameters.h
Tools/AP_Periph/adsb.cpp
libraries/AP_SerialManager/AP_SerialManager.cpp
libraries/AP_SerialManager/AP_SerialManager.h

to support new ADSB device:
http://aerobits.pl/component/virtuemart/tid-aero-detail?Itemid=0
which needs 115200

AP_Periph: Added ADSB_BAUDRATE option

---

libraries/AP_NMEA_Output/AP_NMEA_Output.cpp

AP_NMEA_Output: correct 10Hz rate limiting

---

Tools/environment_install/install-prereqs-ubuntu.sh

Running as root leaves all sorts of things with nasty permissions

Tools: install-prereqs-ubuntu: add not-run-as-root sanity check

---

APMrover2/Rover.h
AntennaTracker/Tracker.h
ArduCopter/Copter.h
ArduPlane/Plane.h
ArduSub/Sub.h
libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
libraries/AP_AHRS/AP_AHRS_NavEKF.h
libraries/AP_Vehicle/AP_Vehicle.h

People have asked me about moving this.
The flag to EKF instantiation was the stopper, but this seems OK-ish.

Instantiate ARHS object in AP_Vehicle base class rather than individual vehicles

---

ArduCopter/precision_landing.cpp

We go through here when we don't have our current location.

Copter: precland: don't use altitude from bad location

---

ArduSub/motors.cpp

Same as #12330, but that was against sub-3.6 (now sub-4.0)

Sub: rate-limit init_motor_test() calls

---

Tools/autotest/antennatracker.py

Try to avoid similar problem the manual test had.

autotest: diversify Tracker SERVOTEST mode test

---

libraries/SITL/examples/Airsim/follow-copter.sh

1. Kill all running Copter binaries while exiting
2. Set default GCS IP address
3. Fix mcast ip address for different platforms
4. Add variable for number of vehicles

SITL: Fixes, improvements to Airsim multi-vehicle script

---

libraries/AP_Logger/AP_Logger.h
libraries/AP_Logger/AP_Logger_MAVLinkLogTransfer.cpp

These weren't great symbols to create...

AP_Logger: use enum class for transfer activity

---

libraries/AP_Scripting/lua_scripts.cpp

If we can't do the initial bit of loading, we won't gain anything by restarting the VM repeatedly. Resolves problems such as setting a bad heap size in SITL. @rmackay9 this should fix the scenario you found.

AP_Scripting: Don't restart scripts if it panic'd during the initial VM creation

---

libraries/AP_GPS/AP_GPS_UAVCAN.cpp
libraries/AP_GPS/AP_GPS_UAVCAN.h

thanks to @VadimZ for the suggestion

AP_GPS: cope with UAVCAN GPS that don't provide Aux message

---

AntennaTracker/mode.cpp

I'm really confused by this.  This PR definitely seems to fix scan mode from being *totally* broken on my Tracker here.
How is scan mode working for anybody at the moment?
@IamPete1 is this generally working for you?  Am I missing something?

Tracker: correct scan mode pitch clamping

---

libraries/AP_Scripting/examples/plane-wind-failsafe.lua

This was written at CubePilot 2019 as part of a workshop.
Blame MdB

AP_Scripting: add example to warn and then RTL based on wind speed

---

libraries/AP_Mission/AP_Mission.cpp

AP_Mission: add string for DO_MOUNT_CONTROL

---

ArduSub/joystick.cpp
ArduSub/system.cpp

Backport #12907 and #12908 to Sub 4.0

Sub 4.0: Fix issue with blinking lights and uninitialized camera

---

libraries/AP_HAL_ChibiOS/SPIDevice.cpp
libraries/GCS_MAVLink/GCS_Common.cpp

prevent a critical error for ahrstrim

Fixed critical error on preflight cal

---

libraries/SITL/SIM_AirSim.cpp

Thanks to @tridge for pointing this out!

SITL: Fix sensor data calculation in Airsim

---

Tools/scripts/configure-ci.sh

Saves 8k on plane, 9.3k on copter

Tools: align ci gcc with environment gcc on arm

---

Tools/autotest/arducopter.py

ping @andyp1per and see #13072

autotest: disable MotorVibration test

---

ArduPlane/GCS_Mavlink.cpp
libraries/GCS_MAVLink/GCS_Common.cpp

Fixed HUD negative throttle

---

ArduPlane/Parameters.cpp

Plane:fix typo in ARSPD_FBW_MAX param description

---

libraries/AP_Logger/AP_Logger.h
libraries/AP_Logger/LogFile.cpp
libraries/AP_Logger/LogStructure.h
libraries/AP_UAVCAN/AP_UAVCAN.cpp
libraries/AP_UAVCAN/AP_UAVCAN.h

i didn't use the existing ESCn msgs as I wanted to use instance logging, plus there are some slightly different fields. We could unify them in the future

Added logging of CAN servo and ESC status

---

libraries/AP_Scripting/lua_boxed_numerics.cpp

Closes #13180 and replaces #13181.

AP_Scripting: Forward declare lua_new_uint32_t

---

ArduCopter/mode.h
ArduCopter/mode_circle.cpp
libraries/AC_WPNav/AC_Circle.cpp
libraries/AC_WPNav/AC_Circle.h

Backport from master to Copter 4

Copter: Circle mode pilot control of radius, rate, and direction

---

Tools/autotest/arduplane.py
Tools/autotest/common.py

Checks the output we get via FRSky for altitude is the same as that we get via mavlink

autotest: test FRSky serial output by taking output via TCP

---

libraries/GCS_MAVLink/MissionItemProtocol_Waypoints.cpp

GCS_MAVLink: fixed valgrind error in mission upload

---

BUILD.md

Include explanation of vehicles types.

Update BUILD.md for vehicle types

---

APMrover2/AP_Arming.cpp
APMrover2/AP_Arming.h
ArduCopter/AP_Arming.cpp
ArduPlane/AP_Arming.cpp
ArduSub/AP_Arming_Sub.cpp
Tools/autotest/common.py
libraries/AP_Arming/AP_Arming.cpp
libraries/AP_Arming/AP_Arming.h
libraries/AP_Logger/LogStructure.h

Log vehicle arm/disarm consistently across vehicles

---

Tools/autotest/common.py

Tools: correct math in frsky passthrough test

---

Tools/AP_Periph/AP_Periph.cpp
Tools/AP_Periph/can.cpp
libraries/AP_Baro/AP_Baro.cpp

AP_Periph: fixed baro calibration issue

---

libraries/AP_Avoidance/AP_Avoidance.cpp

our parser does not handle these embedded comments

AP_Avoidance: fixed generated param docs

---

libraries/AP_HAL_Linux/HAL_Linux_Class.cpp

AP_HAL_Linux: Add storage-directory argument in usage

---

Tools/scripts/configure_all.py
libraries/AP_HAL_ChibiOS/hwdef/KakuteF7Mini/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/MatekF405/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py

Fixed flash overflow and UART DMA configs

Fixed build for several boards

---

Tools/autotest/common.py

Only showed up when running under Valgrind, this was a simple race condition.

autotest: fix race condition in test for AFS on Plane

---

Tools/completion/bash/_ap_bin
Tools/completion/completion.bash
Tools/completion/completion.md
Tools/completion/zsh/_ap_bin

Add completion for vehicle binaries and small readme.
Tested on bash and zsh

Tools: completion

---

Tools/autotest/param_metadata/jsonemit.py
Tools/autotest/param_metadata/param_parse.py

Example output here:
https://jsonblob.com/4fc798b8-2137-11ea-95cc-9db3a505b5b0

Tools: Add JSON format in param_parse

---

APMrover2/GCS_Mavlink.cpp
APMrover2/Rover.h
APMrover2/system.cpp
AntennaTracker/GCS_Mavlink.cpp
AntennaTracker/Tracker.h
AntennaTracker/system.cpp
ArduCopter/Copter.h
ArduCopter/GCS_Mavlink.cpp
ArduCopter/system.cpp
ArduPlane/GCS_Mavlink.cpp
ArduPlane/Plane.h
ArduPlane/system.cpp
ArduSub/GCS_Mavlink.cpp
ArduSub/Sub.h
ArduSub/system.cpp
libraries/AP_Vehicle/AP_Vehicle.cpp
libraries/AP_Vehicle/AP_Vehicle.h

All of these functions have been identical over time.
I've wanted to do this one for years.

Move scheduler delay callback up to AP_Vehicle

---

libraries/AP_Logger/AP_Logger_Backend.h
libraries/AP_Logger/AP_Logger_Block.cpp
libraries/AP_Logger/AP_Logger_Block.h
libraries/AP_Logger/AP_Logger_File.cpp
libraries/AP_Logger/AP_Logger_File.h
libraries/AP_Logger/AP_Logger_MAVLink.h

Change the type of a method that does not use a return value

AP_Logger: Change the type of a method

---

libraries/AP_RangeFinder/AP_RangeFinder.cpp
libraries/AP_RangeFinder/AP_RangeFinder.h
libraries/AP_RangeFinder/AP_RangeFinder_BLPing.h
libraries/AP_RangeFinder/AP_RangeFinder_Backend_Serial.h
libraries/AP_RangeFinder/AP_RangeFinder_Lanbao.h
libraries/AP_RangeFinder/AP_RangeFinder_LeddarOne.cpp
libraries/AP_RangeFinder/AP_RangeFinder_LeddarOne.h
libraries/AP_RangeFinder/AP_RangeFinder_LeddarVu8.cpp
libraries/AP_RangeFinder/AP_RangeFinder_LeddarVu8.h
libraries/AP_RangeFinder/AP_RangeFinder_LightWareSerial.h
libraries/AP_RangeFinder/AP_RangeFinder_NMEA.h
libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp
libraries/AP_RangeFinder/AP_RangeFinder_Wasp.h

This adds a driver for the [LeddarTech Vu8](https://autonomoustuff.com/product/leddartech-vu8/) driver ([datasheet](https://autonomoustuff.com/wp-content/uploads/2019/10/as-leddar-vu8-20190618.pdf)).
This lidar is slightly unusual in that it provides eight distances which are taken at 2.5 degree increments in a plane giving a virtual beam width of 20degrees (other wider beam with versions are also available).  The hope is that this will work better in situations where the surface has some sharp edged bumps or depressions.  This driver will always take the shortest of the readings.
The lidar actually provides an I2C, Serial and CAN interface but I chose to implement just the serial interface.
Each sensor can be configured to use a different address using a configuration tool from the …

AP_RangeFinder: add LeddarTech Vu8 driver

---

libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32F745xx.py
libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32F767xx.py
libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32F777xx.py
libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32H743xx.py
libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py

This makes for slightly larger builds on F7 and H7, but gives us fast double precision maths. I think it is time we started testing that

HAL_ChibiOS: use cortex m7 instructions on F7/H7

---

libraries/AP_HAL_SITL/SITL_State.h
libraries/AP_HAL_SITL/UARTDriver.cpp
libraries/AP_HAL_SITL/sitl_gps.cpp
libraries/SITL/SITL.cpp
libraries/SITL/SITL.h

This makes testing of the code for moving baseline easier

SITL: Allow for separate position of 1st and 2nd SITL GPS

---

Tools/ardupilotwaf/chibios.py

fread is mentioned two time on the same line.

Tools: chibios.py remove duplicate fread from wraplist

---

libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp

https://github.com/ArduPilot/mavlink/pull/118 <- mavlink PR
https://github.com/ArduPilot/MAVProxy/pull/718 <- MAVProxy PR
`chunk_num` will become `seq`

Amalgamate statustexts using chunk number and id

---

libraries/AP_Logger/LogFile.cpp

Backport of https://github.com/ArduPilot/ardupilot/pull/12519 to Sub 4.0

Sub 4.0: AP_Logger: Fix logging of current on non primary instances

---

ArduSub/control_motordetect.cpp

As discussed with @jaxxzer, this relaxes the requirements for the motor direction detection mode.
Previously it required that the tested readings match fully the ones in the motor tables.
This patch relaxes that requirement. With the new implementation, if any of the 3 axis readings match and no axis reads a inverted response, the motor is assumed to be not inverted.
Tested:

Sub: relax direction detection logic in motor detect flight mode

---

libraries/AP_HAL_ChibiOS/Storage.cpp
libraries/AP_HAL_Linux/Storage.cpp
libraries/AP_HAL_SITL/Storage.cpp

Thanks to @Jaaaky for noticing this!

Fixed bitmask error on storage erase

---

ArduPlane/geofence.cpp
libraries/AC_Avoidance/AC_Avoid.cpp
libraries/AC_Avoidance/AC_Avoid.h
libraries/GCS_MAVLink/GCS_Fence.cpp

This uses a new mavlink extension to report when mitigation action is taken to prevent a fence breach, This is the requited ArduPilot mavlink PR https://github.com/ArduPilot/mavlink/pull/108, the extension is already in mavlink master.

AC_Avoid: Report fence mitigation

---

APMrover2/GCS_Mavlink.cpp

APMrover2: Remove post_ignore check since is always true

---

libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Solo.cpp
libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Solo.h

AP_Battmonitor_SMBus_Solo: removed unused code/options

---

libraries/AP_HAL_ChibiOS/RCOutput.cpp
libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_mcuconf.h

This improves the matching of pulse rates for DShot, NeoPixel and for blheli pass-thru
ping @IamPete1 
marked WIP. Even if this passes testing I would like to look at this some more before merging.

Fixed blheli passthru on H7 boards

---

AntennaTracker/GCS_Mavlink.cpp
AntennaTracker/system.cpp

Tracker: Remove links to AP_Camera

---

libraries/AP_Motors/AP_MotorsHeli_Quad.cpp

This PR fixes an issue reported in issue #11852.  The calculation for yaw is referenced to H_COL_MID instead of zero.  Users are instructed to set H_COL_MID to the pwm for zero collective pitch.  @tridge please look at this to see if I got the re-referencing correct.  Thanks!

AP_Motors: HeliQuad- reference zero collective pitch to H_COL_MID for yaw commands

---

Tools/autotest/apmrover2.py
Tools/autotest/arducopter.py
Tools/autotest/common.py

.... and remove some duplicate implementations.

Improve debug for distance-to-home

---

Tools/completion/bash/_waf
Tools/completion/zsh/_waf

Used waf list_boards instead of long sed command for the list of board options for shell tab completion of waf making it more robust.
Also I made all the changes as @khancyr requested and got rid of the merge commit (sorry for that).

Tools : Replaced long sed command with list_boards for shell completion.

---

libraries/SITL/SIM_Webots.cpp
libraries/SITL/SIM_Webots.h
libraries/SITL/examples/Webots/controllers/ardupilot_SITL_QUAD/ardupilot_SITL_QUAD.c
libraries/SITL/examples/Webots/controllers/ardupilot_SITL_QUAD/ardupilot_SITL_QUAD.h
libraries/SITL/examples/Webots/controllers/ardupilot_SITL_TRICOPTER/ardupilot_SITL_TRICOPTER.c

1- Adding argv to controller to limit max execution cyce time for simulation to slow it time and reduce CPU consumption which allows running multiple simulations on the same machine specs.
2- SIM_Webots.cpp is no longer disconnect when webots pause and resume. and no start up sequence is required anymore.

SITL Webots Enhancements

---

ArduPlane/Parameters.cpp
libraries/AP_Landing/AP_Landing_Deepstall.cpp

Needs someone who knows what the deepstall values truly do to correct the description and max/min values and whatnot.

Fix missing Plane docs

---

ArduCopter/Parameters.cpp
ArduSub/Parameters.cpp

This PR fixes #13546.
Please let me know if I missed something!
Thanks

Copter/Sub: Rename SYSID_SW_MREV to FORMAT_VERSION

---

libraries/AP_Filesystem/AP_Filesystem_FATFS.cpp
libraries/AP_Filesystem/AP_Filesystem_posix.cpp

This fixes file download using FTP from mavproxy. The bug caused file truncation and an incorrect error code

Filesystem: fixed issue with EOF on read

---

libraries/AP_Frsky_Telem/AP_Frsky_Telem.cpp
libraries/AP_Frsky_Telem/AP_Frsky_Telem.h

it also fixes https://github.com/ArduPilot/ardupilot/issues/8484

AP_Frsky_Telem: add semaphores to ahrs access

---

libraries/AP_RCProtocol/AP_RCProtocol_FPort.cpp

Respond only to 0x10 packets when the rx is controlling bandwidth, else respond only to 0x00 packets
but in this case never exceed a max number of consecutive frames.
Always respond to 0x10 polling and if necessary send a null frame.
Check delay after get_telem_data() to account for scheduler time
Apply to incoming packets same crc used for sending

fport: handle 0x10 frames, check scheduler delay and fix incoming packet's crc

---

Tools/ardupilotwaf/boards.py
Tools/ardupilotwaf/chibios.py

this fixes a link error on cygwin with the new DSP libs
@rmackay9 this should fix your build

waf: fixed build on cygwin

---

libraries/AP_Arming/AP_Arming.cpp

Fix for this issue https://github.com/ArduPilot/ardupilot/issues/13294

[PreArm] Warning text overflow fix

---

libraries/AP_Compass/Compass_learn.cpp

after recent changes only first compass was learnt
See
https://discuss.ardupilot.org/t/break-in-latest-master-in-flight-compass-calibration/52602

AP_Compass: fixed in-flight learning for all compasses

---

libraries/AP_SerialManager/AP_SerialManager.cpp

I would like to combine the descriptions of UARTF, UARTG, and UARTH with others.

AP_SerialManager: Add a description

---

Tools/GIT_Test/GIT_Success.txt

Adding name to list to test forking / PR workflow for ardupilot

Tools: Add nnaka to git test

---

Tools/GIT_Test/GIT_Success.txt

Adding myself (Gokul) onto the list :)

Tools: Added name(Gokul) to GIT_Success.txt   :)

---

Tools/autotest/arducopter.py

This separates out the test that is causing @peterbarker problems

autotest: separate out harmonic matching test

---

libraries/AP_UAVCAN/AP_UAVCAN.h
libraries/AP_UAVCAN/AP_UAVCAN_DNA_Server.cpp

Just a commit which has so far been missed in Rover backports.

Fix Linux build for Rover stable

---

libraries/AP_HAL/Scheduler.h
libraries/AP_HAL_ChibiOS/SPIDevice.cpp
libraries/AP_HAL_ChibiOS/Scheduler.cpp
libraries/AP_HAL_ChibiOS/Scheduler.h
libraries/AP_HAL_ChibiOS/Util.cpp
libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
libraries/AP_InertialSensor/AP_InertialSensor_Invensensev2.cpp
libraries/GCS_MAVLink/GCS_Common.cpp

This prevents non-mavlink noise on USB console while flashing the bootloader, improving speed and feedback to GCS users
ping @meee1

Improved debug messages when flashing bootloader

---

libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp
libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp

... once is enough to preserve current behaviour.

Stop requesting compass multiple times from the AHRS

---

libraries/AP_HAL_Linux/GPIO_RPI.h
libraries/AP_HAL_Linux/HAL_Linux_Class.cpp
libraries/AP_HAL_Linux/RCInput_RPI.cpp

Add compilation check for valid range

AP_HAL_Linux: Use template to generate raspberry pins

---

ArduPlane/failsafe.cpp
Tools/autotest/antennatracker.py
Tools/autotest/arduplane.py
Tools/autotest/common.py
Tools/autotest/quadplane.py

So the quadplane thing is "interesting".  Probably warrants closer investigation.

Add CPU Failsafe tests

---

Tools/GIT_Test/GIT_Success.txt

Starting to develop a code to use Arduino UNO as a sensor.

Tools: Gabsxk to GIT_Success.txt

---

ArduPlane/servos.cpp

fixed direction of flaperon automatic trim with SERVO_AUTO_TRIM
Thanks to Peter for finding this!

Plane: fixed flaperon auto-trim

---

Tools/autotest/param_metadata/param_parse.py
libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp
libraries/AP_RSSI/AP_RSSI.cpp
libraries/AP_WindVane/AP_WindVane.cpp

This PR fixes #13864 
The duplicate values thus found have also been rectified in this PR.

Tools: Validate that there are no duplicate values in @value fields

---

Tools/scripts/rcda_decode.py
libraries/AP_RCProtocol/AP_RCProtocol_Backend.cpp
libraries/AP_RCProtocol/AP_RCProtocol_Backend.h
libraries/AP_RCProtocol/AP_RCProtocol_DSM.cpp
libraries/AP_RCProtocol/AP_RCProtocol_FPort.cpp
libraries/AP_RCProtocol/AP_RCProtocol_IBUS.cpp
libraries/AP_RCProtocol/AP_RCProtocol_SBUS.cpp
libraries/AP_RCProtocol/AP_RCProtocol_SRXL.cpp
libraries/AP_RCProtocol/AP_RCProtocol_ST24.cpp
libraries/AP_RCProtocol/AP_RCProtocol_SUMD.cpp
libraries/RC_Channel/RC_Channel.h

This should aid in decoding protocol varients
ping @andyp1per 
Requires ```RC_OPTIONS=16```

Added logging of RC protocol bytes

---

ArduPlane/Log.cpp
libraries/AP_Logger/LogStructure.h

NFC updates to meta-data for wiki files
@peterbarker cant test appearance since I dont know how to locally generate the logmessage.html file
question: should logmesages.rst, htm,etc. be added to the .gitignore file in this repo also? had it originally, but took it out until I heard from you

Loggerfixes

---

ArduCopter/mode.cpp
ArduCopter/mode.h
ArduCopter/mode_zigzag.cpp

moving zigzag exit function from Copter::set_mode to ModeZigZag::exit()

Copter: move zigzag exit into mode_zigzag.cpp

---

Tools/GIT_Test/GIT_Success.txt

Tools/GIT_Test: Added a new dev name Tejprakash Sharma to GIT_SUCCESS.txt

Tools/GIT_Test: Added a dev name Tejprakash Sharma

---

Tools/autotest/arducopter.py
Tools/autotest/arduplane.py
Tools/autotest/ardusub.py
Tools/autotest/common.py

rework from https://github.com/ArduPilot/ardupilot/pull/10599
needed for #9254
add a generic wait function
Adjust some test to prevent to pass them directly :
for example we want to wait that speed is at zero but we only check that at a random time the speed is at 0 and not that it stay at 0. That way, doing rc 3 2000 and then rc 3 1000 on a rover will pass the wait speed 0 as we will pass from full speed to full backward speed and 0 is between the two.
Same for yaw testing, we just need to set rc 4 2000 and wait the test to pass since the vehicle is rotating it will always pass by the value we want !

Autotest wait2

---

ArduSub/GCS_Mavlink.cpp
ArduSub/Sub.h
ArduSub/joystick.cpp

Helps https://github.com/mavlink/qgroundcontrol/issues/8360

Sub: Announce roll pitch toggle, send it to GCS

---

ArduPlane/Log.cpp

This is in response to #13900.
@peterbarker I have filled these with the best of my knowledge. Please let me know if I have gotten anything wrong. I'll fix them with your suggestions.

Plane: added remaining logger documentation

---

libraries/AP_Arming/AP_Arming.cpp
libraries/AP_ToshibaCAN/AP_ToshibaCAN.cpp
libraries/GCS_MAVLink/GCS_Common.cpp
libraries/SRV_Channel/SRV_Channels.cpp

These aren't come across in practice because of the structure of our pragmas.
They are faults, however.

Compilation fixes from bugobliterator

---

libraries/AP_Hott_Telem/AP_Hott_Telem.cpp

See https://discuss.ardupilot.org/t/bug-in-ap-hott-telem-cpp-copter-4-0-4dev/53939/3
I have no idea if this is correct or not - I don't have the means to test it.
@lvale

Take GPS fix char from different place in GPS packet

---

.gitignore
Tools/autotest/param_metadata/param_parse.py

Output Error work on param error to help newcomers.
Exclude json parameter file from git
Solve https://github.com/ArduPilot/ardupilot/pull/13430

Param error small fix

---

Tools/autotest/autotest.py

`--list-subtests` gives:
```
pbarker@bluebottle:~/rc/ardupilot(pr/outbound-queue-length)$ ./Tools/autotest/autotest.py --list-subtests
Copter:
PIDTuning: Test PID Tuning
ArmFeatures: Arm features
SetHome: Test Set Home
ConfigErrorLoop: Test Config Error Loop
CPUFailsafe: Ensure we do something appropriate when the main loop stops
Parameters: Test Parameter Set/Get
LoggerDocumentation: Test Onboard Logging Generation
GetCapabilities: Get Capabilities
NavDelayTakeoffAbsTime: Fly Nav Delay (takeoff)
NavDelayAbsTime: Fly Nav Delay (AbsTime)
NavDelay: Fly Nav Delay
GuidedSubModeChange: Test submode change
LoiterToAlt: Loiter-To-Alt
PayLoadPlaceMission: Payload Place Mission
PrecisionLoiterCompanion: Precision Loiter (Companion)
PrecisionLandingSITL: Precision Landing (SITL) …
```

autotest: Add examples to --help and add --list-subtests

---

libraries/AP_Camera/AP_RunCam.cpp

AP_Camera: add RunCam device type 2 documentation

---

ArduCopter/mode_flowhold.cpp
ArduCopter/mode_throw.cpp
ArduCopter/toy_mode.cpp

With #13973, #13962 and this PR, the logger documentation for Copter should be complete.

Copter: Logger documentation for FHLD, FHXY, THRO, THST

---

libraries/AP_Logger/AP_Logger.cpp

#13158 
@peterbarker san, @khancyr san.
Thanks for your comment.
I only went with two.
1 Addition of white space in the for statement.
2 Addition of white space in if statement.

AP_Logger: Change to coding style (NFC)

---

ArduCopter/AP_Arming.cpp

I think it's better to format it with other messages.

Copter: Change messages

---

libraries/AP_BattMonitor/AP_BattMonitor_SMBus_SUI.cpp

fixed bug in total voltage
marked WIP as there seems to be another bug in the capacity reporting we haven't tracked down yet

AP_Battery: fixed bug in SUI driver

---

Tools/vagrant/mavinit.scr

reflected in wiki update: https://github.com/ArduPilot/ardupilot_wiki/pull/2630

fix typo...new wiki info reflects this change also

---

Tools/autotest/common.py
libraries/AC_AttitudeControl/ControlMonitor.cpp
libraries/AC_AutoTune/AC_AutoTune.cpp
libraries/AP_BoardConfig/IMU_heater.cpp
libraries/AP_Compass/AP_Compass_MMC3416.cpp
libraries/AP_EFI/AP_EFI.cpp
libraries/AP_Follow/AP_Follow.cpp
libraries/AP_IOMCU/AP_IOMCU.cpp
libraries/AP_Landing/AP_Landing_Slope.cpp
libraries/AP_Logger/LogStructure.h

... and some improved debug for bad fields

More // LoggerMessage documentation

---

Tools/autotest/apmrover2.py
Tools/autotest/common.py
Tools/autotest/pysim/util.py

@samuelctabor I had to change Rover's frame type for this test.  This is what we've been discussing for your soaring changes.
This is... pretty rough.  But serviceable, I think.

Add simple test for Rover skidsteer

---

libraries/AP_InertialSensor/AP_InertialSensor.cpp
libraries/AP_InertialSensor/AP_InertialSensor_ADIS1647x.cpp
libraries/AP_InertialSensor/AP_InertialSensor_ADIS1647x.h
libraries/AP_InertialSensor/AP_InertialSensor_Backend.h

This is a driver for the ADIS16470 IMU. This is a high quality IMU with low drift rate.
This PR includes changes to allow the pixracer to use SPI on the WiFi port. I will cleanup those changes before this gets merged

Added ADIS16470 IMU driver

---

libraries/AP_HAL_ChibiOS/Storage.cpp

I found a mistake in the calculation of the timeout detection time.
I have changed the calculation of the timeout detection time.

AP_HAL_ChibiOS: Changing the timeout detection

---

libraries/AP_HAL_ChibiOS/hwdef/F35Lightning/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/KakuteF4/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/MatekF405/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/OmnibusNanoV6/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/SuccexF4/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/airbotf4/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/mini-pix/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/omnibusf4v6/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/revo-mini/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/speedybeef4/hwdef.dat

ready for when #14062 is merged

AP_HAL_ChibiOS: eliminate EKF2 from F4 bds not using HAL_MINIMIZE_FEATURES

---

libraries/AP_Logger/LogStructure.h
libraries/AP_Mount/SoloGimbal.cpp

Move Solo Gimbal messages from TimeMS timestamp to TimeUS timestamp

---

ArduPlane/Plane.h
ArduPlane/quadplane.cpp
ArduPlane/servos.cpp
ArduPlane/system.cpp

we forced landing gear retract/deploy on takeoff and landing when we
should be following the options bits
thanks to Arace for pointing this out

Plane: fixed plane landing gear to obey LGR_OPTIONS bits

---

libraries/GCS_MAVLink/GCS.h

Splitting this out to simplify other PR (https://github.com/ArduPilot/ardupilot/pull/14088)

GCS_MAVLink: document the payload-space macros

---

libraries/AP_Logger/LogStructure.h
libraries/GCS_MAVLink/GCS.cpp
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp

Log number of times have-payload-space on GCS_MAVLink returns false

---

ArduCopter/mode.h
ArduCopter/mode_autorotate.cpp
libraries/AP_Baro/examples/ICM20789/ICM20789.cpp

noticed while working on another PR

Fixed copter autorotate build warnings

---

Tools/autotest/common.py

autotest: correct some parsing-out-of-logging-message

---

Rover/Log.cpp
Rover/cruise_learn.cpp

I guess this completes logger documentation for Rover.
This also needs https://github.com/ArduPilot/ardupilot/pull/14163 to be merged.
Please let me know any changes needed in the wording or any mistakes that I have made. Thanks!

Rover: Logger documentation

---

ArduSub/Log.cpp

This was the only left documentation for sub. Copied them from Copter since they are the same.
With this PR I believe all the vehicle specific documentation is over.

Sub: Logger Documentation

---

libraries/AP_HAL_ChibiOS/GPIO.cpp

found by building with --enable-asserts

HAL_ChibiOS: fixed assert in wait_pin()

---

libraries/AP_Logger/LogStructure.h
libraries/AP_Mount/SoloGimbal.cpp

Makes both the Solo and CubeBlack builds slightly smaller.

Use logger->Write for Solo gimbal logging

---

Tools/autotest/autotest.py
Tools/autotest/pysim/util.py
Tools/autotest/sim_vehicle.py

```
SIM_VEHICLE: Configure waf
SIM_VEHICLE: "/home/pbarker/rc/ardupilot/modules/waf/waf-light" "configure" "--board" "sitl" "--enable-math-check-indexes"
```

Tools: sim_vehicle.py: add --enable-math-check-indexes

---

libraries/AP_HAL_Linux/GPIO_RPI.cpp
libraries/AP_HAL_Linux/GPIO_RPI.h
libraries/AP_HAL_Linux/RCInput_RPI.cpp

- Move macros to functions and improve explanation about logic behind it
- Break code in functions to make it more readable
- Add doxygen comments about functions and how they work in a comprehensive manner
- Improve general code maintainability

AP_HAL_Linux: Organize and document GPIO_RPI class

---

.dockerignore
Dockerfile
Tools/completion/bash/_sim_vehicle
Tools/completion/zsh/_sim_vehicle
Tools/environment_install/install-prereqs-ubuntu.sh
Tools/scripts/configure-ci.sh
Tools/vagrant/shellinit.sh

Remove some useless package on ubuntu install that are leftover from Nuttx
Simplify a lot the docker and make it use docker feature for install instead of our install script. Allow docker to build STM based firmware.
You can test docker with : 
`docker build . -t ardupilot`
and then 
````
docker run --rm -it -v `pwd`:/ardupilot ardupilot:latest bash
````

Docker and ubuntu install update

---

Tools/autotest/rover.py

Notionally the statustext could be put aside and we could not have room
for it, so we see the ack first.

autotest: fix rare, random failure in GCSRally test

---

libraries/AP_Filesystem/AP_Filesystem_ROMFS.cpp

Closes #14267
... also, don't seek to an absolute negative offset, you won't like it.

AP_Filesystem: correct comparison of signed/unsigned

---

libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp

when using external yaw we shouldn't use the GSF

AP_NavEKF3: fixed external yaw EK3_MAG_CAL=5 or 6

---

Tools/autotest/rover.py

Accept statustext/ack in any order; statustext may come after ack
Also added some timeouts.
This code needs factoring.

autotest: accept statustext and ack in any order for mission errors

---

ArduPlane/GCS_Mavlink.cpp
ArduPlane/GCS_Mavlink.h
ArduPlane/Plane.h

These are in the correct file but the wrong namespace.

Move plane gcs mavlink send functions

---

libraries/AP_Soaring/Variometer.cpp

I'm quite sure these could do with some improvement.  Still, better than what we currently have.

AP_Soaring: add documentation for VAR dataflash log message

---

libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_FTP.cpp

GCS_MAVLink: give banner on param download with ftp

---

ArduCopter/AP_Arming.cpp

Thank @rmackay9 for [suggestions](https://github.com/ArduPilot/ardupilot/pull/14049#issuecomment-613204621)
This replace #14049, fix #14048

Copter: fix mode and fence gps check fail message

---

libraries/AP_Logger/AP_Logger_File.cpp

If anything in start_new_log did logging (for example, by sending a
statustext), we end up infinitely recursing.
With the patch:
```
--- a/libraries/AP_Logger/AP_Logger_File.cpp
+++ b/libraries/AP_Logger/AP_Logger_File.cpp
@@ -778,6 +778,7 @@ void AP_Logger_File::PrepForArming()
*/
void AP_Logger_File::start_new_log(void)
{
+    gcs().send_text(MAV_SEVERITY_WARNING, "Starting new log");
stop_logging();
start_new_log_reset_variables();
```
We see:
```
at ../../libraries/AP_Logger/AP_Logger_File.cpp:781
this=0x555555ad9d30, pBuffer=0x7fffff8209d0, size=75, is_critical=true)
at ../../libraries/AP_Logger/AP_Logger_Backend.cpp:372
this=0x555555ad9d30, pBuffer=0x7fffff8209d0, size=75)
at ../../libraries/AP_Logger/AP_Logger_Backend.h:32
this=0x555555ad9d30, message=0x7fffff820b10 "Starting new …
```

AP_Logger: prevent potential infinite recursion in log-open codepath

---

libraries/AP_Scripting/examples/mission-edit-demo.lua

lua demo script to match the recently merged mission-editing functionality.

AP_Scripting: add big demo script for editing and updating mission items

---

libraries/GCS_MAVLink/GCS_FTP.cpp

this fixes a bug in burst replies where the duplicate reply may have
the wrong offset. This causes the "paramftp bad type" error

GCS_MAVLink: fixed a ftp duplicate reply

---

libraries/SITL/SIM_Aircraft.cpp

similar to https://github.com/ArduPilot/ardupilot/commit/366361f0bb1e9b11af721c683bcb92d5c745072f
problem introduced by https://github.com/ArduPilot/ardupilot/commit/db1c7d9bdd0f75bfe66c155219ccc2132346a10a

SITL: fixed running of example programs

---

Tools/autotest/autotest.py
Tools/autotest/pysim/util.py
libraries/AP_HAL_SITL/Scheduler.cpp
libraries/AP_Math/matrix_alg.cpp

Depends on https://github.com/ArduPilot/ardupilot/pull/14362

Fixes autotest runs on mac osx

---

Tools/environment_install/install-prereqs-windows.ps1

This adds xtrem, allowing the sitl 'window thingy' to show once you have set your display variable

Tools: environment_install: add xterm to Cygwin packages

---

Tools/autotest/sim_vehicle.py

This is a follow up to: https://github.com/ArduPilot/ardupilot/pull/13405
This allows the terrain, motion_model, and visual_model SCRIMMAGE parameters to be set via command line options passed to sim_vehicle.py. --scrimmage-args was added, which takes a comma-separated list of argument-value pairs optionally prepended with an instance ID.

Tools: Expose some options to SCRIMMAGE

---

libraries/AP_HAL_ChibiOS/CANFDIface.cpp

Please refer https://github.com/ArduPilot/ardupilot/pull/14402 for details and discussion.

Use FIFO mode instead of Queue mode in FDCAN driver

---

Tools/autotest/common.py

Closes https://github.com/ArduPilot/ardupilot/issues/14431

autotest: round frsky altitude rather than truncate

---

libraries/AP_BLHeli/AP_BLHeli.cpp
libraries/AP_BLHeli/AP_BLHeli.h

AP_BLHeli: allow for negative temperatures from BLHeli32 ESCs

---

.dockerignore
Tools/environment_install/install-prereqs-ubuntu.sh

fix the issue mentionned in https://github.com/ArduPilot/ardupilot/pull/13907

Fix for ubuntu install script

---

Tools/AP_Periph/hwing_esc.cpp
libraries/AP_BLHeli/AP_BLHeli.cpp
libraries/AP_Camera/AP_RunCam.cpp
libraries/AP_EFI/AP_EFI_Serial_MS.cpp
libraries/AP_HAL/Util.cpp
libraries/AP_HAL/utility/BetterStream.h
libraries/AP_HAL_ChibiOS/UARTDriver.cpp
libraries/AP_HAL_ChibiOS/UARTDriver.h
libraries/AP_HAL_Empty/UARTDriver.cpp
libraries/AP_HAL_Empty/UARTDriver.h
libraries/AP_HAL_Linux/UARTDriver.cpp
libraries/AP_HAL_Linux/UARTDriver.h
libraries/AP_HAL_SITL/UARTDriver.cpp
libraries/AP_HAL_SITL/UARTDriver.h
libraries/AP_Hott_Telem/AP_Hott_Telem.cpp
libraries/AP_IOMCU/AP_IOMCU.cpp
libraries/AP_RangeFinder/AP_RangeFinder_LeddarOne.cpp
libraries/AP_UAVCAN/examples/UAVCAN_sniffer/UAVCAN_sniffer.cpp

Want to test this on a little more hardware first (io firmware in particular)

Add discard method to UARTDriver

---

libraries/AP_NavEKF2/AP_NavEKF2_MagFusion.cpp
libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp

The current wording can be taken to indicate that the mag sensors
stopped, causing this issue.

Clarify EKF reset diagnostic messages

---

Tools/GIT_Test/GIT_Success.txt
libraries/AP_Logger/LogStructure.h

This PR adds my name to the GIT_Success.txt file.

Tools: Added name to GIT_Success.txt + fix units in logger

---

libraries/AP_GPS/AP_GPS.cpp

when you have a moving baseline pair of ublox GPS modules and the
rover GPS does not have full fixed RTK lock on the base GPS then we
should not use it as our primary GPS as it's position and velocity can
be badly affected by the attempts of the GPS to gain a fixed lock.
This was observed in a flight with two F9P GPS, where the GPS velocity
data from the rover GPS went way off when it lost full RTK lock. It's
status stayed at 4, so it was selected as the primary GPS

AP_GPS: fixed issue with GPS selection for moving baseline

---

Tools/autotest/rover.py

For reproducing https://github.com/ArduPilot/ardupilot/issues/14469
`./Tools/autotest/autotest.py --no-clean --gdb build.Rover test.Rover.DriveMaxRCIN`

Tools: autotest: Add Max RC input test for Rover

---

libraries/AP_AHRS/AP_AHRS.h
libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
libraries/AP_AHRS/AP_AHRS_NavEKF.h
libraries/AP_Logger/AP_Logger.h
libraries/AP_Logger/LogFile.cpp
libraries/AP_Logger/LogStructure.h
libraries/AP_Math/AP_Math.cpp
libraries/AP_Math/AP_Math.h
libraries/AP_NavEKF2/AP_NavEKF2.cpp
libraries/AP_NavEKF2/AP_NavEKF2.h
libraries/AP_NavEKF2/AP_NavEKF2_Control.cpp
libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp
libraries/AP_NavEKF2/AP_NavEKF2_PosVelFusion.cpp
libraries/AP_NavEKF2/AP_NavEKF2_core.cpp
libraries/AP_NavEKF2/AP_NavEKF2_core.h
libraries/AP_VisualOdom/AP_VisualOdom.cpp
libraries/AP_VisualOdom/AP_VisualOdom.h
libraries/AP_VisualOdom/AP_VisualOdom_Backend.h
libraries/AP_VisualOdom/AP_VisualOdom_IntelT265.cpp
libraries/AP_VisualOdom/AP_VisualOdom_IntelT265.h
libraries/AP_VisualOdom/AP_VisualOdom_MAV.cpp
libraries/AP_VisualOdom/AP_VisualOdom_MAV.h
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp

replace #9505
Thanks @rmackay9 for great [suggestions](https://discuss.ardupilot.org/t/gsoc-2020-enhancements-of-non-gps-navigation-and-object-avoidance-with-realsense-cameras/55984/11?u=chobitsfan)
flight log
[visodom_visspeed.zip](https://github.com/ArduPilot/ardupilot/files/4625936/visodom_visspeed.zip)

AP_VisualOdom: support VISION_SPEED_ESTIMATE

---

libraries/AP_Soaring/AP_Soaring.cpp

Thanks to a user Maarten for reporting this.

AP_Soaring: Update parameter ranges.

---

libraries/AP_HAL_ChibiOS/UARTDriver.cpp
libraries/AP_HAL_Linux/UARTDriver.cpp
libraries/AP_HAL_SITL/UARTDriver.cpp

AP_HAL_ChibiOS: correct clearing of UART drivers

---

ArduCopter/mode_flowhold.cpp
libraries/AP_AHRS/AP_AHRS.cpp
libraries/AP_AHRS/AP_AHRS.h
libraries/AP_AHRS/AP_AHRS_View.cpp
libraries/AP_AHRS/AP_AHRS_View.h
libraries/AP_Math/vector3.h
libraries/AP_Scripting/generator/description/bindings.desc
libraries/AP_Scripting/lua_bindings.cpp

useful for heavier navigation in Lua

Add some more maths and AHRS ops in Lua

---

Tools/environment_install/install-prereqs-ubuntu.sh
Tools/vagrant/initvagrant.sh

Testings on LTS : 
Vagrant : 
Docker :

Tools: fix errors in ubuntu install script and improvement

---

ArduPlane/Plane.h

should be a none functional change just tidying up plane.h

Plane: label and sort plane.h functions

---

ArduPlane/ArduPlane.cpp
Tools/autotest/arducopter.py
libraries/SITL/SIM_Frame.cpp

And add pressure altitude compensation to simulated VTOL motors

Added pressure alt compensation to quadplane vtol code

---

Tools/mavproxy_modules/sitl_calibration.py

Lot of recent PR's travis check broke due to this issue.

Fix sitl_calibration stopping at calibration report

---

ArduPlane/system.cpp
libraries/AP_RSSI/AP_RSSI.cpp
libraries/AP_RSSI/AP_RSSI.h
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp

Closes https://github.com/ArduPilot/ardupilot/issues/14512

Add RADIO_STATUS.rssi as an AP_RSSI telemetry source

---

libraries/AC_Fence/AC_Fence.cpp
libraries/RC_Channel/RC_Channel.cpp

The fence can be enabled and disabled in lots of ways, so we shouldn't just log in one place.

Have AC_Fence log fence enabled and disabled

---

ArduCopter/RC_Channel.cpp
ArduCopter/RC_Channel.h
ArduPlane/RC_Channel.cpp
ArduPlane/RC_Channel.h
Rover/RC_Channel.cpp
Rover/RC_Channel.h
libraries/AP_Arming/AP_Arming.cpp
libraries/AP_Camera/AP_RunCam.cpp
libraries/RC_Channel/RC_Channel.cpp
libraries/RC_Channel/RC_Channel.h

Replaces https://github.com/ArduPilot/ardupilot/pull/14500 which I closed accidentally...
There was agreement at the devcall to merge this if it passes CI.

Rename 'enum aux_switch_pos_t' to 'enum class AuxSwitchPos

---

Tools/autotest/rover.py

autotest: increase timeout on receiving mission count

---

libraries/AP_HAL_ChibiOS/Scheduler.h

HAL_ChibiOS: increase monitor thread stack to 768 bytes

---

Tools/AP_Bootloader/board_types.txt

Update URL for ArduPilot board_types.txt

Tools:Bootloader Update URL in board_types.txt

---

libraries/AP_GPS/AP_GPS.h
libraries/RC_Channel/RC_Channel.cpp
libraries/RC_Channel/RC_Channel.h

This is very useful when testing impact of loss of GPS yaw in flight

Added RC option to force disable GPS yaw

---

ArduCopter/Copter.cpp
ArduCopter/Copter.h
libraries/AP_Scripting/examples/set-angle.lua
libraries/AP_Scripting/generator/description/bindings.desc
libraries/AP_Vehicle/AP_Vehicle.h

This adds access to guided mode set angle for scripting

AP_Scripting: add set angle for copter guided

---

Tools/GIT_Test/GIT_Success.txt

GIT_Success.txt modified with my name on it.
Ready to get my hands dirty
Hello everyone!

Tools: Added my name to GIT_Success.txt

---

libraries/AP_Scripting/AP_Scripting.cpp
libraries/AP_Scripting/lua_scripts.cpp
libraries/AP_Scripting/lua_scripts.h

This is in response to #13862
I am not sure if this is the approach that is needed, but it works well. It will be helpful for anyone trying the scripting feature for the first time. Please let me know if this can be accomplished in a better way.

AP_Scripting: Create scripts folder automatically if scripting is enabled 

---

libraries/AP_Scripting/AP_Scripting.cpp

As per the discussion in https://github.com/ArduPilot/ardupilot/pull/14123#issuecomment-646983985
Tested in SITL
@peterbarker @rmackay9

AP_Scripting: Remove send_text if directory is created

---

libraries/AC_AttitudeControl/AC_PosControl.cpp

AC_PosControl: correct VELXY_D_FILT Description

---

Tools/autotest/rover.py

This appears to now be working

autotest: re-enable Rover BendyRuler test

---

libraries/AP_Scripting/generator/src/main.c

Also fixes allowing an extra new line on the depends entries to be emitted, as well as a possible stack overflow in the generator if you inserted a malicious comment.
This should fix #14669. I tested locally by running `unix2dos` on the description file, but I don't have a cygwin setup to test this with. @WillyZehnder can you confirm this fixes the problem for you?

AP_Scripting: Allow generator to cope with windows line endings

---

Tools/autotest/arducopter.py

The bug being exposed is causing too much noise in CI.

autotest: disable Spline waypoint test

---

Tools/autotest/common.py

Also, wait_heartbeat ignores heartbeats from e.g. MAVProxy

autotest: wait for heartbeat when opening connection

---

Tools/Linux_HAL_Essentials/pru/aiopru/RcAioPRU.p

Please receive below two small corrections on the PRU assembler comments.

BeagleBone : comments corrected in RcAioPRU.p

---

libraries/AP_HAL_ChibiOS/hwdef/KakuteF7/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/KakuteF7Mini/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/OMNIBUSF7V2/hwdef.dat

we now have enough space with recent changes for these boards

HAL_ChibiOS: re-enable full features on KakuteF7 and OMNIBUSF7V2

---

Tools/autotest/common.py

This add testing for all serial_protocol 4 frsky packet types.
EDIT: added protocol 10

Tools: autotest added frsky serial_protocol 4 testing against mavlink

---

Tools/autotest/arducopter.py

set_rc will swallow this statustext message.  Make sure we take a copy before it is digested.

autotest: fix race condition between switch message and rc output

---

Tools/autotest/arducopter.py
libraries/AP_HAL_SITL/SITL_State.cpp
libraries/AP_HAL_SITL/SITL_State.h
libraries/AP_RangeFinder/AP_RangeFinder.cpp
libraries/AP_RangeFinder/AP_RangeFinder.h
libraries/AP_RangeFinder/AP_RangeFinder_GYUS42v2.cpp
libraries/AP_RangeFinder/AP_RangeFinder_GYUS42v2.h
libraries/SITL/SIM_RF_GYUS42v2.cpp
libraries/SITL/SIM_RF_GYUS42v2.h

AP_RangeFinder: add serial support for GY-US42v2 rangefinder

---

Tools/autotest/arducopter.py

autotest: SuperSimpleCircle: increase throttle while rolling in stab

---

libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp

GY-US42v2 was added to the list.
But there is no GYUS42v2 in TYPE item.
I add 31: GYUS42v2 to the TYPE item.

AP_RangeFinder: Add GYUS42v2 to the TYPE item

---

libraries/AP_Math/tests/test_vector2.cpp
libraries/AP_Math/vector2.cpp
libraries/AP_Math/vector2.h
libraries/AP_Scripting/generator/description/bindings.desc

AP_Math: added rotate method to Vector2f

---

libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp

CRSF debug was accidentally left on - disable it.

Disable CRSF debug

---

libraries/AP_AHRS/AP_AHRS_NavEKF.cpp

we need to keep origin and home separate for AHRS_EKF_TYPE=10. This
caused issues with resets in RealFlight leading to the plane not
descending

AP_AHRS: fixed SITL origin handling

---

Tools/autotest/sim_vehicle.py
Tools/completion/bash/_sim_vehicle
Tools/completion/zsh/_sim_vehicle

Fix and simplify frame completion that was broken since Rover target change on sim_vehicle.
Add some function to sim_vehicle to retrieve the list of vehicle and the associated frames.

Completion fixs

---

libraries/AP_Mission/AP_Mission.h

Some of the code comments were clearly C&P errors.  This fixes that.  I haven't corrected typos etc, to preserve history.

AP_Mission: NFC Correct some comments

---

Tools/autotest/arducopter.py

@rmackay9 @peterbarker apologies I can't do negative math

autotest: db's are negative so check dynamic notches the right way

---

libraries/AP_HAL/utility/RingBuffer.h
libraries/AP_HAL_ChibiOS/CANSerialRouter.cpp
libraries/AP_UAVCAN/AP_UAVCAN_SLCAN.cpp
libraries/SITL/SIM_Helicopter.cpp

... and fix some places where we weren't checking.

Add WARN_IF_UNUSED to RingBuffer methods

---

ArduCopter/crash_check.cpp

This PR makes the crash check more strict to protect against unhelpful disarms in the air.  The new additional requirements are:
- vehicle must be leaning at **more** than 15deg
- vehicle must be travelling at **less** than 10m/s
This is in response to two reports in the Copter-4.0 testing category where vehicles disarmed because it had very bad tunes.  The underlying AutoTune issue causing the bad tunes is fixed in this PR: https://github.com/ArduPilot/ardupilot/pull/13423 but we think that the crash check should not trigger if the vehicle is mostly upright.
This change still needs testing in SITL at least.  This is probably also a sensitive enough change that it shouldn't be rushed out into a stable release.

Copter: crash check requires vehicle to lean at more than 15deg

---

libraries/AP_Frsky_Telem/AP_Frsky_Telem.cpp
libraries/AP_Frsky_Telem/AP_Frsky_Telem.h

Correct FrSky parameter pass-through scheduling

---

Tools/scripts/decode_devid.py
libraries/AP_Baro/AP_Baro.cpp
libraries/AP_Baro/AP_Baro.h
libraries/AP_Baro/AP_Baro_BMP085.cpp
libraries/AP_Baro/AP_Baro_BMP280.cpp
libraries/AP_Baro/AP_Baro_BMP388.cpp
libraries/AP_Baro/AP_Baro_Backend.h
libraries/AP_Baro/AP_Baro_DPS280.cpp
libraries/AP_Baro/AP_Baro_FBM320.cpp
libraries/AP_Baro/AP_Baro_ICM20789.cpp
libraries/AP_Baro/AP_Baro_KellerLD.cpp
libraries/AP_Baro/AP_Baro_LPS2XH.cpp
libraries/AP_Baro/AP_Baro_MS5611.cpp
libraries/AP_Baro/AP_Baro_SITL.cpp
libraries/AP_Baro/AP_Baro_SPL06.cpp
libraries/AP_Baro/AP_Baro_UAVCAN.cpp
libraries/AP_Baro/AP_Baro_UAVCAN.h

This allows us to tell what barometers were present in a log

Added parameters for barometer device IDs

---

Tools/autotest/common.py

Built on top of #14863 
More diagnostics for if this fails again.

Add some more debug to frsky autotest

---

libraries/AC_Autorotation/AC_Autorotation.cpp

@Gone4Dirt does this look correct?

AC_Autorotation: add documentation for AROT message

---

libraries/AP_OSD/AP_OSD_Backend.h
libraries/AP_OSD/AP_OSD_MAX7456.cpp
libraries/AP_OSD/AP_OSD_MAX7456.h
libraries/AP_OSD/AP_OSD_Screen.cpp

Based on https://github.com/ArduPilot/ardupilot/issues/14853 from @FasaArg
I do not have a setup to test this. Happy to do test builds for others.

AP_OSD: apply aspect ratio correction to horizon

---

Tools/autotest/common.py
Tools/mavproxy_modules/sitl_calibration.py

... also fix bugs in automatic sitl calibration library

autotest: improve compass test diagnostics

---

libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.h

Fixes https://github.com/ArduPilot/ardupilot/issues/14905
See following innovations from test with COMPASS_SCALE = 0 flown in SITLshowing alignment of mag field and expected innovation sequence:

AP_NavEKF3: Fix bug preventing setting of mag field states

---

libraries/AP_Scripting/applets/README.md
libraries/AP_Scripting/applets/SmartAudio.lua
libraries/AP_Scripting/applets/SmartAudio.md

Initial applet....depends on Pete's RC option script switch PR being merged

AP_Scripting: Setup of applets directory and first applet entry

---

libraries/AP_NavEKF3/AP_NavEKF3.cpp
libraries/AP_NavEKF3/AP_NavEKF3.h

AP_NavEKF3: fix comments

---

ArduCopter/Attitude.cpp
ArduCopter/Copter.h
ArduCopter/mode.cpp
ArduCopter/takeoff.cpp

No callers except the mode objects, so move it.

Copter: move set_throttle_takeoff implementation into Mode

---

Tools/autotest/arducopter.py
libraries/AC_Avoidance/AC_Avoid.cpp
libraries/AC_Avoidance/AC_Avoid.h
libraries/AC_Fence/AC_Fence.cpp
libraries/AC_Fence/AC_PolyFence_loader.cpp
libraries/AC_Fence/AC_PolyFence_loader.h
libraries/AP_Logger/AP_Logger.h
libraries/AP_Logger/LogFile.cpp
libraries/AP_Logger/LogStructure.h

This PR is another approach to solving the problem of getting the vehicle to back away from obstacles/fences.
This solves: https://github.com/ArduPilot/ardupilot/issues/7706
Another attempt was made by @IamPete1 here: https://github.com/ArduPilot/ardupilot/pull/14186
This PR takes a lot of inspiration from his original attempt but does not invoke the position controller at all.
Thanks @IamPete1! It would have been very tough to figure this out, had I not seen your experiments with the same feature.
This PR revolves around a new function: `calc_backaway_velocity`
A short explanation would be that the breach in margin is sent to this function, it calculates a speed required to move back the distance it has breached, forms a back away velocity vector. 
So take for eg, these are all the …

AC_Avoid: Back away if vehicle breaches margin to obstacle/fence

---

libraries/AP_UAVCAN/AP_UAVCAN.cpp
libraries/AP_UAVCAN/AP_UAVCAN.h
libraries/GCS_MAVLink/GCS_Common.cpp

This pull request address [this issue ](https://github.com/ArduPilot/ardupilot/issues/13396) and add AP_UAVCAN the ability to send the ESC sensors data as Mavlink ESC message

added support for sending uavcan mavlink esc msgs

---

Tools/autotest/autotest.py
Tools/completion/bash/_sim_vehicle
Tools/completion/zsh/_ap_autotest

Allow to complet subtest on autotest on zsh shell
Correct a function sim_vehicle.py for bash

Tools: add completion for subtest

---

libraries/AP_Scripting/examples/proximity_test.lua
libraries/AP_Scripting/examples/rangefinder_test.lua
libraries/AP_Scripting/generator/description/bindings.desc

AP_Scripting: add rangefinder and proximiy bindings

---

libraries/AP_HAL_Linux/RCInput_RPI.cpp

Ardupilot crashed many times while I was testing it on RasberryPiZero  when I use RCInput_RPI.
I used GDB and found segmentation fault at [(ad+j)->dst](https://github.com/ArduPilot/ardupilot/blob/c8f1b44ee6fb92e02df1291edbf2e35ec11acd2c/libraries/AP_HAL_Linux/RCInput_RPI.cpp#L528)
void *x = circle_buffer->get_virt_addr(**(ad + j)->dst**);
The issue is that nothing guarantees that ad+j is a valid address when j !=0.
I made a fix and tested the board many times and for many hours.

AP_HAL_Linux: Fix RCInput_RPI Segmentation Fault

---

libraries/AP_Baro/AP_Baro_KellerLD.cpp

AP_BARO: Fix zero as nullptr in KellerLD

---

Tools/autotest/rover.py

AT-0417.0: Sending item with seq=0
AT-0417.2: Got (MISSION_REQUEST {target_system : 243, target_component : 250, seq : 0, mission_type : 1})
AT-0417.2: Got (MISSION_REQUEST {target_system : 243, target_component : 250, seq : 0, mission_type : 1})
AT-0417.2: Exception caught: Traceback (most recent call last):
File "/home/travis/build/ArduPilot/ardupilot/Tools/autotest/common.py", line 3950, in run_one_test
test_function()
File "/home/travis/build/ArduPilot/ardupilot/Tools/autotest/rover.py", line 4216, in test_poly_fence
self.test_fence_upload_timeouts()
File "/home/travis/build/ArduPilot/ardupilot/Tools/autotest/rover.py", line 4057, in test_fence_upload_timeouts
target_component=target_component)
File "/home/travis/build/ArduPilot/ardupilot/Tools/autotest/rover.py", line 4010, in …

autotest: slow down simulation to avoid receiving re-request of item

---

libraries/AP_BattMonitor/AP_BattMonitor.cpp
libraries/AP_BattMonitor/AP_BattMonitor.h
libraries/AP_BattMonitor/AP_BattMonitor_Analog.cpp
libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp
libraries/AP_BattMonitor/AP_BattMonitor_Params.h
libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.cpp
libraries/AP_HAL/board/linux.h
libraries/GCS_MAVLink/GCS_Common.cpp

I think a an extra cast here and there is worth the significant de-uglification here.

Move battery type enumeration out of parameters object

---

libraries/AP_Airspeed/AP_Airspeed.cpp
libraries/AP_Airspeed/AP_Airspeed.h

Hitec is developing the 20 and 60 versions and will likely do a 30 in the future.
edit: backport requested

AP_Airspeed: Add additional DLVR support 20inH2O 30inH2O 60inH2O

---

Tools/autotest/arducopter.py

extract from https://github.com/ArduPilot/ardupilot/pull/14882

Tools: copter: correct flip test

---

ArduCopter/Log.cpp

Copter: fix units and multipliers in PL dataflash logs message

---

Tools/scripts/uploader.py

mention STM32F42XX_ERRATA document for 1M flaw
*** someone managed to buy some rev 1 chips recently ***
@peterbarker Is this what you meant?

Tools: scripts: uploader.py: update --identify option

---

libraries/AP_AHRS/AP_AHRS.h
libraries/AP_Scripting/generator/description/bindings.desc

this complements the existing get_gyro() method

scripting: Added get_accel AHRS method

---

Tools/scripts/build_ci.sh

As suggested at devcall, we should build at least one thing with -Werror

travis: build mRoX21-777 with -Werror

---

Tools/ardupilotwaf/boards.py

This came up at the devcall - we're puzzled why this isn't already an error.

waf: build with -Werror=undef

---

Tools/autotest/common.py

Eliminates a race condition when waiting for statustexts.  Getting the
current sim time slurps messages.
Created because I saw this race happen in practise.

autotest: use message hook when waiting for statustext

---

Tools/autotest/arducopter.py
Tools/autotest/common.py

Implement test for https://github.com/ArduPilot/ardupilot/pull/15092

Autotest: copter: add test for mandatory alt estimation for Alt_hold

---

libraries/AP_Logger/AP_Logger.h
libraries/AP_Logger/LogFile.cpp
libraries/AP_Logger/LogStructure.h

@tridge got burnt when these channels weren't in a dataflash log.

AP_Logger: log RCIN channels 14 and 15 in RCI2

---

Tools/autotest/arducopter.py
Tools/autotest/common.py

fix some failure on test_alt_estimate_prearm

Autotest: allow to select which GPS flags we want to wait for

---

Tools/autotest/arduplane.py
libraries/AP_AHRS/AP_AHRS.h
libraries/AP_AHRS/AP_AHRS_DCM.cpp
libraries/AP_AHRS/AP_AHRS_DCM.h
libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
libraries/AP_AHRS/AP_AHRS_NavEKF.h
libraries/AP_Airspeed/AP_Airspeed.cpp
libraries/AP_Airspeed/AP_Airspeed.h
libraries/AP_Baro/AP_Baro.h
libraries/AP_Baro/AP_Baro_SITL.cpp
libraries/AP_Baro/AP_Baro_SITL.h
libraries/AP_HAL_SITL/sitl_airspeed.cpp
libraries/AP_HAL_SITL/sitl_gps.cpp
libraries/AP_Logger/LogStructure.h
libraries/AP_NavEKF2/AP_NavEKF2_Logging.cpp
libraries/AP_NavEKF3/AP_NavEKF3.cpp
libraries/AP_NavEKF3/AP_NavEKF3.h
libraries/AP_NavEKF3/AP_NavEKF3_Logging.cpp
libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp
libraries/AP_NavEKF3/AP_NavEKF3_VehicleStatus.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.h
libraries/SITL/SITL.cpp
libraries/SITL/SITL.h

An EKF3 port of the EK2_Affinity PR #11257 with EKF3 accumulated relative core errors based lane switching #14472 
**_For the general audience_** 
**Affinity** - For a vehicle which has multiple instances of Airspeed - Magnetometer - Barometer - GPS, affinity is a way to assign these sensors between separate EKF cores. This is useful when a vehicle is known to have multiple good quality sensors. If a sensor is healthy and can be used for fusion, we want it to be attached to a specific core. If the number of cores is more than the number of sensor instances, then some cores may share the same sensor (specifically the primary one). A simple example for a vehicle which has 2 baros , 2 GPS, 2 airspeeds, 3 mags and 3 IMUs - following would be the allotment if affinity is enabled and all …

EKF3: Sensor Affinity and Accumulated Error Lane Switching

---

Tools/scripts/build_binaries.py

Something in the program output is not ascii

build_binaries.py: Python3 fix

---

libraries/SITL/SITL.cpp

this came from merging two PRs which both changed SITL params

SITL: fixed SIM_IMU_COUNT conflict

---

Tools/autotest/arducopter.py
Tools/autotest/common.py
Tools/autotest/rover.py

Taken from https://github.com/ArduPilot/ardupilot/pull/9254
Convert wait_distance_to_home to use wait_and_maintain function
Allow to set minimal distance wanted on RTL
Make some progress more readable
add reboot after AltTypes test to prevent the next test to be under the ground

Autotest improvement fixs

---

ArduPlane/Log.cpp

Plane: log speed scaler into AETR

---

libraries/AP_RCProtocol/AP_RCProtocol_DSM.cpp
libraries/AP_RCProtocol/AP_RCProtocol_DSM.h
libraries/AP_RCProtocol/examples/RCProtocolTest/RCProtocolTest.cpp

Put back DSM VTX control and logging

---

libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp
libraries/SITL/SIM_AirSim.cpp
libraries/SITL/SIM_AirSim.h

Plus:
1. Increase RC channels to 12
2. Resend servo output if no message is received in 1 second (Haven't seen it happen, but just to be sure)
Corresponding AirSim PR - https://github.com/microsoft/AirSim/pull/2920
Wiki PR - https://github.com/ArduPilot/ardupilot_wiki/pull/2948

SITL: Airsim: Add support for rangefinder sensor data

---

.travis.yml
Tools/scripts/build_ci.sh
Tools/scripts/configure-ci.sh

Since https://github.com/ArduPilot/ardupilot/pull/14761 was merged, I'm adding a build test to avoid any break for the musl toolchain.

Tools/Travis: Add musl toolchain test for navigator target

---

ArduPlane/Parameters.cpp

Plane: Update THR_FAILSAFE param metadata

---

Tools/scripts/build_ci.sh
Tools/scripts/configure-ci.sh

Split from one of @khancyr 's commits.

Use python-m-pip rather than pip directly so Py2/Py3 is less painfule

---

Tools/autotest/arduplane.py
Tools/autotest/common.py

Use same to fix Plane ThrottleFailsafe check.

autotest: create collections-on-context to record selected messages

---

libraries/AP_Filesystem/AP_Filesystem_Sys.cpp
libraries/AP_Scheduler/AP_Scheduler.cpp
libraries/AP_Scheduler/AP_Scheduler.h
libraries/AP_Scheduler/PerfInfo.cpp
libraries/AP_Scheduler/PerfInfo.h

This is the output on Plane:
```
TasksV1
Plane::ahrs_update               MIN=134 MAX=912 AVG=220 OVR=  1 SLP=  0
Plane::read_radio                MIN=  7 MAX=174 AVG= 22 OVR=  1 SLP=  0
Plane::check_short_failsafe      MIN=  2 MAX=326 AVG=  6 OVR=  1 SLP=  0
Plane::update_speed_height       MIN=  2 MAX=110 AVG= 31 OVR=  0 SLP=  0
Plane::update_control_mode       MIN=  4 MAX= 84 AVG= 14 OVR=  0 SLP=  0
Plane::stabilize                 MIN=  2 MAX=163 AVG= 61 OVR= 28 SLP=  0
Plane::set_servos                MIN= 47 MAX=127 AVG= 61 OVR=  5 SLP=  0
Plane::update_throttle_hover     MIN=  2 MAX= 26 AVG=  3 OVR=  0 SLP=  0
Plane::read_control_switch       MIN=  2 MAX= 18 AVG=  3 OVR=  0 SLP=  0
Plane::update_GPS_50Hz           MIN= 20 MAX=676 AVG= 31 OVR= 13 SLP=  0
Plane::update_GPS_10Hz …
```

Scheduler support for @SYS/tasks.txt

---

Tools/autotest/arducopter.py
Tools/autotest/arduplane.py
Tools/autotest/common.py

Can lead to some very weird and confusing output

autotest: avoid leaving message hooks around

---

Tools/ardupilotwaf/chibios.py
libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py

will be used to generate a web page showing amount of free flash per board and history of flash usage

add flash_total to apj

---

libraries/AC_AttitudeControl/AC_PosControl.cpp
libraries/AC_AttitudeControl/AC_PosControl.h
libraries/AP_Logger/AP_Logger.h
libraries/AP_Logger/LogFile.cpp
libraries/AP_Logger/LogStructure.h

Adds PID logging to PosControl, useful for tuning

AC_AttitudeControl: Add PosControl PID logging

---

Tools/autotest/arduplane.py

the EKF lane switch test in Plane would occasionally fail, mostly because the lane switch status text would sometimes pop up after the parameter change to cause the lane switch but before we actually start looking for it, this PR fixes that bug by collecting status text messages from the beginning of the subtest and look for the lane switch one in context when required. This ensures we do not miss it.
also I've checked this with #15281 and its working fine with the speedups (the aforementioned PR is failing the ekf lane switch test on CI)
fixes #15279

autotest: bug fixes for ekf lane switch test

---

Tools/autotest/common.py

autotest: loosen mag-percent-complete threshold to 95%

---

.travis.yml
Tools/scripts/build_ci.sh

Currently you have to mouse-over the job name to see what it's all about.  This makes several more visible...

Add names to travis jobs

---

Tools/autotest/common.py

Setting a parameter on ArduPilot causes the autopilot to emit the new
value in a PARAM_VALUE message, so we do not need to fetch it ourselves.
Fetching it ourselves causes subtle problems for the autotest suite
where a PARAM_VALUE is currently in the uart buffer - so the autotest
set_parameter has consumed one PARAM_VALUE message (the auto-emitted
one).  If it immediately does a set_parameter then the next
PARAM_VALUE it sees will be the OLD value as the value comes out of the
uart.

autotest: stop set_parameter from using get_parameter

---

libraries/AP_Mount/AP_Mount_Alexmos.cpp
libraries/AP_Mount/AP_Mount_SToRM32.cpp
libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
libraries/AP_Mount/AP_Mount_Servo.cpp
libraries/AP_Mount/AP_Mount_SoloGimbal.cpp

Removes a few includes that were unused

Remove unused includes

---

libraries/AP_GyroFFT/AP_GyroFFT.cpp
libraries/AP_Logger/AP_Logger_Block.cpp

This PR makes sure the logging IO thread gets cycles even when the FFT is running.
Tested on an F4 Pixracer and F7 Kakute F7 Mini
Also confirmed on an omnibus nano v6 (f4)

Reduce FFT and Logging thread/lock contention

---

libraries/GCS_MAVLink/GCS_Common.cpp

GCS_MAVLink: fixed critical error on prefight cal ops

---

AntennaTracker/system.cpp
ArduCopter/AP_Arming.cpp
ArduCopter/Copter.cpp
ArduCopter/Copter.h
ArduCopter/GCS_Mavlink.cpp
ArduCopter/Parameters.cpp
ArduCopter/avoidance_adsb.cpp
ArduCopter/config.h
ArduCopter/mode.cpp
ArduPlane/ArduPlane.cpp
ArduPlane/GCS_Mavlink.cpp
ArduPlane/Parameters.cpp
ArduPlane/Plane.h
ArduPlane/avoidance_adsb.cpp
ArduPlane/is_flying.cpp
ArduPlane/mode.cpp
ArduSub/system.cpp
Rover/system.cpp
libraries/AP_ADSB/AP_ADSB.cpp
libraries/AP_ADSB/AP_ADSB.h
libraries/AP_ADSB/AP_ADSB_Backend.cpp
libraries/AP_ADSB/AP_ADSB_Backend.h
libraries/AP_ADSB/AP_ADSB_MAVLink.cpp
libraries/AP_ADSB/AP_ADSB_MAVLink.h
libraries/AP_ADSB/AP_ADSB_Sagetech.cpp
libraries/AP_ADSB/AP_ADSB_Sagetech.h
libraries/AP_Avoidance/AP_Avoidance.cpp
libraries/AP_Avoidance/AP_Avoidance.h
libraries/AP_UAVCAN/AP_UAVCAN.cpp
libraries/RC_Channel/RC_Channel.cpp

This cuts flash usage and gets the 1mb F7 boards going again.

Conditionally compile in ADSB support

---

.travis.yml
Tools/scripts/configure-ci.sh

Remove some package leftover from nuttx

Travis package cleanup

---

Tools/autotest/common.py

ATM if the SITL binary dies we don't catch it anywhere.  This might
become part of the solution for that, as well as some changes on
run_one_test.

autotest: improve use of SITL-is-running

---

.travis.yml

fix ci failure, this is taken from part of cefd30a0864aad39968934be26231330cf96b7fd

travis: fix typo

---

libraries/SITL/examples/Webots/README.md

SITL: correct Webots README.md

---

ArduSub/GCS_Mavlink.h
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp

See https://github.com/ArduPilot/ardupilot/pull/15096#issuecomment-677691050

Sub: disable capacity remaining on Sub 4.1

---

libraries/AP_Filesystem/examples/File_IO/File_IO.cpp
libraries/AP_Filesystem/examples/File_IO/wscript

Looking forward for suggestions if it can be any helpful and what changes or improvements can be done or need

AP_Filesystem: add simple File I/O example

---

libraries/AP_Baro/AP_Baro_DPS280.cpp

Remove unnecessary debug which shows up on every boot

[AP_Baro_DPS280] Remove unnecessary debug

---

Tools/autotest/arduplane.py

- Update mavlink submodule
- Update soaring autotest to use THERMAL mode name

Plane: THERMAL mode cleanup

---

libraries/AP_ADSB/AP_ADSB.cpp

with ADSB on by default on CubeOrange this debug msg is v annoying

AP_ADSB: remove annoying debug

---

libraries/SITL/SIM_Aircraft.cpp
libraries/SITL/SIM_Aircraft.h
libraries/SITL/SIM_Multicopter.cpp
libraries/SITL/SIM_Rover.cpp
libraries/SITL/SIM_Rover.h
libraries/SITL/SIM_Tracker.cpp
libraries/SITL/SIM_Tracker.h

... and move some others into the class definition

SITL: remove pointless initialisations

---

libraries/AP_Filesystem/AP_Filesystem_Sys.cpp
libraries/AP_Scheduler/AP_Scheduler.cpp

This PR adds a TOT field which shows the total time a task has taken as a percentage of all tasks. The output is quite helpful I think
```
TasksV1
Copter::rc_loop                  MIN= 12 MAX= 94 AVG= 15 OVR=  1 SLP=  0, TOT= 1.8%
Copter::throttle_loop            MIN= 12 MAX= 84 AVG= 14 OVR=  6 SLP=  0, TOT= 0.8%
AP_GPS::update                   MIN= 14 MAX=629 AVG= 28 OVR=102 SLP=  0, TOT= 1.6%
OpticalFlow::update              MIN=  2 MAX= 89 AVG=  3 OVR=  1 SLP=  0, TOT= 0.8%
Copter::update_batt_compass      MIN=  5 MAX= 74 AVG=  7 OVR=  1 SLP=  0, TOT= 0.1%
RC_Channels::read_aux_all        MIN=  5 MAX= 94 AVG=  7 OVR= 13 SLP=  0, TOT= 0.1%
Copter::arm_motors_check         MIN=  2 MAX= 65 AVG=  2 OVR=  2 SLP=  0, TOT= 0.0%
Copter::auto_disarm_check        MIN=  3 MAX= 70 AVG=  4 OVR= 10 …
```

Show task percentage time

---

libraries/AP_LeakDetector/AP_LeakDetector_Digital.cpp

AP_LeakDetector: AP_LeakDetector_Digital: Improve status logic

---

Tools/autotest/arducopter.py

position targets only need to be set once.
velocity targets have to be set all the time

autotest: send position targets once

---

Tools/autotest/arducopter.py

On the basis that random noise can make it drift 10cm

autotest: loosen takeoff check in heli takeoff to 1m

---

libraries/AP_Math/AP_Math.cpp

AP_MATH: Remove isnan check for non-float type

---

libraries/AP_NavEKF2/AP_NavEKF2.h
libraries/AP_NavEKF2/AP_NavEKF2_core.cpp
libraries/AP_NavEKF2/AP_NavEKF2_core.h
libraries/AP_NavEKF3/AP_NavEKF3.h
libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.h

- remove dangling method declarations
- create an enum-class for Height Source
- correct some includes

NFC EKF cleanups

---

libraries/AP_Mount/AP_Mount.cpp
libraries/AP_Mount/AP_Mount.h

AP_Mount: Improve instance validation check

---

libraries/AP_GPS/RTCM3_Parser.cpp
libraries/AP_GPS/RTCM3_Parser.h
libraries/AP_Math/crc.cpp
libraries/AP_Math/crc.h

rework from https://github.com/ArduPilot/ardupilot/pull/14084 with comments addressed

Ap move the crc24 fix

---

libraries/AP_NavEKF2/AP_NavEKF2_core.cpp
libraries/AP_NavEKF2/AP_NavEKF2_core.h
libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.h

... and remove some code duplication

Remove unused state variables from EKFs

---

Tools/autotest/autotest.py
Tools/autotest/web-firmware/index.html
Tools/autotest/web/css/main.css
Tools/autotest/web/index.html

This fix the githash on https://autotest.ardupilot.org/ with Python3.
It fix some html field and use class on CSS for some fix. The output is unchanged
Set google analytics to anonymize IP
Remove Jdrone logos

Autotest HTML fixes

---

libraries/AP_Logger/AP_Logger_File.cpp
libraries/AP_Logger/AP_Logger_File.h

if booting without a microSD and with LOG_DISARMED=1 then this allows
for a retry of opening the log every 5s
ping @WickedShell

AP_Logger: allow for retry of log open with LOG_DISARMED=1

---

Tools/scripts/build_binaries_history.py

This fix database creation that miss a commit to create the database schema.

Database fix

---

Rover/Parameters.cpp
Rover/defines.h
Rover/ekf_check.cpp

I don't know of a filter called EFK.
I'm changing to EKF.

Rover: Change abbreviations

---

libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp

EKF3 is not always informing external callers of yaw resets when "external" yaw is being used (i.e. yaw from GPS or external nav).  In particular it is not informing them during the first yaw alignment.  It may also not be informing callers in other situations as well.
The issue appears to be some missing code in [alignYawAngle()](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp#L181) and I think we can simplify this method by making it more like [setYawFromMag()](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_NavEKF3/AP_NavEKF3_core.cpp#L1873) and call [resetQuatStateYawOnly()](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp#L1531).
From inspection the resetQuatStateYawOnly …

AP_NavEKF3: simplify alignYawAngle and signal yaw reset

---

libraries/AP_ADSB/AP_ADSB.cpp
libraries/AP_ADSB/AP_ADSB.h
libraries/AP_ADSB/AP_ADSB_Backend.cpp
libraries/AP_ADSB/AP_ADSB_Backend.h
libraries/AP_ADSB/AP_ADSB_uAvionix_MAVLink.cpp
libraries/AP_ADSB/AP_ADSB_uAvionix_MAVLink.h

Split the ADSB into a frontend/backend split. This is meant to be a non-functional baby-step change.

ADSB: Backend split

---

ArduCopter/Parameters.cpp

Copter: fix metadata in FS_GCS_ENABLE param

---

libraries/AP_Compass/CompassCalibrator.h

See discussion here:
https://discuss.ardupilot.org/t/location-one-calibration-bad-radius-issue/63714

AP_Compass: raise max scale factor and make symmetric

---

ArduPlane/radio.cpp

Fixes #15691 
Is this ok for you @IamPete1 ?

ArduPlane: Fix throttle nudge reset due to wrong radio timing

---

libraries/AP_Scripting/examples/Serial_Dump.lua

does what it says on the tin, read in and saves it to a file.

AP_Scripting: example saving serial data to SD card

---

ArduPlane/radio.cpp

back port of https://github.com/ArduPilot/ardupilot/pull/15743

Plane: Fix throttle nudge reset due to wrong radio timing - backport

---

libraries/AP_Camera/AP_RunCam.cpp
libraries/AP_Camera/AP_RunCam.h

These are supported via a new ```CAM_RC_TYPE=3```

Add support for RunCam Split4 4k and RunCam Hybrid

---

Tools/autotest/arducopter.py
Tools/autotest/common.py
libraries/GCS_MAVLink/MissionItemProtocol_Rally.cpp

Fixes for autotest so it can generally run
Fix for Rally uploading where data-off-the-stack could be used.

Valgrind fixes

---

libraries/AP_Arming/AP_Arming.cpp
libraries/AP_Scripting/examples/arming-check-batt-temp.lua

AP_Arming: fix aux auth check loophole

---

libraries/SITL/SIM_BattMonitor_SMBus.cpp
libraries/SITL/SIM_BattMonitor_SMBus.h
libraries/SITL/SIM_BattMonitor_SMBus_Generic.h
libraries/SITL/SIM_BattMonitor_SMBus_Rotoye.cpp
libraries/SITL/SIM_BattMonitor_SMBus_Rotoye.h
libraries/SITL/SIM_I2C.cpp

Also correct temperature from generic battery simulator

SITL: add simulator for Rotoye battery monitor

---

libraries/AP_DAL/AP_DAL_RangeFinder.cpp

AP_DAL: fixed distance in rangefinder data

---

libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp
libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp
libraries/AP_Scripting/lua/src/lundump.c

@khancyr can we add a gcc 9.x build to CI?

build: fixed build for gcc 9.x

---

libraries/AP_HAL_ChibiOS/hwdef/f303-periph/hwdef.dat

hwdef: fix misprint in comment
non-functional change

hwdef: fix misprint in comment

---

libraries/AP_BoardConfig/AP_BoardConfig.h

AP_BoardConfig: reorder the fixed-index enum.
non-functional change

AP_BoardConfig: reorder the fixed-index enum

---

libraries/AP_Logger/LogStructure.h

Unused since we've moved to new Replay code

AP_Logger: remove unused IMUDT code

---

libraries/Filter/HarmonicNotchFilter.cpp

We keep getting forum questions about out of range values and defaults. This provides better versions of both.

Correct harmonic notch docs and provide better defaults.

---

ArduCopter/RC_Channel.cpp
libraries/RC_Channel/RC_Channel.cpp

somehow this was missed at some point...if you have a servo mount, you may need this, if for nothing else but to stop stabilization

Add mount retract RC switch option in Plane

---

libraries/AP_Scripting/lua/src/lcode.c
libraries/AP_Scripting/lua/src/lstrlib.c
libraries/AP_Scripting/lua/src/ltable.c

This allows me to build SITL on my XCode 12 environment

Fix lua compile on clang 10

---

libraries/AP_Logger/AP_Logger_Block.cpp

I occasionally get these IO thread died errors when doing development and on further investigation it looks like a transient startup condition from which we never recover. Checking the logging thread every second during normal operation is fine, but at startup there is a whole pile of intense CPU load going on that can catch the thread including expected delays. And once its gone you can't get it back. This simply checks that we are not in an expected delay and raises the timeout to match that of the file logger.

Fix startup penalty on IO thread health

---

ArduCopter/Parameters.cpp
ArduCopter/events.cpp
libraries/AC_AttitudeControl/AC_PosControl.cpp
libraries/AC_PrecLand/AC_PrecLand.cpp
libraries/AP_HAL_ChibiOS/hwdef/mRoPixracerPro/hwdef.dat
libraries/AP_Logger/LogStructure.h
libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp
libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
libraries/AP_RCProtocol/AP_RCProtocol_FPort.cpp
libraries/GCS_MAVLink/GCS_Common.cpp

These are the (I hope) non controversial parts of #15227
All CI tests pass so I hope this can be merged today :)
My plan is to rebase #15227 on top of this, once this one gets merged.

Misc (almost nfc) Copter 4.0 backports

---

Rover/AP_MotorsUGV.cpp
Tools/autotest/rover.py

Should be merged after https://github.com/ArduPilot/ardupilot/pull/14843 as it won't pass due to the current bug in slew rate

Tools: rover: add test for slew rate

---

libraries/AP_GPS/AP_GPS.cpp

AP_GPS: expand gps rate description

---

Tools/autotest/autotest.py

This won't fix all the loading as I don't know where the css is put on our server ...

Autotest: fix css loading for autotest.ardupilot.org

---

libraries/AP_InertialSensor/AP_InertialSensor.h

AP_InertialSensor: use primary gyro (not accel) for get_delta_angle_dt

---

libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp

This leaves us with only a single mis-indented block.
We could remove 2 levels of indentation from this method, and probably should at some stage.

AP_NavEKF3: rearrange readGPSData to remove some nesting

---

libraries/GCS_MAVLink/GCS_Signing.cpp

Tested in SITL and on stm32.
I believe this structure used to be static (it is next to several static structures in the header).
However, it contains link-specific information (the channel number in particular - it is filled in earlier in this function!).  My guess is it was moved to be non-static but this loop remained.
The loop being removed here takes the current channel's signing structure and assigns a pointer to it into each of the backend's status object - so each of them now has data with the wrong link in it, at the very least.  It would appear last-channel-in-wins.
@Jaaaky for visibility

GCS_MAVLink: stop using one backend's signing structure for all backends

---

libraries/AP_OSD/AP_OSD_Screen.cpp

AP_OSD: Fix vertical speed varying length

---

libraries/Filter/HarmonicNotchFilter.cpp

Squashed and backported documentation fixes

Filter: correct harmonic notch docs (NFC) and provide better defaults (non-NFC).

---

ArduPlane/AP_Arming.cpp
ArduPlane/Parameters.h
ArduPlane/Plane.h
ArduPlane/commands_logic.cpp
ArduPlane/defines.h
ArduPlane/geofence.cpp
ArduPlane/quadplane.cpp
ArduPlane/takeoff.cpp
libraries/AP_Param/AP_Param.h

use common code with fixed wing landing
fixes #15917 
ping @lthall 
Note: this also adds a new AP_Enum type for making type safe AP_Int8 for enum

Plane: Fixed auto-disable of fence on quadplane landing

---

ArduCopter/landing_gear.cpp
libraries/AP_LandingGear/AP_LandingGear.cpp

Plane will get this logging too.

Move LandingGear event logging into library

---

libraries/AP_HAL_SITL/SITL_State.cpp
libraries/AP_HAL_SITL/SITL_State.h
libraries/SITL/SIM_PS_RPLidarA2.cpp
libraries/SITL/SIM_PS_RPLidarA2.h
libraries/SITL/SIM_PS_TeraRangerTower.cpp
libraries/SITL/SIM_PS_TeraRangerTower.h
libraries/SITL/SIM_SerialProximitySensor.cpp
libraries/SITL/SIM_SerialProximitySensor.h

I'm not sure how accurate this is for things like out-of-range...

Add TeraRangerTower simulator

---

libraries/AP_HAL_ChibiOS/hwdef/mRoPixracerPro/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py

this allows ESD issues to be avoided by pulling all unused pins low
ping @pkocmoud 
See this note in AN4899

HAL_ChibiOS: added new option DEFAULTGPIO for hwdef.dat

---

ArduPlane/geofence.cpp

Replaces https://github.com/ArduPilot/ardupilot/pull/14809

Plane: be consistent about strings in fence auto-enable/disable

---

libraries/AP_Scripting/generator/description/bindings.desc

useful when creating a mission

AP_Scripting: added offset_bearing location binding

---

libraries/AP_Volz_Protocol/AP_Volz_Protocol.cpp
libraries/AP_Volz_Protocol/AP_Volz_Protocol.h

AP_Volz_Protocol: scaling bugfix

AP_Volz_Protocol scaling bugfix

---

Tools/AP_Periph/AP_Periph.h
Tools/AP_Periph/can.cpp
Tools/AP_Periph/msp.cpp
libraries/AP_Airspeed/AP_Airspeed.cpp
libraries/AP_Airspeed/AP_Airspeed.h
libraries/AP_Airspeed/AP_Airspeed_Backend.h
libraries/AP_Airspeed/AP_Airspeed_MSP.cpp
libraries/AP_Airspeed/AP_Airspeed_MSP.h
libraries/AP_Airspeed/AP_Airspeed_SDP3X.cpp
libraries/AP_Airspeed/AP_Airspeed_UAVCAN.cpp
libraries/AP_MSP/AP_MSP_Telem_Backend.cpp
libraries/AP_MSP/AP_MSP_Telem_Backend.h
libraries/AP_MSP/msp_protocol.h
libraries/AP_MSP/msp_sensors.h

Missing AP MSP side
INAV side: https://github.com/iNavFlight/inav/pull/6090

AP_Periph: support output of MSP airspeed sensor

---

libraries/RC_Channel/RC_Channels_VarInfo.h

thanks @andyp1per  for spotting this

RC_Channel: added FPORT2 to RC_PROTOCOLS parameter

---

libraries/AP_HAL_SITL/SITL_State.cpp
libraries/AP_HAL_SITL/SITL_State.h
libraries/SITL/SIM_PS_LightWare.h
libraries/SITL/SIM_PS_LightWare_SF45B.cpp
libraries/SITL/SIM_PS_LightWare_SF45B.h

@rishabsingh3003 turns out I had one of these almost completed....
I'm not 100% convinced of the output of this one.  It's *close*, but looks like it might be a sector out or something....

Add simulator for SF45B proximity sensor

---

Tools/AP_Periph/can.cpp

This will enable AP_Periph packet UAVCAN_EQUIPMENT_POWER_BATTERYINFO to populate:
state_of_health_pct
state_of_charge_pct
model_instance
model_name
The ```state_of_charge_pct``` value will be taken advantage of by https://github.com/ArduPilot/ardupilot/pull/16003

AP_Periph: populate more fields in batteryinfo

---

libraries/GCS_MAVLink/GCS_Common.cpp

The mavlink code will the automatically either:
send all 14 battery cell voltages using Mavlink2
send only the first 10 cells using Mavlink 1
This is a behaviour change, the current code sends the minimum of the last 3 cells in the voltage of cell 10
@rmackay9 said that he is OK with this behaviour change.
Also updates the mavlink submodule

Support up-to 14 cells in BATTERY_STATUS mavlink message

---

Tools/autotest/bisect-helper.py
Tools/autotest/common.py

Other PR is being hijacked with a Plane fix.
Also sneaking in a change to autotest to allow waiting on a statustext by regex.

Allow bisection using autotest

---

Tools/autotest/arduplane.py
libraries/AP_AHRS/AP_AHRS_NavEKF.cpp

I've renamed this PR to reflect its current content.
It now simply contains a fix for a regression  in our prearm checks where we no longer ensure the AHRS is healthy before allowing arming.
It is believed this only affects Plane, as for the most part the healthy() checks are replicated in the still-running pre_arm_check() code.  However, DCM's health is checked in healthy(), *not* in the pre_arm_checks(), so before this patch is applied Plane can arm even if DCM is not yet healthy.
Old content:
Documentation is here: https://github.com/ArduPilot/ardupilot_wiki/pull/3201
This allows you to write a failing autotest on master and, after nominating a commit where the test passes, use git bisect's `run` option to automatically bisect to find the commit which killed the test.
At some stage …

Check AHRS health before allowing arming

---

libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp

this caused a segfault in replay

AP_NavEKF3: fixed null dereference of airspeed

---

README.md

Fixed some grammatical errors found in the readme file

README: fixes some grammatical errors

---

libraries/AP_HAL_SITL/UARTDriver.cpp

this fixes MSP sensors in SITL with real uarts

HAL_SITL: fixed baudrate 0 set in SITL

---

Tools/autotest/param_metadata/param.py
libraries/AP_NavEKF3/AP_NavEKF3.cpp

@peterbarker asked for it, here it is!!!

Add Wind estimation PR units

---

libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp
libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.h

Fixes https://github.com/ArduPilot/ardupilot/issues/15967
Has been tested using replay of https://www.dropbox.com/s/eohvs991c5mb2ng/ekf3-yaw-spin.BIN?dl=0
A minimum fix to this issue would be the first commit, but the cleanup of the yaw fuson logic has been added to make the code easier to follow and remove some logic inconsistencies.
Requires wider flight testing.

EKF3 yaw fixes

---

libraries/SITL/SIM_FlightAxis.cpp
libraries/SITL/SIM_FlightAxis.h

This improves the frame rate of RealFlight on cygwin by a factor of about 6x

SITL: fixed the speed of FlightAxis on cygwin

---

Tools/GIT_Test/GIT_Success.txt

Tools: add name to GIT_Test.txt

---

libraries/GCS_MAVLink/GCS_Common.cpp

Add signal_quality field to DISTANCE_SENSOR MAVLink message

mavlink: Add signal_quality field to DISTANCE_SENSOR MAVLink message

---

libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
libraries/AP_Motors/AP_MotorsHeli_Dual.h

AP_Motors: add DCP trim feature for Dual Heli backport to AC4.0

---

Tools/AP_Periph/msp.cpp

@tridge please merge before the next stable release

AP_Periph: MSP fix last baro ms

---

Tools/autotest/arducopter.py
Tools/autotest/common.py
Tools/autotest/rover.py

Create set position and set velocity target global test for copter and rover

Add set position and velocity target global tests

---

libraries/AP_Mount/AP_Mount_Alexmos.cpp
libraries/AP_Mount/AP_Mount_Backend.cpp
libraries/AP_Mount/AP_Mount_SToRM32.cpp
libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
libraries/AP_Mount/AP_Mount_Servo.cpp
libraries/AP_Mount/AP_Mount_SoloGimbal.cpp

Relevant mavlink PR is here: https://github.com/ArduPilot/mavlink/pull/179

Handle MAV_MOUNT_MODE_HOME_LOCATION

---

libraries/AP_NavEKF/AP_NavEKF_Source.cpp

Fixed some styling issues in AP_NavEKF_Source.cpp according to the style guide.

AP_NavEKF_Source:Fixed some style issues

---

libraries/AP_RangeFinder/AP_RangeFinder_VL53L1X.cpp

rework from https://github.com/ArduPilot/ardupilot/pull/10092

NFC: AP_RangeFinder: Make measurement time and call back time static constant

---

.github/workflows/test_chibios.yml
.github/workflows/test_linux_sbc.yml
.github/workflows/test_replay.yml
.github/workflows/test_sitl_copter.yml
.github/workflows/test_sitl_periph.yml
.github/workflows/test_sitl_plane.yml
.github/workflows/test_sitl_rover.yml
.github/workflows/test_sitl_sub.yml
.github/workflows/test_sitl_tracker.yml
.github/workflows/test_unit_tests.yml

This allow to rerun jobs on action

actions : add Workflow dispatch

---

libraries/AP_ADSB/AP_ADSB.cpp
libraries/AP_ADSB/AP_ADSB.h
libraries/AP_ADSB/AP_ADSB_Backend.h
libraries/AP_ADSB/AP_ADSB_Sagetech.cpp
libraries/AP_ADSB/AP_ADSB_Sagetech.h
libraries/AP_HAL/utility/sparse-endian.h
libraries/AP_SerialManager/AP_SerialManager.cpp
libraries/AP_SerialManager/AP_SerialManager.h

This builds on top of https://github.com/ArduPilot/ardupilot/pull/15736
Adds the Sagetech ADSB transceiver driver for the XP series of products. This also includes a few hints of the MX driver which will be fully added in a later PR which will support their newer MX series products. The protocol is similar enough that a single driver can handle both.

ADSB: add Sagetech XP driver

---

Tools/AP_Bootloader/board_types.txt

Cross-alignment with PX4, plus whitespace fixes

Tools: Update board_types.txt

---

libraries/AP_HAL_ChibiOS/hwdef/KakuteF7/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/OMNIBUSF7V2/hwdef.dat

HAL_ChibiOS: Reinstate HAL_MINIMIZE_FEATURES for 1MB F7 boards

---

Tools/scripts/build_ci.sh

Tools: build_ci.sh: re-add KakuteF7Mini for bidir d-shot testing

---

libraries/AP_HAL_ChibiOS/RCOutput.cpp

this fixes a build error due to conditional always being false when
NUM_GROUPS==0 by using a C++ iterator. It also makes the code neater

HAL_ChibiOS: fixed build with alarm and no PWM channels

---

libraries/AP_HAL_SITL/I2CDevice.cpp

AP_HAL_SITL: correct I2C callback interval

---

libraries/SITL/SIM_I2C.cpp
libraries/SITL/SIM_I2CDevice.cpp

Also add the 8-bit register helper as it will help with some other PRs.

Correct handling of i2c messages

---

libraries/AP_Math/tests/test_vector2.cpp
libraries/AP_Math/vector2.cpp

I think it is better to make isnan judgment before delta operation.
Also, I think that it is better to perform isnan judgment before the zero judgment of variable a.

AP_Math: judge isnan judgment before operation

---

libraries/AP_Logger/README.md

Add clarity to the multipliers and descriptions

AP_Logger: README add multiplier descriptions

---

Rover/GCS_Mavlink.cpp
Rover/GCS_Mavlink.h
Tools/autotest/rover.py

Co-authored-by: nubcaker
This replaces https://github.com/ArduPilot/ardupilot/pull/13821
It does not reindent the code, which makes scanning through the code to ensure no unintended logic changes have been made easy to do.
A follow-up PR could reindent the code ('though this has the bad side-effect of clouding the line-history in the file).

Rover: tidy GCS_MAVLink handleMessage function

---

ArduCopter/GCS_Mavlink.cpp

I found that the processing was interrupted by the same preprocessor.
I found it to finish in the preprocessor.
I reviewed the processing.

Copter: tidy handling of DO_FLIGHT_TERMINATION

---

libraries/AP_HAL/examples/AnalogIn/AnalogIn.cpp

Added proper comments to the AnalogIn example sketch as suggested [here](https://ardupilot.org/dev/docs/learning-ardupilot-the-example-sketches.html). Thank you

AP_HAL:examples:AnalogIn: Added comments in the AnalogIn example

---

.github/workflows/test_chibios.yml
.github/workflows/test_linux_sbc.yml
.github/workflows/test_replay.yml
.github/workflows/test_sitl_copter.yml
.github/workflows/test_sitl_periph.yml
.github/workflows/test_sitl_plane.yml
.github/workflows/test_sitl_rover.yml
.github/workflows/test_sitl_sub.yml
.github/workflows/test_sitl_tracker.yml
.github/workflows/test_unit_tests.yml

migrate docker images from my repo to ardupilot one's

.github: migrate to ardupilot image

---

libraries/AP_Logger/AP_Logger_File.cpp
libraries/AP_Logger/AP_Logger_File.h

This will make moving stuff to a thread simpler.

Initialise AP_Logger_File instance variables in header

---

libraries/AP_GPS/AP_GPS_UAVCAN.cpp
libraries/AP_GPS/AP_GPS_UAVCAN.h
libraries/AP_UAVCAN/dsdl/ardupilot/gnss/20002.Heading.uavcan

support for uavcan gps heading input into ardupilot

UAVCAN heading support

---

Tools/autotest/common.py

This helps us actually execute the timeouts appropriately and thus
re-fetch the STAT_BOOTCNT parameter we use for detecting the reboot
Eliminates annoying pauses during testing.
We rely on MAVProxy to reset the streamrates so we get messages....
SITL precision landing test:
```
New:
real	0m31.740s
user	0m24.787s
sys	0m6.908s
master:
real	0m50.851s
user	0m30.685s
sys	0m10.912s
```

autotest: prompt ArduPilot for SYSTEM_TIME message during reboot

---

libraries/AP_HAL_ChibiOS/Scheduler.h
libraries/AP_HAL_ChibiOS/UARTDriver.cpp
libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
libraries/AP_Logger/AP_Logger.cpp
libraries/GCS_MAVLink/GCS_FTP.cpp

Adjust stack sizes based on report from @Hwurzburg 
We are a bit low in log_io, and have more than is warranted in some other threads

Adjust stack sizes

---

ArduPlane/mode.h
ArduPlane/soaring.cpp

- Add const methods on mode classes to define those that automatically switch into thermal mode
- Re-order logic to improve readability

Plane: Refactor soaring.cpp

---

Tools/autotest/arducopter.py
Tools/autotest/arduplane.py
Tools/autotest/rover.py

also disarm the vehicle if the vibe test fails

autotest: print stack traces for caught exceptions

---

Tools/vagrant/mavinit.scr

path is no longer valid. not tested.

Tools: vagrant: update path to CMAC-circuit.txt

---

libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp

like what already done in
https://github.com/ArduPilot/ardupilot/blob/1dad0ecb462cbaa4ac83acd5745913d5de5a335c/libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp#L458

AP_NavEKF3: use posxy_source in all places

---

ArduPlane/quadplane.cpp

This does two things. Firstly it moves quad-plane logging from `motors_output` to `update`. This is because tailsitters call `motors_output` a [second time](https://github.com/ArduPilot/ardupilot/blob/9791e520733c74d1fefe46f582e7e72d8b5c4ee1/ArduPlane/tailsitter.cpp#L159) resulting in two `RATE` logs per update.
Secondly this persists `QTUN` logging after a VTOL mode or Qassist for a quarter second. This means we get the final Qassist and transition state in the logs, currently the log just stops so you don't get the true state of the vehicle.
If we decide against the log persisting, we could just only log when calling motors_output and running the rate controllers, I think that would also protect against the double logging with tailsitters.

Plane: move quadplane logging to QuadPlane: update()

---

libraries/AP_Math/AP_Math.h

I now think it is worth the flash space
ping @WickedShell

AP_Math: enable constrain value with line numbers on all boards

---

Tools/autotest/rover.py

The vehicles doesn't send us set messages!

autotest: correct Rover set-position-target-global-int test

---

Tools/autotest/sim_vehicle.py

more fallout from this PR:
https://github.com/ArduPilot/ardupilot/pull/16353

autotest: fixed --tracker option to sim_vehicle.py

---

libraries/AP_HAL_Linux/HAL_Linux_Class.cpp

this makes it clearer what is going on

HAL_Linux: use nullptr for vnav rcinput

---

Tools/autotest/common.py

This just factors out some code and uses it to shorten a loop based on a piece of text arriving.

autotest: Pull out a statustext-in-collection method and use it to shorten waiting-for-disarm

---

Tools/autotest/arducopter.py

... failed on a PR of mine, so let's automatically push that retry button....

autotest: retry GyroFFTHarmonic test on failure

---

libraries/AP_AHRS/AP_AHRS.h
libraries/GCS_MAVLink/GCS_Common.cpp

... because most of the time you really should care.

Add WARN_IF_UNUSED to get_position

---

Tools/autotest/common.py

These can take some time to run and the user is left wonder what's going on

autotest: make arming test a little more verbose

---

.gitignore
Tools/AP_Periph/wscript
Tools/ardupilotwaf/boards.py
wscript

First step in getting betting integration of ardupilot with VSCode. The extension being developed for this:
https://github.com/ardupilot/ardupilot_vscode_devenv
Few Screenshots:

add support for VS Code tasks to do build and upload 

---

Tools/autotest/autotest.py

Broken since https://github.com/ArduPilot/ardupilot/pull/16384

Autotest: fix subtests completion

---

libraries/AP_BLHeli/AP_BLHeli.cpp

Currently invalid erpm values from bi-directional dshot (0xFFFF) will be logged as very large numbers. We expect to get back some number of errors and the errors are always ignored by subsystems interested in the data so this PR makes sure we don't log the scary values thus preventing user confusion.
Tested on a BeastH7

Don't log invalid bi-directional dshot values as they are never used

---

libraries/AP_HAL/examples/Printf/Printf.cpp

Added improvements to the Printf example sketch as suggested [here](https://ardupilot.org/dev/docs/learning-ardupilot-the-example-sketches.html#rough-example-code). Thank you

AP_HAL:examples:Printf: Improvements in the Printf  example

---

AntennaTracker/system.cpp
ArduCopter/Copter.h
ArduPlane/Plane.h
ArduSub/Sub.h
Rover/Rover.h
libraries/AP_Vehicle/AP_Vehicle.h

Alternative to https://github.com/ArduPilot/ardupilot/pull/16463

move control_mode_reason up to AP_Vehicle

---

libraries/AP_CANManager/AP_CANTester.cpp
libraries/AP_GPS/AP_GPS_UBLOX.cpp
libraries/AP_HAL/Device.h
libraries/AP_TempCalibration/AP_TempCalibration.cpp
libraries/SITL/SIM_FlightAxis.cpp

Deleting a null pointer has no effect.

Remove pointer check before delete

---

libraries/AP_Notify/AP_Notify.cpp

This may be copy and paste issue.
I changed the description.

AP_Notify: modify NTF_BUZZ_VOLUME description

---

libraries/AP_Scripting/examples/relay_control.lua

Scripting: simple relay example

---

Tools/autotest/common.py

This should resolve an intermittent failure we're seeing in SITL; @yaapu and I believe the vehicle may be inching forward during the test....

autotest: don't run frsky tests armed for the most part

---

Tools/autotest/examples.py
libraries/AP_Vehicle/AP_Vehicle.h

put FlashTest on example skip list
fix virtual specifier on AP_Vehicle

Fix virtual specifier and example

---

Tools/autotest/common.py

Tools: autotest, common.py remove extra comma

---

ArduCopter/Copter.cpp

No idea whether this is allowed, but I thought I would try.

Copter: All men dream, but not equally.

---

Tools/vagrant/bashrc_git
Tools/vagrant/initvagrant-trusty64.sh
Tools/vagrant/initvagrant.sh

This .bashrc_git originally came from tridge.

Vagrant: augment bash when working in a git repository

---

libraries/AP_Baro/AP_Baro_MS5611.cpp

we were omitting the datasheet compensation for temperatures between -15 and -40C
and here is a graph of baro alt in meters with temperature:
over 14km change in alt at low temperatures. You really do need a heated baro at high altitudes

AP_Baro: added MS5611 baro compensation for -15 to -40C

---

.gitignore

@WickedShell maybe you have a reason why this is a bad idea? 
Maybe it just got overlooked.

gitignore: add scripting repl

---

libraries/AP_GPS/AP_GPS.h
libraries/AP_Hott_Telem/AP_Hott_Telem.cpp

See https://discuss.ardupilot.org/t/bug-in-ap-hott-telem-cpp-copter-4-0-4dev/53939/9

Increase number of fix type displayed via Hott telemetry

---

Tools/autotest/common.py

No actual memcheck bugs, just race condition fixes.

Fix Rover autotest to run under Valgrind

---

libraries/AP_Generator/AP_Generator_IE_650_800.cpp
libraries/AP_HAL_SITL/I2CDevice.cpp
libraries/AP_LandingGear/AP_LandingGear.cpp
libraries/AP_LeakDetector/AP_LeakDetector_Analog.cpp
libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
libraries/GCS_MAVLink/GCS_Common.cpp
libraries/SITL/SIM_Helicopter.cpp
libraries/SITL/SIM_SerialProximitySensor.cpp
libraries/SRV_Channel/SRV_Channel.h

Extract from https://github.com/ArduPilot/ardupilot/pull/16497 of the patches I think are good.

Simplify bool expression extraction

---

libraries/AP_HAL_ChibiOS/RCOutput.cpp

This fixes a bug in IOMCU output of oneshot and oneshot125

Oneshot on IOMCU

---

libraries/GCS_MAVLink/GCS_Common.cpp

```
// because MISSION_SET_CURRENT is a message not a command,
// there is not ACK associated with us successfully changing
// our waypoint.  Some GCSs use the fact we return exactly the
// same mission sequence number in this packet as an ACK - so
// if they send a MISSION_SET_CURRENT with seq number of 4
// then they expect to receive a MISSION_CURRENT message with
// exactly that sequence number in it, even if ArduPilot never
// actually holds that as a sequence number (e.g. packet.seq==0).
```

GCS_MAVlink: return identical seq in MISSION_CURRENT if possible after set

---

Tools/ardupilotwaf/embed.py

fixes bug introduced here https://github.com/ArduPilot/ardupilot/pull/16713 .

waf: need to crc the padded bootloaders before embedding

---

Tools/autotest/common.py

Tools:autotest\common.py fix text typo

---

libraries/AP_Mount/SoloGimbalEKF.cpp
libraries/AP_NavEKF/Models/GimbalEstimatorExample/GenerateEquations.m
libraries/AP_NavEKF/Models/GimbalEstimatorExample/calcMagAng.m
libraries/AP_NavEKF2/AP_NavEKF2.cpp
libraries/AP_NavEKF2/AP_NavEKF2_MagFusion.cpp
libraries/AP_NavEKF2/AP_NavEKF2_core.h
libraries/AP_NavEKF3/AP_NavEKF3.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.h

I think magentic is a misnomer.
I'll change it to magnetic.

AP_NavEKFx/AP_Mount:  Change misnomer (NFC)

---

ArduCopter/mode.h
ArduCopter/mode_guided.cpp

fix #16806, most code copied from #16796 (thanks @rmackay9)
tested on mro pixracer pro, indoor with motion capture system

Copter: send mission_item_reached in guided

---

libraries/AP_OSD/AP_OSD.cpp
libraries/AP_OSD/AP_OSD.h
libraries/AP_OSD/AP_OSD_Screen.cpp

User requested this...Alex is working on adding it to the Frsky telem also

AP_OSD: Add height above terrain panel and warning

---

Tools/autotest/arduplane.py
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp
libraries/GCS_MAVLink/ap_message.h

https://discuss.ardupilot.org/t/can-not-receive-message-attitude-quaternion-using-pymavlink/68219/4

add support for ATTITUDE_QUATERNION

---

ArduPlane/Parameters.cpp

This affects the target pitch, not the elevator directly.
https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/Attitude.cpp#L126

ArduPlane: Correct description of KFF_THR2PTCH parameter.

---

libraries/AP_NavEKF2/AP_NavEKF2.cpp
libraries/AP_NavEKF3/AP_NavEKF3.cpp

I would change ACCE to ACCESS from Processing.

AP_NavEKFx: Change misnomer(NFC)

---

Tools/autotest/arduplane.py
Tools/autotest/common.py

Patch is messy but we basically just try to get messages that are close-in-time

Fix for attitude quaternion test

---

libraries/AC_AttitudeControl/AC_AttitudeControl.h
libraries/AC_AttitudeControl/AC_PosControl.cpp

This implements two todo's from the position controller, this should remove the issue seen on TVBS takeoff when there is a very large pitch angle error.
https://github.com/ArduPilot/ardupilot/pull/16134

AC_PosControl: init with target attitude not actual

---

Tools/autotest/arduplane.py

This PR fixes a flaky autotest.

Fix the climb-before-turn autotest

---

Tools/autotest/common.py

Remove commented code, add more to the verbose option

autotest: tidy set_parameters

---

libraries/AP_Mission/AP_Mission.cpp

I found a discrepancy between the processing and the description.
I changed the description.

AP_Mission: Change the description(NFC)

---

Tools/autotest/arducopter.py

We can't tell if it worked until we're running in auto mode.

autotest: fix fly_square mission

---

Tools/scripts/run-coverage.sh
Tools/scripts/update-coverage.sh

This allow to manually run some build with coverage option and update the coverage database

Tools: split coverage script for easier update

---

Tools/autotest/common.py
libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.cpp
libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.h

This adds a new frame 0x500B with height above terrain, it's sent only when terrain is enabled.

AP_Frsky_Telem: added passthrough frame 0x500B with height above terrain

---

libraries/AP_NavEKF/Models/AttErrVecMathExample/FuseMagnetometer.m
libraries/AP_NavEKF/Models/AttErrVecMathExample/FuseVelocity.m
libraries/AP_NavEKF/Models/GimbalEstimatorExample/FuseMagnetometer.m
libraries/AP_NavEKF/Models/GimbalEstimatorExample/FuseVelocity.m
libraries/AP_NavEKF2/AP_NavEKF2_AirDataFusion.cpp
libraries/AP_NavEKF2/AP_NavEKF2_MagFusion.cpp
libraries/AP_NavEKF2/AP_NavEKF2_OptFlowFusion.cpp
libraries/AP_NavEKF2/AP_NavEKF2_PosVelFusion.cpp
libraries/AP_NavEKF2/AP_NavEKF2_RngBcnFusion.cpp

I would change "This is is" to "This is".

AP_NavEKFx:  Change misnomer(NFC)

---

libraries/AP_NavEKF3/AP_NavEKF3.cpp
libraries/AP_NavEKF3/AP_NavEKF3.h
libraries/AP_NavEKF3/AP_NavEKF3_AirDataFusion.cpp
libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp
libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
libraries/AP_NavEKF3/AP_NavEKF3_OptFlowFusion.cpp
libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp
libraries/AP_NavEKF3/AP_NavEKF3_RngBcnFusion.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.h
libraries/AP_NavEKF3/LogStructure.h

This PR is a continuation of https://github.com/ArduPilot/ardupilot/pull/6466 and fixes the issues logged by https://github.com/ArduPilot/ardupilot/issues/16791 and https://github.com/ArduPilot/ardupilot/issues/16094.
It fixes an issue created when the vehicle is on ground not moving and the combination of aiding sensor update rate and reported observation accuracy can cause state variances to reduce to a level where the covariance matrix processing numerical errors dominate.
These changes have been tested using replay of https://1drv.ms/u/s!AunBK4rE1ZDCg_MeCKOBMYL9W4UIEQ?e=3b6oRq
Before:
Source log and replay show Z axis delta velocity variance collapses:
Source log and replay show vertical position innovation diverging after variances collapse:
Source log and replay show vertical …

EKF3: Fix covariance matrix stability issues

---

Tools/autotest/common.py
libraries/AP_Logger/AP_Logger.h
libraries/AP_Logger/AP_Logger_Backend.cpp
libraries/AP_Logger/AP_Logger_MAVLinkLogTransfer.cpp

Closes https://github.com/ArduPilot/ardupilot/issues/13353

Stop creating many files when disarmed and doing log transfers

---

libraries/AP_OpticalFlow/AP_OpticalFlow_CXOF.cpp
libraries/AP_OpticalFlow/AP_OpticalFlow_UPFLOW.cpp
libraries/AP_OpticalFlow/AP_OpticalFlow_UPFLOW.h
libraries/AP_OpticalFlow/OpticalFlow.cpp
libraries/AP_OpticalFlow/OpticalFlow.h

Add a new optical flow sensor. (The UPFLOW sensor)
It's widely used among hobbyists in China.
It's also available on Aliexpress with the name "LC-302-3C".
It's a sensor using SerialProtocol.
For more info on this sensor:
https://discuss.ardupilot.org/t/cheerson-cx-of-low-cost-optical-flow-sensor-testing/35598/83
https://www.aliexpress.com/item/32969297064.html?spm=a2g0o.productlist.0.0.7e736ba7fkeO27&algo_pvid=53b87016-4503-4819-b309-e990e315a3ce&algo_expid=53b87016-4503-4819-b309-e990e315a3ce-4&btsid=0bb47a2216155643963414074ecf0a&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_
The following sites are in Chinese, please use a translator.
https://item.taobao.com/item.htm?spm=a230r.1.14.33.2db55d17LeQSi1&id=592153127363&ns=1&abbucket=18#detail
Official Site: …

Add a new optical flow sensor(UP-FLOW)

---

libraries/AP_Logger/AP_Logger_File.cpp

Intended to solve issues we're now getting on CI where the IO thread is
blocking-on-write and the main thread is calling it dead.

AP_Logger: multiply IO thread timeout according to SITL speedup

---

Tools/autotest/common.py

Check would appear to be inverted.

autotest: correct pexpect handling of supplementary programs

---

libraries/AP_Airspeed/AP_Airspeed.cpp
libraries/AP_Airspeed/AP_Airspeed.h
libraries/AP_Airspeed/AP_Airspeed_ASP5033.cpp
libraries/AP_Airspeed/AP_Airspeed_ASP5033.h

modified Who am I check, add Sensor confirm function and double IIC addresses check.

AP_Airspeed: add support ASP5033 airspeed sensor

---

Rover/mode.cpp

change norm_input to norm_input_dz

Rover: use deadzone in 2-paddle steering

---

Tools/autotest/arduplane.py

We get a long way from home...

autotest: increase allowed time for climb_before_turn to get home

---

Tools/autotest/arducopter.py

Reproduces https://github.com/ArduPilot/ardupilot/issues/14236

autotest: add test for copter position reset

---

ArduCopter/land_detector.cpp

It fix building errors when LANDING_GEAR_ENABLED is disabled

Copter: fix build error when landinggear disabled

---

Rover/release-notes.txt

This PR includes the release notes and version update for Rover-4.1.0-beta1 release.  I'm raising it as a PR to allow other developers to review the list and highlight anything I've missed.
All feedback welcome!

Rover: 4.1.0-beta1 release notes and version update

---

Rover/release-notes.txt

This PR is NFC to fixup some spelling errors.

Rover: minor fix to release notes

---

libraries/AP_Scripting/examples/LED_poslight.lua

This is an example to use LUA for LED position lights. If the vehicle is disarmed the left strip will light up red the right one green. When the vehicle is armed, the LEDs will change between red / green and white flashing.

AP_Scripting: add position light example

---

ArduPlane/quadplane.cpp
ArduPlane/tailsitter.cpp

Does what it says on the tin, rather than just not trying we now transition to and from inverted flight correctly.

Plane: tailsitter: transition to and from inverted flight

---

Tools/scripts/build_ci.sh
libraries/AP_HAL_ChibiOS/AnalogIn.cpp

needed to cope with ADCv3 MCUs
ping @pkocmoud

ChibiOS: fixed build of G4 firmware

---

libraries/AP_GPS/AP_GPS_NMEA.cpp
libraries/AP_GPS/AP_GPS_NMEA.h
libraries/AP_HAL_SITL/sitl_gps.cpp
libraries/SITL/SITL.cpp
libraries/SITL/SITL.h

Add support for NMEA THS message, which is basically the same as HDT but with a data qualifier.

AP_GPS: Add NMEA THS message.

---

ArduCopter/ReleaseNotes.txt

Copter-4.1.0-beta release notes
I'm raising as a PR in order to get input from all the various devs because I'm sure I've forgotten some items.
Thanks for your help!

Copter: 4.1.0-beta1 release notes

---

libraries/AP_Logger/AP_Logger.cpp

See
https://github.com/ArduPilot/ardupilot/issues/15916#issuecomment-819489618

AP_Logger: raise log_io stack size

---

libraries/AP_HAL_ChibiOS/SPIDevice.cpp

we were only checking this when asserts were enabled, which doesn't help for rarely used devices. 
also remove the printf, which just costs flash and never really helps

HAL_ChibiOS: check bus owner on all SPI transfers

---

Tools/autotest/common.py

https://discuss.ardupilot.org/t/rover-4-1-0-beta1-released/69868/7

autotest: add a test for button change for changing modes

---

libraries/AC_AttitudeControl/AC_AttitudeControl.cpp

Cherry-picked from larger PR and commit message fixed.
Thanks to BreederBai for higlighting this in issue #17059
Thanks to esaldiran and Hs293Go for helping check the math.

AC_AttitudeControl: Fix Angular velocity rotation to body frame

---

libraries/AP_Math/quaternion.cpp
libraries/AP_Math/quaternion.h
libraries/AP_Math/tests/test_quaternion.cpp

Extracted from https://github.com/ArduPilot/ardupilot/pull/17209
The tests here are worth a separate PR, and the new function will be used soon-enough.

Quat Tests and new *(Vector3f) operator

---

Tools/AP_Periph/Parameters.cpp

Follow-up for https://github.com/ArduPilot/ardupilot_wiki/pull/3448

AP_Periph: populate the param meta data for the wiki

---

libraries/AP_VideoTX/AP_SmartAudio.cpp

On some VTX's the free stack is not quite enough
https://discuss.ardupilot.org/t/is-there-a-way-to-get-smartaudio-working/29025/97

Increase stack for smart audio thread

---

Tools/autotest/common.py

autotest: correct string we expect from MAVProxy

---

Tools/autotest/arducopter.py
Tools/autotest/common.py

Mkaes it easier to find last login output.
Also removing pointless lamdaing of some functions

autotest: sort logs before moving

---

libraries/SITL/SIM_Aircraft.cpp
libraries/SITL/SIM_Aircraft.h
libraries/SITL/SIM_Precland.cpp
libraries/SITL/SIM_Precland.h

This allow to change SITL ground level from sensor like precland.

Allow to pass local ground level from sensor

---

Tools/environment_install/install-prereqs-ubuntu.sh

That PR adds Ubuntu 21.04 Hirsute Hippo to environment setup script.

Tools: add Ubuntu 21.04 to environment setup script

---

libraries/AC_AutoTune/AC_AutoTune.cpp

autotest: shorten statustext message to avoid chunking

---

libraries/RC_Channel/RC_Channel.cpp

Leftover from https://github.com/ArduPilot/ardupilot/pull/17287

RC_Channel: log init_aux_function and read_aux

---

Vagrantfile

Vagrant: add hirsute and hirsute-desktop

---

Tools/autotest/arducopter.py

These tests were being retried internally *and* externally.  Double the
outside loop and stop retrying internally.
Took the use set_parameters

autotest: remove retry loops from FFT tests

---

ArduCopter/GCS_Mavlink.cpp
ArduPlane/GCS_Mavlink.cpp
Blimp/GCS_Mavlink.cpp
Rover/GCS_Mavlink.cpp

Rework from https://github.com/ArduPilot/ardupilot/pull/15986
close https://github.com/ArduPilot/ardupilot/pull/15986
This is cover by autotest

USE Mavlink typemask

---

Tools/autotest/arducopter.py

Co-Authored-By: leonardthall@gmail.com
There was one maths line correct in the original test.  The rest almost cancelled each other out.

autotest: fix loiter_to_ne

---

Tools/AP_Bootloader/board_types.txt

add two new horizon31.com boards

---

Tools/autotest/common.py
Tools/autotest/rover.py

Also slip in a change to add accuracy to guided_achieve_heading

autotest: Move script helper functions up from rover to common

---

Tools/autotest/param_metadata/param_parse.py

This appears to fix many bugs in our Wiki documentation:
tracker doesn't do RC options:
https://ardupilot.org/antennatracker/docs/parameters.html#rc10-parameters
Copter doesn't do `FENCE_AUTOENABLE`:
https://ardupilot.org/copter/docs/parameters.html#fence-autoenable-fence-auto-enable
This is a huge delta in Parameter.rst - but everything I've looked at so far seems to correct according to the metadata.

Fix vehicle-specific parameter values in Wiki

---

README.md

Made some changes in the introduction. Changes include removal of unnecessary comma and correcting the spelling mistakes.

Plane: changes in Ardupilot Project introduction

---

libraries/AP_Camera/AP_RunCam.cpp

Wrong comment: stop -> start
(still learning how to work with git..) :)

AP_Camera: Fix wrong comment in libraries/AP_Camera/AP_RunCam.cpp

---

libraries/AP_CANManager/AP_SLCANIface.cpp
libraries/AP_CANManager/AP_SLCANIface.h

I will delete the unused methods

AP_CANManager: Delete unused methods

---

ArduCopter/Parameters.cpp
ArduPlane/quadplane.cpp
ArduSub/Parameters.cpp
Blimp/Parameters.cpp
libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
libraries/AC_Avoidance/AC_Avoid.cpp
libraries/APM_Control/AP_SteerController.cpp
libraries/AP_Mount/AP_Mount.cpp
libraries/AP_OpticalFlow/OpticalFlow.cpp

This is on top of what Basti did in #14741

Various files: make cdeg metadata consistent and incr 10

---

libraries/AP_RangeFinder/AP_RangeFinder_HC_SR04.cpp
libraries/SITL/SIM_Temperature_TSYS01.cpp

These bugs were detected while compiling using clang-12.

Fix use of labs() on subtraction of unsigned values which are always positive

---

ArduCopter/Copter.h
ArduCopter/sensors.cpp
ArduCopter/system.cpp
ArduSub/Sub.h
ArduSub/sensors.cpp
ArduSub/system.cpp
Blimp/Blimp.h

Just makes the code and binary larger.

Remove init_optflow wrapper functions

---

Tools/autotest/arducopter.py

(used `--force-ahrs-type=2` to autotest to get this:)
```
Thread 1 "arducopter" received signal SIGFPE, Arithmetic exception.
0x00005555558ac66a in NavEKF2_core::FuseOptFlow (this=0x555555c4cf40) at ../../libraries/AP_NavEKF2/AP_NavEKF2_OptFlowFusion.cpp:292
292         SH_LOS[3] = 1/(pd - ptd);
(gdb) print pd
$1 = <optimised out>
```
Also dies in EKF3.

autotest: add test to catch bug with opticalflow if no rangefinder

---

Tools/ardupilotwaf/boards.py
Tools/autotest/autotest.py
Tools/autotest/pysim/util.py
Tools/scripts/run_coverage.py
wscript

Add more unittests for math.cpp to reach 100% coverage
Add some correction to run_coverage.py to try to cope with the Blocking error : disable correctly examples, enforce blocking write, disable verbose mode by default

Coverage improvements

---

libraries/AP_HAL_ChibiOS/UARTDriver.cpp

this fixes a problem with the automatic DMA disable on DMA contention
in UARTs. This fixes issue #14581
the problem was that while tx_dma_enabled was correctly set to false,
it would keep looping inside write_pending_bytes_DMA() if the data
arrived in the write buffer at a faster rate than it could be sent
out, which did happen with a mavlink stream rate of 4Hz. This means it
kept using DMA even with tx_dma_enabled set to false. The result was
that the automatic flow control code never got a chance to run and we
didn't switch back to non-DMA for these low baudrate contended UARTs

HAL_ChibiOS: fixed DMA disable on contention

---

Tools/autotest/arducopter.py
libraries/AP_NavEKF3/AP_NavEKF3.cpp
libraries/AP_NavEKF3/AP_NavEKF3.h
libraries/AP_NavEKF3/AP_NavEKF3_Logging.cpp
libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp

Not used after we moved logging to be within AP_NavEKF3
Saves 52 bytes of flash on Plane / CubeBlack.

AP_NavEKF3: remove getBodyFrameOdomDebug

---

Tools/autotest/arducopter.py
Tools/autotest/default_params/copter-hexa-cwx.parm
Tools/autotest/default_params/copter-hexa-dji.parm
Tools/autotest/default_params/copter-octaquad-cwx.parm
Tools/autotest/pysim/vehicleinfo.py

provided a solution for some of the frames listed here #17318.
Thanks !!

autotest:Copter test fix for some frames

---

ArduCopter/Log.cpp

match https://github.com/ArduPilot/ardupilot/blob/16ba99149b495db68836dc464bbcfe5cc8b8b8be/ArduCopter/Log.cpp#L385

Copter: fix build problem when log disabled

---

libraries/AC_WPNav/AC_WPNav.cpp

The parameter `wp_radius_cm` is checked in `AP_WPNav's` constructor, but the parameters get loaded after the constructor. If `WPNAV_RADIUS`  is less than `WPNAV_WP_RADIUS_MIN`, you can end up in a situation where getting to the current waypoint is never registered even if we are within `WPNAV_WP_RADIUS_MIN`.
Also can happen if you update the parameters for example using mavproxy.
To replicate set WPNAV_RADIUS to 0. Most apparent when OA is enabled or upon landing.

AC_WPNav: ensure parameters meet original constraints

---

libraries/AP_Camera/AP_RunCam.cpp
libraries/AP_Camera/AP_RunCam.h

This adds RunCam hybrid as a RunCam type and makes sure the (very small) set of menu options are observed properly

Support RunCam Hybrid correctly

---

Tools/scripts/build_binaries.py

It should be available for release soon.

Tools: Add navigator board in common boards

---

ArduPlane/quadplane.cpp
ArduPlane/quadplane.h
libraries/AP_Math/vector3.cpp
libraries/AP_Math/vector3.h

this fixes the backflip issue on the convergence that Henry found

Plane: fixed issue with overspeed in QPOS_POSITIION1

---

ArduPlane/mode_rtl.cpp
ArduPlane/quadplane.cpp
ArduPlane/quadplane.h
libraries/AP_Vehicle/ModeReason.h

Now that we have QRTL with fixed wing approach, this can be a valid FS/RTL mode for quadplanes
SITL tested

Add Q_RTL_MODE option to alwasy QRTL

---

libraries/AP_HAL_ChibiOS/SPIDevice.cpp

len is 32 bits; i may integer-wrap back to zero at 65535+1

AP_HAL_ChibiOS: fix infinite loop for large SPI transfers

---

README.md

no gitter activity in ~6 months

readme: change wiki discussion link from gitter to discord

---

ArduPlane/Parameters.cpp
ArduPlane/Parameters.h
ArduPlane/defines.h
ArduPlane/reverse_thrust.cpp

Plane: Add options to USE_REVERSE_THRUST to cover all flight modes

---

libraries/AP_OSD/AP_OSD_Screen.cpp
libraries/AP_VideoTX/AP_SmartAudio.cpp
libraries/AP_VideoTX/AP_SmartAudio.h
libraries/AP_VideoTX/AP_VideoTX.cpp
libraries/AP_VideoTX/AP_VideoTX.h

Main changes
1)blinks the OSD power element if VTX is not configured correctly
2)Improvements in CGS message adding band names and making the message clearer.
3)Pulls down the serial port before transmitting, which fixes flaky communication with VTXes

SmartAudio improvements

---

libraries/SITL/examples/follow-copter.sh

Another copy of this script -  but this one doesn't need Morse or AirSim

Tools: add follow-copter.sh for SITL

---

Tools/autotest/arducopter.py

Also looks at last result as we don't appear to have a consistent number
in our tests

autotest: improve diagnostics around touchdown/takeoff expected tests
