Tools/autotest/autotest.py, libraries/AP_Common/tests/test_ap_common.cpp, libraries/AP_Common/tests/test_expandingstring.cpp, libraries/AP_Common/tests/test_location.cpp, libraries/AP_Common/tests/test_tsindex.cpp
Add some more unit test for AP_Common
needs https://github.com/ArduPilot/ardupilot/pull/17720
=> Unittest: AP_Common

libraries/AP_Motors/AP_MotorsMulticopter.cpp
The two figures below show the results of the two equations that convert expo to and from pwm and thrust. This shows the valid range of -1 to +1.
I have users that require this whole range to be available.
=> AP_Motors: correct expo parameter description and internal limits

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_HAL/RCOutput.h, libraries/AP_HAL_ChibiOS/RCOutput.cpp, libraries/AP_HAL_ChibiOS/RCOutput.h, libraries/AP_HAL_ChibiOS/RCOutput_serial.cpp, libraries/SRV_Channel/SRV_Channel_aux.cpp
This is an alternative to https://github.com/ArduPilot/ardupilot/pull/17731 that sends required shot commands at 1Hz until arming as per @rmackay9 's request
=> Update dshot commands at 1hz

Tools/autotest/autotest.py
=> autotest: revert to subprocess.check_call

libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_AttitudeControl/AC_PosControl.h
=> AC_AttitudeControl:AC_PosControl: vibration failsafe fix

Tools/autotest/arduplane.py, libraries/AP_Airspeed/AP_Airspeed.cpp, libraries/AP_Airspeed/AP_Airspeed.h, libraries/RC_Channel/RC_Channel.cpp, libraries/RC_Channel/RC_Channel.h
=> Airspeed disable on-a-switch

Tools/autotest/arducopter.py
This autotest will hopefully ensure that the vibration failsafe remains operational.
The test does the following:
1. takes off in Loiter to 20m
2. sets the simulated accelerometer biases to 2m/s/s to simulate a high vibration environment
3. waits for the "Vibration compensation ON" message to appear
4. waits for the vehicle to switch to LAND mode (as part of the EKF failsafe)
5. waits up to 30 seconds for the vehicle to descend to 2m
This has been tested in SITL and I confirmed that it passed with master but failed if PR https://github.com/ArduPilot/ardupilot/pull/17837 was reverted.
=> Tools: autotest of vibration failsafe

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
```
Target         Text    Data  BSS     Total  
--------------------------------------------
bin/arduplane  955440  1900  129256  1086596
Target         Text    Data  BSS     Total  
--------------------------------------------
bin/arduplane  943896  1900  129256  1075052
```
saves 11.5KB
=> AP_HAL_ChibiOS: remove bl embed in MatekF405-Wing

libraries/AC_AttitudeControl/AC_PosControl.cpp
This PR fixes the Loiter wobble issue and number of small problems with the initialisation and stopping point calculation of the position controller.
Specifically:
Initialisation of the XY controller to ensure the target acceleration matches the roll and pitch.
Correcting the vertical stopping point calculation by setting the desired velocity to zero before the calculation is made,
Correcting the XY relax function to decay the output acceleration and therefore lean angle to zero.
=> Copter: loiter wobble fix

Tools/autotest/common.py
No idea why this is so hard to set, but it failed in CI...
=> Increase number of attempts to set parameters

Tools/autotest/arducopter.py
This new autotest checks if the vehicle twitches after a longer term (e.g. > 7 second) GPS glitch is applied.  In these cases the position controller should consume the EKF position reset and adjust the targets so that the vehicle's attitude remains stable.
The test is:
- takeoff in Loiter and wait for the roll and pitch attitude to reach nearly zero
- apply a GPS glitch of about 100m
- check the roll and pitch angles remain within 2deg for 20 seconds
- revert  the GPS glitch and RTL
This is quite different from the existing GPS Loiter autotest that ensures the vehicle does not move by more than 20m.  The existing test was not enough to catch a bug that was recently fixed by PR https://github.com/ArduPilot/ardupilot/pull/17850
This has been tested to ensure that it fails when the above PR …
=> Tools: add copter gps_glitch_loiter_test2

Tools/scripts/firmware_version_decoder.py
- Adds shebang
- Allow file execution
=> Tools: Allow direct execution of firmware_version_decoder.py from command line

libraries/AP_Common/Location.h, libraries/AP_Math/definitions.h
This fixes the problem with inaccurate waypoint missions over distances of 10s of km. The problem turned out to be inconsistent constants between Location.cpp and definitions.h, which impacted the setting of the destination in AC_WPNav.
This is what caused the following issues:
- flying missions offset from the target waypoints, with the offset based on the distance from origin
- inability to complete an auto takeoff when a long distance from the origin
=> Copter: fixed inaccurate waypoint missions

ArduCopter/Attitude.cpp, ArduCopter/Copter.h
Hi,
I have just started to contribute to open source. Yesterday, I created a pull request for the same thing but there I forgot to squash few of my commits into one, and when asked, while squashing them I got few conflicts and that messed up the things. Hence, I closed that PR and here is my fresh PR with a single commit. I've tried keeping things mentioned in contributing documentation (like rebasing etc.) in mind. I hope I did it correctly this time.
=> ArduCopter : added and fixed few comments

ArduCopter/ReleaseNotes.txt
Release notes for Copter-4.1.0-beta5.  All input welcome!
=> Copter: 4.1.0-beta5 release notes

Rover/release-notes.txt
Release notes for Rover-4.1.0-beta5. All input welcome!
=> Rover: 4.1.0-beta5 release notes

.github/workflows/macos_build.yml, Tools/environment_install/install-prereqs-mac.sh
Also adds the test for the same in CI
=> Update Install Prerequisites script for macos

Tools/ardupilotwaf/chibios.py, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py, wscript
Part of GSOC project to enable custom hwdef options
=> Added --extra-hwdef option

libraries/AP_Soaring/AP_Soaring.cpp, libraries/AP_Soaring/AP_Soaring.h, libraries/AP_Soaring/Variometer.cpp, libraries/AP_Soaring/Variometer.h
- Convert in-line filters to LowPassFilter instances
- Rename variables and cleanup access
=> AP_Soaring: Vario filter cleanup

libraries/AP_Notify/Display.h
=> Re-enable display on 1Mb boards

Tools/autotest/common.py
~~Current passes on Copter but fails on Plane~~
Now based on tridge's fix for the problem
=> Add test that we get a log if arming is forced

ArduPlane/tuning.cpp, ArduPlane/tuning.h
this is wip, will formalize and add others once I get this working
=> Add FF tuning items for Quadplane TX tuning

libraries/AP_Landing/AP_Landing.cpp, libraries/AP_Landing/AP_Landing.h, libraries/AP_Landing/AP_Landing_Deepstall.cpp, libraries/AP_Landing/AP_Landing_Deepstall.h
Saves ~5.5kB
This library really needs a proper frontend/backend split.
=> AP_Landing: enable deepstall landing to be compiled out of the code

Tools/autotest/arducopter.py
This adds a new autotest.
It arms the vehicle in throw mode, then lifts the vehicle gently to ~100m - and then drops it.  It checks we go through the throw mode stages and that we eventually have zero velocity.  It then switches to alt-hold mode and lands the vehicle.
It then sets "throw nextmode" to auto, loads a mission and repeats the drop procedure.  It then waits for the vehicle to disarm at the end of the mission.
It completes all of that successfully, but there appear to be several problems with the way the vehicle is being controlled.
This autotest can be run with
`./Tools/autotest/autotest.py --gdb --debug build.Copter test.Copter.ThrowDoubleDrop`
=> autotest: add test for two consecutive drops with no reboot

.github/workflows/test_sitl_copter.yml, .github/workflows/test_sitl_plane.yml, .github/workflows/test_sitl_rover.yml, .github/workflows/test_sitl_sub.yml, .github/workflows/test_sitl_tracker.yml, Tools/autotest/autotest.py, Tools/autotest/common.py, Tools/scripts/dumpcore.sh, libraries/AP_HAL/system.cpp, libraries/AP_HAL/system.h, libraries/AP_HAL_SITL/SITL_cmdline.cpp, libraries/AP_HAL_SITL/system.cpp
Also retain the files after an autotest run
=> Dump core for ArduPilot on panic/segfault/fpe

AntennaTracker/GCS_Mavlink.cpp, ArduCopter/GCS_Mavlink.cpp, ArduSub/GCS_Mavlink.cpp, Blimp/GCS_Mavlink.cpp
These haven't been relevant for a long time.
=> Remove noinline comments

libraries/AP_HAL/UARTDriver.h, libraries/AP_HAL_ChibiOS/UARTDriver.cpp, libraries/AP_HAL_ChibiOS/UARTDriver.h
This is for the RS-485 boat motor driver @rmackay9 is writing
=> Added set_RTS_PIN() and set_CTS_pin() for UARTs

Tools/autotest/sim_vehicle.py
this makes running with high speedups easier
=> autotest: added --udp option to sim_vehicle.py

libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp
Discussion: https://discuss.ardupilot.org/t/passthrough-telemetry-over-crsf-crossfire/62668/755
@rmackay9 this will need to go in 4.1
=> Correct firmware string length for CRSF

Tools/autotest/arducopter.py
Change takeoff to be in Loiter as we need the loiter controler to do precland correctly
=> Tools: autotest: add IRLock SITL test

ArduCopter/mode.h, ArduCopter/mode_auto.cpp, ArduCopter/mode_follow.cpp, ArduCopter/mode_guided.cpp, ArduCopter/mode_rtl.cpp, ArduCopter/mode_smart_rtl.cpp
marks get_wp() const. A drive by on my way to add get_wp() to sub
=> ArduCopter: mark get_wp() const

Tools/AP_Bootloader/support.cpp, Tools/ardupilotwaf/boards.py, Tools/ardupilotwaf/chibios.py, libraries/AP_BLHeli/AP_BLHeli.cpp, libraries/AP_CANManager/AP_CANTester_KDECAN.cpp, libraries/AP_EFI/AP_EFI_NWPMU.cpp, libraries/AP_HAL/utility/RingBuffer.h
There are some cast-align disable flags being added globally for many builds. Probably not a good idea.
=> Remove cast-align disable flags

Tools/autotest/autotest.py, Tools/autotest/common.py
make for easy creation of EKF replay logs
ping @priseborough
=> autotest: added --replay option to autotest

ArduCopter/mode.h, ArduCopter/mode_guided.cpp, libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_AttitudeControl/AC_PosControl.h, libraries/AC_WPNav/AC_WPNav.h
=> Provide the Crosstrack reporting for mavlink message

ArduCopter/Copter.h, ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduCopter/mode_guided.cpp, ArduCopter/terrain.cpp, libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_AttitudeControl/AC_PosControl.h, libraries/AC_WPNav/AC_WPNav.cpp, libraries/AC_WPNav/AC_WPNav.h
This PR adapts the terrain follow algorithm used in Guided mode to Auto Mode. This slows the forward progress if the height moves outside the buffer zone.
=> Copter: fix auto terrain following

libraries/AP_LeakDetector/AP_LeakDetector.cpp
follow-up to 397def7b9e71efe56ca95a69a7b0e5fecb85e763
=> AP_LeakDetector: update leak pin for navigator r3 in metadata

libraries/AP_BLHeli/AP_BLHeli.cpp
Discussion: https://discuss.ardupilot.org/t/help-about-using-dshot-on-tail-rotor/73269/20
Flown in my office on a 3" quad - still getting telemetry
=> Ensure correct rotation through telemetry ESCs

Tools/Replay/check_replay.py
useful for finding what has diverged. Also useful for stm32 <-> SITL testing
ping @priseborough
=> Replay: added --accuracy option

ArduPlane/Plane.h, Rover/Parameters.cpp, libraries/APM_Control/AP_PitchController.cpp, libraries/APM_Control/AP_PitchController.h, libraries/APM_Control/AP_RollController.cpp, libraries/APM_Control/AP_RollController.h, libraries/APM_Control/AP_SteerController.cpp, libraries/APM_Control/AP_SteerController.h, libraries/APM_Control/AP_YawController.cpp, libraries/APM_Control/AP_YawController.h, libraries/APM_Control/AR_AttitudeControl.cpp, libraries/APM_Control/AR_AttitudeControl.h
Use the singleton accessor for what it is good for
=> Stop taking references to AHRS in APM_Control

libraries/SITL/SIM_Aircraft.cpp
=> SITL: added SIM2 message

libraries/AP_AHRS/AP_AHRS_Backend.h, libraries/AP_AHRS/AP_AHRS_DCM.cpp, libraries/AP_AHRS/AP_AHRS_DCM.h, libraries/AP_AHRS/AP_AHRS_View.h
- init where we declare variables
- stop making a variable for something that is constant
=> Tidy AHRS init

Rover/release-notes.txt
Release notes for Rover-4.1.0-beta6
all feedback greatly appreciated!
=> Rover: 4.1.0-beta6 release notes

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Button/AP_Button.cpp, libraries/AP_Button/AP_Button.h, libraries/AP_HAL_ChibiOS/GPIO.cpp
This fixes a bug found by @kris000 in the recent BRD_PWM_COUNT change, and adds an arming check for BTN_PINx
=> ChibiOS: fixed GPIO enable bug

libraries/AP_SerialManager/AP_SerialManager.cpp
Avoid protocol confusion with normal CRSF RC/Telem
=> AP_SerialManager: relabel protocol 29 to avoid confusion with CRSF RC

ArduPlane/quadplane.cpp
=> Plane: improve description of Q_TRIM_PITCH

libraries/AP_Scripting/generator/description/bindings.desc
=> AP_Scripting: add change alt frame method to location userdata

Tools/autotest/common.py
github action's CI is good at this
=> autotest: stop uploading artifacts to autotest server

ArduSub/ReleaseNotes.txt
=> Sub: update release notes for 4.0.3

libraries/AP_Motors/AP_MotorsTri.cpp
This allows MOT_PWM_TYPE to be used
=> Remove tri yaw servo from motor mask

ArduPlane/soaring.cpp, libraries/AP_Soaring/AP_Soaring.cpp, libraries/AP_Soaring/AP_Soaring.h
Avoid thermalling, suppressing throttle or overriding TECS speed weight during landing.
=> Plane: soaring: No action if in landing sequence.

ArduPlane/ArduPlane.cpp
Was accidently using meter/s instead of cm/s.
=> Plane: fix ADSB stall speed units. 

Tools/autotest/arducopter.py, Tools/autotest/arduplane.py, Tools/autotest/common.py
=> Use SIM_STATE rather than SIMSTATE in autotest

Tools/AP_Periph/can.cpp
libcanard does already convert scalars, but doesn't convert arrays. By
calling fix_float16 on scalers we were double converting, which
reduced resolution.
=> AP_Periph: fixed float16 conversions for scalars

libraries/AP_OSD/AP_OSD.cpp, libraries/AP_OSD/AP_OSD.h, libraries/AP_OSD/AP_OSD_Screen.cpp
per several requests from RCG users
=> AP_OSD: add option to convert to miles at 5280ft vs 10000ft

libraries/AP_Scripting/lua/src/lstring.c
make LUA memory panic message helpful
=> AP_Scripting: make LUA memory panic more helpful

libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp
=> AP_NavEKF3: fixed output LLH to account for IMU offset

ArduPlane/Plane.h, ArduPlane/RC_Channel.cpp, ArduPlane/system.cpp
Same as https://github.com/ArduPilot/ardupilot/pull/18209 but for plane. 
Notify buzzer on every mode change not just from RC aux switch.
=> Plane: notify buzzer on every mode change

ArduPlane/ArduPlane.cpp, ArduPlane/Log.cpp, ArduPlane/Parameters.cpp, ArduPlane/Plane.h, ArduPlane/defines.h
=> Plane: added option to log PIDs at full rate

Tools/ardupilotwaf/ap_library.py
this happens on custom build server when building into a new directory
=> waf: avoid problem with custom build server

Tools/autotest/common.py
A recent PR would have killed this.  Add a test so it gets picked up next time.
=> autotest: add test for FRSkyD battery

libraries/AP_ESC_Telem/AP_ESC_Telem.cpp, libraries/AP_ESC_Telem/AP_ESC_Telem.h
esc_index should be < to ESC_TELEM_MAX
=> Esc telem overrun fixs

libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp, libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
the first line removed is a assignement duplication.
The if condition is alsways false, and do exactly what we just do. So we could remove it
=> Fixs ekf unecessary assignement

libraries/AP_BattMonitor/AP_BattMonitor_MPPT_PacketDigital.cpp
MPPT sequence packet bug fix. Found by @khancyr . Closes https://github.com/ArduPilot/ardupilot/issues/18283
=> AP_BattMonitor: fix mppt sequence bug

Tools/autotest/arducopter.py, libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AP_AHRS/AP_AHRS_DCM.cpp, libraries/AP_AHRS/AP_AHRS_DCM.h, libraries/AP_AHRS/AP_AHRS_Logging.cpp, libraries/AP_AHRS/AP_AHRS_NavEKF.cpp, libraries/AP_AHRS/AP_AHRS_NavEKF.h
This is a 4.1.0 version of this PR:
https://github.com/ArduPilot/ardupilot/pull/18326
=> Plane4.1: allow quadplanes to fly on DCM if EKF unhealthy

ArduCopter/system.cpp, ArduPlane/system.cpp, ArduSub/system.cpp, Blimp/system.cpp, Rover/system.cpp, libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h, libraries/AP_AHRS/AP_AHRS_Backend.h, libraries/AP_DAL/AP_DAL.cpp
.... and renaming the enumeration while we're at it
There's only one of these per vehicle, so it is a frontend thing.
=> move VehicleClass handling to AHRS frontend

ArduPlane/mode_qacro.cpp, ArduPlane/mode_qautotune.cpp, ArduPlane/mode_qhover.cpp, ArduPlane/mode_qland.cpp, ArduPlane/mode_qloiter.cpp, ArduPlane/mode_qrtl.cpp, ArduPlane/mode_qstabilize.cpp, ArduPlane/quadplane.cpp
Follow up to https://github.com/ArduPilot/ardupilot/pull/18014
This is the hard to review moving of functions into there correct files. This is just a copy and paste job, there is no code change.
Done ontop of Master @ 0b0ca6a9e99e5f22621af1d0199f008ce1c786d0 need to check there are no changes come into master after that would get lost when this is merged.
=> Plane: Quadplane mode mode functions to mode files

ArduPlane/commands_logic.cpp, ArduPlane/system.cpp, libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h, libraries/AP_AHRS/AP_AHRS_Backend.h, libraries/AP_AHRS/AP_AHRS_DCM.cpp, libraries/AP_AHRS/AP_AHRS_DCM.h, libraries/AP_VisualOdom/AP_VisualOdom_IntelT265.cpp
Built on top of https://github.com/ArduPilot/ardupilot/pull/18300, which it would otherwise conflict with
=> Move wind estimation state to AHRS frontend

ArduPlane/quadplane.cpp, Tools/autotest/param_metadata/param_parse.py, Tools/autotest/param_metadata/rstemit.py, libraries/AP_EFI/AP_EFI.cpp, libraries/AP_FETtecOneWire/AP_FETtecOneWire.cpp, libraries/AP_ICEngine/AP_ICEngine.cpp, libraries/AP_NavEKF2/AP_NavEKF2.cpp, libraries/AP_NavEKF3/AP_NavEKF3.cpp
Cherry-picked from here: https://github.com/ArduPilot/ardupilot/pull/18160/files
Fixed one bad commit message.
=> Remove @RebootRequired / spelling and grammar fixes

libraries/AP_Math/quaternion.cpp, libraries/AP_Math/quaternion.h
Closes https://github.com/ArduPilot/ardupilot/issues/18359
=> AP_Math: correct descriptions of quaternion functions

libraries/AP_ADSB/AP_ADSB.cpp, libraries/AP_ADSB/AP_ADSB.h, libraries/AP_ADSB/AP_ADSB_uAvionix_MAVLink.cpp, libraries/AP_ADSB/AP_ADSB_uAvionix_UCP.cpp, libraries/AP_ADSB/AP_ADSB_uAvionix_UCP.h, libraries/AP_ADSB/GDL90_protocol/GDL90_Message_Structs.h, libraries/AP_ADSB/GDL90_protocol/hostGDL90Support.h, libraries/AP_Math/crc.cpp, libraries/AP_Math/crc.h, libraries/GCS_MAVLink/GCS_Common.cpp
Relies on https://github.com/ArduPilot/mavlink/pull/207.
=> ADSB: Ping200x driver w/ UCP Protocol

libraries/AP_FETtecOneWire/AP_FETtecOneWire.cpp, libraries/AP_FETtecOneWire/AP_FETtecOneWire.h
master compilation is broken on gcc 7.4.0 (cygwin windows)
This fixes that, and fixes some FETtec support issues in the process
=> FETtec fixes

ArduCopter/Copter.cpp, ArduCopter/Copter.h, ArduCopter/sensors.cpp, Blimp/Blimp.cpp, Blimp/Blimp.h, Blimp/sensors.cpp
Fixes #5062
Flight options is not a great place for this, but I don't think its worth adding a new options param just for this.
=> Copter/Blimp: remove stick gesture compass calibration start and stop

ArduPlane/config.h, ArduPlane/quadplane.cpp, ArduPlane/quadplane.h
…autolands
for use with systems like Swan Hwing when using throttle landing control option
also for use with gamepad style joysticks in MP control of quadplanes
SITL tested on Hwing
=> ArduPlane: add thr position trigger to ThrLandCtrl Q_OPTION

libraries/AP_Baro/AP_Baro.cpp, libraries/AP_Compass/AP_Compass.cpp, libraries/AP_InertialSensor/AP_InertialSensor.cpp
'A = B >= C' kind. The expression is calculated as following: 'A = (B >= C)'
=> Fixs EAHRS initilisation

libraries/AP_AHRS/AP_AHRS.cpp
... also, return perfect airspeed estimate from AHRS_EKF_TYPE 10
=> Constrain airspeed sensor data according to WIND_MAX

libraries/AP_WindVane/AP_WindVane_Airspeed.cpp, libraries/AP_WindVane/AP_WindVane_Airspeed.h, libraries/AP_WindVane/AP_WindVane_Home.cpp, libraries/AP_WindVane/AP_WindVane_Home.h, libraries/AP_WindVane/AP_WindVane_NMEA.cpp, libraries/AP_WindVane/AP_WindVane_NMEA.h, libraries/AP_WindVane/AP_WindVane_RPM.cpp, libraries/AP_WindVane/AP_WindVane_RPM.h, libraries/AP_WindVane/AP_WindVane_SITL.cpp, libraries/AP_WindVane/AP_WindVane_SITL.h
=> AP_WindVane: remove empty contructors

libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h
This can be used for other backends, too.
=> AP_AHRS: factor out an update_notify_from_filter_status

libraries/AP_BoardConfig/IMU_heater.cpp
Fixes https://github.com/ArduPilot/ardupilot/issues/13191
=> AP_BoardConfig: make sure heater is left off if disabled

libraries/AP_HAL_ChibiOS/RCOutput_serial.cpp
=> HAL_ChibiOS: fix for HAL_PWM_COUNT zero

ArduPlane/tailsitter.cpp, libraries/AP_HAL_ChibiOS/hwdef/Swan-K1/defaults.parm
raise priority of attitude control in fixed wing flight
=> HAL_ChibiOS: adjust Swan-K1 tuning

libraries/AP_ESC_Telem/AP_ESC_Telem.cpp, libraries/AP_ESC_Telem/LogStructure.h
Log raw RPM values as well as slewed values
=> Log raw RPM information

libraries/AP_Mount/AP_Mount.cpp
continuation of https://github.com/ArduPilot/ardupilot/pull/18147
updated to latest master
was called a "reasonable patch", but seems to got stuck :)
=> AP_Mount: initialize backends after all mounts were added #2

libraries/AP_NavEKF2/LogStructure.h, libraries/AP_NavEKF3/LogStructure.h
Courtesy Paul Riseborough here: https://github.com/ArduPilot/ardupilot_wiki/issues/3641#issuecomment-913577132
=> Improve description of innovation fields in NKF4/XKF4 

ArduPlane/Parameters.cpp, ArduPlane/Parameters.h
=> Plane: remove unused params

ArduCopter/crash_check.cpp, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.h, libraries/AP_Logger/AP_Logger.cpp, libraries/AP_Logger/AP_Logger.h
https://github.com/ArduPilot/ardupilot/pull/8836 https://github.com/ArduPilot/ardupilot/issues/8384
Love that we have both `TERRRAINFAILSAFE` and `TERRAINFAILSAFE` cant blame me for that one ;)
=> AP_Arming: force longer disarm logging for all nasty disarm reasons

Tools/autotest/arducopter.py, Tools/autotest/common.py, libraries/AC_WPNav/AC_WPNav.cpp, libraries/AC_WPNav/AC_WPNav.h
Free bugfix for incorrect initialisation
=> AC_WPNav: honour changes to wp-speed-up and wp-speed-down in-flight

ArduPlane/Parameters.cpp, ArduPlane/Parameters.h, ArduPlane/Plane.h, ArduPlane/navigation.cpp, ArduPlane/system.cpp
This parameter doesn't do anything, so we should remove it. I'm not sure if it ever did anything.....
=> Plane: remove none-functional NAV_CONTROLLER param

libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp
=> AP_RangeFinder_Params: update PIN description

libraries/AP_Avoidance/AP_Avoidance.cpp
Fixes https://github.com/ArduPilot/ardupilot/issues/9453
=> AP_Avoidance: correct ADSB vertical velocity conversion

ArduPlane/Plane.h, ArduPlane/commands_logic.cpp, libraries/AC_WPNav/AC_WPNav.h
Fixes #8677
Does what is says on the tin, results in much better accuracy on VTOL waypoints. 
Gotta love it when you find a empty else statement...
=> Plane: use VTOL WP radius in VTOL mode

ArduPlane/Plane.h, ArduPlane/servos.cpp, libraries/SRV_Channel/SRV_Channel.cpp, libraries/SRV_Channel/SRV_Channel.h
=> Plane : Improved LAND_THEN_NEUTRL to work on all control surfaces

Tools/scripts/uploader.py
this was broken by the support for extf images for QSPI. Most apj files on our firmware server do not have an extf_image field
=> Tools: fixed uploader for apj files without a extf image

libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp
Exit parameter mode quickly on ping
=> Don't enter parameter mode while armed

ArduPlane/Log.cpp
Not sure this is necessarily worth logging - was basic debug for new issue
=> Plane: log groundspeed undershoot

libraries/AP_Mission/AP_Mission.cpp
Discovered this when trying to run the standard CMAC mission on Sub
Bug can be recreated in SITL by starting Sub, loading CMAC-circuit,txt, and attempting to enter auto mode.
Before:
After:
=> AP_Mission: fix infinite loop with nav commands that won't start

libraries/AP_MSP/AP_MSP_Telem_Backend.cpp
this fixes a rounding issue in the MSP rssi reporting.
=> AP_MSP: fix rssi rounding issue

ArduPlane/AP_Arming.cpp
Per https://github.com/ArduPilot/ardupilot/pull/18680#issuecomment-921344765
=> Plane: allow arming in guided with only arm in Qmodes Q_OPTION

ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduCopter/config.h, ArduCopter/defines.h, ArduCopter/mode.cpp, ArduCopter/mode.h, ArduCopter/mode_acro.cpp, ArduCopter/mode_acro_heli.cpp, ArduCopter/mode_althold.cpp, ArduCopter/mode_auto.cpp, ArduCopter/mode_autorotate.cpp, ArduCopter/mode_autotune.cpp, ArduCopter/mode_circle.cpp, ArduCopter/mode_drift.cpp, ArduCopter/mode_flowhold.cpp, ArduCopter/mode_guided.cpp, ArduCopter/mode_land.cpp, ArduCopter/mode_loiter.cpp, ArduCopter/mode_poshold.cpp, ArduCopter/mode_rtl.cpp, ArduCopter/mode_smart_rtl.cpp, ArduCopter/mode_sport.cpp, ArduCopter/mode_stabilize.cpp, ArduCopter/mode_stabilize_heli.cpp, ArduCopter/mode_systemid.cpp, ArduCopter/mode_zigzag.cpp, ArduCopter/takeoff.cpp, ArduCopter/tuning.cpp, libraries/AP_Math/control.cpp, libraries/AP_Math/control.h
Use maximum rate parameters for ACRO in degrees per second
Update the expo function to provide greater range
=> ACRO parameter and EXPO update

Blimp/mode_loiter.cpp, Blimp/mode_velocity.cpp, libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AP_Logger/AP_Logger.h, libraries/AP_Logger/LogFile.cpp, libraries/AP_Logger/LogStructure.h
This PR updates the Pos Control Logging to include the desired values and transform them to NED frame.
=> Pos Control logging

libraries/AP_ADSB/AP_ADSB_Sagetech.cpp
Saves ~64~ more than 64 bytes on CubeBlack
=> AP_ADSB: tidy sending of SageTech RF mode

Tools/scripts/build_binaries.py
=> Tools: build disco static

Tools/autotest/common.py, libraries/AP_GPS/LogStructure.h, libraries/AP_GPS/LogStructure_SBP.h, libraries/AP_Logger/AP_Logger.cpp, libraries/AP_Logger/LogStructure.h
```
2021-09-25 20:51:49.39: SBPH {TimeUS : 10404170, CrcError : 0, LastInject : 0, IARhyp : 0}
2021-09-25 20:51:49.59: SBPH {TimeUS : 10604090, CrcError : 0, LastInject : 0, IARhyp : 0}
2021-09-25 20:51:49.80: SBPH {TimeUS : 10804843, CrcError : 0, LastInject : 0, IARhyp : 0}
2021-09-25 20:51:50.00: SBPH {TimeUS : 11004763, CrcError : 0, LastInject : 0, IARhyp : 0}
2021-09-25 20:51:50.20: SBPH {TimeUS : 11204683, CrcError : 0, LastInject : 0, IARhyp : 0}
2021-09-25 20:51:50.40: SBPH {TimeUS : 11404603, CrcError : 0, LastInject : 0, IARhyp : 0}
2021-09-25 20:51:50.60: SBPH {TimeUS : 11604523, CrcError : 0, LastInject : 0, IARhyp : 0}
2021-09-25 20:51:50.79: SBPH {TimeUS : 11804443, CrcError : 0, LastInject : 0, IARhyp : 0}
2021-09-25 20:51:50.99: SBPH {TimeUS : 12004363, CrcError : 0, …
```
=> Move SBP GPS logging into AP_GPS log structures

libraries/AP_Logger/AP_Logger_File.cpp
this prevents a stuck write closing logging when LOG_DISARMED=1
this fixes LOG_DISARMED=1 on HWing
=> AP_Logger: fixed stuck logging with LOG_DISARMED=1

libraries/AP_Filesystem/AP_Filesystem_backend.h
=> AP_Filesystem: raise an internal error for fileop on main thread

Tools/AP_Bootloader/support.cpp, Tools/AP_Periph/can.cpp, libraries/AP_Common/AP_ExpandingArray.h, libraries/AP_HAL/utility/RingBuffer.h, libraries/AP_ONVIF/AP_ONVIF.h
extract from https://github.com/ArduPilot/ardupilot/pull/18415
=> fix Pragma

Tools/scripts/generate_manifest.py
this allows beta version to be displayed
=> Tools: added mav-firmware-version-str to manifest

ArduCopter/Copter.h, ArduPlane/Plane.h, ArduSub/Sub.h, Rover/Rover.h, libraries/AP_Camera/AP_Camera.cpp, libraries/AP_Camera/AP_Camera.h, libraries/AP_Camera/AP_Camera_Logging.cpp
... and AHRS while we're at it.
=> Stop Camera from taking reference to current_loc

libraries/AP_HAL/utility/tests/test_ringbuffer.cpp
=> AP_HAL: added peekiovec test

libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_AttitudeControl/AC_PosControl.h, libraries/AC_AttitudeControl/AC_PosControl_Sub.cpp
https://discuss.ardupilot.org/t/copter-4-1-0-rc1-released-for-beta-testing/75878/54
=> Serious Position controller bug fix needed for latest release.

ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_AttitudeControl/AC_PosControl.h, libraries/AC_AttitudeControl/AC_PosControl_Sub.cpp, libraries/AP_Logger/AP_Logger.h, libraries/AP_Logger/LogFile.cpp, libraries/AP_Logger/LogStructure.h, libraries/AP_SerialManager/AP_SerialManager.cpp
This is the Copter-4.1.0-rc4 release which includes the commits shown in the "4.1.0-rc4" column of the [Copter-4.1 project](https://github.com/ArduPilot/ardupilot/projects/19).  In particular it includes @lthall's position controller fix https://github.com/ArduPilot/ardupilot/pull/18817
This has not been tested on a real vehicle but hopefully it is OK with the SITL-only testing.
=> Copter: 4.1.0-rc4 release

Rover/Log.cpp, Rover/Rover.h, libraries/AP_RangeFinder/AP_RangeFinder_Backend.h, libraries/AP_RangeFinder/AP_RangeFinder_NMEA.cpp, libraries/AP_RangeFinder/AP_RangeFinder_NMEA.h, libraries/GCS_MAVLink/GCS_Common.cpp
=> Rover : log rangefinder instance in DPTH message

libraries/AP_HAL_SITL/HAL_SITL_Class.cpp, libraries/AP_HAL_SITL/SITL_cmdline.cpp, libraries/AP_HAL_SITL/Storage.cpp
analogous to our normal "extern hal" stuff but removes need for casting
tridge asked for some cleanup like this on the devcall this-morning
=> AP_HAL_SITL: add and use HAL_SITL &hal_sitl

libraries/AP_HAL_ChibiOS/hwdef/common/chibios_board.mk, libraries/AP_HAL_ChibiOS/hwdef/common/stm32_util.c, libraries/AP_HAL_ChibiOS/hwdef/common/usbcfg.c, libraries/AP_HAL_ChibiOS/hwdef/common/usbcfg_dualcdc.c
it will be interesting to see if we get through CI on this
=> ChibiOS: lock in zero warnings for RTOS build

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Logger/AP_Logger.cpp, libraries/AP_Logger/AP_Logger.h, libraries/AP_Logger/LogStructure.h
useful to see @SYS file content
MAVExplorer support here:
https://github.com/ArduPilot/MAVProxy/pull/955
@bugobliterator I snuck in a lambda function
=> Logging: added logging of file content

libraries/AP_HAL_ChibiOS/hwdef/QioTekZealotH743/hwdef.dat
HAL_ChibiOS: fixed orientation of ADI1674X and optimize SPI3 DMA
=> HAL_ChibiOS: fixed orientation of ADI1674X and optimize SPI3 DMA

.gitmodules
see https://github.blog/2021-09-01-improving-git-protocol-security-github/
=> git: changed submodule protocols to https://

Tools/scripts/size_compare_branches.py
Adds a vehicle option to the elfdiff tool
=> Tools: size_compare_branches.py add -vehicle option

Tools/autotest/sim_vehicle.py
Based on these two previous PRs:
https://github.com/ArduPilot/ardupilot/pull/15728
https://github.com/ArduPilot/ardupilot/pull/15758
They have been rebased against the latest master as of today.
=> Sim vehicle single mavproxy

.github/workflows/test_size.yml
new unstated dependency which is causing CI to fall over
=> .github: install anytree along with elf_diff

Tools/autotest/common.py
Out stack traces are not being useful, so gather some more information on why that might be
=> autotest: Print /proc/PID/status on ardupilot binary death

libraries/AP_Scripting/docs/docs.lua
This completes the docs of scripting argument names. 
Still lots to be done...
function descriptions
argument descriptions
return descriptions
But they will have to wait for a follow up PR.
=> AP_Scripting: Docs: document arguments names

Tools/autotest/common.py
If we do not drain pexpects regularly the ardupilot process can become blocked on terminal IO
=> autotest: read pexpects while waiting for sim time

libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp, libraries/AP_InertialSensor/AP_InertialSensor_Invensensev2.cpp
=> AP_InertialSensor: fixed comments on IMU types supported

libraries/AP_AIS/AP_AIS.cpp, libraries/AP_AIS/AP_AIS.h, libraries/AP_Common/AP_Common.cpp, libraries/AP_Common/AP_Common.h, libraries/AP_WindVane/AP_WindVane_NMEA.cpp, libraries/AP_WindVane/AP_WindVane_NMEA.h
There are multiple methods to convert the hexa character to binary.
I found out that this process is the same.
I will make this method common.
=> Rover: Make the char to hex method a common method

Tools/scripts/run_coverage.py
Also, add BalanceBot and Sailboat to the tests run (oops!)
=> Check tests succeed during coverage testing

libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
=> AC_AttitudeControl: adjust docs for rate max limits

libraries/AP_RCProtocol/AP_RCProtocol.h
Needed this as soon as we got the RC_PROTOCOL bitmask
=> AP_RCProtocol: number all of the RC Protocols supported

ArduCopter/Copter.h, ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduCopter/system.cpp
This is to fix the issue #18165.
=> Copter : add parameter SURFTRAK_MODE

Tools/autotest/arducopter.py, Tools/autotest/common.py
Checks basic functionality of fetching an @SYS file via FTP
=> autotest: add test for PerfInfo tasks.txt info

ArduCopter/Copter.h, Blimp/Blimp.h
=> Remove unimplemented function declarations

Tools/environment_install/install-prereqs-ubuntu.sh, Vagrantfile
Vagrant and environment script updates
=> Add support for Ubuntu Impish

AntennaTracker/Tracker.cpp, ArduCopter/Copter.cpp, ArduPlane/ArduPlane.cpp, ArduSub/ArduSub.cpp, Blimp/Blimp.cpp, Rover/Rover.cpp, Tools/autotest/arducopter.py, libraries/AP_Scheduler/AP_Scheduler.cpp, libraries/AP_Scheduler/AP_Scheduler.h, libraries/AP_Scheduler/examples/Scheduler_test/Scheduler_test.cpp, libraries/AP_Vehicle/AP_Vehicle.cpp
- I've only converted AntennaTracker to specify priorities
- other comments in review to come
=> Specify task priorities in scheduler table

libraries/AP_Logger/AP_Logger.cpp, libraries/AP_Logger/AP_Logger.h, libraries/AP_Logger/LogStructure.h, libraries/AP_Scripting/AP_Scripting.cpp, libraries/AP_Scripting/AP_Scripting.h, libraries/AP_Scripting/lua_scripts.cpp, libraries/AP_Scripting/lua_scripts.h
This saves any loaded scripts to data flash so the script can be extracted from the log. It also adds logging of runtime stats, script runtime and memory useage.
=> AP_Scripting: log loaded scripts and log runtime stats

ArduCopter/radio.cpp
=> Copter: Change the process description

ArduPlane/RC_Channel.cpp
only release on flag high
fixes #18843
=> Plane: fixed chute release on low value of RC option

libraries/AP_Parachute/AP_Parachute.cpp
=> AP_Parachute: added arming check for chute released

libraries/AP_RCProtocol/AP_RCProtocol.cpp, libraries/AP_RCProtocol/AP_RCProtocol.h, libraries/AP_RCProtocol/AP_RCProtocol_SBUS.cpp, libraries/AP_RCProtocol/AP_RCProtocol_SBUS.h, libraries/AP_RCProtocol/SoftSerial.h, libraries/RC_Channel/RC_Channels_VarInfo.h
It's just SBUS... but with increased opportunities for corruption
Fixes #18802
=> AP_RCProtocol: add support for DJI Fast SBUS

libraries/AP_HAL_ChibiOS/GPIO.cpp
=> AP_HAL_ChibiOS: remove unused pin-related defines

ArduPlane/quadplane.cpp
=> Plane: fixed variable name

libraries/AP_Mission/AP_Mission.cpp
PLANE to refuse NAV_SPLINE_WAYPOINT missions items. This replaces https://github.com/ArduPilot/ardupilot/pull/19234
=> AP_Mission: PLANE to refuse NAV_SPLINE_WAYPOINT missions items

libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_AttitudeControl/AC_PosControl.h, libraries/AC_PID/AC_P_1D.cpp, libraries/AC_PID/AC_P_1D.h, libraries/AC_PID/AC_P_2D.cpp, libraries/AC_PID/AC_P_2D.h
This removes unused limit flags from poscontrol and the 1D and 2D position P controllers.
=> AC_PosControl: remove unused limit flags

Tools/autotest/arducopter.py
Collection isn't instantaneous
=> autotest: fetch tasks.txt twice

Rover/mode.h, Rover/system.cpp
This fixes the issue #19305. I have tested this and got expected result. Here's a screenshot.
=> Rover: set MIS_DONE_BEHAVE to LOITER in boats

libraries/AP_AHRS/AP_AHRS.cpp
we need to use the EKF selected airspeed sensor when the EKF is setup
to run a different sensor on each lane
=> AP_AHRS: fixed switching airspeed sensor based on EKF3 affinity

ArduPlane/commands.cpp
This is solution to bug described in #19189.
=> solution to TECS height rate demand spikes due to setting target altitude to soon

Tools/autotest/arducopter.py, Tools/autotest/arduplane.py
This method is a little faster than calling set_parameter individually as it can stream the sets.
=> autotest: use set_parameters some more

ArduCopter/mode_guided.cpp, ArduSub/control_guided.cpp
I've only tested this as far as it compiling.
=> Remove unused GUIDED_LOOK_AT_TARGET_MIN_DISTANCE_CM define

Vagrantfile
Fixes issue https://github.com/ArduPilot/ardupilot/issues/19374
=> updated vagrant file to not start bionic64 desktop by default

ArduPlane/commands_logic.cpp
found by Peter Barker with valgrind
fixes #19407
=> Plane: fixed use before init bug in VTOL land

libraries/AP_Proximity/AP_Proximity.cpp, libraries/AP_Proximity/AP_Proximity.h, libraries/AP_Proximity/AP_Proximity_Cygbot_D1.cpp, libraries/AP_Proximity/AP_Proximity_Cygbot_D1.h
This is an interesting 3-D Lidar from Cygbot. https://www.cygbot.com/2d-3d-dual-solid-state-tof-lidar
I have implemented "2-D" mode only as I am not sure if Cube Orange will be able to handle the 3-D transmission. 
Manual can be found here: https://www.cygbot.com/downloads . My implementation is strictly based on the manual directly.
=> AP_Proximity: Add Cygbot D1 Driver

libraries/AP_Scripting/AP_Scripting.cpp, libraries/AP_Scripting/AP_Scripting.h, libraries/AP_Scripting/examples/plane_aerobatics.lua
added throttle and height controller to aerobatic example using a generic PI controller
changed rolling circle to take the radius and number of circles. negative radius for negative yaw rate and negative number of    circles for left roll
also added two more SCR_USER parameters
=> Plane: update plane aerobatics example

libraries/AP_BattMonitor/AP_BattMonitor.cpp, libraries/AP_BattMonitor/AP_BattMonitor.h, libraries/AP_BattMonitor/AP_BattMonitor_Backend.h, libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Params.h, libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.cpp, libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.h, libraries/GCS_MAVLink/GCS_Common.cpp
This adds a couple things:
- new driver for PacketDigital UAVCAN MPPT
- new DroneCAN msgs (needs PR https://github.com/dronecan/DSDL/pull/3)
- option bits for turning power on/off at boot/arm events For MPPT only
=> Battery_Mon: UAVCAN based MPPT

libraries/AP_L1_Control/AP_L1_Control.cpp
There is a coding style called "initialize and use stack variables".
By adapting to this style, IF statements can be made easier.
=> AP_L1_Control: Simplify the decision process by initializing the stack variables

libraries/AP_HAL_SITL/SITL_State.cpp, libraries/AP_HAL_SITL/SITL_State.h, libraries/AP_HAL_SITL/SITL_cmdline.cpp
This is poked into the model now
=> AP_HAL_SITL: stop passing home_str to _sitl_setup

Tools/scripts/decode_devid.py, libraries/AP_InertialSensor/AP_InertialSensor_Backend.h, libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp, libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.h
AP_InertialSensor: added support for IIM-42652 and ICM-40605 sensors
=> AP_InertialSensor: added support for IIM-42652 and ICM-40605 sensors

libraries/AP_Airspeed/AP_Airspeed.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp, libraries/AP_CANManager/AP_CANDriver.cpp, libraries/AP_Compass/AP_Compass.cpp, libraries/AP_GPS/AP_GPS.cpp, libraries/AP_Gripper/AP_Gripper.cpp, libraries/AP_Notify/AP_Notify.cpp, libraries/AP_OpticalFlow/OpticalFlow.cpp, libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp
NFC....we are globally moving from UAVCAN to DroneCAN in user seen documentation
=> Change UAVCAN to DroneCAN in param metadata

Tools/autotest/arducopter.py, Tools/autotest/common.py, Tools/autotest/rover.py
Adds a couple of bits to test estop-at-boot functionality
Also moves a convenience function up.
=> autotest: Augment estop tests

libraries/StorageManager/StorageManager.cpp
=> StorageManager: fix write_block() comment

libraries/AP_HAL_ChibiOS/Util.cpp
=> AP_HAL_ChibiOS: remove stray 'No Crash Detected' diagnostic

libraries/AP_PiccoloCAN/AP_PiccoloCAN.cpp
- Fixes issues with temperature data in telemetry and logs
- Use the maximum of available temperature values for the ESC (where available)
A customer reported that the temperature data reported from a [Velocity ESC](https://www.currawongeng.com/velocity-esc/) was incorrect. It appears that the available temperature readings are not being directed into the logging structures in the correct fashion.
A pretty simple change to fix the issue.
Another small change is to choose the "maximum" ESC temperature (for variants of the ESC which have multiple temperature readings available).
=> AP_PiccoloCAN: Fix temperature logging bug

libraries/AP_ADSB/AP_ADSB_Sagetech.cpp, libraries/AP_Proximity/AP_Proximity_Backend_Serial.cpp, libraries/AP_RCProtocol/AP_RCProtocol.cpp, libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp, libraries/AP_RCTelemetry/AP_Spektrum_Telem.cpp, libraries/AP_RangeFinder/AP_RangeFinder_Backend_Serial.cpp, libraries/AP_SerialManager/AP_SerialManager.cpp, libraries/AP_SerialManager/AP_SerialManager.h
=> backport of RCIN fix

Tools/autotest/param_metadata/jsonemit.py, Tools/scripts/build_parameters.sh
Closes https://github.com/ArduPilot/ardupilot/issues/19566
=> autotest: param_parse.py: correct JSON output

libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp, libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp, libraries/AP_InertialSensor/AP_InertialSensor_tempcal.cpp, libraries/AP_Math/SCurve.cpp, libraries/AP_Math/vector3.h, libraries/Filter/HarmonicNotchFilter.cpp, libraries/Filter/LowPassFilter.cpp, libraries/Filter/LowPassFilter2p.cpp, libraries/Filter/NotchFilter.cpp
This yields a fairly significant - and means the difference between poor quality flight and controlled flight - CPU improvement. On an F7, before:
```
ThreadsV2
ISR           PRI=255 sp=0x20010000 STACK=1224/1536 LOAD= 5.5%
ArduCopter    PRI=182 sp=0x20010600 STACK=5256/7168 LOAD=64.0%
idle          PRI=  1 sp=0x20023770 STACK= 144/ 352 LOAD= 0.0%
UART_RX       PRI= 60 sp=0x2004EE80 STACK= 760/1104 LOAD= 1.6%
OTG1          PRI= 60 sp=0x2004E588 STACK= 256/ 656 LOAD= 0.5%
monitor       PRI=183 sp=0x20020860 STACK= 480/ 848 LOAD= 0.9%
timer         PRI=181 sp=0x20021AE0 STACK=1480/1872 LOAD= 2.7%
rcout         PRI=181 sp=0x200211A0 STACK= 440/ 848 LOAD=18.6%
rcin          PRI=177 sp=0x20020C00 STACK= 416/1360 LOAD= 9.3%
io            PRI= 58 sp=0x2001FEC0 STACK=1496/2384 LOAD= 0.0%*
storage …
```
=> Optimize filter processing in SPI thread

ArduPlane/quadplane.cpp, ArduPlane/quadplane.h, ArduPlane/transition.h
Also fixed some metadata as a drive by
=> Plane: add Q_OPTION to force fw trans on fail instead of QLAND

libraries/AP_VisualOdom/AP_VisualOdom.cpp, libraries/AP_VisualOdom/AP_VisualOdom.h, libraries/AP_VisualOdom/AP_VisualOdom_Backend.h, libraries/AP_VisualOdom/AP_VisualOdom_IntelT265.cpp, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/SITL/SIM_Vicon.cpp, libraries/SITL/SIM_Vicon.h
This works with the ModalAI VOXL vision inertial odometry system
Example of velocities and positions with EK2 on GPS and EK3 on VIO. Copter was manually aligned pointing north on startup to make log comparison easy between earth and body frame data. Copter was "flown" hand-held (I did make the obligatory motor noises for realism)
=> VisualOdom: Support ODOMOTRY mavlink message

Tools/ardupilotwaf/build_summary.py
This fixes an issue I caused by PR https://github.com/ArduPilot/ardupilot/pull/19534  and closes https://github.com/ArduPilot/ardupilot/issues/19609
=> Tools: fix Build_Summary when more than one targert

ArduPlane/Attitude.cpp, ArduPlane/mode.h, ArduPlane/mode_qrtl.cpp
thanks to Henry for noticing this
=> Plane: fixed stick mixing and throttle nudge in QRTL approach

libraries/AP_InertialSensor/AP_InertialSensor_ADIS1647x.cpp, libraries/AP_InertialSensor/AP_InertialSensor_ADIS1647x.h, libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp, libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
support 32 bit delta angles and velocities
tested on a CUAV-X7 with ADIS16470 and an external ADIS16507 with 32-bit delta-angles and delta-velocity
=> AP_InertialSensor: added support for more ADIS IMUs

libraries/AP_InertialSensor/examples/INS_generic/INS_generic.cpp
=> AP_InertialSensor: fixed INS_generic example

Tools/autotest/autotest.py, Tools/scripts/build_sizes.py
example: https://firmware.ardupilot.org/Tools/BuildSizes/builds.html
Pair programmed with MichelleR
=> Tools: a script to list builds with flash free

ArduPlane/mode_stabilize.cpp
should self-level. Broken by #19171
=> Plane: fix stabilize mode

libraries/AP_Logger/AP_Logger_MAVLink.cpp
Two minor fixes while debugging the mavlink logger backend.
=> AP_Logger: quick fixes

Tools/scripts/build_sizes.py, Tools/scripts/build_sizes/filtertable.js, Tools/scripts/build_sizes/sorttable.js
Add link to use css from main firmware page.
Add return to top link after each table (to make navigating between tables easier).
Make text red for for boards that have less than 5kB flash free or haven't built in the past 3 days. 
Sort by flash free for the group that have low flash free, and by date built for the second group.
=> Tools: Add css formatting and red colour

libraries/RC_Channel/RC_Channel.cpp
Correctly fixes https://github.com/ArduPilot/ardupilot/pull/19663
https://www.dictionary.com/browse/auxiliary
=> RC_Channel: fix typo, again

libraries/AP_Logger/AP_Logger.cpp, libraries/AP_Logger/AP_Logger_Block.cpp, libraries/AP_Logger/AP_Logger_DataFlash.cpp, libraries/AP_Logger/AP_Logger_File.cpp
=> Logging tidy-ups cherry-picked from #19661

Tools/scripts/build_binaries.py
This adds Blimp to also be auto-built by the firmware server.
=> Tools: Auto-build blimp firmwares

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/generator/src/main.c
adds support for `FWVersion:fw_string()` returning `ArduCopter V4.2.0-dev (922dc8c0)`
=> AP_Scripting: add support for getting fw version

Tools/autotest/rover.py
This was checking for speed.
Which is great in that it says that we're basically going somewhere.
OTOH, probably better-still if we go where we're asked to, so this test removes the speed test and replaces it with a location test.
=> autotest: fix rover POSITION_TARGET_LOCAL test

Tools/scripts/board_list.py
request from https://github.com/ArduPilot/ardupilot/pull/19600
=> Tools: add blue and bbbmini to firmware server

Tools/autotest/build-with-disabled-features.py
=> autotest: build-with-disabled-features.py: flake8-clean

libraries/AC_Avoidance/AC_Avoid.cpp, libraries/AC_WPNav/AC_Loiter.cpp, libraries/GCS_MAVLink/GCS_Fence.cpp, libraries/RC_Channel/RC_Channel.cpp
=> Plane: don't link in AC_Avoidance on plane

libraries/AP_GPS/AP_GPS_NMEA.cpp, libraries/AP_GPS/AP_GPS_NMEA.h, libraries/AP_GPS/AP_GPS_UBLOX.cpp, libraries/AP_GPS/GPS_Backend.cpp, libraries/AP_GPS/GPS_Backend.h, libraries/SITL/SIM_GPS.cpp, libraries/SITL/SIM_GPS.h, libraries/SITL/SITL.h
This allows for both yaw and 3D velocity for Unicore NMEA GPS
=> GPS: Implement KSXT message for Unicore NMEA

Tools/scripts/build_options.py
Should be NFC, it does not add nor remove options
=> Tools: add more categories and reorganize a bit

Tools/autotest/pysim/util.py, Tools/autotest/test_build_options.py
This takes a *long* time to run :-)
=> autotest: add test_build_options to test each entry in build_options.py

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Logger/AP_Logger.cpp, libraries/AP_Logger/AP_Logger.h
=> Fix memory leak in file-content logging

libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
keep getting questions from users as to what this really means....we should make it intelligible/useful or lose it...I choose to lose it...
=> AP_NavEKF3: remove user unintelligible GCS message

libraries/AP_SerialManager/AP_SerialManager.cpp
NFC....fixes some forgotten metadata I discovered
@peterbarker think it should be a merge on CI
=> AP_SerialManager: add metadata for merged new protocols

Tools/autotest/autotest.py, Tools/scripts/board_list.py
Should unbreak the build server.
=> Fix source path for build_sizes.py

Tools/scripts/build_options.py, libraries/AP_GPS/AP_GPS.cpp, libraries/AP_GPS/AP_GPS_ERB.cpp, libraries/AP_GPS/AP_GPS_ERB.h, libraries/AP_GPS/AP_GPS_GSOF.cpp, libraries/AP_GPS/AP_GPS_GSOF.h, libraries/AP_GPS/AP_GPS_MAV.cpp, libraries/AP_GPS/AP_GPS_MAV.h, libraries/AP_GPS/AP_GPS_NMEA.cpp, libraries/AP_GPS/AP_GPS_NMEA.h, libraries/AP_GPS/AP_GPS_NOVA.cpp, libraries/AP_GPS/AP_GPS_NOVA.h, libraries/AP_GPS/AP_GPS_SBF.cpp, libraries/AP_GPS/AP_GPS_SBF.h, libraries/AP_GPS/AP_GPS_SBP.cpp, libraries/AP_GPS/AP_GPS_SBP.h, libraries/AP_GPS/AP_GPS_SBP2.cpp, libraries/AP_GPS/AP_GPS_SBP2.h, libraries/AP_GPS/AP_GPS_SIRF.cpp, libraries/AP_GPS/AP_GPS_SIRF.h
add build options to remove non UBLOX only backends
=> AP_GPS: add options to remove backends

Tools/autotest/logger_metadata/emit_rst.py
=> Tools: logger metadata: emit rst description on new line

libraries/AP_Compass/AP_Compass_MMC5xx3.cpp
We found that the sensor sometimes fails to be identified at first try in the SPI bus, so this patch retries up to 10 times
=> AP_Compass: Retry reading MMC5983 ID up to 10 times

Tools/scripts/build_options.py
must be within closing ] for array
=> build_options.py: correct GPS Drivers section

libraries/AP_VideoTX/AP_SmartAudio.cpp, libraries/SITL/SIM_Plane.cpp, libraries/SITL/examples/JSON/MATLAB/tcp_udp_ip_2.0.6/pnet.c
small fixed typo 
`to to` -> `to`
=> Update : typo

Tools/scripts/board_list.py
This is a simple rearrangement.  It has been extracted from https://github.com/ArduPilot/ardupilot/pull/19775
=> board_list.py: tidy

libraries/AP_InertialSensor/AP_InertialSensor.h, libraries/GCS_MAVLink/GCS_Common.cpp
Fixes issue #19599 Failed to build for Pixhawk1 with O3
=> AP_InertialSensor: Disable -Werror=array-bounds on some getters

libraries/AP_ESC_Telem/AP_ESC_Telem.cpp, libraries/AP_PiccoloCAN/AP_PiccoloCAN.cpp, libraries/AP_RSSI/AP_RSSI.h, libraries/SITL/SIM_CRSF.cpp, libraries/SITL/SIM_Frsky.cpp, libraries/SITL/SIM_Frsky_D.cpp
telemtry, telemetery -> telemetry
=> AP_RSSI, AP_ESC_Telem, AP_PiccoloCAN, SITL : Update Telemetry

libraries/AP_EFI/AP_EFI.cpp, libraries/AP_EFI/AP_EFI.h, libraries/AP_EFI/AP_EFI_Serial_Lutan.cpp, libraries/AP_EFI/AP_EFI_Serial_Lutan.h, libraries/AP_EFI/AP_EFI_Serial_MS.cpp, libraries/AP_EFI/AP_EFI_Serial_MS.h, libraries/AP_Math/AP_Math.cpp, libraries/AP_Math/AP_Math.h, libraries/AP_SerialManager/AP_SerialManager.cpp, libraries/AP_SerialManager/AP_SerialManager.h
EFI system from this motor:
https://www.austars-model.com/dle60cc-efi-uav-engine-for-fixed-wing-drone-alternator-12v80w-ros-version-gst-inc-for-local-vip_g21812.html?s_id=4&fbclid=IwAR1XIRTI6cdM9UbjM6orE3bFIi-zsrqXwI-dKfdOmkWbuXWOaaLxZCOWIYQ
tested by Kyle Gardner
=> EFI: support for Lutan EFI system

ArduPlane/GCS_Mavlink.cpp
EKF estimate is both more accurate and less noisy
=> Plane: use EKF climb rate estimate in VFR_HUD.climb

libraries/AP_Scripting/AP_Scripting_helpers.cpp, libraries/AP_Scripting/AP_Scripting_helpers.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
Now we have params from scripting, setting defaults is useful and checking configured can be handy for doing param conversions.
=> AP_Scripting: params, set_defualt and check configured. 

Tools/autotest/arducopter.py, Tools/autotest/common.py
=> autotest : Update receive

libraries/AP_Param/AP_Param.cpp
Change from a direct value to a defined name
=> AP_Param: Change from a direct value to a defined name

AntennaTracker/Log.cpp, ArduCopter/Log.cpp, ArduPlane/Log.cpp, ArduSub/Log.cpp, Blimp/Log.cpp, Rover/Log.cpp, libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h
Factors all of the very similar call chains across our vehicles up into AP_AHRS.
=> Move AHRS logging calls into Log_Write

README.md
Chris Olson has not been the Tradheli maintainer for a few years now.  Just want to update the readme so it is accurate.
=> Update README to reflect current tradheli maintainers

Tools/autotest/sim_vehicle.py
* Add missing comma in `sim_vehicle.py`.
=> fix: Missing comma

libraries/AP_Proximity/AP_Proximity_Cygbot_D1.cpp
Fixes the CRC that I couldn't get working in https://github.com/ArduPilot/ardupilot/pull/19162
Turns out to be a silly mistake
=> AP_Proximity: Fix Cygbot D1 driver CRC

libraries/AC_PrecLand/AC_PrecLand.cpp, libraries/AC_PrecLand/AC_PrecLand.h
Please see https://github.com/ArduPilot/ardupilot/pull/18584#issuecomment-1025398646 for context.
=> AC_PrecLand: Covert parameter to Bitmask

libraries/AP_Avoidance/AP_Avoidance.cpp
trying to reduce places that know the innards of AP_Location
Tested in SITL by creating a swarm, fiddling DEV_OPTION bit....
=> AP_Avoidance: Tidy construction of temporary objects on stack

libraries/AP_NavEKF3/AP_NavEKF3_OptFlowFusion.cpp
This PR resolves issue https://github.com/ArduPilot/ardupilot/issues/19828 which involves EKF3 quietly failing to fuse range finder data into the estimated height above terrain (aka "hagl") which can affect the accuracy of optical flow based position estimation.
The underlying issue was that "gndHgtValidTime_ms" was always updated regardless of whether the rangefinder data was actually fused into the terrain estimate.  This PR fixes this so it is only updated when the rangefinder data is fused.  Also if this fusion does not happen for a full 5 seconds, then the "terrainState" (the ground's height above the EKF origin) is reset using the latest rangefinder data.
Note that the EstimateTerrainOffset() method can use the optical flow sensor (instead of a rangefinder) to estimate the hagl and …
=> AP_NavEKF3: optflow terrain state reset after 5sec

libraries/AP_GPS/AP_GPS.cpp, libraries/AP_GPS/AP_GPS.h, libraries/AP_GPS/AP_GPS_MAV.cpp, libraries/AP_GPS/AP_GPS_UAVCAN.cpp, libraries/AP_GPS/GPS_Backend.cpp, libraries/AP_GPS/GPS_Backend.h
fixes issues mentioned here https://github.com/ArduPilot/ardupilot/issues/19963
=> AP_GPS: fix time_epoch_usec

libraries/AP_HAL_ChibiOS/hwdef/ARK_GPS/hwdef-bl.dat, libraries/AP_HAL_ChibiOS/hwdef/ARK_GPS/hwdef.dat
Added support of the ARK_GPS board on ArduPilot. All sensors are running.
=> ARK_GPS: porting to ArduPilot

libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h
https://github.com/ArduPilot/ardupilot_wiki/pull/4091#issuecomment-1029253509
=> AP_AHRS : remove duplicated words from comments

libraries/AP_BLHeli/AP_BLHeli.cpp, libraries/AP_HAL_ChibiOS/RCOutput.cpp
https://github.com/ArduPilot/ardupilot/pull/19875 broke serial passthrough on H7. This fixes it.
=> H7 passthrough

libraries/AC_AutoTune/AC_AutoTune_Heli.cpp, libraries/AP_Motors/AP_MotorsHeli.h
This PR cleans up some things in preparation for 4.2 beta for tradheli autotune and the collective setup.  
In autotune, it updates parameter descriptions and modifies a parameter default.  In the collective setup, it modifies a parameter default.
=> Tradheli-minor changes to autotune and collective setup

Tools/scripts/build_autotest.sh
these times have had to move out as our builds are taking a long time
now
=> Tools: update build_autotest.sh to reflect server content

libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro-bdshot/hwdef.dat
See https://discuss.ardupilot.org/t/bi-directional-dshot-support/70210/128
=> Fix bi-directional dshot on omnibusf4pro

Tools/autotest/arduplane.py
Now checks that an aborted landing occurs.
=> autotest: Improve Landing-Drift

libraries/AP_Airspeed/AP_Airspeed_DLVR.cpp
This is intended to help with really bad RF interference flipping bits on the I2C bus which can lead to some interesting results.
The check is designed to reject any pressure outside the full scale sensor range, and to ensure that the temperature doesn't change by more then 10C since we last updated the airspeed library (so no temperature changes at a rate of 100C per second).
Tested with a real sensor on the ground by just applying a large scalar to the read airspeed value and then manipulating the actual pressure on the probe. The temperature check wasn't tested past checking that it didn't lead to rejecting the real data.
=> AP_Airspeed: Sanity check DLVR raw data before accumulating it

libraries/AP_NavEKF3/AP_NavEKF3_OptFlowFusion.cpp
This is a small improvement to the EKF3's optical flow fusion done by moving the calculation of two variables ("range" and "posOffsetBody") outside of a for loop so they are only calculated once (instead of twice).
I've run this through replay to confirm that there is no impact on the EKF3 before and after.
Note: I initially tried to also move "relVelSensor" out of the for loop but found that it did have a small impact on the EKF3's output because "relVelSensor" uses "stateStruct.velocity" and each iteration of the loops modifies the velocity (although confusingly this is done using the union'd "statesArray").  I think this is a bug though isn't it?
This was originally part of PR https://github.com/ArduPilot/ardupilot/pull/19878 but I'm pulling it out here to reduce complexity in the …
=> AP_NavEKF3: FuseOptFlow only calculates range and posOffsetBody once

libraries/AP_RTC/AP_RTC.cpp
Also update date to 2022-01-01 00:00 UTC
=> AP_RTC: fix oldest_acceptable_date to be in micros

libraries/AP_Scripting/examples/Aerobatics/Missions/plane_aerobatics.lua
example mission video:
https://cdn.discordapp.com/attachments/797952826847920128/928298942322577428/New_Project.mp4
=> AP_Scripting:Update plane aerobatics scripts with adds and fixes

libraries/Filter/tests/test_modefilter.cpp
.... previously only checking return value of apply
=> Filter: add trivial test that ModeFilter's get method works

libraries/Filter/tests/test_modefilter.cpp
=> Filter: add trivial test for ModeFilter get method (float version)

Tools/AP_Bootloader/can.cpp, libraries/AP_CANManager/AP_CANManager.cpp, libraries/AP_CANManager/AP_CANManager.h, libraries/AP_Common/sorting.cpp, libraries/AP_Common/sorting.h, libraries/AP_Common/tests/test_sorting.cpp, libraries/AP_HAL/CANIface.cpp, libraries/AP_HAL/CANIface.h, libraries/AP_HAL_ChibiOS/CANFDIface.cpp, libraries/AP_HAL_ChibiOS/CanIface.cpp, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_MAVLink.cpp, libraries/GCS_MAVLink/GCS_MAVLink.h
This also fixes a packet corruption problem with mavlink and multiple threads, and fixes a high interrupt latency issue in HAL_ChibiOS CAN handling
=> CAN: added filtering code for low bandwidth CAN over mavlink

libraries/AP_HAL/CANIface.cpp
callback can change from another thread
=> AP_HAL: fixed a race conditon for CAN frame callback

Tools/autotest/common.py
You can't download logs - but we should make sure that the codepaths are
at least crossed
=> autotest: add log download tests for dataflash-over-mavlink

libraries/AP_Logger/AP_Logger.cpp
=> AP_Logger: reduce the stack log frequency

libraries/AP_Notify/AP_Notify.cpp
broken by combination of alarm changes and header changes
=> AP_Notify: fixed builds

Tools/autotest/arducopter.py
... this is a bit odd in that to trigger a parachute via mavlink you must first enable it....
i.e. going from disable -> release doesn't work.  You must send at least two mavlink commands; disable -> enable -> release
=> autotest: add more parachute tests

Tools/autotest/common.py
Really not sure why this suddenly broke...
=> autotest: fix MAVFTP test

libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp
NFC...update name to reflect new functionality
=> AP_BattMonitor: update name of type 10 to Sum of Selected Monitors

libraries/RC_Channel/RC_Channel.h
Adjustments for API usage over time.
Only tested for compilation / autotest
=> Tidy RC_Channel interface

ArduPlane/navigation.cpp, ArduPlane/reverse_thrust.cpp, libraries/AP_IOMCU/AP_IOMCU.cpp, libraries/RC_Channel/RC_Channel.cpp, libraries/RC_Channel/RC_Channel.h
I've only tested that this compiles.... and runs the autotest suite :-)
=> Rename and make enum RC_Channel::ControlType 

libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
fixes #20180
thanks to @liyue75 for spotting this!
=> AP_NavEKF3: fixed constrain indexing bug

Tools/scripts/build_binaries.py
only sub stable and beta on old compiler
=> Tools: switch compiler for new releases to 10.2

libraries/AP_Scripting/examples/orbit_follow.lua
allows a following vehicle to orbit the lead vehicle
=> AP_Scripting: added example for orbit follow

libraries/AP_Follow/AP_Follow.cpp
this is used by qgroundcontrol, allowing follow on a mobile device
note that you must set the qgc option to "always send follow" and also
tested with an android phone and qgc
=> AP_Follow: support the FOLLOW_TARGET mavlink message

Tools/environment_install/install-prereqs-ubuntu.sh
changing to ln -sf is to allow the script to be run twice (if first run fails)
=> Tools: fixed env install for ubuntu 22.04

Tools/autotest/common.py, Tools/scripts/build_binaries.py, Vagrantfile
.... also fix exception handling for Python 3.10.
=> Vagrant: Add support for Ubuntu 22.04 (Jammy)

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_PiccoloCAN/AP_PiccoloCAN.cpp
Spotted while poking about looking at https://github.com/ArduPilot/ardupilot/issues/20218
=> include GPIO in servo no function checks

ArduPlane/radio.cpp, libraries/RC_Channel/RC_Channel.cpp, libraries/RC_Channel/RC_Channel.h
The first patch's context here shows the current inconsistency
=> Rename within_min_dz to in_min_dz for consistency 

libraries/AP_RangeFinder/AP_RangeFinder_LeddarVu8.cpp, libraries/AP_RangeFinder/AP_RangeFinder_LeddarVu8.h
=> AP_RangeFinder: add AP_RANGEFINDER_LEDDARVU8_ENABLED

Tools/CPUInfo/CPUInfo.cpp, Tools/CPUInfo/Makefile
add some dsp function times to the output
=> CPUInfo: add DSP

Tools/autotest/pysim/util.py
This led me to break some things in #19879, so this is my attempt to prevent that from happening again.
=> Tools: util.py: fix comment for reltopdir()

AntennaTracker/sensors.cpp, ArduCopter/GCS_Mavlink.cpp, ArduSub/GCS_Mavlink.cpp, Blimp/GCS_Mavlink.cpp, Rover/commands.cpp
It's a meaningless process for build warnings.
I declare that I will not use the result in the preprocessor.
=> Global: Change the process for errors

Tools/scripts/build_sizes/build_sizes.py
for completeness, and time monitoring
=> Tools: add AntennaTracker to builds list

libraries/SITL/SIM_Buzzer.h
I am buzzing with SITL.
A build error occurred.
I have changed the build error.
I learned that the bug was incorporated in this repository.
72d01aa8
=> SITL: Change build errors

ArduPlane/Attitude.cpp
Follow up to https://github.com/ArduPilot/ardupilot/pull/20232 spotted by @peterbarker during the dev-call.
=> Plane: never stick mix without valid RC input

Tools/AP_Bootloader/board_types.txt, libraries/AP_HAL_ChibiOS/hwdef/Sierra-F9P/hwdef-bl.dat, libraries/AP_HAL_ChibiOS/hwdef/Sierra-F9P/hwdef.dat
@tridge Sierra-F9P board support. 
Moving baseline enabled.
=> AP_HAL_ChibiOS: Add Sierra-F9P support

libraries/AP_HAL_ChibiOS/hwdef/CubeGreen-solo/hwdef.dat
Fixes Issue: https://discuss.ardupilot.org/t/4-1-4-issue-with-oreoled-greencube-solobuild/81655
=> GubeGreen: Add OREOLED support for Solo

Tools/scripts/size_compare_branches.py
=> Tools: correct antennatracker name in size_compare_branches.py

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/RC_override.lua, libraries/AP_Scripting/generator/description/bindings.desc
=> AP_Scripting: added set_override method for scripting

Tools/autotest/arducopter.py, Tools/autotest/common.py
=> autotest: add test for landing speed

ArduCopter/mode.cpp, ArduCopter/mode.h
These changes attempt to clarify what is happening with the math here and address: #20311 #20244 #20242
=> Copter: Clarify calculations in get_pilot_desired_lean_angles

ArduCopter/mode_auto.cpp, ArduCopter/mode_guided.cpp
This resolves a potential bug in Copter's Guided and Auto modes where the mode's submode is changed but the submode's initialisation code is not run because of a subsequent sanity check failure.
I have tested this in SITL and while I could reproduce situations where the submode was set without the initialisation being run, this never led to any bad behaviour.  For example, even though Guided mode's takeoff could fail and it would be left in the takeoff submode with an invalid target, it would remain on the ground and would not actually takeoff until another valid takeoff command was sent (e.g. the vehicle stayed safely on the ground).
While this is a potential bug in Copter-4.2, the Guided mode issue it is a real bug in Copter-4.0 (and perhaps 4.1).  The bug can occur if the rangefinder …
=> Copter: Guided and Auto only set submode after all possible failures have been passed

libraries/AP_GPS/examples/GPS_AUTO_test/GPS_AUTO_test.cpp
Hi, Ardupilot community,
This is Bhumil Depani, a new contributor to the open-source community. As I started learning the codebase of Ardpilot, I landed on the "Library Example Sketches" page. There I learned about different-different core libraries of GPS, Inertial sensors, Compass, and Barometer. I also got to know that examples code is not much well documented and commented. So, I added some comments as per my understanding, and is my little effort to make the Ardupilot codebase more readable. As this is my first pull request to the Ardupilot codebase, please fill free to correct anything I missed. Hoping to write real code, which can be used to enhance the Ardupilot codebase in the future.
=> Added comments in libraries/AP_GPS/examples/GPS_AUTO_text/GPS_AUTO_text/GPS_AUTO_test.cpp file

ArduPlane/quadplane.cpp
when rudder disarm is disabled we should allow full yaw control regardless of throttle level. We should also only disable left yaw
when throttle is at zero, as right yaw does not indicate pilot may be trying to disarm
=> Plane: fixed rudder control when ARMING_RUDDER != 2

libraries/AP_HAL_ESP32/targets/partitions.csv
currently only really needed for copter
=> AP_HAL_ESP32: partitions.csv - increase app partition to 3M

libraries/AP_HAL_ChibiOS/hwdef/CarbonixL496/hwdef-bl.dat, libraries/AP_HAL_ChibiOS/hwdef/CarbonixL496/hwdef.dat
CarbonixL496 hwdef file update to integrate below settings
GPS
ADSB
JTAG
LED
Clock Freq
=> Update: AP_Periph Hwdef Carbonix l496

Blimp/Blimp.cpp, Blimp/Blimp.h
=> Blimp: remove land_acel_ef_filter

libraries/AP_HAL_ChibiOS/hwdef/FlywooF745/hwdef.dat
@tridge....missed a couple....
=> hwdef: minimal GPS support for Flywoo boards

libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_NavEKF2/AP_NavEKF2.cpp, libraries/AP_NavEKF2/AP_NavEKF2.h
... remove entirely unused getGyroScaleErrorPercentage method, too
=> Remove instance id from EK2 external interface

Tools/AP_Bootloader/board_types.txt
Tools: added QioTekAdeptF427 board ID
=>  Tools: added QioTekAdeptF427 board ID

libraries/AP_HAL_ChibiOS/hwdef/revo-mini-sd/hwdef.dat
Killing the custom build server
=> hwdef: remove non-ascii character from hwdef

Tools/AP_Periph/can.cpp, Tools/scripts/CAN/fix2_gap.py
we need more time for other threads on these nodes or we will end up dropping GPS frames
=> AP_Periph: fixed GPS dropout on F4 and L4 GPS nodes

libraries/AP_HAL/RCOutput.h, libraries/AP_HAL/tests/test_prescaler.cpp, libraries/AP_HAL_ChibiOS/RCOutput.cpp
Revert to old bitwidths for neopiexl and profiled
Add a proper neopixel test based on required timings
=> Update neopixel bitwidths

Tools/GIT_Test/GIT_Success.txt
I just realized that I confused the name of commit with the name of pull request (which @rmackay9 had changed for me)... 
I thought the commit name was already changed until the old PR is closed...
Super silly, sorry.
=> Tools: add name to Git_Test (retry)

libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.cpp, libraries/AP_Button/AP_Button.cpp, libraries/AP_Camera/AP_Camera.cpp, libraries/AP_LandingGear/AP_LandingGear.cpp, libraries/AP_Notify/AP_Notify.cpp, libraries/AP_RPM/AP_RPM_Params.cpp, libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp, libraries/AP_Relay/AP_Relay.cpp
@rmackay9 per our discussion....the GPIOs page shows how to look up GPIO pin numbers pretty well, I think...
=> Add note to desc's on how to determine GPIO pin numbers

libraries/SITL/SIM_Frame.h, libraries/SITL/SITL.cpp
.... managed to break it twice in short order.
Only tested compilation for CubeOrange.  Did test that the post locations stuff still works for Proximity avoidance
=> Fix SimOnHardware compilation

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_BLHeli/AP_BLHeli.cpp, libraries/AP_BLHeli/AP_BLHeli.h, libraries/AP_HAL/RCOutput.h, libraries/AP_HAL_ChibiOS/RCOutput.cpp, libraries/AP_HAL_ChibiOS/RCOutput.h, libraries/SRV_Channel/SRV_Channel.h, libraries/SRV_Channel/SRV_Channel_aux.cpp
Related PR https://github.com/ArduPilot/ardupilot/pull/20577
=> Correctly observe channel enablement without breaking PWM default behaviour

ArduSub/wscript
I removed duplicated AP_RCMapper.
=> Sub: wscript: remove duplicated AP_RCMapper

ArduCopter/Parameters.cpp, libraries/AP_BattMonitor/AP_BattMonitor.cpp, libraries/AP_RangeFinder/AP_RangeFinder.cpp, libraries/SRV_Channel/SRV_Channel_aux.cpp
.... so we can remove old parameter conversion...
Oct-2014 seems to be the record....
=> Add PARAMETER CONVERSION comments

libraries/AC_AttitudeControl/AC_AttitudeControl.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
This allows for a lua script to do initial VTOL tuning for copters and quadplanes
=> Lua: added PDmod binding for VTOL tuning

ArduCopter/ReleaseNotes.txt, ArduPlane/RC_Channel.cpp, Tools/autotest/arduplane.py, libraries/AP_Airspeed/AP_Airspeed.cpp, libraries/AP_HAL/Device.h, libraries/AP_HAL_ChibiOS/hwdef/CUAVv5-bdshot/README.md, libraries/AP_HAL_ChibiOS/hwdef/CUAVv5/README.md, libraries/AP_HAL_ChibiOS/hwdef/CubeBlack/README.md, libraries/AP_HAL_ChibiOS/hwdef/Durandal/README.md, libraries/AP_HAL_ChibiOS/hwdef/Pixhawk1/README.md, libraries/AP_HAL_ChibiOS/hwdef/Pixhawk4/README.md, libraries/RC_Channel/RC_Channel.cpp, libraries/RC_Channel/RC_Channel.h, libraries/RC_Channel/RC_Channels.cpp, libraries/SRV_Channel/SRV_Channel_aux.cpp, libraries/SRV_Channel/SRV_Channels.cpp
Should we fix this as well?
https://github.com/ArduPilot/ardupilot/pull/19663
https://github.com/ArduPilot/ardupilot/pull/19686
=> Fix auxiliary typo

libraries/SITL/SIM_BattMonitor_SMBus.cpp, libraries/SITL/SIM_BattMonitor_SMBus.h, libraries/SITL/SIM_BattMonitor_SMBus_Generic.cpp, libraries/SITL/SIM_BattMonitor_SMBus_Generic.h, libraries/SITL/SIM_BattMonitor_SMBus_Maxell.cpp, libraries/SITL/SIM_BattMonitor_SMBus_Rotoye.cpp, libraries/SITL/SIM_I2C.cpp
This pulls in just the SITL changes from my smartbatt PR. Tested with #16167
=> SITL: SIM_BattMonitor_SMBus add registers to smartbatts

ArduCopter/Copter.cpp, ArduCopter/Copter.h, ArduCopter/Log.cpp, ArduSub/ArduSub.cpp, ArduSub/Log.cpp, ArduSub/Sub.h, Blimp/Blimp.cpp, Blimp/Blimp.h, Blimp/Log.cpp, Tools/autotest/arducopter.py, libraries/AP_Scheduler/AP_Scheduler.cpp, libraries/AP_Scheduler/AP_Scheduler.h, libraries/AP_Scheduler/PerfInfo.cpp, libraries/AP_Scheduler/PerfInfo.h, libraries/AP_Scheduler/examples/Scheduler_test/Scheduler_test.cpp, libraries/AP_Vehicle/AP_Vehicle.cpp, libraries/AP_Vehicle/AP_Vehicle.h
This moves the various steps in the fast_loops into a task table that then appears in @SYS/tasks.txt
This allows more detailed timing information of the fast_loop to be determined.
```
STABILIZE> Getting @SYS/tasks.txt as -
TasksV2
AP_InertialSensor::update*       MIN=   6 MAX=  15 AVG=   7 OVR=  0 SLP=  0, TOT= 2.1%
Copter::run_rate_controller*     MIN=   9 MAX=  14 AVG=   9 OVR=  0 SLP=  0, TOT= 2.9%
Copter::motors_output*           MIN=  27 MAX=  38 AVG=  29 OVR=  0 SLP=  0, TOT= 8.4%
Copter::read_AHRS*               MIN= 110 MAX= 439 AVG= 151 OVR=160 SLP=  0, TOT=44.0%
Copter::read_inertia*            MIN=   6 MAX=  20 AVG=   6 OVR=  0 SLP=  0, TOT= 2.0%
Copter::check_ekf_reset*         MIN=   3 MAX=  16 AVG=   3 OVR=  0 SLP=  0, TOT= 0.9%
Copter::update_flight_mode*      MIN=  31 …
```
=> Fast loop task table

ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, ArduPlane/ReleaseNotes.txt, ArduPlane/version.h, Rover/release-notes.txt, Rover/version.h, libraries/AC_AttitudeControl/AC_AttitudeControl.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_Compass/AP_Compass_ExternalAHRS.cpp, libraries/AP_Compass/AP_Compass_MSP.cpp, libraries/AP_Compass/AP_Compass_UAVCAN.cpp, libraries/AP_Scripting/applets/VTOL-quicktune.lua, libraries/AP_Scripting/applets/VTOL-quicktune.md, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
final changes for 4.2.0 stable
=> Plane: prepare for 4.2.0 stable release

libraries/AP_Scripting/applets/VTOL-quicktune.lua, libraries/AP_Scripting/applets/VTOL-quicktune.md, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
thanks to Marco for the suggestion
=> AP_Scripting: pause quicktune during pilot input

ArduSub/GCS_Mavlink.cpp, ArduSub/defines.h
=> Sub: GCS_Mavlink: fix depth hold typemask bug

libraries/AP_Logger/AP_Logger_File.cpp
=> AP_Logger: fixed a bug in wrapped log count

ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, ArduPlane/ReleaseNotes.txt, ArduPlane/version.h, Rover/release-notes.txt, Rover/version.h, libraries/AC_AttitudeControl/AC_AttitudeControl.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_Scripting/applets/VTOL-quicktune.lua, libraries/AP_Scripting/applets/VTOL-quicktune.md, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
This is the Copter-4.2.0-rc3 release which brings Copter up-to-date with Plane's 4.2.0 stable release.  The changes included are in the [Copter-4.2 project](https://github.com/ArduPilot/ardupilot/projects/21) (see the 4.2.0-rc3 column)
=> Copter: 4.2.0-rc3 release

Tools/AP_Bootloader/board_types.txt
Tools: added QioTekAdeptF427 and F407 board ID
=> Tools: added QioTekAdeptF427 and F407 board ID

libraries/AP_HAL_ChibiOS/AnalogIn.cpp
need to check new pin not old pin
broken by https://github.com/ArduPilot/ardupilot/pull/18745
=> HAL_ChibiOS: fixed RSSI from IOMCU analog pin 103

ArduPlane/quadplane.cpp
allows for updating of learned FFT freq
=> Plane: update gyro fft throttle

ArduCopter/Copter.cpp, ArduCopter/Copter.h, ArduCopter/Log.cpp, ArduSub/ArduSub.cpp, ArduSub/Log.cpp, ArduSub/Sub.cpp, ArduSub/Sub.h, Blimp/Blimp.cpp, Blimp/Blimp.h, Blimp/Log.cpp, Tools/autotest/arducopter.py, libraries/AP_Compass/AP_Compass.cpp
Follow up to https://github.com/ArduPilot/ardupilot/pull/20643 - moves compass and removes infrastructure
Log output pre/post patches for the new test bits is the same.
=> Move logging of compass ERR flags into AP_Compass

libraries/AP_Mission/AP_Mission.cpp
instead of wrapping we should use MIN with 255, which is closer to
what was requested
=> AP_Mission: improved handling of large LOITER_TURNS

ArduCopter/tuning.cpp
=> ArduCopter : Modifying the case label code

Tools/environment_install/install-prereqs-ubuntu.sh
Co-authored-by: Peter Barker <pbarker@barker.dropbear.id.au>
=> Tools: install aarch64 ARM compiler if required

ArduCopter/mode_loiter.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/AC_AttitudeControl/AC_AttitudeControl_Multi_6DoF.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl_Multi_6DoF.h
This PR fixes the problem where we apply the yaw slew limit in auto mode to loiter.
=> Fix loiter slew bug

libraries/AP_Param/tools/eedump_apparam.c
Fixes a bug of mine from #19084  Thanks @tridge for finding!
=> AP_Param: eedump_apparam fix accessing uninit var

ArduCopter/events.cpp
=> Copter:changed GPS glitch message

ArduPlane/quadplane.cpp
this fixes a case where we can get false positive on the landing detector for quadplanes.
The issue happens if we cross the LAND_DESCEND to LAND_FINAL threshold while pilot repositioning is active, with stale information in landing_detect.lower_limit_start_ms as we don't run should_relax() in LAND_DESCEND
=> Plane: fixed false positive in landing detector

libraries/AP_Logger/AP_Logger_DataFlash.cpp
=> Add W25Q128 variant

.github/workflows/test_coverage.yml
fix coverage reset: unknown terminal type unknown
=> CI: fix coverage reset: unknown terminal type unknown

libraries/AP_OSD/AP_OSD_ParamSetting.cpp
Fixes https://github.com/ArduPilot/ardupilot/issues/20800
=> Update Parameter menu flightmodes for plane and copter

libraries/AP_Motors/AP_MotorsMulticopter.cpp
#20894
I clarified the max comparison by determining min first.
=> AP_Motors:  Resolve Issue 20894

libraries/AP_EFI/AP_EFI.cpp
... including required compilation fix
=> Move mavlink repo reference forward

Rover/Parameters.h, Rover/Rover.h
A lot of this stuff has moved up to AP_Vehicle or is only used in Parameters.h
=> Rover: reduce and move includes

libraries/AP_Scripting/applets/VTOL-quicktune.lua, libraries/AP_Scripting/applets/VTOL-quicktune.md
allows tuning with 2 position switch
also fixes #20906 to only adjust filters for an axis when an axis starts
=> AP_Scripting: added QUIK_AUTO_SAVE option

Tools/autotest/arduplane.py, Tools/autotest/common.py
... also a fix for a flapping test
=> autotest: increase Plane test speedup to 100

AntennaTracker/Tracker.cpp, ArduCopter/Copter.cpp, ArduPlane/ArduPlane.cpp, ArduSub/ArduSub.cpp, Blimp/Blimp.cpp, Rover/Rover.cpp, libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h, libraries/AP_AHRS/AP_AHRS_Backend.cpp
We can have the library do this itself rather than having the vehicles each do it separately.
=> Have AHRS update its own orientation

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_GyroFFT/AP_GyroFFT.cpp, libraries/AP_GyroFFT/AP_GyroFFT.h
Fixes https://github.com/ArduPilot/ardupilot/issues/20884
=> FFT watchdog

libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
saves some flash, cpu and stack to use the structure method instead of send method
saves 1080 bytes on durandal, 348 on MatekF405
update: added static_assert to check if msgs have been extended
=> AP_ESC_Telem: use send_struct mavlink function

libraries/AP_HAL_ChibiOS/UARTDriver.cpp
Fixes #20951 - thanks to @pbreed
=> Correct UART RX stats

Tools/autotest/arducopter.py
- remove pointless elses
- clarify why a test is failing in exception messages
- move variable definitions closer to their use
=> autotest: tidy hover_and_check_matched_frequency method

libraries/AP_FETtecOneWire/AP_FETtecOneWire.cpp, libraries/AP_FETtecOneWire/README.md
This was raised by @peterbarker .
Thanks
=> AP_FETTecOneWire: Fix the recent change of NUM_SERVO_CHANNELS > 24

ArduCopter/config.h, ArduCopter/land_detector.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp
Should fix https://discuss.ardupilot.org/t/airmode-and-throttle-mixing-is-there-a-bug/86419
=> Keep manual throttle mix at zero throttle when airmode is on

Tools/autotest/web-firmware/Tools/FilterTool/filters.js, Tools/autotest/web-firmware/Tools/FilterTool/index.html
Load FLTD from log, and allow for log scale (dB) for attenuation
=> Tools: FilterTool improvements

Tools/scripts/configure_all.py
This just makes it fatal on any command...
=> Tools: configure_all.py: clarify command-line --stop option

AntennaTracker/GCS_Tracker.cpp, ArduSub/GCS_Sub.cpp, Tools/Replay/Replay.cpp, Tools/scripts/build_options.py, libraries/AP_LTM_Telem/AP_LTM_Telem.cpp, libraries/AP_LTM_Telem/AP_LTM_Telem.h, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
=> Add LTM telemetry build option

ArduPlane/mode_qacro.cpp, ArduPlane/quadplane.cpp, ArduPlane/tailsitter.cpp, ArduPlane/tailsitter.h, ArduPlane/tiltrotor.cpp, ArduPlane/transition.h
NFC
while fixing spelling appearing in wiki, just fixed them all
=> Plane: fixed misspellings of 'transition'

libraries/AP_TECS/AP_TECS.cpp
Coding style of if statement is different within one file.
I adapted the ArduPilot coding style.
=> AP_TECS: Unify coding style for if statements

libraries/AP_InertialSensor/AP_InertialSensor_SITL.cpp, libraries/SITL/SITL.cpp, libraries/SITL/SITL.h
makes for more useful testing of notch filters
=> SITL: added harmonics to motor vibration

Tools/autotest/web-firmware/Tools/FilterTool/filters.js
=> Tools: support triple notch in FilterTool

ArduCopter/ReleaseNotes.txt, ArduCopter/version.h
Copter-4.2.2-rc2 release with no changes from 4.2.2-rc1
=> Copter: 4.2.2-rc2 beta

.github/workflows/test_environment.yml, Tools/environment_install/install-prereqs-arch.sh, Tools/environment_install/install-prereqs-ubuntu.sh
This fix our environment install script.
it removes disco and eoan distro that aren't working anymore (failure to update package list)
it fixs old py2 distro that use python-ABCD and not python2-ABCD packages
add explicitly bionic as python2 distro
Fix submodules on archlinux install due to craps permission stuff
Remove xenial that doesn't work anymore with chibios. and some trusty leftover
=> Fix env again

libraries/AP_Scripting/generator/description/bindings.desc
HAL_MOUNT_ENABLED depends on !HAL_MINIMIZE_FEATURES
=> AP_Scripting: fixed SimOnHardware build

libraries/Filter/tests/test_notchfilter.cpp
=> Filter: fixed test_notchfilter for the change in allocate_filters()

libraries/GCS_MAVLink/GCS_Common.cpp
this fixes two issues:
- we are not reporting the sag corrected voltage to GCS when we are sending individual cells
- we don't cope with having more than AP_BATT_MONITOR_CELLS_MAX cells (or 12 for low flash boards, 14 for 2M boards)
it fixes this by distributing the extra voltage over the cells.
This change is particularly important for high cell count DroneCAN smart batteries, where we currently would not handle more than 14 cells and the GCS would display the wrong voltage. Even if the battery itself reports more than 14 cells (max in DroneCAN is 255 cells) then we discard the cells over AP_BATT_MONITOR_CELLS_MAX in the driver.
the PR also cleans up the use of volts vs mVolts for the local variables
=> GCS_MAVLink: improved battery cell monitoring

Tools/ardupilotwaf/ardupilotwaf.py, Tools/ardupilotwaf/boards.py, Tools/autotest/autotest.py, Tools/autotest/common.py, Tools/autotest/pysim/util.py, Tools/autotest/sim_vehicle.py, libraries/AP_HAL_SITL/GPIO.cpp, libraries/AP_HAL_SITL/Scheduler.cpp, libraries/AP_Math/AP_Math.cpp, libraries/AP_Math/AP_Math.h, libraries/AP_NavEKF2/AP_NavEKF2_Logging.cpp, libraries/AP_NavEKF3/AP_NavEKF3_Logging.cpp
This allows enabling of the undefined behavior sanitizer in the build. When enabled you either get printed warnings with file and line number, or the warning and an abort if --ubsan-abort is used
this can be used to find undefined behavior in our code for code paths and values that are tested in SITL
followup PRs will fix the issues
result with test.plane:
```
ubsan error: /libraries/AP_ExternalAHRS/AP_ExternalAHRS_LORD.cpp:295:68 float-cast-overflow:1.65751e+12 is outside the range of representable values of type 'unsigned int'
ubsan error: /libraries/AP_Frsky_Telem/AP_Frsky_Backend.cpp:89:76 float-cast-overflow:-1.99585 is outside the range of representable values of type 'short unsigned int'
ubsan error: /libraries/AP_Frsky_Telem/AP_Frsky_Backend.cpp:89:76 float-cast-overflow:-3.9978 …
```
=> build: added --ubsan and --ubsan-abort options

libraries/AP_Rally/AP_Rally.cpp, libraries/AP_Rally/AP_Rally.h
Also clarify that the argument is in cm AMSL
=> AP_Rally: tidy calculation of nearest rally/home

Tools/autotest/param_metadata/rstemit.py
This is a rehash of #19781 with requested changes. That user went to ghost and the PR closed.
=> Tools: rstemit.py: Change Range to be clearer meaning

libraries/AP_SerialManager/AP_SerialManager.cpp, libraries/AP_SerialManager/AP_SerialManager.h, libraries/AP_Vehicle/AP_Vehicle.cpp, libraries/AP_Vehicle/AP_Vehicle.h, libraries/AP_VideoTX/AP_Tramp.cpp, libraries/AP_VideoTX/AP_Tramp.h
Implement support for the IRC tramp protocol to allow control of VTX pitmode, power and frequency.
This completes our support for VTX control as we already support SmartAudio and CRSF
https://github.com/ArduPilot/ardupilot/issues/20438
=> Tramp VTX Protocol

libraries/AP_RangeFinder/AP_RangeFinder_Benewake_CAN.cpp, libraries/AP_RangeFinder/AP_RangeFinder_Benewake_CAN.h
30m max radar.
This has been tested on a CUAVv5
=> AP_RangeFinder: support Benewake H30 radar

ArduCopter/mode_rtl.cpp
I would adapt the else statement to the style in the file.
=> Copter: Append WHITE SPACE to the else statement

Tools/FilterTestTool/run_filter_test.py
=> Tools: fixed the filter test tool for instance IMU data

libraries/AP_Soaring/AP_Soaring.h, libraries/AP_Soaring/SpeedToFly.h, libraries/AP_Soaring/Variometer.cpp, libraries/AP_Soaring/Variometer.h
Fix https://github.com/ArduPilot/ardupilot/issues/21043#issuecomment-1183566102 reported on gcc-12
=> Feature/fix #21043

Tools/autotest/common.py
Broken under Python2.
Also fix some flake8 problems under flake8 under Python2
=> autotest: comment out unused context_start_custom_binary method

Tools/autotest/arduplane.py, Tools/autotest/common.py
disarming via mavlink can fail if we think we're still moving
=> autotest: wait for Plane to slow down after frsky test

.github/workflows/test_chibios.yml, ArduPlane/ArduPlane.cpp, ArduPlane/GCS_Mavlink.cpp, ArduPlane/Parameters.cpp, ArduPlane/Parameters.h, ArduPlane/commands_logic.cpp, ArduPlane/mode_qloiter.cpp, ArduPlane/quadplane.cpp, ArduPlane/servos.cpp, Tools/autotest/test_build_options.py, Tools/scripts/build_ci.sh, Tools/scripts/build_options.py, libraries/AP_ICEngine/AP_ICEngine.cpp, libraries/AP_ICEngine/AP_ICEngine.h, libraries/AP_ICEngine/AP_ICEngine_config.h
=> Add and use AP_ICENGINE_ENABLED

Tools/autotest/common.py
Doing these in parallel means we don't need to parse the large file multiple times
=> autotest: make search of dflog for required messages faster

libraries/AP_GPS/AP_GPS.cpp
As discussed with @tridge last week in the EU dev call, this PR is the first of a series of changes that we'd like to upstream from our own fork of ArduPilot that we use for drone light shows to make it easier to maintain a parallel fork.
This PR adds an extra bit in the `GPS_DRV_OPTIONS` parameter that allows the user to tweak how the GPS library handles duplicate packets during RTCM injection.
Injected RTCM packets are potentially fragmented over multiple MAVLink packets, and the GPS library contains a reassembly buffer that stores already received fragments until all the fragments are received. Fragments are identified by fragment indices; fragments belonging to the same RTCM packet share a common sequence number in the protocol. However, the current `master` version drops the entire …
=> AP_GPS: Do not drop reassembly buffer for injected packets when a dupllicate fragment is received

Tools/autotest/common.py
we don't need to be particularly tight on timing here
=> autotest: increase time allowed for mission download

libraries/AP_Landing/AP_Landing.cpp
change LAND_ABORT_THR param docs to match code and wiki of 90%
=> AP_Landing: change LAND_ABORT_THR param docs to match code and wiki of 90%

libraries/AP_GPS/AP_GPS.cpp, libraries/AP_GPS/AP_GPS_UBLOX.h
=> AP_GPS: correct compilation when all serial backends compiled out

Tools/scripts/build_autotest.sh
Nobody is ever reading these
report was not called
=> autotest: remove report of pull failure

ArduCopter/mode_auto.cpp
This fixes a bug introduced in the previous patch and 2 problems previously present.
This also fixes #12570
=> Copter: Fix Payload Place Bug

ArduPlane/Parameters.cpp
NFC last cleanup of Plane logging
=> Plane: change CURRENT to BATT_MON in log bitmask metadata

libraries/AP_EFI/AP_EFI_Serial_Lutan.cpp
=> AP_EFI: prevent flood of Lutan serial port

Tools/scripts/build_ci.sh
=> Tools: build_ci.sh: correct quoting of space-containing value

ArduPlane/quadplane.cpp
if the user hasn't set TECS_LAND_ARSPD then we can use an airspeed
between ARSPD_FBW_MIN and TRIM_ARSPD_CM when on approach
this also fixes landing_desired_closing_velocity() to never go above
the landing target speed, so we don't try to speed up if we are
starting the landing sequence too early
=> Plane: improve target airspeed in landing approach

libraries/AP_Landing/AP_Landing_Slope.cpp
some low hanging fruit to bring them under logging rate control
=> Change logging to be designated as streaming

Tools/autotest/web-firmware/Tools/FilterTool/filters.js
=> Tools: web-filter save use comma instead of =

Tools/autotest/arducopter.py, Tools/autotest/common.py
With behaviour 0 anbd typemask specifying ignore yaw/yaw_cds the yaw should reamin fixed
=> autotest: add test for WP_YAW_BEHAVIOUR 0

Tools/autotest/arducopter.py, Tools/scripts/build_options.py, libraries/AP_HAL/SIMState.cpp, libraries/AP_HAL/SIMState.h, libraries/AP_HAL_SITL/SITL_State.cpp, libraries/AP_HAL_SITL/SITL_State.h, libraries/AP_RangeFinder/AP_RangeFinder.cpp, libraries/AP_RangeFinder/AP_RangeFinder.h, libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp, libraries/AP_RangeFinder/AP_RangeFinder_TeraRanger_Serial.cpp, libraries/AP_RangeFinder/AP_RangeFinder_TeraRanger_Serial.h, libraries/SITL/SIM_RF_TeraRanger_Serial.cpp, libraries/SITL/SIM_RF_TeraRanger_Serial.h
New rangefinder....sample will be sent to me for testing in early July...@tridge will share spec directly to you...would appreciate a cursory review since this is my first driver....thanks
=> AP_RangeFinder: Add TeraRanger Neo Rangefinder

libraries/AP_Motors/AP_MotorsMatrix.cpp, libraries/AP_Motors/AP_MotorsMatrix.h
Allows searching for frame type build options in the ELF file
=> AP_Motors: refactor motor matrix to cleanup and make symbols

ArduPlane/AP_Arming.cpp, ArduPlane/GCS_Mavlink.cpp, ArduPlane/altitude.cpp, ArduPlane/commands_logic.cpp, ArduPlane/events.cpp, ArduPlane/mode_qloiter.cpp, ArduPlane/mode_qstabilize.cpp, ArduPlane/navigation.cpp, ArduPlane/quadplane.cpp, ArduPlane/quadplane.h, ArduPlane/servos.cpp, ArduPlane/system.cpp, ArduPlane/tailsitter.cpp, ArduPlane/tiltrotor.cpp
A little clean up with a helper function. Broken out from https://github.com/ArduPilot/ardupilot/pull/21289
=> Plane: Quadplane: add option_is_set helper for Q_OPTIONS

ArduCopter/AP_Arming.cpp, ArduCopter/AP_Arming.h, ArduPlane/AP_Arming.cpp, ArduPlane/AP_Arming.h, Tools/autotest/arducopter.py, Tools/autotest/arduplane.py, Tools/autotest/common.py, Tools/autotest/quadplane.py, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.h, libraries/AP_Mission/AP_Mission.cpp, libraries/AP_Mission/AP_Mission.h, libraries/AP_Terrain/AP_Terrain.cpp, libraries/AP_Terrain/AP_Terrain.h, libraries/AP_Terrain/TerrainGCS.cpp
Both tridge and I thought the "all loaded" stuff was present for Plane....
=> Move arming checks for terrain-all-loaded up to common Arming library

Tools/AP_Periph/can.cpp, libraries/AP_GPS/AP_GPS_UAVCAN.cpp, libraries/AP_OpenDroneID/AP_OpenDroneID.cpp, libraries/AP_OpenDroneID/AP_OpenDroneID.h
fixes for minor issues that showed up in main PR
=> AP_OpenDroneID: minor updates

libraries/AP_HAL_SITL/SITL_State.cpp
If SITL is not receiving any sitl rc input (so _sitl_rc_in.recv(...) is allways returns -1 then the bind-values code would never be crossed so the RC input values would remain at their initialisation values rather than honouring the SIM_RC_FAIL setting which says they should go to bind values (notably throttle-to-950)
=> AP_HAL_SITL: correct bind-value SIM_RC_FAIL handling

Tools/scripts/extract_features.py
Also switch to keying off the define in build_options.py rather than the label as the label is not unique and we'd have to munge them badly (and enforce shape) where we can just use the ArduPilot defines which are all pretty well-formed.
From
```
self.features = [
('AP_AIRSPEED_ENABLED', 'AP_Airspeed::AP_Airspeed',),
('AP_AIRSPEED_{type}_ENABLED', 'AP_Airspeed_(?P<type>.*)::AP_Airspeed_(?P=type)',),
('HAL_ADSB_ENABLED', 'AP_ADSB::AP_ADSB',),
('HAL_EFI_ENABLED', 'AP_EFI::AP_EFI',),
('BEACON_ENABLED', 'AP_Beacon::AP_Beacon',),
('HAL_TORQEEDO_ENABLED', 'AP_Torqeedo::AP_Torqeedo'),
]
```
we get
```
pbarker@fx:~/rc/ardupilot(pr/extract-features-fixes)$ ./Tools/scripts/extract_features.py build/CubeOrange/bin/arducopter 
/usr/lib/python3.10/subprocess.py:956: RuntimeWarning: line buffering …
```
=> Tools: extract_features.py: allow for regular expressions for features

libraries/AP_OpenDroneID/AP_OpenDroneID.cpp
this fixes DroneCAN operation without a mavlink channel set
=> AP_OpenDroneID: fixed checking of payload space

Tools/ardupilotwaf/boards.py, libraries/AP_OpenDroneID/AP_OpenDroneID.cpp, libraries/AP_OpenDroneID/AP_OpenDroneID.h, wscript
and allow for --enable-opendroneid in configure
=> OpenDroneID: added an operator data lost message

AntennaTracker/Tracker.cpp, ArduCopter/Copter.cpp, ArduCopter/Copter.h, ArduPlane/ArduPlane.cpp, ArduSub/ArduSub.cpp, Blimp/Blimp.cpp, Rover/Rover.cpp, libraries/AP_Vehicle/AP_Vehicle.cpp
`COMPASS_CAL_ENABLED` still doesn't work. but at least it's closer.
=> Move Scheduler call to compass-cal-update up to AP_Vehicle

Tools/autotest/arduplane.py
We now have reliable terrain in autotest
=> autotest: re-enable terrain loiter check

Tools/autotest/quadplane.py
ICE provides forward thrust, which can make us think we're flying
=> autotest: force-disarm quadplane after ICEngine test

Tools/scripts/build_autotest.sh
=> Tools: build_autotest.sh: sync submodules from new master not old

ArduCopter/AP_Arming.cpp
I have voice notification with a propo.
I have clear flight mode notification.
=> Copter: Clarify the mode

Tools/autotest/common.py, Tools/autotest/rover.py
4 would seem to have been just a magic number and could be missed on faster speedups
=> autotest: correct Rover DriveMission test

Tools/autotest/common.py, Tools/scripts/board_list.py
Could be causing rate to be zero on autotest server
=> autotest: cast packet count to floast before determining rate

Tools/autotest/pysim/vehicleinfo.py, Tools/autotest/sim_vehicle.py, libraries/AP_GPS/AP_GPS_UAVCAN.cpp, libraries/AP_GPS/AP_GPS_UAVCAN.h
detect vertical velocity using first non-zero value
also adds --can-gps option to sim_vehicle.py for simplified testing of DroneCAN
=> GPS: fixed DroneCAN GPS without vertical velocity

Tools/autotest/pysim/util.py
Mostly just whitespace changes.
=> autotest: make pysim/util.py AP_FLAKE8_CLEAN

Tools/autotest/common.py
Removes several block-forever calls
=> autotest: use assert_receive_message

Tools/scripts/board_list.py
=> Pixhawk 1M bdshot

.github/workflows/cygwin_build.yml, Tools/ardupilotwaf/boards.py, libraries/AP_OpenDroneID/AP_OpenDroneID_DroneCAN.cpp
should be now with the structure changes
=> waf: allow opendroneid on sitl on cygwin and macos

Tools/Replay/check_replay.py
Helps to filter output from the tool where a field is diverging and you don't care.
=> Tools: check_replay.py: add --ignore-field option

ArduCopter/Parameters.cpp
=> Copter: correct DISARM_DELAY metadata

Tools/autotest/sim_vehicle.py
=> Tools: fixed sim_vehicle.py with -n

Tools/environment_install/install-prereqs-arch.sh, Tools/environment_install/install-prereqs-mac.sh, Tools/environment_install/install-prereqs-ubuntu.sh, Tools/environment_install/install-prereqs-windows-andAPMSource.ps1, Tools/environment_install/install-prereqs-windows.ps1
Close https://github.com/ArduPilot/ardupilot/issues/21538
=> Tools: add dronecan to install scripts

libraries/AP_SerialManager/AP_SerialManager.cpp
=> AP_SerialManager: generalize EFI serial protocol name

Tools/autotest/common.py
... progress is no longer static and hasn't been for years
=> autotest: remove global variable

Tools/autotest/arduplane.py
=> autotest: disable SpeedToFly McReady tests

Tools/autotest/arduplane.py
ground interactions cause fluctuations
=> autotest: fix airspeed driver test mismatch at end of mission

ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, ArduPlane/ReleaseNotes.txt, ArduPlane/version.h, Rover/release-notes.txt, Rover/version.h, libraries/GCS_MAVLink/GCS_Common.cpp
This is the same as the Copter-4.2.3 release (https://github.com/ArduPilot/ardupilot/pull/21564)
=> Rover: 4.2.3 release

libraries/AC_Fence/AC_PolyFence_loader.cpp, libraries/AC_Fence/AC_PolyFence_loader.h, libraries/AC_Fence/LogStructure.h, libraries/AP_Logger/AP_Logger.cpp, libraries/AP_Logger/AP_Logger.h, libraries/AP_Logger/AP_Logger_Backend.cpp, libraries/AP_Logger/AP_Logger_Backend.h, libraries/AP_Logger/LogStructure.h, libraries/AP_Logger/LoggerMessageWriter.cpp, libraries/AP_Logger/LoggerMessageWriter.h
Currently there is no record of any loaded fence in the log. This adds a message writer like those for rally and mission. 
Fixes #20213
=> Logger: log polygon fence points

libraries/AP_ESC_Telem/AP_ESC_Telem.cpp, libraries/AP_Vehicle/AP_Vehicle.cpp
Follow up to https://github.com/ArduPilot/ardupilot/pull/21370
=> Don't provide zero udpates for ESCs that have never been used

libraries/AP_RPM/AP_RPM.cpp, libraries/AP_RPM/AP_RPM.h, libraries/AP_RPM/AP_RPM_Params.cpp, libraries/AP_RPM/RPM_Generator.cpp, libraries/AP_RPM/RPM_Generator.h
useful for notch filtering of generator vibration
=> AP_RPM: added AP_Generator support

Tools/scripts/generate_manifest.py
should help solve loading in MissionPlanner
https://github.com/ArduPilot/MissionPlanner/issues/2934
=> Tools: added Holybro 6C/6X px4 USB IDs

ArduCopter/mode_auto.cpp
This PR helps address a problem where precision place can detect touch down prematurely. The existing code based the hover throttle and decent throttle based on a single reading. This PR replaces this with the minimum reading over 1 second.
=> Copter: Payload Place: Improve touchdown test

Tools/scripts/extract_features.py, Tools/scripts/generate_features_txt_files.py
(built on top of another PR which does some more on extract_features.py)
=> Tools: add generate_features_txt_files.py 

libraries/AP_Common/AP_Common.h, libraries/AP_ExternalAHRS/AP_ExternalAHRS_LORD.cpp, libraries/AP_Frsky_Telem/AP_Frsky_Backend.cpp, libraries/AP_HAL_SITL/SITL_State.cpp, libraries/AP_MSP/AP_MSP_Telem_Backend.cpp, libraries/AP_Math/AP_Math.cpp, libraries/AP_Math/AP_Math.h, libraries/Filter/ModeFilter.cpp, libraries/SITL/SIM_IntelligentEnergy24.cpp
undefined behavior sanitizer found several issues
=> Fixed from using --ubsan in autotest

libraries/AP_RangeFinder/AP_RangeFinder_Benewake.cpp
this impacts the TF03 180m lidar
=> AP_Rangefinder: fixed out of range issue with benewake uart lidars

ArduCopter/AP_Arming.cpp, ArduCopter/AP_Arming.h, ArduPlane/AP_Arming.cpp, libraries/AP_Motors/AP_MotorsCoax.h, libraries/AP_Motors/AP_MotorsHeli.cpp, libraries/AP_Motors/AP_MotorsHeli.h, libraries/AP_Motors/AP_MotorsMulticopter.cpp, libraries/AP_Motors/AP_MotorsMulticopter.h, libraries/AP_Motors/AP_MotorsSingle.h, libraries/AP_Motors/AP_Motors_Class.cpp, libraries/AP_Motors/AP_Motors_Class.h
Moves motors pre arms to AP Motors. Also adds a arming check for that all expected motors are setup.
=> AP_Motors: add pre-arm

ArduCopter/Copter.cpp, ArduCopter/Copter.h, ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduCopter/mode_acro.cpp, ArduCopter/mode_stabilize.cpp, ArduCopter/takeoff_check.cpp, Tools/autotest/arducopter.py, libraries/AP_ESC_Telem/AP_ESC_Telem.cpp, libraries/AP_ESC_Telem/AP_ESC_Telem.h, libraries/AP_ESC_Telem/AP_ESC_Telem_Backend.cpp, libraries/AP_ESC_Telem/AP_ESC_Telem_Backend.h, libraries/AP_ESC_Telem/AP_ESC_Telem_SITL.cpp, libraries/AP_Motors/AP_MotorsMulticopter.cpp, libraries/AP_Motors/AP_Motors_Class.cpp, libraries/AP_Motors/AP_Motors_Class.h, libraries/SITL/SITL.cpp, libraries/SITL/SITL.h
Alternative implementation of https://github.com/ArduPilot/ardupilot/pull/21223
=> Copter: takeoff check that motors are spinning at TKOFF_RPM_MIN 

Tools/AP_Periph/can.cpp, Tools/ardupilotwaf/boards.py
Requires https://github.com/dronecan/libcanard/pull/10
=> Add Redundant CAN bus support in AP_Periph

Tools/scripts/generate_manifest.py
=> Scripts: add 2nd CubeOrange BL usbid

Tools/environment_install/install-prereqs-mac.sh
=> Tools: Check if version exist before installing it

Tools/autotest/autotest.py, Tools/autotest/common.py
... and stop using run_tests entrypoint to the AutoTest objects as it does cause confusion
=> autotest: correct running of single test

Tools/autotest/autotest.py
=> autotest: correct type-check

libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/MissionItemProtocol.cpp, libraries/GCS_MAVLink/MissionItemProtocol.h
Hopefully we can remove the older code in a future release.
=> GCS_MAVLink: add warnings if older messages used

ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, ArduPlane/ReleaseNotes.txt, ArduPlane/version.h, Rover/release-notes.txt, Rover/version.h, Tools/autotest/arducopter.py, Tools/autotest/common.py, libraries/AP_ESC_Telem/AP_ESC_Telem.cpp, libraries/AP_ESC_Telem/AP_ESC_Telem.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/esc_rpm_scale.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/SITL/SIM_FlightAxis.cpp
This is the Copter and Rover 4.3.0-beta1 release which is master at the moment but may be rebased after tomorrow's dev call.
For the release notes I went through the last 30 pages of merged PRs ([starting about here](https://github.com/ArduPilot/ardupilot/pulls?page=30&q=is%3Apr+is%3Aclosed)) but I undoubtedly missed some enhancements and bug fixes so please feel free to comment on this PR or PM me directly with any items I've missed.  Ideally include some user understandable comment on the change that I can add to the release notes.
=> Copter: 4.3.0-beta1 release

ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, ArduPlane/ReleaseNotes.txt, ArduPlane/version.h, Rover/release-notes.txt, Rover/version.h, Tools/autotest/arducopter.py, Tools/autotest/common.py, libraries/AP_ESC_Telem/AP_ESC_Telem.cpp, libraries/AP_ESC_Telem/AP_ESC_Telem.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/esc_rpm_scale.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/SITL/SIM_FlightAxis.cpp
This is exactly the same as the Copter-4.3.0-beta1 release https://github.com/ArduPilot/ardupilot/pull/21705
=> Rover: 4.3.0-beta1 release

ArduPlane/GCS_Mavlink.cpp, ArduPlane/Log.cpp, ArduPlane/Plane.h, ArduPlane/defines.h
This is a duplicate of the data logged into "MAVC"
=> Plane: remove logging of CMDI

libraries/AP_RPM/RPM_HarmonicNotch.cpp
Fixes https://github.com/ArduPilot/ardupilot/issues/20898
=> Fix reporting of RPM from the harmonic notch

libraries/SRV_Channel/SRV_Channels.cpp
as discussed with @peterbarker, it's not only Auxilary o/p but affects the main o/p as well.
=> SRV_Channels.cpp: small correction

Tools/environment_install/install-prereqs-windows-andAPMSource.ps1, Tools/environment_install/install-prereqs-windows.ps1
Adds pexpect to cygwin install as it is required to run
=> Tools: cygwin install script add pexpect

libraries/AP_Scripting/examples/ship_vel_match.lua
match velocity of the vehicle from when last disarmed
=> AP_Scripting: added example script for ship takeoff vel match

Tools/autotest/rover.py
Race condition where we can get too far away to see landing target
=> autotest: use guided mode to move Rover away for Dock test

libraries/SITL/SIM_BattMonitor_SMBus_Rotoye.h
Just updates the SIM_ROTOYE component I forgot about.
=> SITL: SIM_Rotoye update TEMP_EXT Register

libraries/AP_Scripting/examples/plane_guided_follow.lua
very simple, just enough to show how to do it
=> AP_Scripting: simple script for plane GUIDED follow

ArduCopter/APM_Config.h, ArduCopter/Copter.h, ArduCopter/Parameters.cpp, ArduCopter/config.h, ArduCopter/mode_rtl.cpp, ArduSub/Parameters.cpp, ArduSub/Sub.h, ArduSub/config.h, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Filesystem/AP_Filesystem_Mission.cpp, libraries/AP_Terrain/AP_Terrain.cpp, libraries/AP_Terrain/TerrainMission.cpp, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/MissionItemProtocol_Rally.cpp, libraries/GCS_MAVLink/MissionItemProtocol_Rally.h
Eliminate AC_RALLY define while we're there.
=> Correct compilation when fence/rally compiled out

libraries/AP_HAL_Linux/UARTDevice.cpp
The current glibc-based UART code using `termios.h` and `cfsetspeed()` isn't (usually) capable of setting baudrates outside the standard set. I discovered this on a Beaglebone Blue trying to use a ELRS (CRSF) RX which wants 416666 baud. The existing call to `cfsetspeed()` was failing silently in this case (I observed with `stty` that the port was remaining at 115200 throughout the RC protocol search).
Using the Linux-specific ioctl to set custom bauds using `CBAUDEX` fixed the issue. I also added some rudimentary error logging which wasn't present originally.
I note that the SITL `UART_utils.cpp` already uses this ioctl, though is using a different option to set a custom baud (`tc.c_cflag |= BOTHER`). I'm not sure if it's worth attempting a consolidation of Linux serial handling code …
=> AP_HAL_Linux: Support "non-standard" baudrates on UART

Tools/AP_Periph/ReleaseNotes.txt, Tools/AP_Periph/version.h, libraries/AP_Compass/AP_Compass_Backend.cpp
fixes compass diagonal scaling
=> AP_Periph: prepare for 1.4.1 release

libraries/AP_GPS/AP_GPS.cpp, libraries/SITL/SIM_GPS.cpp, libraries/SITL/SIM_GPS.h
Closes https://github.com/ArduPilot/ardupilot/issues/21771
=> AP_GPS: cycle through baud rates for SBF/GSOF/NOVA/SITL

Tools/autotest/arducopter.py
Uses a new kwarg to `watch_altitude_maintained` to explicitly use gps alt.
Reverting a fix for the problem this test ensures never happens again yields this output now:
```
AT-0019.0: Waiting for Altitude=601.28 with accuracy 2.00
AT-0019.1: Altitude=603.83 (got 601.280000 +- 2.000000)
AT-0019.2: Altitude=603.40 (got 601.280000 +- 2.000000) (maintain=1.2/10.0)
AT-0019.4: Altitude=601.80 (got 601.280000 +- 2.000000) (maintain=2.4/10.0)
AT-0019.5: Altitude=599.97 (want 601.280000 +- 2.000000)
AT-0019.7: Altitude=598.16 (want 601.280000 +- 2.000000)
AT-0019.8: Altitude=596.66 (want 601.280000 +- 2.000000)
AT-0019.9: Altitude=594.85 (want 601.280000 +- 2.000000)
AT-0020.1: Altitude=593.06 (want 601.280000 +- 2.000000)
AT-0020.2: Altitude=591.26 (want 601.280000 +- 2.000000)
AT-0020.4: …
```
=> autotest: use new altitude_source keyword  in EKF/GPS test

Tools/autotest/ardusub.py
This addresses an issue I've seen in stable where changing modes causes the vehicle to gain depth.
=> Sub: add test to make sure changing modes does not cause altitude changes

libraries/SITL/SIM_SerialDevice.cpp, libraries/SITL/SIM_SerialDevice.h
Recently, a process for the same purpose was added.
The added process is the same.
I made the method.
=> SITL: Make the same process into a method

libraries/AP_Compass/AP_Compass_Calibration.cpp
.... use a switch statement so we don't make this mistake again
=> AP_Compass: send report if we are in the BAD_RADIUS state

.github/workflows/test_chibios.yml, Tools/scripts/build_bootloaders.py, Tools/scripts/build_ci.sh, libraries/AP_HAL_ChibiOS/hwdef/MatekF405-bdshot/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/Pixhawk1-1M/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro-bdshot/hwdef.dat
this is part of the 4.3.0beta2 release to get 3 boards under flash limit
=> hwdef: reduce flash usage to allow build

libraries/AP_Vehicle/AP_Vehicle.cpp
this can happen with plane with Q_ENABLE=0
=> AP_Vehicle: check for motors being nullptr

.github/workflows/test_size.yml, Tools/scripts/extract_features.py
This will allow us to see if a feature has been inadvertently removed.
For Plane only ATM
=> .github: feature-compare PR branch vs master

Tools/Frame_params/QuadPlanes/Foxtech_Altair370.parm
a really interesting and high performance quadplane
=> Tools: added parameters for Foxtech Altair 370

.github/workflows/test_size.yml
prevent errors showing up on master
=> CI: only run test_size on a pull request

ArduCopter/AP_Arming.cpp, libraries/RC_Channel/RC_Channel.h
=> Copter: RC override arming check fix.

libraries/AP_Scripting/applets/Hexsoon LEDs.lua, libraries/AP_Scripting/applets/Hexsoon LEDs.md
Adds a script setup for the LEDs on the Hexsoon EDU450
https://youtu.be/X-kGiXX4AKU
=> AP_Scripting: applets: add Hexsoon LEDs script

ArduPlane/ArduPlane.cpp, ArduPlane/Log.cpp, ArduPlane/Plane.h
log the target alt we pass into TECS to help debug a CRUISE height issue
for #21984
=> Plane: log TECS target alt

libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
=> AC_AttitudeControl: remove duplicate `_attitude_target.normalize()`

libraries/AP_Soaring/AP_Soaring.cpp
Corrects and expands metadata for SOARING speed parameters
=> AP_SOARING: correct metadata for speed params

libraries/AP_Logger/LoggerMessageWriter.cpp, libraries/AP_Logger/LoggerMessageWriter.h
fixes https://github.com/ArduPilot/ardupilot/issues/21986
Tested on CubeOrange
=> AP_Logger: MessageWriter: SysInfo: write RCOut string

ArduPlane/Parameters.cpp, ArduPlane/Plane.h, ArduPlane/altitude.cpp, ArduPlane/navigation.cpp
Regarding issue #17019. Added ALT_FBWCM_MAX param for max altitude Constraint in FBWB. 
Closes #17019
=> Plane: Max altitude for FBWB

libraries/AP_HAL_ChibiOS/hwdef/BeastF7/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/BeastF7v2/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/MatekF405-Wing/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/MatekF405/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/omnibusf4/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro/hwdef.dat
this buys us about 20k of flash
=> hwdef: use minimal GPS driver (ublox only) on low flash boards

ArduCopter/Parameters.h, ArduCopter/RC_Channel.cpp
We have an explicit define for this mode now
=> Copter: correct defines gating flowhold mode

libraries/AP_Airspeed/AP_Airspeed.cpp
=> AP_Airspeed: generalize ARSPD_BUS metadata

ArduPlane/Parameters.cpp
reference #@21159   user had some confusion...metadata not quite exact
wiki also expanded a bit
=> Plane:add info to LEVEL_ROLL_LIMIT description

libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp, libraries/AP_InertialSensor/AP_InertialSensor_Invensense.h
…M20602"
This reverts commit 05f8e3c18d164ffe3766835786e67aae3a235b61.
this leads to bad IMU data on ICM20602
=> Revert "AP_InertialSensor: disable temperature based fifo check"

ArduCopter/Copter.cpp, ArduCopter/Copter.h, ArduCopter/mode.h, ArduCopter/mode_auto.cpp, ArduPlane/Attitude.cpp, ArduPlane/Plane.h, ArduPlane/commands_logic.cpp, Rover/Rover.cpp, Rover/Rover.h, Rover/mode.h, Rover/mode_auto.cpp, libraries/AP_Scripting/examples/Aerobatics/Missions/plane_aerobatics.lua, libraries/AP_Scripting/examples/Aerobatics/Trajectory/plane_aerobatics.lua, libraries/AP_Scripting/examples/Aerobatics/Trajectory/view_paths.py, libraries/AP_Scripting/examples/copter-fast-descent.lua, libraries/AP_Scripting/examples/copter-nav-script-time.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Vehicle/AP_Vehicle.h
=> Pr trajectory improvements

ArduPlane/system.cpp
we want to allow all landing sequence mode changes
=> Plane: cover more cases in fence breach mode change

libraries/AP_Airspeed/AP_Airspeed.cpp
=> AP_Airspeed: add instance to hygrometer logging

libraries/AP_Scripting/lua_bindings.cpp
This moves to a simpler buffer scheme more like that we user in logger. This saves a little flash and is about 1/3rd faster.
The goal of this was to track down the cause of a watchdog if this script is run and then scripting is restarted:
```
logger.write('A', 'A', 'b', 1)
```
However it doesn't fix.....
=> AP_Scripting: logging: move to char buffer from lua buffer

libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
=> Ensure that hardware AAF and notch filter are enabled on 42605 and 42609

ArduCopter/GCS_Mavlink.cpp, ArduPlane/GCS_Mavlink.cpp, Rover/GCS_Mavlink.cpp, libraries/AP_EFI/AP_EFI.cpp, libraries/AP_Scripting/drivers/EFI_HFE.lua, libraries/AP_Scripting/drivers/EFI_HFE.md, libraries/AP_Scripting/drivers/EFI_SkyPower.lua, libraries/AP_Scripting/drivers/EFI_SkyPower.md
and add documentation for the SkyPower and HFE CAN EFI drivers
=> EFI: support copter, heli and rover with EFI CAN scripting drivers

Tools/autotest/param_metadata/mdemit.py
=> Sub 4.1 improve param docs generation

ArduPlane/Parameters.cpp
=> Plane: clarify ALT_HLD_FBWCM description

ArduCopter/ReleaseNotes.txt, ArduCopter/version.h
This is the Copter-4.3.0 official release which is the same as the final -beta4.
The full list of enhancements and bug fixes is in [this project](https://github.com/ArduPilot/ardupilot/projects/25)
=> Copter: 4.3.0 official release

.github/workflows/cygwin_build.yml
workflow is currently failing in CI, attempt to work out why
=> github: use cygwin installer action in place of chocolatey

libraries/AP_Scripting/examples/Aerobatics/Trajectory/plane_aerobatics.lua
allows alignment to position within maneuver frame
=> AP_Scripting: added straight_align path primitive

libraries/AP_Scripting/examples/Aerobatics/Trajectory/plane_aerobatics.lua
needs ground course to account for wind
=> AP_Scripting: fixed initial ground course in aerobatic tricks

ArduCopter/autoyaw.cpp, ArduCopter/defines.h, ArduCopter/mode.cpp, ArduCopter/mode.h, ArduCopter/mode_auto.cpp, ArduCopter/mode_circle.cpp, ArduCopter/mode_guided.cpp, ArduCopter/mode_land.cpp, ArduCopter/mode_rtl.cpp, ArduCopter/mode_smart_rtl.cpp, ArduCopter/takeoff.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.h
A WIP of what some auto yaw refactoring might look like.
Not tested at all, I'm fairly sure this now allows pilot override in all cases, so that would need to be fixed, possibly by passing a bool.
Is it worth it? ~~looks like flash cost will be at least 2K~~ This does make it easier to pull out auto yaw to its own library at some point so it could be shared between copter, quadplane, blimp and sub (maybe omni rover too).
I tend to think this is a nice improvement, however it ~~quite a bit of flash and~~ will need lots of testing as it touches most every mode.
=> Copter: Autoyaw updates

ArduPlane/Attitude.cpp, ArduPlane/Parameters.cpp, ArduPlane/Plane.h, ArduPlane/mode_acro.cpp, ArduPlane/mode_qacro.cpp
when ACRO_LOCKING=2 this implements a quaternion based ACRO controller, which allows for accurate rolls and knife edge
=> Plane: implement quaternion based ACRO mode

ArduPlane/Attitude.cpp, ArduPlane/Plane.h
this locks the attitude at exactly the stick release position on each axis
thanks to Adrian Nagy for feedback
=> Plane: zero error on release of sticks

libraries/AP_Scripting/examples/Aerobatics/Trajectory/README.md, libraries/AP_Scripting/examples/Aerobatics/Trajectory/plane_aerobatics.lua
=> AP_Scripting: added airshow

libraries/AP_Logger/LogStructure.h, libraries/AP_Scripting/lua_scripts.cpp, libraries/AP_Scripting/lua_scripts.h
This give us a little more insight into where memory is being used.
=> AP_Scripting: log memory cost of initial load and add debug print for state memory cost

libraries/AP_Scripting/examples/Aerobatics/Trajectory/plane_aerobatics.lua
added AEROM_KD_ANG as the side slip angle needed in knifeedge
=> AP_Scripting: improved knifeedge performance in aerobatics

libraries/AP_HAL/SIMState.cpp
=> AP_HAL: add missing include for APM_BUILD_TYPE

libraries/AP_Scripting/examples/Aerobatics/Trajectory/plane_aerobatics.lua
=> AP_Scripting: F3A path adjustments

libraries/AP_Logger/AP_Logger.cpp, libraries/AP_Logger/AP_Logger.h, libraries/AP_Logger/AP_Logger_Backend.cpp, libraries/AP_Scripting/lua_bindings.cpp
This fixes this valgrind issue, https://github.com/ArduPilot/ardupilot/issues/21946#issuecomment-1277585156
But not the crash....
=> AP_Logger: scripting log format allocation fix

libraries/AP_Scripting/examples/Aerobatics/Trajectory/plane_aerobatics.lua, libraries/AP_Scripting/examples/Aerobatics/Trajectory/trick72.txt
this allows for complex sequences to be defined in a file like "trick72.txt"
the example shows how it is done
=> AP_Scripting: allow aerobatic sequences to load from a txt file

libraries/AP_GPS/AP_GPS_UAVCAN.cpp
if we have two CAN GPS on different can drivers we need to inject to both
tested with dual F9P FreeFlyRTK AP_Periph GPS on Pixhawk6X
=> AP_GPS: fixed injection of RTCM on 2 different CAN buses

libraries/AP_Camera/AP_RunCam.cpp
Verified the operation on RunCam Thumb Pro using type 4.
=> Fix parameter caching with RunCam enablement and setup on 3-pos switch

libraries/AP_Filesystem/posix_compat.cpp
=> AP_Filesystem: fixed open to return nullptr on failure

libraries/AP_Scripting/applets/Aerobatics/FixedWing/README.md
added txt scheds to docs, expanded the info a bit
=> AP_Scripting: Update plane_aerobtics.lua and its README.md

Tools/autotest/arduplane.py, libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
allow for better throttle control during maneuvers
=> AP_Scripting: added AEROM_THR_MIN and AEROM_THR_BOOST

Tools/autotest/arduplane.py, libraries/AP_Scripting/applets/Aerobatics/FixedWing/README.md, libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua, libraries/AP_Scripting/applets/Aerobatics/FixedWing/trick72.txt
two spiral barrel roll in trick72:
=> AP_Scripting: added barrell_roll

libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
this smooths out sudden yaw maneuvers
=> AP_Scripting: added yaw angular accel limit for aerobatics

libraries/AC_Sprayer/AC_Sprayer.h
This makes the respective sentence more clear and easy to read.
I am new to open source and ardupilot please let me know if I have done this the right way.
Thanks in advance.
=> AC_Sprayer: fix grammer to make the sentence more understandable

libraries/AP_Scripting/applets/Aerobatics/FixedWing/README.md, libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
- fixed throttle windup
- added multi-point rolls
thanks to @priseborough
=> AP_Scripting: minor aerobatics fixes

ArduPlane/commands_logic.cpp, libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
this was broken by the barrel roll changes
=> AP_Scripting: fixed crossbox-humpty aerobatics

ArduCopter/APM_Config.h, ArduCopter/AP_Arming.cpp, ArduCopter/Copter.cpp, ArduCopter/Copter.h, ArduCopter/Parameters.cpp, ArduCopter/config.h, ArduCopter/mode.h, ArduCopter/mode_zigzag.cpp, Blimp/config.h, Tools/autotest/arducopter.py
~~I've only checked this for compilation.~~
I added a test to make sure this keeps working.
=> Copter: Use HAL_SPRAYER_ENABLED in place of SPRAYER_ENABLED

Tools/autotest/arducopter.py
=> autotest: use implicit context for AutoTuneSwitch

libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450/hwdef.dat
Not going to attach one of these to a SkyViper....
=> hwdef: disable notify displays on SkyViper

libraries/AP_InertialSensor/AP_InertialSensor_SITL.cpp, libraries/AP_InertialSensor/AP_InertialSensor_SITL.h
Extracted from https://github.com/ArduPilot/ardupilot/pull/19507/files
=> AP_InertialSensor: various SITL INS improvements

libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
this implements lookahead, which takes account of the response time of the vehicle to changing rate demands in pitch and yaw
With Sbach in RF:
with zero lookahead:
with 0.5s lookahead:
=> AP_Scripting: implement path lookahead for aerobatics

libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
update the description for H_DUAL_MODE to include the coaxial configuration. No functional change.
=> AP_MotorsHeli: update H_DUAL_MODE description to include coaxial

libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Updated barrel roll so that it is correctly centered.
=> AP_Scripting: Fixed barrel roll arc

libraries/AP_Scripting/applets/Aerobatics/FixedWing/README.md, libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
This allows a sequence to be scaled up or down as needed, and mirrored by using a negative scale
and add some docs on parameters
=> AP_Scripting: added AEROM_PATH_SCALE

libraries/AP_Scripting/applets/Aerobatics/FixedWing/README.md, libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
allows for complex roll sequences within manuevers
=> AP_Scripting: added roll_sequence to simplify complex manuevers

libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
this allows much tighter control over path orientation during a sequence
This is what a funny_loop followed by a normal loop looks like
=> AP_Scripting: added set_orient and funny_loop

libraries/AP_Scripting/applets/Aerobatics/FixedWing/README.md
also, the hold fraction on multi point rolls needs a clearer description...I dont understand...will have to play with it in SITL to figure it out....I can add to this PR
=> AP_Scripting: update readme on plane_aerobatics

libraries/AC_AutoTune/AC_AutoTune.cpp
This PR fixes a bug where the tuned gains are not loaded for pilot testing after tuning succeeds.   This occurs for both heli and multi.
=> AC_AutoTune: Tuned Gains not loaded during pilot testing

libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl_Sub.cpp, libraries/AC_CustomControl/AC_CustomControl_PID.cpp, libraries/APM_Control/AP_PitchController.cpp, libraries/APM_Control/AP_RollController.cpp, libraries/APM_Control/AP_YawController.cpp
NFC....allows application to motors, tilts, control surfaces, etc.
confused a user
=> Generalize PID term descriptions

libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
not knowing if the script loaded as I am setting params for scripting and playing in sims with this drives me crazy :)
especially since MP now takes forever to update its config params screen which is the only way to tell otherwise
=> AP_Scripting: add initial announcement to plane_aerobatics.lua

ArduCopter/GCS_Mavlink.cpp, ArduCopter/GCS_Mavlink.h, ArduPlane/GCS_Mavlink.cpp, ArduPlane/GCS_Mavlink.h, Rover/GCS_Mavlink.cpp, Rover/GCS_Mavlink.h, Tools/autotest/arduplane.py, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
This PR simplifies https://github.com/ArduPilot/ardupilot/pull/22259 by doing the factoring of handling manual control first.
=> Factor out handling of MANUAL_CONTROL messages

libraries/AP_UAVCAN/AP_UAVCAN.cpp
Adds the param description for the option added in https://github.com/ArduPilot/ardupilot/pull/21702
=> AP_UAVCAN: update options bitmask for PWM option

libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
likes this:
message: Loop
thr_boost: true
loop 30
=> AP_Scripting: allow "thr_boost: true" in text aerobatic schedules

ArduCopter/Parameters.cpp, ArduPlane/Parameters.cpp, ArduSub/Parameters.cpp, Rover/Parameters.cpp
Booting was 25 seconds took longer. Tested at ESP32, Copter
=> ArduCopter, ArduPlane, ArduSub, Rover: fix long booting

Blimp/config.h
Unused.
Same as https://github.com/ArduPilot/ardupilot/pull/22220/files but a different vehicle directory....
=> Blimp: remove some unused definitions

Tools/ardupilotwaf/boards.py, libraries/AP_Filesystem/AP_Filesystem.h
Tested with esp-idf v4.2.1 version
=> ESP32: fixed builds for ESP32

Tools/autotest/autotest.py, Tools/autotest/common.py, Tools/autotest/rover.py, libraries/GCS_MAVLink/MAVLink_routing.cpp
returning true from this function means that we should run the command locally.  We really don't want to do that unless the command (or other targetted message) was actually sent at us!
Co-authored-by: dawid.kopec.spectalight@gmail.com
=> GCS_MAVLink: do not run all commands received on private channel

libraries/AP_Landing/AP_Landing.h, libraries/AP_Landing/AP_Landing_Slope.cpp
these are logged so should be defined
=> AP_Landing: assign values to each of the slope approach stages

libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
=> AP_Scripting: stall turn, part 2

ArduCopter/GCS_Mavlink.cpp
alternative to https://github.com/ArduPilot/ardupilot/pull/22027
> Clearly we need more comments in here!
I think it may help following developers.
=> Copter: explain msgs handling in packetReceived

libraries/GCS_MAVLink/GCS_Common.cpp
`bool ret` only be assigned `true` here, maybe we can just remove it?
=> GCS_Common: refactor try_send_mission_message

Tools/AP_Bootloader/board_types.txt
@peterbarker Can you merge this?
Thank you!
=> Tools: add board ID for Sierra F1 AP

Tools/scripts/configure_all.py, libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_Scheduler/AP_Scheduler.cpp, libraries/SITL/SITL.cpp, libraries/SITL/SITL.h
this can be used to reproduce some of the timing issues that are being addressed in #22298 
ping @lthall @rmackay9
=> SITL: added SIM_TIME_JITTER

libraries/AP_HAL/AP_HAL_Boards.h, libraries/AP_HAL/board/esp32.h, libraries/AP_HAL_ESP32/SoftSigReaderRMT.cpp, libraries/AP_HAL_ESP32/Util.cpp, libraries/AP_HAL_ESP32/boards/esp32buzz.h, libraries/AP_HAL_ESP32/boards/esp32diy.h, libraries/AP_HAL_ESP32/boards/esp32empty.h, libraries/AP_HAL_ESP32/boards/esp32icarus.h
**AP_HAL_ESP32: fix build esp32icarus** - The esp32icarus board didn't compile, I guess because nobody cared. There were 3 boards for the ESP32, compiling all of them may simplify the automated tests as all will compile.
**AP_HAL_ESP32: fix the board names** - pin numbers and board names are better stored in one separate file for a given board. Adding a new board will only modify one place, not several files.
**AP_HAL_ESP32: add empty board - without any sensors** - An empty board that does not contain any sensors, it is a great help for a novice user, by flashing an empty board, you can connect via MP and gradually add sensors. When there is a problem with one sensor, the MP connection does not work and such a user does not know what to do next. I had this problem and spent many days …
=> ESP32 board cleaning

.github/workflows/cygwin_build.yml, Tools/scripts/cygwin_build.sh
cygwin has dropped 32-bit support
=> .github: move to compiling 64-bit Windows executables

libraries/AR_Motors/AP_MotorsUGV.cpp, libraries/AR_Motors/AP_MotorsUGV.h
Fixes #21600. @rmackay9 Please check if this is the change you were looking for.
=> AR_Motors: fix have_skid_steering to return true for omnis

ArduCopter/Parameters.cpp
Reserve parameter 63 for use in ship operations mode.
=> Copter: Reserve G2 63 for Ship Operations

libraries/AP_Scripting/applets/Aerobatics/FixedWing/Schedules/SportPlane_Airshow.txt
tested a slightly simpler version, will test today hopefully on 3D XL
=> Applets:add SportPlaneAirshow schedule

libraries/AP_HAL/CANIface.h, libraries/AP_HAL_ChibiOS/CANFDIface.h, libraries/AP_HAL_ChibiOS/CANIface.h, libraries/AP_HAL_ChibiOS/CanIface.cpp, libraries/AP_HAL_SITL/CANSocketIface.cpp, libraries/AP_HAL_SITL/CANSocketIface.h, libraries/AP_UAVCAN/AP_UAVCAN.cpp, libraries/AP_UAVCAN/AP_UAVCAN.h
This logs CAN bus transmit and receive statistics and ESC/servo transmit stats
=> CAN: added CAN statistics logging for DroneCAN

ArduPlane/system.cpp, libraries/AP_Airspeed/AP_Airspeed.cpp, libraries/AP_Airspeed/AP_Airspeed.h
in case a pitot cover is forgotten during init......
=> AP_Airspeed:add warning for large offset change

libraries/AP_GPS/examples/GPS_AUTO_test/GPS_AUTO_test.cpp
=> AP_GPS: fix GPS_AUTO example

libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
this is a simpler approach based on sin(roll)*cos(pitch)
=> AP_Scripting: new version of knife-edge compensation in aerobatics

libraries/AP_Scripting/applets/runcam_on_arm.lua, libraries/AP_Scripting/applets/runcam_on_arm.md
I use this script in real life. I thought I'd add it to the examples directory to demonstrate use of aux functions from a script without T configuration and also as an example of simple, useful automation Lua scripting can bring to ArduPilot.
=> Lua script starts/stops video recording on arm/disarm

Tools/autotest/param_metadata/mdemit.py
=> Tools: parameters: mdemit: stop hiding usable params (Sub)

ArduPlane/system.cpp, Tools/autotest/test_build_options.py, libraries/AP_TemperatureSensor/AP_TemperatureSensor.cpp
Also add instructions to extracting feature sizes, and produce a CSV for same.
=> Fix compilation when QAUTOTUNE/TSYS01 compiled out

libraries/AP_HAL_ChibiOS/hwdef/MatekF405-CAN/hwdef.dat
=> hwdef: go to minimal GPS for MatekF405-CAN

libraries/AP_Scripting/applets/Aerobatics/FixedWing/Schedules/AirShow.txt
=> AP_Scripting: changed airshow rolling circle

libraries/AP_Scripting/applets/Aerobatics/FixedWing/README.md, libraries/AP_Scripting/applets/Aerobatics/FixedWing/Schedules/F4CScaleExample.txt, libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
=> AP_Scripting: fixed derry turn in aerobatics

libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/README.md
=> AP_Scripting:fix format error in readme file

ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduCopter/defines.h, ArduCopter/mode.h, ArduCopter/mode_auto.cpp, Blimp/defines.h, libraries/AP_Gripper/AP_Gripper.h
This PR works to improve the landing detection and help remove false positives. Features added:
- Manual release
- Parameterised touch down threshold
- Range finder minimum range to release
- Wait for decent velocity is established to measure thrust
- Use vertical thrust not motor thrust (motor thrust includes angle boost)
=> Payload Place

ArduPlane/mode.h
=> Plane: QAcro name4 longer than 4

libraries/AP_Scripting/lua_bindings.cpp
adds some more log formats to scripting, makes it easier to keep log sizes small rather than using floats or 32bit int/uint for everything.
=> AP_Scripting: bindings: logger: support more formats

libraries/AP_HAL_ChibiOS/hwdef/MambaF405-2022/hwdef.dat
=> AP_HAL_ChibiOS: minimize Mamba405-2022

Tools/autotest/arduplane.py, Tools/autotest/common.py
There's some useful testing caught up in a PR which is waiting for someone to look at (https://github.com/ArduPilot/ardupilot/pull/21929)
Breaks out the non-contentious parts.
=> Add test that wind estimation works on each AHRS type

libraries/AP_Scripting/AP_Scripting.cpp, libraries/AP_Scripting/AP_Scripting.h, libraries/AP_Scripting/applets/Script_Controller.lua, libraries/AP_Scripting/applets/Script_Controller.md, libraries/AP_Scripting/applets/script_controller.lua, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/lua_bindings.cpp, libraries/AP_Scripting/lua_bindings.h
working on this with @Hwurzburg
=> AP_Scripting: system for switching to alternative versions of lua scripts

libraries/AP_HAL/SIMState.cpp
=> AP_HAL: correct sitl-on-hw compilation for Helicopters

Tools/autotest/arduplane.py
this was written before there was an implicit context and reboot-on-failure at the level calling these tests
=> autotest: simplify Plane Rangefinder test

Tools/autotest/arduplane.py
=> autotest: give WindEstimate more time to converge

libraries/GCS_MAVLink/GCS.cpp, libraries/GCS_MAVLink/GCS.h
This saves a surprising amount of flash, about 3k on H7
=> MAVLink: save flash in CHECK_PAYLOAD_SIZE()

libraries/AP_Landing/AP_Landing_Slope.cpp
I changed division to multiplication with STM32 in mind.
=> AP_Landing: Change from division to multiplication

libraries/AC_AttitudeControl/AC_PosControl.cpp
=> AC_AttitudeControl: fixed time wrap bug in is_active_xy()

ArduPlane/mode_rtl.cpp
when using DO_LAND_START in an RTL scenario and the first AUTO command is a loiter, the loiter direction is overwritten by the RTL loiter radius. This fixes that.
=> Plane: bugfix - RTL_AUTOLAND no longer overrides loiter direction

libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/README.md, libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/sport_aerobatics.lua
added 3 new tricks, fixed some minor bugs, can be used without switch setup (ie only in auto missions) or only selector setup (for GCS tricks on a "button"), as well as with tricks on a switch...
SITL tested heavily
https://youtu.be/ajrYi9NA7rA
new tricks work well in real vehicle test flights
=> AP_Scripting: sport_aerobatics trick additions and fixes

libraries/AP_AHRS/AP_AHRS.h, libraries/AP_AHRS/AP_AHRS_config.h
NFC in here, but has uses in up-coming PRs.
=> AP_AHRS: break out an AP_AHRS_config.h

Tools/simulink/arducopter/sid_pre.m
=> Tools: Remove legacy code from sid_pre.m

AntennaTracker/Parameters.cpp, AntennaTracker/Parameters.h, ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduPlane/Parameters.cpp, ArduPlane/Parameters.h, ArduSub/Parameters.cpp, ArduSub/Parameters.h, Blimp/Parameters.cpp, Blimp/Parameters.h, Rover/Parameters.cpp, Rover/Parameters.h, Tools/AP_Periph/Parameters.cpp, Tools/AP_Periph/Parameters.h, Tools/Replay/Replay.cpp, Tools/Replay/Replay.h, libraries/AP_NMEA_Output/examples/NMEA_Output/nmea_output.cpp, libraries/AP_OSD/AP_OSD.cpp, libraries/AP_Param/AP_Param.h
This saves a bunch of flash due to better packing of the struct.
=> AP_Param: align info structs to save flash

Tools/autotest/param_metadata/param_parse.py
primarily to make the Wiki look nicer
=> Tools: param_parse.py: sort SIM_ parameters into the output files

Tools/autotest/quadplane.py
the fly_mission in quadplane was very-much Dalby-specific
=> autotest: create fresh fly_mission suitable for other missions

ArduPlane/Parameters.cpp, ArduPlane/Parameters.h, libraries/AP_TECS/AP_TECS.cpp, libraries/AP_TECS/AP_TECS.h, libraries/AP_Vehicle/AP_FixedWing.h
This adds TKOFF_THR_MAX_T which is the time to force maximum throttle on fixed wing takeoff without airspeed
fixes #22572
=> Plane: added TKOFF_THR_MAX_T for non-airspeed takeoff

libraries/AP_Logger/LoggerMessageWriter.cpp
Failing due to being out of time meant we wouldn't incremement the counter, even though we'd emitted the item.
it is important we try to send something, so move this check to be after we increment whichever counter we are using.
Tested in SITL with the following patch:
```
--- a/libraries/AP_Logger/LoggerMessageWriter.cpp
+++ b/libraries/AP_Logger/LoggerMessageWriter.cpp
@@ -81,6 +81,10 @@ bool LoggerMessageWriter_DFLogStart::check_process_limit(uint32_t start_us)
if (AP_HAL::micros() - start_us > limit_us) {
return true;
}
+    static uint32_t counter;
+    if (counter++ % 10 == 0) {
+        return true;
+    }
return false;
}
```
=> AP_Logger: avoid logging duplicate FMT/UNIT/FMTU/MULT messages

ArduCopter/AP_Arming.cpp
Fixes #21415 
Hi @rmackay9! I am a newbie and have tried to add the necessary conditions. Please let me know if this is what you were looking for.
Thanks in Advance.
=> Copter: skip throttle high arm check when arming in AUTO

libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp, libraries/AP_Scripting/examples/plane_ship_landing.lua
fixes to gyro logging and ship landing
=> Plane: updates for 4.3.3

libraries/AP_TemperatureSensor/AP_TemperatureSensor.cpp, libraries/AP_TemperatureSensor/AP_TemperatureSensor.h, libraries/AP_TemperatureSensor/AP_TemperatureSensor_MAX31865.cpp, libraries/AP_TemperatureSensor/AP_TemperatureSensor_MAX31865.h, libraries/AP_TemperatureSensor/AP_TemperatureSensor_Params.cpp, libraries/AP_TemperatureSensor/AP_TemperatureSensor_Params.h, libraries/AP_TemperatureSensor/AP_TemperatureSensor_config.h
Add temperature sensor driver MAX31865
=> AP_TemperatureSensor: add driver MAX31865

libraries/AP_AHRS/AP_AHRS.h
extracted from https://github.com/ArduPilot/ardupilot/pull/13858
=> AP_AHRS: tidy available-AHRS-types enumeration

ArduCopter/AP_Arming.cpp, ArduPlane/AP_Arming.cpp, ArduSub/AP_Arming_Sub.cpp, libraries/AP_Arming/AP_Arming.cpp
Uses the helper to ~~save flash~~ and reduce code.  No change in behavior.
Edit: seems not to save flash, maybe we need to inline the `check_enabled` method.
=> AP_Arming: Use arming helper

libraries/AP_Scripting/drivers/EFI_SkyPower.lua, libraries/AP_Scripting/examples/EFI_tester.lua
also:
- and added parameter for enable/disable start when disarmed
- added logging for extra fields not in EFI logging
- fixed endianness of EFI tester
- fixed an engine stop bug
- fixed extended flag in test suite
This has been test flown on a helicopter with an EFI engine controlled by heli governor
=> AP_Scripting: added custom telem msgs for EFI_Skypower driver

libraries/AP_Mount/AP_Mount_Servo.cpp
This PR fixes a bug in the servo gimbal driver's lean angle correction for gimbals with yaw control.  This resolves issue https://github.com/ArduPilot/ardupilot/issues/22510.  This only affects servo gimbals (not self-stabilising brushless gimbals) and only those with yaw control.
The existing gimbal stabilisation code simply subtracts the vehicle's roll and pitch lean angles from the corresponding gimbal roll and pitch servo outputs.  This is incorrect when the gimbal has a yaw servo (which is not pointing exactly forward) and also when the vehicle is at extreme angles (including upside down, see issue https://github.com/ArduPilot/ardupilot/issues/22440).
This PR improves the calculation by rotating the vehicle's roll and pitch lean angles by the (negative) gimbal's body-frame yaw angle …
=> AP_Mount: servo mount yaw handling fix

Tools/autotest/logger_metadata/emit_html.py, Tools/autotest/logger_metadata/emit_rst.py, Tools/autotest/logger_metadata/emit_xml.py, Tools/autotest/logger_metadata/enum_parse.py, Tools/autotest/logger_metadata/parse.py, libraries/AC_Avoidance/AP_OADatabase.h, libraries/AP_AHRS/LogStructure.h, libraries/AP_HAL/UARTDriver.h, libraries/AP_HAL/Util.h, libraries/AP_Logger/LogStructure.h, libraries/AP_NavEKF2/AP_NavEKF2_core.h, libraries/AP_NavEKF3/AP_NavEKF3_core.h, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/RC_Channel/RC_Channel.cpp
```
.. _ARM:
ARM: Canonical vehicle attitude
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+-----------+----------------------------------------------------------------+
| TimeUS    | microseconds since system startup                              |
+-----------+----------------------------------------------------------------+
| ArmState  | 1 if vehicle armed, 0 otherwise                                |
+-----------+----------------------------------------------------------------+
| ArmChecks | ARMING_CHECKS at time of arming                                |
|           | Bitmask bits:                                                  |
|           | +--------------------------+----+--+                           |
|           | | ARMING_CHECK_ALL         | 0  |  |                           |
| …
```
=> Include enumeration information in generated onboard log documentation

libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
=> AP_Scripting: fixed reverse barrel roll

libraries/AP_Motors/AP_MotorsSingle.cpp
This is a replacement for https://github.com/ArduPilot/ardupilot/pull/22758 and https://github.com/ArduPilot/ardupilot/pull/22760 and resolves issue https://github.com/ArduPilot/ardupilot/issues/18201
=> AP_Motors: Corrected the parameters.

libraries/AP_BoardConfig/AP_BoardConfig.cpp
We need to say which outputs this impacts. Should be noted in docs
=> AP_BoardConfig: improve description of BRD_PWM_VOLT_SEL

libraries/AP_HAL_ESP32/README.md
Add information for flashing standalone.
=> AP_HAL_ESP32: Readme update

libraries/AP_Mount/AP_Mount.cpp, libraries/AP_Mount/AP_Mount.h, libraries/AP_Mount/AP_Mount_Backend.h, libraries/AP_Mount/AP_Mount_Params.cpp, libraries/AP_Mount/AP_Mount_Scripting.cpp, libraries/AP_Mount/AP_Mount_Scripting.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/drivers/mount-djirs2-driver.lua, libraries/AP_Scripting/drivers/mount-djirs2-driver.md, libraries/AP_Scripting/generator/description/bindings.desc
This adds support for the DJIR2 and R3 handheld gimbals via a Lua script.
- AP_Mount_Scripting backend added that hold the latest position, angle and/or rate targets from the pilot or mission.  These targets are accessible to scripting using these accessors
- get_location_target returns the location target if available which is useful for gimbals that accept location targets
- get_angle_target returns the latest roll, pitch and yaw angles
- get_rate_target return the latest roll, pitch, yaw rates which are normally provided by the pilot's RC input
- set_attitude_euler allows the script to pass the actual lean angles from the gimbal to AP for reporting
- get_camera_state allows the caller to check if it should trigger taking a picture, start/stop recording video, zoom or focus
- …
=> AP_Scripting/AP_Mount: add support for DJIR2/R3 handheld gimbals

Tools/scripts/unpack_mp.sh
causes issues with changing md5's
=> Tools: unpack_mp.sh exclude files.html and .makehtml

.github/workflows/test_size.yml
Hopefully this fixes test size.
=> Actions: Test Size remove stray tab

.github/workflows/esp32_build.yml, .github/workflows/macos_build.yml, .github/workflows/test_chibios.yml, .github/workflows/test_coverage.yml, .github/workflows/test_environment.yml, .github/workflows/test_linux_sbc.yml, .github/workflows/test_replay.yml, .github/workflows/test_scripting_docs.yml, .github/workflows/test_sitl_copter.yml, .github/workflows/test_sitl_periph.yml, .github/workflows/test_sitl_plane.yml, .github/workflows/test_sitl_rover.yml, .github/workflows/test_sitl_sub.yml, .github/workflows/test_sitl_tracker.yml, .github/workflows/test_size.yml, .github/workflows/test_unit_tests.yml, Tools/autotest/pysim/util.py, Tools/autotest/quadplane.py, Tools/scripts/extract_features.py, Tools/scripts/uploader.py
close https://github.com/ArduPilot/ardupilot/pull/22816
close https://github.com/ArduPilot/ardupilot/pull/22818
clean macos version warning
make faster submodule update by using depth=1 (we don't care about history)
make coverage a bit faster by using premade docker image for sitl periph
correct disco size build
faster size test by removing weasyprint dependency (bit greener too as we donwload less stuff)
tabulate is already included into the docker image
fix git permission
fix flake8 tests
=> .github: update rules

Tools/scripts/extract_features.py
@Hwurzburg I think we need to find some sort of sanity check we can do to ensure `extract_features.py` works...
=> Tools: extract_features.py: correct detection of Currawong ECU

libraries/GCS_MAVLink/GCS.cpp, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_serial_control.cpp
... while we sort out https://github.com/ArduPilot/ardupilot/pull/22411 this gets us some important fixes
=> Tidy valid-channel checks in GCS

libraries/SITL/SIM_Helicopter.cpp
Fixes rpm for the heli SITL models as reported in #22835 
tested in SITL
=> SITL: fix heli RPM for heli SITL models

Tools/AP_Periph/AP_Periph.cpp, Tools/AP_Periph/AP_Periph.h, Tools/AP_Periph/Parameters.cpp, Tools/AP_Periph/Parameters.h, Tools/AP_Periph/wscript, libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h, libraries/AP_Common/NMEA.cpp, libraries/AP_Common/NMEA.h, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py, libraries/AP_NMEA_Output/AP_NMEA_Output.cpp, libraries/AP_NMEA_Output/AP_NMEA_Output.h, libraries/AP_NMEA_Output/AP_NMEA_Output_config.h, libraries/AP_Vehicle/AP_Vehicle.cpp, libraries/AP_Vehicle/AP_Vehicle.h
add msg sentence $PASHR. This allows PhaseOne cameras to get orientation data to embed into it's images
=> AP_NMEA_Output: add msg sentence $PASHR + refactor

ArduPlane/Attitude.cpp, ArduPlane/Plane.h, ArduPlane/commands_logic.cpp, libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Vehicle/AP_Vehicle.h
This is a WIP effort to improve knife-edge and AOA compensation. Not working yet
=> AP_Scripting: rework knife-edge and rudder handling

ArduPlane/Plane.h, ArduPlane/quadplane.cpp, ArduPlane/quadplane.h, ArduPlane/radio.cpp, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.h
this fixes an issue with rudder arming on quadplanes where the vehicle may yaw rapidly during the takeoff if the user is using rudder arming
tested in RealFlight
=> Plane: holdoff auto takeoff till rudder released on rudder arming

.github/workflows/test_size.yml, Tools/scripts/extract_features.py
Adds validation for extract_features.py and makes that validation pass.
=> Tools: extract_features.py: camera, rpm, rc-function-strings

libraries/AP_HAL/SIMState.cpp, libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
Past this `libraries/SITL/examples/on-hardware/sitl-on-hw.py --board CubeOrange --vehicle rover` builds and links.
=> Fixes for Rover SimOnHW

Tools/autotest/param_metadata/param.py, Tools/autotest/param_metadata/param_parse.py, libraries/AP_Scripting/applets/plane_ship_landing.lua, libraries/AP_Scripting/drivers/EFI_SkyPower.lua
Adds more parameter docs, and catches duplicates
=> Scripting: param docs 2

libraries/AP_OSD/AP_OSD.cpp, libraries/AP_OSD/AP_OSD.h, libraries/AP_OSD/AP_OSD_Screen.cpp
Co-authored-by: MichelleRos
this implements the functionality of #22660 but save almost 500 bytes instead of costing flash
=> AP_OSD:Add avg resting cell and refactor

libraries/AP_FlashStorage/AP_FlashStorage.h, libraries/StorageManager/StorageManager.h
=> Storage spelling fix

Tools/scripts/build_options.py, Tools/scripts/extract_features.py, libraries/AP_UAVCAN/AP_UAVCAN.cpp, libraries/AP_UAVCAN/AP_UAVCAN.h
Handle the Volz servo feedback msg and log it.
Depends on new DSDL PR https://github.com/dronecan/DSDL/pull/6
=> AP_UAVCAN: add Volz Servo feedback handling

Tools/scripts/build_ci.sh
Make build_ci.sh git operations a bit faster
=> Tools: build_ci: speedup git download operations

libraries/AP_Mount/AP_Mount.cpp, libraries/AP_Mount/AP_Mount.h, libraries/AP_Mount/AP_Mount_Backend.h, libraries/AP_Mount/AP_Mount_Scripting.cpp, libraries/AP_Mount/AP_Mount_Scripting.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/drivers/mount-viewpro-driver.lua, libraries/AP_Scripting/drivers/mount-viewpro-driver.md, libraries/AP_Scripting/generator/description/bindings.desc
This adds support for ViewPro gimbals including the Q30TIR ([this model in particular](http://www.viewprotech.com/index.php?ac=article&at=read&did=363)) using the ViewPro custom serial protocol including:
- controlling the gimbal using angle or rate targets
- controlling the camera's zoom, manual focus, autofocus, take picture, start/stop recording video features
- select the video feed via an RC_Switch with RCx_OPTION = 300 (scripting1)
There are a few known issues and enhancements that will be addressed in follow-up PRs including:
1. The gimbal shakes slightly whenever new angle or rate commands are received.  This driver should be enhanced to only send commands if they are different from the previous command sent.
2. Earth-frame yaw targets control (aka "lock") should be directly sent …
=> Mount/Scripting: ViewPro gimbal driver

Tools/autotest/arducopter.py, libraries/AP_Mount/AP_Mount.cpp, libraries/AP_Mount/AP_Mount_Backend.cpp, libraries/AP_Mount/AP_Mount_Backend.h
This method is only used in scripting.  So I added a test which makes sure that call's working in scripting...
=> AP_Mount: make get_attitude_euler non-virtual 

Tools/autotest/arduplane.py, Tools/autotest/common.py, Tools/autotest/rover.py
takes advantage of the context now understanding about scripts.
=> autotest: tidy scripting tests

Tools/autotest/helicopter.py
This PR adds an autotest to ensure the power recovery feature works.  It performs the following tests
1) checks that during autorotation the RSCheli servo output is at the value given by the parameter
2) checks that the throttle ramp time during power recovery is the time specified by the parameter
3) checks that after landing during an autorotation the RSCHeli servo output returns to the H_RSC_IDLE value
=> Tradheli autotest for manual autorotation power recovery

Tools/autotest/locations.txt
=> Tools/autotest: locations.txt add Portmoak

libraries/AP_Motors/AP_MotorsHeli_Dual.cpp, libraries/AP_Motors/AP_MotorsHeli_Quad.cpp, libraries/AP_Motors/AP_MotorsHeli_RSC.h, libraries/AP_Motors/AP_MotorsHeli_Single.cpp
This PR fixes inconsistent implementation across three frame types.  It also fixes implementation for DDVP tails.
Functionally checked in SITL.
=> AP_MotorsHeli: patch for manual autorotation

Tools/autotest/helicopter.py
Add test for Turbine start feature.  The following checks are conducted
* ensure turbine start doesn't activate while disarmed
* ensure turbine start doesn't activate while armed and interlock enabled(flying state)
* ensure turbine start works as designed (armed with interlock disabled)
* ensure feature can't be activated again after used for starting in flying state
failure checks were tested to ensure they worked correctly
=> Tools: autotest for Tradheli turbine start feature

Tools/autotest/helicopter.py
Adds some torture tests for SCurve navigation.  These used to provoke numeric exceptions.
Had to add a nasty hack to change to loiter between missions to reset the mission object properly.
=> autotest: add nasty mission tests

ArduPlane/Attitude.cpp, ArduPlane/Plane.h, ArduPlane/mode.cpp, ArduPlane/mode.h, ArduPlane/mode_acro.cpp, ArduPlane/mode_auto.cpp, ArduPlane/mode_guided.cpp, ArduPlane/mode_loiter.cpp, ArduPlane/mode_manual.cpp, ArduPlane/mode_qacro.cpp, ArduPlane/mode_qloiter.cpp, ArduPlane/mode_takeoff.cpp, ArduPlane/mode_training.cpp
Moves functionality down into mode classes, code to be move in a future PR.
=> Plane: move acro and training stablisation into mode classes

libraries/AP_RangeFinder/AP_RangeFinder.cpp, libraries/AP_RangeFinder/AP_RangeFinder.h, libraries/AP_RangeFinder/AP_RangeFinder_Backend.h, libraries/AP_RangeFinder/AP_RangeFinder_Lua.cpp, libraries/AP_RangeFinder/AP_RangeFinder_Lua.h, libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/benewakeH30_can_rangefinder.lua, libraries/AP_Scripting/generator/description/bindings.desc
I have split this from https://github.com/ArduPilot/ardupilot/pull/20015 to make it a little easier to merge. 
This PR attempts to add the ability for a user to add a custom Lua script-based rangefinder backend.
As an example script I have written a script which does Benewake CAN H30 (It has a CPP driver already)
=> Scripting/AP_RangeFinder: Add lua scripting based RangeFinder (Split)

libraries/RC_Channel/RC_Channel.cpp
as I was creating #22924 I noticed how badly formatted the switch statements were so ran it thru astyle...NFC
=> RC_Channel:fix code formatting

Tools/autotest/arducopter.py
Extracted from https://github.com/ArduPilot/ardupilot/pull/18561
=> autotest: add test for flying mission twice back-to-back

Tools/autotest/arducopter.py, Tools/autotest/common.py, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_InertialSensor/AP_InertialSensor_SITL.cpp, libraries/SITL/SITL.cpp, libraries/SITL/SITL.h
Thanks to @robertlong13 for finding this
=> Correct IMU consistency checks

libraries/RC_Channel/RC_Channel.cpp
The NULLPTR determination is also made when not used.
It is better to judge when to use it.
It is better not to do meaningless processing.
=> RC_Channel: Check when to use

.github/workflows/cygwin_build.yml
Enable ccache on cygwin
Half cygwin CI time !
=> .github: add and use ccache on cygwin build

libraries/AP_HAL_ChibiOS/hwdef/MatekF405-Wing/hwdef.dat
add Invensensev3 IMU support
save some flash
=> AP_HAL_ChibiOS:add Invensensev3 IMU support in MatekF405-Wing

Tools/autotest/arducopter.py, libraries/AP_AHRS/AP_AHRS.cpp
thanks to @lthall for finding this
this bug does not affect EKF2
=> AHRS: fixed earth frame accel with significant AHRS trim

Tools/scripts/size_compare_branches.py, libraries/AP_HAL_ChibiOS/hwdef/common/stm32_util.h, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py, libraries/AP_HAL_ChibiOS/system.cpp
`MatekF405-CAN` doesn't build.
This is based on https://github.com/ArduPilot/ardupilot/pull/22941
=> Save even more space in bootloaders

libraries/AP_GPS/GPS_Backend.cpp
=> AP_Compass: add GPYW metadata

libraries/AP_Filesystem/AP_Filesystem.cpp, libraries/AP_Filesystem/AP_Filesystem.h, libraries/AP_Filesystem/AP_Filesystem_ESP32.cpp, libraries/AP_Filesystem/AP_Filesystem_ESP32.h, libraries/AP_Filesystem/AP_Filesystem_FATFS.cpp, libraries/AP_Filesystem/AP_Filesystem_FATFS.h, libraries/AP_Filesystem/AP_Filesystem_backend.h, libraries/AP_Filesystem/AP_Filesystem_posix.cpp, libraries/AP_Filesystem/AP_Filesystem_posix.h, libraries/GCS_MAVLink/GCS_FTP.cpp
already supported by MAVProxy
tested in SITL and on a Pixhawk6C
=> Support rename in MAVLink FTP protocol

Tools/autotest/arducopter.py, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
Partial completion of https://github.com/ArduPilot/ardupilot/issues/7658
=> Add support for MAV_CMD_DO_SET_ROI_NONE

Tools/autotest/arducopter.py, Tools/autotest/common.py, libraries/SITL/SIM_IntelligentEnergy24.cpp, libraries/SITL/SIM_IntelligentEnergy24.h
=> autotest: augment IE24 test with fuel-remaining test
