ArduPilot/ardupilot

- APMrover2/APMrover2.pde
- APMrover2/release-notes.txt
The highly anticipated v2.49 of Rover has come to fruition!
> APMrover2: Creating release 2.49 of Rover.

- mk/PX4/ROMFS/init.d/rc.APM
add -T option to hmc5883 start
> PX4: enable temperature compensation in hmc5883 driver

- libraries/AP_HAL_Linux/RCOutput_Bebop.cpp
CLOCK_MONOTONIC is not affected by discontinuous jumps in the system time.
> RCOutput_Bebop: use CLOCK_MONOTONIC instead of CLOCK_REALTIME

- libraries/AP_NavEKF2/AP_NavEKF2.cpp
- libraries/AP_NavEKF2/AP_NavEKF2_core.cpp
- libraries/AP_NavEKF2/AP_NavEKF2_core.h
- libraries/DataFlash/DataFlash.h
Includes revised tuning parameters and better loss of GPS handling
> EKF2 improvements

- libraries/AP_NavEKF2/AP_NavEKF2_OptFlowFusion.cpp
- libraries/AP_NavEKF2/AP_NavEKF2_core.cpp
- libraries/AP_NavEKF2/AP_NavEKF2_core.h
> EKF2 Critical Bug Fix

- Tools/autotest/sim_vehicle.sh
> sim_vehicle.sh: remove unused -e option and unused variables

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
Adds a default template, updates forum link for the guidelines
> Github: Add and update github templates

- Tools/autotest/sim_vehicle.py
> Fixes to sim_vehicle.py with waf

- ArduCopter/Copter.h
- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/control_guided.cpp
- ArduCopter/defines.h
- ArduCopter/position_vector.cpp
- libraries/AC_Fence/AC_Fence.cpp
- libraries/AC_Fence/AC_Fence.h
This PR replaces https://github.com/ArduPilot/ardupilot/pull/4004
It's related to this issue on the to-do list: https://github.com/ArduPilot/ardupilot/issues/2384
It's not quite a complete solution to the above issue because this PR does not stop a vehicle which is flying with Guided's velocity controller from breaching the fence
> Copter: reject guided mode target positions outside of fence

- Tools/GIT_Test/GIT_Success.txt
Added my name to GIT_Success.txt.
> Git: add Ikegami Atsushi to GIT_Success.txt

- Tools/GIT_Test/GIT_Success.txt
Training is a school of kazutaka ozawa.
It sends a pull request.
> assignment

- Tools/LogAnalyzer/DataflashLog.py
- Tools/LogAnalyzer/tests/TestMotorBalance.py
- Tools/LogAnalyzer/tests/TestVCC.py
These patches at least make LogAnalyzer complete on one modern log I have here.
> Loganalyzer fixes

- APMrover2/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.cpp
Corresponds to this update in Mission Planner: https://github.com/ArduPilot/MissionPlanner/commit/1b91ae21e240f20739dfeaa88172961338838621
> Change sensor health check to prevent false positive

- libraries/AP_AHRS/AP_AHRS.h
- libraries/AP_AHRS/AP_AHRS_NavEKF.h
- libraries/AP_Frsky_Telem/AP_Frsky_Telem.cpp
- libraries/AP_Frsky_Telem/AP_Frsky_Telem.h
This will be used by the Frsky lib in a separate pull request.
> Provide access to EKF status report

- ArduPlane/ArduPlane.cpp
- ArduPlane/navigation.cpp
It is determined only by latitude 0 degrees.
However, the latitude 0 degrees there is land.
Therefore,
To add a judgment of 0 degrees longitude.
> Plane: To add a judgment of 0 degrees longitude.

- ArduPlane/quadplane.cpp
The same wording is multiple use.
Wording to use a fixed area of memory.
Therefore,
The same wording by one, to reduce the memory used.
> Plane: To define the same wording.

- Tools/GIT_Test/GIT_Success.txt
> Added name to GIT_Success.txt

- .gitignore
- .gitmodules
- .travis.yml
- Tools/scripts/build_all_travis.sh
- Tools/scripts/build_ci.sh
- Tools/scripts/configure-ci.sh
- Tools/scripts/install-apt-ci.sh
- Tools/scripts/install-travis-env.sh
EDIT: master-AVR: Updated semaphoreci and travis scripting files.
@OXINARF @gmorph @peterbarker @magicrub please check.
Thanks in advance.
> master-AVR: Fixed Semaphoreci and Travis building.

- Tools/scripts/configure-ci.sh
- Tools/scripts/install-prereqs-arch.sh
- Tools/scripts/install-prereqs-ubuntu.sh
rebase from https://github.com/ArduPilot/ardupilot/pull/4174
reorder pip install to install first furture and lxml
use pip install -U in case of already install pip package
remove : arduino-core, catkin_pkg,curl, droneapi as unused
install libtool-bin starting from ubuntu 15.10
> Tools: Update install scripts

- .travis.yml
- Tools/scripts/install-apt-ci.sh
- Tools/scripts/install-prereqs-ubuntu.sh
I also update travis and ci in prevention of switch to ubuntu 14.04.
I don't have arch (I know only a little about it) so if someone can check if the current script is working !
> Install script fix some lxml dependency for ubuntu

- libraries/SITL/SIM_last_letter.cpp
- libraries/SITL/SIM_last_letter.h
Communication between ardupilot and the last_letter simulator was broken for a few months now.
This is the first commit which brings things up to date.
> WIP: Connection to last_letter once again successful

- libraries/AP_Frsky_Telem/AP_Frsky_Telem.cpp
- libraries/AP_Frsky_Telem/AP_Frsky_Telem.h
> AP_Frsky_Telem: actually set _ap.value flags based in is_flying

- ArduPlane/release-notes.txt
- ArduPlane/servos.cpp
> ArduPlane: Fix typos

- Tools/GIT_Test/GIT_Success.txt
Retry. Added my name to GIT_Success.txt.
> (retry) Added my name to GIT_Success.txt

- APMrover2/APMrover2.cpp
- APMrover2/GCS_Mavlink.cpp
- APMrover2/Rover.h
- APMrover2/commands_logic.cpp
- APMrover2/defines.h
Rover now accepts a new message MAV_CMD_NAV_SET_YAW_SPEED which has an angle in centidegrees and a speed scale and the rover will drive based on these inputs.
> Rover: added a new form of GUIDED mode

- Tools/Frame_params/Parrot_Disco/start_ardupilot.sh
- libraries/AP_Notify/AP_Notify.cpp
- libraries/AP_Notify/DiscoLED.cpp
- libraries/AP_Notify/DiscoLED.h
Use RGBLed generic implementation to support Disco LED.
> Disco: add LED support

- libraries/AP_HAL/utility/RingBuffer.cpp
- libraries/AP_HAL_Linux/RPIOUARTDriver.cpp
- libraries/AP_HAL_Linux/SPIUARTDriver.cpp
- libraries/AP_HAL_PX4/UARTDriver.cpp
- libraries/AP_HAL_VRBRAIN/UARTDriver.cpp
Commits removed from #4934 in its last iteration to make it smaller for review.  Mostly cosmetic changes.
> Remaining ByteBuffer misc changes

- APMrover2/APMrover2.cpp
- APMrover2/GCS_Mavlink.cpp
- APMrover2/GCS_Mavlink.h
- APMrover2/Rover.h
- APMrover2/sensors.cpp
Same as 34718b130a74828af45727d35cc67f9934798fcd which was for Copter
> Rover: update sensor status error flags independently of sending a sys_status message

- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/setup.cpp
- ArduCopter/system.cpp
C++11 is to provide a nullptr for NULL pointer.
Therefore,
To change to nullptr.
> Copter: To nullptr from NULL.

- APMrover2/APMrover2.cpp
- APMrover2/GCS_Mavlink.cpp
- APMrover2/Rover.cpp
- APMrover2/system.cpp
C++11 is to provide a nullptr for NULL pointer.
Therefore,
To change to nullptr.
> Rover: To nullptr from NULL.

- ArduPlane/ArduPlane.cpp
- ArduPlane/GCS_Mavlink.cpp
- ArduPlane/geofence.cpp
- ArduPlane/px4_mixer.cpp
- ArduPlane/servos.cpp
- ArduPlane/system.cpp
- ArduPlane/tuning.cpp
C++11 is to provide a nullptr for NULL pointer.
Therefore,
To change to nullptr.
> Plane: To nullptr from NULL.

- APMrover2/commands_logic.cpp
Ran astyle over commands_logic.cpp because the file was all over the place.  Used the Tools/CodeStyle/astylerc as the options.
No functional changes.  I'll wait for travis to pass it and then pull it in.
> Rover: Whitespace change only

- Tools/scripts/install-prereqs-arch.sh
- Tools/scripts/install-prereqs-ubuntu.sh
see http://discuss.ardupilot.org/t/for-build-compile-instructions/12451
> scripts: add cmake to install-prereq scripts

- libraries/AP_HAL_Linux/Scheduler.cpp
Several return values in the constructor of the scheduler were ignored
before, while they should be respected.
I found that bug while strac'ing ardupilot as it failed at some later
point.
Signed-off-by: Ralf Ramsauer <ralf.ramsauer@othr.de>
> Linux: Scheduler: don't ignore return values

- libraries/AP_Frsky_Telem/AP_Frsky_Telem.cpp
- libraries/AP_Frsky_Telem/AP_Frsky_Telem.h
As suggested by tridge:
- added extra parentheses around pointed to values for readability
- added const to some declarations
> AP_Frsky_Telem: readability and declaration improvements

- Tools/GIT_Test/GIT_Success.txt
This is the Git test from URUS Team.
> GIT Test: Added names from URUS Team.

- Tools/scripts/install-prereqs-arch.sh
- Tools/scripts/install-prereqs-ubuntu.sh
Add additional verbose output to scripts
> Tools: add set -x to install-prereqs scripts

- Tools/GIT_Test/GIT_Success.txt
Pull request exercise
update ardupilot/Tools/GIT_Test/GIT_Success.txt . by Noriyoshi tanaka.
> add my name last line. by tanaka 2016/11/07

- libraries/AP_HAL_Linux/RCOutput_Bebop.cpp
- libraries/AP_HAL_Linux/RCOutput_Bebop.h
- libraries/AP_HAL_Linux/ToneAlarm_Disco.cpp
- libraries/AP_HAL_Linux/ToneAlarm_Disco.h
- libraries/AP_HAL_Linux/Util.cpp
- libraries/AP_HAL_Linux/Util.h
- libraries/AP_Notify/AP_Notify.cpp
Use ToneAlarm class to handle Disco buzzer.
> Disco: add buzzer support

- Tools/GIT_Test/GIT_Success.txt
Add my name for testing pull request.
> Pull request test

- libraries/AP_HAL_Linux/PWM_Sysfs.cpp
> AP_HAL_Linux: fix leaking strings

- libraries/AP_Common/AP_Common.h
- libraries/AP_Common/Location.cpp
- libraries/AP_Math/location.cpp
- libraries/AP_Math/location.h
LOCATION_SCALING_FACTOR, LOCATION_SCALING_FACTOR_INV is defined in location.cpp of AP_Math and Location.cpp of AP_Common.
Therefore,
It is defined in AP_Common.h.
> Global: Aggregate the same definitions.

- Tools/autotest/apmrover2.py
- Tools/autotest/arducopter.py
- Tools/autotest/arduplane.py
- Tools/autotest/autotest.py
- Tools/autotest/common.py
- Tools/autotest/dump_logs.py
- Tools/autotest/fakepos.py
- Tools/autotest/jsb_sim/runsim.py
- Tools/autotest/param_metadata/param_parse.py
- Tools/autotest/param_metadata/rstemit.py
- Tools/autotest/pysim/fdpexpect.py
- Tools/autotest/pysim/rotmat.py
- Tools/autotest/pysim/testwind.py
- Tools/autotest/pysim/util.py
- Tools/autotest/quadplane.py
- Tools/autotest/sim_vehicle.py
Hi, this PR should bring python3 support for sim_vehicule and autotest. 
It works with https://github.com/ArduPilot/pymavlink/pull/10 
Mavproxy is still python 2 ... :cry:
> Python3 support

- Tools/GIT_Test/GIT_Success.txt
Drone Japan homework: input name and pull request.
Please merge Tools/GIT_Test/GIT_Success.txt.
> homework seki

- Tools/GIT_Test/GIT_Success.txt
Update my name "Yu Kuwahara" to GIT_Success.txt
> Japan Drone school homework

- Tools/GIT_Test/GIT_Success.txt
Testing whether I can add changes to git_success via the Windows Client
> Added name to Git_Success

- Tools/CPUInfo/Makefile
I replaced the existing Makefile with one copied from Replay and changed to support CPUInfo.
> CPUInfo: Updated the Makefile to use WAF commands

- libraries/SITL/SIM_Aircraft.cpp
- libraries/SITL/SIM_Aircraft.h
I have added support for turbulence in SITL the effect can observe in this Demonstration video:
https://youtu.be/IjzDwZ5OKxU
> adding turbulance to SITL

- libraries/DataFlash/LogFile.cpp
1. Correct the return value from -1 to 0xFFFF.
Other
2. Correct the tab code to spaces.
3. Delete the space or tab code at the end of the line.
> DataFlash: Adjust the return value to the type of the method.

- APMrover2/GCS_Mavlink.cpp
- APMrover2/GCS_Mavlink.h
- APMrover2/Parameters.cpp
- APMrover2/Parameters.h
As in copter and plane, add sysid_enfore to rover
> Rover: added SYSID_ENFORCE parameter

- ArduPlane/Log.cpp
- ArduPlane/Parameters.cpp
- ArduPlane/px4_mixer.cpp
- ArduPlane/setup.cpp
- ArduPlane/test.cpp
A character string that does not require a parser improves performance by replacing it with a print or println statement that does not have a parser.
> Plane: Change from printf statement to print, println statement.

- APMrover2/Log.cpp
- AntennaTracker/Log.cpp
- ArduCopter/Log.cpp
- ArduPlane/Log.cpp
- ArduPlane/Plane.h
- ArduPlane/arming_checks.cpp
- ArduPlane/system.cpp
- libraries/AP_Arming/AP_Arming.cpp
- libraries/AP_Arming/AP_Arming.h
- libraries/DataFlash/DataFlash_File.cpp
- libraries/DataFlash/DataFlash_File.h
Various fixes  to make arming health more reliable and reportable.
> Arming check fixes

- ArduCopter/Copter.h
- ArduCopter/commands_logic.cpp
- ArduCopter/control_auto.cpp
- ArduCopter/defines.h
- libraries/AP_Gripper/AP_Gripper.cpp
- libraries/AP_Gripper/AP_Gripper.h
- libraries/AP_Gripper/AP_Gripper_Backend.h
- libraries/AP_Gripper/AP_Gripper_EPM.cpp
- libraries/AP_Gripper/AP_Gripper_EPM.h
- libraries/AP_Gripper/AP_Gripper_Servo.cpp
- libraries/AP_Gripper/AP_Gripper_Servo.h
- libraries/AP_Mission/AP_Mission.cpp
- libraries/RC_Channel/RC_Channel_aux.cpp
- libraries/RC_Channel/RC_Channel_aux.h
- libraries/SITL/SIM_Aircraft.cpp
- libraries/SITL/SIM_Aircraft.h
- libraries/SITL/SIM_Gripper_Servo.cpp
- libraries/SITL/SIM_Gripper_Servo.h
- libraries/SITL/SIM_Multicopter.cpp
- libraries/SITL/SIM_Plane.cpp
... descending as necessary for soft placement.
> NAV_PLACE: fly to a location and place an object

- libraries/AP_AHRS/examples/AHRS_Test/AHRS_Test.cpp
AHRS_Test: Modify to NavEKF2 for AHRS Example
> modify NavEKF2 for AHRS Test

- libraries/AP_Mission/AP_Mission.cpp
Location is out of spec for NAV_RETURN_TO_LAUNCH
NAV_LOITER_UNLIM couldn't roundtrip the provided loiter radius
> AP_Mission: Align with spec better

- ArduPlane/ArduPlane.cpp
@magicrub This is going to conflict with your landing changes, but should probably go in soonish...
> Plane: correct on_flight_line landing stage check

- libraries/AP_Motors/AP_MotorsHeli_Single.cpp
About the use of fence in copter, avoid use should be restricted to FENCE define too ?
> All: Some minors fixes

- libraries/AP_Compass/AP_Compass_Backend.cpp
- libraries/AP_Param/AP_Param.h
> fix notify of compass external settings

- ArduCopter/control_poshold.cpp
This hopefully resolves this crash with a traditional helicopter flying AC3.4.
http://discuss.ardupilot.org/t/which-made-the-mini-heli-crash/13479/5
> Copter: fix heli pos-hold run-up-complete issue

- libraries/AP_Math/AP_Math.h
Not sure why it was done like that in the first place
> AP_Math: Remove unecessary check

- APMrover2/Steering.cpp
- APMrover2/commands_logic.cpp
Had a bug where the rover would loiter for ever and not resume even
though its loiter time had expired.  This resolves that.
> Rover: Fixed a bug in the wp loiter functionality

- libraries/AP_Baro/AP_Baro.cpp
The same value is used in multiple if statements.
In this case, I think that it is better to use the switch statement.
> AP_Baro: Changed if statements to switch statement.

- libraries/AP_NavEKF2/AP_NavEKF2_Control.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
Fixes bug causing https://github.com/ArduPilot/ardupilot/issues/5428.
This bug was  introduced when fallback logic was re-worked to include range beacon fusion.
> EKF2 and 3: Fix aiding fallback bugs

- APMrover2/GCS_Mavlink.cpp
- APMrover2/control_modes.cpp
The same value is used in multiple if statements.
In this case, I think that it is better to use the switch statement.
> Rover: Changed if statements to switch statement.

- ArduCopter/navigation.cpp
Multiple modes are judged by if statement.
Replace with switch statement.
Mode becomes easy to find.
> Copter: Changed if statements to switch statement.

- libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
In the case statement, the absence of processing is indicated by a blank line.
For clarity, write "no break" or "no break (no return)".
Other
Change indent of switch statement.
> AP_AHRS: Change indentation.

- libraries/AP_NavEKF2/AP_NavEKF2_Control.cpp
The same value is used in multiple if statements.
In this case, I think that it is better to use the switch statement.
Other
Change indentation.
> AP_NavEKF2: Changed if statements to switch statement.

- Tools/GIT_Test/GIT_Success.txt
> git_test: first commit

- APMrover2/Parameters.cpp
The user might want to change them :)
> APMrover2: publish SPEED2THR_ parameters

- libraries/SITL/SIM_XPlane.cpp
> SITL: XPLANE fix member shadowing

- ArduCopter/system.cpp
- libraries/AP_Motors/AP_MotorsTri.cpp
- libraries/AP_Motors/AP_MotorsTri.h
> Copter: fixed var_info issue

- ArduCopter/GCS_Mavlink.cpp
@rmackay9 @OXINARF please consider for 3.5
> Copter: get mav heartbeats out when board detection fails

- ArduPlane/Parameters.cpp
- ArduPlane/Parameters.h
- ArduPlane/commands.cpp
- ArduPlane/commands_logic.cpp
- ArduPlane/navigation.cpp
- libraries/AP_Vehicle/AP_Vehicle.h
convert Plane.g.loiter_radius to aparm.loiter_radius for AP_Landing deepstall which is coming soon
> Plane: convert g.loiter_radius to aparm.loiter_radius for AP_Landing

- ArduPlane/takeoff.cpp
quite an unusual setup, but has been done :-)
> Plane: fixed auto-takeoff throttle trigger for inverted launch

- Tools/autotest/sim_vehicle.py
…e_type)_(instance number)
This allow to seperate each instance data (log, eeprom)
> SITL: add an option to launch SITL from a directory 

- ArduCopter/commands_logic.cpp
Adds support for the Mavlink DO_FENCE_ENABLE command to copter.
> Copter: Now recognizes DO_FENCE_ENABLE mission command.

- APMrover2/Parameters.cpp
- AntennaTracker/Parameters.cpp
- ArduCopter/Parameters.cpp
- ArduPlane/Parameters.cpp
- Tools/autotest/param_metadata/param_parse.py
- libraries/RC_Channel/RC_Channel.cpp
- libraries/RC_Channel/RC_Channels.cpp
- libraries/SRV_Channel/SRV_Channel.cpp
- libraries/SRV_Channel/SRV_Channels.cpp
This fixes the generated documentation for nested libraries like RC_Channels and SRV_Channels
> fixed parameter doc generation for nested libraries

- ArduCopter/control_guided.cpp
Same fix as for auto takeoff, for the bug that could make some very powerful copters think they landed while in flight.
There may be some discrepancies between guided_takeoff_start and auto_takeoff_start by the way (terrain stuff). @rmackay9 could you check that ?
> Copter : set land_complete to false during guided takeoff

- ArduPlane/Parameters.cpp
- ArduPlane/Parameters.h
Closes #4998, and fix a tab/spaces error on the previous parameter.
> Plane: Remove ALT_MIX

- APMrover2/GCS_Mavlink.cpp
- AntennaTracker/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.cpp
Without these patches logging well never restart after a gcs-induced log erase.
> Log erase log download fix

- libraries/DataFlash/DataFlash_File.cpp
- libraries/DataFlash/DataFlash_File.h
This helps with collating when reviewing log files
Closes #2212
> DataFlash: zero-pad the number in the log filename

- libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
- libraries/AP_RangeFinder/RangeFinder.cpp
> Fix /0 caused by setting RNGFND_GNDCLEAR to zero

- ArduPlane/GCS_Plane.cpp
- ArduPlane/GCS_Plane.h
- ArduPlane/Plane.cpp
- ArduPlane/system.cpp
This is the first commit from https://github.com/ArduPilot/ardupilot/pull/5715/commits/e4030eba72e918c678a8e6359e5c51dea96a3b81 which just fixes problems to do with CLI_ENABLED and starting the CLI.
> Plane: fix startup of CLI menu system

- ArduSub/joystick.cpp
- libraries/AP_JSButton/AP_JSButton.cpp
and fix param metadata in jsbutton library
> Implement relay joystick button functions

- libraries/AP_ADSB/AP_ADSB.cpp
closes https://github.com/ArduPilot/ardupilot/issues/5424
> AP_ADSB: populate altitude via pressure for ADSB-Out

- ArduPlane/Plane.h
- ArduPlane/commands_logic.cpp
- ArduPlane/navigation.cpp
check for scenarios where updrafts can keep you from loitering down indefinitely. Side effect is it allows an exit in ANY case you're loitering to alt and your alt is not met for whatever reason (bad sensors/EKF) after a few orbits.
> Plane: exit LOITER_TO_ALT if stuck in strong thermal

- ArduSub/ArduSub.cpp
as the ahrs_view is not created by AHRS it isn't hooked into the update, so we need to update it directly
> Sub: fixed AHRS_View update

- ArduPlane/quadplane.cpp
- ArduPlane/quadplane.h
- ArduPlane/tiltrotor.cpp
allow control of tilt rate separately for UP and DOWN
always allow at least 90 degrees/second for switching to MANUAL
> Plane: added Q_TILT_RATE_UP and Q_TILT_RATE_DN as separate parameters

- ArduPlane/system.cpp
- libraries/AP_RangeFinder/AP_RangeFinder_PulsedLightLRF.cpp
- libraries/AP_RangeFinder/AP_RangeFinder_PulsedLightLRF.h
- libraries/AP_RangeFinder/RangeFinder.cpp
- libraries/AP_RangeFinder/RangeFinder.h
this avoids the detection of the hw type
> AP_RangeFinder: added type 15 for LidareLiteV3

- libraries/AP_BoardConfig/px4_drivers.cpp
- libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
- libraries/AP_InertialSensor/AP_InertialSensor_Invensense.h
> Sensors: support for ICM-20602 IMU

- libraries/AP_GPS/AP_GPS_SBF.cpp
CID 125035 (SBF_PREABLE1 is already '$')
Last coverity based PR for the evening, I promise!
> AP_GPS: Remove dead SBF code

- APMrover2/system.cpp
Solve https://github.com/ArduPilot/ardupilot/issues/5080
> ROVER: stop mission when leaving AUTO

- libraries/AP_ServoRelayEvents/AP_ServoRelayEvents.cpp
this was broken by the recent SRV_Channels changes
thanks to Jacob for noticing this!
> AP_ServoRelayEvents: fix do_set_servo

- APMrover2/Rover.h
- APMrover2/Steering.cpp
- APMrover2/commands_logic.cpp
- APMrover2/system.cpp
This is on the AVR branch only.
> Rover AVR: Adding LOITER_TIME and LOITER_TIME_UNLIM functionality

- Tools/GIT_Test/GIT_Success.txt
hey I added my name to the txt file - i am new to git i hope everything is alright!
> Adding my name to GIT_Success.txt!

- Tools/GIT_Test/GIT_Success.txt
> Added myself to GIT_Succsess (and proud of it)

- APMrover2/Log.cpp
- ArduCopter/Log.cpp
- ArduPlane/Log.cpp
- ArduSub/Log.cpp
show how much available memory we have
> Add Mem field to PM message

- libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
- libraries/AP_InertialSensor/AP_InertialSensor_Invensense.h
the temperature offset varies between sensors
> AP_InertialSensor: fixed invensense driver temp reading

- Tools/GIT_Test/GIT_Success.txt
hello! hope we get to collaborate for GSOC this year 😄
> Name added - gitsuccess.txt

- README.md
Changed Solo maintainer to myself per discussion in the 4/2/2017 dev call. Removed reference to 3DR's git since it is not mine.
> Update Readme.md for Solo maintainer

- AntennaTracker/GCS_Mavlink.cpp
> removed redundant code

- libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
The previous tilt alignment check  used the norm of the quaternion state variance vector. This meant it also included the yaw component of attitude uncertainty which could be slow to converge.
This change brings this check up to date with the same check mathematics used by the ecl EKF library which converts the quaternion co-variances to an equivalent rotation vector uncertainty and uses the tilt components only for the check.
> AP_NavEKF3: Update tilt alignment check

- libraries/AP_GPS/AP_GPS_QURT.cpp
> AP_GPS: Fix a memory leak in QURT GPS

- ArduCopter/control_autotune.cpp
Comparison with bit variables is done at 1, 0.
Other processes are true and false.
Therefore, it handles the handling of bit variables.
Other:
Change the comment of the bit variable.
Check:
This change was confirmed by source diff.
> Copter: Compare bit variables, change set values.

- libraries/AC_PrecLand/AC_PrecLand.cpp
- libraries/AC_PrecLand/AC_PrecLand.h
- libraries/AC_PrecLand/AC_PrecLand_Backend.h
- libraries/AC_PrecLand/AC_PrecLand_IRLock.cpp
- libraries/AC_PrecLand/AC_PrecLand_SITL_Gazebo.cpp
- libraries/AP_IRLock/AP_IRLock_I2C.cpp
- libraries/AP_IRLock/AP_IRLock_I2C.h
- libraries/AP_IRLock/AP_IRLock_SITL.cpp
- libraries/AP_IRLock/AP_IRLock_SITL.h
- libraries/AP_IRLock/IRLock.h
> IRLock: added selection of I2c bus

- libraries/AP_AHRS/AP_AHRS.h
- libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
- libraries/AP_AHRS/AP_AHRS_NavEKF.h
- libraries/AP_HAL_SITL/SITL_State.cpp
- libraries/AP_HAL_SITL/SITL_State.h
- libraries/AP_HAL_SITL/sitl_compass.cpp
- libraries/AP_HAL_SITL/sitl_gps.cpp
- libraries/AP_HAL_SITL/sitl_ins.cpp
- libraries/AP_NavEKF2/AP_NavEKF2.cpp
- libraries/AP_NavEKF2/AP_NavEKF2.h
- libraries/AP_NavEKF3/AP_NavEKF3.cpp
- libraries/AP_NavEKF3/AP_NavEKF3.h
- libraries/DataFlash/LogFile.cpp
- libraries/DataFlash/LogStructure.h
- libraries/SITL/SIM_Aircraft.cpp
- libraries/SITL/SIM_Gimbal.cpp
- libraries/SITL/SITL.cpp
- libraries/SITL/SITL.h
This helps with tailsitters which spend a lot of time at pitch90
> Log quaternions

- mk/PX4/ROMFS/init.d/rcS
this never worked, and its a bad idea anyway
> PX4: removed attempt at formatting microSD

- libraries/DataFlash/LogFile.cpp
Addresses the bad data @priseborough saw here: https://github.com/ArduPilot/ardupilot/issues/5846#issuecomment-294378765
> Dataflash: Clamp GPS accuracy values

- libraries/AP_Notify/RCOutputRGBLed.cpp
- libraries/SRV_Channel/SRV_Channel.h
- libraries/SRV_Channel/SRV_Channels.cpp
this needs to use SRV_Channels so outputs don't get overridden by servo function code
> Notify: fixed RGBLed code

- ArduCopter/motors.cpp
if we have any auxillary servo channels we need to calculate the
output value
> Copter: output any servo channels on motor output

- libraries/AP_GPS/AP_GPS.cpp
- libraries/AP_GPS/AP_GPS.h
- libraries/AP_GPS/AP_GPS_SBP2.cpp
- libraries/AP_GPS/AP_GPS_SBP2.h
- libraries/AP_GPS/GPS_detect_state.h
- libraries/AP_HAL_SITL/SITL_State.h
- libraries/AP_HAL_SITL/sitl_gps.cpp
- libraries/SITL/SITL.h
This PR adds support for Swift Navigation's new Piksi Multi GPS (https://www.swiftnav.com/piksi-multi)
Piksi Multi speaks the Swift Binary Protocol, version 2 - a major split from the previous SBP version 0. We take care to ensure this addition keeps support for previous Piksi GPS users, while incorporating the new and much-improved featureset of Piksi Multi.
> GPS: Piksi Multi GPS Support

- libraries/AP_HAL_Linux/Thread.cpp
- libraries/AP_HAL_Linux/Util.h
> AP_HAL_Linux: fixes

- libraries/AP_UAVCAN/AP_UAVCAN.cpp
And maybe more issues while tests of UAVCAN ESCs
TODO:
~~- uavcan.equipment.safety.ArmingStatus~~
> AP_UAVCAN: ESC numbering correction

- libraries/AP_HAL_SITL/sitl_gps.cpp
Unused from https://github.com/ArduPilot/ardupilot/commit/341b926a430a3fbb5284ac2aac59d14152eb1c46
> AP_HAL_SITL: gps correct glitch

- README.md
Several of the links to developer's personal pages were formatted incorrectly.
> README: Fix broken links 

- APMrover2/APMrover2.cpp
- APMrover2/GCS_Mavlink.cpp
- APMrover2/GCS_Mavlink.h
- APMrover2/Log.cpp
- APMrover2/Parameters.cpp
- APMrover2/Parameters.h
- APMrover2/Rover.cpp
- APMrover2/Rover.h
- APMrover2/Steering.cpp
- APMrover2/commands_logic.cpp
- APMrover2/config.h
- APMrover2/control_modes.cpp
- APMrover2/crash_check.cpp
- APMrover2/failsafe.cpp
- APMrover2/navigation.cpp
- APMrover2/radio.cpp
- APMrover2/sensors.cpp
- APMrover2/system.cpp
- APMrover2/test.cpp
This PR finish to clean rover workspace. It switch to c++ cast, correct some missing style that weren't fix previously, make some variable const, remove some define that aren't use anywhere, correct some cast (supect leftover from arduino version)
Some cast are from float to unsign value . To correct at least the signum, I use a abs when necessary but there isn't protection agains overflow ...
> Rover cleanup2

- APMrover2/Steering.cpp
- libraries/AP_HAL_SITL/SITL_State.cpp
Hello,
This PR allow to use full power on on spot turn in skid steer config in manual mode. And limit SITL model input for motor between 1000 and 2000
> Rover: ouput range improvements

- libraries/AC_WPNav/AC_WPNav.cpp
When a copter completes a spline waypoint and the next waypoint is a straight line waypoint, the waypoint controller commands the vehicle to slow down for a moment before returning to the desired speed (held in WPNAV_SPEED).  To the user this appears as a slightly ugly twitch backwards.
The reason for the slow-down relates to how we use the "leash" differently in spline and straight-line waypoints.  The "leash" connects the vehicle and the target point that it's chasing.  The target point advances along the segment between the previous and next waypoint but is held back from traveling too far along the segment by this leash.
In the spline controller, the leash is a straight line between the vehicle and the target point  In the straight line controller however it's an "L" shape so it …
> AC_WPNav: reduce vehicle twitch between spline and straight waypoint commands

- ArduPlane/takeoff.cpp
This reduces pitch demand on takeoff when we have a roll error. For hand launches this can help when the launch is not well handled, or there is a cross-wind, as it prioritises getting level over pitch. It has been tested on a flying wing with cross-wind hand launches and found to improve the likelyhood of successful takeoffs.
> Plane: reduce pitch demand on takeoff on roll error

- libraries/AP_NavEKF/AP_Nav_Common.h
- libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_core.h
- libraries/DataFlash/LogFile.cpp
Improve initialisation and handling of the EKF3 IMU and EKF average time step values.
Add monitoring and logging of the EKF average time step.
> EKF: improvements to time step handling and monitoring

- Tools/scripts/decode_devid.py
useful for working out what sensors are installed from a log
> Tools: added decode_devid.py

- libraries/AP_Scheduler/AP_Scheduler.cpp
this is more useful for performance analysis of scheduler, using perf
command
> AP_Scheduler: adjust debug levels

- libraries/AP_GPS/AP_GPS_SBF.cpp
- libraries/AP_GPS/AP_GPS_SBF.h
Leverages the preflight config checks to ensure that the SD card is working, particularly valuable since Septentrio has a high chance of corrupting it's SD card's FS on shutdown if you haven't pressed the button.
> AP_GPS: SBF if RAW_DATA is enabled check that the GPS is succeeding at logging

- ArduCopter/ArduCopter.cpp
- ArduPlane/ArduPlane.cpp
- ArduSub/ArduSub.cpp
- libraries/AP_Notify/Display.cpp
Without this garbage remains on the display.
> AP_Notify display fix for unknown characters

- libraries/AP_Notify/Display_SH1106_I2C.cpp
- libraries/AP_Notify/Display_SSD1306_I2C.cpp
probably leftover from https://github.com/ArduPilot/ardupilot/pull/6162 But this wasn't detected by travis
> AP_Notify: remove unused variables

- APMrover2/APMrover2.cpp
- APMrover2/commands.cpp
- APMrover2/defines.h
This prevent to spam with home position change at 5Hz
> APMRover2: Reduce the home position reset when disarm

- libraries/AP_Notify/AP_Notify.cpp
Enable display for BeagleBone Blue
> AP_Notify: enable display for BeagleBone Blue

- Tools/scripts/build_binaries.sh
I guess we need to push to test?
Fix #6058
> Tools: add aerofc-v1 to autobuild

- libraries/GCS_MAVLink/GCS_Param.cpp
This helps avoid counting parameters on the main thread,
avoiding long-loops
> GCS_MAVLink: count parameters in param thread

- libraries/AP_Arming/AP_Arming.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp
> Spell in comments

- APMrover2/Rover.h
- libraries/AP_NavEKF3/AP_NavEKF3.h
- libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_core.h
> Spell comments

- ArduCopter/Copter.h
- ArduCopter/control_autotune.cpp
Tell the user, at great length, what their vehicle is doing during autotune.
Some of these are cryptic, but some not - particularly "pilot override active"!
> Copter autotune messages

- libraries/AP_HAL_Linux/RCInput_RPI.cpp
- libraries/AP_HAL_Linux/Scheduler.cpp
@patrickpoirier51 @LanderU @staroselskii can you give this a try?
Should fix #6233
> Fix RPI boards

- ArduSub/GCS_Mavlink.cpp
As per request @rmackay9 #6289 I submit the PR for the sub support.
Best regards
Paulo Neves
> Sub: Add MAV_CMD_DO_SET_CAM_TRIGG_DIST support.

- Tools/GIT_Test/GIT_Success.txt
I added my name to the list in GIT_Success.txt because of assignment of 3rd course, "Drone software engineer" which I'm participating in.
> Added my name to GIT_success.txt

- README.md
There was some odd markdown formatting in README.md (e.g., everything
was a block quote).  This commit cleans things up a bit.
> markdown fixes to README.md

- Tools/GIT_Test/GIT_Success.txt
the member of JAPAN drone software engineering school.
> Tools: add my name to GIT_Success.txt

- libraries/AP_NavEKF2/AP_NavEKF2_MagFusion.cpp
Fixed bug spotted by @luweikxy and reported here: https://github.com/ArduPilot/ardupilot/issues/6366#issuecomment-305829936
> AP_NavEKF2: Fix bug in declination fusion

- libraries/AP_Notify/OreoLED_PX4.cpp
The value of boolean is **true** or **false**.
> AP_Notify: Change to the value of boolean.

- ArduCopter/GCS_Mavlink.cpp
- libraries/AP_BoardConfig/AP_BoardConfig.cpp
- libraries/AP_BoardConfig/AP_BoardConfig.h
... also, if someone sets their board type incorrectly, this will allow them to correct their mistake
> Permit boards to boot in case of sensor failure

- libraries/AP_RangeFinder/AP_RangeFinder_VL53L0X.cpp
- libraries/AP_RangeFinder/AP_RangeFinder_VL53L0X.h
- libraries/AP_RangeFinder/RangeFinder.cpp
- libraries/AP_RangeFinder/RangeFinder.h
very short range, useful for small vehicles
> AP_RangeFinder: implement VL53L0X rangefinder

- APMrover2/Log.cpp
- APMrover2/system.cpp
- AntennaTracker/Log.cpp
- AntennaTracker/Tracker.h
- AntennaTracker/system.cpp
- ArduCopter/Log.cpp
- ArduCopter/motors.cpp
- ArduCopter/system.cpp
- ArduPlane/Log.cpp
- ArduPlane/system.cpp
- ArduSub/Log.cpp
- ArduSub/motors.cpp
- ArduSub/system.cpp
- Tools/Replay/Replay.cpp
- libraries/DataFlash/DataFlash.cpp
- libraries/DataFlash/DataFlash.h
- libraries/DataFlash/DataFlash_Backend.cpp
- libraries/DataFlash/DataFlash_Backend.h
- libraries/DataFlash/DataFlash_Block.cpp
- libraries/DataFlash/DataFlash_Block.h
- libraries/DataFlash/DataFlash_File.cpp
- libraries/DataFlash/DataFlash_File.h
- libraries/DataFlash/DataFlash_MAVLink.cpp
- libraries/DataFlash/DataFlash_MAVLink.h
- libraries/DataFlash/DataFlash_SITL.cpp
- libraries/DataFlash/DataFlash_SITL.h
- libraries/DataFlash/LogFile.cpp
- libraries/DataFlash/examples/DataFlash_AllTypes/DataFlash_AllTypes.cpp
- libraries/DataFlash/examples/DataFlash_test/DataFlash_test.cpp
> Correct health status of logging with LOG_DISARMED/multiple backends

- APMrover2/GCS_Mavlink.cpp
- AntennaTracker/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.cpp
- ArduSub/GCS_Mavlink.cpp
- libraries/DataFlash/DataFlash.cpp
- libraries/DataFlash/DataFlash.h
- libraries/GCS_MAVLink/GCS_Common.cpp
Also make the entry into DataFlash more generic
> Move MAVLINK_MSG_ID_REMOTE_LOG_BLOCK_STATUS handling up

- libraries/AP_NavEKF2/AP_NavEKF2_OptFlowFusion.cpp
- libraries/AP_NavEKF2/AP_NavEKF2_core.h
- libraries/AP_NavEKF3/AP_NavEKF3_OptFlowFusion.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_core.h
Thank you to luweikxy@163.com and @OXINARF for finding these.
> EKF: Fix bug preventing use of optical flow for terrain height estimation

- libraries/AP_Compass/AP_Compass_BMM150.cpp
- libraries/AP_Compass/AP_Compass_BMM150.h
fixed numerical errors and improve robustness of BMM150 driver
> Compass: BMM150 improvements

- libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_RngBcnFusion.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_core.h
**BACKGROUND**
The EKF3 uses a multi-hypothesis filter to resolve the height ambiguity when using range beacons that are co-planar in the horizontal (All beacons are at the same or similar height). This filter calculates the vertical position of the range beacons relative to the EKF origin using two hypothesis, one where the beacons are below the flight vehicle and one where they are above. The hypothesis with the most stable vertical position is used. The stability is calculated by low pass filtering the magnitude of the vertical offset changes resulting from each range measurement fusion.
**CHANGES**
This fixes the following bugs:
1) The vertical position calculated by the multi-hypothesis filter was only being updated when the hypothesis selection changed between upper/lower.
2) The …
> EKF3: Fix range beacon fusion bugs

- BUILD.md
- Tools/ardupilotwaf/boards.py
- wscript
Continuation of https://github.com/ArduPilot/ardupilot/pull/6379
> Add upload mechanism for Linux boards (v2)

- ArduCopter/AP_Arming.cpp
cleans up PR https://github.com/ArduPilot/ardupilot/pull/6557
> Use a notify singleton to eliminate common GCS code - cleanup

- APMrover2/radio.cpp
- APMrover2/system.cpp
only enable channels when everything is setup
> Rover: reoder rc and servo init

- libraries/AP_Baro/AP_Baro.cpp
This should have been updated as part of #5930.
> AP_Baro: Improve GND_TEMP parameter docs

- libraries/AP_NavEKF2/AP_NavEKF2.cpp
- libraries/AP_NavEKF2/AP_NavEKF2_Control.cpp
- libraries/AP_NavEKF2/AP_NavEKF2_Outputs.cpp
- libraries/AP_NavEKF3/AP_NavEKF3.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp
Addresses https://github.com/ArduPilot/ardupilot/issues/6594
Plots show local vertical position before and after change.
**Before**
**After**
> EKF: Fix height jump in copter when GPS checks pass in flight

- BUILD.md
@auturgy, this should complement your change to the wiki.
@guludo, this addresses your comments from the previous PR.
> build: fix typos and add example for --upload

- APMrover2/GCS_Mavlink.cpp
- AntennaTracker/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.cpp
- ArduSub/GCS_Mavlink.cpp
- libraries/AP_GPS/AP_GPS.cpp
- libraries/AP_GPS/AP_GPS.h
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
Based on this other PR: https://github.com/ArduPilot/ardupilot/pull/6667
> Move GPS injection message handling up to GCS_MAVLINK

- ArduSub/GCS_Mavlink.cpp
Missed this one in 2aaaba8397284ef48fdc687bfa7b1935b141ca5d
> Sub: handle GPS_INPUT in base GCS_MAVLINK class

- libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
See 
https://github.com/ArduPilot/ardupilot/commit/c7f6d52065d46c82dc329222a59527c928c2e06e#commitcomment-23337804
> AP_NavEKF3: Fix bug in wheel odometry timestamp correction

- ArduSub/ArduSub.cpp
4eee3b1317b954c7c1df16ba2d264e2af695b77d fixed this in Copter
> Sub: fix underflow in scheduler

- Tools/scripts/decode_devid.py
print out device IDs and bus names
> Tools: improve devid decode

- libraries/AP_Compass/AP_Compass_AK8963.cpp
- libraries/AP_Compass/AP_Compass_AK8963.h
- libraries/AP_HAL/Scheduler.h
- libraries/AP_HAL_Linux/Scheduler.cpp
- libraries/AP_HAL_Linux/Scheduler.h
This has been deprecated by the thread per bus infra.
> Remove timeslice support

- Tools/scripts/build_binaries.sh
this switches to waf for all the px4 builds, plus adds px4pro It also
removes apm1/apm2 for plane build, and removes the download directory
for PX4IO
> Tools: updates to build_binaries.sh (use waf)

- libraries/AP_HAL_PX4/HAL_PX4_Class.cpp
It looks like this might have been missing from the original PR: https://github.com/ArduPilot/ardupilot/pull/3927
> AP_HAL_PX4: Adds UARTF as command line option

- ArduCopter/ArduCopter.cpp
- ArduCopter/config.h
- ArduSub/ArduSub.cpp
- ArduSub/config.h
This macro may not be accurate...
Note this includes #6826
> Eliminate main loop macros

- ArduPlane/takeoff.cpp
- libraries/SITL/SIM_Plane.cpp
- libraries/SITL/SIM_Plane.h
Fixes the combination of min-accel and delay, for bungee launch
See
https://discuss.ardupilot.org/t/tkoff-thr-minacc-and-tkoff-thr-delay-doesnt-work-together/19928
> Plane: fixed bungee auto launch

- libraries/AP_ADSB/AP_ADSB.cpp
- libraries/AP_GPS/AP_GPS_SIRF.cpp
Misc commits from #6779 split out here - alternative to #6873.
> AP_ADSB: use references

- ArduPlane/quadplane.cpp
- ArduPlane/quadplane.h
this fixes a sudden throttle drop when starting the descent in QRTL mode
thanks to Marco for finding this issue
> Plane: adjust target altitude slowly in QRTL mode

- Tools/Replay/LR_MsgHandler.cpp
- Tools/Replay/LR_MsgHandler.h
- Tools/Replay/LogReader.cpp
- Tools/Replay/Replay.cpp
This avoid duplication of parameter setting logic.
> Replay: pass a lambda function to LR_MsgHandler_PARM to set parameters

- APMrover2/GCS_Mavlink.cpp
- AntennaTracker/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.cpp
- Tools/autotest/apmrover2.py
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
The current message we use to arm the vehicle is deprecated according to `common.xml`.
> MAV_CMD_DO_SET_MODE support

- ArduPlane/quadplane.cpp
> Plane: fix parameter units

- ArduCopter/control_althold.cpp
- ArduCopter/control_loiter.cpp
- ArduCopter/control_poshold.cpp
- ArduCopter/flight_mode.cpp
- ArduCopter/radio.cpp
Fixes a problem with H_SV_MAN and with mode-change when rotor not up to speed
@ping @R-Lefebvre 
fixes issue #6956
> Copter: some fixes for open heli issues

- Tools/scripts/update_wiki.py
SyntaxError: print() is a function in Python 3
> Tools: update_wiki.py: fix syntax error

- libraries/DataFlash/DataFlash.h
- libraries/DataFlash/LogFile.cpp
Also fixes two bugs:
- incorrect packet type used for battery cells
- IMUDT dleta-velocity incorrect for third IMU
> Factor various logging methods in DataFlash

- libraries/AP_Notify/RCOutputRGBLed.cpp
- libraries/AP_Notify/RCOutputRGBLed.h
Some RGB leds controlled with an inverted logic. This class addresses
this.
> Add RCOutputRGBLedInverted

- ArduPlane/quadplane.cpp
- libraries/AP_Motors/AP_MotorsHeli_Quad.cpp
- libraries/AP_Motors/AP_Motors_Class.cpp
- libraries/SRV_Channel/SRV_Channel.h
This fixes a problem noticed by @OXINARF in the recent change to use SRV_Channels in AP_Motors
> Fixed motors > 8

- libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp
Found by pavloblindnology - see https://github.com/ArduPilot/ardupilot/pull/6685#pullrequestreview-72538650
> EKF3: Fix bugs in use of wheel encoder data

- libraries/AP_BattMonitor/AP_BattMonitor.cpp
> AP_BattMonitor: Solve typo in BATT2 description

- libraries/AP_Beacon/AP_Beacon_Marvelmind.cpp
- libraries/AP_Beacon/AP_Beacon_Marvelmind.h
This is a subset of #6474 with a couple of small changes from me. @ptsneves I hope you are OK with this
It should close #7099
> AP_Beacon: Corrected possible use of nullptr memory.

- ArduPlane/Parameters.cpp
- ArduPlane/servos.cpp
this was lost in the conversion of SRV_Channels
> Plane: re-implement MIXING_OFFSET

- Tools/autotest/sim_vehicle.py
this fixes issue #7180 with an infinite sleep loop, before this solution I've tried with `time.sleep(sys.maxint)` or `time.sleep(sys.maxsize)` with no luck
> sim_vehicle.py: fix wait_unlimited

- ArduCopter/control_althold.cpp
- ArduCopter/heli_control_acro.cpp
- ArduCopter/heli_control_stabilize.cpp
- libraries/AC_AttitudeControl/AC_AttitudeControl.h
Requesting the swash behavior fix that was added to master be added to Copter 3.5.4
> Add Swash behavior fix to 3.5.4

- ArduCopter/control_safe_rtl.cpp
> Copter: add missing disarm-on-land parameter to rtl_land_run

- libraries/AP_Compass/AP_Compass.cpp
- libraries/AP_Compass/AP_Compass_LIS3MDL.h
> AP_Compass: probe for LIS3MDL on 0x1e

- ArduCopter/control_land.cpp
The method name is "land_gps_run" and the method name of the method header is "land_run". 
The method header is modified.
> Copter: Modify method name in method header.

- APMrover2/Rover.h
- ArduCopter/Copter.h
- ArduPlane/Plane.h
- ArduSub/Sub.h
- libraries/AP_Camera/AP_Camera.cpp
- libraries/AP_Camera/AP_Camera.h
- libraries/DataFlash/DataFlash.h
- libraries/DataFlash/LogFile.cpp
> AP_Camera - use gps singleton

- APMrover2/AP_MotorsUGV.cpp
- ArduCopter/compassmot.cpp
- ArduCopter/esc_calibration.cpp
- ArduCopter/motors.cpp
- ArduPlane/radio.cpp
- ArduPlane/servos.cpp
- ArduSub/GCS_Mavlink.cpp
- Tools/ardupilotwaf/ardupilotwaf.py
- libraries/AP_SerialManager/AP_SerialManager.cpp
- libraries/AP_SerialManager/AP_SerialManager.h
- libraries/AP_Volz_Protocol/AP_Volz_Protocol.cpp
- libraries/AP_Volz_Protocol/AP_Volz_Protocol.h
- libraries/SRV_Channel/SRV_Channel.h
- libraries/SRV_Channel/SRV_Channels.cpp
- mk/make.inc
Hi 
proceeding PR 7109:
https://github.com/ArduPilot/ardupilot/pull/7109
last pull request lost connection to my repository, so i took fresh master, added all changes and committed with comments, tested on pixhawk with VOLZ DA26 and DA30.
lest try to finish this merge.
> adding support for volz servos serial protocol

- libraries/SITL/SIM_Submarine.cpp
- libraries/SITL/SIM_Submarine.h
Fix bluerobotics/ardusub/issues/128
Co-Authored-By: Jacob Walser <jwalser90@gmail.com>
> SIM_Submarine: Solve problem when frame is above water level

- APMrover2/commands_logic.cpp
- libraries/AP_Mission/AP_Mission.cpp
- libraries/AP_Mission/AP_Mission.h
```
APM: Reached waypoint #4
APM: Executing ChangeSpeed(ID=178)
APM: Cruise speed: 1.0 m/s
APM: Executing WP(ID=16)
waypoint 6
APM: Reached waypoint #6
APM: Executing WP(ID=16)
```
> Short description for mission item types

- ArduCopter/GCS_Mavlink.cpp
The result variable is not used, but at least it gets documented :)
> Copter: Update the result of a MavLink message, this is a NFC

- ArduSub/radio.cpp
> Sub: Remove unnecessary cast in init_rc_out

- APMrover2/mode.cpp
- APMrover2/mode_manual.cpp
Both steering and acro modes can benefit from this check
> Rover: move RC failsafe check up

- Tools/autotest/sim_vehicle.py
> Tools: fix sim_vehicle.py tab on mac

- libraries/AP_JSButton/AP_JSButton.cpp
> AP_JSButton: Simplifies logic

- libraries/AP_HAL_SITL/UARTDriver.cpp
hardcore const enforcement police!!!!
> AP_HAL_SITL: add const

- ArduCopter/.gitignore
> ArduCopter: remove useless .gitignore from directory

- ArduCopter/Attitude.cpp
- ArduCopter/Copter.h
- ArduCopter/control_guided.cpp
- ArduCopter/defines.h
- ArduCopter/navigation.cpp
- ArduCopter/position_vector.cpp
- ArduSub/Attitude.cpp
- ArduSub/Sub.h
- ArduSub/control_auto.cpp
- ArduSub/control_guided.cpp
- ArduSub/defines.h
- ArduSub/fence.cpp
- ArduSub/position_vector.cpp
- libraries/AC_WPNav/AC_Circle.cpp
- libraries/AC_WPNav/AC_Circle.h
- libraries/AC_WPNav/AC_WPNav.cpp
- libraries/AC_WPNav/AC_WPNav.h
- libraries/AP_Math/definitions.h
- libraries/AP_Math/location.cpp
- libraries/AP_Math/location.h
@peterbarker This one also removes more lines than it adds :)
> Use DEGX100 and move two functions to AP_Math (NFC)

- APMrover2/GCS_Mavlink.cpp
I am not fan of the speed vector handling for rover,but I understand that it is how NED navigation should be handle. This should handle the case where people want to do vectoring or not (I mostly thinking about boat, as for now it isn't possible on rover)
> Rover: adjust setpoint_velocity handling

- ArduPlane/servos.cpp
Fix for https://github.com/ArduPilot/ardupilot/issues/7255
> Plane: Enforce THR_MIN/THR_MAX in VTOL modes

- ArduCopter/mode.cpp
init() may have changed all sorts of things about the
vehicle - wp navigation, position controllers, attitude controllers...
Do the heli check before doing any of that so we don't change state and
then fail to change mode
> Copter: correct checking of heli mode change

- libraries/AP_SerialManager/AP_SerialManager.cpp
Looks good in local wiki build.
> AP_SerialManager: add Volz and Sbus protocols to param metadata

- ArduCopter/fence.cpp
- ArduSub/fence.cpp
- libraries/AC_Fence/AC_Fence.cpp
- libraries/AC_Fence/AC_Fence.h
> Change AC_Fence to get home distance from AHRS

- Tools/scripts/apj_tool.py
- libraries/AP_Param/AP_Param.cpp
- libraries/AP_Param/AP_Param.h
This add Tools/scripts/apj_tool.py which can modify a compiled ArduPilot firmware to change the default parameters. It uses a set of embedded parameters in AP_Param.cpp
As discussed on the dev call a few weeks ago
> Tools: added apj_tool.py

- libraries/AP_AHRS/AP_AHRS.cpp
- libraries/AP_AHRS/AP_AHRS.h
- libraries/AP_AHRS/AP_AHRS_DCM.cpp
- libraries/AP_AHRS/AP_AHRS_DCM.h
- libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
- libraries/AP_AHRS/AP_AHRS_NavEKF.h
Some getter weren't const 
add some constcorrectness
Correct some variable assignement
> AP_AHRS: make getter const and correct some assignements

- Tools/autotest/pysim/vehicleinfo.py
[How to test](https://gist.github.com/patrickelectric/60a1d300e0afadf85066cc5d8e3d51ff)
> Tools: Add gazebo-bluerov2 on vehicleinfo.py

- ArduCopter/fence.cpp
- ArduSub/fence.cpp
- libraries/AC_Fence/AC_Fence.cpp
- libraries/AC_Fence/AC_Fence.h
Also rename it to just check().
Also remove unneeded initialisers.
> AC_Fence: Remove argument to check_fence()

- ArduCopter/mode_acro.cpp
- ArduCopter/mode_auto.cpp
- ArduCopter/mode_guided.cpp
- ArduCopter/mode_stabilize.cpp
- ArduCopter/mode_throw.cpp
This is based on #5227 - it should not be merged before that one.
The patches here change behaviour for helicopters.  It appears that these changes would be for the better!
> More zero throttle and relax factoring

- Tools/autotest/sim_vehicle.py
This will rebuild and use the XML file we generate from our
source code which conveys information about our parameters.
When using this option, "param help PARAMETERNAME" should reflect
changes made to the parameter metadata for PARAMETERNAME.
> Tools: add --fresh-params option to sim_vehicle.py

- ArduCopter/sensors.cpp
- libraries/AC_Fence/AC_Fence.cpp
- libraries/AC_Fence/AC_Fence.h
Also change SYS_STATUS bit to be unhealthy if boundary invalid
> AC_Fence: add a pre-arm check for polygon fence validity

- libraries/AP_GPS/AP_GPS.cpp
Thanks to @ender-chen for noticing, closes #7510
> AP_GPS: Remove unused blending math

- libraries/AP_HAL_Linux/SerialDevice.h
> AP_HAL_Linux: fix typo

- libraries/DataFlash/DataFlash.cpp
- libraries/DataFlash/DataFlash.h
Should only be merged after the units PR has gone in.
> Log_Write() validation

- libraries/RC_Channel/RC_Channel.cpp
- libraries/RC_Channel/RC_Channel.h
this is quite a costly function due to scan in AP_Param. It takes
about 4 to 5 milliseconds when done as part of AP_Arming
> RC_Channel: improved efficiency of min_max_configured

- APMrover2/Parameters.cpp
- APMrover2/failsafe.cpp
Add failsafe actions SmartRTL or RTL and SmartRTL or Hold
Tested in STIL and with build_all.sh #7553
> Rover: Add SmartRTL failsafe action

- APMrover2/GCS_Mavlink.cpp
#7447  tested in SITL with dronekit
> Rover: now sends SCALED_PRESSURE msg

- libraries/AP_HAL_Linux/HAL_Linux_Class.cpp
> AP_HAL_Linux: fix comment

- ArduPlane/quadplane.cpp
- libraries/AP_Param/AP_Param.cpp
- libraries/AP_Param/AP_Param.h
This adds the needed parameter conversion for #7551 
This has not been flight tested (also P #7551 has not been flight tested on a quadplane as far as I know)
> Plane: convert P controller PIDs

- libraries/AP_Motors/AP_MotorsCoax.cpp
- libraries/AP_Motors/AP_MotorsMatrix.cpp
- libraries/AP_Motors/AP_MotorsSingle.cpp
- libraries/AP_Motors/AP_MotorsTri.cpp
This is taken from https://github.com/ArduPilot/ardupilot/pull/7587 .
It is a NFC . I got another PR with more refactoring, the goal here is just to simply @night-ghost PR
> AP_Motors: reduce unnecessary multiple call of get_compensation_gain()

- ArduCopter/Copter.h
- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/defines.h
- ArduCopter/switches.cpp
Like a RC trainer mode but with rc_override.
> Copter: Add a switch option to enable/disable RC_Override

- libraries/AP_Airspeed/AP_Airspeed.cpp
> AP_Airspeed: Fix ARSPD2_TYPE docs

- libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
I think that the mode judgment of the first "PV_AidingMode" can be replaced with a switch statement.
I have PR newly closed the following PR.
AP_NavEKF3: Changed if statements to switch statement. #5439
> AP_NavEKF3: Change the if statement to a switch statement.

- libraries/AP_HAL_Linux/RCOutput_AeroIO.cpp
> AP_HAL_Linux: fix memory deallocation

- libraries/AP_Baro/AP_Baro_BMP085.cpp
- libraries/AP_Baro/AP_Baro_BMP085.h
refreshed and adopted to new API.
> working BMP085 driver

- libraries/AP_HAL_SITL/SITL_State.cpp
- libraries/SITL/SIM_Aircraft.cpp
- libraries/SITL/SIM_Aircraft.h
- libraries/SITL/SITL.cpp
- libraries/SITL/SITL.h
fix-up of PR https://github.com/ArduPilot/ardupilot/pull/7623
> Add SIM_WIND_DIR_Z parameter for SITL v2

- libraries/AP_UAVCAN/AP_UAVCAN.cpp
- libraries/AP_UAVCAN/AP_UAVCAN.h
we're getting lots of things in do_cyclic so lets move each function group into their own function
non-functional change but will likely cause a merge conflict with https://github.com/ArduPilot/ardupilot/pull/7556
> UAVCAN: refactor and cleanup do_cyclic

- ArduCopter/Copter.h
- ArduCopter/Parameters.cpp
- ArduCopter/mode.h
- ArduCopter/mode_flowhold.cpp
reduces build size on px4-v2 by 4k
> Copter: make flowhold mode conditional

- Tools/scripts/build-jsbsim.sh
- Tools/scripts/install-prereqs-ubuntu.sh
- Tools/vagrant/initvagrant-trusty64.sh
- Tools/vagrant/initvagrant.sh
- Tools/vagrant/shellinit.sh
- Vagrantfile
Tools: Vagrantfile: add trusty64 Vagrant VM
Tools: remove unused variable definition
Tools: Vagrantfile: add zesty64
> Tools: add more Vagrant virtual machines

- Tools/ardupilotwaf/px_uploader.py
Added a * to enable recognition of usbmodems
> Updated the usbmodem line for upload

- ArduSub/GCS_Mavlink.cpp
- libraries/GCS_MAVLink/GCS_Common.cpp
Perhaps we should forcibly reboot as well?
> Handle reset params to defaults request

- libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
Fixes https://github.com/ArduPilot/ardupilot/issues/7643
Thank you https://github.com/lesliefan1 for spotting this.
> AP_NavEKF3: Fix origin height estimator indexing bug

- libraries/AP_Scheduler/AP_Scheduler.cpp
- libraries/DataFlash/LogStructure.h
> add load_average() to PM log message

- ArduSub/GCS_Mavlink.cpp
- ArduSub/joystick.cpp
- ArduSub/radio.cpp
> Sub: Add camera pan functionality

- ArduCopter/mode.cpp
this was lost in the mode restructuring
> Copter: re-added reason to mode change log msg

- Tools/autotest/build-with-disabled-features.py
This script disables features found in APM_config.h and ensures the build still works.
> Build with disabled features

- libraries/AP_HAL_F4Light/hardware/osd/osd.cpp
- libraries/AP_HAL_F4Light/hardware/osd/osd.h
- libraries/AP_HAL_F4Light/hardware/osd/osd_core/Params.h
- libraries/AP_HAL_F4Light/hardware/osd/osd_core/compat.h
> AP_HAL_F4light: fixes OSD compilation issue

- Tools/ardupilotwaf/boards.py
- libraries/AP_HAL_ChibiOS/hwdef/fmuv2/hwdef.dat
this adds a 1M flash limited build target
> Added fmuv2 build target

- Tools/scripts/build_binaries.py
Also correct some debug and add flake8 compliance
> Tools: build_binaries.py: catch exception on copy failure

- APMrover2/APMrover2.cpp
- APMrover2/Parameters.cpp
- APMrover2/Parameters.h
- APMrover2/config.h
- APMrover2/system.cpp
- ArduCopter/ArduCopter.cpp
- ArduCopter/Parameters.cpp
- ArduCopter/Parameters.h
- ArduCopter/config.h
- ArduCopter/land_detector.cpp
- ArduCopter/system.cpp
- ArduPlane/ArduPlane.cpp
- ArduPlane/Parameters.cpp
- ArduPlane/Parameters.h
- ArduPlane/config.h
- ArduPlane/is_flying.cpp
- ArduPlane/system.cpp
- libraries/AP_HAL/board/f4light.h
> AP_HAL_F4light: add an ability to disable stats 

- ArduSub/commands_logic.cpp
I think that it is better to combine the value of the comment and the definition value.
> Sub: Adjust to the defined value.

- ArduCopter/radio.cpp
rework from https://github.com/ArduPilot/ardupilot/pull/7793 , thanks @chobitsfan for finding the error
> Copter : allow rc_override input at start

- libraries/AP_Notify/AP_Notify.cpp
- libraries/AP_Notify/UAVCAN_RGB_LED.cpp
- libraries/AP_Notify/UAVCAN_RGB_LED.h
- libraries/AP_UAVCAN/AP_UAVCAN.cpp
- libraries/AP_UAVCAN/AP_UAVCAN.h
a rebase of https://github.com/ArduPilot/ardupilot/pull/7556
> AP_Notify: Support for UAVCAN RGB LEDs v2

- libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
- libraries/AP_UAVCAN/AP_UAVCAN.cpp
- libraries/AP_UAVCAN/AP_UAVCAN.h
I broke PR https://github.com/ArduPilot/ardupilot/pull/6528 by testing the github built-in merge conflict fixer feature but it created a merge commit that was only visible within github and I wasn't able to delete it. SOOOoooo I made a new PR to replace it with the same commits plus two cleanup ones.
> AP_AHRS: UAVCAN Position and attitude broadcast v2

- ArduPlane/GCS_Mavlink.cpp
- ArduPlane/Plane.h
- ArduPlane/defines.h
This was just irking me with the amount of copy/paste when I went to add an additional value to this message.
> Plane: Consolidate some of the MAVLink PID details

- ArduCopter/APM_Config.h
- ArduCopter/Copter.h
- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/Parameters.cpp
- ArduCopter/Parameters.h
- ArduCopter/config.h
- ArduCopter/defines.h
- ArduCopter/make.inc
- ArduCopter/mode.cpp
- ArduCopter/mode.h
- ArduCopter/mode_chase.cpp
- ArduCopter/mode_follow.cpp
- ArduCopter/mode_guided.cpp
- ArduCopter/wscript
- libraries/AC_Avoidance/AC_Avoid.cpp
- libraries/AC_Avoidance/AC_Avoid.h
- libraries/AP_Follow/AP_Follow.cpp
- libraries/AP_Follow/AP_Follow.h
#This PR builds on this earlier PR from @peterbarker (https://github.com/ArduPilot/ardupilot/pull/7460) to add "Chase" mode which allows a vehicle to follow another vehicle or ground station.
- chase mode is built on Guided mode's velocity controller to fly towards a vehicle's position provided by the AP_Follow library.  The control uses the other vehicle's velocity as a base and then adds a correction to try and reduce the position error.
- AP_Follow library is responsible for:
- consuming mavlink messages from the target vehicle (currently only GLOBAL_POSITION_INT is supported)
- providing a 3D distance vector to the other vehicle both with and without "offsets" (both are required to allow moving to a specified distance from the other vehicle while remaining pointed at it) and a 3D …
> Copter: chase/follow mode (attempt 2)

- libraries/AP_Baro/AP_Baro.cpp
- libraries/AP_Baro/AP_Baro_DPS280.cpp
- libraries/AP_Baro/AP_Baro_DPS280.h
- libraries/AP_Baro/AP_Baro_FBM320.cpp
- libraries/AP_Baro/AP_Baro_FBM320.h
- libraries/AP_HAL/AP_HAL_Boards.h
This adds drivers for the FBM320 and DPS280 barometers
> Baro: two new drivers

- libraries/AP_HAL_F4Light/boards/f4light_AirbotV2/1_read_me.md
- libraries/AP_HAL_F4Light/boards/f4light_Revolution/1_read_ME.md
- libraries/AP_HAL_F4Light/boards/f4light_Revolution_EE128/1_read_ME.md
- libraries/AP_HAL_F4Light/boards/f4light_Revolution_SD/1_read_ME.md
- libraries/AP_HAL_F4Light/boards/f4light_cl_racing/1_read_me.md
inspired by PR from estebanavv
> HAL_F4light: fixed board's 1_readme.md

- libraries/AP_Declination/generate/generate.py
Whitespace-only PR.  New script so no history is lost.
> AP_Declination: flake8 compliance for new generate script

- Tools/autotest/bisect-helper.py
This is the start of a tool to help bisect problems with ArduPilot.
Currently it only helps bisect build errors.
I am hoping to improve this to be able to (a) run steps from the autotest suite and (b) run dronekit-python scripts.  This script is useful as-is, however.
> Tools: add bisect-helper.py

- libraries/AP_InertialSensor/AP_InertialSensor.h
@tridge found that we were applying the wrong scaling factors.  Again.
> AP_InertialSensor: Correct scaling of batch data

- libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
this restores the behavior lost with the 20789 driver change
> AP_InerialSensor: setup INT_PIN_CFG correctly

- Tools/scripts/install-prereqs-mac.sh
add a script to install dependencies for mac to compile ardupilot code
> add install-prereqs-mac.sh

- libraries/AP_HAL/board/f4light.h
- libraries/AP_HAL_F4Light/boards/f4light_AirbotV2/board.h
- libraries/AP_HAL_F4Light/boards/f4light_Revolution_EE128/1_read_ME.md
- libraries/AP_HAL_F4Light/boards/f4light_Revolution_EE128/board.h
- libraries/AP_HAL_F4Light/boards/f4light_Revolution_EE128/support/UPLOAD-DFU-plane.sh
- libraries/AP_HAL_F4Light/boards/f4light_Revolution_SD/board.h
- libraries/AP_HAL_F4Light/hardware/hal/systick.c
also small correction of support scripts
> HAL_F4Light: fixed parameter's numbers for some boards

- ArduCopter/Parameters.cpp
these were not updated correctly on merge
> Copter: fixed docs for Follow mode number

- Tools/autotest/run_in_terminal_window.sh
Should fix problems with spaces in usernames.
> Tools: correct quoting in run_in_terminal_window.sh

- ArduCopter/mode_auto.cpp
git history on these lines is not important, this is a simple else
> Copter: Fix else formating (NFC)

- Tools/autotest/apmrover2.py
- Tools/autotest/arducopter.py
- Tools/autotest/arduplane.py
- Tools/autotest/ardusub.py
- Tools/autotest/autotest.py
- Tools/autotest/common.py
- Tools/autotest/quadplane.py
Replaces https://github.com/ArduPilot/ardupilot/pull/7589
This is @khancyr 's work, squashed, corrected a little, and with flake8 compliance on top.
This looks like a complete rewrite because of the indentation changes, so wide-ranging changes aren't a bad idea while we're at it.
> autotest: Create and use objects for vehicle tests

- libraries/AP_Mount/AP_Mount.cpp
- libraries/AP_Mount/AP_Mount.h
- libraries/AP_Mount/AP_Mount_SoloGimbal.cpp
- libraries/AP_Mount/SoloGimbal.cpp
- libraries/AP_Mount/SoloGimbal.h
- libraries/AP_Mount/SoloGimbal_Parameters.cpp
- libraries/AP_Mount/SoloGimbal_Parameters.h
> AP_Mount: use dataflash singleton

- libraries/AP_Beacon/AP_Beacon_Marvelmind.cpp
- libraries/AP_Beacon/AP_Beacon_Marvelmind.h
This should improve the accuracy a lot, by replacing a workaround with the proper solution.
> Use marvelmind raw distances in the EKF

- ArduPlane/commands_logic.cpp
Follow up on issue #7934 to avoid too early exit from loiter_to_alt.
> [Plane] Fix verify_loiter_heading acceptance criteria.

- ArduCopter/motor_test.cpp
- libraries/AP_HAL/utility/print_vprintf.cpp
- libraries/AP_TempCalibration/AP_TempCalibration.cpp
> Fallthrough

- libraries/AP_Airspeed/AP_Airspeed.cpp
- libraries/AP_Airspeed/AP_Airspeed.h
- libraries/GCS_MAVLink/GCS_Common.cpp
This corrects the issue in #6642 and uses a singleton to do so.
> Fix SCALED_PRESSURE.press_diff and create Airspeed singleton

- libraries/AP_Scheduler/AP_Scheduler.cpp
This should be completely NFC.
It simply replaces nested `if` statements with a pair of `continue`s.
> Tidy scheduler loop function (NFC)

- libraries/AP_HAL_Linux/CAN.cpp
Apparently this code came in part from libuavcan that defines this
struct Control. They also had the same issue detailed on
https://github.com/UAVCAN/libuavcan/issues/116.
The solution here is much simpler though: stick to the design of cmsg()
even if it's C. As per cmsg(3), use a union together with CMSG_SPACE().
> AP_HAL_Linux: fix build error with flexible array

- libraries/AP_Notify/AP_BoardLED2.cpp
- libraries/AP_Notify/AP_BoardLED2.h
- libraries/AP_Notify/AP_Notify.cpp
- libraries/AP_Notify/AP_Notify.h
- libraries/AP_Notify/Buzzer.cpp
- libraries/AP_Notify/Buzzer.h
+ buzzer pin as parameter and support for inverted buzzer
> full system status on 2 LEDs

- AntennaTracker/GCS_Mavlink.cpp
- AntennaTracker/GCS_Mavlink.h
- AntennaTracker/GCS_Tracker.cpp
- AntennaTracker/GCS_Tracker.h
- AntennaTracker/Tracker.h
- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
- libraries/AP_AccelCal/AP_AccelCal.cpp
- libraries/AP_AccelCal/AP_AccelCal.h
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
- libraries/GCS_MAVLink/GCS_MAVLink.cpp
We can now use inheritance to achieve the same result of this but in a cleaner fashion.
> Remove msg_snoop MAVLink functionality

- ArduCopter/mode.cpp
> Copter: correct compilation when precland is disabled

- ArduCopter/wscript
- wscript
this makes things less confusing for users
> waf: split copter and heli builds

- libraries/DataFlash/LogFile.cpp
we were logging all baros to one message
thanks to @Naterater for noticing
> AP_Baro: fixed multi-baro logging

- libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
- libraries/AP_InertialSensor/AP_InertialSensor_Invensense.h
this fixes issue from #8118 too
> AP_InertialSensor: use multiply for fifo scale factors

- libraries/AP_HAL_ChibiOS/ToneAlarm.cpp
- libraries/AP_HAL_Linux/ToneAlarm.cpp
bugfix part of https://github.com/ArduPilot/ardupilot/pull/8095
> tonealarm bugfix

- libraries/AP_GPS/AP_GPS_MAV.cpp
> AP_GPS: Allow HIL_GPS to flag vertical velocity

- libraries/AP_HAL/board/f4light.h
- libraries/AP_HAL_F4Light/RC_DSM_parser.cpp
- libraries/AP_HAL_F4Light/boards/f4light_Airbot/board.h
- libraries/DataFlash/DataFlash.cpp
- libraries/DataFlash/DataFlash_Revo.cpp
- mk/board_F4Light.mk
- mk/help.mk
when BetterStream lost a lots of methods
> HAL_F4light: Fixed build after api changes

- libraries/AP_NavEKF/AP_Nav_Common.h
Bikeshedding from @peterbarker and @khancyr on gitter... I cared primarily about adding the static asserts, the bools were to make them happy.
> AP_NavEKF: Make the status unions use bool, add static asserts

- libraries/AP_Baro/AP_Baro.cpp
- libraries/AP_Baro/AP_Baro.h
- libraries/AP_Baro/AP_Baro_BMP085.cpp
- libraries/AP_Baro/AP_Baro_BMP280.cpp
- libraries/AP_Baro/AP_Baro_Backend.cpp
- libraries/AP_Baro/AP_Baro_Backend.h
- libraries/AP_Baro/AP_Baro_DPS280.cpp
- libraries/AP_Baro/AP_Baro_FBM320.cpp
- libraries/AP_Baro/AP_Baro_ICM20789.cpp
- libraries/AP_Baro/AP_Baro_KellerLD.cpp
- libraries/AP_Baro/AP_Baro_MS5611.cpp
- libraries/AP_Compass/AP_Compass.cpp
- libraries/AP_Compass/AP_Compass.h
- libraries/AP_Compass/AP_Compass_Backend.cpp
- libraries/AP_Compass/AP_Compass_Backend.h
- libraries/AP_Compass/AP_Compass_HMC5843.cpp
- libraries/AP_Compass/AP_Compass_MAG3110.cpp
- libraries/AP_Compass/AP_Compass_QMC5883L.cpp
which usually used on long wires
> AP_Baro & AP_Compass:  added range filter to backend, added its usage to some sensors

- Tools/ardupilotwaf/chibios.py
- libraries/AP_HAL_ChibiOS/hwdef/skyviper-f412/hwdef.dat
- libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450/hwdef.dat
> waf: only build abin binary when needed

- APMrover2/APMrover2.cpp
- APMrover2/Log.cpp
- APMrover2/Rover.h
- APMrover2/system.cpp
- AntennaTracker/AntennaTracker.cpp
- AntennaTracker/Log.cpp
- AntennaTracker/Tracker.h
- AntennaTracker/sensors.cpp
- AntennaTracker/system.cpp
- ArduCopter/Copter.h
- ArduCopter/Log.cpp
- ArduCopter/sensors.cpp
- ArduCopter/system.cpp
- ArduPlane/ArduPlane.cpp
- ArduPlane/Log.cpp
- ArduPlane/Plane.h
- ArduPlane/system.cpp
- ArduSub/Log.cpp
- ArduSub/Sub.h
- ArduSub/sensors.cpp
- ArduSub/system.cpp
- libraries/AP_Baro/AP_Baro.cpp
- libraries/AP_Baro/AP_Baro.h
... and out of all the vehicle code
> Move Log_Write_Baro calls into Baro's update

- libraries/AP_BoardConfig/AP_BoardConfig.cpp
- libraries/AP_BoardConfig/AP_BoardConfig.h
- libraries/AP_Compass/AP_Compass.cpp
- libraries/AP_HAL_ChibiOS/hwdef/f4by-ch/hwdef.dat
add support ext compass hmc5883l via external i2c
add configutation parameter PWM count
add usart2 for telemetry
fix: ram size
fix: usart3 for gps
> board:f4by chibios configutation rework

- libraries/AP_BoardConfig/AP_BoardConfig.h
- libraries/AP_HAL_ChibiOS/RCOutput.cpp
- libraries/AP_HAL_ChibiOS/RCOutput.h
thanks to @sh83 for noticing this
> ChibiOS: fixed pwm output on some boards

- ArduCopter/Copter.h
- ArduCopter/Log.cpp
- ArduCopter/Parameters.cpp
- ArduCopter/defines.h
- ArduCopter/mode.h
- ArduCopter/mode_throw.cpp
- libraries/DataFlash/DataFlash.cpp
Just a namespace change, really.
> Copter: move throw logging into ModeThrow

- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
> GCS_MAVLink: fix VISP logging for ATT_POS_MOCAP mocap messages

- ArduSub/ArduSub.cpp
- ArduSub/Sub.h
- ArduSub/control_althold.cpp
- ArduSub/control_surface.cpp
> Sub: Send a clear message if depth sensor is not connected

- libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro/hwdef.dat
Fixed current and voltage defines (thanks Andrea Belloni for testing build)
Added SBUS_INVERT for Omnibus F4 V3
> HAL_ChibiOS: Fixed current and voltage sense on OmnibusF4PRO

- APMrover2/Parameters.pde
- AntennaTracker/Parameters.pde
- ArduCopter/Parameters.pde
- ArduPlane/Parameters.pde
- ArduSub/Parameters.pde
these were here for ancient MissionPlanner versions
ping @meee1
> Remove old pde files

- libraries/AP_HAL_F4Light/0_Done.md
- libraries/AP_HAL_F4Light/Scheduler.cpp
- libraries/AP_HAL_F4Light/Scheduler.h
- libraries/AP_HAL_F4Light/boards/f4light_Airbot/system_stm32f4xx.c
- libraries/AP_HAL_F4Light/boards/f4light_AirbotV2/system_stm32f4xx.c
- libraries/AP_HAL_F4Light/boards/f4light_MatekF405_CTR/system_stm32f4xx.c
- libraries/AP_HAL_F4Light/boards/f4light_MiniF4_OSD/system_stm32f4xx.c
- libraries/AP_HAL_F4Light/boards/f4light_Revolution/system_stm32f4xx.c
- libraries/AP_HAL_F4Light/boards/f4light_Revolution_EE128/system_stm32f4xx.c
- libraries/AP_HAL_F4Light/boards/f4light_Revolution_SD/system_stm32f4xx.c
- libraries/AP_HAL_F4Light/boards/f4light_cl_racing/system_stm32f4xx.c
- libraries/AP_HAL_F4Light/hardware/hal/syscalls.c
- libraries/AP_HAL_F4Light/hardware/hal/systick.c
- libraries/AP_HAL_F4Light/hardware/hal/systick.h
- libraries/AP_HAL_F4Light/system.cpp
- libraries/AP_HAL_F4Light/wirish/cxxabi-compat.cpp
- libraries/AP_HAL_F4Light/wirish/exc.S
kill task in case of exception in armed state (not in main task) instead of dead loop, or reboot a FC. Inspired by [this report](https://www.rcgroups.com/forums/showpost.php?p=39488195&postcount=2515)
> HAL_F4Light: new exception handling

- libraries/AP_HAL_ChibiOS/SoftSigReader.cpp
- libraries/AP_HAL_ChibiOS/SoftSigReaderInt.cpp
- libraries/AP_HAL_ChibiOS/hwdef/common/chibios_board.mk
- libraries/AP_HAL_ChibiOS/hwdef/common/stm32_util.c
- libraries/AP_HAL_ChibiOS/hwdef/common/stm32_util.h
Added input filtering for RCInput timer.
> HAL_ChibiOS: added input capture filter

- libraries/AP_Motors/AP_Motors6DOF.cpp
- libraries/AP_Motors/AP_Motors6DOF.h
- libraries/AP_Motors/AP_MotorsMulticopter.h
> AP_Motors: Add current limiting to 6DOF motors for Sub

- libraries/AP_HAL_ChibiOS/UARTDriver.cpp
thanks to @alielectric for noticing
> HAL_ChibiOS: removed stray debug code

- APMrover2/Parameters.cpp
- APMrover2/afs_rover.cpp
- APMrover2/afs_rover.h
- APMrover2/failsafe.cpp
- ArduCopter/Parameters.cpp
- ArduCopter/afs_copter.cpp
- ArduCopter/afs_copter.h
- ArduPlane/Plane.h
- ArduPlane/afs_plane.cpp
- libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.h
Nothing in AdvancedFailsafe is using RCMap
> Remove rcmap member from AdvancedFailsafe

- libraries/AP_Compass/AP_Compass_MAG3110.cpp
- libraries/AP_HAL_F4Light/boards/f4light_Airbot/board.h
- libraries/AP_HAL_F4Light/boards/f4light_AirbotV2/board.h
- libraries/AP_HAL_F4Light/boards/f4light_MatekF405_CTR/board.h
- libraries/AP_HAL_F4Light/boards/f4light_MatekF405_CTR/support/UPLOAD-STLINK.sh
- libraries/AP_HAL_F4Light/boards/f4light_Revolution/board.h
- libraries/AP_HAL_F4Light/boards/f4light_Revolution_EE128/board.h
- libraries/AP_HAL_F4Light/boards/f4light_Revolution_SD/board.h
- libraries/AP_HAL_F4Light/boards/f4light_cl_racing/board.h
- libraries/AP_HAL_F4Light/support/MMM.sh
also fixes https://github.com/ArduPilot/ardupilot/issues/8300 and https://github.com/ArduPilot/ardupilot/issues/8238
> HAL_F4Light: latest changes

- ArduSub/ArduSub.cpp
- ArduSub/control_althold.cpp
- ArduSub/control_surface.cpp
> Sub: Move SITL barometer check to Sub::control_check_barometer

- Tools/scripts/build_docs.sh
- docs/build-ardusub.sh
- docs/config/ardusub
> Tools: Update build_docs script

- APMrover2/AP_MotorsUGV.cpp
- APMrover2/AP_MotorsUGV.h
- Added is_omni_rover function
- Pre_arm_check method checks for 1 or 2 assigned functions
> Rover: added is_omni_rover function

- APMrover2/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.cpp
- ArduSub/GCS_Mavlink.cpp
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
Reduces code duplication, standardises form of send function.
> Move sending of battery messages up to GCS_MAVLink

- Tools/scripts/build_binaries.py
these just confuse users of ChibiOS
> Tools: don't publish elf files in build_binaries.py

- libraries/AP_Baro/AP_Baro.h
- libraries/AP_Baro/AP_Baro_HIL.cpp
- libraries/AP_Baro/AP_Baro_SITL.cpp
HIL - Add model for underwater 
SITL - Add BARO_TYPE_WATER functionality
> AP_Baro: Improve HIL and SITL 

- Tools/GIT_Test/GIT_Success.txt
> Tools: Add name to GIT_Success.txt

- libraries/AP_Baro/AP_Baro_HIL.cpp
- libraries/AP_Baro/AP_Baro_SITL.cpp
- libraries/AP_Baro/AP_Baro_UAVCAN.cpp
> AP_Baro: Use C_TO_KELVIN

- libraries/AP_BattMonitor/AP_BattMonitor_Analog.h
AP_BattMonitor: fix pin order for PocketPilot
> AP_BattMonitor: fix pin order for PocketPilot

- libraries/AP_HAL_ChibiOS/RCOutput.cpp
- libraries/AP_HAL_ChibiOS/RCOutput.h
- libraries/AP_HAL_PX4/RCOutput.cpp
This fixes some edge cases for OneShot125 on both HAL_PX4 and HAL_ChibiOS
> Oneshot125 fixes

- Tools/autotest/win_sitl/InstallDevEnvironment.ps1
- Tools/autotest/win_sitl/InstallDevEnvironmentAndAPMSource.ps1
Added a few extra packages to support building ChibiOS targets in Cygwin
> Tools - added extra packages for Cygwin environment setup scripts

- Tools/geotag/geotag.sh
It can do all, tag by time, with offset, by CAM messages, detect and
help correct problems, and process multiple logs(flights) at once.
Initial commit. I've used this tool for years.
> geotag.sh - an advanced geotagging tool.

- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
- libraries/SITL/SIM_Vicon.cpp
- libraries/SITL/SIM_Vicon.h
This adds a link lag measurement estimate for correcting for clock offset and transport lag for vision messages
> MAVLink: added link latency correction function

- Tools/autotest/arducopter.py
- Tools/autotest/common.py
I've rebased https://github.com/ArduPilot/ardupilot/pull/6028 onto master and updated it.
At the moment we can only expect octa to survive.  Hexa isn't powerful enough.
@GuilhermeGSousa This OK with you?
> Motor dead test

- libraries/AP_UAVCAN/AP_UAVCAN.cpp
this is to address https://github.com/ArduPilot/ardupilot/issues/8166
> AP_UAVCAN: change default ESC and servo bitmasks to 0

- APMrover2/GCS_Mavlink.cpp
- AntennaTracker/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.cpp
- ArduSub/GCS_Mavlink.cpp
- ArduSub/GCS_Mavlink.h
- ArduSub/Sub.h
- libraries/AP_Compass/AP_Compass.cpp
- libraries/AP_Compass/AP_Compass.h
- libraries/AP_TemperatureSensor/TSYS01.cpp
- libraries/AP_TemperatureSensor/TSYS01.h
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
Reduces code duplication, and a possible duplicate-message problem for sub,
> Move try_send_message handling of RAW_IMU messages up

- Tools/autotest/pysim/util.py
- Tools/scripts/install-prereqs-ubuntu.sh
- Vagrantfile
Also correct install-repreqs-ubuntu
> Make valgrind work on Vagrant virtual machines again

- ArduCopter/toy_mode.cpp
- Tools/CPUInfo/CPUInfo.cpp
- Tools/ardupilotwaf/boards.py
- libraries/AP_Baro/examples/ICM20789/ICM20789.cpp
- libraries/AP_BoardConfig/AP_BoardConfig.cpp
- libraries/AP_BoardConfig/AP_BoardConfig.h
- libraries/AP_HAL/AP_HAL_Boards.h
- libraries/AP_HAL/board/px4.h
- libraries/AP_HAL_ChibiOS/RCInput.cpp
- libraries/AP_HAL_ChibiOS/RCInput.h
- libraries/AP_HAL_PX4/RCInput.cpp
- libraries/AP_HAL_PX4/RCInput.h
- libraries/AP_Radio/AP_Radio.cpp
- libraries/AP_Radio/AP_Radio_cc2500.cpp
- libraries/AP_Radio/AP_Radio_cypress.cpp
- libraries/GCS_MAVLink/GCS_Common.cpp
These warnings are very annoying when looking at Travis output.
> Build warnings Travis

- ArduCopter/GCS_Mavlink.cpp
- ArduSub/GCS_Mavlink.cpp
- ArduSub/Sub.h
- libraries/GCS_MAVLink/GCS.h
Only sub used this - and it sent a fence status message...
> Relace uses of MSG_LIMITS_STATUS  with MSG_FENCE_STATUS

- Tools/autotest/sim_vehicle.py
Before it split up the string by spaces which didn't handle passing a string to "--cmd" or
using an "=" sign after the switch.
Now the string passed with the "-m" switch is split on spaces and "=" signs,
which is revaluated to reconstruct the split components which should be a single string by
looking for "\"" character pairs (denoting that that string should not be split), those
list items that are split up are joined back together as one list item to be passed on.
This has been tested with the call:
```
sim_vehicle.py -m "--state-basedir /dir/dir/dir/ --cmd=\"param load $v2param; module load map\" --master=/dev/ttyUSB0 --console --map --out=udp:192.168.1.1:14550"
```
This would be nicer if regex could handle this but I could not construct a good regex pattern to not pick up the spaces …
> Changed how the options that were passed to mavproxy via the "-m" switch are parsed.

- libraries/DataFlash/DataFlash.cpp
- libraries/DataFlash/LogFile.cpp
> Shorten labels in NKT1 and NKT2 messages

- APMrover2/Parameters.cpp
- APMrover2/control_modes.cpp
- APMrover2/defines.h
This PR fixes the issue posted [here](https://github.com/ArduPilot/ardupilot/issues/8476).
> Rover: add LOITER to ch7 options

- Tools/autotest/param_metadata/param.py
- libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp
Based on feedback from @DonLakeFlyer implementing the battery setup GUI.
> Update battery param docs for better UX

- libraries/AP_HAL_SITL/HAL_SITL_Class.cpp
- libraries/AP_HAL_SITL/Scheduler.cpp
- libraries/AP_HAL_SITL/Scheduler.h
- libraries/AP_HAL_SITL/UARTDriver.cpp
Implement reboot for SITL ! 
Fix socket relaunch by using SOCK_CLOEXEC option.
> Sitl reboot

- ArduCopter/system.cpp
- ArduSub/system.cpp
- libraries/AP_Common/Location.cpp
- libraries/AP_Common/Location.h
Also use the AHRS singleton.  This removes the requirement to have an AP_AHRS_NavEKF.
> Check home is set before allowing its use in Location.cpp

- libraries/AP_NavEKF2/AP_NavEKF2_VehicleStatus.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_VehicleStatus.cpp
https://github.com/ArduPilot/MissionPlanner/issues/1556
I saw this message on the AC 3.5.5 release version.
Clarify this message.
> AP_NavEKF2/3: Change GPS Speed error Message

- APMrover2/Rover.h
- APMrover2/control_modes.cpp
> Rover: factor out a do_aux_function_change_mode

- APMrover2/APMrover2.cpp
- APMrover2/AP_MotorsUGV.cpp
- APMrover2/AP_MotorsUGV.h
- APMrover2/Rover.h
- APMrover2/control_modes.cpp
- APMrover2/radio.cpp
This will help when we come to subclass the Motors library.
> Rover: move motors_active to be motors.active

- ArduCopter/mode_auto.cpp
Fixed for #8491 
The buzzer beeps always when the vehicle first reaches the waypoint.
> Copter: beeping when first reaching waypoint even while in holding there

- libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Improved parsing of timer channels.
Also this fixes build of the targets with complementary pwm channels. For other targets hwdef.h is not changed , so no regression here.
> HAL_ChibiOS: added parse_timer to chibios_hwdef.dat

- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/make.inc
- ArduCopter/wscript
- ArduPlane/GCS_Mavlink.cpp
- ArduPlane/make.inc
- ArduPlane/wscript
- ArduSub/GCS_Mavlink.cpp
- ArduSub/make.inc
- ArduSub/wscript
- Tools/ardupilotwaf/ardupilotwaf.py
- libraries/AP_Gripper/AP_Gripper.cpp
- libraries/AP_Gripper/AP_Gripper.h
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
- mk/make.inc
> Move handling of MAV_CMD_DO_GRIPPER up

- .gitignore
- ArduPlane/Log.cpp
> Plane: Log navigation target location

- ArduSub/Attitude.cpp
- ArduSub/GCS_Mavlink.cpp
- ArduSub/Parameters.cpp
- ArduSub/Sub.h
- ArduSub/commands_logic.cpp
- ArduSub/control_althold.cpp
- ArduSub/control_guided.cpp
- ArduSub/failsafe.cpp
- Update some ArduSub code style to match rest of the project (millis, micros)
- Allow arbitrary attitude control from SET_ATTITUDE_TARGET without a gps system
> Sub: Allow attitude control via mavlink in althold

- libraries/DataFlash/LogStructure.h
Power was being scaled by 1e-2 for some reason. Fixes #8617
> DataFlash: Fix power units

- Tools/GIT_Test/GIT_Success.txt
> Tools: Add my name

- libraries/GCS_MAVLink/GCS_Common.cpp
This is NFC.  The early-return here is confusing, and there were
redundant checks going on.
> GCS_MAVLink: tidy waypoint receiving part of update

- libraries/AP_BLHeli/AP_BLHeli.cpp
- libraries/AP_BLHeli/AP_BLHeli.h
- libraries/AP_BattMonitor/AP_BattMonitor.cpp
- libraries/AP_BattMonitor/AP_BattMonitor_BLHeliESC.cpp
- libraries/AP_BattMonitor/AP_BattMonitor_BLHeliESC.h
- libraries/AP_BattMonitor/AP_BattMonitor_Params.h
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
- libraries/SITL/SIM_Vicon.cpp
and adds ESC_TELEMETRY mavlink messages
> AP_BattMonitor: support ESC telemetry for virtual battery

- libraries/AP_HAL/utility/srxl.cpp
Issues: #8640
I correct this issues and then open a pull request.
> AP_HAL: Remove resource leak in srxl.cpp

- APMrover2/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.cpp
- ArduSub/GCS_Mavlink.cpp
- libraries/GCS_MAVLink/GCS_Common.cpp
This was lost in the rebase of the previous PR
ping @priseborough and @Naterater
> Added ESC_TELEMETRY to mavlink streams

- Tools/GIT_Test/GIT_Success.txt
Adding Tom Pittenger to Git SUccess
> Tools: Git Success - Tom Pittenger

- Tools/ardupilotwaf/ardupilotwaf.py
don't need to build all libraries
ping @bugobliterator
> waf: speed up the bootloader build

- libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
- libraries/AP_Baro/AP_Baro_SITL.cpp
- libraries/AP_Beacon/AP_Beacon_SITL.cpp
- libraries/AP_Compass/AP_Compass_SITL.cpp
- libraries/AP_HAL_SITL/SITL_State.cpp
- libraries/AP_InertialSensor/AP_InertialSensor_SITL.cpp
- libraries/AP_OpticalFlow/AP_OpticalFlow_SITL.cpp
- libraries/AP_Proximity/AP_Proximity_SITL.cpp
- libraries/AP_RPM/RPM_SITL.cpp
- libraries/SITL/SIM_ADSB.cpp
- libraries/SITL/SIM_Aircraft.cpp
- libraries/SITL/SIM_Vicon.cpp
This solve some warning messages when using last clang version
> Libraries: Use reinterpret_cast and singletons

- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/mode.h
- ArduCopter/mode_guided.cpp
- libraries/AC_WPNav/AC_WPNav.cpp
- libraries/AC_WPNav/AC_WPNav.h
It expose horizontal error of the actual position vs the desired position when navigating between waypoints and send it in nav_controller message
> Add wp crosstrack report for copter

- libraries/AP_IRLock/AP_IRLock_SITL.cpp
- libraries/AP_RangeFinder/AP_RangeFinder_Benewake.cpp
- libraries/SITL/SIM_Aircraft.cpp
- Remove extraneous parentheses in AP_RangeFinder
- Use SITL singleton in SIM_Aircraft
> Libraries: Random corrections

- ArduSub/AP_Arming_Sub.h
- ArduSub/Attitude.cpp
- ArduSub/commands.cpp
- ArduSub/control_althold.cpp
- ArduSub/flight_mode.cpp
- ArduSub/system.cpp
- Update functions declarations with definition
- Simplify return
> Sub: Small updates

- ArduCopter/mode_autotune.cpp
> Copter: autotune: raise priorities of autotune success and param saved

- Tools/ardupilotwaf/boards.py
- Tools/ardupilotwaf/chibios.py
- Tools/ardupilotwaf/cxx_checks.py
- Tools/ardupilotwaf/embed.py
- Tools/autotest/sim_vehicle.py
- libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
- libraries/AP_OSD/AP_OSD_SITL.h
- wscript
and move to generic ROMFS embedding code
> SITL: improved SFML library checks

- ArduCopter/ReleaseNotes.txt
> Small correction

- ArduSub/ArduSub.cpp
- ArduSub/GCS_Mavlink.cpp
- ArduSub/Log.cpp
- ArduSub/Parameters.cpp
- ArduSub/Sub.cpp
- ArduSub/capabilities.cpp
- ArduSub/control_auto.cpp
- ArduSub/failsafe.cpp
- ArduSub/sensors.cpp
- Remove unnecessary void as parameter in C++ code
> Sub: Remove void as parameter

- ArduCopter/motor_test.cpp
- ArduPlane/motor_test.cpp
- ArduSub/GCS_Mavlink.cpp
- ArduSub/Sub.h
- ArduSub/motors.cpp
- libraries/AP_Motors/AP_MotorsCoax.cpp
- libraries/AP_Motors/AP_MotorsCoax.h
- libraries/AP_Motors/AP_MotorsHeli.h
- libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
- libraries/AP_Motors/AP_MotorsHeli_Dual.h
- libraries/AP_Motors/AP_MotorsHeli_Quad.cpp
- libraries/AP_Motors/AP_MotorsHeli_Quad.h
- libraries/AP_Motors/AP_MotorsHeli_Single.cpp
- libraries/AP_Motors/AP_MotorsHeli_Single.h
- libraries/AP_Motors/AP_MotorsMatrix.cpp
- libraries/AP_Motors/AP_MotorsMatrix.h
- libraries/AP_Motors/AP_MotorsSingle.cpp
- libraries/AP_Motors/AP_MotorsSingle.h
- libraries/AP_Motors/AP_MotorsTailsitter.h
- libraries/AP_Motors/AP_MotorsTri.cpp
- libraries/AP_Motors/AP_MotorsTri.h
- libraries/AP_Motors/AP_Motors_Class.h
- libraries/AP_Motors/examples/AP_Motors_test/AP_Motors_test.cpp
Something that has been sorely missed since conception.
> Add motor test for Sub

- libraries/AP_OSD/AP_OSD.h
- libraries/AP_OSD/AP_OSD_Screen.cpp
- libraries/GCS_MAVLink/GCS.h
adds throttle in percent and course over ground in degrees.
> AP_OSD: add throttle and ground course item

- Tools/autotest/autotest.py
Also fixed a bug where CalledProcessError has not been imported
> Tools: autotest.py: flake8 compliance

- libraries/AP_OSD/AP_OSD.h
- libraries/AP_OSD/AP_OSD_Screen.cpp
- libraries/AP_OSD/fonts/mcm2bin.py
New osd items:
- added direction to the groundspeed
- compass item
- wind speed/direction item
- airspeed item
- climbrate item
WIP because this PR require testing and checking
> AP_OSD: new osd items

- libraries/AP_OSD/AP_OSD_SITL.cpp
- libraries/AP_OSD/AP_OSD_SITL.h
this allows for window scaling and should fix ubuntu 18 warning
> AP_OSD: use a thread for SITL OSD

- libraries/AP_OSD/AP_OSD.cpp
- libraries/AP_OSD/AP_OSD_Backend.cpp
- libraries/AP_OSD/AP_OSD_SITL.h
- libraries/AP_OSD/AP_OSD_Screen.cpp
Packed dot should be much better now.
> AP_OSD: fixed packed dot

- libraries/AP_BattMonitor/AP_BattMonitor_BLHeliESC.cpp
- libraries/AP_OSD/AP_OSD_Screen.cpp
This should fix the issue noticed by @Naterater and @priseborough
> BLHeli: fixed ESC current scaling 

- Tools/autotest/common.py
> Tools: autotest: fix race condition on parameter values

- libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
thanks to @liang-tang for noticing
> HAL_ChibiOS: fixed duplicate pin definitions

- libraries/AP_HAL_PX4/Util.cpp
> HAL_PX4: fixed link on aerofc-v1

- libraries/AP_SerialManager/AP_SerialManager.cpp
> AP_SerialManager: fixed find_baudrate to return mapped baudrate

- libraries/AP_HAL_Linux/Scheduler.cpp
- libraries/AP_HAL_Linux/Scheduler.h
- libraries/AP_HAL_Linux/Thread.cpp
- libraries/AP_HAL_Linux/Thread.h
> Linux threads

- Tools/scripts/install-prereqs-mac.sh
Update tap to ardupilot and updated the pre-reqs
> Tools: Update tap and update pre-reqs

- libraries/AP_HAL_ChibiOS/Device.cpp
- libraries/AP_HAL_ChibiOS/hwdef/common/bouncebuffer.c
- libraries/AP_HAL_ChibiOS/hwdef/common/bouncebuffer.h
- libraries/AP_HAL_ChibiOS/sdcard.cpp
thanks to @jschall for finding this!
> ChibiOS: enable bounce buffers on SDIOv1

- Tools/autotest/arducopter.py
- Tools/autotest/common.py
- Tools/autotest/param_metadata/param_parse.py
remove some trailling semilocons, make some methods static
fix none initialised variable
> Tools: fix some syntax

- libraries/AP_OSD/AP_OSD.cpp
- libraries/AP_OSD/AP_OSD.h
- libraries/AP_OSD/AP_OSD_Screen.cpp
adds parameter OSDn_MSG_TIME to set message item's show duration in seconds
> Osd message showtime

- libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
- libraries/AP_NavEKF/AP_Nav_Common.h
- libraries/AP_NavEKF2/AP_NavEKF2_Control.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
This allows flying a plane with no compass, if GPS quality is good
ping @vierfuffzig
> Plane: fixed flight with no compass

- libraries/AP_HAL/Util.h
- libraries/AP_HAL_ChibiOS/ToneAlarm.cpp
- libraries/AP_HAL_ChibiOS/ToneAlarm.h
- libraries/AP_HAL_ChibiOS/Util.cpp
- libraries/AP_HAL_ChibiOS/Util.h
- libraries/AP_Notify/ToneAlarm_ChibiOS.cpp
- libraries/AP_Notify/ToneAlarm_ChibiOS.h
> ChibiOS: support playing tunes by string

- libraries/AP_HAL_ChibiOS/I2CDevice.cpp
if we are sharing a DMA channel between i2c and SPI then this saves
latency on SPI by giving up the DMA channel between retries
> HAL_ChibiOS: reduce latency of DMA sharing

- libraries/AP_HAL_Linux/RCInput.cpp
- libraries/AP_HAL_Linux/RCInput.h
- libraries/AP_HAL_Linux/RCInput_RPI.cpp
- libraries/AP_HAL_Linux/RCInput_RPI.h
Continuing https://github.com/ArduPilot/ardupilot/pull/6755 - I have no idea what github did, but that PR is closed and doesn't allow me to reopen it.
@onceme let's continue here.
> AP_HAL_Linux: support PWM input for BH hat

- libraries/AP_OSD/AP_OSD.h
- libraries/AP_OSD/AP_OSD_Screen.cpp
> Osd add temperature item

- Tools/ardupilotwaf/px_uploader.py
adding support for cygwin installations for waf uploader
> adding support for win/cygwin installations

- libraries/AP_HAL_ChibiOS/hwdef/common/bouncebuffer.c
Seems fix sdcard problems on KakuteF7
Thank to @utkinpol, who helped trace and check this.
> HAL_ChibiOS: fix DTCM size in stm32f745 mcu

- ArduCopter/Copter.h
- ArduCopter/mode.cpp
- ArduCopter/mode.h
- ArduCopter/mode_auto.cpp
- ArduCopter/mode_guided.cpp
- ArduCopter/takeoff.cpp
Saves a couple of hundred bytes.
> Copter: Factor out common method for guided and auto takeoff

- APMrover2/crash_check.cpp
I fix the indent from 2 to 4 in the coding style.
> Rover: Modify indentation (NFC)

- Tools/autotest/pysim/util.py
OTOH, screen will be required....
> Tools: autotest: allow use of --gdb when no DISPLAY available

- libraries/AP_Notify/Buzzer.cpp
- libraries/AP_Notify/ToneAlarm.cpp
this makes for easier quiet development sessions
> AP_Notify: use NTF_BUZZ_ENABLE to disable tonealarm

- ArduCopter/mode_auto.cpp
- ArduCopter/mode_guided.cpp
- Tools/autotest/arducopter.py
- Tools/autotest/common.py
> Exit takeoff

- ArduCopter/mode_autotune.cpp
- Tools/autotest/arducopter.py
- Tools/autotest/common.py
Also, factor some repeated maths in the AutoTune mode.
> Add autotest for Copter autotune

- libraries/AP_HAL_SITL/SITL_State.cpp
- libraries/AP_HAL_SITL/SITL_State.h
- libraries/SITL/SIM_Aircraft.cpp
- libraries/SITL/SIM_Aircraft.h
- libraries/SITL/SIM_Calibration.cpp
- libraries/SITL/SIM_Calibration.h
- libraries/SITL/SIM_Frame.cpp
- libraries/SITL/SIM_Frame.h
- libraries/SITL/SIM_Gripper_EPM.cpp
- libraries/SITL/SIM_Gripper_EPM.h
- libraries/SITL/SIM_Gripper_Servo.cpp
- libraries/SITL/SIM_Gripper_Servo.h
- libraries/SITL/SIM_ICEngine.cpp
- libraries/SITL/SIM_ICEngine.h
- libraries/SITL/SIM_Motor.cpp
- libraries/SITL/SIM_Motor.h
- libraries/SITL/SIM_Multicopter.cpp
- libraries/SITL/SIM_Multicopter.h
- libraries/SITL/SIM_Sprayer.cpp
- libraries/SITL/SIM_Sprayer.h
- libraries/SITL/SITL.cpp
- libraries/SITL/SITL.h
- libraries/SITL/SITL_Input.h
> REarrange grippers and sprayers in SITL

- libraries/AP_HAL_ChibiOS/I2CDevice.cpp
- libraries/AP_HAL_ChibiOS/I2CDevice.h
many thanks to Kelly-Foster for chasing me on this one!
> HAL_ChibiOS: fixed an i2c dma callback bug

- Tools/autotest/apmrover2.py
- libraries/RC_Channel/RC_Channel.h
- libraries/RC_Channel/RC_Channels.cpp
- libraries/SRV_Channel/SRV_Channel_aux.cpp
.... and add a simple test for the same.
I broke these with a bad rebase just before the move-channel-option-up stuff was merged.
> Fix RC overrides

- libraries/RC_Channel/RC_Channels.cpp
> RC_Channels: zero all channels before populating

- libraries/AP_HAL_ChibiOS/hwdef/common/hrt.c
- libraries/AP_HAL_ChibiOS/hwdef/common/hrt.h
- libraries/AP_HAL_ChibiOS/hwdef/common/stm32_util.c
- libraries/AP_HAL_ChibiOS/system.cpp
this saves a few cycles
@bugobliterator, please take a look
> HAL_ChibiOS: avoid 64 bit maths in AP_HAL::micros()

- libraries/RC_Channel/RC_Channel.cpp
> RC_Channel: Fix possible user induced out of bounds write

- libraries/AP_RSSI/AP_RSSI.cpp
this will fix RSSI on a couple of boards
> AP_RSSI: allow override of RSSI pin

- Tools/autotest/autotest.py
- Tools/autotest/pysim/util.py
> Tools: autotest: add steps to autotest to build and run unit tests

- Tools/autotest/apmrover2.py
- Tools/autotest/arducopter.py
- Tools/autotest/arduplane.py
- Tools/autotest/ardusub.py
- Tools/autotest/common.py
- Tools/autotest/quadplane.py
Test arm/disarm with mavlink
Test arm/disarm with radio
Test auto disarm
> Tools: add arm and disarm tests

- ArduCopter/ArduCopter.cpp
- ArduCopter/Copter.h
- ArduPlane/ArduPlane.cpp
- ArduPlane/Plane.h
- libraries/AP_OSD/AP_OSD.cpp
- libraries/AP_OSD/AP_OSD.h
- libraries/AP_OSD/AP_OSD_Screen.cpp
This add waypoint and xtrack error items to osd
> AP_OSD: add waypoint item

- libraries/AP_HAL/AP_HAL_Macros.h
- libraries/AP_OSD/AP_OSD.cpp
- libraries/AP_OSD/AP_OSD.h
- libraries/AP_OSD/AP_OSD_Screen.cpp
- libraries/AP_Stats/AP_Stats.cpp
- libraries/AP_Stats/AP_Stats.h
This is cleaned up version of https://github.com/ArduPilot/ardupilot/pull/8928
> AP_OSD: add flytime item

- Tools/autotest/apmrover2.py
> Tools: autotest: increase timeout for RTL test

- ArduCopter/Copter.h
- ArduCopter/mode_auto.cpp
- libraries/AC_PrecLand/AC_PrecLand.cpp
- libraries/AC_PrecLand/AC_PrecLand.h
- libraries/AC_PrecLand/AC_PrecLand_Companion.cpp
- libraries/AC_PrecLand/AC_PrecLand_Companion.h
- libraries/AC_PrecLand/AC_PrecLand_IRLock.cpp
- libraries/AC_PrecLand/AC_PrecLand_SITL.cpp
- libraries/AC_PrecLand/AC_PrecLand_SITL.h
- libraries/AP_Winch/AP_Winch.cpp
taken from https://github.com/ArduPilot/ardupilot/pull/8932
> Various little correction for precland and place

- Tools/scripts/install-prereqs-mac.sh
> scripts: Add mavproxy in pip install

- Tools/autotest/sim_vehicle.py
> Tools: sim_vehicle.py: Print a more readable exception

- libraries/AP_HAL_SITL/Scheduler.cpp
- libraries/AP_HAL_SITL/Scheduler.h
- libraries/AP_OSD/AP_OSD.cpp
Useful for checking stack sizes
> SITL: added stack checking on threads 

- libraries/AP_Notify/RGBLed.cpp
- libraries/AP_Notify/RGBLed.h
Saves 60 bytes, too
... and about 40 lines of code.
> AP_Notify: tidy and remove code duplications

- Tools/autotest/common.py
it should cope with _ENABLE parameter more easily
> Tools: allow to retry to get parameters before timeout

- APMrover2/mode_guided.cpp
tested on SITL
fix https://github.com/ArduPilot/ardupilot/issues/7564
> Rover: fix initial target when setting Guided

- Tools/autotest/arducopter.py
Prevent to behind stuck if we forget to arm before....
> Tools: make takeoff check if it need arming and auto arm

- libraries/AP_AHRS/AP_AHRS.h
- libraries/AP_AHRS/AP_AHRS_DCM.cpp
- libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
- libraries/AP_Avoidance/AP_Avoidance.cpp
- libraries/AP_Avoidance/AP_Avoidance.h
- libraries/AP_Common/Semaphore.h
- libraries/AP_HAL/board/chibios.h
- libraries/AP_HAL/board/linux.h
- libraries/AP_HAL/board/px4.h
- libraries/AP_HAL/board/sitl.h
- libraries/AP_HAL_ChibiOS/AP_HAL_ChibiOS_Namespace.h
- libraries/AP_HAL_ChibiOS/Semaphores.cpp
- libraries/AP_HAL_ChibiOS/Semaphores.h
- libraries/AP_HAL_Linux/Semaphores.cpp
- libraries/AP_HAL_Linux/Semaphores.h
- libraries/AP_HAL_PX4/AP_HAL_PX4_Namespace.h
- libraries/AP_HAL_PX4/Semaphores.cpp
- libraries/AP_HAL_PX4/Semaphores.h
- libraries/AP_HAL_SITL/AP_HAL_SITL_Namespace.h
- libraries/AP_HAL_SITL/Semaphores.cpp
- libraries/AP_HAL_SITL/Semaphores.h
- libraries/AP_Mission/AP_Mission.cpp
- libraries/AP_Mission/AP_Mission.h
This makes it much easier to add semaphores to existing library interfaces
ping @WickedShell
> HAL: added recursive semaphores

- ArduSub/failsafe.cpp
> Sub: failsafe: subtract times, don't add them

- libraries/AP_HAL_ChibiOS/hwdef/common/hrt.c
when we have a 16 bit timer then systime_t is 16 bit, and we need to
handle wrap of get_systime_us32()
thanks to @s0up for finding this bug!
> HAL_ChibiOS: fixed handling of 16 bit timers

- Tools/autotest/arducopter.py
Fixes undefined names on lines 1406 and 1408
> Tools: from common import PreconditionFailedException

- libraries/AP_Arming/AP_Arming.cpp
Also use check_failed throughout
This masks something wrong with our send-statustext function for over-long strings.
> AP_Arming: remove double PreArm: in battery prearm report

- Tools/autotest/arducopter.py
- Tools/autotest/common.py
- libraries/AP_Gripper/AP_Gripper_EPM.cpp
- libraries/AP_Gripper/AP_Gripper_Servo.cpp
- libraries/AP_Gripper/AP_Gripper_Servo.h
- libraries/GCS_MAVLink/GCS_Common.cpp
- libraries/SITL/SIM_Gripper_Servo.cpp
- libraries/SITL/SIM_Gripper_Servo.h
make gripper sim more realistic.
add some parameter to reflect real material and chose at which pwm it open and which it close
> Autotest gripper

- libraries/AP_GPS/GPS_Backend.cpp
- libraries/AP_HAL_SITL/SITL_State.cpp
- libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
- Remove unused operations, variables and update some logics
> Libraries: Remove unused code

- ArduCopter/mode_loiter.cpp
This PR will fix an issue users may experience while spooling down.  Currently the code does not initialize the Nav controllers while the aircraft is spooling down spooling down or sitting on the ground with rotors static (armed or disarmed).  This can cause the aircraft to roll over because as the rotor is spooling down it still has sufficient control power to apply inputs from the Nav controller.  this is only being pushed to Copter-3.6 because the spool logic PR for tradheli is scheduled to go into 3.7 which remedies this situation.  It is a simple change.  Here is a plot of position controller velocity command and actual velocity.   a longitudinal velocity command from the transmitter was made to show when the controller was still allowed to make inputs the aircraft.  the first lift …
> Copter: Tradheli - fix issue with position moving while on ground

- ArduPlane/radio.cpp
This came into master before #9221 was merged which had passed CI.
> Plane: Fix a stale rudder input that was left from rebase

- APMrover2/Parameters.cpp
- APMrover2/Parameters.h
- APMrover2/Rover.h
- APMrover2/config.h
- APMrover2/make.inc
- APMrover2/system.cpp
- APMrover2/wscript
Rover: Activation of OSD for boards which are able to display it
hopefully this PR is way better ...
> Rover: Activation of OSD

- APMrover2/GCS_Mavlink.cpp
- APMrover2/GCS_Mavlink.h
- AntennaTracker/GCS_Mavlink.cpp
- AntennaTracker/GCS_Mavlink.h
- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
- ArduPlane/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.h
- ArduSub/GCS_Mavlink.cpp
- ArduSub/GCS_Mavlink.h
- Tools/Replay/Replay.cpp
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
- libraries/GCS_MAVLink/GCS_Dummy.h
- libraries/GCS_MAVLink/examples/routing/routing.cpp
This is on top of the other PR which is just for the compass singleton.
> Use camera singleton in GCS base class

- libraries/AP_Airspeed/AP_Airspeed_SDP3X.cpp
issue  https://github.com/ArduPilot/ardupilot/issues/8220
> AP_Airspeed: fix spd3x correct pressure issue

- libraries/AP_Notify/Display.cpp
Thanks to Erwin Quilloy for helping to track this down
> AP_Notify: fixed oled probe on first bus

- Tools/autotest/arducopter.py
1500 is sufficient that we may not descend.
> Tools: autotest: correct descent throttle in copter fence test

- Tools/autotest/arducopter.py
- Tools/autotest/arduplane.py
- Tools/autotest/common.py
Also adds a big hammer solution to the rc timeout problem - allow for a very, very long time waiting for the RC to change.
> Tools: autotest: tweak output messages, loosen camera trigger timeout

- ArduPlane/Attitude.cpp
- libraries/AP_AHRS/AP_AHRS_DCM.cpp
when in a Q mode reduce surface movements at low airspeed, in case we
have the wind from behind us. This prevents the control surfaces from
causing instability
> Plane: added speed scaling reduction for Q modes

- ArduPlane/Log.cpp
- ArduPlane/quadplane.cpp
- ArduPlane/quadplane.h
- libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
- libraries/AC_PID/AC_PID.cpp
> Fix VTOL attitude twitch caused by poor initialisation

- ArduCopter/mode_land.cpp
- ArduCopter/mode_poshold.cpp
- ArduCopter/mode_rtl.cpp
- ArduCopter/mode_throw.cpp
> Copter: Initialize desired acceleration before loiter init

- libraries/AP_Airspeed/AP_Airspeed.cpp
This makes the status text messages behave more like the GPS library, where the index printed actually matches user expectations of what sensor is failing. (When users see "Airspeed[1] sensor unhealthy" they tend to check the first airspeed sensor not the second). Log analysis is helped because the index is no longer in brackets so we can differentiate how the indexing is done if it becomes an issue when doing review.
This also takes the sanity check from `PITOT_TUBE_ORDER_POSITIVE` and always runs it. The primary benefit for this is that it adds protection for anyone using `PITOT_TUBE_ORDER_NEGATIVE` which could have failed before.
> AP_Airspeed: Make user facing messages clearer, improve handling of bad tube order

- libraries/AP_HAL_ChibiOS/RCOutput.cpp
this fixes a problem found by Daniel Met with the copter 3.6 beta
release
> HAL_ChibiOS: fixed a race in DShot code

- libraries/AP_Baro/AP_Baro.cpp
I will delete the total temperature because it is not used.
> AP_Baro: Delete the total temperature process.

- libraries/AP_Baro/AP_Baro.cpp
Thanks to OlliW for pointing this out
> AP_Baro: emit calibrated messages for each connected baro

- libraries/AP_OSD/AP_OSD_Screen.cpp
AP_BLHeli td.current is amps * 100
> AP_OSD: fix BLHAMPS current scale

- libraries/AP_Compass/AP_Compass_AK8963.cpp
- libraries/AP_Compass/AP_Compass_AK8963.h
- libraries/AP_Compass/AP_Compass_SITL.cpp
- libraries/AP_Compass/AP_Compass_UAVCAN.cpp
- libraries/AP_Compass/AP_Compass_UAVCAN.h
bug in SITL, and old approach for AK8963 and UAVCAN
> Compass: fixed accumulate calls

- Tools/vagrant/initvagrant.sh
- Vagrantfile
Had to increase the memory allowed to the machine as it appeared to be
running out
> Vagrant: correct init script so profiles work; cosmic support

- libraries/AP_HAL_ChibiOS/hwdef/mRoX21-777/hwdef.dat
Set proper sensor orientation.
> mRo X2.1-777 / hwdef.dat

- Tools/autotest/common.py
These changes fix the autotest for ArduSub
There are three main changes:
- Don't wait for "tilt alignment complete" message, <s>as Subs are not calibrated after reboot by default</s>. It is not sent consistently with sitl and causing the tests to fail.
- Don't test arming/disarming with switches (it doesn't support switches)
- Don't test arming/disarming with RC inputs (it also doesn't support 'stick commands')
> Fix ArduSub autotest

- ArduCopter/mode_auto.cpp
> Copter: Obey and preserve DO_SET_ROI commands when executing LOITER_TURNS mission commands

- ArduSub/Sub.cpp
- ArduSub/Sub.h
Everything here's in a static object - zeroed at program startup.
> Sub: remove pointless zero-initialisation

- .travis.yml
- Tools/scripts/build_ci.sh
Add ArduSub test in travis and in build_ci
> Tools,Travis: Add ardusub test

- libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
This fixes an issue with ESP8366 on Pixracer
> HAL_ChibiOS: restore old ODR behaviour for F4 boards

- libraries/AP_BattMonitor/AP_BattMonitor.cpp
- libraries/AP_HAL/board/linux.h
this will allow boards with builtin monitoring to default correctly
> Battery: Added BATT_MONITOR_DEFAULT

- ArduPlane/Attitude.cpp
this is important for very fast or very slow aircraft
> Plane: ensure speed scaling covers full aircraft speed range

- libraries/AP_Mount/SoloGimbal.cpp
- libraries/AP_Mount/SoloGimbal.h
- libraries/AP_Mount/SoloGimbalEKF.cpp
- libraries/AP_Mount/SoloGimbalEKF.h
mysteriously also saves ~24 bytes
> AP_Mount: SoloGimbal: stop taking reference to AHRS

- ArduCopter/Copter.h
- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
Saves about 200 bytes on fmuv3
> Copter: tidy up send_pid_tuning

- ArduCopter/toy_mode.cpp
I think that the last line break of this telemetry message is unnecessary.
I deleted it according to other messages.
> Copter: Delete the last newline of the message.

- libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Maxell.cpp
Fixed SAFETY_STATUS register typo
> AP_BattMonitor: fixed SAFETY_STATUS register typo

- ArduPlane/GCS_Mavlink.cpp
- ArduPlane/defines.h
allow view of PIDs for accz in quadplanes
> Plane: added ACCZ pid tuning

- Tools/ardupilotwaf/mavgen.py
- libraries/AP_HAL/AP_HAL_Macros.h
avoid spawning a new copy of python for mavlink processing
> waf: direct import mavgen

- ArduPlane/is_flying.cpp
- libraries/AP_AHRS/AP_AHRS.cpp
- libraries/AP_AHRS/AP_AHRS_DCM.cpp
This fixes issue #9349 and also fixes dead-reckoning on GPS loss. Tested in SITL, but really needs testing in a real aircraft
> Plane: fixed dead-reckoning on GPS loss

- libraries/AP_Landing/AP_Landing.cpp
- libraries/AP_Landing/AP_Landing.h
- libraries/AP_Landing/AP_Landing_Slope.cpp
Superseded https://github.com/ArduPilot/ardupilot/pull/7898
Side wind 15 m/s
Without:
With:
Adresses: #7867
> AP_Landing: Touchdown yaw correction with altitude or weight on wheels

- APMrover2/APMrover2.cpp
- APMrover2/GCS_Mavlink.cpp
- APMrover2/Rover.h
- AntennaTracker/AntennaTracker.cpp
- AntennaTracker/GCS_Mavlink.cpp
- AntennaTracker/Tracker.h
- ArduCopter/ArduCopter.cpp
- ArduCopter/Copter.h
- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/RC_Channel.h
- ArduPlane/ArduPlane.cpp
- ArduPlane/GCS_Mavlink.cpp
- ArduPlane/Plane.h
- ArduSub/ArduSub.cpp
- ArduSub/GCS_Mavlink.cpp
- ArduSub/Sub.h
- libraries/AP_Vehicle/AP_Vehicle_Type.h
- libraries/RC_Channel/RC_Channel.h
> Eliminate wrappers

- ArduCopter/APM_Config.h
- ArduCopter/Copter.h
- ArduCopter/config.h
- ArduCopter/mode.cpp
- ArduCopter/mode_flip.cpp
I think flip mode is the same option flight mode as other modes.
> Copter: Flip mode is an option.

- Tools/autotest/common.py
... on the theory that we debounce these so it's a good idea to give the
RC library a good look at each value
> Tools: autotest: delay between transitioning aux switches

- libraries/SITL/SIM_FlightAxis.cpp
the new beta release supports up to 12 channels
> SITL: support up to 12 actuators with RealFlight8

- libraries/AP_HAL_ChibiOS/RCOutput.cpp
- libraries/AP_IOMCU/AP_IOMCU.cpp
- libraries/AP_IOMCU/AP_IOMCU.h
This adds support for brushed motors on the IO outputs.
It includes a new IO firmware which is not ready for master
DO NOT MERGE
> IOMCU: added brushed motor support on IO outputs

- Tools/GIT_Test/GIT_Success.txt
> Tools: added name to GIT_Success.txt

- libraries/AP_OSD/AP_OSD.h
- libraries/AP_OSD/AP_OSD_Screen.cpp
adds item for second airspeed sensor. thanks @Rolf-G for testing!
> OSD add display item for secondary airspeed instance

- ArduPlane/servos.cpp
thanks to Alex for noticing this issue
> Plane: apply throttle slew to dual-motor setups

- libraries/AP_GPS/AP_GPS.cpp
- libraries/AP_GPS/AP_GPS.h
- libraries/AP_GPS/AP_GPS_ERB.cpp
- libraries/AP_GPS/AP_GPS_NMEA.cpp
- libraries/AP_GPS/AP_GPS_NMEA.h
- libraries/AP_GPS/AP_GPS_NOVA.cpp
- libraries/AP_GPS/AP_GPS_SBF.cpp
- libraries/AP_GPS/AP_GPS_SBP.cpp
- libraries/AP_GPS/AP_GPS_SBP2.cpp
- libraries/AP_GPS/AP_GPS_UBLOX.cpp
- libraries/AP_GPS/AP_GPS_UBLOX.h
- libraries/AP_GPS/GPS_Backend.cpp
- libraries/AP_GPS/GPS_Backend.h
- libraries/AP_RTC/JitterCorrection.cpp
- libraries/AP_RTC/JitterCorrection.h
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
this builds on #8403 but for GPS timestamps
> Adjust GPS timestamps using UART latency estimate

- libraries/AP_Proximity/AP_Proximity.cpp
- libraries/AP_Proximity/AP_Proximity.h
- libraries/AP_Proximity/AP_Proximity_MorseSITL.cpp
- libraries/AP_Proximity/AP_Proximity_MorseSITL.h
- libraries/SITL/SIM_Aircraft.cpp
- libraries/SITL/SIM_Aircraft.h
- libraries/SITL/SIM_Morse.cpp
- libraries/SITL/SIM_Morse.h
- libraries/SITL/SITL.h
- libraries/SITL/examples/Morse/rover_scanner.parm
- libraries/SITL/examples/Morse/rover_scanner.py
This allows vehicles to use a Morse laser scanner as a proximity sensor
> SITL: added laser scanner for Morse

- Tools/ardupilotwaf/cxx_checks.py
- libraries/AP_HAL/utility/replace.cpp
- libraries/AP_HAL/utility/replace.h
- libraries/SITL/SIM_Morse.cpp
> SITL: fixed build on MacOS

- libraries/SITL/SIM_Morse.cpp
- libraries/SITL/SIM_Morse.h
- libraries/SITL/examples/Morse/rover_follow.py
This makes it easier to create arrays of vehicles
> SITL: improve swarm handling with morse

- libraries/AP_Follow/AP_Follow.cpp
- libraries/AP_Follow/AP_Follow.h
- libraries/SITL/examples/Morse/start_follow.sh
and add an example follow script for Morse rovers
> Follow: fixed handling of FOLL_SYSID

- Tools/autotest/web/index.html
Adding APO google analytics tags to autotest index files
> AUTOTEST: autotest statistics tags

- libraries/AP_HAL_ChibiOS/hwdef/PH4-mini/hwdef.dat
- libraries/AP_HAL_ChibiOS/hwdef/Pixhawk4/hwdef.dat
use defaults supplied by Holybro
> HAL_ChibiOS: setup PH4 for right voltage scaling

- APMrover2/Log.cpp
- APMrover2/Parameters.cpp
- APMrover2/RC_Channel.cpp
- APMrover2/Rover.h
- APMrover2/commands.cpp
- APMrover2/commands_logic.cpp
- APMrover2/mode.cpp
- APMrover2/mode.h
- APMrover2/system.cpp
This mirrors what we did for Copter
> Rover: move AP_Mission object into ModeAuto class

- APMrover2/GCS_Mavlink.cpp
- APMrover2/GCS_Mavlink.h
- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
- ArduPlane/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.h
- Tools/autotest/apmrover2.py
- Tools/autotest/common.py
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
- also refactor it into the base class
- also add a test for `SYSID_ENFORCE` generally, and components specifically.
Thanks to http://aeronavics.com/ for sponsoring this work.
> Fix SYSID_ENFORCE to accept from components

- libraries/AP_HAL/utility/Socket.cpp
- libraries/AP_HAL/utility/Socket.h
- libraries/AP_HAL_SITL/SITL_State.cpp
More debug for the failed-to-rebind-port issue in SITL, basically.
> Make setting socket and fd options boolean, check results in SITL

- APMrover2/GCS_Mavlink.cpp
- APMrover2/GCS_Mavlink.h
- AntennaTracker/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
- ArduPlane/GCS_Mavlink.cpp
- ArduSub/GCS_Mavlink.cpp
- ArduSub/GCS_Mavlink.h
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
... and rename extended_status1 to sys_status.
> Split sys status power status onto separate ap_message

- libraries/AP_HAL_SITL/SITL_State.cpp
fix the battery consumtion for rover
> AP_HAL_SITL: correct battery setup for rover

- libraries/AC_AutoTune/AC_AutoTune.cpp
- libraries/AC_AutoTune/AC_AutoTune.h
this allows you to stop the tune by disarming part way through and
save the completed axes
> AC_AutoTune: allow save of completed axes

- ArduPlane/quadplane.cpp
A very small fix to [this issue](https://github.com/ArduPilot/ardupilot/issues/10046) raised by @Naterater.
> Plane: fix quadplane pos control param docs

- libraries/AP_NavEKF2/AP_NavEKF2_core.cpp
- libraries/AP_NavEKF2/AP_NavEKF2_core.h
- libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_core.h
> EKF : pass by const ref when need

- APMrover2/mode.h
- APMrover2/mode_guided.cpp
Stop vehicle with loiter for boat in GUIDED mode.
Loiter function is from ModeLoiter::udpate().
I tested it with SITL for FRAME_CLASS 1 and 2, it worked.
But I doesn't comfirm the liter behavior actually. Is there a way to comfirm than with SITL?
> Rover: fix guided mode for boat

- libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
- libraries/AC_AttitudeControl/AC_AttitudeControl.h
- libraries/AP_AHRS/AP_AHRS.cpp
- libraries/AP_AHRS/AP_AHRS.h
- libraries/AP_Mount/SoloGimbal.cpp
- libraries/AP_Mount/SoloGimbal.h
> Pass vector by const ref when needed

- Tools/scripts/build_appveyor.sh
- appveyor.yml
- libraries/DataFlash/DataFlash.cpp
this replaces the previous makefile build that @meee1 was doing
> SITL: build cygwin32 binaries for GCS SITL

- Tools/LogAnalyzer/DataflashLog.py
Fixes the "Unknown mode" warning seen in https://github.com/ArduPilot/ardupilot/issues/10094
> Tools: LogAnalyzer: cope with text version of mode in MODE line

- Tools/ardupilotwaf/ardupilotwaf.py
> waf: fixed static link build

- appveyor.yml
Simplified the getting of prerequisite libraries in cygwin.
Successfully tested at https://ci.appveyor.com/project/stephendade/ardupilot/builds/21412323
> CI: Simplified Appveyor CI script

- libraries/AP_InertialSensor/AP_InertialSensor_SITL.cpp
- libraries/SITL/SITL.cpp
- libraries/SITL/SITL.h
This is useful for testing FFT on logs
> SITL: allow generation of vibration with exact frequencies

- APMrover2/version.cpp
- AntennaTracker/version.cpp
- ArduCopter/version.cpp
- ArduPlane/version.cpp
- ArduSub/version.cpp
- Tools/scripts/build_ci.sh
I delete the version process of NuttX which has already been deleted.
> Global: Delete NuttX version processing

- Tools/autotest/arducopter.py
... only tests the sys-status bit, doesn't actually test flight performance.  But that can be added later.
> Tools: autotest: add test that rangefinder switch works

- libraries/AP_InertialSensor/AP_InertialSensor_SITL.cpp
this allows testing of fast sample logs for FFT
> AP_InertialSensor: support fast sampling in SITL

- libraries/AP_HAL_ChibiOS/hwdef/common/usbcfg.c
I used the same fixed string twice.
This character string length is specified as a direct value.
I make a fixed area by using character string as a variable.
In addition, by obtaining the character string length with strlen, we reduce human errors.
> HAL_ChibiOS: Get the number of characters in strlen

- APMrover2/Rover.h
@rmackay9 I moved the function to its alphabetical order.
> Rover: move mode_from_mode_num function to its alphabetical order.

- ArduSub/AP_Arming_Sub.cpp
- libraries/AP_Arming/AP_Arming.cpp
- libraries/AP_Arming/AP_Arming.h
NFC, gain a little of flash on copter and sub
> AP_Arming clean header and const correctness

- libraries/AP_RCProtocol/AP_RCProtocol.cpp
- libraries/AP_RCProtocol/AP_RCProtocol.h
- libraries/AP_RCProtocol/AP_RCProtocol_Backend.cpp
- libraries/AP_RCProtocol/AP_RCProtocol_Backend.h
- libraries/AP_RCProtocol/AP_RCProtocol_DSM.cpp
- libraries/AP_RCProtocol/AP_RCProtocol_DSM.h
- libraries/AP_RCProtocol/AP_RCProtocol_PPMSum.cpp
- libraries/AP_RCProtocol/AP_RCProtocol_PPMSum.h
- libraries/AP_RCProtocol/AP_RCProtocol_SBUS.cpp
- libraries/AP_RCProtocol/AP_RCProtocol_SBUS.h
- libraries/AP_RCProtocol/AP_RCProtocol_SRXL.cpp
- libraries/AP_RCProtocol/AP_RCProtocol_SRXL.h
- libraries/AP_RCProtocol/AP_RCProtocol_ST24.cpp
- libraries/AP_RCProtocol/AP_RCProtocol_ST24.h
- libraries/AP_RCProtocol/AP_RCProtocol_SUMD.cpp
- libraries/AP_RCProtocol/AP_RCProtocol_SUMD.h
- libraries/AP_RCProtocol/SoftSerial.cpp
- libraries/AP_RCProtocol/SoftSerial.h
This brings the RC protocol decoding in line with master, adding the SUMD, SRXL and ST24 decoders
> Copter: updated copter 3.6 rc protocols

- ArduPlane/quadplane.cpp
we should always takeoff vertically
> Plane: fixed VTOL takeoff to ignore lat/lon in mission

- ArduPlane/ArduPlane.cpp
- ArduPlane/quadplane.cpp
- libraries/DataFlash/LogFile.cpp
This fixes the yaw reset on compass reset in the EKF
> Plane: fixed EKF yaw reset

- libraries/GCS_MAVLink/GCS_Common.cpp
this merges the changes from @amilcarlucas in https://github.com/ArduPilot/mavlink/pull/89
> MAVLink: update to latest XML

- Tools/autotest/sim_vehicle.py
- Tools/autotest/swarminit.txt
Added shifting of initial position for each SITL instance from home location based on swarminit.txt file stored in autotest folder. If the file is not found, shift towards east by 20 meters. Only implemented on using -Z or --swarm while calling sim_vehicle.py
> Swarm SITL

- APMrover2/Log.cpp
- AntennaTracker/Log.cpp
- ArduCopter/Log.cpp
- ArduPlane/Log.cpp
- ArduSub/Log.cpp
- libraries/SITL/SITL.cpp
- libraries/SITL/SITL.h
... use singleton for what it is good for.
> Stop passing dataflash pointer into Log_Write_SITL

- Tools/autotest/sim_vehicle.py
Added multicasting support in sim_vehicle.py by using --mcast.
> sim_vehicle.py multicasting

- libraries/AP_Mount/SoloGimbal_Parameters.cpp
- libraries/AP_Mount/SoloGimbal_Parameters.h
Adds the HAVE_PAYLOAD_SPACE check to the solo gimbal's driver.
> AP_Mount: Solo gimbal params use HAVE_PAYLOAD_SPACE

- ArduPlane/quadplane.cpp
tested only in SITL with quad tailsitter on branch https://github.com/kd0aij/ardupilot/pull/6
> Plane: tailsitter forward transition bugfix

- ArduPlane/events.cpp
Seems the logic was broken.
fixes https://github.com/ArduPilot/ardupilot/issues/10320
> Plane: ignore battery failsafe during landing

- libraries/RC_Channel/RC_Channel.h
- libraries/RC_Channel/RC_Channels_VarInfo.h
thanks to @Kelly-Foster for finding this
> [NFC]RC_Channel: fix receiver typos

- Tools/scripts/install-prereqs-ubuntu.sh
Add lsb-core check for lsb_release
> Tools: Update install-prereqs-ubuntu

- Tools/scripts/install-prereqs-arch.sh
- Tools/scripts/install-prereqs-mac.sh
- Tools/scripts/install-prereqs-ubuntu.sh
Everytime that I run this script I believe that Yes is default because of the capital text.
> Tools: Correct user input text: Yes is not the default option

- libraries/AP_InertialSensor/AP_InertialSensor.cpp
- libraries/AP_InertialSensor/AP_InertialSensor_BMI088.cpp
- libraries/AP_InertialSensor/AP_InertialSensor_BMI088.h
- libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
setup for 1600 Hz accel sample, 2kHz gyro sample, 24g accel range
> AP_InertialSensor: added driver for BMI088

- ArduPlane/quadplane.cpp
if rudder disarming is disabled
> Plane: allow rudder at zero throttle

- ArduCopter/mode.h
- ArduCopter/mode_flip.cpp
- Tools/autotest/arducopter.py
- Tools/autotest/common.py
> Tidy Copter's Flip mode

- libraries/AC_Fence/AC_Fence.cpp
- libraries/AC_Fence/AC_PolyFence_loader.cpp
- libraries/AC_Fence/AC_PolyFence_loader.h
- libraries/AP_Proximity/AP_Proximity_SITL.cpp
This was always passed as true.
> Remove unused store-return-point parameter

- APMrover2/GCS_Mavlink.cpp
- APMrover2/GCS_Mavlink.h
- APMrover2/Rover.h
- AntennaTracker/GCS_Mavlink.cpp
- AntennaTracker/GCS_Mavlink.h
- AntennaTracker/Tracker.h
- ArduCopter/Copter.h
- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
- ArduPlane/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.h
- ArduPlane/Plane.h
- ArduSub/GCS_Mavlink.cpp
- ArduSub/GCS_Mavlink.h
- ArduSub/Sub.h
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
- libraries/GCS_MAVLink/GCS_Dummy.h
- libraries/GCS_MAVLink/examples/routing/routing.cpp
The calculation of the sensor bits is still left to the vehicles; moving it is a larger piece of work to be tackled (again) later.
> Move sending of sys status message up

- ArduPlane/Parameters.cpp
- libraries/AP_ICEngine/AP_ICEngine.cpp
- libraries/AP_ICEngine/AP_ICEngine.h
AP_ICEngine:  use AHRS singleton.
> AP_ICEngine:  use AHRS singleton

- APMrover2/APMrover2.cpp
- APMrover2/GCS_Mavlink.cpp
- APMrover2/Log.cpp
- APMrover2/Parameters.cpp
- APMrover2/Parameters.h
- APMrover2/Rover.h
- APMrover2/sensors.cpp
- APMrover2/system.cpp
simple copy of rpm_sensor implementation from Plane.
> Rover: adding AP_RPM

- APMrover2/APMrover2.cpp
- APMrover2/Log.cpp
- APMrover2/Rover.h
- APMrover2/defines.h
- libraries/AP_Logger/LogStructure.h
- libraries/AP_WheelEncoder/AP_WheelEncoder.cpp
- libraries/AP_WheelEncoder/AP_WheelEncoder.h
This retains the 10Hz logging rate that Rover was using.
> Move Wheel encoder logging from Rover up into library

- libraries/AP_Math/crc.cpp
- libraries/AP_Math/matrix3.cpp
Just a couple of cherry-picked cleanups.
> Cherry-picked math cleanups

- libraries/Filter/LowPassFilter2p.cpp
this fixes #10435 
ping @peterbarker
> Filter: fixed crash on zero cutoff frequency

- Tools/autotest/common.py
Handy if you've got enable parameters in a parameter file...
> Tools: autotest: repeatedly apply parameter file

- .gitignore
for those using CLion like me ... or another jetbrains ide
> gitignore: ignore Jetbrains files and cmake build

- libraries/AP_Rally/AP_Rally.cpp
master currently isn't compiling.  This fixes that.
> AP_Rally: use AP::rally() to get singleton

- libraries/AP_Airspeed/AP_Airspeed_UAVCAN.cpp
- libraries/AP_Airspeed/AP_Airspeed_UAVCAN.h
- libraries/AP_Baro/AP_Baro_UAVCAN.cpp
- libraries/AP_Baro/AP_Baro_UAVCAN.h
- libraries/AP_Compass/AP_Compass_UAVCAN.cpp
- libraries/AP_Compass/AP_Compass_UAVCAN.h
- libraries/AP_GPS/AP_GPS_UAVCAN.cpp
> Remove uavcan-backend give/take registry

- ArduPlane/ArduPlane.cpp
- ArduPlane/Plane.h
- ArduPlane/quadplane.cpp
- ArduPlane/quadplane.h
- ArduPlane/servos.cpp
disable by default
check quadplane.enable in update_hover_learn
> ArduPlane: implement hover throttle learning for quadplanes

- libraries/GCS_MAVLink/GCS_Common.cpp
> GCS_MAVLink: clarify packetReceive calling handlemessage checks

- libraries/AP_ICEngine/AP_ICEngine.cpp
- libraries/AP_ICEngine/AP_ICEngine.h
- libraries/AP_RPM/RPM_Backend.h
AP_ICEngine: add singleton
AP_RPM: remove magic number - non-functional change
> AP_ICEngine: add singleton, fix rpm magic number

- Tools/autotest/apmrover2.py
- Tools/autotest/arducopter.py
- Tools/autotest/arduplane.py
- Tools/autotest/ardusub.py
- Tools/autotest/common.py
- Tools/autotest/quadplane.py
the lambda checker was called on common.py and not the right files
> Tools: fix lambda test

- .azure/autotest_template.yml
- .azure/azure-pipelines.yml
- README.md
- Tools/ardupilotwaf/ardupilotwaf.py
- Tools/ardupilotwaf/boards.py
- Tools/ardupilotwaf/toolchain.py
- Tools/autotest/arduplane.py
- Tools/autotest/common.py
- wscript
GitHub is playing games apparently and didn't re-open the previous PR, so new PR.
Follow the history in #10027, especially last comment.
> CI: add Azure pipelines (continuation of #10027)

- Tools/autotest/arducopter.py
- Tools/autotest/arduplane.py
- Tools/autotest/common.py
We have functions for achieving this
Also, a lot of these places were missing timeouts, so any failure would
cause the entire suite to stop running
> Tools: autotest: eliminate use of recv_match with condition

- ArduPlane/radio.cpp
broken by recent radio input changes
Thanks to Michael for noticing!
> Plane: fixed throttle nudge

- libraries/AP_RangeFinder/AP_RangeFinder_LightWareSerial.cpp
- libraries/AP_RangeFinder/AP_RangeFinder_LightWareSerial.h
it needs a longer serial write to force it to serial mode from i2c
> AP_RangeFinder: fixed lightware serial with LW20 lidar

- libraries/AP_UAVCAN/AP_UAVCAN_Servers.cpp
- libraries/AP_UAVCAN/AP_UAVCAN_Servers.h
Thanks to AeroNavics for sponsoring this work.
> AP_UAVCAN: handle restart_node

- libraries/SITL/SIM_JSBSim.cpp
PR for [issue #10567](https://github.com/ArduPilot/ardupilot/issues/10567)
> PR: ArduPlane + latest JSBSim: Wrong airspeed units conversion, issue #10567

- APMrover2/APMrover2.cpp
- AntennaTracker/AntennaTracker.cpp
- ArduCopter/ArduCopter.cpp
- ArduPlane/ArduPlane.cpp
- ArduSub/ArduSub.cpp
- libraries/AP_AHRS/AP_AHRS.cpp
- libraries/AP_AHRS/AP_AHRS.h
We should reserve set_ for setters...
> Rename set_orientation to update_orientation

- ArduCopter/config.h
- ArduCopter/mode_brake.cpp
- ArduCopter/mode_guided.cpp
- ArduCopter/mode_guided_nogps.cpp
- ArduCopter/mode_loiter.cpp
- ArduCopter/mode_poshold.cpp
- ArduCopter/mode_rtl.cpp
- ArduCopter/mode_sport.cpp
Other options flight mode has code disabled.
I thought it would be better to combine.
> Copter: Disable option code

- ArduCopter/mode.h
- ArduCopter/mode_auto.cpp
> Copter: make LOITER_TIME send "Reached command" message to GCS

- Tools/autotest/common.py
- libraries/AP_AHRS/AP_AHRS_DCM.cpp
- libraries/GCS_MAVLink/GCS.cpp
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
I've preserved the "send immediately" aspect here; I'm not sure we should in the longer term.
... this PR also allows a GCS to request the message...
> Retry sending origin and home if they fail to send

- libraries/AP_HAL_SITL/Storage.cpp
> AP_HAL_SITL: correct comparison between signed and unsigned

- ArduCopter/landing_gear.cpp
- ArduCopter/mode.cpp
- ArduCopter/mode.h
As discussed on devcall today, where I successfully resisted the dreaded scope-creep.
> Copter: get_alt_above_ground to get_alt_above_ground_cm

- .azure/autotest_template.yml
- .azure/azure-pipelines.yml
- .github/SUPPORT.md
- Tools/scripts/build_ci.sh
This does several things:
- adds git and build logs in Azure builds, as requested by @tridge 
- fixes autotest build setup in Azure (likely the tests will actually fail, will need to fix them after they run, likely nagging @peterbarker to help 😜)
- add a support markdown file for GitHub (https://help.github.com/en/articles/adding-support-resources-to-your-project)
- removes old code from CI build file
> Azure, GitHub and CI changes

- ArduCopter/mode_follow.cpp
- libraries/AP_Follow/AP_Follow.cpp
- libraries/AP_Follow/AP_Follow.h
This improves consistency by adding frame and unit information to variables and function calls.
> Copter: (NFC) renames for readability

- libraries/AC_PrecLand/AC_PrecLand.cpp
- libraries/AC_PrecLand/AC_PrecLand.h
- libraries/AC_PrecLand/AC_PrecLand_Backend.h
- libraries/AC_PrecLand/AC_PrecLand_Companion.cpp
- libraries/AC_PrecLand/AC_PrecLand_Companion.h
- libraries/AC_PrecLand/AC_PrecLand_IRLock.cpp
- libraries/AC_PrecLand/AC_PrecLand_IRLock.h
- libraries/AC_PrecLand/AC_PrecLand_SITL.cpp
- libraries/AC_PrecLand/AC_PrecLand_SITL.h
- libraries/AC_PrecLand/AC_PrecLand_SITL_Gazebo.h
- libraries/AP_HAL_SITL/SITL_State.cpp
- libraries/AP_IRLock/AP_IRLock.h
- libraries/AP_IRLock/AP_IRLock_I2C.cpp
- libraries/AP_IRLock/AP_IRLock_I2C.h
- libraries/AP_IRLock/AP_IRLock_SITL.cpp
- libraries/AP_IRLock/AP_IRLock_SITL_Gazebo.cpp
- libraries/AP_IRLock/AP_IRLock_SITL_Gazebo.h
- libraries/AP_IRLock/IRLock.cpp
- libraries/AP_IRLock/IRLock.h
- libraries/SITL/SIM_Aircraft.cpp
- libraries/SITL/SIM_Aircraft.h
- libraries/SITL/SIM_Precland.cpp
- libraries/SITL/SIM_Precland.h
- libraries/SITL/SITL.cpp
- libraries/SITL/SITL.h
This is a slightly tidied version of https://github.com/ArduPilot/ardupilot/pull/9098/files
- split commits appropriately
- squashed
- rebased
@khancyr Some autotests would be nice :-)
@khancyr Has your code been tested on a real vehicle?
> Tidy Precision Landing

- .travis.yml
- Tools/autotest/arducopter.py
- Tools/autotest/common.py
We shouldn't try to upload on ardupilot server by default
I don't know if more action it need on our side
> Fix failed test log download

- AntennaTracker/GCS_Mavlink.cpp
- AntennaTracker/GCS_Mavlink.h
- AntennaTracker/Tracker.h
- AntennaTracker/tracking.cpp
- libraries/GCS_MAVLink/GCS.h
More work extracted from @IamPete1 's PRs.
> Tracker: Use initial position in global_position_int until AHRS is happy with position

- AntennaTracker/GCS_Mavlink.cpp
- AntennaTracker/tracking.cpp
Also don't indicate we are armed if we are in INITIALISING
More work of @IamPete1 's pulled out into a separate PR.
> Tracker: honour vehicle arm status

- libraries/AP_Logger/AP_Logger.cpp
- libraries/AP_Logger/AP_Logger.h
Also strongly type the backend type
> AP_Logger: remove more DataFlash references

- Tools/scripts/uploader.py
The mRoX2.1 may have a board ID of 33 (0x21), but runs the firmware for fmuv3 (boardID=9).  This adds a dictionary (currently only one entry) which specifies firmware which is compatible with a given boardID.
Test result:
```
python Tools/scripts/uploader.py --port COM24 arduplane.apj
Loaded firmware for 9,0, size: 1025656 bytes, waiting for the bootloader...
If the board does not respond within 1-2 seconds, unplug and re-plug the USB connector.
```
**Found board 21,0 bootloader rev 5 on COM24
INFO: Target AUAVX2.1 (board_id: 33) is compatible with firmware for board_id=9)
...**
```
sn: 002700423236510c36363331
chip: 20016419
family: STM32F42x
revision: 3
flash 2080768
Erase  : [====================] 100.0%
Program: [====================] 100.0%
Verify : [====================] 100.0% …
```
> Tools: scripts: support auavx2.1 bootloader with board ID of 33

- Tools/CPUInfo/CPUInfo.cpp
- Tools/CPUInfo/EKF_Maths.cpp
- Tools/CPUInfo/EKF_Maths.h
- libraries/SITL/SIM_Motor.cpp
Useful for looking at caching effects
> Add an EKF maths test to CPUInfo

- libraries/AP_RCProtocol/examples/RCProtocolTest/RCProtocolTest.cpp
based on data from Luis from issue #10346
> AP_RCProtocol: added another SUMD test

- ArduPlane/tailsitter.cpp
tested in SITL/RF8 with AddictionX
original behavior with Q_TAILSIT_THSCMX > 1
Mainly intended for "copter" tailsitters.
Set Q_TAILSIT_THSCMX < 1 if your vehicle doesn't lack hover stability and you plan to fly relatively fast in Qmodes.  Will use airspeed if sensor available, throttle and attitude otherwise.
Probably need to add a new parameter for max_atten
Possibly need one for throttle threshold (tthr)
This PR is related to https://github.com/ArduPilot/ardupilot/pull/9167 but is aimed at extending use of the copter attitude controller to all attitudes, i.e. QACRO mode works for "fixed wing" flight as well as VTOL flight.  
The "no airspeed sensor" code is necessary for tailsitters because wind estimation is not accurate during VTOL operation.  
Future enhancement: If an airspeed …
>  tailsitter gain scaling with support for airspeed sensor for high-speed flight in Qmodes

- ArduCopter/Copter.h
> Copter: remove unused includes

- ArduPlane/ArduPlane.cpp
- ArduPlane/GCS_Mavlink.cpp
- ArduPlane/GCS_Plane.cpp
- ArduPlane/GCS_Plane.h
- ArduPlane/Plane.h
- Tools/autotest/arduplane.py
- libraries/AP_Airspeed/AP_Airspeed.h
- libraries/AP_Airspeed/Airspeed_Calibration.cpp
When other vehicles get support for this the code will be there..
> Move sending of airspeed autocal into AP_Airspeed

- Tools/autotest/common.py
Sub has issues getting messages out early.
> Tools: autotest: increase timeout on pid tuning

- APMrover2/AP_Arming.cpp
- ArduCopter/AP_Arming.cpp
This is on top of https://github.com/ArduPilot/ardupilot/pull/10711 and https://github.com/ArduPilot/ardupilot/pull/10710
Still not sure how to fix the AP_Motors ones.
> Remove redundant PreArm: text

- Tools/scripts/build-jsbsim.sh
- Tools/vagrant/initvagrant-trusty64.sh
- Tools/vagrant/shellinit.sh
Just a tidy-up of https://github.com/ArduPilot/ardupilot/pull/10185 to meet our standards.
> Move Vagrant to using new JSBSim

- Tools/autotest/arducopter.py
Also remove pointless (unclosed) contexts and try blocks
> Tools: autotest: reduce output lines in NavDelay test

- Tools/autotest/arduplane.py
70 degrees is past LIM_ROLL_CD!
> Tools: autotest: fix Plane guided test

- libraries/AP_HAL_ChibiOS/Device.cpp
- libraries/AP_HAL_ChibiOS/SPIDevice.cpp
This fixes an issue with microSD on F405
> ChibiOS: fixed SD card issues on F405

- .travis.yml
- Tools/scripts/build_ci.sh
ensure these two build types don't get broken
> travis: added F7 and H7 boards to travis builds

- libraries/AP_HAL_ChibiOS/Storage.cpp
this prevents a single flash write error from causing parameter reset
> HAL_ChibiOS: added retries to flash based storage

- ArduPlane/AP_Arming.cpp
- ArduPlane/quadplane.h
- Tools/autotest/arducopter.py
- Tools/autotest/common.py
- Tools/autotest/quadplane.py
Built on top of https://github.com/ArduPilot/ardupilot/pull/10214
> Use Controller pre-arm checks in QuadPlane

- libraries/AP_InertialSensor/AP_InertialSensor.cpp
Fix typo in comments should be NFC
> INS: Update comment AP_InertialSensor.cpp

- Tools/autotest/antennatracker.py
- Tools/autotest/apmrover2.py
- Tools/autotest/arducopter.py
- Tools/autotest/arduplane.py
- Tools/autotest/ardusub.py
- Tools/autotest/common.py
- Tools/autotest/quadplane.py
This makes us more consistent across our testing.
> Factor init and __init__ up into AutoTest base class

- APMrover2/sensors.cpp
- AntennaTracker/sensors.cpp
- ArduCopter/sensors.cpp
- ArduPlane/system.cpp
- ArduSub/sensors.cpp
- libraries/AP_AHRS/examples/AHRS_Test/AHRS_Test.cpp
- libraries/AP_Compass/AP_Compass.cpp
- libraries/AP_Compass/AP_Compass.h
- libraries/AP_Compass/examples/AP_Compass_test/AP_Compass_test.cpp
This can never fail, so make it void and stop checking the return value.
> Make Compass::init() void

- Tools/autotest/common.py
The EKF can be healthy and the GPS unhealthy.
I have mixed feelings about this PR.
https://api.travis-ci.org/v3/job/505177906/log.txt shows a failure:
```
AUTOTEST: Wait EKF.flags: required:831 current:165 errors=128
APM: EKF2 IMU0 is using GPS
AUTOTEST: Wait EKF.flags: required:831 current:831 errors=0
AUTOTEST: EKF Flags OK
AUTOTEST: Arm motors with MAVLink cmd
APM: PreArm: GPS is not healthy
Got MAVLink msg: COMMAND_ACK {command : 400, result : 4}
```
The problem is that I've never seen that sequence of events before in SITL, and I can't understand why the GPS would be marking itself as unhealthy there.  Unfortunately, this PR will neatly paper over that issue.
> Tools: autotest: add check that GPS is healthy before arming

- libraries/AP_RCProtocol/AP_RCProtocol_Backend.cpp
- libraries/AP_Vehicle/AP_Vehicle_Type.h
- libraries/RC_Channel/RC_Channel.h
- libraries/RC_Channel/RC_Channels_VarInfo.h
> Added RC_OPTIONS bit for ignoring RC failsafe

- libraries/AP_ADSB/AP_ADSB.cpp
- libraries/AP_ADSB/AP_ADSB.h
Add simple accessor for a remote library/vehicle to fetch an adsb_vehicle by icao id
Useful for https://github.com/ArduPilot/ardupilot/pull/10522/
> AP_ADSB: add accessor to fetch a vehicle from database by icao

- AntennaTracker/Parameters.cpp
- AntennaTracker/Parameters.h
- AntennaTracker/system.cpp
> Tracker: add initial mode parameter

- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Param.cpp
time-of-check-to-time-of-use error :-)
> GCS_MAVLink: correct check for parameter_value space

- libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
- libraries/AC_AttitudeControl/AC_AttitudeControl.h
- libraries/AP_AHRS/AP_AHRS.h
- libraries/AP_AHRS/AP_AHRS_View.h
> AP_AHRS: add new method get_quat_body_to_ned()

- Tools/autotest/antennatracker.py
- Tools/autotest/apmrover2.py
- Tools/autotest/arducopter.py
- Tools/autotest/arduplane.py
- Tools/autotest/common.py
- libraries/GCS_MAVLink/GCS_Common.cpp
Should replace https://github.com/ArduPilot/ardupilot/pull/9941
> Do not allow rebooting via mavlink when armed

- libraries/AP_UAVCAN/AP_UAVCAN.cpp
- libraries/AP_UAVCAN/AP_UAVCAN.h
Avoids heap allocation in flight
> AP_UAVCAN: use fixed-size memory pool

- libraries/AP_Frsky_Telem/AP_Frsky_Telem.h
Following up on @yaapu comment https://github.com/ArduPilot/ardupilot/pull/10499#issuecomment-474625077
> FrSky: Adjusted offsets

- APMrover2/AP_MotorsUGV.cpp
- APMrover2/radio.cpp
- APMrover2/sailboat.cpp
- APMrover2/system.cpp
> Rover: Fix typos

- AntennaTracker/GCS_Mavlink.cpp
- Tools/autotest/common.py
Possible better fix for #10896
> Emit  EKF status report in tracker / add timeout for EKF_STATUS_REPORT to autotest

- Tools/autotest/ardusub.py
> autotest: Remove magic numbers in ardusub

- Tools/autotest/apmrover2.py
... via mavlink.
These are the same tests we use for rc channel overrides.
> Tools: autotest: add test for Rover manual control

- ArduCopter/Attitude.cpp
- ArduCopter/mode.cpp
> Copter: move Mode functions into mode.cpp from Attitude.cpp (NFC)

- Tools/scripts/decode_devid.py
- libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
- libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
- libraries/AP_InertialSensor/AP_InertialSensor_Invensense.h
- libraries/AP_InertialSensor/AP_InertialSensor_Invensense_registers.h
30g accel limit, 4k deg/sec gyro
> Added driver for ICM20601

- ArduCopter/Attitude.cpp
- ArduCopter/Copter.h
- ArduCopter/Log.cpp
- ArduCopter/inertia.cpp
There were only two users of it and dozens of places using
get_velocity_z
> Copter: remove climb_rate cache of inertial_nav.get_velocity_z

- libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
- libraries/AP_NavEKF2/AP_NavEKF2.cpp
- libraries/AP_NavEKF2/AP_NavEKF2.h
- libraries/AP_NavEKF3/AP_NavEKF3.cpp
- libraries/AP_NavEKF3/AP_NavEKF3.h
attitude check needs to be performed in vehicle body frame to account for AHRS_TRIM
replaces #10854
> AP_AHRS: fix attitudes_consistent bug

- ArduPlane/servos.cpp
when wiggle value is zero servos should be neutral
> Plane: fixed WAIT_ALTITUDE wiggle

- Vagrantfile
Note that jsbsim doesn't actually work on this VM...
Still, this way someone can replicate the problem and fix it if they like.
> Vagrant: add support for disco

- libraries/AP_InertialSensor/AP_InertialSensor.cpp
NFC: Correct comments ICM20648 should have been ICM20948
> INS: AP_InertialSensor comments for new cubes

- libraries/AP_Airspeed/examples/Airspeed/Airspeed.cpp
- libraries/AP_Baro/examples/BARO_generic/BARO_generic.cpp
- libraries/AP_Compass/examples/AP_Compass_test/AP_Compass_test.cpp
- libraries/AP_GPS/examples/GPS_AUTO_test/GPS_AUTO_test.cpp
I have added new comments, and improved existing comments, to the example sketches of the following libraries:
AP_Airspeed
AP_Baro
AP_Compass
AP_GPS
> added comments to example sketch

- Tools/autotest/arducopter.py
- Tools/autotest/common.py
> Tools: autotest: check we're seeing PL messages in the log during

- Tools/autotest/arducopter.py
make sure the target is away from the current location
> autotest: fixed precision landing test for copter

- Tools/scripts/build_binaries.py
This auto builds tracker on the common boards.
> Tools: autobuild tracker on common boards

- ArduCopter/defines.h
- ArduCopter/mode.h
- ArduCopter/mode_flip.cpp
... including a redundant definition of the states...
> Copter: clean up flip state enumerations

- libraries/AP_InertialSensor/AP_InertialSensor_BMI088.cpp
- libraries/AP_InertialSensor/AP_InertialSensor_BMI088.h
this fixes an issue with setting up accel config registers on SPI.
> AP_InertialSensor: added BMI088 accel config retry

- ArduPlane/quadplane.cpp
- libraries/AC_Fence/AC_Fence.cpp
- libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
- libraries/AP_Arming/AP_Arming.cpp
- libraries/AP_Avoidance/AP_Avoidance.cpp
- libraries/AP_Beacon/AP_Beacon_SITL.cpp
- libraries/AP_Common/Location.cpp
- libraries/AP_Common/Location.h
- libraries/AP_GPS/AP_GPS.cpp
- libraries/AP_L1_Control/AP_L1_Control.cpp
- libraries/AP_Landing/AP_Landing_Deepstall.cpp
- libraries/AP_Math/location.cpp
- libraries/AP_Math/location.h
- libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp
- libraries/AP_NavEKF2/AP_NavEKF2_Outputs.cpp
- libraries/AP_NavEKF2/AP_NavEKF2_VehicleStatus.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_VehicleStatus.cpp
- libraries/AP_Soaring/AP_Soaring.cpp
- libraries/AP_Terrain/TerrainIO.cpp
- libraries/AP_Terrain/TerrainUtil.cpp
- libraries/SITL/SIM_CRRCSim.cpp
Warning, there are three place where I change to get_distance instead of getting the length of the NE distance vector.
> AP_Math: move location_diff to Location and rename

- libraries/AP_Declination/generate/generate.py
I don't know where to grab the relevant Python library from to actually do the generation.  If someone could add some directions into the generation script that would be great...
> AP_Declination: generate tables with float designator

- ArduCopter/Parameters.cpp
- ArduCopter/Parameters.h
- ArduCopter/mode.cpp
- ArduCopter/mode.h
- Tools/autotest/arducopter.py
... presumably again.
I believe this was code which was supposed to come in from Solo but never did.
I wonder if this would be better done as a minimum climb rate?
> Remove unused PILOT_TKOFF_DZ / add test for user-takeoff

- APMrover2/Log.cpp
- ArduCopter/ArduCopter.cpp
- ArduPlane/Log.cpp
- libraries/AP_Logger/AP_Logger.h
- libraries/AP_Logger/LogFile.cpp
- libraries/GCS_MAVLink/GCS_Common.cpp
Means AP_Logger.h (incuded by a lot of places) doesn't need to include AP_RSSI.h
> Use singleton for RSSI logging

- ArduCopter/Copter.h
- ArduCopter/esc_calibration.cpp
prevent spamming on esc calibration
factorize to reduce size
> Copter: solve always true condition on esc_calibration and factorize

- libraries/AP_HAL_SITL/UARTDriver.cpp
> AP_HAL_SITL: Correct range check on UART ports

- libraries/AP_HAL/AP_HAL.h
- libraries/AP_HAL/AP_HAL_Namespace.h
- libraries/AP_HAL/Flash.h
- libraries/AP_HAL/HAL.h
- libraries/AP_HAL_ChibiOS/AP_HAL_ChibiOS_Namespace.h
- libraries/AP_HAL_ChibiOS/AP_HAL_ChibiOS_Private.h
- libraries/AP_HAL_ChibiOS/Flash.h
- libraries/AP_HAL_ChibiOS/HAL_ChibiOS_Class.cpp
- libraries/AP_HAL_ChibiOS/Storage.cpp
- libraries/AP_HAL_ChibiOS/Storage.h
- libraries/AP_HAL_ChibiOS/Util.cpp
- libraries/AP_HAL_Empty/AP_HAL_Empty_Namespace.h
- libraries/AP_HAL_Empty/AP_HAL_Empty_Private.h
- libraries/AP_HAL_Empty/Flash.h
- libraries/AP_HAL_Empty/HAL_Empty_Class.cpp
- libraries/AP_HAL_Linux/HAL_Linux_Class.cpp
- libraries/AP_HAL_SITL/HAL_SITL_Class.cpp
This adds a semaphore to protect flash API usage from multiple threads
> HAL: added flash interface

- Tools/autotest/common.py
This gets logged into the dataflash so you can quickly find relevant
logs
> Tools: autotest: send statustext with test name to autopilot

- libraries/SITL/SIM_FlightAxis.cpp
use 3D wind to get airspeed along X axis of aircraft
> SITL: improve airspeed in FlightAxis for RF8

- Tools/autotest/arducopter.py
- Tools/autotest/common.py
This is mostly @caomuqing 's work
> Add test for zigzag mode

- libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
- libraries/AC_AttitudeControl/AC_AttitudeControl.h
- libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp
- libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.h
- libraries/AC_AttitudeControl/AC_PosControl.cpp
- libraries/AC_AttitudeControl/AC_PosControl.h
> AC_AttitudeControl: Formatting Changes

- ArduCopter/takeoff.cpp
This PR back ports PR #10935 to Copter 3.6.
> Copter: Tradheli- removes suppression of hover_trim_roll on auto takeoff

- libraries/AC_Fence/AC_Fence.cpp
- libraries/GCS_MAVLink/GCS_Common.cpp
- libraries/GCS_MAVLink/GCS_Rally.cpp
Doesn't seems worthy
will allow to const multiple fonctions
> Change mavlink send_buf usage to send

- libraries/AP_GPS/AP_GPS_SBF.cpp
- libraries/AP_GPS/AP_GPS_SBF.h
This is a backport for @rmackay9 of #11025
I also stuffed up and did Copter first by accident, so https://github.com/WickedShell/ardupilot/tree/wickedshell/3.6-gps-backport is sitting around if you want.
> Rover 3.5: Backport #11025

- libraries/AP_OSD/AP_OSD.cpp
- libraries/AP_OSD/AP_OSD.h
This is alternative implementation for OSD screen switching basing on discussion in https://github.com/ArduPilot/ardupilot/pull/10679
> AP_OSD: Switch screens basing on ARM state

- libraries/AP_Airspeed/AP_Airspeed_MS5525.cpp
- libraries/AP_Baro/AP_Baro_MS5611.cpp
- libraries/AP_Baro/AP_Baro_MS5611.h
- libraries/AP_Math/crc.cpp
- libraries/AP_Math/crc.h
I think it is better to share the CRC4 calculation method.
> AP_Math: Commonize the CRC4 method

- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/mode_guided.cpp
> Copter: replace 4 divisions with multiplications
