ArduPilot/ardupilot

libraries/AC_Fence/LogStructure.h, libraries/AP_Logger/LogStructure.h
trailing comma if not compiled in.
This can't have been tested.
=> AP_Logger: correct compilation when fence compiled out

libraries/AP_Baro/AP_Baro.cpp, libraries/AP_Baro/AP_Baro.h, libraries/AP_Baro/AP_Baro_BMP085.cpp
This is a proposed fix for this issue [https://github.com/ArduPilot/ardupilot/issues/20887](https://github.com/ArduPilot/ardupilot/issues/20887)
The fix checks that there is no baro driver already allocated on the same type/bus/address, and if found then it does not create it.
=> fix: baro same driver multi-definition issues:20887

Tools/scripts/apj_tool.py, Tools/scripts/generate_manifest.py
production bootloader uses 0x38
=> Tools: fixed Holybro 6C product ID in manifest

libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_WPNav/AC_Loiter.cpp
This PR fixes two problems:
1. The position controller relax_velocity_controller_xy function results in a much slower decay of the target acceleration than expected because it uses the attitude controller target attitude as the reference state. The additional input shaping means that the target attitude does not follow the commanded attitude exactly meaning that each commanded angular step towards zero is much smaller than expected.
2. Loiter was not using relax_velocity_controller_xy and instead was using init_xy_controller. This meant that if loiter landed and shut down with a non-zero attitude, this attitude would persist until the following take-off. 
Master:
Attitude target does not return to zero.
After PR:
The change to the position controller ensures the aircraft relaxes as …
=> PosController: Slow relax behaviour bug

libraries/AP_IOMCU/AP_IOMCU.cpp, libraries/AP_IOMCU/AP_IOMCU.h
Tested with this patch to the IOMCU firmware:
```
--- a/libraries/AP_IOMCU/iofirmware/iofirmware.cpp
+++ b/libraries/AP_IOMCU/iofirmware/iofirmware.cpp
@@ -437,6 +437,12 @@ bool AP_IOMCU_FW::handle_code_read()
COPY_PAGE(rc_input);
break;
case PAGE_STATUS:
+
+    if (AP_HAL::millis() > 10000 &&
+        AP_HAL::millis() < 20000) {
+        return false;
+    }
+
COPY_PAGE(reg_status);
break;
case PAGE_SERVOS:
```
yielded this data:
=> Log IOMCU status-page receive errors

ArduCopter/mode_poshold.cpp
This is a small and unimportant update to PosHold where I have removed the unnecessary calls to loiter_nav->update.
It doesn't fix any problems, just simplifies the code and makes it consistent with Loiter.
=> Copter: PosHold: remove unnecessary loiter_nav->update

libraries/AP_HAL_SITL/SITL_State.cpp
This fixes the behavior of SIM_RC_FAIL = 1 (no pulses) when RC override messages are being received.
Currently, in SITL, if the user sets SIM_RC_FAIL = 1 while sending RC overrides, conventional RC messages are still received by the vehicle for channels not being overridden. In this [screen recording](https://www.youtube.com/watch?v=Rrjh9ruWUpY), the vehicle is sent RC overrides for channel 4 to induce yaw motion. SIM_RC_FAIL is then set to 1. Conventional RC messages are then sent for channels 1 and 2, to which the vehicle responds. Expected behavior is for the vehicle to not receive these conventional RC messages, as there is a simulated RC failure.
This [screen recording](https://www.youtube.com/watch?v=Oj37U4ZvjbM) shows the behavior after applying this patch. After setting …
=> SITL: fix simulated RC failure while receiving RC overrides

Tools/autotest/quadplane.py
trivial takeoff test in qloiter.
Will break with the default ship speed of 3.
=> autotest: add a test for SIM_SHIP_ENABLE

Tools/scripts/build_options.py, Tools/scripts/extract_features.py
here is the first part of updating extract_features.py
I also have the list in text form for feature name, so it will be easy to diff on each board to get the shorter list of EXCLUDED features once the features list is extracted, to present to users...
also corrected the existing feature names in this file
I changed the labels to include the class, since the subclasses which were being used are not unique...this fixes that...
~~a few strange things during testing....I used a master build for the CubeOrange....it could not find either the NMEA nor UAVCAN airspeed sensor....the UAVCAN sensor is present in the elf and matches the string, but is not reported....and the NMEA airspeed sensor is not in the elf dump, but should be as far as I can tell tracing the ifdefs....I tried looking for the …
=> Tools: added build features list to extract_features.py

Tools/autotest/arducopter.py
Test sporadically failing on autotest server.
=> autotest: explicltly close filehandle with streamrate contents

ArduPlane/Attitude.cpp
This fixes a error from https://github.com/ArduPilot/ardupilot/pull/9680
The current code uses airspeed min for scaling min and airspeed max for scaling max. This is backwards. Currently changing max air speed makes no difference to the lower scaling limit used at high airspeed, instead it changes the upper limit used at low airseed.
In order to not change the limits too much I have changed the scale factors from 0.5 and 1.5 to 0.7 and 2.0. This matches up the two limits fairly well with default param, but might not for others. 
I wonder if we should just hard code the upper limit to 2 at low airspeed. That is the one that will likely cause issues. Due to the gradient of the line at low airspeed small changes will make a big scaling difference.
=> Plane: correct extened range airspeed scailing limits

libraries/AP_GPS/AP_GPS.cpp
this has options for things other than moving baseline
=> AP_GPS: remove incorrect build option on GPS_DRV_OPTIONS param

ArduPlane/AP_Arming.cpp, ArduPlane/Attitude.cpp, ArduPlane/defines.h
Follow up to https://github.com/ArduPilot/ardupilot/pull/21632. It turns out is it more common that I had expected for users to set very low min airspeeds due to setup misunderstandings. This both protects against a potential divide by zero and adds a arming check.
=> Plane: add min airspeed arming check and constrain for speed scailing

ArduCopter/GCS_Mavlink.cpp
This fixes a scaling issue in Copter's consumption of the MAV_CMD_DO_MOUNT_CONTROL message.  The command's yaw was being interpreted as if it was centi-degrees but the [mavlink spec](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1166) says degrees.  This only affects Copters with a 2-axis gimbal
This is related to PR https://github.com/ArduPilot/ardupilot/pull/21530 (which solved a similar problem in the AP_Mount driver but didn't resolve this Copter vehicle level issue).
This resolves issue https://github.com/ArduPilot/ardupilot/issues/15699
I've tested this in SITL and confirmed that before, the vehicle was always pointed quite close to zero (e.g. a request for 90 degrees would point the vehicle at 0.9 deg) and that after it points in the correct …
=> Copter: fix do-mount-control yaw scaling

libraries/AP_Scripting/applets/VTOL-quicktune.lua, libraries/AP_Scripting/examples/Aerobatics/Missions/plane_aerobatics.lua, libraries/AP_Scripting/examples/Aerobatics/Via_Switch/10_loops-and-immelman.lua, libraries/AP_Scripting/examples/Aerobatics/Via_Switch/5_knifedges.lua, libraries/AP_Scripting/examples/CAN_MiniCheetah_drive.lua, libraries/AP_Scripting/examples/CAN_read.lua, libraries/AP_Scripting/examples/CAN_write.lua, libraries/AP_Scripting/examples/OOP_example.lua, libraries/AP_Scripting/examples/SN-GCJA5-particle-sensor.lua, libraries/AP_Scripting/examples/UART_log.lua, libraries/AP_Scripting/examples/i2c_scan.lua, libraries/AP_Scripting/examples/logging.lua, libraries/AP_Scripting/examples/plane-wind-fs.lua, libraries/AP_Scripting/examples/plane_ship_landing.lua, libraries/AP_Scripting/lua_bindings.cpp
This updates our manual bindings to allow both types of access. EG `logger.write(...` and `logger:write(...`. This oddity of the manual bindings is annoying and confusing. 
This also updates all the examples to use the `:` in line with all the other AP bindings. This does mean that all the master examples will not work on stable, but that is true whenever we add new stuff. 
Old scripts using `.` will still work on master, tested both methods for i2c and CAN on CubeOrange and logging in SITL.
=> AP_Scripting: allow : access to manual bindings 

Tools/environment_install/install-ROS-ubuntu.sh
This is a re-submission of PR https://github.com/ArduPilot/ardupilot/pull/21579 to add an easy installation of an ArduPilot compatible setup of ROS on an ubuntu machine.  In particular this makes it easy to get AP SITL + ROS running.
I've tested this on my WSL2/Ubuntu20.04 installation and it works.
=> Tools: Add ROS and Ardupilot-ros environment install script

libraries/AC_PrecLand/AC_PrecLand_Companion.cpp, libraries/AC_PrecLand/AC_PrecLand_Companion.h
This PR add support for LANDING_TARGET mavlink2 position extension field.  For companion computer using fiducial markers, it makes FC integration easier.  I will do more tests once weather condition is ok.
[2022-08-01 15-49-41.zip](https://github.com/ArduPilot/ardupilot/files/9238663/2022-08-01.15-49-41.zip)
=> PrecLand: support LANDING_TARGET ext field

libraries/AP_Logger/AP_Logger_MAVLink.cpp
This is an expanded version of #18397, see the comment from the commit below for more reasoning.
This is a change in bevaiour. The previous behaviour was to check for a NACK, and if it wasn't a NACK it was assumed to be an ACK. This is a bad assumption to let people get away with, because in the future if we ever add other options to the enum we are more likely to have to cope with bad implementation in the wild
This was tested with SITL and mavlink-router and seems to work fine. We need to also test that all the other known backends work:
As a final aside handling the `_END` entry in the enum doesn't increase code size at all, it just gets optimized out.
=> AP_Logger: Be stricter on MAVLink ack handling

libraries/AP_Mission/AP_Mission_Commands.cpp, libraries/AP_Mount/AP_Mount.cpp, libraries/AP_Mount/AP_Mount.h
This PR adds support for a 2nd gimbal, and while at first this looks like a big change, in fact, it is only the last 3 commits that are new.  The rest are from this existing PR https://github.com/ArduPilot/ardupilot/pull/21602
Changes included in this PR are:
1. MNT2_xx parameters appear in the parameter list for all vehicles that include AP_Mount
2. DO_GIMBAL_MANAGER_PITCHYAW handling is enhanced to consume the gimbal_id (aka "instance") and pass it to the mount library which already supports multiple gimbals.  This change affects both mission commands and "immediate" commands sent from the ground station.
This is how it behaves:
1. Older commands including MOUNT_CONTROL, MOUNT_CONFIG, SET_ROI have no way to specify the "gimbal id" (aka "instance") so they always affect the "primary" …
=> AP_Mount: add second instance of mount

libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/MissionItemProtocol.cpp, libraries/GCS_MAVLink/MissionItemProtocol_Waypoints.cpp
Corrects a lack of space check on mission items. This leads to corrupted partial items being sent over the link, it's particularly noticeable if a UART is being kept extremely busy.
=> GCS_MAVLink: Check for mission space before sending items

Tools/autotest/arduplane.py, Tools/autotest/common.py, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
This allows us to drop any queued commands that may have arrived while we were calibrating. Rather then entering a second and unexpected calibration.
EDIT: Testing was done against mission planner with a cube orange over usb and using the level accel cal button (the param5==2 path). I don't have a GCS here that lets me test the simple_accel_cal path. If I sent commands within 5 seconds of it finishing it was rejected, if I waited they worked again.
EDIT2: `accelcalsimple` in mavproxy looks like it works as intended.
=> GCS_MAVLink: Rate limit blocking accel calibrations

Tools/environment_install/install-ROS-ubuntu.sh
This updates the install_ROS_ubuntu.sh script so that it uses [ArduPilot's ardupilot_ros repo](https://github.com/ArduPilot/ardupilot_ros) instead of @snktshrma's.
=> Tools: install_ROS_ubuntu points at ArduPilot repo

Tools/autotest/arducopter.py, Tools/autotest/autotest.py, Tools/scripts/build_ci.sh
travis had a split into two tests, test1 and test2 - which we no longer need
=> Tools: remove vestiges of travis autotest hooks

Rover/mode_dock.cpp
This restricts the vehicle speed in DOCK mode such that it stops _before_ the stopping distance instead of overshooting beyond it.
I have tested this on SITL and my real rover. It worked perfect in both the cases.
=> Rover: fix overshoot beyond stopping dist in dock mode

Tools/autotest/rover.py
The `delta` must be calculated from stopping point instead of the position of docking station.
@peterbarker Can you please have a look on this one?
=> Tools: fix Rover AutoDock test

Tools/autotest/arducopter.py
may fix flapping test @andyp1per
=> autotest: check context for expected esc-rpm statustext

Tools/autotest/antennatracker.py, Tools/autotest/arducopter.py, Tools/autotest/arduplane.py, Tools/autotest/ardusub.py, Tools/autotest/balancebot.py, Tools/autotest/common.py, Tools/autotest/helicopter.py, Tools/autotest/quadplane.py, Tools/autotest/rover.py, Tools/autotest/sailboat.py
We had a pattern emerging of using the test name as the method name to contain the actual test.  We also tended to duplicate the docstrings in the test description - or omit the docstring.
This uses reflection to retrieve both the test name and the description, meaning less duplication of this information and enforcing having docstrings on the test methods.
=> autotest: use reflection to collect test details

libraries/AP_Airspeed/Airspeed_Calibration.cpp, libraries/AP_Math/vector3.cpp, libraries/AP_Math/vector3.h, libraries/SITL/SIM_FlightAxis.cpp
After the bug fixed in #21237 I wondered if the same bug was in other places. It was also in SITL (in a rarely used location), so this renames the operator to row_times_mat() to make the bug less likely
=> Math: create row_times_mat()

Tools/autotest/common.py
We no longer permit the use of lambda functions in test lists
@khancyr FYI
=> autotest: remove syntax test for test lambdas

Tools/autotest/arducopter.py, Tools/autotest/arduplane.py, Tools/autotest/ardusub.py, Tools/autotest/balancebot.py, Tools/autotest/common.py, Tools/autotest/helicopter.py, Tools/autotest/quadplane.py, Tools/autotest/rover.py
This has been unused for a long time, and is getting in the way of reforms.  Its position as a test rather than as a part of a framework was always going to cause oddities, particularly after we split the Copter tests into several chunks.
=> autotest: remove disabled LogUpload test

Tools/autotest/arducopter.py, Tools/autotest/autotest.py, Tools/autotest/common.py
This attempts to simplify the way results are handled.
We need to preserve the creation of `self.fail_list` as the autotest.py script uses it when printing an overall test result summary.
=> autotest: create and use a Result object to ship failure data around

libraries/AP_Mount/AP_Mount_Gremsy.cpp, libraries/AP_Mount/AP_Mount_SToRM32.cpp, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/MAVLink_routing.cpp, libraries/GCS_MAVLink/MAVLink_routing.h
This is an alternative implementation of https://github.com/ArduPilot/ardupilot/pull/21658.  The changes are:
- GCS_MAVLink::find_by_mavtype_and_compid is added and used to more directly find the Gremsy (and SToRM32 mavlink) gimbals.  The advantage is that this skips the need for the two drivers to iterate through all the matching devices to find the one with the correct component id.  For this reason I prefer this solution to the original PR.
- SToRM32 mavlink driver requires the gimbal component id to be MAV_COMP_ID_GIMBAL, MAV_COMP_ID_GIMBAL2, etc.
Some SToRM32 users will need to re-configure their gimbals to use them with AP but this change is consistent with @olliw42's popular BetaPilot fork of AP.
This has been lightly tested on a Gremsy gimbal to confirm two gimbals could be …
=> GCS_MAVLink/AP_Mount: find_by_mavtype supports instance (attempt2)

libraries/AC_Fence/AC_Fence.cpp
Fixes https://github.com/ArduPilot/ardupilot/issues/17302. Just moves the clear above the early return so changing type to 0 will clear.
=> AC_Fence: always clear breaches

libraries/AP_ESC_Telem/AP_ESC_Telem.cpp, libraries/AP_ESC_Telem/AP_ESC_Telem.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/esc_rpm_scale.lua, libraries/AP_Scripting/generator/description/bindings.desc
This allows for vehicles with different numbers of poles per motor by running a lua script which adds a scale factor for ESC RPMs
=> Scripting: added set_rpm_scale ESC telem API

libraries/AP_Param/AP_Param.h, libraries/AP_Param/AP_ParamT.cpp
Moves param template functions into a new CPP file to save flash.
=> AP_Param: move complex AP_ParamT functions to cpp

libraries/AP_Arming/AP_Arming.cpp
Expose the option to all vehicles, I don't see a reason why it doesn't apply to all of them, and on plane I don't want these broadcast at me continuously.
Tested against plane.
=> AP_Arming: Expose ARMING_OPTIONS to all vehicles

Tools/autotest/autotest.py
I've confirmed the autotest server is adding the relevant command-line option.
This makes the autotest tool less dangerous; running without arguments causes all sorts of fun stuff to happen as we do the build binaries step.
=> autotest: fail if no steps supplied and not autotest server

AntennaTracker/GCS_Mavlink.cpp, ArduCopter/GCS_Mavlink.cpp, ArduPlane/GCS_Mavlink.cpp, ArduSub/GCS_Mavlink.cpp, Blimp/GCS_Mavlink.cpp, Rover/GCS_Mavlink.cpp
The Vcc field is duplicated (with more/better information) in `POWER_STATUS` and we don't populate `I2CErr` which means it's wasted. This leaves it in so it can be requested with a message interval, but removes it from the default stream groups to save bandwidth for the average user who hasn't delved into the specific messages they are seeing.
=> Don't send HWSTATUS by default

Tools/AP_Periph/AP_Periph.h, Tools/AP_Periph/can.cpp, Tools/AP_Periph/rc_out.cpp, libraries/AP_UAVCAN/AP_UAVCAN.cpp, libraries/AP_UAVCAN/AP_UAVCAN.h
This makes debugging CAN servo setups easier
=> CAN: support sending actuators as PWM

libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/generator/src/main.c
This fixes some of uint16's that were skipping checks, that would results in accepting any int32 and casting to uint16.
This limits skip checks to only floats, int32 and unit32. Then skips checks on all of those that allow the full range.
=> AP_Scripting: enforce skip check on correct types update description to match

libraries/SITL/SIM_FlightAxis.cpp
the rotation was backwards since https://github.com/ArduPilot/ardupilot/pull/21268
the previous code relied on a double error to get correct airspeed for tailsitters
=> SITL: fixed tailsitter airspeed in RF9

libraries/AP_OSD/AP_OSD.cpp, libraries/AP_OSD/AP_OSD_Backend.h, libraries/AP_OSD/AP_OSD_MSP_DisplayPort.cpp, libraries/AP_OSD/AP_OSD_MSP_DisplayPort.h
Thanks to @pbreed for catching this issue https://github.com/ArduPilot/ardupilot/issues/20955
Uart read access requires initialization in the OSD thread which was missing.
Without this fix the OSD thread could write but not read, so the MSP DisplayPort OSD was working but ArduPilot was not responding to telemetry data polls, as a side effect the VTX "sticks" menu was not working.
=> AP_OSD: fixed serial port initialization for MSP DisplayPort protocol

libraries/AP_Proximity/AP_Proximity.cpp, libraries/AP_Proximity/AP_Proximity.h, libraries/AP_Proximity/AP_Proximity_Utils.cpp
I am working on obstacle avoidance using multiple VL53l1X sensors, and I found that 
**PROXIMITY_GND_DETECT_THRESHOLD** is hardcoded to 1m although user may want to change it as in my case.
[https://youtu.be/w5PDfuFFKsI](https://youtu.be/w5PDfuFFKsI)
=> LIB: change PROXIMITY_GND_DETECT_THRESHOLD to param

ArduCopter/GCS_Mavlink.cpp, ArduCopter/GCS_Mavlink.h, Blimp/GCS_Mavlink.cpp, Blimp/GCS_Mavlink.h, Tools/AP_Periph/GCS_MAVLink.cpp, Tools/AP_Periph/GCS_MAVLink.h, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
These fields are only available in the message, so make this a handler where we pass through the message.
This PR also removes the empty override for Blimp.
```
Before:
STABILIZE> Got COMMAND_ACK: PREFLIGHT_REBOOT_SHUTDOWN: ACCEPTED
< COMMAND_ACK {command : 246, result : 0, progress : 0, result_param2 : 0, target_system : 0, target_component : 0}
After:
STABILIZE> Got COMMAND_ACK: PREFLIGHT_REBOOT_SHUTDOWN: ACCEPTED
< COMMAND_ACK {command : 246, result : 0, progress : 0, result_param2 : 0, target_system : 255, target_component : 230}
```
Note that our other `COMMAND_ACK`s already fill this in correctly - but rebooting is done specially.
=> Populate COMMAND_ACK with sysid/compid from received message

libraries/AP_HAL_SITL/HAL_SITL_Class.cpp, libraries/AP_HAL_SITL/Scheduler.cpp, libraries/AP_HAL_SITL/Scheduler.h
This structure was set up to mimic the should_exit code originally from the Linux HAL.  It runs contrary to the intent of the HAL reboot call, which is not expected to return.  This oddity leads us to emit wo acks sequentially, one success, one failure, which is just weird.
Since the original code was written we factored out that `actually_reboot` call which made this work.
=> AP_HAL_SITL: do not return from reboot command

libraries/AP_Motors/AP_MotorsMulticopter.cpp
A user had a typo in Q_M_SPIN_MIN, entering 0.8 instead of 0.08, leading to loss of an aircraft.
=> AP_Motors: added a SPIN_MIN check

libraries/AP_Logger/LogStructure.h
=> AP_Logger: Fix an error in the doc string for the MAVC message

libraries/AP_Airspeed/Airspeed_Calibration.cpp
Delete unused definitions.
If it's for future use, I don't think it's necessary.
=> AP_Airspeed: Delete unused definitions

Tools/autotest/bisect-helper.py
Same fix as #20235 for the exception handler.
=> Autotest: fixes bisect-helper for python 3.10

libraries/AP_Filesystem/AP_Filesystem.cpp, libraries/AP_Filesystem/AP_Filesystem.h, libraries/AP_Filesystem/AP_Filesystem_Mission.cpp, libraries/AP_Filesystem/AP_Filesystem_Mission.h, libraries/AP_Filesystem/AP_Filesystem_Param.cpp, libraries/AP_Filesystem/AP_Filesystem_Param.h, libraries/AP_Filesystem/AP_Filesystem_ROMFS.cpp, libraries/AP_Filesystem/AP_Filesystem_ROMFS.h, libraries/AP_Filesystem/AP_Filesystem_Sys.cpp, libraries/AP_Filesystem/AP_Filesystem_Sys.h, libraries/AP_Filesystem/AP_Filesystem_backend.h, libraries/AP_Filesystem/AP_Filesystem_config.h, libraries/AP_HAL_ChibiOS/sdcard.cpp, libraries/AP_Logger/AP_Logger.h, libraries/AP_Terrain/AP_Terrain.h, libraries/GCS_MAVLink/GCS.h
This should allow us to move `HAVE_FILESYSTEM_SUPPORT` to be renamed and defined in AP_Filesystem_config.h as `AP_FILESYSTEM_ENABLED`
=> Create and use AP_FILESYSTEM_x_ENABLED defines

libraries/AP_Scripting/AP_Scripting.cpp, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/generator/src/main.c, libraries/AP_Scripting/lua_bindings.cpp, libraries/AP_Scripting/lua_bindings.h
This adds a binding for multi byte read which is required for some i2c devices. 
This also clears any allocated i2c scripting devices when scripting is stopped. We have a limit of 4 devices so without clearing you only get a few restarts without running out.
=> AP_Scripting: i2c multi byte read

libraries/AP_InertialSensor/AP_InertialSensor_BMI270.cpp
The PANIC method writes a newline at the end of the string.
Therefore, I do not think that a newline is necessary for PAMIC.
This process is for debugging.
The contributor mistakenly thinks that a newline is required in the PANIC string.
I think there are some new contributors, too.
I want the code to be a model.
=> AP_InertialSensor: Remove line breaks from PANIC strings

libraries/AP_Mission/AP_Mission_Commands.cpp
The final RETURN of this method is the same regardless of whether MOUNT is enabled or disabled.
Therefore, it can be shared.
=> AP_Mission: Share the method RETURN

ArduCopter/AP_Arming.cpp, Tools/autotest/arducopter.py
I have tested the radio receiver not connecting to FC.
The "Throttle below failsafe" message is incorrect.
I added the message "Radio signal not received".
AFTER
BEFORE
=> Copter: Add a "RC not found" message

libraries/AP_HAL_SITL/HAL_SITL_Class.cpp
fill_count is a UINT8_T value.
Therefore, the next value after 255 will be 0 and will not be a 10-count cycle.
I will use 10-count cycles.
BEFORE
=> AP_HAL_SITL: Accurate 10 counts

Tools/autotest/rover.py
reboot will fail if we are still armed
=> autotest: correct reboot in failure case for dock mode test

ArduPlane/Parameters.cpp
Change to the ArduCopter doc style and add 0 = disable to the doc (what I was missing)
=> ArduPlane: add 0 disable to FLTMODE_CH parameter doc

libraries/AP_InertialSensor/AP_InertialSensor.h
The number of gyros and accelerometers are counted individually.
The method to get the gyro count should be changed to return the gyro count.
=> AP_InertialSensor: Allow gyro counts to be returned

libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Rotoye.cpp
The Rotoye battery monitor was not reporting temperature due to `_has_temperature` not being set. Also the external thermistor was set to the wrong register. The wrong register was confirmed using a hardware debugger. With this register the temperatures read then match the values seen on the OLED display.
@amilcarlucas  have you had issues with the temperature reporting? 
@echoGee is this the correct register for the external thermistor for your older models as well?
=> AP_BattMonitor: fix Rotoye Temperature Monitoring

libraries/AP_Mount/AP_Mount_Backend.h, libraries/AP_Mount/AP_Mount_SToRM32.cpp, libraries/AP_Mount/AP_Mount_SToRM32.h, libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp, libraries/AP_Mount/AP_Mount_SToRM32_serial.h, libraries/AP_Mount/AP_Mount_SoloGimbal.cpp, libraries/AP_Mount/AP_Mount_SoloGimbal.h
This fixes a bug in the Solo, SToRM32 MAVLink and (maybe) SToRM32 serial drivers that would cause the MNTx_DEFLT_MODE parameter to be ignored.
The user would set this parameter to the mode they would like the gimbal to be in after startup (e.g. RC_TARGETING) but it had no effect because these drivers override the set_mode() method so that it immediately returns if the gimbal is not yet "initialised".
The SToRM32_MAVLink gimbal, the gimbal is not "initialised" until the update() method has been called at least once and the find_gimbal() method has searched the mavlink routing tablet and found the gimbal (e.g. the gimbal must have sent at lesat one message to the autopilot)
There is no need to block setting the AP_Mount's driver's mode because this only controls the source of the angle …
=> AP_Mount: remove set_mode overrides to fix mode defaulting at startup

ArduCopter/AP_Arming.cpp, ArduPlane/AP_Arming.cpp, Tools/autotest/arducopter.py, libraries/AP_Motors/AP_MotorsMulticopter.cpp
Follow up to https://github.com/ArduPilot/ardupilot/pull/21635 this moves the PWM range check in to the AP_Motors pre-arm. ~The only disadvantage is we loose the param prefix, `MOT_` or `Q_M_`, we could add it back with a vehicle dependent define.~
=> AP_Motors: move PWM range check from copter and plane

libraries/SRV_Channel/SRV_Channel_aux.cpp
Currently if the first channel of a particular function is outside of the 40% to 60% limit the remainder of the channels are not checked. This could result auto trim not working with differential ailerons where travel in one direction is reduced by design.
=> SRV_Channel: adjust trim, check all channels for range limit

ArduPlane/Log.cpp, libraries/APM_Control/AP_SteerController.cpp, libraries/APM_Control/AP_SteerController.h, libraries/APM_Control/AP_YawController.h
Should result in a significant reduction in log size with full rate logging.
=> Plane: only log steer and yaw PIDs if there doing something

Tools/autotest/arducopter.py, Tools/autotest/common.py, libraries/GCS_MAVLink/GCS_Common.cpp
This is a PR about sending local neu home location in [HOME_POSITION](https://mavlink.io/en/messages/common.html#HOME_POSITION) MAVLink message.
Can be tested using: `./Tools/autotest/autotest.py build.Copter test.Copter.TestLocalHomePosition`
This helps to calculate the distance between the vehicle and home rather than the origin (calculating the euclidian distance between [HOME_POSITION](https://mavlink.io/en/messages/common.html#HOME_POSITION) and [LOCAL_POSITION_NED](https://mavlink.io/en/messages/common.html#LOCAL_POSITION_NED)).
=> Send local ned home location to GCS

libraries/AP_MSP/AP_MSP_Telem_Backend.cpp, libraries/AP_MSP/AP_MSP_Telem_Backend.h, libraries/AP_MSP/msp.h, libraries/AP_OSD/AP_OSD.h, libraries/AP_OSD/AP_OSD_MSP_DisplayPort.cpp, libraries/AP_OSD/AP_OSD_Screen.cpp
This adds
OSDn_HD_RES_EN to enable HD resoloution
OSDn_HD_FONT for HD font index selection
Notes:
- settings are per screen (future OSD fw will even allow the use of custom font tables)
- resolution refers to the size of text frame buffer not to the actual pixel resolution.
Latest HDZERO MSP DisplayPort firmware supports 2 text resolutions 30x16 and 50x18 switchable with MSP sub command 5
What follows is an example of the same OSD settings applied to 30x16 and 50x18, same coordinates draw on different screen positions due to higher resolutin.
Low resolution DisplayPort has 30 cols and 16 rows i.e. 30x16
High resolution DisplayPort has 50 cols and 18 rows i.e 50x18
=> AP_OSD: Added new per screen PARAMs for HD OSD options

libraries/AP_MSP/AP_MSP_Telem_Backend.cpp, libraries/AP_MSP/AP_MSP_Telem_Backend.h, libraries/AP_MSP/AP_MSP_Telem_DJI.cpp
**Issue**: while using MSP DisplayPort with a rooted DJI FPV Goggles (V1/V2) kit running the [msp-osd module](https://github.com/fpv-wtf/msp-osd) arming is not detected and the goggles do not exit low power mode
Both the default MSP telemetry backend and the MSP DisplayPort backend do not report arming status in the flight mode bitmask (BOXARM bit). Arming status is only reported in the "arming disarmed" flag which up to now seemed good enough.
The only backend that required the BOXARM bit to be set was the DJI one.
The PR changes this behaviour and sets the BOXARM bit for all backends (fortunately the BOXARM bit is the same for BF, INAV and DJI so this should not introduce new issues)
[betaflight BOXARM](https://github.com/betaflight/betaflight/blob/025ee87a7aca068e3659fd066b8a9afbed12336 …
=> AP_MSP: move arming status to MSP telemetry base class

libraries/AP_Vehicle/AP_Vehicle.cpp
The is_inactive() is unilaterally checked but only set in the throttle notch. On my 3" this was causing the notches to be disabled entirely
=> Make sure notches are not spuriously disabled when not using throttle notch

libraries/AP_InertialSensor/AP_InertialSensor.cpp, libraries/Filter/NotchFilter.cpp, libraries/Filter/NotchFilter.h
This PR constraints the maximum change allowed per-tick to the harmonic notch center frequency as a percentage of the old frequency. Experiments show that rapid changes to the center frequency can result in filter instability and cascading failures.
This works well and solves the problem on my 5" Beater with KakuteH7v2. Lower values prevent filter instability entirely at some cost to accuracy. Higher values allow more accurate tracking but can result in filter instability in extreme conditions, however this PR also prevents runaway instability.
Flying at 5% (0.05) gave less control in propwash due to the filter tracking less well. Flying at 10% (0.1) made it possible to provoke the issue but in a very subdued form. 7.5% (0.075) turned out to be a good compromise.
=> Harmonic notch slew limit

libraries/AP_HAL/Util.h, libraries/AP_HAL_ChibiOS/Util.cpp, libraries/AP_HAL_ChibiOS/Util.h, libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-SimOnHardWare/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/skyviper-f412-rev1/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/skyviper-journey/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450/hwdef.dat, libraries/AP_HAL_ESP32/Util.cpp, libraries/AP_HAL_ESP32/Util.h, libraries/AP_HAL_Linux/Util.cpp, libraries/AP_HAL_Linux/Util.h, libraries/AP_HAL_SITL/Util.cpp, libraries/AP_HAL_SITL/Util.h, libraries/AP_Logger/LoggerMessageWriter.cpp, libraries/AP_Radio/AP_Radio_cc2500.cpp, libraries/GCS_MAVLink/GCS_Common.cpp
EDIT: This started as a quick fix to improve the readability of QioTek board names in GCS banner messages, but Pete suggested a broader fix to allow for longer board names overall.
Discussion:
https://discuss.ardupilot.org/t/zealoth743-board-name-truncated-in-gcs-messages/86770
=> HAL_ChibiOS: increase short board names to 23 chars

libraries/AP_Mission/AP_Mission.cpp
Well, probably not initialised, but certainly holding values we don't want
=> AP_Mission: prevent use of uninitialised stack data

libraries/AP_VideoTX/AP_SmartAudio.cpp, libraries/AP_VideoTX/AP_SmartAudio.h, libraries/AP_VideoTX/AP_Tramp.cpp, libraries/AP_VideoTX/AP_VideoTX.cpp, libraries/AP_VideoTX/AP_VideoTX.h
Split from https://github.com/ArduPilot/ardupilot/pull/19497
correct settings when power set is received
add support for capturing all supported power levels learn power levels in SmartAudio 2.1
add better support for VTX power levels
don't set power to 0 if in pitmode
add option for iNav compatibility
support non-conforming SmartAudio implementations
re-enable pitmode on SmartAudio 2.0
add support for "blind" VTX setting
=> Add lookup tables for VTX power settings to fix many SmartAudio bugs

libraries/Filter/NotchFilter.cpp, libraries/Filter/NotchFilter.h
Harmonic notch frequency updates are done in the fast loop. This change prevents recalculation of notch coefficients if the effective frequency has not changed.
=> Optimize notch filter frequency updates when the requested frequency has not changed

Tools/autotest/common.py, libraries/AP_Mission/AP_Mission.cpp
This reverts https://github.com/ArduPilot/ardupilot/pull/21761 and just zeroes the frame field.
Surprisingly, the callers to this method fill some bits in before calling this method, so zeroing the packet breaks them.
Added a warning about this pitfall, and zeroes just hte field that wasn't being reset.
=> Explicitly zero frame field rather than entire packet

libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/generator/src/main.c
Alternate to https://github.com/ArduPilot/ardupilot/pull/21788
This corrects the binding descriptions to associate the skip check with the type rather than the access. It then adds a error to catch it being in the wrong place again.
=> AP_Scripting: fix userdata skip check

Tools/autotest/arduplane.py, libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h, libraries/AP_Airspeed/AP_Airspeed.cpp, libraries/AP_Airspeed/AP_Airspeed.h, libraries/AP_Airspeed/AP_Airspeed_Health.cpp, libraries/AP_Logger/LogStructure.h, libraries/AP_NavEKF3/AP_NavEKF3.cpp, libraries/AP_NavEKF3/AP_NavEKF3.h, libraries/AP_NavEKF3/AP_NavEKF3_AirDataFusion.cpp, libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp, libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp, libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.h, libraries/AP_TECS/AP_TECS.cpp
Refer to https://github.com/ArduPilot/ardupilot/pull/19883 for prior discussion of the issues
=> Airspeed Sensor Failure Handling Improvements

libraries/AC_Avoidance/AP_OADijkstra.cpp, libraries/AC_Fence/AC_Fence.cpp, libraries/AC_PrecLand/AC_PrecLand_StateMachine.cpp, libraries/AP_AccelCal/AP_AccelCal.cpp, libraries/AP_AccelCal/AP_AccelCal.h, libraries/AP_Camera/AP_Camera_Logging.cpp, libraries/AP_EFI/AP_EFI.cpp, libraries/AP_Follow/AP_Follow.cpp, libraries/AP_Mount/AP_Mount_Backend.cpp, libraries/AP_Mount/AP_Mount_Gremsy.cpp, libraries/AP_WindVane/AP_WindVane.cpp, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_config.h
A lot of places really only care that GCS is present or not.  This is a pattern we're generally adopting which helps avoid include loops.
=> Create and use GCS_MAVLink/GCS_config.h

libraries/AP_Filesystem/AP_Filesystem_Param.cpp
The actual filesize of the parameter downloadfile is around 15200 bytes. The indicated filesize is used in QGC for the progressbar. This patch does not try to compute the exact filesize but to do a better estimate. Only the full download is considered to avoid more complexity. So the actual fixed number is 1 MByte while the new estimation for 1350 parameters is 16200 bytes.
=> AP_Filesystem_Param: Better estimation of filesize

libraries/AP_Mission/AP_Mission.cpp
The jump tracking array in AP_Mission only initializes when the mission is restarted, for example when disarming or when the waypoint is set to zero. This means it is possible for that array to never initialize, e.g. if you use Set WP to set the waypoint to anything other than zero after boot but before switching to Auto mode the first time.
It seems like AP_Mission::init() is an appropriate place to call init_jump_tracking.
I encountered this on a quadplane that uses RTL_AUTOLAND. It usually takes more than 30s after boot for me to connect, so it switches to auto mode and sets the waypoint to the landing sequence. Before takeoff, I set the waypoint to 1. In flight, my DO_JUMP commands were not working.
It's really easy to work around: I just set waypoint to 0 now instead of 1, but this …
=> Initialize jump-tracking in AP_Mission::init()

ArduPlane/ArduPlane.cpp, ArduPlane/Plane.h, libraries/AP_Vehicle/AP_Vehicle.cpp, libraries/AP_Vehicle/AP_Vehicle.h
This fixes (again) the OSD VTOL view ;-)
It was originally authored by @Hwurzburg and broken by the "big quadplane refactoring" https://github.com/ArduPilot/ardupilot/pull/17941
=> ArduPlane: fixed roll and pitch for OSD VTOL view

ArduCopter/version.h, ArduPlane/version.h, Rover/version.h
This updates the version for Copter (including TradHeli), Plane and Rover to 4.4.0-DEV now that we have branched for 4.3.0-beta testing.
I have not updated AntennaTracker or Sub because we haven't branched for those releases yet.
=> Copter, Plane, Rover to 4.4.0-DEV

Tools/autotest/common.py
=> autotest: remove use of fstring

libraries/AP_Math/quaternion.h, libraries/AP_Mount/AP_Mount.cpp, libraries/AP_Mount/AP_Mount.h, libraries/AP_Mount/AP_Mount_Backend.cpp, libraries/AP_Mount/AP_Mount_Backend.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/mount-poi.lua, libraries/AP_Scripting/generator/description/bindings.desc
This Lua script example allows the user to more accurately determine the lat, lon and alt (above sea level) of the point in the center of the camera's frame.  E.g. the pilot can aim the camera at a point (on the ground) and pull an auxiliary switch high and the Location is then displayed on the ground station's messages tab.  The location is calculated using the vehicle's position, the gimbal's attitude and the terrain database.
I'm hoping to use this at the upcoming [Japan Inovation Challenge](https://japan-innovation-challenge.com/en/) to more easily determine the Lat, Lon, Alt of the mannequin
This can be tested in SITL by doing the following
- cd ardupilot/ArduCopter
- mkdir scripts
- cp ../Tools/libraries/AP_Scripting/examples/mount-poi.lua scripts
- ../Tools/autotest/sim_vehicle.py …
=> AP_Scripting: gimbal/mount POI example

ArduCopter/GCS_Mavlink.cpp, ArduPlane/GCS_Mavlink.cpp, ArduSub/GCS_Mavlink.cpp, Blimp/GCS_Mavlink.cpp, Rover/GCS_Mavlink.cpp, libraries/AP_RPM/RPM_SITL.cpp, libraries/AP_RPM/RPM_SITL.h
Tested in SITL using
```
--- a/Tools/ardupilotwaf/boards.py
+++ b/Tools/ardupilotwaf/boards.py
@@ -601,6 +601,8 @@ class sitl(Board):
cfg.define('AP_GENERATOR_RICHENPOWER_ENABLED', 1)
cfg.define('AP_OPENDRONEID_ENABLED', 1)
cfg.define('AP_SIGNED_FIRMWARE', 0)
+        cfg.define('AP_RPM_ENABLED', 0)
+        cfg.define('AP_ICENGINE_ENABLED', 0)
if self.with_can:
cfg.define('HAL_NUM_CAN_IFACES', 2)
```
=> Squelch warning about sending RPM mavlink message if RPM not compiled in

Tools/autotest/arducopter.py, Tools/autotest/rover.py, libraries/AP_HAL_SITL/UARTDriver.cpp, libraries/SITL/SIM_RF_NMEA.h, libraries/SITL/SIM_SerialDevice.cpp, libraries/SITL/SIM_SerialDevice.h
... and drops reads and writes if they don't match.
Example implementation for NMEA rangefinder is included.
=> SITL SerialDevice optionally checks baudrates match

ArduSub/sensors.cpp
This is harmless and prevents a "bounce-back" effect when the depth is badly calibrated. This can happen when rebooting the vehicle underwater without a proper depth calibration.
=> Sub: update baro calibration even if armed

libraries/AP_CANManager/AP_SLCANIface.cpp
this disables SLCAN if enabled using CAN_SLCAN_CPORT and SERIALn_PROTOCOL=22 when we are armed, to reduce load on the CAN thread from the very inefficient SLCAN processing
=> AP_CANManager: disable SLCAN when armed

Tools/autotest/arducopter.py, Tools/autotest/arduplane.py, Tools/autotest/common.py, libraries/AP_NavEKF3/AP_NavEKF3.cpp, libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp
This fixes an issue that happens with the following scenario:
- EK3_AFFINITY=1, giving GPS affinity
- EK3_SRC1_POSZ=3 using GPS altitude
- dual GPS enabled
- at startup the two GPS modules give different AMSL alt
- this causes XKF1[0].OH and XKF1[1].OH to differ by the GPS height difference
- the difference in AMSL alt between the GPS modules goes away before takeoff
- this causes XKF1.PD to compensate for the difference in origin
- takeoff copter in GUIDED mode
- we get a temporary glitch that causes a lane change
- on the new lane the reported above-origin alt changes, causing copter to change altitude (in the provided log it led to a crash)
This PR adds a test that reproduces the issue in SITL and also a fix so that the reported origin uses the public origin and getPosD() in EKF3 …
=> EKF3: fix EKF reported altitude against public origin

ArduCopter/mode.cpp
This PR allows `distance` field in [LANDING_TARGET](https://mavlink.io/en/messages/common.html#LANDING_TARGET) been used to slow down descend speed. 
It is tested with CubeBlack in RTL [2022-08-25 10-24-58.zip](https://github.com/ArduPilot/ardupilot/files/9542345/2022-08-25.10-24-58.zip)
Hi @kapacheuski , would you mind taking a look at this PR? Thank you very much
=> Copter: use 3d vector from plnd to slow down

Tools/scripts/build_options.py, libraries/AP_Camera/AP_Camera.cpp, libraries/AP_Camera/AP_Camera.h, libraries/AP_Mount/AP_Mount.cpp, libraries/AP_Mount/AP_Mount.h, libraries/AP_Mount/AP_Mount_Alexmos.cpp, libraries/AP_Mount/AP_Mount_Backend.h, libraries/AP_Mount/AP_Mount_Params.cpp, libraries/AP_Mount/AP_Mount_SToRM32.h, libraries/AP_Mount/AP_Mount_SToRM32_serial.h, libraries/AP_Mount/AP_Mount_Siyi.cpp, libraries/AP_Mount/AP_Mount_Siyi.h, libraries/AP_Mount/AP_Mount_SoloGimbal.h, libraries/RC_Channel/RC_Channel.cpp, libraries/RC_Channel/RC_Channel.h
This adds support for the Siyi ZR10 using its custom [serial protocol which is documented here](https://www.dropbox.com/s/7o08yt9r5g6mp0j/ZR10%20SDK%202022-9-19-randy-updated.docx?dl=0).  For reference there is a long [user discussion re this gimbal here](https://discuss.ardupilot.org/t/zr10-2k-qhd-30x-hybrid-zoom-gimbal-camera-siyis-first-industry-gimbal-camera-and-it-wont-be-the-last/86069/77).
The hardware connection is shown below:
ArduPilot configuration is:
- SERIALx_PROTOCOL = 8 (SToRM32) (where "x" is the serial port number connected to the gimbal)
- SERIALx_BAUD = 115
- MNT1_TYPE = 8 (Siyi)
- MNT1_PITCH_MIN = -90
- MNT1_PITCH_MAX = 25
- MNT1_YAW_MIN = -80
- MNT1_YAW_MAX = 80
- MNT1_RC_RATE = 90 (deg/s) to control speed of gimbal curing RC targeting
- RCx_OPTION = 163 (Mount Lock) …
=> AP_Mount: add Siyi gimbal driver

libraries/AP_Compass/AP_Compass.cpp, libraries/AP_Compass/AP_Compass.h, libraries/AP_Compass/AP_Compass_Backend.cpp, libraries/AP_HAL_ChibiOS/hwdef/HerePro/hwdef.dat
diagonals are no longer initialised to 1.0, which leaves us with zero compass after matrix mul
broken by this PR: https://github.com/ArduPilot/ardupilot/pull/21290
=> AP_Compass: fixed AP_Periph compass

libraries/AP_Mount/AP_Mount_Siyi.cpp
Enable conditions for debug output and variables for debug output in the debug definition.
Normal processing does not output debugging.
Enable when debug output is desired.
=> AP_Mount: Enable debugging outputs and variables in debug definitions

libraries/AP_Logger/AP_Logger_Block.cpp, libraries/AP_Logger/AP_Logger_Block.h, libraries/AP_Logger/AP_Logger_DataFlash.cpp, libraries/AP_Logger/AP_Logger_DataFlash.h, libraries/AP_Logger/AP_Logger_W25N01GV.cpp, libraries/AP_Logger/AP_Logger_W25N01GV.h
Dramatically increasing performance from about 140kbyte/s to 790kbyte/s
This works because during log download we basically read the same block a number of times before moving onto the next one.
=> Ensure that we don't read the same block more than once

libraries/AP_Scripting/examples/copter_alt_offset.lua
this was requested by a user that has GCS function for setting
ALT_OFFSET for magnetometer surveys
=> AP_Scripting: ALT_OFFSET example for copter

ArduPlane/commands_logic.cpp
This allows us to send a MAVLink (or mission) command to resume the tuned airspeed of the aircraft, without having to know the speed in advance. This is useful for allowing a GCS to send any aircraft back to it's normal flight state, without having any dependency upon understanding it's parameters.
This should probably wait until I get the proposed flag change into MAVLink before coming in, unless we want to just push forward with it. I've opened this now though to prompt discussion of it.
As a note, I didn't change anything functional in the normal airspeed case, I simply fixed a tab/space whitespace issue, and split the if line into 2 lines for readability. I would *really* like to remove the send text of "Set airspeed" though :) We have NACK's for a reason!
This was tested using SITL …
=> Plane: Allow reseting target airspeed to the parameter value

libraries/GCS_MAVLink/GCS.cpp, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
This removes individual member pointers for each of the mission types which we can transfer via the mission item protocol, instead using an array to store them.  This removes a chunk of code and we can iterate the list to work on all of the items in a loop rather than each pointer separately.
Also fixes the nesting problem found by @muramura here: https://github.com/ArduPilot/ardupilot/pull/21820
Also fixes a bug where if fence wasn't compiled in we wouldn't have rally or mission items.
=> GCS_MAVLink: remove individual static members for fence, mission and rally

ArduCopter/mode_loiter.cpp, ArduCopter/mode_poshold.cpp, ArduCopter/mode_sport.cpp
This is a simple clean up of Loiter, PosHold and Sport modes to make the state machine easer to read and understand.
No behaviour changes, just some moved code in the switch statement where each section starts and ends in a break.
=> Copter: Reorder Alt_hold state switch statement for clarity

ArduPlane/Parameters.cpp
NFC...questions came up in RCG about using negatives for downthrust
=> Plane: correct range for kff_thr_2_pitch

ArduCopter/mode.cpp
This "Mode change to AUTOTUNE failed: initialisation failed" message was split in two.
The split "led" was displayed on the MP's HUD.
One message is 50 bytes.
I will change the short name to flight mode.
I want to use 1 message for message display and voice notification.
AFTER
=> Copter: Message length within 50 bytes

Tools/AP_Periph/can.cpp
=> AP_Periph: correct build for EFI can

libraries/AP_HAL/RCOutput.cpp, libraries/AP_HAL/RCOutput.h, libraries/AP_HAL/tests/test_prescaler.cpp
There were several off-by-one errors in the use of prescalers for dshot and neopixel that affected both the clock generation and the testing. kudos to @bugobliterator for spotting this.
This PR cleans up the prescaler calculation and significantly tightens the testing regime.
=> Correct prescaler calculation and add testing debug

libraries/AP_InertialSensor/AP_InertialSensor_Logging.cpp
Firstly stops logging centre frequency of a fixed notch. Its just the frequency set in the params.
Secondly it splits logging into one message for per motor and one for other sorts. So ESC telem based logging, or FFT if configured,  will get the big message everything else will get the smaller. 
Main goal is to stop logging 11 zeros at 25hz for static, throttle or RPM based, there is no way to disable this log message so this at least makes it smaller most of the time.
=> AP_InertialSensor: Logging: only log single notch frequency unless per-motor, never log fixed

libraries/AP_Compass/AP_Compass.cpp, libraries/AP_Compass/AP_Compass.h, libraries/AP_Compass/AP_Compass_Calibration.cpp, libraries/AP_Compass/AP_Compass_config.h
The fix is really just to move a `#endif` down.
This also lets any board be compiled without diagonals.  Saves 368 bytes on CubeOrange ~~ - 'though I haven't tested it on HW ~~ .  Calibration works about as well as it does on master, which is "not really".
I've tested this patch with diagonals both enabled and disabled on CubeOrange.  Works like master.
Haven't tested this on AP_Periph - except to make sure that `f103-QiotekPeriph` now compiles.
=> AP_Compass: correct compilation when COMPASS_MAX_INSTANCE>1 and no diagonals

Tools/ardupilotwaf/chibios.py, Tools/scripts/uploader.py, libraries/AP_HAL_ChibiOS/hwdef/common/malloc.c, libraries/AP_Scripting/lua/src/lauxlib.c, libraries/AP_Scripting/lua/src/lauxlib.h, libraries/AP_Scripting/lua/src/lstate.c, libraries/AP_Scripting/lua/src/ltablib.c, libraries/GCS_MAVLink/GCS_FTP.cpp
With the 11.3 compiler we gain about 6.5k of flash on 2M boards. It also found some bugs. The key bug was two places in lua where it tried to use clock() and time() to get a random number, which actually gave constants.
This may well impact performance of the heap in lua
We need to flight test builds with the 11.3 compiler to see if we can switch to it for 4.4.x
=> build: fixed stm32 build with g++ 11.3

.github/workflows/test_chibios.yml, Tools/AP_Bootloader/mcu_f4.h, Tools/AP_Bootloader/mcu_h7.h, Tools/AP_Bootloader/support.cpp, Tools/AP_Bootloader/support.h, Tools/scripts/build_bootloaders.py, Tools/scripts/build_ci.sh, libraries/AP_HAL_ChibiOS/hwdef/MatekF405-bdshot/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/Pixhawk1-1M/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/Pixhawk1/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/common/stm32_util.c, libraries/AP_HAL_ChibiOS/hwdef/common/stm32_util.h, libraries/AP_HAL_ChibiOS/hwdef/fmuv2/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/fmuv3/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro-bdshot/hwdef.dat, libraries/AP_Vehicle/AP_Vehicle.cpp, libraries/AP_Vehicle/AP_Vehicle.h
This adds a warning when running a firmware meant for 2M boards on a board with 1M flash. This can happen if you have an old enough bootloader that it doesn't limit flash size to 1M. This is sent at level CRITICAL so it displays on the HUD:
the PR also adds an INFO warning every 30s if you are running a 1M firmware on a board that can use 2M. Sending as INFO means it just shows in the messages tab:
=> ChibiOS: added warnings for incorrect 1M/2M firmware

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/winch-test.lua, libraries/AP_Scripting/generator/description/bindings.desc
This adds bindings and documentation allowing Lua scripts to control a winch.
An example script is also included that raises or lowers the winch at configurable rates using an auxiliary switch or a servo **output** (see explanation below).
I require this functionality for an [upcoming search and rescue event](https://japan-innovation-challenge.com/en/) which stipulates the pilot must remotely operate the vehicle from >4km away.  My team will use the 3G/LTE mobile phone network, Mission Planner and a Real Flight joystick to control the vehicle.  The issue is that, like many joysticks, the RealFlight joystick only has 5 channels with full range meaning we do not have an RC channel free to set the winch deploy/retract rate.
The example script gets around this issue by allowing the user to …
=> AP_Scripting: add winch binding and example script

ArduPlane/quadplane.cpp
Fixed a bug where when Q_GUIDED_MODE was set to 1 and you attempted to change to GUIDED a divide by zero exception occurred. This issue would occur because the next and current waypoints were set to be the same and attempting to get the vector norm between the two waypoints would be a divide by zero.
Changed so that the distance between waypoints is checked before computing the norm of the vector
=> Plane: Fixed divide by zero error when changing to GUIDED

Tools/AP_Bootloader/board_types.txt
Added a line in board_types.txt to reserve the board ID 1081 for the JHEMCU GF16 F405
=> AP_Bootloader: reserve board ID for JHEMCUGF16F405

Tools/ardupilotwaf/chibios.py
Turns out Windows python.exe v3.10.x works fine when using WSL2 for build --upload. I must have had something funny in my python setup when I was testing that originally.
=> Tools: remove warning for WSL2 --upload on python.exe 3.10.x

libraries/AP_Airspeed/AP_Airspeed.cpp, libraries/AP_Airspeed/AP_Airspeed_Backend.cpp, libraries/AP_Airspeed/AP_Airspeed_Backend.h, libraries/AP_Airspeed/AP_Airspeed_UAVCAN.cpp, libraries/AP_Airspeed/AP_Airspeed_UAVCAN.h
persist DEVID and use it to ensure that we keep the order of DroneCAN sensors between boots. It still allows for a sensor to be swapped out for a new one, while keeping slot of the one that hasn't been removed
=> AP_Airspeed: use DEVID to maintain lineup of CAN sensors

libraries/AP_TECS/AP_TECS.cpp
Does what it says on the tin. We stop calling the `update_50hz` function if not in a auto throttle mode, in that case we end up with a big gap and should reset the filter.
From a TECS point of view we might be better to just always call the update function so there is never a need to reset. It would be even nicer if the AHRS could provide the filtered heights and accelerations calculated in this function.
=> AP_TECS: reset vdot filter if not been called

Tools/autotest/test_build_options.py, Tools/scripts/build_ci.sh, Tools/scripts/build_options.py, libraries/AP_RPM/AP_RPM.cpp, libraries/AP_RangeFinder/AP_RangeFinder_SITL.cpp, libraries/AP_RangeFinder/AP_RangeFinder_SITL.h, libraries/AP_UAVCAN/AP_UAVCAN.cpp, libraries/SITL/SIM_AirSim.cpp, libraries/SITL/SIM_Aircraft.cpp, libraries/SITL/SIM_Aircraft.h, libraries/SITL/SITL.cpp, libraries/SITL/SITL.h
Adds a feature to `test_build_options.py` which disables all features *except* one feature and its dependencies.
This PR also contains fixes for various problems found by this new test - mostly build_options.py dependencies, but also some transitive-include bugs.
=> Correct compilation when most features out, one in

ArduPlane/quadplane.cpp, ArduPlane/transition.h
Because we set the TECS pitch limit after we have already got the pitch output in the first loop after starting to transition to forward flight we were getting one step where it was not applied. This results in a ugly twitch. 
Master:
This PR:
So the TECS output is unchanged in that first step, but we now enforce the desired pitch to the intended limit.
We still have a aggressive snap to 0 deg and then to 3 deg (Q_TRAN_PIT_MAX) as the pitch limit expands, which could be improved. But we no longer pitch past 0 and the back up again.
=> Plane: Quadplane: SLT: enforce TECS pitch limits to beat race

libraries/AP_Common/Bitmask.h, libraries/AP_Relay/AP_Relay.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/aux_cached.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/RC_Channel/RC_Channel.cpp, libraries/RC_Channel/RC_Channel.h, libraries/RC_Channel/RC_Channels.cpp
This allows for scripts to implement aux functions. This complements the new Aux Function tab in MissionPlanner, allowing for scripts to implement aux functions via DO_AUX_FUNCTION in mavlink or missions or via rc switches
It also adds a binding for scripts to read relay state
=> AP_Scripting: added get_aux_cached()

ArduPlane/GCS_Mavlink.cpp, ArduPlane/mode.h, ArduPlane/mode_guided.cpp
mavlink change: https://github.com/ArduPilot/mavlink/pull/240
Replaced https://github.com/ArduPilot/ardupilot/pull/19297
This adds an adjustable radius for Guided mode vis the . This does not effect any other vehicle since the concept of radius does not apply to any vehicle that has a guided mode.
It's fully backwards compatible to existing command.
param3: was unused, now it's the positive-only radius. Ignore if <= 0
param4: controls radius, as stated in existing mavlink spec. Added option to ignore yaw if not == 0 or == 1.
This also lays the groundwork to easily add a new param GUIDED_LOIT_RAD in the future [which is requested](https://github.com/ArduPilot/ardupilot/pull/19297#issuecomment-1002163538) by @pompecukor
Behavior:
when entering guided mode, it uses WP_LOITER_RAD like usual. …
=> Plane: Add radius to MAV_CMD_DO_REPOSITION

libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp, libraries/AP_InertialSensor/AP_InertialSensor_Invensense.h
There have been numerous reports of ICM20602 sensor showing temp reset message and reseting FIFO. It has been found that although the Temperature data is invalid, the rest of the data in FIFO is valid. The data was collected with FIFO disabled, and still occasional invalid Temperature data was observed.
=> Disable temperature based fifo check on ICM20602

libraries/AP_Notify/AP_Notify.cpp
The default is -1 - disabled - but we don't have that in the documentation...
=> AP_Notify: correct NTF_BUZZ_PIN documentation

libraries/AP_Button/AP_Button.cpp, libraries/RC_Channel/RC_Channel.cpp, libraries/RC_Channel/RC_Channel.h
This adds instance to aux function prints:
```
RC6: MotorEStop HIGH
```
Of course one should know which switch one has toggled, but this is useful for setup if there are multiple switchs doing one thing.
This also adds the aux pos and button index to the same button print.
```
Button 1: executing (ParachuteRelease HIGH)
```
I find these prints extremely useful, especially when getting up-to speed with someone else's setup and pre-flight radio checks. I'm tempted to remove the requirement for having the name string and just print the function number in that case. 
EG if we did not have the `MotorEStop` string in our table you would get:
```
RC6: Option 31 HIGH
```
In that case It would probably also make sense to only print if `run_aux_function` returns true for a valid option. We would …
=> RC: Button: add instance to aux function prints

Tools/autotest/quadplane.py
we need to use quadplane-ice or plane-ice to get a simulated IC engine the test was just using an electric motor
=> autotest: fixed ICE tests to use an IC engine

libraries/AP_ESC_Telem/AP_ESC_Telem_SITL.cpp, libraries/AP_HAL_SITL/SITL_State.cpp, libraries/AP_InertialSensor/AP_InertialSensor_NONE.h, libraries/AP_InertialSensor/AP_InertialSensor_SITL.cpp, libraries/AP_InertialSensor/AP_InertialSensor_SITL.h, libraries/AP_RPM/RPM_SITL.cpp, libraries/AP_Vehicle/AP_Vehicle.cpp, libraries/Filter/HarmonicNotchFilter.cpp, libraries/Filter/HarmonicNotchFilter.h, libraries/SITL/SIM_Aircraft.cpp, libraries/SITL/SIM_Aircraft.h, libraries/SITL/SIM_FlightAxis.cpp, libraries/SITL/SIM_Frame.cpp, libraries/SITL/SIM_JSBSim.cpp, libraries/SITL/SIM_Multicopter.cpp, libraries/SITL/SIM_Multicopter.h, libraries/SITL/SIM_Plane.cpp, libraries/SITL/SIM_QuadPlane.cpp, libraries/SITL/SIM_QuadPlane.h, libraries/SITL/SIM_XPlane.cpp, libraries/SITL/SITL.cpp, libraries/SITL/SITL.h
This fixes a bug in handling non-contiguous motor sets introduced by this PR:
https://github.com/ArduPilot/ardupilot/pull/21370
In quadplanes it is common for the ESCs to be on motors 5-8 or 9-12, plus a fwd motor on output 3 (SERVO3)
The above PR broke this by assuming that all motors were contiguous starting at index 0
This PR also makes it possible to test this setup in SITL, by converting SITL to using a 32 bit mask of which outputs are motors instead of a starting index and count. That matches the way real aircraft are setup.
It also fixes the assumption that all ESCs are in AP_Motors. In quadplanes some of the motors can be not managed by AP_Motors. I changes the harmonic notch filter to allow expansion of the number of filters which allows for ESCs to be outside of AP_Motors, or …
=> Filtering: fixed non-contiguous ESC telemetry motor sets

libraries/AP_Scripting/AP_Scripting.cpp
Another PR that doesn't fix the scripting issue.
=> AP_Scripting: set lua nullptr after delete

ArduPlane/quadplane.cpp, ArduPlane/quadplane.h, libraries/AC_AttitudeControl/AC_AttitudeControl.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/APM_Control/AP_PitchController.h, libraries/APM_Control/AP_RollController.h, libraries/AP_AHRS/AP_AHRS_Logging.cpp, libraries/AP_AHRS/LogStructure.h
During POSITION1 we still have significant airspeed and using the VTOL Q_A_ANG_P gain may be too high when the fixed wing controller is still dominant and the fixed wing time constant equates to a much smaller angle P gain.
When tuning the VTOL controller we tune in hover, with low airspeed and correspondingly low fixed wing control. It is really not surprising that when we use those gains at high airspeed in POSITION1 that we sometimes see P gain oscillation
This is a simple change to keep using the fixed wing angle gains until we get to the POSITION2 state
=> Plane: scale angle gains in POSITION1 state with airspeed

libraries/AP_GPS/AP_GPS_NOVA.cpp, libraries/AP_GPS/AP_GPS_NOVA.h
There's an error with the init blob for novatel in that it sends 3 different configuration strings for psrdop, which conflict with each other. If using actual Novatel hardware what you end up getting is a single DOP message once while doing the configuration, and then no more DOP messages. While I like onchanged for the dop message the best, it wasn't clear to me that all the other vendors would suppoprt it, so I consolidated on 5Hz updates for it.
This also corrects an error with the horizontal accuracy estimate. It was just splitting the difference between the  east/west and north/south error. However these terms are actually defining something more like an ellipse. Doing the pathagorean distance gives a more accurate (IE: reduces the over estiamte of accuracy) result, and makes us …
=> AP_GPS: Fix novatel driver to handle DOP correctly, and fix overly optimistic horizontal accuracy estimate

Tools/autotest/common.py, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
this fixes a problem where a GCS must know that a message isn't sent by default if they want to set it back to its default rate
The test changes fail before the patches are applied and work afterwards.
Fix to the mavlink return code while we're at it.
=> GCS_MAVLink: fix set-default-rate of a message we don't send by default

libraries/AP_InertialSensor/AP_InertialSensor_BMI088.cpp, libraries/AP_InertialSensor/AP_InertialSensor_BMI088.h
Original BMI088 has 24G range so scale has a 24.0 multiplier within read_fifo_accel. Added a class variable RANGE which is assigned the correct value when the sensor type is received (16.0 or 24.0) - at accel_init().
=> Fix BMI085 scaling issue

libraries/AP_RCProtocol/AP_RCProtocol.h, libraries/AP_SerialManager/AP_SerialManager.cpp
Currently last past the post wins which is almost certainly not what the user expects or wants. This also attempts to print out a warning about the duplicate definition.
=> Use first defined RCIN serial port

.github/workflows/test_scripting_docs.yml, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/generator/src/main.c, libraries/AP_Scripting/tests/docs_check.py
This adds a check that scripting docs are upto date. It re-generates the docs using the generator and then spots the difference between the current docs and the generated ones. It ignores argument names and comments.
This should currently fail because there is a bunch of stuff missing. It will also fail because there is no definition for the expected number of arguments for manual bindings, this will also need to be added. 
Could expand further in the future to also check fields, argument/return types.
=> CI: add Scripting docs check

libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.cpp
This fixes vtol view roll and pitch telemetry data, reported values now match mavlink and OSD.
Depends on https://github.com/ArduPilot/ardupilot/pull/21783
=> AP_Frsky_Telem: fixed roll and pitch for VTOL view

ArduCopter/GCS_Mavlink.cpp, ArduPlane/GCS_Mavlink.cpp, Rover/GCS_Mavlink.cpp
requested by MAVLink perpheral user to help understand which rates to set
update Copter and added data to Plane and Rover params appropriately for each vehicle as spec'd in their static const constructs
=> Update SRX metadata

libraries/AP_AHRS/AP_AHRS.cpp
Callers of the AHRS::pre_arm_check() method prefix the returns string with "AHRS:" so we don't need again.
Below is a screen shot of a test in SITL after setting AHRS_EKF_TYPE = 2
=> AP_AHRS: pre-arm msg loses extra AHRS prefix

libraries/GCS_MAVLink/GCS_Common.cpp
Many of these mthods are calling another method which has no body when HAL_VISUALODOM is false
=> GCS_MAVLink: remove more methods based on HAL_VISUSALODOM_ENABLED

libraries/AP_InternalError/AP_InternalError.cpp
a user recently had a flow of control panic in quadplane in cygwin/missionplanner SITL. The panic this caused means we don't get logging information on what line of code was triggered
the panic in SITL for internal errors is only useful if you have debug information and can then attach a debugger. Without debug information it is much better to behave the same as a real vehicle and report an internal error (with line number)
=> AP_InternalError: only panic in SITL if debug enabled

Tools/scripts/decode_devid.py, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Baro/AP_Baro.cpp, libraries/AP_Baro/AP_Baro.h, libraries/AP_Baro/AP_Baro_Backend.h, libraries/AP_Baro/AP_Baro_MS5611.cpp
some vendors are using MS5607 instead of MS5611 in "Pixhawk 2.4" boards. The pressure is off by about 2x, but there is no register to distinguish between the two. This causes severe problems with airspeed calibration and height estimate
this adds a GPS alt arming check, and an option to treat MS5611 as MS5607
=> Baro: cope with MS5607 substitution for MS5611 in "Pixhawk 2.4.x"

libraries/GCS_MAVLink/MissionItemProtocol_Fence.cpp
7/8 into array range bracket will be integral type, therefore 7/8 is reported as always 0.
=> GCS_MAVLink: fix always 0 division.

libraries/AP_NavEKF3/AP_NavEKF3.cpp, libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.h
this fixes a bug introduced in #21834
this fix in #21834 was correct for getPosD, but should not have been applied to getLLH
this caused cruise mode in plane to descend/ascend by the difference between the public and local origins on mode entry
fixes #21984
=> AP_NavEKF3: fixed getLLH alt for local origin height

ArduCopter/mode_auto.cpp, ArduPlane/commands_logic.cpp, Rover/mode_auto.cpp, libraries/AP_Common/float16.cpp, libraries/AP_Common/float16.h, libraries/AP_Mission/AP_Mission.cpp, libraries/AP_Mission/AP_Mission.h
This is an experiment in using a float16 type in AP_Mission storage. It would allow us to store more parameters in the fixed 10 bytes (or 12 for mission command IDs below 256)
In this example NAV_SCRIPT_TIME is able to store an extra two parameters. Due to the use of MISSION_ITEM_INT those two parameters need to be integers
update: I initially meant this just to be a demo of using float16, but after discussions with @rmackay9 I think we could merge this. It would break the mission format for people with NAV_SCRIPT_TIME in missions, but that might be acceptable given small number of users
update: now added a mechanism to auto-convert the structure format to cope with existing stored missions
=> Use Float16_t in AP_Mission

ArduPlane/Attitude.cpp
don't reset yaw rate controller continuously while we are trying to use it. This prevented yaw autotune
=> Plane: fixed yaw rate tuning in AUTOTUNE mode

ArduPlane/system.cpp
when we are in a fence breach we by default disallow mode changes, but we need to allow for the switch to AUTO if the reason is we are entering a landing sequence, which is part of the RTL process which is the fence action
this bug was introduced in 4.3.0
=> Plane: allow mode switch on fence breach for RTL_AUTOLAND

Tools/AP_Periph/can.cpp, Tools/scripts/build_options.py
can_printf() to send longer strings using multiple packets.
Sends multiple debug_LogMessage packets if the fmt string is too long.
=> AP_Periph: can_printf() to send longer strings using multiple packets

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
That new bindings are needed for my still running script RelocateMission.lua that is nearly identical in function to the PR in cpp for 1MB boards without scripting https://github.com/ArduPilot/ardupilot/pull/21363
=> bindings.desc: bindings for RelocateMission.lua

libraries/AP_Arming/AP_Arming.cpp
Currently the various LED lua scripts cause arming failures. This is because the scripting funciton is just used as a label to assign a LED channel.
For example from LED_roll.lua:
```
--[[
use SERVOn_FUNCTION 94 for LED. We can control up to 16 separate strips of LEDs
by putting them on different channels
--]]
local chan = SRV_Channels:find_channel(94)
if not chan then
gcs:send_text(6, "LEDs: channel not set")
return
end
-- find_channel returns 0 to 15, convert to 1 to 16
chan = chan + 1
-- initialisation code
serialLED:set_num_neopixel(chan,  num_leds)
```
Bug report on facebook:
https://www.facebook.com/groups/ArduPilot.org/permalink/5810753962281082/
"On my Hexsoon EDU-450, I've set up the LED's according to the instructions but get this warning when I try to arm. It's clearly not a …
=> AP_Arming: allow scripting channels to be disabled

libraries/SRV_Channel/SRV_Channel.cpp
When changing output function from disabled to scaled output `high_out` is zero until we call `update_aux_servo_function` which is done a a lower rate than the outputs. So we end up with a divide by 0 for a few loops. 
`pwm_from_range` already checks for `high_out` of 0.
https://github.com/ArduPilot/ardupilot/pull/21347 (although I suspect setting a function to scaled output is not the only way to hit this.)
Found when checking we can do full range servo for https://github.com/ArduPilot/ardupilot/issues/22011
=> SRV_Channel: pwm_from_angle: return trim for 0 high_out

ArduCopter/failsafe.cpp, ArduPlane/ArduPlane.cpp, Rover/failsafe.cpp, Tools/autotest/common.py, libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.cpp, libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.h
We now have a singleton which all Plane, Rover and Copter all use - so use that singleton in AFS.
I tidied the AFS test and checked it under Copter (needs a few not-included hacks as AFS isn't enabled on Copter by default).
Also removes code in lieu of calling a method which does exactly the same thing.
Note the equivalent behaviour to the old code - if you don't have fence compiled in then you won't breach the geofence, even if your AFS parameters say "check the geofence".  Note the same parameter gates checking the qnh altitude limit, however.
=> Remove passing of fence state into AFS

Rover/Rover.cpp, libraries/AP_Vehicle/AP_Vehicle.cpp
Because the FFT* and HNTCH* parameters are exposed to the user, it makes sense to enable the feature.
I've had some preliminary success using the filter on a combustion-engined Rover with both a fixed notch filter as well as dynamic/FFT based updates.
Recommend that users increase SCHED_LOOP_RATE beyond the default 50Hz for effective dynamic frequency following.
Throttle based updates may be awkward on skid-steered vehicles because the motors may be at differing output states, but we can only follow one throttle output (that being `AR_Motors::get_throttle()`).
=> Rover: enable HNTCH

libraries/AP_Notify/RGBLed.cpp, libraries/AP_Notify/RGBLed.h
... also remove some `virtual` designators where they're not over-rtidden
=> AP_Notify: use existing method for setting rgb and rate

libraries/GCS_MAVLink/GCS_Common.cpp
Right now we only add and subtract multiples of 20 to stream_slowdown_ms - but this is a bear-trap.
=> GCS_MAVLink: correct potential uint underflow n stream slowdown

ArduCopter/mode.h, ArduCopter/mode_turtle.cpp
This adds a couple of safety features to turtle mode:
- You now will not be able to enter turtle mode unless the throttle is at zero
- When you enter turtle mode the motors stay disarmed but the notfiy LEDs flash
- When you raise the throttle the motors arm, when you lower the throttle the motors disarm
- You can only spin up the motors with the throttle raised
Fixes #22005
=> Add turtle mode safety features

ArduPlane/ArduPlane.cpp, ArduPlane/Attitude.cpp, ArduPlane/Plane.h, ArduPlane/commands_logic.cpp, ArduPlane/mode_cruise.cpp, ArduPlane/mode_loiter.cpp, ArduPlane/servos.cpp, libraries/AP_Scripting/examples/Aerobatics/Trajectory/README.md, libraries/AP_Scripting/examples/Aerobatics/Trajectory/plane_aerobatics.lua, libraries/AP_Scripting/examples/Aerobatics/Trajectory/view_paths.py
this re-implements tricks on a switch with the new accurate trajectory tracking code.
It adds new parameters:
- TRIK_ENABLE=0/1
- TRIK_COUNT for number of tricks
- TRIK_ACT_FN for the rc option to use to activate tricks (default 300)
- TRIK_SEL_FN for the rc option to use to select which trick (default 301)
So if you want to use a 3 position switch on RC7 to activate and use a knob on RC8 for selection then you would set:
- RC7_OPTION = 300
- RC8_OPTION = 301
then if tricks are enabled the following parameters are created per trick:
- TRIKn_ID
- TRIKn_ARG1
- TRIKn_ARG2
- TRIKn_ARG3
- TRIKn_ARG4
You can have a maximum of 11 tricks.
The ID numbers are from the trajectory table. The arguments are path specific.
=> AP_Scripting: implement tricks on a switch on top of trajectory tracking

libraries/AP_Scripting/examples/Aerobatics/Trajectory/plane_aerobatics.lua, libraries/AP_Scripting/lua/src/lstring.c
rework aerobatics script to make objects fall out of scope to allow gc to do its job on low memory
=> AP_Scripting: greatly reduce memory in aerobatic scripting

libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp, libraries/AP_InertialSensor/AP_InertialSensor_Invensense.h
This is to resolve a potential bug on ICM20602 where data on all sensor modules randomly jumps to a very high offset. The fix seems to be doing a FIFO reset via USER_CTRL register.
=> AP_InertialSensor: add fast reset for ICM20602 instead of full reset on bad temp sample

libraries/APM_Control/AP_RollController.h
Pulled out of https://github.com/ArduPilot/ardupilot/pull/22023/files to simplify it
=> APM_Control: remove unused methods

libraries/AP_HAL/AP_HAL_Boards.h
Swiped from https://github.com/ArduPilot/ardupilot/pull/22054
=> AP_HAL: add a sanity check that we don't minimize features on a 2MB board

libraries/AP_OSD/AP_OSD_Screen.cpp
=> AP_OSD: fix error in stats screen introduced in #18396

libraries/AP_Scripting/examples/Aerobatics/Trajectory/README.md, libraries/AP_Scripting/examples/Aerobatics/Trajectory/plane_aerobatics.lua
- Corrected scale figure eight with -ve radius
- Changed Immelmann turn to roll rate / length scaling with radius
- Added Derry turn
- Added F3C Scale schedule example - not complete - requires barrel roll
- Added to test suite
- F3A P23 example maneuver positioning updated (to suit F3A model flying @ 150m using the full box) 
- Clubman schedule positioning updated to suite clubman type model. Still requires stall turn.
=> Aerobatics trajectory script edits

libraries/AP_Scripting/generator/src/main.c, libraries/AP_Scripting/lua_bindings.cpp
A number of efficiency improvements that each save a bit of flash. 32c27e06886e214579f0ffd58691a6b8a79d26fb and b134eacf82ccfe8f73b88cca44440ab994acef6e make up the majority of the saving.
The best way to review is probably a compare of the generated bindings before and after. 
There is still some more that could be saved, but its getting harder to find.
=> AP_Scripting: generation flash savings

libraries/AC_Sprayer/AC_Sprayer.h, libraries/AP_Camera/AP_RunCam.h, libraries/AP_Gripper/AP_Gripper_config.h, libraries/AP_HAL_ChibiOS/hwdef/KakuteF7/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/MatekF405-CAN/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/OMNIBUSF7V2/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/include/minimize_features.inc
The two hwdefs modified also include minimize_features.inc so the defines are redundant there.
=> Move sprayer, gripper and runcam defines into minimize_features.inc

Tools/AP_Bootloader/bl_protocol.cpp, Tools/AP_Bootloader/support.cpp, Tools/AP_Bootloader/support.h, Tools/scripts/uploader.py
I pulled target power once while flashing firmware, which lead to corrupting the ECC on flash. The bootloader contains an optimization to not erase an already empty flash page. Unfortunately to verify this it has to read it, which then fails the ECC check and results in a fault. This PR adds a path to the bootloader protocol that skips the check for empty flash and instead just always erases the flash. It is dependent upon the uploading software to select the force erase path, but it at least provides a fallback way to recover boards without JTAG.
Tested on CubeOrange.
=> Allow force erasing flash on F7/H7 boards

libraries/AP_BoardConfig/AP_BoardConfig.cpp, libraries/AP_HAL_ChibiOS/RCOutput.cpp
fix for boards that have both FMU safety switch and IOMCU
=> HAL_ChibiOS: fixed BRD_SAFETY_MASK 

Tools/scripts/size_compare_branches.py, libraries/AP_HAL_ChibiOS/hwdef/skyviper-f412-rev1/hwdef.dat
- can test a cross-product of boards and vehicles
- has options for all boards and all vheicles
- now takes current branch as branch to test, rather than requiring `--branch`
- now tests the merge base of the supplied and master branches, rather than the two branches directly
- add an option to not run elf_diff
- emits a CSV file while working and CSV end of run
=> Add features to size_compare_branches.py

ArduPlane/commands_logic.cpp, libraries/AP_HAL_SITL/SITL_State.cpp, libraries/AP_Scripting/examples/Aerobatics/Trajectory/plane_aerobatics.lua, libraries/SITL/SIM_FlightAxis.cpp, libraries/SITL/SIM_FlightAxis.h
- cope with timing glitches in RealFlight
- fixed aborting trick on mode change
- fixed cygwin timing with lua scripts
- fixed thread performance at high SITL speedups
The cygwin change allows cygwin to run with high speedups. When SIM_SPEEDUP>2 the cpu will run flatout, which is needed as sleeps have much too high granularity. So users will notice their CPUs are pegged, but they will also achieve high speedups
@peterbarker changing the usleep from usleep(1000) to usleep(1000/speedup) helps things quite a lot at high speedups (on linux). But it breaks the dataflash erase test test.CopterTests2b.DataFlashErase. Any idea why?
=> AP_Scripting: improve knifeedge handling in aerobatics

ArduPlane/Parameters.cpp, ArduPlane/Parameters.h, ArduPlane/Plane.h, ArduPlane/control_modes.cpp
Tridge, turns out this was not in the code after all, only for QuadPlane....useful for aerobatic tuning where you have manually tweaked an axis and dont want it disturbed
=> Plane: added AUTOTUNE_AXES function to normal tune

libraries/AP_GPS/GPS_Backend.cpp
it is much more useful to check on the flight controller, not on the periph, or users just get mysterious failures
=> AP_GPS: disable GPS lag checking in AP_Periph

libraries/AP_Baro/AP_Baro.cpp
Bus 6 is the external bus for the Navigator board.
=> AP_Baro: add Bus6 to BARO_EXT_BUS values

Tools/autotest/common.py, Tools/autotest/rover.py
In the short period of time it takes for us to get organised/draining mavlink connections, the ArduPilot process might block writing to the primary mavlink connection - in which case we'll never get the message we requested.
Should solve
2022-08-31T23:17:43.6904119Z AT-0227.6: waiting for a message - any message....
2022-08-31T23:17:43.6904958Z AT-0227.6: Received (ATTITUDE {time_boot_ms : 3146, roll : 0.00013471684360411018, pitch : -4.076504410477355e-05, yaw : -2.1274349689483643, rollspeed : 6.679168291157112e-05, pitchspeed : 3.297374496469274e-05, yawspeed : 9.125166684498254e-07})
2022-08-31T23:17:43.6905505Z AT-0227.6: Waiting for mission count of (3) from (1:1) to (243:250)
2022-08-31T23:17:43.6905909Z AT-0227.6: Asserted mission count (type=2) is 3 after 0.100000s …
=> autotest: drain self.mav while waiting on other link

libraries/AP_GPS/AP_GPS.cpp, libraries/AP_HAL_ChibiOS/hwdef/include/minimize_features.inc
this allows SIRF to be specified even on minimised boards if it is requested
=> Fix SIRF GPS defines

libraries/AP_HAL_SITL/SITL_State.cpp, libraries/AP_HAL_SITL/Scheduler.cpp, libraries/AP_HAL_SITL/Scheduler.h
this stops us chewing lots of CPU while disarmed, and also stops the logging thread from chewing a lot of CPU
=> HAL_SITL: only do the cygwin speedup hack for scripting while armed

libraries/AP_Param/AP_Param.cpp, libraries/AP_Scripting/examples/Aerobatics/Trajectory/plane_aerobatics.lua
when a parameter is removed it leaves a gap in the index numbers. We need to cope with that gap when we add the parameters  in the script to allow params to be re-ordered or removed
=> AP_Param: allow for removal of script parameters

libraries/AP_Mount/AP_Mount_Gremsy.cpp
This reduces the rate at which the AUTOPILOT_STATE_FOR_GIMBAL_DEVICE mavlink messages are sent to the Gremsy gimbal from 100hz to 50hz.  There has been one report that the gimbal's internal buffer is being overloaded at the higher rate.
I have lightly tested this on my vehicle (CubeOrange+GremsyPixyU) and it seems fine although it seemed fine before as well.
=> AP_Mount: gremsy driver sends vehicle attitude at 50hz

Rover/Parameters.cpp, Rover/Parameters.h, Rover/mode_manual.cpp
This adds a new MANUAL_STR_EXPO parameter that allows configuring an expo on the steering control while in manual mode.  This is meant to address issue https://github.com/ArduPilot/ardupilot/issues/22173
This has been lightly tested on a real vehicle and seems to work.
FYI @IamPete1, @xianglunkai
=> Rover: add MANUAL_STR_EXPO

libraries/AP_LeakDetector/AP_LeakDetector.cpp, libraries/AP_LeakDetector/AP_LeakDetector.h
This pull request addresses issue #22013.
At present, the AP_LeakDetector library used in ArduSub contains compilation directives that only allow this sensor to initialize on FMUv3, FMUv5, or Linux navigator boards. Sensor initialization is neglected for all other board types, without providing any sort of notice to the user.
The changes proposed will here remove the initialization's dependence on board type. In this updated code, leak detectors can be initialized over connection to arbitrary pin number on any type of board. A new advanced parameter, `LEAKx_TYPE`, has been introduced that can be used to enable manual configuration of the leak detector pin. In order to use this feature, a user would set the `LEAKx_TYPE` parameter to indicate the signal type (analog or digital) of an …
=> AP_LeakDetector: add manual leak-pin selection to extend board compatibility

ArduPlane/servos.cpp, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_ICEngine/AP_ICEngine.h
Don't use THR_MIN when disarmed unless on an IC system with throttle while disarmed set
=> Plane: fixed use of THR_MIN when disarmed

libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/generator/src/main.c, libraries/AP_Scripting/lua_bindings.cpp
Adds some helpers for "full range" variables, just wraps the get functions with hard coded ranges. Allows the `skip_check` keyword on the basic types.
=> AP_Scripting: use helpers for full range return types to save flash

libraries/AP_Mission/AP_Mission.cpp
Change DO_LAND_START from 2D distance (lat, lng only) to 3D (also consider altitude). This is useful for having two DO_LAND_START's near each other for things like main go-home at cruise-ish altitude on RTL event and and a low-alt one for more tailored aborted landings
mavlink change PRs: https://github.com/ArduPilot/mavlink/pull/293 and https://github.com/mavlink/mavlink/pull/1910
=> AP_Mission: DO_LAND_START to consider altitude (3D distance)

Tools/scripts/board_list.py
non bdshot version has many issues and was not fully tested, AndyP created the bdshot version once he obtained a sample device and recommends removing this from the build, I agree...
=> Tools: blacklist the SkystarsH7HD board,use only bd-shot version

Tools/AP_Bootloader/can.cpp, Tools/AP_Bootloader/wscript, Tools/AP_Periph/wscript, Tools/ardupilotwaf/ap_library.py, Tools/ardupilotwaf/boards.py, Tools/ardupilotwaf/chibios.py, Tools/ardupilotwaf/dronecangen.py, wscript
* moves bootloader to use dronecan dsdl compiler
* adds dynamic source option to ap_stlib, making it much convenient to add generated source code.
* do dronecan_dsdlc operation as a bld() task rather than pre build task, which doesn't recompile if dsdl is changed.
=> Cleanup Dronecan generate build step

libraries/AC_AutoTune/AC_AutoTune_Heli.h, libraries/AP_CANManager/AP_CANManager.cpp, libraries/AP_CANManager/AP_CANManager.h, libraries/AP_CANManager/AP_CANTester_KDECAN.cpp, libraries/AP_CANManager/AP_SLCANIface.cpp, libraries/AP_CheckFirmware/AP_CheckFirmware.h, libraries/AP_CheckFirmware/AP_CheckFirmware_secure_command.cpp, libraries/AP_EFI/AP_EFI_NWPMU.cpp, libraries/AP_Frsky_Telem/AP_Frsky_MAVliteMsgHandler.cpp, libraries/AP_Generator/AP_Generator_RichenPower.cpp, libraries/AP_HAL_ChibiOS/Util.h, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py, libraries/AP_Motors/AP_MotorsMatrix_6DoF_Scripting.cpp, libraries/AP_OSD/AP_OSD.cpp, libraries/AP_OSD/AP_OSD.h, libraries/AP_OSD/AP_OSD_Backend.cpp, libraries/AP_OSD/AP_OSD_MSP_DisplayPort.cpp, libraries/AP_OSD/AP_OSD_ParamScreen.cpp, libraries/AP_OSD/AP_OSD_ParamSetting.cpp, libraries/AP_OpenDroneID/AP_OpenDroneID.cpp, libraries/AP_OpenDroneID/AP_OpenDroneID_DroneCAN.cpp, libraries/AP_RangeFinder/AP_RangeFinder_UAVCAN.cpp, libraries/AP_Vehicle/AP_Vehicle.cpp
Remove many inclusions of GCS.h header, notably the one in the HAL Util.h file.  This stops us creating dependencies where none exist, improving cache efficency
```
Board                     AP_Periph  blimp  copter  heli  iofirmware  plane  rover  sub
AIRLink                              112    0       0                 0      0      0
ARKV6X                               112    0       0                 0      0      0
ARK_GPS                   0                                                         
AeroFox-Airspeed          0                                                         
AeroFox-PMU               0                                                         
AtomRCF405NAVI                       0      0       0                 0      0      0
BeastF7 …
```
=> Remove GCS includes from headers

ArduCopter/radio.cpp, libraries/RC_Channel/RC_Channel.h, libraries/RC_Channel/RC_Channels_VarInfo.h
This adds a user configurable RC failsafe timeout (aka throttle failsafe).  Both @CraigElder and I have been flying with joysticks over 4G/LTE and have noticed that the RC failsafe triggers too easily.
If FS_THR_TIMEOUT is zero then the current behaviour is used (0.5sec for regular RC, 1sec for RC_OVERRIDES).  If non-zero then the FS_THR_TIMEOUT value (in seconds) is used for both regular RC and RC_OVERRIDES.
This has been lightly tested in SITL and seems to work.
Ideally I would like to make this change for Rover as well although Rover already has FS_TIMEOUT that applies to all failsafe so slightly more thought is required.
=> Copter: user configurable RC failsafe timeout

libraries/AP_Math/AP_Math.cpp, libraries/AP_Math/AP_Math.h
Marking this for DevCallEU to ask why this is normalized when the sole caller would appear to not want that (compass noise, each axis should be independent)
=> AP_Math: make rand_vec a little more efficient

libraries/AC_Sprayer/AC_Sprayer.cpp
We should rename this boolean to something meaningful rather than just calling it true_false.
=> AC_Sprayer: rename the boolean passed to run method

libraries/AP_Camera/AP_RunCam.cpp
retries is unsigned, so using -1 doesn't make sense
=> Retry RunCam device info maximum number of times

libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp, libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp
When using range finder as the primary height sensor when low and slow via the EK3_RNG_USE_HGT and EK3_RNG_USE_SPD parameters a condition can occur where if the range finder is not returning valid readings and the takeOffDetected test is tricked into thinking the vehicle is on ground, the range finder value is set to the RNGFNDx_GNDCLEAR value which results in rapid switching of the EKF's height estimate as shown in this user log with
EK3_RNG_USE_HGT  50.000000
EK3_RNG_USE_SPD  5.000000
After this change is applied, the rapid height estimate switching is eliminated
=> EKF3 Rangefinder Use Bugfix

libraries/AP_GPS/AP_GPS.cpp, libraries/AP_GPS/AP_GPS_UBLOX.cpp, libraries/AP_GPS/AP_GPS_UBLOX.h
this sets up the M10 to use the BaiDou B1C signal instead of B1, and disables glonass. This is needed to get a consistent 5Hz lock
bench tested on MatekL431-GPS with M10
flight tested with dual M10 based MatekL431-GPS on a CubeOrange, with good results
Before the fix:
with the fix:
before the fix the GPS would frequently report as unhealthy, preventing arming
=> AP_GPS: improve support for uBlox-M10

ArduCopter/mode.h, ArduCopter/mode_turtle.cpp
I had a frustrating hour at the field because I had turtle mode on a switch and the only thing telling me it was active were the flashing lights which I could not see. This change also prints a message to the GCS every 5s when turtle mode is active but not armed.
=> Inform GCS that turtle mode is active

Tools/autotest/arducopter.py
Ensure that the switch seems to happen.
This is a little strange - it takes a long time for the EKF to start using it again - in simulation the rangefinder is engaged at 14m on the way down, not the 20m specified:
=> autotest: add a test for EK3_RNG_USE_HGT

libraries/AP_Scripting/generator/src/main.c
It does not make sense to expose ap object creation to lua scripts, the script itself cannot populate the object as it can with userdata, so it would error out as null the first time it was used. 
Removes the following from the loaded global function table:
```
#if (AP_EFI_SCRIPTING_ENABLED == 1)
{"AP_EFI_Backend", new_AP_EFI_Backend},
#endif // (AP_EFI_SCRIPTING_ENABLED == 1)
#if HAL_MAX_CAN_PROTOCOL_DRIVERS
{"ScriptingCANBuffer", new_ScriptingCANBuffer},
#endif // HAL_MAX_CAN_PROTOCOL_DRIVERS
{"AP_HAL::AnalogSource", new_AP_HAL__AnalogSource},
{"AP_HAL::I2CDevice", new_AP_HAL__I2CDevice},
{"AP_HAL::UARTDriver", new_AP_HAL__UARTDriver},
{"RC_Channel", new_RC_Channel},
```
Currently you could do:
```
local efi_backend = AP_EFI_Backend()
```
Now you cannot, the only way to get a EFI …
=> AP_Scripting: remove lua acess to ap object creation

Tools/autotest/common.py, Tools/scripts/build_options.py, libraries/AP_BattMonitor/AP_BattMonitor.cpp, libraries/AP_BattMonitor/AP_BattMonitor.h, libraries/AP_BattMonitor/AP_BattMonitor_Analog.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Synthetic_Current.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Synthetic_Current.h, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py, libraries/SITL/SIM_Plane.cpp
=> Add synthetic current backend and correct SITL current computation

ArduSub/Parameters.cpp
Current gain state is an internal variable, not a parameter, but it's sent to the GCS via MAVLink. Accessing the current value [has been asked about](https://discuss.bluerobotics.com/t/fetching-js-gain-value/13192) because it wasn't previously obvious how to do so. This mentions it in the most obvious/relevant location.
=> ArduSub: Parameters: mention PilotGain message

ArduCopter/config.h
As kindly pointed out by @amilcarlucas the [RC failsafe timeout PR](https://github.com/ArduPilot/ardupilot/pull/22200) neglected to remove the older definitions.  A few other unused definitions have also been removed.
This should be a non-functional change.
=> Copter: remove some unused definitions

ArduPlane/quadplane.cpp
`get_gyro` is rad/sec `rate_bf_yaw_target` is expecting centi-deg/sec.
This is the original intent, but the current code is effectively setting to 0. Changing to that might be a better fix.  
Thanks to @skoch1s for finding the issue. https://github.com/ArduPilot/ardupilot/pull/22109 https://github.com/ArduPilot/ardupilot/issues/22103
=> Plane: Quadplane: correct units used in rate_bf_yaw_target

libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-bdshot/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus-bdshot/hwdef.dat
These were merged in a state where they would never have compiled.
Oops.
Notionally we could have a CI check which compiles any board which is being added...
=> hwdef: correct compilation of CubeOrange bdshot variants

Tools/autotest/arduplane.py, libraries/AP_Scripting/applets/Aerobatics/FixedWing/README.md, libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua, libraries/AP_Scripting/applets/Aerobatics/FixedWing/trick72.txt, libraries/AP_Scripting/examples/test_load.lua, libraries/AP_Scripting/lua/src/lauxlib.c, libraries/AP_Scripting/lua/src/lbaselib.c, libraries/AP_Scripting/lua/src/ldo.c, libraries/AP_Scripting/lua/src/luaconf.h
This exposes the load() lua function so we can load new lua code from within a lua script
We then use this to allow for new manoeuvrers to be added in text schedules. This means users can create very
complex aerobatic schedules without having to edit the base plane_aerobatics.lua
The trick72.txt airshow has been modified to use the new capability so it is tested in CI
this costs 424 bytes on H7:
with the change to remove binary load support this ends up saving nearly 2k of flash, leaving this PR overall 1.7k smaller
=> AP_Scripting: allow for user functions to be added in schedule text files

libraries/GCS_MAVLink/GCS_Common.cpp, libraries/SITL/SIM_Vicon.cpp
This corrects AP's consumption of the [ODOMETRY](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L5787) mavlink message so that the velocity vector is converted from the FRD frame ([the only frame we accept for the velocity](https://github.com/ArduPilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS_Common.cpp#L3402)) to the NED frame which is what the VisualOdometry and EKF require.
This has been bench tested on a quadcopter with a [ModalAI VOXL-CAM](https://ardupilot.org/copter/docs/common-modalai-voxl.html) mounted to the front of the vehicle.  Debug was added to print the raw velocity and final velocity values to confirm they were in the correct frame.
A bit anecdotal but the EKF status reporting appears much healthier after this change.
flight …
=> GCS_MAVLink: correct consumption of ODOMETRY velocity

libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp, libraries/RC_Channel/RC_Channel.h, libraries/RC_Channel/RC_Channels_VarInfo.h
Like how it is handled in betaflight and inav, adding a start char at the end of the flight mode string to indicate the craft is not armed. 
This allow the commonly used lua widget able to tell the correct arming status.
=> Add * to the end of flight mode string in CRSF

libraries/AP_Scripting/lua_bindings.cpp
Fixes a bug introduced in https://github.com/ArduPilot/ardupilot/pull/21980 and reported by @rishabsingh3003.
The new `check_...` function check for nullptr and never return. However in this case were getting the object in order to assign it so it is expected to be null. I fixed this issue in the generated bindings but missed these manual ones. 
Tested with the i2c scan and CAN write examples.
=> AP_Scripting: dont check objects that are expected to be null

ArduPlane/tailsitter.cpp, ArduPlane/tiltrotor.cpp, libraries/AP_Motors/AP_MotorsMulticopter.cpp, libraries/AP_Motors/AP_MotorsMulticopter.h, libraries/AP_Motors/AP_MotorsTri.cpp, libraries/AP_Motors/AP_MotorsTri.h
This allows the full 12 motors that are currently supported to be used in forward flight. Currently limited to 8.
=> AP_Motors: output_motor_mask use uin16_t mask

libraries/GCS_MAVLink/GCS_Common.cpp
We use mission protocol to upload fence. But it stop working if auto mode is not compiled (`MODE_AUTO_ENABLED` is disabled). In https://github.com/ArduPilot/ardupilot/blob/fc2090161b842b5453fe82e1248834aeb57c7a0c/libraries/GCS_MAVLink/GCS_Common.cpp#L3946-L3951
`AP::mission()` will return NULL because auto mode is unavailable. But checking `AP::mission()` in the beginning of `handle_common_mission_message()` is not necessary, because it is only used in
https://github.com/ArduPilot/ardupilot/blob/fc2090161b842b5453fe82e1248834aeb57c7a0c/libraries/GCS_MAVLink/GCS_Common.cpp#L3973-L3977
We can make it local to this case. This PR is tested on skyviper journey.
=> GCS_MAVLink: upload fence when auto mode not complied

libraries/AP_CANManager/AP_CANManager.cpp, libraries/AP_CANManager/AP_CANManager.h
this fixes firmware update of peripheral nodes using MAVCAN
tested on CubeOrange loading firmware onto a CAN GPS using dronecan_gui_tool
=> AP_CANManager: add an output buffer for MAVCAN

libraries/AP_Mount/AP_Mount_Siyi.cpp
This PR includes two fixes for the AP_Mount Siyi driver:
1. add support for the A8 gimbal which uses a shortened firmware version reply message ([discussion](https://discuss.ardupilot.org/t/siyi-a8-mini-4k-ai-mini-zoom-gimbal-camera-ai-identify-tracking-4k-1-1-7-inch-8mp-sony-sensor-6x-zoom/92133/30))
2. fixes a bug in the firmware version banner displayed when the autopilot first connects with the gimbal
This has been successfully tested on real hardware (a CubeOrange with a SiyiA8 attached).  Below is a screen shot of the corrected version display.
I've marked this for backporting to 4.3 because it is a relatively low risk change and I think it is quite important that we support this gimbal.
=> AP_Mount: fix for Siyi A8

libraries/AP_TECS/AP_TECS.cpp, libraries/AP_TECS/AP_TECS.h
This bug was reported by https://github.com/ArduPilot/ardupilot/pull/22191#issuecomment-1325428328 
The failure to reset the counter after exiting flare was preventing subsequent flares being performed unless the vehicle was power cycled after landing.
The  flare control no longer requires a counter to schedule the pitch limits, so this has been replaced with a boolean as suggested by https://github.com/ArduPilot/ardupilot/pull/22191#issuecomment-1325443278
=> Fix TECS bug preventing flare for subsequent landings

Tools/autotest/arduplane.py
test is flapping here, channel value is moving in right direction
=> autotest: loosen channel-value constrain in Soaring test

Tools/AP_Periph/AP_Periph.h, Tools/AP_Periph/Parameters.cpp, Tools/AP_Periph/Parameters.h, Tools/AP_Periph/can.cpp, Tools/AP_Periph/rc_out.cpp
Fixes a periph continuing to drive an ESC output to the last received value when the esc_rawcommand packets are lost. If the packets are continuously dropped or the bus is lost for whatever reason, this could result in the ESC output doing some very untoward things.
This change is tested on MatekL431-DShot configured for DSHOT600 output to an ESC, and reporting telemetry back to the flight controller.
=> AP_Periph: Add timeout to ESC output when CAN packets are lost

libraries/AP_HAL/Scheduler.cpp, libraries/AP_HAL/Scheduler.h, libraries/AP_Logger/LoggerMessageWriter.cpp, libraries/AP_Logger/LoggerMessageWriter.h
ensure` that the logging process() doesn't take more than 1ms
This also adds the TIME_CHECK() macro which can be used to find this type of issue
This PR fixes a few key issues:
- EKF being unhappy on takeoff due to a 40ms to 100ms loop
- radio failsafe on arming due to RC not being updated
- internal error due to false alarm in AC_AttitudeControl
=> AP_Logger: prevent long loops due to parameter logging

libraries/AP_Camera/AP_Camera.cpp, libraries/AP_Camera/AP_Camera.h
delay the next photo until minimum interval is met, which is what the documentation says. This fixes a nasty bug with mission plans where an extra photo can be triggered by a camera trigger in a mission which results in the number of CAM msgs being more than the number of images on the microSD, which makes the mapping run unusable
=> AP_Camera: fixed CAM_MIN_INTERVAL

ArduPlane/quadplane.cpp
this prevents us getting the AC_PosControl internal error, which is turning up as a common false positive, usually on arming when we can get a long loop
I test flew this on a Striver mini today
=> Plane: ensure we init z controller when inactive

ArduCopter/ReleaseNotes.txt, ArduCopter/version.h
This is the Copter-4.3.1 official release which has been in beta testing for a couple of weeks.
The [beta discussion thread is here](https://discuss.ardupilot.org/t/copter-4-3-1-rc1-available-for-beta-testing/93378) and we received a couple of positive comments from beta testers.
=> Copter: 4.3.1 release

ArduPlane/Attitude.cpp, ArduPlane/navigation.cpp
this makes it much easier to do a yaw rate autotune, and also means you don't need to use the rudder stick at all, as the yaw controller is already exercised nicely with roll movements, so overall the tune is faster and more accurate as less cross-axis coupling
tested in RF9 with AddictionX
=> Plane: added turn corrdination to autotune yaw rate tuning

libraries/AP_TECS/AP_TECS.cpp, libraries/AP_TECS/AP_TECS.h
The TECS_LAND_PTRIM  parameter is not used in the code. It was included by mistake in https://github.com/ArduPilot/ardupilot/pull/22191 and belongs with a yet to be submitted set of changes that will improve flare control for aircraft using flaps.
=> AP_TECS: Remove unused TECS_LAND_PTRIM parameter

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Logger/LogStructure.h, libraries/AP_Scheduler/AP_Scheduler.cpp, libraries/AP_Scheduler/AP_Scheduler.h, libraries/AP_Scheduler/PerfInfo.cpp, libraries/AP_Scheduler/PerfInfo.h
This PR has been reworked to slightly improve reporting of issues with the main loop rate to users
- SYS_STATUS.load jumps to 1000 if the main loop is less than 95% of the configured main loop rate.  This was tested in SITL by setting SIM_LOOP_DELAY = 1000 and confirming the load jumped to 1000 (see below).
- Arming check added that stops arming if the main loop rate is < 90% of the configured main loop rate.  Perhaps we should make this 95% to be consistent with above but I picked this level because this is the threshold where our users started seeing problems.  This applies to all vehicles but it can be override by forcing the arming.
- PM log message gets a new "LR" (aka Loop Rate) field with the filtered main loop rate.  To make space the existing "NLoop" field was shortened to "NL". …
=> Copter: add main loop performance warning

ArduPlane/ArduPlane.cpp
this will be needed with #22298 as that now relies on integrating position based on loop times
=> Plane: added FAST_TASK() for key scheduler tasks

Tools/autotest/arducopter.py, Tools/autotest/common.py, libraries/GCS_MAVLink/GCS_Common.cpp
Similar to "disarm force" and "send debug trap", uses a magic number in a parameter to force the vehicle to reboot.  This is useful for vehicle that are `ARMING_REQUIRE` 0 and AntennaTracker.
=> Add forced-reboot via mavlink

libraries/AP_Scheduler/AP_Scheduler.cpp
the breakup of the fast loop resulted in us sometimes (under heavy CPU load) not running a fast task on every loop
ping @andyp1per
=> AP_Scheduler: guarantee that FAST_TASK tasks do run on every loop

libraries/AP_OpticalFlow/AP_OpticalFlow_Calibrator.cpp
Mainly just to get the instance column to make graphing axes easier
```
pbarker@fx:~/rc/ardupilot(master)$ mavlogdump.py logs/00000003.BIN --t FMTU | grep 251
2022-12-12 09:41:47.06: FMTU {TimeUS : 62248424, FmtType : 251, UnitIds : s#-???, MultIds : F00000}
pbarker@fx:~/rc/ardupilot(master)$ mavlogdump.py logs/00000003.BIN --t FMT | grep OFCA
2022-12-12 09:41:46.48: FMT {Type : 251, Length : 25, Name : OFCA, Format : QBBfff, Columns : TimeUS,Axis,Num,FRate,BRate,LPred}
```
```
MAV> graph OFCA[1].
OFCA[1].Axis    OFCA[1].BRate   OFCA[1].FRate   OFCA[1].LPred   OFCA[1].Num     OFCA[1].TimeUS
MAV> graph OFCA[1].LPred
```
=> AP_OpticalFlow: add some units to OFCA log message

ArduPlane/mode.h, ArduPlane/mode_rtl.cpp
If VTOL is active and within RTL radius and under QRTL alt then switch to QRTL. 
For example if you takeoff in Qloiter to 5m and then switch to RTL currently we will transition into forward flight, climb and circle. This will now switch to QRTL and it will return home and land.
Also tidy's up the `switch_QRTL` function a little.
=> Plane: if RTL with VTOL active and within QRTL radius and alt then QRTL

libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
Align the data of the incoming RPY data of the Storm32 data to be in the same coordinate frame as ardupilot.
Found the bug by looking through how RPY data was being sent to the gimbal through the `send_target_angles` command where I proceeded to see this:
```
// send CMD_SETANGLE (Note: reversed pitch and yaw)
cmd_set_angles_data.pitch = -degrees(angle_target_rad.pitch);
cmd_set_angles_data.roll = degrees(angle_target_rad.roll);
cmd_set_angles_data.yaw = -degrees(get_bf_yaw_angle(angle_target_rad));
```
So then I flipped the incoming data from storm32 gimbal on the `parse_reply` function to match.
=> AP_Mount: Align received data to AP coordinate frame for Storm32 Serial

libraries/AP_RangeFinder/AP_RangeFinder.cpp
The analog back end uses analog pins not GPIO pins, so its not correct to use `hal.gpio->valid_pin` this breaks out of the check before reaching that case. 
There is sometimes cross over between GPIO and analog, but as far as I am aware never analog and SERVO.
Resolves outstanding issue from 4.3 release, https://github.com/ArduPilot/ardupilot/issues/21711
=> AP_RangeFinder: skip GPIO arming check on analog backend

libraries/AP_HAL/SIMState.cpp, libraries/AP_HAL/SIMState.h
this instance variable was always nullptr due to constructor ordering
Extracted from https://github.com/ArduPilot/ardupilot/pull/21929
The AP_HAL_SITL class already has this change in it.
=> AP_HAL: use singleton getter for Baro in SIMState

ArduPlane/GCS_Mavlink.cpp
This moves to use the base class method as the overrides are already in place for `set_home_to_current_location` and `set_home`. They were already being used for the command int this brings command long to that same behavior. 
Base class methods is here:
https://github.com/ArduPilot/ardupilot/blob/3abdc6ad25fbf4f197a755cef6d12c17ab36d8c3/libraries/GCS_MAVLink/GCS_Common.cpp#L4467-L4491
The only difference is the checking if lat/lon are zero when deciding to set home to current location.
=> Plane: GCS_Mavlink: use base class DO_SET_HOME

libraries/AP_Logger/LogFile.cpp
AC_PID.h includes a remarkable amount of stuff
=> AP_Logger: include PIDInfo header in place of PID header

libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua, libraries/AP_Scripting/lua_bindings.cpp
This converts the aerobatics code to a metatable based object system, which reduces memory usage a lot
For the current largest schedule, F3AF23.txt, the required SCR_HEAP_SIZE in SITL reduces from 350000 to 285000, a reduction of 18%
Surprisingly, CPU cost seems to be unchanged, at least in terms of VM instructions
=> Scripting: reduce memory needed for aerobatics

Tools/AP_Periph/AP_Periph.cpp, Tools/AP_Periph/AP_Periph.h, Tools/AP_Periph/Parameters.cpp, Tools/AP_Periph/Parameters.h, Tools/AP_Periph/can.cpp, Tools/AP_Periph/wscript, libraries/AP_HAL_ChibiOS/hwdef/MatekL431-Proximity/hwdef-bl.dat, libraries/AP_HAL_ChibiOS/hwdef/MatekL431-Proximity/hwdef.dat, libraries/AP_Proximity/AP_Proximity.cpp, libraries/AP_Proximity/AP_Proximity.h, libraries/AP_Proximity/AP_Proximity_Backend.cpp, libraries/AP_Proximity/AP_Proximity_Backend.h, libraries/AP_Proximity/AP_Proximity_Boundary_3D.cpp, libraries/AP_Proximity/AP_Proximity_Boundary_3D.h, libraries/AP_Proximity/AP_Proximity_DroneCAN.cpp, libraries/AP_Proximity/AP_Proximity_DroneCAN.h, libraries/AP_Proximity/AP_Proximity_Params.cpp, libraries/AP_Proximity/AP_Proximity_Params.h, libraries/AP_Proximity/AP_Proximity_Utils.cpp, libraries/AP_UAVCAN/AP_UAVCAN.cpp
This needs: https://github.com/dronecan/DSDL/pull/15 to be merged first
=> Add AP_Periph support for Proximity sensors

AntennaTracker/GCS_Tracker.h, ArduCopter/GCS_Copter.h, ArduPlane/GCS_Plane.h, ArduSub/GCS_Sub.h, Blimp/GCS_Blimp.h, Rover/GCS_Rover.h, Tools/AP_Periph/GCS_MAVLink.h, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Dummy.h
A recent PR had to change every single one of these methods, which was kind of unfortunate.
So generate the methods using a #define so the duplication happens at preprocessor-time.
=> GCS_MAVLink_*: code-generate chan-fetching methods 

libraries/AP_Logger/AP_Logger.cpp
This change enables users to log while disarmed during flight testing without generating unnecessary logs when powered up via USB whilst downloading  logs, adjusting parameters, etc.
=> Add option to only log on disarm when battery is connected

ArduCopter/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.cpp
This PR clears up some false-positive arming failures when using Non-GPS navigation (e.g. the [ModalAI VOXL camera](https://ardupilot.org/copter/docs/common-modalai-voxl.html)).  The troublesome messages are:
- GPS and AHRS differ by 1.5e+07m
- High GPS HDOP (Copter only)
The changes are:
1. Skip the AP_Arming comparison of AHRS vs the primary GPS if no GPSs are enabled (e.g. AP_GPS::num_sensors() == 0)
2. Skip the Copter specific GPS HDOP arming check if no GPSs are enabled (e.g. AP_GPS::num_sensors() == 0)
BTW, I was concerned about the difference between "AP_GPS::num_sensors()" and the number configured (e.g. GPS_TYPE, GPS_TYPE2) but the existing AP_GPS::first_unconfigured_gps() check catches cases where the user has set GPS_TYPE, GPS_TYPE2 but the drivers haven't found the GPS.  It …
=> AP_Arming: skip AHRS vs GPS location check if GPS is disabled

libraries/AP_HAL_ChibiOS/sdcard.cpp
~~... also move include of same to the user of that include.~~  Weird namespacing problems, `ChibiOS::bouncebuffer_t` vs `bouncebuffer_t` with this change, so removed.
Still compiles!
And I flashed it to a CubeBlack, which hasn't catch fire yet.
=> Add missing bouncebuffer.h include in sdcard.cpp

ArduCopter/Copter.h, Rover/Rover.h, libraries/GCS_MAVLink/GCS.cpp, libraries/GCS_MAVLink/GCS.h
introduces unnecessary dependencies
=> GCS_MAVLink: remove unnecessary include of OpticalFlow header in GCS.h

libraries/AP_Mount/AP_Mount_Siyi.cpp
With the arrival of my Siyi A8 camera I've discovered a couple of issues that this PR fixes:
1. The Siyi A8 camera sends the Gimbal Configuration message with 7 fields (the ZR10 sends 5).  This caused the consumption of the message to fail and so the AP driver was never sure whether video recording was working or not.
2. Request the Gimbal Configuration at 1hz to be sure that we've got the latest status.  The previous method only requested this status if the pilot had actively changed the status but the camera recording can fail for other reasons (like the SD Card filling up) so it is more reliable to also request an update at 1hz
3. The "Recording ON/OFF" message was sent as an ERROR which is not correct.  Although we'd like the user to see this message, INFO is perhaps good enough.
This …
=> AP_Mount: fix Siyi A8 reporting of record on/off status

Tools/autotest/arduplane.py
EKF may still be active when arming is first attempted
=> autotest: fix race condition in NeedEKFToArm

Tools/scripts/extract_features.py
... well, for all backends, but this is the one that has backend-specific defines
=> Tools: extract_features.py: add Richenpower define

ArduSub/GCS_Mavlink.cpp
Just like MANUAL_CONTROL messages, RC_CHANNELS_OVERRIDE message should also update the pilot_input timeout.
After that, letting the common handler to do all the rest, like before.
=> Sub: consider RC_CHANNELS_OVERRIDE for pilot_input_failsafe

libraries/SITL/SIM_GPS.cpp
I changed HDOP of SIM_GPS from 2.0 to 1.2 to prevent triggering arming check.
I tested this with these settings:
SIM_GPS_TYPE 5
GPS_TYPE 5
=> SITL: change HDOP from 2.0 to 1.2

ArduPlane/tiltrotor.cpp
This adds throttle scaling to vectored yaw tilt-rotors. It uses the same scaling method as tailsitters. There scale range is hard coded to the same as the default range for tailsitters (where we have parameters for min and max). So will reduce gains to half at high throttle and double at low throttle. At hover throttle they remain 1 so no change in behavior. We may want to change the max scale factor to 1 so gains are never increased at low throttle, thus making oscillation unlikely. Only yaw is scaled, the roll input used at high tilt angles is not changed. 
It also now sets the yaw limit flags if either tilt is at its limit, this prevents I wind up. 
https://youtu.be/W760-G-N7_I
=> Plane: tiltrotor: add throttle scaling for vectored yaw

libraries/AP_Baro/AP_Baro.cpp, libraries/AP_Baro/AP_Baro.h
This sets the active baro field elevation from the origin altitude if not set by the user. This should make baro altitude better match aviation altitude for all users, without having to setup the parameter on each flights
ping @rbeall
tested successfully on a CubeOrange plane with 4 flights
=> AP_Baro: auto-set field elevation from origin

libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp, libraries/AP_NavEKF2/AP_NavEKF2_core.h, libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.h
EKF always checks two rangefinders even if RANGEFINDER_MAX_INSTANCES is 1.
I added the RANGEFINDER_MAX_INSTANCES check.
=> AP_NavEKF2/3: do not check the second range finder if RANGEFINDER_MAX_INSTANCES is 1

libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h, libraries/AP_AHRS/AP_AHRS_DCM.cpp, libraries/AP_AHRS/AP_AHRS_DCM.h, libraries/AP_NavEKF2/AP_NavEKF2.h, libraries/AP_NavEKF3/AP_NavEKF3.h
this fixes a "climb away" in quadplanes when AHRS_EKF_TYPE=2 and EK2_ENABLE=0. The user has ARMING_CHECK=5390 to disable key arming checks, and the plane flew on DCM as the configured EKF wasn't enabled.
This resulted in AHRS::get_origin() returning false as it couldn't ask EKF2 for the origin (as EKF2 was not enabled or instantiated)
The result was an incorrect calculation for target height during the descent stage of QRTL, resulting in a climb away until the user took over
The fix involves several changes:
- if the configured EKF type cannot provide an origin then use the active EKF type if we are armed. We don't do this while disarmed as the vehicle code may use the boolean result of get_origin() to determine if the EKF is initialised or not (see for example set_home() in copter).
- if …
=> AP_AHRS: use active EKF type for origin and crtl limits

ArduPlane/altitude.cpp, ArduPlane/mode.h, ArduPlane/mode_loiter.cpp, ArduPlane/mode_qrtl.cpp
A none functional re-work of the `adjust_altitude_target` function, moving functionality down into the existing per-mode `update_target_altitude` function. This simplifys code by keeping mode specific functionality in mode files.
The if's for fbwb, cruise, loiter and guided have been moved down. The remaining functionality is then moved to the base `Mode` class. Currently this is left in `altitude.cpp` to minimize the diff (just lots of `plane.` due to the namespace change), but it should be moved into `mode.cpp` in the future.
=> Plane: move adjust_altitude_target functionality to per mode functions

libraries/AP_Airspeed/AP_Airspeed.cpp, libraries/AP_Airspeed/AP_Airspeed.h, libraries/AP_Airspeed/AP_Airspeed_Backend.cpp, libraries/AP_Airspeed/AP_Airspeed_Backend.h, libraries/AP_Airspeed/AP_Airspeed_Health.cpp
Extract/precursor to https://github.com/ArduPilot/ardupilot/pull/22297. The goal its to save a bunch of flash on periph so we feel less bad about costing lots in the param split in https://github.com/ArduPilot/ardupilot/pull/22297. This removes usage of params that are already hidden from the user and also hides tube order.
=> AP_Airspeed: Periph: remove usage of hidden params and remove tube order

Tools/autotest/autotest.py
prevent deprecation warning
```
Tools/autotest/autotest.py:14: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
```
=> autotest: removed deprecated distutils

libraries/AP_TemperatureSensor/AP_TemperatureSensor.cpp
fix AP_TemperatureSensor param count change when loading drivers which was causing GCS spam. Closes  https://github.com/ArduPilot/ardupilot/issues/22357
=> AP_TemperatureSensor: fix param count change when loading drivers

libraries/AP_Mount/AP_Mount_Servo.cpp, libraries/AP_Mount/AP_Mount_Servo.h
This fixes a bug (see issue https://github.com/ArduPilot/ardupilot/issues/22225) in AP_Mount's servo gimbal driver.  In RC targetting mode, if the user moved the yaw control to the maximum (e.g. RCx_MAX) then gimbal would yaw completely to the left.
The troublesome line was this line in AP_Mount_Servo::closest_limit() that would cause a yaw input angle of 180 deg to become -180 deg.  This issue only came to light after we changed the default MNT1_YAW_MAX angle from 45deg to 180deg.
`while (angle >= 1800) angle -= 3600;`
We do not need this closest_limit() method at all anymore because SRV_Channel::move_servo() enforces limits.  Also an earlier PR corrected the mixed-up use of body-frame and earth-frame angles.
This has been tested in SITL to confirm the RC input issue is corrected and to …
=> AP_Mount: servo driver loses unnecessary closest_limits method

Tools/autotest/default_params/copter-gimbal.parm
This corrects a parameter name in the copter-gimbal.parm file which is used when testing a gimbal in SITL.  This is very low risk because it is only used by developers as a convenient way to get the virtual gimbal working in SITL.
I've tested this on my local machine.
=> Tools: correct autotest copter-gimbal .parm

Tools/environment_install/install-prereqs-mac.sh
the 3.10.8 to 3.10.9 upgrade is failing in CI
=> Tools: macos-env: overwrite files when upgrading Python

libraries/AP_Scripting/README.md
change the two things:
- avoid to call set_output_pwm before setting origin
- make get_home() once
=> AP_Scripting: modify example script of README.md

ArduCopter/Copter.cpp, ArduCopter/Copter.h, ArduCopter/GCS_Mavlink.cpp
This allows compilation when GUIDED, AUTO and CIRCLE modes are disabled.
I've confirmed that the compilation succeeds when the following combinations are disabled.
- AUTO
- AUTO and CIRCLE
- AUTO and GUIDED 
- AUTO, CIRCLE and GUIDED
CIRCLE / GUIDED are dependent on AUTO , so it cannot be disabled independently.
=> Copter: fix compilation when GUIDED, AUTO and CIRCLE modes are disabled

libraries/AP_Motors/AP_MotorsHeli_Single.cpp, libraries/AP_Motors/AP_MotorsHeli_Single.h
This PR corrects a long time concern I had with how collective to yaw compensation was implemented in traditional heli code.  The feature is designed to compensate for collective inputs to keep the added torque from causing yaw  excursions by feeding in yaw inputs with the collective input.  The compensation is not only needed to help reduce yaw excursions when making collective changes in flight but also when changing gross weight.
It was originally designed as a linear relationship for feedforward from collective.  However theory for hover performance of full scale helicopters shows that the relationship between gross weight and hover power required is gross weight ^ 3/2.  This assumes that density altitude and rotor speed are not changed.  This theory can be applied to the collective …
=> Improve collective to yaw compensation for traditional helicopters

ArduCopter/Copter.cpp, libraries/AP_HAL/UARTDriver.h, libraries/AP_HAL_ChibiOS/UARTDriver.h, libraries/AP_RCProtocol/AP_RCProtocol.h, libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp, libraries/AP_RCProtocol/AP_RCProtocol_CRSF.h, libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp, libraries/AP_RCTelemetry/AP_CRSF_Telem.h, libraries/RC_Channel/RC_Channel.h, libraries/RC_Channel/RC_Channels_VarInfo.h
Shave off a few of the rough edges when using ELRS including radio failsafes that occur at higher frame rates
It seems the main change that people need to make for ELRS is to set the UART RX baudrate to 416666 when upgrading
Adds a bit to RC_OPTIONS to allow CRSF to bootstrap at 420000
Prompted by https://github.com/ExpressLRS/ExpressLRS/issues/1773
=> ELRS improvements

libraries/AP_DAL/AP_DAL_RangeFinder.cpp
This fixes #18205.
If the first backend could not be obtained, subsequent ones were not checked.
This PR checks for the number of num_sensors, even if the first backend is nullptr.
I could reproduce the issue, and tested it in SITL.
=> AP_DAL: call start_frame for all backends

Tools/scripts/size_compare_branches.py
useful if there are fixes on two branches that are required for the size-compare to complete.
=> Tools: add --no-merge-base option to size_compare_branches.py

ArduCopter/mode.h, ArduCopter/mode_auto.cpp
This PR removes code duplication and reduced the chance of bug introduction by using wp_start(target_loc) in do_nav_wp() like other DO functions.
=> Copter: Use wp_start() in do_nav_wp()

Tools/environment_install/install-prereqs-mac.sh
... this doesn't pin the Python package so later steps may still be installed - and they still haven't fixed the files-exist problem
=> github: macosx: remove github-installed Python symlinks in /usr/local/bin

libraries/AP_HAL_Linux/RCInput_RPI.cpp, libraries/AP_HAL_Linux/RCInput_RPI.h
Ardupilot running on RaspberryPi Bulleyes 64OS crashes in RCInput_RPI.cpp
This is due to enabling **CONFIG_STRICT_DEVMEM** in LinuxKernel.
Still after disabling this configuration item virtual memory address needs to be 64bit.
This PR works on RPI-Zero running (Raspberry OS 32-bit)
& RPI-Zero W2 64 bit running  (Raspberry Bulleyes 64)
=> AP_HAL_Linux: Raspberry 64OS Address fix

Tools/autotest/arducopter.py
sending the arm command isn't sufficient if there are other arming problems.
Caught a test failing when throttle was found to be high - I think the rc(3, 1700) was managing to have effect before we processed the arm command because of the way the input queues to ArduPilot SITL work
=> Fix race condition in Copter TakeoffCheck test

ArduPlane/quadplane.cpp
Added Y4 config to Q_Frame_Type in Quadplane - already supported in AP_MotorsMatrix
=> Plane: Added Y4 config to Q_Frame_Type 

libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/README.md, libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/sport_aerobatics.lua
Adds back a restructured version of the old rate-based aerobatics that allow even trainer-style vehicles to do some tricks either in missions or on a switch, as well as more capable vehicles in significant wind that fail trajectory based tricks. Separated directories
=> Add rate controlled aerobatics applet

libraries/AC_AttitudeControl/AC_PosControl.cpp
This PR fixes a serious bug that can cause the aircraft to command an exponentially increasing pitch or roll rate during takeoff.
The problem is part of the initialisation of the xy position controller when the vel xy feed forward term PSC_VELXY_FF is non zero.
This meant that each loop the FF component would be moved into the I term, resulting in the exponential growth.
Before fix:
1: Normal takeoff
2: WP_NAVALT_MIN = 1 m
3 WP_NAVALT_MIN = 1 m and PSC_VELXY_FF = 0.5
After fix, WP_NAVALT_MIN = 1 m and PSC_VELXY_FF = 0.5 :
=> AC_PosControl: Include FF in _pid_vel_xy integrator initialisation

ArduCopter/Copter.cpp, Tools/autotest/arducopter.py, libraries/AP_GyroFFT/AP_GyroFFT.cpp, libraries/AP_GyroFFT/AP_GyroFFT.h, libraries/AP_GyroFFT/examples/ReplayGyroFFT/ReplayGyroFFT.cpp, libraries/AP_GyroFFT/examples/ReplayGyroFFT/wscript, libraries/AP_HAL_SITL/SITL_cmdline.cpp, libraries/AP_HAL_SITL/UARTDriver.cpp, libraries/AP_InertialSensor/AP_InertialSensor.cpp, libraries/AP_InertialSensor/AP_InertialSensor.h, libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp, libraries/AP_InertialSensor/AP_InertialSensor_Backend.h, libraries/AP_InertialSensor/AP_InertialSensor_SITL.cpp, libraries/AP_InertialSensor/AP_InertialSensor_SITL.h, libraries/AP_Vehicle/AP_Vehicle.cpp, libraries/AP_Vehicle/AP_Vehicle.h, libraries/SITL/SITL.cpp, libraries/SITL/SITL.h
This PR adds the ability to run the in-flight FFT after the filtering. This enables a couple of things:
- FFT driven notches that "clean-up" the remaining noise
- The ability to check whether there is significant noise at a motor frequency
Working reasonably well now and verified by SITL
To run:
```
./waf configure --board sitl --debug
./waf copter
./Tools/autotest/autotest.py fly.ArduCopter.GyroFFTPostFilter
```
This puts IMU data in /tmp. Then:
```
./waf build --target examples/ReplayGyroFFT
./build/sitl/examples/ReplayGyroFFT -M quad -C -v ArduCopter
```
=> In-flight FFT postfilter

libraries/AP_InertialSensor/AP_InertialSensor_BMI088.cpp, libraries/AP_InertialSensor/AP_InertialSensor_BMI088.h
This makes the BMI088 filtering and FIFO update more closely match our standard setup on the Invensense sensors
- Gyro LPF 1/4 ODR
- Accel LPF close to 190Hz
- Synchronize period on each fifo read
=> Optimize LPF and fifo update on BMI088

libraries/SITL/SIM_PS_LightWare.h, libraries/SITL/SIM_PS_LightWare_SF45B.h, libraries/SITL/SIM_PS_RPLidarA2.h, libraries/SITL/SIM_PS_TeraRangerTower.h
This was a bit of a mystery for me - there's some strange things around `using` when other subclasses override a constructor.
=> SITL: tidy simulated proximity sensor constructors

libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
prevents nil derefernce in loading tricks
=> AP_Scripting: don't start aerobatics until we have a vel estimate

libraries/AP_FETtecOneWire/AP_FETtecOneWire.cpp
these comments break the MissionPlanner param parser
see these errors in MissionPlanner.log
```
2022-12-30 08:28:42,641  INFO MissionPlanner.Utilities.ParameterMetaDataParser - using cache https://raw.oborne.me/ardupilot/ardupilot/master/libraries/AP_FETtecOneWire/AP_FETtecOneWire.cpp (D:\a\MissionPlanner\MissionPlanner\ExtLibs\Utilities\ParameterMetaDataParser.cs:503) [65]
2022-12-30 08:28:42,641 ERROR MissionPlanner.Utilities.ParameterMetaDataParser - Invalid MetaFrame Blimp (D:\a\MissionPlanner\MissionPlanner\ExtLibs\Utilities\ParameterMetaDataParser.cs:390) [70]
2022-12-30 08:28:42,641  INFO MissionPlanner.Utilities.ParameterMetaDataParser - using cache https://raw.oborne.me/ardupilot/ardupilot/master/libraries/AP_Proximity/AP_Proximity_Params.cpp …
```
=> AP_FETtecOneWire: change comments to not use @param

ArduCopter/mode.h, ArduCopter/takeoff.cpp
This PR fixes a bug that happens if the aircraft is told to take off to the current altitude.
Previously this line:
bool reached_altitude = (copter.pos_control->get_pos_target_z_cm() - auto_takeoff_start_alt_cm) >= ((auto_takeoff_complete_alt_cm + terr_offset - auto_takeoff_start_alt_cm) * 0.90);
Would always simplify down to :
(0) >= ((0 + terr_offset) * 0.90);
so it would pass or fail based on the terrain altitude.
The new approach bases the height threshold to above 1% of the stopping distance below the target altitude.
=> Copter: Fix Auto Takeoff when complete_alt_cm is current altitude

libraries/AC_WPNav/AC_WPNav.cpp, libraries/AC_WPNav/AC_WPNav.h
This PR removes the set and save for _wp_accel_cmss to remove a number of problems that this can cause when the lean angel max is changed.
=> AC_WPNav: remove _wp_accel_cmss.set_and_save_ifchanged

Tools/autotest/common.py, libraries/AC_WPNav/AC_WPNav.cpp, libraries/AC_WPNav/AC_WPNav.h
This PR lets the user explicitly define the cornering acceleration limit different to the acceleration/deceleration limit. This follows a history of:
1. Setting it equal to the acceleration/deceleration limit. People wanted to go faster around corners.
2. Setting it to the lean angle. Not always possible due to wind resulting in compromised path following and complaints of overly aggressive behaviour in sharp corners.
This lets the user choose.
This PR also changes the sanity check introduced in this PR:
https://github.com/ArduPilot/ardupilot/pull/17673
This form checks that both the old value and new value are positive rather than just the old value.
I would like to discuss exactly how we should  handle these limits and sanity checks. In particular should we:
1. decrease the acceleration …
=> AC_WPNav: Add corner acceleration limit parameter

ArduCopter/mode_guided.cpp, ArduPlane/mode_qhover.cpp, ArduPlane/mode_qloiter.cpp, ArduPlane/mode_qrtl.cpp, ArduPlane/quadplane.cpp, ArduPlane/quadplane.h, libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_AttitudeControl/AC_PosControl.h, libraries/AP_Math/control.cpp, libraries/AP_Math/tests/test_control.cpp
This PR improves the handling of limits in the position controller and clarifies some of the code.
1. Fixes problem where limits can result in the aircraft overshooting the stopping point. This was seen during a landing where the aircraft becomes limited during the early deceleration phase. This slides the stopping point past the intended altitude resulting in a possible "hard landing".
2. Moves the removal of ignore_descent_limit from input_vel_accel_z to land_at_climb_rate_cm (a better name would be nice). This simplifies the use of input_vel_accel_z  for the vast majority of use cases and clarifies the use of land_at_climb_rate_cm.
3. A few efficiency clean ups
4. Math library changes to support 1.
5. Math library changes to prevent limits from altering the velocity vector direction.
=> Position Control Limit Handling

ArduCopter/UserParameters.cpp, ArduCopter/UserParameters.h
I am not completely convinced that we need these custom "user parameters" at all, but they are disabled by default. 
This fixes a bug since we did not have the "setup_object_defaults" call.
=> Copter: set param default for user parameters

ArduCopter/takeoff.cpp
This addresses a bug found here:
https://discuss.ardupilot.org/t/feedback-and-assistance-with-new-takeoff-behaviour/94121/40?u=leonardthall
in logs 4.3.2_Suspected_Integrator_Windup.zip 
Takeoff is initialised as soon as the mode is switched to Auto. The vertical altitude then drifts while the pilot waits to takeoff. When the aircraft take-off it is already above wp_navalt_min and switches immediately to flying.
=> Copter: Fix takeoff with alt drift and wp_navalt_min set

libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro/hwdef.dat
Modified the omnibusf4pro/hwdef.dat file to support bmi270 imu. Verified the modifications on eachine x220 clone and omnibusf4 flight controller. Changes could be merged into main branch.
=> BMI270 IMU support for omnibusf4 controllers

ArduCopter/Copter.h, ArduPlane/Plane.h, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Parachute/AP_Parachute.cpp, libraries/AP_Parachute/AP_Parachute.h, libraries/AP_Parachute/examples/AP_Parachute_test/AP_Parachute_test.cpp
We use this pattern in many other places (e.g. AP_Camera).
The Parachute library doesn't actually need the relay library to function.
=> Use relay singleton in AP_Parachute

ArduPlane/events.cpp
These mode prints are redundant.
=> Plane: Events: combine failsafe event prints

libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS.h, libraries/AP_ExternalAHRS/AP_ExternalAHRS_LORD.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS_LORD.h, libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.h, libraries/AP_ExternalAHRS/AP_ExternalAHRS_backend.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS_backend.h, libraries/AP_InertialSensor/AP_InertialSensor_ExternalAHRS.cpp, libraries/AP_InertialSensor/AP_InertialSensor_ExternalAHRS.h, libraries/SITL/SIM_VectorNav.cpp, libraries/SITL/SIM_VectorNav.h
This adds support for the VN-100, not a full AHRS as it cant provide position, but it can be used as a source for IMU and mag data. 
- Adds autodetection of VN-100 vs VN-300
- Stops VN streaming NMEA data as well as the requested binary data
- removes all the unused feilds from the VN-300 message
- Adds uncompensated mag reading to the VN-300
- Adds option to use uncompensated IMU values, these may get on better with the EKF.
- Always runs EAHRS arming check if enabled
- Adds a IMU print eg `IMU0: External: VN-100S-CR 60Hz`
This has had a fair bit of bench testing, but no flight testing yet.
=> AP_ExternalAHRS: add support for VectorNAV 100

libraries/AP_Terrain/AP_Terrain.cpp, libraries/AP_Terrain/AP_Terrain.h, libraries/AP_Terrain/TerrainGCS.cpp, libraries/AP_Terrain/TerrainIO.cpp, libraries/AP_Terrain/TerrainMission.cpp, libraries/AP_Terrain/TerrainUtil.cpp
... many of our boards don't have a terrain directory (e.g. stm32 / no SD card)...
also prune some un-needed includes in cpp files.  These look like they were copy/pasted.
=> AP_Terrain: only include GCS_MAVLink if terrain is enabled

libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/README.md, libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/sport_aerobatics.lua
to avoid trick param conflicts when swtiching between sport and trajectory aerobatics
this is most consistent with how we renamed AEROM to AEROR
=> AP_Scripting: rename TRIK to TRIKR for sport_aerobatics

libraries/AP_Arming/AP_Arming.cpp
It's OK to not have AP_RALLY_ENABLED if the user isn't requiring that a rally point be avaiable.  i.e. if the user is requesting that there be a landing point that doesn't infer rally must be compiled in!
Tested in SITL; before this PR we fail to arm if "require RTL" bit is set and rally is not present
=> AP_Arming: only require AP_RALLY_ENABLED if MIS_ITEM_CHECK_RALLY

ArduCopter/Parameters.cpp, ArduPlane/Parameters.cpp, Blimp/Parameters.cpp, Rover/Parameters.cpp, Tools/autotest/param_metadata/param_parse.py, libraries/AP_Button/AP_Button.cpp, libraries/AP_SerialManager/AP_SerialManager.cpp
Alternative to https://github.com/ArduPilot/ardupilot/pull/22516 which allows for copying all fields, not just Values or Bitmasks.
There might still be scope for that other PR given we still need CopyValuesFrom.
But this removes a whole bunch of repeated parameter metadata.
Not without change to apm.pdef.xml output - but it seems to be a bugfix:
```
--- apm.pdef.xml-master	2022-12-30 12:29:06.128966405 +1100
+++ apm.pdef.xml	2022-12-30 13:12:37.657126343 +1100
@@ -17440,23 +17440,23 @@
<field name="Bitmask">0:InvertRX, 1:InvertTX, 2:HalfDuplex, 3:Swap, 4: RX_PullDown, 5: RX_PullUp, 6: TX_PullDown, 7: TX_PullUp, 8: RX_NoDMA, 9: TX_NoDMA, 10: Don't forward mavlink to/from, 11: DisableFIFO, 12: Ignore Streamrate</field>
<field name="RebootRequired">True</field>
</param>
-      <param …
```
=> param_parse.py: understand @CopyFieldsFrom

ArduCopter/commands.cpp, ArduSub/commands.cpp, Rover/commands.cpp
Three of our vehicles log the first home position they see into a CMD message.  This adds confusion in the logs as CMD messages can already come from a mission upload, at log-open or actually executing the mission item in auto mode!
The message really adds no benefit as you will only ever get one, regardless of whether HOME is subsequently reset (e.g. by the GCS).  If you're not logging at the time it will be lost.  Compare and contrast vs the `ORGN` message which is logged when the home position is changed and at log open.
The following dump was taken on master.  The vehicle was armed after home was acquired (SITL), and the home was set by right-clicking on the map and choosing "Set Home".  You can see CMD is not logged but the new home *is* logged in ORGN.
``` …
```
=> Remove erratic logging of first home position into CMD log

libraries/AP_Logger/AP_Logger.h, libraries/AP_Logger/AP_Logger_config.h
This is just moving the config stuff into a separate file; should make no functional difference.
=> AP_Logger: create and use AP_Logger_config.h

libraries/AP_SerialManager/AP_SerialManager.cpp
I would allow 2 Mbps to be specified for SITL ON HW.
=> AP_SerialManager: Add 2Mbps for simulator

libraries/AP_HAL_SITL/UARTDriver.cpp
I think this one's too useful to keep out of tree.  Just makes it very easy to quickly test a parser against a capture.
=> AP_HAL_SITL: add option to create uart connection to file

libraries/AP_HAL_ChibiOS/hwdef/VRBrain-v52/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/VRCore-v10/hwdef.dat
these are failing to build on the firmware server
=> hwdef: minimize features on VRBrain-v52 and VRCore-v10

libraries/AP_AHRS/AP_AHRS.cpp
This problem was found by running Plane's rangefinder test like this:
```
./Tools/autotest/autotest.py --gdb --debug --force-ahrs-type=10  build.Plane test.Plane.RangeFinder
```
The test fails because we decide takeoff is complete because the vehicle's relative altitude becomes equal to its AMSL altitude (or its negative, one of the two....) until home is set.  It never takes off from the ground in this case, staying at its starting spot and failing to reach waypoint 5.  This *may* be because we never run the takeoff "do" code because the verify passes instantaenously, so we never unlock the throttle (I'm only theorising here, haven't stepped through it.
This debug code neatly shows the problem in the autotest output:
```
index e69f7abe2b..ee61b0338d 100644
--- a/ArduPlane/ArduPlane.cpp …
```
=> AP_AHRS: get_relative_position_D_home: don't use home until set

Tools/autotest/sim_vehicle.py
This allows sim_vehicle to know we're in WSL2 and auto-forward mavproxy's --out on 14550 and 14551 to the host IP. This makes MissionPlanner automagically work without having to add any flags to sim_vehicle
=> Tools/autotest: automate sim_vehicle in WSL2

libraries/AP_Filesystem/AP_Filesystem_Param.cpp, libraries/AP_Vehicle/AP_Vehicle.cpp
The recent AP_Airspeed changes could lead to invalid parameter counts in param ftp. This fixes the issue plus protects against repeated failures of ftp due to this issue
This issue is most visible on real boards, because AP_InertialSensor::init() is called before AP_Airspeed::init(). The gyro init takes time and the parameters can start to download before the airspeed init has run, which means the default ARSPD_TYPE isn't set yet
=> Param: fixed invalid param count issues

libraries/AP_Airspeed/AP_Airspeed.cpp
A delay in defaults being set can result in getting the wrong params initially if the user is very quick connecting, so moving to constructor. Doesn't help with param conversion, but that only happens once. 
Reported by @tridge: https://discord.com/channels/674039678562861068/800819275069390920/1060053746119352320
https://github.com/ArduPilot/ardupilot/pull/22573
=> AP_Airspeed: move setting of first backend defualts to constructor to avoid race

Tools/environment_install/install-prereqs-ubuntu.sh
translate Mint-codenames to Ubuntu-codenames for not only to support Mint ulyssa, but all current versions
=> Tools:environment_install:install-prereqs-ubuntu.sh: Mint to Ubuntu

Tools/autotest/sim_vehicle.py
Changes sim_vehicle.py's WSL2 method to match [uploader.py's method](https://github.com/ArduPilot/ardupilot/blob/master/Tools/scripts/uploader.py#L75)
This will likely close https://github.com/ArduPilot/ardupilot/issues/22577
=> Tools: fix wsl2 check in sim_vehicle to match uploader.py

Tools/environment_install/install-ROS-ubuntu.sh
Added ardupilot_gazebo package for simulation purposes
=> Tools: Add ardupilot_gazebo install script

Tools/AP_Bootloader/board_types.txt
This PR aligns boards.txt between ArduPilot and PX4. A matching PR will be submitted to the other repo, so that the contexts of boards.txt matches exactly (at the time of drafting).
=> AP_Bootloader: sync ArduPilot and PX4 boards.txt

libraries/AP_GPS/AP_GPS.cpp, libraries/AP_GPS/AP_GPS_NMEA.cpp, libraries/AP_GPS/AP_GPS_NMEA.h
this allows for good yaw even without a RTK fix, which makes yaw with dual-antenna Unicore GPS modules much more useful
this also fixes a bug in reported WGS84 altitude for the 2nd GPS if the two GPS modules have different MSL models
this has been tested successfully with a C-RTK2-HP CUAV GPS on a Pixhawk6X, with GPS yaw reliable throughout the flight
=> AP_GPS: support UNIHEADINGA message for Unicore NMEA

libraries/AC_Avoidance/AP_OADatabase.cpp, libraries/AP_CANManager/AP_CANManager.cpp, libraries/AP_HAL/utility/RingBuffer.h, libraries/AP_HAL_Linux/OpticalFlow_Onboard.cpp, libraries/AP_Scripting/AP_Scripting.cpp, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_FTP.cpp
This saves over 7k of ram and also makes FTP faster as replies can be sent without waiting for the next send window from the main thread
This PR also fixes a nasty bug in handling ObjectBuffer allocation which is what led me to look into the FTP send code. When you have:
```
x = new ObjectBuffer<pending_ftp>(30);
```
then this actually does 3 allocations:
- the ObjectBuffer object
- the ByteBuffer object
- the data buffer itself (the largest allocation)
The problem happens if the allocation of the ObjectBuffer succeeds but the allocation of the ByteBuffer or the data fails then the caller doesn't see it has failed without checking get_size(). The pattern of just checking the pointer returned from the new of ObjectBuffer is the problem. This affects several subsystems, though the one that …
=> MAVLink: send FTP replies from within the FTP thread

ArduCopter/Copter.cpp, ArduCopter/Copter.h, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/AP_Vehicle/AP_Vehicle.h, libraries/GCS_MAVLink/GCS_Common.cpp
This corrects two issues reported with the AUTOPILOT_STATE_FOR_GIMBAL_DEVICE messages sent to our mavlink enabled gimbals (e.g. Gremsy, SToRM32)
- Earth frame rate targets sent instead of the actual body-frame rate (see https://github.com/ArduPilot/ardupilot/issues/22564)
- Zero (0) is sent when the vehicle is landed or disarmed (when disarmed the landed state is always true)
This only affects Copter because it is the only vehicle to override the state sent.  We should eventually extend this to Plane, Rover, etc but this is an existing issue that need not be handled in this PR.
This has been tested in SITL and below are before vs after screens shots of the rates sent.  These rates were generated using a custom debug logging message.
=> Copter: fix yaw feed-forward rate sent to gimbal

Tools/ardupilotwaf/boards.py
this ensures the compiler doesn't assume that new always returns a non-NULL value. Without this the compiler may remove the error path in code like this:
```
MyObject *x = new MyObject;
if (x == nullptr) {
::printf("Alloc failed\n");
}
```
the reason it can do this is the new operator is marked as throwing an exception on failure, which means the error path is unreachable. As we don't have C++ exceptions in ArduPilot could (and does!) have code that ends up losing protection against allocation failures
@andyp1per I believe this is possible the cause of your PixracerPro errors
an example of the impact of this is here:
```
void AP_RollController::autotune_start(void)
{
if (autotune == nullptr) {
autotune = new AP_AutoTune(gains, AP_AutoTune::AUTOTUNE_ROLL, aparm, rate_pid);
if (autotune == …
```
=> waf: add -fcheck-new to g++ build

Dockerfile
Maybe this is a duplicate of this PR. https://github.com/ArduPilot/ardupilot/pull/20948
When I started a container from a Docker-built image and ran SITL, I got an error that mavproxy.py was not found. mavproxy.py was installed in $HOME/.local/bin but no path.
OS: Mac Big Sur 11.6
Docker Desktop 4.8.2
Engine: 20.10.14
Currently mavproxy not found
It should work properly with this PR.
firmware build test for CubeOrange
=> Dockerfile: sim_vehicle.py can not found mavproxy.py

libraries/AP_Scripting/examples/gen_control.lua
control throttle on a generator to achieve a target battery voltage
This is meant to replace throttle governors on some hybrid drone generators. It monitors battery voltage and controls the throttle of the generator to maintain a target voltage using a PI controller
=> AP_Scripting: added example for generator throttle control

Tools/environment_install/install-ROS-ubuntu.sh
Follow up to https://github.com/ArduPilot/ardupilot/pull/22598
- Update prerequisites
- Update workspace and build order.
- Update GZ envs.
**Host**: macOS Monterey 12.6, Intel Mac Pro
**System**: Ubuntu Focal 20.04.5 LTS on VMware Fusion 13.0
1. Run script for package `ros-base`
```bash
./install-ROS-ubuntu.sh -p ros-base
```
2. Check env variables correctly set in .bashrc
```bash
$tail ~/.bashrc
#---------------------------------------------------------
export  PATH=$PATH:$HOME/Code/ardupilot/ardupilot/Tools/autotest
source /home/rhys/ardupilot-ws/devel/setup.bash
export GZ_SIM_SYSTEM_PLUGIN_PATH=/home/rhys/ardupilot_gz_ws/src/ardupilot_gazebo/build:
export GZ_SIM_RESOURCE_PATH=/home/rhys/ardupilot_gz_ws/src/ardupilot_gazebo/models:/home/rhys/ardupilot_gz_ws/src/ardupilot_gazebo/worlds: …
```
=> Tools: Update ardupilot_gazebo install script

libraries/AP_OSD/AP_OSD.h, libraries/AP_OSD/AP_OSD_ParamSetting.cpp, libraries/AP_OSD/AP_OSD_Setting.cpp
This re-works to use the AP pattern of calling `setup_object_defaults` and overriding only where needed. Saves a little flash. Paves the way for tracking defaults correctly for OSD params.
=> AP_OSD: rework param defaulting

ArduCopter/Parameters.cpp, ArduPlane/Parameters.cpp, ArduSub/Parameters.cpp, Blimp/Parameters.cpp, Rover/Parameters.cpp, Tools/AP_Periph/Parameters.cpp, Tools/Replay/Replay.cpp, libraries/AP_Param/AP_Param.cpp, libraries/AP_Param/AP_Param.h, libraries/AP_Vehicle/AP_Vehicle.cpp
Every caller to this method dies if it returns false.  By that time we've lost a lot of information about what's going on, especially if you've got a debugger attached.
I created this PR in frustration after enabling debug caused the autopilot to hard-fault rather than panic!  The reason there was that the Debug statement was referencing a bad pointer value - that hasn't changed, but at least without debug your panic will be in the right place!
All this code does is makes it panic earlier rather than later.
Without debug enabled we save a small amount of flash.
```
Board              AP_Periph  blimp  copter  heli  plane  rover  sub
Durandal                      -16    -24     -16   -32    -24    -24
Hitec-Airspeed     -56                                           
KakuteH7-bdshot …
```
=> Make AP_Param::check_var_info void (die-early, die-often)

ArduCopter/surface_tracking.cpp
This PR is intended to address the problems highlighted here:
https://discuss.ardupilot.org/t/massive-amounts-of-noise-on-us-d1-radar-rangefinder-leads-to-erratic-altitude-hold
Previously surface tracking use the unfiltered last measured range value rather than the filtered and interpolated value. This change corrects.
=> Copter: Use filtered and corrected range finder in surface tracking

Tools/autotest/param_metadata/emit.py, Tools/autotest/param_metadata/param_parse.py, Tools/autotest/param_metadata/rstemit.py
This starts to emit the `SIM_` parameters along with all of the other parameters.
We will need to make sure it's clear in the Wiki that these are simulation parameters (somehow...).
MissionPlanner should start to display these when the vehicle actually has the parameter (in its simulation), which will be cool.
Current XML diff:
```
--- apm.pdef.xml-master	2023-01-07 12:01:30.994715169 +1100
+++ apm.pdef.xml	2023-01-07 12:31:37.822057604 +1100
@@ -23078,6 +23078,154 @@
<field name="UnitText">seconds</field>
</param>
</parameters>
+    <parameters name="SIM_">
+      <param humanName="Baro Noise" name="SIM_BARO_RND" documentation="Amount of (evenly-distributed) noise injected into the 1st baro" user="Advanced">
+        <field name="Units">m</field>
+        <field …
```
=> param_parse.py: emit SIM_ parameters along with everthing else

libraries/AP_Param/AP_Param.cpp
Correct passing through of varargs from macro
The branch was stale when it was merged - this was already present when I tested locally :-/
=> AP_Param: correct compilation when debugging enabled

Tools/autotest/arducopter.py, libraries/AC_AttitudeControl/AC_AttitudeControl.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp, libraries/AC_PID/AC_PID.cpp, libraries/AC_PID/AC_PID.h, libraries/AP_AHRS/AP_AHRS_Logging.cpp, libraries/AP_AHRS/LogStructure.h, libraries/AP_Motors/AP_MotorsMulticopter.cpp, libraries/AP_Motors/AP_Motors_Class.cpp, libraries/AP_Motors/AP_Motors_Class.h
This supersedes https://github.com/ArduPilot/ardupilot/pull/20738 by only providing the necessary features - namely boosting of PD on roll and pitch when the throttle slews above a limit. This dramatically reducing "nodding" - uncommanded pitch and roll variations caused by the copter accelerating into the airstream.
=> Throttle-Gain Boost aka "Anti-Gravity" support

ArduCopter/Copter.h, ArduCopter/Parameters.cpp
This code is in 4.0.7 but not 3.6.11 - i.e. after this someone upgrading from 3.6 to master (and presumably 4.4) won't get this conversion done.
This conversion is flawed in that someone configuring a default for a parameter in a configuration file will have that value over-ridden by this code.
=> Copter: remove FS_OPTIONS parameter conversion

libraries/AP_HAL_ChibiOS/Scheduler.cpp
Fixes compiler error on g++ 12
../../libraries/AP_HAL_ChibiOS/Scheduler.cpp:568:20: error: array subscript 0 is outside array bounds of 'const uint8_t [0]' [-Werror=array-bounds]
568 |         if (addr0[i] != 0) {
=> AP_HAL_ChibiOS: ignore array bounds check while checking 0x0 for writes

Tools/autotest/common.py
floating point storage means an absolute error doesn't work
=> autotest: use percentage error when determining if z is preserved

libraries/AP_HAL_SITL/UARTDriver.cpp, libraries/GCS_MAVLink/GCS_FTP.cpp, libraries/SITL/SITL.cpp, libraries/SITL/SITL.h
this caused ftp downloads to intermittently fail. The cause is the FTP client may ask for a session terminate and then immediately afterwards a ftp open. The open would fail as the ftp session was considered active
this also adds SIM_UART_LOSS to make it easier for us to test lossy links
=> GCS_MAVLink: fixed FTP terminate session error

libraries/AP_Common/MultiHeap.cpp, libraries/AP_Common/MultiHeap.h, libraries/AP_HAL/Util.h, libraries/AP_HAL_ChibiOS/Util.cpp, libraries/AP_HAL_ChibiOS/Util.h, libraries/AP_HAL_ESP32/Util.cpp, libraries/AP_HAL_ESP32/Util.h, libraries/AP_HAL_Linux/Util.cpp, libraries/AP_HAL_Linux/Util.h, libraries/AP_HAL_SITL/Util.cpp, libraries/AP_HAL_SITL/Util.h, libraries/AP_Scripting/lua_scripts.cpp, libraries/AP_Scripting/lua_scripts.h
This allows for the heap to be split across multiple underlying heaps on ChibiOS, which allows for large amount of memory in scripting on boards which don't have a large enough contiguous region of memory (common on many H7 and F7 boards)
Note the change to the API for heap_realloc() is to allow for the old_size parameter in lua alloc() call to be validated in SITL and on ChibiOS debug builds, which provides us with some level of checking against lua heap corruption
This was tested in SITL and with SIM-on-hw using #22474 using aerobatics scripting
=> Scripting: use MultiHeap class for memory

libraries/AP_Mission/AP_Mission.cpp, libraries/AP_Mission/AP_Mission.h, libraries/AP_Scripting/applets/Script_Controller.lua, libraries/AP_Scripting/applets/Script_Controller.md, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/mission-load.lua, libraries/AP_Scripting/generator/description/bindings.desc
replaces #22582 
-adds optional mission file load on scripts switching..can also be used as a mission switcher by itself, if desired
-adds ability to select which aux function (301-307) is used for switching
-no RC channel need be set,ie use GCS only
-if no RC channel set, nothing occurs on restart or boot....script can be active always if desired with no impact if GCS switching is not used or subdirectories not setup
-minimally verbose
@timtuxworth you might be interested in this
=> AP_Scripting:Add mission to Script_Controller and improve

libraries/AP_OpenDroneID/AP_OpenDroneID.cpp, libraries/AP_OpenDroneID/AP_OpenDroneID.h
RemoteID modules are required to set EMERGENCY status on uncontrolled descent or crash. This fixes our implementation to do that, either via existing vehicle crash checking code or via a parachute release
=> AP_OpenDroneID: set EMERGENCY status on crash or chute deploy

libraries/AP_BattMonitor/AP_BattMonitor_Backend.cpp
Fix for the issues from: https://discuss.ardupilot.org/t/no-rtl-engagement-after-a-fail-safe-battery/95312
In that case both low and critical voltage thresholds were the same so the low action of RTL was skipped for the critical action of none.
This is one way to fix of course, if the voltages are not the same but very close the same thing might happen if the battery is dropping fast. Maybe we should enforce some minimum split? Maybe low must be 1v above critical. Not really sure what threshold for capacity should be. We could use a percentage....
The other fix would be to take the low battery action if not in low failsafe and critical action is none, but that makes the failfafe behavior less clear for users.
=> AP_BattMoniter: don't allow equal low and critical FS thresholds

libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS_SIM.cpp
This came up on DevCallEU - that we were defining this `AP_AHRS_SIM` method in AP_AHRS.cpp.  I did that to make that PR easier to review, and said I'd create a PR to move the code.
This PR just moves the code from one file to another.
=> AP_AHRS: move AP_AHRS_SIM::get_results method into AP_AHRS_SIM.cpp

libraries/AC_PID/AC_HELI_PID.cpp, libraries/AC_PID/AC_PID.cpp, libraries/AC_PID/AC_PID_2D.cpp, libraries/AC_PID/AC_PID_Basic.cpp, libraries/APM_Control/AP_PitchController.cpp, libraries/APM_Control/AP_RollController.cpp
This stops setting `_pid_info.I` in a set integrator call, that means that the PID value logged is always the one actually used. This means that after a I reset to 0 the 0 I is never actually logged because it increases in the loop.
The goal is simply to report the actual value used, this is already filled in the various update calls.
It also removes a race where the I value changes depending if you grab it before or after the set integrator calls.
=> AC_PID: don't change pid info I in reset calls, report actual value used.

Tools/ardupilotwaf/boards.py, libraries/AP_CSVReader/AP_CSVReader.cpp, libraries/AP_CSVReader/AP_CSVReader.h, libraries/AP_CSVReader/tests/test_csvreader.cpp, libraries/AP_CSVReader/tests/wscript, libraries/AP_HAL_SITL/UARTDriver.cpp, libraries/AP_HAL_SITL/UARTDriver.h
From the accompanying wiki PR:
```
Replaying serial data from Saleae Logic data captures
=====================================================
Saleae Logic is often used when decoding and debugging protocols for the first time.  The "async serial" analyzers can export the data to a CSV, and this data can then be replayed through ArduPilot's simulated UARTDriver to test parsing of that data.
Serial data is replayed into the simulation at the same rate it appeared on the wire when taking the trace, preserving frame-gaps and the like.
After you have Logic decoding the serial stream, export the data using this interface element:
.. figure:: ../images/saleae-async-save.png
:target: ../_images/saleae-async-save.png
:width: 450px
That data should be in this format:
::
Time [s],Value,Parity …
```
=> SITL: add option to read Saleae Logic Async serial data into UART

ArduCopter/GCS_Copter.cpp, ArduCopter/GCS_Mavlink.cpp
this makes the user experience of a first time install nicer for copters/helis. At the moment the user finds the GCS is not functional, for example flight mode drop-downs don't display. This can be confusing as the user doesn't know about the link between displaying flight modes and the FRAME_CLASS
fixes #22657
Note that when FRAME_CLASS=0 we do allocate a MultiCopter matrix backend, even though there are lots of places that check for motors==nullptr
=> Copter: allow for flight mode UI when FRAME_CLASS=0

libraries/AP_Compass/AP_Compass_Backend.cpp, libraries/AP_Compass/AP_Compass_Calibration.cpp
this fixes a regression from 4.2 to 4.3.
previously we automatically set the diagnoals to 1,1,1 if they were 0,0,0. We don't do that any more. I was helping a user who had copied an old config with 0,0,0 for diagonals and did not understand two things:
- why the compass did not work in 4.3
- why large vehicle mag cal didn't work to fix it
tested on CubeOrange
=> AP_Compass: fixed zero compass diagonals

libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
=> AP_ESC_Telem: correct esc telem debug

libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h, libraries/AP_AHRS/AP_AHRS_Backend.cpp, libraries/AP_AHRS/AP_AHRS_Backend.h, libraries/AP_AHRS/AP_AHRS_DCM.h, libraries/AP_AHRS/AP_AHRS_SIM.cpp, libraries/AP_AHRS/AP_AHRS_SIM.h, libraries/AP_AHRS/AP_AHRS_View.h
This gives callers a fighting chance to not use a wind-vector with an angle of 0 when no wind estimate is available.
No wind estimate is available when using external AHRS, and NavEKF3 can refuse to provide a wind estimate.  At the moment we'll just ignore than and use 0 as a wind angle, which might not be the best choice.
=> Add a boolean AP::ahrs().wind_estimate

Tools/autotest/arducopter.py, Tools/autotest/common.py, libraries/AP_HAL_SITL/RCOutput.cpp, libraries/SITL/SITL.cpp
This was otherwise unused.  Looks like it might have been meant to be used at some stage...
=> Correct use of SIM_ESC_TELEM parameter

libraries/AP_HAL_ChibiOS/hwdef/scripts/convert_betaflight_unified.py
Address some small issues with the betaflight converter script working on other boards:
- if IMU orientation is not set, use a default
=> Cope with sensor alignment not being set in betaflight

libraries/AP_Scripting/examples/rangefinder_test.lua
found while reviewing lua examples..
Ratation -> Rotation
=> AP_Scripting:examples - rangefinder_test.lua : Minor Spelling Correction

libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
log was flooded with resets:
```
2023-01-19 00:17:23.537 IMU0 fast fifo reset 6
2023-01-19 00:17:23.540 IMU0 fast fifo reset 6
2023-01-19 00:17:23.544 IMU0 fast fifo reset 6
2023-01-19 00:17:23.547 IMU0 fast fifo reset 6
2023-01-19 00:17:23.550 IMU0 fast fifo reset 6
2023-01-19 00:17:23.554 IMU0 fast fifo reset 6
2023-01-19 00:17:23.557 IMU0 fast fifo reset 6
2023-01-19 00:17:23.560 IMU0 fast fifo reset 6
2023-01-19 00:17:23.564 IMU0 fast fifo reset 6
2023-01-19 00:17:23.567 IMU0 fast fifo reset 6
2023-01-19 00:17:23.570 IMU0 fast fifo reset 6
2023-01-19 00:17:23.574 IMU0 fast fifo reset 6
2023-01-19 00:17:23.577 IMU0 fast fifo reset 6
2023-01-19 00:17:23.580 IMU0 fast fifo reset 6
2023-01-19 00:17:23.584 IMU0 fast fifo reset 6
2023-01-19 00:17:23.587 IMU0 fast fifo reset 6
2023-01-19 …
```
=> AP_InertialSensor: fixed flood of log with fast fifo reset

libraries/AP_Scripting/applets/plane_ship_landing.lua
if terrain follow is enabled then this would result in mixing a terrain alt with an absolute alt, resulting in attempts to descend to a negative alt
thanks to ARACE for reporting this bug!
=> AP_Scripting: fixed alt frame error in ship landing

libraries/AP_Scripting/generator/description/bindings.desc
figured I would fix Buz's example first since I used that in the Scripting_Controller PR...when its okay, will use it in that
rather than changing his file reading code, I added a data integrity check...minimal changes approach
this checks : 
that each seq number increments and matches the input matrix index (no out of sequence numbers), the first fields are integers, and the lat and long ranges are correct....
tested in SITL
=> AP_Scripting:add error check to mission_load.lua

Tools/scripts/build_options.py
Looks like was maybe copy-paste error. 
'Enable RPM Pin-based sensors' -> 'Enable Generator RPM sensors'
=> Tools:build_options.py rename generator rpm option to reflect what it is

libraries/AC_AttitudeControl/AC_CommandModel.cpp, libraries/AC_AttitudeControl/AC_CommandModel.h, libraries/AC_PID/AC_P.cpp, libraries/AC_PID/AC_P.h, libraries/AC_PID/AC_PI.cpp, libraries/AC_PID/AC_PI.h, libraries/AC_PID/AC_PID.cpp, libraries/AC_PID/AC_PID.h, libraries/AC_PID/AC_PID_2D.cpp, libraries/AC_PID/AC_PID_2D.h, libraries/AC_PID/AC_PID_Basic.cpp, libraries/AC_PID/AC_PID_Basic.h, libraries/AC_PID/AC_PI_2D.cpp, libraries/AC_PID/AC_PI_2D.h, libraries/AC_PID/AC_P_1D.cpp, libraries/AC_PID/AC_P_1D.h, libraries/AC_PID/AC_P_2D.cpp, libraries/AC_PID/AC_P_2D.h, libraries/AP_OSD/AP_OSD.h, libraries/AP_OSD/AP_OSD_ParamSetting.cpp, libraries/AP_OSD/AP_OSD_Setting.cpp, libraries/AP_Param/AP_Param.cpp, libraries/AP_Param/AP_Param.h, libraries/PID/PID.cpp, libraries/PID/PID.h
This allows defaults to be loaded via the param table in the same way as params are referenced. This means we don't have to add to the linked list of defaults changed at run-time saving memory (https://github.com/ArduPilot/ardupilot/issues/22529)
Also means we don't have to keep a second list for embedded defaults.
=> AP_Param: allow class specific defaults using pointer diff. 

libraries/AP_Landing/AP_Landing.cpp, libraries/AP_Landing/AP_Landing.h, libraries/AP_Landing/AP_Landing_Slope.cpp, libraries/AP_TECS/AP_TECS.cpp
It was found that entry airspeed was critical to the pseudo open loop flare.  In this case, the `TECS_LAND_AIRSPEED` needed to be higher than `TRIM_ARSPD_CM`.  The aircraft flew safely at `ARSPD_FBW_MIN` and `TRIM_ARSPD_CM`, but in order to get predictable and safe flare behavior, the aircraft required slightly higher than trim airspeed on flare entry.  It was discovered that this configuration wasn't capable because the current master implementation constrains at `TRIM_ARSPD_CM`.  Test flights were flown with raising this constraint to `ARSPD_FBW_MAX` airspeed with successful results.  However, also unique to this aircraft, the headwind compensation was desired to be disabled.  As this was a static constant in the code, I've added a user defined parameter to allow user to pick their …
=> Plane: Auto Landing Refinement

ArduPlane/tailsitter.cpp, ArduPlane/tailsitter.h
This does a couple of things:
- Only sets motors limit based on elevon and V tail if elevons or V tail is setup.
In motors only assist:
- Use the relax integrator call rather than reset. This means there is no step in outputs as I term is removed. After a second or so it amounts to the same thing as I will be 0.
- Allows motor roll I term to be active in motors only assist if there is no yaw control surface setup. This means there is some method for yaw trimming.
=> Plane: tailsitter: update I reset and limit handling

libraries/AC_WPNav/AC_Circle.cpp
closes #21098 
added parameter description in Circle_rate that it must be smaller than Slew_yaw. Open for feedback.
thanks to @rmackay9 and @IamPete1 for the help. I found what I was doing wrong and will avoid it in future.
=> Copter: AC_WPNav: circle_rate param description added

ArduPlane/tiltrotor.cpp
Fixes a exciting issue where it was possible to manually move the tilts past tilt max thus the `tilt_over_max_angle` check returns true and control of the vectored tilts is handed over to the FW controller while still in a VTOL mode:
https://github.com/ArduPilot/ardupilot/blob/12c24df47653f769b35bce7ba756499c98209f46/ArduPlane/tiltrotor.cpp#L548
Now uses the same constraint as when in position control VTOL modes:
https://github.com/ArduPilot/ardupilot/blob/12c24df47653f769b35bce7ba756499c98209f46/ArduPlane/tiltrotor.cpp#L313
=> Plane: Quadplane: limit manual throttle tilt angle to Q_TILT_MAX

Tools/autotest/arducopter.py, libraries/AP_GyroFFT/AP_GyroFFT.cpp, libraries/AP_GyroFFT/AP_GyroFFT.h, libraries/AP_GyroFFT/tests/test_harmonic_fit.cpp, libraries/AP_GyroFFT/tests/wscript, libraries/AP_HAL/DSP.cpp, libraries/AP_InertialSensor/AP_InertialSensor.cpp, libraries/AP_InertialSensor/AP_InertialSensor.h, libraries/Filter/HarmonicNotchFilter.h
This fixes a bug whereby we would select the wrong harmonic and set the wrong throttle reference when tuning a copter with a higher energy higher frequency harmonic. This occurred for me tuning the Hexsoon 650.
Also fixes a bug where a stack overflow can occur when more than one frequency peak is detected during tuning
Adds better notification of FFT tune success or failure
Changes FFT default frequency range to 50->450Hz to better cover a reasonable range of setups. The old defaults were really only suitable for smaller copters at low revs.
Tested on a Hexsoon 650
=> Correct FFT Tune notch calculation

libraries/AP_VisualOdom/AP_VisualOdom.cpp, libraries/AP_VisualOdom/AP_VisualOdom.h, libraries/AP_VisualOdom/AP_VisualOdom_Backend.h, libraries/AP_VisualOdom/AP_VisualOdom_IntelT265.cpp, libraries/AP_VisualOdom/AP_VisualOdom_IntelT265.h, libraries/RC_Channel/RC_Channel.cpp
This PR improves the AP_VisualOdometry library's handling of [ModalAI VOXL camera](https://ardupilot.org/copter/docs/common-modalai-voxl.html) resets which are different than the IntelT265 camera with which it shares a driver.
When the T265 "resets" it increments the reset_counter and the position jumps (often to a location many meters away).  The yaw normally does not jump.  Resets often occur many times in a row.  The camera continues providing position, velocity and yaw estimates although they unreliable for about 1sec.  These resets normally occur due to high vibration or sunlight hitting the camera.
When the ModalAI "resets" it stops providing position, velocity and yaw estimates for a few seconds.  When it recovers increments the reset_counter and resets the position and yaw back to …
=> AP_VisualOdom: handle ModalAi VOXL resets

ArduCopter/AP_Arming.cpp, Blimp/AP_Arming.cpp, Rover/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.cpp
Follow up to https://github.com/ArduPilot/ardupilot/pull/22706, this one is a change in behavior. 
Currently these call are checking `checks_to_perform == ARMING_CHECK_ALL` rather than `checks_to_perform & ARMING_CHECK_ALL`. This means you will skip all checks except the ones in your arming mask even if the all bit is set. This changes to run all checks whenever the bit is set.
For example if I had `ARMING_CHECK` set to 3 for "ALL" and "Barometer". The current pattern would only check "Barometer". The new pattern checks "ALL" and "Barometer". Of course its not as bad as that because not all the methods follow the bad pattern.
=> AP_Arming: Use arming helper to always check if all bit is set.

libraries/AP_InertialSensor/AP_InertialSensor_BMI088.cpp, libraries/AP_Math/vector3.cpp
A log on a mRoControlZeroH7 seems to show a transfer giving 0xff data from a BMI088:
tested on a CUAV-X7
=> AP_InertialSensor: cope with 0xff from BMI088 gyro

libraries/AP_TemperatureSensor/AP_TemperatureSensor_Params.cpp
correct metadata...discovered as I was preparing to add TempSensors to wiki futures
=> AP_TemperatureSensor:correct TEMP sensor metadata

libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/sport_aerobatics.lua, libraries/AP_Scripting/applets/Aerobatics/FixedWing/Schedules/AirShow.txt, libraries/AP_Scripting/applets/Aerobatics/FixedWing/Schedules/SportPlane_Airshow.txt
Alex (yaapu) has updated his telem to verbally announce tricks selected in the plane_aerobatics and sport_aerobatics scripts so someone using only a TX can turn the selection knob and hear what trick is selected (I have tested and flown this...very cool)
this PR:
- aligns the sports_aerobatics script to use the same gcs messages for trick selection announcements (must be same hash)
- fixes the radius of the rolling circle for trajectory Sports_Plane_Airshow and aligns the messages in that schedule properly
- does the same for the SuperAirShow script
=> Aerobatics scripts updates

libraries/AP_HAL_SITL/UARTDriver.cpp
this fixes a long standing problem with SITL not exiting when you close connection in MissionPlanner
tested on Win10
=> HAL_SITL: exit on close of port 0 on cygwin

libraries/SITL/SIM_FlightAxis.cpp
use AGL height from FlightAxis to populate first rangefinder
=> SITL: fixed SIM lidar for FlightAxis

libraries/AP_RCProtocol/AP_RCProtocol.cpp
This can move us towards not instantiating backends (having an _num_backends) at some stage.
More typical of what we do throughout the code, and makes the derefernces on the subsequent lines a lot more comfortable to casual browsing.
=> AP_RCProtocol: iterate over array size rather than to last entry

Tools/AP_Periph/AP_Periph.cpp, libraries/AP_HAL_ChibiOS/hwdef/MatekL431-HWTelem/hwdef-bl.dat, libraries/AP_HAL_ChibiOS/hwdef/MatekL431-HWTelem/hwdef.dat
It's not possible to change the serial port to be used for accessing telemetry from HW ESC. This PR makes it possible without adding a parameter.
=> AP_Periph: Allow user to change serial port for HW Telem

ArduPlane/Plane.h, ArduPlane/altitude.cpp, ArduPlane/mode_qrtl.cpp, ArduPlane/quadplane.cpp, ArduPlane/quadplane.h
This applies a cone logic similar to copters for QRTL close to home.
This is only a change in behavior in VTOL inside 1.5 radius and under QRTL altitude. The vehicle will always climb up to at least `Q_LAND_FINAL`. It will climb higher if it is further from home as defined by the cone. Once the climb is done, or if already above the cone it will then return at the current altitude. 
Currently close in QRTL's start returning home and climbing up to QRTL altitude. Then start descending again before getting home due to the cone type logic in the VTOL position controller. 
I have not tested extensively and not with ship landing.
edit: maybe I should add that the brown, blue, red and green locations all result in pure VTOL flight. Yellow fly's FW home and transitions for a VTOL landing. Green …
=> Plane: QRTL: use cone for QRTL climb close to home

libraries/AP_Math/vectorN.h, libraries/AP_NavEKF2/AP_NavEKF2_MagFusion.cpp, libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp, libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.h
```
we don't need to persist this across multiple calls as we now fuse all axes on the one step.
I've moved the defintion of these variables to where they are initialised to make it clear they're not used uninitialised.
```
Some of the initialisations could probably be tidied up to `const` the variables at definition, but that would have made this patch look pretty complicated.
Memory saved as expected on CubeBlack:
```
master:  RTL> 96: MEMINFO {brkval : 0, freemem : 59944, freemem32 : 59944}
new: RTL> 163: MEMINFO {brkval : 0, freemem : 60224, freemem32 : 60224}
222
```
(delta is 280)
=> AP_NavEKF3: remove mag_state state

Tools/scripts/size_compare_branches.py
Previously binaries which haven't changed between branches would come out as zero bytes.
After this, if the files are byte-for-byte then we will get a `*` indicating no change in place of the `0`
Interestingly, identical branches don't give identical results for AP_Periph on master.  In fact, we don't get a stable build at all, with it sometimes being identical, sometimes not.  elf_diff shows no changes, because it doesn't care about symbol ordering.
```
-out-branch-f303-Universal/f303-Universal/bin/AP_Periph:     file format elf32-littlearm
+out-master-f303-Universal/f303-Universal/bin/AP_Periph:     file format elf32-littlearm
Disassembly of section startup:
@@ -6973,110 +6973,110 @@
800b218:	e7a8      	b.n	800b16c <uavcan_protocol_param_GetSetRequest_decode+0x70>
...
-0800b21c …
```
=> size_compare_branches.py: add test for identicality

libraries/AP_ADSB/AP_ADSB.cpp
AP_ADSB: bug fix send mavlink status for only two types
=> AP_ADSB: bug fix send mavlink status for only two types

libraries/AC_WPNav/AC_WPNav.h
This PR fixes a simple bug where we use _wp_accel_cmss instead of _wp_accel_c_cmss during a sanity check.
=> AC_WPNav: Fix Bug to use WPNAV_ACCEL_C

libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_AttitudeControl/AC_PosControl.h, libraries/AP_Scheduler/AP_Scheduler.cpp, libraries/AP_Scheduler/AP_Scheduler.h
this fixes a bug if scheduling is very uneven. The particular case I hit was with XPlane simulating a quadplane, and the timing is erratic enough that the XY controller was continually reset during back transitions causing the quadplane to crash. This can happen when you have a very slow loop followed by a fast loop
Using ticks is a much better approach, and tests what is_active means to test
=> AC_AttitudeControl: change to using ticks for is_active

ArduPlane/quadplane.cpp
pilot should be able to override pitch, very important on motor failure to control glide
many thanks to Callan from ALTIUas for  reporting this bug!
tested in RF9.5 with AltiTransition model
=> Plane: transition pitch limit should not apply to FBWA

libraries/AP_Baro/AP_Baro.cpp, libraries/AP_Compass/AP_Compass.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS.h, libraries/AP_InertialSensor/AP_InertialSensor.cpp
This enables each sensor type to be disabled, both for backends that can't provide it and for when you just don't want to use that sensor
tested in SITL with VectorNav backend
=> AP_ExternalAHRS: added EAHRS_SENSORS parameter

ArduPlane/Attitude.cpp, ArduPlane/Plane.h, ArduPlane/RC_Channel.cpp, ArduPlane/control_modes.cpp, ArduPlane/mode.cpp, ArduPlane/mode.h, ArduPlane/mode_autotune.cpp, ArduPlane/system.cpp
Was surprised that Loiter let me autotune pitch and roll, but not yaw....this corrects that
Did not include ACRO or STABILIZE since I thought stick banging would be an issue....but now also allows yaw tuning in FBWA and FBWB switched autotune modes
=> Plane:expand yaw autotune to other modes

libraries/AP_Scripting/applets/Script_Controller.lua
interesting that this extreme copy/paste error would only show up once in a while when running the script...95% of the time it ran perfectly...
=> AP_Scripting:fix duplicate function in Script_Controller

libraries/AC_AttitudeControl/AC_AttitudeControl.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.h
As requested by @bnsgeyer to prevent Heli users seeing the parameter. @rmackay9 needs to go in 4.4 before it goes to beta
=> Move THR_G_BOOST to Multicopter only

libraries/AP_ESC_Telem/AP_ESC_Telem.cpp, libraries/AP_ESC_Telem/AP_ESC_Telem.h
Cleanup of 89bcd656032977d305144898bf0f667797988307 from PR https://github.com/ArduPilot/ardupilot/pull/21662 that also saves 20 bytes! This also fixes a bug where ```AP_ESC_Telem::get_temperature()``` returns false if you've ONLY used external temperature.
=> AP_ESC_Telem: simplify AP_TemperatureSensor integration

libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.cpp, libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.h
Reduce MPPT-specific GCS spam by disabling on-event fault msg strings. When turning on/off there's always a transient fault which causes on/off fault spam. It's not as critical to display these MPPT specific ones any more because the battery fault mavlink messages now include mppt faults.
This also saves 256 bytes of flash!
=> AP_BattMonitor: reduce MPPT gcs spam

ArduPlane/mode.h, ArduPlane/mode_qrtl.cpp, ArduPlane/mode_rtl.cpp
This moves to a shared mode QRTL method for getting the distance at which we just VTOL home. The main change in behavior is for RTL mode with `Q_RTL_MODE` 1 or 2, this moves from RTL radius else waypoint radius to using 1.5 times the larger. The key thing is to make the two modes behave the same. Now no matter RTL or QRTL it will VTOL home at the same radius.
These two poscontrol prints also now report the full radius. Previously they would omit the 1.5 multiplyer.
https://github.com/ArduPilot/ardupilot/blob/8a312d4f342deb327928ee1a6ef9bed4490eab6b/ArduPlane/mode_qrtl.cpp#L60
=> Plane: QRTL: combine threshold radius for QRTL and RTL

libraries/Filter/HarmonicNotchFilter.cpp
Fixes a bug which affect throttle notch FFT tunining
=> Save freq_min_ratio when saving parameters

Tools/autotest/models/xplane_heli.json, Tools/autotest/models/xplane_plane.json, libraries/SITL/SIM_Aircraft.cpp, libraries/SITL/SIM_Aircraft.h, libraries/SITL/SIM_Frame.cpp, libraries/SITL/SIM_Frame.h, libraries/SITL/SIM_GPS.cpp, libraries/SITL/SIM_XPlane.cpp, libraries/SITL/SIM_XPlane.h, libraries/SITL/examples/EvaluateBatteryModel/wscript, libraries/SITL/examples/EvaluateMotorModel/wscript, libraries/SITL/examples/XPlane/xplane_alia.json, libraries/SITL/picojson.cpp, libraries/SITL/picojson.h
this makes use of DRefs to greatly improve XPlane support. It only  supports XPlane 11 and later. Tested on XPlane 11 and 12
The key change is the use of a JSON file to map ArduPilot output channels to DataRefs, and map raw joystick inputs to RC inputs
this gets rid of the awful throttle hack handling, and allows for control of a much wider range of aircraft
This PR comes with two sample json files, one for 5 channel planes and one for helis. Tested on the Cessna Skyhawk plane and R22 Heli.
It also comes with an example for the Alia quadplane in XPlane 12
To use a custom json file copy the base json file to the directory where you start ArduPilot. It should be called xplane_plane.json for planes and xplane_heli.json for helis.
Demo video: https://www.youtube.com/watch?v=bNXrJor4150
=> SITL: new DRef based XPlane backend

libraries/AP_VideoTX/AP_SmartAudio.cpp
When using VTX's with SmartAudio 2.0, the code is unable to learn the correct power levels. This PR changes the learned levels to match the smart audio spec.
Confirmed by a user to now be working: https://discuss.ardupilot.org/t/smartaudio-not-working-correctly-any-longer/96007
=> Learn all the power levels when using SmartAudio 2.0

libraries/AP_NavEKF2/AP_NavEKF2.cpp, libraries/AP_NavEKF3/AP_NavEKF3.cpp
Currently checking health of each core and reporting the message from the primary. If your primary is healthy and second core is not we would currently not give a useful message instead giving the generic unhealthy one.
=> EKF: Pre-arm: report message from correct core

libraries/AP_Logger/LogFile.cpp, libraries/AP_Logger/LogStructure.h
~~Saves lots of empty logs fields.~~
~~Quite tempted to split into multiple messages.~~
~~The only change here is that we would no longer log the safety flag, it would be the only none-zero thing.~~
Now just removes stuff that is not there rather than trying to selectively log.
=> AP_Logger: split MCU from POWR into new messages, POWR log nan if voltages not available

libraries/AP_Camera/AP_RunCam.cpp, libraries/AP_Camera/AP_RunCam.h
Adaptation of AP_Runcam for the Runcam 2 4k version : 
- new camera type (Run24k = 5),
- OSD menu modification for use with no "Save and Exit" option,
- Use same command than Split 2 4k and Hybrid for remote recording.
AP_Runcam.h and AP_Runcam.cpp modified.
=> AP_Camera: add support for Runcam 2 4k

libraries/AP_HAL/UARTDriver.h, libraries/AP_HAL_ChibiOS/UARTDriver.h, libraries/AP_HAL_ESP32/UARTDriver.h, libraries/AP_HAL_ESP32/WiFiDriver.h, libraries/AP_HAL_ESP32/WiFiUdpDriver.h, libraries/GCS_MAVLink/GCS_FTP.cpp, libraries/GCS_MAVLink/GCS_Param.cpp
The function bw_in_kilobytes_per_second() does return a value of zero for baudrates of 4800 and lower, which in https://github.com/ArduPilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS_FTP.cpp#L504 would result in a division by zero.
This is corrected here by changing the function to return bytes/sec and not kBytes/sec.
Note: While I'm not using such small baudrates myself, I have seen that some folks do.
The division by zero should probably be considered serious.
The occasion is grabbed to correct also a long standing bug in the calculation for the parameter upload here https://github.com/ArduPilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS_Param.cpp#L50-L54. A value of zero doesn't cause a real issue here thx to the following if's, but the factor 26 is wrong, i.e., too large by …
=> MAVFtp: possible division by zero, and another correction

libraries/AP_Notify/Buzzer.cpp
The _pin is uint8_t.
It is inherently not less than 0.
Therefore, it is better to compare it with 0.
=> AP_Notify: Match value types

ArduCopter/mode.cpp, libraries/AC_PrecLand/AC_PrecLand.cpp, libraries/AC_PrecLand/AC_PrecLand.h
Currently, if the user were to reposition the vehicle during a Prec Land manually, it would cancel Prec Land and not resume it even if the target was in view (i.e Copter just does a normal land). 
By using PLND_OPTIONS parameter, one can now allow resuming prec land even after a manual reposition. 
This has been tested on SITL
=> Copter: Add option to resume precland after reposiiton

libraries/AC_AutoTune/AC_AutoTune.cpp, libraries/AC_AutoTune/AC_AutoTune.h, libraries/AC_AutoTune/AC_AutoTune_Heli.cpp, libraries/AC_AutoTune/AC_AutoTune_Heli.h, libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
This PR improves the tradheli autotune angle P tuning by looking at the disturbance rejection peak.  Also incorporates a tune check option that allow the user to do a frequency sweep with the tuned values.
=> Tradheli AutoTune: improve angle P tuning

libraries/AP_HAL_ChibiOS/HAL_ChibiOS_Class.cpp, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
This just adds defines in `chibios_hwdef.py`, re-using the existing variable uses to control the watchdog, rather than explicitly checking for being a bootloader build.
=> AP_HAL_ChibiOS: disable watchdog in hwdef.h not in-line in code

ArduPlane/Attitude.cpp, ArduPlane/Parameters.cpp, ArduPlane/defines.h
This removes the direct stick mixing option, preserving it only for use in stabilize mode. In order to not remove stick mixing from a user completely the old direct param setting is now used to enable fbw mixing.
=> Plane: remove direct roll/pitch stick mixing support

libraries/AP_HAL/GPIO.cpp, libraries/AP_HAL/utility/packetise.cpp, libraries/AP_HAL_ChibiOS/Util.cpp, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
previous cleanups made it easy to make it benign to include `GCS_MAVLink/GCS.h` on the bootloader build.  Use it instead of explicit bootloader check.
```
MatekF405                     *      *           *       *                 *      *      *
Pixhawk1-1M                   *      *           *       *                 *      *      * …
```
=> Clean up use of HAL_GCS_ENABLED

Tools/AP_Bootloader/board_types.txt
Allocate board IDs from 1091 to 1095 for Sierra True series of DroneCAN peripherals.
@peterbarker can you check this?
Thank you!
=> Tools: Add Sierra True series periphs

libraries/AP_Logger/LogStructure.h
Base units only in onboard log files.
=> Reserve letter y in AP_Logger for litres/second

Tools/AP_Bootloader/board_types.txt
Adds 2 boards to board_types.txt
=> Tools:board_types.txt - reserve ids for esp32 and esp32s3 ap_periph

libraries/AP_BattMonitor/AP_BattMonitor_Generator.cpp, libraries/AP_Generator/AP_Generator.h, libraries/AP_Generator/AP_Generator_IE_2400.cpp, libraries/AP_Generator/AP_Generator_IE_650_800.cpp, libraries/AP_Generator/AP_Generator_RichenPower.cpp
This makes it clearer what units are being returned by the method.  This clears the way for returning fuel remaining on other units.
=> Tweak generator libary method name

libraries/AP_Mission/AP_Mission.cpp
I initialize the return variable.
This method does not initialize the return variable.
I initialize the return value variable with FALSE.
By this process, if the return value variable is not set in the loop process, it becomes FALSE.
Initializing an automatic variable means that I do not need to be aware of whether or not it is undefined in subsequent processing.
=> AP_Mission: Initialize return variables

.github/workflows/test_size.yml
Unable to install compiler package on server for unknown reason
Replaces https://github.com/ArduPilot/ardupilot/pull/22816
=> .github: remove Disco from size builds

libraries/SITL/SIM_FlightAxis.cpp
broken by motor mask handling code
=> SITL: fixed RealFlight RPM

ArduCopter/Copter.cpp, ArduCopter/Copter.h, ArduCopter/config.h, ArduCopter/heli.cpp, ArduCopter/land_detector.cpp, libraries/AP_Motors/AP_MotorsHeli.h, libraries/AP_Motors/AP_MotorsHeli_Dual.cpp, libraries/AP_Motors/AP_MotorsHeli_Quad.cpp, libraries/AP_Motors/AP_MotorsHeli_RSC.cpp, libraries/AP_Motors/AP_MotorsHeli_RSC.h, libraries/AP_Motors/AP_MotorsHeli_Single.cpp
This PR implements a manual autorotation capability for tradheli frames.  This is the first step toward incorporating autonomous autorotations.  Currently it is only implemented for the Single heli.  After it goes through review, it will be pretty quick to extend it to the dual and quad heli frames as they all use the same RSC class.
This takes manual autorotation out of the SITL only capability and brings it into the actual flight capability.  Manual autorotation has an enable setting that is disabled by default.   There is a feature that allows users that employ ESCs with an autorotation feature (it enables fast spool up) to set the throttle output to enable that feature in the ESC.  This works in conjunction with the bailout feature (in-flight power recovery) that ramps the throttle …
=> Implement manual autorotation feature for Tradheli

libraries/AC_PID/AC_PI.cpp
This fixes a bug caused by me in https://github.com/ArduPilot/ardupilot/pull/22531
I forgot to change to the new define in the param table for the PI controller. I did not spot when comparing defaults in SITL because board heater is the only user, which we don't have in SITL.
Thanks to @pompecukor for the report.
=> AC_PID: AC_PI: fix param defaulting

libraries/RC_Channel/RC_Channel.cpp, libraries/RC_Channel/RC_Channel.h
I should've done this a long time ago; units are being shipped by multiple partners using channel options which have different meanings in my old PR branch and the PR against master.
At least this means they'll only have to fix things once.
=> RC_Channel: allocate channel option for loweheiser manual control

ArduPlane/Attitude.cpp, ArduPlane/Plane.h
`get_speed_scaler()` just returns a plane variable, there is no calculation so passing it through all these functions has no advantage and is confusing.
https://github.com/ArduPilot/ardupilot/blob/c13eada89857e2d3faf0c1129952abc2fc0bd6d9/ArduPlane/Plane.h#L857
=> Plane: stop passing speed_scaler all over the place

ArduCopter/Parameters.h, ArduCopter/mode.h, ArduCopter/mode_rtl.cpp
Co-authored-by: Pierre Kancir <pierre.kancir.emn@gmail.com>
Co-authored-by: Peter Barker<pbarker@barker.dropbear.id.au>
Alternative to https://github.com/ArduPilot/ardupilot/pull/22803/files - but gives type-safety and if another altitude type gets added this there will be a compilation error instead of a silent squashing to relative alt.
Compiles to the exact same code, interestingly.
```
Hitec-Airspeed     0                                                                     
MatekF405                     *      * …
```
=> Copter: Clarify the exclusion determination in the ENUM definition

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/Safety_States.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/lua_bindings.cpp, libraries/AP_Scripting/lua_bindings.h
Adds bindings to allow scripts to be more aware of the safety critical states of the vehicle. If motors are in interlock or E-Stop is active then the script should stop outputting to any motors it might be controlling. If the safety state is disarmed it should not try and output stuff that is not allowed through the safety mask. 
Usefull for some of the new EFI/generator/governor scripts. If safety is active then the engine should not be started. If E-Stop is active then the engine should be stopped.
I ended up adding a passthrough method for safety state to servo channels `hal.util->safety_switch_state()`. We could add a `hal.util` binding like we have for `hal.gpio` but I don't think there would ever be any other methods. Servo seems a logical place for it to live in scripting.
=> AP_Scripting: add bindings for E-Stop, Motor interlock and safety state

libraries/AP_EFI/AP_EFI.cpp, libraries/AP_EFI/AP_EFI_State.h
=> AP_EFI: correct EFI ignition_voltage flag values

Tools/autotest/logger_metadata/emit_html.py, Tools/autotest/logger_metadata/emit_xml.py, Tools/autotest/logger_metadata/parse.py
Follow up from https://github.com/ArduPilot/ardupilot/pull/13858 to allow mission planner to use the new fields which are not currently output for the xml format.  https://github.com/ArduPilot/MissionPlanner/pull/3046
`@FieldBits` gets the converted to the new format, previously it was only parsed in the `xml`. Now it works for `rst` too. This then updates the `xml` parser to output the new bitmask format. `TECS` is the only log using  `@FieldBits` so we could change it, but there is no rush.
Some example xml:
```
<field name="ArmState">
<description>true if vehicle is now armed</description>
</field>
<field name="ArmChecks">
<description>arming bitmask at time of arming</description>
<bitmask>
<bit name="ARMING_CHECK_ALL">
<value>1</value>
</bit>
<bit name="ARMING_CHECK_BARO"> …
```
=> Tools: autotest: logger_metadata: parse `@FieldBits` to new bitmask format and ouput bitmask in xml

libraries/AP_Mission/AP_Mission.cpp
The type of int is basically not used.
Also, the return value of numcommand() is of type uint16_t.
I would change it to uint16_t.
=> AP_Mission: Match variable types

Tools/scripts/build_options.py, libraries/AP_OSD/AP_OSD_Screen.cpp, libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp, libraries/RC_Channel/RC_Channel.cpp
I've run this through the script which disables all build options in turn; the tramp dependency seems to work.
```
Board              AP_Periph  blimp  bootloader  copter  heli  plane  rover  sub
Durandal                      0      0           0       0     0      0      0
Hitec-Airspeed     0                                                         
KakuteH7-bdshot               0      0           0       0     0      0      0
MatekF405                     0      0           0       0     0      0      0
Pixhawk1-1M                   0      0           0       0     0      0      0
f103-QiotekPeriph  0                                                         
f303-Universal     0                                                         
revo-mini                     0      0           0 …
```
=> Remove more code based on AP_VIDEOTX_ENABLED

Tools/autotest/arduplane.py
EKF3 can remain annoyed for a very, very long time after disarm
=> autotest: reboot after DCMFallback test

Tools/environment_install/install-prereqs-mac.sh
https://bugs.python.org/issue45405
Version of pyenv 2.3.12 has patched most versions of python to properly compile with Mac clang 13.  This version is required to properly install python on new machine.
=> Tools: Update pyenv for new MacOS Clang13

libraries/AP_Terrain/TerrainIO.cpp
The configuration formula for loc2.lat and loc1.lat are the same.
In this case, the latitude of loc1 and the latitude of loc2 are the same.
I will simply clarify that the latitudes are the same.
=> AP_Terrain: Explicitly state that they are at the same latitude

Tools/autotest/sim_vehicle.py
Change the WSL2 hostname detection method app from ```route``` to ```ip``` because:
- ```route``` is deprecated, no longer installed in modem Ubuntu builds. Would require installing ```net-tools```.
- ```ip``` is now installed by default on Ubuntu 20+. 
This is a better solution than the original one done in PR https://github.com/ArduPilot/ardupilot/pull/22588/. This is also better than having to install net-tools which was proposed in PR https://github.com/ArduPilot/ardupilot/pull/22824
=> Tools: change WSL2 host IP detection method from route to ip

libraries/AP_Camera/AP_Camera.cpp, libraries/AP_Camera/AP_Camera.h
the parameters and the callers all use float, we unnecessarily lose precision here
thanks to D Przybysz for finding the issue
=> AP_Camera: make trigger dist a float

ArduPlane/AP_Arming.cpp, ArduPlane/ArduPlane.cpp, ArduPlane/GCS_Mavlink.cpp, ArduPlane/Plane.h, ArduPlane/commands_logic.cpp, ArduPlane/quadplane.cpp, ArduPlane/quadplane.h, libraries/AP_Scripting/applets/plane_package_place.lua, libraries/AP_Scripting/applets/plane_package_place.md, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Vehicle/AP_Vehicle.h
This allows quadplanes to do package delivery using a lua script. Documentation is provided in the applets directory
This is a typical mission:
The script adds some PKG_ parameters to control the release height and hold time. It supports both payload place with hover, and waiting for a full landing before releasing the package
Testing has only been done in SITL so far
MissionPlanner needs the following change: https://github.com/ArduPilot/MissionPlanner/pull/3045
Demo video: https://www.youtube.com/watch?v=A8Romq6wiek
=> Plane: support NAV_PAYLOAD_PLACE mission item for quadplanes

libraries/AP_BattMonitor/AP_BattMonitor.cpp, libraries/AP_BattMonitor/AP_BattMonitor.h, libraries/AP_BattMonitor/AP_BattMonitor_EFI.cpp, libraries/AP_BattMonitor/AP_BattMonitor_EFI.h, libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp
As EFI engines become more common it is nice to be able to use the battery failsafe functionality to cope with fuel usage.
This PR maps Ah to Litres and Amps to Litres/hour, which is convenient and easy to explain.
We will need some documentation to explain the setup.
Tested in SITL
=> AP_BattMonitor: support EFI "battery" backend

libraries/AP_HAL_ChibiOS/RCInput.cpp, libraries/AP_HAL_ChibiOS/RCInput.h
The patch reasonably clearly shows that the variable being manipulated here wasn't ever used.
```
Durandal                      0      *           0       0                 0      0      0
Hitec-Airspeed     0                                                                     
KakuteH7-bdshot               -24    *           -24     -24               -24    -24    -24
MatekF405                     -24    *           -24     -24               -32    -32    -32
Pixhawk1-1M                   0      *           0       0                 0      0      0
f103-QiotekPeriph  0                                                                     
f303-Universal     0 …
```
=> AP_HAL_ChibiOS: exclude more code based on HAL_WITH_IO_MCU

libraries/AP_Baro/AP_Baro.cpp
The sanity check for the barometer calls `get_altitude_difference` and compares it to MSL altitude, but `get_altitude_difference` already subtracts field elevation. This means that the error was always approximately equal to the field elevation. This went unnoticed because most people don't fly at fields above 2000m. This can be easily reproduced by flying at the RealFlight Castle airfield in SITL.
=> AP_Baro: fix bug in alt error arming check

Tools/scripts/firmware_version_decoder.py
Properties need to be Enum type to use with defined enums
=> Tools: scripts: Use Enum values over int

Tools/AP_Bootloader/board_types.txt
Add new board id for custom board PixFlamingo L4R5 v1
=> AP_Bootloader: add board id for PixFlamingo L4R5 v1

ArduCopter/ekf_check.cpp
What is set in this variable is a boolean value.
The type of the variable is set to bool.
=> Copter: Match type to set value

Tools/scripts/build_binaries.py, Tools/scripts/size_compare_branches.py
just because we're not showing output doesn't mean we shouldn't raise exceptions on failure!
=> Tools: fix show_output bug in run_program methods

libraries/AP_Scripting/docs/docs.lua
Just corrects a small error in the docs.
=> AP_Scripting: Docs: correct update_rpm and set_rpm_scale markup

Tools/autotest/test_build_options.py, Tools/scripts/build_options.py
This fixes duplicate labels used in NMEA GPS and Airspeed driver features. Also adds an autotest to test duplicate labels in build_options.py and raise an error if we find any.
=> Tools: fix duplicate label for NMEA GPS and Airspeed drivers  

Tools/autotest/param_metadata/param.py, Tools/autotest/param_metadata/param_parse.py, libraries/AP_Scripting/applets/VTOL-quicktune.lua
This allows for parameter docs in lua applets and drivers. This will make using the applets a lot easier for users
we could get rid of the need for // in the lua docs with a bit more regex work
parameter docs added for one script (VTOL-quicktune.lua) as a test
Example output: http://uav.tridgell.net/tmp/Parameters.rst
=> Scripting: added ability to generate param docs for lua applets and drivers

libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32H757xx.py
* Did bench test to see if MCU Voltage for H757 show up on CubeOrangePlus
=> AP_HAL_ChibiOS: add HAL_WITH_MCU_MONITORING define for H757

libraries/AP_Logger/LogStructure.h
will add meaning to Wiki and log analysis tools
```
--- LogMessages.rst-master	2023-02-11 14:03:51.204650105 +1100
+++ LogMessages.rst	2023-02-11 14:04:32.297022568 +1100
@@ -4764,6 +4764,20 @@
| Dist     | Reported distance from sensor                 |
+----------+-----------------------------------------------+
| Stat     | Sensor state                                  |
+|          | Values:                                       |
+|          |                                               |
+|          | +----------------+---+--+                     |
+|          | | NotConnected   | 0 |  |                     |
+|          | +----------------+---+--+                     |
+|          | | NoData         | 1 |  |                     |
+|          | +----------------+---+--+ …
```
=> AP_Logger: add @FieldValueEnum for rangefinder status

libraries/AP_IOMCU/AP_IOMCU.cpp, libraries/AP_IOMCU/AP_IOMCU.h, libraries/AP_IOMCU/iofirmware/iofirmware.cpp
if the IOMCU resets twice in quick succession then the code that restores the safety state while flying can fail, leading to the aircraft trying to continue flying with safety on
This results from two issues:
- a race in handling the last_safety_off variable
- the fact that plane sets the soft_armed state based on safety state
issue reported here: https://discuss.ardupilot.org/t/plane-4-3-stable-release/91727/107
we could change the behaviour of plane so it doesn't set soft armed based on safety by removing this line of code:
https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/AP_Arming.cpp#L383
we would then need to carefully check the consequences of that for takeoff delays etc when safety is on
tested on CubeOrange quadplane and in bench testing
=> AP_IOMCU: fixed an issue with double reset of IOMCU

libraries/AP_Scripting/drivers/mount-djirs2-driver.lua
This fixes a couple of issues discovered during follow-up testing of the recently added DJI RS2 driver (implemented in Lua).
- missing wrap360 added so earth-frame yaws are supported (oops)
- roll direction corrected
These have been tested on real hardware.
=> AP_Scripting: dji rs2 driver fixes

ArduCopter/mode.h, ArduCopter/mode_auto.cpp, ArduSub/Sub.h, ArduSub/commands_logic.cpp, ArduSub/control_auto.cpp, libraries/AC_WPNav/AC_Circle.cpp, libraries/AC_WPNav/AC_Circle.h
It was currently impossible to set the direction of travel in loiter turns even though we have a flag in AP_Mission just to set that. Setting a radius negative would allow you to travel in ccw direction. Also, this aligns with the mavlink message description: https://mavlink.io/en/messages/common.html#MAV_CMD_NAV_LOITER_TURNS
log of SITL testing: https://drive.google.com/drive/folders/1nYc4-lnAd6QgAIBKLO5yVyDQlQWoZ7hC?usp=share_link
=> Copter: Obey loiter_ccw flag for loiter turns

libraries/AP_VideoTX/AP_VideoTX.cpp
I had an incident where the VTX switched into pitmode while flying even though I didn't have VTX control enabled but I did have VTX power on a knob. This makes sure this can't happen.
=> Protect vtx from pitmode changes when not enabled or not armed

libraries/AP_Scripting/lua_boxed_numerics.cpp
It seems unary operators have a second fake argument for some reason. This seems to fix. I can't find any documentation but did find this in our lua source.
https://github.com/ArduPilot/ardupilot/blob/8d1a362db7156aacd402e572a767b71383b1109b/libraries/AP_Scripting/lua/src/lapi.c#L306-L309
=> AP_Scripting: fix uint32 bitwise not

ArduPlane/AP_Arming.cpp, ArduPlane/mode.cpp, ArduPlane/mode.h, ArduPlane/mode_auto.cpp
Moves mode based arming checks to be in one place. It does mean that the Quadplane checks move from pre-arm to arm, so you will not be shouted at until you try and arm, but they can all be resolved by a mode change so I think thats OK. 
RTL is now never armable, currently none quadplanes are allowed to arm in RTL. If there is a good reason for this we can preserve that behavior, I couldn't think of one. 
We move to the same arming fail message as copter. Currently its just `"Mode does not allow arming" now we get for example "RTL mode not armable".
=> Plane: mode allows arming return string allowing quadplane mode checks tidy

Tools/autotest/common.py
makes writing tests for scripts easier as you don't need your own try/except block to make sure the script goes away
=> autotest: add install_example_script_context

Tools/ardupilotwaf/boards.py, Tools/scripts/size_compare_branches.py, libraries/AP_HAL/Semaphores.h, libraries/AP_InternalError/AP_InternalError.h, libraries/AP_Math/AP_Math.h, wscript
This stops us using `__LINE__` in three places when building, which means vertical whitespace and ineffective pragma changes don't modify the build output.
Used to create output on https://github.com/ArduPilot/ardupilot/pull/22893
(edited to make this less confusing, @andyp1per )
=> Add and use waf argument to get consistent builds 

libraries/AP_GPS/AP_GPS_UBLOX.cpp, libraries/AP_GPS/AP_GPS_UBLOX.h
this fixes a pre-arm failure "GPS 1 failing configuration checks" on non-M10 GPS modules, including AP_Periph
it also adds the ublox unconfigured msgs to the DroneCAN GNSS.Status errors field for easier diagnosis of this type of issue in the future
=> AP_GPS: don't try and configure M10 options on non-M10 GPS

ArduPlane/AP_Arming.cpp, ArduPlane/ArduPlane.cpp, ArduPlane/Plane.h, ArduPlane/commands.cpp, Tools/autotest/arduplane.py
when this is called the higher level code has already reset the  barometer and accepted the GPS alt for home, so if we reject it here we end up with a relative alt above home equal to the current error, which can lead to a crash on takeoff
Added autotest AltResetBadGPS that demonstrates the bug.
The scenario is:
- get good GPS lock and normal EKF startup sequence, ready to arm
- an auto VTOL takeoff and mission is setup with relative altitude waypoints
- self-reported GPS accuracy then gets much worse, bad enough to be failing the "good GPS" checks in the EKF
- GPS altitude glitches by a significant amount
- Plane::update_home() does a baro and AHRS/EKF height reset
- EKF rejects the height reset, but baro reset is still done
- plane now reports a relative alt while still on the ground …
=> Plane: fixed home height with bad GPS accuracy pre-arm

libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp
this saves quite a lot of flash
=> AP_RCTelemetry: fixed warning with gcc 12.2

libraries/AP_TECS/AP_TECS.cpp
We were not checking the airspeed on the early return, can lead to divide by zeros.
=> AP_TECS: protect against low airspeed in reset

libraries/AP_OpenDroneID/AP_OpenDroneID.h
required by ASTM F3411, thanks to Brian H for noticing
=> AP_OpenDroneID: fixed static msg timing

ArduPlane/AP_Arming.cpp
Fixes a bug introduced by me in https://github.com/ArduPilot/ardupilot/pull/22812
The old plane arm check used to always display failure however now there pre-arm that makes them extremely spammy. They now honor the `display_failure` flag.
=> Plane: arming: modes: don't always display

libraries/AP_HAL_SITL/SITL_State.cpp
Populating vcas on flight gear SITL. @samuelctabor has been using this for a while on our KHA fork.
=> SITL: Send VCAS in Flightgear packet.

ArduPlane/AP_Arming.cpp, ArduPlane/Attitude.cpp, ArduPlane/commands_logic.cpp, ArduPlane/failsafe.cpp, ArduPlane/is_flying.cpp, ArduPlane/quadplane.cpp, ArduPlane/servos.cpp, ArduPlane/tailsitter.cpp, ArduPlane/takeoff.cpp, ArduPlane/tiltrotor.cpp, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.h
this changes plane to not set soft_armed false when safety off, making plane match copter
instead a new method is_armed_and_safety_off() is used where we do need to know that actuators are active
see also #22899 
test flown on CubeOrange quadplane
=> Plane: added is_armed_and_safety_off()

libraries/AP_OSD/AP_OSD_Backend.h, libraries/AP_OSD/AP_OSD_MSP_DisplayPort.cpp, libraries/AP_OSD/AP_OSD_MSP_DisplayPort.h
makes DisplayPort OSD output of artificial horizon match actual horizon..
tested with DJI goggles running DIsplayPort OSD and Walksnail/Avatar system
and a minor unrelated drive by that @tridge noticed as we were discussing this
=> AP_OSD:add aspect ratio correction for DisplayPort

libraries/AP_Airspeed/AP_Airspeed_NMEA.cpp, libraries/AP_Proximity/AP_Proximity_Cygbot_D1.cpp, libraries/AP_Proximity/AP_Proximity_RPLidarA2.cpp, libraries/AP_Proximity/AP_Proximity_TeraRangerTower.cpp, libraries/AP_Proximity/AP_Proximity_TeraRangerTowerEvo.cpp
Fixes #21836.
The actual return type is int16_t.
Thank you.
=> AP_Proximity/AP_Airspeed: corrected return type of uart::read()

AntennaTracker/GCS_Mavlink.cpp, AntennaTracker/GCS_Mavlink.h, ArduCopter/GCS_Mavlink.cpp, ArduCopter/GCS_Mavlink.h, ArduPlane/GCS_Mavlink.cpp, ArduPlane/GCS_Mavlink.h, ArduSub/GCS_Mavlink.cpp, ArduSub/GCS_Mavlink.h, Blimp/GCS_Mavlink.cpp, Blimp/GCS_Mavlink.h, Rover/GCS_Mavlink.cpp, Rover/GCS_Mavlink.h, Tools/autotest/arduplane.py, Tools/autotest/common.py, libraries/AP_Airspeed/AP_Airspeed.cpp, libraries/AP_Airspeed/AP_Airspeed.h, libraries/AP_Filesystem/AP_Filesystem.cpp, libraries/AP_Filesystem/AP_Filesystem.h, libraries/AP_Filesystem/AP_Filesystem_FATFS.cpp, libraries/AP_Filesystem/AP_Filesystem_FATFS.h, libraries/AP_Filesystem/AP_Filesystem_backend.h, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
```
MANUAL> Got COMMAND_ACK: PREFLIGHT_CALIBRATION: IN_PROGRESS
Calibration response (5)
AP: Updating barometer calibration
AP: Barometer calibration complete
AP: Airspeed 1 calibration started
AP: GPS 1: detected as u-blox at 230400 baud
Got COMMAND_ACK: PREFLIGHT_CALIBRATION: IN_PROGRESS
Calibration response (5)
AP: EKF2 IMU0 MAG0 initial yaw alignment complete
AP: EKF2 IMU1 MAG0 initial yaw alignment complete
Got COMMAND_ACK: PREFLIGHT_CALIBRATION: IN_PROGRESS
Calibration response (5)
AP: EKF3 IMU0 initialised
AP: EKF3 IMU1 initialised
AP: Airspeed 1 calibrated
Got COMMAND_ACK: PREFLIGHT_CALIBRATION: ACCEPTED
Calibrated
AP: EKF3 IMU0 tilt alignment complete
AP: EKF3 IMU1 tilt alignment complete
AP: EKF3 IMU0 MAG0 initial yaw alignment complete
AP: EKF3 IMU1 MAG0 initial yaw alignment …
```
=> add support for mavlink in-progress message

ArduCopter/AP_Arming.cpp, ArduCopter/mode_guided.cpp, libraries/AP_Scripting/applets/RockBlock.lua, libraries/AP_Scripting/applets/RockBlock.md, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/MAVLinkHL.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/GCS_MAVLink/GCS.cpp, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_MAVLink.cpp
This is a (better) replacement for #21068, requiring far fewer modifications to the ArduPilot c code - "Less c, more Lua".
For bonus points, this also adds an example of encoding and decoding MAVLink packet in pure Lua.
This PR adds support for sending & receiving very basic MAVLink telemetry via a RockBlock SBD satellite modem.
It will allow for literal worldwide telemetry coverage for any vehicle fitted with the aforementioned modem.
The modem bandwidth is very low (~50 bytes per 20sec or so), so I've deliberately limited what can be sent and when (1 HIGH_LATENCY2 packet every 20 sec).
Requires https://github.com/stephendade/rockblock2mav at the GCS end to send and receive packets.
Tested with a real vehicle and modem.
=> Add Rockblock Satellite modem support

Tools/AP_Periph/can.cpp
ESC temp is supposed to be in kelvin according to the DSDL: https://github.com/dronecan/DSDL/blob/94ea1e98ffbb9d24b6717905e092dba2f211d1a1/uavcan/equipment/esc/1034.Status.uavcan#L10
But the hwing esc telem parser decodes it as celsius:
=> AP_Periph: Fix hwesc telem temp units

libraries/AP_BattMonitor/AP_BattMonitor.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Params.h, libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.cpp, libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.h
Refactors battery param OPTIONS to use a member function. Then using that I cleaned up some MPPT code using the new options and just considered all enable/disable attempts to be treated as force because all except two places were forcing and the one that didn't wasn't a big deal to just do it. Just saves a single GCS message from going out if you're trying to set it to a state it already was.
=> AP_BattMonitor: refactor Option param usage

libraries/AP_Scripting/drivers/mount-djirs2-driver.lua
This adds support to orient the DJIRS2 gimbals upside down.  It also adds parameter descriptions.
This has been lightly tested on a real gimbal.
=> AP_Scripting: DJIRS2 gimbal driver upside down support

libraries/AP_PiccoloCAN/AP_PiccoloCAN.cpp
ESC voltage and current were (*somehow*) both being scaled incorrectly and reporting at *0.1 the actual value. e.g. ESC at 30V, reported 3V.
Now actually follows what is defined in the protocol spec at https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_PiccoloCAN/piccolo_protocol/ESCVelocity_source.xml:
```
<Data comment="ESC Rail Voltage" inMemoryType="unsigned16" name="voltage" units="0.1V per bit" />
<Data comment="ESC Current. Current IN to the ESC is positive. Current OUT of the ESC is negative" inMemoryType="signed16" name="current" units="0.1A per bit" />
```
=> AP_PiccoloCAN: Fix ESC voltage and current telem scaling

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/src/main.c, libraries/AP_Scripting/tests/luacheck.lua
Adds checking of globals, everything passes already. Was able to do it by parsing the existing docs.
Prevents stuff like this:
```
gcs:not_a_method()
gcs = 10
```
I wasn't able to get parsing of emus from the docs to work, so I have just added them manually, there are only 13. 
This still has all the built in methods. So for example `print('foo')` is not a error.
Luacheck is not return type aware, so we don't get any checking of userdata or ap-objects. So I can still:
```
foo = uint32_t(0)
foo:bar()
```
The VS-Code extension that uses the current docs actually is return type aware and catches stuff like the above. I might poke about and see if we can use what ever it does in CI.
=> AP_Scripting: luacheck: check globals

Tools/AP_Bootloader/AP_Bootloader.cpp, Tools/AP_Bootloader/support.cpp, libraries/AP_HAL_ChibiOS/hwdef/common/stm32_util.c
- entirely remove a method rather than just its body using `#if`s
- use iterators rather than normal for loops
It wasn't *far* over....
=> Fix flash overflow building DrotekP3Pro bootloader

Tools/autotest/arduplane.py, Tools/autotest/common.py, libraries/AP_Mission/AP_Mission.cpp, libraries/AP_Mission/AP_Mission.h, libraries/GCS_MAVLink/GCS_Common.cpp
Add support for JUMP_TAG mission items
DO_JUMP_TAG is same as DO_JUMP except instead of p1 being an index, it's a tag number (can be anything) and it looks for a JUMP_TAG mission item that has p1 as it's tag.
=> Add support for JUMP_TAG mission items

libraries/AP_HAL_ChibiOS/UARTDriver.cpp
This changeset intends to fix Half Duplex communications on Peripherals.
Tested on a MatekL431, with external device connected to `TX2`.
Without this changeset, the periph is unable to read the returned bytes from the devices on the far end.
With this changeset, the periph is able to read the returned bytes from the devices on the far end.
=> AP_HAL_ChibiOS: Fix half-duplex serial on L431 periph nodes

ArduPlane/Parameters.cpp, ArduPlane/mode.h, ArduPlane/mode_takeoff.cpp, ArduPlane/takeoff.cpp
For mode takeoff and auto-takeoff, use a param instead of a fixed 5 deg pitch up during your takeoff run while airspeed is below rotate airspeed.
=> Plane: add takeoff param TKOFF_GND_PITCH

libraries/AP_HAL_Linux/GPIO_RPI.cpp, libraries/AP_HAL_Linux/RCInput_RPI.cpp
Check more mmap() call sites for failure and exit. Also exit when starting on an unknown board.
I'm having some problems bringing up ardupilot on a new Pi4. Since mmap failures will prevent the RCInput driver from working, print and exit().
=> AP_HAL_Linux: Raspberry more initialization checks

libraries/AP_Scripting/applets/RockBlock.lua, libraries/AP_Scripting/examples/MAVLinkHL.lua
Fixed warnings in a lua script that had local variables that mirrored globals because they weren't declared local. These warnings are new and all new PRs that touch the scripts will fail until this is fixed.
```
Checking libraries/AP_Scripting/applets/RockBlock.lua 8 warnings
libraries/AP_Scripting/applets/RockBlock.lua:116:5: mutating non-standard global variable _crc_extra
libraries/AP_Scripting/applets/RockBlock.lua:117:5: mutating non-standard global variable _crc_extra
libraries/AP_Scripting/applets/RockBlock.lua:118:5: mutating non-standard global variable _crc_extra
libraries/AP_Scripting/applets/RockBlock.lua:119:5: mutating non-standard global variable _crc_extra
libraries/AP_Scripting/applets/RockBlock.lua:122:5: mutating non-standard global variable _messages …
```
=> AP_Scripting: fix doc warnings

libraries/AP_Mount/AP_Mount_Gremsy.cpp, libraries/AP_Mount/AP_Mount_Gremsy.h, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_MAVLink.cpp
Tested on a PixyU connected to SITL.
Note that most of the nullptr checks are can't-happens due to checks elsewhere.
Note also that we can save some bytes in the send-message methods in future by using `link->set_message(type, pkt)`.   Not done here to make backport easier.
This work sponsored by Harris Aerial.
=> AP_Mount: correct double-mapping of port to channel number

libraries/AP_Scripting/generator/description/bindings.desc
this avoids the interrupt handling bug. Proper fix in 4.4.x
=> AP_Scripting: disable PWMSource in scripts for 4.3.4

Tools/autotest/quadplane.py, libraries/AP_Scripting/applets/VTOL-quicktune.lua
makes it possible to use aux buttons in MissionPlanner
=> AP_Scripting: change VTOL-quicktune to use cached aux

libraries/AP_BattMonitor/AP_BattMonitor.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Backend.h, libraries/AP_BattMonitor/AP_BattMonitor_Params.h, libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.cpp
This fixes my PR-foo mixup on https://github.com/ArduPilot/ardupilot/pull/22964 (aka v1)
PR https://github.com/ArduPilot/ardupilot/pull/22965 (mppt enable) was on top of this v1 version and in that PR it was suggested to move option_is_set() from _Param to _Backend. I did but since it was a different branch, the v1 branch PR didn't change so when @khancyr reviewed and approved it I had thought I had updated it before I merged. My mistake, I should have double-checked before merging :(
Sorry about the commit churn.
=> AP_BattMonitor: refactor Option param usage v2

libraries/AP_Mount/AP_Mount_Gremsy.cpp, libraries/GCS_MAVLink/GCS.cpp, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/MissionItemProtocol.cpp, libraries/GCS_MAVLink/MissionItemProtocol.h
This removes a lot of boiler-plate around sending messages on a mavlink channel.  Now you just create a `static const` message and ask the link to send it.
I believe this may also fix a problem where downloading fence points using the old protocol may not be checking for buffer space before sending.
Needs testing on a Gremsy, which I will do.
=> Have send_message(id, buffer) check size, use it in Gremsy

Tools/AP_Periph/can.cpp
Fixed a bug in AP_Peirph which was sending GNSS::HEADING at the same interval as GNSS:FIX2 because it wasn't correctly keeping track of time.
=> Periph: fix sending GNSS:Heading packet at correct interval

ArduPlane/RC_Channel.cpp, ArduPlane/quadplane.cpp
this prevents yaw from rudder arming on 2nd flight
after 1st flight in QHOVER if you don't change mode then throttle_wait is not reset as we don't re-enter the mode
=> Plane: re-init throttle wait on quadplane arm and disarm

ArduPlane/tiltrotor.cpp
this prevents a case where we can demand unlimited vectored yaw, leading to loss of control
this was particularly noticible before the fix in #23023 - if you armed for a 2nd time in QHOVER after moving the throttle above 10% so throttle_wait was cleared then the motors would try to tilt fully so one motor is in fwd flight position. This would cause a prop strike while on the ground
Bug was introduced in https://github.com/ArduPilot/ardupilot/pull/22376 - bug not present in 4.3.x
=> Plane: constrain tilt range for vectored yaw

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py, libraries/AP_HAL_ChibiOS/system.cpp
... these are really quite expensive
~~Also adds a test to make sure `MatekF405-CAN` bootloader compiles (which it doesn't in master ATM)~~  Will PR the test after this is merged
=> AP_HAL_ChibiOS: Do not include debug variables in bootloader build

Tools/autotest/common.py
All callers were supplying a value, and it isn't clear why zero makes a good default.
=> autotest: remove default value for paramValue in setGCSfailsafe

Tools/autotest/arduplane.py
Improvements to PR #23032 as suggested by @peterbarker
Cleans up multiple calls to `set_parameter` with a single call to `set_parameters`.
Replaces `delay_sim_time` with timeouts on `wait_mode`, hopefully speeding up this test somewhat.
=> Plane: Cleanup GCS autotest

libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.cpp, libraries/AP_GPS/AP_GPS_UAVCAN.cpp, libraries/AP_UAVCAN/AP_UAVCAN.cpp
Under Alpine linux, with g++11 and g++12
```
#0 33.08 ../../libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.cpp:160:10: error: 'isnanf' was not declared in this scope; did you mean 'isnan'?
#0 33.08   160 |     if (!isnanf(temperature_K) && temperature_K > 0) {
#0 33.08       |          ^~~~~~
#0 33.08       |          isnan
#0 33.08 compilation terminated due to -Wfatal-errors.
#0 33.08 
#0 34.47 Waf: Leaving directory `/ardupilot/src/build/sitl'
#0 34.47 Build failed
#0 34.47  -> task in 'objs/AP_BattMonitor' failed (exit status 1): 
#0 34.47 	{task 140300009668304: cxx AP_BattMonitor_UAVCAN.cpp -> AP_BattMonitor_UAVCAN.cpp.0.o}
#0 34.47  (run with -v to display more information)
------
```
those are the only place we are using isnanf that need math.h
=> Remove isnanf

.github/workflows/test_size.yml
- ensure that the MatekF405-CAN bootloader continues to build - AFAIK it's the closest on flash space
- tidy the CI test somewhat by creating more variables to indicate periph or bootlaoder builds
- probably include tabs rather than spaces in the yml and need to force-push to correct problem
=> .github: test MatekF405-CAN bootloader builds

libraries/AP_Notify/SITL_SFML_LED.cpp, libraries/AP_Notify/SITL_SFML_LED.h, libraries/SITL/SIM_RGBLED.cpp, libraries/SITL/SIM_RGBLED.h, libraries/SITL/SIM_ToshibaLED.cpp, libraries/SITL/SIM_ToshibaLED.h
This incorporates the bugfix from https://github.com/ArduPilot/ardupilot/pull/23044 which leds simulated SerialLEDs work.
This change means the SITL layer does the displaying of the ToshibaLED state, rather than a special backend in `libraries/AP_Notify`.  This means the data must travel over the simulated serial bus and then be displayed by the simualted ToshibaLED.
This new structure will allow for graphical simulation of i2c-connected LEDs other than ToshibaLED, which should aid development.
All tested in SITL, including the SerialLED stuff which works post-afore-mentioned bugfix.  The SerialLED stuff should also probably move down to the SITL directory at some stage - but that would require creation of a `SITL::SIM_ProfiLED` class.
=> Use simulated i2c-connected ToshibaLED for graphical LED display

ArduSub/Log.cpp, libraries/AP_Logger/LogStructure.h, libraries/AP_Motors/AP_MotorsMulticopter.cpp
We don't actually log the motors output throttle anywhere. This can be different to input throttle in CTUN in cases of motor saturation where throttle mix params allow boosting of throttle.
This also removes duplicate log documentation that was in SUB.
=> AP_Motors: add throttle output logging.

libraries/AP_HAL_ChibiOS/hwdef/CUAV-X7/hwdef.dat
Corrects the 6.6v pin scale factor, bug reported on discord. https://discord.com/channels/674039678562861068/780728024756781056/1071757983937216522
Of course there is the usual dilemma about whether or not its safe to correct the bug and mess up peoples parameters.....  I suspect this pin is very rarely used.
=> ChibioOS: hwdef: CUAV-X7: correct 6.6v ADC scale factor

libraries/AP_DAL/AP_DAL.cpp, libraries/AP_DAL/AP_DAL_Compass.cpp
Was poking about trying to diagnose EKF compass stuff, turns out we never actually fill in `learn_offsets_enabled` so its always false.
It is used here in EKF3:
https://github.com/ArduPilot/ardupilot/blob/bb05f405600c5bf4244ded8df859c67c91b34176/libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp#L297-L307
And here in EKF2:
https://github.com/ArduPilot/ardupilot/blob/bb05f405600c5bf4244ded8df859c67c91b34176/libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp#L242-L252
So this will change behavior with `COMPASS_LEARN` 3.
After finding that I did a sweep of all the structures, the rest are all filled in correctly except the EKF type. Its only used in one place for a init message so its not nearly as nasty. We might just want to remove the variable. …
=> AP_Dal: populate missing fields `learn_offsets_enabled` and `ekf_type`

libraries/AP_InertialSensor/AP_InertialSensor_BMI088.cpp
this error happens often enough that it is frustrating for users who can't arm, which just encourages use of forced arming.
logs show this happening at a rate of once every few seconds, which doesn't impact on the usability of the gyro (which is at 2kHz), but does prevent arming with this error incremement
=> AP_InertialSensor: removed the error count on BMI088 0xff data

libraries/AC_AttitudeControl/AC_WeatherVane.cpp, libraries/AC_AttitudeControl/AC_WeatherVane.h
alternate to #23043 ....personally I don't think making it a direction value makes sense...better an operation option and its double the flash (although 16 vs 8 bytes is not significant)
=> AC_Attitude:add TKOFF/LAND only weathervane option

ArduCopter/Parameters.cpp, ArduCopter/system.cpp, ArduPlane/Parameters.cpp, ArduPlane/system.cpp, ArduSub/Parameters.cpp, ArduSub/system.cpp, Rover/Parameters.cpp, Rover/system.cpp, Tools/autotest/arduplane.py, Tools/autotest/common.py, Tools/autotest/rover.py, libraries/AP_Camera/AP_Camera.cpp, libraries/AP_Camera/AP_Camera.h, libraries/AP_Camera/AP_Camera_Backend.cpp, libraries/AP_Camera/AP_Camera_Backend.h, libraries/AP_Camera/AP_Camera_Logging.cpp, libraries/AP_Camera/AP_Camera_MAVLink.cpp, libraries/AP_Camera/AP_Camera_MAVLink.h, libraries/AP_Camera/AP_Camera_Mount.cpp, libraries/AP_Camera/AP_Camera_Mount.h, libraries/AP_Camera/AP_Camera_Params.cpp, libraries/AP_Camera/AP_Camera_Params.h, libraries/AP_Camera/AP_Camera_Relay.cpp, libraries/AP_Camera/AP_Camera_Relay.h, libraries/AP_Camera/AP_Camera_Servo.cpp, libraries/AP_Camera/AP_Camera_Servo.h, libraries/AP_Camera/AP_Camera_SoloGimbal.cpp, libraries/AP_Camera/AP_Camera_SoloGimbal.h, libraries/AP_Camera/LogStructure.h
This restructures the AP_Camera library into our regular frontend/backend split which provides these advantages:
1. easier to add support for new cameras
2. easier support of multiple cameras (this PR adds support for a 2nd camera but adding even more is trivial)
The changes include:
- New backend classes created for Servo, Relay, SoloGimbal, Mount and MAVLink
- Most parameters are moved into a new AP_Camera_Params class.  parameter conversion is done for these params
- CAM_TRIGG_TYPE becomes CAM1_TYPE
- CAM_DURATION becomes CAM1_DURATION.  Note change of scale from deci-seconds to seconds
- CAM_MIN_**INTERVAL** becomes CAM1_**INTRVAL**_MIN.  Note change of scale from milliseconds to seconds.  Also missing "E"
- CAM_**FEEDBACK**\_PIN and POL become CAM1_**FEEDBAK**_PIN and POL (Note …
=> AP_Camera: frontend/backend split and support for 2 cameras

Tools/autotest/arducopter.py, libraries/AP_Proximity/AP_Proximity_LightWareSF45B.h, libraries/Filter/ModeFilter.cpp
During testing with the SF45b I found that it was unable to detect a person standing in front of the drone.  The reason was that the SF45b uses a 5 element mode filter and the person was only 2 elements wide (approximately 6 degrees).  This PR reduces the mode filter to 3 elements so that narrower objects can be detected.
This has been tested on real hardware.
=> AP_Proximity: SF45b mode filter reduced to detect narrower obstacles

libraries/AP_Compass/AP_Compass_config.h, libraries/AP_HAL_ChibiOS/hwdef/f103-GPS/hwdef.dat
We noted this oddity on the DevCall and I said I'd make a future PR to move this definition around.  This is that - if you don't want a compass on an AP_Periph you should put that in the hwdef.
I built all of the periphs and none change - particularly the f103s:
```
VRUBrain-v51,
ZubaxGNSS,0
airbotf4,
bbbmini,
blue,
crazyflie2,
edge,
erlebrain2,
f103-ADSB,*
f103-Airspeed,0
f103-GPS,0
f103-HWESC,0
f103-QiotekPeriph,*
f103-RangeFinder,*
f103-Trigger,0
f303-GPS,*
f303-HWESC,*
f303-M10025,*
f303-M10070,0
f303-MatekGPS,*
f303-PWM,*
f303-TempSensor,*
f303-Universal,0
f405-MatekAirspeed,0
f405-MatekGPS,0
fmuv2,
fmuv3,
fmuv3-bdshot,
fmuv5,
iomcu,
iomcu_f103_8MHz,
luminousbee4,
luminousbee5,
mRo-M10095,0
```
=> Tidy the BMM150-on-f103 compass oddity into hwdef files

libraries/AP_RangeFinder/AP_RangeFinder.cpp, libraries/AP_RangeFinder/AP_RangeFinder_USD1_CAN.cpp, libraries/AP_RangeFinder/AP_RangeFinder_USD1_CAN.h
This allows for multiple CAN USD-D1s.
Currently, if you attach multiple, the values add up.
=> AP_RangeFinder: Allow multiple USD-D1-CAN

Tools/scripts/build_options.py, Tools/scripts/extract_features.py, libraries/AP_GPS/AP_GPS_UAVCAN.cpp, libraries/AP_GPS/AP_GPS_UAVCAN.h, libraries/AP_UAVCAN/AP_UAVCAN.cpp, libraries/AP_UAVCAN/AP_UAVCAN.h
Add a UAVCAN Options bit to send GNSS packets to that bus. This works with or without a GPS attached but is more interesting when one is :)
=> AP_UAVCAN: add option to send GPS

ArduPlane/mode.h, ArduPlane/mode_takeoff.cpp, ArduPlane/takeoff.cpp
This is another step closer to unifying AUTO-takeoff and Mode TAKEOFF so that the params are shared and, thus, less confusing.
Existing behavior:
Mode TAKEOFF:
- On takeoff, keep wings level until you reach TKOFF_LVL_ALT (default 20) or if altitude is completed when reaching TKOFF_ALT.
- Desired Roll restriction is removed immediately.
Mode AUTO-takeoff
- Keep wings level until 5m.
- Allow normal full roll range at 15m.
- Scale the limit between those altitudes
New behavior that mode methods will share:
- Keep wings level until TKOFF_LVL_ALT (default 5).
- Allow normal full range at MIN(TKOFF_LVL_ALT*3,TKOFF_ALT).
- Scale the limit between those altitudes
=> Plane: Auto takeoff roll-limits to use TKOFF_LVL_ALT

Rover/Parameters.cpp
Continuing on from #23048, this PR updates the description for ``MIS_DONE_BEHAVE`` to make it more clear if there's a mode change.
=> Rover: Better wording for MIS_DONE_BEHAVE (NFC)

libraries/AP_Mount/AP_Mount.cpp
Also adds a sanity check on a public method
I've tested this on a Gremsy T3v3 by setting the gimbal's component ID to GIMBAL2 and executing a retract command.
```
STABILIZE> long DO_GIMBAL_MANAGER_PITCHYAW 0 0 0 0 1 0 0
STABILIZE> Got COMMAND_ACK: DO_GIMBAL_MANAGER_PITCHYAW: ACCEPTED
STABILIZE> 
STABILIZE> long DO_GIMBAL_MANAGER_PITCHYAW 0 0 0 0 1 0 1
STABILIZE> Got COMMAND_ACK: DO_GIMBAL_MANAGER_PITCHYAW: FAILED
long DO_GIMBAL_MANAGER_PITCHYAW 0 0 0 0 1 0 2
STABILIZE> Got COMMAND_ACK: DO_GIMBAL_MANAGER_PITCHYAW: ACCEPTED
```
The gimbal retracted appropriately.
=> AP_Mount: allow gimbals other than primary to be retracted/neutralised

libraries/GCS_MAVLink/GCS_Common.cpp
When using a battery under 100% charged that has a generator or MPPT available to charge during flight, it's possible to calculate and report a capacity_remaining_pct() greater than 100%. [MAVLink spec for BATTERY_STATUS](https://github.com/ArduPilot/mavlink/blob/734d04188897f70c8b19e119543a395d4f61d6de/message_definitions/v1.0/common.xml#L5141) specifies a valid range as 0-100. Mission Planner is correctly-ish treating 101% as 0%. MAVProxy is not effected (it correctly-ish shows >100% values).
The other battery % packets such as HIGH_LATENCY and SYS_STATUS do not specify an out-of-range high value.
=> GCS_MAVLink: constrain battery % to 0-100

AntennaTracker/Parameters.h
remove some wrong comments from a copy/paste that aren't even there in other vehicles
=> Tracker: remove wrong comments

libraries/AP_Mission/AP_Mission_Commands.cpp, libraries/AP_Mount/AP_Mount.cpp, libraries/AP_Mount/AP_Mount.h
Turn the instance back into an object as quickly as possible.  This helps prevent dereferencing things by the instance when we shouldn't.
```
Durandal                      -64    *           -72     -72               -72    -72    -72
KakuteH7-bdshot               -168   *           -192    -192              -184   -184   -192
MatekF405                     -144   *           -168    -160              -160   -160   -160
Pixhawk1-1M                   *      *           *       *                 *      *      * …
```
=> Use backend * throughout AP_Mount frontend 

libraries/AP_Winch/AP_Winch_Daiwa.cpp
Removed if statement forcing baud rate of 115200 to be consistent with documentation, and to avoid issues in future if manufacturer changes baud rate again. Correct baud rate is 38400. Documentation needs to be updated as well. 
Confirmed with manufacturer, and with a winch on v1.02. Also confirmed w/ manufacturer that newest winches on v1.04 also use 38400. 
From issue: https://discuss.ardupilot.org/t/daiwa-winch-not-working-prearm-winch-unhealthy-documentation-drivers-outdated-for-current-units/97532
=> AP_Winch: Fix baud rate handling in AP_Winch_Daiwa

libraries/AP_HAL/GPIO.cpp, libraries/AP_HAL/GPIO.h, libraries/AP_Scripting/AP_Scripting.cpp, libraries/AP_Scripting/AP_Scripting.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/lua_bindings.cpp, libraries/AP_Scripting/lua_bindings.h
This fixes a crash caused by deleting the scripting `PWMSource` object. The object registers a interrupt callback, so when its deleted the callback points to nothing and we crash. 
This moves to handle in a similar way to `i2c` Scripting not the script keeps the object and give the script a pointer to it. This means we can delete it properly if we need to. This does limit the number of `PWMSource` objects to 4, but I think that OK (we can change to more is we need to).
=> AP_Scripting: fix PWMSource deletion crash

libraries/SITL/SIM_Gimbal.cpp
=> SITL: correct use of uninitialised stack data in SIM_Gimbal

Tools/AP_Periph/AP_Periph.cpp, Tools/AP_Periph/can.cpp, libraries/AP_HAL_ChibiOS/hwdef/MatekL431-Rangefinder/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/f103-RangeFinder/hwdef.dat, libraries/AP_RangeFinder/AP_RangeFinder.cpp, libraries/AP_RangeFinder/AP_RangeFinder.h
This fixes a few issues with peripheral rangefinder init
- cope with sensors that take a long time to startup (eg. LW20)
- cope with sensors that are powered on separately to the periph CAN node
- cope with boards without a uart and only i2c sensors
issue reported here: https://discuss.ardupilot.org/t/ap-periph-not-working-with-lightwarei2c/95913
=> AP_Periph: improved probing of rangefinders

libraries/AP_Motors/AP_MotorsMulticopter.cpp, libraries/AP_Motors/AP_MotorsMulticopter.h, libraries/AP_Motors/AP_Motors_Class.cpp, libraries/AP_Motors/AP_Motors_Class.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
For vehicles with rudders on tilting motors, which should be fixed wing rudder in fwd flight and VTOL rudder in hover
=> Scripting: implement a tilting rudder as a lua script

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_InertialSensor/AP_InertialSensor.h
I forgot to reboot and got no batch logging, not for the first time.....
Of course, runtime init would be better, but would be a significantly more complex patch....
=> AP_Arming: add INS batch sampling initialized check 

libraries/AP_GPS/AP_GPS_NMEA.cpp
wont reset GPS to rover mode (moving baseline) if attached as type 24....this correct that
=> AP_GPS:make Unicore reset to rover in all cases

Tools/AP_Periph/can.cpp, libraries/AP_Compass/AP_Compass_MMC5xx3.cpp
we only read mag on the vehicles at 10Hz. Some magnetometers were reporting data at 500Hz (see MMC5xx3 driver)
by sampling more slowly the data is accumulated and averaged on the node which saves a lot of bandwidth
this also drops the MMC5xx3 driver to 100Hz, from current I2C read at 1kHz. That used too much I2C bandwidth
=> AP_Periph: limit peripheral mag to 25Hz by default

libraries/AP_Mount/AP_Mount_Alexmos.h, libraries/AP_Mount/AP_Mount_Gremsy.cpp, libraries/AP_Mount/AP_Mount_Gremsy.h, libraries/AP_Mount/AP_Mount_SToRM32.cpp, libraries/AP_Mount/AP_Mount_SToRM32.h, libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp, libraries/AP_Mount/AP_Mount_SToRM32_serial.h
just copy in the one from the parent class
```
Durandal                      *      *           -72     -72               -72    -72    -72
KakuteH7-bdshot               *      *           -72     -72               -72    -72    -72
MatekF405                     *      *           -8      -16               -16    -16    -16
Pixhawk1-1M                   *      *           *       *                 *      *      *
f103-QiotekPeriph  0                                                                     
f303-Universal     0                                                                     
iomcu …
```
=> AP_Mount: remove redundant constructors

ArduCopter/Copter.cpp, ArduCopter/Copter.h, ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduCopter/sensors.cpp, ArduCopter/surface_tracking.cpp, ArduSub/sensors.cpp, libraries/AC_WPNav/AC_Circle.cpp, libraries/AC_WPNav/AC_Circle.h, libraries/AC_WPNav/AC_WPNav.cpp, libraries/AC_WPNav/AC_WPNav.h
This PR adds a time constant based decay in the terrain height measured by the range finder. This is intended to be used to smooth ground perterbations and sensor noise.
=> Copter: add surface tracking time constant

Tools/AP_Bootloader/board_types.txt
these are clashing with board IDs already in-tree
=> board_types.txt: move rFCU and rGNSS to different IDs

ArduCopter/Copter.cpp, ArduCopter/mode_systemid.cpp
This is a simple fix to re-enable the writing of PID log messages when a copter enters system identification mode. This issue currently occurs on all versions of Copter-4.3.
Explanation:
I noticed that the PID log messages are disabled when entering the SystemID mode while I was experimenting with the ArduCopter Simulink model. These messages are required when feeding part of the flight using SystemID to the Matlab scripts.
The missing PID messages seem to be caused by #21372 which separated the writing of PIDs from the attitude messages. However, since the SystemID mode records both attitude and PIDs at its own rate and not at the full loop rate, it is necessary to write the PIDs from this mode as well.
I also added the `logs_attitude` condition mask to the PID writing in the …
=> Copter: Re-enable PID logging in SystemID mode

libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/MAVLink_routing.cpp, libraries/GCS_MAVLink/MAVLink_routing.h, libraries/GCS_MAVLink/examples/routing/routing.cpp
Our one user of check_and_forward passes itself through rather than its channel ID through.
This forms the basis for a future PR allowing filtering of mavlink messages.
=> GCS_MAVLink: use GCS_MAVLINK& when routing

ArduCopter/Copter.h, ArduCopter/Parameters.cpp, ArduCopter/defines.h, ArduCopter/events.cpp
This PR provides an option to change mode to Break Mode in the event of a Radio Failsafe. If GPS is not available a no-gps land is done.
This is required for some industrial operations where the aircraft is connected to tethers and carrying a load. In this case an RTL or payload release could both be dangerous. By changing to Break Mode the operators have the remaining battery capacity to solve the problem. This may be achieved by moving the pilot radio to a better line of sight position, moving to GCS controlled operations, or simply clearing the area of personnel and detaching or securing tethers.
=> Copter: Add Radio Failsafe Brake Mode option

libraries/AP_Camera/AP_Camera.cpp, libraries/AP_Camera/AP_Camera.h
This PR is built on top of https://github.com/ArduPilot/ardupilot/pull/23119  .  There is only one commit on top of that other PR
It (hopefully) simply makes the code use fewer bytes.
Comparison vs the parent PR, #23119 :
```
Durandal                      -168   *           -200    -200              -200   -200   -200
Hitec-Airspeed     0                                                                     
KakuteH7-bdshot               -264   *           -264    -264              -264   -272   -272
MatekF405                     -264   *           -264    -264              -272   -272   -264
Pixhawk1-1M                   -256   *           -280    -280              -280   -280   -280 …
```
=> Save some bytes in the Camera library

ArduPlane/commands_logic.cpp, ArduSub/commands_logic.cpp, Rover/mode_auto.cpp, libraries/AP_Mission/AP_Mission.cpp
This fixes a potentially dangerous fallthough that could happen if AP_CAMERA_ENABLED is false.
The bug could lead to DO_DIGICAM_CONFIGURE or DO_DIGICAM_CONTROL message accidentally executing the DO_PARACHUTE command.
This PR also includes a drive-by fix to remove the unused [DO_CONTROL_VIDEO command](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1111).  Mission Planner does not display this command and it seems that if it did, all we would end up with is a Panic in SITL and an ignored command on a real vehicle.
=> AP_Mission: fix AP_CAMERA_ENABLED related fallthrough

ArduCopter/mode_auto.cpp, Tools/autotest/arducopter.py
I think the reporting can be a little confusing for pause and resume in AUTO. If either the GCS or companion computer get out of sync with AP's paused sate, then the GCS will receive reports for the command failing. This isn't the case for GUIDED mode where the command is always accepted.
If the aircraft is already paused, rather than reporting a failure to pause, and sending the GCS a status text message, we can just return success as the aircraft has already paused. Similarly for resume.
=> Copter: pause resume reporting

Tools/scripts/size_compare_branches.py
The vast majority of the time I run this tool with `--no-elf-diff` - but it is painful if you forget it and really didn't want it.
The original script didn't handle multiple boads/vehicles at once, so this really was an anachronism.
=> Tools: size_compare_branches.py: change --no-elf-diff into --elf-diff

libraries/AP_Airspeed/AP_Airspeed.cpp
```
Durandal                      *      *           8       8                 8      16     16
KakuteH7-bdshot               *      *           -8      -8                -8     -8     -8
MatekF405                     *      *           *       *                 -8     -8     -8
Pixhawk1-1M                   *      *           *       *                 -8     -8     -8
f103-QiotekPeriph  *                                                                     
f303-Universal     *                                                                     
iomcu                                                          * …
```
=> AP_Airspeed: save some bytes by making conversion structure static

libraries/AP_HAL_ChibiOS/hwdef/Nucleo-L496/hwdef.dat
minimized builds and AP_Periph don't make sense together
=> hwdef: stop minimizing Nucleo-L496 - it's an AP_Periph

Tools/scripts/build_binaries.py
I ran build_binaries without this and everything seemed fine. Is there something else I should test/look into?
=> Tools: use gcc 10.2.1 for Sub too

libraries/AP_Scripting/docs/docs.lua
Added scripting hooks `FWVersion:hal_board()` and `FWVersion:hal_board_subtype()`. I've also added suitable documentation to make the function calls more useful.
My inspiration was to check for
```
local HAL_BOARD_SITL = 3
if FWVersion:hal_board() == HAL_BOARD_SITL then
-- do SITL specific handling
end
```
=> AP_Scripting: add some docs

libraries/AP_Logger/AP_Logger.h, libraries/AP_Logger/LogFile.cpp, libraries/AP_Logger/LogStructure.h
Change size check to keep it building
```
Durandal                      -392   *           -392    -392              -392   -192   -392
KakuteH7-bdshot               -384   *           -384    -384              -384   -184   -384
MatekF405                     -384   *           -384    -384              -384   -184   -384
Pixhawk1-1M                   -384   *           -384    -384              -384   -192   -384
f103-QiotekPeriph  *                                                                     
f303-Universal     *                                                                     
iomcu …
```
=> Save bytes in AP_Logger to get Pixhawk1-1M-bdshot compiling again

.github/workflows/test_scripts.yml, .github/workflows/test_unit_tests.yml, Tools/autotest/autotest.py, Tools/scripts/build_ci.sh
- fix autotest.py --list-subtests
- add test so we don't break --list-subtests again
- stop running param parse step every time we invoke build_ci.sh
- stop printing test names out when we run autotest.py - it's just noise, usually
=> Various small CI / autotest fixes

Tools/gittools/pre-commit.py
Bringing the same improvements added in #21035 to the pre-commit script.
Also I was thinking about the command line length limit. Hopefully by the time we get to close to that limit, the tag won't be necessary and the whole project will pass with `flake8 .` and the current .flake8 config file.
This commit did pass it's own check! (also shows it does work as a hook)
```
~/ardupilot$ git commit -m "Tools: Bring flake8 speed improvements to pre-commit"
***** Checking (Tools/gittools/pre-commit.py)
[pr/udpate-pre-commit dd08d5754c] Tools: Bring flake8 speed improvements to pre-commit
1 file changed, 21 insertions(+), 16 deletions(-)
```
=> Tools: Bring flake8 speed improvements to pre-commit

libraries/StorageManager/StorageManager.cpp, libraries/StorageManager/StorageManager.h
this crash was caused by AP_UAVCAN_DNA_Server declaring a storage object on the stack, which meant file was not initialised to nullptr.
thanks to @rmackay9 for reporting
=> StorageManager: fixed startup crash

libraries/AP_Notify/AP_Notify.cpp
this is static memory
```
Durandal                      -40    *           -40     -40               -40    -40    -40
KakuteH7-bdshot               -32    *           -32     -32               -40    -32    -40
MatekF405                     -32    *           -40     -32               -32    -40    -40
Pixhawk1-1M                   -32    *           -40     -40               -32    -40    -32
f103-QiotekPeriph  *                                                                     
f303-Universal     *                                                                     
iomcu …
```
=> AP_Notify: remove pointless zeroing of memory

.github/workflows/test_size.yml
If the target repo is a private repo then CI fails when checking out the various branches to test size them against
This is the current failure msg in CI:
```
git config user.email ardupilot-ci@ardupilot.org
+ git config user.name 'ArduPilot CI'
+ git remote add ardupilot https://github.com/ArduPilot/ardupilot.git
+ git fetch --no-tags --prune --progress ardupilot some-branch-on-a-private-repo
fatal: couldn't find remote ref some-branch-on-a-private-repo
Error: Process completed with exit code 128.
```
=> CI: allow test_size to work on private repos

libraries/AP_Notify/AP_Notify.cpp
I would change the direct value to an array number.
The following process sets NULL at the end of the array.
I saw a similar process in the send_text method.
By using the number of arrays, there is no code change.
=> AP_Notify: Use the number of arrays

Tools/autotest/arducopter.py, libraries/AC_AutoTune/AC_AutoTune.cpp, libraries/AC_AutoTune/AC_AutoTune.h, libraries/AC_AutoTune/AC_AutoTune_Heli.cpp, libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
This patch allows one to tune ATC_RAT_YAW_D rather than ATC_RAT_YAW_FLTE in autotune. This is particularly necessary for quadplanes using vectored yaw which have no momentum-based D component. This can also be used as a mechanism for tightening a copter yaw tune once a standard FLTE tune has been completed.
Enabled by setting:
```
AUTOTUNE_AXES = 8
````
Tested on a Heewing T-1 Ranger tri-tilt
=> Yaw D Autotune

libraries/AP_Terrain/AP_Terrain.cpp
This increases the default terrain altitude's offset (aka TERRAIN_OFS_MAX) to 30m (from 15m).
To provide background, this is the maximum altitude that the terrain database will be shifted up or down to match the vehicle's altitude at takeoff.  This shift happens at takeoff and is built on the assumption that the vehicle is taking off from the ground (e.g. not the top of a building).
The current 15m default is too strict (e.g. triggers too often under normal use) resulting in two problems:
1. unnecessary user confusion and fear and support calls due to the "Terrain: clamping xxx" message appearing
2. a real risk of terrain based missions flying at the wrong altitude.  Normally this results in the vehicle flying too high but too low is also possible.
I personally have seen the clamping …
=> AP_Terrain: terrain offset max default to 30m

libraries/AP_BattMonitor/AP_BattMonitor_Generator.cpp, libraries/AP_Generator/AP_Generator.h, libraries/AP_Generator/AP_Generator_Backend.cpp, libraries/AP_Generator/AP_Generator_Backend.h, libraries/AP_Generator/AP_Generator_IE_2400.cpp, libraries/AP_Generator/AP_Generator_IE_650_800.cpp, libraries/AP_Generator/AP_Generator_RichenPower.cpp
This is a scale, not a percentage.
It's used as such and commented as such.
This has caused at least one bug.
=> AP_Generator: rename fuel_remain_pct to fuel_remain_scale

libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_WPNav/AC_Loiter.cpp
This is a backport of PR https://github.com/ArduPilot/ardupilot/pull/21605 to the Copter-4.1 branch.
This bug can cause the vehicle to flip on takeoff in Loiter mode and is sadly quite easy to reproduce.  The two known ways it can happen are:
1. Pilot switch to RTL and the Loiter (while on the ground) and then takes off in Loiter.  This is the worst situation and can lead to very large desired roll and pitch angles (>ANGLE_MAX in unlucky cases where the autopilot is mounted upside-down and the vehicle enters RTL and then Loiter as the EKF is correcting itself to be right side up).
2. Pilot provide RC input while switching into Loiter (while on the ground) and then takes off in Loiter
This has been tested in SITL and resolves the problem.
This is serious enough that we probably need to …
=> Copter-4.1: PosController: Slow relax behaviour bug 

libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_WPNav/AC_Loiter.cpp
This is a backport of PR https://github.com/ArduPilot/ardupilot/pull/21605 to the Copter-4.2 branch.
This bug can cause the vehicle to flip on takeoff in Loiter mode and is quite easy to reproduce.  The two known ways it can happen are:
1. Pilot switch to RTL and the Loiter (while on the ground) and then takes off in Loiter.  This is the worst situation and can lead to very large desired roll and pitch angles (>ANGLE_MAX in some cases)
2. Pilot provide RC input while switching into Loiter (while on the ground) and then takes off in Loiter
This is serious enough that we probably need to warn users and release Copter-4.2.4 with this fix.  The issue also occurs in 4.1 but does not occur in 4.0 or 4.3.
Thanks very much to @tatsuy for discovering this problem and working with me on the fix. …
=> Copter-4.2: PosController: Slow relax behaviour bug 

Tools/scripts/build_options.py, Tools/scripts/extract_features.py
This partially resolves https://github.com/ArduPilot/CustomBuild/issues/35
Also fixes dependency for the existing EKF3_EXTNAV option.
BTW, I debated whether the option should be called "EKF3_WINDEST" vs "EKF3_DRAG_FUSION" but I figured that the former was more easily understood by users but I don't feel strongly about it.  The human readable description is clear enough in either case.
=> Tools: add EKF3 wind estimation to build options

libraries/SITL/picojson.h
some cygwin versions define a macro _serialize with 1 argument
=> SITL: prevent a conflict with a _serialize() macro on cygwin

libraries/AP_RCProtocol/AP_RCProtocol_SRXL.h, libraries/AP_RCProtocol/AP_RCProtocol_SRXL2.cpp, libraries/AP_RCProtocol/AP_RCProtocol_SRXL2.h
This started with SRXL2 just using its own define.
There's another fix in here now, right-sizing an array and using ARRAY_SIZE to make sure everything is passed correctly.
=> AP_RCProtocol: correct SRXL max-channels usage

libraries/AP_EFI/AP_EFI_Serial_MS.cpp
prevents infinite loop if there are exactly 255 bytes ready to read
=> AP_EFI: use uint16_t to store offset

libraries/AP_Camera/AP_Camera.cpp, libraries/AP_Camera/AP_Camera.h, libraries/AP_Mission/AP_Mission.cpp, libraries/AP_Mission/AP_Mission.h, libraries/AP_Mission/AP_Mission_Commands.cpp, libraries/GCS_MAVLink/GCS_Common.cpp
This improves support for controlling the camera both using real-time commands from the GCS and using mission commands in Auto mode.  The newly supported commands are:
- [MAV_CMD_SET_CAMERA_ZOOM](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1507) <-- only continuous type (not step or position yet)
- [MAV_CMD_SET_CAMERA_FOCUS](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1515) <-- only continuous type (not step or distance yet)
- [MAV_CMD_IMAGE_START_CAPTURE](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1544) <-- only takes 1 picture
- [MAV_CMD_VIDEO_START_CAPTURE](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1584)
- …
=> AP_Mission/AP_Camera: improve camera controls

ArduCopter/ReleaseNotes.txt, ArduCopter/version.h
This is the Copter-4.2.4 release which is just the 4.2.3 release with the single fix to Loiter's wonky takeoff ([see PR](https://github.com/ArduPilot/ardupilot/pull/23206))
This is the equivalent of the [4.1.6 release](https://github.com/ArduPilot/ardupilot/pull/23226).
=> Copter: 4.2.4 release

ArduCopter/ReleaseNotes.txt, ArduCopter/version.h
This is the Copter-4.1.6 release which is just 4.1.5 with the single "[Loiter level bug](https://github.com/ArduPilot/ardupilot/pull/23203)" fixed.  I think I might rename this issue "Loiter's wonky takeoff"
This is equivalent to the 4.2.4 release (see https://github.com/ArduPilot/ardupilot/pull/23227)
=> Copter: 4.1.6 release

libraries/AP_HAL_ChibiOS/hwdef/CubeYellow/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/fmuv3-bdshot/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/fmuv3/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/mRoX21-777/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/thepeach-k1/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/thepeach-r1/hwdef.dat
we can tell these are incorrect as they init to LOW, and previously we didn't have handling of VDD_5V_PERIPH_EN, so we know that LOW is enabled or the boards would not have worked
this fixes GPS on Pixhawk1
fix needed since #22882
=> hwdef: fixed polarity of VDD_5V_PERIPH_EN on several boards

libraries/AP_HAL_ChibiOS/hwdef/common/board.c, libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_mcuconf.h
this fixes an issue where a variable in SRAM1 gets set to a bad value when we reset AHB1 with the top bit (a reserved bit)
the bug was only reproducible with this particular commit:
https://github.com/tridge/ardupilot/commits/cubeorangplus-crash-boot-bisect
but likely is just luck that it triggered on that commit. In this instance it triggered as AP_OSD::singleton was reset to non-nullptr, causing a panic() in AP_OSD::AP_OSD()
compiler was gcc 10.2-2020-q4
=> HAL_ChibiOS: fix a memory corruption bug on STM32H757

libraries/AP_HAL_ChibiOS/hwdef/common/board.c, libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_mcuconf.h
This reverts #23228 which had an inadvertent side effect of disabling some clock init. Instead this just changes the one line in the ChibiOS hal_lld_init. That caused CAN1 to not work on some H743 chip versions
basically, @andyp1per was right :-)
=> HAL_ChibiOS: fixed STM32H7 SRAM1 memory corruption

Tools/scripts/build_options.py, Tools/scripts/extract_features.py, libraries/AP_Camera/AP_Camera_config.h, libraries/AP_GPS/AP_GPS_config.h, libraries/AP_Generator/AP_Generator_config.h, libraries/AP_Gripper/AP_Gripper_config.h, libraries/AP_HAL_ChibiOS/hwdef/include/minimize_features.inc, libraries/AP_Mission/AP_Mission.cpp, libraries/AP_Notify/AP_Notify_config.h
This is built on https://github.com/ArduPilot/ardupilot/pull/23231  There is only one commit on top.
Run through the test-build-options script OK.  extract features output on CubeOrange and Pixhawk1-1M are correct.
=> Tools: add camera backends to custom build server

Tools/scripts/size_compare_branches.py
Sometimes the vehicle/board combinations are empty as no build is done.  For example, when building bootloaders several boards don't have one, and hte output is cluttered with their results.
Don't show these empty lines by default
=> Tools: size_compare_branches.py: do not show lines where no builds made

libraries/AP_RCProtocol/AP_RCProtocol_Backend.cpp
We don't care how logging works, just that it does
```
MatekF405                     *      *           *       *                 *      *      *
Pixhawk1-1M                   *      *           *       *                 *      *      *
f103-QiotekPeriph  *                                                                     
f303-Universal     *                                                                     
iomcu …
```
=> AP_RCProtocol: HAL_LOGGING_ENABLED in place of checking build types

ArduCopter/autoyaw.cpp, ArduCopter/mode.h, Blimp/mode.h, Tools/autotest/arducopter.py, Tools/autotest/common.py
There is a current bug that results in the maximum yaw rate being slowed by high guided update rates:
=> Update rate vs guided yaw rate

libraries/AP_HAL_ChibiOS/CanIface.cpp
This is due to the way that the APB peripheral was configured. RCC_APB1ENR1_CAN2EN was not accounted for in the CAN hardware init, so CAN2 clock init was never attempted. I copied the way CAN1 is initialized based on different hardware description headers.
=> Fix problem where STM32L496 would not init CAN2

Tools/AP_Periph/Parameters.cpp, Tools/autotest/param_metadata/param_parse.py, libraries/RC_Channel/RC_Channel.cpp
Allows formatting to be reworked making it much easier to read and reducing conflicts. No change in parsed output.
Is a little odd in that if there is a a `@Values{vehicle}` anywhere all `@Values` without a vehicle type will be ignored. This means if something does apply to all vehicles it needs them all to be called out. eg: `@Values{Copter, Rover, Plane, Blimp}: 0:Do Nothing`. A new "all" tag might make this less painful.
The next one would be the servo functions. Again there its a little more complicated, because there is a full list and then a vehicle list for copter plane and rover. So in that case we need everything twice eg:
```
// @Values: -1:GPIO
// @Values{Copter, Rover, Plane}: -1:GPIO
// @Values: 0:Disabled
// @Values{Copter, Rover, Plane}: 0:Disabled
```
We can't just take …
=> Tools: Param Parse: multi line @Values

libraries/AP_NavEKF/EKFGSF_yaw.cpp
avoid errors during compass mot
=> AP_NavEKF: ensure gyro biases are numbers

ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduCopter/takeoff.cpp
This PR follows the discussion here:
https://discuss.ardupilot.org/t/feedback-and-assistance-with-new-takeoff-behaviour/
This PR provides the ability for the user to specify the throttle point where the vertical position controller will initialise and take over from the linear throttle ramp. If the takeoff detection is activated before this then there will be no change in behaviour.
Aircraft setup with high vertical climb rates and acceleration settings will detect takeoff at a higher threshold as these parameters are used to define the detection point. These thresholds are hard coded to 50% acceleration and 10% velocity.
By setting this parameter below hover throttle a user could get a fast thrust slew to that point then let the vertical position controller lift the aircraft off the …
=> Copter: Add TKOFF_TH_MAX

libraries/RC_Channel/RC_Channel.cpp
As I was documenting, the switch name felt very clumsy....It does abort all landings while in AUTO mode...hence the name change
=> RC_Channel:rename 173 option more appropriately

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_HAL/GPIO.h, libraries/AP_HAL_ChibiOS/GPIO.cpp, libraries/AP_HAL_ChibiOS/GPIO.h
ISR flood code can trigger at boot if the connected device is not yet powered. Once fully powered the only way to clear the internal error (and get the function to work) is to soft reboot the flight controller. Instead this waits 10 seconds and has another go at enabling. Currently only the `PWMSource` path will allow re-enable on a `set_pin` call. 
In order to re-enable the vehicle must be disarmed and have waited 10 seconds since last ISR or disarm. It then will re-enable the interrupt.
ISR flood is no longer a internal error if disarmed. There is a new arming check to prevent arming if a pin is disabled due to a flood. 
#20609
Some example messages:
```
Button: retrying pin 50 after ISR flood
ISR flood on pin 50
PreArm: Pin 50 disabled (ISR flood)
```
=> HAL ChibiOS: Interrupt storm pin retry

libraries/AP_GPS/AP_GPS.cpp, libraries/AP_GPS/AP_GPS.h
This moves us towards being able to compile the GPS library without having the MAVLink headers available.  We shouldn't need those headers when building for Periph.
If the headers are available then we ensure our values match mavlink so we can do a simple cast from one to the other
```
MatekF405                     *      *           *       *                 *      *      *
Pixhawk1-1M                   *      *           * …
```
=> AP_GPS: decouple status enumeration from MAVLink fix types

libraries/AP_DDS/gen_config_h.py, libraries/AP_DDS/wscript
Use python3 shebang since python3 is required
removed utf-8 encoding since that's only needed in python2
=> AP_DDS: Use python3 shebang

libraries/AP_InertialSensor/AP_InertialSensor_Invensensev2.cpp
* We have found some instances of ICM20649s triggering FIFO reset because of noisy Temperature Sensor. It seems like the temperature sensor is generally noisy and keeps quite close to 400 threshold, the solution I believe would be to simply increase the threshold. I have attached log with Raw Temperature data (GYR.T)
[log7.zip](https://github.com/ArduPilot/ardupilot/files/11035117/log7.zip)
=> AP_InertialSensor: increase the temperature tolerance for ICM20649 for fifo reset

libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py, libraries/AP_InertialSensor/AP_InertialSensor.cpp
Stops detection of same sensor type multiple times. Impacts CubeOrangePlus where ICM20948 ends up appearing twice in Initial version of CubeOrangePlus.
DevID CubeOrange+ Standard:
INS_GYR_ID: bus_type:SPI(2)  bus:4 address:4(0x4) devtype:52(0x34) INS_ICM42688 (3408930)
INS_GYR2_ID: bus_type:SPI(2)  bus:4 address:1(0x1) devtype:44(0x2c) INS_ICM20948 (2883874)
INS_GYR3_ID: bus_type:SPI(2)  bus:1 address:4(0x4) devtype:46(0x2e) INS_ICM20649 (3015690)
INS_ACC_ID: bus_type:SPI(2)  bus:4 address:4(0x4) devtype:52(0x34) INS_ICM42688 (3408930)
INS_ACC2_ID: bus_type:SPI(2)  bus:4 address:1(0x1) devtype:44(0x2c) INS_ICM20948 (2883874)
INS_ACC3_ID: bus_type:SPI(2)  bus:1 address:4(0x4) devtype:46(0x2e) INS_ICM20649 (3015690)
DevID CubeOrange+ BG:
INS_GYR_ID: bus_type:SPI(2)  bus:4 address:4(0x4) …
=> AP_InertialSensor: fix duplicate sensor detection for CubeOrangePlus

.github/workflows/test_environment.yml
Hirsute is OEL and don't work for long time
Jammy is 22.04 and should be properly tested
close https://github.com/ArduPilot/ardupilot/issues/23202
=> .github: replace testing of Hirsute by Jammy

libraries/AP_Baro/AP_Baro_LPS2XH.cpp
I guess the driver only was tested for SPI.
When used with I2C top bit of register address should not be set.
=> AP_Baro: LPS2XH SPI/I2C bug during setup

libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py, libraries/AP_InertialSensor/AP_InertialSensor.cpp
Stops detection of same sensor type multiple times. Impacts CubeOrangePlus where ICM20948 ends up appearing twice in Initial version of CubeOrangePlus.
=> [Backport Plane 4.4] AP_InertialSensor: fix duplicate sensor detection for CubeOrangePlus

ArduPlane/ReleaseNotes.txt, ArduPlane/version.h, libraries/AP_HAL_ChibiOS/RCOutput.cpp, libraries/AP_HAL_ChibiOS/RCOutput.h
- fixed 32 bit microsecond wrap in BDShot code
This release has a single bug fix for a critical bug for anyone using
bi-directional DShot on their vehicle. If using bi-directional DShot
and the vehicle is running its motors when 32 bit microsecond time
wraps at 71 minutes (or multiples of 71 minutes) then the bug that is
fixed in this release has an approximately 1 in 3 chance of causing
the motor to stop.
Note that the time is the time since boot, not the time since arming,
so even vehicles flying for a short time could be vulnerable if they
sit for a long time on the ground before takeoff.
=> Plane: 4.3.5beta release

ArduCopter/AP_Arming.cpp, ArduCopter/Copter.h, ArduCopter/compassmot.cpp, ArduCopter/motor_test.cpp, ArduCopter/radio.cpp, ArduCopter/system.cpp
this doesn't actually do what it says it does.  I think the functionality to set the motors armed was split out long ago but this little method and its misleading comments remained
=> Copter: remove enable_motor_output method

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.h, libraries/AP_Arming/AP_Arming_config.h
only the LUA bindings can actually activate this... so exclude it on builds that don't have scripting:
```
HerePro            *                                                                     
MatekF405                     -392   *           -416    -416              -408   -400   -416
Pixhawk1-1M                   -384   *           -400    -408              -400   -384   -400 …
```
=> AP_Arming: add and use a define for AP_ARMING_AUX_AUTH_ENABLED

ArduCopter/system.cpp
This doesn't actually enable the motors output.  It's a trivial method which sets the motor output level.
Not all places which set the motors as armed actually call this, so we can't roll it in there without a bit of thought.
This also removes the setting of the motor output levels at boot, based on your calibration at boot.  Leaving the motor outputs unconfigured based off rc configuration doesn't help.  We do these checks explicitly in the motor test routines where it is important.
=> Copter: Remove misleading enable_motor_output method

libraries/AP_HAL_ChibiOS/RCOutput.cpp
This fixes a bug in bdshot whereby dma cancellation could result in the wrong DMA channel being used for dshot output and hence motors stopping.
This only affects boards with DMA channels shared between UP and IC - which generally means all H7 boards but no others.
DMA cancellation is almost always triggered by time wrapping
=> Ensure the rcout TIM_UP DMA request source is re-instated after cancellation

ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, ArduPlane/ReleaseNotes.txt, ArduPlane/version.h, Rover/release-notes.txt, Rover/version.h, libraries/AP_HAL_ChibiOS/RCOutput.cpp, libraries/AP_HAL_ChibiOS/RCOutput.h
This is the the Copter-4.3.6-beta1 release which includes the critical BDShot fix that's being released with Plane-4.3.5.
This will also become the Rover-4.3.0-beta11 release.
BTW, the use of "beta1" instead of "rc1" is because Tridge and I are trying to make the Plane, Rover and Copter releases more consistent.
=> Copter: 4.3.6-beta1 release

libraries/AP_HAL/CANIface.cpp
Fixes a bug in the CAN_Frame constructor where dlc was not being set if there were invalid arguments like nullptr data or data_len=0 which actually is a valid CAN packet. This variant of the constructor now operates like the base constructor for consistent behavior
=> AP_HAL: fix CANFrame initialization in constructor

ArduCopter/mode.h, ArduCopter/mode_zigzag.cpp
rework from https://github.com/ArduPilot/ardupilot/pull/17456
use NAV_CONTROLLER_OUTPUT to display zigzag target when on auto zigzag mode. Otherwise don't send anything.
Tested with SITL.
=> Copter: Add an element of NAV_CONTROLLER_OUTPUT to ZIGZAG mode

ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, ArduPlane/ReleaseNotes.txt, ArduPlane/version.h, Rover/release-notes.txt, Rover/version.h, libraries/AP_HAL_ChibiOS/RCOutput.cpp
This is the Copter-4.3.6-beta2 release.  This is hot on the heels of the -beta1 release because there are two more commits that @tridge and @andyp1per came up with to more completely resolve the bi-directional dshot issue.
This will also become the Rover-4.3.0-beta12 release.
=> Copter: 4.3.6-beta2 release

libraries/AP_DDS/README.md
The AP_DDS README.md bash scripts about some of the required installations weren't clear or fully functional and the tutorial order was somewhat misleading.
Besides that I am still planning to [update the ardupilot wiki](https://ardupilot.org/copter/docs/parameters.html#serial1-protocol-telem1-protocol-selection) with SERIAL PROTOCOL 45. I also think it would be awesome to add another commit with an example to the "Adding DDS messages to Ardupilot" section, @Ryanf55  can you help me figure it out?
=> AP_DDS: update readme scripts and tutorial

libraries/AP_DDS/Idl/NavSatFix.idl, libraries/AP_DDS/Idl/NavSatStatus.idl, libraries/AP_DDS/Idl/PoseStamped.idl, libraries/AP_DDS/wscript
* Adds -cs argument to fix case sensitive issue with PoseStamped
* Adds support for uint8_t type alias
* Updated the copies of IDL to remove these mods, matching upstream
* Solves #23302
If the PR fails, it's likely because the docker image with MicroXRCEDDSGen needs to be rebuilt using latest develop hash `20bbbd0ed8fcb3284e25fe1fa257a08537cfb5fa`. See https://github.com/ArduPilot/ardupilot_dev_docker/pull/16
=> AP_DDS: Bump to using latest MicroXRCEDDSGen

.pre-commit-config.yaml
This adds an XML linter for AP_DDS. 
Note. This tool can't run on Windows. Perhaps we shouldn't adopt it (or fix it) if we expect windows developers to want to use the hook? 
Solves #23282
=> .pre-commit: Add xmllint for AP_DDS xml file

libraries/SITL/SIM_JSON.cpp, libraries/SITL/SIM_JSON.h, libraries/SITL/examples/JSON/readme.md, libraries/SRV_Channel/SRV_Channel.h
Enable 32 servos in SITL_JSON when the parameter SERVO_32_ENABLE is set.
- Add new static method to SRV_Channel that returns true if 32 servos are enabled.
- Add new struct in SITL_JSON with 32 channels and new magic number.
- Update output_servos method to use either 16 channel or 32 channel struct depending on whether or not the parameter SERVO_32_ENABLE is set.
1. Verified backwards compatibility using the `iris_runway.sdf` model in ArduPilot/ardupilot_gazebo.
2. Verified new servo packet is being sent when SERVO_32_ENABLE is set. This currently causes the ArduPilot/ardupilot_gazebo to issue a bad magic number warning. A separate PR will add support for 32 channels on the Gazebo simulation side (there is no dependency here).
=> Enable 32 servos in SITL_JSON

Tools/scripts/size_compare_branches.py
Just as we do the CubeOrange equivalent; this uses the CubeOrangePlus bootloader
=> Tools: blacklist build of CubeOrangePlus-SimOnHardware bootloader

libraries/AP_HAL_ChibiOS/SPIDevice.cpp
There appear to still be issues with SPI driver model v2 leading to IMU resets on CubeOrange.
This PR simply reverts to the older v1 driver model with which we have not had issues.
I have verified that the driver model v1 files are identical to those in the ChibiOS version used in 4.3
Did a short test flight in my office to double check all was good 👍 
Uses https://github.com/ArduPilot/ChibiOS/pull/61
=> Revert to ChibiOS SPI driver model v1

libraries/AP_Motors/AP_MotorsMatrix.cpp, libraries/AP_Motors/AP_MotorsMatrix.h, libraries/AP_Motors/AP_MotorsMulticopter.cpp, libraries/AP_Motors/AP_MotorsMulticopter.h, libraries/AP_Motors/examples/AP_Motors_test/AP_Motors_test.cpp, libraries/AP_Motors/examples/AP_Motors_test/MotorTestSweep.sh
This is simplification for the main motor mixer, the goal is to make the mixer easier to understand while being mathematically identical. This is more of a what it might look like than a tested suggestion. If this seems like a good idea we can test it is functionally the same using the motors example script. 
- moves the variables declared at the top down to where there used, this means that the handy comment that explains what they do is in the same place the variable is used. This also means a couple can become const.
- ~moves to `if (!motor_enabled[i]) { continue; }` pattern. This means code is not a for and a if loop.~
- removes the unused variable `rp_low` and `rp_high`
- adds a `boost_ratio` helper to simplify the code.
- adds a `const float` intermediate step in the yaw headroom …
=> AP_Motors: Matrix: mixer simplification

ArduPlane/ArduPlane.cpp, ArduPlane/quadplane.cpp, libraries/AP_Common/Location.cpp, libraries/AP_Common/Location.h
There is currently a 2D comparison (`Location::same_latlon_as()`), but there is no 3D comparison.
This also adds a `Location::same_alt_as()` function.
=> AP_Common: Add same_loc_as() function to Location

ArduPlane/RC_Channel.cpp
What a tangled web......
A user complained that RC failsafe was activating his flaps....simple SITL testing showed that indeed flaps went to servo_min during RC failure....reported and Tridge suggested a fix....it did not work....then I realized that the code was forcing manual FLAPS=0 until RC is restored which is indeed supposed to be no flaps, and is the correct behavior ..the user had setup his flaps servo as a manual spoiler AND flap which the FLAP function will not do correctly...so it was operating correctly...taking his input of 1500 and forcing the output to 1100 (should be no flaps)....BUT....
as I was checking every other flap or similar function, I discovered that AIRBRAKE was not being initialized....#20370 supposedly fixed, but did not actually...boot gives a nag message …
=> Plane:allow airbrakes to be used

libraries/AP_Mount/AP_Mount.cpp, libraries/AP_Mount/AP_Mount.h, libraries/GCS_MAVLink/GCS_Common.cpp
Task from Gimbal enhancement list #20985  
consumes [GIMBAL_MANAGER_SET_ATTITUDE](https://mavlink.io/en/messages/common.html#GIMBAL_MANAGER_SET_ATTITUDE) messages
This needs to be merged before it
[#308](https://github.com/ArduPilot/mavlink/pull/308)
=> AP_Mount:Add GIMBAL_MANAGER_SET_ATTITUDE support

Tools/scripts/size_compare_branches.py
waf doesn't take care of this for us
hopefully temporary.  it would be nice to correct the generation of these.
=> Tools: remove dsdl_generated before building bootloader

libraries/AP_InertialSensor/AP_InertialSensor.cpp, libraries/AP_Notify/AP_Notify.h, libraries/AP_Notify/Buzzer.cpp, libraries/AP_Notify/Buzzer.h
More and more autopilots are including the simple buzzer on their USB remotes....the only useful sounds currently for someone standing next to the plane are armed and disarmed....this adds a noise when the plane must not be moved and when it first becomes arm ready....could be more complex and have it notify if pre-arm checks return before arm, but I don't think that it really needed in 99.9% of the cases where this would be used.
flight tested
=> Add notify noises to Buzzer

libraries/AP_InertialSensor/AP_InertialSensor.h, libraries/AP_InertialSensor/AP_InertialSensor_Logging.cpp, libraries/AP_InertialSensor/BatchSampler.cpp
Fixes setting param INS_LOG_BAT_CNT while the batch logging has already started can lead to hardfault.
=> AP_InertialSensor: fix hardfault in BatchSampler

libraries/AP_GPS/MovingBase.h, libraries/AP_HAL_ESP32/README.md, libraries/RC_Channel/RC_Channel.h
I spelled it wrong earlier and found a few other places others did the same. It's all just comments, so a low risk PR
=> Fix spelling of receiver in ArduPilot repo

ArduCopter/ReleaseNotes.txt, ArduCopter/version.h
This is the Copter-4.3.6 official release which is exactly the same as the last beta.
=> Copter: 4.3.6 release

libraries/AP_OSD/AP_OSD.cpp, libraries/AP_OSD/AP_OSD.h, libraries/AP_OSD/AP_OSD_Screen.cpp
direction arrows are inverted and rotate in the opposite direction if BF font set is used instead of AP font sets...BF font is used on some DisplayPort goggle systems 
end user tested successfully in flight
awaiting @yaapu opinion if this can be activated instead directly with MSP_OPTIONS bit that sets the use of BF font symbols in DisplayPort....I believe it can and I can drop the new OSD option bits...simple change
=> AP_OSD:add option to correct direction arrows for BF font set

libraries/AP_SerialManager/AP_SerialManager.cpp
Many boards rely on setting the SERIAL1 port protocol in the hwdef....but it doesn't...ran into this checking my SpeedyBeeF405WING hwdef.....this fixes that for
FlywooF405S-AIO/hwdef.dat:define HAL_SERIAL1_PROTOCOL SerialProtocol_RCIN
FoxeerH743v1/hwdef.dat:define HAL_SERIAL1_PROTOCOL SerialProtocol_RCIN
JHEMCU-GSF405A/hwdef.dat:define HAL_SERIAL1_PROTOCOL 23
SPRacingH7/hwdef.dat:define HAL_SERIAL1_PROTOCOL SerialProtocol_RCIN
SkystarsH7HD-bdshot/hwdef.dat:define HAL_SERIAL1_PROTOCOL SerialProtocol_RCIN
speedybeef4v3/hwdef.dat:define HAL_SERIAL1_PROTOCOL SerialProtocol_DJI_FPV
=> AP_SerialManager: allow SERIAL1 protocol to be hwdef defined

Tools/autotest/common.py, Tools/autotest/rover.py
accels inconsistent was popping up in here.
We can ignore that - we only care we won't arm because of the estop being active.  This will also save a bit of time with the removal of the raw delay-for-10-seconds
=> autotest: allow other prearm failures while waiting for estop prearm

Tools/autotest/test_build_options.py, Tools/scripts/extract_features.py, libraries/RC_Channel/RC_Channel.cpp
I noticed that our OSD detection isn't right.
This doesn't pick that problem up (not compiled into our test boards by default), but this did catch several others.
=> Tools: validate features are removed when we compile them out

Tools/scripts/build_options.py, Tools/scripts/extract_features.py, libraries/AP_Scripting/generator/description/bindings.desc
this was renamed throughout - except in here
'\bWINCH_ENABLED` doesn't exist in the tree past this.
=> Tools: build_options.py correct winch enablement

Tools/autotest/rover.py
vagaries of interaction with Python script means we need to give this more time when running balancebot
=> autotest: give Rover longer to arrive home

Tools/autotest/common.py
correct problem where we only rebooted if the vehicle was armed after a failed test.
Should correct cascading failures after some tests
=> autotest: correct implicit reboot after a failed test

Tools/scripts/extract_features.py
... setting OSD_ENABLED false doesn't actually get rid of AP_OSD::AP_OSD ATM!
=> Tools: correct OSD feature extraction

libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
This changes the TRIKx defaults to result in a "Not setup message"...this forces users to consciously setup the trick params since some work in a fashion with current defaults and some do not, causing confusion
It also adds param metadata to the most commonly changed params at the field for GCS display
=> AP_Scripting: Plane_aerobatics.lua enhancements

libraries/AP_Mount/AP_Mount.cpp, libraries/AP_Mount/AP_Mount.h, libraries/AP_Mount/AP_Mount_Backend.cpp, libraries/AP_Mount/AP_Mount_Backend.h, libraries/GCS_MAVLink/GCS_Common.cpp
Moves the handling of exiting ROI Targetting out of `GCS_MAVLink` and into `AP_Mount`. More importantly, ensures the internal `_roi_target_set` flag is cleared in the Mount backend.
=> AP_Mount: Add clear_roi_target() function

libraries/AP_Motors/AP_MotorsTri.cpp, libraries/AP_Motors/AP_MotorsTri.h, libraries/SRV_Channel/SRV_Channel.h, libraries/SRV_Channel/SRV_Channel_aux.cpp
Moves checking of yaw servo setup to arming check.
This also removes the last user of the default channel variable in the `get_channel_for` function, tricopter was the last user. 
Adds a `_have_tail_servo` bool plane does not try to use the tail servo if none is setup.
=> AP_Motors: Tricopter: rework yaw servo defaulting, remove yaw from mix if no servo is setup

ArduCopter/AP_Arming.cpp, ArduPlane/AP_Arming.cpp, Rover/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.h
This PR has two parts:
1. move the individual estop prearm checks from each vehicles arming into top level AP_Arming
2. add the exclusion for the ARM_EMERGENCY_STOP switch in estop position
tested in SITL for plane,copter., and rover using sw 31(ESTOP) and sw 165(ARM_EMERGENCY_STOP)
Rover autotest needs rework since the flow of prearms has changed
=> Move Estop prearm up into Arming and add exception

libraries/AP_Airspeed/AP_Airspeed_DroneCAN.cpp, libraries/AP_Airspeed/AP_Airspeed_DroneCAN.h, libraries/AP_Airspeed/AP_Airspeed_MS4525.h, libraries/AP_Airspeed/AP_Airspeed_MS5525.h, libraries/AP_Airspeed/AP_Airspeed_NMEA.cpp, libraries/AP_Airspeed/AP_Airspeed_NMEA.h, libraries/AP_Airspeed/AP_Airspeed_SDP3X.cpp, libraries/AP_Airspeed/AP_Airspeed_SDP3X.h, libraries/AP_Airspeed/AP_Airspeed_analog.h
... and clean out some unused includes
```
Durandal                       *      *           -8      -16               -16    -24    -24
KakuteH7-bdshot                *      *           -16     -16               -16    -24    -32
MatekF405                      *      *           *       *                 -16    -32    -32
Pixhawk1-1M-bdshot             *                  *       *                 -24    -24    -24
f103-QiotekPeriph   -24 …
```
=> AP_Airspeed: reuse airspeed backend contructor in more backends

libraries/SITL/SIM_Aircraft.h
This fixes a crash when running Sub on an M1 mac.
millivolts had a negative value which caused a crash when casting to uint16_t
=> SITL: use int16_t signature for SMBus voltage reporting

libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
This PR was previously on the Copter-4.3 branch and now on the master branch.
The PR link of Copter-4.3 is as follows:
[the accel fast-sampling rate of MPU6500 is 4k,not 1k](https://github.com/ArduPilot/ardupilot/pull/22915)
=> AP_InertialSensor: the accel fast-sampling rate of MPU6500 is 4k Hz,not 1k Hz(master branch)

libraries/AP_Scripting/drivers/mount-viewpro-driver.lua, libraries/AP_Scripting/drivers/mount-viewpro-driver.md
This makes two non-functional changes to the ViewPro lua script driver
- Adds parameter descriptions
- Minor fix to the setup instructions now that the AP_Camera frontend/backend split has been completed
=> AP_Scripting: ViewPro gimbal drivers gets parameter descriptions

libraries/AP_InertialSensor/AP_InertialSensor.h, libraries/AP_InertialSensor/AP_InertialSensor_Logging.cpp, libraries/AP_InertialSensor/BatchSampler.cpp
Fixes setting param INS_LOG_BAT_CNT while the batch logging has already started can lead to hardfault.
=> [4.3 backport] AP_InertialSensor: fix hardfault in BatchSampler

Tools/autotest/common.py
we have a sanity check that when you reboot a vehicle that soon afterwards the vehicle is in the place we expect it to start.
That's fine for most vehicles, which stay put.  But we start the ship simulation with wind, so it can actually drift before we get around to checking its location.  Simply skip this check for now (we could, perhaps, allow for a very large radius instead?)
=> autotest: exempt sailboats from initial location check

Tools/scripts/extract_features.py, libraries/AP_BattMonitor/AP_BattMonitor.cpp
Makes all of the clauses in this switch look the same.
``` …
```
=> AP_BattMonitor: move defines around battery types for consistency

libraries/AP_Logger/AP_Logger_Backend.cpp
You really don't want your nice replay log having holes in the middle.  So ignore the request to rotate on disarm if we are doing replay logging.
=> AP_Logger: do not rotate logs when disarming if we are replay-logging

libraries/AP_Mount/AP_Mount.cpp, libraries/AP_Mount/AP_Mount.h, libraries/AP_Mount/AP_Mount_Backend.h, libraries/AP_Scripting/drivers/mount-viewpro-driver.lua
This fixes a bug in the ViewPro camera gimbal driver introduced in PR https://github.com/ArduPilot/ardupilot/pull/23423 (merged last night).
Apologies for this bug, this must have occurred during some last minute rebasing.
I've also done a drive-by non-functional change to remove some unused methods in AP_Mount.
=> AP_Scripting: viewpro driver fix

libraries/AP_Logger/AP_Logger.cpp, libraries/AP_Logger/AP_Logger.h, libraries/AP_Logger/AP_Logger_Backend.cpp, libraries/AP_Logger/AP_Logger_Backend.h, libraries/AP_Logger/AP_Logger_Block.cpp, libraries/AP_Logger/AP_Logger_File.cpp, libraries/AP_Logger/AP_Logger_File.h, libraries/AP_Logger/AP_Logger_MAVLink.cpp, libraries/AP_Param/AP_Param.h
This adds a nice option for disarmed logging without taking up a lot of space on the microSD.
Setting LOG_DISARMED=3 will log while disarmed, but the file is marked to be discarded on reboot. The marker is removed when we arm. 
The LOG_DARM_RATEMAX parameter allows to set the max logging rate while disarmed. In combination with LOG_DISARMED=3 you can get logging while disarmed with very little increase in log file size.
For replay logging we would use:
- LOG_DISARMED=3
- LOG_REPLAY=1
- LOG_DARM_RATEMAX=1
this will give very nice replay logging while minimising log sizes.
=> Logging: implement LOG_DISARMED=3 and LOG_DARM_RATEMAX

libraries/AP_HAL_ChibiOS/hwdef/common/stm32f47_mcuconf.h
This fixes ChibiOS so that https://github.com/ArduPilot/ardupilot/pull/23455 is unnecessary
=> Fix SDIO PWRSAV on F4/F7 and MMC SPI reads

libraries/AP_DDS/AP_DDS_Client.cpp, libraries/AP_GPS/AP_GPS.cpp, libraries/AP_GPS/AP_GPS.h
This PR adds support for populated the double matrix of covariance, which will be consumed in ROS2 in a follow up PR. 
The covariance units are m^2 (it's a variance).
It's only computed when requested. 
Note, I did clarify this is the position covariance, since it seems the GPS receivers can also report velocity covariance. Currently, the velocity covariance is not part of the NavSatFix(yet), but we can expect a future with a `velocity_covariance` method when that is true.
Closes #23259
=> AP_GPS: Add covariance output to AP_GPS matching ROS NavSatFix

Rover/AP_Arming.cpp
Currently arming check 0 on Rover skips all checks, whereas if you force arm from the GCS you still get the mandatory checks. This bring them both inline, and inline with copter and soon plane https://github.com/ArduPilot/ardupilot/pull/23189
Rover does not have have any extra mandatory checks, so its just the base method.
https://github.com/ArduPilot/ardupilot/blob/9cc8622ccc59cd2a64f06d79af53f91d8e4f36b1/libraries/AP_Arming/AP_Arming.cpp#L1589-L1598
=> Rover: Arming: still run mandatory checks if ARMING_CHECK 0

libraries/AP_Airspeed/AP_Airspeed.cpp
Typos in the source code parameter docs
=> AP_Airspeed: Add missing D in ARSP

libraries/GCS_MAVLink/GCS_Common.cpp
As requested in https://github.com/ArduPilot/ardupilot/pull/22066
=> GCS_MAVLink: send deprecated message received warning at INFO not WARN

libraries/AP_Mount/AP_Mount_Servo.cpp, libraries/AP_Mount/AP_Mount_Servo.h
We're doing a lot of pointless to-ing and fro-ing from degrees to radians and back again in here.
=> AP_Mount: use only radians within servo backend

libraries/AP_Proximity/AP_Proximity.cpp
fixes a compilation problem if all of the backends are compiled out!
=> AP_Proximity: include AP_Proximity_Backend.h in AP_Proximity.cpp

Tools/autotest/common.py
AKA avoid dreaded gyros-inconsistent failure
=> autotest: wait ready to arm in autotest

libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp, libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp, libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp, libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.h
This provides a work around for the problems with incorrect yaw alignment that some planes with no compass have encountered which have been reported here https://github.com/ArduPilot/ardupilot/issues/23224
By default the first yaw alignment after launch will be performed using the GPS ground course. Some additional protection against accidental yaw alignment during shake to arm and due to GPs glitches has been added.
This has been tested on replay of a log from a Matek F765-Wing flight controller fitted to a Strix Nano Goblin airframe, however this setup has not previously encountered the issue reported. The following figure shows the yaw alignment to GPS ground course after launch which is the behaviour with EK3_SRC1_YAW set to 1 (compass) or 0 (none) with no compass enabled. GPS ground …
=> Provide alternative to use of GSF for initial yaw alignment for fixed wing and rovers

Tools/autotest/arduplane.py
intermittent failures in CI - perhaps due to Plane dynamics changes
=> autotest: allow more time for deepstall text

libraries/AP_Logger/LogFile.cpp
```
Board,copter
skyviper-v2450,-64
```
briefly tested in SITL to ensure we still get data in RCOU
=> AP_Logger: avoid many method calls logging RCOU

ArduCopter/mode_turtle.cpp, ArduCopter/sensors.cpp, ArduPlane/ArduPlane.cpp, ArduPlane/tailsitter.cpp, libraries/AP_Motors/AP_MotorsCoax.cpp, libraries/AP_Motors/AP_MotorsMatrix.cpp, libraries/AP_Motors/AP_MotorsMatrix_6DoF_Scripting.cpp, libraries/AP_Motors/AP_MotorsMulticopter.cpp, libraries/AP_Motors/AP_MotorsMulticopter.h, libraries/AP_Motors/AP_MotorsSingle.cpp, libraries/AP_Motors/AP_MotorsTailsitter.cpp, libraries/AP_Motors/AP_MotorsTri.cpp, libraries/AP_Motors/AP_Motors_Class.cpp, libraries/AP_Motors/AP_Motors_Class.h, libraries/AP_Motors/AP_Motors_Thrust_Linearization.cpp, libraries/AP_Motors/AP_Motors_Thrust_Linearization.h, libraries/AP_Motors/examples/expo_inverse_test/expo_inverse_test.cpp
Moves functions and code to new class for easier use by others in the future. https://github.com/ArduPilot/ardupilot/pull/22661
Since I was moving the code I also took the opportunity for motors ask baro for air density ratio directly rather than having the vehicles set it into motors.
=> AP_Motors: move Thrust Linearization functions and variables to own class

ArduPlane/Attitude.cpp, ArduPlane/mode_guided.cpp, Tools/autotest/arduplane.py
Moves guided overrides from core roll/pitch/throttle functions upto mode guided. There is still a override for yaw that is not moved, it is more tangled.
=> Plane: move guided roll, pitch and throttle overrides upto guided mode

ArduPlane/GCS_Mavlink.cpp, ArduPlane/GCS_Mavlink.h, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_config.h
The mavlink command MAV_CMD_DO_SET_MISSION_CURRENT has been in place since January 2019 and is superior to this.
ArduPilot has had support since 2021 (4.1.x but not 4.0.x)
We have to get GCSs to move forward!  Before we can do that PX4 has to support the command.
A GCS could try the command and if it gets back an UNSUPPORTED try the message instead.
I'm not intending tthe message to be technically deprecated any time soon - raising for discussion on DevCall to make sure people are OK with me putting out an announcement on ArduPilot's GCS maintainers list suggesting people move to the command in their GCSs rather than the message.
Eventually this will save ~240 bytes on MatekF405-Wing when we can remove support for this message.
=> GCS_MAVLink: deprecate use of MISSION_SET_CURRENT message

.pre-commit-config.yaml
This enforces black code style in AP_DDS.
Black is nice because it can run in CI, as well as run in editor, without a user manually modifying their code to satisfy the linter. 
Since black is cross-platform, and the version is specified as 23.1.0, everyone edits with the same version. 
The next step would be to enforce the same rules in CI because pre-commit hooks are not mandatory. 
Question for maintainers - is there going to be any conflict by formatting AP_DDS to this code style with the other tooling in the repo?
=> .pre-commit: Enfore code style for AP_DDS

libraries/AP_GPS/AP_GPS_NMEA.cpp
```../../libraries/AP_GPS/AP_GPS_NMEA.cpp: In member function 'void AP_GPS_NMEA::parse_versiona_field(uint16_t, const char*)':
../../libraries/AP_GPS/AP_GPS_NMEA.cpp:787:16: error: 'char* strncpy(char*, const char*, size_t)' output may be truncated copying 19 bytes from a string of length 29 [-Werror=stringop-truncation]
787 |         strncpy(v.version, _term, sizeof(v.version)-1);
|         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```
```
pbarker@fx:~/rc/ardupilot(pr/AP_RANGEFINDER_ENABLED)$ arm-none-eabi-g++ --version
arm-none-eabi-g++ (GNU Tools for Arm Embedded Processors 9-2019-q4-major) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
```
=> AP_GPS_NMEA: fix stringop truncation failure on g++ 9

libraries/AP_DroneCAN/AP_DroneCAN.cpp
Fixes:
```
../../libraries/AP_DroneCAN/AP_DroneCAN.cpp:190:6: error: ‘%u’ directive output may be truncated writing between 1 and 10 bytes into a region of size 4 [-Werror=format-truncation=]
```
Related to:
```
snprintf(_thread_name, sizeof(_thread_name), "dronecan_%u", driver_index);
```
Problem seems semi genuine, `_thread_name` is only 13 characters long `dronecan_` takes up 9 so the warning is that were trying to print a uint32 with `u` but only have 4 characters left. The fix is to add the length specifier `hh` so the compiler knows its a uint8 not a uint32. 
I guess newer compilers are clever enough to know its a uint8 from inspection of the variable rather than only the format string. 
In any case this means I don't have to update my compiler to build SITL.
=> AP_DroneCAN: add length specifier to format print to keep  g++ 7.5.0 happy

libraries/AC_AttitudeControl/AC_AttitudeControl.cpp, libraries/AP_Math/quaternion.h, libraries/AP_Mount/AP_Mount.cpp, libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
This isn't an exhaustive list of changes to the calls - there's quite a few more in the EKFs, for example.
(also adds the double equivalent)
```
Durandal                       0      *           8       0                 8      8      8
KakuteH7-bdshot                0      *           -80     -80               -80    0      -80
MatekF405                      8      *           -72     -80               -80    0      -80
Pixhawk1-1M-bdshot             *                  -80     -80               -80    *      -80 …
```
=> Add convenient Quaternion::to_euler(Vector3f &rpy)

Tools/autotest/common.py, Tools/autotest/rover.py, libraries/AP_Compass/AP_Compass.cpp
The check for zero-length magnetic field on the primary is redundant given the one on the loop
I tested this by printing the values calculated by the new method with those by the old and making sure they matched.
Builds are a little larger on the smaller boards as this now includes the se angle methods:
A few more uses of those will make this a net win on those boards.  Plane already uses one of those methods so it's already a saving on that vehicle.
```
Durandal                       -96    *           -72     -72               -200   -72    -80
HerePro             -104                                                                  
Hitec-Airspeed      * …
```
=> AP_Compass: use new vector methods to make for more compact code

libraries/AP_DroneCAN/AP_Canard_iface.cpp, libraries/AP_DroneCAN/AP_DroneCAN.cpp, libraries/AP_HAL/EventHandle.cpp, libraries/AP_HAL/EventHandle.h, libraries/AP_HAL_ChibiOS/EventSource.cpp, libraries/AP_HAL_ChibiOS/EventSource.h, libraries/AP_HAL_ChibiOS/RCOutput.cpp, libraries/AP_HAL_ChibiOS/Scheduler.cpp, libraries/AP_HAL_Linux/CANSocketIface.cpp, libraries/AP_HAL_Linux/CANSocketIface.h, libraries/AP_HAL_SITL/CANSocketIface.cpp, libraries/AP_HAL_SITL/CANSocketIface.h
this fixes an issue that prevents boot on some boards with a single CAN interface and no CAN devices attached. Reproduced by henry and me on a MatekH743-Wing. Without this change the loop sending 5 status messages in AP_DroneCAN::init() won't complete. Unfortunately gdb debug interface is pretty badly broken at the moment to try to work out the underlying issue
even a 1 microsecond delay is enough to avoid the issue
=> AP_DroneCAN: fixed timeout for 16 bit timers in events

libraries/AP_Camera/AP_Camera.cpp, libraries/AP_Camera/AP_Camera.h, libraries/AP_Camera/AP_Camera_Backend.h, libraries/AP_Camera/AP_Camera_MAVLinkCamV2.cpp, libraries/AP_Camera/AP_Camera_MAVLinkCamV2.h, libraries/AP_Camera/AP_Camera_Mount.cpp, libraries/AP_Camera/AP_Camera_Mount.h, libraries/AP_Camera/AP_Camera_Scripting.cpp, libraries/AP_Camera/AP_Camera_Scripting.h, libraries/AP_Camera/AP_Camera_shareddefs.h, libraries/AP_Mission/AP_Mission_Commands.cpp, libraries/AP_Mount/AP_Mount.cpp, libraries/AP_Mount/AP_Mount.h, libraries/AP_Mount/AP_Mount_Backend.h, libraries/AP_Mount/AP_Mount_Siyi.cpp, libraries/AP_Mount/AP_Mount_Siyi.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/drivers/mount-viewpro-driver.lua, libraries/AP_Scripting/drivers/mount-viewpro-driver.md, libraries/AP_Scripting/generator/description/bindings.desc, libraries/RC_Channel/RC_Channel.cpp
This enhances AP_Camera to support a new "percentage" zoom type.  E.g. the user can specify they would like the camera to zoom to a percentage (expressed as a value from 0 to 100%) of its maximum.
For now only the MAVLinkCamV2 and Scripting backends (e.g. ViewPro) make use of this feature.  The Siyi ZR10 can apparently also support this feature but I haven't done this yet because it shares a driver with the Siyi A8 which doesn't have this ability.
There are two questionable parts to this PR:
Below is an screenshot from a test in which the SET_CAMERA_ZOOM command was used to zoom a ViewPro camera to 25% of its maximum.
The command can also be sent as a real-time command from a GCS so that a user can be presented with a slider from 0% to 100% instead of (or in addition to) "zoom in", "zoom …
=> AP_Camera: add zoom percent control

libraries/AP_Arming/AP_Arming.cpp
... we'll warn but not fail prearms
=> AP_Arming: correct prearm check for mission storage file

Tools/AP_Periph/AP_Periph.h, Tools/AP_Periph/Parameters.cpp, Tools/AP_Periph/Parameters.h, Tools/AP_Periph/can.cpp, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_CANManager/AP_CAN.h, libraries/AP_CANManager/AP_CANDriver.cpp, libraries/AP_CANManager/AP_CANManager.cpp, libraries/AP_CANManager/AP_CANManager.h, libraries/AP_CANManager/AP_CANSensor.cpp, libraries/AP_CANManager/AP_CANSensor.h, libraries/AP_DroneCAN/AP_DroneCAN.cpp, libraries/AP_EFI/AP_EFI_NWPMU.cpp, libraries/AP_KDECAN/AP_KDECAN.cpp, libraries/AP_PiccoloCAN/AP_PiccoloCAN.cpp, libraries/AP_RangeFinder/AP_RangeFinder_Benewake_CAN.h, libraries/AP_RangeFinder/AP_RangeFinder_USD1_CAN.h, libraries/AP_Scripting/AP_Scripting_CANSensor.h, libraries/AP_Scripting/lua_bindings.cpp, libraries/AP_Vehicle/AP_Vehicle.h, libraries/SRV_Channel/SRV_Channels.cpp
Stop AP_Periph including AP_CANManager class definition.
```
HerePro             -8                                                                     …
```
=> Move and rename AP_CANManager::Driver_Type to AP_CAN::Protocol

libraries/AP_Arming/AP_Arming.cpp
Remove meaningless semicolons.
=> AP_Arming: Remove unnecessary empty sentences

ArduCopter/mode.h, ArduCopter/mode_rtl.cpp
This allows the vehicle's speed to be changed during RTL (either the flight mode or mission command) using a DO_CHANGE_SPEED command.
This has been tested in SITL (both the mode and the mission) and works as expected.
=> Copter: RTL accepts do-change-speed commands

libraries/AP_RCProtocol/AP_RCProtocol.cpp, libraries/AP_RCProtocol/AP_RCProtocol_Backend.cpp, libraries/AP_RCProtocol/AP_RCProtocol_Backend.h, libraries/AP_RCProtocol/AP_RCProtocol_DSM.cpp, libraries/AP_RCProtocol/AP_RCProtocol_SRXL2.cpp, libraries/AP_RCProtocol/AP_RCProtocol_SRXL2.h
Having the DSM backend calling into the SRXL2 backend isn't nice, so this fixes that.
Two commits, one changing namespaces the other moving the code into the correct files.
```
Durandal                      0      *           0       0                 0      0      0
KakuteH7-bdshot               0      *           0       0                 0      0      0
MatekF405                     0      *           0       0                 0      0      0
Pixhawk1-1M                   0      *           0       0                 0      0      0 …
```
=> Remove coupling between AP_RCProtocols SRXL2 and DSM

Rover/Parameters.cpp
This adds Dock mode to the list of values for INTITAL_MODE and MODE1 parameters in Rover.
Thanks @rmackay9 for bringing this to my notice.
=> Rover: add dock mode to INTIAL_MODE and MODE1 params

ArduCopter/GCS_Mavlink.cpp, ArduCopter/GCS_Mavlink.h, ArduCopter/mode.h, ArduCopter/mode_auto.cpp, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
- mission state (useful for "complete")
- number of commands
@auturgy this might be problematic in that I've implemented the spec as-written which is the number of commands - but we consider the home location a command, so your current squence number is never going to equal this new "total" field.
=> Add support for new fields in MISSION_CURRENT message

libraries/AP_DDS/AP_DDS_Client.cpp, libraries/AP_DDS/AP_DDS_Client.h
* Removes the hard coded timing, now it's driven by the GPS update times
* Changed the function signature to return true if the data topic has been changed
* Tested on SITL, got ~4.5Hz
* Relates to #23277 
* This is the recommended way of doing it, by @tridge
=> AP_DDS: Publish NavSatFix as soon as its available

.gitmodules
* No new features added, just switching to the tag on master
* Develop tags expire
=> AP_DDS: Switch to master instead of develop tag

libraries/AP_HAL_ChibiOS/hwdef/PixPilot-V3/hwdef-bl.dat, libraries/AP_HAL_ChibiOS/hwdef/PixSurveyA1-IND/hwdef-bl.dat, libraries/AP_HAL_ChibiOS/hwdef/thepeach-k1/hwdef-bl.dat, libraries/AP_HAL_ChibiOS/hwdef/thepeach-r1/hwdef-bl.dat
.... more fall-out from the size changes in the new ChibiOS.
All bootloaders build locally for me past this except an EVAL board.
=> Get another 4 bootloaders compiling

libraries/AC_WPNav/AC_WPNav.cpp, libraries/AC_WPNav/AC_WPNav.h
This is an alternative to https://github.com/ArduPilot/ardupilot/pull/23220
This PR fixes an issue where RTL_SPEED = 400 but if users changed the WPNAV_SPEED parameter the vehicle would immediately change to this new speed.
This has been tested in SITL to confirm that user changes to WPNAV_SPEED will only take effect if the WPNAV_SPEED parameter value was used to initialise the vehicle's speed in the current mode.  The results are slightly unintuitive in some situations though so I'm happy to discuss if people think the behaviour is odd.
1. Fly in Auto mode, waypoint command, changes to WPNAV_SPEED take effect immediately
2. Fly in Auto mode, RTL command, if RTL_SPEED was zero when command started meaning WPNAV_SPEED was used, changes to WPNAV_SPEED will take effect immediately.  If …
=> AC_WPNav: wpnav speed param check fixed

ArduPlane/Parameters.cpp, ArduPlane/Plane.h, ArduPlane/defines.h, ArduPlane/mode.cpp, ArduPlane/quadplane.cpp, ArduPlane/quadplane.h, ArduPlane/radio.cpp, ArduPlane/servos.cpp, ArduPlane/takeoff.cpp
prevents throttle up while stick is still hard right...spectator saver
similar to VTOL takeoff prevention when rudder armed
tested in SITL
addresses #23181
=> Plane:rudder arm in AUTO/TAKEOFF only after stick returns

ArduPlane/Attitude.cpp, ArduPlane/quadplane.cpp, ArduPlane/quadplane.h, ArduPlane/tailsitter.cpp, ArduPlane/tailsitter.h, ArduPlane/transition.h
This moves the quadplane allows stick mixing bool out of the `set_FW_roll_pitch` function. This removes the use of a local variable in the per-mode if allowing future clean ups. After this the `mode_stabilize` case can be moved into the mode.
=> Plane: use dedicated quadplane function for stick mixing enable

ArduPlane/quadplane.cpp
in master the wait works only the first time (uses the zero initialized variable to allow it to run the wait) but subsequent takeoffs bypass this and immediately takeoff without waiting..this fixes that...
SITL confirms the fix in quadplanes
=> Plane: fix error in Qplane wait for rudder neutral
