ArduPilot/ardupilot

libraries/AP_Mission/AP_Mission.cpp
Jump tags to use optimized mission search
This is a single 2-line commit on top of PR https://github.com/ArduPilot/ardupilot/pull/22421 to jive with https://github.com/ArduPilot/ardupilot/pull/22921
=> AP_Mission: Jump tags to use optimized mission search

.pre-commit-config.yaml
=> pre-commit: Disable isort and mypy temporarily

libraries/AP_Scripting/applets/Aerobatics/FixedWing/README.md, libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
would have prevented a crash I had today while distracted running the Airshow as a demo to someone...duh!
my fault but this would have saved the plane
=> AP_Scripting:provide altitude loss safety abort for plane aerobatics

libraries/AP_Arming/AP_Arming.cpp
NFC...correct description of parameter as discussed in Devcall..will also update each wiki arming page
=> AP_Arming:correct ARMING_RUDDER description

AntennaTracker/Parameters.cpp, ArduCopter/Parameters.cpp, ArduPlane/Parameters.cpp, ArduSub/Parameters.cpp, Blimp/Parameters.cpp, Rover/Parameters.cpp, Tools/Replay/Replay.cpp, Tools/autotest/autotest.py, Tools/autotest/common.py, Tools/autotest/pysim/util.py, Tools/autotest/sim_vehicle.py, Tools/scripts/build_ci.sh, libraries/AP_DAL/AP_DAL.cpp, libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus/hwdef.dat, libraries/AP_InertialSensor/AP_InertialSensor.cpp, libraries/AP_InertialSensor/AP_InertialSensor.h, libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp, libraries/AP_InertialSensor/AP_InertialSensor_Params.cpp, libraries/AP_InertialSensor/AP_InertialSensor_Params.h, libraries/AP_InertialSensor/AP_InertialSensor_config.h, libraries/AP_InertialSensor/AP_InertialSensor_tempcal.cpp, libraries/AP_InertialSensor/AP_InertialSensor_tempcal.h, libraries/AP_NavEKF/AP_NavEKF_core_common.h, libraries/AP_NavEKF3/AP_NavEKF3.cpp, libraries/SITL/SITL.cpp, libraries/SITL/SITL.h, wscript
* This allows instantiation of more IMU instances atleast for logging.
* Upto 4 IMUs support tested.
* Fix 5 IMU gives error with AP_DAL
=> Additional IMUs support

Tools/environment_install/install-prereqs-ubuntu.sh
Allow to install dev environment on distros that have 'jolnir' as release name
=> Tools: add jolnir on install script

Tools/AP_Periph/AP_Periph.cpp, libraries/AP_CANManager/AP_SLCANIface.cpp, libraries/AP_Common/tests/test_expandingstring_failure.cpp, libraries/AP_Common/tests/test_nmea_print.cpp, libraries/AP_Common/tests/test_nmea_vaprint.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS_LORD.cpp, libraries/AP_HAL/UARTDriver.h, libraries/AP_HAL/Util.cpp, libraries/AP_HAL/utility/BetterStream.cpp, libraries/AP_HAL/utility/BetterStream.h, libraries/AP_HAL_ChibiOS/UARTDriver.cpp, libraries/AP_HAL_ChibiOS/UARTDriver.h, libraries/AP_HAL_ESP32/UARTDriver.cpp, libraries/AP_HAL_ESP32/UARTDriver.h, libraries/AP_HAL_ESP32/WiFiDriver.cpp, libraries/AP_HAL_ESP32/WiFiDriver.h, libraries/AP_HAL_ESP32/WiFiUdpDriver.cpp, libraries/AP_HAL_ESP32/WiFiUdpDriver.h, libraries/AP_HAL_Empty/UARTDriver.cpp, libraries/AP_HAL_Empty/UARTDriver.h, libraries/AP_HAL_Linux/UARTDriver.cpp, libraries/AP_HAL_Linux/UARTDriver.h, libraries/AP_HAL_SITL/UARTDriver.cpp, libraries/AP_HAL_SITL/UARTDriver.h, libraries/AP_Mount/AP_Mount_Siyi.cpp, libraries/AP_OpticalFlow/AP_OpticalFlow_CXOF.cpp, libraries/GCS_MAVLink/GCS_Common.cpp
Actually checking the return value of the existing call is pretty clunky.  At this means we become more C++-ish vs the -1 return value from Arduino days.
=> Add and use a "bool read(c)" method to AP_HAL

Rover/AP_Arming.cpp, Rover/mode_auto.cpp, libraries/AP_Mission/AP_Mission.cpp
trivial change requested by @tridge
=> AP_Mission: allow mission clear in AUTO when disarmed

Tools/AP_Bootloader/board_types.txt
allocate a board ID for AP_HW_JFB110
=> Tools: allocate a board ID for AP_HW_JFB110

libraries/AP_DDS/AP_DDS_Client.cpp, libraries/AP_DDS/AP_DDS_Client.h, libraries/AP_DDS/AP_DDS_Topic_Table.h, libraries/AP_DDS/dds_xrce_profile.xml
* Implement NavSatFix message
* Support covariance
* Set frame ID to WGS-84
* Closes #23284
=> AP_DDS: Add multi-topic support with NavSatFix

libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
This PR is work from @priseborough and it disables learning of wind estimates while the vehicle is dead reckoning.  This has been tested in SITL and below are before vs after pictures of the EKF3's wind estimates.  The red line shows when the GPS is disabled.
This does not seem to make a huge difference to where the vehicle actually lands.  Below is a SITL test with the Copter dead-reckoning failsafe set to 50 sec (meaning the EKF keeps trying to estimate position for 50sec after loss of GPS).
=> AP_NavEKF3: reduce updates to wind estimates while dead reckoning

libraries/AP_DDS/dds_xrce_profile.xml
Resolves #23365.
Here is the print of it working with SITL:
And here is the example provided by @Ryanf55:
=> AP_DDS: Switch NavSatFix topic to sensor data QOS

libraries/SRV_Channel/SRV_Channel.cpp
Follow up to https://github.com/ArduPilot/ardupilot/pull/23244 moving servo channels to new format,
=> SRV_Channel: move FUNCTION @Values to multi line format

Tools/autotest/param_metadata/param_parse.py
many scripts are now categoriesed e.g. Aerobatics
=> autotest: param_parse.py: recurse, don't glob in lua script dirs

Tools/CPUInfo/CPUInfo.cpp, Tools/ardupilotwaf/chibios.py, Tools/scripts/build_ci.sh, Tools/scripts/make_abin.sh
=> Tools: fixed build of CPUInfo and other tools

libraries/AP_TECS/AP_TECS.cpp
NFC...obviously  incorrect metadata here
=> AP_TECS: correct metadata for FLARE_HGT

Tools/ardupilotwaf/ap_library.py
@Ryanf55 asked about how to do this for AP_DDS, this shows the method
we could merge this without the change in AP_DDS
=> waf: per library C and C++ flags support

ArduCopter/Copter.cpp, ArduCopter/Copter.h, ArduPlane/AP_Arming.cpp, ArduPlane/Plane.h, Rover/AP_Arming.cpp, Rover/Rover.h, Tools/autotest/arducopter.py, Tools/autotest/arduplane.py, Tools/autotest/common.py, Tools/autotest/rover.py, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Vehicle/AP_Vehicle.h
Henry and I pair-programmed this.
We tested it in SITL (finding some other issues along the way), and also wrote some auto-tests for it.
=> AP_Arming: AP_Arming ensures mission items present when in auto mode

Tools/autotest/sim_vehicle.py
We haven't supported make for a very long time
=> Tools: sim_vehicle.py: remove old --build-system

libraries/AP_Radio/AP_Radio_bk2425.cpp, libraries/AP_Radio/AP_Radio_bk2425.h
=> AP_Radio: correct build of AP_Radio_bk2425

libraries/AP_EFI/AP_EFI_Serial_MS.cpp
Similar to 4585c9fdc1f5b2e6a962cc9d2be02bff5c347073
=> AP_EFI: avoid requesting data too often

libraries/AP_DDS/AP_DDS_Client.cpp, libraries/AP_DDS/AP_DDS_Client.h, libraries/AP_DDS/AP_DDS_Topic_Table.h, libraries/AP_DDS/Idl/sensor_msgs/msg/BatteryState.idl, libraries/AP_DDS/dds_xrce_profile.xml
Resolves #23360 
This is just a draft, I still need to integrate the battery data from AP_BattMonitor
For now it looks like this:
=> AP_DDS: Support sensor_msgs/BatteryState message

AntennaTracker/GCS_Mavlink.cpp
=> Tracker: remove annoying 'Command received' message

libraries/AP_HAL_ChibiOS/hwdef/OMNIBUSF7V2/hwdef.dat
=> hwdef: correct compilation of OMNIBUSF7V2

libraries/AP_Camera/AP_Camera.cpp
...so we can remove this stuff more easily over time
=> AP_Camera: add timestamp on parameter conversion function

Tools/autotest/autotest.py, Tools/scripts/build_autotest.sh, Tools/scripts/build_binaries.py
=> Tools: change autotest to python3

libraries/AP_InertialSensor/AP_InertialSensor.cpp, libraries/AP_InertialSensor/AP_InertialSensor.h, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
replaces https://github.com/ArduPilot/ardupilot/pull/21882
- can't force-push that branch over there.
This is that but with changes to avoid getting the wrong result :-)
=> Factor accel trim calibration from GCS to INS

libraries/AP_DDS/README.md
Recommend using our internal mirror because that's what's tested with our code.
=> AP_DDS: Use mirror of DDS Gen

libraries/AP_DDS/README.md
It came up in dev call that we want to recommend somewhere that devs should use these tools since it's not documented anywhere.
=> AP_DDS: Add developer recommended steps for pre-commit

libraries/AP_Mount/AP_Mount_Alexmos.cpp, libraries/AP_Mount/AP_Mount_Backend.cpp, libraries/AP_Mount/AP_Mount_Backend.h, libraries/AP_Mount/AP_Mount_Gremsy.h, libraries/AP_Mount/AP_Mount_Params.cpp, libraries/AP_Mount/AP_Mount_Params.h, libraries/AP_Mount/AP_Mount_SToRM32.h, libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp, libraries/AP_Mount/AP_Mount_Scripting.h, libraries/AP_Mount/AP_Mount_Servo.cpp, libraries/AP_Mount/AP_Mount_Siyi.cpp, libraries/AP_Mount/AP_Mount_SoloGimbal.cpp
=> AP_Mount: add MNTx_SYSID_DFLT param to easier support following another vehicle

libraries/AP_EFI/AP_EFI.h
=> AP_EFI : Hirth type id is reserved

libraries/AC_WPNav/AC_WPNav.cpp
Initialize near the use.
Initialize nearby for easy recognition.
=> AC_WPNav: Initialize near use

libraries/AP_DroneCAN/AP_Canard_iface.cpp, libraries/AP_DroneCAN/AP_Canard_iface.h
Requires this PR to be merged in: https://github.com/dronecan/libcanard/pull/24
=> Use CanardTxTransfer object when sending payloads

ArduPlane/AP_Arming.cpp, ArduPlane/ArduPlane.cpp, ArduPlane/Attitude.cpp, ArduPlane/GCS_Mavlink.cpp, ArduPlane/Plane.h, ArduPlane/mode_acro.cpp, ArduPlane/mode_loiter.cpp, ArduPlane/mode_rtl.cpp, ArduPlane/navigation.cpp, ArduPlane/radio.cpp, ArduPlane/reverse_thrust.cpp, ArduPlane/servos.cpp, ArduPlane/takeoff.cpp
=> Plane:add FlightOptions helper

libraries/AP_Logger/AP_Logger.cpp, libraries/AP_Logger/AP_Logger.h, libraries/AP_Logger/AP_Logger_Backend.cpp, libraries/AP_Logger/AP_Logger_Backend.h, libraries/AP_Logger/AP_Logger_Block.cpp, libraries/AP_Logger/AP_Logger_File.cpp, libraries/AP_Logger/AP_Logger_File.h, libraries/AP_Logger/AP_Logger_MAVLink.cpp, libraries/AP_Param/AP_Param.h
this makes replay logging much nicer for users, so should encourage us to get more replay logs
=> Plane: backport LOG_DISARMED=3 to 4.4

libraries/AP_HAL_ChibiOS/hwdef/common/stm32l4+_mcuconf.h
=> Advanced timers are now determined automatically on L4+

libraries/AP_Scripting/examples/servo_slew.lua
useful for measuring servo capabilities by looking at achieved deflection vs frequency
=> AP_Scripting: added example that slew a servo with controls

.github/workflows/test_environment.yml, Tools/environment_install/install-prereqs-ubuntu.sh, Vagrantfile
We've had to move to venv to here - polluting the system Python is now very difficult to do.
Also incorporates a change to waf required for Lunar's Python to function for our `waf`.
=> Add support for Ubuntu Lunar release

Tools/autotest/sim_vehicle.py
saves some time with rapid small code changes
=> Tools: option to not reconfigure on each sim_vehicle.py run

libraries/AP_DDS/AP_DDS_Client.cpp, libraries/AP_DDS/AP_DDS_Client.h, libraries/AP_DDS/AP_DDS_Topic_Table.h, libraries/AP_DDS/Idl/geographic_msgs/msg/GeoPoint.idl, libraries/AP_DDS/Idl/geographic_msgs/msg/GeoPose.idl, libraries/AP_DDS/Idl/geographic_msgs/msg/GeoPoseStamped.idl, libraries/AP_DDS/README.md, libraries/AP_DDS/dds_xrce_profile.xml
Resolves #23534, here is the PR working on SITL:
Uses the same orientation logic as #23480 since both follow ENU
=> AP_DDS: GeoPose Publisher

Tools/scripts/mavlink_parse.py
Backport #22278 to latest active Sub version.
=> Sub: backport mavlink_parse for docs generation

Tools/simulink/arducopter/functions/dcmFromEuler.m, Tools/simulink/arducopter/functions/fromAxisAngle.m, Tools/simulink/arducopter/functions/quatMult.m, Tools/simulink/arducopter/sid_controller_validation.m
=> Tools: Add missing functions for Simulink model

Tools/autotest/web-firmware/Tools/FilterReview/DecodeDevID.js, Tools/autotest/web-firmware/Tools/FilterReview/FilterReview.js, Tools/autotest/web-firmware/Tools/FilterReview/Readme.md, Tools/autotest/web-firmware/Tools/FilterReview/index.html, Tools/autotest/web-firmware/Tools/FilterReview/parser.js
This adds a browser based FFT log review tool for batch logging. Mostly works, but I have not tested on all combinations of batch logging options. 
Like https://github.com/ArduPilot/ardupilot/pull/22775 this uses the excellent js parser from @Williangalvani  https://github.com/Williangalvani/JsDataflashParser (I had to mess with a tiny bit to get the batch logs to parse)
Lots of scale options, can select/un-select all lines. Some FFT options, option to use only a sub section of the log based on start and end time. Some info about sensors, logging rate and FFT resolution.
Also a spectogram, so you can (hopefully see peeks moving about with throttle/rpm). This log is not great because everything is logging, the spectogram should be a much better for just a single gyro.
Future enhancement is …
=> Tools: Web: Add FFT batch log review tool

Tools/autotest/web-firmware/Tools/FilterReview/FilterReview.js, Tools/autotest/web-firmware/Tools/FilterReview/index.html, Tools/autotest/web-firmware/Tools/FilterReview/parser.js
- move to the latest version of the log parser: https://github.com/Williangalvani/JsDataflashParser/pull/1
- Fixes a bug if none continuous sensors logging was being used (eg gyro 1 and 3 without 2)
- moves to array math functions in place of loops. I was hoping for a speedup here, but it doesn't make a difference. But I do think it makes the code a bit easier to follow. We could potentially go a step further and use matrix functions, however I think that might be a step too far.
=> Tools: Web: FilterReview update

Tools/autotest/common.py
... also pass through suppress_stdout to TeeBoth
in the case we couldn't run some tools we would return early, meaning we wouldn't reset things appropriately and carry on.
We were also not populating the result object correctly.
=> autotest: break out a dump_process_status method

libraries/AC_Avoidance/AP_OADatabase.cpp, libraries/AC_Avoidance/AP_OADatabase.h
Also remove namespacing from OA_DbOutputLevel
=> AC_Avoidance: make _output_level AP_Enum

Tools/ardupilotwaf/boards.py, libraries/AP_Scripting/generator/description/bindings.desc, wscript
This allows you to configure skyviper with --enable-scripting and have it work
=> Fix SkyViper scripting

Tools/autotest/web-firmware/Tools/FilterReview/FilterReview.js, Tools/autotest/web-firmware/Tools/FilterReview/index.html
This fixes a few issues and adds notch tracking overlay based on configured settings. Also moves to a 2D plot for better speed (and easier overlaying)
Currently the overlay is spectograph only, but it could be added to the average plot also.
=> Tools: Web: FilterReview: add spectrograph notch tracking overlay

libraries/AP_HAL_Linux/CANSocketIface.cpp, libraries/AP_HAL_SITL/CANSocketIface.cpp
=> remove std:: scope from uint16_t

libraries/AP_DroneCAN/canard/canard_helpers_user.h
* Requires this PR to be merged in first https://github.com/dronecan/libcanard/pull/30
=> Move to using malloc and placement new for allocation in libcanard cxx iface

libraries/AP_HAL_ChibiOS/RCOutput.cpp
The new LED thread had a locking problem which could lead to watchdogs
=> Correct locking on LED thread

libraries/AP_RCProtocol/AP_RCProtocol_ST24.cpp
Fix the issue of ST24 receiver not working
=> AP_RCProtocol: Fix the issue of ST24 receiver not working

Tools/autotest/common.py, libraries/SITL/SITL.cpp
=> SITL: add metadata to simulated compass

libraries/AP_GPS/AP_GPS_GSOF.h
* Another trivial gsof improvement, this was spotted by @magicrub
=> AP_GPS: More const for gsofmsgreq

libraries/AP_Notify/AP_Notify.cpp
Too many LEDs spoil the sim...
=> AP_Notify: bump up max number of simulated notify devices

ArduPlane/mode_takeoff.cpp
replaces #23630....has not been squashed in order to show, step-by-step, the changes for review....once approved, I will squash , change commit messages , and a merge on CI pass label can be attached.
=> Mode takeoff step by step

libraries/AP_Motors/examples/AP_Motors_test/AP_Motors_test.cpp
This makes a json file such as this: 
[MotorsJSON.txt](https://github.com/ArduPilot/ardupilot/files/11511969/MotorsJSON.txt)
This allows tools to give extra info on motor test pages or frame selection, only matrix types currently but we could others manualy.
A example wiki page from @yuri-rage 
https://discuss.ardupilot.org/t/copter-wiki-motor-diagram-overhaul/101046/24?u=iampete
My Mission planner attempt:
https://github.com/ArduPilot/MissionPlanner/pull/3043
To get json just run example and dump to file, `./build/linux/examples/AP_Motors_test p > test.json`
This is a snippet:
```
{
"Version": "AP_Motors library test ver 1.1",
"layouts": [
{
"Class": 1,
"ClassName": "QUAD",
"Type": 0,
"TypeName": "PLUS",
"motors": [
{
"Number": 1,
"TestOrder": 2,
"Rotation": "CCW",
"Roll": -0.5000, …
```
=> AP_Motors: example: add ability to dump all matrix motor layouts in JSON format

libraries/AP_ICEngine/AP_ICEngine.cpp
if you have a mission item for engine control with delayed start at height and the engine is already running them it would put the ICE subsystem into a state where it would no longer start the engine
It was actually 2 bugs:
- an engine control to do a height delayed start should be ignored if the engine is already running. This prevents an engine control to start the engine from stopping the engine
- a start_chan high should always try to start the engine immediately, even if in the wait state
=> AP_ICEngine: fixed a bug engine control when running (4.3 backport)

libraries/AP_DroneCAN/AP_DroneCAN.cpp, libraries/AP_DroneCAN/AP_DroneCAN.h
This adds support for the these ESCs (the ones that list CAN support):
https://www.hobbywing.com/en/products?id=46
These ESCs use DroneCAN but with their own message set. This is a bit annoying, but worth it for an ESC maker that has a good reputation for high quality ESCs.
Tested on a 14S 60A ESC in bench testing. Pending flight testing
=> DroneCAN: support hobbywing DroneCAN ESCs

Tools/scripts/build_binaries.py, Tools/scripts/generate_manifest.py
temporary measure for new beta-4.3 for RCIN fix
=> Tools: support beta-4.3 tags for doing new beta releases

libraries/AP_Baro/AP_Baro.cpp, libraries/AP_Baro/AP_Baro.h, libraries/AP_Compass/AP_Compass.cpp, libraries/AP_Compass/AP_Compass.h, libraries/AP_IOMCU/AP_IOMCU.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
Added the ability to test sensor health through LUA.
This will be used for our internal testing which will use LUA.
=> AP Scripting: Add health

Tools/scripts/build_sizes/build_sizes.py
=> Tools: added beta-4.3 to build list

libraries/AP_DDS/README.md
This adds the setup for UDP to the README (and recommends it). 
I did change the ordering of some of the CLI args, finding it easier to put the thing you modify (DDS serial port number) at the end. 
Also, I made all the sim_vehicle commands with `-DG` so you only compile in debug, and also get GDB terminal. Some were missing `--console`, so I added that. 
I left out `--map` because people should use Foxglove or RVIZ instead :)
=> AP_DDS: Add UDP instructions to README

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py, libraries/AP_RCProtocol/AP_RCProtocol.h
I need this for something which isn't an IO firmware!
=> Add and use AP_RCPROTOCOL_ENABLE_SET_RC_PROTOCOLS

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
we need to align the endpoint ID in the structure
=> HAL_ChibiOS: fixed USB pass-thru for 2nd USB endpoint

ArduPlane/Parameters.cpp, libraries/AP_ICEngine/AP_ICEngine.cpp, libraries/AP_ICEngine/AP_ICEngine.h
and use RPM singleton for AP_ICEngine
=> ICE: fixed AP_ICEngine without RPM support

Tools/autotest/param_metadata/param.py, libraries/AP_Scripting/drivers/EFI_Halo6000.lua, libraries/AP_Scripting/drivers/EFI_Halo6000.md, libraries/AP_Scripting/examples/EFI_tester.lua
used to monitor Foxtech Halo6000 generator for Thor210 hexacopter
=> AP_Scripting: added Halo6000 generator/EFI driver

libraries/AP_TemperatureSensor/AP_TemperatureSensor.cpp, libraries/AP_TemperatureSensor/AP_TemperatureSensor.h, libraries/AP_TemperatureSensor/AP_TemperatureSensor_MAX31865.cpp, libraries/AP_TemperatureSensor/AP_TemperatureSensor_MCP9600.cpp
slow down temp driver threads and some minor cleanup
=> AP_Temperature: slow down temp driver thread

libraries/AP_HAL_ChibiOS/hwdef/speedybeef4v3/hwdef.dat
=> Remove bdshot from speedybeef4 as it doesn't work an increases flash usage

Tools/autotest/common.py
sometimes we're not done in 2 seconds
=> autotest: poll ftp status at intervals

libraries/AP_HAL_ChibiOS/hwdef/common/malloc.c
this is replacement for #23941 
that PR won't work on low memory systems, and also wastes a lot of memory. This PR fixes the issue plus makes filesystem operations faster by avoiding the bouncebuffer on most operations
=> ChibiOS: fixed mkdir by moving allocation to HAL_ChibiOS for FATFS

libraries/AP_DDS/AP_DDS_Client.cpp
* Found under valgrind
`Conditional jump or move depends on uninitialised value(s)`
=> AP_DDS: Fix unitialized memory

libraries/AP_Scripting/drivers/EFI_Halo6000.lua
=> AP_Scripting: fixed temperatures for Halo6000 driver

libraries/AP_JSButton/tests/test_jsbutton.cpp, libraries/AP_JSButton/tests/wscript
=> AP_JSButton: add unittest

Tools/ardupilotwaf/boards.py, Tools/ardupilotwaf/chibios.py, libraries/AP_DroneCAN/AP_Canard_iface.cpp, libraries/AP_DroneCAN/AP_Canard_iface.h, libraries/AP_DroneCAN/AP_DroneCAN.h, libraries/AP_GPS/AP_GPS_DroneCAN.cpp, libraries/AP_GPS/AP_GPS_DroneCAN.h, libraries/AP_HAL_ChibiOS/CANFDIface.cpp, libraries/AP_HAL_ChibiOS/CanIface.cpp
This fixes multiple bugs in the canard implementation in ArduPilot AP_DroneCAN, shown by testing with RTCM injection
=> DroneCAN: fix RTK injection into DroneCAN GPS

libraries/AP_Mount/AP_Mount.cpp
... but still do the parameter conversion
=> AP_Mount: correct compilation when HAL_MOUNT_SERVO_ENABLED is 0

Tools/AP_Periph/AP_Periph.cpp, Tools/AP_Periph/AP_Periph.h, Tools/AP_Periph/Parameters.cpp, Tools/AP_Periph/Parameters.h, Tools/AP_Periph/can.cpp, Tools/ardupilotwaf/boards.py, libraries/AP_HAL_ChibiOS/hwdef/MatekL431-Proximity/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
boolean truth rather than defines, and simplifies code
=> Use HAL_PROXIMITY_ENABLED in place of defined(HAL_PERIPH_ENABLE_PRX)

Tools/scripts/size_compare_branches.py
=> Tools: size_compare_branches.py: blacklist build of Pixhawk1-bdshot

Rover/AP_Arming.cpp
Fixed a typo in AP_Arming.cpp.
=> Rover: Comment typo fix in AP_Arming.cpp

libraries/AP_Scripting/applets/Aerobatics/FixedWing/dual_log.py, libraries/AP_Scripting/applets/Aerobatics/FixedWing/dual_plane.sh, libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua, libraries/AP_Scripting/applets/Aerobatics/FixedWing/view_paths.py, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
dual-aircraft synchronised aerobatics
Note that this has now been converted to using the new mavlink parsing code in lua, and includes a lua implementation of the jitter correction code
=> AP_Scripting: dual-aircraft synchrosised aerobatics

Tools/scripts/solution_status_change.py
=> Tools: tidy solution_status_change.py

libraries/AP_DDS/README.md
This updates the list of topics with what's available. Mainly, adding subscriber support.
=> AP_DDS: Update docs for supported topics

libraries/AP_HAL_Linux/HAL_Linux_Class.cpp
As requested on https://github.com/ArduPilot/ardupilot/pull/23937 (@lucasdemarchi )
=> AP_HAL_Linux: fix help ouput from Options to Examples

libraries/AP_Scripting/examples/plane-wind-fs.lua
Just fixes up the example so it no longer needs the luacheck exception.
=> AP_Scripting: examples: plane-wind-fs: fixup for luacheck

ArduSub/surface_bottom_detector.cpp, ArduSub/system.cpp
Fixed comment typo in ArduSub code
=> ArduSub: Comment Typo Fix

ArduCopter/mode_brake.cpp
BRAKE treatment is available for SOLO.
Indicating that it is for SOLO makes it easier to understand.
=> Copter: Note that this process is for SOLO

ArduCopter/GCS_Mavlink.cpp, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
support MAV_CMD_AIRFRAME_CONFIGURATION
=> Plane: added support for landing gear control

libraries/AP_DroneCAN/AP_DroneCAN.cpp, libraries/AP_Notify/DroneCAN_RGB_LED.cpp, libraries/AP_Notify/DroneCAN_RGB_LED.h
=> DroneCAN: fixed LEDs

libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
=> AC_AutoTune: correct incorrect min raw rate value

ArduPlane/ArduPlane.cpp, ArduPlane/Plane.cpp, ArduPlane/Plane.h, ArduPlane/mode.cpp, ArduPlane/mode.h, ArduPlane/mode_auto.cpp
Adds is_landing and is_taking_off functionality for Plane as requested. Closes [23901](https://github.com/ArduPilot/ardupilot/issues/23901)
=> Plane: support is_landing and is_taking_off in lua scripts

libraries/AP_Logger/AP_Logger.cpp
=> AP_Logger:correct blk rate param metadata

Tools/autotest/common.py
also add several convenience functions
=> Tidy autotest MISSION_ACK testing

libraries/AP_Mount/AP_Mount_Xacti.cpp
This removes some debug that was left-over from PR https://github.com/ArduPilot/ardupilot/pull/24117
Sorry!
=> AP_Mount: remove xacti debug

libraries/AC_WPNav/AC_Circle.cpp
=> :AC_WPNav: add roi circle_option metadata

libraries/AP_Mount/AP_Mount_Backend.cpp
this work sponsored by Harris Aerial
=> AP_Mount: correct gimbal manager flags

ArduPlane/quadplane.cpp
this message was lost in recent refactoring
=> Plane: fixed transition started airspeed message

Tools/AP_Bootloader/board_types.txt
@peterbarker  Hello! This is my designed board your help!
=> AP_HAL_ChiBiOS Reserve board id for PodmanH7

ArduPlane/mode_training.cpp, ArduPlane/servos.cpp
Along the same lines as https://github.com/ArduPilot/ardupilot/pull/24096 this moves pilot inputs up into the mode.
=> Plane: Training: output rudder from mode run function

Tools/environment_install/install-prereqs-mac.sh
Some sort of repository corruption on the github side; see https://github.com/orgs/Homebrew/discussions/4612
Will need to be a temporary measure...
=> Tools: remove brew update (fix MacOSX CI)

libraries/AP_BoardConfig/AP_BoardConfig.h
add accessor for param BRD_SERIAL_NUM
=> AP_BoardConfig: add accessor for param BRD_SERIAL_NUM

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.h
wrap things in AP_INERTIALSENSOR_ENABLED where needed. This is useful for AP_Peirph builds
=> AP_Arming: wrap things in AP_INERTIALSENSOR_ENABLED

ArduCopter/AP_Arming.cpp, libraries/AC_AutoTune/AC_AutoTune_Heli.h, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_BattMonitor/AP_BattMonitor_INA2xx.h, libraries/AP_Follow/AP_Follow.h, libraries/AP_HAL_SITL/UARTDriver.cpp, libraries/AP_Logger/AP_Logger_Block.cpp, libraries/AP_Math/AP_Math.cpp, libraries/AP_OSD/AP_OSD_ParamSetting.cpp, libraries/AP_Proximity/AP_Proximity_RPLidarA2.cpp, libraries/AP_TECS/AP_TECS.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/SITL/SIM_Frame.cpp, libraries/SITL/SIM_Helicopter.h, libraries/SITL/SIM_LM2755.h, libraries/SITL/SIM_VectorNav.h, libraries/SITL/SIM_XPlane.h
Cherry-picked from https://github.com/ArduPilot/ardupilot/pull/24064
May help us bisect the test issue in there if nothing else.
=> Cherry-picked fixes from MacOSX compiler fixes

ArduSub/ArduSub.cpp, ArduSub/Parameters.cpp, ArduSub/Parameters.h, ArduSub/Sub.h, ArduSub/config.h, ArduSub/system.cpp
=> Sub: Add AP_Stats

Dockerfile
* That's what most devs have moved to
* This gets us closer in line with using ROS 2 humble
=> Update to jammy in Docker

Tools/scripts/build_binaries.py
#24275 only covered the "latest" case
=> Tools: don't fail if feature extraction failed (beta/stable version)

ArduPlane/commands_logic.cpp, ArduPlane/mode_qrtl.cpp, ArduPlane/navigation.cpp, libraries/AP_Math/definitions.h, libraries/AP_Mission/AP_Mission_Commands.cpp, libraries/Filter/tests/test_notchfilter.cpp
Extracts commits from https://github.com/ArduPilot/ardupilot/pull/24064 to help bisect what's causing CAN sim to reliably fail
=> Extract more MacOSX fixes from CI-problematic PR

libraries/AP_RCProtocol/AP_RCProtocol.cpp, libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp
Fixes https://github.com/ArduPilot/ardupilot/issues/22886
=> Rescan at CRSFv3 baudrates to avoid RX loss

libraries/RC_Channel/RC_Channel.cpp
NFC...normalized formatting...tried to make presentation in MP drop down viewable and consistent where possible
=> RC_Channel:clean up metadata for AUX switches

Tools/AP_Bootloader/board_types.txt, libraries/AP_HAL_ChibiOS/hwdef/SIYI_N7/hwdef-bl.dat, libraries/AP_HAL_ChibiOS/hwdef/SIYI_N7/hwdef.dat
=> hwdef: added SIYI N7 flight controller

ArduPlane/Log.cpp
NFC....helps in decoding QPlane logs
=> Plane:expand log metadata for QTUN

ArduCopter/Parameters.cpp
Param only takes effect at init.
=> Copter: SURFTRAK_MODE: mark as reboot required

ArduSub/GCS_Mavlink.cpp, ArduSub/mode.h, ArduSub/mode_guided.cpp
Improved support for the Mavlink command: SET_POSITION_TARGET_LOCAL_NED.
1. Added support for MAV_FRAME_BODY_FRD coordinate frame of reference.
2. Included handling of yaw control.
3. Added overloaded functions for:
- guided_set_destination_posvel()
- guided_set_velocity()
- guided_set_destination()
=> Sub: Improved support for SET_POSITION_TARGET_LOCAL_NED (MAV ID: #84)

Tools/autotest/arduplane.py
taking off when we're already aloft
also correct the test to make things actually tested; things were setup in such a way they'd pass without testing the things they were supposed to be
=> autotest: tweak plan GCS failsafe test

Tools/autotest/common.py, libraries/SITL/SIM_GPS.cpp, libraries/SITL/SIM_GPS.h, libraries/SITL/SITL.cpp
allow for testing of the MSP GPS driver
=> SITL: added simulated MSP GPS

ArduCopter/Copter.cpp
The RATE in the method description is 3.3 Hz.
In the task table, it is 3 Hz.
Change the method description.
=> Copter: Change RATE (NFC)

libraries/AP_L1_Control/AP_L1_Control.cpp
See details here: https://github.com/ArduPilot/ardupilot/issues/24319
=> Fixed formula in AP_L1_Control::nav_roll_cd

libraries/AC_Fence/AC_Fence.cpp
these aren't just polygon fences ('though they used to be)
=> AC_Fence: clarify bit 2 in FENCE_ENABLE parameter

ArduPlane/tiltrotor.cpp
=> Plane:correct metatdata for Q_YAW_ANGLE param

Tools/AP_Bootloader/board_types.txt
ControlZero revision G board ID
=> Tools:Reserve board ID for M10059G

libraries/AP_RangeFinder/AP_RangeFinder_NoopLoop.cpp
correct max dist value   its 8m not 8000m
=> AP_RangeFinder:correct nooploop max dist

Tools/autotest/arducopter.py, Tools/autotest/helicopter.py
use common wait_altitude instead
=> autotest: remove copter wait_for_alt

libraries/AP_Networking/AP_Networking.cpp
This message changes from debug to informational.
=> AP_Networking: Change message level from DEBUG to INFO

libraries/SITL/SIM_GPS.cpp, libraries/SITL/SIM_GPS.h
* These are also needed by the upcoming GSOF PR
=> SITL: Add heading and speed_2d utils

ArduPlane/mode.cpp, Tools/autotest/arduplane.py
Not good, but better than nothing.
Based on top of https://github.com/ArduPilot/ardupilot/pull/24535 which fixes the bug being tested for here.
Test fails before the fix, passes after.
=> Add autotest for MAV_CMD_GUIDED_CHANGE_ALTITUDE

libraries/AP_DDS/AP_DDS_Client.cpp, libraries/AP_DDS/AP_DDS_Client.h, libraries/AP_DDS/AP_DDS_Topic_Table.h, libraries/AP_DDS/README.md, libraries/AP_DDS/dds_xrce_profile.xml
This adds the velocity control DDS topic through a TwistStamped message compliant with ROS REP 147. It obeys the plan decided here:
https://github.com/ArduPilot/ardupilot/issues/23363
Run SITL (make sure you set the DDS_ENABLE param)
```
sim_vehicle.py -v ArduPlane -D --enable-dds
```
Then, run the microROS agent
```
(.humble) ryan@ryan-B650-970:~/Development/ardu_ws/src/ardupilot/libraries/AP_DDS$ ros2 run micro_ros_agent micro_ros_agent udp4 -p 2019 -r dds_xrce_profile.xml
[1690947142.178340] info     | UDPv4AgentLinux.cpp | init                     | running...             | port: 2019
[1690947142.178722] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 4
[1690947143.016761] info     | Root.cpp           | create_client            | …
```
=> AP_DDS: Add velocity control DDS subscriber

libraries/AP_RPM/AP_RPM.cpp, libraries/AP_RPM/AP_RPM_Params.cpp
AP_RPM: enable AP_RPM to set ESC Telemetry RPM
=> AP_RPM: enable AP_RPM to set ESC Telemetry RPM

Tools/scripts/sensor_status_change.py
```
2022-10-27 07:24:16.61:  health-SENSOR_RC_RECEIVER
2022-10-27 07:24:17.35:  health+SENSOR_RC_RECEIVER
2022-10-27 07:24:27.00:  health-SENSOR_RC_RECEIVER
2022-10-27 07:24:27.74:  health+SENSOR_RC_RECEIVER
2022-10-27 07:24:28.61:  health+SENSOR_YAW_POSITION health+SENSOR_Z_ALTITUDE_CONTROL health+SENSOR_XY_POSITION_CONTROL
2022-10-27 07:24:31.89:  health-SENSOR_RC_RECEIVER
2022-10-27 07:24:32.62:  health+SENSOR_RC_RECEIVER
2022-10-27 07:24:34.35:  health-SENSOR_RC_RECEIVER
2022-10-27 07:24:34.86:  health+SENSOR_RC_RECEIVER
2022-10-27 07:24:42.02:  health-SENSOR_RC_RECEIVER
```
=> Tools: add sensor_status_change.py

libraries/AP_VisualOdom/AP_VisualOdom.cpp, libraries/AP_VisualOdom/AP_VisualOdom.h, libraries/AP_VisualOdom/AP_VisualOdom_Backend.h, libraries/AP_VisualOdom/AP_VisualOdom_IntelT265.cpp, libraries/AP_VisualOdom/AP_VisualOdom_IntelT265.h, libraries/AP_VisualOdom/AP_VisualOdom_MAV.cpp, libraries/AP_VisualOdom/AP_VisualOdom_MAV.h, libraries/GCS_MAVLink/GCS_Common.cpp
The function takes position (linear) + orientation (angular), therefore it's a pose, not a position.
Reference: https://robotics.stackexchange.com/questions/19785/whats-the-difference-between-pose-measurement-and-position-measurement
=> Rename handle vision position estimate

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
- make and mark it flake8-clean
- fix several minor bugs
I've done a configure-all one master and this and verified no changes.
=> Clean chibios_hwdef.py - flake8 cleanliness

libraries/GCS_MAVLink/GCS_Common.cpp
title says it. Would cause issues if more is to come.
=> GCS_Common: brackets missing in switch case

libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
EKF3 filter status was initially set to zero then updated. This interacts with the IMU filtering code which checks filter status from a different thread to determine active_EKF_type(). When the race condition is hit then the IMU we are running notch filters on changes for a single sample, causing a notch filter glitch
this is a bench test reproduction without the fix:
and with the fix:
=> AP_NavEKF3: fixed race condition in updateFilterStatus()

Tools/AP_Bootloader/board_types.txt
Reserve board id for QioTekAdeptH743
=> AP_Bootloader: reserve board id for QioTekAdeptH743

Tools/ardupilotwaf/ap_library.py, Tools/autotest/arducopter.py, libraries/AP_HAL_SITL/wscript, libraries/SITL/SIM_BalanceBot.cpp, libraries/SITL/SIM_Blimp.cpp, libraries/SITL/SIM_GPS.cpp, libraries/SITL/SIM_MS5611.cpp, libraries/SITL/SIM_Plane.cpp, libraries/SITL/SITL.cpp, libraries/SITL/wscript
this builds on #24559 and extends to all files in libraries/SITL and libraries/AP_HAL_SITL
=> SITL: build libraries/SITL and libraries/AP_HAL_SITL as double

Tools/environment_install/install-prereqs-ubuntu.sh
=> Tools: Install the right serial module for Ubuntu lunar

libraries/AP_HAL_ChibiOS/hwdef/CubeRedPrimary/defaults.parm, libraries/AP_HAL_ChibiOS/hwdef/CubeRedPrimary/hwdef.dat, libraries/AP_Networking/AP_Networking.cpp
Fix default MAC Address to actually be more random-ish.
=> AP_Networking: fix default MAC Address

libraries/AP_DDS/AP_DDS_Client.h, libraries/AP_DDS/AP_DDS_config.h
This will be expanded upon for visual odom and other optional features. It's need by https://github.com/ArduPilot/ardupilot/pull/24518
=> AP_DDS: Add AP_DDS_config.h for feature defines

Tools/ros2/ardupilot_msgs/srv/ArmMotors.srv
Updates the description for Arming Motor Service .. as was requested in #24145 
@srmainwaring , @Ryanf55 , @tridge
=> Tools : Updated description  for Arming Motor Service

Tools/scripts/build_options.py, Tools/scripts/extract_features.py
this has been requested for MatekF765-Wing
=> Tools: allow selection of sdcard storage

BUILD.md
Took me a bit to figure this out, so I thought I'd add a hint to the BUILD.md.  Open to suggestions.
=> BUILD.md: instructions for using clang

libraries/AP_HAL_SITL/Synth.hpp
replace https://github.com/ArduPilot/ardupilot/pull/23642
=> AP_HAL_SITL: fix possible divide by 0 on synth.hpp

Tools/autotest/rover.py
take advantage of created infrastructure
remove bad patterns so other tests don't copy them!
=> autotest: tidy Rover DriveMaxRCIN test

libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h, libraries/AP_AHRS/AP_AHRS_Logging.cpp
this lowers CPU usage and fixes race conditions. It is a more complete fix for the issue in #24606
test flown on a CubeOrange quadplane successfully
=> AP_AHRS: return estimates from state structure

.github/workflows/test_sitl_blimp.yml, Tools/autotest/autotest.py, Tools/autotest/blimp.py, Tools/scripts/build_ci.sh
Add autotests to test Manual, Loiter and RTL modes.
Also adds github workflow and adds blimp to the build_ci.sh script so the tests are actually run on github.
This PR is currently rebased on my other pending PR to update the mavlink module (#24745), as it needs the RTL mode addition in pymavlink.
=> Blimp: Add autotests

libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp
CRSF/ELRS warning on H7 bds not required
=> AP_RCTelemetry:Surpress DMA warning on H7 bds

Tools/scripts/gen_stable.py
allows creation of the stable-4.3.x directories
I've run this on the server and it did create the stable-4.3.8 directories and populated them
=> Tools: support new stable release of 4.3.x

libraries/AP_HAL_ChibiOS/hwdef/thepeach-k1/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/thepeach-r1/hwdef.dat
... hwdef probably copied from the fmuv3 hwdef
=> hwdef: don't include solo gimbal or oreoled on thepeach autopilots

Tools/autotest/rover.py, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_ServoRelay.cpp
=> Take set-servo and set-relay commands as COMMAND_INT too

AntennaTracker/GCS_Mavlink.cpp, AntennaTracker/GCS_Mavlink.h, Tools/autotest/antennatracker.py
Based on https://github.com/ArduPilot/ardupilot/pull/24766
=> Tracker: take all command_longs as command_int too

libraries/AP_ADSB/AP_ADSB_Sagetech.cpp, libraries/AP_Camera/AP_RunCam.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain5.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.cpp
these only compile because of transitive includes
=> Add missing includes

libraries/AP_HAL_ChibiOS/Scheduler.h
Add provision to change Rcin thread priority
-needed to increase priority for some low speed cpu
=> AP_HAL_CHIBIOS: Change RCIN Prio

Tools/LogAnalyzer/DataflashLog.py, Tools/Replay/check_replay.py, Tools/ardupilotwaf/boards.py, Tools/ardupilotwaf/build_summary.py, Tools/ardupilotwaf/chibios.py, Tools/ardupilotwaf/mavgen.py, Tools/ardupilotwaf/toolchain.py, Tools/autotest/arducopter.py, Tools/autotest/arduplane.py, Tools/autotest/autotest.py, Tools/autotest/bisect-helper.py, Tools/autotest/check_autotest_speedup.py, Tools/autotest/common.py, Tools/autotest/helicopter.py, Tools/autotest/logger_metadata/parse.py, Tools/gittools/pre-commit.py, Tools/mavproxy_modules/sitl_calibration.py, Tools/scripts/CAN/fix2_gap.py, Tools/scripts/apj_tool.py, Tools/scripts/configure_all.py, Tools/scripts/param_unpack.py, Tools/scripts/tempcal_IMU.py
extracted from https://github.com/ArduPilot/ardupilot/pull/24715 
fix flake8 test for 22.04 release.
fix a bit more of strong issue spotted.
=> Feature/flake8 fix for 22.04

libraries/AP_DroneCAN/AP_DroneCAN.cpp, libraries/AP_GPS/AP_GPS.cpp
=> Use correct define for DroneCAN GPS drivers

libraries/AP_Logger/AP_Logger.h
Align indentation with others to clarify groups.
Align indentation to clarify separations.
=> AP_Logger: Align indentation with others

Tools/scripts/build_options.py, libraries/AP_TemperatureSensor/AP_TemperatureSensor.cpp, libraries/AP_TemperatureSensor/AP_TemperatureSensor.h, libraries/AP_TemperatureSensor/AP_TemperatureSensor_Params.cpp, libraries/AP_TemperatureSensor/AP_TemperatureSensor_Params.h, libraries/AP_TemperatureSensor/AP_TemperatureSensor_TSYS03.cpp, libraries/AP_TemperatureSensor/AP_TemperatureSensor_TSYS03.h, libraries/SITL/SIM_Temperature_TSYS03.h
Courtesy of FreeSpace.
Built on top of https://github.com/ArduPilot/ardupilot/pull/24866 which adds a simulator for this sensor.
=> Add support for TSYS03 temperature sensor

ArduPlane/mode_takeoff.cpp
Since ICE could start in the pits
=> Plane:correct TKOFF_DIST metadata

libraries/AP_HAL_ChibiOS/hwdef/airbotf4/hwdef.dat
=> hwdef: get airbotf4 building with 4.4

libraries/AP_Scripting/applets/Aerobatics/FixedWing/README.md
=> AP_Scripting: add version requirement to plane_aerobatics

libraries/AP_Mount/AP_Mount_Siyi.cpp
=> AP_Mount: In Siyi, fix zoom percentage in CAMERA_SETTINGS

libraries/AC_AttitudeControl/AC_AttitudeControl.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.h, libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.h, libraries/AC_AttitudeControl/AC_AttitudeControl_Sub.h, libraries/AC_PID/AC_PID.h
This PR addresses feedback from @luweiagi on issue https://github.com/ArduPilot/ardupilot/issues/23308 and https://github.com/ArduPilot/ardupilot/issues/23117
=> AC_AttitudeControl: Fix yaw limit calculations

libraries/AP_Notify/AP_Notify.h, libraries/AP_Notify/OreoLED_I2C.h
this was copied over into the OreoLED driver
=> AP_Notify: remove unused enumeration

ArduPlane/Plane.h, ArduPlane/commands_logic.cpp, ArduPlane/mode.h
```
Board               plane
Durandal            -32
KakuteH7-bdshot     8
MatekF405           0
Pixhawk1-1M-bdshot  -48
revo-mini           8
```
=> Plane: move nav_delay state to be private in ModeAuto

Tools/autotest/common.py, Tools/autotest/quadplane.py
.... this one seems to have been accidentally removed at some stage...
... wanders around a bit, 'though: 
Some of these post-QAUTOTUNE values look kind of extreme:
```
2023-09-12 16:49:56.222 Q_A_RAT_RLL_P 0.150000 -> 0.101651
2023-09-12 16:49:56.222 Q_A_RAT_RLL_I 0.250000 -> 0.101651
2023-09-12 16:49:56.222 Q_A_RAT_RLL_D 0.002000 -> 0.001027
2023-09-12 16:49:56.222 Q_A_ANG_RLL_P 4.500000 -> 36.000000
2023-09-12 16:49:56.222 Q_A_ACCEL_R_MAX 40000.000000 -> 149913.437500
2023-09-12 16:49:56.222 Q_A_RAT_PIT_P 0.150000 -> 0.097785
2023-09-12 16:49:56.222 Q_A_RAT_PIT_I 0.250000 -> 0.097785
2023-09-12 16:49:56.222 Q_A_RAT_PIT_D 0.002000 -> 0.001081
2023-09-12 16:49:56.222 Q_A_ANG_PIT_P 4.500000 -> 36.000000
2023-09-12 16:49:56.222 Q_A_ACCEL_P_MAX 40000.000000 -> 147519.281250
2023-09-12 …
```
=> autotest: tidy and re-enable QAUTOTUNE test

ArduPlane/GCS_Mavlink.cpp, ArduPlane/GCS_Mavlink.h, Tools/autotest/quadplane.py
=> Plane: allow DO_VTOL_TRANSITION as both LONG and INT commands

Tools/AP_Periph/Parameters.cpp
=> AP_Periph: fixed debug bitmask docs

libraries/AP_Mount/AP_Mount_Siyi.cpp
=> AP_Mount: In Siyi, fix missing braces in process_packet()

Tools/autotest/arduplane.py
=> autotest: add test for ArduPlane fly-inverted mission item

libraries/AP_HAL_ChibiOS/AnalogIn.cpp
=> AP_HAL_ChibiOS: change adc sampling rate stm32l4+

libraries/AP_HAL_ChibiOS/Storage.h
STm32l4+ has 512 flash pages in dual flash mode
=> AP_HAL_ChibiOS: Increase limit for Storage pages

Tools/autotest/arduplane.py
apparently within 5 degrees is asking too much....
=> autotest: loosen constraint on achieved angles

Tools/AP_Periph/README.md
based on some recent user inquires
=> Tools:add qualifier for ADSB type in readme

libraries/AP_HAL_ChibiOS/CANIface.h, libraries/AP_HAL_ChibiOS/CanIface.cpp
=> HAL_ChibiOS: fixed CAN statistics on F4/L4/F3/F7

ArduCopter/GCS_Mavlink.cpp, ArduCopter/GCS_Mavlink.h, Tools/autotest/arducopter.py
=> Copter: handle MISSION_START as both LONG and INT

ArduCopter/GCS_Mavlink.cpp, ArduCopter/GCS_Mavlink.h, Tools/autotest/arducopter.py
Output from new test, second peak being COMMAND_INT
=> Copter: handle DO_CHANGE_SPEED as both long and int

libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h
NFC, just a straight search/replace
``` …
```
=> AP_AHRS: rename EKFType::NONE to EKFType::DCM

ArduPlane/GCS_Mavlink.cpp, ArduPlane/GCS_Mavlink.h, Tools/autotest/arduplane.py
=> Plane: handle DO_PARACHUTE as both COMMAND_LONG and COMMAND_INT 

ArduPlane/Parameters.cpp, ArduPlane/Plane.h, ArduPlane/radio.cpp, ArduPlane/tuning.cpp, ArduPlane/tuning.h, Tools/scripts/build_options.py, Tools/scripts/extract_features.py, libraries/AP_Tuning/AP_Tuning.cpp, libraries/AP_Tuning/AP_Tuning.h, libraries/AP_Tuning/AP_Tuning_config.h
=> Add and use AP_TUNING_ENABLED

libraries/SITL/SIM_Aircraft.cpp, libraries/SITL/SIM_Aircraft.h
=> SITL: log achieved speedup rate

libraries/AP_Generator/AP_Generator_IE_650_800.cpp
This backend does have fuel remaining. Closes #24974
=> AP_Generator: IE 650/800: does have fuel remaining

ArduPlane/commands_logic.cpp, libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h, libraries/AP_AHRS/AP_AHRS_DCM.cpp, libraries/AP_AHRS/AP_AHRS_DCM.h, libraries/AP_AHRS/AP_AHRS_config.h, libraries/AP_Compass/AP_Compass_config.h, libraries/AP_VisualOdom/AP_VisualOdom_IntelT265.cpp
```
Durandal                       32     *           24      24                32     32     24
HerePro             -1240                                                                 
KakuteH7-bdshot                24     *           24      24                24     24     24
MatekF405                      16     *           16      16                16     16     16
Pixhawk1-1M-bdshot             16                 16      16                16     16     16 …
```
=> Add and use AP_AHRS_DCM_ENABLED

libraries/AP_Scripting/examples/copter_pingpong.lua, libraries/AP_Scripting/examples/copter_pingpong.md
Introducing a new Lua script example that instructs the drone to move forward and backward over a specified distance and number of repetitions. Additionally, there's an accompanying .md file that provides an explanation of the code's functionality, along with fundamental Lua functions and libraries related to drone control. This code has been  tested in both simulation and on an actual drone.
=> New Lua script example

libraries/SITL/SIM_Aircraft.cpp
This adds a simple thermal right at home so you know exactly where it is.
=> SITL: add a thermal at home

ArduCopter/GCS_Mavlink.cpp, Tools/autotest/arducopter.py
=> ArduCopter: accept several mode-changing commands via command_int 

ArduCopter/GCS_Mavlink.cpp, Tools/autotest/arducopter.py
... and add simple autotests for the functionality.
=> Copter: acccept DO_LAND_START as both int and long

libraries/AP_Scripting/drivers/INF_Inject.lua, libraries/AP_Scripting/drivers/INF_Inject.md
https://innoflighttechnology.com/efi/
this is now tested and is working well
=> AP_Scripting: added INF_Inject EFI driver

ArduCopter/mode_systemid.cpp
The flags of the arguments are changed according to the flag judgment.
Thus, this flag can be used to make one.
=> Copter: Two processes in one

libraries/AP_Avoidance/AP_Avoidance.cpp
STM32 is fast at multiplication. I want faster.
=> AP_Avoidance: Change division to multiplication

libraries/AC_Fence/AC_Fence.cpp
Descriptions help you understand the process.
It is better to combine the description with the processing.
=> AC_Fence: Change the description to match the actual value(NFC)

ArduPlane/Log.cpp, libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h
=> Add airspeed estimate status logging

libraries/AP_DroneCAN/AP_DroneCAN.cpp
tested using:
Tools/scripts/sitl-on-hardware/sitl-on-hw.py --board Pixhawk6C --vehicle plane --simclass Plane --frame plane
=> AP_DroneCAN: fixed sim on hw build

libraries/AP_Scripting/applets/revert_param.lua
these may be changed in a tuning session
tested on a CubeOrange based vehicle in a tuning session
=> AP_Scripting: added INS filters to revert list

libraries/AP_OpenDroneID/AP_OpenDroneID.cpp, libraries/AP_OpenDroneID/AP_OpenDroneID.h
... my guess is conflict resolution caused this
=> AP_OpenDroneID: remove duplicate definition of AP_OPENDRONEID_ENABLED

.github/workflows/test_environment.yml, Tools/environment_install/install-prereqs-ubuntu.sh, Tools/vagrant/initvagrant.sh, Vagrantfile
... and add a Vagrant VM for it
@khancyr I was unable to use your "install wx from repository" patches in here as you did for lunar; just didn't seem to work as it did for Lunar.
So we're `pip3` install` ing wxpython, which takes about 30 minutes!
=> Tools: adjust install_prereqs_ubuntu.sh to handle Mantic 

ArduPlane/quadplane.cpp
=> Plane:force min transition timer to 2 sec

Tools/autotest/common.py, Tools/autotest/rover.py, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
... and add new explicit tests for same.
=> Accept MAV_CMD_GET_HOME_POSITION as both long and int

Tools/AP_Bootloader/board_types.txt
- ID reservation request for Airvolute DCS2
=> AP_Bootloader: Airvolute DCS2 ID reservation

libraries/AP_HAL_ChibiOS/RCOutput.cpp, libraries/AP_HAL_ChibiOS/RCOutput.h, libraries/AP_HAL_ChibiOS/RCOutput_bdshot.cpp, libraries/AP_HAL_ChibiOS/RCOutput_iofirmware.cpp
This is an NFC refactor of a couple of the bdshot code paths that make review of https://github.com/ArduPilot/ardupilot/pull/25197 substantially easier.
Code has been copy and pasted in it's entirety where possible
=> AP_HAL_ChibiOS: NFC refactor of dshot/bdshot in preparation for bdshot on iomcu

libraries/AP_Compass/AP_Compass.cpp
No change in behavior, adds a comment, consts some local variables and uses the `wrap_PI` helper function.
=> AP_Compass: add big comment explaining calculate_heading

Tools/autotest/common.py, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
=> GCS_MAVLink: handle control-high-latency as both long and int 

libraries/AP_HAL_ChibiOS/hwdef/F35Lightning/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/KakuteF4Mini/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/ReaperF745/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/speedybeef4/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/speedybeef4v3/hwdef.dat
F35Lightning was overflowing
redefinition on the other board
=> Fix broken builds

ArduPlane/GCS_Mavlink.cpp
QGC's interfaces want to send nan for these parameters
=> Plane: consider nan as zero in DO_REPOSITION

BUILD.md
added binding for ap_periph for building waf
=> ardupilot: Update BUILD.md

libraries/AP_ICEngine/AP_ICEngine.cpp
NFC ...reflects changes in #25138
=> AP_ICEngine:update OPTIONS metadata

libraries/AP_Scripting/examples/mission-load.lua
Updated description - Lua script with SITL
=> using the lua script with SITL

ArduPlane/Plane.h, ArduPlane/commands_logic.cpp, ArduPlane/mode.h, ArduPlane/mode_auto.cpp, ArduPlane/servos.cpp, Tools/autotest/arduplane.py, Tools/autotest/vehicle_test_suite.py
More plane tidy ups. This removes the early return in the `set_servos` function. New auto test added to look for the wiggle, it passes before and after the plane changes.
=> Plane: move servo wiggle to mode auto

ArduCopter/AP_ExternalControl_Copter.h, Rover/AP_ExternalControl_Rover.h, libraries/AP_ExternalControl/AP_ExternalControl.h
=> Add warn if unused to AP_ExternalControl base class

libraries/AP_HAL_ChibiOS/hwdef/JFB110/README.md
Corrected a type in the README.md file.
=> hwdef: corrected README.md file in JFB110

ArduSub/version.h
Planning on having a 4.5 release in sync with the other vehicles =]
=> Sub: Version to 4.5.0-dev

Tools/ros2/ardupilot_dds_tests/package.xml
=> Tools: ros2: Add missing socat dependency

libraries/AP_OSD/AP_OSD_Screen.cpp
correct to include HD displays
=> AP_OSD:correct xy limits for panels

libraries/AP_Mount/AP_Mount_Siyi.cpp, libraries/AP_Mount/AP_Mount_Siyi.h
will be used by SIYI for improved gimbal control
=> AP_Mount: added sending of attitude and velocity for SIYI

libraries/AP_HAL_ChibiOS/hwdef/ARK_CANNODE/hwdef.dat
It's an F4, no issue having this on
=> Enable serial LEDs on ARK_CANNODE

libraries/AP_MSP/AP_MSP.cpp
NFC....expand option bit descriptions,remove unused option bit name removed from code in #18396
=> AP_MSP: update option metadata for clarity

ArduCopter/Copter.h, ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduCopter/UserParameters.cpp, ArduCopter/config.h, ArduCopter/toy_mode.h
fix USER_PARAMS_ENABLED to not build UserParameters.cpp if not need.
cascade some include fixs
=> Copter: fix USER_PARAMS_ENABLED includes

libraries/AP_GPS/AP_GPS_GSOF.cpp, libraries/AP_GPS/AP_GPS_GSOF.h
Reverts https://github.com/ArduPilot/ardupilot/pull/25525 which should not have been merged
=> Revert GSOF parsing changes

Tools/ardupilotwaf/boards.py
We had two PRs cross over killing this.
=> waf: correct sitl_periph_gps build

libraries/SITL/SIM_GPS_MSP.cpp, libraries/SITL/SIM_GPS_NMEA.cpp, libraries/SITL/SIM_GPS_Trimble.cpp
=> SITL: add missing includes

ArduPlane/servos.cpp
This is another minor logical rework to the `set_servos_controlled` function.  No change in behavior.
=> Plane: set_servos_controlled rework

libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/hwdef.dat
=> AP_HAL_ChibiOS: Set RADIX2HD HAL_I2C_INTERNAL_MASK  (backport to 4.4)

libraries/AP_Follow/AP_Follow.cpp, libraries/AP_Follow/AP_Follow_config.h
=> AP_Follow: correct defaulting of AP_FOLLOW_ENABLED

libraries/AR_WPNav/AR_WPNav.cpp, libraries/AR_WPNav/AR_WPNav_OA.cpp
... need to include what you use
=> AR_WPNav: correct missing include

libraries/AP_MSP/AP_MSP_Telem_Backend.cpp, libraries/AP_MSP/AP_MSP_Telem_DJI.cpp, libraries/AP_OSD/AP_OSD.cpp, libraries/AP_OSD/AP_OSD_Screen.cpp, libraries/AP_RSSI/AP_RSSI.cpp, libraries/AP_RSSI/AP_RSSI.h, libraries/AP_RSSI/AP_RSSI_config.h, libraries/AP_Vehicle/AP_Vehicle.h
primarily to help eliminate HAL_PERIPH_HEAVY
=> Add and use AP_RSSI_ENABLED

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_OSD/AP_OSD.cpp
... primarily to easy PERIPH_HEAVY out of the code
=> Fix compilation with RC_Channels not available

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_DAL/AP_DAL.cpp, libraries/AP_Scheduler/AP_Scheduler.cpp, libraries/AP_Vehicle/AP_Vehicle.cpp, libraries/AP_Vehicle/AP_Vehicle.h, libraries/AP_Vehicle/AP_Vehicle_config.h, libraries/GCS_MAVLink/GCS_Common.cpp
These are kind of layering violations... so at least now they're well-marked?!
Several of these could be fixed relatively easily if we were keen.
=> Correct compilation when AP_VEHICLE_ENABLED is false

libraries/AP_Scripting/drivers/EFI_SkyPower.lua
support SP-275 dual-cylinder ECU
tested and working on partners system
=> AP_Scripting: update SkyPower driver to support new model

libraries/AP_HAL_ChibiOS/hwdef/common/hrt.c, libraries/AP_HAL_ChibiOS/hwdef/common/hrt.h
this caused the reboot on IOMCU for fw update to fail
=> HAL_ChibiOS: fixed micros and millis on boards without 1MHz clock

libraries/AP_ExternalAHRS/AP_ExternalAHRS_InertialLabs.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.cpp, libraries/AP_HAL_SITL/UARTDriver.cpp
This should help with some of the CI failures
=> AP_ExternalAHRS: fixed issues with uart ownership

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
new devs will not understand the exception
=> hwdef: give a more useful error message on no bootloader

libraries/AP_ExternalAHRS/AP_ExternalAHRS_InertialLabs.cpp
=> AP_ExternalAHRS: fixed InertialLabs gyro/accel data

libraries/AP_Scripting/lua_scripts.cpp
=> AP_Scripting: fixed use after free bug

libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp
=> AP_ExternalAHRS: add InertialLabs to type parameter

Tools/autotest/pysim/util.py, Tools/completion/zsh/_ap_bin, libraries/AP_ADSB/AP_ADSB.cpp, libraries/AP_ESC_Telem/AP_ESC_Telem_Backend.cpp, libraries/AP_HAL/utility/Socket.cpp, libraries/AP_HAL_ChibiOS/UARTDriver.cpp, libraries/AP_HAL_SITL/SITL_State.cpp, libraries/AP_HAL_SITL/SITL_cmdline.cpp, libraries/AP_HAL_SITL/UARTDriver.cpp, libraries/AP_HAL_SITL/UARTDriver.h, libraries/SITL/SIM_Aircraft.cpp
This is a small set of changes pulled out of the networking PR:
https://github.com/ArduPilot/ardupilot/pull/25741
that PR is waiting on review of the BinarySemaphore changes by @bugobliterator  but I'd like to get these fixes in now to use them in other PRs
@magicrub has already approved all of these as part of #25741
=> misc fixes from networking PRs

libraries/AC_Fence/AC_Fence.cpp
=> AC_Fence:expand FENCE_AUTOENABLE description

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
I've run this through configure-all and compared vs master - no changes
=> hwdef: tidy checking of is-bootloader-build

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py, libraries/AP_HAL_ChibiOS/hwdef/scripts/dma_resolver.py
useful if you want to use the parsing elsewhere.
=> chibios_hwdef.py: add quiet option to remove parsing debug output

libraries/AP_Camera/AP_Camera_Backend.h, libraries/AP_Camera/AP_Camera_Params.cpp
Noticed this while working on its wiki
=> AP_Camera:fix OPTIONS bitmask

Tools/scripts/CAN/CAN_playback.py, libraries/AP_Scripting/examples/CAN_logger.lua
Script for logging raw CAN frames. 
Thank you @tridge for your help.
=> AP_Scripting: Add CAN_Logger example script

libraries/AP_HAL_ESP32/targets/esp32s3/partitions.csv
just completing this PR for the S3..
https://github.com/ArduPilot/ardupilot/commit/fa70a56a65533caa6c509eaf9ebfdd521568c3c3
=> AP_HAL_ESP32: S3 also needs change to storage sector size to 128K

libraries/AP_Networking/AP_Networking_port.cpp
plus some minor tweaks....NFC...checked param_parse.py
=> AP_Network:add reboot req'd metadata to params missing it

libraries/AP_HAL_ESP32/Scheduler.cpp, libraries/AP_HAL_ESP32/SdCard.cpp, libraries/AP_HAL_ESP32/WiFiUdpDriver.cpp
all these rtc_wdt_feed calls are no longer wanted because of... 
https://github.com/ArduPilot/ardupilot/commit/b9ac504d0daa4e370e5b8660b618005b31a16796
=> AP_HAL_ESP32 : this was an attempt at resolving watchdog issues , now just needs to go

libraries/AP_Networking/AP_Networking_PPP.cpp, libraries/AP_Networking/AP_Networking_PPP.h
this makes it easier to handle startup timing with PPP
=> AP_Networking: auto-restart PPP on error

Tools/scripts/sitl-on-hardware/README.md
The sitl-on-hardware paths have changed.  This updates the readme file to reflect the new file locations.
=> Update sitl-on-hardware README.md to match new file paths.

.github/problem-matchers/autotestfail.json, .github/problem-matchers/autotestwarn.json, .github/problem-matchers/gcc.json, .github/problem-matchers/python.json, .github/workflows/esp32_build.yml
This is demoing the use of these built-in features of 'actions' with the esp32 target.
=> github actions problem solvers , annotations and summary

libraries/RC_Channel/RC_Channel.cpp
=> RC_Channel:update aux switch name to RELAY1

Tools/scripts/build_sizes/build_sizes.py
to allow us to see if linux builds are failing
=> Tools: added linux boards to build sizes web page

Tools/AP_Bootloader/board_types.txt
https://github.com/ArduPilot/ardupilot/pull/26021#issuecomment-1897759625
=> Added board id for Anyleaf H7

libraries/AP_Logger/LogStructure.h, libraries/AP_OpticalFlow/AP_OpticalFlow.h
... including log message documentation
=> Correct OF comments

libraries/AR_Motors/AP_MotorsUGV.cpp
Fix https://github.com/ArduPilot/ardupilot/issues/25974
=> Fix Riscv64 compiler error issue #25974

libraries/AP_HAL_ChibiOS/Util.cpp
Fixes https://github.com/ArduPilot/ardupilot/issues/26051
=> AP_HAL_ChibiOS: allow dshot beeps to play on all dshot ESC types

ArduCopter/GCS_Mavlink.cpp, ArduCopter/GCS_Mavlink.h, ArduPlane/GCS_Mavlink.cpp, ArduPlane/GCS_Mavlink.h, Blimp/GCS_Mavlink.cpp, Blimp/GCS_Mavlink.h, Rover/GCS_Mavlink.cpp, Rover/GCS_Mavlink.h, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
```
Durandal                       8      *           0       0                 0      -40    352
HerePro             360                                                                   
KakuteH7-bdshot                16     *           8       8                 32     8      336
MatekF405                      16     *           0       8                 24     8      328
Pixhawk1-1M-bdshot             8                  0       0                 24     0      328 …
```
=> Move handling of RADIO_STATUS up to GCS_Common

ArduPlane/GCS_Mavlink.cpp, ArduPlane/GCS_Mavlink.h
In preparation for fixing or at least addressing bug in set-position-target-local-ned
=> Plane: factor handle_message

libraries/AP_Param/AP_Param.cpp
this fixes an issue with resetting of parameters when going between 4.4.x and 4.5.x on MatekH743, and on any other board using flash storage where the storage size has increased from 16k to 32k between 4.4.x and 4.5.x
The problem is that when you update to 4.5.x the parameter code stored a backup of parameters in the StorageParamBak storage region which is in the last section of storage. When you downgrade to 4.4.x the AP_FlashStorage::load_sector() code tries to load this data and gets an error as it is beyond the end of the available 16k storage. This triggers an erase_all() and loss of parameters
Note that we could instead lower the storage of MatekH743 back to 16k, but that would cause an erase for those already on 4.5.x, plus would lose the ability to store larger missions and sets …
=> AP_Param: don't enable param backup on all boards

ArduPlane/Plane.h, ArduPlane/commands_logic.cpp, ArduPlane/mode.h, ArduPlane/mode_takeoff.cpp, ArduPlane/takeoff.cpp
obviously missing from MODE TAKEOFF
=> add TKOFF_TIMEOUT to MODE TAKEOFF

libraries/AP_HAL_ChibiOS/hwdef/HEEWING-F405/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/SpeedyBeeF405WING/hwdef.dat
=> hwdef: remove bad hwdef lines

Tools/AP_Bootloader/board_types.txt
See https://github.com/ArduPilot/ardupilot/pull/26139
=> board_types.txt: reserve 1410 for RadiolinkPIX6

libraries/AP_HAL_ChibiOS/hwdef/CubePilot-CANMod/hwdef.dat
* Enables and fixes build for CubePilot CANMod with scripting support
=> Add scripting to CubePilot CANMod

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
Added the ability to format the SD card from LUA which we use to prepare the SD card
Tested with Cube Orange Plus
=> AP_Scripting: Add filesystem format

libraries/AP_Vehicle/AP_Vehicle.cpp
CubeOrange-periph-heavy was broken
=> AP_Vehicle: correct compilation when AHRS not available

libraries/AP_Mount/AP_Mount_Backend.cpp
=> AP_Mount: correct compilation with GCS disabled

libraries/AP_Vehicle/AP_Vehicle_config.h, libraries/AP_Vehicle/Parameters.cpp
... and the missing include for AP_BoardConfig.h
=> Add compilation guards around AP_Vehicle/Parameters.cpp

ArduPlane/servos.cpp
The `is_armed_and_safety_off` and `suppress_throttle` functions both override the scaled throttle in all cases so we can move the `use_battery_compensation` and `use_throttle_limits` above and remove the early returns.
This paves the way for moving all this functionality out of the `set_throttle` function.
=> Plane: reorder set_throttle function

libraries/AP_BattMonitor/AP_BattMonitor_Scripting.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Scripting.h
... including config is our pattern in all of the other backends
=> AP_BattMonitor: tidy defines in scripting backend

ArduCopter/AP_Arming.cpp, ArduCopter/RC_Channel.cpp, ArduCopter/RC_Channel.h, ArduCopter/tuning.cpp, ArduPlane/RC_Channel.cpp, ArduPlane/RC_Channel.h, Blimp/RC_Channel.cpp, Blimp/RC_Channel.h, Rover/RC_Channel.cpp, Rover/RC_Channel.h, libraries/RC_Channel/RC_Channel.cpp, libraries/RC_Channel/RC_Channel.h, libraries/RC_Channel/RC_Channels.cpp
this really doesn't add anything over just using the enumeration directly
=> Eliminate aux_func_t typedef

Rover/mode.cpp, Rover/mode.h
Add const attribute to Some member functions in Rover Mode class that don't change any state in the class.
=> Rover : class Mode : Add const attribute to some 'getter' member function signatures

AntennaTracker/version.h, ArduCopter/version.h, ArduPlane/version.h, ArduSub/version.h, Blimp/version.h, Rover/version.h, Tools/AP_Bootloader/AP_Bootloader.cpp, Tools/AP_Bootloader/network.h, Tools/AP_Periph/version.cpp, Tools/AP_Periph/version.h, libraries/AP_CheckFirmware/AP_CheckFirmware.cpp, libraries/AP_CheckFirmware/AP_CheckFirmware.h, libraries/AP_CheckFirmware/AP_CheckFirmwareDefine.h, libraries/GCS_MAVLink/GCS_Dummy.cpp
=> Add support for showing App version and boot status on Network Bootloader

ArduCopter/Copter.cpp, ArduCopter/Copter.h, ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduCopter/crash_check.cpp, ArduCopter/events.cpp, ArduCopter/mode_auto.cpp, ArduCopter/system.cpp, ArduPlane/ArduPlane.cpp, ArduPlane/Parameters.cpp, ArduPlane/Parameters.h, ArduPlane/system.cpp, ArduSub/ArduSub.cpp, ArduSub/Parameters.cpp, ArduSub/Parameters.h, ArduSub/Sub.h, ArduSub/system.cpp, Rover/Parameters.cpp, Rover/Parameters.h, Rover/Rover.cpp, Rover/system.cpp, libraries/AP_Gripper/AP_Gripper.cpp, libraries/AP_Gripper/AP_Gripper.h, libraries/AP_Mission/AP_Mission_Commands.cpp, libraries/AP_Param/AP_Param.h, libraries/AP_Vehicle/AP_Vehicle.cpp, libraries/AP_Vehicle/AP_Vehicle.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/RC_Channel/RC_Channel.cpp
All parameter conversions have been tested.
We autotest a lot of gripper stuff and I've mucked around with stuff randomly in SITL.
=> Move AP_Gripper object up to AP_Vehicle

.github/workflows/esp32_build.yml
ensure apt db is up to date before first install
=> CI: fix ESP32 CI issue

libraries/AP_Scripting/applets/Aerobatics/FixedWing/dual_log.py, libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
allow sync of PTHT messages between vehicle logs
=> AP_Scripting: improved dual log handling

Tools/environment_install/install-prereqs-mac.sh
Fixes the mac install as the xcode install text has changed
=> environment_install: fixup mac xcode install text

libraries/AP_GPS/AP_GPS.cpp, libraries/AP_GPS/AP_GPS.h, libraries/AP_GPS/GPS_Backend.cpp, libraries/AP_HAL_ESP32/UARTDriver.h, libraries/AP_HAL_Linux/UARTDriver.h, libraries/AP_HAL_SITL/UARTDriver.h, libraries/AP_SerialManager/AP_SerialManager_config.h
This makes for much faster startup for most users
=> GPS: do initial probe at SERIALn_BAUD 

Tools/CPUInfo/CPUInfo.cpp, libraries/AP_HAL/SIMState.cpp
allow examples/tools to build with esp32s3empty
=> ESP32: improved build of example firmwares

libraries/RC_Channel/RC_Channel.cpp
this means that we get "EKFPosSource 1" rather than "EKFPosSource LOW"
=> RC_Channel: allow customisation of position text in aux switch announcement

ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduCopter/mode_auto.cpp
I noticed that I messed up the name of PLDP_RNG_MIN. This PR fixes this problem by changing PLDP_RNG_MIN to PLDP_RNG_MAX
=> Copter: Payload Place: Change PLDP_RNG_MIN to PLDP_RNG_MAX

ArduSub/ArduSub.cpp
this is required for #26415 to work properly
=> Sub: add missing call to calc_pwm()

ArduSub/ReleaseNotes.txt
These were way out of sync with Sub-4.1 branch
=> Sub: update release notes

libraries/SITL/SIM_Ship.cpp
```
2024-03-07 14:12:52.20: GLOBAL_POSITION_INT {time_boot_ms : 82099, lat : -353589024, lon : 1491694117, alt : 573750, relative_alt : -9981, vx : 239, vy : 971, vz : -28, hdg : 6928} srcSystem=1 srcComponent=1
2024-03-07 14:12:52.28: GLOBAL_POSITION_INT {time_boot_ms : 82182, lat : -353588993, lon : 1491694255, alt : 574002, relative_alt : 0, vx : 240, vy : 970, vz : 0, hdg : 7609} srcSystem=17 srcComponent=34
2024-03-07 14:12:52.28: ATTITUDE {time_boot_ms : 82182, roll : 0.0, pitch : 0.0, yaw : 1.328181505203247, rollspeed : 0.0, pitchspeed : 0.0, yawspeed : 0.019999997690320015} srcSystem=17 srcComponent=34
2024-03-07 14:12:52.45: ATTITUDE {time_boot_ms : 82349, roll : 0.0022011874243617058, pitch : 7.261766768351663e-06, yaw : 1.2141329050064087, rollspeed : 0.0004429089603945613, …
```
=> SITL: Sim_Ship: label global_position_int and attitude packet fields

Tools/Replay/Replay.h, libraries/AP_Vehicle/AP_Vehicle.cpp, libraries/SRV_Channel/SRV_Channel_config.h
... also in order to make this easier for GenericVehicle.
=> Avoid using BUILD_TYPE_Replay in AP_Vehicle

libraries/AP_Scripting/applets/VTOL-quicktune.lua
=> AP_Scripting: prevent "Starting XXX tune" happening multiple times

libraries/AP_HAL_ESP32/README.s3.debug.howto.md
tridge asked for more info on debugging the s3 variant, so i brain-dumped a .txt file, and got chatgpt to turn it into a .md file for me.
=> AP_HAL_ESP32: esp32s3 debugger readme in .md format

Tools/autotest/test_param_upgrade.py
Splitting this out of PR which adds GPS per-instance parameters
=> autotest: add script for testing parmameter upgrades

libraries/AP_VideoTX/AP_VideoTX.cpp, libraries/AP_VideoTX/AP_VideoTX.h
=> AP_VideoTX:add additional freq bands(Band X)

libraries/AP_Motors/AP_MotorsMulticopter.cpp, libraries/AP_Motors/AP_Motors_Class.cpp, libraries/AP_Motors/AP_Motors_Class.h
This adds a new PWM type for angle output, this means motors respect MIN/MAX/TRIM and reversals. https://github.com/ArduPilot/ardupilot/pull/26300
=> AP_Motors: add new PWM_TYPE_ANGLE

Tools/scripts/build_options.py
long names here push out the display on a generated Wiki page.
=> Tools: shorten labels in build options

Tools/scripts/build_autotest.sh
needed for new git version after server upgrade
=> CI: added --force to git tags --fetch

Tools/AP_Periph/AP_Periph.cpp
Replaces https://github.com/ArduPilot/ardupilot/pull/26543
=> AP_Periph: add assert that AP_CHECK_FIRMWARE_ENABLED is set

Tools/GIT_Test/GIT_Success.txt
Added my name to the GIT_Success file. Reason for this was because I was following an example doc on the ardupilot dev docs.
=> Tools: First commit test: added name to GIT_Success.txt file

AntennaTracker/ReleaseNotes.txt, AntennaTracker/version.h, ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, ArduPlane/ReleaseNotes.txt, ArduPlane/version.h, Rover/release-notes.txt, Rover/version.h
This is the Copter, Rover and Tracker 4.5.0 release
I'll merge and update tags in an hour or so.  We don't really need to wait for CI to pass.
=> Copter/Rover/Tracker: 4.5.0 release

libraries/AP_Scripting/examples/servo_scan.lua
The "period" here is really frequency, bigger numbers make it go faster not slower. Lua knows PI we can get it from the math lib.
=> AP_Scripting: examples: update servo scan

Tools/autotest/vehicle_test_suite.py
This currently returns 128, rather than True/False.
Also augments the WaitAndMaintain class and adds WaitAndMaintainArmed
=> autotest: Fix return value of `def armed()`

AntennaTracker/ReleaseNotes.txt, AntennaTracker/version.h, ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, ArduPlane/ReleaseNotes.txt, ArduPlane/version.h, Rover/release-notes.txt, Rover/version.h, libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp, libraries/AP_RCProtocol/AP_RCProtocol_CRSF.h, libraries/AP_RCProtocol/AP_RCProtocol_GHST.cpp, libraries/AP_RCProtocol/examples/RCProtocolTest/RCProtocolTest.cpp
this only includes the CRSF bug fix
https://github.com/ArduPilot/ardupilot/pull/26702
=> Plane: prepare for 4.5.1 release

Tools/autotest/ArduSub_Tests/SimTerrainMission/terrain_mission.txt, Tools/autotest/ardusub.py, libraries/AP_Scripting/examples/sub_test_synthetic_seafloor.lua
This PR adds robust tests of the surface tracking modes that already exist in ArduSub.
=> Test ArduSub surface tracking modes with a Lua range finder driver returning distances to a simulated sea floor.

libraries/Filter/HarmonicNotchFilter.cpp
NFC...current wording inaccurate
=> Filter:correct which vehicles can use of throttle based notches

ArduPlane/Parameters.cpp
units changed from centidegrees to degrees
=> Plane: fix units metadata for PTCH_LIM_MIN_DEG

libraries/AP_HAL_ChibiOS/Scheduler.cpp
=> AP_HAL_ChibiOS: add missing Math.h include

Tools/ardupilotwaf/boards.py, libraries/AP_Airspeed/AP_Airspeed.cpp, libraries/SITL/tools/Sailboat_VPP.m
I think the word is wrong.
I have changed it.
=> global:  Change a word(NFC)

Tools/AP_Bootloader/board_types.txt
=> Tools: reserve ID for PixPilot-V6PRO

Tools/AP_Bootloader/board_types.txt
Reserve an ID for NxtPX4v2 in PR: [#26639](https://github.com/ArduPilot/ardupilot/pull/26639)
=> Reserve an ID for NxtPX4v2

Tools/AP_Bootloader/board_types.txt
Reserve ID for MicoAir405Mini in PR [#26637](https://github.com/ArduPilot/ardupilot/pull/26637)
=> Reserve ID for MicoAir405Mini

libraries/AP_Scripting/drivers/INF_Inject.lua
make it more robust to serial errors, and support correct checksum
tested on INF inject system
=> AP_Scripting: improve INF inject driver

ArduCopter/compassmot.cpp, Tools/autotest/arducopter.py
~Currently provokes Arithmetic Exception errors, so can't be merged.~
Disabled the test, so can now be merged
=> Add test for copter CompassMot

wscript
most elements duplicated for sitl, linux and ChibiOS
Note that blimp was missing....
FreeSpace Operations is sponsoring this work.
=> waf: factor out a vehicles array

libraries/AP_RCMapper/AP_RCMapper.cpp, libraries/AP_RCMapper/AP_RCMapper_config.h
... and add the missing include
=> AP_RCMapper: exclude body of AP_RCMapper based on AP_RCMAPPER_ENABLED

Tools/autotest/helicopter.py
Adds an autotest for the Heli Autotune feature
Performs tuning flights as directed in wiki on the sitl heli model
=> Add Heli Autotune Autotest

Tools/autotest/test_param_upgrade.py
Allows testing against things which are not the master branch
This requires getting nasty in terms of removing the build directory because of our missing-dependecy-file waf issues.
Also requires handling branches that don't have the "novehicle" model.
I've used this modification to test moving parameters from Copter-4.5 into master with a relatively complicated upgrade.
We'll need this when moving GPS up into AP_Vehicle as sub-objects need to be converted when base objects are moved and we've already had some conversions in there.
=> Tools: test_param_upgrade.py: take a --master-branch parameter

Tools/scripts/decode_devid.py
SCHA63T was added in #23652, but it was not in the devid tools.
=> Tools: Scripts: Decode devid: add SCHA63T

libraries/AP_Baro/AP_Baro.cpp
wind compensation and field elevation should be unrelated
=> AP_Baro: correct placement of field elevation #endif

Tools/autotest/arducopter.py, libraries/SITL/SIM_GPS_UBLOX.cpp
Extracted from blended backend creation PR.
One just tests basic functionality, the other tests that the weighting works
=> Add two new tests for AP_GPS_Blending

ArduPlane/Plane.h, ArduPlane/commands_logic.cpp, ArduPlane/mode.h, ArduPlane/mode_auto.cpp, ArduPlane/servos.cpp
this PR is just the refactor commit from PR https://github.com/ArduPilot/ardupilot/pull/26913
=> Plane: refactor NAV_ALTITUDE_WAIT match NAV_DELAY

Tools/scripts/build_options.py, Tools/scripts/extract_features.py
to allow this to be re-added to boards where it was removed by #26576
and a small driveby for readability
=> Tools: add blended GPS build option

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/generator/src/main.c, libraries/AP_Scripting/tests/docs_check.py
AP_Objects can mostly be nil. This updates to output that in the generated docs. It also fixes some of the existing docs that were missing params and return types.
Now updates all docs types to be correct and enforces that with the test.
=> AP_Scripting: docs update

libraries/AP_HAL_ChibiOS/hwdef/MicoAir405Mini/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/MicoAir405v2/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/MicoAir743/hwdef.dat
=> hwdef:preconfig MicoAir bds shipping with BF for BF migration

libraries/AP_Scripting/applets/copter_terrain_brake.lua, libraries/AP_Scripting/applets/copter_terrain_brake.md
for automatic BRAKE mode when flying in LOITER in steep terrain
=> AP_Scripting: added copter_loiter_brake script

ArduCopter/mode.cpp, ArduCopter/mode.h, ArduCopter/mode_althold.cpp, ArduCopter/mode_flowhold.cpp, ArduCopter/mode_loiter.cpp, ArduCopter/mode_poshold.cpp, ArduCopter/mode_sport.cpp, ArduCopter/mode_zigzag.cpp
ENUM name with ALTHOLD_.
I group by CLASS name.
=> Copter: Change from enum to class

.github/workflows/test_environment.yml
mantic is EOL, save some CI time
=> github: test_environment: test Ubuntu noble and not Ubuntu mantic

Rover/Steering.cpp
By initializing the variable, the decision process becomes unnecessary.
=> Rover: Initialize variables

Tools/autotest/vehicle_test_suite.py
.... by re-implementing in terms of a WaitAndMaintain class
=> autotest: add support for minimum_duration to wait_ekf_flags

Tools/autotest/rover.py
These turn out to be useful for preventing some regressions.
@andyp1per
=> autotest: add polygon pre-arm tests

libraries/AP_Scripting/docs/docs.lua
This copy's across all the documentation from the wiki to docs.lua. This is a step towards using the auto generated docs on the wiki.
=> AP_Scripting: docs: document all functions currently documented on the wiki

Tools/scripts/run_lua_language_check.py
This gives a hint about how to fix the missing import.
=> Tools: Scripts: run_lua_language_check: give hint about github-release-downloader

libraries/SITL/SIM_Aircraft.cpp
fixes a build error with current cygwin
=> SITL: update to work on newer cygwin versions

AntennaTracker/ReleaseNotes.txt, AntennaTracker/version.h, ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, ArduPlane/ReleaseNotes.txt, ArduPlane/version.h, Rover/ReleaseNotes.txt, Rover/version.h
This updates the release notes and versions for the Copter, Rover, Plane and Tracker 4.5.3 release
=> Copter, Rover, Plane, Tracker: 4.5.3 release

Tools/scripts/run_lua_language_check.py, libraries/AP_Scripting/examples/notch_switch.lua
switch between two notch setups using attenuation change
=> AP_Scripting: added notch_switch example

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
useful for seeing if switching to a GPS yaw source set in EK3 will work
=> AP_Scripting: added GPS yaw binding

libraries/AP_HAL_SITL/UARTDriver.cpp
This give 3 attempt for tcp clients to connect, with 1s wait between attempt
This make tcp client connection easier when connecting multiple sitl instances together
=> AP_HAL_SITL: Give tcp client 3 attempts to connect

ArduSub/joystick.cpp
Adds missing Servo 2 and 3 min and max toggle functions to the button-handling switch-case.
=> Add servo 2 and 3 min/max toggle function implementation

libraries/AP_DDS/AP_DDS_Client.cpp
A common initialization function. Follow up to the previous PR.
https://github.com/ArduPilot/ardupilot/pull/27140#discussion_r1614957993
=> AP_DDS: Use common quaternion initialization function

Rover/GCS_Mavlink.h, Tools/autotest/rover.py
=> Rover: disable AP_MAVLINK_MAV_CMD_NAV_SET_YAW_SPEED_ENABLED

libraries/AP_BLHeli/AP_BLHeli.cpp
User got confused on param reversing unidirectional motor control direction and reversing operation masks...NFC
=> AP_BLHeli:expand metadata of 3d and Reverse masks

libraries/AP_Camera/AP_Camera.cpp, libraries/AP_Camera/AP_Camera.h, libraries/GCS_MAVLink/GCS_Common.cpp
neatens GCS_Common a bit, reduces repetitive code
=> move switch for sending camera messages into AP_Camera 

libraries/AP_Notify/RGBLed.cpp, libraries/AP_Notify/RGBLed.h
I think converting the ENUM definition to a class will make it clearer.
=> AP_Notify: Convert the ENUM definition to a class

Tools/autotest/arducopter.py
take advantage of new infrastructure
=> autotest: simplify  AC_Avoidance_Proximity test

ArduCopter/mode_guided.cpp
Velocity is the explanation for Accel, VelAccel, and PosVelAccel in sub-mode.
I think not.
=> Copter: Change the sub-mode description(NFC)

Tools/AP_Bootloader/board_types.txt
- either missing or too complicated to be a good text-tag for a board
-
=> Correct board reservations

Tools/environment_install/install-prereqs-arch.sh
=> Tools: fix archlinux install script

libraries/AP_HAL_Linux/Storage.cpp, libraries/AP_HAL_Linux/UARTDriver.cpp, libraries/AP_HAL_Linux/Util.cpp
clean some unused header files.
=> AP_HAL_Linux: delete unused header files

ArduCopter/motors.cpp
Initialize the counter if it is changed during operation.
=> Copter: Clear the counter when rudder arm operation is disabled

ArduCopter/events.cpp
Mode changes will not work when mode not compiled in
=> Copter: tidy failsafe action handling

Tools/ardupilotwaf/ap_library.py, wscript
* Adds improvement over the older process, the compile_commands.json are generated before compilation rather than after.
=> Add back the support for generating compile commands

Tools/AP_Periph/buzzer.cpp, libraries/AP_HAL_ChibiOS/Util.cpp, libraries/AP_Notify/AP_Notify.cpp, libraries/AP_Notify/AP_Notify.h, libraries/AP_Notify/MMLPlayer.cpp
```
f303-Universal      *                                                                     
iomcu …
```
=> Use enum-class for BuzzerType enumeration

libraries/AP_Scripting/drivers/INF_Inject.lua
allows full control over serial
tested by partner
=> AP_Scripting: added throttle and ignition control for INF_INject

Tools/scripts/create_OEM_board.py
=> Include, don't copy defaults.parm in create_OEM_setup.py

libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS_Backend.h, libraries/AP_DAL/AP_DAL_InertialSensor.cpp, libraries/AP_DAL/AP_DAL_InertialSensor.h, libraries/AP_DAL/LogStructure.h, libraries/AP_InertialSensor/AP_InertialSensor.cpp, libraries/AP_InertialSensor/AP_InertialSensor.h, libraries/AP_Mount/SoloGimbal.cpp, libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp, libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp, libraries/GCS_MAVLink/GCS_Common.cpp
Alternative to renaming to get_default_accel
=> rename get_primary_accel to get_first_usable_accel

libraries/AP_InertialSensor/AP_InertialSensor_ADIS1647x.h, libraries/AP_InertialSensor/AP_InertialSensor_BMI055.h, libraries/AP_InertialSensor/AP_InertialSensor_BMI088.h, libraries/AP_InertialSensor/AP_InertialSensor_BMI160.cpp, libraries/AP_InertialSensor/AP_InertialSensor_BMI160.h, libraries/AP_InertialSensor/AP_InertialSensor_BMI270.cpp, libraries/AP_InertialSensor/AP_InertialSensor_BMI270.h, libraries/AP_InertialSensor/AP_InertialSensor_Backend.h, libraries/AP_InertialSensor/AP_InertialSensor_ExternalAHRS.h, libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp, libraries/AP_InertialSensor/AP_InertialSensor_Invensense.h, libraries/AP_InertialSensor/AP_InertialSensor_Invensensev2.cpp, libraries/AP_InertialSensor/AP_InertialSensor_Invensensev2.h, libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.h, libraries/AP_InertialSensor/AP_InertialSensor_L3G4200D.cpp, libraries/AP_InertialSensor/AP_InertialSensor_L3G4200D.h, libraries/AP_InertialSensor/AP_InertialSensor_LSM9DS0.cpp, libraries/AP_InertialSensor/AP_InertialSensor_LSM9DS0.h, libraries/AP_InertialSensor/AP_InertialSensor_LSM9DS1.cpp, libraries/AP_InertialSensor/AP_InertialSensor_LSM9DS1.h, libraries/AP_InertialSensor/AP_InertialSensor_RST.cpp, libraries/AP_InertialSensor/AP_InertialSensor_RST.h, libraries/AP_InertialSensor/AP_InertialSensor_SCHA63T.h, libraries/AP_InertialSensor/AP_InertialSensor_SITL.h
=> AP_InertialSensor: move gyro and accel instance ids into AP_InertialSensor_Backend

ArduSub/ArduSub.cpp
=> Sub: sync MAVLink system id in 1hz loop

libraries/AP_Scripting/applets/VTOL-quicktune.lua, libraries/AP_Scripting/applets/forward_flight_motor_shutdown.lua
Typo fix
Removed unused variable
=> AP_Scripting: Misc. small improvements.

libraries/AP_Logger/LogStructure.h, libraries/AP_SmartRTL/AP_SmartRTL.cpp, libraries/AP_SmartRTL/AP_SmartRTL.h
we log these values, so number them explicitly
```
Board,copter
CubeOrange,*
```
=> AP_SmartRTL: use enum class for Action, number entries

libraries/AP_Frsky_Telem/AP_Frsky_SPort.cpp
=> AP_Frsky_Telem: avoid use if int16-t read call

ArduPlane/quadplane.cpp
This updates the description to match what the option actually does.
=> Plane: Quadplane: update Q_OPTION bit 22 description

libraries/AP_Logger/AP_Logger_Backend.cpp, libraries/AP_Logger/AP_Logger_Backend.h, libraries/AP_Logger/AP_Logger_Block.cpp
=> AP_Logger: remove unused _log_file_size_bytes variable

Tools/GIT_Test/GIT_Success.txt
Tools: add name to GIT_Success.txt
=> Tools: add name toGIT_Success.txt

libraries/AP_Common/Bitmask.h, libraries/AP_Common/tests/test_bitmask.cpp
Please see commits for details.
Tested full test suite and that a vehicle seems to work okay. Saves 1.3K flash on Cube Orange.
=> AP_Common: fix and clean up Bitmask class

libraries/AP_Mount/AP_Mount.cpp
The serial instance value does not match the next serial instance. I will adjust it to match the others.
=> AP_Mount: Increment the serial instance

libraries/AP_DDS/AP_DDS_Client.cpp
the std:copy was copying from uint16_t to float
=> AP_DDS: fixed cell voltages

libraries/AP_Scripting/lua_bindings.cpp
=> AP_Scripting: fixed remove call

libraries/AP_Compass/AP_Compass_IST8308.cpp, libraries/AP_Compass/AP_Compass_IST8310.cpp, libraries/AP_Compass/AP_Compass_LIS3MDL.cpp, libraries/AP_Compass/AP_Compass_MMC3416.cpp, libraries/AP_Compass/AP_Compass_MMC5xx3.cpp, libraries/AP_Compass/AP_Compass_QMC5883L.cpp, libraries/AP_Compass/AP_Compass_QMC5883P.cpp, libraries/AP_OpticalFlow/AP_OpticalFlow_PX4Flow.cpp, libraries/AP_RangeFinder/AP_RangeFinder_PulsedLightLRF.cpp, libraries/AP_RangeFinder/AP_RangeFinder_VL53L0X.cpp, libraries/AP_RangeFinder/AP_RangeFinder_VL53L1X.cpp
Extracted from https://github.com/ArduPilot/ardupilot/pull/27504
=> Printf warning fixes

libraries/AP_HAL/Device.h, libraries/AP_HAL/I2CDevice.h, libraries/AP_HAL/WSPIDevice.h, libraries/AP_HAL_Linux/I2CDevice.cpp, libraries/AP_HAL_Linux/I2CDevice.h
=> Remove use of <vector> in HAL

libraries/AP_NavEKF3/AP_NavEKF3_Logging.cpp, libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.h, libraries/AP_NavEKF3/LogStructure.h
This helps us better understand what kind of yaw fusion the ekf is doing.
It was very useful while debugging  #18229
=> AP_NavEKF3: log mag fusion selection to XKFS

.github/workflows/qurt_build.yml, Tools/Frame_params/ModalAI/AutonomyDevKit.parm, Tools/ardupilotwaf/qurt.py, libraries/AP_HAL/board/qurt.h, libraries/AP_HAL_QURT/I2CDevice.cpp, libraries/AP_HAL_QURT/RCOutput.cpp, libraries/AP_HAL_QURT/Scheduler.cpp, libraries/AP_HAL_QURT/UARTDriver.cpp, libraries/AP_HAL_QURT/UARTDriver.h, libraries/AP_HAL_QURT/ap_host/service/README.md, libraries/AP_HAL_QURT/ap_host/service/voxl-ardupilot, libraries/AP_HAL_QURT/ap_host/service/voxl-ardupilot.service, libraries/AP_HAL_QURT/ap_host/src/main.cpp, libraries/AP_HAL_QURT/ap_host/src/protocol.h, libraries/AP_HAL_QURT/replace.cpp, libraries/AP_HAL_QURT/replace.h
and build copter, plane and rover
=> QURT: adjustments to support different frames

Tools/autotest/arducopter.py, Tools/autotest/arduplane.py, Tools/autotest/quadplane.py, Tools/autotest/rover.py, Tools/autotest/vehicle_test_suite.py
... also rename do_reposition to send_do_reposition
=> Fix circular exclusion fence upload

Tools/scripts/build_options.py, Tools/scripts/extract_features.py
=> Tools: fixed typo in HAGL feature

libraries/AP_Notify/AP_Notify.h
=> AP_Notify: remove unused BUZZER_ON/OFF defines

ArduCopter/mode.h, ArduCopter/mode_auto.cpp
Tested a couple of these in SITL.
=> Copter: add and use private ModeAuto::option_is_enabled method

libraries/SITL/SIM_VectorNav.cpp
can't use nmea_printf here as the buffer data won't be null-terminated
=> SIM_VectorNav: stop using nmea_printf on buffer data

ArduCopter/Copter.cpp, ArduCopter/Parameters.cpp, ArduCopter/system.cpp, ArduPlane/Log.cpp, ArduPlane/Parameters.cpp, ArduPlane/system.cpp, Blimp/Blimp.cpp, Blimp/Parameters.cpp, Blimp/system.cpp, Rover/GCS_Mavlink.cpp, Rover/Log.cpp, Rover/Parameters.cpp, Rover/system.cpp, Tools/scripts/build_options.py, Tools/scripts/extract_features.py, libraries/AP_LTM_Telem/AP_LTM_Telem.cpp, libraries/AP_OSD/AP_OSD_Screen.cpp
Replaces https://github.com/ArduPilot/ardupilot/pull/25925/files
=> Correct compilation when RSSI compiled out

libraries/Filter/HarmonicNotchFilter.cpp
should have been done in #25442 as requested and agreed....NFC
=> Filter: add "source" to option 5

ArduCopter/Copter.cpp
Include the methods for LUA scripts within the range of the preprocessor.
=> Copter: Change the description(NFC)

Tools/autotest/ardusub.py
Test several EK3_MAG_CAL values for sub
=> autotest: test mag fusion

Rover/GCS_Mavlink.cpp
C++ has a SWITCH statement.
Other methods use the SWITCH statement.
I don't think it is necessary to use IF statement for this process.
I think the SWITCH statement is better.
=> Rover: Change the IF statement to a SWITCH statement

Tools/scripts/build_options.py, Tools/scripts/extract_features.py
AP_WINCH build options have been added to custom-build server
Please review the addition of feature in list.
=> Added AP_WINCH options to Custom-Build server

Tools/autotest/arducopter.py
autotest: clean MotorVibration test for new infrastructure
autotest: clean VisionPosition test for new infrastructure
autotest: clean MotorFail test for new infrastructure
autotest: clean OpticalFlowLimits test for new infrastructure
autotest: tidy OpticalFlow test for new infrastructure
autotest: tidy SetModeViaModeSwitch test for new infrastructure
autotest: tidy SetModesViaAuxSwitch test for new infrastructure
autotest: tidy SplineLastWaypoint test for new infrastructure
autotest: tidy PIDNotches test for new infrastructure
autotest: tidy ThrottleGainBoost test for new infrastructure
autotest: tidy PrecisionLoiterCompanion test for new infrastructure
autotest: tidy BeaconPosition test for new infrastructure
=> autotest: tidy various tests to take advantage of new infrastructure

Tools/autotest/rover.py
autotest: tidy Sprayer test
autotest: tidy rover AC_Avoidance test
autotest: tidy rover ModeSwitch test
autotest: tidy rover AuxModeSwitch
autotest: tidy rover RCOverrides test
autotest: tidy rover MANUAL_CONTROL test
autotest: tidy rover PolyFenceObjectAvoidance test
=> autotest: tidy various Rover autotests

Tools/autotest/helicopter.py
autotest: tidy PosHoldTakeoff heli test
autotest: tidy StabilizeTakeoff heli test
autotest: tidy SplineWaypoint heli test
autotest: tidy ManAutoRotation heli test
autotest: tidy AirspeedDrivers heli test
autotest: tidy PIDNotches heli test
=> autotest: tidy Helicopter missions to use new infrastructure

libraries/AP_Math/matrix3.cpp, libraries/AP_Math/matrix3.h, libraries/AP_Math/quaternion.h, libraries/AP_Math/tests/test_rotations.cpp
our main euler functions did not have a comment on the ordering convention
=> AP_Math: added comments and a test for euler ordering

libraries/AC_AutoTune/AC_AutoTune.cpp, libraries/AC_AutoTune/AC_AutoTune.h, libraries/AC_AutoTune/AC_AutoTune_Heli.cpp, libraries/AC_AutoTune/AC_AutoTune_Heli.h, libraries/AC_AutoTune/AC_AutoTune_Multi.cpp, libraries/AC_AutoTune/AC_AutoTune_Multi.h
Replaces https://github.com/ArduPilot/ardupilot/pull/20990/files which has bitrotted
=> AC_AutoTune: make axis-type enum-class

Tools/autotest/rover.py, libraries/RC_Channel/RC_Channel.cpp
Rework of https://github.com/ArduPilot/ardupilot/pull/19230/files
=> RC_Channel: Rework duplicate-rc-options sanity check

libraries/AP_BattMonitor/AP_BattMonitor_Sum.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Sum.h
Does what is says on the tin, reports the average temperature of the selected monitors.
=> AP_BattMonitor: Sum: report average temperature

Tools/autotest/vehicle_test_suite.py
Add tests for iBus protocol.
https://github.com/ArduPilot/ardupilot/pull/27695 is resurrecting an effort to give ArduPilot iBus telemetry support.
=> autotest: add tests for iBus telemetry

Tools/autotest/arducopter.py, Tools/autotest/arduplane.py, Tools/autotest/rover.py, libraries/AC_Fence/AC_Fence.cpp
NFC....can be inside or outside a fence to be in breach
=> AC_FENCE:correct prearm message

libraries/AC_Fence/AC_Fence.cpp
Can be changed to prearm checkfailed in 4.7
=> AC_FENCE:Add AUTOENABLE deprecation warning

AntennaTracker/config.h
=> Tracker: remove ENABLED/DISABLED defines

libraries/SRV_Channel/SRV_Channels.cpp
setting 3 works well with AM32
=> SRV_Channel: added AM32 to the SERVO_DSHOT_ESC param docs

libraries/AP_Camera/AP_Camera.cpp, libraries/AP_Camera/AP_Camera_Backend.cpp
our location may not be coming from a GPS
Closes https://github.com/ArduPilot/ardupilot/issues/6378
=> AP_Camera: rely on AHRS for position, not GPS

ArduPlane/ArduPlane.cpp, ArduPlane/Log.cpp, libraries/AP_Scripting/examples/Motor_mixer_dynamic_setup.lua, libraries/AP_Scripting/examples/ahrs-source-gps-optflow.lua, libraries/AP_Scripting/examples/arming-check-wp1-takeoff.lua, libraries/AP_Scripting/examples/copter_alt_offset.lua, libraries/AP_Scripting/examples/servo_slew.lua
Small typographical fixes in various places.
=> Bit and pieces 2

libraries/AP_Camera/AP_Camera_Backend.cpp
=> CAMERA_FOV_STATUS altitude unit fix

Tools/scripts/sitl-on-hardware/README.md, Tools/scripts/sitl-on-hardware/sitl-on-hw.py
Add a bit more help on SITL on HW for copter frame selection ! 
Tested working with octa-quad
=> Tools: improve sitl-on-hw copter handling

Tools/scripts/extract_features.py
Forgot to force push changes on my previous branch. Sorry @peterbarker
=> Scripts: Fix extract features missing CustomRotations

libraries/AP_Baro/AP_Baro.cpp
This is obviously not buying us anything except non-conformity
=> AP_Baro: replace gcs().send_text with GCS_SEND_TEXT

libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp, libraries/AP_VideoTX/AP_VideoTX_config.h
=> AP_RCTelemetry: add missing gate for AP_VIDEOTX_ENABLED

libraries/AP_VideoTX/AP_VideoTX.cpp, libraries/AP_VideoTX/AP_VideoTX.h
Add additional freq bands(RushFPV 3.3GHz)
=> AP_VideoTX:add additional freq bands(RushFPV 3.3GHz)

ArduCopter/version.h
We don't really need a PR for this but just for tracking purposes I've created it
=> Copter: 4.5.6-beta1 version label fix

Tools/environment_install/install-prereqs-ubuntu.sh
=> Tools: Translate Linux Mint Wilma to Noble

libraries/AP_GPS/AP_GPS.cpp, libraries/AP_GPS/MovingBase.cpp
=> AP_GPS:add note to old param names to avoid confusion

libraries/AP_Motors/AP_MotorsHeli_Single.cpp
Replace previous PR (https://github.com/ArduPilot/ardupilot/pull/27950).
=> AP_Motors: fix DDVP tail servo initialization

libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.cpp
Style and conciseness improvements. No compiler output change.
=> AP_DroneCAN: DNA_Server: polish db methods

ArduSub/Parameters.cpp, ArduSub/Sub.h, ArduSub/commands_logic.cpp, ArduSub/config.h, ArduSub/defines.h, ArduSub/mode_auto.cpp, ArduSub/mode_poshold.cpp, ArduSub/sensors.cpp
same as Plane, Rover, Sub, Tracker
No compiler output change across any target (except the SITL ones...)
=> Sub: remove ENABLE/DISABLE defines, use 0/1 instead

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/modules/MAVLink/Readme.md
Just a couple of minor spelling fixes that I discovered as part of PR https://github.com/ArduPilot/ardupilot/pull/27783
=> AP_Scripting: minor spelling fixes

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
... problematic for re-use of this object, which we do in various places
=> Avoid using global "args" object within ChibiOSHWdef object

Tools/autotest/autotest.py, Tools/autotest/pysim/util.py, Tools/autotest/sim_vehicle.py, Tools/autotest/vehicle_test_suite.py
To output to FlightGear...
tested... in SITL....
=> Add options to sim_vehicle.py and autotest.py for --enable-fgview

libraries/AP_GPS/AP_GPS.cpp, libraries/AP_ICEngine/AP_ICEngine.cpp
not sure the Movingbaseline ones are correct
=> Legacy tags

Tools/autotest/arducopter.py, libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h, libraries/AP_AHRS/AP_AHRS_Backend.h, libraries/AP_NavEKF/AP_NavEKF_Source.cpp, libraries/AP_NavEKF/AP_NavEKF_Source.h, libraries/AP_NavEKF3/AP_NavEKF3.cpp, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/RC_Channel/RC_Channel.cpp
Replaces https://github.com/ArduPilot/ardupilot/pull/17566 as the PR isn't updating when the branch is pushed to github
=> RC_Channel: refactor EKF_POS_SOURCE

libraries/AP_HAL_ChibiOS/RCOutput.cpp, libraries/AP_HAL_ESP32/RCOutput.cpp, libraries/AP_Mission/AP_Mission.cpp
What does 255 mean?
I think it is the maximum value of UINT8_T.
I am the name of the definition of the maximum value of UINT8_T.
I change to the definition name.
=> global: Change the magic number to a defined value

Tools/autotest/param_metadata/param_parse.py
=> Tools: update param_parse.py

libraries/AP_Scripting/drivers/EFI_SkyPower.lua
and accept both extended and 11-bit CAN
=> AP_Scripting: added 2nd supply voltage to SkyPower EFI driver

libraries/AP_Scripting/applets/ahrs-source-extnav-optflow.lua, libraries/AP_Scripting/applets/ahrs-source-extnav-optflow.md, libraries/AP_Scripting/examples/ahrs-source-gps-optflow.lua, libraries/AP_Scripting/examples/ahrs-source-gps-wheelencoders.lua, libraries/AP_Scripting/examples/ahrs-source.lua, libraries/RC_Channel/RC_Channel.cpp, libraries/RC_Channel/RC_Channel.h
Co-authored-by: Michelle Rossouw <michelleros128@gmail.com>
these data sources span more than just position
=> RC_Channel: rename EKF_POS_SOURCE to EKF_SOURCE_SET

libraries/AP_Scripting/applets/Param_Controller.lua, libraries/AP_Scripting/applets/Param_Controller.md
depends on #22438 dirlist binding and can run at the same time
=> AP_Scripting:Add parameter controller applet

Tools/scripts/build_autotest.sh, Tools/scripts/build_ci.sh
the command-line interface for setup.py is deprecated
See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
=> Tools: stop invoking setup.py directly

Tools/Replay/MsgHandler.cpp
The return type is BOOL. BOOL values are TRUE and FALSE.
=> Replay: Change to a Boolean value

Tools/Replay/MsgHandler.cpp
n C++, I think nullptr is better.
=> Replay: Change NULL to nullptr

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
allows setting alternate pin modes pin drive strengths etc.
=> AP_Scripting: add bindings get/set full mode for GPIO

Tools/Replay/MsgHandler.cpp
Type declarations and processing can be done together.
=> Replay: Declare the type of the loop variable and consolidate the processing

libraries/AP_Compass/AP_Compass.cpp
Add existing devices to the list.
=> AP_Compass: Add existing devices

ArduCopter/mode_auto.cpp
Replaces https://github.com/ArduPilot/ardupilot/pull/14554
```
MatekF405                           *      *           -32     -32               *      *      *
Pixhawk1-1M-bdshot                  *                  -32     -32               *      *      * …
```
=> Copter: mode_auto: remove more code based on defines

libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
this makes "map POSM POST" work on aerobatic scripts
=> Scripting: added Lat,Lon to aerobatics POSM/POST

libraries/AP_RobotisServo/AP_RobotisServo.cpp
Replaces https://github.com/ArduPilot/ardupilot/pull/23689 as I can't force-push that branch
=> AP_RobotisServo: Send register write values as little-endian

libraries/AP_Arming/AP_Arming.cpp
Specify the product in the parameter itself
=> AP_Arming: mark ARMING_RUDDER as Plane,Rover,Copter and Blimp only

libraries/SITL/SIM_Gripper_EPM.cpp, libraries/SITL/SIM_Gripper_Servo.cpp, libraries/SITL/SIM_RF_LightWareSerial.cpp, libraries/SITL/SIM_RF_NMEA.cpp, libraries/SITL/SIM_RF_Wasp.cpp, libraries/SITL/SIM_Sprayer.cpp, libraries/SITL/SITL.cpp
Extracted from https://github.com/ArduPilot/ardupilot/pull/26855/files
- lower barrier to entry for these patches
- simplifies the other PR
- nobody's going to complain by a slightly faster SITL.  Or notice.
- 
-
=> SITL: Change division to multiplication

ArduCopter/mode.h, ArduCopter/mode_auto.cpp
This is a small comment improvement that came out of the review of the slung payload PR https://github.com/ArduPilot/ardupilot/pull/27783
=> Copter: add comment to loc_from_cmd

libraries/AP_HAL_ESP32/AnalogIn.cpp, libraries/AP_HAL_ESP32/AnalogIn.h
AP_HAL_ESP32: ADC ported to new idf 5.x driver and debugged
=> AP_HAL_ESP32: ADC ported to new idf 5.x driver and debugged

Tools/autotest/quadplane.py
DCM really degrades quickly when travelling in straight lines:
=> autotest: add simple test that wind estimates from DCM and EKF3 converge

ArduPlane/Plane.h, ArduSub/Sub.h
=> Remove stray log_init declaration

libraries/AP_DAL/LogStructure.h
Well, explain the names rather than document, really.
=> AP_DAL: document more replay messages

libraries/AP_Scripting/examples/AHRS_switch.lua
and use EKF2/EKF3, more likely to be useful
=> AP_Scripting: use cached in AHRS_switch example

libraries/AP_TemperatureSensor/AP_TemperatureSensor.cpp, libraries/AP_TemperatureSensor/AP_TemperatureSensor_MCP9600.cpp
fix MCP9600 i2c address and TEMP9 index.
=> AP_Temperature: fix MCP9600 i2c address and TEMP9 index

Tools/environment_install/install-prereqs-mac.sh
=> Tools: remove curl from installation as its not needed

ArduPlane/quadplane.cpp
According to @peterbarker 's suggestions here: https://github.com/ArduPilot/ardupilot/pull/28329#discussion_r1793096558
=> Plane: Refactored quadplane's SLT_Transition::active_frwd()

libraries/AP_HAL_QURT/packaging/.gitignore, libraries/AP_HAL_QURT/packaging/make_package.sh, libraries/AP_HAL_QURT/packaging/pkg/control/control.in, libraries/AP_HAL_QURT/packaging/pkg/control/postinst
AP_HAL_QURT: Add Debian packaging script and support files
=> AP_HAL_QURT: Add Debian packaging script and support files

.github/workflows/qurt_build.yml, libraries/AP_HAL_QURT/packaging/make_package.sh
and fixed make_package.sh to not use sudo, which is not allowed on the build server
ping @katzfey
=> HAL_QURT: build deb packages in CI

libraries/AP_HAL_QURT/install.sh
copies so and frontend elf to vehicle
ping @rmackay9
=> HAL_QURT: added install script

Tools/scripts/size_compare_branches.py
```
Board,plane
CubeOrange,*
```
=> Tools: strip python2 support from size_compare_branches.py

ArduCopter/mode_poshold.cpp
Use the common definition of G-force.
=> Copter: Use GRAVITY_MSS

libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
This is done on the other devices and avoids stack allocation and buffer copying in the SPI driver
=> Direct DMA transfer on Invensense v3

Tools/autotest/arducopter.py
... default context and reboot is rather helpful.
=> autotest: tidy GpsForYaw using new infrastructure

Tools/AP_Bootloader/board_types.txt
New board id has been added for CrazyF405 FC
=> feat:New board id added for CrazyF405 FC

Tools/AP_Bootloader/board_types.txt
Board ID for CSKY-PMU upcoming board
=> AP_Bootloader: reserve a board ID for CSKY-PMU

Tools/autotest/vehicle_test_suite.py
=> autotest: remove parameters from SIM-param-whitelist

libraries/AP_HAL/board/esp32.h, libraries/AP_HAL_ESP32/Scheduler.cpp
Please see commits for details.
=> AP_HAL_ESP32: misc fixes

libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.cpp
the apparent wind had an offset error in the passthrough WIND frame, this fixes the issue.
=> Ap_Frsky_Telem: fix for apparent wind in the passthrough WIND frame

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/drivers/UltraMotion.lua, libraries/AP_Scripting/drivers/UltraMotion.md, libraries/AP_Scripting/generator/description/bindings.desc, libraries/SRV_Channel/SRV_Channel.h, libraries/SRV_Channel/SRV_Channels.cpp
Support for these servos:
https://www.ultramotion.com/servo-cylinder/
@CraigElder has tested
=> AP_Scripting: support UltraMotion CAN servos

libraries/AP_HAL_ChibiOS/system.cpp
=> AP_HAL_ChibiOS: add lf to panic message

Tools/CPUInfo/CPUInfo.cpp, libraries/AP_AHRS/AP_AHRS_View.cpp, libraries/AP_DDS/AP_DDS_Client.cpp, libraries/AP_FlashStorage/examples/FlashTest/FlashTest.cpp, libraries/AP_HAL_ChibiOS/UARTDriver.cpp, libraries/AP_HAL_Linux/AnalogIn_Navio2.cpp, libraries/AP_HAL_Linux/CameraSensor_Mt9v117.cpp, libraries/AP_HAL_Linux/OpticalFlow_Onboard.cpp, libraries/AP_HAL_Linux/RCInput_Navio2.cpp, libraries/AP_HAL_Linux/RCOutput_AioPRU.cpp, libraries/AP_HAL_Linux/RCOutput_PRU.cpp, libraries/AP_HAL_Linux/RCOutput_ZYNQ.cpp, libraries/AP_HAL_Linux/SPIUARTDriver.cpp, libraries/AP_HAL_Linux/VideoIn.cpp, libraries/AP_HAL_SITL/Scheduler.cpp, libraries/AP_HAL_SITL/Storage.cpp, libraries/AP_InertialSensor/AP_InertialSensor_BMI160.cpp, libraries/AP_InertialSensor/AP_InertialSensor_LSM9DS0.cpp, libraries/AP_InertialSensor/AP_InertialSensor_LSM9DS1.cpp, libraries/AP_InternalError/AP_InternalError.cpp, libraries/AP_Logger/AP_Logger_Backend.cpp, libraries/AP_Param/AP_Param.cpp, libraries/AP_RCProtocol/AP_RCProtocol_SRXL2.cpp, libraries/AP_Radio/AP_Radio_bk2425.cpp, libraries/AP_Radio/AP_Radio_cc2500.cpp, libraries/AP_Radio/AP_Radio_cypress.cpp, libraries/SITL/SIM_Frame.cpp, libraries/SITL/SIM_JSON_Master.cpp, libraries/SITL/SIM_XPlane.cpp
panic adds this within the HAL layer.
=> Remove superfluous linefeed from panic strings

libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.h, libraries/AP_VisualOdom/AP_VisualOdom.cpp
Happened to stumble on a couple typos.
=> Fix singleton panic messages

ArduCopter/Parameters.cpp, ArduPlane/Parameters.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp
=> update FS actions metadata with DO_RETURN_PATH_START

Tools/Frame_params/ModalAI/SentinelM0065.parm
Added a default parameter set for the ModalAI Sentinel with IO board and PWM ESCs
=> Tools: Frame_params: Added ModalAI Sentinel with IO board

.github/workflows/macos_build.yml
ccache is segfaulting in CI on MacOS
=> CI: disable ccache for MacOS builds

.github/workflows/macos_build.yml
This reverts commit c4327161bce5e4ee8b68b6ff4cdc8d19c0d9afc5.
=> Revert "CI: disable ccache for MacOS builds"

libraries/AP_Soaring/AP_Soaring.h, libraries/AP_Soaring/AP_Soaring_config.h
* Prepare for more compile time additional features in soaring that will be enabled/disabled in the config header
=> AP_Soaring: Move define to config file

Tools/ros2/ardupilot_dds_tests/ardupilot_dds_tests/copter_takeoff.py
* Finish timeout implementation missing variables
* Remove unused imports
=> Tools: ros2: Clean up copter takeoff

Tools/scripts/generate_manifest.py
add MicoAir743 to Tools/scripts/generate_manifest.py
=> Tools: add MicoAir743 to manifest generator

libraries/AP_HAL/SIMState.cpp
mirrors if c1016ae52ee4de3181b2c0a07369e51f05eb46f7
=> AP_HAL: SIMState: do a single nullptr check in SIMState servo sim

libraries/AP_DDS/AP_DDS_Client.cpp
Allow waiting forever for DDS to come up. You will now see this in terminal:
The rate it's displayed is by default 1Hz, but configurable via the existing DDS_TIMEOUT_MS. 
Currently, we make users bump up `DDS_TIMEOUT_MS` * `DDS_MAX_RETRY` to the time they expect the companion computer to boot up. Now, if you know DDS is always available, you don't care about the time it takes.
I also added a message to show DDS is initializing, which is handy if you bumped up `DDS_TIMEOUT_MS` * `DDS_MAX_RETRY` to a really high value.
Add an arming check to require a DDS connection. An infinite wait will wait as long as needed for the companion computer to boot up. Once it's up, you can arm.
=> AP_DDS: Add infinite initialization wait

libraries/AP_DDS/README.md
* Remove conflicting info with the wiki
=> AP_DDS: Sync README with Wiki

.github/workflows/colcon.yml, .github/workflows/esp32_build.yml, .github/workflows/test_coverage.yml, .github/workflows/test_scripting.yml, .github/workflows/test_sitl_periph.yml, .github/workflows/test_unit_tests.yml, Tools/AP_Periph/wscript, Tools/environment_install/install-prereqs-arch.sh, Tools/environment_install/install-prereqs-mac.sh, Tools/environment_install/install-prereqs-openSUSE-Tumbleweed.sh, Tools/ros2/README.md, Tools/scripts/configure-ci.sh, Tools/scripts/esp32_get_idf.sh, Tools/scripts/size_compare_branches.py, libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/README.md
Leonard got an error message which told him to use plain `python` and that was may not have ended well...
=> use python3 -m pip to install Python packages

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
... I can't commit without these fixes :-)
=> AP_HAL_ChibiOS: chibios_hwdef.py: flake8 correctness fixes

Tools/AP_Bootloader/board_types.txt
=> Tools:reserve bd id for BrahamF4

Tools/ardupilotwaf/boards.py
seems to have changed between versions
=> waf: correct clang++ extension name

libraries/AP_Mount/AP_Mount_Viewpro.cpp, libraries/AP_Mount/AP_Mount_Viewpro.h
Add zoom function for ViewPro IR sensor. Also read IR zoom value from Viewpro
=> AP_Mount: zoom for Viewpro IR sensor

ArduPlane/Parameters.cpp
Missed in original add of flight mode
=> ArduPlane:add missing flight mode metadata

libraries/AP_BLHeli/AP_BLHeli.cpp
they can be combined on both BLHeli32 and AM32
=> AP_BLHeli: fixed documentation for SERVO_BLH_3DMASK and SERVO_BLH_RVMASK

libraries/RC_Channel/RC_Channel.cpp
Missed from https://github.com/ArduPilot/ardupilot/pull/28881
=> RC_Channel: add docs for copter inflight ahrs trim

Tools/AP_Periph/rc_out.cpp
This matches how Hitec servos report. I don't have any other types to test.
=> Tools: AP_Periph: SIM: servo telem move to one indexed

ArduPlane/RC_Channel_Plane.cpp, libraries/RC_Channel/RC_Channel.cpp, libraries/RC_Channel/RC_Channel.h
Sorry, couldn't stop myself
needs #29302 merged first
=> ArduPlane:add AUTOLAND AUX Function

libraries/AP_Filesystem/AP_Filesystem_FlashMemory_LittleFS.cpp
=> AP_Filesystem: LittleFS: fix minor memory issues

ArduPlane/Plane.h, ArduPlane/events.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp
Last one....for today...just as a low action....to save some flash...easy add to crt if we think its needed
=> Add Autoland batt fs action

Tools/autotest/sim_vehicle.py, Tools/vagrant/initvagrant.sh, Vagrantfile
Had to find another source for a base box for this; bento doesn't seem to have published one properly yet.
=> Add Vagrant VM for Oracular

libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp
=> AP_NavEKF3: correct the scope of posErr

libraries/AP_NavEKF3/LogStructure.h
I based this off reading through `generate_1.py`
=> AP_NavEKF3: document variance state fields

Tools/autotest/arducopter.py, libraries/AP_Mission/AP_Mission.h
on top of https://github.com/ArduPilot/ardupilot/pull/29436 which should be merged first
=> autotest: add copter autotest for mission clearing after reboot 

libraries/AP_ADSB/AP_ADSB.cpp
=> AP_ADSB: clarify ADSB_LIST_ALT docs

libraries/AP_Airspeed/AP_Airspeed.cpp, libraries/AP_Airspeed/AP_Airspeed.h
simplifies https://github.com/ArduPilot/ardupilot/pull/29467
=> AP_Airspeed: move calibration state into calibration state struct

libraries/AP_Beacon/AP_Beacon.cpp, libraries/AP_Beacon/AP_Beacon_SITL.cpp
gets us closer to making alt private
=> AP_Beacon: construct locations using Location constructor

Tools/autotest/rover.py, Tools/autotest/vehicle_test_suite.py
will need to wait for MAVProxy corrections before enabling by default
autotest: correct assert_rally_content_same method
Actually found several bugs in MAVProxy while fixing this test.
=> autotest: correct GCSRally autotest

libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
This is a NFC.
When reading logs from a vehicle with few diverged states/variances, it's very hard to know if the divergence stopped on its own or if it is hitting the constraints. I attempted to document them here.
=> AP_NavEKF3: Add table to read EKF states and varainces limits

libraries/RC_Channel/RC_Channel.cpp, libraries/RC_Channel/RC_Channel.h
=> RC_Channel: make pwm_to_angle_dz_trim and pwm_to_range_dz full resolution

libraries/AC_Fence/AC_PolyFence_loader.cpp, libraries/AC_Fence/AC_PolyFence_loader.h
=> AC_Fence: rename load_from_eeprom to load_from_storage

.github/workflows/cygwin_build.yml, .github/workflows/esp32_build.yml, .github/workflows/test_dds.yml, .github/workflows/test_replay.yml, .github/workflows/test_sitl_blimp.yml, .github/workflows/test_sitl_copter.yml, .github/workflows/test_sitl_plane.yml, .github/workflows/test_sitl_rover.yml, .github/workflows/test_sitl_sub.yml, .github/workflows/test_sitl_tracker.yml, .github/workflows/test_unit_tests.yml
=> .github: move upload artifact forward

libraries/AP_Baro/AP_Baro.cpp
the bodies of he cases are identical, so consolidate the case statements
=> AP_Baro: consolidate MS5611 probes in feature-detect

Tools/environment_install/install-prereqs-mac.sh
Adding setuptools and matplotlib packages to install using pip.
=> Tools: adding necessary packages to prereqs script for macos

Tools/scripts/build_binaries.py, Tools/scripts/build_sizes/build_sizes.py, Tools/scripts/gen_stable.py, Tools/scripts/generate_manifest.py
this is just slowing down the build server
=> Tools: removed special case for old beta-4.3 builds

libraries/AP_Math/AP_Math.h, libraries/AP_Param/AP_Param.h
These haven't been a thing for nearly a decade.
=> drop vestiges of ancient parameter types

libraries/SITL/SITL.cpp
This is a similar type to 3b96788c
=> SITL: adding @Group tag to BZ_

Tools/environment_install/install-prereqs-mac.sh
this seems to fix the bdist_wheel issue
=> Tools: try to fix MacOS builds

Tools/AP_Bootloader/board_types.txt
=> AP_Bootloader: add UAV-DEV GmbH FC-UM982-H7 FC-M10S-H7 UM982-H7

ArduSub/config.h, Blimp/config.h
=> Remove vestiges of far-from-origin checks

libraries/AP_GPS/AP_GPS.cpp
Alternative to https://github.com/ArduPilot/ardupilot/pull/29642/files
=> AP_GPS: correct _port array-overread in EAHRS case

libraries/AP_DAL/AP_DAL.cpp, libraries/SITL/SITL.cpp
- stop leaking 
- avoif nullptr dereference
-
=> Correct filehandle handling in error paths

ArduCopter/commands.cpp, libraries/AP_Common/Location.cpp, libraries/AP_Common/Location.h, libraries/AP_GPS/AP_GPS_ExternalAHRS.cpp, libraries/AP_GPS/AP_GPS_MSP.cpp, libraries/SITL/SIM_AirSim.cpp, libraries/SITL/SIM_Aircraft.cpp, libraries/SITL/SIM_JSBSim.cpp, libraries/SITL/SIM_Scrimmage.cpp, libraries/SITL/SIM_SilentWings.cpp, libraries/SITL/SIM_last_letter.cpp
removes external knowledge of internal Location shape
=> add and use a Location::copy_alt_from

ArduPlane/avoidance_adsb.cpp, ArduPlane/commands.cpp, ArduPlane/commands_logic.cpp, ArduPlane/fence.cpp, ArduPlane/mode_circle.cpp, ArduPlane/mode_qrtl.cpp, ArduPlane/quadplane.cpp
backport of https://github.com/ArduPilot/ardupilot/pull/29765
=> Plane: backport of circle alt fix

ArduCopter/Copter.h, ArduCopter/fence.cpp, ArduPlane/Plane.h, ArduPlane/fence.cpp, ArduSub/Sub.h, ArduSub/fence.cpp, Rover/Rover.h, Rover/fence.cpp, Tools/autotest/arducopter.py, libraries/AC_Fence/AC_Fence.cpp, libraries/AC_Fence/AC_Fence.h, libraries/AP_Vehicle/AP_Vehicle.cpp, libraries/AP_Vehicle/AP_Vehicle.h
It seems I did not push the latest changes for https://github.com/ArduPilot/ardupilot/pull/28840 and it got merged without these. I am not quite sure what happened.
=> Missing commits from fence margin check code.

libraries/AP_DroneCAN/AP_Canard_iface.cpp
applies this fix
https://github.com/dronecan/libcanard/pull/80
=> DroneCAN: update libcanard

ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduCopter/mode_throw.cpp
Replaces https://github.com/ArduPilot/ardupilot/pull/29359 which I inadvertently closes
=> Copter: Throw mode add params for desired ascent alt after throw

libraries/AP_TECS/AP_TECS.cpp
... something better than nothing?
=> AP_TECS: add documentation for TEC3 message

Tools/AP_Periph/can.cpp, libraries/AP_DroneCAN/AP_Canard_iface.cpp
The defined value is inverted. 
By inverting the variable value, it can be determined based on the defined value.
=> DroneCAN: determine based on the defined value

ArduPlane/Plane.h, ArduPlane/commands_logic.cpp, ArduPlane/mode.cpp, ArduPlane/takeoff.cpp, Tools/autotest/arduplane.py
For details, see https://github.com/ArduPilot/ardupilot/pull/29834
The new autotest has been renamed in this iteration, to better fit its context.
=> Master: Prevent rotation pitch calculations from running post-rotation

libraries/AP_GPS/AP_GPS_NOVA.cpp, libraries/AP_GPS/AP_GPS_NOVA.h
The URL of the PDF file is incorrect. 
Define the message IDs and use a SWITCH statement.
=> AP_GPS: Define the message IDs for NOVA

ArduPlane/transition.h
In Japan, there is an ArduPilot Japan community on Facebook.
This community includes Professor Miwa from Tokushima University.
Professor Miwa pointed out an error in the description.
I reviewed the source code and submitted a correction PR.
=> Plane: Change the class description (NFC)

libraries/SITL/SIM_Vicon.cpp
Some snuck in after #29711 was created but before it was merged
=> Fixed missed now-incorrect uses of AP_Float

Tools/Replay/DataFlashFileReader.cpp, Tools/Replay/DataFlashFileReader.h, Tools/Replay/Replay.cpp, Tools/Replay/Replay.h
Adds a progress bar to show percentage of file processed through replay
=> Replay: add option to show progress of log file processed

ArduCopter/mode_rtl.cpp
Even if the conditions differ, we consolidate when the processing is the same.
I don't think there's any benefit in increasing the number of steps.
=> Copter: Consolidate processing

Tools/autotest/arducopter.py, libraries/SITL/SIM_Precland.cpp, libraries/SITL/SIM_Precland.h
Closes https://github.com/ardupilot/ardupilot/issues/29594
=> Avoid dying when precland parameters are zero

libraries/AC_Fence/AC_PolyFence_loader.cpp, libraries/AP_Beacon/AP_Beacon_Pozyx.cpp, libraries/AP_EFI/AP_EFI_Serial_MS.cpp, libraries/AP_WheelEncoder/WheelEncoder_SITL_Quadrature.cpp
STM32 is good at multiplication.
=> Global: Change division to multiplication

libraries/AP_Logger/AP_Logger_MAVLink.cpp, libraries/AP_Logger/LogStructure.h
... the regex is pretty tight!
=> AP_Logger: correct extraction of DMS message metadata

ArduSub/AP_Arming_Sub.cpp, ArduSub/Sub.cpp, ArduSub/failsafe.cpp, ArduSub/radio.cpp
This makes SITL behave the same as a real board does...these must have been patches for older CI issues...
=> Sub:remove SITL dependancies

ArduSub/failsafe.cpp, Tools/autotest/ardusub.py
Very simple CI tests, but better than nothing
=> Add Sub tests for GCS and RC

Tools/ardupilotwaf/boards.py, wscript
allows embedding of any lua driver or applet in the tree into ROMFS
=> waf: allow --embed-XXX on configure

ArduSub/Parameters.cpp, ArduSub/Parameters.h, ArduSub/mode.cpp, ArduSub/mode_althold.cpp, libraries/AP_Motors/AP_Motors6DOF.cpp, libraries/AP_Motors/AP_Motors6DOF.h
This solves an issue where the thrusters start sucking in air when at the surface, which increased noise and power consumption
=> Sub: allow limiting upwards throttle at surface

ArduPlane/Plane.h
=> Plane:remove unused declaration

Tools/autotest/vehicle_test_suite.py
this should ensure that when a log message is added then it must be documented as well
... and hopefully we can reduce the length of these lists over time
=> autotest: add ratchet for log message documentation

Tools/autotest/vehicle_test_suite.py, libraries/AP_Generator/AP_Generator_RichenPower.cpp
Also removes the "GEN" message as something that needs documenting.
=> Document RICH logger message

libraries/RC_Channel/RC_Channel.cpp
missed a few the first time...verified that they work in SITL for Sub
=> RC_Channel:add sub to additional aux sw metadata

ArduSub/Parameters.h, ArduSub/radio.cpp, libraries/RC_Channel/RC_Channel.h, libraries/RC_Channel/RC_Channels.cpp
@ES-Alexander fyi...now it works
=> Sub: Enable RCMAP to function

libraries/AP_Landing/AP_Landing.cpp, libraries/AP_Landing/AP_Landing.h, libraries/AP_Landing/AP_Landing_Slope.cpp
backport of https://github.com/ArduPilot/ardupilot/pull/30041
=> Plane: backport of terrain landing fix

libraries/AP_HAL_SITL/SITL_State.cpp
check is at the top of the function
=> AP_HAL_SITL: remove redundant sitl nullptr checks

libraries/AP_Scripting/AP_Scripting_helpers.cpp
#30087 for master-specific code
=>  AP_Scripting: fix more non-string-induced null pointer dereferences

Tools/autotest/vehicle_test_suite.py, libraries/AC_Fence/AC_Fence.cpp
Pretty much so we can clear it out of the greylist.
=> Document FENC fence diagnostic message

libraries/AP_TECS/AP_TECS.cpp
=> AP_TECS: Fix spelling

libraries/AP_TECS/AP_TECS.cpp, libraries/AP_TECS/AP_TECS.h
* And access with option_is_set helper
=> AP_TECS: Convert option to enum class

Tools/autotest/vehicle_test_suite.py, libraries/AP_DAL/LogStructure.h
Despite the comment, these are actually useful to have
=> Create LogMessage documentation for Replay messages

libraries/AP_HAL_ChibiOS/hwdef/NarinFC-H7/README.md
=> AP_HAL_ChibiOS: UPDATE NarinFC-H7

ArduCopter/mode.h, ArduCopter/mode_auto.cpp
=> Copter: announce number of completed circles in NAV_LOITER_TURNS

Dockerfile
=> correct typo in Dockerfile

ArduSub/Parameters.cpp, ArduSub/Parameters.h, ArduSub/Sub.h, ArduSub/system.cpp
was wondering why I got no video on my DIY reference sub frame
tested on AET-H743-Basic
=> Sub:Add OSD into std builds for FPV

libraries/AP_DroneCAN/AP_DroneCAN.cpp
Currently DroneCAN will try and output 0 PWM as a valid output. Our onboard outputs treat 0 as no pulses. Over DroneCAN for servos this will result in them going to min (unless direct PWM output option is set). For non reversing ESCs it will set to 0 output, for reversible ESCs this will result in full reverse.
=> AP_DroneCAN: servo/esc don't output zero pwm

libraries/RC_Channel/RC_Channel.h, libraries/RC_Channel/RC_Channels.cpp
will allow more consts throughout code.
=> RC_Channel: make RC dummy channel file-scoped to allow consting methods

.github/workflows/colcon.yml, .github/workflows/test_dds.yml, libraries/AP_DDS/AP_DDS_Client.cpp, libraries/AP_DDS/AP_DDS_ExternalControl.cpp
This updates global constant in sync with this PR: https://github.com/ArduPilot/Micro-XRCE-DDS-Gen/pull/5
=> AP_DDS: Added namespace representation for global constants

Tools/AP_Periph/AP_Periph.h, Tools/AP_Periph/serial_tunnel.cpp, Tools/ardupilotwaf/boards.py, Tools/autotest/arducopter.py, Tools/autotest/pysim/util.py, Tools/autotest/vehicle_test_suite.py, libraries/AP_HAL_SITL/SITL_Periph_State.cpp
This work sponsored by Freespace Solutions.
=> Allow for simultaneous serial passthrough connections on AP_Periph

ArduPlane/VTOL_Assist.cpp, Tools/autotest/quadplane.py
... and augment the autotests to check pitch assist
=> Plane: remove use of roll_sensor from VTOL assist calculations

libraries/AP_DDS/wscript
Reworked version of @Ryanf55 's patch (https://github.com/Ryanf55/ardupilot/tree/28497-fix-waf-dds-gen-race)
- Fixes https://github.com/ArduPilot/ardupilot/issues/28497
=> AP_DDS: fix race condition in waf DDS build

.pre-commit-config.yaml, libraries/AP_DDS/gen_config_h.py
% `pre-commit autoupdate`
```
[https://github.com/psf/black] updating 23.7.0 -> 25.1.0
```
% `pre-commit run black --all-files`
```
black....................................................................Failed
- hook id: black
- files were modified by this hook
reformatted libraries/AP_DDS/gen_config_h.py
All done! ✨ 🍰 ✨
1 file reformatted, 33 files left unchanged.
```
% `pre-commit run black --all-files`
```
black....................................................................Passed
```
=> Upgrade psf/black in pre-commit

.github/workflows/colcon.yml
* Allows development to proceed on master without breaking ardupilot again
=> .github: Pin uXRCEDDSGen and use depth 1

ArduCopter/AP_Arming_Copter.cpp, ArduCopter/Copter.h, ArduCopter/GCS_MAVLink_Copter.cpp, ArduCopter/autoyaw.cpp, ArduCopter/mode.cpp, ArduCopter/mode.h, ArduCopter/mode_althold.cpp, ArduCopter/mode_auto.cpp, ArduCopter/mode_autotune.cpp, ArduCopter/mode_brake.cpp, ArduCopter/mode_circle.cpp, ArduCopter/mode_guided.cpp, ArduCopter/mode_land.cpp, ArduCopter/mode_loiter.cpp, ArduCopter/mode_rtl.cpp, ArduCopter/mode_smart_rtl.cpp, ArduCopter/mode_systemid.cpp, ArduCopter/mode_zigzag.cpp, ArduCopter/takeoff.cpp, ArduSub/mode.h, libraries/AC_AttitudeControl/AC_AttitudeControl.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_AttitudeControl/AC_PosControl.h
This PR converts the heading structure to radians.
To follow #30423
=> Copter: Change heading to radians

libraries/AP_Networking/AP_Networking_PPP.cpp, libraries/AP_Networking/config/lwipopts.h
backport of https://github.com/ArduPilot/ardupilot/pull/30274 to 4.6
test flown on a copter with a BotBloxDroneNet board
=> AP_Networking: make PPP much more robust (4.6 backport)

libraries/AP_Terrain/TerrainUtil.cpp
We can share the timestamp for these touches.
=> AP_Terrain: reduce calls to AP_HAL::millis()

.github/workflows/test_branch_conventions.yml
=> .github: add test that there are no Merge commits in the branch

libraries/AP_HAL/AP_HAL_Boards.h
Reserving id 1028 to pocketbeagle2
=> AP_HAL: reserve HAL_BOARD_SUBTYPE_LINUX_POCKET2

Tools/scripts/size_compare_branches.py
Building a branch which disabled scripting on CubeOrange:
```
pbarker@crun:~/rc/ardupilot(pr/size-compare-features)$ ./Tools/scripts/size_compare_branches.py --compare=features --vehicle copter,rover,plane --board=CubeOrange
SCB: Running (git symbolic-ref --short HEAD) in (.)
SCB-GIT: pr/size-compare-features
SCB: Running (git merge-base pr/size-compare-features master) in (.)
SCB-GIT: 260732a2eab82a9344dfc68a237c99258dceeed1
SCB: Using merge base (260732a2eab82a9344dfc68a237c99258dceeed1)
SCB: Building Task(CubeOrange, 260732a2eab82a9344dfc68a237c99258dceeed1, /tmp/tmpxcuos0ze/out-master-CubeOrange, ['copter', 'rover', 'plane'], [])
SCB: Running (git checkout 260732a2eab82a9344dfc68a237c99258dceeed1) in (.)
SCB: Running (git submodule update --recursive) in (.)
SCB: Running (./waf …
```
=> Tools: add option to compare features to size_compare_branches.py

libraries/AP_Scripting/applets/plane_ship_landing.md
based on https://discuss.ardupilot.org/t/ship-landing-support/82772
=> AP_Scripting: added docs for plane_ship_landing.lua

Tools/scripts/build_options.py, libraries/AP_HAL_ChibiOS/hwdef/scripts/defaults_periph.h
Tested this on custom build server. It works good.
=> Fix dependencies for AP_PERIPH_DEVICE_TEMPERATURE_ENABLED

.github/workflows/test_branch_conventions.yml
Tested in my own repo - both new tests work
=> .github: test_branch_conventions.py: test for fixup commits and commits lacking a :

libraries/AP_Servo_Telem/AP_Servo_Telem.cpp
=> AP_Servo_Telem: correct update of STATUS

ArduCopter/config.h, ArduCopter/mode_acro.cpp, ArduCopter/mode_sport.cpp
Does what it says on the box.
```
CubeOrange,*,*,0,0,*,*,*
```
=> Copter: Convert Sports Mode to radians and finish Acro Mode

ArduCopter/Copter.h
=> Copter: heli: remove unused rotor speed deglitch filter

Tools/scripts/build_options.py, Tools/scripts/extract_features.py, libraries/AP_HAL_ChibiOS/hwdef/scripts/defaults_periph.h
Tested this on Custom Build Server. It builds fine.
=> Add AP_PERIPH_RELAY_ENABLED as a build option

libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
This allows using external clock input on IIM42652. We have tested on real hardware and it works well.
IIM42653 seems has the same register for CLKIN configuration, but after testing on real hardware, we found that the data could not be read normally. So we have only enabled CLKIN on IIM42652 now.
=> AP_InertialSensor: support CLKIN configuration on IIM42652

Tools/scripts/build_options.py, Tools/scripts/extract_features.py, libraries/AP_HAL_ChibiOS/hwdef/scripts/defaults_periph.h
Tested this on CBS, works good.
=> Allow selecting AP_PERIPH_PROXIMITY_ENABLED on custom build server

Tools/scripts/build_options.py, Tools/scripts/extract_features.py
Tested this on custom build server and it works good.
=> Tools: add  AP_PERIPH_MAG_ENABLED as a build option

Tools/scripts/build_options.py, Tools/scripts/extract_features.py
=> Tools: add  AP_PERIPH_RANGEFINDER_ENABLED as a build option

Tools/scripts/build_options.py, Tools/scripts/extract_features.py, libraries/AP_HAL_ChibiOS/hwdef/scripts/defaults_periph.h
=> Allow selecting AP_PERIPH_EFI_ENABLED on custom build server

ArduCopter/Copter.cpp, ArduCopter/GCS_MAVLink_Copter.cpp, ArduCopter/mode.h, ArduCopter/mode_guided.cpp, ArduCopter/mode_zigzag.cpp, ArduPlane/GCS_MAVLink_Plane.cpp, ArduPlane/Plane.cpp, libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_AttitudeControl/AC_PosControl.h, libraries/AC_WPNav/AC_WPNav.h
```
Board,antennatracker,blimp,bootloader,copter,heli,plane,rover,sub
CubeOrange,*,*,*,*,*,*,*,*
```
=> Add units to crosstrack error - No Compiler Change

Tools/scripts/build_options.py, Tools/scripts/extract_features.py
=> Tools: add  AP_PERIPH_RCIN_ENABLED as a build option

.github/workflows/test_scripting.yml, Tools/scripts/run_lua_language_check.py
This check has been failing in CI sometimes, this extra logging should help us work out why.
=> actions: test scripting: add more verbose logging of language server install

Tools/scripts/build_options.py, Tools/scripts/extract_features.py
=> Tools: add  AP_PERIPH_RPM_ENABLED as a build option

libraries/RC_Channel/RC_Channel.cpp
Tested in combination with the changes in this PR --> https://github.com/ArduPilot/ardupilot/pull/30786
=> RC_Channel: Add All-Vehicles value to scripting options for OPTION param.

ArduCopter/mode_guided.cpp
This should be a no-compiler-change but when I change the static names we do see a change but no change to size.
```
CubeOrange,*,0,0,0,*,*,*
```
bootloader changed on the last PR for some reason.
=> Convert Copter to meters (0-Static): No Compiler name, axis and units

ArduCopter/config.h, ArduCopter/mode.cpp, ArduCopter/mode.h, ArduCopter/mode_althold.cpp, ArduCopter/mode_auto.cpp, ArduCopter/mode_autotune.cpp, ArduCopter/mode_brake.cpp, ArduCopter/mode_circle.cpp, ArduCopter/mode_flowhold.cpp, ArduCopter/mode_follow.cpp, ArduCopter/mode_guided.cpp, ArduCopter/mode_land.cpp, ArduCopter/mode_loiter.cpp, ArduCopter/mode_poshold.cpp, ArduCopter/mode_rtl.cpp, ArduCopter/mode_sport.cpp, ArduCopter/mode_systemid.cpp, ArduCopter/mode_throw.cpp, ArduCopter/mode_zigzag.cpp
```
CubeOrange,*,*,-312,-288,*,*,*
```
=> Convert Copter to meters (1): Convert Position Control limit setters to meters

ArduCopter/AP_Arming_Copter.cpp, ArduCopter/Attitude.cpp, ArduCopter/Copter.h, ArduCopter/GCS_MAVLink_Copter.cpp, ArduCopter/Log.cpp, ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduCopter/avoidance_adsb.cpp, ArduCopter/mode.cpp, ArduCopter/mode.h, ArduCopter/mode_althold.cpp, ArduCopter/mode_auto.cpp, ArduCopter/mode_autotune.cpp, ArduCopter/mode_circle.cpp, ArduCopter/mode_flowhold.cpp, ArduCopter/mode_guided.cpp, ArduCopter/mode_loiter.cpp, ArduCopter/mode_poshold.cpp, ArduCopter/mode_rtl.cpp, ArduCopter/mode_smart_rtl.cpp, ArduCopter/mode_sport.cpp, ArduCopter/mode_systemid.cpp, ArduCopter/mode_zigzag.cpp, ArduCopter/takeoff.cpp
```
CubeOrange,*,0,-544,-512,*,*,*
```
=> Convert Copter to meters (2): Convert Climb Rate functions to meters

Tools/autotest/arduplane.py, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/simple_named_string.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/GCS_MAVLink/GCS.cpp, libraries/GCS_MAVLink/GCS.h
Requires https://github.com/ArduPilot/mavlink/pull/415
=> Add support for NAMED_VALUE_STRING

ArduCopter/AP_Arming_Copter.cpp, ArduCopter/Attitude.cpp, ArduCopter/Copter.h, ArduCopter/Log.cpp, ArduCopter/autoyaw.cpp, ArduCopter/avoidance.cpp, ArduCopter/baro_ground_effect.cpp, ArduCopter/config.h, ArduCopter/crash_check.cpp, ArduCopter/inertia.cpp, ArduCopter/land_detector.cpp, ArduCopter/landing_gear.cpp, ArduCopter/mode.cpp, ArduCopter/mode.h, ArduCopter/mode_auto.cpp, ArduCopter/mode_circle.cpp, ArduCopter/mode_guided.cpp, ArduCopter/mode_loiter.cpp, ArduCopter/mode_rtl.cpp, ArduCopter/mode_smart_rtl.cpp, ArduCopter/precision_landing.cpp, ArduCopter/sensors.cpp, ArduCopter/surface_tracking.cpp, ArduCopter/takeoff.cpp, libraries/AP_LandingGear/AP_LandingGear.cpp, libraries/AP_LandingGear/AP_LandingGear.h, libraries/AP_SurfaceDistance/AP_SurfaceDistance.cpp, libraries/AP_SurfaceDistance/AP_SurfaceDistance.h
```
CubeOrange,*,*,-472,-464,40,*,*
```
=> Convert Copter to meters (4): Convert Guided Mode to meters

libraries/SITL/SIM_Sailboat.cpp
Alternative to https://github.com/ArduPilot/ardupilot/pull/30918
- the steering was already fixed, the throttle was missed
=> SITL: correct sailboat understanding of 0 input to servos

libraries/AP_Networking/AP_Networking_port.cpp
I have seen a stack overflow on a TCP client connection, this fixes it
the stack overflow led to a watchdog
=> AP_Networking: increase stack for network ports

Tools/ardupilotwaf/boards.py, libraries/AP_Baro/AP_Baro.h, libraries/AP_Baro/AP_Baro_Backend.cpp
Closes https://github.com/ArduPilot/ardupilot/issues/30854
=> Make Baro data timeout on Sub much larger

Tools/autotest/arduplane.py
simulation works perfectly - but the check was against the elevator servo which just happened to sometimes be 20-off.
Adjust test to check the correct surface and also require several samples off in a row to make sure the servo position error is consistent
=> autotest: correct servo offset for aileron on stuck-aileron test

libraries/AP_Scripting/drivers/LTE_modem.lua
nice modem with good CAT-M support
this PR also includes some robustness improvements for other modems
=> AP_Scripting: added LTE BG95 and EG800Q support

.pre-commit-config.yaml, Tools/ardupilotwaf/boards.py, Tools/autotest/arducopter.py, Tools/autotest/quadplane.py, Tools/scripts/build_options.py, libraries/AP_Generator/scripts/test-loweheiser.py
=> pre-commit: Discover typos in Python files using codespell again

libraries/GCS_MAVLink/GCS_MAVLink_Parameters.cpp
Bit 0's description accidentally got deleted in #30094
=> GCS_MAVLink: fix MAVn_OPTIONS doc

Tools/autotest/arducopter.py
This should hopefully avoid any Tether-stuck failures
=> autotest: relax TetherStuck test constraints

Tools/environment_install/install-prereqs-ubuntu.sh
Check if a venv already exist on the local directory before trying to make one.
use extras.wxpython.org to get wxpython weel if available !
=> Tools: improve venv install and add wxpython wheel for ubuntu

libraries/AP_Proximity/AP_Proximity_RPLidarA2.cpp, libraries/AP_Proximity/AP_Proximity_RPLidarA2.h
As discussed here: https://discuss.ardupilot.org/t/rplidar-a2-m12-integration/136807
=> AP_Proximity: Add support for RPLidar A2M12

libraries/AC_Avoidance/AC_Avoid.cpp, libraries/AC_Avoidance/AP_OABendyRuler.cpp, libraries/AC_Fence/AC_Fence.cpp, libraries/AC_Fence/AC_Fence.h
Adds support for a separately configurable horizontal fence XY margin via ```FENCE_MARGIN_XY```
=> Fence Horizontal Margin

Tools/autotest/arducopter.py
=> autotest: Fix Autotune Tests

ArduCopter/mode_acro.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/AC_AttitudeControl/AC_AttitudeControl_Logging.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp, libraries/AC_PID/AC_PID.cpp, libraries/AC_PID/AC_PID.h, libraries/AP_AHRS/LogStructure.h
Equivalent of #30570 but without the mode
=> Rate acro with scaled I-term

libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
Somehow we missed this in review
=> AC_AttitudeControl: yaw I scaling should use Z-axis

libraries/AP_Filesystem/AP_Filesystem_FlashMemory_LittleFS.cpp, libraries/AP_Logger/AP_Logger_Flash_JEDEC.cpp
Datasheet: https://www.infineon.com/assets/row/public/documents/10/49/infineon-s25fl064l-64-mbit-8-mbyte-3-datasheet-en.pdf
I have tested this on a new Periph hardware
=> AP_Logger: Add support for S25FL064L
