ArduPilot/ardupilot

- libraries/AP_Notify/AP_Notify.h
- libraries/AP_Notify/Buzzer.cpp
- libraries/AP_Notify/Buzzer.h
type and compare is wrong....it always instantiates (unless pin =0 which is not default)
> AP_Notify: fix incorrect buzzer pin type to stop always instantiating

- .github/workflows/test_chibios.yml
- Tools/ardupilotwaf/boards.py
We are doing all production builds with 10.2.1. We should push all devs to use at least that version. That will allow us to use new C++ features and also ensures users are using a compiler that we do real testing with
> build: require gcc 10.2.x or later for ChibiOS builds

- libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
- libraries/AP_HAL_ChibiOS/hwdef/scripts/dma_resolver.py
we need to use sorted keys in dictionaries to ensure we end up with
the same DMA mapping when using py2 and py3
fixes #15534
ping @WickedShell
> HAL_ChibiOS: fixed hwdef DMA resolver dependency on python2/python3

- libraries/AP_DDS/AP_DDS_Client.cpp
- libraries/AP_DDS/AP_DDS_Client.h
- libraries/AP_DDS/AP_DDS_Topic_Table.h
- libraries/AP_DDS/dds_xrce_profile.xml
Resolves #23278, here is the PR working on SITL:
The NED to ENU conversion seemed fine when I analysed the position coordinates of a plane flying in SITL. As you can see in the screenshot the plane went North-West after takeoff which resulted in a negative X axis (points towards east in ENU) and a positive Y axis (points towards north in ENU). Z is positive after takeoff.
> AP_DDS: Local Pose Publisher

- libraries/AP_Airspeed/AP_Airspeed.cpp
- libraries/AP_Airspeed/AP_Airspeed_Health.cpp
- libraries/AP_GPS/AP_GPS.h
This adds support in the airspeed checks for checking 3D speed instead of just using 2D. 
Redacted: I did lower the necessary quality of GPS to FIX_2D which would expand the time that GPS is used to validate against.
The purpose of this is to allow users to increase the value of `AHRS_WIND_MAX` without the risk that the airspeed sensor is removed from EKF when vertical velocity is a non-trivial part of the airspeed vector. 
Needs validation in SITL with the original changes, however PR scope was reduced and testing was no longer needed before this PR. Will be sure to test this in the plane release. 
Airspeed SIM params:
```
SIM_ARSPD2_FAIL  0.0
SIM_ARSPD2_FAILP 0.0
SIM_ARSPD2_OFS   2013.0
SIM_ARSPD2_PITOT 0.0
SIM_ARSPD2_RATIO 1.9900000095367432
SIM_ARSPD2_RND   2.0
SIM_ARSPD2_SIGN  0 …
```
> Use 3d velocity for airspeed health

- libraries/AP_Motors/AP_MotorsMulticopter.cpp
- libraries/AP_Motors/AP_Motors_Class.h
- libraries/AP_Motors/AP_Motors_Thrust_Linearization.cpp
@lthall believes this might cope better with the big temporary sags small copters get on punch out
> AP_Motors: use raw voltage for battery compensation

- AntennaTracker/version.h
- ArduCopter/version.h
- ArduPlane/version.h
- Blimp/version.h
- Rover/version.h
This updates the versions for "latest" to 4.5.0 for Copter, Plane, Rover, Tracker and Blimp.
I think we've decided that we should try and keep each vehicle's major version number consistent.
Blimp's version file also gets an EOL character (this is on purpose).
> Copter, Plane, Rover, Tracker, Blimp: version to 4.5.0-dev

- libraries/AP_Camera/AP_Camera.cpp
- libraries/AP_Camera/AP_Camera.h
- libraries/AP_Camera/AP_Camera_Backend.h
- libraries/AP_Camera/AP_Camera_MAVLinkCamV2.cpp
- libraries/AP_Camera/AP_Camera_MAVLinkCamV2.h
- libraries/AP_Camera/AP_Camera_Mount.cpp
- libraries/AP_Camera/AP_Camera_Mount.h
- libraries/AP_Camera/AP_Camera_Scripting.cpp
- libraries/AP_Camera/AP_Camera_Scripting.h
- libraries/AP_Camera/AP_Camera_shareddefs.h
- libraries/AP_Mission/AP_Mission_Commands.cpp
- libraries/AP_Mount/AP_Mount.cpp
- libraries/AP_Mount/AP_Mount.h
- libraries/AP_Mount/AP_Mount_Backend.h
- libraries/AP_Mount/AP_Mount_Siyi.cpp
- libraries/AP_Mount/AP_Mount_Siyi.h
- libraries/AP_Scripting/docs/docs.lua
- libraries/AP_Scripting/drivers/mount-viewpro-driver.lua
- libraries/AP_Scripting/generator/description/bindings.desc
- libraries/RC_Channel/RC_Channel.cpp
This PR replaces AP_Camera's set_manual_focus_step() and set_auto_focus() methods with a single, set_focus() method that accepts a "focus type" and a "focus value".  This is very similar to the recent set_focus change https://github.com/ArduPilot/ardupilot/pull/23465
As-is this PR is an NFC but this paves the way for supporting more focus types including the percentage type (aka "PCT" or "Range") which could be useful for missions and other situations where we know the distance to the subject in the frame.  This would allow operators to avoid situations where the camera auto focuses on the fuselage.  Actually when I started on this PR I hoped to implement the PCT type on the ViewPro but sadly while it appears in the ViewPro API it is not yet implemented (at least not on the camera I …
> AP_Camera: set_focus replaces set_manual_focus_step and set_auto_focus

- libraries/AP_RCProtocol/AP_RCProtocol_SRXL2.cpp
- libraries/AP_RCProtocol/AP_RCProtocol_SRXL2.h
We have a static function to retrieve the singleton.
We don't need several static functions that then retrieve the singleton to call methods on - we can just get the singleton and call methods on it...
> AP_RCProtocol: remove intermediate srxl2 callback-chain functions

- libraries/AP_DDS/AP_DDS_Client.cpp
- libraries/AP_DDS/AP_DDS_Client.h
- libraries/AP_DDS/AP_DDS_Topic_Table.h
- libraries/AP_DDS/dds_xrce_profile.xml
Resolves #23279 
Here is the PR working in its current state in SITL:
It is currently following:
```
// In ROS REP 103, it follows this convention
// X - Forward
// Y - Left
// Z - Up
// https://www.ros.org/reps/rep-0103.html#axis-orientation
```
For linear velocity, the data is earth-fixed but starts alligned with the robot body (x-forward)
For angular velocity, the gyro data is body-fixed.
> AP_DDS: Local Velocity Publisher

- Tools/ros2/ardupilot_dds_tests/ardupilot_dds_tests/time_listener.py
- Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_navsat_msg_received.py
- Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_time_msg_received.py
- libraries/AP_DDS/README.md
- libraries/AP_DDS/dds_xrce_profile.xml
Update published topic names to use lower case underscore, and add a prefix `/ap` to prevent conflicts as the `micro_ros_agent` does not currently implement namespaces.
@Ryanf55, [this section](http://docs.ros.org/en/noetic/api/robot_localization/html/integrating_gps.html) of the `robot_localization` manual discusses pose estimates that include GPS and further distinguishes `local` and `global` odom estimates. So we could have: 
- `/pose/filtered/local` - when GPS data excluded from EKF.
- `/pose/filtered/global` - when GPS data is included in EKF.
- (see diagram for remaining topics and frames).
There are also alternate suggestions for naming other sensor topics (e.g. `navsat`). Unfortunately there does not seem to be a standard for topic naming that is consistently applied between …
> AP_DDS: update topic names

- ArduPlane/Parameters.cpp
- ArduPlane/defines.h
- ArduPlane/events.cpp
This is very useful with an aircraft that is expected to be autonomously operating in auto from takeoff to landing. It is convenient to have a GCS connected or RC, but the loss of either isn't considered a reason to terminate the mission, and if we had interrupted for a moment it's actually better to get back into the mission.
A slightly more aggressive version of this that just went to auto regardless of flight mode has been used for several hundred flight hours on 4.2 without any issues. For actually bringing it in, I left the carveouts if we were landing, or in a Q mode.
> Plane: Support a long failsafe that goes straight to auto

- Tools/autotest/common.py
- Tools/autotest/rover.py
- libraries/AP_HAL/board/chibios.h
- libraries/AP_HAL/board/esp32.h
- libraries/AP_HAL/board/linux.h
- libraries/AP_HAL/board/sitl.h
- libraries/AP_Scripting/AP_Scripting.h
- libraries/AP_Scripting/lua/src/lbaselib.c
- libraries/AP_Scripting/lua/src/loadlib.c
- libraries/AP_Scripting/lua/src/luaconf.h
- libraries/AP_Scripting/lua_bindings.cpp
- libraries/AP_Scripting/lua_common_defs.h
- libraries/AP_Scripting/lua_scripts.cpp
- libraries/AP_Scripting/lua_scripts.h
- libraries/AP_Scripting/tests/modules/test/nested.lua
- libraries/AP_Scripting/tests/modules/test/top.lua
- libraries/AP_Scripting/tests/scripting_test.lua
Also move the global library initialisation out of sandbox method. This way we initialise the lua libs once and then set the reference inside the sandbox, this is similar to what we do with our generated lua bindings.
Split from following PR as requested:
https://github.com/ArduPilot/ardupilot/pull/13660
Current master
```
AP: Lua: Running ./scripts/ahrs-print-home-and-origin.lua
AP: Home - Lat:-353632608.0 Long:1491652352.0 Alt:58409.0
AP: Origin - Lat:-353632608.0 Long:1491652352.0 Alt:58409.0
AP: Lua: Time: 0 Mem: 50777 + 886
AP: Lua: Running ./scripts/ahrs-print-angle-and-rates.lua
AP: Ang R:0.1 P:0.1 Y:-5.9 Rate R:0.0 P:0.0 Y:0.1
AP: Lua: Time: 0 Mem: 50629 + 738
```
With package module loaded
```
AP: Lua: Running ./scripts/ahrs-print-home-and-origin.lua
AP: Home - Lat:-353632608.0 …
```
> Add support for require method in lua

- libraries/AP_BattMonitor/AP_BattMonitor_Analog.cpp
This fixes what appears to be a copy/paste error.
The hwdef erroneously sets the second battery monitor instance up for volt divider and amp_per_volt to use the same definition, it should however use `HAL_BATT2_CURR_SCALE`
> AP_BattMonitor: Fixes the setting of a default parameter for battery 2 defined in hwdef

- libraries/AP_HAL/board/sitl.h
having this default to 1 slows down SITL startup for a lot of people due to the CAN wait for sensor delays. It is easy to enable it when CAN is needed in SITL
> AP_HAL: default CAN_Px_DRIVER to 0 on SITL

- ArduPlane/AP_Arming.cpp
- ArduPlane/AP_Arming.h
- ArduPlane/radio.cpp
This brings plane in line with copter. Currently if you boot with no RC the vehicle will sit in initial mode for a bit and then take failsafe actions. This can be quite annoying because control surfaces will all start moving.
Because the failsafe action of switching to RTL, or starting landing sequence (https://github.com/ArduPilot/ardupilot/issues/23180) currently causes arming to fail this adds a new arming check that RC is present if the failsafe has been skipped by the new path.
> Plane: don't trigger RC failsafe until RC has been received for the first time

- Tools/autotest/sim_vehicle.py
instead of sim_vehicle.py launching both a 14550 and a 14551 UDP fwd stream by default, use only 14550.
- This decreases cpu work on MAVProx and Mission Planner and SITL by not generating and parsing two streams when only 1 is being looked at by the user.
- reduces confusion of GCSs seeing two vehicles with the same SSID (times however many vehicles you have)
- doesn't cause Mission Planner to fetch params twice, at the same time from the same vehicle, at the moment it boots which is both not realistic in most cases and is also likely the reason Mission Planner often gets bogged down trying to fetch params at SITL boot as it's booting up.
Multiple streams can still be launch, of course, using the other argus such as --out.
> Tools: sim_vehicle to only launch one 1455x UDP port

- ArduPlane/Attitude.cpp
- ArduPlane/Plane.h
- ArduPlane/mode.cpp
- ArduPlane/mode.h
- ArduPlane/mode_stabilize.cpp
Follow up to https://github.com/ArduPilot/ardupilot/pull/23513. Now we can move the default and stabilize mode cases down into the mode classes.
> Plane: move to more mode run functions

- libraries/AP_Math/chirp.cpp
- libraries/AP_Math/chirp.h
- libraries/Filter/SlewLimiter.cpp
- libraries/Filter/examples/SlewLimiter/SlewLimiter.cpp
- libraries/Filter/examples/SlewLimiter/SlewLimiterPlot.m
- libraries/Filter/examples/SlewLimiter/wscript
Should always calculate slew limit so it will be logged without having to set large values. Just a re-ordering within the function. Not yet tested.
> Filter: SlewLimiter: always caculate slew limit

- libraries/AP_Mount/AP_Mount_Siyi.cpp
- libraries/AP_Mount/AP_Mount_Siyi.h
This replaces PR https://github.com/ArduPilot/ardupilot/pull/23523 by adding absolute zoom control for the Siyi A8 and ZR10.
The ZR10's API provides absolute zoom control so this was fairly straight forward but the A8 does not meaning we needed to add a slew controller (?) that uses the zoom rate control to get the actual zoom to the target.  The result (on the A8) is slightly slow and jerky but it works.
This has been tested successfully on real hardware (both an A8 and ZR10) and below is some debug output showing the zoom controller in action.
Thanks to @Davidsastresas who did the original PR and wrote the zoom controller for the A8.
> AP_Mount: Siyi supports absolute zoom control

- ArduCopter/Parameters.cpp
- ArduCopter/Parameters.h
- ArduCopter/takeoff_check.cpp
- Tools/autotest/arducopter.py
- libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
- libraries/AP_ESC_Telem/AP_ESC_Telem.h
This extends the minimum RPM check offered  #21499 to check the maximum RPM. Reasons to check the maximum RPM are to cover the case of if a prop has come off and it's overspeeding, or if the ESC is desyncing (this can sometimes be seen as crazy RPM values), or generally just a problem with the RPM data coming in.
This was just tested in SITL, and the autotest script.
> Copter takeoff max rpm check

- Tools/ardupilotwaf/boards.py
- wscript
this adds debug symbolds to the build without enabling other debug code. This is needed for analysing watchdog crash dumps
> waf: added -g option to configure

- libraries/AP_Scripting/applets/RockBlock.lua
- libraries/AP_Scripting/examples/MAVLinkHL.lua
Check if the user has a configured battery monitor before getting battery voltage.
Also fix an undefined variable that crept in (``MAV_SEVERITY_ERROR``)
> AP_Scripting: Check for battery in MAVLinkHL and Rockblock

- libraries/AP_HAL_ChibiOS/hwdef/airbotf4/hwdef.dat
not currently building.
The FLASH_RESERVE_START_KB at 64 means we're short on space on this board
> hwdef: airbotf4: minimize this board

- Tools/ros2/README.md
Improvements to the ROS 2 launch instructions.
Closes https://github.com/ArduPilot/ardupilot/issues/23549
- Correct paths to `ros2.repos` file.
- Improve build and install instructions.
> Tools: update ROS 2 README

- Tools/autotest/common.py
Test failure because we instantly reached the waypoint and did the RTL - so the change-mode-to-auto never saw us in auto mode
> autotest: stop vehicle from entering RTL instantly when it enters auto

- .github/workflows/test_chibios.yml
- Tools/ardupilotwaf/dronecangen.py
- Tools/ardupilotwaf/mavgen.py
- wscript
for 4.5.x we no longer support py2
> waf: require python 3.8.0 or later

- Tools/scripts/mavlink_parse.py
A parser that finds incoming, requestable, and outgoing MAVLink messages for each vehicle. May not indicate full support, but at least shows the messages which are handled in the code.
- Python >= 3.11
- pymavlink installed
- Used to determine which MAVLink dialect a given message is from, and for the set of known messages
- `git` command accessible from terminal
- Used to automatically determine the current branch, for the filename and the markdown code source links
- Can be manually specified instead via the `-b`/`--branch` argument
- Supports generating for a specific vehicle, or all vehicles
- Optionally allows detecting handled MAVLink commands
- Includes breakout of (otherwise undocumented) `NAMED_VALUE_FLOAT` and `NAMED_VALUE_INT` message names
- Optionally allows showing breakout …
> Tools: scripts: create mavlink_parse.py

- libraries/AP_HAL_ChibiOS/AnalogIn.cpp
- libraries/AP_HAL_ChibiOS/AnalogIn.h
when building with --enable-asserts on boards with ADC1 and ADC3 (eg. Holybro H7 based boards) we were triggering asserts on bad ADC index. In order to preserve the asserts (which are good for catching errors) we need to ifdef the relevant calls
> HAL_ChibiOS: fixed asserts in AnalogIn driver

- Tools/autotest/sim_vehicle.py
- waf
- wscript
this should help on old machines where /usr/bin/python has to stay as py2
> waf: use python3 for builds, even if usr/bin/python is v2

- libraries/AP_Motors/AP_MotorsHeli.cpp
- libraries/AP_Motors/AP_MotorsHeli.h
- libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
- libraries/AP_Motors/AP_MotorsHeli_Dual.h
- libraries/AP_Motors/AP_MotorsHeli_Quad.cpp
- libraries/AP_Motors/AP_MotorsHeli_Quad.h
- libraries/AP_Motors/AP_MotorsHeli_RSC.cpp
- libraries/AP_Motors/AP_MotorsHeli_RSC.h
- libraries/AP_Motors/AP_MotorsHeli_Single.cpp
This corrects heli's `get_output_mask` function to only return motors. Currently all outputs being used are returned. Only single heli was correctly returning a servo output mask, dual and quad heli's incorrectly return a motor number mask. 
This is the same issue as https://github.com/ArduPilot/ardupilot/issues/18201, https://github.com/ArduPilot/ardupilot/pull/19202  and https://github.com/ArduPilot/ardupilot/pull/18181
The `get_output_mask` function is used in various places to assign different motor protocols and ESC telemetry. This is really a change of use for the function since it was first added, we have updated it else where but overlooked heli.
> AP_Motors: Heli: get_output_mask return only motors

- Tools/scripts/size_compare_branches.py
this isn't necessary and makes the output more difficult to read
> Tools: size_compare_branches.py: quieten rsync

- libraries/AP_NavEKF2/AP_NavEKF2.cpp
- libraries/AP_NavEKF3/AP_NavEKF3.cpp
This fixes a watchdog on a pixracer that happens when EKF cores fail to allocate
> EKF: fixed watchdog on failure to allocate EKF cores

- libraries/AP_Scripting/docs/docs.lua
- libraries/AP_Scripting/generator/description/bindings.desc
- libraries/AP_Scripting/generator/src/main.c
This allows reading enums and userdata fields from userdata. This allows the two outstanding `EFI_State` fields to become read and write. This should also allow https://github.com/ArduPilot/ardupilot/pull/23640.
This also stops adding a creation function for userdata that is all read only. This remove only the `camera_state_t` creation function. Currently that would not be useable in any case as the creation function is currently `AP_Camera::camera_state_t` which is invalid in lua. If we were to add some writable fields we would have to add a rename so it could be called. fixes https://github.com/ArduPilot/ardupilot/issues/23445
> AP_Scripting: allow getting enum and userdata fields for userdata

- libraries/AP_Camera/AP_Camera.cpp
- libraries/AP_Camera/AP_Camera.h
- libraries/AP_Camera/AP_Camera_Backend.h
- libraries/AP_Camera/AP_Camera_MAVLinkCamV2.h
- libraries/AP_Camera/AP_Camera_Scripting.cpp
- libraries/AP_Camera/AP_Camera_Scripting.h
- libraries/AP_Camera/AP_Camera_SoloGimbal.h
- libraries/AP_Camera/AP_Camera_shareddefs.h
- libraries/AP_Scripting/docs/docs.lua
- libraries/AP_Scripting/drivers/mount-viewpro-driver.lua
- libraries/AP_Scripting/generator/description/bindings.desc
- libraries/AP_Scripting/generator/src/main.c
- libraries/GCS_MAVLink/GCS_Common.cpp
- libraries/RC_Channel/RC_Channel.cpp
- libraries/RC_Channel/RC_Channel.h
This adds support for a camera gimbal to track an image on the video feed.
- GCS_MAVLink sends [CAMERA_TRACK_POINT](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1649), [CAMERA_TRACK_RECTANGLE](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1655) and [CAMERA_STOP_TRACKING](MAV_CMD_CAMERA_STOP_TRACKING) commands to AP_Camera
- AP_Camera gets a new set_tracking() method allowing callers to start tracking a point, a rectangle or stop tracking
- AP_Camera::camera_state and corresponding AP_Scripting's bindings are extended to hold the tracking state
- AP_Scripting's mount-viewpro-driver.lua is enhanced to send the appropriate commands to the ViewPro gimbal
- RC_Channel gets a get auxiliary function, …
> AP_Camera: support image tracking

- libraries/AP_Motors/AP_MotorsHeli.cpp
- libraries/AP_Motors/AP_MotorsHeli.h
- libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
- libraries/AP_Motors/AP_MotorsHeli_Dual.h
- libraries/AP_Motors/AP_MotorsHeli_Quad.cpp
- libraries/AP_Motors/AP_MotorsHeli_Quad.h
- libraries/AP_Motors/AP_MotorsHeli_RSC.cpp
- libraries/AP_Motors/AP_MotorsHeli_RSC.h
- libraries/AP_Motors/AP_MotorsHeli_Single.cpp
- libraries/AP_Motors/AP_MotorsHeli_Single.h
This is an extension to this PR: #23591 (that I have now closed).
This is a basic rework that removes unnecessary virtual functions.  There is no functional change.  Main benefit is to start making the library simpler.  We get the added benefit of approx. 100 b of flash saved.
> AP Motors Heli: Remove/Simplify Unneeded Virtuals

- libraries/AP_DroneCAN/AP_DroneCAN.cpp
- libraries/AP_DroneCAN/AP_DroneCAN.h
- libraries/AP_Logger/AP_Logger.h
- libraries/AP_Logger/LogFile.cpp
- libraries/AP_Logger/LogStructure.h
- libraries/AP_PiccoloCAN/AP_PiccoloCAN.cpp
These servos use a different UAVCAN message than other UAVCAN servos. 
The command format is a linear array (max 17 servos) and status gives info on voltage, current, commanded position, temperature etc. Having commanded position as well as actual position is great for analysing errors
To use you need to set CAN_D1_UC_OPTION=32 to enable use of the Himark servo output protocol
Example logging:
This is the setup on the servos (for SERVO3, idx 2)
This has been successfully test flown with a CUAV-X7 with 5 servos for fixed wing control surfaces
> CAN: support Himark CAN servos

- libraries/AP_Motors/examples/AP_Motors_test/AP_Motors_test.cpp
This fixes up the motors example for the heli, it can then be used to run a input sweep and output the three swash and single tail servo PWM values. This means we can mess about with the motors lib and prove there is no change in output (https://github.com/ArduPilot/ardupilot/pull/23655). With a little more poking about we can get it working for the other heli types as well.
> AP_Motors: test: fix for heli

- libraries/AP_OSD/AP_OSD_Screen.cpp
SITL tested...and discovered a bug in the analog RF backend and in the SITL emulation of it ( #23669 )....flight tested
> AP_OSD: fix format of RF panel and check for out of range

- libraries/AP_DDS/AP_DDS_Client.cpp
@tridge asked for a bug fix in discord:
> small bug in the new pose topic, that sqrt() should be a sqrtf() or sqrtF() so we do single precision for boards that don't have double precision hw
and we prefer * 0.01 to / 100
> AP_DDS: Support single and double precision hardware

- .github/workflows/test_size.yml
Hopefully this fixes... 
Broken since at least https://github.com/ArduPilot/ardupilot/pull/23037 no one noticed till now, so maybe we should just remove the test....
I would be fine with that if we uploaded the elf files from the build so its easy to download and check them locally without having to mess about trying to match up versions to get the same result as the size compare.
> Actions: test_size: fix elf diff for vehicles

- Tools/autotest/arduplane.py
- libraries/AP_Vehicle/AP_Vehicle.cpp
it should be INFO not WARNING as not having an airspeed sensor isn't an issue if it is disabled
see https://discuss.ardupilot.org/t/plane-4-3-stable-release/91727/143
> AP_Vehicle: change no airspeed sensor message

- libraries/SITL/SIM_JSON_Master.cpp
this is due to asprintf doing realloc.
It can be catched with valgrind
> SITL: fix memory leak on multi fcu json sim

- Tools/scripts/configure_all.py
- libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
This allows other scripts to ask the canonical hwdef interpreter for information gleaned from hwdefs.
This will allow us to fix several bugs in various scripts (notably not understanding includes can make things AP_Periphs).
A follow-up branch https://github.com/peterbarker/ardupilot/pull/new/wip/use-chibios-hwdef-lib-for-configure-all shows how we can use this.
This should also allow us to do better in terms of factoring this script.  For example, creating an object to handle the "seen device" code which is exists 4 times.
> hwdef: chibios_hwdef.py becomes a library

- libraries/AP_GPS/AP_GPS.h
- libraries/AP_GPS/AP_GPS_GSOF.cpp
- libraries/AP_GPS/AP_GPS_GSOF.h
Another improvement for the GSOF driver. Added const everywhere possible. (and WARN_IF_UNUSED)
Why? https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#con1-by-default-make-objects-immutable
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#e25-if-you-cant-throw-exceptions-simulate-raii-for-resource-management
> AP_GPS: Add const and WARN_IF_UNUSED to AP_GPS_GSOF

- Tools/ardupilotwaf/chibios.py
When WSL2 runs python.exe to access the windows serial ports, the buffered print() msgs don't print. It relays on the several ```sys.stdout.flush()``` lines in that script.. but there are many more needed. Native systems seem to handle the buffering OK but not when it's crossing the platforms like this. When uploading via WSL, it looks like it hangs when encountering these non-flushed prints in the script
Solution, call ```python.exe -u <filename>``` instead of ```python.exe <filename>``` to force all prints to be unbuffered
> Tools: WSL2 python.exe uploader.py stdout to be unbuffered via -u

- Tools/ardupilotwaf/ardupilotwaf.py
- Tools/ardupilotwaf/chibios.py
New ./waf compile argument --upload-force
Example using a fresh stock CubeOrange with vehicle code on it:
```
./waf configure --board CubeOrange-periph
./waf AP_Periph --upload
```
An error would be shown saying "Firmware not suitable...". Using this new argument allows it:
```
./waf AP_Periph --upload --upload-force
```
NOTE: This does not change the bootloader. You'll need to update that at runtime via the usual method
> Tools: add ./waf --upload-force arg to allow uploader.py to do --force

- libraries/AP_GPS/AP_GPS_GSOF.cpp
- libraries/AP_GPS/AP_GPS_GSOF.h
Another (trivial) GSOF improvement. This variable was set, but never used. The start character is always the same (it's known at compile time). No reason to store it.
> AP_GPS: Remove unused member variable in gsof driver

- libraries/AP_HAL/utility/sparse-endian.h
As mentioned in https://github.com/ArduPilot/ardupilot/pull/23758#discussion_r1191869260, I didn't realize what sparse endian header was for. Once I found the manpage, it was more clear. I drop the link directly into the header here.
> AP_HAL: Add reference to sparse endian manpage

- libraries/AP_HAL_ChibiOS/hwdef/common/spi_hook.h
- libraries/AP_HAL_ChibiOS/sdcard.cpp
this affects boards that share sdcard on the same bus as another SPI device. In this case it was a QiotekZealotH743 where logging stopped
this issue is that the SPI hooks for MMC SPI did not do a DMA channel lock before the SPI device lock. So when the RAMTRON driver on the QiotekZealotH743 which is on the same SPI2 bus as the sdcard did an operation we had a lock order violation
We need to check if this affects 4.4 too ..... checked, it does not affect 4.4
> ChibiOS: fixed a lockup of sdcard on some boards

- libraries/AP_OSD/AP_OSD.h
- libraries/AP_OSD/AP_OSD_Screen.cpp
- libraries/AP_RPM/AP_RPM_config.h
displays main rotor rpm in OSD
> AP_OSD: support for main rotor rpm

- Tools/ros2/ardupilot_dds_tests/ardupilot_dds_tests/time_listener.py
- Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_time_msg_received.py
- libraries/AP_DDS/AP_DDS_Client.cpp
- libraries/AP_DDS/AP_DDS_Client.h
- libraries/AP_DDS/AP_DDS_Topic_Table.h
- libraries/AP_DDS/Idl/rosgraph_msgs/msg/Clock.idl
- libraries/AP_DDS/README.md
- libraries/AP_DDS/dds_xrce_profile.xml
Add a publisher for `rosgraph_msgs/msg/Clock` on topic `/ap/clock`.
ROS 2 nodes use the [`rosgraph_msgs/msg/Clock`](http://docs.ros.org/en/melodic/api/rosgraph_msgs/html/msg/Clock.html) message published on `/clock` to control the behaviour of time accessed via `Node.get_clock).now()` depending on the value of the parameter `use_sim_time`. 
The built-in type `builtin_interfaces/msg/Time` is not usually exposed as a ROS topic, but generally contained inside another message type - either `Clock` or in `Header`. Rather than remove publishing the `Time` message, it has been mapped instead to the topic `ap/time`.
- Publish `builtin_interfaces/msg/Time` to `/ap/time` (renamed from `/ap/clock`).
- Publish `rosgraph_msgs/msg/Clock` to `/ap/clock`.
Launch SITL with the micro ROS agent:
```bash …
```
> AP_DDS: add publisher for rosgraph_msgs/msg/Clock

- libraries/SITL/SIM_I2C.cpp
... not included on SIMOnHardware, for  example
> SITL: guard against LP5562 not being included

- libraries/AP_GPS/AP_GPS_GSOF.cpp
- libraries/AP_GPS/AP_GPS_GSOF.h
* Related to #23743, but I missed this since I didn't realize the buffer was not modified in-place
> AP_GPS: Add missing const to the rest of the headers

- libraries/AP_AHRS/AP_AHRS_Backend.h
we don't need to know the storage, and if you cut enough stuff out then we don't end up transitively including the required header for this.
> AP_AHRS: pre-declare Location object

- libraries/AP_BoardConfig/AP_BoardConfig.cpp
- libraries/AP_BoardConfig/AP_BoardConfig.h
- libraries/AP_BoardConfig/board_drivers.cpp
Added the ability to skip board validation to the BRD_OPTIONS param. This will allow the board to continue on board errors.
> APBoardConfig: Add skip validate board

- Tools/ardupilotwaf/boards.py
- Tools/ardupilotwaf/chibios.py
- libraries/AP_HAL_ChibiOS/hwdef/common/chibios_board.mk
- wscript
debug symbols subtly change the compiler output which can lead to problems with repeatable builds
> AP_HAL_ChibiOS: do not build ChibiOS with debug symbols unless debug build

- libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
- libraries/AP_SerialManager/AP_SerialManager.cpp
No Periphs Were Harmed(tm)
```
Board,AP_Periph
ARK_GPS,*
ARK_RTK_GPS,*
AeroFox-Airspeed,*
AeroFox-Airspeed-DLVR,*
AeroFox-PMU,*
BirdCANdy,*
C-RTK2-HP,*
CUAV_GPS,*
CarbonixF405,*
CarbonixL496,*
CubeBlack-periph,*
CubeOrange-periph,*
CubeOrange-periph-heavy,*
CubePilot-CANMod,*
FreeflyRTK,*
G4-ESC,*
HerePro,*
Hitec-Airspeed,*
HitecMosaic,*
HolybroG4_Compass,*
HolybroG4_GPS,*
HolybroGPS,*
MatekH743-periph,*
MatekL431-Airspeed,*
MatekL431-BattMon,*
MatekL431-DShot,*
MatekL431-EFI,*
MatekL431-GPS,*
MatekL431-HWTelem,*
MatekL431-Periph,*
MatekL431-Proximity,*
MatekL431-Rangefinder,*
MatekL431-bdshot,*
Nucleo-G491,*
Nucleo-L476,*
Nucleo-L496,*
Pixracer-periph,*
f103-ADSB,*
f103-Airspeed,*
f103-GPS,*
f103-HWESC,*
f103-QiotekPeriph,*
f103-RangeFinder,*
f103-Trigger,*
f303-GPS,*
f303-HWESC,* …
```
> Consolidate AP_Periph serialmanager defaults

- libraries/GCS_MAVLink/GCS_MAVLink.h
- libraries/SITL/SIM_RF_MAVLink.cpp
- libraries/SITL/SIM_Ship.cpp
- libraries/SITL/SIM_Ship.h
- libraries/SITL/SIM_Vicon.cpp
- libraries/SITL/SIM_Vicon.h
precedent was set in the mavlink rangefinder; we don't need to re-use SITL buffers for this
mavlink rf and Vicon is tested in autotest.
I tested the ship simulation by hand.
> SITL: stop using mavlink channels for packing messages

- libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
We were incorrectly loading gains for pitch rather than yaw D
Re-tested on my 5" - results in a very tight yaw tune
> Load test gains for correct axis when testing yaw D

- libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
- libraries/AP_Mount/AP_Mount_Siyi.cpp
- libraries/AP_SerialManager/AP_SerialManager.cpp
- libraries/AP_SerialManager/AP_SerialManager.h
Both the [SToRM32 (serial) gimbal driver](https://ardupilot.org/copter/docs/common-storm32-gimbal.html) and [Siyi driver](https://ardupilot.org/copter/docs/common-siyi-zr10-gimbal.html) require the SERIALx_PROTOCOL = 8.
This PR generalises the serial protocol parameter description, enums and baud rate definitions to make it more clear that they apply to both gimbals.  E.g. SERIALx_PROTOCOL = 9 param description has been changed from "SToRM32 Gimbal Serial" to "Gimbal (SToRM32, Siyi)".  I hope this will clear up user confusion as found in [this discussion](https://discuss.ardupilot.org/t/ip-cameras-rtsp-mavlink-support/99893/20).
In a future PR we will change the Alexmos gimbal driver to also use this same serial protocol enum (or perhaps either this one or the previously used enum).
BTW …
> AP_SerialManager/AP_Mount: generalise SToRM32 serial protocol description and enum

- libraries/AP_GPS/AP_GPS_GSOF.cpp
- libraries/AP_GPS/AP_GPS_GSOF.h
The GSOF code hasn't been touched in a while. Before I add support for some new messages and hardware, there are a few things that can be done to improve it. Expect some more (small) PR's. 
Why enum class? https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Renum-class
Per Peter's recommendation, I also removed all the extra `gsof` parts of the variable names, since it's in class scope and won't conflict with global scope. The class and enum names were not complying with the style guide, and are now updated. 
Before names
```c++
struct gsof_msg_parser_t {} gsof_msg;
enum {} gsof_state;
static const uint8_t GSOF_STX = 0x02;
```
After names
```c++
struct Msg_Parser {} msg;
enum class State {};
State state;
static const uint8_t STX = 0x02;
```
> Use enum classes and shorten variable names in GSOF

- AntennaTracker/Tracker.cpp
- ArduCopter/Copter.cpp
- ArduPlane/ArduPlane.cpp
- ArduSub/ArduSub.cpp
- Rover/Rover.cpp
- libraries/AP_Vehicle/AP_Vehicle.cpp
Biggest change here is in Sub; previously ServoRelayEvent's update was called at 3Hz, this moves it to 50 like all the other vehicles.
The estimated max time taken for the calls in the ServoRelayEvent case was different for each of the vehicles here.
Flashed this onto a PixRacer and the notify LED still works.
Also flashed onto a PixHawk and `MAV_CMD_DO_REPEAT_SERVO` still works.
> Move update calls for Notify up to AP_Vehicle

- libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
- libraries/AP_Notify/AP_Notify.cpp
> Use chibios_hwdef to define NOTIFY_LED_OVERRIDE_DEFAULT for periph

- Tools/autotest/common.py
- Tools/autotest/pysim/util.py
- Tools/autotest/rover.py
This is extracted from a larger PR that allows tests to be run in parallel.
When we run tests in parallel the default range of 10 ports between instances can not be enough.  Adding these methods allows that distance to be widened based on the number of threads.
> Tools: use methods to determine port numbers

- .github/workflows/test_ccache.yml
- .github/workflows/test_chibios.yml
- .github/workflows/test_coverage.yml
- .github/workflows/test_linux_sbc.yml
- .github/workflows/test_replay.yml
- .github/workflows/test_scripting.yml
- .github/workflows/test_scripts.yml
- .github/workflows/test_sitl_copter.yml
- .github/workflows/test_sitl_periph.yml
- .github/workflows/test_sitl_plane.yml
- .github/workflows/test_sitl_rover.yml
- .github/workflows/test_sitl_sub.yml
- .github/workflows/test_sitl_tracker.yml
- .github/workflows/test_size.yml
- .github/workflows/test_unit_tests.yml
Set fixed revision for docker container instead of using latest.
That will allow to update without breaking old releases.
> .github: use fixed revision for docker dev containers

- Tools/environment_install/install-prereqs-ubuntu.sh
- Tools/scripts/apj_tool.py
- Tools/scripts/bin2hex.py
- Tools/scripts/board_list.py
- Tools/scripts/build_iofirmware.py
- Tools/scripts/make_apj.py
- Tools/scripts/make_intel_hex.py
- Tools/scripts/param_unpack.py
This allow to test our enviromnents setup scripts when we change them.
They are still run weekly
We are still able to run the test manually
On devenv scipts change, we only run the devenv testing and not the other autotest as they aren't impacted.
Update Debian buster to python3
Install wheel with pip and install setuptools and wheel before all other packages to prevent issue with package compilation and benefit from pre build wheels
Enforce python3 on some build tools to prevent issue if python is a valid command 
Remove old semaphore directory that is unused
> Feature/env Allow environement workflow to run on scripts changes

- libraries/AP_Mount/AP_Mount_Alexmos.cpp
- libraries/AP_Mount/AP_Mount_Backend.cpp
- libraries/AP_Mount/AP_Mount_Backend.h
- libraries/AP_Mount/AP_Mount_SToRM32.cpp
- libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
- libraries/AP_Mount/AP_Mount_Servo.cpp
- libraries/AP_Mount/AP_Mount_SoloGimbal.cpp
Callers are now asking the object for all of r, p and y rather than invoking a special method which has to interrogate the object anyway!
> AP_Mount: move get_bf_yaw to be a method on the object it takes

- ArduPlane/Plane.h
- ArduPlane/mode_loiter.cpp
- ArduPlane/navigation.cpp
The check for the aircraft being lined up for a tangent exit has an early breakout condition if the next waypoint is too close to the loiter circle which can prevent the required ground course to waypoint ever being achieved. This check was using the WP_LOITER_RAD parameter value, not the actual radius being used which can be set differently by the mission plan. If a large value for WP_LOITER_RAD was set and being over-written by the mission plan with a smaller value compatible with the distance to the next waypoint, the aircraft would still exit early.
This bug was encountered when using a loiter to altitude waypoint with tangent exit followed by a landing waypoint. The WP_LOITER_NAV had been set to a large value prior to landing whilst flying in guided mode. The following figure shows …
> Fix early exit from loiter to alt and loiter to time when using large WP_LOITER_NAV values

- .gitignore
- Tools/autotest/logger_metadata/emit_md.py
- Tools/autotest/logger_metadata/parse.py
Add markdown output option for DataFlash log messages, so it can be [used in ArduSub docs](https://docs.bluerobotics.com/ardusub-zola/software/autopilot/ArduSub-4.1/developers/log-messages/).
@Williangalvani
> Tools: logger_metadata: add emit_md

- libraries/AP_BattMonitor/AP_BattMonitor_INA2xx.cpp
- libraries/AP_BattMonitor/AP_BattMonitor_INA2xx.h
this allows for higher current ranges with lower resolution
If the current exceeds this number then the current reading will be zero. The default of 90 matches the previous limit.
> AP_BattMonitor: allow max amps to be configured on INS2XX

- libraries/AP_GPS/AP_GPS_GSOF.cpp
- libraries/AP_GPS/AP_GPS_GSOF.h
Add in new links for all the packets. The old link was dead. 
I think GSOF 2 (pos) is deprecated. It's no longer documented in the API. I can follow up with Applanix to see why.
> AP_GPS: Update GSOF docs with newer links

- libraries/AP_GPS/AP_GPS_GSOF.cpp
The manual says the following: 
https://receiverhelp.trimble.com/oem-gnss/index.html#GSOFmessages_Overview.html?TocPath=Output%2520Messages%257CGSOF%2520Messages%257COverview%257C_____0
```
The receiver allows a maximum of ten GSOF messages to be output.
```
Right now, you could steadily increase the size of `gsofmsgreq` without concern. It is currently length `5`. Now, the compiler prevents you from exceeding the claimed limit in the manual.
> Enforce max of 10 GSOF outputs per the manual via static_assert

- ArduCopter/Parameters.cpp
- ArduCopter/defines.h
- ArduCopter/events.cpp
I've added a "Brake Mode" option, which allows the copter to hover in place (in Brake Mode) if the connection to the GCS is lost while in Auto or Guided flight modes.
When conducting BVLOS operations, it is crucial to maintain control over the drone via the GCS at all times. In the event of a GCS disconnection, the drone switches to Brake mode, halting flight without GCS control. Upon reestablishing the connection, the drone can be returned to Auto mode via the GCS.
In the case where the connection does not recover, the drone will take RTL or Land actions through a battery failsafe.
This feature follows a similar implementation as in the PR #23110, which added a Brake Mode option to the Radio Failsafe.
I tested this in SITL.
> Copter: Add GCS Failsafe Brake option

- ArduPlane/Attitude.cpp
- ArduPlane/mode_qacro.cpp
- ArduPlane/mode_qautotune.cpp
- ArduPlane/mode_qhover.cpp
- ArduPlane/mode_qloiter.cpp
- ArduPlane/mode_qrtl.cpp
- ArduPlane/mode_qstabilize.cpp
This moves the quadplane modes to use run functions fully. Now we have the default case in the base class the VTOL modes can call down to it in tailsitter transition the stabilize function are just moved up to the run function.
Still need to run this through realflight.
> Plane: Quadplane: move modes fully to run function

- .editorconfig
I use neovim as my primary editor, it's started throwing errors recently that `.editorconfig` wasn't valid: `editorconfig: invalid value for option trim_trailing_whitespace: false # these are the correct rules for apm coding standards, but fixing up old files causes git spam. trim_trailing_whitespace must be either "true" or "false"`. This was happening on every file I opened, which was pretty frustrating. This was solvable by just moving the comment to it's own line.
The other change presented here was to swap the final newline. This was causing any file I edited to change the last line, which was just git noise. If we are are fine with these slowly moving to not having the trailing new line then I can drop this.
I'm not an expert on .editorconfig by any means, this was all just an …
> .editorconfig: Update for more standards aware editors

- libraries/AP_Logger/LogStructure.h
This PR changes the formatting of the "SCR" (Script) logging message within the AP_Logger.
Specifically, the "Name" field has been modified to be an instance field.
I tested this in SILT, and I can see the script's name from log viewer in MP.
> AP_Logger: make SCR name field instance

- Tools/scripts/build_binaries.py
From the build server:
File "./build_binaries.py", line 570, in get_exception_stacktrace
ret = "%s\n" % e
File "/usr/lib/python3.8/subprocess.py", line 113, in __str__
if self.returncode and self.returncode < 0:
Tested by running `build_binaries.py`, raising exceptions within the getting of the exception stack trace.
> Tools: build_binaries.py: avoid exception while handling exception

- libraries/AP_NavEKF3/AP_NavEKF3.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
A hardware setup using RTK GPs with a longer than usual time spent static on ground prior to flight ran into an issue where the covariance terms for the IMU delta velocity bias (accelerometer bias) became badly conditioned and the filter diverged in vertical position and velocity.
There is supposed to be a reset that occurs if the delta velocity state variances collapse below a minimum safe value, but this was not working correctly. This has been fixed the minimum allowed value determined based on replay of the log from the problem flight. This ended up being the same minimum safe value of 1E-9 for the delta velocity variance that PX4 uses for their estimator which uses the same underlying equations.
The figures show before [index 0] and after the patch  [index 100] using the default …
> Improve stability of EKF3 covariance calculation

- libraries/AP_Mount/AP_Mount.cpp
- libraries/AP_Mount/AP_Mount.h
- libraries/GCS_MAVLink/GCS_Common.cpp
In reference to #20985. Adds support for GIMBAL_MANAGER_SET_PITCHYAW message listed [here](https://github.com/ArduPilot/ardupilot/issues/20985#:~:text=add%20GIMBAL_MANAGER_SET_PITCHYAW%20message%20support%20(not%20to%20be%20confused%20with%20MAV_CMD_DO_GIMBAL_MANAGER_PITCHYAW))
These other pulls needs merging before it:
#https://github.com/ArduPilot/mavlink/pull/305
> AP_MOUNT: add GIMBAL_MANAGER_SET_PITCHYAW message support

- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
- Tools/autotest/arducopter.py
- Tools/autotest/common.py
This PR prevents a *specific* problem which caused a user's vehicle to fly away.
The user input a bad value to the vehicle in GUIDED mode, which caused the position controller state to become corrupt - bunches of NaNs logged in the dataflash log etc.
The tests included in this PR recreate that user's input, but does not look at other supplied fields - accel, yaw and yaw-rate, all of which could create the same problem.
I left it here because there are other ways to accomplish the same thing - most notably, dropping it on the set_pos_vel_acc methods on guided mode (and making them boolean if they're not already) would also stop bad things getting in from scripting.  IMO we should also add periodic validation of the position controller's state - forcing an internal error and reset if we …
> Copter: Prevent position controller madness caused by bad MAVLink input

- Tools/autotest/default_params/copter-winch.parm
- libraries/RC_Channel/RC_Channel.cpp
This adds the missing 45:Winch Control to the auxiliary switch parameter descriptions for Copter.
I've also added a copter-winch.parm file to slightly ease the SITL testing of the winch.  I've tested this in SITL.
Thanks to ohitstarik for pointing this out in [this discussion](https://discuss.ardupilot.org/t/do-winch-mission-waypoints-not-working-with-daiwa-winch/98946).
> RC_Channel: add winch control to aux switch param description

- Tools/AP_Periph/can.cpp
We consume these at line rate from the receiver, don't allow this to cause unnecessary congestion on the bus, as it may be used for flight critical functions. A more proper solution would be to behave more like the actual AP_ADSB library, and simple rate limit how often we send any updates out to the host device, as well as filtering for distance, but that requires more information then is currently readily available.
This was only compilation tested, as I don't have the appropriate hardware available for testing at the moment (it went on a walk somehow).
> Tools: AP_Periph: Reduce the priority of outgoing ADS-B messages

- Tools/AP_Periph/AP_Periph.cpp
- Tools/AP_Periph/AP_Periph.h
- Tools/AP_Periph/Parameters.cpp
- Tools/AP_Periph/Parameters.h
- Tools/AP_Periph/can.cpp
- Tools/AP_Periph/esc_apd_telem.cpp
- Tools/AP_Periph/esc_apd_telem.h
- libraries/AP_Math/crc.cpp
- libraries/AP_Math/crc.h
This add's support for decoding APD ESC telemetry and forwarding it over UAVCAN. This has been bench tested with some upcoming APD firmware and CubeOrange-periph firmware.
Fletcher 16 is actually a standard CRC, so I added it in AP_Math, rather then keeping it in the periph driver. (And there was some drive by const adding in CRC).
> AP_Periph: add support for APD ESC telemetry

- libraries/AP_BoardConfig/AP_BoardConfig.cpp
on and off were reversed. I have marked this for backport as it affects the safety setup of vehicles and impacts the UI that users see
> AP_BoardConfig: fixed documentation of safety options

- Tools/scripts/run_coverage.py
when a test fails on coverage that return exit code 1 and raise subprocess exception which stop the coverage scripts from running
This catch the exception and allow to continue the coverage gathering
> Tools: continue on coverage test failure

- wscript
Make submodule-sync as part of the distclean. This way devs don't have to fight with weird errors even after distclean due to bad submodule state. Distclean should be a kill all clean state which should include cleaning up submodule states.
> waf: also run Tools/gittools/submodule-sync.sh at distclean

- ArduCopter/Copter.cpp
- ArduCopter/Copter.h
- libraries/AP_Scripting/docs/docs.lua
- libraries/AP_Scripting/generator/description/bindings.desc
- libraries/AP_Vehicle/AP_Vehicle.h
I added is_landing and is_taking_off function to the AP_Vehicle and Copter class to use these in LUA scripting.
These can be used, for example, to specify failsafe behavior during takeoff and landing at LUA.
I tested this in SITL and it works.
> AP_Scripting/Copter: support is_landing and is_taking_off in lua script

- ArduCopter/mode_follow.cpp
- libraries/AP_Follow/AP_Follow.cpp
- libraries/AP_Follow/AP_Follow.h
While In follow mode, Mount also follows the same sysid the vehicle is following.
> AP_Follow: support for Mount following the lead vehicle in follow mode

- libraries/AP_Camera/AP_Camera_SoloGimbal.h
- libraries/AP_Mount/AP_Mount.cpp
- libraries/AP_Mount/AP_Mount.h
- libraries/AP_Mount/AP_Mount_Backend.h
- libraries/AP_Mount/SoloGimbal.h
- libraries/AP_Mount/SoloGimbalEKF.h
- libraries/AP_Mount/SoloGimbal_Parameters.h
- libraries/GCS_MAVLink/GCS.h
Results are as expected:
```
Durandal                       *      *           -32     -32               -32    -32    -32
KakuteH7-bdshot                *      *           -24     -24               -24    -24    -24
MatekF405                      *      *           -40     -40               -40    -40    -40 …
```
> AP_Mount: use switch statement on mount type when creating backends

- libraries/AP_GPS/AP_GPS_UBLOX.cpp
it's a bit confusing named, because it doesn't actually "set" anything - it gets messages from the GPS which are then parsed and responded to based on the received values.
> AP_GPS: add clarifying comment on _configure_config_set method

- libraries/AP_GPS/AP_GPS_GSOF.h
https://ardupilot.org/dev/docs/style-guide.html?highlight=zero+initialization#implicit-zeroing-of-memory
https://en.cppreference.com/w/cpp/language/zero_initialization
Remove flash space by using implict zero'ing
> AP_GPS: Remove gsof zero initialization

- libraries/AP_OSD/AP_OSD_ParamSetting.cpp
Per the title, a number of new serial protocols have been added to [`AP_SerialManager`](https://github.com/ArduPilot/ardupilot/blob/fa800e23e2d05d3051c63b041051368308292ba6/libraries/AP_SerialManager/AP_SerialManager.h#L161), but the labels in `AP_OSD` have not been updated.
> AP_OSD: Add missing labels for new serial protocols

- Rover/Parameters.cpp
- Rover/Parameters.h
- Rover/Rover.h
- Rover/mode.cpp
- Rover/mode.h
- Rover/mode_auto.cpp
- Rover/mode_circle.cpp
- libraries/APM_Control/AR_PosControl.cpp
- libraries/APM_Control/AR_PosControl.h
This adds Circle mode support to Rover which is useful on its own but will also be used as part of a new Rover AutoTune feature.
Enhancements include:
- Added a new ModeCircle class added (mode 9)
- ModeAuto enhanced to support LOITER_TURNS commands
- Auto mode implements wp_bearing, nav_bearing(), crosstrack_error() and get_desired_lat_accel() to properly get the values from the sub mode.  The default implementations always called AR_WPNav which was correct for many sub modes (e.g. RTL) but not others (including this new Circle mode).
- AR_PosControl implements input_pos_vel_target() and input_pos_vel_accel_target() to allow callers to pass in target positions, velocities and accelerations which allows the rover to drive a nearly perfect circle.
Also a couple of drive-by fixes are also …
> Rover: add Circle mode and Auto mode Loiter_Turns support

- libraries/GCS_MAVLink/GCS_Common.cpp
> GCS_MAVLink: remove more compass cal if it is not enabled

- libraries/AP_Scripting/applets/mount-poi.lua
This modifies the mount-poi applet so that it sends CAMERA_FEEDBACK messages to the ground station so that little camera icons appear on the map.  This has been tested in SITL and on a real vehicle.  This new ability is thanks to PR https://github.com/ArduPilot/ardupilot/pull/13660
A couple of questionable things:
1. The CAMERA_FEEDBACK messages is always send to the 1st and 2nd mavlink channel.  This covers most use cases but an improvement might be to use a definition at the top of the script, a parameter or perhaps automatically listen for heart-beat messages
2. The encode and decode messages created by mav-gen (and this PR) are copy-pasted right into the script
related issue: https://github.com/ArduPilot/ardupilot/issues/23897
> AP_Scripting: mount-poi applet sends camera feedback message

- libraries/SITL/SIM_GPS.cpp
Change to use value sematics because then you can use const-return value. 
Now, the time is captured in a documented struct which makes it clearer too.
> SITL: Value Semantics for TOW calc

- Tools/AP_Periph/can.cpp
This was broken by the APD support
> Tools: AP_Periph: fix building of hwesc telem

- wscript
This reverts PR https://github.com/ArduPilot/ardupilot/pull/23898 which led to issue https://github.com/ArduPilot/ardupilot/issues/23913
I've confirmed the reported issue is real by switching between master and Copter-4.3 and confirming that the build fails and that the build directory is not being cleared in master.  After the commit is reverted the build directly is correctly cleared as part of "distclean".
> waf: revert run Tools/gittools/submodule-sync.sh at distclean

- Tools/scripts/size_compare_branches.py
Past this you get source in elf_diff:
This requires the use of `--parallel-copies` - so we have old and new source trees available.  There must also be enough parallel copies to cover the number of tasks - so something like this works:
```
./Tools/scripts/size_compare_branches.py --board=Durandal --vehicle=plane --elf-diff --parallel=2
```
as there are exactly as many tasks as parallel-copies.
> Allow source code to display in size_compare_branches.py elf_diff output

- Tools/autotest/common.py
This avoids some race conditions that we currently avoid with sleeps.
It also improves our diagnostics around timesyncs - moving a failure clause earlier which helps getting to the root-cause of timesync problems.
> Improve autotest mavlink connection resiliency

- Tools/autotest/common.py
- Tools/autotest/pysim/util.py
Useful for disambiguating when running multiple binaries:
> Adjust autotest text output to prefix ArduPilot stdout

- libraries/AP_HAL_ChibiOS/hwdef/VRUBrain-v51/hwdef.dat
out of space for everything, or close to it
some reordering required to keep OSD and synthetic-current definitions happy.
> AP_HAL_ChibiOS: minimize VRUbrain-v51

- Tools/scripts/size_compare_branches.py
- libraries/AP_AHRS/AP_AHRS.cpp
- libraries/AP_AHRS/AP_AHRS.h
- libraries/AP_AHRS/AP_AHRS_External.cpp
- libraries/AP_AHRS/AP_AHRS_External.h
This starts to make all our existing backends inherit from AP_AHRS_Backend - rather than just AP_AHRS_DCM.
Future PRs make SITL and the EKFs backends as well.
> AP_AHRS: make ExternalAHRS an AP_AHRS_Backend

- Tools/autotest/pysim/util.py
these are just accumulating as-is
> autotest: empty buffer after printing prefixed lines

- Tools/autotest/common.py
> autotest: timesync roundtrip after setting parameter

- Tools/autotest/arducopter.py
- Tools/autotest/common.py
- Tools/autotest/pysim/util.py
3 seconds every time we start SITL really adds up.
> autotest: remove pause when starting SITL

- Tools/ardupilotwaf/boards.py
- Tools/scripts/build_ci.sh
- libraries/AP_Common/AP_Common.cpp
- libraries/AP_Common/AP_Common.h
- libraries/AP_ExternalAHRS/AP_ExternalAHRS_LORD.cpp
- libraries/AP_ExternalAHRS/AP_ExternalAHRS_LORD.h
- libraries/AP_HAL/utility/sparse-endian.h
- libraries/AP_Math/AP_Math.cpp
- libraries/AP_Math/AP_Math.h
- libraries/AP_Param/AP_Param.cpp
- wscript
I removed the type pun warnings plaguing our builds. In addition to work @peterbarker did in #23825, the SITL build now compiles without warnings, so I enabled `Werr` in CI to prevent regressions. 
The approach I took is to use `memcpy`. While type punning via `union` could also work in C, it's undefined behavior in the C++ standard.
I tried enabling `Werr` in other places, but there are more compiler warnings that need solving. They can be dealt with in a follow up PR.
Reference: See the example here for `memcpy`, the usage I switched to is exactly in line with it. 
https://en.cppreference.com/w/cpp/string/byte/memcpy
> Remove type pun warnings and enable Werr in g++ SITL CI

- Tools/scripts/build_options.py
- Tools/scripts/extract_features.py
- libraries/AP_Filesystem/AP_Filesystem.h
- libraries/AP_HAL_ChibiOS/hwdef/common/ffconf.h
The new ChibiOS 21.xx supports formatting for SPI connected microSD cards. This enables the feature now for all boards
it is slow to format with a SPI microSD (takes about 15s for a 32G card) but it does work
> ChibiOS: support formatting microSD cards on all boards

- libraries/AP_HAL_ChibiOS/hwdef/common/board.c
- libraries/AP_HAL_ChibiOS/hwdef/common/chibios_board.mk
- libraries/AP_HAL_ChibiOS/hwdef/common/common_extf.ld
- libraries/AP_HAL_ChibiOS/hwdef/common/common_extf_h730.ld
- libraries/AP_HAL_ChibiOS/hwdef/common/common_extf_h750.ld
- libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_mcuconf.h
- libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32H750xx.py
- libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
I have been working on support for a new target (BrainFPV RADIX 2 HD), which is STM32H750 based. The target uses a custom bootloader and the code is stored in an external flash connected via QUADSPI running at 120 MHz.
I found that the CPU load was quite high, about 80% with the default settings for Copter. Some of the time critical code had already been relocated to RAM. To optimize it further, I used a logic analyzer to capture the QUADSPI traffic and then analyzed it to see what functions / symbols are read most frequently within a 1 second period. The number of QUADSPI transactions in 1 second was about 1.1 million, which is quite impressive. I captured data repeatedly and moved functions and symbols to RAM (ITCM, DTCM, flashram). By doing so, I was able to reduce the CPU load for …
> AP_HAL_ChibiOS: Optimizations for external flash targets (H750 etc.)

- libraries/AP_Math/crc.cpp
- libraries/AP_Math/crc.h
- libraries/AP_Math/tests/test_math.cpp
- libraries/AP_RCProtocol/SoftSerial.cpp
- we only need to do one byte, and we can do that faster that __builtin_popcount
- __builtin_parity hardfaults AP_Periph
The last implementation here is the on we're going with:
```
uint8_t popcount = 0;
for (uint8_t i=0; i<8; i++) {
if (byte & 1U<<i) {
popcount++;
}
}
return popcount & 0x1;
```
parity(17)  0.4886 usec/call
```
uint8_t popcount = 0;
for (uint8_t i=0; i<8; i++) {
if (byte & 0x1) {
popcount++;
}
byte >>= 1;
}
return popcount & 0x1;
```
parity(17)  0.4882 usec/call
```
uint8_t popcount = 0;
for (uint8_t i=0; i<8; i++) {
popcount += byte & 0x1;
byte >>= 1;
}
return popcount & 0x1;
```
parity(17)  0.4388 usec/call
```
return 0:
```
parity(17)  0.0400 usec/call
```
return (((byte * 0x0101010101010101ULL) & 0x8040201008040201ULL) % 0x1FF) & 1;
```
parity(17)  0.8058 usec/call …
> Replace __builtin_parity with custom implementation

- Tools/scripts/extract_features.py
- libraries/AP_Filesystem/AP_Filesystem.cpp
- libraries/GCS_MAVLink/GCS_Common.cpp
The mkfs symbol is stil present in ArduPilot even with this feature removed.  The following command found this problem: `./Tools/autotest/test_build_options.py --define-match-glob=AP_FILESYSTEM_FORMAT_ENABLED`
```
Traceback (most recent call last):
File "/home/pbarker/rc/ardupilot/./Tools/autotest/test_build_options.py", line 451, in <module>
tbo.run()
File "/home/pbarker/rc/ardupilot/./Tools/autotest/test_build_options.py", line 396, in run
self.run_disable_in_turn()
File "/home/pbarker/rc/ardupilot/./Tools/autotest/test_build_options.py", line 314, in run_disable_in_turn
self.test_disable_feature(feature, options)
File "/home/pbarker/rc/ardupilot/./Tools/autotest/test_build_options.py", line 188, in test_disable_feature
raise ValueError(error)
ValueError: feature gated by …
```
> Fix feature detection of AP_FILESYSTEM_FORMAT_ENABLED

- libraries/AP_GPS/AP_GPS_SBF.cpp
As pointed out in issue https://github.com/ArduPilot/ardupilot/issues/23613, the ellipsoid height and undulation are calculated incorrectly. This likely occurred because Ardupilot has an opposite definition of undulation as the Septentrio receiver (and virtually all GPS receivers for that matter). Septentrio defines undulation as the distance from the ellipsoid to the geoid with up being positive (geoid is above ellipsoid). Ardupilot defines down as positive. 
This PR reconciles the undulation definition and fixes the height above ellipsoid computed [here](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_GPS/AP_GPS.cpp#L1421).
@tridge, @hendjoshsr71 and/or @BluemarkInnovations
**Platform**
[X] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine
> Fix height above ellipsoid and undulation for SBF GPS

- libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp
The received position needs to be projected forwards to compensate for delay.
> AP_NavEKF3: Fix sign error in position fix delay compensation

- Tools/scripts/size_compare_branches.py
Useful when you want all boards *except* these ones (because they're not compiling on one branch or the other, for example)
> Tools: add --exclude-board=glob to size_compare_branches.py

- libraries/GCS_MAVLink/GCS_Common.cpp
CMD_DO_SET_ROI_NONE support was added recently, but it was only processed if sent as command long. 
QGroundControl allows to set a ROI, and for cancelling that ROI is sending a CMD_DO_SET_ROI_NONE as command int. QGC uses a command int instead of command long because Ardupilot returns the capability flags as supporting command int, and technically CMD_DO_SET_ROI_NONE is a location based command, even though it doesn't use location.
We have support for CMD_DO_SET_ROI processed as command int so I thought it would be better to fix it here rather than in QGC.
> GCS_Common: handle CMD_DO_SET_ROI_NONE for command int packets

- libraries/AP_EFI/AP_EFI_Currawong_ECU.cpp
- Currawong ECU does not report EGT
- Change to report this value as NAN
> AP_EFI: Update EGT for Currawong ECU

- libraries/AP_Mount/AP_Mount_Siyi.cpp
- libraries/AP_Mount/AP_Mount_Siyi.h
The SiYi gimbal when facing upside-down (Put on the table or maybe rover in future) doesn't takes mounting direction into account.
This PULL fixes that by taking advantage of  mounting direction information that zr10 and A8 provides.
> AP_Mount: fix SiYi gimbal upside-down facing not working

- Tools/AP_Bootloader/board_types.txt
> AP_Bootloader: add YJUAV_A6 and YJUAV_A6Nano to board types.

- libraries/AP_HAL_ChibiOS/hwdef/FlywooF405S-AIO/hwdef.dat
- libraries/AP_HAL_ChibiOS/hwdef/MatekF405-TE/hwdef.dat
- libraries/AP_HAL_ChibiOS/hwdef/SuccexF4/hwdef.dat
- libraries/AP_HAL_ChibiOS/hwdef/include/no_bootloader_DFU.inc
- libraries/AP_HAL_ChibiOS/hwdef/speedybeef4/hwdef.dat
- libraries/AP_HAL_ChibiOS/hwdef/speedybeef4v3/hwdef.dat
omit bootloader from ROMFS if the board is low on flash and has a DFU button
> hwdef: save flash on boards with DFU

- libraries/AP_Mount/AP_Mount_Backend.cpp
- libraries/AP_Mount/AP_Mount_Siyi.cpp
This resolves https://github.com/ArduPilot/ardupilot/issues/13815, partially resolves issue https://github.com/ArduPilot/ardupilot/issues/21547 and should also fix the Siyi A8 ROI problem reported by @kellyschrock (see the [Copter-4.4 issues list](https://github.com/ArduPilot/ardupilot/issues/23192)).
The changes include:
1. AP_Mount::set_angle_targets() limits the roll, pitch and (sometimes) yaw angles to be sure they are within the user defined limits (e.g. MNT1_ROLL_MIN/MAX, MNT1_PITCH_MIN/MAX, MNT1_YAW_MIN/MAX).  Note that yaw is only checked when it is in body-frame.  We sadly cannot limit the yaw when it is defined in earth-frame at the moment it is received because the yaw of the vehicle will likely change over time.  Instead the individual backends must enforce earth-frame yaw …
> AP_Mount: implement user defined angle limits (especially for Siyi)

- libraries/AP_GPS/AP_GPS_UBLOX.cpp
- libraries/AP_GPS/AP_GPS_UBLOX.h
this copes with the M10S rejecting multiple-key VALGET calls. We fall back to fetching one at a time
tested on a M10S and a F9P
> AP_GPS: fixed ublox M10S auto-config

- ArduCopter/mode.h
ZigZag mode has takeoff feature.
When I tried to takeoff in ZigZag mode, the error (attached later) has occured.
This change caught the error.
https://github.com/ArduPilot/ardupilot/pull/21158/commits/dbe4873347f92b3d5e9029c357688b11ade51c3f#diff-11eec0f85c4837d179da630ca2869de2df174424ae7b8e15452548c5e404e67f
After the change, I confirmed that the copter can takeoff in ZigZag mode on SITL.
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fd12b001c7f in __GI___wait4 (pid=26691, stat_loc=stat_loc@entry=0x7ffcd1299f48, options=options@entry=0, usage=usage@entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
27	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
#0  0x00007fd12b001c7f in __GI___wait4 …
```
> Copter: add has_user_takeoff in ZigZag mode

- libraries/AP_HAL_ChibiOS/Scheduler.cpp
- libraries/AP_HAL_ChibiOS/Scheduler.h
- libraries/AP_HAL_ChibiOS/hwdef/JFB100/hwdef.dat
This PR replaces https://github.com/ArduPilot/ardupilot/pull/23750 and includes these minor changes from the earlier PR:
1. Renamed definition, function and local variables to be a little more consistent (I think)
2. Removed a call to AP_HAL::millis()
3. changed an "int" to an "int32_t"
4. The external watchdog pin is toggled no faster than 10hz (previously it could be as fast as 20hz)
This has been lightly tested on real hardware.
@jfbblue0922 could you confirm that you're ok with these changes?  Also could you tell me where on the board the external watchdog pin is?
> AP_HAL_ChibiOS/Scheduler: add external watchdog for JFB100

- Tools/autotest/arducopter.py
- libraries/SITL/SIM_PS_LightWare_SF45B.cpp
- libraries/SITL/SIM_PS_LightWare_SF45B.h
This adds some fixes and enhancements to our simulated SF45b 350deg lidar.
- Resolve SITL crash if time_delta_ms is too long
- Correct sample_count calculation (was sending too many samples)
- Sends one reading per 3deg which is closer to real device than the previous 1deg
- Distance max is 53m (was 16m which is far shorter than the real device)
- Returns distance of -1m on failure (instead of 0)
- Sweeps back and forth -190~190 deg (previously wrapped which the real device is not capable of doing)
I've tested this in SITL and below are some screen shots of dataflash logs after a debug message to record individual angles and distances was added.
Here's the real sensor.
Here's the test sensor:
> SITL: simulated SF45b fixes and enhancements

- libraries/AP_RPM/AP_RPM.cpp
- libraries/AP_RPM/AP_RPM.h
- libraries/AP_RPM/RPM_Backend.cpp
- libraries/AP_RPM/RPM_EFI.cpp
- libraries/AP_RPM/RPM_EFI.h
- libraries/AP_RPM/RPM_ESC_Telem.cpp
- libraries/AP_RPM/RPM_ESC_Telem.h
- libraries/AP_RPM/RPM_HarmonicNotch.cpp
- libraries/AP_RPM/RPM_HarmonicNotch.h
- libraries/AP_RPM/RPM_Pin.cpp
dt_avg was using integer division and thus lost some part of the division. Changing the division to float correct this.
The other commit remove a zero assignement that is useless and bring more const.
> Correct RPM_PIN dt

- ArduPlane/Plane.h
- ArduPlane/navigation.cpp
The code had a bug where if GPS fix was lost, the demanded airspeed would be set to the measured or estimated airspeed causing unpredictable variations in the demanded airspeed. This patch prevents the minimum ground speed protection speed up from running if the ground speed undershoot cannot be calculated. This patch extends the range of conditions over which the minimum ground speed functionality can be used by enabling the ground speed undershoot to be calculated when the navigation system is able to estimate velocity.
The bug can be replicated in SITL with the following parameter modifications:
RC7_OPTION = 65 (enables GPS to be 'failed' by setting rc channel 7 to 2000)
MIN_GNDSPD_CM = 500
SIM_WIND_SPD = 5
Set mode to TAKEOFF and wait for pre-arm checks to pass
Arm and wait for …
> Fix ground speed undershoot correction bug

- libraries/AP_Motors/AP_MotorsHeli_Single.cpp
- libraries/AP_Motors/AP_MotorsHeli_Single.h
- libraries/AP_Motors/AP_Motors_Thrust_Linearization.cpp
- libraries/AP_Motors/AP_Motors_Thrust_Linearization.h
This PR includes code from the multicopter motors library that linearizes the DDFP tail rotor thrust and adjusts for battery voltage.  This was tested on an actual heli.
> AP_MotorsHeli: add thrust linearization for ddfp tail rotors

- libraries/AP_HAL_ChibiOS/Scheduler.cpp
works on F7 and H7, but on F7 the resulting crash_dump.bin is only 45k, too small to find the bug
> ChibiOS: get crash dump info on main thread lockup

- libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450/hwdef.dat
```
Board,copter
skyviper-v2450,-528
```
> hwdef: SkyViper doesn't have two batteries; remove code based on that

- ArduCopter/mode.h
This PR removes the has_user_takeoff method from ModeAuto class.
I think that it was redundant and not necessary.
> Copter: remove has_user_takeoff from ModeAuto class (NFC)

- libraries/AP_HAL_Linux/GPIO_RPI.cpp
- libraries/AP_HAL_Linux/RCInput_RPI.cpp
- libraries/AP_HAL_Linux/RCInput_RPI.h
- libraries/AP_HAL_Linux/Util_RPI.cpp
- libraries/AP_HAL_Linux/Util_RPI.h
[PR#22841](https://github.com/ArduPilot/ardupilot/pull/22841) assumes that  int UtilRPI::_check_rpi_version_by_rev() returns values from 0 to 3 which is not the case.
The modification applied made ardupilot wrongly detect RPI and as mentioned [here](https://discuss.ardupilot.org/t/obal-a-simple-linux-based-raspberry-pi-ardupilot-fcb/75479/101?u=mhefny)
I just removed the unnecessary modification.
> HAL_Linux: fix RPI Check

- libraries/AP_HAL_Linux/HAL_Linux_Class.cpp
The wiki barely documents the UART A/B/C mappings anymore (and they're not that intuitive), which is confusing for anyone adopting a Linux board.
This PR updates the Linux HAL to accept `--serialX` options alongside (and in preference to) the older `--uartX`, in the same manner as SITL. This will hopefully avoid other people needing to read the source to figure out why `-B` isn't SERIAL2, then being lead down an APM nostalgia trip!
Also fixed a bug where getopt was missing some of the more recent option additions.
> AP_HAL_Linux: Modernise CLI serial options

- libraries/AP_WindVane/AP_WindVane.cpp
- libraries/AP_WindVane/AP_WindVane.h
I think the SITL process should be enabled only when SITL is used.
> AP_WindVane: Enable SITL when it is selected

- libraries/SITL/SIM_I2C.cpp
object won't exist in that case
> SITL: correct compilation when AP_SIM_IS31FL3195_ENABLED off

- Rover/Parameters.cpp
- libraries/AR_Motors/AP_MotorsUGV.cpp
- libraries/AR_Motors/AP_MotorsUGV.h
... use the singleton instead.
This is extracted from a larger PR which allows Relay and ServoRelayEvents to be compiled out
> Stop taking ServoRelayEvents in constructo for MotorsUGV

- libraries/AP_HAL_SITL/Synth.hpp
I had a lot of missing-declarations errors in Synth.hpp when I did a SITL build.
I added method declarations to run SITL.
> AP_HAL_SITL: Resolve missing-declarations errors

- libraries/AP_RCProtocol/AP_RCProtocol_SBUS.cpp
I did not check the slot IDs, so I disabled the process.
I described the rules for slot IDs.
> AP_RCProtocol: Remove invalid Slot ID checks

- libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
This copes better with 10Hz monitors, or losing a single packet on a 10Hz line. This is setting the threshold down for 5Hz, with some timing jitter. This was discussed with @andyp1per first.
> AP_ESC_Telem: Raise default timeout for the RPM spin check to 210ms

- libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/sport_aerobatics.lua
- libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
only allow trick execution on switch transition to state 2
Also require that get_relative_position_NED_origin() is non-nil
> AP_Scripting: tricks-on-a-switch activation cleanup

- libraries/AC_CustomControl/AC_CustomControl_PID.cpp
- libraries/AC_CustomControl/AC_CustomControl_PID.h
correct error due to changes in PID interface!
> AC_CustomControl: correct error due to changes in PID interface

- libraries/AP_Notify/AP_Notify.h
This was close, but not close enough...
`test_build_options.py` passes everything once this is applied.
> AP_Notify: correct gate on inclusion of profiled_spi enum entry

- Tools/ardupilotwaf/chibios.py
- libraries/AP_HAL_ChibiOS/hwdef/common/chibios_common.mk
this adds a chibios_flags.h which contains the flags we pass to the ChibiOS make, which allows us to have a make level dependency on the flags
this fixes (among other things) the build of copter followed by bootloader for SPRacingH7
> waf: fixed dependency of ChibiOS build on compiler flags

- libraries/AP_Arming/AP_Arming.cpp
M10S (no storage) throws this for a considerable period of time and the wording makes this process sound scary.
> AP_Arming: reword GPS pre-arm failure

- Tools/AP_Periph/adsb.cpp
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
- libraries/GCS_MAVLink/GCS_MAVLink.cpp
- libraries/GCS_MAVLink/GCS_MAVLink.h
- libraries/GCS_MAVLink/GCS_Signing.cpp
Currently we define `MAVLINK_COMM_NUM_BUFFERS` without defining MAVLINK_GET_CHANNEL_BUFFER
This makes the mavlink library statically allocate objects to hold data about messages being received.  Combined this comes to about 300 bytes per value in `MAVLINK_COMM_NUM_BUFFERS`
`MAVLINK_COMM_NUM_BUFFERS` is 5 on our embedded boards.  Our default parameters set mavlink on serials 0, 1 and 2.  So in the default configuration we burn ~900 bytes of RAM on static buffers that will never be used.
This change moves the buffer (and the status object) into the GCS_MAVLink objects, which are dynamically allocated at boot-time according to the user's parameters.  This will stop us burning that 900 bytes, and for each backend the user disables will free up an additional 300 bytes.
Drawbacks here include
- …
> Move mavlink receive buffer into GCS_MAVLINK object

- Tools/AP_Bootloader/board_types.txt
Reserve IDs for CM4PILOT and F405AIO
> AP_Bootloader: Reserve IDs for CM4PILOT and F405AIO

- Rover/mode_circle.cpp
From https://discuss.ardupilot.org/t/rover-boat-quiktune-alpha-testers-wanted/101989/46
The minimum tracking distance for Circle mode doesn't scale for smaller robots and circles.
This PR lowers that limit, allowing for much smaller circles (a few metres radius) to be tracked correctly.
Tested with a real vehicle and a 2m radius circle.
Circle tracking before this patch:
Circle tracking with this patch:
> Rover: Lower minimum circle tracking distance

- libraries/AP_HAL_SITL/UARTDriver.cpp
this will allow the SITL button on cygwin to work with multicast, allowing for complex vehicle interactions between machines
For example, you can do this:
and the simulated vehicle will appear on multicast, along with other vehicles on the same LAN
> HAL_SITL: fixed multicast UDP on cygwin

- Tools/autotest/arducopter.py
- libraries/AP_NavEKF2/AP_NavEKF2_PosVelFusion.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp
The ResetVelocity() function is only supposed to reset XY states, not  Z state. Resetting the Z state for velocity results in a large velocity glitch if a vehicle is descending or ascending when aiding  switches to AID_NONE
this fixes #19386
before fix:
after fix:
> EKF: fixed Z velocity reset on loss of aiding

- libraries/AP_Motors/AP_MotorsHeli_RSC.cpp
`SRV_Channels::set_range(SRV_Channels::get_motor_function(_aux_fn), 1000);`
It passes `_aux_fun` heli_rsc. That is 31. It then incorrectly tries to convert "motor" 31 to a servo function. We take away 8 and then offset by `motor9` (82). 31 - 8 + 82 = 105. (Scripting 12)
The function should just be:
`SRV_Channels::set_range(_aux_fn, 1000);`
But as I say its unneeded anyway, as its set in the servos lib. This is also proved by the fact that it has been working up to now.
> AP_Motors: Heli: remove incorrect set range call

- libraries/AP_Compass/AP_Compass.cpp
- libraries/AP_Compass/AP_Compass.h
- libraries/AP_Compass/AP_Compass_Calibration.cpp
Currently if you have multiple CAN compasses but only use and calibrate the first if that compass ever does not show up at boot it will be replaced by the second. This removes that ability so compasses cannot change ordering unexpectedly. This can happen if the flight controller is powered from USB and the primary compass from battery. 
Because the second compass had not been calibrated its dev-id is never saved, this means the `expected_dev_id` is 0 and it is detected as a replacement compass. 
This can be avoided by setting all to use and calibrating all and then deselecting use for the unwanted compasses.
A alternate solution would be to save all dev-id's in a calibration to "lock" the ordering, however we would then also need to force offsets to 0 for the un-calibrated compasses so …
> AP_Compass: stop CAN auto replacement by default add option to re-enable

- libraries/AP_HAL/RCOutput.h
- libraries/AP_HAL_ChibiOS/RCOutput.cpp
- libraries/AP_HAL_ChibiOS/RCOutput.h
- libraries/AP_HAL_ChibiOS/RCOutput_bdshot.cpp
- libraries/AP_HAL_ChibiOS/RCOutput_serial.cpp
- libraries/SRV_Channel/SRV_Channels.cpp
https://github.com/bird-sanctuary/extended-dshot-telemetry
Requires BLHeli32 32.93 (beta version) and setting ```SERVO_DSHOT_ESC``` to 3
Appears to be working!
> Extended Dshot Telemetry (EDT)

- libraries/AP_Vehicle/AP_Vehicle.cpp
each of the vehicles does a load-defaults-from-files.  Use that fact to ensure any generator backend parameter's defaults are loaded.
Raised as an alternative to https://github.com/ArduPilot/ardupilot/pull/24007
> AP_Vehicle: initialise generator before init_ardupilot

- Tools/scripts/build_options.py
- Tools/scripts/extract_features.py
- libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
- libraries/AP_SBusOut/AP_SBusOut.cpp
- libraries/AP_SBusOut/AP_SBusOut.h
- libraries/AP_SBusOut/AP_SBusOut_config.h
- libraries/SRV_Channel/SRV_Channel.h
- libraries/SRV_Channel/SRV_Channels.cpp
> Add and use AP_SBUSOUTPUT_ENABLED

- libraries/AP_HAL_ChibiOS/Scheduler.cpp
- libraries/AP_HAL_ChibiOS/Scheduler.h
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
This allows recovery from a mutex deadlock due to lock order violation by forcing the release of the mutex that is holding up the main thread.
Without the forced release we would watchdog. This type of deadlock should never happen, but we have had bugs like this in master, for example the bug fixed by this patch which was in master for a short time:
https://github.com/ArduPilot/ardupilot/pull/23982/commits/e795dc1bf1ae2eb4bac325068c8825f7d781ddc8
When the deadlock happens the monitor thread detects it and uses chMtxForceReleaseS() to force the release of the mutex. That has the potential to cause data corruption, but it is better than the alternative of a watchdog
This PR also adds test code to generate a deliberate deadlock
Log message:
```
1970-01-01 10:00:18.122 DLCK {TimeUS : …
```
> ChibiOS: added force mutex release for deadlock recovery

- ArduCopter/motor_test.cpp
- ArduPlane/motor_test.cpp
- libraries/AP_Motors/AP_MotorsHeli.cpp
- libraries/AP_Motors/AP_MotorsHeli.h
- libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
- libraries/AP_Motors/AP_MotorsHeli_Dual.h
- libraries/AP_Motors/AP_MotorsHeli_Quad.cpp
- libraries/AP_Motors/AP_MotorsHeli_Quad.h
- libraries/AP_Motors/AP_MotorsHeli_Single.cpp
- libraries/AP_Motors/AP_MotorsHeli_Single.h
- libraries/AP_Motors/AP_Motors_Class.cpp
- libraries/AP_Motors/AP_Motors_Class.h
This removes the ability for heli to run motor test and adds a warning message "Motor Test: Disabled on heli". It also adds a config check for the other frame types.
> Motors: Heli: remove motor test. 

- Tools/AP_Periph/can.cpp
- libraries/AP_GPS/AP_GPS.cpp
- libraries/AP_GPS/AP_GPS_DroneCAN.cpp
- libraries/AP_GPS/AP_GPS_DroneCAN.h
- libraries/AP_HAL_ChibiOS/hwdef/HolybroG4_GPS/hwdef.dat
- libraries/AP_HAL_ChibiOS/hwdef/common/board.c
- libraries/AP_HAL_ChibiOS/hwdef/common/flash.c
- libraries/AP_HAL_ChibiOS/hwdef/common/flash.h
This fixes the following issues:
- if the RTK base is the 2nd DroneCAN GPS then it couldn't receive RTMStream data from GCS
- the buffer sizes on the GPS uarts were too small for RTCM data to be fully reliable
- increase CAN priortity of MovingBaseline data
- increase CAN buffer size when doing moving baseline
- fixed a power reset issue on the HolybroG4 GPS by setting the NRST_MODE bits in the option registers
This test by Foxtech shows it fixes their issue
> GPS: fixed for RTCM injection

- libraries/AP_RCProtocol/AP_RCProtocol_Backend.cpp
- libraries/AP_RCProtocol/AP_RCProtocol_SUMD.cpp
- libraries/AP_RCProtocol/AP_RCProtocol_SUMD.h
Of particular note this removes the partial SUMH support. This has been broken as far back as 2018, as we only called add_input() if we were in the SUMD or SUMD failsafe cases, which meant SUMH didn't work. This commits to that path, and removes all the 8 bit CRC, SUMH support.
This also refactors a number of things for readability (condensing white space, simplifying guards around debug code). Many of the debugs could probably be removed, but this simplifies it.
This was tested against the RCProtocol example test, and everything there reports a pass. I do not have a real SUMD receiver to test against.
> AP_RCProtocol: Refactor SUMD to remove legacy cruft

- libraries/AP_Common/time.cpp
- libraries/AP_Common/time.h
- libraries/AP_Filesystem/AP_Filesystem_FATFS.cpp
- libraries/AP_GPS/GPS_Backend.cpp
- libraries/AP_RTC/AP_RTC.cpp
- libraries/AP_RTC/AP_RTC.h
RTC isn't required for this to be of use.
> Move mktime implementation out of AP_RTC

- libraries/AP_BoardConfig/AP_BoardConfig.cpp
Thanks to @andyp1per for spotting this.
We have conflicting parameter indexes between `BRD_SER3_RTSCTS` and `BRD_HEAT_LOWMGN` and between  `BRD_SER4_RTSCTS` and `BRD_SD_MISSION`. This is because the higher index params were hiding higher up in the table. This is not caught by CI because we don't have RTS and CTS pins or parameters in SITL. 
`BRD_SER3_RTSCTS` is easy, nothing actually uses it so we can just change the index. 
`BRD_SER4_RTSCTS` is used by four boards: PH4-mini, PH4-mini-bdshot, Swan-K1 and TBS-Colibri-F7. But the RTS CTS setting are rarely changed, so we will just loose the config on those boards. Alternatively we could move `BRD_SD_MISSION`, it hasn't been in that long, but all "high performance" boards would loose the config.
Checked what is using what by running …
> AP_BoardConfig: fix conflicting param indexs

- libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.cpp
- libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.h
This allows DroneCAN battery backends to be reset correctly if were not using the returned SoC. This is needed for devices such as: http://www.mateksys.com/?portfolio=can-l4-bm
This also changes to correctly bounce the battery reset if we are using the provided SoC.
This work is sponsored by ARACE.
> AP_BattMonitor: DroneCAN: allow battery reset if not using CAN SoC

- ArduPlane/quadplane.cpp
this sets up the vfwd integrator more reasonably when we are in POSITION1 stage of VTOL landing. We need to have enough throttle to cope with a headwind, but want it lower when we are at or above our target closing speed so can minimise the amount of pitch up
This also makes the landing_desired_closing_velocity() consistent with the landing speed used in approach, using average of airspeed min and cruise speed if TECS_LAND_ARSPD is not set
Test flown successfully on a MakeFlyEasy Hero with CubeOrange
> Plane: improved fwd throttle during VTOL landing

- Tools/scripts/build_options.py
ran across this while documenting gcs failsafe....brake mode is an optional mode...this adds it to the build options server...extract features already has a regex for it
> Tools:add brake mode to build options

- Tools/autotest/arducopter.py
- libraries/AP_HAL/SIMState.cpp
- libraries/AP_HAL/SIMState.h
- libraries/AP_HAL_SITL/SITL_State.cpp
- libraries/AP_HAL_SITL/SITL_State.h
- libraries/AP_RangeFinder/AP_RangeFinder.cpp
- libraries/AP_RangeFinder/AP_RangeFinder.h
- libraries/AP_RangeFinder/AP_RangeFinder_NoopLoop.cpp
- libraries/AP_RangeFinder/AP_RangeFinder_NoopLoop.h
- libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp
- libraries/SITL/SIM_RF_NoopLoop.cpp
- libraries/SITL/SIM_RF_NoopLoop.h
This adds UART driver for Nooploop TOF sense P rangefinder: https://ftp.nooploop.com/software/products/tof/doc/TOFSense_User_Manual_V2.5_zh.pdf
> AP_RangeFinder: Add driver for NoopLoop rangefinder

- ArduCopter/Copter.h
- ArduCopter/mode.cpp
- ArduPlane/Plane.h
- ArduPlane/system.cpp
- Rover/Rover.h
- Rover/system.cpp
- libraries/AP_Vehicle/AP_Vehicle.cpp
- libraries/AP_Vehicle/AP_Vehicle.h
This adds a new parameter to block mode entry from GCS. This does not block mode entry from any other source. The idea is to prevent GCS mistakes from putting the vehicle into a mode that the pilot is not experienced with or expecting. For example if the GCS operator mean to hit alt-hold but accidentally selected acro. 
This does not prevent entry from any other source, the main other candidate would be RC, but in that case you can just not setup switches for modes you don't want to use. 
There are some modes that it is not allowed to disable, stabilize, alt-hold RTL and land. Since this is only GCS I can see the case for also allowing disabling stabilize and alt-hold, switching into them without coordination with the pilot will also cause issues. 
Unfortunately there are too many modes …
> Copter/Plane/Rover: Add a bitmask parameter to block mode entry from GCS

- libraries/AP_ADSB/AP_ADSB_uAvionix_MAVLink.cpp
Pulled out of #24107 as a standalone. This fixes us spamming the error level status text at 10Hz on ADS-B backends, a behavior I've gotten inflight with a PingRx (on 4.3).
Should be backported to 4.4.
> AP_ADSB: Fix spam of lost transciever message at update() rate

- Tools/AP_Bootloader/board_types.txt
Adds the board ID for RADIX2HD, see #23948
> Tools: Add Board ID for RADIX2HD

- ArduCopter/RC_Channel.cpp
- ArduCopter/RC_Channel.h
- ArduPlane/RC_Channel.cpp
- ArduPlane/RC_Channel.h
- ArduSub/RC_Channel.h
- Blimp/RC_Channel.cpp
- Blimp/RC_Channel.h
- Rover/RC_Channel.cpp
- Rover/RC_Channel.h
- libraries/RC_Channel/RC_Channel.h
- libraries/SRV_Channel/SRV_Channel.h
- libraries/SRV_Channel/SRV_Channel_aux.cpp
- libraries/SRV_Channel/SRV_Channels.cpp
Allows selecting any scaled passthru channel to go to input trim on rc failsafe instead of freezing
Allows pilot controlled gimbals to revert to forward  position while returning  to home
builds off some of @peterbarker work
> Allow scaled passthru to go to trim on rc failsafe

- Tools/autotest/param_metadata/param_parse.py
https://github.com/ArduPilot/ardupilot/pull/24017 added our first direct parameter at the vehicle level `FLTMODE_GCSBLOCK`. This exposed a issue with the param parser always expecting a name. This adds the a name, `VEHICLE`.
Previously we had only had subgroups in vehicle which get the group prefix as the reference name.
> Tools: Param Parse: add reference name to vehicle parameter table

- libraries/AP_BattMonitor/AP_BattMonitor.cpp
> AP_BattMonitor: fix missing INA2xx param descriptions

- ArduPlane/ArduPlane.cpp
- ArduPlane/quadplane.cpp
- ArduPlane/quadplane.h
this fixes a bug where TECS maintains its slow integrator while in a VTOL hover mode in AUTO or GUIDED.
Among other things this affects PAYLOAD_PLACE and DO_VTOL_TRANSITION. In those states the height can change while hovering outside the control of TECS. When TECS regains control in a fwd transition then can lead to a very large height loss or gain until the TECS integrator can catch up
By not running TECS when in these VTOL states we force it to reset when we start needing it again, preventing the integrator issue.
This bug affects 4.4.x as well
Without the fix we get this:
with the fix we get this:
> Plane: fixed TECS state reset in VTOL auto

- libraries/AP_Scripting/applets/revert_param.lua
- libraries/AP_Scripting/applets/revert_param.md
This script implements a easy parameter reversion system to help with manual in-flight tuning. It allows you to do a wide range of manual tuning while flying and if you get in trouble (eg. an oscillation) then you can use a switch to instantly revert all the parameter changes to the values from startup.
> AP_Scripting: added revert_param.lua applet

- libraries/AP_VisualOdom/AP_VisualOdom.cpp
Healthy Methods checks for driver availability.
Healthy checks are performed when a driver is present.
Therefore, it is better to perform driver presence/absence first.
> AP_VisualOdom: Check for driver availability first

- libraries/AP_GPS/AP_GPS.cpp
Tiny patch in preparation for removing some code duplication in here.
```
MatekF405                      0      *           0       0                 0      0      -8
Pixhawk1-1M-bdshot             -8                 0       -8                0      -8     0 …
```
> AP_GPS: check delay_ok in one place

- libraries/AP_Scripting/AP_Scripting.cpp
- libraries/AP_Scripting/AP_Scripting.h
- libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
- libraries/AP_Scripting/docs/docs.lua
- libraries/AP_Scripting/examples/MAVLink_Commands.lua
- libraries/AP_Scripting/generator/description/bindings.desc
- libraries/AP_Scripting/lua_bindings.cpp
- libraries/AP_Scripting/lua_bindings.h
- libraries/AP_Scripting/modules/MAVLink/mavlink_msg_COMMAND_ACK.lua
- libraries/AP_Scripting/modules/MAVLink/mavlink_msg_COMMAND_LONG.lua
- libraries/AP_Scripting/modules/MAVLink/mavlink_msgs.lua
- libraries/AP_Scripting/tests/mavlink_test.lua
- libraries/GCS_MAVLink/GCS_Common.cpp
This adds the ability for scripting to block MAVLink commands, this means we can process a command long or int in the script without AP acking unsupported, or override the default behavior of commands (or just block commands all together).
This also does a little re-work to the existing MAVLink bindings so they work like the rest, from `mavlink.receive_chan` to `mavlink:receive_chan`. This is a breaking change, we could support both as we do for logger, but they have not been in that long.
This also changes the uint32 receive timestamp to return as a uint32 rather than a native int and fixes up the docs. 
I have added a example of receive a user command.
This does bring some generated code into tree for the new example.
> AP_Scripting: add binding to block MAVLink commands

- Tools/autotest/arduplane.py
- libraries/AP_Landing/AP_Landing_Slope.cpp
- libraries/AP_TECS/AP_TECS.cpp
alternate to #23601 that affects only FW autolanding approach speed since a group is working on VTOL approach/speed
> If FW landing speed -1, set to halfway between min and trim aspd; FW only autolands

- libraries/AP_EFI/AP_EFI.cpp
- libraries/AP_EFI/AP_EFI.h
I've run this through test-build-options with no problems
``` …
```
> AP_EFI: move case labels inside ifdefs

- Tools/ardupilotwaf/boards.py
- libraries/AP_GPS/GPS_Backend.cpp
> AP_GPS: use AP_AHRS_ENABLED in place of HAL_BUILD_AP_PERIPH

- libraries/AP_DroneCAN/AP_DroneCAN.cpp
- libraries/AP_DroneCAN/AP_DroneCAN.h
this allows for testing of a fwd motor or control surfaces while not allowing for VTOL ESCs to run. This makes CAN actuators behave the same as direct PWM actuators
> AP_DroneCAN: allow BRD_SAFETY_MASK to work on CAN ESCs and servos

- libraries/AP_HAL_ChibiOS/hwdef/Pixhawk6C/hwdef.dat
Without this the RTS line does an up-down transition on startup that puts Sik radios into bootloader mode
> Pull RTS lines low on Pixhawk6C to avoid glitches on startup

- libraries/AP_Motors/AP_MotorsHeli.cpp
- libraries/AP_Motors/AP_MotorsHeli.h
- libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
- libraries/AP_Motors/AP_MotorsHeli_Dual.h
- libraries/AP_Motors/AP_MotorsHeli_Quad.cpp
- libraries/AP_Motors/AP_MotorsHeli_Quad.h
- libraries/AP_Motors/AP_MotorsHeli_Single.cpp
- libraries/AP_Motors/AP_MotorsHeli_Single.h
```
set_initialised_ok(frame_class == MOTOR_FRAME_HELI);
```
In `AP_MotorsHeli` base class is incorrect because it is used by all heli backends not just single. The correct check is already done in `init_outputs` for each heli backend. This means the after init dual and heli quad are not `initialised_ok` this does not cause issues because we call `init_outputs` continually in `output_disarmed` so the init is set true again almost immediately.
This also removes the unused return of `init_outputs`, it always returned true. This is just a tidy up.
> AP_Motors: Heli: Remove unused init_output return and don't assume single for initialised OK

- libraries/AP_Scripting/applets/VTOL-quicktune.lua
- libraries/AP_Scripting/applets/VTOL-quicktune.md
this limits the amount that rate gains can reduce from the original values in a quicktune. Large reductions in rate gains can be incorrectly triggered by a frame resonance or gust of wind which can result in gains that are dangerously low, which can trigger an angle P oscillation
This PR also fixes QUIK_ENABLE, which was lost in the change to use aux cached values, and fixes lua check errors
> AP_Scripting: added QUIK_MAX_REDUCE to VTOL-quicktune.lua

- ArduCopter/Copter.cpp
- ArduCopter/Copter.h
- ArduPlane/ArduPlane.cpp
- ArduPlane/Plane.h
- libraries/AP_DroneCAN/AP_DroneCAN.cpp
- libraries/AP_Vehicle/AP_Vehicle.h
This implements the new NotifeState.is_landing and Notifystate.is_taking_off flags from PR https://github.com/dronecan/DSDL/pull/34.
> DroneCAN: NofityState msg to include is_landing and is_taking_off

- libraries/AP_HAL_ChibiOS/hwdef/KakuteH7Mini-Nand/defaults.parm
- libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Reads the old filepath in, writes the pre-processed result into the builds directory as `preprocessed_defaults.py`.
The only pre-processing directive understood is `@include FILEPATH`.
This PR also changes `KakuteH7Mini-Nand` to not have a copy of `KakuteH7Mini`'s defaults.parm, but rather include `KakuteH7Mini`'s.  It's build is byte-for-byte identical afterwards.
I've also included a file from /tmp/ into a CUAVv5 build and ensured that the default in there appears after flashing.
```
Hitec-Airspeed      * …
```
> Change chibios_hwdef.py to pre-process defaults files

- Tools/ardupilotwaf/chibios.py
- libraries/AP_HAL_ChibiOS/hwdef/common/malloc.c
this fixes the crash found by @IamPete1 in PR #24106 
the issue was the way scripting used string functions that called down to newlib allocation functions that are not thread safe. Using sbrk based functions on ChibiOS is a really bad idea
> ChibiOS: fixed use of sbrk based allocation in newlib

- libraries/AP_Camera/AP_Camera_Backend.cpp
- libraries/AP_Camera/AP_Camera_Backend.h
- libraries/AP_Camera/AP_Camera_Params.cpp
- libraries/AP_Camera/AP_Camera_Params.h
Tested on SiYI zr10.
**Possible Problems**: It works great if there is no auxiliary fucntions for recording is set. If set then Arm/disarm based start and stop takes precedence. Also you can't stop recording in flight (in Air) without Force disarming i.e. crash the plane :(
May be @rmackay9 @peterbarker you can give a hint how i can solve this suggesting me a different approach.
> AP_Camera: add CAMx_OPTION support for start/stop recording when arm/Disarm

- Rover/mode.h
- Rover/mode_circle.cpp
Circle mode can behave very badly if the user sets the target speed to be very high (for example >10m/s) while leaving the acceleration limits at their defaults (or lower).  Changes include:
1. Speed checked to ensure it does not lead to a lateral acceleration beyond the TURN_MAX_G value (speed is reduced and a warning displayed)
2. Radius checked to ensure it is not below the TURN_RADIUS value (radius is increased if necessary and a warning displayed)
3. Target position, velocity and acceleration are input to the position controller with no input shaping performed.  The input shaping was the main cause of the wild path shown below (perhaps there is still a bug in the Rover's input shaping code)
4. Target acceleration is fixed to include the forward-back acceleration
Below are before and …
> Rover: circle mode safety improvements

- Tools/AP_Periph/AP_Periph.h
- Tools/AP_Periph/adsb.cpp
- Tools/AP_Periph/can.cpp
as discussed on DevCall.  Moved canard_broadcast to be non-static, and simply moved the method.
> AP_Periph: Move ADSB CAN function into adsb.cpp

- libraries/AP_Camera/AP_Camera.cpp
- libraries/AP_Camera/AP_Camera.h
- libraries/AP_Camera/AP_Camera_Backend.h
- libraries/AP_Camera/AP_Camera_MAVLinkCamV2.cpp
- libraries/AP_Camera/AP_Camera_MAVLinkCamV2.h
- libraries/AP_Camera/AP_Camera_Mount.cpp
- libraries/AP_Camera/AP_Camera_Mount.h
- libraries/AP_Camera/AP_Camera_Scripting.cpp
- libraries/AP_Camera/AP_Camera_Scripting.h
- libraries/AP_Camera/AP_Camera_shareddefs.h
- libraries/AP_Mission/AP_Mission_Commands.cpp
- libraries/AP_Mount/AP_Mount.cpp
- libraries/AP_Mount/AP_Mount.h
- libraries/AP_Mount/AP_Mount_Backend.h
- libraries/AP_Mount/AP_Mount_Siyi.cpp
- libraries/AP_Mount/AP_Mount_Siyi.h
- libraries/AP_Mount/AP_Mount_Xacti.cpp
- libraries/AP_Mount/AP_Mount_Xacti.h
- libraries/RC_Channel/RC_Channel.cpp
This corrects the mavlink result codes being sent to the GCS.  Currently we just send through unsupported when there's actually a problem with the command (deserving a DENIED response)
> Add and use SetFocusResult for camera focus commands

- libraries/APM_Control/AR_AttitudeControl.cpp
- libraries/APM_Control/AR_AttitudeControl.h
- libraries/APM_Control/AR_PosControl.cpp
- libraries/APM_Control/AR_PosControl.h
- libraries/AP_Math/vector2.cpp
- libraries/AP_Math/vector2.h
This resolves issue https://github.com/ArduPilot/ardupilot/issues/23989 by zeroing Rover's position controller's velocity controller's I-term in the vehicle's forward-back direction.  The lateral I-term is also limited based on a new pair of steering limit flags from the attitude controller.
This is a good idea because:
- The speed controller already has an I-term so we do not need an other I-term in the higher level velocity controller (in general Leonard recommends that we keep the I-term a the lowest level possible)
- Zeroing out the I-term ensures that it does not get transferred to the vehicle's lateral direction when the vehicle turns at a waypoint (see SITL testing images below).
- By the way, we do need the velocity controller I-term in the lateral direction because this is a …
> Rover: limit velocity controller I-term build-up in forward-back direction

- Tools/ardupilotwaf/chibios.py
while _sbrk isn't used now, this will prevent a repeat of the bug in #24218
> waf: wrap _sbrk to prevent its use

- libraries/AP_BLHeli/AP_BLHeli.cpp
This MSP command is now being request by esc-configurator and causes it to hang if we don't return data. This just returns valid data.
Also gives internal error if an unknown MSP command occurs.
> Add battery status MSP handling to BLHeli

- Tools/scripts/run_luacheck.sh
This allows passing a file name to run just a single file such as:
```
./Tools/scripts/run_luacheck.sh  ./libraries/AP_Scripting/examples/terrain_warning.lua 
```
With no arguments it runs as before.
> Tools: Scripts: run_luacheck: allow passing extra arguments

- libraries/AP_Scripting/AP_Scripting.cpp
- libraries/AP_Scripting/lua/src/ldo.c
this fixes an issue where a lua library function triggers an exception after it does a math operation which changes the floating point registers on M7 MCUs (such as STM32H7). An example is math.random() which calls math_random(), which pre-calculates a double value before checking if the arguments to the call are valid. When it then checks and finds invalid values the exception longjmp does not restore the floating point registers.
An example script which reproduces this error is:
math.random(1,0)
if you run that and then do a "scripting restart" scripting dies
This PR takes a belt and braces approach to fixing the problem:
- it adds the FPU save/restore in the LUAI_TRY() code 
- it avoids the use of FPU registers in the thread loop by changing to O0 optimisation
either change is …
> AP_Scripting: stash and restore FPU register context in LUAI_TRY

- Tools/autotest/autotest.py
this fixes behaviour when --no-configure and --no-build are passed in, causing subsequent test steps to fail rather than proceed with an old binary
> autotest: remove binary before attempting to build it

- libraries/AP_Scripting/applets/RockBlock.lua
- libraries/AP_Scripting/examples/MAVLinkHL.lua
So, turns out QGC uses ``SET_MODE`` instead of ``MAV_CMD_DO_SET_MODE``, so adding support for it here.
> AP_Scripting: Add SET_MODE support for Rockblock lua script

- libraries/AP_CheckFirmware/AP_CheckFirmware.cpp
when we have a bad unsigned firmware we check if it is a good signed firmware. If it is then we should return OK, if not we should return the original error code, otherwise we end up giving a misleading reason for not booting a peripheral
> AP_CheckFirmware: fixed error code for bad firmware

- libraries/AP_Motors/examples/AP_Motors_test/AP_Motors_test.cpp
- libraries/AP_Motors/examples/AP_Motors_test/MotorTestSweep.sh
- libraries/AP_Motors/examples/AP_Motors_test/run_heli_comparison.py
This PR is part of AP_Heli_Motors improvement work.  Tracker here: https://github.com/ArduPilot/ardupilot/issues/23691
This adds a python tool to easily compare the outputs of AP_Motors before and after changes.  To make this work some changes have been made to the AP_Motors_test.cpp to allow for frame_class changes at run time, as oppose to needing to change defines and rebuild.
The output of the script is a series of correlation plots for each heli frame class.  Before the new changes (old) on the y axis and with the changes on x (new).  Red circles are limit cases, Blue X's are non-limit cases.  If we are looking for no changes then everything should be on a straight 45 deg line.
I prefer to inspect via a plot, instead of a completely automated test, as some changes to these plots are …
> AP_Motors_test: Add tool for comparison of changes to heli motors library

- libraries/AP_Motors/AP_MotorsMatrix.cpp
If unsupported by each frame method, the frame name is set to UNSUPPORTED and FALSE is returned in the processing result.
This frame name is tied to FALSE.
Therefore, when the processing result is FALSE, the frame name should be changed to "set to unsupported.
When the setup_deca_matrix method is FALSE, it is not unsupported.
This bug will no longer occur.
> AP_Motors: If frame specification is FALSE, frame name is unsupported

- Tools/environment_install/install-prereqs-mac.sh
this was temporarily removed to allow MacOSX to pass; github's repository seemed to be corrupt somehow
~~Whatever was happening on github seems to have been resolved, judging from the CI results on my own repo.~~  (edit: or, you know, not)
> Tools: reinstantiate MacOSX brew update call

- Tools/AP_Bootloader/board_types.txt
Allocating BL IDs for new mRo AP_Periph boards.
> Tools: Allocate board IDs for M10044 and M10053

- libraries/AP_ADSB/AP_ADSB_Sagetech.cpp
- libraries/AP_ADSB/AP_ADSB_Sagetech_MXS.cpp
- libraries/AP_ADSB/AP_ADSB_uAvionix_UCP.cpp
In the case rad returns -1 `data` will take on the value of 255, which is > 0 so parsing of that byte will be attempted (and we'll continue the loop.... a lot....)
I don't think this can happen in practice on master, but if threads got involved somehow it might happen when ports get stolen by pas-through.
Untested past compilation.
> AP_ADSB: correct bad port read in Sagetech driver

- libraries/AP_Mount/AP_Mount_Xacti.cpp
This fixes the lat, lon, alt and date EXIF data stored in pictures taken by the Xacti camera.
In fact, the two issues are  quite clear when looking at the [DroneCAN definition for the GnssStatus message](https://github.com/dronecan/DSDL/blob/master/com/xacti/20305.GnssStatus.uavcan) and the comments above the get [AP_RTC::get_date_and_time_utc()](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_RTC/AP_RTC.h#L48) method.
This has been tested on real hardware by taking a picture and confirming that the lat, lon, alt and GPS date appear correctly (previously they did not)
> AP_Mount: Xacti fix for gnss format

- Tools/autotest/arducopter.py
- Tools/autotest/common.py
- libraries/AP_HAL/board/sitl.h
- libraries/AP_HAL_SITL/RCOutput.cpp
- libraries/AP_HAL_SITL/RCOutput.h
- libraries/AP_HAL_SITL/Util.cpp
- libraries/SITL/SITL.cpp
- libraries/SITL/SITL.h
- makes this look a lot like the ChibiOS HAL
- moves the state from being in SITL to being in RCOutput (same as in ChibiOS; the safety switch state should never have been in the simulation itself, in the same way that a real autopilot doesn't have a safety state as such.
- adds a simple autotest
.... tested in.... SITL.....
> Make safety switch in SITL affect RC outputs

- libraries/AP_HAL_ChibiOS/hwdef/F35Lightning/hwdef.dat
both boards on our Wiki seem to show boot0 pins
> hwdef: disable bootloader flashing for F35Lightning

- AntennaTracker/GCS_Mavlink.cpp
- AntennaTracker/GCS_Mavlink.h
- Tools/autotest/arducopter.py
- Tools/autotest/common.py
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
An alternative to https://github.com/mavlink/mavlink/pull/1982
```
Durandal                       -24    *           128     120               120    -24    -24
HerePro             24                                                                    
KakuteH7-bdshot                40     *           40      32                40     32     40
MatekF405                      48     *           40      48                48     48     40
Pixhawk1-1M-bdshot             72                 72      72                72     72     72 …
```
> Make many more commands available as COMMAND_INT

- libraries/AP_Scripting/docs/docs.lua
- libraries/AP_Scripting/examples/motor_lost.lua
- libraries/AP_Scripting/generator/description/bindings.desc
this allows a script to take an action on loss of a VTOL motor
> AP_Scripting: added bindings for VTOL motor loss

- libraries/AP_Arming/AP_Arming.cpp
- libraries/AP_Arming/AP_Arming.h
- libraries/AP_OSD/AP_OSD.cpp
- libraries/AP_OSD/AP_OSD.h
- libraries/AP_OSD/AP_OSD_Backend.h
- libraries/AP_OSD/AP_OSD_MAX7456.h
- libraries/AP_OSD/AP_OSD_MSP.h
- libraries/AP_OSD/AP_OSD_MSP_DisplayPort.h
- libraries/AP_OSD/AP_OSD_ParamScreen.cpp
- libraries/AP_OSD/AP_OSD_SITL.h
This will enable a second OSD backend in parallel with the default one.
A check is in place to only allow certain backend combinations, for instance two MSP serial backends are not supported as well as two MAX or SITL backends.
stats and panels are shared between the two instances.
> AP_OSD: added OSD_TYPE2 param to enable a second OSD backend

- libraries/AP_HAL_SITL/UARTDriver.cpp
txspace could change if another thread is involved
> AP_HAL_SITL: remove race in SITL::UARTDriver::_write

- Tools/autotest/pysim/util.py
- libraries/AP_HAL_SITL/SITL_cmdline.cpp
tested as part of https://github.com/ArduPilot/ardupilot/pull/24297
> AP_HAL_SITL: correct parsing of --rate on SITL commandline 

- Tools/autotest/sim_vehicle.py
At least it starts past this patch:
> sim_vehicle.py: roughly fix auto-sysid functionality

- libraries/AP_Mount/AP_Mount_Alexmos.cpp
- libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
- libraries/AP_Mount/AP_Mount_Siyi.cpp
- libraries/AP_Mount/AP_Mount_SoloGimbal.cpp
We dont need to set default mode again in each backend when we already have set  default mode [here](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mount/AP_Mount.cpp#L158). 
Tested on **SiYi zr10**
> AP_Mount: fix setting default mode redundantly in each backend

- Tools/autotest/arducopter.py
- Tools/autotest/common.py
This one is bouncing in CI a bit.
This will probably need some infrastructure change to change speedup within a test in a context-revertible-manner.  As CPUs get faster but scheduling intervals remain the same the chances of timeouts passing on the autopilot increase.
> Tweak timeout on Proximity Avoidance test

- Tools/autotest/arducopter.py
- Tools/autotest/common.py
most commands don't use all the parameters.  Counting through these was painful.
> autotest: use named parameters for send_cmd and run_cmd

- Tools/autotest/arduplane.py
edit: apparently we've previously merged support for terrain-relative-reposition.  Just adding the test now.
Rely on the function we have for mapping from mavlink coordinate frames into our Location::ALT_FRAME.
Fixes both terrain-alt and relative-alt frames.
Adds test for terrain-alt.
Note that the old Plane code here is at odds with the Mission code which also sets the item as relative: https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_Mission/AP_Mission.cpp#L1015
> autotest: add test for relative-terrain missions

- Tools/autotest/autotest.py
- Tools/autotest/common.py
test test.CAN.CANGPSCopterMission needs to use binarues for test.CAN
> autotest: fixed supplementary test prefix

- libraries/AP_Motors/AP_MotorsHeli.cpp
- libraries/AP_Motors/AP_MotorsHeli.h
- libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
- libraries/AP_Motors/AP_MotorsHeli_Dual.h
- libraries/AP_Motors/AP_MotorsHeli_Single.cpp
- libraries/AP_Motors/AP_MotorsHeli_Single.h
- libraries/AP_Motors/AP_MotorsHeli_Swash.cpp
- libraries/AP_Motors/AP_MotorsHeli_Swash.h
- libraries/AP_Motors/examples/AP_Motors_test/AP_Motors_test.cpp
- libraries/AP_Motors/examples/AP_Motors_test/run_heli_comparison.py
Moves a bunch of functionality down into the swash lib and tidies it up a bit. Should be functionally identical although I have not done significant testing yet. 
The only outstanding tidy up of the swash stuff is its use in `get_motor_mask` that is just wrong and should be removed. It should only return actual motors. I will do a PR for that at somepoint but I didn't want to confuse this PR with that issue.
> AP_Motors: Heli: move swash functionality down into swash lib

- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
```
Durandal                       -152   *           -152    -160              -152   -152   -152
HerePro             -208                                                                  
KakuteH7-bdshot                -216   *           -248    -248              -248   -216   -224
MatekF405                      -216   *           -232    -240              -240   -216   -216
Pixhawk1-1M-bdshot             -200               -192    -192              -200   -200   -200 …
```
> GCS_MAVLink: convert to COMMAND_INT to handle MAV_CMD_DO_SET_HOME

- ArduPlane/quadplane.cpp
I was planning quadplane landings like a manned aircraft (downwind, base, and final at 90 degree turns), and found that when on final the plane didn't attempt to get back on the line from the last waypoint to the landing location. This has a couple significant failure modes, mostly the plane could be blown past the desired final line during the turn, but it would never attempt to get back on it, or it could experience strong wind pushing it off of the target line, which resulted in flying a parallel to desired path. This is particularly bad when trying to operate in confined areas in a narrowly controlled manner.
This shouldn't have any impact upon QRTL, and should only apply if we are flying from the previous waypoint in auto. I've flown this a bunch in the simulator, and am planning to …
> Plane: On vtol landings if from a mission perform crosstracking

- ArduPlane/ArduPlane.cpp
- ArduPlane/Log.cpp
- ArduPlane/Parameters.cpp
- ArduPlane/defines.h
> Allow notch frequencies to be logged at full rate in plane

- libraries/AP_HAL_SITL/UARTDriver.cpp
We were returning the number of bytes we were asked to write, not the number we actually wrote.
Removed a redundant clause - writing zero bytes should be a noop.
> AP_HAL_SITL: correct return values on UARTDriver write call

- libraries/AP_Beacon/AP_Beacon_Marvelmind.cpp
constrain the number of bytes read.  Simplify the way bytes are read.
the return value from available() is unsigned...
I can't test this past compilation as there's no simulator, no sample data, and I don't have the equipment.
> AP_Beacon: MarvelMind: avoid potentially reading INT32_MAX bytes of input

- libraries/AP_OpticalFlow/AP_OpticalFlow_Backend.cpp
Tested this in SITL to make sure the answers are the same; I used a rotation of 26 degrees for this testing.
> AP_OpticalFlow: use vector rotate method

- libraries/AP_Logger/AP_Logger.cpp
- libraries/AP_Logger/AP_Logger.h
for getting diagnostics into the code during ddebug fast
This doesn't use any flash until you use it:
```
Board               AP_Periph  blimp  bootloader  copter  heli  plane  rover  sub
Durandal                       *      *           *       *     *      *      *
Hitec-Airspeed      *
KakuteH7-bdshot                *      *           *       *     *      *      *
MatekF405                      *      *           *       *     *      *      *
Pixhawk1-1M-bdshot             *                  *       *     *      *      *
```
> AP_Logger: add Write_NamedValueFloat

- libraries/AP_Arming/AP_Arming.cpp
Rewording metadata...we should not be enticing users to set ARMING_CHECKS to zero...
NFC
> AP_Arming:change metatdata for ARMING_REQUIRE

- Tools/AP_Periph/serial_tunnel.cpp
- libraries/AP_HAL/utility/RingBuffer.cpp
- libraries/AP_HAL/utility/RingBuffer.h
- libraries/AP_HAL_ChibiOS/UARTDriver.cpp
this ensures we have reasonable UART buffer sizes. As blocks are written 520 bytes at a time the default 512 is not reliable
> Periph: make uCenter fw update more reliable

- Tools/ros2/ardupilot_msgs/CMakeLists.txt
- Tools/ros2/ardupilot_msgs/package.xml
- Tools/ros2/ardupilot_msgs/srv/ArmMotors.srv
Add ROS 2 service interface to `Tools/ros2`.
- Defines a ROS 2 service interface for arming motors.
- Pre-requisite for https://github.com/ArduPilot/ardupilot/pull/24145.
> Tools: add custom ROS 2 messages and service interfaces

- libraries/AP_DDS/AP_DDS_Client.cpp
- libraries/AP_DDS/AP_DDS_Client.h
Fix reliable stream buffer size and ensure correct arg passed to `uxr_create_input_reliable_stream` etc.
- Fixes segfault observed in https://github.com/ArduPilot/ardupilot/pull/24155#pullrequestreview-1529549217
When the message payload is larger than supported by the client the agent emits a warning, for example:
```bash
[micro_ros_agent-1] 2023-07-18 21:04:48.463 [RTPS_READER_HISTORY Error] Change payload size of '1068' bytes is larger than the history payload size of '1031' bytes and cannot be resized. -> Function can_change_be_added_nts
```
> AP_DDS: fix reliable stream buffer size

- Tools/autotest/arducopter.py
- libraries/GCS_MAVLink/GCS_Common.cpp
```
Durandal                       -16    *           -24     -24               -24    -24    -24
HerePro             -8                                                                    
KakuteH7-bdshot                -32    *           -8      -8                -8     -40    -32
MatekF405                      -32    *           -16     -8                -16    -32    -32
Pixhawk1-1M-bdshot             -136               -136    -128              -136   -136   -136 …
```
> Handle DO_SET_ROI_NONE conversion from long-to-int rather than directly

- Tools/ardupilotwaf/boards.py
We've had a report of a bad assert from APD:
https://github.com/dronecan/libcanard/commit/1dc4796df6ead87ee6878ba2977ce3d7f637fbae
> DroneCAN: enable libcanard asserts in SITL

- libraries/AP_Scripting/docs/docs.lua
- libraries/AP_Scripting/examples/motor_lost.lua
- libraries/AP_Scripting/generator/description/bindings.desc
this allows a script to take an action on loss of a VTOL motor
> AP_Scripting: added bindings for VTOL motor loss (4.4backport)

- libraries/AP_Scripting/AP_Scripting.cpp
- libraries/AP_Scripting/lua/src/ldo.c
this fixes an issue where a lua library function triggers an exception after it does a math operation which changes the floating point registers on M7 MCUs (such as STM32H7). An example is math.random() which calls math_random(), which pre-calculates a double value before checking if the arguments to the call are valid. When it then checks and finds invalid values the exception longjmp does not restore the floating point registers.
> AP_Scripting: stash and restore FPU register context in LUAI_TRY (4.4 backport)

- ArduPlane/servos.cpp
fixes #24363 
This fixes a momentary bypassing of the set minimum throttle in FBWA/stabilize/acro/training/autotune. `has_valid_input` goes false for a few seconds before the failsafe action kicks in and changes modes. This can lead an ICE engine to stop.
Our throttle handling is very complex, it is next getting near to the top of my list for re-work.
> Plane: fix throttle going bellow min in fbwa RC failsafe

- libraries/AP_Camera/AP_Camera.cpp
- libraries/AP_Camera/AP_Camera.h
- libraries/AP_Camera/AP_Camera_Backend.h
- libraries/AP_Camera/AP_Camera_Mount.cpp
- libraries/AP_Camera/AP_Camera_Mount.h
- libraries/AP_Mount/AP_Mount.cpp
- libraries/AP_Mount/AP_Mount.h
- libraries/AP_Mount/AP_Mount_Backend.h
- libraries/AP_Mount/AP_Mount_Viewpro.cpp
- libraries/AP_Mount/AP_Mount_Viewpro.h
- libraries/RC_Channel/RC_Channel.cpp
- libraries/RC_Channel/RC_Channel.h
This allows users to change the active video feed (aka "lens") using an auxiliary switch.  This is only implemented for the ViewPro backend.
There are also some other unrelated improvements to the Viewpro driver:
1. recording state is taken from the gimbal instead of assuming the start recording is always successful.  This means the state will remain correct in case of SD card failure or when another interface is used to start/stop recording.
2. zoom level, model name and firmware version are retrieved from the gimbal and displayed to the user and reported to the GCS
3. packet structures are filled in all at once as requested by @peterbarker
4. minor capitalisation fix to some enum values
This has been tested on real hardware.
> AP_Mount/RC_Channel: viewpro supports setting active lens

- ArduSub/defines.h
- ArduSub/mode.h
- ArduSub/mode_auto.cpp
- ArduSub/mode_guided.cpp
A new AUTO_YAW mode has been introduced to allow for control of the vehicle's turn rate or yaw rate. This feature is supported in both guided and auto modes.
1. **defines.h**: Defined AUTO_YAW_RATE in the enum.
2. **mode.h**: Declared set_yaw_rate(float turn_rate_dps).
3. **mode_auto.cpp**: Defined set_yaw_rate(float turn_rate_dps).
4. **mode_guided.cpp**: Added an additional case to handle this new yaw mode.
> Sub: Introduced AUTO_YAW_RATE mode and its features.

- ArduSub/Parameters.cpp
- libraries/AP_Motors/AP_Motors6DOF.cpp
This removes the hardcoded `400` and now consumes MOT_MIN/MAX for calculating the range.
fix #16576
> Sub: tweak output function in AP_Motors6DOF

- libraries/AC_AttitudeControl/AC_AttitudeControl_Sub.cpp
- libraries/AC_AttitudeControl/AC_AttitudeControl_Sub.h
This function ensures that the vehicle reaches the target orientation with the desired yaw rate.
Defined MAX_YAW_ERROR = 5 radians. This parameter defines the error between the current and target heading/yaw.
1. Computes the error between current vehicle heading and desired/target heading.
2. Computes the directionality of movement.
3. If the error is greater than MAX_YAW_ERROR, then rotate with desired yaw rate until the target heading is reached.
4. Else, hold the vehicle's orientation.
> Sub: AC_AttitudeControl_Sub: Improved yaw control

- ArduSub/Sub.h
- ArduSub/mode.h
- ArduSub/mode_auto.cpp
- ArduSub/mode_guided.cpp
1. Added a helper function to set desired yaw state while in guided mode.
- Computes the directionality based on the error between current heading and desired heading.
- Created for different cases to handle the incoming yaw commands:
- Target yaw
- Target yaw and yaw rate
- Target yaw rate
- Hold vehicle's current yaw
2. Updated **set_auto_yaw_look_at_heading()** to use yaw_look_at_heading_slew.
3. Moved **set_yaw_rate()** from ModeGuided to ModeAuto.
> Sub: Guided Mode: Helper funtion to set target yaw state

- libraries/AP_DroneCAN/AP_DroneCAN.cpp
- libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.cpp
- libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.h
We were using the values from passed AP_DroneCAN object to AP_DroneCAN_DNA_Server. But the members might not have been initialized if they are out of order.  More specifically the driver_index wasn't initialised and we were registering subscribers to the wrong driver. This lead to the DroneCAN 2nd driver to not receive any packets.
Resolves issue: https://github.com/ArduPilot/ardupilot/issues/24415
> AP_DroneCAN: pass all the variables to AP_DroneCAN_DNA_Server by value

- Rover/Parameters.h
the constructor order comes from the order in the class
> Rover: fixed constructor ordering build error with gcc-12.2

- libraries/AP_DDS/AP_DDS_Client.cpp
- libraries/AP_DDS/AP_DDS_Client.h
- libraries/AP_DDS/AP_DDS_Topic_Table.h
- libraries/AP_DDS/README.md
- libraries/AP_DDS/dds_xrce_profile.xml
* This is the first step for GSOC Cartographer external odometry input
> AP_DDS: Add dynamic TF subscriber support for odometry

- Tools/scripts/extract_features.py
when taking differences between output of this file it is more useful to sort the list regardless of compiled-in/compiled-out.
> Tools: extract_features.py: sort extracted features string into more useful order

- Rover/Rover.cpp
- Rover/Rover.h
- libraries/AC_PID/AC_PID_2D.cpp
- libraries/AC_PID/AC_PID_2D.h
- libraries/APM_Control/AR_AttitudeControl.cpp
- libraries/APM_Control/AR_AttitudeControl.h
- libraries/APM_Control/AR_PosControl.cpp
- libraries/APM_Control/AR_PosControl.h
- libraries/AP_Scripting/applets/rover-quicktune.lua
- libraries/AP_Scripting/applets/rover-quicktune.md
- libraries/AP_Scripting/docs/docs.lua
- libraries/AP_Scripting/generator/description/bindings.desc
- libraries/AP_Vehicle/AP_Vehicle.h
- libraries/Filter/SlewCalculator2D.cpp
- libraries/Filter/SlewCalculator2D.h
- libraries/Filter/SlewLimiter.cpp
- libraries/Filter/SlewLimiter.h
This implements a "QuickTune" for Rovers and Boats based on the VTOL-quick tune method.  This script is meant to be run with the vehicle in Circle mode running above 20% throttle and turning at at least 10 deg/sec.
The axes tuned are:
- Steering Turn Rate controller (ATC_STR_RAT_P, ATC_STR_RAT_I, ATC_STR_RAT_D, ATC_STR_RAT_FF)
- Speed/Throttle controller (ATC_SPEED_P, ATC_SPEED_I, ATC_SPEED_D, CRUISE_SPEED, CRUISE_THROTTLE)
- Position controller's velocity controller (PSC_VEL_P, PSC_VEL_I, PSC_VEL_D)
The tuning method is basically the same as the VTOL-quick tune in that first D is tuned, then P, then I may be set to the P value (if FF isn't set) then finally FF is tuned (and I is set again to be the same as the FF value).  In the case of D and P, the Slew Rate provided by AC_PID is used …
> Rover: quik tune lua script

- libraries/AP_AHRS/AP_AHRS.cpp
- libraries/AP_AHRS/AP_AHRS.h
this comes up over and over....
two alternatives for improvement....the latter commit being suggested by Tim T. and I think I agree....at least it gives the user directions on how to resolve it...
but this is about as clear as you can make it unfortunately since the inconsistency can be from many sources
whichever the group decides on I will remove the other/squash
@peterbarker we need to discuss TIm's idea of automating this page also : https://ardupilot.org/plane/docs/common-prearm-safety-checks.html....I sent you a metadata format proposal
edit: Peter and I have talked at length....there are 3 options:
1. I try to improve the wiki page on prearms....which I have done
2. we try to add metadata to selected cryptic prearms like this and parse to auto update the wiki docs in some …
> AP_AHRS: give clearer prearm messages

- ArduCopter/AP_Arming.cpp
- libraries/AP_Motors/AP_MotorsHeli.cpp
- libraries/AP_Motors/AP_MotorsHeli.h
- libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
- libraries/AP_Motors/AP_MotorsHeli_Dual.h
- libraries/AP_Motors/AP_MotorsHeli_Quad.cpp
- libraries/AP_Motors/AP_MotorsHeli_Single.cpp
- libraries/AP_Motors/AP_MotorsHeli_Single.h
This moves the heli motors pre-arm checks into the motors pre-arm method. This removes a heli specific code path from copter. All checks are maintained, param checks are moved across, frame type checks come from the base class arming check that motors have "initialised_ok". 
This also removes the "RSC control mode change failed" from all heli backends, this is sent at loop rate and is extremely spammy. There is a base class `AP_MotorsHeli` arming check for RSC mode that warns of the same issue.
Finally this changes copter to run several pre arms at once so the failure messages all get seen, currently you have to get past the "Motor Interlock Enabled" pre-arm before you will see the motors issues. Now you get both failures reported at once. 
I have test by setting each parameter …
> AP_Motors: Heli move parameter checks into pre-arm check method. 

- libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
- libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.h
The heli flags `limit_roll`, `limit_pitch`, `limit_yaw` and `do_piro_comp`  are not used, this removes them.
This also moves `integrate_bf_rate_error_to_angle_errors` method from public to private as it should only be used internally.
> AC_AttitudeControl: Heli: remove unused code

- Tools/autotest/arducopter.py
- libraries/GCS_MAVLink/GCS_Common.cpp
```
Board,AP_Periph,blimp,bootloader,copter,heli,iofirmware,plane,rover,sub
Durandal,,-48,*,-24,-16,,-24,-48,-48
HerePro,-72,,,,,,,,
Hitec-Airspeed,*,,,,,,,,
KakuteH7-bdshot,,-48,*,-48,-48,,-48,-48,-48
MatekF405,,-48,*,-48,-48,,-48,-48,-48
Pixhawk1-1M-bdshot,,-8,,-8,0,,-8,-8,-8
f103-QiotekPeriph,*,,,,,,,,
f303-Universal,*,,,,,,,,
iomcu,,,,,,*,,,
revo-mini,,-72,*,-48,-48,,-48,-72,-72
skyviper-v2450,,,,-16,,,,,
```
> GCS_MAVLink: use long-to-int conversion code for SET_ROI_SYSID

- libraries/AC_Fence/AC_Fence.cpp
- libraries/AC_Fence/AC_Fence.h
- libraries/AC_Fence/AC_PolyFence_loader.cpp
- libraries/AC_Fence/AC_PolyFence_loader.h
this allows for treating total inclusion area as union of all inclusion areas. This is useful for:
- circles with corridors between them
- a fence for each flying site all loaded at once
- temporary addition of an extra area to a complex fence
Note that FENCE_OPTIONS is plane only, so this change only impacts planes
> AC_Fence: added option bit for union of inclusion areas

- ArduCopter/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.cpp
- Blimp/GCS_Mavlink.cpp
Also correct the error codes this command might return in both Plane and Copter.
Tested in SITL, both command-int and command-long still work for Copter and Plane, and the correct error codes are returned both in the compiled-out case and the bad-parameter case.
> Use CMD_LONG conversion for DO_FOLLOW commands

- libraries/AP_HAL_ChibiOS/hwdef/common/stm32f47_mcuconf.h
- libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_mcuconf.h
- libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
this was already done on many (most?) boards, and greatly reduces DMA sharing which improves performance of UARTs. This changes the default to no DMA on I2C
this is an alternative to #24454  which works on a lot more boards
> ChibiOS: disable DMA on I2C on F7 and H7 by default (4.4 backport)

- Tools/ardupilotwaf/boards.py
- wscript
Before this fix:
```
pbarker@fx:~/rc/ardupilot(master)$ CXX=g++-10 CC=gcc-10 ./waf configure --board=sitl | grep Werror
Enabling -Werror                         : yes 
pbarker@fx:~/rc/ardupilot(master)$ 
```
(wrong as 11.3.0 is the only whitelisted compiler; this is actually lying with a bad message, it's not really enabled)
```
pbarker@fx:~/rc/ardupilot(master)$ CXX=g++-11 CC=gcc-11 ./waf configure --board=sitl --enable-Werror | grep Werror
Enabling -Werror                         : no 
pbarker@fx:~/rc/ardupilot(master)$ 
```
This message is correct, it's not enabling it, even 'though it should.  The option `--disable-Werror` is set to true in the waf config by default.
After this fix:
```
pbarker@fx:~/rc/ardupilot(pr/werror-cleanup)$ g++-10 --version
g++-11 --version
g++-12 --version …
```
> waf: tidy interpretation of -Werror

- Tools/scripts/build_options.py
- Tools/scripts/extract_features.py
saves 4.1kB when disabled
I've run this through `./Tools/autotest/test_build_options.py --board=CubeOrange --define-match-glob='*SLCAN*'`
> Tools: build_options.py: add SLCAN to build options

- Tools/AP_Periph/AP_Periph.h
- Tools/AP_Periph/can.cpp
- Tools/AP_Periph/serial_tunnel.cpp
I'd like to use `ins` for inertial sensor.
> AP_Periph: rename ins locals to avoid conflict with ins member variable

- libraries/AP_Scripting/applets/RockBlock.lua
- libraries/AP_Scripting/examples/MAVLinkHL.lua
``battery:capacity_remaining_pct(0)`` returns nil in some cases, so just return 0 for the Rockblock and MAVLinkHL scripts if that's the case.
> AP_Scripting: Account for nil battery in Rockblock and MAVLink_HL scripts

- libraries/AP_Mount/AP_Mount_Viewpro.cpp
non-trivial designators not implemented
Closes https://github.com/ArduPilot/ardupilot/issues/24444
I have only tested that compilation completes on g++-7.5.0
> AP_Mount: correct ViewPro compilation under g++-7.5.0

- libraries/AP_Mount/AP_Mount_Params.cpp
When we merged the Viewpro cpp driver (PR https://github.com/ArduPilot/ardupilot/pull/24259) I forgot to update the MNT1_TYPE parameter description
> Mount: type param desc gets Viewpro

- libraries/AP_CANManager/AP_SLCANIface.cpp
- libraries/AP_HAL_ChibiOS/UARTDriver.cpp
SLCAN broke when we moved to the unified AP_HAL locking system for  UARTs. The SLCAN code relied on the fact that the thread owner check was not done for the read_locked() path. Now that we have a higher level consistent API that check is done and SLCAN broke
> CAN: fixed SLCAN

- libraries/AP_BattMonitor/AP_BattMonitor.h
Reserving an ID for a Battmonitor type which reads the analog value from an I2C ADC IC.
Replaces https://github.com/ArduPilot/ardupilot/pull/24350 which is having CI problems and I can't force-push.
> AP_BATTMonitor: Reserve ID 28 for AD7091R5  I2C ADC

- libraries/AP_AHRS/AP_AHRS.cpp
- libraries/AP_AHRS/AP_AHRS.h
The AHRS functions get_relative_position_NED_home() and get_relative_position_NE_home() should directly use home, not go via the origin.
The difference this makes is for planes without a compass. The origin isn't set by the EKF until "using GPS", but the current location and home location is known. This matters for FENCE_AUTOENABLE=3 without a compass. If going via the origin arming is refused with a failure to get position. When using home for the calculation you can arm with fence enable.
> AHRS: fixed relative home functions not to go via origin

- Tools/scripts/size_compare_branches.py
we don't have a hardware definition for this
> size_compare_branches.py: blacklist build of RADIX2HD bootloader

- Tools/autotest/arducopter.py
This removes unnecessary try/except blocks from the copter GSF autotest which leads to clearer output if the test fails.
> autotest: remove pointless try/except block in GSF test

- libraries/AP_RobotisServo/AP_RobotisServo.cpp
This fix probably reflects the original intention of the code author, because without it delays set in detect_servos() are ignored. Without this fix Dynamixel XC330-T288-T does not start and enters something like a "soft bricked" state (no errors reported, but not responding to any commands). This adds a delay after ping messages so that servos have time to respond to the pings and are ready to be configured further.
> AP_RobotisServo: fix delay after subsequent Robotis servo detections

- ArduPlane/Plane.h
- ArduPlane/altitude.cpp
- ArduPlane/navigation.cpp
- libraries/AP_Terrain/AP_Terrain.cpp
- libraries/AP_Terrain/TerrainGCS.cpp
this fixes a bug where a change of home altitude would cause a sudden height demand change. This copes with 3 situations:
- flying with AMSL alt demand. Changing home altitude makes for no change
- flying with AGL alt demand. Changing home altitude requires update of next_WP_loc
- flying with home relative alt demand. Changing home altitude changes demand at end of current navigation leg
> Plane: cope with home altitude change while navigating

- ArduPlane/Attitude.cpp
- ArduPlane/Log.cpp
- ArduPlane/Plane.h
- ArduPlane/mode.cpp
- ArduPlane/mode.h
- ArduPlane/mode_acro.cpp
- ArduPlane/mode_manual.cpp
- ArduPlane/mode_training.cpp
- ArduPlane/servos.cpp
Some more rudder output tidying. This removes the `steering_control` struct and instead outputs directly to the `k_steering` and `k_rudder` servo output functions as we do for roll/pitch/throttle.
> Plane: output rudder and steering directly removing steering_control struct

- libraries/AP_Camera/AP_Camera.cpp
- libraries/AP_Camera/AP_Camera.h
- libraries/AP_Camera/AP_Camera_Backend.cpp
- libraries/AP_Camera/AP_Camera_Backend.h
> AP_Camera: add time based triggering support

- Tools/environment_install/install-prereqs-ubuntu.sh
`Tools/autotest/pysim/util.py` requires `screen` for GDB; it doesn't support any other terminal types, yet screen wasn't installed by the setup scripts. 
In the future, it would be great for autotest to make use of other terminal types such as `tmux`, which is what I prefer, and conveniently also supported in `Tools/autotest/run_in_terminal_window.sh`
> Tools: Add missing GNU screen that's required for autotest

- Tools/autotest/pysim/util.py
- Tools/autotest/run_in_terminal_window.sh
screen doesn't start the process in the current working directory
> autotest: fixed using GNU screen for opening gdb

- libraries/AP_HAL_ChibiOS/hwdef/KakuteH7/hwdef.dat
these are thge default values, and KakuteH7 isn't minimized
```
Board     copter
KakuteH7  -16
```
> hwdef: remove un-needed lines in KakuteH7 config

- libraries/AP_Scripting/generator/src/main.c
This fixes a bug for depends on userdata fields. We don't currently have any uerdata items with no feilds and a depends, so there is no change in generated output with the current bindings, this is needed for https://github.com/ArduPilot/ardupilot/pull/24429
> AP_Scripting: generator: fix dependancy start and end miss-match

- libraries/AP_Motors/AP_MotorsHeli_Single.cpp
> AP_Motors: correct metadata for H_DDFP_SPIN_MIN param

- libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/README.md
- libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/hwdef.inc
- libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus/README.md
This maps the same change onto CubeOrange that we have for CubeBlack, which allows you to use the EXTERN_DRDY and !EXTERN_CS pins as ADC pins. This is generally useful as I have carrier boards which map this out and use it, and the usage of the bus as SPI is strongly discouraged/not desired. I've validated this on my carrier board here.
@bugobliterator @proficnc any concerns with bringing this change in by default, so that we don't have to maintain a custom hwdef for the feature?
> AP_HAL_ChibiOS: CubeOrange map EXTERN_DRDY and !EXTERN_CS to ADC

- libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
- libraries/AP_ESC_Telem/AP_ESC_Telem.h
- libraries/AP_ESC_Telem/AP_ESC_Telem_Backend.h
The primary target here is to close a window where after time wraps we would ignore the last reported RPM data even if it was valid (such as in the are_motors_running function). The secondary thing this helps us with is that by zeroing out the time we can ensure that if we lose telemetry after wrapping around we don't have a window of time where we consider it to be valid again.
This PR is worth reviewing in separate commits. The second commit is a combination of me kibitzing, and attempting some drive by improvements. They're detailed in the commit message and should be reviewed carefully.
Thus far this has been run through the autotest sequence, but needs to be tested on real hardware still. I'm hoping to get back to that shortly, and do some explicit testing of the behavior on wraps.
> AP_ESC_Telem: Improve handling of time wrap with RPM data

- libraries/AP_BattMonitor/AP_BattMonitor_Logging.cpp
- libraries/AP_BattMonitor/LogStructure.h
Currently we may have a sensor not working in the GCS because its unhealthy, but seemingly working fine in the log since health is not logged.
> AP_BattMonitor: add health logging

- libraries/AP_Networking/AP_Networking_ChibiOS.cpp
Builds using the HAL_GPIO_ETH_ENABLE pin were broken during the recent AP_Networking_ChibiOS refactor. Simple fix.
> AP_Networking: fix build for periph

- libraries/AP_Compass/AP_Compass.h
- libraries/AP_Compass/AP_Compass_Calibration.cpp
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
```
+ column -ts, /tmp/some.csv
Durandal                       -88    *           -88     -88               -88    -88    -96
KakuteH7-bdshot                -40    *           -32     -40               -40    -32    -32
MatekF405                      -8     *           -16     -8                -16    -8     -8
Pixhawk1-1M-bdshot             -16                -16     -16               -16    -16    -16 …
```
> Allow compass mag cal command to come in as COMMAND_INT

- ArduCopter/config.h
- ArduCopter/mode.h
- ArduCopter/mode_auto.cpp
- libraries/AP_HAL/AP_HAL_Boards.h
- libraries/AP_HAL_ChibiOS/hwdef/include/minimize_features.inc
This is primarily a Copter patch.
Had to rename `NAV_GUIDED` to `AC_NAV_GUIDED` to avoid affecting Sub, which turns that on on all boards.
No change in compiler output:
```
Pixhawk1-1M-bdshot             64                 64      72 …
```
> Eliminate MINIMIZE_FEATURES define

- ArduPlane/mode.cpp
One-liner: This PR fixes a bug that leads to the plane crashing while using offboard guidance and switching between modes.
This PR resets the plane guided state `target_alt_time_ms` field on mode switch. This field is not currently being reset to its [initialized](https://github.com/ArduPilot/ardupilot/blob/c99b5e5d47d3d891f0d77a2bf026c5bae588e06c/ArduPlane/Plane.h#L537-L542) value on [mode enter](https://github.com/ArduPilot/ardupilot/blob/c99b5e5d47d3d891f0d77a2bf026c5bae588e06c/ArduPlane/mode.cpp#L57-L63). The other guided state fields are reset to their [initialized](https://github.com/ArduPilot/ardupilot/blob/c99b5e5d47d3d891f0d77a2bf026c5bae588e06c/ArduPlane/Plane.h#L537-L542) values on [mode enter](https://github.com/ArduPilot/ardupilot/blob/c99b5e5d47d3d891f0d77a2bf026c5bae588e06c/ …
> Plane: reset guided target altitude time on mode enter

- libraries/AP_GPS/AP_GPS.cpp
this removes some duplicate code and simplifies the flow of control
Will prevent a bug if we ever do blended on a periph
``` …
```
> AP_GPS: tidy is_healthy calculations

- libraries/AP_GPS/AP_GPS.cpp
- libraries/AP_GPS/AP_GPS_ERB.h
- libraries/AP_GPS/AP_GPS_MAV.cpp
- libraries/AP_GPS/AP_GPS_MAV.h
- libraries/AP_GPS/AP_GPS_SBF.h
- libraries/AP_GPS/AP_GPS_SBP.h
- libraries/AP_GPS/AP_GPS_config.h
- libraries/AP_GPS/GPS_Backend.cpp
- libraries/AP_GPS/GPS_Backend.h
```
Durandal                       0      *           0       0                 0      0      0
MatekF405                      0      *           0       0                 0      0      0
Pixhawk1-1M-bdshot             0                  0       0                 0      0      0
f303-Universal      -72 …
```
> AP_GPS: avoid use of mavlink_channel_t when GCS not compiled in

- ArduPlane/events.cpp
currently a parachute fs in a throttle controlled mode results in the motors remaining on.....possible parachute tangle...this disarms if parachute FS is activated
> Plane:disarm on parachute release FS

- ArduCopter/GCS_Mavlink.cpp
Tested by using breakpoints with the existing autotest suite,
The code in the base class does exactly what Copter is doing here, so this clause is entirely redundant.
> Copter: rely on magic COMMAND_INT transform for MAV_CMD_DO_PAUSE_CONTINUE

- libraries/AP_Camera/AP_Camera_Backend.cpp
- libraries/AP_Camera/AP_Camera_Backend.h
- libraries/AP_Camera/AP_Camera_Logging.cpp
- libraries/AP_Camera/AP_Camera_Mount.cpp
- libraries/AP_Camera/AP_Camera_Params.cpp
- libraries/AP_Camera/AP_Camera_Params.h
- libraries/AP_Mount/AP_Mount.cpp
- libraries/AP_Mount/AP_Mount.h
This adds a new parameter, CAMx_MNT_INST to allow users to specify which mount the camera is in.  This is useful in numerous situations including allowing the correct mount angles to be logged at the moment a picture is taken.
> AP_Camera: add support for the user to specify which gimbal each camera is in

- Tools/autotest/common.py
- libraries/SITL/SIM_GPS.cpp
- libraries/SITL/SIM_GPS.h
Here's the first draft of the GSOF Sim. A few fields aren't done, mainly the bitfields, or fields I don't know how to populate. It does the required data so far.
Tested in GDB, no crashes (yet). This should be a great tool to refactor the GSOF driver and verify it doesn't break anything. 
Doing this testing exposed #23842. There are other vulnerabilities I have found, mainly the `valid` flag is not safe, but nothing to crash it (yet). 
Please provide any initial feedback on any of the TODO's or any other improvements you see.
Thanks to @peterbarker and @tridge for the suggestion to make this; I learned a ton! 
1. Use sim_vehicle and set the following params
```
sim_vehicle.py  -v Copter -DG
param set SIM_GPS_TYPE 11
param set GPS_TYPE 11
```
OR, break on the GSOF driver like so:
``` …
```
> Trimble GSOF GPS Simulator for SITL

- libraries/AP_TemperatureSensor/AP_TemperatureSensor_MCP9600.cpp
This PR does two things:
- adds support for the MCP9601 (just checks the WHOAMI value)
- removes some debug
- checks the status register for new data availability before reading new data to prevent reading stale data. This is also useful to gracefully handle error conditions where stale data remains available forever.
> AP_TemperatureSensor: add support for MCP9601

- libraries/AP_Arming/AP_Arming.cpp
when a user forced armed and had FENCE_AUTOENABLE=3 for enable on arming then the fence did not enable
> AP_Arming: fixed auto-enable of fence with forced arm

- .gitignore
- .vscode/extensions.json
Allow you to add extensions to staging without git complaing it's in the vscode folder
This extensions lets you render the diagrams I made in the AP_DDS/README.md inside VSCode liek so:
> .vscode: Recommend mermaid extension for rendering mermaid diagrams in markdown

- libraries/AP_DroneCAN/AP_DroneCAN.cpp
- libraries/AP_DroneCAN/AP_DroneCAN.h
This adds a 0.1 sec timeout while waiting for a response after attempting to get or set a parameter on a device/node which resolves issue https://github.com/ArduPilot/ardupilot/issues/24541
I've also attempted to improve the comments around the methods involved.
This has been tested on real hardware using a Xacti camera/gimbal which may fail to respond to get/set parameter requests if it is busy handling the latest gimbal target message.  Without this change once the device failed to respond, AP would never send another get/set request.
I have also lightly tested with a Here4 DroneCAN GPS to confirm that it still works and that parameters can be retrieved.
This was written after a discussion with @bugobliterator.
One small thing that I'm not completely happy with is that we assumption …
> DroneCAN: add get/set param timeout

- Tools/scripts/battery_fit.py
- libraries/AP_BattMonitor/AP_BattMonitor_INA239.h
- libraries/AP_BattMonitor/AP_BattMonitor_INA2xx.h
- libraries/AP_BattMonitor/AP_BattMonitor_LTC2946.h
- libraries/AP_Scripting/applets/BattEstimate.lua
- libraries/AP_Scripting/applets/BattEstimate.md
This implements a simple model based SoC estimator for LiPo batteries.
To use it please read BattEstimate.md in the AP_Scripting/applets directory
here is an example fit for a 12S LiPo:
Here is a 3s LiOn from Henry:
here is a 4s LiOn from henry:
here is a 6S LiOn from Alex
> AP_Scripting: added battery state of charge estimator

- libraries/AP_Camera/AP_Camera_Backend.cpp
- libraries/AP_Camera/AP_Camera_Backend.h
- libraries/AP_Camera/AP_Camera_MAVLinkCamV2.cpp
- libraries/AP_Mount/AP_Mount_Backend.cpp
- libraries/AP_Mount/AP_Mount_Siyi.cpp
- libraries/AP_Mount/AP_Mount_Viewpro.cpp
- libraries/AP_Mount/AP_Mount_Xacti.cpp
- libraries/GCS_MAVLink/GCS_Common.cpp
This is a rebased version of PR https://github.com/ArduPilot/ardupilot/pull/24354
This PR allows ground station to know which camera is in which gimbal
- mavlink module updated to HEAD so that the camera info message includes the gimbal id field (see https://github.com/ArduPilot/mavlink/pull/323)
- AP_Mount backends (default, MAVLinkCAMv2, Siyi, ViewPro, Xacti) fill in the gimbal_device_id field of the [CAMERA_INFORMATION mavlink message](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L5744C1-L5744C49)
There is an additional drive-by enhancement to vehicle's actual z-axis rotation rate which only affects MAVLink enabled gimbals which means the Gremsy gimbals.
This has been lightly tested on real hardware including a Gremsy PixyU.  Testing included:
- …
> AP_Camera/AP_Mount: camera info msg gets device id to improve multi camera support

- libraries/AP_Networking/AP_Networking.cpp
- libraries/AP_Networking/AP_Networking_address.cpp
- libraries/AP_Networking/AP_Networking_macaddr.cpp
defining two parameter tables in one file causes duplicates
> AP_Networking: fixed duplicate parameters in wiki

- libraries/AP_Mount/AP_Mount.cpp
title says it. _backends[instance] doesn't make sense.
> AP_Mount: use backend instead of _backends[instance]

- libraries/AP_Airspeed/AP_Airspeed.cpp
- libraries/AP_Airspeed/AP_Airspeed_DroneCAN.cpp
this fixes a bug introduced in
https://github.com/ArduPilot/ardupilot/pull/22416 which results in using bad airspeed data on timeout. The prev_health variable is updated by the get_pressure call
This defeated the IIR bad data protections:
> AP_Airspeed: fixed handling of unhealthy airspeed

- libraries/SITL/SIM_GPS.cpp
Clearly lacking an include:
```
../../libraries/SITL/SIM_GPS.cpp: In member function 'void SITL::GPS::send_gsof(const uint8_t*, uint16_t)': ../../libraries/SITL/SIM_GPS.cpp:1292:24: error: 'AP_InternalError' has not been declared
1292 |         INTERNAL_ERROR(AP_InternalError::error_t::flow_of_control);
```
> SITL: correct compilation for CubeOrange-SimOnHardware

- ArduCopter/AP_Arming.cpp
- ArduCopter/mode_guided.cpp
- ArduPlane/AP_Arming.cpp
- libraries/AP_Arming/AP_Arming.cpp
- libraries/AP_Arming/AP_Arming.h
- libraries/AP_DDS/AP_DDS_Client.cpp
- libraries/AP_DDS/AP_DDS_Client.h
- libraries/AP_DDS/AP_DDS_Service_Table.h
- libraries/AP_DDS/Is-Config/Arm_Motors_DDS_IS_config.yaml
- libraries/AP_DDS/README.md
- libraries/AP_DDS/dds_xrce_profile.xml
This is work in progress PR that aims to provide support for service support as requested in #23822 and will work as a foundation for #23363 . Currently we focus on providing support for Arming / Disarming motors.
@Ryanf55 @srmainwaring @tridge would like to know your thoughts on this
> AP_DDS: Added ROS 2 service support

- .vscode/extensions.json
This relates to #24521 and now prompts VSCode users who open the ArduPilot source tree to install a new extension. The extension supports automatically attaching to a process by allowing use of shell commands. Previous behavior means it pops up a window, you type in arducopter, then click it. I used `pgrep arducopter` which worked great to reliably find the process ID of the ArduCopter binary when run under SITL. Saves me ~5 seconds every time I run. 
**.vscode/tasks.json**
```json
{
"version": "0.2.0",
"configurations": [
{
"name": "Copter Attach",
"type": "cppdbg",
"request": "attach",
"program": "${workspaceFolder}/build/sitl/bin/arducopter",
"processId": "${input:FindCopterPID}",
"MIMode": "gdb",
"setupCommands": [
{
"description": "Enable pretty-printing for gdb",
"text": …
```
> vscode: Add extension for automatically picking process

- ArduCopter/mode_guided.cpp
A BREAK statement is never executed after a RETRUN statement.
Many other methods do not have such statements.
Code that is never executed is unnecessary.
> Copter: Remove code that will never be executed

- Tools/AP_Periph/can.cpp
- libraries/AP_TemperatureSensor/AP_TemperatureSensor_Backend.cpp
- libraries/AP_TemperatureSensor/AP_TemperatureSensor_Params.cpp
- libraries/AP_TemperatureSensor/AP_TemperatureSensor_Params.h
AP_Periph: add support for RawAirData.Pitot_temperature in outbound packets
As of now, Ardupilot does not yet have any inbound use for this yet - it's for reporting only. There is a coming PR for a thermostat-based heated pitot tube to take advantage of this.
> AP_Periph: add support for RawAirData.Pitot_temperature

- Tools/scripts/build_binaries.py
This line got lost somewhere....
I've tested `build_binaries.py` locally and the relevant file is written out correctly.
Fix for @Hwurzburg 's features.json Wiki generation warnings.
> Tools: write features json at same place we write manifest

- libraries/SITL/SIM_Aircraft.cpp
- libraries/SITL/wscript
- wscript
The change to use single precision by default apparently included the SITL folder, and unfortunately that made the position jump around. I originally noticed this on Blimp, but Copter does it too, and the screenshots below are with Copter.
This PR changes SIM_Aircraft to use double precision which fixes the problem.
Before:
After:
Grid size is 1m in both images.
> SITL: Make SIM_Aircraft use double precision to stop SITL's short-range teleporting

- Tools/autotest/arducopter.py
This is clouding a real error where we're not within 1m of where we are supposed to be
> autotest: disarm vehicle in exception handle for PrecLand test

- Tools/autotest/arducopter.py
This relaxes the Copter VibrationFailsafe autotest so that the vehicle has 50 seconds instead of 40 seconds to reach the ground.  This is required in the 4.4 branch in order to past the test.  Master does not need the extra time but it is very close.  [Here's a link to the Copter-4.4 vibration failsafe autotest](https://github.com/ArduPilot/ardupilot/blob/Copter-4.4/Tools/autotest/arducopter.py#L1103).
BTW, while testing I noticed a change in behaviour of this test between 4.4 and 4.5.  There is no change in behaviour between 4.3 and 4.4 though so we don't need to delay the 4.4.0 release.  The cause of the change in behaviour is PR https://github.com/ArduPilot/ardupilot/pull/23807.
Below are screenshots of the desired and actual altitude and horizontal position (see map) for 4.3.7, 4.4.0 …
> autotest: relax Copter vibration failsafe timeout

- libraries/SRV_Channel/SRV_Channel.h
this is a 32-bit parameter.
I think the implication is that values will not go to their trims even if configured to do so.
> SRV_Channel: correct RC channel failsafe mask

- libraries/AP_HAL_ChibiOS/hwdef/ARKV6X/hwdef.dat
This PR updates the ARKV6X hwdef to default to no IO MCU.
> hwdef: arkv6x default to no IO MCU

- libraries/GCS_MAVLink/GCS_FTP.cpp
this led to not being able to do FTP transfers with support.ardupilot.org unless MissionPlanner used the same component ID as the support engineer GCS
this led to a very frustrating support session where I could not upload a lua script
> GCS_MAVLink: fixed corruption of FTP reply component ID

- libraries/AP_Logger/AP_Logger_Backend.cpp
A developer might be able to craft a fault such that s could be nullptr here.  They would need to work at it, but we can do better.
Note that here we are forming up a string to pass to `AP_HAL::panic`, so we're already going to stop execution.
> AP_Logger: correct use of nullptr in SITL structure sanity checks

- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
chan was present in the structure for the in-progress task but was never being initialised.  Meaning it works on USB but not on other links.
The commands still complete, but we send the in-progress and result ACKs to the wrong place.
Thanks to FoxTech for reporting this and working with me to find the problem.
> GCS_MAVLink: fix airspeed cal / format commands via non-USB telemetry

- Tools/autotest/arducopter.py
- Tools/autotest/common.py
- libraries/SRV_Channel/SRV_Channel_aux.cpp
- libraries/SRV_Channel/SRV_Channels.cpp
we may not have valid input but not be at the stage of declaring an RC failsafe.
Now contains a test which fails before but not after.
The fix prevents a glitch on something which is in this go-to-trim mask.  Right now in master the channel will glitch to the RC input value being provided by the receiver until the failsafe kicks in.  "valid input" goes false when the throttle goes below the failsafe value, so use it here to avoid using the bad value.
This configuration had servo-7-out using the scaled-channel-7-input servo function:
> SRV_Channel: avoid using bad RC data in passthrough code

- libraries/AP_GPS/AP_GPS_NOVA.cpp
if we have a very fast stream of garbage coming in available() may never return 0
> AP_GPS_NOVA: avoid infinite reading of bytes

- libraries/GCS_MAVLink/GCS_FTP.cpp
It is easier to understand access with a definition name than with 0.
> GCS_MAVLink: Change a number to a defined name

- libraries/AP_Mission/AP_Mission.cpp
Change mission send_text msg when starting new wp item to also show p1 value for MAV_CMD_DO_JUMP, MAV_CMD_JUMP_TAG, and MAV_CMD_DO_JUMP_TAG. This makes the message more useful for GCSs to know whats going on in-the-moment instead of having to wait and see what happens next... if that's even possible to know.
> AP_Mission: show tag or jump index on WP change

- libraries/AP_DDS/AP_DDS_Client.cpp
- libraries/AP_DDS/README.md
* DDS is still disabled by default in all builds for the library level compile flag
* This parameter was blocking running ROS 2 automated testing in CI
* This can be changed once ENABLE_DDS compiler flag is enabled in SITL or for the 4.5 release
When we try to run tests in CI, the testing framework doesn't work on MacOS. @srmainwaring has spent a signficant amount of time already on it, but no luck yet without some poor workarounds. Instead of spending time on that now, I'd like to prioritize augmenting the automated ROS 2 test infrastructure as a means of validating all the recent GSoC work. Additionally, augmented testing at the ROS level will give us the confidence to perform refactors, switch to MicroROS, or adjust any of the ArduPilot internals without breaking ROS 2 users. 
Overall, …
> AP_DDS: Enable the DDS parameter by default

- libraries/AP_RPM/AP_RPM.cpp
- libraries/AP_RPM/AP_RPM_Params.cpp
- libraries/AP_RPM/AP_RPM_Params.h
- libraries/AP_RPM/AP_RPM_config.h
- libraries/AP_RPM/RPM_Backend.cpp
- libraries/AP_RPM/RPM_Backend.h
This reverts PR https://github.com/ArduPilot/ardupilot/pull/24486 and replaces it with a new param RPMn_ESC_INDEX as discussed in the devcall. It also moves the work to the backend wrapped in a cute AP_RPM_ESC_TELEM_OUTBOUND_ENABLED bow.
> AP_RPM: Fwd rpm data to ESC_Telem

- ArduCopter/ReleaseNotes.txt
- ArduCopter/version.h
- ArduPlane/ReleaseNotes.txt
- ArduPlane/mode.cpp
- ArduPlane/version.h
- Rover/release-notes.txt
- Rover/version.h
- Tools/autotest/arducopter.py
- libraries/AP_Arming/AP_Arming.cpp
- libraries/AP_BattMonitor/AP_BattMonitor_INA2xx.h
- libraries/AP_BattMonitor/AP_BattMonitor_LTC2946.h
- libraries/AP_GPS/AP_GPS_UAVCAN.cpp
- libraries/AP_GPS/AP_GPS_UAVCAN.h
- libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
- libraries/AP_Scripting/AP_Scripting.cpp
- libraries/AP_Scripting/lua/src/ldo.c
This is the Copter-4.3.8-beta1 release which is the same as the Plane-4.3.8-beta1 release (see PR https://github.com/ArduPilot/ardupilot/pull/24611)
PRs included in this release are listed in the "4.3.8-beta1" column of [this project](https://github.com/ArduPilot/ardupilot/projects/25).
This will probably also become the Rover-4.3.0-beta14 release although it is unlikely that users will be interested because Rover-4.3.0 was never released as the stable version and Rover-4.4.0-beta has surpassed it in all ways.
> Copter: 4.3.8-beta1 release

- libraries/AP_RPM/AP_RPM_config.h
- libraries/AP_RPM/RPM_ESC_Telem.cpp
Wrong define, `RPM_TYPE_ESC_TELEM` is not available if ~AP_RPM_ESC_TELEM_ENABLED, and that's being used in this block
> AP_RPM: correct compilation when AP_RPM_ESC_TELEM_ENABLED is disabled

- Tools/AP_Bootloader/board_types.txt
Reserve board id for QioTekAdept_6C
> AP_Bootloader: reserve board id for QioTekAdept_6C

- README.md
The old URL shows a security warning on browsers due to invalid ssl certificate for domain ardupilot.com
> README: fix GPL license URL

- libraries/AP_HAL_ChibiOS/Scheduler.cpp
- libraries/AP_HAL_ChibiOS/hwdef/scripts/defaults_periph.h
if Periph panics before we mark the scheduler as initialised then we don't watchdog, which we really need to do on periph nodes so they can be re-flashed conveniently.
> AP_HAL_ChibiOS: prevent Periph bricking problem when paniccing early

- Tools/autotest/arduplane.py
The WindEstimate CI test thresholds occasionally don't get reached but they're still twiddling so a little extra time will likely make it pass much more reliably
> Tools/autotest: extend WindEstimate duration

- Tools/AP_Bootloader/board_types.txt
Grabbing some internal board ID's similar to other OEM's.
> Tools: AP_Bootloader: Reserve board id's for SpektreWorks

- libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
Credit to @casrya on github for spotting this (#24665), and investigating. The intent here was to bail out only if no data was within the timeout, which I had messed up in a bad refactor.
> AP_ESC_Telem: Correct a regression with calclulating active_esc_mask

- libraries/AP_RPM/RPM_EFI.cpp
- libraries/AP_RPM/RPM_EFI.h
- libraries/AP_RPM/RPM_ESC_Telem.cpp
- libraries/AP_RPM/RPM_ESC_Telem.h
- libraries/AP_RPM/RPM_Generator.cpp
- libraries/AP_RPM/RPM_Generator.h
- libraries/AP_RPM/RPM_HarmonicNotch.cpp
- libraries/AP_RPM/RPM_HarmonicNotch.h
- libraries/AP_RPM/RPM_Pin.cpp
- libraries/AP_RPM/RPM_Pin.h
```
Durandal                       *      *           -40     -48               -40    -40    -40
KakuteH7-bdshot                *      *           -48     -48               -48    -48    -40
MatekF405                      *      *           -32     -40               -40    -32    -40
Pixhawk1-1M-bdshot             *                  -32     -40               -40    -40    -32 …
```
> AP_RPM: tidy constructors and use of config.h

- Tools/scripts/build_ci.sh
- Tools/scripts/run_astyle.py
Instead of running:
`./Tools/CodeStyle/ardupilot-astyle.sh libraries/AP_DDS/*.h libraries/AP_DDS/*.cpp` and so on
You now run:
`./Tools/scripts/run_astyle.py`
CI now specifically has to set the dry-run option, so users don't have to.
This makes it easier to avoid astyle violations in CI.
> Tools: Allow enforcing astyle in CLI automatically

- libraries/AP_DroneCAN/AP_DroneCAN.cpp
- libraries/AP_DroneCAN/AP_DroneCAN.h
These changes are aimed at making it possible to control reversible DroneCAN ESCs in both directions. Previously,[  RawCommands](https://dronecan.github.io/Specification/7._List_of_standard_data_types/#rawcommand) were restricted to the range [0,8191], so according to the DroneCAN specification attached ESCs could only spin in the forward direction. See #17497 , this should address that issue.
I added a new parameter (ESC_RM) which provides a bitmask that can be used to indicate if an ESC is reversible. This parameter name is tacked onto CAN_D1_UC, so there are not many characters left before hitting the 16 character limit. So I chose this relatively terse name. If an ESC is not reversible, the RawCommands are created and scaled in the same way they were before, which should help with …
> AP_DroneCAN: Update DroneCAN to allow sending negative RawCommands to ESCs

- Blimp/AP_Arming.cpp
- Blimp/Blimp.cpp
- Blimp/Blimp.h
- Blimp/Fins.h
- Blimp/GCS_Mavlink.cpp
- Blimp/GCS_Mavlink.h
- Blimp/Log.cpp
- Blimp/Loiter.cpp
- Blimp/Loiter.h
- Blimp/Parameters.cpp
- Blimp/Parameters.h
- Blimp/RC_Channel.cpp
- Blimp/config.h
- Blimp/defines.h
- Blimp/ekf_check.cpp
- Blimp/events.cpp
- Blimp/mode.cpp
- Blimp/mode.h
- Blimp/mode_land.cpp
- Blimp/mode_loiter.cpp
- Blimp/mode_manual.cpp
- Blimp/mode_rtl.cpp
- Blimp/mode_velocity.cpp
- Blimp/motors.cpp
- Blimp/radio.cpp
- Blimp/system.cpp
- Blimp/wscript
- Tools/autotest/default_params/blimp.parm
- libraries/SITL/SIM_Blimp.cpp
- libraries/SITL/SIM_Blimp.h
This PR moves the Loiter and Velocity mode PIDs into a separate class for neatness and also adds a very simple RTL mode using that class.
It also fixes the inverted throttle and removes a bunch of unused code.
> Blimp: Loiter class, add RTL and other improvements

- AntennaTracker/GCS_Mavlink.cpp
- AntennaTracker/GCS_Mavlink.h
- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
- ArduPlane/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.h
- ArduSub/GCS_Mavlink.cpp
- ArduSub/GCS_Mavlink.h
- Blimp/GCS_Mavlink.cpp
- Blimp/GCS_Mavlink.h
- Rover/GCS_Mavlink.cpp
- Rover/GCS_Mavlink.h
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
the "special case" blocks are getting longer and longer.  Merge the switch statements for the command type to be handled by passing around the message.
This would also allow a vehicle to inspect the `mavlink_message_t` if it really felt like it.
The methods which actually use the msg_t when passed in as a command_long need to be moved over to command_int too.  Moving them in this PR will avoid moving them into the special-case-switch in `handle_command_int`.
```
Durandal                       24     *           48      56                48     24     16
HerePro             40                                                                    
Hitec-Airspeed      * …
```
> Pass mavlink_message_t to handle_command_*_packet

- libraries/AR_Motors/AP_MotorsUGV.cpp
- libraries/AR_Motors/AP_MotorsUGV.h
Context: the [BlueBoat](https://bluerobotics.com/store/blueboat/blueboat/) uses propellers that produce roughly halft the thrust when running in reverse:
This causes it to "spiral out" whenever trying to turn in Manual or Acro modes.
> AP_MotorsUGV: add handling of asymmetric thrust

- libraries/AP_Param/AP_Param.cpp
- libraries/AP_Param/AP_Param.h
we need to add up the total for all comma separated parameter files
this fixes a bug where we can address beyond the end of the param_overrides array if we have multiple comma separated param files
> AP_Param: fixed parameter defaults array length handling

- ArduCopter/AP_ExternalControl_Copter.cpp
- ArduCopter/AP_ExternalControl_Copter.h
- ArduCopter/Copter.h
- ArduCopter/mode.h
- ArduPlane/Plane.h
- Rover/Rover.h
- Tools/ardupilotwaf/ardupilotwaf.py
- Tools/scripts/run_astyle.py
- libraries/AP_DDS/AP_DDS_Client.cpp
- libraries/AP_DDS/AP_DDS_ExternalControl.cpp
- libraries/AP_DDS/AP_DDS_ExternalControl.h
- libraries/AP_DDS/AP_DDS_Frames.h
- libraries/AP_ExternalControl/AP_ExternalControl.cpp
- libraries/AP_ExternalControl/AP_ExternalControl.h
- libraries/AP_ExternalControl/AP_ExternalControl_config.h
This is a very basic implementation of an external control library, just to unblock @pedro-fuoco 
Relates to #23363 
1. Run sim_vehicle with --enable-dds --console --map
2. Set DDS_ENABLED param to 1
3. Use mavproxy to arm the vehicle, set the mode to guided, and takeoff to ~50m
4. Run the microROS agent like normal
5. Verify with ros2 CLI that you see the `ap/cmd_vel` topic
6. Publish commands to `ap/cmd_vel`, or use rqt. Current behavior is this
```
ros2 topic pub /ap/cmd_vel geometry_msgs/msg/TwistStamped '{twist: {linear: {z: 1.0}}}'
ros2 topic pub /ap/cmd_vel geometry_msgs/msg/TwistStamped '{twist: {linear: {z: -1.0}}}'
ros2 topic pub /ap/cmd_vel geometry_msgs/msg/TwistStamped '{twist: {linear: {x: 1.0}}}'
```
We do need to decide if the cmd_vel topic should be in body frame or map …
> AP_ExternalControl: initial implementation of external control library

- libraries/AP_Networking/AP_Networking.cpp
The generated class pointer variable is set to NULLPTR.
The generated class pointer is released before setting.
AND、I have found the bug.
After setting NULLPTR, this variable was used.
The initialization failed and the process was terminated.
> AP_Networking: Delete entity class pointer

- Rover/GCS_Mavlink.cpp
- Tools/autotest/rover.py
New test added to make sure it continues to work.  At least in guided.
> Rover: rely on magic conversion to handle DO_SET_REVERSE as both int/long

- ArduPlane/Parameters.cpp
- ArduPlane/Parameters.h
- Tools/autotest/arduplane.py
- libraries/APM_Control/AP_AutoTune.cpp
- libraries/APM_Control/AP_AutoTune.h
- libraries/AP_Vehicle/AP_FixedWing.h
Fixed wing autotune sets FLTT and FLTD. This can have two unwanted side-effects:
- VTOL setups typically require higher gyro, D and notch filter setups in VTOL modes but these filter settings can be too high for fixed-wing control
- FLTT filters the feed-forward component, but also the pilot input meaning that it can hide P/D oscillation that is occurring during autotune as well hiding pilot input resulting in a very soft tune
We have seen similar issues in copter autotune in the past with FLTT masking input and creating a very soft tune.
This PR adds an AUTOTUNE_OPTIONS bitmask that allows users to switch off the update of these settings so that they can be selected manually (so for instance a higher value for FLTT and a lower value for FLTD)
> Autotune options to allow filter control

- libraries/AP_Mount/AP_Mount.cpp
- libraries/AP_Mount/AP_Mount.h
- libraries/AP_Mount/AP_Mount_Backend.cpp
- libraries/AP_Mount/AP_Mount_Backend.h
- libraries/AP_Mount/AP_Mount_Viewpro.cpp
- libraries/AP_Mount/AP_Mount_Viewpro.h
- libraries/AP_Mount/LogStructure.h
This add basic support for retrieving the distance from a ViewPro gimbal with an integrated range finder.  For the moment the distance is simply logged to the MNT message but in the future it will be used for more useful things including calculating the lat,lon,alt of what the gimbal is pointing at (see PR https://github.com/ArduPilot/ardupilot/pull/24657).  It will also be expanded to include other gimbals like the Siyi ZT30.
This has been tested on real hardware (ViewPro A10T) and below are some some screenshots of the ViewPro app (aka Viewlink) showing the LRF distance and then similar numbers from some debug output sent to Mission Planner.
Below is a screen shot of showing the logging is working (the distances are faked)
Note that I had to shorten some of the MNT log message fields to …
> AP_Mount: Viewpro supports get rangefinder distance

- .github/workflows/test_ccache.yml
- libraries/AP_NavEKF/AP_NavEKF_Source.cpp
- libraries/AP_NavEKF/AP_NavEKF_Source.h
- libraries/AP_NavEKF3/AP_NavEKF3.cpp
- libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp
Currently boards without baros quickly accumulate large velocity errors while sitting on the bench. Here is an example from a MambaF405v2:
The reason is that the EKF is fusing completely invalid data (the columns are all zero?). @priseborough suggested that a way around this would be to provide a dummy baro on these boards. Fortunately we already have one which only needed some minor changes and using this yielded much more sane results:
The second part of the fix is to allow much larger values of EK3_ALT_M_NSE to be set since the baro will always be giving a constant fixed height, but the height of the copter will vary. This value is in meters so allowing a value for the maximum height of these copters (usually relatively small because of the lack of baro) is prudent.
The fix allows the …
> Support baroless boards correctly in the EKF

- ArduCopter/Copter.cpp
There is no fast_loop method.
It is registered as FAST_TASK.
I will change it.
> Copter: Change from fast_loop method to FAST_TASK(NFC)

- Rover/GCS_Mavlink.cpp
- Tools/autotest/rover.py
test doesn't pass before but does after.
> Rover: accept MAV_CMD_NAV_RETURN_TO_LAUNCH as both long and int

- ArduCopter/system.cpp
Class initialization availability is done by preprocessor.
The range finder is also enabled/disabled by the preprocessor.
> Copter: The preprocessor determines whether rangefinder initialization is possible

- libraries/GCS_MAVLink/GCS_Common.cpp
When a GCS requests the home position and we respond via ```send_home_position()``` we used to always send it if home was set. Now we'll ignore the request for many more seconds until ```home.get_vector_from_origin_NEU()``` returns true which is when the EKF origin is set. Is that really necessary? It's just populating another part of the home_position() message which is otherwise 0 and used to be hard-coded to 0. If a GCS really wants that info then it can re-request until it gets non-zero data there.
> GCS_MAVLink: home position should always send

- ArduCopter/Copter.h
- Tools/scripts/build_ci.sh
- libraries/AP_DDS/AP_DDS_Client.cpp
- libraries/AP_DDS/AP_DDS_External_Odom.cpp
- libraries/AP_DDS/AP_DDS_External_Odom.h
- libraries/AP_DDS/AP_DDS_Type_Conversions.cpp
- libraries/AP_DDS/AP_DDS_Type_Conversions.h
- libraries/AP_DDS/AP_DDS_config.h
- libraries/AP_DDS/tests/test_ap_dds_external_odom.cpp
- libraries/AP_DDS/tests/test_ap_dds_type_conversions.cpp
- libraries/AP_DDS/tests/wscript
This is an implementation of allowing external localization data from DDS to augment ArduPilot's EKF for position data. It will solve #23387. Providing an initial world frame position is out of scope of this PR. This is required to complete the Google Cartographer section of @pedro-fuoco's GSoC project.
* Broke out external odom into its own file because it only has message dependencies, nothing on DDS - this will allow easier moving to `AP_ExternalOdometryDDS` backend in the future. 
* Added a new `TransformF` type in ArduPilot for working with homogonous transforms. This reduces the need to pass both a position and orientation separately to similar functions.
* Implemented frame ID checking, since there may be multiple transforms published to ArduPilot in the future and localization is …
> DDS external odometry/localization support

- Dockerfile
This allows you to override the base image like so, so ROS developers have an environment. I'll add some docker-compose files and associated documentation later. If no options are suggested, the current behavior is used.
```
docker build . -t ardupilot_ros --build-arg "BASE_IMAGE=ros" --build-arg "TAG=humble"
```
> Docker: Add args to allow changing base image

- libraries/GCS_MAVLink/GCS_Common.cpp
Slipped through in https://github.com/ArduPilot/ardupilot/pull/24679
FYI: @peterbarker
> GCS_MAVLink: Remove unreachable return in handle_command_mount()

- Tools/AP_Bootloader/board_types.txt
And adjust the reservations for Carbonix and SpektreWorks to reserve 100 IDs instead of 101.
> AP_Bootloader: Reserve 100 IDs for SYPAQ Systems

- libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain.cpp
- libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.cpp
- libraries/AP_GPS/AP_GPS.cpp
- libraries/AP_GPS/AP_GPS.h
Certain GNSS drivers, like the MicroStrain GQ7, have multiple GPS antennas that get reported separately to the driver. Rather than only handling GPS data for one GPS sensor, or publishing the same GPS data to two external GPS types like recommended in the [tutorial](https://ardupilot.org/copter/docs/common-external-ahrs.html), this will allow future drivers to uniquely populate two GPS instances with data. 
To preserve existing behavior, I added a utility to get the first external AHRS instance, which is what the code was doing before.
To consume this new behavior, an external AHRS system could do the following:
```
switch(packet_id)
case gps_0_packet:
gps_data = parse_gps_packet(packet)
AP::gps().handle_external(gps_data , 0)
case gps_1_packet:
gps_data = parse_gps_packet(packet) …
```
> Allow multiple External AHRS GPS instances

- Rover/GCS_Mavlink.cpp
- Tools/autotest/rover.py
> Rover: rely on magic long-to-int conversion to handle MAV_CMD_DO_CHANGE_SPEED

- Tools/ardupilotwaf/cmake.py
Before the comment, the variable had no effect. 
Now, you get this when you use the min cmake version
```
Checking for program 'cmake'                   : /usr/local/bin/cmake 
Checking cmake version                         : 3.27.0 
```
> ardupilotwaf: Fix incorrect comment for cmake minimum version

- ArduCopter/ReleaseNotes.txt
- ArduCopter/version.h
This is the Copter-4.3.8 release which has no functional changes vs the 4.3.8-beta1 release that's been out since last week.
> Copter: 4.3.8 release

- libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_mcuconf.h
- libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_type2_mcuconf.h
- libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
this allows for hwdef.dat lines like this:
PA8 MCO1 RCC
PC9 MCO2 RCC
you can control the scaling by defining the following:
- STM32_MCO1SEL
- STM32_MCO1PRE_VALUE
- STM32_MCO2SEL
- STM32_MCO2PRE_VALUE
> hwdef: allow for MCO pin to be configured

- Rover/GCS_Mavlink.cpp
I've tested this in SITL, both before and after; before the COMMAND_INT gets `UNSUPPORTED`, afterwards it works.
```
MANUAL> 
MANUAL> gservo6
MANUAL> Adding graph: ['SERVO_OUTPUT_RAW.servo1_raw', 'SERVO_OUTPUT_RAW.servo2_raw', 'SERVO_OUTPUT_RAW.servo3_raw', 'SERVO_OUTPUT_RAW.servo4_raw', 'SERVO_OUTPUT_RAW.servo5_raw', 'SERVO_OUTPUT_RAW.servo6_raw', 'SERVO_OUTPUT_RAW.servo7_raw', 'SERVO_OUTPUT_RAW.servo8_raw']
MANUAL> 
MANUAL> 
MANUAL> 
MANUAL> command_int 1 DO_MOTOR_TEST 1 1 1 1 1200 4 0 0 0
MANUAL> Got COMMAND_ACK: DO_MOTOR_TEST: ACCEPTED
AP: Throttle armed
ARMED
AP: EKF variance
AP: Throttle disarmed
AP: EKF failsafe cleared
DISARMED
command_int 1 DO_MOTOR_TEST 1 1 1 1 1200 4 0 0 0
MANUAL> Got COMMAND_ACK: DO_MOTOR_TEST: ACCEPTED
AP: Throttle armed
ARMED
AP: EKF3 IMU0 is using GPS
AP: …
```
> Rover: allow motor test to be issued as COMMAND_INT

- libraries/AP_BattMonitor/AP_BattMonitor_Torqeedo.cpp
The STM32 is fast at multiplying floating values
> AP_BattMonitor: Change to floating value multiplication

- Rover/GCS_Mavlink.cpp
- Tools/autotest/common.py
- Tools/autotest/rover.py
New test doesn't pass the command_int before but does afterwards.
> Rover: support MAV_CMD_MISSION_START as both command_long and command_int

- libraries/AP_Mount/AP_Mount_Siyi.cpp
- libraries/AP_Mount/AP_Mount_Siyi.h
While sending a Manual zoom (rate) command to SiYi. zoom stops multiple time in between. This Pull fixes this by sending the same command multiple time at 20Hz. Tested on Zr10.
Support issue link [here](https://discuss.ardupilot.org/t/zr10-2k-qhd-30x-hybrid-zoom-gimbal-camera-siyis-first-industry-gimbal-camera-and-it-wont-be-the-last/86069/429)
I find out one more bug that is probably SiYI side. that is when we watch the zoom value on the SiYI FPV app the values are different than real zoom. eg: on 30x sometime it tell 20x, 22x, 27x etc.
> AP_Mount: fix SiYi doesn't zoom continuously while manual zoom control

- libraries/AP_Mount/AP_Mount.cpp
- libraries/AP_Mount/AP_Mount.h
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
In reference to issue #24571 
Initial Draft
(Not tested yet so Draft)
> AP_Mount/GCS_MAVLink: move handling of all do-set-roi to AP_Mount library

- Rover/GCS_Mavlink.cpp
- Rover/GCS_Mavlink.h
- Tools/autotest/common.py
- Tools/autotest/rover.py
Also add tests for same command as both long and int
Since this was the last entry handled solely as command_long, I've structured the change to minimise the delta.
> Rover: support running MAV_CMD_NAV_SET_YAW_SPEED as command_int

- Tools/autotest/default_params/quadplane-ice.parm
- Tools/autotest/quadplane.py
- libraries/SITL/SIM_ICEngine.cpp
without this we continuously try to restart the motor as the minimum thrust output from the ICE is translated into a value less than the default ICE_RPM_THRESH (so the ICEngine library believes the engine to be stopped, when it is really just at idle).
Also send SIM_ICEngine diagnostics to GCS.  They're pretty much useless on stdout.
> autotest: set ICE_RPM_THRESH for quadplance-ice

- Rover/GCS_Mavlink.cpp
- Rover/GCS_Mavlink.h
Built on top of https://github.com/ArduPilot/ardupilot/pull/24775
There's only one patch on top here that matters.
Saves 240 bytes when compiled out using the new define
> Rover: deprecate nav set yaw speed

- libraries/AP_Scripting/generator/src/main.c
Currently we can do things like this:
```
local location = Location("foo")
local target_velocity = Vector3f("bar") 
```
Any arguments passed to construction functions is discarded. This can lead to bugs where one thinks the arguments do something but they don't.
Now the code will error out with:
`Lua: ./scripts/test.lua:12: bad argument #1 to 'Location' (too many arguments)`
Unfortunately luacheck does not catch these issues related number or type of arguments (although the VSCode lua extension does... )
> AP_Scripting: add argcheck to default userdata creation functions

- Tools/autotest/ardusub.py
- Tools/autotest/common.py
- libraries/AP_BattMonitor/AP_BattMonitor.cpp
AP_BattMonitor: extend AP_BATT_MONITOR_MAX_INSTANCES limit to 16 (default is still 9)
Doesn't hurt to bump the max up to 16, especially for vehicles with lots of power monitoring and AP_Periphs with sensors galore!
Note: if we ever consider pushing above 16 The limitation is param1 being treated as uint16 in handle_command_battery_reset()
```
MAV_RESULT GCS_MAVLINK::handle_command_battery_reset(const mavlink_command_long_t &packet) {
const uint16_t battery_mask = packet.param1;
const float percentage = packet.param2;
if (AP::battery().reset_remaining_mask(battery_mask, percentage)) {
```
Since it's a command_long, the float could give us 24 bitmask bits as-is. The [MAVLink docs don't mention any limit](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/ardupilotmega. …
> AP_BattMonitor: extend AP_BATT_MONITOR_MAX_INSTANCES to 16

- .pre-commit-config.yaml
* To fix https://github.com/pre-commit/pre-commit/issues/2782
* Discovered in https://github.com/ArduPilot/ardupilot/pull/24683#issuecomment-1687242147
This should fix the issue of not being able to commit on older branches when using pre-commit once installed. If we want to help out developers working on old releases, this would require a backport of the pre-commit config. This is super low risk to the release, and I don't see it needing a beta, since pre-commit is only used when changing code, and does not affect any flight behavior. 
To do this on a release branch, you can see running the autoupdate brings in the new `isort` version which has the fix for the poetry error.
```
ryan@ryan-B650-970:~/Development/ardu_ws/src/ardupilot$ pre-commit autoupdate …
```
> pre-commit: Run autoupdate

- Tools/AP_Bootloader/bl_protocol.cpp
Stm32L4r5 flash has 512 sectors in dual bank configuration -tested
> Tools: Change erase sectors size

- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
I've tested this with in SITL using gdb, setting a breakpoint on `GCS_MAVLINK_Copter::handle_MAV_CMD_SOLO_BTN_PAUSE_CLICK` and checking that all relevant clauses are covered when run as both COMMAND_LONG and COMMAND_INT
I think we could probably turn the new define off on where `HAL_SOLO_GIMBAL_ENABLED` isn't on.
> ArduCopter: allow MAV_CMD_SOLO_BTN_PAUSE_CLICK as COMMAND_INT

- libraries/AP_Mount/AP_Mount_Params.cpp
- libraries/AP_Mount/AP_Mount_Viewpro.cpp
- libraries/RC_Channel/RC_Channel.cpp
This makes 3 unrelated fixes to AP's camera and mount subsystems found during recent testing.  These changes have been tested on real hardware.
1. Viewpro driver fix to the date sent to the camera gimbal.  The mask applied to the date was incorrect meaning it was incorrect after the 15th of the month.  Below is a screenshot of the Viewlink app showing the correct date after this PR was applied.
2. AP_Mount's DEVID field should be writeable so that users can reset it to zero in case they swap one Xacti camera for another (assuming the other has a different DroneCAN node id).
3. RC_Channel's init_aux_function was missing entries for the recently added CAMERA_IMAGE_TRACKING and CAMERA_LENS features.  For image tracking we don't need to initialise the state but for set-lens we should.
> AP_Mount: Viewpro date fix (and other small fixes)

- Tools/autotest/autotest.py
these were never particularly useful, and now we can actually retrieve the defaults from the running vehicle, so this is even less useful.
.... also, these steps are failing on the autotest server....
> autotest: remove generation of defaults files

- .github/workflows/test_coverage.yml
- .github/workflows/test_sitl_periph.yml
- Tools/AP_Periph/rc_out.cpp
- Tools/ardupilotwaf/boards.py
- Tools/autotest/sim_vehicle.py
- libraries/AP_AHRS/AP_AHRS.cpp
- libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.cpp
- libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.h
- libraries/AP_CANManager/AP_CANManager.h
- libraries/AP_Compass/AP_Compass_DroneCAN.cpp
- libraries/AP_Compass/AP_Compass_DroneCAN.h
- libraries/AP_GPS/AP_GPS_DroneCAN.cpp
- libraries/AP_HAL_SITL/CANSocketIface.cpp
- libraries/AP_HAL_SITL/CANSocketIface.h
- libraries/AP_HAL_SITL/CAN_Multicast.cpp
- libraries/AP_HAL_SITL/CAN_Multicast.h
- libraries/AP_HAL_SITL/CAN_SocketCAN.cpp
- libraries/AP_HAL_SITL/CAN_SocketCAN.h
- libraries/AP_HAL_SITL/CAN_Transport.h
- libraries/AP_Mount/AP_Mount_Scripting.h
- libraries/SITL/SITL.cpp
- libraries/SITL/SITL.h
This allows for the choice of both multicast and socketcan in SITL. This will allow for CAN in SITL on cygwin and WSL/WSL2
To select transport set SIM_CAN_TYPE0 and SIM_CAN_TYPE1 (you can have different transports for the 2 interfaces)
The default is multicast UDP
Testing done:
> SITL: support both multicast and socketcan in CAN SITL

- Tools/autotest/quadplane.py
- libraries/AP_Arming/AP_Arming.cpp
- libraries/AP_Arming/AP_Arming.h
This adds an arming check of the vehicle's primary compass's magnetic field vs the world magnetic model.  The purpose is to try and catch situations where metal objects in the environment near the vehicle result in a bad yaw estimate which can lead to short-term loss of control soon after takeoff.  The loss of control is "short-term" because normally the [EKF failsafe](https://ardupilot.org/copter/docs/ekf-inav-failsafe.html) and/of [GSF's emergency yaw reset](https://ardupilot.org/copter/docs/common-compassless.html) lead to regaining control if given enough time and space.
The vehicle's primary compass magnetic field values are rotated into earth frame and then each axis is compared vs the expected value to ensure it is less than the threshold held in a new ARMING_MAGTHRESH parameter. …
> AP_Arming: mag field check vs world magnetic model

- Tools/autotest/common.py
- Tools/autotest/rover.py
when MAVProxy says "loaded" it is only refering to getting the files into its own state, not into the autopilot
> autotest: fix flapping Rally test

- libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain5.cpp
If you didn't set the serial port parameter correctly, but enabled MicroStrain AHRS, it would crash on boot. VectorNAV is not subject to this issue because it has checks before reading the uart. 
Discovered here: https://github.com/ArduPilot/ardupilot/pull/24723#issuecomment-1694833045
> AP_ExternalAHRS: Fix MicroStrain nullptr crash on bootup

- libraries/AP_Mount/AP_Mount_Siyi.cpp
- libraries/AP_Mount/AP_Mount_Siyi.h
Siyi's recent firmware for the A8 includes absolute zoom control so we can remove the simple absolute-to-rate-zoom controller we required previously.
It seems this addition was made to Siyi firmware ver 1.3 or 1.4 (released July 2023).  The latest firmware is ver 1.5 (released Aug 2023).
This has been tested on the A8 and ZR10.
> AP_Mount: Siyi absolute zoom simplification

- libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp
default clause is in wrong place and shouldn't be present to start with...
Replaces https://github.com/ArduPilot/ardupilot/pull/24784 because github interface not updating.  Grrr.
> AP_ExternalAHRS: correct AP_ExternalAHRS init

- libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp
- libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.h
- libraries/AC_PID/AC_PID.h
Came up on the DevCall that the current constructor for AC_PID is a bit of a nightmare to work with.
Perhaps this structure might be better?
I've only converted one PID here, and if we do go down this path we'd remove the old constructor and move the content into the new constructor.
> Allow initialisation of AC_AttitudeControl pids with a structure

- libraries/AP_HAL_ESP32/Storage.h
- libraries/AP_HAL_ESP32/targets/esp32/partitions.csv
Increase the storage partition for esp32 to 256K to allow for two 128K sectors when using `AP_FlashStorage`.
This fixes an issue where the EEPROM was always erased on boot for rover and plane builds as the `format_version` loaded from flash did not match the version in the build.
- build, flash and run for `esp32buzz` (plane), `esp32nick` (plane) - bare board only - so run up to hardware init.
- verified that params changes are persisted and EEPROM not cleared on reboot for `esp32empty` (copter, plane, rover).
> AP_HAL_ESP32: change storage sector size to 128K

- libraries/AP_Mount/AP_Mount_Siyi.cpp
- libraries/AP_Mount/AP_Mount_Siyi.h
This PR adds the following enhancements to the Siyi driver:
- set_lens allows specifying which cameras(s) are streamed in real-time to the GCS
- supports rangefinder on ZT30.  Updates are at 10hz and the outputs are currently only logged
- model detection is improved by using the reported hardware id which allows detecting the A2, A8, ZR10, ZR30, ZT30.  The model name is also displayed to the user
- Zoom firmware version is displayed to the user on cameras with a zoom
This has been lightly tested on an A8 and ZR10 to confirm:
- model names are displayed to the user and appear in the CAMERA_INFORMATION mavlink message
- zoom still works
Testing required:
- set RCx_OPTION = 175 (CAMERA_LENS)
- ensure real-time video is being streamed to the ground station
- move RC aux switch to low, med …
> AP_Mount: Siyi supports set_lens and get_rangefinder_distance

- Tools/ros2/ardupilot_msgs/CMakeLists.txt
- Tools/ros2/ardupilot_msgs/srv/ModeSwitch.srv
Added custom ROS-2 service definition for switching drive modes.
Service definition used from [here](https://github.com/arshPratap/ardupilot_ros2/blob/main/ap_custom_services/srv/ModeSelect.srv)
@Ryanf55 @srmainwaring @tridge
> Tools : Added custom ROS-2 service definition for switching drive modes

- libraries/AP_HAL_ESP32/Scheduler.cpp
- libraries/AP_HAL_ESP32/Scheduler.h
- libraries/AP_HAL_ESP32/boards/esp32empty.h
- libraries/AP_InertialSensor/AP_InertialSensor_NONE.cpp
Update AP_InertialSensor_NONE and the EPS32 scheduler to allow the esp32empty board to run.
The main change is to disable the initialisation check in the timer thread as this was preventing the IMU from completing its initialisation checks.
The changes to esp32empty.h are mainly formatting - tabs to whitespace. UART_NUM_2 is changed to use the default pinout which uses the IO_MUX rather than the GPIO matrix.
There is a recurring message arising from a Fence breach which is not addressed in this PR.
Baseline for future profiling and optimisation changes:
```bash
APM_MAIN        26222159                43%
IDLE            44275628                73%
IDLE            12344488                20%
APM_UART        2487045         4%
APM_WIFI1       2225550         3%
APM_RCIN        913707 …
```
> Fix AP_InertialSensor_NONE to work with esp32empty

- libraries/AP_Scripting/drivers/EFI_DLA.lua
- libraries/AP_Scripting/drivers/EFI_DLA.md
a simple serial protocol, no CRC, gap framed
confirmed as working by JacksonUAS:
> AP_Scripting: added EFI driver for DLA EFI serial protocol

- libraries/AP_DAL/AP_DAL_RangeFinder.cpp
- libraries/AP_OpticalFlow/AP_OpticalFlow_Calibrator.cpp
- libraries/AP_RangeFinder/AP_RangeFinder.cpp
These cpp files are using the library without getting the header file.  If transitive includes break then you can get errors in seemingly unrelated places.....
> Add missing internal-error includes

- ArduPlane/quadplane.cpp
the nav_roll_cd and nav_pitch_cd were not being set in the VTOL takeoff code when disarmed. This led to small increments accumulating in the stick mixing code, leading to large control surface movements before arming
see this bug report for a video:
https://discuss.ardupilot.org/t/plane-4-4-release/99954/83
> Plane: fixed nav_roll/nav_pitch when waiting for VTOL takeoff

- libraries/AP_HAL/SIMState.cpp
Only the contributor who commented out the process knows the reason for leaving the process commented out when it is no longer needed.
Therefore, delete it as an unnecessary process.
> AP_HAL: Delete commented-out processes

- libraries/AP_HAL_Linux/GPIO_Navigator.h
The comment was wrong. gpio 26 is actually used for the PCA Output Enable signal. This also adds GPIO18, which is the one broken out to the PWM0 pin
> AP_HAL_Linux: update Navigator available GPIOs

- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
Tested in SITL using gdb and breakpoints; all codepaths through these two functions were tested with both command-int and command-long
> Copter: accept solo buttons as both long and int

- libraries/AP_ICEngine/AP_ICEngine.cpp
This is a change in behavior, although I think a correct one. I guess we could add a option to not do this if there is a good reason one would want to keep the engine running under parachute.
> AP_ICEngine: stop engine on parachute release

- libraries/AP_L1_Control/AP_L1_Control.cpp
It appears that the L1 navigation controller assume the vehicle heading (yaw) is always in a direction that will close the distance to the desired ground track between waypoints.
In the case of an aircraft flying into a large headwind (higher than `TRIM_ARSPD_CM`), the controller will begin to swing between left and right roll.
This is possibly related to: https://github.com/ArduPilot/ardupilot/issues/20080 ; however, this is more of a corner case than general wrapping of the calculation.
**SITL command from top level directory**: `python ./Tools/autotest/sim_vehicle.py --vehicle ArduPlane --out=tcpin:localhost:5760 --out=tcpin:127.0.0.1:14550 --frame quadplane -D -w`
**Waypoints**: [canberra_180.txt](https://github.com/ArduPilot/ardupilot/files/12490556/canberra_180.txt)
**BIN log …
> AP_L1_Control: check vehicle yaw (heading) and ground track agree

- libraries/AP_Mount/AP_Mount_Xacti.cpp
- libraries/AP_Mount/AP_Mount_Xacti.h
This adds support for setting the "lens" (which camera is used for the live video feed) and the digital zoom.
The camera rejects messages if sent too close together meaning that I had to add some additional checks to existing methods to increase the likelihood that the messages are spaced apart.
This has been tested on real hardware.  Below are some screen shots taken during testing.
> AP_Mount: xacti supports set lens and zoom

- libraries/AP_BattMonitor/AP_BattMonitor.cpp
- libraries/AP_BattMonitor/AP_BattMonitor_Backend.cpp
- libraries/AP_BattMonitor/AP_BattMonitor_Backend.h
- libraries/AP_BattMonitor/AP_BattMonitor_Logging.cpp
The existing method just looks at the internal state, whereas if there is an external temperature set then the frontend chooses teh external temperature if it is available (i.e. ignores the "normal" temperature.
We change here to log the same value as the frontend would return.
> AP_BattMonitor: log external temperature if available

- libraries/AP_DDS/README.md
- libraries/AP_DDS/dds_xrce_profile.xml
This PR is part of a group of PRs with focus on eliminating the excessive remaps in `ardupilot_gz`, `AP_DDS` and `ardupilot_ros`
https://github.com/ArduPilot/ardupilot_gz/pull/27
https://github.com/ArduPilot/ardupilot_ros/pull/14
> AP_DDS: use /tf  instead of /ap/tf

- libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
before this change this environment variable is a string, which means anything checking it for truth will get back true even if it is empty ("") or the string zero ("0").  The existing is_periph_fw check only works because "1" != 0 - if it was "0" then it would still be considered a periph firmware
... also random flake8 fix...
> AP_HAL_ChibiOS: chibios_hwdef.py: canonicalise AP_PERIPH env define

- .gitignore
I often use a Python virtual environment to ensure I'm using the correct versions of Python modules. This PR adds the default `venv` folder to the `.gitignore`.
> gitignore: Add Python venv folder

- libraries/AP_DDS/AP_DDS_ExternalControl.cpp
The aim of this PR is for `/ap/cmd_vel` to be able to receive body frame messages with the `base_link` `frame_id`.
This check is performed first as this should be the most common use case for aerial vehicles per `ROS REP 147`
> AP_DDS: /ap/cmd_vel accepts body-frame messages

- libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.cpp
- libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.h
AP_AdvancedFailsafe:  option to continue the mission even after data link is recovered
When set MAX_COM_LOSS to a negative number, the aircraft will continue to fly the mission even after data link is recovered. This is useful when the landing sequence is part of the flight plan.
> AP_AdvancedFailsafe:  option to continue the mission even after data link is recovered

- libraries/AP_HAL_Linux/Semaphores.cpp
Make semaphores use priority-inheritance to reduce the rate of "MPU: temp reset IMU" when running fast sampling(8KHz) on linux.
> AP_HAL_Linux: make all semaphores priority-inherit

- Tools/scripts/build_options.py
- Tools/scripts/extract_features.py
- libraries/AP_DroneCAN/AP_DroneCAN.cpp
- libraries/AP_DroneCAN/AP_DroneCAN.h
this came out of this PR for 4.4.1:
https://github.com/ArduPilot/ardupilot/pull/24713
> DroneCAN: make himark servos an optional build item

- libraries/AP_DDS/Idl/ardupilot_msgs/srv/ArmMotors.idl
- libraries/AP_DDS/Idl/ardupilot_msgs/srv/ModeSwitch.idl
Add IDL for ArduPilot specific messages and services to AP_DDS.
In preparation for:
- Use message bindings to correctly size and serialise service messages. 
- Simplify integration of services into the AP / ROS 2 workflow (auto mapping of service names from DDS to ROS2).
> AP_DDS: add IDL for ArmMotors and ModeSwitch services

- libraries/GCS_MAVLink/GCS_Common.cpp
Looks to be a copy-paste error.
> GCS_MAVLink: Fix CAMERA_SETTINGS payload size check

- libraries/AP_Logger/AP_Logger_Backend.cpp
- libraries/AP_Logger/AP_Logger_Backend.h
- libraries/AP_Logger/AP_Logger_Block.cpp
- libraries/AP_Logger/AP_Logger_DataFlash.cpp
- libraries/AP_Logger/AP_Logger_File.cpp
- libraries/AP_Logger/AP_Logger_MAVLink.cpp
- libraries/AP_Logger/AP_Logger_MAVLink.h
- libraries/AP_Logger/LoggerMessageWriter.cpp
Don't need the storage size in the header
> AP_Logger: remove AP_Logger.h include in AP_Logger_Backend

- libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_mcuconf.h
There is a mistake in the H7 clock tree that results in an incorrect clock for the FDCAN peripheral when a core clock of 480 MHz is used. This changes the PLL1 Q divider such that the 80 MHz clock needed for FDCAN can be generated.
Note: The same values for `STM32_PLL1_DIVQ_VALUE` are also used in the `master` branch.
> AP_HAL_ChibiOS: Fix H7 PLL1 Q clock for 480 MHz clock (4.4 backport)

- ArduPlane/Attitude.cpp
prevent small stick offsets causing navigation errors
> Plane: use dead zone in stick mixing

- libraries/AP_TECS/AP_TECS.cpp
update_pitch_throttle can be called when update_50hz hasn't run in a very long time, or ever.  This requires a main loop rate >50Hz, and for the mode change to occur in the same loop that update_50Hz doesn't run but update_pitch_throttle does.
Tested with these patches - fails before this patch, passes after:
```
diff --git a/ArduPlane/ArduPlane.cpp b/ArduPlane/ArduPlane.cpp
index 61d76425333..63bd6fefd8d 100644
--- a/ArduPlane/ArduPlane.cpp
+++ b/ArduPlane/ArduPlane.cpp
@@ -69,7 +69,7 @@ const AP_Scheduler::Task Plane::scheduler_tasks[] = {
SCHED_TASK(navigate,               10,    150,  36),
SCHED_TASK(update_compass,         10,    200,  39),
SCHED_TASK(calc_airspeed_errors,   10,    100,  42),
-    SCHED_TASK(update_alt,             10,    200,  45),
+    SCHED_TASK(update_alt, …
```
> AP_TECS: ensure good TECS state before running update_pitch_throttle

- ArduPlane/takeoff.cpp
taildragger elevator holdown was omitted on TAKEOFF mode....this fixes it
holdown possible if setup, in auto and takeoff mode while in Flight Stage TAKEOFF and still with aux switch in FBWA
Tested by Yakman on his vehicle
> Plane:add taildrag holdown to TAKEOFF mode

- libraries/AP_ESC_Telem/AP_ESC_Telem_SITL.cpp
I noticed that ESC temp of SITL displays 0 due to the difference in units between cdeg and deg.
After this fix, I can see the value.
> AP_ESC_Telem: fix fake value of SITL ESC

- libraries/AP_Relay/AP_Relay.cpp
- libraries/SITL/SITL.cpp
- libraries/SITL/SITL.h
Adds a parameter for allowing relays to be driven by SIM on HW.
This reflects similar changes that allowed driving servo channels with SIM on HW.
> Allow SITL on HW to drive actuators

- libraries/AP_Torqeedo/AP_Torqeedo.cpp
This fixes a copy-paste error in the Torqeedo libraries error reporting.  This bug would cause two errors to be sent to the user in case the battery is too hot but worse yet it would send no message when the battery is nearly empty.
This has not been tested on real hardware because I don't currently have access to my Torqeedo motor but surely this is correct.
Thanks very much to skyfox00 for reporting this!
> AP_Torqeedo: error code reporting fix

- libraries/AP_Scripting/examples/UART_log.lua
The spaces cause issues for some log viewers, Mission planner is OK so this was not spotted in the first place.
> AP_Scripting: Examples: UART log: remove spaces in log description

- ArduCopter/afs_copter.cpp
- ArduCopter/afs_copter.h
- ArduPlane/afs_plane.cpp
- ArduPlane/afs_plane.h
- Rover/afs_rover.cpp
- Rover/afs_rover.h
- libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.cpp
- libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.h
Automatically set mode to auto when there is datalink loss in Advanced Failsafe. This is to make sure advanced failsafe is entered when Plane is flying with other autonomous modes. For example, right now when Plane is flying in Guided mode, it will not enter the specified mission item unless the mode is switched to Auto
> AP_AdvancedFailsafe: automatically set mode to auto when datalink loss

- libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/sport_aerobatics.lua
- libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Make last_trick_action_state fetch conditional on TRIK_ENABLE in plane_aerobatics.lua
and (cosmetic change for clarity) move declaration near TRIK_ACT_FN param setup in sport_aerobatics.lua.
Tested both scripts in SITL with RealFlight PA Addiction.
> bugfix for tricks-on-a-switch activation cleanup

- ArduPlane/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.h
- ArduPlane/Plane.h
- ArduPlane/commands_logic.cpp
- Tools/autotest/arduplane.py
- Tools/autotest/common.py
- libraries/AP_Mission/AP_Mission.cpp
- libraries/AP_Mission/AP_Mission.h
This also stops us converting the mavlink command into a mission item before trying to handle it.  It was the last user of the method which did the conversion from command_long into a mission command, so that method is now removed.  I factored the existing handler  to cut out the complicated conversion process.  I could have converted from command_int -> mission_cmd instead, but this seemed neater.
Critical lines in AP_Mission.cpp to do with conversion from cmd_long -> mission_item_it_t -> mission_cmd -> field values change in this PR:
```
case MAV_CMD_DO_CHANGE_SPEED:                       // MAV ID: 178
cmd.content.speed.speed_type = packet.param1;   // 0 = airspeed, 1 = ground speed
cmd.content.speed.target_ms = packet.param2;    // target speed in m/s
cmd.content.speed.throttle_pct = …
```
> Plane: accept DO_CHANGE_SPEED as command_int

- Tools/autotest/common.py
```
```
This resolves the flapping `MAV_CMD_DO_SET_REVERSE` test; it's not that tests' fault, it's this one leaving the vehicle in a state it won't seem to recover from.
> autotest: paper over problem with EKF heading not recovering

- ArduCopter/mode_circle.cpp
- libraries/AP_AHRS/AP_AHRS.cpp
- libraries/AP_AHRS/AP_AHRS.h
- libraries/AP_Common/Location.cpp
- libraries/AP_Common/Location.h
- libraries/AP_Common/tests/test_location.cpp
This work came out of work sponsored by SpektreWorks
> AP_Common: use AHRS to get Locations from origin-offset

- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
- Tools/autotest/arducopter.py
Also add regression tests for Winch mavlink commands
> Allow MAV_CMD_DO_WINCH to be accepted via COMMAND_INT

- libraries/AP_Mount/AP_Mount_Siyi.cpp
- libraries/AP_Mount/AP_Mount_Siyi.h
The Siyi driver is in active development, and may be using features that are only available in the latest firmware. This PR adds a check to make sure that the connected Siyi gimbal is running a supported firmware version.
Tested on Siyi A8.
FYI: @rmackay9
> AP_Mount: In Siyi, add check for minimum supported firmware version

- libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp
it returns double, which will not fit into this float
> AP_NavEKF3: do not use fmaxF on floating point values

- libraries/AP_GPS/AP_GPS_SIRF.cpp
- libraries/AP_GPS/GPS_Backend.cpp
- libraries/AP_GPS/GPS_Backend.h
Tested with this patch:
```
--- a/libraries/AP_GPS/GPS_Backend.cpp
+++ b/libraries/AP_GPS/GPS_Backend.cpp
@@ -157,6 +157,21 @@ AP_GPS_Backend::inject_data(const uint8_t *data, uint16_t len)
void AP_GPS_Backend::_detection_message(char *buffer, const uint8_t buflen) const
{
+    const int32_t values[] { 0, 1, INT32_MAX, INT32_MIN, 17, 123456789};
+    for (auto value : values) {
+        if (swap_int32(value) != (int32_t)htobe32(value)) {
+            abort();
+        }
+    }
+    gcs().send_text(MAV_SEVERITY_INFO, "swap32 OK");
+    const int16_t values16[] { 0, 1, INT16_MAX, INT16_MIN, 17, -17};
+    for (auto value : values16) {
+        if (swap_int16(value) != (int16_t) htobe16(value)) {
+            abort();
+        }
+    }
+    gcs().send_text(MAV_SEVERITY_INFO, "swap16 OK");
+ …
```
> AP_GPS: replace utility functions with compiler builtins

- libraries/AP_Logger/AP_Logger.h
- libraries/AP_Logger/LogFile.cpp
- libraries/AP_Logger/LogStructure.h
Can now sensibly log these now the RC_Channels library has the methods
This always logs RCI2 now.  Could make a fresh message.
> AP_Logger: log valid-input and in-rc-failsafe

- Tools/AP_Periph/Parameters.cpp
- Tools/AP_Periph/Parameters.h
- Tools/AP_Periph/battery.cpp
This will allow you to keep Battery instance info internal and not send them over CAN as a BATTERYINFO msg.
Use-case:
1 - Smart-battery or a battery with sub-packs or a periph that is also acting as a power manager. On this periph I have multiple battery instances and one of them is BATTn_MONITOR=10 for SUM. I don't want to consume CAN bandwidth or confuse other systems with sending battery CAN packets of batteries that don't apply to systems outside of the periph. I only want to send the SUM battery instance over the CAN bus.
2- Periph-based ESC or Servo. You want feedback that also includes voltage/current. This allows you to use AP_BattMon without having to spam the bus with your battery data as if you're a battery supply. You can make your own Acturator::Status or ESC:; status …
> Periph: Add BATT_HIDE_MASK to not broadcast (hide) battery instances

- libraries/AP_OSD/AP_OSD.cpp
- libraries/AP_OSD/AP_OSD.h
- libraries/AP_OSD/AP_OSD_Screen.cpp
add inverted flight indication (flashing horizon line) and reverses horizon movement when inverted....currently an option in this PR but we may want to make it the default mode even if its a change in behavior...or just change to it instead of the current Betaflight copied behavor...I think that having the option but defaulting it is probably best, but dont have strong feelings either way
tested in SITL
https://youtu.be/RZamcZy_5Zs
> AP_OSD:add Aviation style AH option

- libraries/AP_Mount/AP_Mount_Siyi.cpp
Order of rotation for Siyi gimbals is `(yaw, roll, pitch)`, which is 312 order. `Quaternion::from_euler()` function assumes a 321 order of rotation `(yaw, pitch, roll)`.
Currently a draft, because:
* I need to investigate the handling of the quaternions coming in; and
* we need to check if this problem affects other gimbals.
FYI: @rmackay9, @tridge, @priseborough
> AP_Mount: In Siyi, fix calculation of attitude quaternion

- ArduCopter/mode.cpp
- libraries/AC_PrecLand/AC_PrecLand.cpp
- libraries/AC_PrecLand/AC_PrecLand.h
This allows user to skip slowing down the speed of the copter automatically when the vehicle is 2m above the target.
> Allow Precland fast descend

- Tools/ros2/ardupilot_sitl/package.xml
This was missing when I tried testing #24880
> Tools: Add missing runtime dependency for running ardupilot_sitl

- Tools/autotest/arducopter.py
the floating/double changes appear to have cause this to start to flap
> autotest: loosen constrain on proximity distance message

- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
- ArduPlane/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.h
- ArduSub/GCS_Mavlink.cpp
- ArduSub/GCS_Mavlink.h
- Blimp/GCS_Mavlink.cpp
- Blimp/GCS_Mavlink.h
- Rover/GCS_Mavlink.cpp
- Rover/GCS_Mavlink.h
- Tools/autotest/arduplane.py
- Tools/autotest/common.py
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
I've stepped through the code which the new tests don't cover.
> Support preflight calibration ia command_int 

- ArduPlane/Attitude.cpp
- ArduPlane/quadplane.cpp
- ArduPlane/quadplane.h
- libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
- libraries/AC_AttitudeControl/AC_AttitudeControl.h
- libraries/APM_Control/AP_PitchController.cpp
- libraries/APM_Control/AP_PitchController.h
- libraries/APM_Control/AP_RollController.cpp
- libraries/APM_Control/AP_RollController.h
- libraries/AP_AHRS/AP_AHRS_Logging.cpp
The idea behind this PR is to allow higher angle P in VTOL modes - which is proven to provide superior disturbance rejection in copters - without compromising the stability of transitions. Experimentation shows that plane tunes tend to have very low angle P tunes (1/time constant - typically 2 in the default parameter setup), and relatively high feed forward gains. This combination means that in VTOL modes oscillation is driven by the fixed-wing feed forward component and the VTOL controller is constantly having to compensate for this. Solutions to date have focused on backing off the VTOL gains (angle P in particular) based on airspeed, but this leads to lowest common denominator tunes that do not oscillate but have poor position holding capability. Instead this PR scales the angle P …
> Feed-forward scaling based on angle gain ratio

- libraries/AP_VideoTX/AP_Tramp.h
- libraries/AP_VideoTX/AP_VideoTX.cpp
- libraries/AP_VideoTX/AP_VideoTX.h
Added frequency change support for Matek VTX-1G3SE 1.2/1.3GHZ.
IRC Tramp protocol.
Frequencies:
VTX_BAND = 6 // 1G3_A
1080, 1120, 1160, 1200, 1240, 1280, 1320, 1360
VTX_BAND = 7 // 1G3_B
1080, 1120, 1160, 1200, 1258, 1280, 1320, 1360
Works with Matek VTX 1G3SE and green version.
> AP_VideoTX: Added frequency change support for Matek VTX-1G3SE. IRC Tramp protocol.

- libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.cpp
- libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.h
tested by running SITL with Gazebo and QGroundControl
> AP_AdvancedFailsafe: make GCS failsafe timeout a parameter

- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
- Tools/autotest/arducopter.py
... also modified the autotest to run both command-long and command-int versions.
> Copter: allow motor tests to be triggered with COMMAND_INT

- Tools/autotest/common.py
- don't echo statustexts back to autopilot, there's no point
- send all of autotest message rather than just first chunk
> autotest: improve STATUSTEXT handling

- libraries/AP_Notify/AP_Notify.cpp
- libraries/AP_Notify/AP_Notify.h
DiscreteRGB was a notify driver we had, but never instantiated. This allows you to request it via AP_Periph. This was tested using an AP_Periph board here based on a F405. The simple target is to simply have a separate GPIO line controlled for each color.
> AP_Notify: Reenable the DiscreteRGB backend

- libraries/AP_Notify/AP_Notify.cpp
- libraries/AP_Notify/AP_Notify.h
- libraries/AP_Notify/AP_Notify_config.h
- libraries/AP_Notify/DiscreteRGBLed.cpp
- libraries/AP_Notify/DiscreteRGBLed.h
```
Durandal                       0      *           0       0                 0      0      0
MatekF405                      0      *           0       0                 0      0      0
Pixhawk1-1M-bdshot             0                  0       0                 0      0      0 …
```
> AP_Notify: tidy use of DiscreteRGB

- libraries/AP_Mount/AP_Mount_Siyi.cpp
Removes the braced list initialisers because the environment tests are failing.
Looks like older compiler versions don't support this and the build is failing.
> AP_Mount: Fix brace enclosed initializer list

- libraries/GCS_MAVLink/GCS.cpp
GCSs will know we have no baros on-board, as will the RC telemetry library
Alternative to https://github.com/ArduPilot/ardupilot/pull/25001/files
> GCS_MAVLink: correct sensors when no baros found

- libraries/AP_Mount/AP_Mount_Siyi.cpp
- libraries/AP_Mount/AP_Mount_Siyi.h
Update the Siyi driver to use the reported info from the gimbal (from the "Acquire Gimbal Configuration Information" (0x0A) message), rather than the last values sent. Primary reason is to stop repeatedly sending `set_lock()`.
Also changes `set_lock()` to `set_motion_mode()` so that we can set it to FPV mode if desired (which partially addresses https://github.com/ArduPilot/ardupilot/issues/22900).
Minimally tested on Siyi A8.
> AP_Mount: In Siyi, use config info received from gimbal

- libraries/AP_SmartRTL/AP_SmartRTL.cpp
Currently `_last_position_save_ms` is not set when `set_home` is called. This means if the next point fails to add, due to failing to get the semaphore, then it has been more than the time out since boot, or since the last point was added in a previous flight SRLT will deactivate reporting "buffer full", in this case its actually just a failure to get the semaphore one time. 
https://github.com/ArduPilot/ardupilot/blob/23150a0830cb5af405754db9af7e105d6192a3aa/libraries/AP_SmartRTL/AP_SmartRTL.cpp#L265-L270
This can be seen in the log as the addition of a point (action 0) followed by a semaphore fail (action 3) then a deactivate (action 10).
> AP_SmartRTL: fix disable if second point fails to add

- libraries/AP_OSD/AP_OSD.cpp
control reaches end of non-void function
> AP_OSD: correct compilation when OSD compiled out

- Tools/AP_Periph/AP_Periph.h
- Tools/AP_Periph/can.cpp
- Tools/AP_Periph/rc_out.cpp
Add define HAL_PERIPH_ALWAYS_ARMED to always be safety_off for Periph.
I've had trouble with a race condition on a periph with a PWM/ESC output.
Scenario:
- Autopilot is sending ESC/SERVO commands fast (like 20-50Hz)
- Autopilot is sending armed state slow (1-2Hz)
- on autopilot I switch to AUTO/TAKEOFF and then arm.
- over CAN we see the ESC values ramp up quickly but the disarmed msg hasn't gone out yet.
- The Periph is still disarmed but is getting ESC signals going up
- The Peirph then gets the ARMED state change and immediately outputs this rising (maybe always maxxed) throttle.
- ESC is just now getting it's first valid PWM signal but it needs a low PWM to initialize and thus rejects the PWM
Notes:
- This is equivalent to setting BRD_SAFETYENABLE = 0 and ARMING_REQUIRE = 0 and …
> AP_Periph: add AP_PERIPH_SAFETY_SWITCH_ENABLED

- ArduPlane/tailsitter.cpp
If no pitch control surfaces are present in motors only assist we will now leave the motor I term active, this means the motors can close a steady state error.
We now have this option for both FW pitch and FW yaw. These are the "strong" motor control axis. This allows control surfaces to still be used for FW roll (VTOL yaw), this is the weak axis of motor control where using motor I term can quickly lead to large splits and output saturation.
> Plane: Tailsitter: use motor I term for pitch in assist if no surfaces are setup

- libraries/AP_DroneCAN/AP_DroneCAN.cpp
- libraries/AP_DroneCAN/AP_DroneCAN.h
- libraries/AP_Mount/AP_Mount_Xacti.cpp
- libraries/AP_Mount/AP_Mount_Xacti.h
This PR enhances the Xacti driver by displaying the gimbal's firmware version and also error status to the user.  It also sets the camera's date and time which means the date/time on the video and image files is correct.
Changes include:
- AP_DroneCAN supports getting and setting string parameters
- AP_Mount_Xacti gets these enhancements
- request_firmware_version() method requests the FirmwareVersion parameter at 1hz until received
- request_status() method requests the Status parameter every 3 seconds
- handle_param_get_set_response_string() processes the replies:
- the FirmwareVersion string is decoded and displayed to the user via send_text() and also included in the CAMERA_INFORMATION mavlink message
- the Status message is backed up to a new _status structure and changes to the …
> AP_Mount/AP_DroneCAN: Xacti accepts gimbal firmware version and status

- libraries/AP_OSD/AP_OSD_MSP_DisplayPort.h
Update the BF symbol translation for DJI DisplayPort when using O3 vehicle units...
The original translation table was based on an obsolete BF font set and has multiple errors....this corrects these plus enhances with better icons some panels...
unfortunately DJI O3 mode cannot record the OSD, so I had to wedge my phone into the goggles to show the before and after images..
This should be a backport into 4.4 since its no risk and does not change function, only a table of icon lookups...
CURRENT
After PR
> Update/correct DisplayPort BF MSP symbols

- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
- Tools/autotest/arducopter.py
tested in SITL using the existing autotest, which has been adjusted to test for both
>  ArduCopter: handle DO_PARACHUTE as both command_long and command_int 

- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
- Tools/AP_Periph/GCS_MAVLink.cpp
- Tools/AP_Periph/GCS_MAVLink.h
- Tools/autotest/common.py
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
Tested in SITL.  Forced reboot still works.
Also tweaked autotest suite to use the cmd-int reboot ordinarily.
> Handle MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN as INT or LONG

- Tools/scripts/build_options.py
- Tools/scripts/extract_features.py
Temporary (hopefully) fix that allows Plane to remove AFS from a build, and not show it as an option on Copter/Rover(which its not at this point since the defines are different)....adding AFS to those vehicles will require a manual intervention, and Randy should be fine with that since he sees no reason for AFS in Copter/Rover he's told me
> Tools: limit AFS to Plane and fix symbol lookup

- libraries/AP_AHRS/AP_AHRS.cpp
- libraries/AP_AHRS/AP_AHRS.h
- libraries/AP_AHRS/AP_AHRS_Backend.h
- libraries/AP_AHRS/AP_AHRS_DCM.cpp
- libraries/AP_AHRS/AP_AHRS_DCM.h
- libraries/AP_AHRS/AP_AHRS_External.cpp
- libraries/AP_AHRS/AP_AHRS_External.h
- libraries/AP_AHRS/AP_AHRS_SIM.cpp
- libraries/AP_AHRS/AP_AHRS_SIM.h
with the change to cache results inside AP::ahrs().state we no longer need to worry about the backend's attempts to project the last-known-location forwards according to amount of time elapsed since that last-known-location was calculated.
Changes the AHRS backend requirements such that they not longer need to provide the `get_location` method, instead supplying it in their (hopefully coherent) results structure.
Also moves the backends and the results structures to the end of the header for alignment reasons (changes in the Backend results structure size was causing compiler conniptions in terms of its alignments).
> AP_AHRS: return location inside backend_results structure

- libraries/AP_AHRS/AP_AHRS.cpp
the comment here was incorrect; we do not need EKF3 to have a good wind estimate to fall back to DCM here.
Also restructure the code to make it more obvious that this is what's going on.
> AP_AHRS: make comment match code behaviour in airspeed DCM-fallback

- libraries/AP_AHRS/AP_AHRS.cpp
- libraries/AP_AHRS/AP_AHRS.h
```
given that DCM doesn't specify to use the primary accel or gyro when fetching the data from the Ins library, it shouldn't be special-cased here when asked what the primary IMU and accel are.  Note that this was asking for the *configured* backend type, rather than the active EKF type, making these clauses even stranger.
This also changes the definition of the "primary IMU index" to be whichever gyro is active rather than the accel.  Since we don't currently split primary gyro/primary accel, this is a reasonable change.
```
Also remove `get_primary_IMU_index` from the public interface.  In the case that we ever split gyros and accels we will want to be able to e.g. have separate position offsets for each.
```
Durandal                       -72    *           -72     -72 …
```
> AP_AHRS: simplify primary/accel indexes

- libraries/AP_AHRS/AP_AHRS.cpp
- libraries/AP_AHRS/AP_AHRS_DCM.cpp
```
Durandal                       0      *           0       0                 0      0      0
MatekF405                      0      *           0       0                 0      0      0
Pixhawk1-1M-bdshot             0                  0       0                 0      0      0 …
```
> Move AHRS functions out of AP_AHRS_DCM.cpp

- libraries/AP_HAL_ChibiOS/hwdef/MambaF405v2/hwdef.dat
Diatone sent me a 8" quad with a MambaF405v2 in it and I ran into all sorts of problems:
- Pin inversion was inverted
- Battery setup was wrong
- NeoPixel output wasn't configured
- Camera control wasn't pinned out
- Tramp was not enabled even though this is the default protocol for Diatone
- RSSI pin not defined
- Missing UARTs prevented GPS working on SERIAL6 by default
> Mamba F405 v2 fixes

- Tools/AP_Periph/AP_Periph.h
- Tools/AP_Periph/Parameters.cpp
- Tools/AP_Periph/Parameters.h
- Tools/AP_Periph/can.cpp
This allows us to mirror CAN traffic between ports on demand. This allows you to run a separate CAN bus off of an AP_Periph node. This can be very useful for managing CAN bus stubs.
This was tested with CubeOrange-periph with `define HAL_PERIPH_CAN_MIRROR` added to the hwdef. I then connected a CubeOrangePlus to a Zubax babel (let's call this `BABEL1`), and the other babel port to the CubeOrange-periph on CAN1. From the periph node I then connected CAN2 to another babel (let's call this `BABEL2`). Without any changes `BABEL2` can only see data from the AP_Periph node, and can't see the cube, or `BABEL1`. If I then set the parameter and reboot `BABEL2` is able to see both the flight controller, and the `BABEL1`l, and from `BABEL1` I can actually see `BABEL2`.
> Tools: AP_Periph: Add CAN_MIRROR

- libraries/AP_AHRS/AP_AHRS.cpp
- libraries/AP_AHRS/AP_AHRS_Backend.h
over-kill, and can be derived from backend biases if required
I think this can be rather more-simplified if we can include that rotation-into-vehicle-body-frame in the DCM result; I wonder if having these in separate files caused this discrepancy...
> AP_AHRS: remove un-needed AP_AHRS_Backend::getCorrectedDeltaVelocityNED

- libraries/AP_AHRS/AP_AHRS.cpp
- libraries/AP_AHRS/AP_AHRS.h
- libraries/AP_AHRS/AP_AHRS_Backend.cpp
- libraries/AP_AHRS/AP_AHRS_Backend.h
these don't use any information from the specific backend, but they are called within the backends so making them static on that class is handy
> AP_AHRS: make a pair of methods static on AP_AHRS_Backend

- ArduPlane/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.h
- Tools/autotest/arducopter.py
- Tools/autotest/common.py
- Tools/autotest/quadplane.py
Changed autotest to also test quadplane motor test.
Also tested in SITL as we don't explicitly check we only run the specified number of motors in the autotest.
> Plane: Accept MAV_CMD_DO_MOTOR_TEST as COMMAND_INT as well as COMMAND_LONG

- libraries/AP_TemperatureSensor/AP_TemperatureSensor_Params.cpp
> AP_TempertureSensor:clarify temp source for pitot tube

- libraries/AP_HAL/RCOutput.cpp
- libraries/AP_HAL/RCOutput.h
- libraries/AP_HAL/tests/test_prescaler.cpp
- libraries/AP_HAL_ChibiOS/RCOutput.cpp
- libraries/AP_HAL_ChibiOS/RCOutput.h
Experimentation shows that BLHeli_S wants a prescaler that gives at least the requested clock frequency. This is particularly true for BlueJay ESCs. Our old (incorrect) algorithm was actually doing this, but now that the algorithm has been corrected it is no longer working.
> Correct prescaler calculation for BLHeli_S

- libraries/AP_HAL/AP_HAL_Boards.h
Our notch constraints prevents using the triple notch per motor with a harmonic. With one IMU this is perfectly acceptable from a performance perspective
> AP_HAL: relax F4 notch constraints slightly to allow triple notch on quads

- libraries/AP_CANManager/AP_CANManager.cpp
- libraries/AP_CANManager/AP_CANManager.h
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
Tested in SITL using `quad-can` and dronecan_gui_tool, hacking up pydronecan to send command_int in place of command_long
> Handle CAN_FORWARD as both command_INT and COMMAND_LONG

- libraries/AP_HAL_ChibiOS/Util.cpp
AP_Periph debug builds fail because InternalError is not being included - The Util class uses InternalError.
AP_Periph debug is built using `./waf configure --board f405-MatekGPS --debug AP_Periph` 
The include was being passed up from Logger->LoggerMessageWriter->LoggerBackend->Bitmask. Periph Builds tend not to have HAL_LOGGING_ENABLED, and so the include was not present.
> AP_HAL_ChibiOS: Explicitly include InternalError in Util

- libraries/SITL/SIM_BalanceBot.cpp
... or at least closer to it.
We were hard-resetting the yaw to zero when the vehicle was upright.  That makes for huge simulated gyro rates, and that means the differences between the gyros can be huge sample-to-sample, so we can get gyros-inconsistent errors.
Fix things so we don't reset yaw at the same time as pitch, and also twist the vehicle to point North again when disarmed.
Before:
After:
> Fix balancebot yaw reset to be kinimatically consistent

- libraries/AP_GPS/AP_GPS.cpp
- libraries/AP_GPS/AP_GPS_DroneCAN.cpp
- libraries/AP_GPS/AP_GPS_ERB.cpp
- libraries/AP_GPS/AP_GPS_NMEA.cpp
- libraries/AP_GPS/AP_GPS_NOVA.cpp
- libraries/AP_GPS/AP_GPS_SBF.cpp
- libraries/AP_GPS/AP_GPS_SIRF.cpp
- libraries/AP_GPS/AP_GPS_UBLOX.cpp
- libraries/AP_GPS/GPS_Backend.cpp
- libraries/AP_GPS/GPS_Backend.h
this allows a lot more drivers to use the GPS_DRV_OPTION but to use ellisoid height. Particularly useful for DroneCAN GPS modules
using ellisoid height instead of AMSL is useful in some specialised application
> AP_GPS: implement the GPS_DRV_OPTION for ellisoid height in mode drivers

- Tools/autotest/arducopter.py
we could arrive back at our home location and stop before enough time passed to satisfy the test.  i.e. doing exactly the same steps out and back again without allowing for differences in timing leads to random failure
> autotest: fix DO_CHANGE_SPEED test

- libraries/AP_Camera/AP_Camera.cpp
- libraries/AP_Camera/AP_Camera.h
- libraries/AP_Camera/AP_Camera_Backend.cpp
- libraries/AP_Camera/AP_Camera_Backend.h
- libraries/AP_Mission/AP_Mission.cpp
- libraries/AP_Mission/AP_Mission.h
- libraries/AP_Mission/AP_Mission_Commands.cpp
- libraries/GCS_MAVLink/GCS_Common.cpp
This adds support for [MAV_CMD_IMAGE_STOP_CAPTURE](https://mavlink.io/en/messages/common.html#MAV_CMD_IMAGE_STOP_CAPTURE).  This is from the camera enhancements list  #23151 
Thanks to @trolledbypro for initial work on this
This has been tested latest in Mission and with simple mavlink command. (Single camera is used) Multiple should work.
> AP_Mission/AP_Camera: add mavlink STOP_CAPTURE/START_CAPTURE command support and fixes to existing implementation

- libraries/AP_Generator/AP_Generator_IE_2400.cpp
- libraries/AP_Generator/AP_Generator_IE_2400.h
- libraries/AP_Generator/AP_Generator_IE_FuelCell.cpp
- libraries/AP_Generator/AP_Generator_IE_FuelCell.h
- libraries/AP_Generator/AP_Generator_RichenPower.cpp
- libraries/AP_Generator/AP_Generator_RichenPower.h
Tested for compilation (when logging compiled out) only.  Which it does.
``` …
```
> AP_Generator: use HAL_LOGGING_ENABLED

- libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp
> AP_AHRS: fill in error string when invalid backend specified

- Tools/autotest/arducopter.py
we only need to see the sample once when hold is 0
> autotest: tweak test_mount_pitch win condition

- ArduPlane/Log.cpp
NFC.....this has some of us confused when analyzing logs since CTUN.As can be "synthetic" also when no airspeed sensor is used while CTUN.As is the cannonical airspeed, synthetic or measured
> Plane:clarify CTUN.SAs message meaning

- ArduPlane/quadplane.cpp
- libraries/AP_TECS/AP_TECS.cpp
was causing some confusion to a user
> Correct/expand metadata for Q_OPTION bit12 and TECS_SYNAIRSPEED

- libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Solo.cpp
- libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Solo.h
Added support for extended cell count.
This change is perfectly backwards compatible with 3DR Batteries as well as BMSone.
The addition enables the BMSOne to monitor up to six cells.
> SMBus :expanded SoloBMS to 6s - providing support for madhacker BMSOne

- AntennaTracker/Parameters.cpp
- ArduPlane/Log.cpp
- Blimp/Log.cpp
- Blimp/Parameters.cpp
- libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp
- libraries/AC_AttitudeControl/AC_AttitudeControl_Sub.cpp
- libraries/AC_AttitudeControl/AC_PosControl.cpp
- libraries/AC_CustomControl/AC_CustomControl_PID.cpp
- libraries/AC_PID/AC_PID.cpp
- libraries/AC_PID/AC_PID.h
- libraries/AC_PID/AP_PIDInfo.h
- libraries/APM_Control/AP_PitchController.cpp
- libraries/APM_Control/AP_RollController.cpp
- libraries/APM_Control/AP_YawController.cpp
- libraries/APM_Control/AR_AttitudeControl.cpp
- libraries/AP_Logger/LogFile.cpp
- libraries/AP_Logger/LogStructure.h
- libraries/AP_WheelEncoder/AP_WheelRateControl.cpp
This feature lets the user limit the maximum PD output of the PID object. This is useful in large aircraft or systems where the actuators are slew limited.
> Add PID object PD limit

- libraries/AP_Camera/AP_Camera.cpp
- libraries/AP_Camera/AP_Camera.h
- libraries/AP_Camera/AP_Camera_Mount.cpp
- libraries/AP_Mission/AP_Mission_Commands.cpp
This is a follow-up to PR https://github.com/ArduPilot/ardupilot/pull/24772 to fix some issues found with the [IMAGE_START_CAPTURE](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1670) and  [IMAGE_STOP_CAPTURE](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1693) support both when sent as real-time commands and when included in missions.
The issues fixed are:
1. IMAGE_START_CAPTURE with zero "interval" and "total images" fields would lead to potentially huge numbers of images being taken.  With this PR we only take one picture.  This may be slightly unintuitive in that an IMAGE_START_CAPTURE with "Total Images = 0" has the same effect as "Total Images = 1" but I think it is safer.
2. IMAGE_STOP_CAPTURE was …
> Camera: image start/stop capture fixes

- libraries/AP_Scripting/examples/winch-test.lua
This is a follow-up to PR https://github.com/ArduPilot/ardupilot/pull/25093 to improve usability of the winch ahead of the [Japan Innovation Challenge](https://japan-innovation-challenge.com/en/) in a couple of weeks.
This simplifies the winch-test lua script and brings it more inline with other newer scripts:
1. The SRV_SRC_FN param (which allowed the target rate to be set from a servo **output**) is replaced with RC_FUNC (which allows the target rate to be set an RC auxiliary function switch position and/or MP's AuxFunction screen).   A year ago we could not access the auxiliary switch positions sent from Mission Planner's Aux Function page.
2. Added parameter descriptions ahead of possibly moving this to an applet.
3. The script gets a small welcome message
This has been tested on real …
> AP_Scripting: winch-test simplification

- libraries/AP_Scripting/AP_Scripting.cpp
- libraries/AP_Scripting/AP_Scripting.h
- libraries/AP_Scripting/generator/description/bindings.desc
- libraries/AP_Scripting/generator/src/main.c
- libraries/AP_Scripting/lua_bindings.cpp
- libraries/AP_Scripting/lua_scripts.cpp
First step towards running scripting with more stuff disabled. This also fixes a bug where all of the `GCS` singleton depended on `HAL_HIGH_LATENCY2_ENABLED`. To support that per method dependencies are now supported. There are a number of existing  methods that could have dependencies added in the future.
> AP_Scripting: add some missing dependencies and support per method

- libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
- libraries/AP_SerialManager/AP_SerialManager.cpp
- libraries/AP_SerialManager/AP_SerialManager.h
This fixes the issue where EMPTY serial ports in hwdef will still get SERIALx_ parameters leading to all sorts of confusion
> Only provide config for serial ports that exist

- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
- Tools/autotest/arducopter.py
Adjusted the auto-test to run as both int and long.
```
2023-09-20 16:09:28.779 MAVC {TimeUS : 57926820, TS : 1, TC : 1, SS : 250, SC : 250, Fr : 5, Cmd : 115, P1 : 269.0, P2 : 10.0, P3 : 1.0, P4 : 0.0, X : 0, Y : 0, Z : 0.0, Res : 0, WL : 0}
2023-09-20 16:10:06.969 MAVC {TimeUS : 96117371, TS : 1, TC : 1, SS : 250, SC : 250, Fr : 5, Cmd : 115, P1 : 329.0, P2 : 2.0, P3 : 1.0, P4 : 0.0, X : 0, Y : 0, Z : 0.0, Res : 0, WL : 0}
```
(WL is zero, meaning it was received as an int)
>  Copter: allow MAV_CMD_CONDITION_YAW to be run as COMMAND_INT 

- ArduCopter/ReleaseNotes.txt
- ArduCopter/version.h
- ArduPlane/ReleaseNotes.txt
- ArduPlane/version.h
This is the Copter-4.4.1 release which has been rebased on the Plane-4.4 branch and is otherwise the same as the 4.4.1-beta2.
> Copter: 4.4.1 release

- libraries/AP_Winch/AP_Winch.cpp
- libraries/AP_Winch/AP_Winch.h
- libraries/AP_Winch/AP_Winch_Backend.h
- libraries/AP_Winch/AP_Winch_Daiwa.cpp
- libraries/AP_Winch/AP_Winch_Daiwa.h
This PR aims to ease the use of the Daiwa winch in particular which I'm planning to use at the [Japan Innovation Challenge](https://japan-innovation-challenge.com/en/) in a couple of weeks.
1. WINCH_OPTIONS parameter is added with two bits
- bit0: Spin freely on startup allows the line to be pulled out after startup.  This is the current default but is actually quite annoying because we need to remember to disengage the clutch before takeoff or the package will likely be left on the ground.
- bit1: Verbose output sends text to the user when any important state of the winch changes (healthy, moving up or down, clutch position, line length).  In previous competitions we've stared at the WINCH_STATUS message but it's tough to interpret in the heat of the moment (see below)
By the way, I …
> AP_Winch: Options param for init state and verbose output

- libraries/AP_Baro/AP_Baro_DPS280.cpp
- libraries/AP_Baro/AP_Baro_DPS280.h
DPS280/DPS310 use the same driver(AP_Baro_DPS280.cpp/h), but it is necessary to distinguish between the two.
> AP_Baro: Fix GCS DPS310 HWID issue

- ArduCopter/mode_zigzag.cpp
Ternary operators are numerous in the ArduPilot code.
There is no reason not to make this method a ternary operator.
I would change it to a ternary operator.
> Copter: Change to ternary operator

- libraries/AP_Logger/LoggerMessageWriter.cpp
- libraries/AP_Logger/LoggerMessageWriter.h
- libraries/RC_Channel/RC_Channel.h
- libraries/RC_Channel/RC_Channels.cpp
This bring a bunch of small fix on AP_Logger, mostly warning reported by clang
Switch NULL to nullptr
Correct on instantiation order
Make explicit comparison for strncmp
Make out_of_time_for_writing_messages() explicitly virtual
> Fix log various

- Tools/AP_Periph/esc_apd_telem.cpp
le16toh() returns an unsigned type, which keeps the number as positive when cast to float. It needs to be explictly converted to a signed number first. Without this very small negative numbers are reported as insanely high currents.
Tested with real hardware.
> AP_Periph: Fix bad conversion of APD ESC telemetry

- libraries/AP_ICEngine/AP_ICEngine.cpp
- libraries/AP_ICEngine/AP_ICEngine.h
Basically I don't want to start the engine while disarmed. Currently it's a flick of a switch away. To replicate the start while disarmed in SITL set `ICE_IDLE_PCT` to a non 0 value like 20, set the start channel and raise it. You can then set ICE_OPTIONS 8 and it won't do this anymore unless you have armed the aircraft.
This has only been SITL tested. I have some follow ups that will build off of this.
> AP_ICEngine: Add an option to disable starting while disarmed

- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
- ArduSub/GCS_Mavlink.cpp
- ArduSub/GCS_Mavlink.h
- Blimp/GCS_Mavlink.cpp
- Blimp/GCS_Mavlink.h
- Tools/autotest/arducopter.py
- Tools/autotest/arduplane.py
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
... add tests for same.
Blimp and Sub have identical "disarm" code to Copter.
> Handle MAV_CMD_DO_FLIGHT_TERMINATION as both long and int

- libraries/SITL/SITL.cpp
Requires https://github.com/ArduPilot/mavlink/pull/329
This brings in the upstream mavlink SIM_STATE with integer lat/lng and sends that message.
Authored by @samuelctabor
> SITL: update SIM_STATE msg to use integer lat/lng

- libraries/AP_GPS/AP_GPS.cpp
- libraries/AP_GPS/AP_GPS_FixType.h
useful when you need nice symbols for the numbers, but are not compiling the GPS headers in
> AP_GPS: add an AP_GPS_FixType header

- Tools/AP_Bootloader/board_types.txt
I erroneously used the wrong one
> AP_Bootloader: update board id for TMotor H7

- Tools/autotest/common.py
This is confusing as it doesn't actually query the autopilot for the rate, which it can (via `GET_MESSAGE_INTERVAL`)
> autotest: rename get_message_rate to measure_message_rate

- libraries/AP_TECS/AP_TECS.cpp
this fixes a state where we either cannot climb or descend in an uncontrolled manner in a TECS controlled mode
the conditions under which this happened were:
- _use_synthetic_airspeed_once was true due to quadplane takeoff
- we left _thr_clip_status as MAX from previous use of synthetic airspeed
- then run without airspeed
note that this can also impact users with an airspeed sensor if they disable it or it fails in flight, particularly during a climb
> AP_TECS: fixed descent or lack of climb bug

- libraries/AP_GPS/AP_GPS.cpp
users with busy CAN bus often get significantly lower GPS rates on a  moving baseline rover, preventing arming. This PR relaxes the required frame rate as the EKF is quite happy with 3Hz yaw and the yaw is the only data consumed from a moving baseline rover
This PR also prevents us doing blending when using moving baseline yaw, as it makes no sense
> GPS: lower required rate for moving baseline rover

- libraries/AP_Scripting/drivers/EFI_Halo6000.lua
allows for log analysis of current/voltage
> AP_Scripting: added logging to EFI_Halo6000.lua driver

- .github/workflows/test_size.yml
Add KakuteF7 and MatekH743-bdshot to the test size boards to represent boards intended for FPV a bit better.
I realised that the Matek board doesn't have the FPV include because that is specifically for 1MB boards. But since the only other H743 board we have there is the Durandal (which is quite different since it has an IOMCU) I thought it would be good to have it in there in any case.
Added the KakuteF7 since that one does have the FPV include.
> Add KakuteF7 and MatekH743-bdshot to the test size boards

- libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp
This will be useful when we move to allowing telemetry from periph
> AP_RCTelemetry: remove some uses of gcs singleton

- libraries/AP_Motors/AP_MotorsMulticopter.cpp
- libraries/AP_Motors/AP_MotorsMulticopter.h
This relates to #20354 and allows you to have a separate spool down timer which can be much shorter then spooling up. If it's set to 0 then we will use the spool up time.
As usual with parameter names, I'm open to suggestions, there just wasn't quite enough space to get the name in there well.
This was tested with a scope on the motor outputs, and parameter manipulation.
> AP_Motors: Add a seprate spool down time, if it's 0 use spool up time

- Tools/scripts/build_options.py
- Tools/scripts/extract_features.py
Add OpenDroneID to build_option.py
This is on top of PR https://github.com/ArduPilot/ardupilot/pull/25163
> Tools: add OpenDroneID to build_option.py

- libraries/AP_InertialSensor/AP_InertialSensor.cpp
- libraries/AP_InertialSensor/AP_InertialSensor.h
- libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
- libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
This expands the capability of raw sensor logging to allow post filter and pre-post. If the board can keep up with it raw sensor is much nicer than batch logging.
- logs as float, much less quantization noise
- its continuous so you can change FFT window size after the fact, also much better for seeing how the frequency tracking is doing
- Pre-post is of the same samples so a true comparison can be made in dynamic flight
This re-uses the batch sampler options, which means we loose this functionality if batch sampler is compiled out. This will be a change in behavior if users have left over options from filter setup but now have disabled the batch mask. We could also add a new param for just raw sensor logging, this would allow us to add a new bits "primary IMU only" and "gyro only" that …
> AP_InertialSensor: use batch logging options to allow pre-post raw gyro logging

- libraries/AP_Mount/AP_Mount_Xacti.cpp
- libraries/AP_Mount/AP_Mount_Xacti.h
This PR is built on top of https://github.com/ArduPilot/ardupilot/pull/25075
This improves Xacti's picture taking reliability in two ways:
1. Set parameter commands are put in a queue before being sent to ensure that they are spaced at least 20ms apart from any other commands sent to the gimbal.
2. If the camera reports that the time is not set, the driver resends the time
This has been tested on real hardware to ensure that existing features (take picture, record video, zoom, focus) all still work and that 100 pictures can reliably be taken.  This was done with a short mission shown below.
Below are before vs after screen shots showing that before only 95 pics were taken and the date/time of the files was incorrect.  After we see that 100 pics were taken and the date/time on the files is …
> AP_Mount: improve Xacti picture taking reliability

- libraries/AC_PID/AC_PID.cpp
This is a simplification to try and keep all the complexity of the PIDs in one spot. This should result in identical outputs. 
The remaining callers are tracker, one in blimp and one in plane. These can't simply be removed as there all acting on target headings, so the error must be wrapped.
This will simplify https://github.com/ArduPilot/ardupilot/pull/24567 and https://github.com/ArduPilot/ardupilot/pull/24411 but I don't mind which goes in first.
> AC_PID: Simplify update_error method by calling update_all

- ArduPlane/GCS_Mavlink.cpp
- ArduPlane/Parameters.h
- ArduPlane/Plane.h
- ArduPlane/mode_guided.cpp
Spotted while looking into the last users of `update_error` for https://github.com/ArduPilot/ardupilot/pull/25084. 
The current anti windup handling just does nothing, it fetches `I`, then it fetches it again. `AC_PID` will already handle anti windup correctly if we pass a limit flag.
> Plane: fix guided heading control anti windup

- libraries/AP_EFI/AP_EFI_Serial_MS.cpp
- libraries/AP_EFI/AP_EFI_Serial_MS.h
This fixes it up so that the driver actually works on things like AP_Periph that poll at a high rate. This was never a problem with the main firmware as EFI was run at a lower rate, but on AP_Periph this was much to fast. This lead to spamming fresh requests and keeping the buffer completly stuffed with requests. To compound it, the EFI device would start over when there was a fresh request, and eventually our buffer writes become corrupted leading to bad checksums, and a complete failure of the comms. This prevents that situation from happening.
Tested with a HFE engine, and custom AP_Periph.
> AP_EFI: Rate limit the megasquirt driver

- libraries/AP_RCProtocol/AP_RCProtocol_Backend.cpp
We're asking the singleton here for information on whether we should do raw logging.  We may not actually be compiling the RC_Channel library in.
Solves the compilation problem.  We can probably do better here by creating a new define, but there's even better things that could be done to remove this method and its callers to save bytes....
> AP_RCProtocol: disable raw logging if no RC_Channel

- Tools/autotest/common.py
- Tools/autotest/rover.py
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
... also add (more) tests for same
> Handle message-rate commands as both long and int

- libraries/AP_Winch/AP_Winch.cpp
- libraries/AP_Winch/AP_Winch.h
- libraries/AP_Winch/AP_Winch_Daiwa.cpp
- libraries/AP_Winch/AP_Winch_Daiwa.h
The [Daiwa winch](https://ardupilot.org/copter/docs/common-daiwa-winch.html) will stop raising or lowering the package if the tension on the line falls below a (supposedly configurable) weight.  The reason for this "failsafe" behaviour is to protect the winch line from getting tangled but it can also be falsely triggered during a real delivery if the vehicle hits turbulence.  The result being that the package is not lowered or the empty hook is not raised without manual intervention.
This PR adds an optional "stuck protection" feature that checks if the winch has stopped unexpectedly and if it does it momentarily (for 1 sec) returns the desired rate to zero which normally clears the issue.
This has been fairly extensively tested on real hardware and below is a screenshot of some output …
> AP_Winch: Daiwa driver gets stuck protection

- libraries/AP_Mount/AP_Mount_Xacti.cpp
- libraries/AP_Mount/AP_Mount_Xacti.h
This PR is built upon https://github.com/ArduPilot/ardupilot/pull/25082
This PR adds optical zoom support for the Xacti cameras that support it (e.g. the [CX-GB400](https://ardupilot.org/copter/docs/common-xacti-gimbal.html))
We cannot currently retrieve the model directly from the Xacti cameras so instead the driver determines if the camera supports optical zoom by attempting to change the optical zoom parameter value to 100 (1x zoom) soon after startup.  If this succeeds we assume the camera supports optical zoom, if there is no reply then it doesn't.
The driver's existing zoom rate and zoom percentage controls have been updated so that optical zoom is used for the 1x to 2.5x range and digital zoom is used beyond this (e.g. 2.5x to 25x).
There's a small drive-by change to how zoom …
> Xacti: support optical zoom

- libraries/AP_HAL/RCOutput.cpp
- libraries/AP_HAL/RCOutput.h
- libraries/AP_HAL_ChibiOS/RCOutput.cpp
- libraries/AP_Notify/AP_Notify.cpp
- libraries/AP_Notify/AP_Notify.h
- libraries/AP_Notify/NeoPixel.cpp
- libraries/AP_Scripting/docs/docs.lua
- libraries/AP_Scripting/generator/description/bindings.desc
- libraries/AP_SerialLED/AP_SerialLED.cpp
- libraries/AP_SerialLED/AP_SerialLED.h
NeoPixels can take either RGB or GRB order, with GRB being the default. This adds support for RGB order.
This work was sponsored by Proto Systems
> Support NeoPixel RGB

- libraries/AP_Scripting/docs/docs.lua
- libraries/AP_Scripting/generator/description/bindings.desc
- libraries/AP_Scripting/lua_bindings.cpp
- libraries/AP_Scripting/lua_bindings.h
This adds a very basic print method, its not as clever as the build in print which can handle multiple arguments.
https://www.lua.org/manual/5.3/manual.html#pdf-print
This is a quick method for debug that should work on all platforms. It uses the `GCS_SEND_TEXT` macro, so will print over CAN on periph.
> AP_Scripting: add basic print

- ArduSub/GCS_Mavlink.cpp
- ArduSub/GCS_Mavlink.h
- Tools/autotest/ardusub.py
I've tested this in SITL by setting a breakpoint on AC_WPNav set_speed_xy and issuing the relevant commands on the SITL commandline to run that codepath.  Values come through as expected.
The new autotest is disabled as it doesn't work; the vehicle doesn't achieve the speeds for reasons unknown.
> Allow Sub to handle DO_CHANGE_SPEED as both command_ong and command_int

- AntennaTracker/Parameters.cpp
- AntennaTracker/Parameters.h
Tested in SITL and on CubeOrange.
> Tracker: enable EK2 and EK3 parameters

- libraries/AP_HAL_ChibiOS/hwdef/SpeedyBeeF405WING/Readme.md
- libraries/AP_HAL_ChibiOS/hwdef/SpeedyBeeF405WING/hwdef.dat
> hwdef:add VTX power control to SpeedyBeeF405-Wing

- libraries/AP_HAL_ChibiOS/hwdef/common/flash.c
stm32l4+ flash reset register has been reset properly
> Fix stm32l4+ flash issue

- libraries/AP_GPS/AP_GPS_UBLOX.cpp
Relying on our autotests for this one...
> AP_GPS: have AP_GPS_UBLOX  use boolean uart read

- libraries/AP_InertialSensor/AP_InertialSensor_BMI088.cpp
the bad value is -32767 not 0xffff (which is -1)
-32767 badly corrupts the low-pass filter, and is what we see in logs (a large negative spike on all 3 axes)
update to bug fix from:
https://github.com/ArduPilot/ardupilot/pull/23033
> AP_InertialSensor: fixed the error value for BMI088

- Tools/autotest/param_metadata/param.py
- libraries/AP_BattMonitor/AP_BattMonitor_INA2xx.cpp
- libraries/AP_BattMonitor/AP_BattMonitor_INA2xx.h
allows vendor to choose shunt resistor to control power dissipation
> AP_BattMonitor: added SHUNT parameter for INA2xx batt mon

- ArduCopter/Copter.h
Remove duplicate declaration of `friend class AP_ExternalControl_Copter`.
> Copter: remove duplicate friend declaration

- libraries/AP_Winch/AP_Winch_Daiwa.cpp
The HEALTHY string is common. This string can be made common.
> AP_Winch: Make healthy strings common

- libraries/AP_GyroFFT/AP_GyroFFT.cpp
- libraries/AP_InertialSensor/AP_InertialSensor.cpp
- libraries/Filter/HarmonicNotchFilter.cpp
- libraries/Filter/HarmonicNotchFilter.h
Lots of harmonics are useful for low frequency excitation. For example a heli, in this case with 3 blades. 
This is the best I can do with all 8 harmonics.
This does increase the max number of harmonics to 16, but in this particular case a total of 8 would have been fine. Because of the three bladed head the 3,6,9,12... harmonics are much stronger. I would have much rather have the 9th and 12th harmonic and not the 7th and 8th and keeping the max total to 8. But we do already have a check for the total number of notches, so I don't think we need to limit to only 8 active harmonics.
> Filter: HarmonicNotch: allow upto 16 harmonics

- libraries/Filter/LowPassFilter2p.cpp
Currently its possible to get stuck in a boot loop if the frequency is set too high. For example set `INS_GYRO_FILTER` to 1500 you will find the board will no longer boot all the way. The main goal of this PR is to fix that boot loop but I have also done a couple of other tidy ups.
The stops numerical errors by constraining the cutoff down, we could also just turn off the filter as we would for a cutoff of zero.
> Filter: LowPassFilter2p: constrain cuttoff to 40% of  sample rate

- libraries/GCS_MAVLink/GCS_Common.cpp
tested in SITL, running command gives appropriate messages back saying to reboot the board.
Note the correction of the result code from `UNSUPPORTED` to `DENIED` when parameters are incorrect.
> GCS_MAVLink: allow PREFLIGHT_STORAGE as COMMAND_INT and COMMAND_LONG

- ArduSub/GCS_Mavlink.cpp
- ArduSub/GCS_Mavlink.h
- Tools/autotest/ardusub.py
.... also corrects the return value if some parameters are bad.
>  ArduSub: accept MAV_CMD_CONDITION_YAW as both long and int in Sub 

- libraries/AP_GPS/AP_GPS.cpp
should be voided when no logging, not just on periph...
> AP_GPS: correct placement of voiding clause

- libraries/AP_HAL_ChibiOS/hwdef/scripts/defaults_bootloader.h
There are two definition judgments for HAL_GCS_ENABLED.
Both are the same.
I would like to remove.
> AP_ChibiOS: Delete the same definition

- Tools/autotest/autotest.py
needs extra defines as we kill features from it
Not working on autotest server as AP_Beacon isn't available on this board by default.
> autotest: don't build examples for fmuv2

- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
Tested on CubeBlack and `command_int`
> GCS_MAVLink: accept accel cal vehicle positions as both int and long

- libraries/AP_Logger/AP_Logger_Backend.cpp
- libraries/AP_Logger/LogStructure.h
this allows log review tools to use right parameter and mode map when vendor has changed the vehicle type strings
goes with this pymavlink change for MAVExplorer: https://github.com/ArduPilot/pymavlink/pull/865
> AP_Logger: added build directory to VER message

- libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus-SimOnHardWare/hwdef.dat
../../libraries/AP_InertialSensor/AP_InertialSensor_config.h:20:2: error: #error "INS_AUX_INSTANCES must be zero if INS_MAX_INSTANCES is less than 3"
20 | #error "INS_AUX_INSTANCES must be zero if INS_MAX_INSTANCES is less than 3"
|  ^~~~~
> hwdef: correct compilation of CubeOrange-SimOnHW

- ArduPlane/Plane.h
- ArduPlane/altitude.cpp
- ArduPlane/commands_logic.cpp
- ArduPlane/mode.cpp
- Tools/autotest/arduplane.py
- Tools/autotest/common.py
this fixes a bug where if the terrain database cache does not have the tile for the location of a rally point then RTL to the rally point with TERRAIN_FOLLOW=1 will not track terrain
The underlying issue is that Location::loc.change_alt_frame() will return false if the location is not in the terrain memory cache. We can't just extrapolate as the rally point could be in a totally different terrain area to the current location. So instead we set it as terrain_following_pending and fix it as soon as the terrain cache is filled.
this fixes #25157
> Plane: fixed terrain RTL rally bug

- libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus-SimOnHardWare/defaults.parm
I implemented SimOnHW with CUBE ORANGE PLUS.
I received a "PreArm: 3D Accel Calibration needed" message.
I got advice from ArduPilot member Petter.
I quoted "CubeOrange-SimOnHardWare/defaults.parm" in INCLUDE.
Petter's advice:
Compare libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-SimOnHardWare/defaults.parm and libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus- SimOnHardWare/defaults.parm - the latter should look much like the former. So whoever created the CubeOrangePlus one forgot a step. Try copying the CubeOrange-SimOnHW defaults.parm over the CubeOrangePlus-SimOnHardWare defaults.parm and recompile/flash
AFTER
BEFORE
> hwdef: Cite CubeOrange-SimOnHW as the default file

- Tools/autotest/arducopter.py
these hooks were remaining active if the test failed
> autotest: correct hook removal for Copter tests

- libraries/GCS_MAVLink/MAVLink_routing.cpp
- libraries/GCS_MAVLink/MAVLink_routing.h
@rmackay9 @davidbuzz @proficnc This PR replaces the PR https://github.com/ArduPilot/ardupilot/pull/22692 which I accidentally closed last week.
It should work for CubeSolo, CubeGreen and fmuv3 boards when HAL_SOLO_GIMBAL_ENABLED is met and when a Gopro heartbeat is broadcasted. I tested it successfully with AC 4.4beta on a Solo with a CubeSolo board and a non-Solo copter with CubeBlack installed.
> GCS_MAVLink: Fix for the Gopro/Solo Gimbal issue 

- libraries/Filter/NotchFilter.cpp
- libraries/Filter/NotchFilter.h
- libraries/Filter/examples/TransferFunctionCheck/TransferFunctionCheck.cpp
I had spotted we could pre-multiply by a0 to same some runtime calculation and was looking at the betaflight filter code and they also have different handling of the "memory" elements that saves one value. 
https://github.com/betaflight/betaflight/blob/90d09e2e5bccc9e21101811618be79621286f56e/src/main/common/filter.c#L210-L224
I have run this in my MATLAB thingy (https://github.com/ArduPilot/ardupilot/pull/24249) result is the same to 10^-4. floating point math does mean the result comes out a tiny bit different. The difference is only due to the pre-multiplication of a0. The removal of `ntchsig` makes no difference to the result.
> Filter: notch filter: remove unneeded value and pre-multiply for speed

- Tools/AP_Periph/AP_Periph.h
- Tools/AP_Periph/efi.cpp
Also remove the last update variables for features that were compiled out.
This is the requested follow up from #25095.
Testing:
> AP_Periph: Rate limit EFI driver updates

- libraries/AC_PID/AC_PID.cpp
Currently once you limit PD max once the flag was always set, which makes it less useful in log files.
> AC_PID: If PD max limiting isn't active clear the flag

- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
Tested in autotest by inserting a `self.send_debug_trap()`  and ensuring old call works, then changing that method to call `self.run_cmd_int` instead and making sure new behavior works.
> GCS_MAVLink: handle MAV_CMD_DEBUG_TRAP as both long and int

- libraries/AP_ServoRelayEvents/AP_ServoRelayEvents.cpp
- libraries/SRV_Channel/SRV_Channel.cpp
- libraries/SRV_Channel/SRV_Channel.h
Allow `MAV_CMD_DO_SET_SERVO` and `MAV_CMD_DO_REPEAT_SERVO` to be used on
a servo output set to an RCINnScaled function (i.e. k_rcinN_mapped).
Scaling is applied so that a commanded servo PWM of <=1000 maps to
SERVOn_MIN, a PWM of 1500 maps to SERVOn_TRIM, and a PWM of >=2000 maps to
SERVOn_MAX. Linear interpolation is performed between ranges.
This allows control of servos/hardware with reasonable/safe scaling applied by firmware and allows more functionality from mission scripts.
In our use case we have a variable aperture controlled by a hobby servo for releasing crop seeds. The scaling is controlled by the mechanical geometry and programmed in the autopilot firmware so that SERVOn_MIN is fully closed and SERVOn_MAX is fully open. By setting the servo function to an RC scaled value, we …
> AP_ServoRelayEvents: allow mavlink command of rcin scaled functions

- Tools/scripts/build_options.py
- Tools/scripts/extract_features.py
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
- libraries/GCS_MAVLink/GCS_config.h
- libraries/GCS_MAVLink/MissionItemProtocol.cpp
replaced by MISSION_REQUEST_INT
Not used by default, but available on the custom build server.
> GCS_MAVLink: add build option for deprecated MISSION_REQUEST

- libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.cpp
- libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.h
If we do not receive consumed energy directly it is already calculated from current draw.
https://github.com/ArduPilot/ardupilot/blob/fcd4152b30aa1f50b110303e7cae1f9f35f5e645/libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.cpp#L129-L134
This just changes to report true for the "manually" calculated case.
> AP_BattMonitor: DroneCAN: always have consumed energy

- ArduPlane/mode.cpp
if you lose rc or accidentally change mode to rtl while disarmed on the ground with a DO_LAND_START setup you will prevented from arming when rc is restored or mode changed,if you dont have a gcs to reset the mission ...unless you power cycle
this will reset the mission to allow arming on non-autothrottle mode entry IF.....in landing sequence, disarmed, and not flying
tested in SITL
> Plane:reset in landing seq on mode change while disarmed

- ArduCopter/Copter.h
- ArduCopter/mode.h
- ArduCopter/mode_auto.cpp
- ArduCopter/mode_guided.cpp
- ArduCopter/takeoff.cpp
similar to the encapsulation of "user takeoff" into an object
```
Durandal                       *      *           -88     -80               *      *      *
KakuteH7-bdshot                *      *           -72     -72               *      *      *
MatekF405                      *      *           -64     -64               *      *      *
Pixhawk1-1M-bdshot             *                  -104    -104              *      *      * …
```
> Copter: encapsulate auto takeoff into an ojbect

- Blimp/GCS_Mavlink.cpp
this would return success when it, in fact, does nothing.
> Blimp: remove misleading implementation of MAV_CMD_CONDITION_YAW

- ArduPlane/quadplane.cpp
- Tools/autotest/quadplane.py
We're actually mixing different frames in different clauses here
Closes https://github.com/ArduPilot/ardupilot/issues/25283
> Use above-origin in place of above-home for position2

- Tools/autotest/balancebot.py
- Tools/autotest/rover.py
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
rewrite the autotest to test both and use new infrastructure to simplify it.
> GCS_MAVLink: handle MAV_CMD_DO_SEND_BANNER as both long and int 

- libraries/AP_DDS/AP_DDS_Client.cpp
- libraries/AP_DDS/AP_DDS_Client.h
- libraries/AP_Vehicle/AP_Vehicle.cpp
Housekeeping to replace use of GCS message prefix `XRCE Client:` and use prefix `DDS Client:` consistently.
1. Run the DDS examples and monitor the GCS messages in MAVProxy console. 
Figure: GCS messages using consistent prefix.
Figure: previous output for comparison
> AP_DDS: standardise GCS_SEND_TEXT message prefix

- libraries/AP_Compass/AP_Compass_AK09916.cpp
- libraries/AP_Compass/AP_Compass_AK09916.h
* During production testing it was found that AK09916 significant percentage (~15%) of Cubes AK09916 will hangup for around half a second and then come back. To resolve this we call reset to AK09916 and that seems to be solving the issue
[CompassFail.zip](https://github.com/ArduPilot/ardupilot/files/12987889/CompassFail.zip)
> AP_Compass: fix AK09916 hangup issue

- Tools/autotest/common.py
... and reimplement assert_parameter_vaue in terms of that function
> autotest: add an epsilon kwarg for assert_parameter_values

- libraries/AP_Scripting/applets/VTOL-quicktune.lua
- libraries/AP_Scripting/applets/VTOL-quicktune.md
this allows for low/high instead of low/mid for quicktune with a 2 position switch such as with a herelink transmitter
tested successfully on a 30" quad
> AP_Scripting: make 2-position switch easier for quicktune

- libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
- libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
- libraries/AP_InertialSensor/AP_InertialSensor_Logging.cpp
This fixes issue #25025 
the ICM42688 has an "AFSR" feature (enabled by default) where it switches between a low-noise mode at angular rates below 100 deg/sec and a higher noise mode above that level. When it switches it causes the gyro to become "stuck" for between 1ms and 2ms, leading to a significant gyro bias that can under some circumstances lead to a crash of the vehicle if it is not able to switch to another IMU.
This PR does 2 things:
- it disables this AFSR feature on the ICM42688
- it enables optional FIFO rate logging to make the fix apparent in a log using the GYR log message. This FIFO rate logging is disabled by default
> IMU: Fixed ICM42688 "stuck" gyro issue

- libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
* also allows passing APP_RAM_START index through hwdef, this could be to add support for old bootloaders which used different app ram map.
* This is to support HerePro Alpha series, we changed the application map for STM32H757, so there are few really old herepros running old bootloader with incorrect APP RAM MAP.
> AP_HAL_ChibiOS: fix setting APP_RAM size

- libraries/AP_HAL/utility/Socket.cpp
- libraries/AP_HAL/utility/Socket.h
- libraries/SITL/SIM_FlightAxis.cpp
this times out socket connects in an attempt to reduce glitches. It seems to help on my network
> SITL: reduce the impact of long socket glitches in realflight

- .gitignore
gitignore mission.stg (missions on sd card)
This file gets left behind in SITL
> gitignore mission.stg (missions on sd card)

- libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/sport_aerobatics.lua
- libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
rudder was not being activated in sport aerobatics
> AP_Scripting: fixed rudder in sport aerobatics

- libraries/AP_TECS/AP_TECS.cpp
TECs weighting is now between 0 and 1 for both weights as seen here:  https://github.com/ArduPilot/ardupilot/blob/fb87369c7ef174c4ae2eda996a97dbc283bc1df5/libraries/AP_TECS/AP_TECS.cpp#L948C1-L951C1
We can no longer infer the other weight from here: https://github.com/ArduPilot/ardupilot/blob/fb87369c7ef174c4ae2eda996a97dbc283bc1df5/libraries/AP_TECS/AP_TECS.cpp#L946
Add a log message for `_SKE_weight` directly.
[00000035.BIN.txt](https://github.com/ArduPilot/ardupilot/files/12934151/00000035.BIN.txt)
Figure: Demonstration of how `TEC2.PEW` remains 1 even though `TEC2.KEW` is changing.
> AP_TECS: log SKE weight since both weights are now [0,1]

- libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/hwdef.dat
Probing of external I2C compasses was missing for RADIX2HD. 
I tested it with a HMC5983. Both the compass and the internal DPS310 baro on the same I2C bus are working as expected.
Please also backport this to 4.4
> AP_HAL_ChibiOS: RADIX2HD Probe external I2C compasses

- ArduCopter/GCS_Mavlink.cpp
- ArduCopter/GCS_Mavlink.h
- ArduPlane/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.h
- Blimp/GCS_Mavlink.cpp
- Blimp/GCS_Mavlink.h
- Tools/autotest/arducopter.py
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
~Built on top of https://github.com/ArduPilot/ardupilot/pull/25294 as a bugfix.~ merged now
> Handle MAV_CMD_NAV_TAKEOFF as both command-long and command-int

- libraries/AP_BattMonitor/AP_BattMonitor.cpp
- libraries/AP_BattMonitor/AP_BattMonitor.h
- libraries/AP_Scripting/docs/docs.lua
- libraries/AP_Scripting/examples/cell_balance_check.lua
- libraries/AP_Scripting/generator/description/bindings.desc
This adds get_cell_voltage() to get an individual cell voltage in a lua script. This allows for a pre-arm check for cell balance
I implemented this using a simple instance/cell get call instead of returning the whole cells structure as it is much simpler to implement and meets the needs for a pre-arm check where cell voltages will not be rapidly changing. We could add a userdata for the whole cells structure but that adds complexity for a case we don't need
> AP_Scripting: added get_cell_voltage and balance arming check

- ArduPlane/GCS_Mavlink.cpp
- ArduPlane/commands_logic.cpp
- ArduPlane/mode_qloiter.cpp
- ArduPlane/quadplane.cpp
- libraries/AP_ICEngine/AP_ICEngine.cpp
- libraries/AP_ICEngine/AP_ICEngine.h
- libraries/AP_Mission/AP_Mission.cpp
- libraries/AP_Mission/AP_Mission.h
This allows you to bypass the disable starting while disarmed option in #25053 once. The workflow this enables is as follows:
1. Start with a disarmed/safety enabled aircraft
2. Disable the safety switch (physically or with software)
3. Preform inspections of the fixed wing flight control surfaces/motor test as desired
4. Send the MAVLink command (or jump via the mission) to allow starting while disarmed
5. Start the engine, preform engine checks
6. Arm the aircraft and start the flight.
The main target here is the minimization of risk as we move through the system. When inspecting the fixed wing surfaces we don't want to risk starting the ICE engine, but when we get to starting it we'd actually like to be disarmed, as that stops us from risking taking off by accident or flying the …
> Plane: Allow a ICE start even if disable while disarmed is set

- libraries/AP_DDS/AP_DDS_Client.cpp
Some words are changed by flags.
I would consolidate the wording.
> AP_DDS: Aggregate message

- Tools/ardupilotwaf/boards.py
- libraries/AP_HAL_SITL/SITL_cmdline.cpp
- libraries/SITL/SIM_AIS.cpp
- wscript
this removes the only build root specific define on the g++ command line, which allows for better ccache results between build directories
> waf: remove SKETCHBOOK define

- ArduPlane/GCS_Mavlink.cpp
- ArduPlane/GCS_Mavlink.h
Minor modification -  implementation of the send_attitude_target msg. streaming (for quadplanes). The code is analogous in its structure and functionality to the implementation in Copter. 
This is the same mod as reviewed in #25253. I broke the PR along the way, but now it is all good (and requesting to pull to master, as instructed).
> Plane: send attitude target message implementation (for quadplanes)

- libraries/AP_DDS/AP_DDS_Client.cpp
Use the TopicIndex enum to index topics table.
- Follow up to https://github.com/ArduPilot/ardupilot/pull/23966
> AP_DDS: use TopicIndex enum to index topics table

- Rover/AP_ExternalControl_Rover.cpp
- Rover/AP_ExternalControl_Rover.h
- Rover/Rover.h
- Rover/mode.h
Implement external control for Rover.
Tested in Gazebo with WildThumper robot, cartographer and navigation 2.
> Rover: implement external control

- ArduCopter/AP_Arming.cpp
- ArduPlane/AP_Arming.cpp
- ArduSub/AP_Arming_Sub.cpp
- Blimp/AP_Arming.cpp
- Rover/AP_Arming.cpp
- libraries/AP_Arming/AP_Arming.cpp
- libraries/AP_Arming/AP_Arming.h
I don't find the status text of "Throttle armed" useful at all on plane, particularly because I have both generally good tracking of that, and on a ICE plane where you may be starting the throttle while disarmed this is particularly misleading. Interestingly both copter and sub actually only sent text messages in SITL, so presumably this isn't a unique opinion.
This adds an opt in behavior to not send the message. SITL tested on plane.
> Make it possible to surrpress the status text on arming/disarming the aircraft.

- Tools/autotest/common.py
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
```
This was the old offboard-calibration code.
We've checked MAVProxy, QGC and MissionPlanner and they're not using this code.
The onboard calibration stuff is better.
```
> Remove handling of PREFLIGHT_SET_SENSOR_OFFSETS

- libraries/AP_DDS/README.md
- libraries/AP_DDS/dds_xrce_profile.xml
Without a namespace prefix the micro-ROS agent will attempt to send all `/tf` messages to ArduPilot DDS. This can quickly overwhelm the AP_DDS subscriber for large TF trees.
The preferred approach should be to use a `topic_tools` relay node to forward TF only when required, and prune the tree with a filter if appropriate.
Without this change the rover example
```bash
ros2 launch ardupilot_gz_bringup wildthumper_playpen.launch.py rviz:=true use_gz_tf:=true
```
results in continuous reporting of `[RTPS_READER_HISTORY Error]`
```bash
[micro_ros_agent-3] 2023-10-27 09:21:03.217 [RTPS_READER_HISTORY Error] Change payload size of '1764' bytes is larger than the history payload size of '1031' bytes and cannot be resized. -> Function can_change_be_added_nts
[micro_ros_agent-3] 2023-10-27 …
```
> AP_DDS: revert change that removed namespace for TF subscriber topic

- libraries/AP_Mission/AP_Mission.cpp
The comment for the AP_Mission::clear method had an incorrect claim as to the return value
> Fix comment in AP_Mission.cpp

- libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
TDK has confirmed this applies to all IxM42xxx sensors
> AP_InertialSensor: apply stuck gyro fix to all IxM42xxx sensors

- libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp
Unnecessary white space in the device list description.
I will remove the unnecessary spaces.
I want to match the style.
There is an unnecessary blank in the description of adding a device in JRE_Serial.
I think it is NG to continue this format.
https://github.com/ArduPilot/ardupilot/pull/25377/files#diff-694515b5270fae871ad393be4521b6948a7049c501d072c7687be7b2c463df87R13
> AP_RangeFinder: Remove unnecessary whitespace(NFC)

- ArduCopter/autoyaw.cpp
- ArduSub/mode_auto.cpp
- Tools/autotest/arducopter.py
- libraries/AP_Mount/AP_Mount.cpp
- libraries/AP_Mount/AP_Mount.h
- libraries/GCS_MAVLink/GCS_Common.cpp
Addresses #25276:
> There are two ways to remove a Region of Interest (ROI):
>
> 1. Send a DO_SET_ROI/DO_SET_ROI_LOCATION command with the location set to (0, 0, 0); or
> 2. Send a DO_SET_ROI_NONE command.
>
> However, in Copter and Sub, the first case has special handling to set the Auto Yaw behaviour, but the second case doesn't.
FYI: @rmackay9
> Copter, Sub, AP_Mount: Fix inconsistent handling of clearing ROIs

- Tools/AP_Bootloader/board_types.txt
AP_Bootloader: Fix AIRVOLUTE format issue
Which was discussed in https://github.com/ArduPilot/ardupilot/pull/25398
> AP_Bootloader: Fix AIRVOLUTE format issue

- Tools/AP_Bootloader/board_types.txt
AP_Bootloader: Reserve Aocoda-RC board IDs and apply for H743DUAL/F405V3
> AP_Bootloader: Reserve Aocoda-RC board IDs and apply for H743DUAL/F405V3

- libraries/AP_HAL_ChibiOS/hwdef/mini-pix/hwdef.dat
Andy pointed out this was the wrong include in a recent PR, post-merge.
> hwdef: minimize_features on mini-pix, not minimize_fpv_osd

- Tools/autotest/ardusub.py
-1 was added to avoid "waves" at the surface, though I'm not quite sure if they actually affect anything.
lower speed targets because the sub model can't go faster than 2m/s.
looser speed check because the speed controller seems to be lagging the speed target a bit (I noticed the same behavior  in other vehicles)
> Tools: Autotest: fix and re-enable Subs's MAV_CMD_DO_CHANGE_SPEED test

- libraries/AP_OpenDroneID/AP_OpenDroneID.cpp
- libraries/AP_Winch/AP_Winch.cpp
- libraries/AP_Winch/AP_Winch_Daiwa.cpp
This fixes a send-text message sent to the user when the winch is being retracted.  Previously it would always say "lowering" but then provide a negative length.  With this change it instead says "lowering" or "raising" and always displays an absolute length.
Below is a SITL test showing the fix.
I've also done a couple of drive-by spelling corrections discovered while working on this PR.
> AP_Winch fix verbose user output when using pos control

- ArduPlane/Attitude.cpp
- ArduPlane/quadplane.cpp
- ArduPlane/radio.cpp
- ArduPlane/servos.cpp
- ArduPlane/takeoff.cpp
- libraries/AP_AHRS/AP_AHRS.cpp
- libraries/AP_AHRS/AP_AHRS.h
- libraries/AP_TECS/AP_TECS.cpp
The `airspeed_sensor_enabled()` function checks the primary sensor, however, we may not be using the primary sensor thanks to affinity. 
The problem is whenever affinity tries to use a sensor other than primary. It checks health, but not use.
https://github.com/ArduPilot/ardupilot/blob/e0a012919c5ab11a964a70890237960d96b01a03/libraries/AP_AHRS/AP_AHRS.cpp#L3080-L3085
I should add that I have not checked if affinity could actually try and use a sensor which is not set to use. So this may or may-not be possible to hit this issue.
> AP_AHRS: ensure we check health of the sensor we are using.

- libraries/AP_HAL_Linux/UARTDriver.cpp
- libraries/AP_HAL_Linux/UARTDriver.h
- libraries/AP_HAL_SITL/UARTDriver.cpp
- libraries/AP_HAL_SITL/UARTDriver.h
This improves parameter loading speed with SITL and Linux. After the linked patch, parameter loading speed (not using mavftp) got ~10x slower.
There is no reason for assuming that these are limited to 57600 baud.
In my tests:
param fetch in master with QGC takes ~30 seconds
with this patch (thanks @magicrub), it takes ~2s
Linux shows similar results
~Apparently it was a typo in here:~
https://github.com/ArduPilot/ardupilot/commit/866db281a6de3fce07a5e2214e9893c9aabc8e72#diff-da049e0cf2dd85cd33145ab82688554b96b56444b22e5475a1d961e259aa69d9L136
> AP_HAL: Improve speed param download in network links (sitl/linux)

- libraries/AP_BattMonitor/AP_BattMonitor_Backend.cpp
- libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.cpp
- libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.h
- libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp
- libraries/AP_BattMonitor/AP_BattMonitor_Params.h
This allows for a different CAN node to provide InfoAux messages for cell voltages to the node providing base current/voltage. This is useful to allow for a separate balance plug AP_Periph CAN node
The PR also includes a small cleanup to reduce flash usage in the driver
tested by ARACE on MatekH743-bdshot
> AP_BattMonitor: added option allowing split InfoAux

- libraries/AP_Scripting/applets/Hexsoon LEDs.lua
- libraries/AP_Scripting/examples/Serial_Dump.lua
- libraries/AP_Scripting/examples/aux_cached.lua
- libraries/AP_Scripting/examples/copy_userdata.lua
- libraries/AP_Scripting/examples/opendog_demo.lua
- libraries/AP_Scripting/examples/param_get_set_test.lua
- libraries/AP_Scripting/examples/rangefinder_test.lua
- libraries/AP_Scripting/examples/rover-SaveTurns.lua
- libraries/AP_Scripting/examples/set-target-location.lua
- libraries/AP_Scripting/examples/set_target_posvel_circle.lua
- libraries/AP_Scripting/examples/terrain_warning.lua
- libraries/AP_Scripting/examples/wp_test.lua
Fixes some basic lua check issues, mostly unused variables.
> AP_Scripting: fix easy lua check issues in examples

- ArduPlane/Plane.h
- ArduPlane/servos.cpp
A relatively small rework to pave the way for future clean ups. 
- reworks the `flight_stage_determines_max_throttle` calculation. Result is the same but method is less confusing.
- always outputs 0 scaled throttle is `!is_armed_and_safety_off()`, this prevents a miss match between the scaled value and the output PWM value that can cause slew limits and other functions that use the scaled value to get confused. 
-  moves the unrelated `set_takeoff_expected` functionality to its own function.
> Plane: rework set_servos_controlled function

- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
... also rename the method to something better
> GCS_MAVLink: handle MAV_CMD_START_RX_PAIR as both int and long

- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
Tested on CubeOrange, both long and int
> GCS_MAVLink: handle FLASH_BOOTLOADER as command-long and command-int

- libraries/AP_Scripting/examples/README.md
> AP_Scripting:add README file to examples directory

- libraries/APM_Control/AP_AutoTune.cpp
It would be nice to be able to use `AUTOTUNE_LEVEL` 0 anywhere down to the bottom entries that it can reach. (IE if you want to do a RMAX of 30 (which is level 2), with a custom tau you can't actually do that at the moment.
> APM_Control: Allow autotune level 0 to actually reach the lowest entries of the autotune level table

- Tools/autotest/arducopter.py
- libraries/AP_Mount/AP_Mount_Servo.cpp
This fixes a bug in the AP_Mount_Servo backend's attitude reporting to the GCS sent via the [GIMBAL_DEVICE_ATTITUDE_STATUS](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L6042).  The current implementation uses the target output angles sent to the gimbal which is OK for BrushlessPWM but incorrect for regular Servo gimbals.  This PR changes the attitude reporting so that the target angle sent to the backend is used.  This is the best we can do for these gimbals because they do not typically have a way to return their actual angles.
By the way, the AP_Mount_Servo backend is actually used for two slightly different mount types
- MNT1_TYPE = 1 ([Servo](https://ardupilot.org/copter/docs/common-camera-gimbal.html)) is for gimbals implemented with actual …
> Mount: servo backend attitude reporting fix

- ArduCopter/mode_rtl.cpp
- Tools/autotest/arduplane.py
- libraries/AP_Logger/AP_Logger_Backend.cpp
- libraries/AP_Logger/LogStructure.h
- libraries/AP_Rally/AP_Rally.cpp
- libraries/AP_Rally/AP_Rally.h
- libraries/GCS_MAVLink/MissionItemProtocol_Rally.cpp
This work is sponsored by Spektreworks.
This adds support for alt frames in rally points. There were some free bits in "flags" that we can use. This assumes that those unused bits are zero. It is possible that they are none zero in storage if uploaded with the old `RALLY_POINT` MAVLink message.  
Tested conversion from old format, all alt frames manually on plane and added new method to the existing `TerrainRally` plane test.
> AP_Rally: support altitude frames

- Tools/autotest/ardusub.py
I noticed that the recently updated MAV_CMD_DO_CHANGE_SPEED test is flapping.
I ran this change 20 times with no failures.
> Autotest: improve flapping Sub test

- libraries/AP_GPS/AP_GPS.cpp
- libraries/AP_GPS/AP_GPS.h
Tidy up of what looks like an old hangover from an improvement to me.  I cannot find where this time constant or the lpf omega is used anymore.
Not sure what best practice is with old param meta data
> AP_GPS: Remove GPS_TC_BLEND

- libraries/SITL/SITL.cpp
Uses same bit as enable for the library for convenience
> SITL: correct bit for enabling MXS simulation

- Tools/autotest/blimp.py
- libraries/GCS_MAVLink/GCS_Common.cpp
only in progress if we have started a task running
> GCS_MAVLink: correct mavlink result when airspeed not available

- libraries/AP_HAL/SIMState.cpp
- libraries/AP_HAL_SITL/SITL_Periph_State.cpp
- libraries/AP_HAL_SITL/SITL_State.cpp
- libraries/SITL/SIM_ADSB.cpp
- libraries/SITL/SIM_ADSB.h
- libraries/SITL/SIM_ADSB_Sagetech_MXS.cpp
- libraries/SITL/SIM_Aircraft.cpp
- libraries/SITL/SIM_Aircraft.h
removes dependence on ArduPilot AHRS library
Also removes vehicles based off vehicle simulated position rather than distance-from-origin, so you always have company
This shows the vehicle moving far from home and still having company:
Without this change, by the time you get far from the ArduPilot home location you don't have any vehicles near you.
This work sponsored by SpektreWorks.
> Track SITL ADSB vehicle positions vs SITL origin

- Tools/autotest/rover.py
- libraries/AP_Camera/AP_Camera.cpp
- libraries/AP_Camera/AP_Camera.h
- libraries/AP_Camera/AP_Camera_Backend.cpp
- libraries/AP_Camera/AP_Camera_Backend.h
- libraries/AP_Camera/AP_Camera_MAVLink.cpp
- libraries/AP_Camera/AP_Camera_MAVLink.h
- libraries/AP_Camera/AP_Camera_Servo.cpp
- libraries/AP_Camera/AP_Camera_Servo.h
- libraries/GCS_MAVLink/GCS.h
- libraries/GCS_MAVLink/GCS_Common.cpp
Added more tests into the autotest suite to ensure fields get passed through appropriately.
The integer fields in these commands are used for integer values (enumeration / de-dupe sequencing / exposure integer), so that's handy.
Comments on what the command fields mean can be found in the message equivalents of the commands.
> Handle digicam messages as COMMAND_INT as well as COMMAND_LONG

- Tools/AP_Periph/can.cpp
- libraries/AP_DroneCAN/AP_Canard_iface.cpp
* Follows similar implementation down for AP_Periph https://github.com/ArduPilot/ardupilot/pull/24840/commits/d892df492bebba23ebf42186f3179533891dc7cb but for DroneCAN. This ensures that we are not filling up buffers with stale transactions just because second interface is down/disconnected.
> AP_DroneCAN: add support for detecting downed link

- libraries/AP_Camera/AP_Camera_Backend.cpp
- libraries/AP_Camera/AP_Camera_Backend.h
- libraries/AP_Camera/AP_Camera_Params.cpp
- libraries/AP_Camera/AP_Camera_Params.h
This small change built on top of PR https://github.com/ArduPilot/ardupilot/pull/25390 populates the hfov and vfov fields in the [CAMERA_FOV_STATUS](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L5926C1-L5926C41) message with values from two new CAMx_HFOV and CAMx_VFOV parameters.
This has been lightly tested in SITL and below are screen shots showing the two fields are populated.
> AP_Camera: CAMERA_FOV_STATUS includes horizontal and vertical field-of-view

- libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
- libraries/AP_ESC_Telem/AP_ESC_Telem_Backend.cpp
- libraries/AP_ESC_Telem/AP_ESC_Telem_Backend.h
- libraries/Filter/NotchFilter.cpp
an incorrectly configured ESC telemetry source can lead to a notch running at very low frequencies. A simple example is a lua script like this:
function update()
esc_telem:update_rpm(12, 0, 0)
return update, 10
end
return update()
where motor 12 is unused.
with that script in place we get a 1.0078 Hz filter which leads to massive phase lag and a crashed aircraft. I suspect the 1.0078 is the last value from the slew limiter before we hit 1.0 Hz 
Note: this is a safety protection. We should also try to find out why the INS_HNTCH_FREQ lower limit is not working
this is what the filtered (in red) vs unfiltered (in green) looks like with the above lua script for a quadplane takeoff in QLOITER in SITL:
this is the same test with the protection in place:
> Filter: protect against extremely low notch filter frequencies

- libraries/SITL/SIM_GPS.cpp
- libraries/SITL/SIM_GPS.h
I added docs for why they exist. If ArduPilot had a general purpose floating point byte swapping functions, these would go away. 
Desire:
```
float htobefloat(const float& src);
double htobedouble(const double& src);
float betohostfloat(const float& src);
double betohostdouble(const double& src);
```
And the corresponding little endian versions. 
This PR is just to rename the simulator. If we can write generic utils in `sparse_endian`, then these can be removed.
> AP_GPS: Rename GSOF packing functions

- libraries/AP_Mount/AP_Mount_Siyi.cpp
this caused lots of lost packets (about 90% packet loss)
> AP_Mount: fixed SIYI parser bug

- ArduPlane/mode_cruise.cpp
If transitioning from VTOL is possible to have a ground course that does not agree with the vehicles heading. We do check for a speed of more than 3m/s, but with strong wind (or flying backwards) it is possible to exceed this.
Currently in this case we will transition and do a 180 at the same time:
With this patch we move off forwards:
Reported in https://github.com/ArduPilot/ardupilot/issues/25434
Moving forward logic stolen from https://github.com/ArduPilot/ardupilot/pull/24834
[tests.zip](https://github.com/ArduPilot/ardupilot/files/13228459/tests.zip)
> Plane: Cruise: only lock in heading once moving forwards

- libraries/AP_Scripting/docs/docs.lua
- libraries/AP_Scripting/generator/description/bindings.desc
This adds a binding for `sysid_myggcs_last_seen_time_ms` renaming it to `last_seen` such then it can be called as `gcs:last_seen()`.
This allows GCS failsafe actions to be implemented in scripting. Very basic example:
```
function update()
local gcs_dt = millis() - gcs:last_seen()
gcs:send_text(0, string.format("Last GCS was: %0.2f seconds ago", gcs_dt:tofloat() * 0.001))
return update, 1000
end
return update()
```
> AP_Scripting: add binding for GCS last seen time

- libraries/AP_Scripting/docs/docs.lua
- libraries/AP_Scripting/drivers/Hobbywing_DataLink.lua
- libraries/AP_Scripting/drivers/Hobbywing_DataLink.md
- libraries/AP_Scripting/generator/description/bindings.desc
this supports the DataLink v2:
https://www.hobbywingdirect.com/products/data-link-v2
tested by Kyle from AerialVisionAustralia on a hexacopter
> AP_Scripting: added HobbyWing DataLink driver

- libraries/AP_Mount/AP_Mount.cpp
- libraries/AP_Mount/AP_Mount.h
- libraries/AP_Mount/AP_Mount_Alexmos.cpp
- libraries/AP_Mount/AP_Mount_Backend.cpp
- libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
This PR changes the name of the function handle_command_gimbal_manager_set_pitchyaw() to handle_gimbal_manager_set_pitchyaw(), since the underlying MAVLink message is not a command but a message.
The PR grabs the opportunity to also change one access of _mode to get_mode(). All other function in the AP_Mount library call get_mode(), except in this one place.
The PR also does two tiny formattings.
The PR is only cosmetic and nfc. Compiles and very lightly tested.
> AP_Mount: gimbal_manager_set_pitchyaw is not a command

- libraries/AP_Scripting/applets/mount-poi.lua
- libraries/AP_Scripting/applets/mount-poi.md
This makes two small enhancements to the mount-poi lua script:
1. if RCx_OPTION = 301 (Scripting2) then in addition to displaying the POI the mount's target location is set to the POI
2. MP's AuxFunction tab can be used instead of actually setting up an RC switch
This has been lightly tested in SITL and seems to work fine
> AP_Scripting: mount-poi supports locking mount to Location

- libraries/AP_Scripting/docs/docs.lua
- libraries/AP_Scripting/examples/FenceBreach.lua
- libraries/AP_Scripting/generator/description/bindings.desc
This adds bindings allowing fence failsafe actions to be taken by scripting. A simple example:
```
function update()
local breaches = fence:get_breaches()
if breaches ~= 0 then
local msg = ""
local breach = false
if (breaches & 1) ~= 0 then
msg = msg .. "Maximim altitude"
breach = true
end
if (breaches & 2) ~= 0 then
if breach then
msg = msg .. " + "
end
msg = msg .. "Circle"
breach = true
end
if (breaches & 4) ~= 0 then
if breach then
msg = msg .. " + "
end
msg = msg .. "Polygon"
breach = true
end
if (breaches & 8) ~= 0 then
if breach then
msg = msg .. " + "
end
msg = msg .. "Minimum altitude"
end
local breach_time = millis() - fence:get_breach_time()
gcs:send_text(0, string.format("Breached: %s fence, outside for %0.2f seconds", msg, breach_time:tofloat() * 0.001))
end
return update, …
```
> AP_Scripting: add bindings for fence

- libraries/AP_ADSB/AP_ADSB.cpp
- libraries/AP_ADSB/AP_ADSB.h
- libraries/AP_ADSB/AP_ADSB_Sagetech.cpp
- libraries/AP_ADSB/AP_ADSB_Sagetech_MXS.cpp
- libraries/AP_ADSB/AP_ADSB_uAvionix_MAVLink.cpp
- libraries/AP_ADSB/AP_ADSB_uAvionix_UCP.cpp
- libraries/AP_GPS/AP_GPS_FixType.h
instead, add fields to canonical AP_ADSB location "_my_loc" to hold all of the information backends might want.  This will allow consistent presentation of data regardless of backend type, and for the sources of the information to change more easily.
This work sponsored by SpektreWorks
> AP_ADSB: avoid using GPS and RTC libraries in backend

- libraries/GCS_MAVLink/GCS_Common.cpp
Tested in SITL using GDB and breakpoints; works as both long and int
> GCS_MAVLink: handle DO_ADSB_OUT_IDENT as both long and int

- libraries/AP_GPS/AP_GPS_GSOF.cpp
- libraries/AP_GPS/AP_GPS_GSOF.h
* This removes magic numbers of hard coding the hardware port and output rate
* This also fixes configuring the incorrect hardware port
* Now, COM2 (TTL) is configured for GSOF output; previously it was not and likely a bug on the BD930 unless they were using RS232 level logic on the drone/bench
* The data rate remains the same as before
* Once this PR goes in, the Trimble PX-1 is functional as a GPS in ArduPilot
You can see in the screenshot, the config UI shows the device is now configured on COM2 for 230k, which is the desired behavior when the user sets the parameter correctly. COM2 is the TTL level serial port that users typically connect to a flight controller.
Output overview:
COM2 data configuration:
Parts of this were split from #25449 to make it easier to merge.
Old behavior was …
> AP_GPS: Expose COM port and Output Rate in header, Fix default COM port

- ArduPlane/quadplane.cpp
- ArduPlane/tiltrotor.cpp
- libraries/RC_Channel/RC_Channel.cpp
NFC
as I was preparing to write this up for the wiki I ran across some unclear wording and some metadata errors
@IamPete1 Pete tagged you since this is an easy review and merge and Paul sometimes misses these requests
question, this new addition did test that the _ALT qualifier is adhered to in its new CI?
> Add expanded explanation in Fwd throttle code comments and metadata

- libraries/AP_Compass/AP_Compass.cpp
- libraries/AP_HAL_ChibiOS/hwdef/f103-QiotekPeriph/hwdef.dat
we don't need anything not related to raw magnetic field
> AP_Compass: reduce number of parameters on periph

- libraries/AP_EFI/AP_EFI_State.h
... these would go into the .config.h anyway
> AP_EFI: remove unused definitions

- ArduSub/Attitude.cpp
- ArduSub/Parameters.cpp
This fixes an issue where trying to control altitude with very low pilot gain (say 10%) has no result at all.
This happens is because the input is scaled so much it falls into the deadzone area. This PR scales the deadzone with the pilot gain.
> Sub: scale get_pilot_desired_climb_rate() deadzone and output with pilot gain

- libraries/AP_GPS/AP_GPS.cpp
- libraries/AP_GPS/AP_GPS_GSOF.cpp
- libraries/AP_GPS/AP_GPS_GSOF.h
In #25456, I exposed the COM port to the header of the GSOF driver. In that PR, it was requested by @WickedShell to then use [GPS_COM_PORT](https://ardupilot.org/copter/docs/parameters.html#gps-com-port-gps-physical-com-port).  Instead of hard-coding to COM2, this PR allows users to set their desired port. Most will still want to use COM2. The enum is confusing, so this needs a wiki entry.
Config UI:
Logic Analyzer capture of Handshake:
Connect a GSOF GPS to the computer. 
1. Use the PX-1 Web UI to disable all data streaming services
1. `./Tools/autotest/sim_vehicle.py -v Plane -A "--serial3=uart:/dev/ttyUSB0" --console --map -DG`
1. Set `GPS_COM_PORT` to `1`
1. Set `GPS_TYPE` to `11`
1. Set `SERIAL3_PROTOCOL` to  `5`
1. Reboot
1. View the config UI now shows COM2 GSOF at 115k with the …
> AP_GPS: Use GPS_COM_PORT param in GSOF driver

- libraries/AP_Logger/AP_Logger_Backend.cpp
correct compilation errors like this:
../../libraries/AP_Logger/AP_Logger_Backend.cpp: In member function ‘bool AP_Logger_Backend::Write_VER()’:
../../libraries/AP_Logger/AP_Logger_Backend.cpp:577:5: sorry, unimplemented: non-trivial designated initializers not supported
};
^
> AP_Logger: correct the filling order of the struct

- libraries/AP_DDS/AP_DDS_Client.cpp
- libraries/AP_DDS/AP_DDS_Client.h
- libraries/AP_DDS/AP_DDS_Serial.cpp
- libraries/AP_DDS/AP_DDS_UDP.cpp
Add ping test and attempt to automatically reconnect to the micro-ROS agent.
Closes #23372
For details see: https://github.com/ArduPilot/ardupilot/issues/23372#issuecomment-1756076321
> AP_DDS: support automatic reconnect to micro-ROS agent
