ArduSub/mode_althold.cpp, ArduSub/mode_poshold.cpp, ArduSub/mode_stabilize.cpp
Analog to #25417 
Yaw input is lost if the pilot gain is set to 10%, this fixes the issue.
=> Sub: use gain-ajusted deadzone for pilot_desired_yaw_rate

ArduCopter/mode_autorotate.cpp, ArduCopter/toy_mode.cpp, libraries/AP_AHRS/AP_AHRS_SIM.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain5.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.cpp, libraries/AP_Parachute/AP_Parachute.cpp
The bit type is a boolean.
0 and 1 are integer values.
Change to a Boolean value.
=> Global: Change to boolean value

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
this avoids issues with SiK and RFD900x radios getting stuck in bootloader mode due to a high RTS pin on power on.
We did this for Pixhawk6C in this PR:
https://github.com/ArduPilot/ardupilot/pull/24169
this now applies it to all boards
=> HAL_ChibiOS: default RTS pins to PULLDOWN

ArduCopter/ReleaseNotes.txt
As reported in [this thread](https://discuss.ardupilot.org/t/copter-4-4-1-released/107005/3), the TKOFF_TH_MAX feature was not actually included in Copter-4.4.0 so we need to fix the release notes.
=> Copter: fix 440-beta1 release notes

libraries/AP_Networking/AP_Networking.cpp, libraries/AP_Networking/AP_Networking.h, libraries/AP_Networking/AP_Networking_Backend.h, libraries/AP_Networking/AP_Networking_ChibiOS.cpp, libraries/AP_Networking/AP_Networking_ChibiOS.h, libraries/AP_Networking/AP_Networking_Config.h, libraries/AP_Networking/AP_Networking_backend.h
AP_Networking: cleanup names and defines
Non-functional change
=> AP_Networking: cleanup names and defines

Tools/autotest/arducopter.py, Tools/autotest/rover.py, Tools/autotest/vehicle_test_suite.py, libraries/AP_Mission/AP_Mission.cpp, libraries/AP_Mission/AP_Mission.h, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
This PR adds handling for `param2` ("Reset Mission") in the [`DO_SET_MISSION_CURRENT`](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_SET_MISSION_CURRENT) command.
=> Handle "Reset Mission" param in DO_SET_MISSION_CURRENT command

ArduCopter/system.cpp, libraries/AP_Motors/AP_MotorsHeli.h, libraries/AP_Motors/AP_MotorsHeli_Single.cpp, libraries/AP_Motors/AP_MotorsHeli_Single.h, libraries/AP_Motors/AP_Motors_Thrust_Linearization.cpp
Issue found by user on master and reported via Trad Heli channel on discord.
Issues resolved:
- Servo min, max, trim values were always being retrieved from servo channel 4 not the servo channel assigned to motor 4.
- The update of the min, max, trim values was only being done in spool state unlimited.  So the output was being forced to 0 instead of min until the system is armed and spooled up.
Issues still to resolve:
- I am fairly sure that trim is currently being ignored.  So this is a breaking change from prior DDFP setups (ref: https://ardupilot.org/copter/docs/traditional-helicopter-tailrotor-setup.html#setting-tail-trim)
Testing thus far has been on a bench setup.  Board is FMUV3.  Signal output is dshot.
=> AP_Motors_Heli: Fix DDFP Min Max Trim Variables

libraries/AP_Motors/AP_MotorsHeli_Dual.cpp, libraries/AP_Motors/AP_MotorsHeli_Dual.h, libraries/AP_Motors/examples/AP_Motors_test/AP_Motors_test.cpp, libraries/AP_Motors/examples/AP_Motors_test/run_heli_comparison.py
This re-factors the dual heli swash plate mixing. The motors example was updated to allow setting of the `H_DUAL_MODE` in the heli test. This allowed a full sweep comparison or each dual heli type.
Results:
```
Dual_Heli H3 Longitudinal:
Inputs max change:
Roll: 0.000000
Pitch: 0.000000
Yaw: 0.000000
Thr: 0.000000
Outputs max change:
Mot1: 0.000000
Mot2: 0.000000
Mot3: 0.000000
Mot4: 0.000000
Mot5: 0.000000
Mot6: 0.000000
Mot7: 0.000000
Mot8: 0.000000
Limits max change:
LimR: 0.000000
LimP: 0.000000
LimY: 0.000000
LimThD: 0.000000
LimThU: 0.000000
Dual_Heli H3 Transverse:
Inputs max change:
Roll: 0.000000
Pitch: 0.000000
Yaw: 0.000000
Thr: 0.000000
Outputs max change:
Mot1: 0.000000
Mot2: 0.000000
Mot3: 0.000000
Mot4: 0.000000
Mot5: 0.000000
Mot6: 0.000000
Mot7: 0.000000
Mot8: 0.000000 …
```
=> AP_Motors: Heli_Dual: refactor swash plate mixing

Tools/autotest/vehicle_test_suite.py, libraries/AP_GPS/AP_GPS.cpp
On the GSOF driver, previously, it said "detected", which made it seem like it already happened. After chasing this down, the message is right, but the GSOF driver is missing certain flags. 
It needs to set `dstate->auto_detected_baud = false`
After this change, the logs now state:
```
AP: GPS 1: specified as GSOF
AP: GPS 1: specified as GSOF
AP: GPS 1: specified as GSOF
```
Before this change, the logs stated:
```
AP: GPS 1: detected as GSOF at 4800 baud
AP: GPS 1: detected as GSOF at 19200 baud
AP: GPS 1: detected as GSOF at 38400 baud
```
=> Fix GSOF autobaud detection message.

libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp, libraries/AP_RCTelemetry/AP_CRSF_Telem.h
I'm not sure you'll like it, but I like it a lot and hence dare to suggest:
There are situations in which one wants to use CRSF, but only with one wire (receiver Tx -> ardupilot Rx), without the additional telemetry wire (receiver Rx <- ardupilot Tx). Examples would be companions or third-party receivers. In such cases the RCTelemetry library sends 50 statustest messages at 2 Hz rate, i.e., for a total of 25 seconds, before it concludes it can stop requesting a CRSF message. The PR here throttles the sending of these statustext messages to one every 5 seconds, which should be really sufficient to have the full attention of the user.
Alternatives: One could add an option which either supresses sending these messages (similar to RC_Channels::Option::SUPPRESS_CRSF_MESSAGE) or which disables …
=> AP_RCTelemetry: throttle CRSF request RX device info messages

libraries/AP_OpticalFlow/AP_OpticalFlow.cpp
This simply increases the valid range that users can enter for the FLOW_FXSCALER and FLOW_FYSCALER parameters.  There is no danger in users using these larger values and in fact, some flow sensors ([like the MatekSys sensor](https://github.com/ArduPilot/ardupilot_wiki/pull/5547)) require it.
=> AP_OpticalFlow: increase scaler param desc ranges

libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.cpp
* The VN driver was likely written before there were multiple EAHRS types
* The log messages make it seem like core AHRS problems rather than issues directly with VN
=> AP_ExternalAHRS: Specify brand on all VN log messages

libraries/AP_HAL/RCOutput.h, libraries/AP_HAL_ChibiOS/RCOutput.cpp, libraries/AP_HAL_ChibiOS/RCOutput.h
This makes the signal match 4.1. Still does not work for me, but that may be down to my hardware setup.
Tested and working on the forums.
=> ProfiLED Fix

ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, ArduPlane/ReleaseNotes.txt, ArduPlane/version.h, Rover/release-notes.txt, Rover/version.h, libraries/AP_GPS/AP_GPS_UBLOX.cpp
This is the Copter-4.4.3 release which is the same as the 4.4.3-beta1 with one addition PR added:
- https://github.com/ArduPilot/ardupilot/pull/25477
The full list of commits can be seen int he 4.4.3-beta1 and 4.4.3 columns of [this project](https://github.com/ArduPilot/ardupilot/projects/27).
=> Copter: 4.4.3 release

libraries/AP_BattMonitor/AP_BattMonitor_FuelLevel_Analog.cpp, libraries/AP_BattMonitor/AP_BattMonitor_FuelLevel_Analog.h
Add in reventech fuel level driver to differentiate from fuel level analog for review. Currently issue is that the new paramters for reventech fuel sensor do not appear in parameter list when BATTx_MONITOR is set to 29.
=> Carbonix PR - AP_BattMonitor: Add in reventech fuel level driver

libraries/SRV_Channel/SRV_Channel_aux.cpp
This resolves a bug in the servo output when the SERVOx_FUNCTION = RCIn**X**Scaled and the RCInput is a range instead of an angle.  For example on Copter the problem occurs when RCx_FUNCTION = RCIn3Scaled..  Details of the issue are explained in issue https://github.com/ArduPilot/ardupilot/issues/25524 and is also [discussed here](https://discuss.ardupilot.org/t/release-rover-4-4-as-stable-ok/106080/6).
In current master the PWM output will always be between SERVOx_TRIM (e.g. 1500) and SERVOx_MAX (e.g. 2000).  After this change the PWM output is correctly in the SERVOx_MIN (e.g. 1000) to SERVOx_MAX (e.g. 2000) range.
I've tested this fairly carefully including before and after tests.
Test1 | Fn=RCIN3Scaled | RC3_TRIM=1106
-- | -- | --
RC3 input | RC9 output (before) | RC9 output (after) …
=> SRV_Channel: fix RCInxScaled when input is range (instead of angle)

ArduCopter/takeoff_check.cpp
In 4.4 and earlier ESC telemetry is always indexed from 0 even when the servo channels are on AUX
This is fixed in 4.5 by https://github.com/ArduPilot/ardupilot/pull/25197 which always gives ESCs their correct index
=> Correct ESC mask for takeoff check

ArduCopter/GCS_Mavlink.cpp, ArduCopter/GCS_Mavlink.h, ArduPlane/GCS_Mavlink.cpp, ArduPlane/GCS_Mavlink.h, Blimp/GCS_Mavlink.cpp, Blimp/GCS_Mavlink.h, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_config.h
- tidies last two command_long packets to also be handled via command_int
- these were tested in SITL
- adds a define to remove command_long handling if you feel like it
- removes unused methods
- tested that everything still compiles and disabling options still works
-
=> Tidy last of command-long to command-int conversions

Tools/autotest/sim_vehicle.py, wscript
* DDS was built without networking so UDP stopped working
This wasn't caught because `colcon test` doesn't run in CI (yet). Note, `--enable-networking` should only do something on SITL. On hardware, it's automatically enabled if an ethernet port is detected. If you set `--enable-networking` on master when compiling for Pixhawk6X, it breaks.
=> Tools: ros2: Fix missing networking

libraries/AP_Mount/AP_Mount_Siyi.cpp, libraries/AP_Mount/AP_Mount_Siyi.h
this means photos on microSD have correct date, based on time we get from GPS, and allows for easier geo-reference
=> AP_Mount: set clock on SIYI

libraries/AP_Mount/AP_Mount_Backend.cpp, libraries/AP_Mount/AP_Mount_Backend.h, libraries/AP_Mount/AP_Mount_Siyi.cpp, libraries/AP_Mount/AP_Mount_Siyi.h
Useful for diagnostic of gyro bias issues
tested on Siyi ZT30
=> AP_Mount: added support for sending gimbal rates to GCS

libraries/AP_DroneCAN/AP_Canard_iface.cpp
this caused a crash on CubeOrange on boot if SLCAN is enabled
=> AP_DroneCAN: cope with null stats (for SLCAN interface)

Tools/AP_Periph/Parameters.cpp, libraries/AP_HAL_ChibiOS/hwdef/kha_eth/hwdef.dat
Allow showing serialmanager params without HAL_GCS_ENABLED
I also enabled this in board target kha_eth and also snuck in a logging change while I was changing that hwdef
=> Periph: Allow showing serialmanager params without HAL_GCS_ENABLED

libraries/AP_RangeFinder/AP_RangeFinder_JRE_Serial.cpp
The value of distance_cm_max is used for invalid values.
For normal values, it is not used.
Therefore, it is better to get the maximum value in the illegal value process.
This process is executed each time, thus increasing processing time.
const int16_t distance_cm_max = max_distance_cm();
=> AP_RangeFinder: Move to a process that uses maximum value acquisition

libraries/AP_DroneCAN/AP_DroneCAN.cpp
some hobbywing ESCs have a bug where requesting the ID table can cause the ESC to stutter
this has been tested by Foxtech and confirmed that this fixes the issue
=> AP_DroneCAN: don't update hobbywing ESC table while armed

Tools/ardupilotwaf/boards.py, Tools/autotest/ardusub.py, Tools/autotest/sim_vehicle.py, Tools/autotest/vehicle_test_suite.py, Tools/scripts/build_tests/test_ccache.py, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py, libraries/AP_Networking/AP_Networking.cpp, libraries/AP_Networking/AP_Networking.h, libraries/AP_Networking/AP_Networking_Config.h, libraries/AP_Networking/AP_Networking_port.cpp, libraries/AP_SerialManager/AP_SerialManager.cpp, libraries/AP_SerialManager/AP_SerialManager.h, libraries/AP_Vehicle/AP_Vehicle.cpp, wscript
This is an alternative approach to allowing UART drivers as AP_Networking ports
Tested on CubeRed and Pixhawk6X, works with MAVLink and gimbal SIYI ZT30
=> AP_Networking: added NET_Pn_ network ports for AP_SerialManager

libraries/AP_Baro/AP_Baro.cpp
The result is the same without the variables.
=> AP_Baro: Returns directly calculated values

libraries/SITL/SIM_GPS.cpp
_sitl is guaranteed non-nullptr by the SITL::GPS::update()
=> SITL: set sitl point for GPS backends in constructor

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.h, libraries/AP_BoardConfig/AP_BoardConfig.cpp, libraries/AP_BoardConfig/AP_BoardConfig.h
Hwdef would include define of HAL_ARM_GPIO_PIN <gpio pin number> to change pin level  on arm/disarm...IF... BRD_OPTIONS bit 8 (Disable arm gpio) is not set
Polarity can be changed using HAL_ARM_GIPO_POL_INVERT (1 to change pin output polarity)   default if not defined is dont change
it is the bootloader's responsibility to set the initial gpio state.
this should be also controllable by the user, if desired, with a relay assignment
tested using a board's blue led
=> Add HAL config to provide GPIO that reflects arm/disarm to control RF power modules

libraries/AP_DDS/README.md, libraries/AP_SerialManager/AP_SerialManager.cpp
This was missing from the wiki:
https://ardupilot.org/copter/docs/parameters.html#serial1-protocol-telem1-protocol-selection
=> AP_SerialManager: Add missing option for XRCE DDS

libraries/AP_HAL/RCOutput.h, libraries/AP_HAL_ChibiOS/RCOutput.cpp, libraries/AP_HAL_ChibiOS/RCOutput.h, libraries/AP_HAL_SITL/RCOutput.cpp, libraries/AP_HAL_SITL/RCOutput.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_SerialLED/AP_SerialLED.cpp, libraries/AP_SerialLED/AP_SerialLED.h
This fixes two issues:
- A race condition in serial_led_send() which could mean that sending out data could be delayed
- Allow scripts to know the return status of serial_led_send() and set_serial_led_rgb_data() so that they can retry if necessary
The first commit should be back-ported to 4.4
=> Fix SerialLED scripting interface

libraries/AP_BattMonitor/AP_BattMonitor_FuelLevel_Analog.cpp, libraries/AP_BattMonitor/AP_BattMonitor_FuelLevel_Analog.h
=> AP_BattMonitor:remove unused param from analog fuel level

libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
Saves a few more bytes, and can remove code that some users may not want on their vehicles.
=> GCS_MAVLink: exclude deadlock-creation based on FAILURE_CREATION_ENABLED

libraries/AP_DDS/AP_DDS_Client.cpp
Related to #25535
Increase the timeout used in `AP_DDS::create` when sending creation requests for participants and entities. This allows a SiK telemetry radio to be used for the serial connection which is useful for testing the DDS library on vehicles without a companion computer.
Tested on a MatekH743-WING v1 installed in a tilt-rotor VTOL using a 433 MHz 100mW telemetry radio on `SERIAL2`.
```bash
SERIAL2_BAUD     57          # 57600
SERIAL2_OPTIONS  0           # 
SERIAL2_PROTOCOL 45
```
Run micro-ROS agent:
```bash
./install/micro_ros_agent/lib/micro_ros_agent/micro_ros_agent serial --dev /dev/cu.usbserial-0001 --baudrate 57600 --verbose 6 --refs /Users/rhys/Code/ros2/humble/ros2-ardupilot/install/ardupilot_sitl/share/ardupilot_sitl/config/dds_xrce_profile.xml
```
Change mode to …
=> AP_DDS: increase the timeout when creating participants and entities

libraries/AP_Compass/AP_Compass_AK09916.cpp, libraries/AP_Compass/AP_Compass_AK09916.h, libraries/AP_Compass/AP_Compass_AK8963.cpp, libraries/AP_Compass/AP_Compass_AK8963.h, libraries/AP_Compass/AP_Compass_LSM9DS1.cpp, libraries/AP_Compass/AP_Compass_LSM9DS1.h
Two structs with the same name must have exactly the same definition, no matter where they occur in the program, otherwise the program is undefined. This problem is diagnosed by the compiler when LTO is enabled (which it currently not for Ardupilot).
Move each sample register struct definition into the associated class definition so they are in a different namespace and no longer identically named, thus fixing this issue.
There is no code size or functional change. Supersedes #25394
=> AP_Compass: fix C++ One Definition Rule violations

Tools/AP_Periph/GCS_MAVLink.cpp, libraries/AP_ADSB/AP_ADSB_uAvionix_UCP.cpp, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_config.h
Be consistent with our pattern of removing entire case statements throughout the try-send-message code
```
Durandal                       -8     *           -8      -8                -8     8      -8
MatekF405                      -32    *           -32     -32               -32    -24    -32
Pixhawk1-1M-bdshot             -24                -32     -32               -32    -32    -24 …
```
=> GCS_MAVLink: Tidy defines in try_send_message

libraries/SITL/SIM_GPS.cpp, libraries/SITL/SIM_GPS.h
* Read/Write of serial data has been split and exposed to ensure physics/write rate is still coupled to avoid impacting the jamming and delayed data
* The update() for backend was removed since you want read/write running at different rates.
* Removed passing the gps data in read() because it's not calculate yet, and not used.
* Created a utility to allocate the SITL instance
Needed by #23843. Broke out this logic as separate. This is needed to do active configuration quickly
=> SITL: Bump up read rate on SITL

libraries/AP_HAL_ChibiOS/hwdef/scripts/defaults_periph.h, libraries/AP_Vehicle/AP_Vehicle.cpp, libraries/Filter/AP_Filter.cpp, libraries/Filter/AP_Filter_params.cpp, libraries/Filter/AP_NotchFilter_params.cpp
- checking the build type is very rarely used and definitely not required here
- fix boilerplate to conform to normal pattern of including the config header and #if'ing based on the _ENABLED directly after that
=> Correct AP_Filter defines 

libraries/AP_RangeFinder/AP_RangeFinder.cpp, libraries/AP_RangeFinder/AP_RangeFinder.h, libraries/AP_RangeFinder/AP_RangeFinder_BLPing.cpp, libraries/AP_RangeFinder/AP_RangeFinder_BLPing.h, libraries/AP_RangeFinder/AP_RangeFinder_Backend.h, libraries/AP_RangeFinder/AP_RangeFinder_Backend_Serial.cpp, libraries/AP_RangeFinder/AP_RangeFinder_Backend_Serial.h, libraries/AP_RangeFinder/AP_RangeFinder_JRE_Serial.h, libraries/AP_RangeFinder/AP_RangeFinder_LightWareSerial.h, libraries/AP_RangeFinder/AP_RangeFinder_MAVLink.cpp, libraries/AP_RangeFinder/AP_RangeFinder_MAVLink.h, libraries/GCS_MAVLink/GCS_Common.cpp
Addresses issue #25528 "Add signal_quality to RangeFinder_State".
Any suggestions on the appropriate way to test this? It is a lightly used feature. A follow-on PR has already been created to add signal_quality to the lua range finder frontend and backend interfaces. That PR has a more complete lua autotest.
=> AP_RangeFinder Add signal_quality_pct to range finder state

libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/hwdef.dat
=> AP_HAL_ChibiOS: RADIX2HD Probe external I2C compasses (4.4 backport)

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
fixes compilation problem with gcc 10.3
```
../../libraries/AP_HAL_ChibiOS/SPIDevice.cpp: In static member function 'static void ChibiOS::SPIDeviceManager::__static_initialization_and_destruction_0(int, int)': ../../libraries/AP_HAL_ChibiOS/SPIDevice.cpp:76:18: error: statement has no effect [-Werror=unused-value]
76 | ChibiOS::SPIDesc SPIDeviceManager::device_table[] = { HAL_SPI_DEVICE_LIST };
|                  ^~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
```
=> AP_HAL_ChibiOS: base HAL_USE_SPI on devices not buses

libraries/AP_Scripting/AP_Scripting.cpp, libraries/AP_Scripting/lua_scripts.cpp
Some of the AP_Scripting error handling gcs send_texts as MAV_SEVERITY_INFO deserve to get bumped up to MAV_SEVERITY_CRITICAL
=> AP_Scripting: change some _INFO msgs to _CRITICAL

libraries/AP_Stats/AP_Stats.cpp
* We noticed that STAT_BOOTCNT wasn't incrementing. The reason was that param.reset was being set to 0 and resetting everything at boot.
=> AP_Stats: initialise parameter defaults

libraries/AP_DDS/README.md
Update docs for deploying DDS on hardware like Pixhawk 6X.
Relates to #25535
=> AP_DDS: Add instructions for running HW test

Tools/AP_Periph/Parameters.cpp, Tools/AP_Periph/Parameters.h, Tools/AP_Periph/can.cpp
Some periph nodes (e.g. ARK) have software configured termination, this allows it to be configured
=> AP_Periph: add CAN_TERMINATE for software driven termination

Tools/autotest/vehicle_test_suite.py
You can't concetenate a double to a string without fstring or a type change. This wasn't on master branch, but the test does have a failure that caused this crash. 
```
$ python3 ./Tools/autotest/autotest.py build.Plane test.Plane.MicroStrainEAHRS7
>>>> FAILED STEP: test.Plane.MicroStrainEAHRS7 at Thu Nov 23 00:14:29 2023 (can only concatenate str (not "float") to str)
Traceback (most recent call last):
File "/home/ryan/Dev/ros2_ws/src/ardupilot/./Tools/autotest/autotest.py", line 718, in run_tests
success = run_step(step)
File "/home/ryan/Dev/ros2_ws/src/ardupilot/./Tools/autotest/autotest.py", line 525, in run_step
return run_specific_test(specific_test_to_run, binary, **fly_opts)
File "/home/ryan/Dev/ros2_ws/src/ardupilot/./Tools/autotest/autotest.py", line 385, in run_specific_test …
```
=> Tools: autotest: Fix exception in junit printing for double  to str conversion during failed test

libraries/AP_HAL/utility/Socket.cpp, libraries/AP_HAL/utility/Socket.h, libraries/AP_HAL_SITL/CAN_Multicast.cpp, libraries/AP_HAL_SITL/CAN_Multicast.h, libraries/AP_HAL_SITL/SITL_Periph_State.cpp, libraries/AP_HAL_SITL/SITL_Periph_State.h, libraries/AP_Networking/AP_Networking_ChibiOS.cpp
This adds multicast support to SocketAPM, which also allows it to be used by AP_Networking for a UDP_CLIENT port. It will automatically use multicast when the destination IP is in the multicast range
This also sets up SITL to use SocketAPM, which removes two other implementations of multicast UDP sockets, simplifying the SITL code
For SITL this allows for the NET_Pn_ ports to send multicast by just choosing the right IP address range. For ChibiOS there is a bit more work needed as we don't yet enable the multicast support in lwip. I'm looking at the changes needed for lwip multicast support 
Note: this requires the following ChibiOS PR: https://github.com/ArduPilot/ChibiOS/pull/84
=> Networking: added multicast support

.git-blame-ignore-revs
This reduces commit noise in Tools/ros2 by ignoring our mass-format commit when we switched to black. I'd like to propose this as a way to start ignoring commits in ArduPilot that are format-only. 
For more info on how this feature works, see here:
https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view
This approach is used on other major repos with >1M Lines of Code like GDAL:
https://gdal.org/development/rfc/rfc69_cplusplus_formatting.html
This strategy can be used in the future to ignore things like
* flake8 format
* astyle format changes
* Fixing incorrect indent errors: 
Using automated formatting reduces developer time, so that people like Randy do not need to spend [cognitive load nitpicking …
=> .git-blame-ignore-revs: Ignore black format change

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.h
That's another one where I'm not sure you'll like it, but I like it a lot and hence dare to suggest:
The prearmchecks code in AP_Arming serve two functions, first to handle the prearmchecks at startup and report on this and second for continously checkingy health of some components. An example of the latter is the Gremsy gimbal driver, which checks for the gimbal failure flags as well as for the presence of a response from the gimbal: https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mount/AP_Mount_Gremsy.cpp#L108-L122. These tests can go from passed to fail anytime later during continious operation, and this is then reported by the AP_Arming library.
However, the AP_Arming library reports in 30 second time slices, which means that the report can be sent out up to 30 seconds …
=> AP_Arming: Reduce response time when checks go from true to false

.github/workflows/colcon.yml, Tools/autotest/sim_vehicle.py
This enables running our existing colcon tests in CI. 
https://github.com/ArduPilot/ardupilot/pull/25523 introduced a regression that would have been caught by `colcon test`.
I assumed `colcon test` was already running in CI. 
https://github.com/ArduPilot/ardupilot/pull/25552 is a fix for the regression.
The purpose of this PR is to prevent further regressions that are caught by our existing DDS tests in CI by running a new job in CI. 
Since the underlying networking code is expecting to evolve often, this will add additional testing, since AP_Networking has no automated testing yet.
Closes #25554
Depends on https://github.com/ArduPilot/ardupilot/pull/25597
=> Use colcon test in CI to protect against AP_DDS regressions

libraries/AP_HAL/utility/Socket.cpp
Add define AP_NETWORKING_SOCKETS_BROADCAST_ALLOWED to enable Broadcast IP (255.255.255.255) on sockets.
=> AP_Networking: Allow Broadcast

Tools/AP_Periph/AP_Periph.cpp, Tools/AP_Periph/AP_Periph.h, Tools/AP_Periph/Parameters.cpp, Tools/AP_Periph/Parameters.h, Tools/AP_Periph/networking.cpp, Tools/AP_Periph/networking.h, Tools/AP_Periph/networking_passthru.cpp, Tools/autotest/sim_vehicle.py, libraries/AP_Networking/AP_Networking.h
Enable Network Socket to UART passthrough
This allows a periph to be a UART to IP/Ethernet converter!
Needs more docs..
=> Periph: enable Network Socket to UART passthrough

Tools/ardupilotwaf/boards.py, Tools/autotest/sim_vehicle.py, libraries/AP_AHRS/AP_AHRS_config.h, wscript
We're looking to remove EKF2 from the codebase.
This is a first step; we'll retain the ability to compile it in on the custom build server and OEM setups and the like for at least one stable version.
=> Remove EKF2 from all builds

libraries/AR_Motors/AP_MotorsUGV.cpp
This PR extends the current pre-arm check for motor/steering config to include a check for _no_ controllable outputs.
So, the check will fail if there's no steering, throttle, sail or scripting1 servo outputs configured.
The reason for this is that I've worked through several user-support cases where the user has configured all the ``SERVOn_FUNCTION`` parameters as ``RCINn`` (RC pass-through).
This has the effect (for the user) that manual mode _seemingly_ works fine, but any other modes have no output - leading to a very confused user.
=> Rover: Extra pre-arm checks on outputs

libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.cpp
when we have aux battery information we had assumed the CAN device would provide the battery remaining percentage. We should obey the "do not use CAN SoC" with or without an AUX message
This fixes CAN battery monitors with a cell monitor
=> AP_BattMonitor: fixed battery percentage with aux info

libraries/AP_CANManager/AP_CANManager.cpp, libraries/AP_DroneCAN/examples/DroneCAN_sniffer/DroneCAN_sniffer.cpp, libraries/AP_HAL/AP_HAL_Namespace.h, libraries/AP_HAL_ChibiOS/CANFDIface.cpp, libraries/AP_HAL_ChibiOS/CanIface.cpp, libraries/AP_HAL_ChibiOS/HAL_ChibiOS_Class.cpp, libraries/AP_HAL_ESP32/system.cpp, libraries/AP_HAL_Empty/HAL_Empty_Class.cpp, libraries/AP_HAL_Linux/HAL_Linux_Class.cpp, libraries/AP_HAL_SITL/HAL_SITL_Class.cpp
Eliminates undefined behavior caused by const_casting and makes obvious to the programmer where mutability is occurring in a library.
No functional or code size change.
Tested on a real CubeOrange and verified that the board boots and DroneCAN devices still function correctly.
Supersedes #25394 .
=> AP_HAL: add and use function to get mutable reference

Tools/scripts/uploader.py
this ensures that the first port on linux is used, the 2nd port may not have mavlink enabled
this is why --upload sometimes fails to reboot the board
=> Tools: sort serial ports for uploader

AntennaTracker/Parameters.cpp, ArduCopter/Parameters.cpp, ArduPlane/Parameters.cpp, ArduSub/Parameters.cpp, Blimp/Parameters.cpp, Rover/Parameters.cpp, Rover/RC_Channel.cpp, libraries/APM_Control/AR_PosControl.cpp, libraries/RC_Channel/RC_Channel.cpp
This PR adds Rover support for the existing Circle mode auxiliary function switch.  Circle mode was added to Rover in PR https://github.com/ArduPilot/ardupilot/pull/23890 back in may.
There are also these unrelated parameter description fixes that I noticed while making the above change:
- Rover's PSC_VEL_I parameter range is updated to allow "0" which is actually the params default value.
- SYSID_MYGCS parameter increment is set to "1" for all vehicles.  This should fix MP's odd behaviour of making it easy to set the parameter to values like 254.9 (see below how this can happen)
These changes have been lightly tested in SITL.
=> Rover: Circle mode aux function support and SYSID_MYGCS param desc fix

ArduPlane/mode.cpp, ArduPlane/mode_LoiterAltQLand.cpp
Current behavior:
- When switching to mode LoiterAltQLand we set the current location as the center of the loiter.
Problem:
- If we were already performing a loiter then our circle center changes
New/Proposed behavior in this PR:
- When switching to mode LoiterAltQLand, if we were already in a loiter then continue using that same center location point
=> Plane: Mode LoiterAltQLand to reuse same loiter point if available

libraries/AP_Param/AP_Param.cpp
The add param method did not check if a param table had been added. The result was a segfault. At least people are unlikely to be adding params in flight..... but it might be worth a backport, its a very simple patch.
fixes https://github.com/ArduPilot/ardupilot/issues/25605
=> AP_Param: check dynamic param tables are available before adding a param

Tools/autotest/arducopter.py, libraries/AP_Generator/AP_Generator_IE_2400.cpp, libraries/AP_Generator/AP_Generator_IE_2400.h, libraries/AP_Generator/AP_Generator_IE_650_800.cpp, libraries/AP_Generator/AP_Generator_IE_FuelCell.cpp, libraries/AP_Generator/AP_Generator_IE_FuelCell.h, libraries/SITL/SIM_IntelligentEnergy24.cpp, libraries/SITL/SIM_IntelligentEnergy24.h
This adds support for a new protocol version that will be used by Intelligent Energy fuel cells going forward. The protocol version is auto-detected, core functionality is the same but we get better error messages and more information about the hardware and software version running on the fuel cell. It also adds a checksum to give some protection against data corruption. 
This also adds the new protocol version to our simulator and autotest. 
This is already hidden `AP_GENERATOR_IE_2400_ENABLED` define, which is currently enabled on 2M boards.
This has been flight tested by the folks at intelligent energy.
=> AP_Generator: Intelligent Energy: add support for new protocol version

libraries/AP_ExternalAHRS/AP_ExternalAHRS_backend.h
Changes in design intent from discussions with Tridge. This aligns with current implementation, which also doesn't yet handle runtime reboot.
=> AP_ExternalAHRS: Clarify public interface design intent

Rover/mode_auto.cpp, libraries/APM_Control/AR_PosControl.cpp, libraries/AR_WPNav/AR_WPNav.cpp
This PR improves improves auto modes handling of corners especially for skid-steering vehicles by keeping the position controller active during delays and pivot turns.
The detailed changes are:
1. Auto's WP submode continues to "navigate_to_waypoint" even after reaching the destination instead of switching to the Stop submode.  This means the vehicle will continue to try to correct any position errors during the delay which (for better or worse) may mean the vehicle even backs up.
2. AR_WPNav continues to update the position controller even during pivot turns.  The position controller's desired turn rate output is ignored but its desired speed is used meaning the vehicle may move forward or backwards to stay close to the segments origin.  Another positive effect is that when pivoting at a …
=> Rover: auto keeps navigating while paused at waypoints

libraries/AP_GPS/AP_GPS_GSOF.cpp, libraries/AP_GPS/AP_GPS_GSOF.h
This PR implements robust configuration in the GSOF driver. The core design change here is to read responses to configuration commands, and check they were successful.
The DCOL commands have an ACK/NACK return code (single byte). During configuration, the first step now is to disable all data channels (streaming) so they don't conflict with configuration data. 
Next, the same original commands are run as before, except this time a response is attempted to be read before continuing. 
Even though all data channels are disabled before configuration,  as the requestGSOF command starts going through each request, the unit starts sending data again. The only way I could get around this is by adding retry logic. 
While doing this, I broke apart the checksum and transaction number into separate …
=> AP_GPS: Increase robustness of GSOF configuration with ACK/NACK handling and retry logic

libraries/AP_GPS/AP_GPS_GSOF.cpp, libraries/SITL/SIM_GPS.cpp, libraries/SITL/SIM_GPS.h, libraries/SITL/SIM_SerialDevice.h
In #25525, the driver changes require active configuration parsing and response from the driver. That PR can't merge easily, and it wasn't trivial to implement because bidirectional serial simulators for GPS did not exist. This performs the leg work to set up the GPS as a full bidirectional capability.
* Enable testing GPS configuration in CI.
* Enable GSOF to implement configuration guarantees as part of initialization logic
* Enable higher code coverage prior to my planned GSOF refactor of splitting into separate library for EAHRS support
1. A call to `update_publish(const GPS_Data *d)` in the backend builds the packet and immediately publishes, so this needs to be throttled
1. A call to `update_read(const GPS_Data *d)` in the backend reads incoming data. Previously, it read one bit per …
=> SIM_GPS_GSOF - support dcol parser via new bidirectional data parsing

libraries/AP_InertialSensor/AP_InertialSensor.cpp, libraries/Filter/HarmonicNotchFilter.cpp, libraries/Filter/HarmonicNotchFilter.h, libraries/Filter/NotchFilter.cpp, libraries/Filter/NotchFilter.h
We were only setting the first notch center freq. If multi source data is missing it just does a hold on that channel so if never init and never getting data it can be stuck holding at that 0 value.
=> AP_InertialSensor: init all notch center frequencies

Tools/autotest/param_metadata/param_parse.py
fix AP_Periph param docs generator by not generating *ALL* params from AP_Vehicle when you really just want Periph's param docs.
=> Tools: fix AP_Periph param docs generator

Tools/AP_Periph/AP_Periph.h, Tools/AP_Periph/networking.h, Tools/AP_Periph/networking_passthru.cpp, libraries/AP_Networking/AP_Networking_port.cpp
=> AP_Periph: fix network build

Tools/AP_Periph/AP_Periph.h
this was causing loss of bytes on GPS peripherals as the reboot check swallowed data. The option is really only meant for debug builds to make ./waf AP_Periph --upload work, so disable by default on non-debug builds
we could just remove this option where it is in hwdef.dat files, but I know quite a few peripherals are out-of-tree, so this catches the error for those too
the symptoms were high GPS delta values
=> AP_Periph: disable UART reboot check for non-debug builds

ArduPlane/quadplane.cpp, ArduPlane/quadplane.h, ArduPlane/reverse_thrust.cpp, ArduPlane/servos.cpp
Extract from https://github.com/ArduPilot/ardupilot/pull/25416 superseding https://github.com/ArduPilot/ardupilot/pull/25631
This now always ignores pilot throttle if there is invalid RC. Currently on master you can get stuck at your last throttle in some cases with guided or suppressed passthrough and manual mode. This should be covered by the `set_control_in` call here:
https://github.com/ArduPilot/ardupilot/blob/bf6bd3a023da746cf21319138cab7cb6be3b2cef/ArduPlane/radio.cpp#L278
However that does not fix all cases. 
If we call `get_throttle_input(true)` to get the no deadzone value we call `get_control_in_zero_dz`:
https://github.com/ArduPilot/ardupilot/blob/bf6bd3a023da746cf21319138cab7cb6be3b2cef/ArduPlane/reverse_thrust.cpp#L123-L139
However, `get_control_in_zero_dz` does not use …
=> Plane: ignore invalid pilot throttle

libraries/AP_RangeFinder/AP_RangeFinder_BLPing.cpp, libraries/AP_RangeFinder/AP_RangeFinder_Benewake.cpp, libraries/AP_RangeFinder/AP_RangeFinder_Lanbao.cpp, libraries/AP_RangeFinder/AP_RangeFinder_LeddarVu8.cpp, libraries/AP_RangeFinder/AP_RangeFinder_LightWareSerial.cpp, libraries/AP_RangeFinder/AP_RangeFinder_MaxsonarSerialLV.cpp, libraries/AP_RangeFinder/AP_RangeFinder_NMEA.cpp, libraries/AP_RangeFinder/AP_RangeFinder_TeraRanger_Serial.cpp, libraries/AP_RangeFinder/AP_RangeFinder_USD1_Serial.cpp, libraries/AP_RangeFinder/AP_RangeFinder_Wasp.cpp
Fixes some minor bugs in these drivers:
- `available()` returns `uint32_t`, so assigning it into an `int16_t` isn't right
- several places were ignoring the fact read() returns `int16_t`
These have only been tested in SITL autotest.
```
Durandal                       *      *           -136    -136              -136   -136   -136
KakuteH7-bdshot                *      *           -88     -88               -88    -88    -88
MatekF405                      *      *           -88     -88               -88    -88    -88 …
```
=> AP_RangeFinder: use boolean uartdriver read method

libraries/AP_Math/crc.cpp, libraries/AP_Math/crc.h, libraries/AP_RCProtocol/AP_RCProtocol_FPort.cpp, libraries/AP_RCProtocol/AP_RCProtocol_FPort2.cpp
@Ryanf55 pointed out that "sum8" should be reserved for sum-bytes-modulus-256 only as that's the common name for that algorithm.
``` …
```
=> Rename sum8 to sum8_with_carry

libraries/AP_Scripting/applets/rover-quicktune.lua, libraries/AP_Scripting/applets/rover-quicktune.md
This greatly simplifies the Rover quiktune so that it only tunes the Steering (aka Turn rate) and Speed controller feed-forward values.  It then simply sets the corresponding P and I values to configurable ratios of the feed-forward.
While the rover tune received initial positive feedback, over time it became clear that the gains it produced were always too high and to get them into a reasonable range we had to set the backoff margin to ridiculously high values like 90% at which point it became very questionable as to whether the raise-gains-until-it-oscillates method is appropriate for rovers and boats.
This has been successfully tested in SITL and on a real vehicle.
This resolves issue https://github.com/ArduPilot/ardupilot/issues/24729
The [testing discussion is …
=> AP_Scripting: simplify Rover quick tune

Tools/scripts/build_options.py, Tools/scripts/extract_features.py, Tools/scripts/imu_uart_decode.py, libraries/AP_InertialSensor/AP_InertialSensor.cpp, libraries/AP_InertialSensor/AP_InertialSensor.h, libraries/AP_OSD/AP_OSD_ParamSetting.cpp, libraries/AP_SerialManager/AP_SerialManager.cpp, libraries/AP_SerialManager/AP_SerialManager.h, libraries/AP_SerialManager/AP_SerialManager_config.h
This allows unfiltered IMU data to be sent at the main loop rate to a UART. This is for supporting external visual odomotry systems that need to augment image data with the autopilots IMU data
was used for this ANU research project: https://github.com/STR-ANU/eqf_vio
=> Support sending raw IMU data to a UART

ArduSub/Parameters.h, Tools/autotest/ardusub.py
Bring over the parameter defaults from Sub-4.1. This will preserve existing behavior for users upgrading from sub 4.1 to 4.5.
=> Sub: copy 4.1 parm defaults

libraries/AP_Networking/AP_Networking.cpp, libraries/AP_Networking/AP_Networking.h, libraries/AP_Networking/AP_Networking_port.cpp, libraries/AP_Networking/AP_Networking_tests.cpp
this ensures we wait till DHCP has completed
=> AP_Networking: improve startup wait

libraries/AP_Networking/AP_Networking_port.cpp
and document broadcast and multicast
=> AP_Networking: fixed docs for network port types

libraries/AP_Networking/AP_Networking_ChibiOS.cpp, libraries/AP_Vehicle/AP_Vehicle.cpp
an off by one bug led to some of the memory being cacheable, which led to TCP checksum errors
=> Networking: fixed cache disable area size calculation

ArduCopter/mode_auto.cpp
=> Copter: Fix AP_MISSION_NAV_PAYLOAD_PLACE_ENABLED

ArduCopter/Copter.h, ArduCopter/Parameters.cpp, ArduCopter/mode.h, ArduCopter/system.cpp, libraries/AC_CustomControl/AC_CustomControl.cpp, libraries/AC_CustomControl/AC_CustomControl.h, libraries/AC_CustomControl/AC_CustomControl_Backend.h, libraries/AC_CustomControl/AC_CustomControl_Empty.cpp, libraries/AC_CustomControl/AC_CustomControl_Empty.h, libraries/AC_CustomControl/AC_CustomControl_PID.cpp, libraries/AC_CustomControl/AC_CustomControl_PID.h
The base `AC_AttitudeControl` class implements all the methods from `AC_AttitudeControl_Heli` and `AC_AttitudeControl_Multi` so there is no need for the extra level of indirection. 
This also changes over `AC_CustomControl` from `AC_AttitudeControl_Multi` to `AC_AttitudeControl`.
If we were to add any new methods to multi or heli attitude control this now requires that a virtual or pure virtual function be added in the base class and then overridden, but we have been following that pattern anyway.
=> Copter: use attitude control base class

Tools/autotest/quadplane.py, libraries/AP_AHRS/AP_AHRS_DCM.cpp, libraries/AP_InertialNav/AP_InertialNav.cpp, libraries/GCS_MAVLink/GCS_Common.cpp
This PR adds the ability for AP_InertialNav to fall back to a filtered numeric derivative of altitude when measuring vertical velocity whenever the AHRS refuses a request for velocities. This prevents the vertical velocity from simply freezing when GPS is lost on Plane.
Related to this issue: https://discuss.ardupilot.org/t/near-crash-in-qhover-after-gps-loss/107723/3
I also intend to make another PR to prevent DCM fallback (like Copter does) when hovering. But wanted to start with this one first.
This does cause some noise to feed into the altitude control, but this is vastly superior to the current behavior.
[Download Before/After Logs](https://github.com/ArduPilot/ardupilot/files/13169282/logs.zip)
I am also planning to test this on a physical aircraft this week.
=> AP_InertialNav: add fallback numeric vert velocity

libraries/AP_Filesystem/AP_Filesystem.cpp, libraries/AP_Filesystem/AP_Filesystem.h, libraries/AP_Scripting/AP_Scripting.cpp, libraries/AP_Scripting/AP_Scripting.h, libraries/AP_Scripting/lua_scripts.cpp, libraries/AP_Scripting/lua_scripts.h, libraries/AP_Vehicle/AP_Vehicle.cpp, libraries/GCS_MAVLink/GCS_FTP.cpp
This allows a arming check that the correct scripts are running and loaded preventing a missing SD card from meaning critical scripts are missing. 
This does a crc32 on the each file and XOR's the result for multiple files. The crc caculation gives the same result per file as the `crc32` command on linux and pages such as this one:  https://emn178.github.io/online-tools/crc32_checksum.html
However, because of float parameter transport we can't actually set the CRC we want into parameters, so this is still a draft. 
We could move to a 16 bit checksum, or add a "lock in scripts" command to set the current value to the parameters.
This is also very much a pass/fail arming check, we can only tell that the check sum failed, we cannot tell which script is missing. 
I the future this would allow …
=> AP_Scripting: add checksum of running and loaded scripts with arming check

libraries/AP_Motors/AP_MotorsHeli_Dual.h, libraries/AP_Motors/AP_MotorsHeli_Quad.h
`AP_MotorsHeli_Quad` and `AP_MotorsHeli_Dual` both inherit from `AP_MotorsHeli` which implements the same methods. There is no need to override. 
https://github.com/ArduPilot/ardupilot/blob/b5e2f9aa0a7337d9bb1d5cc4e57bb472b112a5c1/libraries/AP_Motors/AP_MotorsHeli.h#L72-L73
https://github.com/ArduPilot/ardupilot/blob/b5e2f9aa0a7337d9bb1d5cc4e57bb472b112a5c1/libraries/AP_Motors/AP_MotorsHeli.h#L120-L121
Alternately we could make the base class a pure virtual so the child class must implement.
=> AP_Motors: Heli: dual and quad: remove un-needed override methods

libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/hwdef.dat
The detection of external compasses wasn't working and I though I had it fixed in #25291. It still wasn't working because `HAL_I2C_INTERNAL_MASK` wasn't set and so no external buses were scanned (as `HAL_I2C_INTERNAL_MASK` defaults to 1). 
Note that for some reason it was working with the HMC5983 I used for testing, but other compasses, e.g., the QMC5883L were not working.
=> AP_HAL_ChibiOS: Set RADIX2HD HAL_I2C_INTERNAL_MASK

ArduSub/GCS_Mavlink.cpp, ArduSub/Parameters.cpp, ArduSub/Parameters.h, ArduSub/Sub.h, ArduSub/joystick.cpp
fix #18811 
I see some room for refactoring here, but I'd rather not do it in this PR.
=> Sub: support up to 32 buttons and 2 additional axis in MANUAL_CONTROL

libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h, libraries/SITL/SIM_GPS.cpp, libraries/SITL/SIM_GPS.h, libraries/SITL/SITL.cpp, libraries/SITL/SITL.h
this brings in the separable parts of #24899 to try to progress that work
this includes the AHRS_OPTIONS addition to allow disabling of DCM fallback in plane
=> AHRS: added AHRS_OPTIONS and jamming simulator

libraries/AP_HAL_ChibiOS/hwdef/CubeRedPrimary/hwdef.dat
checking allocation of peripherals
=> AP_HAL_ChibiOS: disable core m4 use to silence the chibios asserts

Tools/ros2/ardupilot_sitl/package.xml
This PR adds a build dependency to the `ardupilot_sitl` package that allows colcon to build `ardupilot_msgs` when asked to `colcon build --packages-up-to ardupilot_sitl`.
How to test: 
- If you have a ros2_ws already, delete `ros_msgs` from the _install_ folder
- Before this PR, run `colcon build --packages-up-to ardupilot_sitl` and verify that no ardupilot messages are built (either inspect the install folder or source the environment and then `ros2 interface list`)
- With this PR, `ardupilot_msgs` will be visible in the install folder. Verify that messages are available with `ros2 interface list`, which will show those services:
```
Services:
action_msgs/srv/CancelGoal
ardupilot_msgs/srv/ArmMotors
ardupilot_msgs/srv/ModeSwitch
```
=> ROS2 sitl package added ardupilot_msgs dependency

libraries/AP_RTC/AP_RTC.cpp
this impacts the ViewPro mount driver
=> AP_RTC: fixed ms value from AP_RTC::get_date_and_time_utc

Tools/environment_install/install-prereqs-mac.sh
* brew update was crashing due node update, which we don't use. In general we don't want to fail just because brew update can't do its job cleanly.
=> Tools: ignore the error from brew update

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/lua_bindings.cpp, libraries/AP_Scripting/lua_bindings.h
this is much more efficient than reading a byte at a time
broken out from #25678
=> AP_Scripting: added readstring for uarts

ArduPlane/commands_logic.cpp
After loading the rally point, `ModeRTL:navigate` checks if rally altitude has been reached before `altitude_error_cm` gets updated:
What this means is that with `RTL_AUTOLAND = 1`, if RTL is entered near a rally point, it will skip straight to the landing sequence instead of climbing to the rally point's altitude first.
Instead of the fix in this PR, is there a reason we don't update this variable inside of `Plane::set_target_altitude_location`? That would seem to be the better place to do it, but I wasn't 100% sure. There are multiple places where we set the altitude error variable immediately after this function:
https://github.com/ArduPilot/ardupilot/blob/50eaa1cc549cfbaa877d165255f68037459f3c3e/ArduPlane/mode_guided.cpp#L88-L89 …
=> Plane: fix bug in RTL_AUTOLAND with rally points

libraries/AP_Motors/AP_MotorsHeli_Single.cpp, libraries/AP_Motors/AP_MotorsHeli_Single.h, libraries/AP_Motors/examples/AP_Motors_test/AP_Motors_test.cpp, libraries/AP_Motors/examples/AP_Motors_test/run_heli_comparison.py
This is a none-functional change to re-work tail rotor handling into what is hopefully easier to understand. This moves the tail types to be a enum class and uses switch statements where possible. 
Helper functions have been added to check if DDFP and direct drive var pitch.
Yaw offset had been moved to its own function. 
As usual the motors example has been updated to allow testing of different tail types, it shows no difference before vs after. 
```
Single_Heli H3 Servo_only:
Inputs max change:
Roll: 0.000000
Pitch: 0.000000
Yaw: 0.000000
Thr: 0.000000
Outputs max change:
Mot1: 0.000000
Mot2: 0.000000
Mot3: 0.000000
Mot4: 0.000000
Mot5: 0.000000
Mot6: 0.000000
Mot7: 0.000000
Mot8: 0.000000
Limits max change:
LimR: 0.000000
LimP: 0.000000
LimY: 0.000000
LimThD: 0.000000
LimThU: 0.000000 …
```
=> AP_Motors: Heli: Single: rework tail rotor handling

ArduCopter/config.h, ArduCopter/mode_rtl.cpp
This PR replaces the hard coded height increase in the cone slope calculation with the parameter RTL_CLIMB_MIN.
The current behaviour determines the RTL altitude based on the minimum of:
- The parameter RTL_ALT (default 10m)
- The hash define RTL_ALT_MIN (2m)
- The current altitude + RTL_CLIMB_MIN
If we are in the cone slope we can reduce the altitude to a minimum of:
- rtl_return_dist_cm * RTL_CONE_SLOPE
- The current altitude + RTL_ABS_MIN_CLIMB (2.5m)
This means that even if you are right above the RTL location the aircraft will increase in altitude by 2.5m before descending.
This PR changes the minimum altitude in the cone to:
- rtl_return_dist_cm * RTL_CONE_SLOPE
- MAX(RTL_ALT_MIN, The current altitude + RTL_CLIMB_MIN)
This means that when you are right over the landing point the …
=> Copter: Use RTL_CLIMB_MIN in cone slope.

libraries/AP_Scripting/AP_Scripting_CANSensor.cpp, libraries/AP_Scripting/AP_Scripting_CANSensor.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/CAN_read.lua, libraries/AP_Scripting/generator/description/bindings.desc
Add filters to the CAN buffer; mask is bitwise ANDed with the frame ID and compared to value. If not match, frame is not  put to the receiving buffer
-- By default, no filters are added, and all frames are buffered, writing is not affected by filters
-- Maximum number of filters is 8 per buffer.
-- You can open as many buffers per driver as you want (every get_device() call creates a new buffer)
Usage : - driver:add_filter(mask, value) add a generic filted
- driver:add_DroneCAN_filter(message ID) to add filter for a DroneCan message.
Peter Hall rewrote my original version to a fully configurable, multi-buffer filter, so it is basically his code...
Use cases:
On a shared bus non-handled frames can be filtered out, making processing relevant frames easier and requiring less buffer and …
=> AP_Scripting: Add filtering of incoming CAN frames

libraries/AC_AutoTune/AC_AutoTune.cpp, libraries/AC_AutoTune/AC_AutoTune.h, libraries/AC_AutoTune/AC_AutoTune_Heli.cpp, libraries/AC_AutoTune/AC_AutoTune_Heli.h, libraries/AC_AutoTune/AC_AutoTune_Multi.cpp, libraries/AC_AutoTune/AC_AutoTune_Multi.h, libraries/AC_AutoTune/AC_AutoTune_config.h
Not used yet anywhere, but eases elimination of AP_PERIPH_HEAVY
=> AC_AutoTune: add and use header guards

libraries/AC_AttitudeControl/AC_WeatherVane.cpp, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Avoidance/AP_Avoidance.cpp, libraries/AP_Landing/AP_Landing.cpp, libraries/AP_Landing/AP_Landing_Deepstall.cpp, libraries/AP_Landing/AP_Landing_Slope.cpp, libraries/AP_Motors/AP_MotorsHeli_RSC.cpp, libraries/AP_OSD/AP_OSD_MSP_DisplayPort.cpp, libraries/AP_SmartRTL/AP_SmartRTL.cpp, libraries/AP_VisualOdom/AP_VisualOdom_Backend.cpp, libraries/AP_VisualOdom/AP_VisualOdom_Backend.h, libraries/AP_WindVane/AP_WindVane_Analog.cpp, libraries/AP_WindVane/AP_WindVane_Backend.cpp, libraries/AP_WindVane/AP_WindVane_ModernDevice.cpp, libraries/AR_Motors/AP_MotorsUGV.cpp
primarily to make eliminating HAL_PERIPH_HEAVY easier
=> Correct compilation when GCS library not available

ArduPlane/Plane.h, ArduPlane/mode.cpp, ArduPlane/servos.cpp
One functional change to allow take off expected to be set in manual. This will only happen if not flying armed and either high throttle or a throw is detected.
Mode enter now updates flight stage. This would usually happen at 10Hz in the `update_alt` call or in `setup_glide_slope` which RTL already calls as part of its enter.
With the flight stage race removed we can be sure that we will never be in `FlightStage::LAND` in manual mode. This means the landing servo override can be moved up with no change in behavior. 
I have also renamed `set_servos_controlled` to `set_throttle`.
=> Plane: allow takeoff setting expected in manual and move landing override up

libraries/AP_DAL/AP_DAL_GPS.cpp, libraries/AP_DAL/AP_DAL_GPS.h
removes this from the global namespace and means it isn't included when DAL isn't
update the location where we update the fields.
=> AP_DAL: remove tmp_location from global namespace

Tools/environment_install/install-prereqs-mac.sh
2023-12-11T23:04:39.8671350Z already exists. You may want to remove it:
2023-12-11T23:04:39.8679620Z   rm '/usr/local/lib/node_modules/npm/node_modules/@npmcli/agent/lib/agents.js'
2023-12-11T23:04:39.8682240Z
2023-12-11T23:04:39.8691710Z To force the link and overwrite all conflicting files:
2023-12-11T23:04:39.8700070Z   brew link --overwrite node@18
2023-12-11T23:04:39.8726220Z
2023-12-11T23:04:39.8736300Z To list all files that would be deleted:
2023-12-11T23:04:39.8744090Z   brew link --overwrite --dry-run node@18
... also remove hack to force update to succeed
=> Tools: mac: force install to avoid npm installation error

libraries/AP_SerialManager/AP_SerialManager.h
This pull request would reserve the ID 47 for our serial protocol so we don't need to keep updating our future pull request's ID as discussed in the devcall on 12/11/2023.
=> AP_SerialManager: Reserving serial protocol ID for future Vertiq IFCI implementation

ArduPlane/quadplane.cpp
Extract from https://github.com/ArduPilot/ardupilot/pull/25581, bad things are happening if we hit one of these so should be a warning rather than info.
=> Plane: Quadplane: alt and angle assist messages to warning

libraries/AP_Scripting/applets/runcam_on_arm.lua, libraries/AP_Scripting/examples/OOP_example.lua, libraries/AP_Scripting/examples/plane-doublets.lua, libraries/AP_Scripting/examples/protected_call.lua, libraries/AP_Scripting/examples/quadruped.lua, libraries/AP_Scripting/examples/test_load.lua
Slowly getting more of our scripts to pass.
=> AP_Scripting: fix some more of the easy luacheck warnings

libraries/AP_Scripting/drivers/mount-djirs2-driver.lua, libraries/AP_Scripting/drivers/mount-djirs2-driver.md
This is a replacement for PR https://github.com/ArduPilot/ardupilot/pull/24461
Three important fixes are included:
1. Support for both legacy and latest gimbal firmware
2. bug fix the reported yaw angle when the gimbal is mounted "upside down"
3. reduce the reply timeout from 1 sec to 0.1 sec.  Replies are normally received within 5ms and waiting for 1sec leads to the gimbal stopping
This has been tested on a DJIR2 running the legacy firmware.  I hope that @tpwrules can check that it also works on the latest firmware.
=> AP_Scripting: mount-djirs2 script handles latest gimbal software

libraries/AP_Scripting/AP_Scripting.cpp, libraries/AP_Scripting/AP_Scripting.h
this makes it possible to run lua scripts at higher priorities, which makes real time lua scripts (such as IMU drivers) possible
Tested with a 200Hz external AHRS driver over a UART
broken out from #25678
=> AP_Scripting: added SCR_THD_PRIORITY

libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain7.cpp
MicroStrain won't support >400Hz yet, so don't offer IMU data by default.
This matches AdNav driver behavior, and is recommended by Tridge.
=> AP_ExternalARHS: Don't offer IMU by default

libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain7.cpp, libraries/AP_ExternalAHRS/MicroStrain_common.cpp
Fix typos in configuration docs and file descriptions
=> AP_ExternalAHRS: Fix typos in configuration for microstrain7

libraries/AP_Motors/AP_MotorsHeli.cpp, libraries/AP_Motors/AP_MotorsHeli.h, libraries/AP_Motors/AP_MotorsHeli_Dual.cpp, libraries/AP_Motors/AP_MotorsHeli_Dual.h, libraries/AP_Motors/AP_MotorsHeli_Quad.cpp, libraries/AP_Motors/AP_MotorsHeli_Quad.h, libraries/AP_Motors/AP_MotorsHeli_RSC.cpp, libraries/AP_Motors/AP_MotorsHeli_RSC.h, libraries/AP_Motors/AP_MotorsHeli_Single.cpp, libraries/AP_Motors/AP_MotorsHeli_Single.h
The recent tail clean up means we can remove the spool state to rotor control state conversion that is done for each heli type. This adds a new helper function so we only have to do it in one place. It also moves `RotorControlState` inside `AP_MotorsHeli_RSC` and converts to a enum class.
Should be no functional change.
=> AP_Motors: Heli: RotorControlState to enum class and helper to remove duplication

ArduPlane/Log.cpp, ArduPlane/defines.h, ArduPlane/quadplane.cpp, ArduPlane/quadplane.h, ArduPlane/tailsitter.cpp, ArduPlane/tailsitter.h
This adds a new tailsitter log message `TSIT`. This allows moving the speed scale `Sscl` out of `QTUN`. In addition to that value this also logs the throttle only scale and the disk loading min throttle. For those last two values to be different you need to be not using throttle scaling for speed scale and be using min outflow speed with disk theory. 
This is currently at full loop rate. 
As a drive by I also put the "PIQ" message definitions behind `HAL_QUADPLANE_ENABLED` which should save a little flash on boards without quadplane.
We might want to add more stuff in the future, but this is a start.
=> Plane: Quadplane: log tailsitter speed scaling in TSIT msg

Tools/CPUInfo/CPUInfo.cpp, libraries/AP_HAL_ChibiOS/hwdef/common/hrt.c, libraries/AP_HAL_ChibiOS/hwdef/common/hrt.h, libraries/AP_HAL_ChibiOS/system.cpp
This greatly speeds up our time functions
@andyp1per this needs testing with DShot and BDShot, on F4 and H7
H743, 32 bit timer, old code:
```
micros()    0.0622 usec/call
micros16()  0.0616 usec/call
millis()    0.5189 usec/call
millis16()  0.5702 usec/call
micros64()  0.2969 usec/call
hrt_micros32()  0.2658 usec/call
hrt_micros64()  0.2769 usec/call
hrt_millis32()  0.4887 usec/call
```
H743, 32 bit timer, new code:
```
micros()    0.0627 usec/call
micros16()  0.0616 usec/call
millis()    0.2662 usec/call
millis16()  0.2787 usec/call
micros64()  0.2002 usec/call
hrt_micros32()  0.0722 usec/call
hrt_micros64()  0.1906 usec/call
hrt_millis32()  0.2456 usec/call
hrt_millis64()  0.2460 usec/call
```
matekh743 (16 bit timer) old code:
```
micros()    0.3432 usec/call
micros16()  0.0618 …
```
=> ChibiOS: faster millis micros64 implementation

ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, Rover/release-notes.txt, Rover/version.h
This is the Copter-4.4.4 and Rover-4.4.0 release. No changes vs the beta except for the version label and releases notes.
=> Copter-4.4.4 / Rover-4.4.0 release

Tools/AP_Periph/AP_Periph.h, Tools/AP_Periph/can.cpp, Tools/AP_Periph/gps.cpp, Tools/ardupilotwaf/boards.py, Tools/ardupilotwaf/chibios.py
This enables deadlines in libcandard for AP_Periph. It fixes an issue with the C-RTK2-HP where we would get long GPS deltas when the safety switch was on.
The cause was the Fix2 CAN frames being discarded early due to a combination of the low transmit slots on the F4 and the slight increase in traffic with the safety on
I suspect this may fix issues with high delta on other boards too
=> AP_Periph: added CAN deadline handling

ArduPlane/AP_ExternalControl_Plane.cpp, ArduPlane/AP_ExternalControl_Plane.h, ArduPlane/ArduPlane.cpp, ArduPlane/Plane.h, Tools/ros2/ardupilot_dds_tests/ardupilot_dds_tests/plane_waypoint_follower.py, Tools/ros2/ardupilot_dds_tests/package.xml, Tools/ros2/ardupilot_dds_tests/setup.py, Tools/ros2/ardupilot_msgs/CMakeLists.txt, Tools/ros2/ardupilot_msgs/msg/GlobalPosition.msg, Tools/ros2/ardupilot_msgs/package.xml, libraries/AP_Common/Location.h, libraries/AP_DDS/AP_DDS_Client.cpp, libraries/AP_DDS/AP_DDS_Client.h, libraries/AP_DDS/AP_DDS_ExternalControl.cpp, libraries/AP_DDS/AP_DDS_ExternalControl.h, libraries/AP_DDS/AP_DDS_Topic_Table.h, libraries/AP_DDS/Idl/ardupilot_msgs/msg/GlobalPosition.idl, libraries/AP_DDS/README.md, libraries/AP_DDS/dds_xrce_profile.xml, libraries/AP_ExternalControl/AP_ExternalControl.h, libraries/AP_Vehicle/AP_Vehicle.h
This adds DDS support for controlling global position control in LLH of Plane in alignment with REP-147's proposed [High Level Goal Interface](https://ros.org/reps/rep-0147.html#goal-interface).  It relies on [GUIDED](https://ardupilot.org/plane/docs/guided-mode.html) mode in plane. When supplying position, it's intended to be used for in features like "Click to go here" from the GCS. This is NOT a good interface for low-level carrot-on-stick kind of control due to the loitering behavior around the target point.
* `map` frame in ROS would be used for this type of control
* Only plane implements the interface,  other vehicles will ignore the command.
* Only position control is supported. The ROS interface supports velocity and accel, but it's ignored for now.
In ArduPilot repo:
```bash …
```
=> DDS - REP-147 Goal Interface Support for Plane (position only)

ArduPlane/Parameters.cpp, ArduPlane/Parameters.h, ArduPlane/Plane.h, ArduPlane/servos.cpp
Added a sub class to tidy the functionality slightly. This will cost a little flash, the key thing is to split the application to min/max and to the actual throttle output. There are not both applied in all cases. Spiting them now paves the way for further re-work later.
=> Plane: rework forward throttle voltage compensation into sub class and split min/max from throttle

libraries/AP_ICEngine/AP_ICEngine.cpp, libraries/AP_Relay/AP_Relay_Params.cpp, libraries/AP_Relay/AP_Relay_Params.h
With the new relay re-work (https://github.com/ArduPilot/ardupilot/pull/25108) its very easy to add new functions. This adds a relay output for ICE starter, very simple change as a `set_starter` method already exists.
=> AP_ICEngine: add support for starter relay

libraries/AP_HAL_ChibiOS/SPIDevice.h
F1 does not have palReadLineMode()
fixes ZubaxGNSS build
=> HAL_ChibiOS: fixed SPI build on F1xx

Tools/CPUInfo/CPUInfo.cpp, libraries/AP_HAL_ChibiOS/hwdef/common/hrt.c, libraries/AP_HAL_ChibiOS/hwdef/common/hrt.h, libraries/AP_HAL_SITL/system.cpp, libraries/AP_Math/div1000.h, libraries/AP_Math/tests/test_math.cpp
This removes the assembler implementation for an equivalent (and just as fast) C implementation,
used by millis() so speed is critical
this means we can test it in CI and use it in SITL
=> ChibiOS: reimplement div1000 in C

libraries/AP_Motors/AP_MotorsHeli_Single.cpp
NFC, as I was updating heli tail stuff for yaw trim add,I found this info lacking in metadata that would help users setting up
=> AP_Motors:expand heli tail param metadata

libraries/AP_Baro/AP_Baro.cpp
This changes the time constant from 15-20s to around a minute.
This slows down the slew rate when changing BARO_ALT_OFFSET. The reason it's so slow is to hide the change from the EKF. If it happens too fast then the EKF gets angry at the baro. When I added this param 8 years ago the slew-rate would take about 15-20 seconds and the EKF was happy with that. However, recently I've seen the EKF start to complain about it so I guess it's gotten better. Good problem to have!
=> AP_Baro: slow down slew rate of param BARO_ALT_OFFSET

libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h, libraries/AP_Landing/AP_Landing.cpp, libraries/AP_Landing/AP_Landing.h, libraries/AP_Landing/AP_Landing_Slope.cpp, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
I've written this code a few times in scripts and I just realized I wrote it 7 years ago in AP_Landing.. so lets move it to AP_AHRS. It would turn [messy LUA code like this](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/jump_tags_into_wind_landing.lua#L91-L104) into 1 line.
wind_alignment():
You pass a heading to wind_alignment and it will return from -1 to +1 how aligned it is with the wind. +1 is perfectly inline headwind (your heading matches wind heading), 0 is perfect cross-wind, and -1 is perfect tailwind. This is useful to check arbitrary headings to the wind such as different legs of an auto mission
head_wind():
calls wind_alignment with our current yaw and converts to the meters/sec component
=> AHRS: move wind helper maths functions from AP_Landing to AP_AHRS

ArduPlane/mode_takeoff.cpp
NFC...changed to match actual takeoff_calc_roll code
=> Plane: correct TKOFF_LVL_ALT metadata

libraries/AP_Relay/AP_Relay_Params.cpp
NFC....except without this a user cant use these functions!!
=> AP_Relay:correct function param metadata

libraries/AC_Avoidance/AP_OABendyRuler.cpp, libraries/AC_Avoidance/AP_OABendyRuler.h, libraries/AC_Avoidance/AP_OADijkstra.cpp, libraries/AC_Avoidance/AP_OADijkstra.h, libraries/AC_Avoidance/AP_OAPathPlanner.cpp, libraries/AC_Avoidance/AP_OAPathPlanner.h, libraries/AC_WPNav/AC_WPNav.cpp, libraries/AC_WPNav/AC_WPNav.h, libraries/AC_WPNav/AC_WPNav_OA.cpp, libraries/AC_WPNav/AC_WPNav_OA.h, libraries/AR_WPNav/AR_WPNav.h, libraries/AR_WPNav/AR_WPNav_OA.cpp, libraries/AR_WPNav/AR_WPNav_OA.h
This allows Copters using Dijkstras avoidance to fly through waypoints at the regular speed (using SCurves) instead of always stopping.  This behaviour is enabled by setting AVOID_OPTIONS's bit 2 (e.g set to "4).  The parameters' default value has not been changed so the existing behaviour is maintained for unsuspecting users.
This change does add some danger of fence breaches:
1. During OA "processing" (when the vehicle has just arrived at a WP and Dijkstras is calculating a safe path to the next WP) the vehicle will start moving towards the next waypoint.  If a fence is placed very close to the waypoint the vehicle may breach it but this is unlikely because the vehicle will have stopped at the waypoint because Dijkstar's has been enhanced to check again one more waypoint.  So the …
=> Copter/AC_Avoidance: option to support "fast waypoints" when using Dijkstras

Tools/scripts/decode_ICSR.py
The `decoder_m4_pendsvset` is not used instead `decoder_m4_pendstset` is used twice. Spotted while porting to js for https://github.com/ArduPilot/WebTools/pull/98
=> Tools: Scripts: decode_ICSR: use `decoder_m4_pendsvset` function

libraries/AP_Scripting/examples/SN-GCJA5-particle-sensor.lua, libraries/AP_Scripting/examples/mission-save.lua
https://github.com/ArduPilot/ardupilot/pull/22171 means that `io.open` can return `nil` so we need to check. Previous behavior was to always return a object.
=> AP_Scripting: examples: update examples for fixed io.open behaviour

libraries/AP_AHRS/AP_AHRS.cpp
Look at the parameter to see if DCM uses GPS; if not don't prefer DCM for using GPS.
=> Don't Switch to DCM to get Better GPS if DCM Isn't Using GPS

libraries/AR_Motors/AP_MotorsUGV.cpp
This PR fix the support for omni vehicles in rover that seems broken for some time. We can not use ```is_omni()``` here because it check for ```_motors_num > 0``` which will be set in ```setup_omni()```.
=> AR_Motors: fix support for omni vehicles

Tools/autotest/ardusub.py, libraries/AP_RangeFinder/AP_RangeFinder_Backend.cpp, libraries/AP_RangeFinder/AP_RangeFinder_Backend.h, libraries/AP_RangeFinder/AP_RangeFinder_Lua.cpp, libraries/AP_RangeFinder/AP_RangeFinder_Lua.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/rangefinder_quality_test.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/lua_bindings.cpp, libraries/AP_Scripting/lua_bindings.h
This PR adds support for signal_guality to the lua range finder driver. This involves extending the lua interface to get signal_quality for scripts that would like to make decisions based on range finder measurement signal_quality. It also involves setting signal_quality for lua range finder device drivers.
Here are a few scenarios where the functionality in this PR would be useful:
- A script wants to get the signal_quality of a distance measurement provided by an attached Range Finder.
- A lua hardware driver could be developed for a range finder device that provides signal_quality data.
- A sitl lua driver could be developed that provides synthetic signal_quality data for testing other ardupilot algorithms
This PR includes:
- modifications to the LUA interface
- modifications to the …
=> AP_Scripting: Add lua interface to access range finder signal quality

Tools/autotest/vehicle_test_suite.py
the log being downloaded can be very large, and times out. Setting LOG_DISARMED=1 gives us a small log to download
=> autotest: fixed flapping sub log download test

libraries/AP_VideoTX/AP_VideoTX.cpp
This functionality was lost when a significant rewrite of this code was done in commit 0658f060301c9230c5b170bbad005dee68fbcd8a
This restores the documented use of MAX_POWER for the 6 position switch power control.
Without this change I was unable to select 25mw via a radio channel on two builds with two different VTX boards controlled via IRC TRAMP.
I've tested this change with the following hardware and VTX protocols:
GOKU F405 1-2S 12A 5-in-1 400mw + ELRS AIO board (TRAMP)
GOKU VTX 625 (TRAMP)
TBS Unify Pro Nano (SA)
=> Restore use of the VTX_MAX_POWER parameter

libraries/AP_HAL_SITL/CANSocketIface.cpp
Compilation started breaking after a system update with:
```
CXX Compiler                             : g++ 13.2.1 
```
I suspect that `stdint` types have been pulled implicitly by some other header and they aren't for some reason anymore, so including the header explicitly ensures it doesn't break and shouldn't affect anything negatively if it's already included.
=> AP_HAL_SITL: ensure stdint include

libraries/AP_NMEA_Output/AP_NMEA_Output.cpp
There is an extra zero before the seconds in the messages.
For example: now 11:22:33.00 is `1122033.00` but it should be `112233.00`
=> AP_NMEA_Output: fix time format

ArduPlane/GCS_Mavlink.cpp, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
With code compiled out:
```
Durandal                       -616   *           -632    -632              -672   -608   -608
HerePro             -416                                                                  
KakuteH7-bdshot                -400   *           -424    -424              -456   -384   -392
MatekF405                      -400   *           -416    -416              -456   -384   -384
Pixhawk1-1M-bdshot             -408               -416    -424              -456   -384   -392 …
```
=> Return MAV_RESULT_COMMAND_INT_ONLY if command-long support compiled out

libraries/AP_HAL/UARTDriver.cpp, libraries/AP_HAL/UARTDriver.h, libraries/AP_NMEA_Output/AP_NMEA_Output.cpp
altitude from NMEA_Output was zero due to passing a uint16_t for hdop, and it didn't work over network ports due to lack of receive time constrain function
=> GPS: fixed 2 NMEA bugs

Tools/AP_Periph/can.cpp
We use `ins` for inertialsensor, so stop using it as a local
No change in compiler output:
```
Board,AP_Periph
AR-F407SmartBat,*
ARK_CANNODE,*
AeroFox-Airspeed,*
AeroFox-Airspeed-DLVR,*
AeroFox-GNSS_F9P,*
AeroFox-PMU,*
```
=> AP_Periph: rename rx-protocol-stats ins local to avoid conflict with ins singleton

libraries/AC_PID/AC_PID.cpp, libraries/AC_PID/AC_PID.h, libraries/AC_PID/AP_PIDInfo.h, libraries/AP_Logger/LogFile.cpp
This does some tidying of the interface and adds some logging.
- moves `update_i` and `_slew_rate_tau` to protected, this means external code cannot see them, nothing it using them so there is no external change.
- removes `get_pid()` and `get_pi()` from the header as the functions are not implemented
- updates `get_p`, `get_d` ~~and `get_i`~~ to return the value from `_pid_info` this means there exactly the same values as would be summed and returned from the `update_all` call. Currently P and D are re-calculated and thus skip the application of slew limit and P+D max. I term can be set externally so currently you would not get the same value as was used if there had been a I term set. 
- `get_ff` is now const this is in line with the other `get_..` methods
-  `set_integrator` with …
=> AC_PID: tidy interface and add logging of resets and I term sets

Tools/autotest/rover.py
this way if the test gets an exception part-way through the scripts are removed from the directories appropriately
Tests could still leave the wrong Rover binary running if they get an exception part-way through.
=> autotest: Use contexts to control script lifetimes in networking tests

libraries/AP_Camera/AP_Camera.cpp
=> AP_Camera: correct compilation when AP_CAMERA_RELAY_ENABLED is 0

libraries/AP_HAL_ChibiOS/hwdef/Pixhawk6C/hwdef.dat
BMI 055 is about to be discontinued. BMI 088 and BMI 055 have the same functions and PCB footprint.  We use BMI088 to replace BMI055 on the lastest hardware revision.  These changes have been tested on Pixhawk6c and pixhawk6c-MINI. They can all work properly.
=> Add support for BMI088 on Pixhawk6c

libraries/AP_Relay/AP_Relay.cpp, libraries/AP_Relay/AP_Relay.h
This allows hwdef to look for more then 6 hwdef's. This won't have an impact unless you need it, I have existing systems that need more then this, but didn't want to force it on others. This also allows you to shrink the number on a system if you want. Tested briefly on CubeOrangePlus
=> AP_Relay: allow hwdef to provide more then 6 relays

libraries/AP_InertialSensor/AP_InertialSensor_SITL.cpp
It is better to use SIZEOF than to set a direct value.
=> AP_InertialSensor: Specify the number of arrays by sizeof

libraries/AP_Networking/AP_Networking_Config.h, libraries/AP_Networking/lwip_hal/arch/sys_arch.cpp
this saves a bit of compile time, but also means devs not doing networking don't need to update the submodules
=> AP_Networking: don't build lwip code if not needed

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
currently the code populates the hash in "write_mcu_config", something in what one might consider an "output" step, rather than when we're processing the lines in the hwdef.
Fix that.  And some ugliness recently introduced around a specific define.
Tested by using `configure_all.py` and comparing the output directories.
```
2025  ./Tools/scripts/configure_all.py --copy-hwdef /tmp/new-hwdefs
2026  git checkout master
2027  git submodule update --init --recursive
2028  ./Tools/scripts/configure_all.py --copy-hwdef /tmp/master-hwdefs
2029  diff -ur /tmp/master-hwdefs /tmp/new-hwdefs/
```
=> chibios_hwdef.py: populate intdefines as part of parsing, not output

Tools/autotest/logger_metadata/enum_parse.py
=> autotest: fixed missing Blimp for enum parsing

libraries/AP_Networking/lwip_hal/arch/evtimer.c
the firmware server uses --out option to waf configure which changes the include paths
this is causing the build server to not produce binaries
=> AP_Networking: fixed build of evtimer.c on firmware server

libraries/AP_HAL_ESP32/WiFiDriver.cpp, libraries/AP_HAL_ESP32/WiFiUdpDriver.cpp, libraries/AP_HAL_ESP32/WiFiUdpDriver.h
Update the WiFi initialization code to the newer ESP-IDF (4.2+) and add WiFi station mode for both TCP and UDP.
Added ability to select the softAP channel too.
Additional definitions:
```
#define WIFI_STATION 1
#define WIFI_HOSTNAME "ArduPilotESP32"
#define WIFI_SSID_STATION "myhomeSSID"
#define WIFI_CHANNEL 7
```
=>  Update the WiFi init code to the newer ESP-IDF (4.2+) and add WiFi station mode for both TCP and UDP.

libraries/AP_HAL_ChibiOS/hwdef/common/malloc.c
this fixes DMA failures affecting IMUs on H743. The reason for the failure is not yet clear, but this reverts back to our old stragegy of always using the bouncebuffer on H7 as a quick workaround
update: found the reason for the failure. The problem is the SPIv3 driver for H7 doesn't do cache invalidation/flush. We rely on the bouncebuffer code to do that.
=> HAL_ChibiOS: fixed DMA on SPI on H743

libraries/AP_Scripting/AP_Scripting.cpp, libraries/AP_Scripting/AP_Scripting.h, libraries/AP_Scripting/lua_bindings.cpp
this leaked the SocketAPM on each sendfile() call, we now rely on the script calling close(). The net_webserver.lua is already using close() correctly, this change just makes close able to find the socket
tested on CubeOrange and in SITL, confirmed this fixes the leak. Found with valgrind
=> AP_Scripting: fixed memory leak in sendfile()

libraries/AP_TECS/AP_TECS.cpp, libraries/AP_TECS/AP_TECS.h
This PR improves TECS deceleration rates by allowing to decrease speed more rapidly, the faster a plane is going.
The current calculation for `velRateMin` scales incorrectly with airspeed, where currently, the max allowable velocity rate _decreases_ as velocity increases. i.e. the faster an aircraft is going, the less-quickly it's able to slow down. This is particularly problematic on aircraft which operate over a wide range of speeds or which have a large difference between `TECS_SINK_MIN` and `TECS_SINK_MAX`, since they are empirically determined.
This change introduces discrete calculations for:
* `_STEdot_neg_max` — Specific total energy rate at max speed (using `TECS_SINK_MAX`)
* `velRateNegCruise` — Velocity rate at cruise speed (existing velocity rate calc at `TRIM_ARSPD_CM`)
* …
=> AP_TECS: scale velRateMin correctly with airspeed

libraries/AP_HAL/SIMState.cpp, libraries/AP_HAL_SITL/SITL_State.cpp, libraries/AP_OpticalFlow/AP_OpticalFlow_SITL.cpp, libraries/AP_Proximity/AP_Proximity_SITL.cpp, libraries/SITL/SIM_Aircraft.cpp, libraries/SITL/SITL.h
..... required to have OpticalFlow-on-simulated-periph work correctly (`AP_OpticalFlow_SITL` uses it)
=> Set height AGL in simulated periph state

ArduCopter/AP_Arming.cpp, ArduCopter/AP_Arming.h, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.h
```
MatekF405                      -24    *           -32     -32               -32    -32    -32
Pixhawk1-1M-bdshot             -32                -32     -32               -32    -32    -32 …
```
=> Be more consistent withb our defines around optional features

libraries/SITL/SIM_Frame.cpp
This line was referencing the config type from the wrong variable array (vars rather than per_motor_vars), making it so that per motor variables (motor position, thrust vector, and yaw factor) could not be loaded into SITL
=> SITL: SIM_Frame: fixed per_motor_vars config loading

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
Useful hooks to have, since there's a fair amount of work being done for us.
=> AP_Scripting: Add bindings for jump to landing and abort in the mission

ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduCopter/mode_throw.cpp
Allow the user to set altitude restrictions in which a throw can be detected via parameters.
This feature has been really useful preventing accidental throw detection, which I am sure many users struggled with during fully autonomous missions.
The scenario in which we use it is with a VTOL plane which has many copters attached to it.
The copters would tend to detect a throw and attempt to stabilize when still attached to the plane, during transition to fixed wing or turbulence.
The problem is solved by simply setting the throw altitude max parameter below the transition altitude.
Only when the plane descends to perform the drop copters are able to stabilize.
Code modifications are very simple, testing was performed in SITL to ensure the feature works as intended with different parameter …
=> Copter: Throw mode check altitude params

Tools/scripts/uploader.py
This is needed to prevent Windows from hanging when trying to write to
"Standard Serial over Bluetooth" ports.
=> Tools: uploader.py: set write_timeout

libraries/AR_Motors/AP_MotorsUGV.cpp
This fix the prearm check for omni vehicle when only omni motors are defined.
=> AR_Motors: fix prearm for omni outputs

libraries/AP_Mount/AP_Mount_Backend.cpp, libraries/AP_Mount/AP_Mount_Backend.h, libraries/AP_Mount/AP_Mount_Gremsy.cpp, libraries/AP_Mount/AP_Mount_SToRM32.cpp, libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp, libraries/AP_Mount/AP_Mount_Scripting.cpp, libraries/AP_Mount/AP_Mount_Servo.cpp, libraries/AP_Mount/AP_Mount_Siyi.cpp, libraries/AP_Mount/AP_Mount_SoloGimbal.cpp, libraries/AP_Mount/AP_Mount_Viewpro.cpp, libraries/AP_Mount/AP_Mount_Xacti.cpp
This is a slightly simplified version of PR https://github.com/ArduPilot/ardupilot/pull/25850
This PR makes it more convenient for users to retake manual control of the gimbal using RC input.  Currently users can only retake control after pushing a button on the ground station (see below).
With this new change, the Mount's mode is automatically changed to RC_TARGETING if the user moves one of the configured mount RC inputs by at least the channel's deadzone or 10pwm (whichever is larger).  The only exception is when the mode is in RETRACT mode.
This has been tested on real hardware (a CubeOrange paired with a Xacti camera gimbal) and I could easily move between controlling the gimbal with the RC inputs and Mission Planner's Payload screen.
=> AP_Mount: switch to RC_TARGETING on RC input

libraries/AP_HAL_ChibiOS/HAL_ChibiOS_Class.cpp
Fixes building of the `NucleoH743` which has `HAL_SPI_CHECK_CLOCK_FREQ` defined but no SPI bus (there are pins but no devices by default). Reported on discord: https://discord.com/channels/674039678562861068/780728024756781056/1194021251602202767
=> AP_HAL_ChibiOS: Only test SPI clock if  SPI is enabled

libraries/AP_Scripting/applets/Heli_idle_control.lua, libraries/AP_Scripting/applets/Heli_idle_control.md
allows manual and/or automatic engine rpm control during ground idling.
Handles transition to flight regime and does not affect pre-existing functinalities (idle setting for manual autorotation -H_RSC_AROT_IDLE).
Video below for reference (ch10 as script auxiliary potentiometer/ H_RSC_AROT_IDLE set to 6):
https://www.youtube.com/watch?v=Iau5VVvgd3A
=> TradHeli: script for idle control 

Tools/autotest/vehicle_test_suite.py, libraries/AP_DroneCAN/AP_DroneCAN_serial.cpp, libraries/AP_Networking/AP_Networking_port.cpp
This fixes the bug that caused a critical error during my recent demonstration video.
We should not hold the write semaphore when we are doing socket operations as the lwip layer can block if (for example) PPP is reconnecting
Also changed CAN serial ports to use the same strategy
=> AP_Networking: fixed lockup bug with network port send

libraries/AP_Mount/AP_Mount_Backend.cpp, libraries/AP_Mount/AP_Mount_Backend.h
This sends a [GIMBAL_MANAGER_STATUS ](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L5997C9-L5997C9)message in cases where a [DO_GIMBAL_MANAGER_CONFIGURE](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L1662) command has led to a change in who/what is in control of the gimbal.
This change has been split out and simplified from this original PR https://github.com/ArduPilot/ardupilot/pull/25850 and is part of the ongoing work to create [QGC's custom gimbal control screen](https://github.com/mavlink/qgroundcontrol/pull/10667).
The original justification for the change is below:
_By default we are sending this message at 0.2 Hz. This is totally fine as no more rate is needed, but whenever control changes it is …
=> AP_Mount.cpp: send gimbal_manager_status msg when control changes

ArduPlane/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.h
saves bytes and removes some redundant code which is obscured when the ifdefs are inside the body
... also adds a missing include and a redundant return
=> AP_Arming: remove entire airspeed_checks if AP_AIRSPEED_ENABLED is off

libraries/AP_BattMonitor/AP_BattMonitor.cpp, libraries/AP_BattMonitor/AP_BattMonitor.h, libraries/AP_BattMonitor/AP_BattMonitor_Backend.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Backend.h, libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.cpp, libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.h, libraries/AP_BattMonitor/AP_BattMonitor_Logging.cpp, libraries/AP_BattMonitor/LogStructure.h
This adds state-of-health percentage logging for DroneCAN battery backends.  I've reduced the scope of this PR by removing the reporting via MAVLink.
The [DroneCAN DSDL message](https://github.com/dronecan/DSDL/blob/master/uavcan/equipment/power/1092.BatteryInfo.uavcan#L47) already includes this field and the [Tattu DroneCAN batteries](https://ardupilot.org/copter/docs/common-tattu-dronecan-battery.html) send the value but we haven't made use of it until now.
This has been tested on real hardware (CubeOrangePlus with a Tattu battery).  Below is a screenshot showing the SOH of 95%.
=> BattMonitor: DroneCAN batteries report and log state-of-health percentage

libraries/AP_Networking/AP_Networking_Config.h, libraries/AP_Networking/config/lwipopts.h, libraries/AP_Networking/wscript
Add config for macOS / clang to `lwipopts.h`.
- Replaces: https://github.com/ArduPilot/lwip/pull/1
System
- macOS Sonoma 14.2.1
- Xcode 15.1 
1. Run the AP_DDS / UDP SITL tests on macOS (networking required for this to work because of Socket_native). 
2. PPP webserver test (following the rover auto test example) 
3. DDS and webserver via PPP
- Update DDS_IPn params to the host / companion computer IP address
- Run the micro-ROS agent: 
```
ros2 launch ardupilot_sitl micro_ros_agent.launch.py transport:=udp4 refs:=$(ros2 pkg prefix ardupilot_sitl)/share/ardupilot_sitl/config/dds_xrce_profile.xml verbose:=6
```
=> AP_Networking: enable networking on macOS

Tools/AP_Bootloader/AP_Bootloader.cpp, Tools/AP_Bootloader/support.cpp
- sometimes a method doesn't exist
- a define was nested within another #if which it shouldn't have been
=> Correct defines use in Bootloader code

Tools/scripts/build_binaries.py
Builds .bin file for Here4FC as its needed to be used when doing first update from Periph firmware
=> Tools: add bin file when building binaries for Here4FC

Tools/ros2/ardupilot_sitl/src/ardupilot_sitl/launch.py
Update the micro-ROS agent launch script to pass the verbose flag.
This is the new expected behaviour. Previously the default verbosity level of 4 would always be set.
```bash
$ ros2 launch ardupilot_sitl micro_ros_agent.launch.py transport:=udp4 refs:=$(ros2 pkg prefix ardupilot_sitl)/share/ardupilot_sitl/config/dds_xrce_profile.xml verbose:=6
[INFO] [launch]: All log files can be found below /Users/rhys/.ros/log/2024-01-08-14-30-56-023186-MacBookPro2-2.local-4579
[INFO] [launch]: Default logging verbosity is set to INFO
namespace:        
transport:        udp4
middleware:       dds
verbose:          6
discovery:        7400
port:             2019
refs:             /Users/rhys/Code/ros2/humble/ros2-ardupilot/install/ardupilot_sitl/share/ardupilot_sitl/config/dds_xrce_profile.xml
[INFO] …
```
=> Tools: ros2: pass verbose flag to micro-ROS agent.

Tools/AP_Bootloader/board_types.txt
Reserve range of Board IDs for Sierra.
=> Tools: Reserve board IDs for Sierra

libraries/AP_ESC_Telem/AP_ESC_Telem.cpp, libraries/AP_ESC_Telem/LogStructure.h
The values of RPM and raw RPM come to logging as `float`s, but were logged as `int32`s (multiplied by 100). This PR fixes it.
This PR is mutually exclusive with #25977.
[Log sample](https://github.com/ArduPilot/ardupilot/files/13932894/24-01-14_19-31-08_float_rpm.bin.tgz) is attached and looks OK.
=> AP_ESC_Telem: Log RPM and raw RPM values as floats

libraries/AP_HAL_ChibiOS/hwdef/revo-mini-sd/hwdef.dat
this isn't built on the firmware server, so we won't notice when it dies
In this case the SMBUS batter define was being set differently
Also remove some redundant defines which come from includes anyway
=> hwdef: correct compilation of revo-mini-sd

libraries/AP_HAL_ChibiOS/hwdef/common/stm32_util.h, libraries/AP_IOMCU/iofirmware/iofirmware.cpp
`__main_thread_stack_base__` and `__main_thread_stack_end__` are variables whose address is defined to be the corresponding part of the stack. These are declared as `extern stkalign_t` in ChibiOS code, and being declared as `extern uint32_t` in ArduPilot code creates a warning at link time when using LTO. Correct the declaration to eliminate this warning.
Also update `__main_stack_base__` and `__main_stack_end__` which don't currently trigger this warning but serve similar purposes and so might in the future.
The hardware expects an alignment of `stkalign_t` (which is 8 bytes) and the linker script defines the variable values with this alignment as well, so this is safe.
No code size or functional change.
=> Match thread stack pointer types to ChibiOS

ArduPlane/Plane.h, ArduPlane/mode.cpp, ArduPlane/mode.h, ArduPlane/quadplane.cpp, ArduPlane/quadplane.h, ArduPlane/servos.cpp
More throttle output re-work, this is another step towards keeping it contained within the flight modes. 
There is a little more going on in this PR than the others, I have split each change into its own commit, which hopefully when reviewed in sequence will make it more clear. 
Firstly this adds a helper for quadplane `allow_forward_throttle_in_vtol_mode` this is so we can used it in two places in the last commit.
Secondly this adds in early returns in the `set_throttle` function for disarmed and throttle suppressed. This makes the final commit simpler by ensuring min/max limits are never applied in that case.
Finally this moves the decision if min/max limits should be applied down in to the flight mode. The existing logic is duplicated (for now) in `mode.cpp`, the same function is used …
=> Plane: ask flight mode if min/max throttle limits should be applied

libraries/AP_ADSB/AP_ADSB_Sagetech_MXS.cpp, libraries/AP_ADSB/AP_ADSB_Sagetech_MXS.h
the same message is sent in two places, and much code was duplicated.
This work sponsored by SpektreWorks
```
Durandal                       -184   *           -184    -184              -184   -184   -184 …
```
=> AP_ADSB: de-duplicate packing of operating message

libraries/AP_ADSB/AP_ADSB.cpp
Creates a null-terminated temporary copy of the string on the stack so we don't lose the last character in the callsign when sending the statustext.
=> AP_ADSB: emit last char for callsign in statustext

libraries/AP_ADSB/AP_ADSB_Sagetech_MXS.cpp
Documentation specifies WGS-84 ellipsoid.
This work sponsored by Spektreworks
=> AP_ADSB: send absolute height in GPS packet to MXS device

BUILD.md, Tools/completion/bash/_waf, Tools/completion/zsh/_waf, wscript
This adds a waf command and completions for the submodulesync script.
Simpler version of https://github.com/ArduPilot/ardupilot/pull/23898 since it doesn't mess with normal distclean
Note : I called it `submodulesclean` to be more in common with other projects but am not tied to it. 
To Fix:  I couldn't get `./waf --help` to show the `submodulesclean` command ?
=> Waf add submodulesclean

libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h, libraries/AP_AHRS/AP_AHRS_External.cpp, libraries/AP_AHRS/AP_AHRS_External.h, libraries/AP_AHRS/AP_AHRS_config.h
For orthogonality; allows for a specific backend to be compiled in with `AP_AHRS_BACKEND_DEFAULT_ENABLED` set to false and just the one you want enabled
The zero-rather-than-* comes about with the include of `AP_AHRS_Backend.h`; need this include because otherwise we fail to compile because AP_AHRS uses bits and pieces from AP_AHRS_Backend.h and it only comes in transitively ATM
```
KakuteH7-bdshot                0      * …
```
=> Add and use AP_AHRS_BACKEND_EXTERNAL_ENABLED

libraries/AP_HAL_SITL/SITL_State.cpp
... or at least not die instantly because instance-0 has bound this port
I don't know what a complete fix for this looks like, as peripherals also do instance numbers.
Perhaps the "fix" is to only bind this port on instance 0; no owrry about which vehicle a peripheral needs to listen to to get its servo data then...
=> AP_HAL_SITL: allow sim_vehicle.py -I to work again

libraries/AP_RCProtocol/AP_RCProtocol_Backend.h, libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp, libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp, libraries/AP_RCTelemetry/AP_GHST_Telem.cpp
This removes the CRSF version spam that you can get while protocol detection is going on. With this change CRSF will only ping for versions and make rf changes if the front end protocol has been detected.
=> CRSF device info checks

Tools/autotest/param_metadata/htmlemit.py, Tools/autotest/param_metadata/jsonemit.py, Tools/autotest/param_metadata/mdemit.py, Tools/autotest/param_metadata/param.py, Tools/autotest/param_metadata/rstemit.py, Tools/autotest/param_metadata/xmlemit.py, libraries/RC_Channel/RC_Channel.cpp
This is an alternative to PR https://github.com/ArduPilot/ardupilot/pull/25963 and adds support for a new "@SortValues : AlphabeticalZeroAtTop" parameter description and this new definition has been added for the RCn_OPTION parameters.
Once merged this will affect the apm.pdef.xml files that are found [here for Copter](https://autotest.ardupilot.org/Parameters/ArduCopter/).
This PR does not change the "emitter" that produces the html files for the wiki.  E.g. the RCn_OPTION sorting on our wiki [here](https://ardupilot.org/copter/docs/parameters.html#rc1-option-rc-input-option) is unaffected.
As a drive-by we also fixed an existing bug in the JSON emitter that was producing unnecessary "__field_text" entries.  Open [this file](https://autotest.ardupilot.org/Parameters/ArduCopter/apm.pdef.js …
=> Sort Values in RCn_OPTIONS in apm.pdef.xml

libraries/AP_Relay/AP_Relay.cpp
This adds a pre-arm check for conflicting pins between two relays. If the user has two functions using the same pin neither will work as expected. This could be especially bad if the pin for something critical is also used by some thing trivial, for example parachute and camera trigger.
=> AP_Relay: pre-arm check for pin conflicts between relays.

ArduPlane/mode.cpp, ArduPlane/mode.h, ArduPlane/servos.cpp
A continuation of the plane throttle output tidy ups. This asks the flight mode if voltage compensation should be applied. This can't be moved up to the flight mode when the throttle is set because throttle is used and modified in a number of other places. Voltage compensation must be the last thing done before outputting.
=> Plane: ask mode if battery voltage compensation should be done

libraries/AP_HAL/UARTDriver.h, libraries/GCS_MAVLink/GCS_MAVLink.cpp
this prevents the panic in SITL when we get zero writes on a locked port
=> SITL: fixed serial passthru

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py, libraries/AP_Param/AP_Param.cpp, libraries/AP_Param/AP_Param.h
Corrects defaults on MatekL431-RC
=> hwdef: enable ROMFS if we have a defaults filepath to embed

libraries/AP_ExternalAHRS/AP_ExternalAHRS.h
We are planning to add our IMU support as an ExternalAHRS in the Ardupilot.
=> AP_ExternalAHRS: Reserve Aeron ID

libraries/AP_AccelCal/AP_AccelCal.cpp, libraries/AP_RTC/AP_RTC.cpp
this is a stack variable, so assigning a new value to it in a return statement is pointless.
Pointed out by clang-scan-build
=> AP_RTC/AP_AccelCal: remove pointless assignment of total_delay_ms

libraries/AP_GPS/AP_GPS.cpp, libraries/AP_GPS/AP_GPS.h, libraries/AP_GPS/AP_GPS_UBLOX.cpp, libraries/AP_GPS/AP_GPS_UBLOX.h
* Since GPS L5 signal is currently marked unhealthy ublox by default doesn't use it. To allow using L5, we need to allow override the health using the L1 equivalent. This PR refers this document for this https://content.u-blox.com/sites/default/files/documents/GPS-L5-configuration_AppNote_UBX-21038688.pdf 
* Also adds support to enable L5 signal in general.
=> Add option to override L5 signal health and also support to enable it

ArduPlane/Log.cpp, Tools/autotest/logger_metadata/emit_rst.py, Tools/autotest/logger_metadata/enum_parse.py, libraries/AC_Avoidance/LogStructure.h, libraries/AP_AHRS/LogStructure.h, libraries/AP_GPS/LogStructure.h, libraries/AP_GPS/LogStructure_SBP.h, libraries/AP_Landing/LogStructure.h, libraries/AP_Logger/LogStructure.h, libraries/AP_NavEKF2/LogStructure.h, libraries/AP_NavEKF3/LogStructure.h, libraries/AP_Torqeedo/AP_Torqeedo.cpp
Following up from #25861, in which the wiki now shows log message units, myself and others spotted a number of things that don't appear quite as they should. This PR aims to fix at least the low-hanging-fruit.
- emit_rst.py: Remove lone bullet points rendered on replay messages
For replay messages, the field list is not included in the help, but the wiki currently shows a random empty bullet point. This fix does not output the lone '#' for an empty table.
- enum_parse.py: Tweak regex on enum parser to handle comments like: "FRED = 10, ///< text"
GPS Status enum values are formatted with with "///<". This avoids adding including the extra "/<" in the wiki output.
- Link GPS.Status to AP_GPS::GPS_Status enum
- Link LGR.WOW to AP_LandingGear::LG_WOW_State enum
- Separate descriptions for PID …
=> Updates to log message units and help text

libraries/AP_HAL_ChibiOS/AnalogIn.cpp, libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32H757xx.py
* We weren't looking into pin lists for ADC2 and ADC3.
=> AP_HAL_ChibiOS: fix set_pin and _pin_scalar methods for ADC2 and ADC3

libraries/AP_Common/AP_Common.h, libraries/AP_Common/Location.cpp, libraries/AP_Generator/AP_Generator_RichenPower.cpp, libraries/AP_Generator/AP_Generator_RichenPower.h, libraries/AP_Mission/AP_Mission.cpp, libraries/AP_Rally/AP_Rally.cpp, libraries/GCS_MAVLink/GCS.cpp, libraries/SITL/SIM_ADSB_Sagetech_MXS.cpp, libraries/SITL/SIM_EFI_Hirth.cpp, libraries/SITL/SIM_Invensense_v3.cpp, libraries/SITL/SIM_RichenPower.cpp, libraries/SITL/SIM_RichenPower.h
saves having to name the dummy variable yourself
=> Add ASSERT_STORAGE_SIZE macro

libraries/AP_Relay/AP_Relay.cpp, libraries/AP_Relay/AP_Relay.h, libraries/AP_Relay/AP_Relay_Params.h
I missed this one when adding `AP_RELAY_DRONECAN_ENABLED` in https://github.com/ArduPilot/ardupilot/pull/25862.
=> AP_Relay: use correct define for DroneCAN relay

libraries/AP_Baro/AP_Baro_ICP201XX.cpp
**Changes**
- Updated the baro identification code according to the datasheet (see below)
**Why**
In certain situations, the driver failed to ID the barometer correctly. In my case, the register for the ID was returning 0x40 instead of 0x63. It would work however when clicking the reboot button found in the compass section. I suspect in this case, the baro was already prepped and ready for reading. Digging further, I found the blurb in the datasheet that mentions the situation I was running into and how to address, hence the double read of the ID (reading seems to work fine vs writing as indicated in the blub).
=> ICP201XX Baro Driver Fix

ArduCopter/mode_auto.cpp, ArduPlane/commands_logic.cpp, ArduSub/commands_logic.cpp, Rover/mode_auto.cpp, Tools/autotest/arduplane.py, libraries/AP_Mission/AP_Mission.cpp, libraries/AP_Mission/AP_Mission.h
Adds special storage handling to allow for fractional loiter turns. Fractional Loiter Turns 0<N<1 are stored by multiplying the fractional turn number by 256, then dividing that number by 256 on retrieval if a bit flag (type_specific_bit_1) is set, similar to how radii > 255 are currently handled.
Initial Discord Post:
https://discord.com/channels/674039678562861068/797952826847920128/1181661424720822322
Issue Ref:
Closes https://github.com/ArduPilot/ardupilot/issues/18138
Tested In SITL using (QGC and ArduPlane):
Before (Breakout logic applied immediately as turn value was cast implicitly to an integer 0):
After (Breakout logic still hit, but fractional turn sent clearly adhered to):
Notes: (Not sure where is best to note these down, since this is my first time contributing.)
1. I chose …
=> AP_Mission: Fractional Loiter Turn Support

libraries/AP_HAL_ChibiOS/AnalogIn.cpp
* fixes mistake introduced in PR https://github.com/ArduPilot/ardupilot/pull/26049 .
=> AP_HAL_ChibiOS: Use correct pin config for ADC2 and ADC3

libraries/AP_Mission/AP_Mission.cpp
loading missions via FTP ends up using uninitialised stack data when storing missions.
... this is `type_specific_bits`, @IamPete1
=> AP_Mission: fix use of uninitialised stack data

AntennaTracker/GCS_Mavlink.cpp, AntennaTracker/GCS_Mavlink.h, ArduCopter/GCS_Mavlink.cpp, ArduCopter/GCS_Mavlink.h, ArduPlane/GCS_Mavlink.cpp, ArduPlane/GCS_Mavlink.h, ArduSub/GCS_Mavlink.cpp, ArduSub/GCS_Mavlink.h, Blimp/GCS_Mavlink.cpp, Blimp/GCS_Mavlink.h, Rover/GCS_Mavlink.cpp, Rover/GCS_Mavlink.h, Tools/AP_Periph/GCS_MAVLink.h, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_Dummy.h
Use on virtual method rather than a pure-virtual and a named one.
```
Durandal                       -8     *           0       -8                -8     -8     -8
HerePro             -8                                                                    
MatekF405                      8      *           8       0                 0      8      8
Pixhawk1-1M-bdshot             8                  0       8                 0      0      8 …
```
=> Use virtual method for GCS_MAVLink::handle_messag

Tools/autotest/autotest.py
splitting the string isn't pretty - just set two variables.
=> autotest: tidy setting of board type

libraries/AP_Logger/AP_Logger.cpp
fix #26002
This PR corrects the for-loop condition expression in functions unit_name and multiplier_name of AP_Logger.cpp.
As described in the issue these were using the ID to search for (which could be something like: 'e' = 101), and not the actual size of the arrays, so could theoretically overrun the array when searching.
(Although as the loop with break when a match is found, it is pretty unlikely unless bad units/multipliers get used somehow).
SITL compiled and ran OK with the change.
=> AP_Logger: Correct for loop condition

libraries/AP_Filesystem/AP_Filesystem_Mission.cpp, libraries/AP_Filesystem/AP_Filesystem_Mission.h, libraries/GCS_MAVLink/MissionItemProtocol_Fence.cpp, libraries/GCS_MAVLink/MissionItemProtocol_Fence.h, libraries/GCS_MAVLink/MissionItemProtocol_Rally.h
Tested in SITL, using MAVProxy, both rally and ftp ftp up/down.  waypoints still work.
Tested with Valgrind, no problems on fence / rally.  Pre-existing valgrind uninitialised stack allocation bug preserved (see https://github.com/ArduPilot/ardupilot/pull/26063)
=> Allow FTP upload of fence and rally points

Tools/ardupilotwaf/chibios.py, libraries/AP_HAL_ChibiOS/CANFDIface.cpp, libraries/AP_HAL_ChibiOS/CANFDIface.h, libraries/AP_HAL_ChibiOS/hwdef/common/stm32g4_mcuconf.h, libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32G431xx.py, libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32G441xx.py, libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32G474xx.py, libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32G491xx.py, libraries/AP_HAL_ChibiOS/system.cpp
our CANFD timings were resulting in a lot of busoff errors. Here is an example of master at 1Mbit/5MBit:
Getting @SYS/can0_stats.txt as -
------- Clock Config -------
CAN_CLK_FREQ:   80MHz
Std Timings: bitrate=1000000 presc=7
sjw=0 bs1=7 bs2=0 sample_point=90.00000%
FD Timings:  bitrate=5000000 presc=1
sjw=0 bs1=5 bs2=0 sample_point=90.00000%
------- CAN Interface Stats -------
tx_requests:    2689
tx_rejected:    0
tx_overflow:    443
tx_success:     7
tx_timedout:    2232
tx_abort:       0
rx_received:    18470
rx_overflow:    0
rx_errors:      0
num_busoff_err: 34439
num_events:     18477
ECR:            F8
fdf_rx:         18467
fdf_tx_req:     2182
fdf_tx:         0
here is an example with the new timings:
------- Clock Config -------
CAN_CLK_FREQ:   80MHz
Std Timings: bitrate=1000000 …
=> HAL_ChibiOS: fixed CANFD timings

libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_mcuconf.h
this allows for faster log download on ethernet.
On CubeRedPrimary log download using the web server on ethernet goes up from 2.4MByte/s to 4.0MByte/s
I don't think this should go straight into 4.5.x, I'd like to see if anyone notices any reliability issues with the faster clock first
=> HAL_ChibiOS: raise SDMMC clock limit on H7

ArduPlane/quadplane.cpp, ArduPlane/servos.cpp
Finally getting to some of the tidy ups. This moves the outputting of forward throttle in VTOL modes up to QuadPlane output. There is no huge change in ordering, `quadplane.update()` is called a couple of lines above the `set_throttle` where were currently running this code.
https://github.com/ArduPilot/ardupilot/blob/6ce4dfea5747e959746f652fe823c7e7458693bb/ArduPlane/servos.cpp#L871-L883
=> Plane: move forward throttle output in VTOL modes to QuadPlane update

ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, ArduPlane/ReleaseNotes.txt, ArduPlane/version.h, Rover/release-notes.txt, Rover/version.h
These are the Copter, Rover, Plane-4.5.0-beta1 release notes.
All feedback and corrections are more than welcome.
Just looking at the list myself, I can see that some lines are a little too long or could be explained better so don't be shy..
=> Copter/Rover/Plane: 4.5.0-beta1 release

ArduPlane/mode_guided.cpp, ArduPlane/servos.cpp
More throttle output tidyup. This moves guided throttle pass throughout up to guided mode.
I there is no change in behavior,  except that throttle passthrough will no longer work in VTOL modes because its now overridden by VTOL forward throttle output that was moved in https://github.com/ArduPilot/ardupilot/pull/26028.
Tested in SITL with `FENCE_ACTION` 7.0.
Not really related to this PR, but I don't really understand why this would ever be wanted....
=> Plane: move guided throttle passthrough to mode_guided

libraries/AP_Logger/LogStructure.h
this is very tiny tidy up: Link quality (LQ) is pretty universally given in units of 0...100%.
=> AP_Logger: RXLQ in RSSI is in percent

libraries/AP_HAL_ChibiOS/Util.cpp
bootloader already disables GCS, so we can rely on HAL_GCS_ENABLED in place of HAL_BOOTLOADER_BUILD
```
Board               AP_Periph  antennatracker  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
Durandal                       *               *      *           *       *                 *      *      *
HerePro             *                                                                                     
Hitec-Airspeed      *                                                                                     
KakuteH7-bdshot                *               *      *           *       *                 *      *      *
MatekF405                      *               *      *           *       *                 *      *      *
Pixhawk1-1M-bdshot             * …
```
=> AP_HAL_ChibiOS: use HAL_LOGGING_ENABLED in place of HAL_BOOTLOADER_BUILD

libraries/AP_Param/AP_Param.cpp, libraries/AP_Param/AP_Param.h
when we load a VARPTR subtree we need to re-scan the parameter defaults file from @ROMFS/defaults.parm in case there are defaults applicable to this subtree
this affects things like BATT2_I2C_ADDR, which was not loading correctly from defaults.parm on periphs
=> AP_Param: fixed setting of defaults for dynamic param trees

libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_A3_mcuconf.h
need to tell ChibiOS this is a newer H7
this line was in my test fw but was removed during a review cleanup. Turns out it is needed
=> HAL_ChibiOS: fixed support for STM32H7A3

ArduPlane/AP_Arming.cpp
if safety is on and you force arm them turn safety off then Q modes cannot run the motors as the AP_Motors armed state will still be off.
This ensures that the motors are armed immediately we arm. This matches what copter does when arming with safety on
=> Plane: fixed handling of arming with safety on

libraries/AP_HAL_ChibiOS/hwdef/scripts/dma_resolver.py
=> HAL_ChibiOS: fixed I2C4 on STM32G4

README.md
Looks like one of the tests changed names from 'test unit tests' to 'test unit tests and sitl building'.
=> README: Fix broken link to CI unit test

libraries/AP_HAL_Linux/OpticalFlow_Onboard.cpp, libraries/AP_HAL_Linux/system.cpp, libraries/AP_HAL_SITL/system.cpp
avoid floating point rounding errors after long uptimes.
thanks to Richard (RSAXVC) for finding this
=> HAL_Linux: fixed time function to use integer maths

ArduPlane/mode.cpp, ArduPlane/mode.h, ArduPlane/mode_acro.cpp, ArduPlane/mode_autotune.cpp, ArduPlane/mode_fbwa.cpp, ArduPlane/mode_stabilize.cpp, ArduPlane/mode_training.cpp, ArduPlane/servos.cpp
More throttle output tidy-ups. Adds a helper function for pilot throttle output and then uses it in control modes. Tested all changed modes in SITL.
=> Plane: move pilot throttle output up to control modes

AntennaTracker/system.cpp, ArduCopter/system.cpp, ArduPlane/system.cpp, ArduSub/system.cpp, Rover/system.cpp, Tools/ardupilotwaf/ardupilotwaf.py, libraries/AP_Vehicle/AP_Vehicle.cpp
note that these calls are right at the top of init_ardupilot, so moving them into the caller of that function is equivalent.
=> Move can_mgr.init call up to AP_Vehicle

AntennaTracker/GCS_Mavlink.cpp, AntennaTracker/GCS_Mavlink.h, Blimp/GCS_Mavlink.cpp, Blimp/GCS_Mavlink.h, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Dummy.h
in preparation for some cleanups, and hopeful eventual removal of this mechanism.
=> Provide base-class implementation of guided_mode_request function

Tools/autotest/logger_metadata/enum_parse.py, Tools/autotest/logger_metadata/parse.py, libraries/AP_HAL/AnalogIn.h, libraries/AP_Logger/LogStructure.h
```
pbarker@fx:~/rc/ardupilot(pr/power-flags-metadata)$ diff -u LogMessages.rst{-master,}
--- LogMessages.rst-master	2024-02-02 14:04:14.393640400 +1100
+++ LogMessages.rst	2024-02-02 14:40:57.747704313 +1100
@@ -4528,19 +4528,51 @@
System power information
-+----------+----+--------------------------------------------------------------------+
-| TimeUS   | μs | Time since system startup                                          |
-+----------+----+--------------------------------------------------------------------+
-| Vcc      | V  | Flight board voltage                                               |
-+----------+----+--------------------------------------------------------------------+
-| VServo   | V  | Servo rail voltage                                                 | …
```
=> AP_HAL: add power status bits to logger metadata

libraries/AP_BattMonitor/AP_BattMonitor_INA2xx.cpp, libraries/AP_BattMonitor/AP_BattMonitor_INA2xx.h
this will give more temperature monitoring to quite a few boards, good for detecting power supply overload
=> AP_BattMonitor: added temperature reading to INA2xx driver

AntennaTracker/Parameters.cpp, AntennaTracker/Parameters.h, AntennaTracker/Tracker.h, AntennaTracker/system.cpp, ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduCopter/system.cpp, ArduPlane/Parameters.cpp, ArduPlane/Parameters.h, ArduPlane/system.cpp, ArduSub/Parameters.cpp, ArduSub/Parameters.h, ArduSub/system.cpp, Blimp/Parameters.cpp, Blimp/Parameters.h, Blimp/system.cpp, Rover/Parameters.cpp, Rover/Parameters.h, Rover/system.cpp, libraries/AP_Vehicle/AP_Vehicle.cpp, libraries/AP_Vehicle/AP_Vehicle.h
Setup for testing was this for each vehicle:
```
param set SCR_ENABLE 1
param ftp
param set SCR_USER6 17
param set SCR_HEAP_SIZE 222222
```
... then making sure those parameter values were still present on the new firmware.
=> Move AP_Scripting object up to AP_Vehicle

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
Added the ins:calibrating() binding to scripting to be able to tell if the autopilot is calibrating or not so that we don't run other processes
This was tested on a Cube Orange Plus.
=> AP_Scripting: Add calibrating method

.vscode/settings.default.json
This adds the scripting lua version to the vscode default settings.
=> vscode: set lua version to 5.3

libraries/AP_Parachute/AP_Parachute.cpp
A fix to mitigate https://github.com/ArduPilot/ardupilot/issues/26132. this broadens the scope of param conversion to if the enable parameter has ever been changed by the user. Currently it will only convert if enabled when it checks. 
This is still not fool proof, relay chute will still work with 100% default prams, This also means were more likely to override some other function that the user was using because they intended to not use chute.
=> AP_Parachute: do relay conversion if ever enabled

ArduCopter/Copter.cpp, ArduCopter/Copter.h, ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduCopter/config.h, ArduCopter/ekf_check.cpp, ArduCopter/system.cpp
From a discussion with @priseborough
=> Filter ekf variances for failsafe and vibration checks

libraries/AP_Notify/AP_Notify.cpp, libraries/AP_Notify/AP_Notify.h, libraries/AP_Notify/Display.cpp, libraries/AP_Notify/Display.h, libraries/AP_Notify/NotifyDevice.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/hello_world_display.lua, libraries/AP_Scripting/generator/description/bindings.desc
Added the ability to override the default text on the onboard oled display using scripting.
One can use notify:send_text(text, row) to update a given row on the display, this will take priority over the default. You can replace the entire screen or any desired line, for example if i don't care about battery i can use scripting to replace it with other information.
This has been tested on a Cube Orange Plus with a SSH1106.
=> Added send_text via scripting for onboard display

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
Added bindings for ins:get_gyro(instance) and ins:get_accel(instance) so that scripting can get the readings from individual sensors. We need this to be able to validate that the IMUs are reading correctly for testing purposes.
This has been tested using the Cube Orange Plus
=> AP_Scripting: Add getting of gyro/accel values

libraries/AP_Mount/AP_Mount_Siyi.cpp
The Siyi A8 (at least) will report an all-zero camera firmware version for the first 20seconds after startup.  Assuming the gimbal and autopilot are powered up together this may or may not result in a warning sent to the user (see below):
This PR changes the Siyi mount driver so that it does not complete initialisation until a non-zero camera version is provided.
The only downside is Siyi gimbals that always report camera fw version of 0,0,0 will become unusable.  I'm not aware of any Siyi gimbals that do this however.
This has been tested on real hardware.
**Before:**
**After:**
[Related discussion is here.](https://discuss.ardupilot.org/t/siyi-a8-camera-fw-version-reporting-issue/112870)
=> Mount: Siyi waits for non-zero cam firmware version

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_InertialSensor/AP_InertialSensor.cpp, libraries/AP_InertialSensor/AP_InertialSensor.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
Added ins:gyros_consistent(threshold, consistency_seconds) and ins:accels_consistent(threshold, consistency_seconds) for access to LUA for our testing requirements.
With this i also moved ins_accels_consistent and ins_gyros_consistent from AP_Arming to AP_IntertialSensor as i feel that this makes more sense. If this was still in AP_Arming you would need to pass the ins to the function via scripting which i'm not entirely sure how to do.
I also added the threshold and consistency_seconds to be parameters as they were hard coded previously and we need to be sensitive via scripting.
=> Added inertial sensor consistency checking for LUA access

libraries/AP_HAL_ChibiOS/CANFDIface.cpp
the timing table was not correct, thanks to APD for pointing this out.
This is recalculated from
https://www.kvaser.com/support/calculators/can-fd-bit-timing-calculator, with transmitter timing delay compensation added and tested with Salae captures to ensure we are getting the right bit rates
example with 8M CANFD between two CANFD ports on CubeOrange with ESC data sending 0xAAAA
=> HAL_ChibiOS: fixed CANFD timings (again!)

Tools/scripts/board_list.py
This reverts commit 039701b6167d22ef8a4eb039152a70722a365484.
This broken builds on the build server.  We should be correcting the other way anyway, from antennatracker -> tracker
=> Revert "board_list.py: correct autobuild target name"

AntennaTracker/RC_Channel.h, ArduCopter/Attitude.cpp, ArduCopter/Copter.h, ArduCopter/GCS_Copter.cpp, ArduCopter/mode.cpp, ArduCopter/mode_turtle.cpp, ArduCopter/radio.cpp, ArduPlane/GCS_Plane.cpp, Blimp/Blimp.h, Blimp/GCS_Blimp.cpp, Blimp/mode.cpp, Blimp/radio.cpp, Tools/scripts/du32_change.py, libraries/GCS_MAVLink/GCS.cpp, libraries/RC_Channel/RC_Channel.h, libraries/RC_Channel/RC_Channels.cpp
This makes all vehicles set these status bits based off the same information.
Tested on CubeOrange using a DroneCAN-connected R-XSR for all vehicles (but not periph...)
Note that ArduCopter is using the "RC receiver bits" as "pilot control" bits (i.e. if we receive overrides they are counted as "rc receiver").  This is long-standing behaviour.
Plane changes semantics to work like Copter.  Previously if you did not have an RC receiver connected it would appear red ("unhealthy") in the MAVProxy interface.  Now it stays black until Plane sees a receiver.  If that receiver disappears then it will go red ('unhealthy").
Copter is unchanged.
Blimp is unchanged.
Sub does weird things; it uses overrides as a matter of course (see `set_neutral_controls`), basically always providing overrides.  We …
=> Extract reporting of RC status bits into GCS base class

Tools/autotest/arduplane.py
vehicle should be a in a steady state before we make the ratio change to synthesise a pitot blockage.
Otherwise, changes to the shape of the takeoff will affect the heuristics used to detect pitot blockage.
=> autotest: only check for PitotBlockage once vehicle is loitering

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
This should be useful for people wanting to make OEM setups but don't want to re-build (or copy...) the bootloader.
```
env added HAS_EXTERNAL_FLASH_SECTIONS=0
env added CHIBIOS_BUILD_FLAGS=USE_FATFS=yes CHIBIOS_STARTUP_MK=os/common/startup/ARMCMx/compilers/GCC/mk/startup_stm32h7xx.mk CHIBIOS_PLATFORM_MK=os/hal/ports/STM32/STM32H7xx/platform.mk MCU=cortex-m7 ENV_UDEFS=-DCHPRINTF_USE_FLOAT=1
Padded 16 bytes for bootloader.bin to 38816
Embedding file bootloader.bin:/home/pbarker/rc/ardupilot/Tools/bootloaders/CubeOrange_bl.bin
Embedding file defaults.parm:/home/pbarker/rc/ardupilot/build/e0-CubeOrange/processed_defaults.parm
Embedding file hwdef.dat:/home/pbarker/rc/ardupilot/build/e0-CubeOrange/hw.dat
```
Note it getting the bootloader from `CubeOrange`, not `e0-CubeOrange`  That's because …
=> chibios_hwdef.py: allow re-use of bootloader from other boards

Tools/autotest/test_build_options.py
rather more rpresentative of what people are likely to compile for
=> autotest: change default board for test_build_options

.github/workflows/test_sitl_periph.yml, Tools/AP_Periph/can.cpp, Tools/ardupilotwaf/dronecangen.py, wscript
This was prompted by a watchdog from corrupt DroneCAN packets where the initial frames for a multi-frame packet were sent more than once. It exposed a vulnerability in our DroneCAN packet decoder.
Note that the nature of the bug meant that the 16 bit CRC did not protect us against bad packets
This includes the following two PRs:
- https://github.com/dronecan/dronecan_dsdlc/pull/20
- https://github.com/dronecan/libcanard/pull/65
=> DroneCAN: fixed handling of bad multi-frame pkts and check array bounds

ArduPlane/mode_takeoff.cpp, libraries/AC_Fence/AC_Fence.cpp
fixes bug in Mode takeoff where autoenable occurs immediately after initial phase of climb and triggers min alt fence breach....AUTO takeoffs (both fw and VTOL) do not auto-enable until takeoff alt is obtained and mission moves to next item....this does roughly the equivalent
addresses https://github.com/ArduPilot/ardupilot/issues/25783
also fixes the climb portion from TKOFF_LVL_ALT to TKOFF_ALT which used to drop throttle immediately to TECS and release roll/pitch limits instead of smoothly backing off like autotakeoffs in AUTO
=> Mode takeoff fixes for fence autoenable

ArduPlane/mode.h, ArduPlane/mode_loiter.cpp
This reworks the loiter break out code to better handle destination inside loiter circle. It also removes a bug where the set radius parameter was used for the inside/outside determination rather than the altitude corrected radius.
Firstly this changes from using ground course to using the location of the vehicle relative to the center +- 90 deg depending on CW or CCW loiter. This removes error caused by the vehicle tracking its loiter sub-optimally. 
Secondly it removes the inside/outside discontinuity. If the point is inside it aims for the closes point on the radius, advancing that by the angle of a segment with chord length given by the distance the target point is inside the radius. If the target point is exactly on the radius this would be 0 deg advance. If the target point is …
=> Plane: rework `isHeadingLinedUp` function for loiter breakout

ArduPlane/Attitude.cpp, ArduPlane/mode_auto.cpp, ArduPlane/servos.cpp
This moves the last of the throttle outputs up, not to modes because nav scripting pushes in, but up to the same place everything else for nav scripting is output.
=> Plane: output nav scripting throttle with rest of nav scripting stuff

libraries/AP_Scripting/applets/net_webserver.lua, libraries/AP_Scripting/lua_bindings.cpp
this gives a lua exception if you try to do this:
```
sock:recv(1024)
sock:close()
sock:recv(1024)
```
without this we dereference null, causing a crash
initially noticed by @magicrub
=> AP_Scripting: prevent use of closed network socket

Tools/ros2/ardupilot_sitl/src/ardupilot_sitl/launch.py
The ROS2 ardupilot_sitl launch file is currently setting the --out argument to mavproxy as default to localhost:14550. This PR allows to change the default output, in case for example we launch the node on a docker container and we want to connect to a Ground Station running on the host.
How to test:
We can follow the example provided in https://ardupilot.org/dev/docs/ros2-sitl.html and launch the _sitl_ with:
`ros2 launch ardupilot_sitl sitl_dds_udp.launch.py transport:=udp4 refs:=$(ros2 pkg prefix ardupilot_sitl)/share/ardupilot_sitl/config/dds_xrce_profile.xml synthetic_clock:=True wipe:=False model:=quad speedup:=1 slave:=0 instance:=0 defaults:=$(ros2 pkg prefix ardupilot_sitl)/share/ardupilot_sitl/config/default_params/copter.parm,$(ros2 pkg prefix …
=> ROS2 - ardupilot_sitl launch file to include a "out" parameter for Mavproxy

AntennaTracker/Parameters.cpp, ArduCopter/Parameters.cpp, ArduPlane/Parameters.cpp, ArduSub/Parameters.cpp, Blimp/Parameters.cpp, Rover/Parameters.cpp, libraries/AP_Vehicle/AP_Vehicle.h, libraries/AP_Vehicle/Parameters.cpp
Tested in SITL; parameters are preserved going from master to this, and setting FORMAT_VERSION still erases parameters.
I've chosen this shape (vehicles call a method on the base class) as not all vehicles which inherit from AP_Vehicle actually have a k_format_version (e.g. Replay).  These vehicles do their own thing, so we have to consider the format-version-checking an optional feature which AP_Vehicle can provide.
=> Move parameter storage formatting up to AP_Vehicle 

libraries/AP_Vehicle/AP_Vehicle.h
we're making this object, so we should include the header
=> AP_Vehicle: add missing inertialsensor include

libraries/RC_Channel/RC_Channel.cpp
We're calling methods on the mission object in here - not going to work if its not compiled in
=> RC_Channel: correct compilation when AP_MISSION_ENABLED is false

libraries/AP_Scripting/generator/src/main.c
this external line was coming in from a header file somewhere...
there are lines like this in `lua_generated_bindings.cpp`:
```
AP_HAL::AnalogSource *data = hal.analogin->channel(            ANALOG_INPUT_NONE);
```
... so we really should generally know what `hal` looks like.
=> AP_Scripting: include extern-hal line to fix compilation

Tools/ros2/ardupilot_sitl/CMakeLists.txt
Add options for networking and PPP to match waf configure flags.
Build ArduPilot SITL with DDS and PPP enabled using colcon:
```bash
colcon build --symlink-install --cmake-args -DARDUPILOT_ENABLE_PPP=ON --packages-select ardupilot_sitl
```
The options available are:
| option | default | waf |
| --- | --- | --- |
| `ARDUPILOT_DISABLE_NETWORKING` | `OFF` | `--disable-networking` |
| `ARDUPILOT_DISABLE_SCRIPTING` | `OFF` | `--disable-scripting` |
| `ARDUPILOT_DISABLE_WATCHDOG` | `OFF` | `--disable-watchdog` |
| `ARDUPILOT_ENABLE_DDS` | `ON` | `--enable-dds` |
| `ARDUPILOT_ENABLE_NETWORKING_TESTS` | `OFF` | `--enable-networking-tests` |
| `ARDUPILOT_ENABLE_PPP` | `OFF` | `--enable-ppp` |
=> Add cmake options to ardupilot_sitl

libraries/AP_Mission/AP_Mission.cpp, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_config.h
these are static methods which are called when they really shouldn't be.
Currently the mavlink library uses pieces of the AP_Mission library even when it's not compiled in.
Stop doing that.
Currently we don't allow AP_Mission to be compiled out of vehicles, but after this change when it is compiled out we would lose the ability to change altitude and use the magic "waypoint-in-guided-mode" mission items.  There's good alternatives for both of these functions.
=> Remove specially-cased use of static AP_Mission methods

ArduCopter/Parameters.cpp, ArduCopter/ekf_check.cpp
Cleanup to https://github.com/ArduPilot/ardupilot/pull/25621
=> Copter: cleanup EKF failsafe units and division

libraries/AP_Filesystem/AP_Filesystem.cpp, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
https://github.com/ArduPilot/ardupilot/pull/26157 made me realize that we only apply our checksum to the loaded scripts, those scripts could then be using modules that could be incorrectly versioned. This adds a binding for the same crc32 function we use for the scripting check sum, this allows scripts to checksum there modules if they want to. 
However, I was unable to get the correct checksum because we were not initializing the pass by reference values, so the checksum did not start with 0 and the crc32 function does not zero it. This is possibly a issue else where but we have not noticed....
=> AP_Scripting: Add filesystem crc32 binding

libraries/AP_Camera/AP_Camera_Backend.cpp, libraries/AP_Camera/AP_Camera_Backend.h
This fixes a bug introduced by https://github.com/ArduPilot/ardupilot/pull/25883 that meant the CAM1_OPTIONS's RecordWhileArmed option was not working.
This has been tested on real hardware (CubeOrangePlus + Xacti CX-CB100)
FYI @Hwurzburg (not saying it's all your fault of course, I reviewed and merged it and also didn't catch the issue).
=> AP_Camera: fix video recording while armed

libraries/AP_Param/AP_Param.cpp
the cygwin build is not generating binaries failing with:
undefined reference to `AP_Param::load_param_defaults(char const volatile*, int, bool)
there is a 2nd problem that the CI test for cygwin doesn't fail when the build fails. That will be addressed separately
=> AP_Param: fixed cygwin build

libraries/AP_Torqeedo/AP_Torqeedo.cpp
this variable is unused in that case
=> AP_Torqeedo: correct compilation when GCS not available

Tools/scripts/cygwin_build.sh
error if any part of build fails
also ensure cygwin build in CI is parallelised
note: this PR will fail until rebased on #26215
=> Tools: added -e to cygwin build

libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.cpp
This gives a better clue to the CAN bus layout by including the driver index in the `CAND` log. 
I also can't see we won't get node ID conflicts between two drivers since the DNA storage is shared......
=> AP_DroneCAN: DNA_Server: log driver index in CAND

libraries/AP_TemperatureSensor/AP_TemperatureSensor_TSYS03.cpp
=> AP_TemperatureSensor: correct compilation when GCS not available

Tools/environment_install/install-prereqs-openSUSE-Tumbleweed.sh
Tried to make it as complete as compatible as possible with Ubuntu environment
Installing static libs for SITL_static
And gcc_arm-linux for Linux based boards
=> Tools: Add prerequisites install script for openSUSE Tumbleweed

libraries/AP_Scripting/applets/revert_param.lua, libraries/AP_Scripting/applets/revert_param.md
incorrect prefix and missing time constants
=> AP_Scripting: fixed pitch param reversion in revert_param.lua

libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
This method is resetting the euler angle target not the euler rate target. It also only updates the `_attitude_target` quaternion so the euler is not up to date. 
The only users that have `reset_rate` true are in copter acro while in shut down or ground idle:
https://github.com/ArduPilot/ardupilot/blob/1d08662c726a794190e49211f56550ea25c16e9e/ArduCopter/mode_acro.cpp#L34-L46
=> AC_AttitudeControl: fix reset_target_and_rate method

libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp, libraries/AP_RCProtocol/AP_RCProtocol_CRSF.h, libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp, libraries/AP_RCTelemetry/AP_GHST_Telem.cpp
Extracted from https://github.com/ArduPilot/ardupilot/pull/26183/files#diff-b461323452ea70e83fbc1217b71154b88fad81484395ac5dde19ba7ad5c57327R244-R246
=> Correct CRSF spelling (CSRF->CRSF)

libraries/AC_Avoidance/AP_OAPathPlanner.cpp
Extracted from https://github.com/ArduPilot/ardupilot/pull/23716/commits/d6a0fbe718ab7a2e6ec3dc9178a35815904e5ed4 so we can discuss the meat of (and rename) that other PR properly.
@xianglunkai 
```
Pixhawk1-1M-bdshot …
```
=> AP_OAPathPlanner: using static constexpr instead const

ArduPlane/events.cpp
For QuadPlanes utilizing the RTL_AUTOLAND functionality with DO_LAND_START points and the Q_RTL_MODE parameter set to 0, in order to use a mission-based landing approach:
Presently, if a LONG_FAILSAFE event is triggered during an automated VTOL takeoff, the aircraft will transition back to forward flight regardless of its current altitude, and continue to the waypoint subsequent to the DO_LAND_START command. This behavior presents a significant safety risk, especially for larger aircraft.
This change results in the aircraft entering QLAND mode if a LONG_FAILSAFE is triggered during a VTOL takeoff.
=> Plane: QLAND if long failsafe on VTOL takeoff

libraries/GCS_MAVLink/GCS_Common.cpp
SET_MODE message does not exist inside the MAV_CMD enum
as described in the mavlink specification for [COMMAND_ACK](https://mavlink.io/en/messages/common.html#COMMAND_ACK).
The system that is using SET_MODE to communicate with the
vehicle should rely on HEARTBEAT message to detect if
the mode was set correctly.
=> GCS_MAVLink: Remove wrong usage of COMMAND_ACK message

ArduCopter/ReleaseNotes.txt, ArduPlane/ReleaseNotes.txt, Rover/release-notes.txt
Start the release notes for DDS for 4.5. Let me know which branch they should target, and if I should copy them to other vehicles. 
THere is vehicle-specific support in DDS, so I might want to handle that. For example, the waypoint support only works in plane right now.
=> Copter: Add DDS details to release notes for 4.5

libraries/AP_Scripting/generator/src/main.c
Some functions may not initialize correctly. In place of checking them all this does the initialization in the binding.
=> AP_Scripting: ensure that all pass by reference values are initialized

ArduPlane/mode.h, ArduPlane/servos.cpp
More throttle tidy ups, by ensuring `use_throttle_limits`, `use_battery_compensation` and `suppress_throttle` return false in manual mode we can remove the not in manual check on the `set_throttle` function. Moving the `is_armed_and_safety_off` case up means it keeps the manual check and its in the same function as the other `is_armed` case that does a very similar thing. The next step is to combine those two checks.
=> Plane: allow set_throttle in manual and move disarmed override up

libraries/AC_Fence/AC_Fence.cpp, libraries/AC_Fence/AC_Fence_config.h, libraries/AC_Fence/AC_PolyFence_loader.cpp
=> AC_Fence: ensure fencepoint protocol not compiled in if not HAL_GCS_ENABLED

libraries/SITL/SIM_Motor.cpp
Follow up to https://github.com/ArduPilot/ardupilot/pull/26248. The drag effects should be included before calculating torque resulting from thrust vectoring.
=> SITL: SIM_Motor: include momentum drag in derived torque

ArduCopter/mode_follow.cpp
This PR fixes a bug where Copter would not reach its target in FOLLOW mode.
Currently, when the Copter would be in FOLLOW mode, following a **moving** target, it would never actually reach its desired position; instead there would be a steady-state position error.
The reason is that there are slowdown calculations in place in `ArduCopter/mode_follow.cpp`, in order to overwrite the position controller velocity setpoint and slow down the UA as it approaches its target, and prevent an overshoot.
However, these slowdown calculations would be applied over the absolute velocity, not the velocity relative to the target.
Effectively, the absolute velocity would be required to be zero above the moving target, which is inconsistent with a moving target.
This issue likely blocks the implementation …
=> Copter: Excluded target velocity from slowdown calculations in FOLLOW mode

Tools/autotest/vehicle_test_suite.py, libraries/AP_GPS/AP_GPS.cpp, libraries/AP_GPS/AP_GPS.h, libraries/AP_GPS/GPS_Backend.cpp, libraries/SITL/SIM_GPS.cpp, libraries/SITL/SITL.cpp
Master:
after this PR:
And the most common uBlox case where the thing got auto-configured:
=> Add detected message when GPS found

Tools/ardupilotwaf/boards.py
we started to include this everywhere anyway
... initially we set this to be only on by request.  We had to change that to be on by default, so this line is now redundant in SITL.
=> waf: remove richenpower special-case

libraries/AP_OSD/AP_OSD.h, libraries/AP_OSD/AP_OSD_ParamScreen.cpp, libraries/AP_OSD/AP_OSD_ParamSetting.cpp
this will let us more-easily compile without the mavlink headers
```
Durandal                            *      *           0       0                 0      0      *
KakuteH7-bdshot                     *      *           0       0                 0      0      *
MatekF405                           *      *           0       0                 0      0      * …
```
=> AP_OSD: use internal enumeration in place of mavlink enumeration

libraries/AP_RCProtocol/AP_RCProtocol.cpp, libraries/AP_RCProtocol/AP_RCProtocol.h
I've tested this with an R-XSR connected to a MatekL431 connected to a CubeRed.  Still get RC input.
Should make the RC-input-via-mavlink-packet from  @olliw42 simpler.
```
Board,AP_Periph,blimp,bootloader,copter,heli,iofirmware,plane,rover,sub
CubeOrange-periph-heavy,*,,,,,,,,
Durandal,,8,*,8,8,,8,8,8
Hitec-Airspeed,*,,,,,,,,
KakuteH7-bdshot,,*,*,*,*,,*,*,*
MatekF405,,*,*,*,*,,*,*,*
Pixhawk1-1M-bdshot,,24,,24,32,,24,32,24
f103-QiotekPeriph,*,,,,,,,,
f303-Universal,*,,,,,,,,
iomcu,,,,,,*,,,
revo-mini,,*,*,*,*,,*,*,*
skyviper-v2450,,,,*,,,,,
```
=> AP_RCProtocol: factor out a poll_protocol method

.github/workflows/test_unit_tests.yml, Tools/autotest/unittest/extract_param_defaults_unittest.py, Tools/scripts/__init__.py, Tools/scripts/extract_param_defaults.py
Contains unittests with 96% coverage
@peterbarker how should I integrate the unittests with the autotest suite?
=> Tools: Extract parameter default values from an ArduPilot .bin log file

Rover/mode.cpp, Rover/mode_hold.cpp, Rover/mode_manual.cpp, Rover/sailboat.cpp, Rover/sailboat.h
Rover Sailboat: refactor the mainsail/wingmast/mast_rotation logic and make non const sailboat functions private to the sailboat class. Refactor saves around 128 bytes of text image size (in SITL anyway) and easier to read the source code
=> Rover Sailboat: refactor the mainsail/wingmast/mast_rotation logic

Tools/scripts/build_log_message_documentation.sh
After brief discussion on a previous PR (https://github.com/ArduPilot/MAVProxy/pull/1320#issuecomment-1936996052), I got thinking about the idea using the log message meta data for various things within MAVExplorer, and I noticed that the meta-data for "Sub" does not get created and stored in here: https://autotest.ardupilot.org/LogMessages/ alongside the others.
The aim of this PR is to create LogMessages.* files for 'Sub', and include them with the others on the autotest web site.
Tested locally by running 'Tools/scripts/build_log_message_documentation.sh', and got the full set of meta-data in the local 'buildlogs\LogMessages' folder.
=> Autotest: Generate LogMessages.xml for Sub

Tools/ardupilotwaf/boards.py, libraries/AP_Filesystem/AP_Filesystem.cpp, libraries/AP_Filesystem/AP_Filesystem_ROMFS.cpp, libraries/AP_ROMFS/AP_ROMFS.cpp, libraries/GCS_MAVLink/GCS_FTP.cpp
Currently scripting will try and load any scripts in the `@ROMFS/scripts` directory or subdirectorys. This means it will also attempt to load any modules which will fail and cause a pre-arm. This is needed for https://github.com/ArduPilot/ardupilot/pull/26157 to be useful.
Tested in SITL with `ROMFS_custom`.
=> ROMFS: allow list over FTP

.github/workflows/test_unit_tests.yml, Tools/autotest/unittest/annotate_params_unittest.py, Tools/scripts/annotate_params.py
This script fetches on-line ArduPilot documentation (if not cached) and adds it to the specified file or to all *.param and *.parm files in the specified directory.
1. Checks if a local cache of the XML file exists in the target directory or on the directory of the target file:
- If it does, the script loads the file content.
- If it doesn't, the script sends a GET request to the URL to fetch the XML data for the requested vehicle type.
2. Parses the XML data and creates a dictionary of parameter documentation.
3. DELETES all comments that start at the beginning of a line
4. Adds the parameter documentation to the target file or to all *.param,*.parm files in the target directory.
Supports AP_Periph, AntennaTracker, ArduCopter, ArduPlane, ArduSub, Blimp, Heli, Rover and SITL vehicle types …
=> Tools: Annotate parameter files with up-to-date documentation

ArduPlane/mode.h
This fixes a bug I added in https://github.com/ArduPilot/ardupilot/pull/26223 where the two new manual methods were not overriding because the base class was not virtual.
I'm actually a bit surprised that the compiler allowed this..
=> Plane: manual: fix not overriding functions

libraries/AP_GPS/AP_GPS.cpp, libraries/AP_GPS/AP_GPS_DroneCAN.cpp
=> AP_GPS: prevent announcing DroneCAN at 5Hz

libraries/AP_Filesystem/AP_Filesystem.h, libraries/AP_Logger/AP_Logger_File.h, libraries/AP_Mount/AP_Mount_Siyi.h, libraries/AP_Mount/AP_Mount_Xacti.h, libraries/AP_Param/AP_Param.cpp, libraries/AP_RCProtocol/AP_RCProtocol_Backend.cpp, libraries/AP_RCProtocol/AP_RCProtocol_GHST.h, libraries/SITL/SIM_GPS_Trimble.cpp, libraries/SITL/SIM_InertialLabs.cpp, libraries/SITL/SIM_Loweheiser.h, libraries/SITL/SIM_QMC5883L.h
More macOS compile warnings to nuke
=> Nuke macOS warnings

Tools/AP_Periph/AP_Periph.h, Tools/AP_Periph/can.cpp, libraries/AP_DroneCAN/AP_DroneCAN.cpp, libraries/GCS_MAVLink/GCS.h
This allows peripherals to send messages that can appear on the GCS based on the send debug level and the CAN_LOGLEVEL parameter
Useful for critical warnings from peripherals
The main downside is CAN_LOGLEVEL doesn't give the ability to only display messages from particular nodes. In practice I think this will work OK, but it isn't ideal.
=> DroneCAN: map GCS_SEND_TEXT levels in periph to DroneCAN debug levels

libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp, libraries/AP_RCProtocol/AP_RCProtocol_CRSF.h, libraries/AP_RCProtocol/examples/RCProtocolTest/RCProtocolTest.cpp
This fixes an issue with CRSF and ELRS where fast update rates and/or high CPU load can lead to radio failsafes due to scheduling delays preventing full parsing of frames and then the re-synchronization taking too long. The approach is to look for the CRSF frame marker (0xC8) and parse from that point. If parsing fails then the next frame marker is searched for and intermediate bytes are dropped. This means that re-synchronization should take place in a single frame.
=> Decode high duty-cycle CRSF frames using frame marker rather than timeouts

libraries/AP_RCProtocol/AP_RCProtocol.cpp
caused RCP protocol detection to break for everything other than DroneCAN
=> AP_RCProtocol: correct assignment of new_input in rcprotocol detecion

ArduPlane/quadplane.cpp, ArduPlane/quadplane.h
This fixes a bug that was incorrectly applying the forward flight motor failure detection to tilt rotors.
This adds a protection to prevent quadplanes from performing excessive pitch up during braking manoeuvres in VTOL modes that could over stress the airframe.
The following figure is from a simulation test and shows how the upper pitch angle limit lowers as the vehicle speeds up in a forward acceleration followed by a braking manoeuvre in QLOITER.
We will update as testing continues and we determine the appropriate default value for the Q_BCK_PIT_LIM parameter. The limit can be disabled by setting the parameter to a non positive value.
This is something that should be considered for the Beta release.
=> High speed VTOL flight fixes

libraries/AC_PID/examples/AC_PID_test/AC_PID_test.cpp
The comment above the two allocation lines is bogus; those lines can be moved to the bss without issue AFAICS.
=> AC_PID: avoid use of uninitialised stack data in example

libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
This PR is, in a sense, continuation of #25978 as, among other things, it implements a suggestion from that conversation.
What it does is:
- initializes RPM values, to be subsequently logged, with NaN instead of 0, so that an absence of a measurement will be reported as such;
- in `update()`, deduplicates calls to `micros64()` when actually logging ESC data;
- replaces repeated constructions such as `_telem_data[esc_index]` with an appropriate reference;
- cleans up some whitespace and redundant initialization.
=> AP_ESC_Telem: log NaNs on no measurements, various cleanups

libraries/AP_MSP/AP_MSP_Telem_Backend.cpp
... which is all the time on some AP_Periph devices
```
../../libraries/AP_MSP/AP_MSP_Telem_Backend.cpp: In member function 'virtual void AP_MSP_Telem_Backend::update_gps_state(AP_MSP_Telem_Backend::gps_state_t&)': ../../libraries/AP_MSP/AP_MSP_Telem_Backend.cpp:206:5: error: 'AP_GPS' was not declared in this scope; did you mean 'RAW_GPS'?
206 |     AP_GPS& gps = AP::gps();
|     ^~~~~~
|     RAW_GPS
```
We still send the packet but just with the airspeed in it.  I think that does sound  Quite Right.
=> AP_MSP: correct compilation when GPS disabled

libraries/AP_Logger/LogStructure.h
The aim of this PR is to add help text for the VER and FILE log messages (linked to issue #26088).
Implemented by adding the relevant comment tags into AP_Logger.cpp.
(Note that it does _not_ link the VER fields to enumerations, as they are #defines and not pure enums, and so not currently extracted. Ref comments on https://github.com/ArduPilot/ardupilot/pull/26308#issuecomment-1962065366).
=> AP_Logger: Add metadata for VER and FILE messages

libraries/AP_HAL_Linux/Scheduler.cpp
Fix delay(1) rarely returning immediately due to a TOCTOU when the millisecond increment occurred during a call to delay(), just after millis() was first sampled. On my RPi4, delay(1) returned immediately once per 5-20k calls to delay(1) that delay.
This also prevents delay(ms) from returning early due to starting in the middle of a millisecond, and each loop taking slightly longer than a millisecond.
Reduce the last call to microsleep according to the remaining time needed in the last loop iteration.
This is a histogram of delay(100) time taken for both approaches, on an isolated core with only the timer interrupt:
I'd like to do a little more testing with this first, but also wanted to ask for feedback.
=> HAL_Linux: reduce delay(ms) jitter

libraries/AP_TECS/AP_TECS.cpp, libraries/AP_TECS/AP_TECS.h
During descent with low drag planes, TECs will limit the rate of descent so that the specified  mission speed can be maintained. This result in shallow descents.
One of the main reason for wanting this is to be able to better predict (forward planning) how far we should set waypoints when coming in for landing. With low drag airframes,  no matter what max decent in TECS is set to, the aircraft achieves some fraction of that. This means the approach has to be done from unnecessarily far away which becomes a safety risk due to obstacles. If a Loiter to alt method of descent is used it still wastes mission time.
This PR addresses the issue by adding an enum to TECS_OPTIONS that progressively increases set speed to the maximum allowed as the descent rate approaches the TECS internal limit. …
=> Add TECS option to allow low drag planes to descend faster

Tools/ardupilotwaf/ap_library.py, Tools/ardupilotwaf/ardupilotwaf.py, libraries/AP_HAL_ChibiOS/HAL_ChibiOS_Class.cpp, libraries/AP_HAL_ChibiOS/Storage.cpp, libraries/AP_HAL_Linux/Storage.cpp, libraries/AP_HAL_SITL/SITL_cmdline.cpp
... renaming one of them to AP_BUILD_TARGET
``` …
```
=> waf: remove SKETCH and SKETCHNAME from build sysmte

libraries/AP_NavEKF3/AP_NavEKF3_RngBcnFusion.cpp
simply take a refefence and use it
```
Durandal                            -128   *           -128    -128              -128   -128   -128
KakuteH7-bdshot                     -128   *           -128    -128              -128   -128   -128 …
```
=> AP_NavEKF3: tidy population of fusion reports

libraries/AP_Scripting/lua/src/loadlib.c, libraries/AP_Scripting/lua/src/luaconf.h, libraries/AP_Scripting/lua_bindings.cpp, libraries/AP_Scripting/lua_common_defs.h
This allows `require` to find modules in ROMFS. Possibly helps with other file system methods too. Note that this adds the new search path even if we don't have ROMFS compiled in. I think it will be fine, but I have not tested. 
Adding `"./modules/?.lua;" "./modules/?/init.lua"` to get to the same place relative to a script loaded in ROMFS does not seem to work, I'm not sure why. 
This should allow a SD card script to require something from ROMFS, which using relative paths would not. Because of the ordering it should also mean a SD card version of the same file gets priority over a ROMFS copy. Its convenient for development but might give users a very exciting way to break stuff. We could swap the ordering so ROMFS takes priority. Again, I have not tested this.
=> AP_Scripting: add ROMFS to lua path

AntennaTracker/Parameters.cpp, ArduCopter/Parameters.cpp, ArduPlane/Parameters.cpp, ArduSub/Parameters.cpp, Blimp/Parameters.cpp, Rover/Parameters.cpp, libraries/AP_Param/AP_Param.cpp, libraries/AP_Param/AP_Param.h
```
Durandal                            -48    *           -68     -68               -112   -96    -88
KakuteH7-bdshot                     48     *           20      20                -16    -8     -8
MatekF405                           60     *           68      60                60     44     32
Pixhawk1-1M-bdshot                  60                 60      60                60     44     40
f103-QiotekPeriph        *                                                                     
f303-Universal …
```
=> Simplify g2 object conversion

libraries/AP_GPS/GPS_Backend.cpp
I didn't find this debug message particularly informative; add more info.
Old:
```
calculate_moving_base_yaw:372: Exceeded the permitted error margin 29.73999 > 0.052001
calculate_moving_base_yaw:372: Exceeded the permitted error margin 29.73999 > 0.052001
calculate_moving_base_yaw:372: Exceeded the permitted error margin 29.73999 > 0.052001
calculate_moving_base_yaw:372: Exceeded the permitted error margin 29.73999 > 0.052001
```
New:
```
calculate_moving_base_yaw:372: Offset=0.300000 vs reported-distance=0.250000 (max-delta=0.050000)
calculate_moving_base_yaw:372: Offset=0.300000 vs reported-distance=0.250000 (max-delta=0.050000)
calculate_moving_base_yaw:372: Offset=0.300000 vs reported-distance=0.250000 (max-delta=0.050000)
calculate_moving_base_yaw:372: Offset=0.300000 vs …
```
=> AP_GPS: improve reporting of backend inaccurancy

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_CANManager/AP_CAN.h, libraries/AP_CANManager/AP_CANDriver.cpp, libraries/AP_CANManager/AP_CANSensor.cpp, libraries/AP_CANManager/AP_CANSensor.h, libraries/AP_Proximity/AP_Proximity_MR72_CAN.cpp, libraries/AP_Proximity/AP_Proximity_MR72_CAN.h, libraries/AP_RangeFinder/AP_RangeFinder_Backend_CAN.cpp, libraries/AP_RangeFinder/AP_RangeFinder_Backend_CAN.h, libraries/AP_RangeFinder/AP_RangeFinder_Benewake_CAN.cpp, libraries/AP_RangeFinder/AP_RangeFinder_Benewake_CAN.h, libraries/AP_RangeFinder/AP_RangeFinder_NRA24_CAN.cpp, libraries/AP_RangeFinder/AP_RangeFinder_NRA24_CAN.h, libraries/AP_RangeFinder/AP_RangeFinder_TOFSenseP_CAN.cpp, libraries/AP_RangeFinder/AP_RangeFinder_TOFSenseP_CAN.h, libraries/AP_RangeFinder/AP_RangeFinder_USD1_CAN.cpp, libraries/AP_RangeFinder/AP_RangeFinder_USD1_CAN.h
This is helpful because it allows us to have NRA24 (Rangefinder) and MR72 (Proximity sensor) on the same bus. 
This also greatly simplifies the entire CAN interface for the RangeFinder's.
=> AP_CANManager: Add support for multiple libraries to share a CAN Protocol

libraries/AP_Compass/AP_Compass.cpp, libraries/AP_Compass/AP_Compass_Backend.cpp, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Vehicle/AP_Vehicle.h, libraries/GCS_MAVLink/GCS.cpp, libraries/GCS_MAVLink/GCS_Common.cpp
Mostly excluding compass code, but a few other minor fixes
``` …
```
=> Correct use of various defines

Tools/ardupilotwaf/boards.py, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py, libraries/AP_Scripting/lua_scripts.cpp
https://github.com/ArduPilot/ardupilot/pull/26225 means that ROMFS will fail to open directories that don't exist. This results in a failed to open directory warning in ROMFS:
We can tell at compile time if there are any scripts we could try to load,  so we can compile out trying to load from ROMFS.
=> Scripting: only try loading from ROMFS if scripts exist

Tools/ardupilotwaf/chibios.py, Tools/scripts/make_intel_hex.py
if we are producing _with_bl.hex then don't also build *.hex as it can confuse users who think they should flash *.hex with a DFU flashing tool
=> Tools: only produce _with_bl.hex not *.hex for vehicle firmware

libraries/AP_Motors/AP_MotorsTri.cpp
This corrects the tricopter actuator indexing it was off by one, confusingly `AP_MOTORS_MOT_1` = 0. This fix means it lines up with the indexing used by quadplanes to output in forward flight in the `output_motor_mask` method:
https://github.com/ArduPilot/ardupilot/blob/728d9a9f965ca9b644116887f51e964cdf0eef99/libraries/AP_Motors/AP_MotorsMulticopter.cpp#L726
This also corrects to zero the `_actuator` in the `SpoolState::SHUT_DOWN` case so the slewing picks up again in the correct spot.
Nether of these bugs are a issue unless your using a slew limit on the outputs with `MOT_SLEW_UP_TIME` and `MOT_SLEW_DN_TIME`.
=> AP_Motors: Tricopter: fix actuator indexing

libraries/AP_NavEKF3/AP_NavEKF3_RngBcnFusion.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.h
This just moves the code 1:1
First step in privatising these variables.
I've copied the "from" text in this branch into a file, and the "to" next into a file, run perl against the former to remove rngBcn and compared the two.  The difference then is just grabbing the dal object.
```
Durandal                            -16    *           -16     -16               -16    -16    -16
KakuteH7-bdshot                     -24    *           -24     -24               -24    -24    -24
MatekF405 …
```
=> AP_NavEKF3: move initialisation of rngBcn into BeaconFusion method

libraries/AP_HAL_ChibiOS/hwdef/Pixhawk1-1M/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/Pixhawk1-bdshot/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
and add it to Pixhawk1-bdshot
add support for removing ROMFS from hwdef
=> AP_HAL_ChibiOS: remove iomcu dshot from Pixhawk1-1M

libraries/AP_AHRS/AP_AHRS_External.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS.h, libraries/AP_ExternalAHRS/AP_ExternalAHRS_InertialLabs.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS_backend.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS_backend.h, libraries/AP_InertialSensor/AP_InertialSensor.cpp, libraries/RC_Channel/RC_Channel.cpp
This pulls some patches from this PR
https://github.com/ArduPilot/ardupilot/pull/23267
it also allows backends to know when GPS is disabled, for dead-reckoning testing
=> ExternalAHRS: fixed IMU access, check origin and common logging

Tools/autotest/arducopter.py, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
XML is here: https://github.com/mavlink/mavlink/pull/2081
=> GCS_MAVLink: handle MAV_CMD_DO_SET_SAFETY_SWITCH_STATE

libraries/SITL/SIM_FlightAxis.cpp
This PR fixes the "de-mixing" for using Heli H3-120 swashplates in Real Flight.
Without this fix the collective was mixing in pitch to the collective output.  This also reverses the pitch output so that is matches our normal conventions in AP.
=> SITL: Flight Axis: Fix heli demixer

libraries/AP_NavEKF3/AP_NavEKF3_Logging.cpp, libraries/AP_NavEKF3/AP_NavEKF3_RngBcnFusion.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.h
Stop trusting that the number of beacons will not change at runtime.
Also fixes reininitialisation.
=> AP_NavEKF3: dereference arrays using remembered allocation count

libraries/AP_Filesystem/AP_Filesystem.cpp
```
D 45
D 48
D @ROMFS
D @SYS
Total size 0.00 kByte
AP: EKF3 IMU1 tilt alignment complete
```
=> AP_Filesystem: don't show directory entries for empty @ filesystems

Tools/autotest/examples.py, Tools/scripts/build_ci.sh, libraries/AP_HAL_SITL/SITL_cmdline.cpp, libraries/AP_HAL_SITL/Scheduler.cpp, libraries/AP_InertialSensor/AP_InertialSensor.cpp, libraries/AP_JSON/examples/XPlane/XPlane.cpp, libraries/AP_Scheduler/AP_Scheduler.cpp, libraries/AP_Scheduler/examples/Scheduler_test/Scheduler_test.cpp, libraries/SITL/SIM_NoVehicle.h
WIP PR to allow examples to run in CI
=> CI: get more examples working 

ArduCopter/Copter.cpp
An attempt at checking fences quickly to avoid massive breaches
Adds support for auto-enabling fence floors on copter
Current master is fixed at 3Hz so if you are going 30m/s you will be 10m before the fence before it is even checked
Demo: https://youtu.be/8umjR5EAKfg
=> Fast Copter Fences 

Blimp/Loiter.cpp, Blimp/wscript, libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_AttitudeControl/AC_PosControl.h, libraries/AC_AttitudeControl/AC_PosControl_Logging.cpp, libraries/AC_AttitudeControl/LogStructure.h, libraries/APM_Control/AR_PosControl.cpp, libraries/AP_Logger/AP_Logger.h, libraries/AP_Logger/LogFile.cpp, libraries/AP_Logger/LogStructure.h
Moves these closer to where they are used, less scattered across the codebase.  We've done the same for a lot of libraries (e.g. the EKFs) and it has worked well.
=> Move PositionControl logging (PSCN, PSCE, PSCD) into AC_AttitudeControl library

libraries/AP_DDS/AP_DDS_Client.cpp, libraries/AP_DDS/AP_DDS_Client.h, libraries/AP_DDS/AP_DDS_Frames.h, libraries/AP_DDS/AP_DDS_Topic_Table.h, libraries/AP_DDS/Idl/sensor_msgs/msg/Imu.idl, libraries/AP_DDS/dds_xrce_profile.xml
This code enables imu data transmission between ros2 nodes and AP via DDS. @Ryanf55 please review this and suggest changes.
=> adding IMU data in AP_DDS library for high frequency raw imu data transmission

Tools/scripts/build_options.py, Tools/scripts/extract_features.py, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_FTP.cpp, libraries/GCS_MAVLink/GCS_config.h
```
pbarker@fx:~/rc/ardupilot(pr/ftp-out)$ ./Tools/scripts/size_compare_branches.py --board=CubeOrange --extra-hwdef-branch=/tmp/branch.hwdef --vehicle=plane --master=pr/ftp-out
```
yields
```
Board,plane
CubeOrange,-4696
```
=> GCS_MAVLink: allow FTP to be compiled out with build_options.py

ArduPlane/ArduPlane.cpp, libraries/AP_TECS/AP_TECS.cpp, libraries/AP_TECS/AP_TECS.h
the pitch trim variable that was not connected in aparm is needed to allow tuning of the flight speed using PTCH_TRIM_DEG and TRIM_THROTTLE.
This was broken in 4.4.x by this PR:
https://github.com/ArduPilot/ardupilot/pull/22191
Fixes https://github.com/ArduPilot/ardupilot/issues/26340
many thanks to @fredowski for reporting and @Hwurzburg for reproducing
=> TECS: fixed tuning of speed without airspeed sensor

ArduPlane/mode.h, ArduPlane/mode_manual.cpp, Tools/autotest/arduplane.py
This moves the application of throttle limits to the main `apply_throttle_limits` function that all other modes used here:
https://github.com/ArduPilot/ardupilot/blob/e01e697343cf3eb9b0991d7153f135b60b96f965/ArduPlane/servos.cpp#L507
This makes manual mode behave the same as any other mode. This does result in a couple of changes in behavior:
-  `THR_MAX` is also applied along with `THR_MIN`. 
- Battery compensation is done if enabled.
- Watt limiting is done if enabled.
=> Plane: Manual: use `apply_throttle_limits` function in manual mode if `IDLE_GOV_MANUAL` is enabled.

libraries/AP_Motors/AP_MotorsHeli.cpp, libraries/AP_Motors/AP_MotorsHeli.h
We don't need two copies of the same function, this removes `output_armed_zero_throttle`.
`output_armed_zero_throttle`:
https://github.com/ArduPilot/ardupilot/blob/079ffb4a400714689792e54babca6d45938bde1d/libraries/AP_Motors/AP_MotorsHeli.cpp#L241-L249
`output_armed_stabilizing`:
https://github.com/ArduPilot/ardupilot/blob/079ffb4a400714689792e54babca6d45938bde1d/libraries/AP_Motors/AP_MotorsHeli.cpp#L230-L238
=> AP_Motors: Heli: remove `output_armed_zero_throttle` and use identical `output_armed_stabilizing`

ArduCopter/AP_Arming.cpp, ArduCopter/Copter.h, ArduCopter/RC_Channel.cpp, ArduCopter/mode.cpp, ArduCopter/mode.h, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.h, libraries/AP_Motors/AP_MotorsHeli.h, libraries/AP_Motors/AP_MotorsHeli_Dual.cpp, libraries/AP_Motors/AP_MotorsHeli_Quad.cpp, libraries/AP_Motors/AP_MotorsHeli_Single.cpp
This removes the inverted flight state in copter and motors and just keeps it in Attitude control. This then adds a new per mode `allows_inverted` which is false for everything except stabilize. This method allows checking that the current mode allows inverted before enabling it and it allows disabling inverted flight on mode exit if the new mode does not support it.
=> Copter: Heli: rework inverted flight flags and ensure only in a supported mode. 

libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp
Building copter for Pixhawk6C with ``#define HAL_LOGGING_ENABLED 0`` gives error:
``` [ 264/1240] Compiling libraries/AP_Frsky_Telem/AP_Frsky_Telem.cpp
../../libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp: In member function 'void AP_ExternalAHRS::update()':
../../libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp:327:13: error: 'logger' is not a member of 'AP'
327 |         AP::logger().WriteStreaming("EAHR", "TimeUS,Roll,Pitch,Yaw,VN,VE,VD,Lat,Lon,Alt,Flg",
|             ^~~~~~
```
Builds fine with ``HAL_LOGGING_ENABLED 1``.
This is arises due to missing ``#if HAL_LOGGING_ENABLED``  in recent pushed changes (#26329)
=> AP_ExternalAHRS: missing check for HAL_LOGGING_ENABLED in common logging

ArduPlane/quadplane.cpp, libraries/AP_Motors/AP_MotorsMatrix.cpp, libraries/AP_Motors/AP_MotorsMulticopter.cpp, libraries/AP_Motors/AP_MotorsMulticopter.h, libraries/AP_Motors/AP_MotorsTri.cpp
this removes the special case for SHUT_DOWN state of the motors in tilt quadplanes. The old code seemed to assume that the output_motor_mask() doesn't work in SHUT_DOWN state, but in fact it does, so we can get proper spoolup behavious on back transition just by removing the special case
this PR builds on https://github.com/ArduPilot/ardupilot/pull/26248 to give us a quadplane-tilt frame for testing
=> Plane: fixed ramp of motors on back transition in tilt quadplanes

ArduPlane/radio.cpp
This reverts PR https://github.com/ArduPilot/ardupilot/pull/8337
I assume this had a a good reason to go in when it did but all things CAN have changed since then and is only creating confusion. If we still want this, I suggest we move it to Q_OPTIONS
=> Plane: allow quadplanes to scale CAN ESC throttle like normal

libraries/AC_PrecLand/AC_PrecLand.cpp, libraries/AC_PrecLand/AC_PrecLand.h, libraries/AC_PrecLand/AC_PrecLand_Companion.cpp, libraries/AC_PrecLand/AC_PrecLand_Companion.h, libraries/AC_PrecLand/AC_PrecLand_IRLock.cpp, libraries/AC_PrecLand/AC_PrecLand_IRLock.h, libraries/AC_PrecLand/AC_PrecLand_SITL.cpp, libraries/AC_PrecLand/AC_PrecLand_SITL.h, libraries/AC_PrecLand/AC_PrecLand_SITL_Gazebo.cpp, libraries/AC_PrecLand/AC_PrecLand_SITL_Gazebo.h, libraries/AC_PrecLand/AC_PrecLand_StateMachine.cpp
Removes code duplication in SITL
Make SITL behave like other backends
Small (mostly NFC) cleanups on the Precland that make the future sensor lag estimation PR smaller.
=> Precland cleanups

libraries/SITL/SIM_Ship.cpp
this was broken by https://github.com/ArduPilot/ardupilot/pull/23763
we need to look for other places where we have assumed the MAVLink field orderin in recent changes
=> SITL: fixed the vehicle type of the simulated ship

libraries/SITL/SIM_Loweheiser.cpp
=> SITL: name fields in loweheiser mavlink packet

Tools/scripts/extract_features.py
currently custom builds have no logging enabled by default....this should correct that, as well as correcting the feature lists for ALLthe boards which currently show no logging is included .....tested on omnibusf4pro build...logging now in included features list
=> fix logging feature extract

libraries/SITL/SIM_Vicon.cpp
```
2024-03-07 14:02:53.17: VISION_POSITION_ESTIMATE {usec : 5475101845, x : -14.284647941589355, y : -117.79100799560547, z : -19.517837524414062, roll : -0.17139466106891632, pitch : -0.00023988541215658188, yaw : -0.12294592708349228, covariance : [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], reset_counter : 0}
2024-03-07 14:02:53.17: VICON_POSITION_ESTIMATE {usec : 5475101845, x : -14.284647941589355, y : -117.79100799560547, z : -19.517837524414062, roll : -0.17139466106891632, pitch : -0.00023988541215658188, yaw : -0.12294592708349228, covariance : [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]}
2024-03-07 14:02:53.29: VISION_POSITION_ESTIMATE {usec : 5475155157, …
```
=> SIM_Vicon: label fields going into _POSITION_ESTIMATE packets

libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp, libraries/GCS_MAVLink/GCS_Common.cpp
This is a minor follow up to #23903. The feature works great, thanks a lot! I ran into some minor surprises when implementing support for it in our GCS. I initially wrote the code based on the [MAVLink docs for MAV_CMD_EXTERNAL_POSITION_ESTIMATE](https://mavlink.io/en/messages/common.html#MAV_CMD_EXTERNAL_POSITION_ESTIMATE), and found that frame and accuracy weren't handled as I expected.
Accuracy is explicitly advised to be set to NaN if unknown:
> estimated one standard deviation accuracy of the measurement. Set to NaN if not known. [source](https://github.com/mavlink/mavlink/blob/bcdbeb7f07906490fbc945fb5e2db29bad1196d7/message_definitions/v1.0/common.xml#L2489)
But I found that it was stopping the whole autopilot when I tried that in SITL (`Connection reset or closed by peer on TCP …
=> EKF: Match handling of MAV_CMD_EXTERNAL_POSITION_ESTIMATE to common MAVLink dialect

libraries/AP_MSP/AP_MSP_Telem_Backend.cpp
This makes the MSP RC output scaled RC inputs instead of just passing through the received RC input. 
This is especially useful if you have RC reversals, so that ArduPilot's _REVERSED parameters still apply.
Tested with a copter with an HDZero VTX which uses stick commands.
I've also reversed pitch because ArduPilot's pitch is inverted relative to other flight controllers (eg Betaflight) and OpenTX and thus how devices like the HDZero VTX expect it to be.
@yaapu Re our previous discussion - not sure if this would affect other (non-VTX/OSD) MSP devices that wouldn't expect pitch to be reversed? At the moment, if people using MSP devices used ArduPilot's _REVERSED parameter to reverse pitch instead of reversing it on their transmitter, then how I've currently done it should result in no …
=> AP_MSP: Use scaled RC inputs instead of direct RC in

libraries/AP_Torqeedo/AP_Torqeedo.cpp
removes a larger block to avoid warnings about uninitialised values
compilation was failing because `health` and `actual_motor_speed` are unused when both logging and gcs are compiled out
=> AP_Torqeedo: correct compilation with HAL_GCS_ENABLED is false

libraries/GCS_MAVLink/GCS_Common.cpp
deprecating and hopefully removing the _INT frames.
This method is only called by Rover, so thankfully the altitude is not that important...
=> GCS_MAVLink: send set_position_target_global_int with non _INT frame

libraries/SITL/SIM_Morse.cpp
arising from AP_GenericVehicle
=> SITL: SIM_Morse: correct compilation with HAL_GCS_ENABLED false

ArduPlane/radio.cpp
this change can cause a flyaway if you have low SERVO3_MAX for k_throttle. 
This can be reproduced with -f quadplane-can
=> Revert "Plane: allow quadplanes to scale ESC CAN like normal"

libraries/GCS_MAVLink/GCS_Common.cpp
we directly use this library's singleton, so include the header
Fixed CubeOrange-SimOnHardware build
=> GCS_Common: add missing include for AP_RCProtocol

Tools/autotest/vehicle_test_suite.py
this should make the test more reliable. It doesn't make sense to be using speedup=100 for a download with mavproxy
passed 1st time, I'm re-running the sub test a few times to see how reliable it is with this change
- number of consecutive passes: 4
=> autotest: set SIM_SPEEDUP=1 for log download

libraries/AP_Arming/AP_Arming.cpp
Parameter is used as a bitmask but not marked as one, this makes it hard to setup in the GCS as you get a values drop down rather than bitmask check boxes. 
https://github.com/ArduPilot/ardupilot/blob/dc97899ce8a95aa8c328a2e380b0c5e693b3eea0/libraries/AP_Arming/AP_Arming.h#L141-L148
=> AP_Arming: OPTIONS parameter is a bitmask

libraries/AP_GPS/AP_GPS.cpp, libraries/AP_GPS/AP_GPS.h
Also uses get_type in a few spots to avoid external callers doing something nasty.
```
CubeOrange-periph-heavy  -32                                                     
Durandal                            48     *           56      48                56     56     48
KakuteH7-bdshot                     80     *           80      80                80     80     80
MatekF405                           64     *           64      72                64     64     72
Pixhawk1-1M-bdshot                  64                 56      64                56     64     64 …
```
=> Tidy use of backend type in AP_GPS

libraries/AP_Filesystem/AP_Filesystem_config.h, libraries/AP_Scripting/AP_Scripting.cpp
This gates the attempted creation of the directory on `AP_FILESYSTEM_FILE_WRITING_ENABLED`. If that is disabled the creation will always fail. Secondly it only attempts to create the directory if it is not disabled with `SCR_DIR_DISABLE`.
Finally it fixes up a comment in AP_Filesystem.
=> AP_Scripting: Only try to make scripts directory if file write and directory is enabled

ArduPlane/GCS_Mavlink.cpp
the old frames are deprecated
This is the only place I could find in the code where we don't treat them as equal.
=> Plane: accept set_position_target_global_int with non_INT frames

libraries/AP_HAL_SITL/Scheduler.cpp
... you may not be a periphs and *still* not have RC...
... 'though I'm actually not sure what this call is really doing here in the first place.  Needed a comment....
=> AP_HAL_SITL: correct define around use of RC singleton

libraries/GCS_MAVLink/MAVLink_routing.cpp
This should mean that tracker will forward on ADSB packets from the vehicle to the GCS.
=> GCS_MAVLink: Routing: forward ADSB if local ADSB parsing if disabled

ArduPlane/ArduPlane.cpp, ArduPlane/RC_Channel.cpp, ArduPlane/mode.h, ArduPlane/mode_qland.cpp, ArduPlane/mode_qloiter.cpp, libraries/AP_Scripting/applets/plane_precland.lua, libraries/AP_Scripting/applets/plane_precland.md, libraries/SITL/SIM_Aircraft.cpp, libraries/SITL/SIM_Precland.cpp, libraries/SITL/SIM_Precland.h, libraries/SITL/SIM_Ship.cpp, libraries/SITL/SIM_Ship.h
This extends the plane_precland.lua script to support precision loiter, enabled with the same AUX function as for copter (value 39)
=> Plane: support precision QLOITER in quadplanes

libraries/AP_Generator/AP_Generator_IE_2400.cpp, libraries/AP_Generator/AP_Generator_IE_2400.h, libraries/AP_Generator/AP_Generator_IE_FuelCell.cpp, libraries/AP_Generator/AP_Generator_IE_FuelCell.h
This adds variable severity levels to the IE 2400 fuel cell generator driver based on the error code.
=> AP_Generator: IE 2400: MAV_SEVERITY level depends on error code

libraries/AP_BattMonitor/AP_BattMonitor_INA239.cpp, libraries/AP_BattMonitor/AP_BattMonitor_INA239.h
allows for a wider range of current
=> AP_BattMonitor: added MAX_AMPS and SHUNT parameters for INA239

libraries/AC_Fence/AC_Fence.h, libraries/AC_Fence/AC_PolyFence_loader.cpp, libraries/AC_Fence/AC_PolyFence_loader.h, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_BoardConfig/AP_BoardConfig.cpp, libraries/AP_BoardConfig/AP_BoardConfig.h
this uses the same mechanism as BRD_SD_MISSION with a new BRD_SD_FENCE parameter
I have tested briefly in SITL
=> Fence: allow for storage expansion of fence items on microSD

libraries/AP_GPS/AP_GPS.cpp
takes an instance, not a type
recently introduced as part of a type cleanup.
Discovered as part of adding some type safety....
=> AP_GPS: correct update_primary check

Tools/autotest/vehicle_test_suite.py
A fixed time this log is open for ensures we know what we are downloading.
We will not be keeping dataflash logs of the rest of this test after this PR as we leave LOG_DISARMED as it is.
Waiting for GPS ensures the file gets a timestamp, so MAVProxy's "log download latest" will return that log file.
This is an excerpt from a test which failed in CI.  Note that the log being downloaded is *massive*, despite the test's attempts to make a small log (it is not downloading the latest log, but the previous).  This is because that really small log does not have a timestamp associated with it before the simulation gets GPS, and MAVProxy's `log download latest` treats zero as oldest-log.  Key line is "Downloading log 23 as..."
```
2024-03-11T10:41:51.5074012Z Log 11  numLogs 24 lastLog 24 size …
```
=> autotest: ensure latest log is timestamped, small and not growing

Tools/autotest/rover.py
Would be nice to load these fences using the autotest suite - and that should be straight-forward.
But even nicer to have the tests now...
=> autotest: re-enable Dijkstra tests

libraries/GCS_MAVLink/GCS.cpp, libraries/GCS_MAVLink/GCS_Common.cpp
Currently, the ``TIMESYNC`` and ``NAMED_VALUE_FLOAT`` MAVLink messages are sent over High Latency MAVLink ports. They should not be sent.
This PR prevents them from being sent.
Note I'm using the ``send_to_active_channels()`` function in ``libraries/GCS_MAVLink/GCS.cpp`` to filter out the ``NAMED_VALUE_FLOAT`` messages, as ``send_named_float()`` doesn't allow me to select which channels to send/not send.
=> GCS_MAVLink: dont send timesync or on active channels for high latency links

.github/workflows/test_environment.yml, Tools/environment_install/install-prereqs-ubuntu.sh
Added `bookworm` alongside `lunar` and `mantic`.
Tested via Proxmox LXC container(s) running fully updated Debian 12 instances.
=> Tools: add Debian 12 support to prereqs script

Tools/autotest/ardusub.py
we now instantiate AP_Stats so the boot count is available
=> autotest: remove special-case-for-reboot for Sub

libraries/AP_DDS/AP_DDS_Client.cpp, libraries/AP_DDS/AP_DDS_Client.h, libraries/AP_DDS/wscript
Remove unused TFMessage variable and reduce size of pre-allocate arrays in XRCE DDS message types.
Requires upstream change:
- https://github.com/eProsima/Micro-XRCE-DDS-Gen/issues/68
- https://github.com/eProsima/Micro-XRCE-DDS-Gen/pull/74
Which are applied to the ArduPilot forks in:
- https://github.com/ArduPilot/OMG-IDL-Parser/pull/1
- https://github.com/ArduPilot/Micro-XRCE-DDS-Gen/pull/2
Before
```bash
AP: DDS: ********** DDS message sizes **********
AP: DDS: ardupilot_msgs_srv_ArmMotors_Request:   1
AP: DDS: ardupilot_msgs_srv_ArmMotors_Response:  1
AP: DDS: builtin_interfaces_msg_Time:            8
AP: DDS: geographic_msgs_msg_GeoPoseStamped:     320
AP: DDS: geometry_msgs_msg_PoseStamped:          320
AP: DDS: geometry_msgs_msg_TwistStamped:         312
AP: DDS: …
```
=> Reduce memory used by DDS client 

libraries/AP_DDS/AP_DDS_Client.h, libraries/AP_DDS/AP_DDS_Type_Conversions.h
Follow up to https://github.com/ArduPilot/ardupilot/pull/26342
=> AP_DDS: add missing config include in client and type_conversions

libraries/AP_RangeFinder/AP_RangeFinder_SITL.cpp
AP_Rangefinder: fix (very) out-of-range lidar causing float inf which caused a sitl crash. This was triggered when a wrongly configured VTOL was flipping over and the simulated lidar was pointing at the sky
=> AP_Rangefinder: fix (very) out-of-range lidar causing float inf

ArduPlane/radio.cpp
this fixes a bug with TVBS land flare handling. The if() statement was just far too complex and was giving the wrong answer. A ! and ( was swapped
=> Plane: fixed throttle_at_zero()

libraries/SITL/SIM_Ship.cpp, libraries/SITL/SIM_Vicon.cpp
autotest still uses 7.5.0 for x86-64 builds
```.cpp: In member function void SITL::ShipSim::send_report(): BB-WAF: /mnt/volume_nyc3_01/autotest/APM/APM/libraries/SITL/SIM_Ship.cpp:189:42: sorry, unimplemented: non-trivial designated initializers not supported
BB-WAF:          autopilot : MAV_AUTOPILOT_INVALID};
BB-WAF:                                           ^
BB-WAF: compilation terminated due to -Wfatal-errors.
BB-WAF:
BB-WAF: Waf: Leaving directory `/home/autotest/build/tmp/binaries.build/SITL_x86_64_linux_gnu
```
Tested on a bionic64 VM.
=> SITL: correct compilation on g++-7.5.0

libraries/AP_ExternalAHRS/AP_ExternalAHRS.h, libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain7.cpp, libraries/AP_ExternalAHRS/MicroStrain_common.cpp, libraries/AP_ExternalAHRS/MicroStrain_common.h, libraries/SITL/SIM_MicroStrain.cpp, libraries/SITL/SIM_MicroStrain.h, libraries/SITL/SIM_MicroStrain7.cpp
* Populating AHRS orientation from IMU was not correct, this should be populated by the full navigation filter orientation packet. 
* This requires users to turn on the orientation output on the filter (WIKI needed for which channels to enable in SensorConnect anyways)
* I would like this backported to 4.5 as it is a bug to use IMU orientation for EARHS instead of the navigation solution
This needs testing before merge and a comment in the method on what quaternion order the Microstrain packet is in. I assume it's the same as the other packet, but would like to verify on hardware before merge.
`./Tools/autotest/autotest.py build.Plane test.Plane.MicroStrainEAHRS7`
FYI @CraigElder
=> AP_ExternalAHRS: Populate Microstrain7 orientation from filter

libraries/AP_HAL_ESP32/RmtSigReader.cpp
Fix RCInput doesn't work with idf4.4
=> AP_HAL_ESP32: bugfix RmtSigReader for idf - 4.4

libraries/AP_HAL_ChibiOS/hwdef/crazyflie2/hwdef.dat
These two boards are both made for very small quadcopters and it would be difficult to use them for a different vehicle, so probably best to stop autobuilding them for all vehicles.
Also, they're both currently failing to build for Plane.
=> hwdef: Make Crazyflie2 board and JHEMCU-GSF405A board only autobuild for Copter

libraries/AP_InertialSensor/AP_InertialSensor.cpp, libraries/AP_InertialSensor/AP_InertialSensor_Logging.cpp, libraries/AP_Logger/AP_Logger_Backend.cpp, libraries/AP_Logger/LogStructure.h, libraries/AP_Vehicle/AP_Vehicle.cpp, libraries/Filter/Filter.h, libraries/Filter/HarmonicNotchFilter.cpp, libraries/Filter/HarmonicNotchFilter.h, libraries/Filter/NotchFilter.cpp, libraries/Filter/NotchFilter.h, libraries/Filter/tests/plot_harmonictest2.gnu, libraries/Filter/tests/plot_harmonictest3.gnu, libraries/Filter/tests/plot_harmonictest4.gnu, libraries/Filter/tests/test_notchfilter.cpp
This reworks the harmonic notch setup. Major changes include:
- move all clamping decisions down to one place in HarmonicNotchFilter<T>::set_center_frequency
- by default disable notch completely when freq is under 50% of min freq
- added INS_HNTCH_OPTS bit to use min freq when RPM source stops (for heli governors)
- make the double and triple notch clearer, note this changes the spread for harmonics, need to think if that is correct
- removed code that initialised frequencies to the min freq, instead rely on update calls
- allow harmonic notches to run in quadplanes in fwd flight
=> Filtering: re-work harmonic notch filter freq clamping and disable

Tools/scripts/build_parameters.sh
this option was removed because we now mix the SIM parameters in with everything else.
alternative to https://github.com/ArduPilot/ardupilot/pull/26522
=> Tools: build_parameters: stop using --sitl option

libraries/AP_AHRS/AP_AHRS_View.h
... don't need to know the shape of the library here
=> AP_AHRS: avoid use of AP_Motors include in header

libraries/AP_HAL_ChibiOS/hwdef/common/bouncebuffer.c, libraries/AP_HAL_ChibiOS/hwdef/common/malloc.c
This fixes a bug introduced in this PR:
https://github.com/ArduPilot/ardupilot/pull/25900
the bug is that when we don't go via the bouncebuffer on H7 we were also skipping the cache invalidate/flush ops. This caused data corruption for filesystem operations, particularly noticible as lua scripts failing to load with parse errors or log corruption
=> HAL_ChibiOS: fixed a cache corruption issue on H7

libraries/AP_CANManager/AP_CANManager.cpp
these only differ by the constant substring, so pull that out as a variable
```
Board,plane
Pixhawk1-1M,-40
```
=> AP_CANManager: remove redundant calls to snprintf

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Allows IOMCU to be turned off in includes.
Note that Durandal build here is unchanged :-)
``` …
```
=> AP_HAL_ChibiOS: allow IOMCU to be turned off in includes

.github/workflows/test_chibios.yml, Tools/scripts/build_ci.sh, libraries/AP_BLHeli/AP_BLHeli.cpp, libraries/AP_BLHeli/AP_BLHeli.h, libraries/AP_IOMCU/AP_IOMCU.cpp, libraries/AP_OSD/AP_OSD_MSP.cpp, libraries/AP_RCTelemetry/AP_Spektrum_Telem.cpp
this build was failing:
Tools/scripts/sitl-on-hardware/sitl-on-hw.py --board Pixhawk6X --vehicle plane --frame QuadPlane --simclass QuadPlane
=> BLHeli: fixed build without BLHeli with sim on hw

AntennaTracker/wscript, ArduCopter/wscript, ArduPlane/wscript, ArduSub/wscript, Blimp/wscript, Rover/wscript, Tools/ardupilotwaf/ardupilotwaf.py
```
Durandal                            0      *           0       0                 0      0      0
KakuteH7-bdshot                     0      *           0       -8                0      -8     0
MatekF405                           0      *           -8      -8                0      0      0
f103-QiotekPeriph        *                                                       
f303-Universal           * …
```
=> Move AP_OSD from vehicle wscripts into ardupilotwaf.py

AntennaTracker/system.cpp, ArduCopter/system.cpp, ArduPlane/system.cpp, ArduSub/system.cpp, Blimp/system.cpp, Rover/system.cpp, Tools/AP_Periph/AP_Periph.cpp, libraries/AP_AHRS/examples/AHRS_Test/AHRS_Test.cpp, libraries/AP_GPS/AP_GPS.cpp, libraries/AP_GPS/AP_GPS.h, libraries/AP_GPS/examples/GPS_AUTO_test/GPS_AUTO_test.cpp, libraries/AP_Module/examples/ModuleTest/ModuleTest.cpp, libraries/AP_NMEA_Output/examples/NMEA_Output/nmea_output.cpp
it can get this via the singleton
=> Stop passing serial manager to GPS init

libraries/AP_CANManager/AP_CANManager.h
both of these are currently HAL_MAX_CAN_PROTOCOL_DRIVERS in length
=> AP_CANManager: correct array bounds used for sanity check

libraries/AP_Logger/AP_Logger.cpp
logging of dma.txt currently does no good as the first time you read it you get no content. It then enables statistics in the shared_dma code which makes all DMA operations slower, so all we are doing is making DMA slower
=> AP_Logger: avoid logging dma.txt for normal builds

ArduCopter/Copter.h, ArduCopter/heli.cpp, libraries/AP_Motors/AP_MotorsHeli.cpp, libraries/AP_Motors/AP_MotorsHeli.h, libraries/AP_Motors/AP_MotorsHeli_Dual.cpp, libraries/AP_Motors/AP_MotorsHeli_Quad.cpp, libraries/AP_Motors/AP_MotorsHeli_Single.cpp
This moves event logging of "runup complete" and "rotor speed below critical" events down to motors. This means we can remove some extra state from the copter level. 
Tested by running the auto test and checking we still get the events:
=> Copter: Heli: move runup event log down to AP_Motors

ArduPlane/commands_logic.cpp
I find this extra log message when `do_RTL` is called confusing. It makes one think the mode has been re-entered when it really has nothing to do with mode changes.
=> Plane: do_RTL: don't log mode

libraries/AP_Filesystem/AP_Filesystem_ROMFS.cpp, libraries/AP_ROMFS/AP_ROMFS.cpp, libraries/AP_ROMFS/AP_ROMFS.h
This makes ROMFS much more efficient. It is particularly important when serving up javascript and html for the web server as we use if-modified-since to avoid re-sending files to the client. Without this changes we decompress every time.
=> ROMFS: avoid decompressing in stat()

libraries/AP_Mount/AP_Mount_Viewpro.cpp, libraries/AP_Mount/AP_Mount_Viewpro.h
This corrects the vehicle roll and pitch angles sent to the [ViewPro gimbals](https://ardupilot.org/copter/docs/common-viewpro-gimbal.html#common-viewpro-gimbal).  We hope that his will resolve reports that the gimbal is unable to remain level during hard maneuvers.
Not that it matters but this mistake is due to a typo in the ViewPro protocol document.  They have just confirmed that bytes 9-10 hold Roll and 11-12 hold Pitch.
This still needs testing on real hardware.
=> AP_Mount: viewpro fix for swapped ahrs roll pitch

libraries/AP_Proximity/AP_Proximity_RPLidarA2.cpp, libraries/AP_Proximity/AP_Proximity_RPLidarA2.h
This adds support for the [RPLidar C1](https://www.slamtec.ai/product/slamtec-rplidar-c1/) based on [development and discussion here](https://discuss.ardupilot.org/t/rplidar-c1-has-different-results-in-firmware-copter-4-5-and-copter-4-4/114466/4).
The datasheet says the lidar has a "low blind range of 0.05m" so the 0.2m minimum is slightly conservative but consistent with other RPLidar.
=> AP_Proximity: add RPLidarC1 support

Tools/autotest/rover.py, Tools/autotest/vehicle_test_suite.py, libraries/AP_HAL_ChibiOS/hwdef/CubePilot-PPPGW/defaults.parm, libraries/AP_HAL_ChibiOS/hwdef/CubeRedPrimary-PPPGW/defaults.parm, libraries/AP_Networking/AP_Networking.cpp
The new networking capability in 4.5.0 has used NET_ENABLED. With rare exceptions, NET_ENABLE seems to be the standard. This fixes that.
There is no parameter conversion since this code has never been officially released.
=> Use NET_ENABLE instead of NET_ENABLED for consistency with other _ENABLE parameters

libraries/AC_WPNav/AC_WPNav.cpp, libraries/AR_WPNav/AR_WPNav.cpp
This PR resolves issue https://github.com/ArduPilot/ardupilot/issues/26519 in which, given enough time, a waypoint is "completed" even though the vehicle never got close to it.
The fix is to remove the constraint on the minimum size of the "track_scaler_dt".  This variables controls how quickly the target point may advance along the track and is used to be sure that the target never gets too far ahead of the vehicle.
This has been tested in SITL for both Copter and Rover and no ill effects were observed.  The testing included:
1. creating a square mission
2. increasing the SIM_WIND_SPD or SIM_TIDE_SPEED so that the vehicle could make almost no progress
3. ran the above mission with and without these changes to confirm that **without these changes** some waypoints would be completed with …
=> Copter/Rover: allow target position on track to stop advancing

libraries/AC_PrecLand/AC_PrecLand_Backend.h, libraries/AC_PrecLand/AC_PrecLand_Companion.cpp, libraries/AC_PrecLand/AC_PrecLand_Companion.h, libraries/AC_PrecLand/AC_PrecLand_IRLock.cpp, libraries/AC_PrecLand/AC_PrecLand_IRLock.h, libraries/AC_PrecLand/AC_PrecLand_SITL.cpp, libraries/AC_PrecLand/AC_PrecLand_SITL.h, libraries/AC_PrecLand/AC_PrecLand_SITL_Gazebo.cpp, libraries/AC_PrecLand/AC_PrecLand_SITL_Gazebo.h
And initialize member variables
-requires #26238- (that one was already merged)
```
Binary Name      Text [B]         Data [B]     BSS (B)        Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  ---------------  -----------  -------------  ----------------------------  -------------------------
arducopter       -204 (-0.0115%)  0 (0.0000%)  4 (+0.0015%)   -204 (-0.0115%)                                  190116
arduplane        -204 (-0.0115%)  0 (0.0000%)  4 (+0.0015%)   -204 (-0.0115%)                                  190916
antennatracker   0 (0.0000%)      0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      641840
arducopter-heli  -204 (-0.0115%)  0 (0.0000%)  -4 (-0.0015%)  -204 (-0.0114%)                                  183676 …
```
=> AC_PrecLand: move common code to base class

libraries/AP_Mount/AP_Mount.cpp, libraries/AP_Mount/AP_Mount.h, libraries/AP_Mount/AP_Mount_Backend.h, libraries/AP_Mount/AP_Mount_Viewpro.cpp, libraries/AP_Mount/AP_Mount_Viewpro.h, libraries/RC_Channel/RC_Channel.cpp, libraries/RC_Channel/RC_Channel.h
This adds support for enabling/disabling the ViewPro rangefinder using an auxiliary function switch.
This has been lightly tested on real-hardware and appears to work although testing in my office is difficult because the LRF doesn't reliably read distances below about 5m.
I would like to add support for enabling/disabling using a MAVLink message but that requires more thought and coordination and this change gets one of our Partners what they most urgently need.
How to Test:
- Install firmware from this PR
- Set RC8_OPTION = 177 (Mount LRF enable)
- Reboot the autopilot
- Raise and lower the RC8 auxiliary switch and confirm that messages like, "RC8: Mount LRF Enable LOW" (or HIGH) appear
- Connect to the ViewPro camera's video output and check the OSD for the LRF distance.
- Pull the aux …
=> Mount: Viewpro support for enable/disable rangefinder

Tools/scripts/size_compare_branches.py
The current construct wipes the old file before reading and collating the data and writing to the file.  This meant the file was empty a lot of the time...
Formulate the output then write to file....
=> Tools: size_compare_branches.py: write out some.csv less racily

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
many of our hwdef files contain lines which look like this:
define STM32_PWM_USE_ADVANCED TRUE
The current regex does not allow for numbers in those define, so the regex ends up matching "STM" as a name....
the "intdefines" hash which is populated from these is only used internally to chibios_hwdey.py for logic purposes, not directly in hwdef output purposes, and none of the strings which it looks at contain numbers at the moment, so this is a non-functional change.
I have done a `configure_all.py` on master and this and compared the results to ensure there are no changes to any hwdefs.
=> chibios_hwdef.py: correct extraction of intdefines from hwdef files

libraries/AP_HAL/utility/sparse-endian.h
* This caused position quantization errors in the MicroStrain7 converting the double
* This function is currently only used in the MicroStrain7 driver
* This should be backported to 4.5, it was a bug.
=> AP_HAL: Fix incorrect return type for 64 bit float pointer conversion for MicroStrain7

ArduCopter/mode_guided.cpp
This fixes #26404.
I am simply initialising the attitude to the current heading so it does not rotate when it doesn't receive an initial attitude like normal guided attitude mode.
=> Copter: Guided Angle: Initialize yaw to current yaw.

libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_AttitudeControl/AC_PosControl.h
This resolves issue https://github.com/ArduPilot/ardupilot/issues/24717 which involves the vehicle pointing towards an out-of-date yaw target.
This has been tested in SITL
=> Copter: condition yaw fix

Tools/autotest/arducopter.py
I did notice this rather interesting hole if you have an RC failsafe while in RTL mode; we continue to honour the ch6 tuning knob value:
=> autotest: add autotest for channel-6 tuning of wp speed

libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.h
This improves GSF performance for Copter and Rover 4.4 by reducing the minimum speed the vehicle must be travelling at for a GSF reset to occur.
The minimum speed requirement issue (see https://github.com/ArduPilot/ardupilot/issues/24183) was introduced with PR https://github.com/ArduPilot/ardupilot/pull/23515 but the minimum (5m/s) was likely designed with Planes in mind.This PR reduces the limit to 1m/s for all other vehicles (Copter, Helis, Boats, Rover, etc).  While slightly arbitrary I have tested these and I could not make GSF produce an incorrect yaw even if I set the speed limit to zero.
Related discussion [is here](https://discuss.ardupilot.org/t/yaw-not-aligning-to-gsf-anymore-after-updating-from-4-2-3-to-4-4-0-beta1/101844/13)
Alternatively we could add a parameter although i …
=> AP_NavEKF3: define Yaw alignment min GPS speed per vehicle

libraries/AP_Mount/AP_Mount.cpp, libraries/AP_Mount/AP_Mount.h, libraries/AP_Mount/AP_Mount_Backend.cpp, libraries/AP_Mount/AP_Mount_Backend.h, libraries/AP_Mount/AP_Mount_Params.cpp, libraries/AP_Mount/AP_Mount_Params.h
This makes a few enhancements to our AP_Mount library to improve the GCS's ability to set and retrieve the current yaw-lock state.  This is required for the QGC custom gimbal control screen (see https://github.com/mavlink/qgroundcontrol/pull/11264)
To clear up terminology:
- yaw **lock** means the yaw (target or actual) is in earth-frame
- yaw **follow** means the yaw is in body-frame
Detailed changes are:
1. MNT1_OPTIONS parameter added with a single option bit called, "RC lock state from previous mode" allows users to specify that they want the yaw lock state carried over from the previous mode when they switch to RC_TARGETING (e.g. the pilot controls the sticks).  Previously the yaw-lock state was only set-able using an RC auxiliary switch.  If the user is actively controlling the …
=> Mount: improve yaw lock reporting to GCS

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.h, libraries/AP_GPS/AP_GPS.cpp, libraries/AP_GPS/AP_GPS.h, libraries/AP_GPS/AP_GPS_Blended.cpp, libraries/AP_GPS/AP_GPS_config.h
those boards which are not including all backends will lose blended after this
```
Board                    AP_Periph  blimp  bootloader  copter  heli   iofirmware  plane  rover  sub
CubeOrange-periph-heavy  *
Durandal                            *      *           *       *                  *      *      *
Hitec-Airspeed           *
KakuteH7-bdshot                     *      *           *       *                  *      *      *
MatekF405                           -2688  *           -2656   -2680              -2792  -2680  -2688
Pixhawk1-1M-bdshot                  -2624              -2664   -2656              -2624  -2672  -2624
f303-Universal           *
iomcu                                                                 *
revo-mini …
```
=> AP_GPS: remove blended GPS from small boards

Tools/AP_Bootloader/board_types.txt
it would be very unfortunate for someone to allocate out of the same range we are using.
once this is merged I'll PR against PX4-Bootloader
We should probably encourage anyone who wants to be able to reserve areas in that file to add comments.
=> AP_Bootloader: update comment to represent what we actual want to reserve

libraries/AP_HAL_ChibiOS/hwdef/include/skyviper.inc, libraries/AP_HAL_ChibiOS/hwdef/skyviper-journey/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450/hwdef.dat, libraries/AP_Radio/AP_Radio_cc2500.cpp
Start to share excludes from Skyviper-v2450
Also fixes the defines in one of the radio .cpp files which got missed in earlier work
=> Fix Skyviper-Journey build

libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain7.cpp, libraries/AP_ExternalAHRS/MicroStrain_common.cpp, libraries/AP_ExternalAHRS/MicroStrain_common.h
The MicroStrain5 and MicroStrain7 were reporting the EKF status uncertainties using GPS uncertainty. The position uncertainty was too high, so the EKF status was yellow in MavProxy (position uncertainty was greater than 0.5.
I switched to use Vector3f's to represent some of the values as it makes the data structure simpler to work with, such as using the `.xy()` operator for horizontal vector and `.length` for L2 norm.
With this patch, we still sometimes see bad gyro health warnings on hardware, but those can be addressed in another PR.
The original MicroStrain5 driver introduced  this problem and still has it, but I'm no longer maintaining that driver. 
```
>>> status EKF*
>>> MANUAL> 8126: EKF_STATUS_REPORT {flags : 831, velocity_variance : 0.08249999582767487, pos_horiz_variance : …
```
=> AP_ExternalAHRS: Use filter data to populate EKF status report

libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain7.cpp
Only populate GPS data from the GPS. If the filter diverges, then the reported GPS velocity can go haywire, while the GPS may still be stable. This should be considered a bug. 
The original MicroStrain5 driver introduced  this problem and still has it, but I'm no longer maintaining that driver.
=> AP_ExternalAHRS: Only use GPS data when populating GPS fields in MicroStrain7

libraries/AP_DAL/examples/AP_DAL_Standalone/main.cpp, libraries/AP_NavEKF2/AP_NavEKF2.cpp, libraries/AP_NavEKF3/AP_NavEKF3.cpp
Just calling set here makes it look like a user change. Alternately we could just not change the param at all and mask a local copy.
=> EKF: use `set_and_default` when changing IMU mask

libraries/AP_OSD/AP_OSD.cpp
The set here makes it look like a user change. I have also updated the comment to reflect what the code does, forcing to enabled. Alternatively we could just call `set_default` to only change the default but not set the value if the user has configured which is what the comment seems to suggest it should do.
=> AP_OSD: use `set_and_default` when ensuring first screen is enabled

libraries/AP_OSD/AP_OSD_SITL.cpp, libraries/AP_OSD/AP_OSD_SITL.h, libraries/SITL/SITL.cpp, libraries/SITL/SITL.h
this adds SIM_OSD_ROWS and SIM_OSD_COLUMNS
this aims to make it easier to test PRs like this one:
https://github.com/ArduPilot/ardupilot/pull/26605
=> OSD: allow size of simulated OSD to be set

libraries/AP_InertialSensor/AP_InertialSensor.cpp
The current param description indicates that bit 0 will do _both_ accels and tempcals. However, `INS_TCAL_OPTIONS` is a bitmask that is used to persist 0:tempcals and 1:accels (or both).
See: [TCalOptions Definition](https://github.com/ArduPilot/ardupilot/blob/77c7052865517975d04fe4cf747ad2c40cb024c8/libraries/AP_InertialSensor/AP_InertialSensor.h#L777)
I don't have access to add labels to wiki, but there is an associated wiki PR to better describe how to use the persistence here: [ardupilot_wiki PR#5841](https://github.com/ArduPilot/ardupilot_wiki/pull/5841)
=> AP_InertialSensor: Improve bitmask indicating persistent parameters on bootloader flash

Tools/scripts/build_options.py
addresses https://github.com/ArduPilot/CustomBuild/issues/75
I think advanced failsafe should remain under plane since its a plane-only option
=> Tools: move items to different build options sections

libraries/AP_Scripting/applets/VTOL-quicktune.lua, libraries/AP_Scripting/applets/VTOL-quicktune.md
=> AP_Scripting: raise max FLTE for yaw to 8

Tools/autotest/ardusub.py, libraries/AP_AHRS/AP_AHRS.cpp, libraries/GCS_MAVLink/GCS_Common.cpp
Update AHRS state (`origin` and `origin_ok`) when setting EKF origin. Fixes #26619.
Added an autotest for SET_GPS_GLOBAL_ORIGIN mav msg to verify that ORGN records are being written.
=> AP_AHRS: update state when setting EKF origin

libraries/AP_Logger/AP_Logger_Backend.cpp
Same problem as https://github.com/ArduPilot/ardupilot/pull/25362:
```
../../libraries/AP_Logger/AP_Logger_Backend.cpp: In member function ‘bool AP_Logger_Backend::Write_VER()’:
../../libraries/AP_Logger/AP_Logger_Backend.cpp:579:5: sorry, unimplemented: non-trivial designated initializers not supported
};
^
```
This keeps g++ 7.5 working for now, at some point I guess we might want say we don't support it anymore.
=> AP_Logger: `Write_VER` keep g++ 7.5 happy by removeing non-trivial designated initializers

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
the string FULL_CHIBIOS_BOOTLOADER doesn't exist anywhere else in the source code
... and this would be better done as an include, anyway.
=> hwdef: remove handling of FULL_CHIBIOS_BOOTLOADER directive

libraries/AP_Arming/AP_Arming.cpp
Commit d80449ac1323d5b26d356a2d4295bc62f1667158 fixed the comparison direction in the safety delay of 10 seconds to ensure multiple gyros or accelerometers are consistent and stable at that.
However, on flight controllers where there is only one gyro or accel, or only one is used, this delay, which is unconditional, does not make much sense. It certainly feels like a regression at the moment. What is more, pre-arm messages like "Gyros inconsistent" or "Accels inconsistent" only add to confusion in the presence of a single gyro or accel.
This PR turns the 10 second delay to be conditional on having more than one sensor.
I understand that this is a slight encapsulation breach, and one should probably have `bool AP_InertialSensor::gyros_can_be_inconsistent`, which, if `false`, bypasses the …
=> AP_Arming: do not wait 10 seconds with single gyro/accel

libraries/AP_HAL_ESP32/SPIDevice.cpp
I accidentally found a typo in printf statement so this small PR fixes that.
Hi @rmackay9, I had to create this new PR because the previous one got closed automatically after I reset the head. Sorry for the confusion.
=> AP_HAL_ESP32: Bugfix added missing printf statement

libraries/AP_HAL/UARTDriver.cpp, libraries/AP_HAL/UARTDriver.h, libraries/AP_HAL_ChibiOS/UARTDriver.cpp, libraries/AP_HAL_ChibiOS/UARTDriver.h, libraries/AP_HAL_ChibiOS/Util.cpp, libraries/AP_HAL_ChibiOS/Util.h, libraries/AP_HAL_Empty/UARTDriver.cpp, libraries/AP_HAL_Empty/UARTDriver.h, libraries/AP_HAL_SITL/UARTDriver.cpp, libraries/AP_HAL_SITL/UARTDriver.h, libraries/AP_HAL_SITL/Util.cpp, libraries/AP_HAL_SITL/Util.h
Extract from https://github.com/ArduPilot/ardupilot/pull/26532. This adds a byte tracking helper `StatsTracker` which allows the UART driver to keep a cumulative count rather than zeroing. ChibiOS is moved to use that and SITL gets by tracking and fills in  `@SYS/uarts.txt`.
SITL:
```
UARTV1
SERIAL0 TX=   60956 RX=     354 TXBD= 36742 RXBD=   213 connected     (tcp:0:wait)
SERIAL1 TX=       0 RX=       0 TXBD=     0 RXBD=     0 not connected (tcp:2)
SERIAL2 TX=   19259 RX=     812 TXBD= 11608 RXBD=   489 connected     (tcp:3)
SERIAL3 TX=    1089 RX=   35358 TXBD=   656 RXBD= 21312 connected     (GPS1)
SERIAL4 TX=       0 RX=       0 TXBD=     0 RXBD=     0 connected     (GPS2)
SERIAL5 TX=       0 RX=       0 TXBD=     0 RXBD=     0 not connected (tcp:5)
SERIAL6 TX=       0 RX=       0 …
```
=> SITL: add UART tx/rx tracking and `@SYS/uarts.txt`

libraries/AP_Logger/AP_Logger_MAVLink.cpp
The removed code changed behavior of the send_log_block function when simulating with SITL. While I can understand the intention I do not think that it is the right way to do it and has the potential to confuse people debugging stuff with SITL and comparing to the real world.
=> AP_Logger_MAVLink: Remove code that changes behavior when in SITL

libraries/AP_InertialSensor/AP_InertialSensor_tempcal.cpp
Saving Persistent Accel cals for Aux IMUs resulted in a duplicate instance and that parameter does not exist.
Without this change, you get:
* IMU_ACCOFFS_*
* IMU_ACC2OFFS_*
* IMU_ACC3OFFS_*
* **IMU3_ACCOFFS_**
After this change, you get:
* IMU_ACCOFFS_*
* IMU_ACC2OFFS_*
* IMU_ACC3OFFS_*
* **IMU4_ACCOFFS_**
=> AP_InertialSensor: Fix parameter name when saving persistent accel cals for Aux IMUs

libraries/AP_Stats/AP_Stats.cpp
This PR fixes an issue where flight time was not being updated if the power was shut down immediately after flight.
Since the update occurs in 30-second cycles, turning off the power before the update process means the last flight time is not added.
I have modified update function so that the flight time updates upon disarming, in addition to the regular updates every 30 seconds.
I have confirmed that the flight time is updated immediately after disarming in SITL.
=> AP_Stats: update flight time on disarm

libraries/AP_HAL_Linux/HAL_Linux_Class.cpp, libraries/AP_HAL_Linux/HAL_Linux_Class.h
This addresses 2 problems for Linux builds:
1. If the code hangs during initializations in `HAL_Linux::run` (e.g. missing a critical sensor) the whole process would lock up and not respond to `SIGINT` / `SIGTERM`, which makes it inconvenient to work with. The solution is suboptimal because in such a shutdown scenario the teardown would be skipped, however otherwise `callbacks->setup()` in particular needs to be made interruptible instead.
2.  Signal handler runs in a separate context, so the compiler may choose to optimize the loop condition out. Marking it as volatile explicitly prevents this.
=> Allow proper shutdown in Linux

Tools/ardupilotwaf/boards.py, wscript
Not all (actually none?) Linux boards have `linux` in their names, but the task detection logic only checks that, resulting in Linux boards being misclassified. In practical terms this means they also pull the unnecessary bootloader in, but overall this makes the clause misleading.
This PR adds functionality to detect the base class of the board by probing inheritance and thus fixes this.
=> Detect board class by inheritance instead of naming

Tools/AP_Bootloader/board_types.txt
Add several new board_types for holybro.
=> Add board_types for holybro

libraries/AP_Relay/AP_Relay.cpp, libraries/AP_Relay/AP_Relay_Params.cpp, libraries/AP_Relay/AP_Relay_Params.h
added a option for every relay to invert the output signal.
If enabled, Relay on would be Pin output off and Relay off would be Pin output on.
=> Relay: add relay output invert function

libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp, libraries/AP_RCProtocol/AP_RCProtocol_CRSF.h, libraries/AP_RCProtocol/AP_RCProtocol_GHST.cpp, libraries/AP_RCProtocol/examples/RCProtocolTest/RCProtocolTest.cpp
this fixes a crash bug that caused a watchdog for Henry on a F765-Wing. The bug happens with corrupt serial data causing an underflow in the length argument to the crc call
this also adds a random data test that triggers the bug, which demonstrates the fix
=> AP_RCProtocol: fixed crc memory range error in CRSF

libraries/AP_HAL_ChibiOS/hwdef/JHEM_JHEF405/hwdef.dat
the older version of the JHEMCU GF16 board used a mpu6000 instead of a icm42688. I added the lines for the firmware to be compatible.
=> hwdef: adding IMU lines for older version of board

ArduSub/ArduSub.cpp, ArduSub/GCS_Mavlink.cpp, ArduSub/GCS_Mavlink.h, ArduSub/Sub.h
This change removes the need to have a home position when calculating GLOBAL_POSITION_INT.alt, GLOBAL_POSITION_INT.relative_alt and VFR_HUD.alt.
Fixes #26647
Fixes #26648
=> Sub: do not require home position to publish filtered altitude in MAVLink messages

libraries/AP_Scripting/applets/VTOL-quicktune.lua, libraries/AP_Scripting/applets/VTOL-quicktune.md
although the change merged yesterday was an improvement, it does not allow Leonards recommended yaw flte to be used (0) for vectored yaw quadplanes...this allows that and recommends it in the script setup instructions...matching wiki recommendations already updated.
currently, the default of 2.5 would be unchanged by the script which can result in yaw wobble in the outer angle loop
if the user changes to 0, it would reset to 8hz by the script which may or may not wobble...this allows it to be set to 0 and remain at that value when the script is run
=> AP_SCripting: update VTOL QuickTune to allow YAW FLTE = 0

libraries/AP_HAL_ChibiOS/hwdef/Sierra-F412/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/Sierra-F9P/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/kha_eth/hwdef.dat
this is set in the periph defaults file
=> hwdef: remove redundant defines from hwdefs

AntennaTracker/GCS_Mavlink.cpp, AntennaTracker/GCS_Mavlink.h, AntennaTracker/Tracker.cpp, AntennaTracker/Tracker.h, AntennaTracker/sensors.cpp, AntennaTracker/system.cpp, ArduCopter/Copter.h, ArduCopter/GCS_Mavlink.cpp, ArduCopter/GCS_Mavlink.h, ArduPlane/GCS_Mavlink.cpp, ArduPlane/GCS_Mavlink.h, ArduPlane/Plane.h, ArduSub/GCS_Mavlink.cpp, ArduSub/GCS_Mavlink.h, ArduSub/Sub.h, Blimp/Blimp.h, Blimp/GCS_Mavlink.cpp, Blimp/GCS_Mavlink.h, Rover/GCS_Mavlink.cpp, Rover/GCS_Mavlink.h, Rover/Rover.h, libraries/AP_Vehicle/AP_Vehicle.h, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_Dummy.h
This takes advantage of all our vehicles inheriting from AP_Vehicle, which they didn't when the pure-virtual methods on GCS_MAVLink were first created.
I'm not sure this is the correct shape for handling home generally, but given all but one of our vehicles had the relevant methods already on the vehicle class it seems a reasonable improvement.
There's the basic question of whether home is an AHRS thing or an AP_Vehicle thing.  While AHRS has been a good place for home, notionally you don't need AHRS to have a home (Tracker kinda-sorta shows that....)
A first step in further unifying home-position behaviour across vehicle types, anyway.
=> Make GCS_MAVLink base class handle DO_SET_HOME

libraries/AP_HAL/LogStructure.h, libraries/AP_HAL/UARTDriver.cpp, libraries/AP_HAL/UARTDriver.h, libraries/AP_HAL/Util.h, libraries/AP_HAL_ChibiOS/UARTDriver.h, libraries/AP_HAL_ChibiOS/Util.cpp, libraries/AP_HAL_ChibiOS/Util.h, libraries/AP_HAL_SITL/UARTDriver.h, libraries/AP_HAL_SITL/Util.cpp, libraries/AP_HAL_SITL/Util.h, libraries/AP_Logger/LogStructure.h, libraries/AP_Logger/README.md, libraries/AP_Vehicle/AP_Vehicle.cpp
This is a generalized version of https://github.com/ArduPilot/ardupilot/pull/26532 for all serial ports rather than only MAVLink. It does not have all the extra logging fields that https://github.com/ArduPilot/ardupilot/pull/17360 does, but they could be added in the future.
From SITL:
CubeOrangePlus:
Which matches more or less mission planners stats:
Note that we do get log for every port except 4. 
0 I was connected to on USB.
1 and 2 are set to MAVlink, there is no rx, but we see tx data going out (both ports are the same).
3 is set to GPS, so it was trying to do something.
4 is the second GPS which is disabled, so not in the log.
5 is the internal ADSB over MAVLink:
6 is the second USB end point which is set to SLCAN. Interestingly this is in the log, so there must have been some data …
=> ChibiOS, SITL: add 1Hz logging of UART data rates

libraries/AP_GPS/AP_GPS.h, libraries/AP_GPS/GPS_detect_state.h
Save some memory when backends are compiled out
=> AP_GPS: protect detection structures with GPS backend defines

.github/workflows/test_ccache.yml, Tools/scripts/build_tests/test_ccache.py
Currently, the ccache test uses two pairs of boards: `Matek-F405` vs `Matek-F405-bdshot`, and `Pixhawk6X` vs `Durandal`.
With more code coming that depends on bidirectional DShot, these boards will increasingly diverge, causing the test to fail. My work-in-progress PR #26321 is one of such changes. In light of this, the choice of boards different by being or not being bdshot-enabled seems imperfect.
This PR updates the configuration of the ccache test, so that both pairs of boards have bdshot code enabled. I tried to change as little as possible, so the first pair becomes `Matek-F405-bdshot` vs `Matek-F405-TE-bdshot`, and the second pair becomes `Pixhawk6X` vs `Durandal-bdshot`. Note that `Pixhawk6X`, just like `Pixhawk6X-bdshot`, is bdshot-enabled in terms of code compilation, because it …
=> Tools, CI: use same-bdshotness boards for ccache test

libraries/AP_HAL_ChibiOS/hwdef/CSKY405/hwdef.dat
These are all gotten from somewhere else.
No idea why this includes parachute...
=> Remove un-needed lines from CSKYF405 hwdef

Tools/AP_Periph/GCS_MAVLink.h
I missed this GCS_MAVLINK subclass in my recent restructure.
This overrides are no longer required.
=> AP_Periph: correct compilation when HAL_GCS_ENABLED

ArduCopter/AP_Arming.cpp, ArduCopter/Copter.h, ArduCopter/commands.cpp, ArduSub/Sub.h, ArduSub/commands.cpp, ArduSub/commands_logic.cpp, Blimp/Blimp.h, Blimp/commands.cpp
Based on @rmackay9 's comment, and my preference here: https://github.com/ArduPilot/ardupilot/pull/26724
=> Remove "far_from_EKF_origin" sanity checks

libraries/AP_GPS/AP_GPS.cpp
allows to not break older firmware in terms of available metadata
=> AP_GPS: copy GPS metadata in for pre-per-instance-parameters

ArduPlane/mode_rtl.cpp, Tools/autotest/quadplane.py
we are calling "reached_loiter_target" as part of our checks as to whether to fly home or not.
We need to call update_loiter so the L1 controller can update its internal state for the new waypoint which do_RTL has set.  Depending on location (but typically), that will mean that L1's reached_loiter_target() will then return false, so we fly home.
This bug was affected by f8d7be5e43686e5a20a1a59420c308ac1fab4c70 .  Any sort of altitude error greater than 10m would delay us entering the landing sequence, allowing the L1 controller to update its state.
autotest added for same
=> Plane: correct RTL_AUTOLAND=1 behaviour

ArduCopter/Parameters.cpp, ArduSub/Parameters.cpp, Blimp/Parameters.cpp
Match behavior of all vehicles. Allows GCSes to use documented behavior of a zero write to FORMAT_VERSION to reset EEPROM contents.
Verified that this does not change the built firmware contents. Presumably GCSes will need to update their parameter metadata.
=> Vehicles: Unmark FORMAT_VERSION as read-only

libraries/AP_HAL_ChibiOS/hwdef/mRoControlZeroClassic/hwdef.dat
Missing definition for servo rail ADC input added for the mRo Control Zero Classic.
=> mRo Control Zero Classic: Added ADC input for servo rail

libraries/AP_VisualOdom/AP_VisualOdom_Backend.cpp
when both logging and gcs are compiled out
=> AP_VisualOdom: correct unused variable in visualodom

Tools/scripts/create_OEM_board.py
basic script that allows you to make a copy of a board for a OEM setup. It takes the name of the board you want to copy and the name of your OEM board in parameters and creates the folder with the files that include the original board in it.
=> Tools : add a script to make an OEM setup

ArduCopter/land_detector.cpp, Tools/autotest/arducopter.py
This was calling several methods on the mode to work out what that mode wants to do when the landing detector fires.
The logic should be the same here, just unrolled to be legible.
I've added a test for the parameter used to change the vehicle behaviour.
=> Tidy land-detected handling

libraries/AP_NavEKF/EKF_Buffer.cpp, libraries/AP_NavEKF/tests/test_ring_buffer.cpp
This is an alternate solution to a bug @luweiagi found in the EKF buffer code.
His PR is here: https://github.com/ArduPilot/ardupilot/issues/25316
My formulation here switches the determination of whether the buffer has ever been full to looking for us wrapping the new offset, rather than looking at the old offset.
I think all of these approaches are bogus; if we advance the oldest pointer then we may never actually be "full".  I think the current behaviour only works because the EKF doesn't consume until the buffers have been full at least once.
The supplied tests fail before this PR, pass after (the buffer says it is full on the third element, not the fourth, as @luweiagi pointed out in the issue).
Closes #25316
=> Correct off-by-one problem in EKF IMU ringbuffer

Tools/AP_Bootloader/board_types.txt
Added board ID reservations between 6600 and 6699 for EagleEye Drones.
=> Added board IDs for Eagle Eye Drones

ArduCopter/crash_check.cpp, ArduPlane/events.cpp, libraries/AP_Parachute/AP_Parachute.cpp, libraries/AP_Parachute/AP_Parachute.h
Based on discussion of PR #25570 and #25562.
Disarm before parachute release to avoid parachute tangling if parameter CHUTE_OPTIONS:1 = 0.
=> AP_Parachute:  Optional (CHUTE_OPTIONS:1) disarm before parachute release

ArduPlane/quadplane.cpp
Rolf makes a good argument for why some quadplanes need less than 2s
https://discuss.ardupilot.org/t/plane-4-5-0-beta-release/112518/37
=> Plane: drop min Q_TRANSITION_MS to 500ms

Tools/autotest/fakepos.py, Tools/autotest/pysim/fg_display.py, Tools/autotest/pysim/util.py
A replacement for (the merged) https://github.com/ArduPilot/ardupilot/pull/26471
thee ArduPilot SITL binary *must* honour the `--speedup` parameter above the initial value of the `SIM_SPEEDUP` parameter, so any time we `reboot_sitl()` the speedup goes back to the command-line option value.  tridge worked around that in his PR by setting the speedup after reboot in several tests where it really matters that we get the right speedup.
This PR, instead, stops the autotest suite from setting the `--speedup` command-line option, instead relying on setting the `SIM_SPEEDUP` parameter to accomplish speedup.
I have not reverted the changes made in that other PR, but it should be reasonable to do so after this.
=> autotest: use speedup parameter default for speedup, not command-line option

ArduCopter/RC_Channel.cpp, libraries/RC_Channel/RC_Channel.cpp, libraries/RC_Channel/RC_Channel.h
Tested in SITL with both guided/auto on Copter.
=> Add RC option for flightmode pause/resume

ArduCopter/autoyaw.cpp, ArduCopter/mode.h
there are other methods on the autoyaw object which make it clear that they're working in cd, and others in there that work in degrees.  This method doesn't specify cd yet returns in that unit.
Change the method and state variable to store in degrees (as our naming standards suggest)
Tested in SITL by using "Set ROI" to swing the vehicle to a yaw, then using `WP_YAW_BEHAVIOR` set to 3 to swing back to "look ahead"
=> Copter: autoyaw: correct units returned by look_ahead_yaw

libraries/RC_Channel/RC_Channel.cpp
Unimplemented RC option can be selected.
Notify the operator with a message that an unimplemented RC option has been selected.
AFTER
BEFORE
=> RC_Channel: Notify function error if ADS-B is not implemented

libraries/AP_Mount/AP_Mount_Siyi.cpp, libraries/AP_Mount/AP_Mount_Viewpro.cpp
If there is no instance, I think it is unnecessary to execute the following process.
=> AP_Mount: Do not perform unnecessary processing

libraries/AP_GPS/AP_GPS_SBF.cpp
When the NrSV field of the SBF PVTGeodetic message contains the Do-Not-Use value of 255, set the satellite count to 0 instead of ignoring the change.
=> AP_GPS: SBF report correct satellite count on NrSV DNU value

ArduCopter/RC_Channel.cpp
this means a user will get a warning if they try to run a function and it isn't supported
Aux Function 43 is `AUX_FUNC::INVERTED`, which is only supported on heli.  Below I was trying to use it on Multi:
master:
```
STABILIZE> long DO_AUX_FUNCTION 43 1
STABILIZE> Got COMMAND_ACK: DO_AUX_FUNCTION: ACCEPTED
```
after this PR:
```
STABILIZE> long DO_AUX_FUNCTION  43 1
STABILIZE> AP: Invalid channel option (43)
Got COMMAND_ACK: DO_AUX_FUNCTION: FAILED
```
This pattern is also good because we can coalesce cases which are dependent on the same #if - which I've done for several in here.
```
4723192inputs+165133200outputs (12115major+209830723minor)pagefaults 0swaps
+ column -ts, /tmp/some.csv …
```
=> Copter: move #ifs to outside case statements in do_aux_function

Tools/AP_Bootloader/board_types.txt
Will be released for purchase in mainland china, may be available globally but not sure.
=> Reserving board id for sakurarc h743

libraries/RC_Channel/RC_Channel.cpp
We need to make sure the behaviour changes between master and this PR - so bad on master, good after this patch.
@timtuxworth if you're up for testing I'll create a similar PR for the functions you suggested also needed to be in this list.  Henry volunteered to test the ones in this PR.
@Hwurzburg I'm a bit concerned about that 3-pos switch change.  Past this change we will not enable auto-release if your switch is in the middle position at first-rc-received time.  If you're working off muscle memory to ensure your switches are in expected positions, it could currently actually be a middle-position-by-default sort of thing... and this would mean people flying without their safety system engaged.... IOW I'm not convinced we can use this exact option for the parachute 3-pos.
=> Add more AUX_FUNC options to RC_Channel transition-required list

ArduSub/AP_Arming_Sub.cpp
this is already guaranteed to be the case
Expand the diff upwards you can see the `if` is already checking the return from this function call
=> Sub: remove redundant home_is_set check

libraries/AP_Mount/AP_Mount_Backend.cpp, libraries/AP_Mount/AP_Mount_Backend.h
When the AP boots it sets the gimbal mount mode from MNTx_DEFLT_MODE, but if there are also RC channels for roll, pitch, yaw on the mount, when the RC connects it will immediately override the default because the RC values "changed" (from nothing to whatever is coming from RC). I noticed this with SysID tracking mode, but it would also have affected other modes using _DEFLT_MODE.
This fix ignores the initial RC values until it has received valid values one time, so it will only override the gimbal targeting mode if the pilot actually changes the relevant RC channels. "relevant" is any one of the channels set for pan/tilt/roll for the specific camera mount (MNTx).
=> AP_Mount: Do not override default mode when first connecting to RC

Tools/autotest/arducopter.py, Tools/autotest/vehicle_test_suite.py
There were some oddities when home was significantly different to origin
=> Add test for moving from guided to loiter

ArduCopter/GCS_Mavlink.cpp, ArduCopter/GCS_Mavlink.h
Nice in that you can set breakpoints on the method you're testing
Nice in that there's not a single method several hundred lines long...
I've tested this in SITL while playing around with MAVProxy guided commands.
We also test this stuff a lot in autotest.
=> Copter: factor out methods for guided-mode commands

Tools/autotest/arducopter.py
Raises an internal error when you run it.
=> autotest: add test for GuidedModeThrust

libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_FTP.cpp, libraries/GCS_MAVLink/GCS_Param.cpp
This gives slow radio links a fighting chance of getting FTP bulk download working efficiently, even when they use a baud rate which is much higher than their current bandwidth.  The strategy is similar to what Ardupilot already does for PARAM_VALUE messages.
This should eliminate the need to disable FTP for parameter download on slow to moderate speed radio links like mLRS.  It allows removal of a hack in mLRS which results in a decrease in parameter download time for 19 Hz mLRS from 45-60 seconds to 11-17 seconds. Other mLRS message rates show similar improvement.  This should also be good news for the ELRS rc-mavlink branch.
Also, improve get_last_txbuf() to allow message flow in the unlikely event that we stop receiving radio_status messages.
This has also been tested with TBS …
=> GCS_MAVLink: respect txbuf flow control for FTP messages

Tools/scripts/build_options.py, Tools/scripts/extract_features.py
See this report:
https://discuss.ardupilot.org/t/after-upgrading-the-aircraft-version-above-4-4-0-the-parameters-of-mnt-cannot-be-found
=> Tools: added DroneCAN dependencies

libraries/SITL/SIM_AirSim.cpp
Co-authored-by: Oleksiy Protas <elfy.ua@gmail.com>
Replaces https://github.com/ArduPilot/ardupilot/pull/24158/files
=> SITL: correct diagnostic message obout what AirSim-in addr we bound

libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS_Backend.cpp
this is our object, we don't need permission
=> AP_AHRS: remove call to get_home()

ArduPlane/navigation.cpp
In FBWB/CRUISE Plane can drastically overshoot altitude and continue to climb/descent long after pilot gives opposite elevator stick input, resulting in crashing into the ground or drastically overshooting the ceiling. This fixes the issue.
```
CRUISE_ALT_FLOOR 0
FBWB_CLIMB_RATE 5
TECS_SINK_MIN 2.5
TECS_SINK_MAX 5
```
Imagine you are at 120 meters in CRUISE and want to do your max descent with lowest airspeed. You lower your throttle to zero and command full nose down. You requested slowest airspeed, so your plane will not be able to sink 5 m/s as directed, more like 2.5 m/s. You descent to 20 m and want to pull up, so you move your elevator stick for full nose up, you expect your airplane to pull up and climb, but it does not, it continues down and will hit the ground.
Imagine you want …
=> Plane: Fix FBWB/CRUISE missing zero crossing of elevator input

libraries/AP_GPS/AP_GPS_NOVA.cpp, libraries/AP_GPS/AP_GPS_NOVA.h
Relying on the simulator to test this
=> AP_GPS: remove dedundant crc32 routine from Nova

ArduCopter/mode_zigzag.cpp
The flight mode name can be obtained with the name method.
The flight mode name is described in each GCS message.
When the flight mode name is changed, multiple messages are changed.
I think it is better to centralize flight mode names.
=> Copter: Get the flight mode name display from the name method

Tools/autotest/vehicle_test_suite.py
name is a string, not an integer
=> autotest: correct format string in error path

Tools/autotest/test_build_options.py
This allows simple redirection from `./Tools/autotest/test_build_options.py --board=FSO_Beacon --emit-disable-all-defines` to a file which can then be inserted into an editor buffer easily.
Sponsored by FreeSpace Operations
=> Tools: stop emitting debug as part of test_build_options.py

libraries/AP_DAL/AP_DAL_InertialSensor.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
this is a possible fix for #20710 
the velocity corrections introduce a lot of noise in the reported velocity to external controllers. With the velocity correction enabled a VTOL aircraft may oscillate badly if the IMU position is significant.
This PR uses the filtered gyro, and lowers the filter frequency in the DAL to 10Hz
This is an example on a large quadplane:
the yellow line shows the much better velocity east output with this change versus the original in blue
this aircraft has:
- INS_POSn_X = 0.5
- GPS_POS1_X = -0.1
- GPS_POS1_Y = -1.2
the issue was noticed as the aircraft oscillated in QLOITER mode with the correct INS and GPS position parameters. Setting INS_POSn_X==0 stopped the oscillation
=> AP_NavEKF3: filter velocity corrections for IMU position

libraries/AP_DAL/AP_DAL_VisualOdom.h
This resolves issue https://github.com/ArduPilot/ardupilot/issues/26800
This has been lightly tested using the ModalAI VOXL camera to confirm that it still works.  I also tried setting the delay to a large value (>100ms) and the EKF variances become large so we know the parameter is being used.
Thanks very much to @luweiagi for finding this!
=> AP_DAL: visual odom get_delay_ms return fix

Tools/autotest/arducopter.py
.... end up passing `--defaults` twice on SITL command-line, which is last-one-in-wins
=> autotest: correct command-line for sitl in FlyEachFrame

libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
ATC_SLEW_YAW parameter does not affect the Loiter mode. (#20758)
https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/ReleaseNotes.txt#L1153
> Loiter mode ignores ATC_SLEW_YAW parameter
This parameter seems to work in the following flight modes:
- Auto
- Circle
- Guided
- RTL
- SmartRTL
- Land
=> AC_AttitudeControl: fix ATC_SLEW_YAW description (NFC)

libraries/AP_Param/AP_Param.cpp, libraries/AP_Param/AP_Param.h, libraries/Filter/HarmonicNotchFilter.cpp
This fixes parameter conversion for the harmonics bitmask in the harmonic notch. If the 7th bit was set the conversion comes out incorrectly because it does a numerical conversion rather than a bitmask one. The original conversion was added in https://github.com/ArduPilot/ardupilot/pull/24309. This conversion is included in 4.5 so we should include this fix since we only get one attempt at conversion. 
The current conversion results in all harmonics above 8 being enabled if the 8th harmonic is enabled. For example:
int8 -1 is 0b1111,1111 the current conversion converts this to int32 -1 which is 0b1111,1111,1111,1111,1111,1111,1111,1111 this is all harmonics on (although we only support 16).
The new conversion converts to int32 255 which is 0b0000,0000,0000,0000,0000,0000,1111,1111.
I don …
=> AP_Param: add Convert bitmask parameter width, Harmonic notch use new param width conversion.

AntennaTracker/Tracker.cpp, ArduCopter/Copter.cpp, ArduPlane/ArduPlane.cpp, ArduSub/ArduSub.cpp, Blimp/Blimp.cpp, libraries/AP_Baro/AP_Baro.cpp, libraries/AP_Baro/AP_Baro.h, libraries/AP_Baro/AP_Baro_Backend.h, libraries/AP_Baro/examples/BARO_generic/BARO_generic.cpp
no backend actually needs to be prodded, everything is done on timers
... note that the virtual function is being removed; if any backend was overriding it they would now fail as they must have said they were overriding and now don't.
=> Remove AP_Baro accumulate API

libraries/AP_Motors/AP_MotorsHeli_RSC.h
Currently, when performing autorotations, bool variable "rotor_speed_above_critical" is allowed to switch to false.
This cause the rotor_runup_complete bool to change to false and consequently limits the I-term of the yaw axis controller (AC_AttitudeControl_Heli.cpp line line 515) , in flight, see following log screenshot:
This has potentially dangerous consequences on vehicle controllability.
Suggested mod keeps the "rotor_runup_complete" variable true, thus preventing decay of yaw axis I-term during glide descent.
=> TradHeli: fix yaw behavior in autorotation

Tools/autotest/arducopter.py, Tools/autotest/helicopter.py
... and remove some verbiage by over-riding  do_RTL and land_and_disarm in heli
=> autotest: rewrite PosHoldTakeoff using newly-available methods

libraries/AP_HAL/utility/DataRateLimit.cpp, libraries/AP_HAL/utility/DataRateLimit.h, libraries/AP_HAL_SITL/SITL_State_common.cpp, libraries/AP_HAL_SITL/SITL_State_common.h, libraries/AP_HAL_SITL/UARTDriver.cpp, libraries/AP_HAL_SITL/UARTDriver.h, libraries/SITL/SIM_ELRS.cpp, libraries/SITL/SIM_ELRS.h, libraries/SITL/SITL.cpp, libraries/SITL/SITL.h
This adds a simulator for a ELRS radio running the mavlink-rc branch. Nothing clever, just a data rate limit and some buffers with reporting via the RADIO_STATUS mavlink message. ~~It creates its own HAL SITL UART driver so all the usual commands for addresses and ports should still work. I have been testing with: `-A --serial2=sim:ELRS:tcp:3` which allows you to connect tcp to 5763 (the same as normal for serial 2).~~ You also have to set the serial baud to 460. Now runs its own little TCP server.
The goal is to have a limited data link for testing both AP and GCS. EG (https://github.com/ArduPilot/ardupilot/pull/26098)
A real ELRS setup:
This PR:
This also improves the UART data rate limiting by tracking the fractional number of bytes remainder on each call.
=> SITL: add ELRS simulator

libraries/AP_Baro/AP_Baro.cpp, libraries/AP_Baro/AP_Baro.h
Caching this introduces discontinuities in TECS, as the step change modifies the target speed demand.
The graph of speed demand steps are from EAS2TAS recalculating every 25 meters in the climb, these changes then ripple into the throttle feed forward for throttle as a throttle spike, that makes it all the way out to the motor.
My understanding of the reason for this cache is this was very expensive for us back in the APM2 days, but the world has moved on since then and has a lot more processing power available then we used to. We could try to limit this to faster boards, but I think we can probably afford this on all our currently supported boards. (Side benefit, saves memory :) )
Will be test flying this on a backport to 4.4 tomorrow.
=> AP_Baro: Do not cache EAS2TAS conversions

ArduPlane/navigation.cpp
A simple constrain to never change target altitude more than configured TECS limits, even if `FBWB_CLIMB_RATE` is more than `TECS_SINK_MAX` or `TECS_CLMB_MAX`. Should not change anything for properly configured `FBWB_CLIMB_RATE`. This constrain is asymetrical, meaning climb or sink constrain may happen at different stick deflections if `TECS_SINK_MAX` is different than `TECS_CLMB_MAX`.
Tested with SITL with:
```
TECS_SINK_MAX 4
TECS_CLMB_MAX 6
FBWB_CLIMB_RATE 8
```
Before:
After:
=> Plane: Limit possible climb/sink rate in FBWB/CRUISE to TECS limits

Tools/AP_Periph/gps.cpp, libraries/AP_GPS/AP_GPS.cpp, libraries/AP_GPS/AP_GPS.h
If the rover GPS does not get a RelPosNed sample for 500ms then it would send invalid values on the CAN bus, causing the flight controller to show GPS yaw as unhealthy
=> AP_Periph: fixed check of return of get_RelPosNed

ArduCopter/mode_guided.cpp, Tools/autotest/arducopter.py
This resolves an Internal Error (see issue https://github.com/ArduPilot/ardupilot/issues/26865) which is caused by **Guided** mode neglecting its responsibility to call set_land_complete(false) when it believes the vehicle has taken off.
This only occurs when the caller is providing [SET_ATTITUDE_CONTROL messages](https://ardupilot.org/dev/docs/copter-commands-in-guided-mode.html#set-attitude-target) where the "thrust" field is really interpreted as a thrust (as opposed to being interpreted as a climb rate).
This has been tested in SITL to confirm that before this fix the issue occurs and afterwards it does not.
The GuideMostThrust autotest (see PR https://github.com/ArduPilot/ardupilot/pull/26782) has also been enabled
=> Copter: guided mode fix for landing detector internal error

libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp, libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp, libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.h
if using GPS yaw we don't want to do a yaw reset on completion of GPS yaw, so just don't detect compass learning
this avoids an issue where COMPASS_LEARN=3 is set in flight with EK3_SRC1_YAW=3 for GPS with compass fallback. That leads to a yaw alignment reset on completion of compass learning which leads the EKK to diverge
we really need to better understand the divergence as well
Some clues:
- when the bug happens we end up with huge compass offsets. The compass_learn=3 system uses GSF, which should be unaffected, so this doesn't make sense
UPDATE: reworked by @priseborough
=> AP_NavEKF3: don't look at compass learning with GPS yaw

libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
ESC_Telemetry will not send MAVLink MSG_ESC_TELEMETRY_1_TO_4 if ESC_TELEM_MAX_ESCS (PWM/SERVO) count is <=3 as logic was to keep idx = ESC_TELEM_MAX_ESCS/4 It gives rise to 3 big issues that are :-
1.It will leave some values if ESC_TELEM_MAX_ESCS which are not completely divisible by 4 e.g. 1,2,3,5,6,7,9....
2. (next_idx + idx) % num_idx it will give error if escs are less than 4
3. for loop will never start if escs count is less than 4 i.e the message inside loop will be skipped even if escs are present. Also if escs are not in multiple of 4 then it will skip 1 iteration
Solution in commit:
This is rectified by logic to add 1 to num_idx if ESC_TELEM_MAX_ESCS is not multiple of 4.
=> solved the logical error in grouping of escs into 4

Tools/AP_Periph/airspeed.cpp, Tools/AP_Periph/compass.cpp
This propagates the new periph option and not armed check to the continuous probe used by airspeed and compass, brining them in line with rangefinder.
=> Periph: Add probe continuous checks to airspeed and compass

libraries/Filter/NotchFilter.cpp, libraries/Filter/NotchFilter.h
This means we get NaN rather than zero in the log if not initialised. Could also change to log -1 rather than NaN.
I hope it will help with debugging https://discuss.ardupilot.org/t/notch-filters-turn-on-with-a-delay/116276/12
=> Filter: NotchFilter: return NaN for `logging_frequency` if not initialised

libraries/GCS_MAVLink/GCS_Common.cpp
Rework the serial port write logic in passthru_timer() to use the return value to detect partial writes due to the serial buffer filling up.  Unwritten data is saved in buf1 or buf2 and the write is retried on the next iteration.  This avoids lost data when the speed of the two serial ports differs and large blocks of data are sent.
For example, flash programming of ESP MCUs via USB to serial passthrough results in writes of more than 6000 bytes at a time which quickly fills the serial port buffer.
The existing code fails when flashing ELRS receivers via serial passthrough of ELRS which has become a more common need with the mavlink-rc branch of ELRS and the recent support of ESP based receivers in mLRS.  This is especially troublesome with AIO flight controllers which may not provide …
=> GCS_MAVLink: Avoid serial passthrough buffer exhausted/lost data

ArduCopter/GCS_Mavlink.cpp, ArduCopter/mode.cpp, ArduCopter/mode.h, ArduCopter/mode_auto.cpp, Tools/autotest/arducopter.py, libraries/AP_Common/Location.cpp, libraries/AP_Common/Location.h, libraries/AP_Mission/AP_Mission.cpp, libraries/AP_Mission/AP_Mission.h
This adds support for a new mission item (https://github.com/ArduPilot/mavlink/pull/212, https://github.com/mavlink/mavlink/pull/2088) that acts as a marker to the autopilot that it can rejoin a mission at any point after this marker and before a landing or MAV_CMD_DO_LAND_START.
Demo: https://youtu.be/SoHXRTD0vEs?si=pHTvRDMcOsStv4l6
This was originally done on 4.1.0 where it has a lots of testing on real vehicles this rebase has not had the same level of testing.
Along with the new mission item this also adds support for passing in a location to the various `DO_LAND_...` AP mission functions. Copter then uses this to pass in the stopping point rather than the current location. Helpers are added to so the current method without location still works for plane. Passing in the stopping point …
=> Copter: support `DO_RETURN_PATH_START` in AUTO RTL mode

Tools/autotest/arduplane.py, libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS_InertialLabs.h, libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain5.h, libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain7.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain7.h, libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.h, libraries/AP_ExternalAHRS/AP_ExternalAHRS_backend.h
* This catches when there's a mismatch of GPSx_TYPE and EAHRS_SENSORS when GPS is enabled
* Before this pre-arm, failure to set GPS_TYPE2 to 21 (ExternalAHRS) resulted in silent rejection of the data in AP_GPS because the default is off
* The wiki did not say to set GPS_TYPE on anything but the VN300
* For now, until we support 3+ GPS instances, this only checks if you have at least on GPSx_TYPE set to EAHRS.
Drive by fix - logging problem in Microstrain7 with format strings.
Tested in SITL with MicroStrain7 hardware. And, a new CI test:
```bash
./Tools/autotest/autotest.py build.Plane test.Plane.GpsSensorPreArmEAHRS
```
The default behavior is to disable the 2nd GPS, so MicroStrain7 was dropping the data on the floor in the call to `AP::gps().handle_external(gps, instance);`
The same …
=> AP_ExternalAHRS: Add pre-arm for misconfigured EAHRS_SENSORS and GPS_TYPE

libraries/AP_Logger/AP_Logger_W25N01GV.cpp, libraries/AP_Logger/AP_Logger_W25N01GV.h
Add support to W25N02KV flash
Tested on custom hardware, now the driver W25NXX will detect the flash automatically, so I will rename the related hwdef and class in another pr
=> AP_Logger: Add support to W25N02KV nand flash

libraries/AP_HAL/RCOutput.h
Fixes https://github.com/ArduPilot/ardupilot/issues/26295
@rmackay9 's LED is not compliant with the LED spec. The original 4.4 timing gives an output of 833Khz which is incorrect - it should be 800Khz which has been corrected in 4.5. With this output rate Randy's LED is unable to parse the pulse widths even though they too are in-spec (widths should be 850ns +- 150ns and 400us +- 150ns. The current 4.5 widths are: 464/776 and 930/310. Randy's LED will work with the following timings: 308/932 and 930/310. So it is the T0 timing that is the problem *even though* the current timing is closer to spec. That said, the timing that Randy's LED wants is still in spec and means that T0 and T1 are symmetrical - so I think this is an ok change, even though its a hardware problem. 
A final note - …
=> AP_HAL: make NeoPixel high-low proportions match for 0 and 1

ArduCopter/config.h, ArduCopter/land_detector.cpp, Tools/autotest/helicopter.py
This PR fixes #26864 where the aircraft can detect a landing when at full throttle in stabilize and upside down. Now the aircraft will correct detect a crash.
Sorry I didn't explain what is happening here and why this fix works. 
The land detector checks that the throttle mix value has dropped to near throttle_mix_at_min as part of the landing checks. To set the throttle mix value to throttle_mix_at_min we have two key checks:
1. Angle requested < 15 degrees
2. Angle error < 30 degrees
It then sets throttle_mix to throttle_mix_at_min.
The land detector checks to see if throttle_mix is close to throttle_mix_at_min before proceeding but this is not the same as checking that it has been set to throttle_mix_at_min. This check passes all the time with the default settings as …
=> Copter: Land Detector: Include angle checks

Tools/autotest/arducopter.py, Tools/autotest/vehicle_test_suite.py, libraries/AP_Baro/AP_Baro_SITL.cpp, libraries/AP_Baro/AP_Baro_SITL.h, libraries/SITL/SITL.cpp
- accumulate simulated barometer drift rather than setting based on vehicle uptime
- add description for SIM_BARO_DRIFT
- bugfixes for hook removal in exception handling
... and, of course, add a test that we adjust the barometer altitude over time.If the EKF parameter is not set then the test doesn't pass.  In fact, it fails with a flow-of-control error in the landing detector....
=> Add test for EK3_ORGN_HGT_MASK

libraries/AP_Compass/AP_Compass_IST8310.cpp
the WAI (whoami) register is writeable. Not only is it writeable, but the written value is persistent across a power cycle. You have to remove power for about 30s for it to finally go back to the right default value of 0x10
this makes using WAI as a test for finding a IST8310 problematic. The best we can do is send a soft reset which will reset it to default for us to then check
fixes #25946
=> AP_Compass: workaround hardware bug in IST8310 whoami

Tools/autotest/arducopter.py, libraries/AC_Avoidance/AC_Avoid.cpp, libraries/AC_Avoidance/AC_Avoid.h
This fix is the result of a log where home changed altitude resulting in a huge breach of the max altitude fence. There was no fence action configured, however avoidance was enabled resulting in the vehicle trying to back away from the max altitude fence at 15 m/s. The configured climb rate limits were +-2.5 m/s. 
Firstly this fixes the avoidance to constrain the velocity to `AVOID_BACKUP_SPD` parameter.
Secondly this constrains Z backup to half the set pos controller speeds. This helps keep the speeds in balance since the the avoid backup speed is probably set with XY speed in mind and could be too large for Z. 
I have not tested this yet. We might want a minimal fix to just apply the backup speed in avoid for a backport.
=> Copter: fix unconstrained avoidance backup speed

ArduCopter/AP_ExternalControl_Copter.cpp, ArduCopter/AP_ExternalControl_Copter.h, ArduCopter/Copter.cpp, ArduCopter/Copter.h, Rover/AP_ExternalControl_Rover.cpp, Rover/AP_ExternalControl_Rover.h, Rover/Rover.cpp, Rover/Rover.h, Tools/scripts/run_astyle.py
This is to fix the issue #25381 
Implemented `set_global_location` for Rover and Copter ( taking inspiration from  ArduPlane)
Taking everything from [this](https://github.com/ArduPilot/ardupilot/pull/25722#issue-2030071065) pull request
In ArduPilot repo:
```shell
./sim_vehicle.py -v ArduCopter --map --console --enable-dds
```
Running MicroROS agent:
```shell
cd ~/ros2_ws
. /opt/ros/humble/setup.bash
colcon build --packages-up-to ardupilot_sitl
. install/setup.bash
cd src/ardupilot/libraries/AP_DDS
ros2 run micro_ros_agent micro_ros_agent udp4 -p 2019 -r dds_xrce_profile.xml
``` 
Taking off the copter
```shell
mode guided
arm throttle
takeoff 50
```
Now publish a message for drone to go to greyhound track.
```shell
cd ~/ros2_ws
. /opt/ros/humble/setup.bash
colcon build --packages-up-to …
```
=> Enabled sending waypoints to ardupilot for copter and rover

Tools/scripts/serial_playback.py, libraries/AP_Scripting/drivers/INF_Inject.lua, libraries/AP_Scripting/drivers/INF_Inject.md
the serial_playback.py can be used to play back a log. Useful for diagnosing errors when they occur
=> AP_Scripting: added logging and checksum fix to INF_Inject driver

Tools/autotest/arducopter.py, Tools/autotest/vehicle_test_suite.py, libraries/AP_InertialSensor/AP_InertialSensor.cpp, libraries/AP_InertialSensor/AP_InertialSensor.h
This caused there to be no notch filtering at all in the first 30 seconds of operation.
Bug introduced in https://github.com/ArduPilot/ardupilot/pull/25442
=> AP_InertialSensor: ensure that notches get updated while converging

Tools/scripts/build_options.py
```
#if AP_OSD_EXTENDED_LNK_STATS
bool AP_OSD_Screen::is_btfl_fonts()
{
const AP_MSP *p_msp = AP::msp();
return (p_msp != nullptr && p_msp->is_option_enabled(AP_MSP::Option::DISPLAYPORT_BTFL_SYMBOLS));
}
```
=> Tools: build_options.py: note extended link stats requires MSP

libraries/AP_Scripting/drivers/INF_Inject.lua
the device does send 0x00 sometimes and data is valid
=> AP_Scripting: allow for 0x00 for 2nd checksum byte in INF_Inject driver

ArduPlane/Parameters.cpp
Moving from centidegree to degree need adjusting the increments in the metadata (MP uses metadata to setup GUI)
=> Plane: Fix metadata (increments) for changed params

libraries/AP_Filesystem/AP_Filesystem.cpp, libraries/AP_Filesystem/AP_Filesystem.h, libraries/AP_Filesystem/AP_Filesystem_ROMFS.cpp, libraries/AP_Filesystem/AP_Filesystem_backend.cpp, libraries/AP_Filesystem/AP_Filesystem_backend.h, libraries/AP_ROMFS/AP_ROMFS.cpp, libraries/AP_ROMFS/AP_ROMFS.h
Provides the same safety guarantee and user experience improvement as `AP_ROMFS::find_decompress`.
Also clean up the users and the comments and clarify AP_ROMFS's usage too.
Tested on CubeOrange. Flashing its own bootloader works and so does the LASTLOG.TXT, which exercises the changed code.
=> AP_Filesystem: guarantee load_file() data is null-terminated

libraries/AP_Motors/AP_MotorsHeli.cpp, libraries/AP_Motors/AP_MotorsHeli.h, libraries/AP_Motors/AP_MotorsHeli_Dual.cpp, libraries/AP_Motors/AP_MotorsHeli_Dual.h, libraries/AP_Motors/AP_MotorsHeli_Single.cpp, libraries/AP_Motors/AP_MotorsHeli_Single.h, libraries/AP_Motors/AP_MotorsHeli_Swash.cpp, libraries/AP_Motors/AP_MotorsHeli_Swash.h
This pr adds logging for blade pitch angle contributions from collective and cyclic.  Whilst it is possible to calculate these values from other log fields it requires the user to understand how we do the blade angle conversions and to know how the mixers work.  This is therefore a convenient logging field.
This PR only makes changes to logging.  There are no functional changes to flight dynamics or actuators.
For cyclic angle contributions to be accurate users will need to set the newly added H_CYC_MAX_ANG param.
Example from dual heli logging in SITL:
=> Heli: Add blade pitch angle logging

Rover/sailboat.cpp
The value of throttle_out is 0 or the result value of the IF statement processing.
Setting 0 at the beginning ensures that 0 is determined.
=> Rover: Delete unnecessary decisions

Rover/Parameters.cpp
Add a terminate to the parameter item.
The user selects from the parameter description.
The developer understands the source and sets it.
GCS displays the parameter description.
=> Rover: Add terminate to parameter description

ArduCopter/mode_acro.cpp, ArduCopter/mode_acro_heli.cpp, ArduSub/mode.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl_TS.cpp
This moves `euler_rate_to_ang_vel`, `ang_vel_to_euler_rate` and `euler_accel_limit` to use Quaternions. The goal is to minimize the use of the euler representation of target attitude with the eventual goal of removing it. This would simplify https://github.com/ArduPilot/ardupilot/pull/26253.
There is some extra overhead because we have to calculate euler angles from the quaternion. We could do a bit of quaterinon gymnastics to get the trig values directly, which would reduce the overhead, but its quite a bit more scary looking.
I'm not really sure if this is worth it.....
=> AC_AttitudeControl: use euler angle target less in favor of quaternion.

Tools/ardupilotwaf/boards.py
Fix issue where linker fails with Xcode 15.3.
Reported here:
- https://discuss.ardupilot.org/t/compile-ardupilot-4-4-4-copter-sitl-on-mac-m1-sonoma-14-4/115210
- https://discord.com/channels/674039678562861068/674039678982422579/1225621147278770316
Some discussion about Xcode linker changes here:
- https://developer.apple.com/forums/thread/731089?page=2
Fix verified using:
- MacBookPro M1 Max
- macOS Sonoma 14.3.1
- Xcode_15.3
- Command_Line_Tools_for_Xcode_15.3
=> Tools: ardupilotwaf: use classic clang linker when compiling on macOS

libraries/AP_CANManager/AP_CANSensor.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/lua_bindings.cpp
Currently you will get a valid can device in your script even-though it will never actually work because the is no protocol configured for it. This allows that case to be caught by the script and an appropriate message given if required.
=>  AP_Scripting: CAN: `get_device` and `get_device2` return nil if no driver is configure with the correct protocol

README.md
I've been pretty busy in the last years with the Linux kernel and couldn't dedicate the time needed to really maintain the Linux HAL in Ardupilot. I will still be around and receive notification when people mention my username, but I may not have time to review/reply as it's already happening.  Hopefully I can return in future and be more active.
=> README: Remove myself from maintainers list

Rover/GCS_Mavlink.cpp, Rover/Rover.cpp, Rover/mode.cpp, Rover/mode_guided.cpp
ArduPilot is based on the STM32.
The STM32 is better at multiplication than division.
Strong at multiplication means shorter time to use.
=> Rover: Change division to multiplication

ArduPlane/Log.cpp, ArduPlane/defines.h, ArduPlane/quadplane.cpp, ArduPlane/tiltrotor.cpp, ArduPlane/tiltrotor.h
This adds logging of tilt rotor tilt angles. The base angle 0 to 90 if vectored the left and right tilt outputs. This is much easyer than trying to back calculate from the servo outputs. Tested with the Griffin in realflight. It has a tilt yaw angle of 25 deg, so in hover we see the base output at 0 and the left and right opposite in that range.
As it transitions they all move to 90:
Back transition:
This is logged at the same rate as QTUN, 25Hz.
=> Plane: Tiltrotor: add logging of tilt angles.

libraries/AP_HAL_ChibiOS/hwdef/BlitzH743Pro/defaults.parm
we usually do this on any bd with CAN to ease setup.....adding DroneCAN GPS only requires setting GPS_TYPE to work
=> hwdef: enable can port on Blitz743Pro

ArduPlane/GCS_Mavlink.cpp, ArduPlane/Log.cpp, ArduPlane/Plane.h, ArduPlane/commands_logic.cpp, ArduPlane/mode.cpp, ArduPlane/mode_guided.cpp, ArduPlane/mode_qrtl.cpp, ArduPlane/mode_rtl.cpp, ArduPlane/navigation.cpp, ArduPlane/quadplane.cpp
This variable updated unpredictably, and it was easy to introduce bugs. It was not used in many places and is clearer to calculate the error directly when needed. This is related to h. This PR should make it much harder to let a bug like https://github.com/ArduPilot/ardupilot/pull/23458 slip through.
This is a better alternative to PR https://github.com/ArduPilot/ardupilot/pull/24195
=> Plane: remove altitude_error_cm variable

libraries/AP_JSON/AP_JSON.cpp
Was experimenting with the `AP_JSON` library and noticed that not all the `::printf()` calls have a terminating `\n`,
=> AP_JSON: Ensure all printf() calls end with line break

Tools/AP_Bootloader/board_types.txt
we allocated outside the comment mentioned at the top of the file, so add a comment at the end too
=> Tools: add comment at end of file restricting range to be allocated from

Rover/mode_rtl.cpp, Tools/autotest/rover.py
```
MAX wasn't treating these things as floats
```
Closes https://github.com/ArduPilot/ardupilot/issues/26995
=> Rover: Allow fractional RTL_SPEEDs

libraries/AP_HAL_Linux/SPIUARTDriver.cpp, libraries/AP_HAL_Linux/SPIUARTDriver.h, libraries/AP_HAL_Linux/UARTDriver.h
GPS auto-detection requires get_baud_rate to return non-zero.  The SPIUARTDriver was returning 0.
Tested on NavIO2.
Still something strange going on:
... but it's now working.
Note that the return value doesn't actually matter here, it's just got to be non-zero.
=> AP_HAL_Linux: fix SPIUARTDriver to work with GPS autodetection

Tools/AP_Periph/AP_Periph.cpp
Currently you cannot build periph including airspeed but without i2c. There only realistic reason you would want to do this would be to use MSP airspeed, but even that would be quite unusual. This gets it building again. The other option would be to put in a `#error` that airspeed requires i2c.
=> AP_Periph: allow airspeed without I2C

Tools/AP_Periph/rangefinder.cpp
This fixes a bug introduced in https://github.com/ArduPilot/ardupilot/pull/26607. The `last_rangefinder_update_ms` was only set if when a reading was sent. That resulted in calling rangefinder update at the periph loop rate if the sensor is unhealthy or had no new reading. In my case I was testing a serial "request and response" rangefinder and this bug meant we just flooded the uart with requests.
=> AP_Periph: always limit rangefinder update rate to given max rate

libraries/Filter/NotchFilter.cpp
Common processing is in TRUE and FALSE.
I put it out there as a common process.
=> Filter: Get common processes out of the way

Rover/Parameters.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Torqeedo.cpp, libraries/AP_Torqeedo/AP_Torqeedo.cpp, libraries/AP_Torqeedo/AP_Torqeedo.h, libraries/AP_Torqeedo/AP_Torqeedo_Backend.cpp, libraries/AP_Torqeedo/AP_Torqeedo_Backend.h, libraries/AP_Torqeedo/AP_Torqeedo_Params.cpp, libraries/AP_Torqeedo/AP_Torqeedo_Params.h, libraries/AP_Torqeedo/AP_Torqeedo_TQBus.cpp, libraries/AP_Torqeedo/AP_Torqeedo_TQBus.h
This PR adds a frontend/backend split to the AP_Torqeedo library allowing up to two motors to be used and also opening the door for supporting higher powered Torqeedo motors in the future (they use a CAN protocol).  Changes in this PR include:
- TRQD parameters become TRQ1 and TRQ2.  Parameter conversions are included and tested
- New TRQx_SERVO_FN parameters allow the user to specify if the motor output should use the Throttle, ThrottleLeft or ThrottleRight servo output.  This means we can support two motors for use on Ackermann or skid-steering vehicles.
- Logging has a new "I" (for instance) field.  Units and multipliers were also added in order to allow the GCSs to properly display the output separated by instance.
- Most functionality has simply been moved to a new AP_Torqeedo_TQBus …
=> AP_Torqeedo: add support for two motors

libraries/AP_Mission/AP_Mission.cpp
previously if there was a jump limit we informed the user we were jumping and provided the current count and the limit.
This changes things so that if there's no limit we emit the same message, with the count and "unlimited" in place of the limit number
Closes https://github.com/ArduPilot/ardupilot/issues/26802
=> AP_Mission: emit jump count even if no limit

Tools/ardupilotwaf/ap_library.py, Tools/ardupilotwaf/chibios.py, Tools/ardupilotwaf/git_submodule.py, wscript
depends on:
- https://github.com/ArduPilot/mavlink/pull/359
- https://github.com/ArduPilot/waf/pull/17
note the waf PR will require a force push as it rebases on upstream 2.0.27
tested on ubuntu 24.04
=> waf: support python 3.12

libraries/AP_Motors/AP_MotorsHeli_Swash.cpp, libraries/AP_Motors/AP_MotorsHeli_Swash.h
A minor PR to make the motor numbers in heli swashplate const.  This provides additional protection so that we cannot accidently change the motor numbers.
=> Heli Swashplate: Make motor numbers const

Tools/environment_install/install-prereqs-ubuntu.sh, Tools/vagrant/initvagrant.sh, Vagrantfile
This requires Python 3.12 support, which tridge is working on over here: https://github.com/ArduPilot/waf/pull/17
Closes https://github.com/ArduPilot/ardupilot/issues/26976
=> Add support for Ubuntu Noble (24.04)

Tools/scripts/build_ci.sh
the new release of pymonocypher breaks generation of public keys
see this issue:
https://github.com/jetperch/pymonocypher/issues/9
=> Tools: use previous release of pymonocypher

libraries/AP_GPS/AP_GPS.h, libraries/AP_GPS/AP_GPS_GSOF.cpp, libraries/SITL/SIM_GPS.cpp, libraries/SITL/SIM_GPS.h, libraries/SITL/SIM_GPS_NMEA.cpp, libraries/SITL/SIM_GPS_Trimble.cpp
Both the NMEA and GSOF simulators have broken ground course in SITL. 
Set these params for GSOF against UBX:
```
GPS2_TYPE  11
SIM_GPS2_TYPE    11
```
Or these for NMEA
```
GPS2_TYPE  5
SIM_GPS2_TYPE  5
```
Then, start SITL with plane, arm, and takeoff.
Here's the GPS course over ground for Ublox (GPS 1) and GSOF (GPS 2).
GSOF:
NMEA:
Is it bad you can have a flyaway if you don't wrap the GPS ground course from 0-360?
=> Gps ground course in NMEA and GSOF was incorrect

libraries/AP_HAL_Linux/GPIO_RPI.cpp, libraries/AP_HAL_Linux/GPIO_RPI.h, libraries/AP_HAL_Linux/GPIO_RPI_BCM.cpp, libraries/AP_HAL_Linux/GPIO_RPI_BCM.h, libraries/AP_HAL_Linux/GPIO_RPI_HAL.h, libraries/AP_HAL_Linux/GPIO_RPI_RP1.cpp, libraries/AP_HAL_Linux/GPIO_RPI_RP1.h, libraries/AP_HAL_Linux/Util_RPI.cpp, libraries/AP_HAL_Linux/Util_RPI.h
Fix #26386
Adds support to RP1 coprocessor.
=> AP_HAL_Linux: Add Raspberry Pi 5 GPIO support

ArduPlane/quadplane.cpp
The description refers to TRIM_PITCH, which was recently renamed to
PTCH_TRIM_DEG.
=> Quadplane: fix Q_TRIM_PITCH description

Tools/autotest/rover.py, libraries/GCS_MAVLink/MissionItemProtocol.cpp
In the case that we reject the new packet for some reason the receiving status and link persisted.
This isn't fatal in that the upload-timeout will trigger, but it is messy in that we will end up sending back two acks - the one for the bad `MISSION_COUNT`, and then the timeout later.
=> Correct back-to-back mission transfer with bad mission count

libraries/AP_RangeFinder/AP_RangeFinder_Lua.cpp
This change moves the timeout test from `AP_RangeFinder_Lua::handle_script_msg` back to `AP_RangeFinder_Lua::update`. This should revert the behavior to what folks are seeing in Copter 4.4, prior to https://github.com/ArduPilot/ardupilot/commit/2cc63f52a1d61424584f06c504374e33c8d2c9a0.
The timeout is still set to 500ms.
=> AP_RangeFinder: fix Lua timeout

Tools/ros2/README.md, Tools/ros2/ardupilot_sitl/src/ardupilot_sitl/launch.py
Expose mavproxy map and console into the ROS 2 launch CLI
Try the README changes, expect MAVProxy to start with map and console when supplied. Default is false which maintains existing behavior (which will work in CI).
=> Tools: Expose map/console mavproxy args

libraries/AP_BattMonitor/AP_BattMonitor.cpp, libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.cpp, libraries/AP_BattMonitor/AP_BattMonitor_ESC.cpp, libraries/AP_BattMonitor/AP_BattMonitor_ESC.h
This adds a `ESC_MASK` parameter to allow assigning particular ESCs to particular batteries. Default is 0 for use all which is the current behaviour.
=> AP_BattMonitor: ESC: add mask parameter

libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain7.cpp
Fix duplicate logic in the pre-arm check of microstrain7. Filter state was checked above.
=> AP_ExternalAHRS: Fix duplicate condition

Tools/ardupilotwaf/boards.py, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Currently on ChibiOS these flags are set before files are added from `ROMFS_custom` so the flags may be incorrect. This moves the setting of the flags to the same step as where the files are imbedded so nothing is missed. This also has the advantage of unifying the approach across all boards. 
I have tested imbedding a script in SITL, I have built a ChibiOS board and grepped the bin to see that the script is embedded correctly, but I have not had a chance to flash to a board to double check.
=> waf: move setting of ROMFS flags to embed step

AntennaTracker/ReleaseNotes.txt, AntennaTracker/version.h, ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, ArduPlane/ReleaseNotes.txt, ArduPlane/version.h, Rover/ReleaseNotes.txt, Rover/version.h, Tools/scripts/build_ci.sh
This is the Plane-4.5.2 release which is the same as the 4.5.2-beta1 release
This is the corresponding Copter release: https://github.com/ArduPilot/ardupilot/pull/27054
=> Plane: 4.5.2 release

libraries/AC_AutoTune/AC_AutoTune.h, libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
AutoTune requires that the target be unmodified by D_FF during twitch testing
=> AC_AutoTune: zero out D_FF during twitching

libraries/AP_Scripting/examples/fault_handling.lua, libraries/AP_Scripting/lua/src/ldo.c
this PR adds a test that exercises rapid fault handling and fixes it by shifting the save of the extra registers before the setjmp call and adding save/restore of the first 16 fp registers
The test was derived from the networking web server. The reason the web server triggered this issue is it continues running after a fault, and continually calls async functions (server side lua calls) that may fault. Most lua scripts when they fault will stop, so only have one chance to trigger the bug. The web server gets lots of chances per second to trigger the bug.
without the fix this lua script hard faults in a few seconds
This bug has been confirmed to happen with 4.3.x and 4.4.x as well as current stable 4.5.x
=> AP_Scripting: fixed hard fault on handling of lua exception

Tools/autotest/rover.py, libraries/GCS_MAVLink/MissionItemProtocol.cpp
Fixes this internal error:
```
ardurover: #4  0x0000604a12ed5b75 in AP_HAL::dump_stack_trace () at ../../libraries/AP_HAL_SITL/system.cpp:147
ardurover: No locals.
ardurover: #5  0x0000604a12ed5757 in AP_HAL::panic (errormsg=0x604a1302b4cd "AP_InternalError::error_t::%s") at ../../libraries/AP_HAL_SITL/system.cpp:51
ardurover:         ap = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7ffd7b9dec00, reg_save_area = 0x7ffd7b9deb40}}
ardurover: #6  0x0000604a12dc0d9f in AP_InternalError::error (this=0x604a13139258 <instance>, e=AP_InternalError::error_t::flow_of_control, line=217) at ../../libraries/AP_InternalError/AP_InternalError.cpp:28
ardurover:         buffer = "flow_of_ctrl", '\000' <repeats 36 times>, <incomplete sequence \354>
ardurover: #7  0x0000604a12fd4eee in …
```
=> GCS_MAVLink: deny attempt to do partial upload while mission transfer in progress

libraries/AP_Terrain/AP_Terrain.cpp, libraries/AP_Terrain/AP_Terrain.h
for a fast moving aircraft with small TERRAIN_SPACING you need a larger cache to prevent thrashing of the cache
=> AP_Terrain: added parameter for terrain cache size

Tools/ardupilotwaf/chibios.py, Tools/scripts/signing/README.md, Tools/scripts/signing/generate_keys.py, Tools/scripts/signing/make_secure_bl.py, Tools/scripts/signing/make_secure_fw.py
ensure users don't end up with the wrong version, and throw an error if they do
=> Tools: specify pymonocypher version in more places

libraries/AC_PrecLand/AC_PrecLand.cpp, libraries/AP_EFI/AP_EFI.cpp, libraries/AP_GPS/AP_GPS_Params.cpp, libraries/AP_SerialManager/AP_SerialManager.cpp
This only affects parameter documentation so should be low-risk.
This makes consistent the Type to be "MAVLink" in those few cases where we call it something else.
There's actually [one more in RC_Channels](https://github.com/ArduPilot/ardupilot/blob/master/libraries/RC_Channel/RC_Channels_VarInfo.h#L104) where we call it "MAVRadio" so I'd like to rename this one as well at some point if people are happy with that but that can be a separate PR.
=> AP_GPS, PrecLand, EFI, SerialManager: TYPE param docs renamed to MAVLink

libraries/AP_OSD/AP_OSD.cpp, libraries/AP_OSD/AP_OSD.h, libraries/AP_OSD/AP_OSD_Screen.cpp
Adds configurable parameters for adjusting the horizontal spacing and vertical extension of the OSD sidebar elements.
The parameters works as offsets, so the default value of 0 changes nothing in regards to the actual implementation. By setting the horizontal offset to positive values, it will increase the width/spacing between the sidebar elements, to the right, by the amount of columns specified. By setting the vertical extension parameter to a positive value, the vertical length will increase equally, both top and bottom, by the specified amount of lines.
This is specially useful for HD video systems, where the OSD screen size is larger and the default sidebar size and spacing can be small and a nuisance right in the middle of the screen.
Below is how a horizontal offset of 16 columns …
=> AP_OSD: Add configurable sidebar horizontal and vertical size extensions

libraries/AP_OSD/AP_OSD_MSP_DisplayPort.h
Adds the sidebar symbols translation to BTFL fonts, so sidebar is properly displayed in DJI O3 OSD.
(The image above shows the sidebars with a non-default width, made possible by the changes in #26359, but this PR and that one are completely independent, I just used the same code for testing).
=> AP_OSD: add BTFL sidebar symbols

libraries/AP_Param/AP_Param.cpp
I don't think it's necessary to separate type definitions and settings.
=> AP_Param: Summarize the type definitions settings

libraries/AP_HAL_SITL/SITL_State.cpp, libraries/AP_HAL_SITL/SITL_State.h, libraries/SITL/SITL.cpp, libraries/SITL/SITL.h
wind in the real world does not change instantly. Adding a time constant prevents the EKF from getting confused with instant changes in wind speed
=> SITL: added SIM_WIND_TC

libraries/AP_BattMonitor/AP_BattMonitor_FuelLevel_Analog.h
This was changed in https://github.com/ArduPilot/ardupilot/pull/25219, I'm not sure why. Fixes https://github.com/ArduPilot/ardupilot/issues/27017
=> AP_BattMonitor: FuelLevel_Analog: set has_current true so capacity is reported

ArduPlane/altitude.cpp
Previous behavior was either to flare extremely high or crash into the ground, depending on whether the land waypoint is higher or lower than home.
This allows the user to set a land waypoint altitude other than 0 relative without causing a crash.
=> Plane: fix rangefinder correction when terrain follow is off

Tools/autotest/arducopter.py
... the harness takes care of the cleanup in case of error
=> autotest: neaten Copter Loiter test

AntennaTracker/Parameters.cpp, ArduCopter/Parameters.cpp, ArduPlane/Parameters.cpp, ArduSub/Parameters.cpp, Blimp/Parameters.cpp, Rover/Parameters.cpp, Tools/autotest/param_metadata/param_parse.py
we have enforced this one-of-Values-or-Bitmask in libraries for a long time, and should have been enforcing it in vehicles before now.
MissionPlanner and MAVProxy ignore Values if Bitmask is present
Built on top of https://github.com/ArduPilot/ardupilot/pull/27070
=> Remove reduntant @Values from parameter documentation

libraries/AP_Mount/AP_Mount.cpp, libraries/AP_Mount/AP_Mount.h, libraries/AP_Mount/AP_Mount_Backend.cpp, libraries/AP_Mount/AP_Mount_Backend.h
Clarifies that Mount pitch and roll targets are in earth frame.
Explains why my servo mount wasn't doing what I expected when I was sending it `DO_MOUNT_CONTROL` commands.
=> AP_Mount: Clarify angle frames of set_angle_target()

Tools/AP_Bootloader/board_types.txt
Complements PR #27036 with a new Board ID proposal.
=> AP_Bootloader: ID reserve for FlywooF405HD_AIOv2

libraries/AP_Motors/AP_MotorsTri.cpp, libraries/AP_Motors/AP_MotorsTri.h, libraries/AP_Motors/examples/AP_Motors_test/AP_Motors_test.cpp
Still need to add more types, but tri frames are a rather common VTOL frame, and this is needed for Mission Planner's motor test page to work.
=> AP_Motors_test: add tri frames to json output

Tools/autotest/arducopter.py, libraries/AP_Mount/AP_Mount_Backend.h, libraries/AP_Mount/AP_Mount_Servo.cpp, libraries/AP_Mount/AP_Mount_Servo.h
Currently, the attitude quaternion reported by the Servo backend is the target angles, not the current angles. This PR changes the reported attitude to be the currently demanded servo angles.
FYI: @rmackay9
=> AP_Mount: In Servo backend, report attitude as demanded servo angles

Tools/AP_Bootloader/board_types.txt
Reserve ID range for UAV-DEV GmbH
=> AP_Bootloader: Reserve ID range for UAV-DEV GmbH

libraries/AP_Compass/AP_Compass_IST8308.cpp
this is not useful and just causes concern to users. Any small bus delay can trigger this. We have health monitoring at a higher level
=> AP_Compass: removed IST8310 overrun message

libraries/AP_Mount/AP_Mount.cpp
The mount library force configures the mount type on conversion, even if the mount was never configured in the first place.
=> AP_Mount: Only save converted mount parameter if mount was previously set in the first place

libraries/AP_Mount/AP_Mount.cpp, libraries/AP_Mount/AP_Mount_Backend_Serial.cpp, libraries/AP_Mount/AP_Mount_Backend_Serial.h, libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp, libraries/AP_Mount/AP_Mount_SToRM32_serial.h, libraries/AP_Mount/AP_Mount_Siyi.cpp, libraries/AP_Mount/AP_Mount_Siyi.h, libraries/AP_Mount/AP_Mount_Viewpro.cpp, libraries/AP_Mount/AP_Mount_Viewpro.h
This PR fixes a bug in our three serial mount drivers which currently always try to use the first serial port defined for use with gimbals (e.g. SERIALx_PROTOCOL = 8/Gimbal).  The bug appears when the user tries to set up two serial mounts.
The fix uses a similar pattern to our rangefinder drivers in that we track the serial driver instance and pass that into the constructor.  This serial instance (instead of the regular instance) is used when searching for the serial port.
This has been lightly tested on CubeRed connectded to a Siyi A8 (over ethernet) and ViewPro A10 (over serial).  Below is a picture of the new QGC 4.4 that includes support for controlling multiple gimbals.  Using the changes in this PR I was able to control both gimbals independently.
It will likely be difficult to get …
=> Mount: fix serial port used for 2nd serial driver

ArduCopter/mode_guided.cpp, Tools/autotest/arducopter.py
Closes https://github.com/ArduPilot/ardupilot/issues/27103
Supplied test causes internal error before, passes afterwards.
Only tested in SITL/autotest
=> Correct Copter guided submode change

ArduPlane/system.cpp
When in plane only mode the dshot type was not getting set late enough meaning that BlueJay ESCs would not work.
I worry that RC speed also does not appear to be being set.
=> Plane: ensure the dshot type gets set

libraries/AP_InternalError/AP_InternalError.cpp
`AP_InternalError::errors_as_string` casts the return value of `snprintf`, which is signed `int`, to unsigned `size_t`. So the comparison `<= 0` is effectively `== 0`, ignoring errors.
I don't think snprintf actually returns an error unless the format string is wrong, which it isn't, so this is probably mostly academic. I don't believe the `== 0` case is hit anyway, since the loop exits earlier by checking `buffer_used >= len`.
Also included a micro-optimization to avoid a conditional in the loop.
Note: I am employed by Exyn Technologies
=> Fix signedness issue with snprintf

libraries/AP_HAL_ChibiOS/hwdef/AnyleafH7/hwdef.dat
https://github.com/ArduPilot/ardupilot/pull/26999
=> Added mag and dataflash logging support to AnyLeaf H7

Tools/autotest/arducopter.py, libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp, libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp, libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp
This bug-finding and fix are not mine.  The autotest is mine, however :-)
@pavloblindnology reported them here: https://github.com/ArduPilot/ardupilot/issues/24039
@pavloblindnology was this the fix you were recommending?
This PR is based on https://github.com/ArduPilot/ardupilot/pull/26916 which adds some infrastructure changes to make autotesting with baro drift easier.
=> Fix infinite climb bug when using EK3_OGN_HGT_MASK

libraries/RC_Channel/RC_Channel.cpp
Fixing two (related) issues in here, from a user support session:
1. The arming check for duplicate RC Aux functions didn't check for Scripting functions, as it only checked for Aux function with an ID <256 (Scripting was 300+)
~~2. Added an extra check in the rover-quiktune script to warn the user if they had a mis-configured (or no) RC channel mapped to scripting~~
=> Fix arming check for duplicate scripting RC channels and extra RC checks for rover-quiktune

Tools/ardupilotwaf/boards.py
I was having an issue where an AP_Periph hwdef I was working on started failing when I added a comment to the top of the file. In fact, it was failing if the include was anywhere except at the very top. To reproduce the bug on master, place a line-break at the top of `libraries/AP_HAL_ChibiOS/hwdef/AeroFox-Airspeed/hwdef.dat` and try to compile.
When waf was trying to determine which boards AP_Periph could compile for, it did not correctly follow includes. It only considered one include at the very beginning of the file. This fixes that so it correctly scans through all includes, wherever they are in the hwdef.
=> Tools: fix checking of hwdef includes for Periph

Tools/ros2/ardupilot_sitl/CMakeLists.txt, Tools/ros2/ardupilot_sitl/src/ardupilot_sitl/launch.py
* Install models for other users such as the `plane.parm` that SITL launches with for plane
* Fix bool parsing in some launch args such as mavproxy and console
Create a launch file with the contents;
```xml
<?xml version="1.0"?>
<launch>
<include file="$(find-pkg-share ardupilot_sitl)/launch/sitl_dds_udp.launch.py">
<arg name="defaults" value="$(find-pkg-share ardupilot_sitl)/config/models/plane.parm"/>
<arg name="model" value="plane"/>
<arg name="command" value="arduplane"/>
</include>
</launch>
```
```bash
ros2 launch your_package your_launch_file.launch.xml \
refs:=$(pwd)/src/ardupilot/libraries/AP_DDS/dds_xrce_profile.xml \
map:=True \
console:=True
```
Then, change map and console to false and observe them not appear.
The plane should boot up just like sim_vehicle, and be able to use …
=> Tools: ros2: Improve ability to launch plane in headless mode

libraries/AP_DDS/AP_DDS_Client.cpp
ROS expects quaternions to be normalised and the default message constructor does not enforce this.
Quick check is to run the copter launch example:
```bash
ros2 launch ardupilot_sitl sitl_dds_udp.launch.py transport:=udp4 refs:=$(ros2 pkg prefix ardupilot_sitl)/share/ardupilot_sitl/config/dds_xrce_profile.xml synthetic_clock:=True wipe:=False model:=quad speedup:=1 slave:=0 instance:=0 defaults:=$(ros2 pkg prefix ardupilot_sitl)/share/ardupilot_sitl/config/default_params/copter.parm,$(ros2 pkg prefix ardupilot_sitl)/share/ardupilot_sitl/config/default_params/dds_udp.parm sim_address:=127.0.0.1 master:=tcp:127.0.0.1:5760 sitl:=127.0.0.1:5501
```
Then run rviz with the ArduPilot TF topics remapped:
```bash
ros2 run rviz2 rviz2 --ros-args -r tf:=/ap/tf -r tf_static:=/ap/tf_static
``` …
=> AP_DDS: ensure zero rotation quaternions are normalised

Tools/completion/zsh/_ap_bin, Tools/ros2/ardupilot_sitl/src/ardupilot_sitl/launch.py, libraries/AP_HAL_SITL/SITL_cmdline.cpp, libraries/SITL/SIM_InertialLabs.h, libraries/SITL/SIM_Loweheiser.h
Code remains to check for use of these options and give an error which contains the correct option to use, due to the non-intuitive mapping between --uartX and --serialN.
A future version will remove that code too, plus the similar deprecation warning in AP_HAL_Linux.
Tested that the arguments are correctly rejected.
=> AP_HAL_SITL: remove deprecated --uartX options

libraries/AP_BoardConfig/AP_BoardConfig.cpp, libraries/AP_HAL/UARTDriver.cpp, libraries/AP_HAL/UARTDriver.h, libraries/AP_HAL_ChibiOS/UARTDriver.cpp, libraries/AP_HAL_ChibiOS/UARTDriver.h, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py, libraries/AP_Scripting/generator/description/bindings.desc, libraries/GCS_MAVLink/GCS_Param.cpp
This adds support for outputting a driver enable signal from the UART. That is a line that is held high for the duration of a transmit. This is used with RS-485 transceivers. The STM32 has hardware support for this, so we just need to set the pin to the correct alternative function and set the bit in the UART config.  
The new flow control type can be set with the `BRD_SERx_RTSCTS` param. 
This is MAVLink with it enabled:
Currently this just uses the default timings for the time the pin goes high before the transmit is started and the time it takes to go low after the transmit has finished. There are config registers we could use to change this if we needed to.
In order to know which alternate function to use the information must be passed in from the hwdef.
=> ChibiOS: UART: Add support for RS-485 Driver Enable RTS flow control

ArduCopter/Copter.h, ArduCopter/config.h, ArduCopter/sensors.cpp, ArduCopter/surface_tracking.cpp, ArduCopter/wscript, libraries/AP_SurfaceDistance/AP_SurfaceDistance.cpp, libraries/AP_SurfaceDistance/AP_SurfaceDistance.h
Following on from the discussion in this PR: https://github.com/ArduPilot/ardupilot/pull/26827, it was agreed that the best way forward was to move the copter rangefinder functionality into a library (we called it AP_HAGL then).  This PR is the start of that process.
**No functional change should result from this PR**
As his way, @IamPete1 already had a branch for it! https://github.com/ArduPilot/ardupilot/pull/20535
I have rebased his original PR to get this.  I will continue the work and do the testing.
=> Start Surface Distance Library

Tools/ardupilotwaf/boards.py, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
This moves the rough processing that boards.py does into `chibios_hwdef.py`.
I've added a comment noting some of the warts with the implementation, but generally left it alone.  There's a trade-off between speed and correctness, and speed needs to win here or `./waf configure CubeOrange` takes an extra 2 seconds to run!  At least this centralises the hwdef parsing.
I've corrected the code to recursive rather than just handle a single level of includes.
Output from `./waf list_ap_periph_boards | xargs -n1 | sort` is unchanged this vs master.
=> waf: boards.py: use chibios_hwdef.py to get boards list

libraries/AP_DroneCAN/AP_DroneCAN_serial.cpp
This allows the short hand baud rates to work. EG "57" for 57600. The param descriptions suggest they should work already because they just copy from the main serial port descriptions.
=> AP_DroneCAN: Serial: map baudrates so param works as expected

Tools/autotest/autotest.py
this is unused
... should we make it used?  Why?  The tests aren't written for different frame dynamics.
=> autotest.py: remove unused frame parameter

libraries/AP_Scripting/applets/pelco_d_antennatracker.lua, libraries/AP_Scripting/applets/pelco_d_antennatracker.md
This script uses the scaled output from the antennatracker servos and map them to corresponding Pelco-D messages to be sent via a RS-485 interface to a motorized base (can be anything from motorized tracker to a PTZ camera). If your FCU doesnt offer a RS-485 interface by default, you can use or TTL-RS485- or USB-RS485-adapters. I tested this script using a USB-RS485 adapter using Linux/Obal board and a Hikvision PTZ camera.
=> AP_Scripting: added tracker Pelco-D control script

libraries/AP_Scripting/lua/src/ldo.c
backport of this critical PR:
https://github.com/ArduPilot/ardupilot/pull/27056
=> Scripting: backport of pcall fault fix for 4.4.x

libraries/AP_Scripting/lua/src/ldo.c
backport of this critical PR:
https://github.com/ArduPilot/ardupilot/pull/27056
=> Scripting: backport of pcall fault fix for 4.3.x

libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp, libraries/AP_RCTelemetry/AP_CRSF_Telem.h, libraries/AP_VideoTX/AP_SmartAudio.cpp, libraries/AP_VideoTX/AP_Tramp.cpp, libraries/AP_VideoTX/AP_Tramp.h, libraries/AP_VideoTX/AP_VideoTX.cpp, libraries/AP_VideoTX/AP_VideoTX.h
This fixes a bug whereby it was impossible to select the highest power level when using Tramp because the CRSF provider would immediately reset it.
It also fixes a bug where Tramp was unreliable due to temperature fluctuations and implements the same autobauding scheme that SmartAudio uses.
Tramp lies about power levels and always takes fixed input of 25/100/200/400/600 even though the output may be very different.
=> Support all Tramp Power Levels

libraries/AP_Networking/config/lwipopts.h
Broadcast support has been broken in LwIP because we never enabled Socket Reuse. Enabling SO_REUSE will enable SO_REUSEADDR.
This change allows us to use UDP Client/Server broadcast IP of 255.255.255.255 on ChibiOS/LwIP systems. It's already enabled on Linux/SITL systems. I don't know about Cygwin.
4.5.3 and on master:
- Correctly defined in the bootloader [here](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL_ChibiOS/hwdef/scripts/defaults_bootloader.h#L47)
- Not defined in the app's AP_Networking/config/lwipopts.h so the lwip default in opts.h sets it to zero [here](https://github.com/ArduPilot/lwip/blob/143a6a5cb8023921b5dced55c30551ffb752b640/src/include/lwip/opt.h#L2112-L2117)
I would consider this a candidate for a 4.5.x backport but not important enough to cause …
=> AP_Networking: enable Socket SO_REUSEADDR on LwIP

libraries/AC_AutoTune/AC_AutoTune.cpp, libraries/AC_AutoTune/AC_AutoTune.h, libraries/AC_AutoTune/AC_AutoTune_Heli.cpp, libraries/AC_AutoTune/AC_AutoTune_Heli.h, libraries/AC_AutoTune/AC_AutoTune_Multi.cpp, libraries/AC_AutoTune/AC_AutoTune_Multi.h
This PR attempts to address some of the long term concerns with AutoTune.
1. Autotune now fails when it becomes clear the aircraft will probably fail to tune well.
2. The recovery from the rate twitch makes use of the control model to reduce the severity of the ESC command. This should dramatically reduce the chance of desync.
3. The waiting for level criteria has been adjusted to reduce the chance initial conditions cause problems with the tests.
4. The practice of sipping a side in an attempt to save time has been removed as it causes aircraft velocity to build. I believe removing this is a net gain in both time and reliability.
5. Base test angles on ratio's of ANGLE_MAX.
These changes are expected to dramatically reduce crashes due to desync and successful autotune with bad/dangerous …
=> Copter: Autotune performance and safety enhancements

Tools/autotest/vehicle_test_suite.py, libraries/SITL/SIM_GPS_SBP.cpp
Somehow we lost this aspect of autotest where a non-zero valgrind log means failiure.
Fix that.
I've tested the failure case here and CI hsould cover the no-failure case.
=> autotest: correct Valgrind error detection 

Tools/autotest/param_metadata/jsonemit.py
`__field_text` is basically the raw parsed text, and is used internally but as far as I can tell it was never meant for external usage, the JSON emitter already removes other fields that were not intended to be there. By including the `__field_text` entry we were doubling the size of the emitted documentation.
As a sample this is the old output:
``` json
"ADSB_EMIT_TYPE": {    
"Description": "ADSB classification for the type of vehicle emitting the transponder signal. Default value is 14 (UAV).",    
"DisplayName": "Emitter type",    
"User": "Advanced",    
"Values": {    
"0": "NoInfo",    
"1": "Light",    
"10": "LightAir",    
"11": "Parachute",    
"12": "UltraLight",    
"13": "RESERVED",    
"14": "UAV",    
"15": "Space",    
"16": "RESERVED",    
"17": "EmergencySurface", …
```
=> Tools: Do not emit __field_text in JSON parameter documentation

libraries/AP_HAL_ChibiOS/hwdef/FlywooF405HD-AIOv2/hwdef-bl.dat
my mistake....the internal module's RX pin needs to be high during boot to prevent the ELRS module from going into a special mode....I suggested the wrong pin during the review as we moved things around...
=> AP_HAL_ChibiOS:correct pin to be pulled high during boot

libraries/Filter/tests/plot_harmonictest5.gnu, libraries/Filter/tests/test_notchfilter.cpp
this was for a single notch set at 60Hz with bandwidth of 60Hz. Source frequency was 50Hz, and the test frequency varies for the 5 graphs from 10Hz to 50Hz.
=> Filter: added test of phase lag vs attenuation

libraries/SITL/SIM_Plane.cpp, libraries/SITL/SIM_Plane.h
needs to be updated with improved yaw rate calculation
need to set SERVO5_FUNCTION = 26
and launch with sim_vehicle.py -f plane-steering
=> SITL: added plane-steering model for ground steering

libraries/AP_HAL_SITL/SITL_cmdline.cpp
needed for MissionPlanner SITL
see https://github.com/ArduPilot/MissionPlanner/pull/3359
we will need this till a new stable release of MissionPlanner is done
broken by this PR: https://github.com/ArduPilot/ardupilot/pull/26156
=> SITL: added --uartA alias for SITL

libraries/AP_GPS/AP_GPS_MAV.cpp
according to mavlink specification, GPS_MAV should check "gps_id" field before handle incoming GPS_INPUT or HIL_GPS message for correct multiply GPS support via mavlink.
=> add checking of instance number before update with incoming data

libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp
We use the vtx singleton in here, so we need the header.
... also fix up the includes and ifdefs a little.
=> AP_CRSF_Telem: add missing VideoTX include

libraries/SITL/SIM_GPS_SBP2.cpp
Make it the same process as commit hash b2b8eb93 .
=> SITL: correct valgrind failure in SIM_GPS_SBP2

Tools/scripts/run_lua_language_check.py, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/tests/check.json, libraries/AP_Scripting/tests/docs_check.py, libraries/AP_Scripting/tests/luacheck.lua
A number of fixes:
- luacheck ignores the new lua-language-sever lua code that is downloaded when you first run the new checks (the code does not pass the checks configured for the AP environment)
- lua-language checks can now be run on a single file. The file is copied to a new temporary directory the checks run and the directory is then deleted. 
- lua-language checks stop using gitignore so they will check scripts your working on in the SITL `scripts` dir.
- lua-language checks report the number of files it has tested and errors out if the number is 0 or not known.
- the docs document the logger write function both with and without units and multipliers so the checks will now pass in both cases.
=> AP_Scripting: checks fixes and improvements 

ArduCopter/config.h, ArduPlane/config.h, Rover/config.h
we do this in AP_OSD_config.h too so include ordering can break things badly
=> remove defaulting of OSD_ENABLED

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/tests/docs_check.py
This adds a `Parameter_ud_const` class to the docs which does not exist in the code. This is used to tell the lua language server checks that we don't need to check for nil on a parameter created with a name: `Parameter("SCR_ENABLE")`. The old method of `p = Parameter(); p:init("SCR_ENABLE")` will still need to check nil.
Test script:
```
local p = Parameter("SCR_ENABLE")
p:set(p:get())
local p2 = Parameter()
p2:init("SCR_ENABLE")
p2:set(p2:get())
```
On master we get warnings for both:
```
/home/peter/ardupilot/scripts/param_test.lua:3:7
Code: param-type-mismatch
Cannot assign `number|nil` to parameter `number`.
- `nil` cannot match `number`
- Type `nil` cannot match `number`
/home/peter/ardupilot/scripts/param_test.lua:7:7
Code: param-type-mismatch
Cannot assign `number|nil` to …
```
=> AP_Scripting: add virtual class in docs to avoid need nil check warning in lua language check

libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
highres sampling is not working on the ICM42670 on some versions of the Pixhawk6X. Disable for now.
without this change the 3rd IMU gets no data
=> AP_InertialSensor: fixed ICM42670

libraries/AP_Scripting/docs/docs.lua
This is confusing the `.md` to `.rst` converter.
=> AP_Scripting: Docs: remove stray grave

libraries/AP_Scripting/drivers/EFI_Halo6000.lua, libraries/AP_Scripting/drivers/EFI_Halo6000.md
=> AP_Scription: added CANF logging to Halo6000 EFI driver

Tools/autotest/arducopter.py
We weren't passing in a valid relative altitude.
This was a problem as the AP_Follow library was actually consuming that value....
I've also in-lined the function into its sole caller to avoid getting the message all the time.
Extracted from https://github.com/ArduPilot/ardupilot/pull/27250
This work sponsored by Freespace Operations
=> autotest: ModeFollow: correct relative altitude being fed to autopilot

Tools/autotest/arducopter.py
Just makes the test take a shorter amount of time
Extracted from https://github.com/ArduPilot/ardupilot/pull/27250
This work sponsored by Freespace Operations
=> autotest: revert SIM_SPEEDUP for RTL in follow test

Tools/autotest/arducopter.py, Tools/autotest/vehicle_test_suite.py
Just cleans things up a little to have less parameter fetching.
Also clears up a mis-understanding in the test about the way reported parameter gains work in autotune once tuning is complete.
=> autotest: clarify AutoTuneSwitch test

libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
Currently, we do not constrain cyclic output for roll on intermeshing/coax configs.
This PR fixes it.
=> Heli dual: Constrain cyclic roll for intermeshing

libraries/AP_Motors/AP_MotorsHeli_Swash.cpp
I didn't account for reversed collective directions correctly in my original PR that added swash plate angle logging: https://github.com/ArduPilot/ardupilot/pull/26606
Plot below shows the issue.  This aircraft has two reversed collectives and the collective angle range has come out reversed:
This fix up resolves the issue by storing the collective value before we apply the collective reversal for the control outputs.
=> AP_Motors: Heli: Fix SWSH logging for reversed collectives

libraries/AP_HAL_SITL/HAL_SITL_Class.cpp, libraries/AP_HAL_SITL/HAL_SITL_Class.h, libraries/AP_HAL_SITL/SITL_State.cpp, libraries/AP_HAL_SITL/SITL_State_common.h, libraries/SITL/SIM_Aircraft.cpp
SITL pauses the simulation if we do not have a minimum amount of space in its out queue.
Log the number of times we do this.
Fora run of the AutoTuneSwitch test:
...shows we drop a packet at the start before we bring up the mavlink connection from autotest.  I think.  `SIM_SPEEDUP` was the default 100.
I've also tested ctrl-z on the terminal running autotest, and the sim starts complaining a lot:
=> SITL: log number of times sim paused on serial0 buffer

libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/README.md
Updated the readme for the RADIX2HD target with better instruction for how to obtain or create firmware files.
Also changed SERIAL4 to ESC telemetry, as this is now the default.
=> AP_HAL_ChibiOS: Update readme for RADIX2HD

Rover/Log.cpp, Rover/mode.cpp, Rover/mode_acro.cpp, Rover/mode_auto.cpp, Rover/mode_circle.cpp, Rover/mode_guided.cpp, Rover/mode_loiter.cpp
Common variables G and G2 are used.
G and G2 are used directly.
Mixed in the same file.
I think it would be better to unify common variables.
=> Rover: Use common variables

ArduCopter/mode_guided.cpp
This process will never be executed, so I will enable it. 
I believe that processes that are never executed are unnecessary.
=> Copter: Enable processing

libraries/AP_HAL/UARTDriver.cpp, libraries/AP_HAL/UARTDriver.h, libraries/AP_HAL_ChibiOS/UARTDriver.cpp, libraries/AP_HAL_ChibiOS/UARTDriver.h, libraries/AP_HAL_ChibiOS/hwdef/common/usbcfg.c, libraries/AP_HAL_ChibiOS/hwdef/common/usbcfg.h, libraries/AP_HAL_ChibiOS/hwdef/common/usbcfg_dualcdc.c, libraries/AP_HAL_Linux/UARTDriver.cpp, libraries/AP_HAL_SITL/UARTDriver.h, libraries/AP_HAL_SITL/UART_utils.cpp, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
Add code to reflect USB ACM parity setting to the passthrough port alongside existing support for ACM baud rate changes.  Some use cases for serial passthrough require specific parity settings.
For example, even parity is used and required by the USART protocol used in the STM32 system bootloader. This enhancement allows the use of standard flash programming tools such as STM32CubeProgrammer to flash connected STM based peripherals such as Receivers and Telemetry radios via serial passthrough.  Some examples of such peripherals include the FrSky R9 receivers as well as various other STM based LoRa modules used by the mLRS project.
=> GCS_MAVLink: Add support for parity to Serial passthrough

Tools/autotest/vehicle_test_suite.py, libraries/SITL/SIM_GPS_SBP2.cpp
I have no idea if this is actually the sort of number which these devices will return.
However, for the EKF to be happy with the GPS the reported speed accuracy must be much lower than the SBP2 driver reports when we give it these numbers.
It might be that we are interpretting these fields incorrectly in the driver and that the simulator is, in fact, correct.
=> SITL: make simulated SBP2 vastly more accurate

Tools/ardupilotwaf/boards.py, Tools/autotest/arducopter.py, Tools/autotest/autotest.py, libraries/AP_BattMonitor/AP_BattMonitor.cpp, libraries/AP_BattMonitor/AP_BattMonitor.h, libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.cpp, libraries/GCS_MAVLink/GCS_Common.cpp
```
./Tools/autotest/autotest.py --gdb --debug build.SITLPeriphBattMon build.Copter test.BattCAN
```
Casting a backend to the wrong pointer type and then dereferencing  it is unlikely to end well.  We were doing that in at least two places.
No reason this can't be bad in flight, but the operator is probably insane manipulating these parameters in-flight.
=> AP_BattMonitor: prevent memory corruption when manipulating DroneCAN backends

Tools/autotest/arducopter.py, libraries/GCS_MAVLink/GCS_config.h
Also add lifetime hint comments so we remove these in 4.7
=> GCS_MAVLink: remove MOUNT_CONFIGURE/MOUNT_CONTROL handling by default 

libraries/AP_NavEKF/EKFGSF_yaw.cpp
```
f103-QiotekPeriph        *                                                                     
f303-Universal           *                                                                     
iomcu …
```
=> AP_NavEKF: tidy creation of vectors

libraries/AC_Fence/AC_Fence_config.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_config.h
Send mavlink warning if old FENCE_POINT / RALLY_POINT protocols are used.
MAVProxy stopped using these protocols roughly a year ago, MissionPlanner and QGC years before that.
```
STABILIZE> message fence_fetch_point AP: EKF3 IMU1 origin set
AP: Field Elevation Set: 584m
1 AP: EKF3 IMU0 origin set
1 6
STABILIZE> AP: Received message (FENCE_FETCH_POINT) is deprecated
```
=>  AC_Fence: warn on use of old fence point / rally point protocols 

libraries/AP_Follow/AP_Follow.cpp
odd sort of a transform, make it clear what's happening
Tested in SITL using this:
```
--- a/libraries/AP_Follow/AP_Follow.cpp
+++ b/libraries/AP_Follow/AP_Follow.cpp
@@ -495,6 +495,15 @@ Vector3f AP_Follow::rotate_vector(const Vector3f &vec, float angle_deg) const
Vector3f ret = vec;
ret.xy().rotate(radians(angle_deg));
+    const float cos_yaw = cosf(radians(angle_deg));
+    const float sin_yaw = sinf(radians(angle_deg));
+    Vector3f old_ret = Vector3f((vec.x * cos_yaw) - (vec.y * sin_yaw), (vec.y * cos_yaw) + (vec.x * sin_yaw), vec.z);
+    const float delta = (ret - old_ret).length();
+    gcs().send_text(MAV_SEVERITY_INFO, "ang=%f %f/%f/%f delta: %f", angle_deg, ret.x, ret.y, ret.z, delta);
+    if (delta > 0.0001) {
+        abort();
+    }
+
return ret;
}
```
=> AP_Follow: clarify what we're doing when rotating a vector

libraries/AP_Common/Location.cpp, libraries/AP_Common/Location.h, libraries/AP_Common/tests/test_location.cpp
this change means that if the origin call failes we don't half-update the object before returning false
Extracted from https://github.com/ArduPilot/ardupilot/pull/27250
This work sponsored by Freespace Operations
=> AP_Common: rearrange get_vector_from_origin_NEU to be less destructive

Tools/ardupilotwaf/boards.py
This allows users to set an environment variable (AP_NO_COMPILE_COMMANDS) to stop the build system from adding the compile commands to their c_cpp_properties.json file.
This is useful for testing - say if I'm switching between sitl and a real board and I don't want VS code's Intellisense to keep being switched around between the two, or if one wants the Intellisense to be for a specific board even when one is compiling other boards (i.e. you could set it for a specific board's compile_commands.json and have it not be changed when you compile other boards). Also, because the build system sets the file when it starts compiling but when the file was being generated, it would only be generated at the end, it means that if you do a ./waf clean then the Intellisense would be broken until the …
=> Tools: Added option to set environment variable to not add the compile_commands.json to VSCode's c_cpp_properties.json

libraries/AP_Common/Location.cpp, libraries/AP_Common/Location.h, libraries/AP_HAL/AP_HAL_Boards.h, libraries/AP_Math/control.h
Extracted from https://github.com/ArduPilot/ardupilot/pull/27250
This allows a vehicle using double-precision position offsets to get that increased precision object from a Location.
I've used a template here as the maths is identical, just the types different.  Since we don't instantiate the second type at the moment there's no flash cost.
This is also built on top of https://github.com/ArduPilot/ardupilot/pull/27253 which fixes the methods up a bit.
```
Durandal                            0      *           0       0                 0      0      0
Hitec-Airspeed           * …
```
=> AP_Common: Location: allow retrieval of Vector3p from vector-from-origin

AntennaTracker/ReleaseNotes.txt, AntennaTracker/version.h, ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, ArduPlane/ReleaseNotes.txt, ArduPlane/version.h, Rover/ReleaseNotes.txt, Rover/version.h, libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
This moves copter, rover, plane and tracker to 4.5.4. The only change from 4.5.3 is the inclusion of https://github.com/ArduPilot/ardupilot/pull/27264.
Note that this is not a beta.
=> Copter, Rover, Plane, Tracker: 4.5.4 release

ArduCopter/mode_circle.cpp
I believe it's better to perform processing where it's needed. 
I will move the processing to the necessary location. 
This change should reduce unnecessary access.
=> Copter: Move to the processing section to be used

Rover/Parameters.h, Rover/mode.h, Rover/mode_auto.cpp, Rover/system.cpp
I can't help but wonder why we don't support `MAV_CMD_DO_CHANGE_MODE` as a mission item.  All of these options could be done with one of those.
Testing is limited to a quick spin in SITL and checking that the `EndMissionBehaviour` autotest output seems to cover the cases.
=> Rover: use enum-class for mission-done behaviours

libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_config.h, libraries/GCS_MAVLink/ap_message.h
Duplicates #24258 
It allows a companion computer to query the flightcontrollers IMU for navigation and control.
This PR implements all fields for the [HIGHRES_IMU](https://mavlink.io/en/messages/common.html#HIGHRES_IMU) Mavlink message.
=> GCS_MAVLink: support HIGHRES_IMU

ArduCopter/RC_Channel.cpp, ArduPlane/RC_Channel.cpp, Blimp/RC_Channel.cpp, Rover/RC_Channel.cpp, libraries/AP_Vehicle/ModeReason.h
Aux function are no longer only from RC. This changes to use a dedicated mode reason.
We don't check for the old `ModeReason::RC_COMMAND` anywhere in the main code. Nor is it exposed over MAVLink. There is a scripting binding, and it is used in logging.
The scripting binding is `vehicle:get_control_mode_reason()`, it is not used by any of our examples.
=> Add and use new ModeReason::AUX_FUNCTION
