ArduPilot/ardupilot

libraries/AP_Logger/AP_Logger_Block.cpp

The current block logger can generate logs that have significant holes. It turns out this is due to the very short time it waits to acquire the write buffer lock before giving up. The file logger blocks and the block logger should do the same. Tested on my Marmotte 5

AP_Logger: take a blocking semaphore when writing messages using the block logger

---

libraries/AP_Arming/AP_Arming.cpp
libraries/AP_Param/AP_Param.cpp
libraries/AP_Param/AP_Param.h

this allows users to know if their params won't persist, which is dangerous for a common
preflight reboot

Param: added arming check for eeprom full

---

libraries/AP_Scripting/docs/docs.lua
libraries/AP_Scripting/generator/description/bindings.desc
libraries/AP_Scripting/generator/src/main.c
libraries/AP_Scripting/lua_bindings.cpp
libraries/AP_Scripting/lua_boxed_numerics.cpp
libraries/AP_Scripting/lua_boxed_numerics.h
libraries/AP_Scripting/tests/scripting_test.lua

This adds a new userdata for uint64 much like the existing one for uint32. This makes big numbers much easier. A small section is added to the test script to make sure there doing the correct thing. There is also support for logging the new type.
Currently you could use it is a argument for a binding, but it would be better to do some more work so that it can be "coerced" so you could pass a normal lua number if you wanted to. We don't have many functions that take a uint64 argument, so I have not added that (it will still work, you just have to be sure to pass the correct type).
This adds a binding to get unix epoc from gps which needs the uint64 type. In the future we might want to add support for `micros64` too.
I have also moved the uint32 operators to automatically generated bindings …

AP_Scripting: add `uint64_t` userdata and auto generate `uint32_t` operators.

---

ArduCopter/GCS_Mavlink.cpp

this change add a step in the booting process to let know a companion computer if the autopilot has rebooted

ArduCopter: get MAV_STATE_BOOT on reboot

---

libraries/SITL/SIM_EFI_Hirth.cpp

we weren't sending an ACK for the set-values message

SITL: correct and improve Hirth simulator

---

libraries/AP_Logger/LoggerMessageWriter.cpp
libraries/AP_Logger/LoggerMessageWriter.h

... use the fact these all have a common base class to reduce effectively duplicate code.
Also un-virtualise and const a function which wasn't overridden and can be const
Tested in SITL by creating fence, mission and rally and ensuring they still get to the log.
```
CubeOrange-periph-heavy  16                                                                    
Durandal                            -64    *           -64     -64               -64    -64    -64
KakuteH7-bdshot                     -88    *           -88     -88               -96    -88    -96
MatekF405                           -96 …
```

AP_Logger: tidy running of LoggerMessageWriter sub-writers

---

ArduPlane/Log.cpp
libraries/AP_Compass/AP_Compass_DroneCAN.cpp
libraries/AP_GPS/LogStructure.h

This PR contains 3 minor updates to log message help.
(Note I did a seperate commit per library, but have not done 3 seperate PRs, as I was thinking it was all one topic and small enough, but happy to do differently if I should).
1. I noticed that the ordering of the fields on the CTUN message help differs from the actual order of the fields.
This ends up causing the units to be mis-attributed, so that the wiki says that AsT (airspeed type) is in m/s, but this should instead be shown against SAs (DCM’s airspeed estimate).
Probably the parser could be smarter to cope with this, or an autotest check could check that fields match the real order, but I thought this may not be worth the time/effort.
2. When testing this change with logger_metadata/parse.py, I checked that CTUN was corrected, …

ArduPlane: Minor log message help text updates

---

libraries/AP_ADSB/AP_ADSB_Sagetech_MXS.cpp
libraries/AP_ADSB/AP_ADSB_Sagetech_MXS.h

stops the vehicle flipping around as speed goes to/comes from 0

AP_ADSB: cache course-over-ground for GPS message

---

ArduPlane/quadplane.cpp

This PR adds the missing help text for the QPOS log message in quadplane.cpp.
I have checked the generated output files (xml, rst, etc) after running Tools/autotest/logger_metadata/parse.py, and the output looks correctly parsed, including enum values for QPOS_xxx states.

ArduPlane: Add help text for QPOS log message

---

Tools/autotest/vehicle_test_suite.py
libraries/AP_Math/definitions.h
libraries/AP_TECS/AP_TECS.cpp
libraries/SITL/SITL.cpp

This PR is two small legibility improvements in TECS.cpp
It also adds small typo fixes I did while reading TECS.cpp.

Legibility changes

---

Tools/AP_Bootloader/board_types.txt

Adding initial ID's and small reservation block for HAKRC flight controllers.

board-types.txt: Hakrc initial IDs and reservation 

---

libraries/AP_Baro/AP_Baro.cpp

I am grouping BMP device headers. 
I believe grouping them will make it easier to understand supported devices.

AP_Baro: Group device headers

---

libraries/AP_Mount/AP_Mount_Alexmos.cpp
libraries/AP_Mount/AP_Mount_Alexmos.h

Noticed this issue when helping someone out.  We are using integer math when calculating the angle in degrees from the provided value.  This minor rework helps to maintaining a little more accuracy so that we don't round to integer degrees.
I have also done a little tidying by moving the defines to the .cpp.

AP_Mount: Alexmos: increase precision on parsed angle

---

Rover/GCS_Rover.cpp
Tools/autotest/rover.py

identical code in the parent class

Rover: remove redundant setting of optical flow bits

---

ArduSub/GCS_Mavlink.cpp

PR to get MAV_STATE_BOOT on reboot on Sub in a different PR as asked in PR #27289

ArduSub:  get MAV_STATE_BOOT on reboot

---

Tools/AP_Periph/Web/scripts/pppgw_webui.lua
libraries/AP_HAL/utility/Socket.cpp
libraries/AP_HAL/utility/Socket.hpp
libraries/AP_HAL/utility/packetise.cpp
libraries/AP_HAL/utility/packetise.h
libraries/AP_Networking/AP_Networking.h
libraries/AP_Networking/AP_Networking_port.cpp

Tested on a variant of CubePilot CANMod. The issue was that we were using connected UDP Server socket. Meaning once we connect to an application, then we shutdown that application and then restart the application the listen port on the application can change. But the UDP Server will be stuck with old IP:Port and will not even listen to the new application.
This PR moves to using sendto command with IP:Port from last received packet.
This is the case for example with Mavproxy, or any other client where the data is sent without binding to specific port.

Allow multiple UDP clients to connect/disconnect/reconnect

---

libraries/AP_Beacon/AP_Beacon.cpp
libraries/AP_Beacon/AP_Beacon.h

Relying on autotests to make sure this works.
zero-byte-change on CubeOrange/ArduCopter.

AP_Beacon: use enum class for type

---

libraries/AP_Scripting/lua_bindings.cpp

Currently you cant just log a bool, it must be a integer value to use `B` (uint8_t) format. This now allows bools.
EG this currently you have to do this:
```
local bool = true
logger:write('BOOL', 'boolean', 'B', bool and 1 or 0)
```
With this PR it you can just use the bool:
```
local bool = true
logger:write('BOOL', 'boolean', 'B', bool)
```

AP_Scripting: allow logging lua boolean with uint8 format `B`

---

Tools/autotest/arduplane.py
libraries/AP_Scripting/lua_scripts.cpp

... I think a restructure may not be a bad option here....
Before the patch is applied the autotest reproduces the valgrind problem if you run it like this:
`./Tools/autotest/autotest.py build.Plane --valgrind test.Plane.ScriptStats`
No Valgrind problem after the patch.
OTOH, `math.lua` doesn't seem to work any more - before *or* after this patch.
```
AT-0031.7: AP: Lua: ./scripts/math.lua exceeded time limit
```
... in fact, that's why we're getting the Valgrind problem, the removal of that script due to it running overtime.  So if we fix `math.lua` we might need a `run_overtime.lua` to make sure we cross the relevant path in our lua script handling.
Implications here.... well, you're limited to reading memory with random contents, but AFAICS that memory pointer will always be valid.  A …

AP_Scripting: correct use-after-free in script statistics

---

libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp
libraries/AP_NavEKF3/AP_NavEKF3_VehicleStatus.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.h

Fix several EK3_MAG_CAL cases for sub by flipping signs:
* EK3_MAG_CAL,3 (AFTER_FIRST_CLIMB): look for -2.5m altitude change (vs +2.5m)
* EK3_MAG_CAL,0 (WHEN_FLYING): look for -1.5m altitude change (vs +1.5m) or -0.5m rangefinder change (vs +0.5)
This might help a little with https://github.com/ArduPilot/ardupilot/issues/18229.
[I edited this comment to match the latest code, and deleted older comments.]

Sub: fix several EK3_MAG_Fusion cases for Sub

---

ArduCopter/GCS_Mavlink.cpp
ArduCopter/mode_guided.cpp
libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
libraries/AC_AttitudeControl/AC_AttitudeControl.h
libraries/AC_AttitudeControl/AC_AttitudeControl_Multi_6DoF.cpp
libraries/AC_AttitudeControl/AC_AttitudeControl_Multi_6DoF.h

This PR fixes a problem where the angular rate inputs to MAVLINK_MSG_ID_SET_ATTITUDE_TARGET were not in the body frame if both attitude and rate are specified. It also checks to make sure each of the three rotation rate axis are specified.
This fixes the bug where when only rates are specified they are in body frame but when using quaternion attitude and rates the rates were in earth frame.
The message clearly specifies the rates are in body frame.

Correct MAVLINK_MSG_ID_SET_ATTITUDE_TARGET anglular rate input frame

---

libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
libraries/AP_ESC_Telem/AP_ESC_Telem.h
libraries/AP_OSD/AP_OSD.h
libraries/AP_OSD/AP_OSD_Screen.cpp
libraries/AP_RCTelemetry/AP_Spektrum_Telem.cpp

Currently the OSD displays ESC 0 only. This attempts to show the most relevant information

Use active ESC when only one can be displayed

---

libraries/AP_GPS/AP_GPS_UBLOX.cpp

If using 32 bit time for PPS interrupt the corrected time can be set incorrectly after 2^32 microsecond, and cause ublox redetection code to run again and result in Ublox module to drop out after around 1hour and 12 minutes.

Use 64 bit time for PPS interrupt in Ublox driver

---

libraries/AP_Mount/AP_Mount_Siyi.cpp
libraries/AP_Mount/AP_Mount_Siyi.h

This adds support for the new [Siyi ZT6 RGB+Thermal camera](https://en.siyi.biz/products/siyi-zt6).
This resolves issue https://github.com/ArduPilot/ardupilot/issues/27060
This is in response to this discussion https://discuss.ardupilot.org/t/gimbal-zoom-type-issue/117708

AP_Mount: add Siyi ZT6 support

---

libraries/AP_Notify/RGBLed.cpp
libraries/AP_Notify/RGBLed.h

Your Copter in stabilize mode can flash rapid-green indicating a good DGPS lock or better, and yet your vehicle still doesn't have a good idea of where it is.
That means that your vehicle may end up RTL'ing onto a point somewhere along your flight path, when you were given an all-green indication by teh vehicle before you armed in stabilize.
Past this PR, we require the same GPS as before, but in addition we must have been happy enough with our location to set the navigation origin, *and* currently be able to get a location.
A user will receive slow-flashing blue lights if they can't currently get a location, or the navigation origin isn't set, even if they've got a "good" fix.
We also require a good location to get a solid green light - you will get a solid blue light if you can't get a …

AP_Notify: flash green lights based off location not GPS

---

libraries/AP_Scripting/examples/sitl_standby_sim.lua

Add an example of standby usage on SITL with a LUA scripting to do the switching of motor control
Will make a blog post and wiki entry about this

AP_Scripting: add an example to use Copter Standby mode in SITL with LUA

---

libraries/AC_AutoTune/AC_AutoTune.h
libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
libraries/AC_AutoTune/AC_AutoTune_Multi.h

https://github.com/ArduPilot/ardupilot/pull/27370/files

AC_AutoTune: More extracted autotune cleanups from larger cleanup

---

README.md

@Williangalvani [fits the description](https://github.com/ArduPilot/ardupilot/pulls?q=is%3Apr+is%3Aclosed+Navigator):
> ... people that regularly contribute to the project and are responsible for reviewing patches on their specific area
so nice to give some attribution :-)

README: add Navigator maintainer attribution

---

Tools/autotest/vehicle_test_suite.py

Adds a more detailed error string on failure:
```
AT-0004.8: want=831 got=167 errors=128
AT-0004.8: want=831 got=167 errors=128
AT-0004.9: want=831 got=167 errors=128
AT-0004.9: want=ATTITUDE|VELOCITY_HORIZ|VELOCITY_VERT|POS_HORIZ_REL|POS_HORIZ_ABS|POS_VERT_ABS|PRED_POS_HORIZ_REL|PRED_POS_HORIZ_ABS missing=POS_HORIZ_REL|POS_HORIZ_ABS|PRED_POS_HORIZ_REL|PRED_POS_HORIZ_ABS errors=CONST_POS_MODE
```

autotest: make WaitAndMaintainEKFFlags progress nicer

---

Rover/Rover.cpp
Rover/Rover.h

Rover had a `stats_update` function, but its not called from anywhere. Rather than keeping the function this moves the one line that was in it to the 1Hz loop.

Rover: call stats set_flying from 1Hz loop

---

Blimp/GCS_Mavlink.cpp

PR to get MAV_STATE_BOOT on reboot on Blimp in a different PR as asked in PR #27289

Blimp:  get MAV_STATE_BOOT on reboot

---

ArduSub/Sub.h

Found this while looking through the code [for this](https://github.com/ArduPilot/ardupilot/issues/19103#issuecomment-2195818938) - seems like the failsafes list didn't get updated in this function definition.
Rover uses a bitmask for the failsafes (instead of separate variables), which seems like a better approach, but this is at least an improvement for now.
@Williangalvani

Sub: update status to include all failsafes

---

ArduSub/ArduSub.cpp
ArduSub/motors.cpp

it turns out that sub was missing this, which meant that there were two code paths able to change pwm, which harmed cpu usage and made the fifty_hz_loop() take longer than it should. 
I also moved calc_pwm from the fifty_hz loop down to motors_output, which despite causing us to calculate the servos more often, improves things as we no longer write to rcout on that task

Sub: use cork() when writing motors,  move servo updates to motors_output()

---

libraries/AP_NavEKF2/AP_NavEKF2.h

```
pbarker@fx:~/rc/ardupilot(pr/remove-unused-initfailurereason)$ git grep initFailureReason
pbarker@fx:~/rc/ardupilot(pr/remove-unused-initfailurereason)$ 
```

AP_NavEKF2: remove unused initFailureReason

---

libraries/AP_TemperatureSensor/AP_TemperatureSensor_Analog.cpp

NFC....expands metadata which tends to imply only the values listed work

AP_Temperature:expand metadata for analog sensors

---

libraries/AP_Scripting/docs/docs.lua
libraries/AP_Scripting/examples/command_int.lua
libraries/AP_Scripting/generator/description/bindings.desc
libraries/AP_Scripting/lua_bindings.cpp
libraries/AP_Scripting/lua_bindings.h
libraries/GCS_MAVLink/GCS.cpp
libraries/GCS_MAVLink/GCS.h

This makes it possible to call most MAV_CMD_xxx calls from lua scripts, gaining us a lot of functionality with a small amount of flash
This was prompted by #27223 and the MAV_CMD_GUIDED_xxx commands, but is really very broadly useful
some questions:
- should we return the full MAV_RESULT enum? Is it useful?
- should we create a dedicated GCS_MAVLink channel for lua?
this also adds an example that tests DO_SET_MODE and DO_REPOSITION

Scripting: added command_int API for accessing MAV_CMD_xxx

---

Rover/failsafe.cpp
Rover/fence.cpp

I am not sure if there's an underlying reason for these to be set to BATTERY_FAILSAFE of it it was a mistake.
If it was on purpose, we should at least add a comment explaining what is going on.

Rover: fix ModeReason on fence breaches

---

libraries/AP_BattMonitor/AP_BattMonitor.cpp
libraries/AP_BattMonitor/AP_BattMonitor.h
libraries/AP_BattMonitor/AP_BattMonitor_Backend.cpp

Currently if your battery monitor goes away the only way to tell is a bit in sys status. This is quite easy to miss. This now results in a full battery failsafe with no action. We might want to consider adding a parameter in the future. This uses a 5 second timeout.
This becomes more likely with CAN battery monitors which are often powered from the battery itself, so if the battery fails the node also disappears rather than telling us that the battery is gone. 
Example:

AP_BatteryMonitor: add missing failsafe with no action

---

Tools/autotest/arduplane.py
libraries/AP_Arming/AP_Arming.cpp
libraries/AP_GPS/AP_GPS.cpp
libraries/AP_GPS/AP_GPS.h
libraries/AP_GPS/AP_GPS_DroneCAN.cpp
libraries/AP_GPS/AP_GPS_DroneCAN.h

Will allow backends to have their own pre-arm checks.
Rename pre-arm checks to be consistent with our libraries.  Note that the pre-arm check doesn't actually check the backends are healthy, despite the previous name...

Tidy GPS pre-arm checks

---

libraries/AP_Generator/AP_Generator_IE_FuelCell.cpp

AP_Generator: avoid use of int16_t-read

---

libraries/AP_GPS/AP_GPS_UBLOX.cpp

the time may be set by an offline assistance client and may not be accurate
... this is not my commit, but it's in a WIP branch...
MAVProxy can supply this assistance data, so perhaps this patch is worth looking at?

AP_GPS: don't consider uBlox PVT time correct unless we have 2D fix

---

libraries/AP_Logger/AP_Logger_Backend.cpp
libraries/AP_Logger/AP_Logger_Backend.h
libraries/AP_Logger/AP_Logger_Block.cpp
libraries/AP_Logger/AP_Logger_File.cpp
libraries/AP_Logger/AP_Logger_MAVLink.cpp
libraries/AP_Logger/LogFile.cpp
libraries/AP_Logger/LoggerMessageWriter.cpp

We may need to resurrect the `push_log_blocks` stuff here to try to make more room?
```
pbarker@fx:~/rc/ardupilot(pr/logger-formats-when-required)$ mavlogdump.py logs/00000001.BIN  | head
2024-06-14 22:52:00.55: FMT {Type : 128, Length : 89, Name : FMT, Format : BBnNZ, Columns : Type,Length,Name,Format,Columns}
2024-06-14 22:52:00.55: FMT {Type : 59, Length : 75, Name : MSG, Format : QZ, Columns : TimeUS,Message}
2024-06-14 22:51:51.96: MSG {TimeUS : 37148468, Message : Arming motors}
2024-06-14 22:51:51.96: FMT {Type : 3, Length : 16, Name : D32, Format : QBi, Columns : TimeUS,Id,Value}
2024-06-14 22:51:51.96: D32 {TimeUS : 37148468, Id : 9, Value : 35570}
2024-06-14 22:51:51.96: FMT {Type : 71, Length : 24, Name : ORGN, Format : QBLLe, Columns : TimeUS,Type,Lat,Lng,Alt}
2024-06-14 …
```

AP_Logger: write formats out as required rather than at start of log

---

Tools/autotest/arducopter.py
Tools/autotest/arduplane.py
Tools/autotest/vehicle_test_suite.py

allows state to be encapsulated within the object rather than simply in the same scope / closure of the method being called.
Will allow easier re-use of these blocks
A few other bits-and-pieces also in here:
```
a67655d52d815543bd0148bc32326769de7defc4 (HEAD -> pr/test-harness-improvements, github/pr/test-harness-improvements) autotest: break out a run_replay method
02c0a424cdd3d1fd17ed6b0443e913a691fcb43b autotest: allow message hooks to be instances of a MessageHook class
5ee967b3221465007fad130bb1eaa1ed25675511 autotest: add test infrastructure for installing lua modules
841642a706e958937f05330788492a5fb6b532f6 autotest: add option to ingore RTL mode change during in auto mode
0cc71f4904dc15e891969ebf37f67691afae1c0f autotest: add get_mode_string_for_mode …
```

autotest: Factor out a MessageHook class

---

libraries/AP_Scripting/lua_scripts.cpp

On macOS, sometimes ._script.lua is created to store metadata when the user copies script.lua over to their SD card. Previously, the scripting engine would barf since the file is not Lua. Now, these files are ignored.
Also avoids a case where a hidden and valid script might be loaded without the user's knowledge.
Tested on SITL that a hidden file is rejected and non hidden files are still loaded.

AP_Scripting: ignore hidden Lua files

---

libraries/AP_Airspeed/AP_Airspeed_Params.cpp
libraries/AP_BattMonitor/AP_BattMonitor_FuelLevel_Analog.cpp
libraries/AP_RSSI/AP_RSSI.cpp
libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp

NFC... @IamPete1 suggested that the metadata be more consistent...unfortunately, one description does not fit all...but this make analog and dual mode inputs more consistent

Make Analog Pin metadata more consistent

---

Tools/autotest/helicopter.py
libraries/AC_AttitudeControl/AC_AttitudeControl.h
libraries/AC_AutoTune/AC_AutoTune.h
libraries/AC_AutoTune/AC_AutoTune_FreqResp.cpp
libraries/AC_AutoTune/AC_AutoTune_FreqResp.h
libraries/AC_AutoTune/AC_AutoTune_Heli.cpp
libraries/AC_AutoTune/AC_AutoTune_Heli.h

This PR was primarily focused on enabling the safe tuning of larger helicopters.  I have made other changes along the way that help clean up the code and make it more efficient.  Here is a list of changes
- feedforward tuning was switched to a 5 deg attitude frequency dwell test for safety
- all tuning of the rate PIDs is accomplished with a sweep in attitude rather than rate to provide more safety when going to low frequencies for larger vehicles. 
- Rate and acceleration limits are used and included as separate parameters
- removed the sweep conducted before Rate D tuning and modified code so that data could be gathered during Max Gain sweep
- Significantly cleaned up the dwell_run method
- significantly cleaned up the test_init method
- Significantly cleaned up the update gain methods …

Tradheli Autotune Improvements

---

libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.h

This is my attempt at fixing https://github.com/ArduPilot/ardupilot/issues/18229
Here's a log using it:
[00000228.zip](https://github.com/ArduPilot/ardupilot/files/13502545/00000228.zip)
I am using a script to set the origin so we can use the earth field database.
I can see that XKF2 fields are all populated for magnetic field in body frame and earth frame.
I am not sure of what else to look at, though. magnetic field innovations seem bad, but at least they exist?

EKF3: allow earth-frame fields to be estimated with an origin but no GPS

---

libraries/AP_Scripting/applets/x-quad-cg-allocation.lua
libraries/AP_Scripting/applets/x-quad-cg-allocation.md

This PR is a script that corrects for the CoM discrepancy in a quad-X frame. It is applicable both in Copter and (quad)Plane.
I guess it's what #17461 was envisioned for.
It uses the dynamic mixer matrix to update the front-to-back thrust ratio on the fly.
I've been testing with RealFlight on [this model](https://github.com/ArduPilot/SITL_Models/tree/master/RealFlight/Released_Models/QuadPlanes/Skywalker_X8_QuadPlane), after "bringing it close to reality" by reverting the "cheat" I had made in the motor positions: 
The issue with this model is that due to the CoM misplacement, a throttle-up causes a pitch-down. The script corrects the buildup of the pitch I-term and suppresses the pitch-down motion upon throttling up.
The results have been documented in [this blog …

Lua Script for copter CoM compensation

---

ArduCopter/mode.h
ArduCopter/mode_autotune.cpp

This PR fixes a bug in autotune that was documented in issue #27418.  A tradheli user discovered this bug after landing in autotune and as the aircraft rotor system was spooling down, accidentally raised the collective, commanding positive climb rate.  This caused the motor interlock to engage unintentionally and caused the main gear to be stripped.  This would not usually happen in this case but did because of a bad setting for H_RSC_IDLE.  Regardless, this illustrates the possibility for the rotor to spool up once landed.
The fix to this bug is to change the logic so the interlock can never be enabled after landing in autotune.  In fact this PR causes the aircraft to disarm once ground idle is reached.  So this will affect the behavior for multirotors too.  @lthall I wasn't sure what …

AC_AutoTune: make safe shutdown for tradheli when landing in Autotune

---

libraries/AC_AutoTune/AC_AutoTune_Heli.cpp
libraries/AC_AutoTune/AC_AutoTune_Heli.h

The first patch just adds _cd to some_cd variables.
The second patch removes some variables which are no longer in use.
Post-the-first-patch, there are no binary changes (below).  The second patch must be correct if everything still compiles.  It saves a few bytes of both flash and (presumably) RAM.
```
Hitec-Airspeed      *                                                            
Pixhawk1-1M-bdshot             * …
```

AC_AutoTune: (heli-only) Rename and remove some variables

---

libraries/AC_Sprayer/AC_Sprayer.cpp
libraries/AC_Sprayer/AC_Sprayer.h
libraries/AC_Sprayer/AC_Sprayer_config.h

Also includes more stuff within the defines in the sprayer header file

AC_Sprayer: create and use an AP_Sprayer_config.h

---

libraries/SITL/SIM_GPS_NOVA.cpp
libraries/SITL/SIM_GPS_NOVA.h

same as one we already have
... also the one used in the driver itself

SITL: remove duplicated crc code

---

libraries/AP_Scripting/drivers/EFI_NMEA2k.lua
libraries/AP_Scripting/drivers/EFI_NMEA2k.md
libraries/AP_Scripting/modules/NMEA_2000.lua

this has been tested on a marine engine, and correctly produces key telemetry data
the NMEA_2000.lua module is broken out to make it easier to add other NMEA 2000 based drivers

AP_Scripting: added NMEA 2000 EFI driver

---

Tools/ardupilotwaf/boards.py
libraries/AP_Common/c++.cpp

on Cygwin we need to wrap _malloc_r not malloc
See https://cygwin.com/pipermail/cygwin/2000-July/038916.html
fixes #27197

build: fixed cygwin build with malloc wrap

---

ArduCopter/surface_tracking.cpp

the contents of this entire file are removed when AP_RANGEFINDER_ENABLED is false
``` …
```

Copter: remove unused #if around rangefinder

---

Tools/autotest/ardusub.py

Co-authored-by: Thomas Watson <twatson52@icloud.com>
Thomas noted that tests prior to RngFndQuality were leaving a LUA rangefinder hanging around in https://github.com/ArduPilot/ardupilot/pull/27484
Thomas' patch fixes RngFndQuality to only collect context messages after a reboot, which will fix the problem.
But tests should *not* leave the vehicle in this state, so this patch fixes that.

autotest: reboot after reverting rangefinder settings

---

Tools/autotest/vehicle_test_suite.py

we're running at large speedups; 5 simulated seconds might not be enough time for MAVProxy to accumulate statistics.  So get MAVProxy to emit the rate each second instead

autotest: fix race condition in DataFlashOverMAVLink test

---

libraries/AP_Scripting/lua_bindings.cpp

corrects compilation of cubeorange-periph-heavy

AP_Scripting: add missing scheduler include

---

libraries/GCS_MAVLink/MAVLink_routing.cpp

Probably changed from a pointer to reference at some point and forgot to update a normally disabled block

GCS_MAVLink: correct a debugging message

---

libraries/AP_Compass/CompassCalibrator.cpp

Not having a GPS connected currently causes compass calibration to skip the fix_radius step, which prevents using the WMM in the ekf.
I also added a warning so users can know something is wrong.
this is a step towards fix #18229, and is extracted from #26506

Allow full compass calibration with location sources other than GPS

---

Tools/autotest/arducopter.py
Tools/autotest/vehicle_test_suite.py
libraries/AP_Logger/AP_Logger.cpp
libraries/AP_Logger/AP_Logger.h
libraries/AP_Logger/AP_Logger_Backend.cpp
libraries/AP_Logger/AP_Logger_Backend.h

This stops us tracking formats-written in two places.
The Write() method will now emit formats as required and set the relevant bit in the backend-owned bitmask of formats sent.
Update: evidently this doesn't fix the DataFlash Erase issues...

AP_Logger: remove format sent_mask, use backend formats-sent bitmask

---

libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.h

this is only used in one place, and that place is called from the same routine setting the persistent state.  The only other place which calls readIMUData shouldn't be running the prediction step, but mmay, depending on the previous setting of the prediction step.
We are not initialising this state on filter reset, so it's possible that the state will be set when we do an InitialiseFilterBootstrap, which is probably not desired

AP_NavEKF3: do not store prediction-enabled as state

---

Tools/autotest/arducopter.py
libraries/AC_WPNav/AC_Loiter.h

This is a (currently failing) test which checks what happens if we re-enter LOITER from AUTO while we are in RC failsafe.
This picture shows that we maintain 1.3m/s in LOITER when in RC failsafe following an auto mission.
If the set-parameter of `SIM_RC_FAIL` is removed, and the re-setting of the roll input to 1500 is commented back in the test passes (i.e. the vehicle comes to a stop)

AC_WPNav: correct calculation of predict-accel when zeroing pilot desired accel

---

libraries/AP_Mount/AP_Mount_Siyi.cpp
libraries/AP_Mount/AP_Mount_Siyi.h

This replaces PR https://github.com/ArduPilot/ardupilot/pull/25736
This adds support for sending the vehicle's position and velocity to the siyi gimbal which allows the lat, lon and altitude to be recorded in each image via EXIF.  This has been tested on real hardware and works.  Below is a screen shot from the Siyi manual describing the command structure.

AP_Mount: added sending of position data to Siyi gimbal

---

libraries/AC_PID/AC_PID.cpp

This fixes a bug that was introduced in https://github.com/ArduPilot/ardupilot/pull/24411.
Currently the error is calculated before the target filter is applied, this means the error calculation is using the target from the last loop. 
The fix is to do all the target filtering, then calculate the error and do all of the error filtering.

AC_PID: correct error calculation to use latest target

---

libraries/AP_Logger/AP_Logger_File.cpp
libraries/AP_Logger/AP_Logger_File.h

We used to produce files hwih looked like log1.BIN.  We moved to 00000001.BIN instead so things collate.
This code allowed the autopilot to return data from SD cards which had old logs on them.

AP_Logger: remove short-filename compatability code

---

libraries/AP_NavEKF/AP_NavEKF_Source.cpp
libraries/AP_NavEKF/AP_NavEKF_Source.h

This is a cut-down version of PR https://github.com/ArduPilot/ardupilot/pull/26632
This adds a new EK3_SRC_OPTION bit that allows "re-aligning" the External Nav position to the AHRS when optical flow is used (e.g. when External Nav is not used).  Previously this re-alignment would only occur when using GPS or Beacons that provide an absolute position.
Re-aligning to the optical flow is useful when the ModalAI VOXL cameras (and perhaps other external nav systems) are paired with an optical flow sensor for backup.  It means the pilot should not notice any position jumps when switching between the two sources.
This has been tested on real hardware and below are the before and after screenshots.  During this testing the vehicle was first switched to use Optical Flow, the vehicle was then …

AP_NavEKF: option to align extnav to optflow pos estimate

---

libraries/AP_HAL_ChibiOS/hwdef/H757I_EVAL/hwdef-bl.dat
libraries/AP_HAL_ChibiOS/hwdef/H757I_EVAL/hwdef.dat

avoids this compilation error:
../../Tools/AP_Periph/can.cpp:152:33: error: static assertion failed: DroneCAN bootloader cannot support external flash
152 | static_assert(EXT_FLASH_SIZE_MB == 0, "DroneCAN bootloader cannot support external flash");

hwdef: H757_EVAL: make it not-AP_Periph

---

Tools/autotest/arducopter.py
Tools/autotest/helicopter.py
Tools/autotest/rover.py
Tools/autotest/vehicle_test_suite.py

this makes the assumption that any reboot done within a SITL was because some parameter changes only take effect after a reboot.
... so after we have reverted the parameters, reboot again to make the reverted parameter values take effect

autotest: reboot after any context in which a reboot was done

---

Tools/AP_Periph/rc_out.cpp

Same sort of difficulty as https://github.com/ArduPilot/ardupilot/pull/27093 and same sort of fix.
Observed problems with a BLHeli_S ESC and DShot600. Applying this patch fixes it.

AP_Periph: ensure the dshot type gets set

---

libraries/SITL/SIM_JSON.cpp

Airspeed calculation for JSON was not quite working because velocity_air_ef was not updated in SIM_JSON.cpp

SITL: fix json airspeed

---

Tools/AP_Bootloader/board_types.txt

PMU And GNSS ID Reserve for ZeroOne.

board_types.txt:  PMU And GNSS ID Reserve for ZeroOne.

---

libraries/AP_InertialSensor/AP_InertialSensor_ADIS1647x.cpp
libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp

The basis for the clip count thresholds of 39.5G and 15.5G is unclear. 
By explicitly stating it, we can be aware that 0.5G is being subtracted.

AP_InertialSensor: Clearly state the maximum G-force

---

libraries/AP_Math/matrix3.h
libraries/AP_Math/vector2.h
libraries/AP_Math/vector3.h
libraries/AP_Math/vectorN.h

Not valid in C++20, and makes GCC 14.1.1 very unhappy.
Without these changes you get the following spammed at you when building, for basically every compilation unit, makes it very very hard to find actual build errors.
```
[  68/1324] Compiling libraries/APM_Control/AP_AutoTune.cpp
In file included from ../../libraries/AP_Math/matrix3.h:42,
from ../../libraries/AP_Math/AP_Math.h:13,
from ../../libraries/AC_AutoTune/AC_AutoTune_FreqResp.h:7,
from ../../libraries/AC_AutoTune/AC_AutoTune_FreqResp.cpp:6:
../../libraries/AP_Math/vector3.h:79:25: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
79 |     constexpr Vector3<T>()
|                         ^
../../libraries/AP_Math/vector3.h:79:25: note: remove the ‘< >’
../../libraries/AP_Math/vector3.h:85:25: …
```

AP_Math: Remove template parameter from constructor

---

libraries/AP_RPM/AP_RPM.cpp
libraries/AP_RPM/LogStructure.h

Lots of users struggle with setting up interrupt-based RPM sensors.  (see here for a number of users asking for help: https://discuss.ardupilot.org/t/rpm-sensor-wiki-knowledge-share/45091/83).
In an attempt to demystify RPM sensors, this PR improves the logging:
- Move to instance based logging.
- Always log the rpm reading regardless of quality.
- Log the calculated quality value.
- Log the bool so that we can clearly see when AP reports the sensor as healthy.
It is my hope that adding this information will help users to figure out what is going wrong.
**Example from Testing:**  
Tested IRL on Heli.
Thankfully I had a dodgy RPM sensor for testing 😬
So now, by always logging raw RPM I can see that something is not right in the measurement and I can see that the corresponding quality is …

AP_RPM: Demystifying RPM sensors 

---

libraries/AP_Proximity/AP_Proximity_LightWareSF45B.cpp
libraries/AP_Proximity/AP_Proximity_TeraRangerTower.cpp

Replaces https://github.com/ArduPilot/ardupilot/pull/27059 and is careful not to change any logic.

AP_Proximity: avoid use of int16_t-read call

---

libraries/RC_Channel/RC_Channel.cpp
libraries/RC_Channel/RC_Channel.h

Rovers and other vehicles sometimes have cameras mounted on both the front and rear.

MOUNT: Add a mount2 retract

---

libraries/AP_InertialSensor/AP_InertialSensor.h
libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
libraries/AP_InertialSensor/AP_InertialSensor_Backend.h

No compiler output change when the IMU killing code remains in.
Saves 64 bytes when the feature is removed - and the code is actually *gone* from ArduPilot, which is good.

AP_InertialSensor: tidy IMU killing

---

Tools/AP_Periph/Parameters.cpp
Tools/AP_Periph/Parameters.h
Tools/AP_Periph/rc_out.cpp

Like other vehicles (which use RC_SPEED), ESC_RATE is used to set the PWM output rate for outputs whose functions are set to MotorN so that ESCs can be driven at a fast speed (400Hz, same default as aerial vehicles) while servos still run at normal speed (50Hz, controlled by OUT_RATE).
Tested the PWM outputs with real devices and a scope. Also tested that PWM and DShot600 still fly well.

AP_Periph: add ESC_RATE parameter to RC_OUT peripherals

---

libraries/AP_Compass/CompassCalibrator.cpp
libraries/AP_Compass/CompassCalibrator.h

forces user to make decisions in these cases.
No size difference on CubeOrange or MatekF405 Plane

Use enumerations in CompassCalibrator

---

libraries/AP_HAL/Util.h
libraries/AP_HAL_ChibiOS/Util.h
libraries/AP_HAL_ESP32/Util.h
libraries/AP_HAL_Empty/Util.h
libraries/AP_HAL_Linux/Util.h
libraries/AP_HAL_SITL/Util.h

Extracted from https://github.com/ArduPilot/ardupilot/pull/27504

Remove debug shell

---

libraries/AP_GPS/AP_GPS_SITL.cpp

```
./../libraries/AP_GPS/AP_GPS_SITL.cpp:37:27: error: aggregate 'timeval first_tv' has incomplete type and cannot be defined
37 |     static struct timeval first_tv;
|                           ^~~~~~~~
Waf: Leaving directory `/ardupilot/src/build/sitl'
Build failed
-> task in 'objs/AP_GPS' failed (exit status 1):
{task 135805090486368: cxx AP_GPS_SITL.cpp -> AP_GPS_SITL.cpp.0.o}
```
Closes https://github.com/ArduPilot/ardupilot/issues/27227

AP_GPS: resolve compilation problem with timeval

---

Tools/scripts/build_options.py
Tools/scripts/extract_features.py

Tools: build_options.py: add AP_BARO_PROBE_EXTERNAL_COMPASSES

---

libraries/AP_Filesystem/AP_Filesystem.cpp

normally fgets is on a buffered FILE handle. For AP_Filesystem we use an unbuffered file descriptor. This means we were reading one byte at a time from the file
this uses lseek to make fgets() much more efficient by reading the max buffer size at a time in the file
Extracted https://github.com/ArduPilot/ardupilot/pull/27504

AP_Filesystem: make fgets() much more efficient

---

libraries/AP_Baro/AP_Baro_ICP101XX.cpp

this sensor doesn't like reading at higher than expected rate

AP_Baro: avoid i2c errors with ICP101XX

---

Tools/ardupilotwaf/boards.py
libraries/AP_HAL/Util.h
libraries/AP_HAL_ChibiOS/Util.cpp
libraries/AP_HAL_ChibiOS/Util.h
libraries/AP_HAL_ESP32/Util.cpp
libraries/AP_HAL_ESP32/Util.h
libraries/AP_HAL_Linux/Util.cpp
libraries/AP_HAL_Linux/Util.h
libraries/AP_HAL_SITL/Util.cpp
libraries/AP_HAL_SITL/Util.h

Extracted from https://github.com/ArduPilot/ardupilot/pull/27504
Buzz gave verbal approval for the HAL change on DevCall.

Make ENABLE_HEAP to #if not defined()

---

Tools/ardupilotwaf/boards.py

this change made use of gdb so slow it is completely unusable for ArduPilot. Far too many macros, loading gdb takes forever
I don't know exactly how long it does take as I gave up before it finished parsing all the macros

waf: Revert "waf: use debug option 3 which records defines as well"

---

ArduSub/AP_Arming_Sub.cpp
ArduSub/ArduSub.cpp
ArduSub/Parameters.cpp
ArduSub/Parameters.h
ArduSub/Sub.h
Tools/autotest/ardusub.py

This change makes it so that, when arming, if no GPS is present and the origin wasn't set some other way (dvl or ugps), we use set a backup origin so we are able to use the WMM table even without position data

Sub: allow setting backup origin parameters for a happier gps-less operation

---

libraries/AP_Logger/LogStructure.h

I believe the existing `m/s` units are wrong and should be `rad/s` instead, based on:
- https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Logger/LogStructure.h#L881
- https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_OpticalFlow/AP_OpticalFlow.h#L97
@MattKear FYI.

AP_Logger: Fix logged units

---

Tools/autotest/arducopter.py
libraries/AP_HAL_SITL/AnalogIn.cpp

This adds a test for the battery unhealthy fail safe added in https://github.com/ArduPilot/ardupilot/pull/27358.
So we can easily make a monitor unhealthy this changes SITL `ADCSource::set_pin` to return false for a pin of value `ANALOG_INPUT_NONE` (-1).

Tools: autotest: copter: add test for unhealthy pre-arm and failsafe

---

libraries/AP_GPS/AP_GPS.h

https://en.wikipedia.org/wiki/Dilution_of_precision_(navigation)

AP_GPS: hdop and vdop are unitless

---

libraries/AP_EFI/AP_EFI_DroneCAN.cpp

The last_update_ms variable was never set in the DroneCAN implementation of the Electronic Fuel Injector sensor. This causes the function `bool AP_EFI::is_healthy` to always return false. Solved by adding one line of code to set the variable to the correct value.

set the last_updated_ms field of efi_state

---

libraries/AP_HAL_SITL/CANSocketIface.cpp
libraries/SITL/SITL.cpp
libraries/SITL/SITL.h

Also corrects an issue where setting an invalid type could result in undefined behavior.
Tested by running two peripherals on two different buses.

AP_HAL_SITL: allow disabling CAN interfaces

---

ArduCopter/mode_auto.cpp

This fixes the bug in payload place where we do not set the start altitude when we abort payload place because the gripper is already released.
This bug causes the aircraft to go to the previous altitude or zero.
I also made the message clearer as this was one of the reasons I didn't pick up on the problem initially.

Copter: Payload Place: Fix first run abort

---

Rover/Parameters.cpp
libraries/AR_Motors/AP_MotorsUGV.cpp
libraries/AR_Motors/AP_MotorsUGV.h

Add a frame type to support 3 wheel rovers that use Mecanum wheels. The frame requires different mixing weights to Omni3 to ensure the linear (v_x, v_y) and angular (omega_z) velocities align with the vehicle axes. 
Mecanum wheeled rover examples have been added to the Gazebo models in https://github.com/ArduPilot/SITL_Models/pull/139.
_Figure: `rc 3` controls forward and back movement._
_Figure: `rc 4` controls lateral movement._
_Figure: `rc 1` controls yaw._
The weights are determined using the approach to derive the inverse kinematics described in A. Gfrerrer. _"Geometry and kinematics of the Mecanum wheel"_, Computer Aided Geometric Design 25 (2008) 784–791. Retrieved from https://www.geometrie.tugraz.at/gfrerrer/publications/MecanumWheel.pdf.

Rover: add frame type Omni3Mecanum

---

libraries/AP_HAL/SIMState.cpp

used if you want to use the Glider model in Sim-on-Hardware

AP_HAL: SIMState: include SITL glider header

---

libraries/AP_HAL_SITL/SITL_Periph_State.cpp

Removes busywait for simulation state packet, dramatically reducing CPU usage. The dominant wait time in AP_Periph is 1024 microseconds as this is the default value of HAL_PERIPH_LOOP_DELAY_US, so a 1ms wait is unlikely to be a problem.

AP_HAL_SITL: improve periph simulation efficiency

---

libraries/AP_HAL_ESP32/Util.cpp

Avoids stuffing uninitialized data into the ID.

AP_HAL_ESP32: use correct unformatted system ID length

---

libraries/AP_Camera/AP_Camera_MAVLinkCamV2.cpp

I believe the original code was a typo, because `.32` as a string doesn't make sense (and it did confuse me for a long time). It was probably meant as a safeguard against a full 32 byte string situation where the mavlink library would not add a terminator. Without this fix a camera advertising such a name would cause a buffer overflow.

AP_Camera: proper string formatting

---

libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.cpp
libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.h
libraries/SITL/SIM_VectorNav.cpp
libraries/SITL/SIM_VectorNav.h

Currently, all configuration commands sent to the VN unit are not validated for a response, leading to difficult-to-diagnose errors when a command doesn't go through or is rejected by the VN. All commands send to the unit (particularly setup commands) should have their acceptance confirmation checked before the driver begins to use the data.

Add validation to initialization configuration commands

---

Tools/autotest/pysim/vehicleinfo.py
libraries/SITL/SIM_Sailboat.cpp
libraries/SITL/SIM_Sailboat.h

Adding a SITL model for a skid-steering motorboat, as we don't currently have one in the built-in simulator.
Makes it easier to debug pivot turns, etc for boats.
Use ``sim_vehicle.py --vehicle=Rover --frame=motorboat-skid`` to use it

Add SITL support for skid-steering boat

---

libraries/AP_DDS/AP_DDS_Client.cpp
libraries/AP_DDS/AP_DDS_Client.h

Add a param `DDS_DOMAIN_ID`.
This allows the `ROS_DOMAIN_ID` to be set to values other than the current default of 0, useful for managing multiple vehicles or keeping various ROS 2 running instances separated. The behaviour is backward compatible with a default of 0.
The range of valid domain ids is 0 to 232 (see: https://docs.ros.org/en/rolling/Concepts/About-Domain-ID.html)
Comment: the param should really be `ROS_DOMAIN_ID` to be consistent with usage with the ros2 cli, but as it's in the `DDS_` param tree the name `DDS_ROS_DOMAIN_ID` would just be confusing.
Run the default UDP instance:
```bash
ros2 launch ardupilot_sitl sitl_dds_udp.launch.py transport:=udp4 synthetic_clock:=True wipe:=False model:=quad speedup:=1 slave:=0 instance:=0 defaults:=$(ros2 pkg prefix …
```

AP_DDS: add param DDS_DOMAIN_ID

---

Tools/autotest/arducopter.py
libraries/AP_HAL/board/sitl.h
libraries/AP_Mount/AP_Mount_SoloGimbal.cpp
libraries/AP_Mount/AP_Mount_SoloGimbal.h
libraries/SITL/SIM_Gimbal.cpp
libraries/SITL/SIM_Gimbal.h

Simulation was just broken; we were rejecting MAVLink traffic from the simulated gimbal as it was coming from the autopilot sysid/compid
Had to disable the rate tests as the Solo backend doesn't allow specifications of the rates (but could, from my reading)

Add autotest for Solo mount

---

libraries/AP_Scripting/docs/docs.lua
libraries/AP_Scripting/examples/battery_internal_resistance_check.lua
libraries/AP_Scripting/generator/description/bindings.desc

Closes https://github.com/ArduPilot/ardupilot/issues/1898

Add script for monitoring battery resistance

---

Tools/scripts/firmware_version_decoder.py

The script is failing when we do `#define FW_TYPE FIRMWARE_VERSION_TYPE_BETA+1` and so on...
Required for https://github.com/bluerobotics/BlueOS/issues/2833

tools: firmware_version_decoder.py: fix detection for BETA+n firmware

---

libraries/AP_Scripting/generator/src/main.c

A few re-engineerings to make the state setup more efficient and on-demand. Please see the commits for details.
There are no visible changes to scripts except for ones that play games reading `_ENV`, which none in the repo do. There might be a slight downside of increased risk of fragmentation and out of memory problems at inopportune moments, but I think the savings are worth it.
Tested some scripts including my REPL in SITL and on Cube Orange.
Total savings on Cube Orange:
* 104 bytes of statically allocated RAM
* 14K of Lua heap memory (reduced by 2/3)
* ~800 bytes per running script
* 216 bytes of flash

AP_Scripting: reduce Lua state memory usage

---

ArduPlane/Parameters.cpp
ArduPlane/Parameters.h
libraries/AP_TECS/AP_TECS.cpp
libraries/AP_Vehicle/AP_FixedWing.h

When stall prevention is enabled we were scaling from the aircraft's minimum flight speed. However this is normally already picked as being above the stall speed, and for a variety of reasons we may want to pin the aircraft at a higher minimum speed. But if the aircraft was commanded to fly to close to that minimum speed as soon as it banked for a pattern it would command a increase in speed to keep it away from stalling. However if your minimum speed is far from stalling this increase was incorrect. To make it worse what this actually results in happening is an aircraft diving for more speed (over 10 m/s on some aircraft) as well as descending to gain that speed resulting in over 200 foot deviations in altitude control.
This was found on a real vehicle (in a rather alarming flight), I've …

AP_TECS: Add a separate stall speed parameter used for minimum speed scaling

---

libraries/AP_HAL_SITL/CANSocketIface.cpp

If HAL_CAN_WITH_SOCKETCAN is undefined, set transport to NULLPTR instead of leaving it undefined.
When undefined, treat it the same as NONE, and set it to NULLPTR.

AP_HAL_SITL: If HAL_CAN_WITH_SOCKETCAN is undefined, treat it as NONE

---

libraries/AP_Mount/AP_Mount_Topotek.cpp
libraries/AP_Mount/AP_Mount_Topotek.h

This replaces PR https://github.com/ArduPilot/ardupilot/pull/26666
This PR adds 3 enhancements to the Topotek driver:
1. versions can be returned by the gimbal in "1.2.3" format (previously it was only "123"
2. gimbal's model name is retrieve
3. image tracking status is improved to handle gimbals that do not have this feature
This has been lightly tested on a real gimbal but we need to clear up these issues:
1. the model name appears as "000000000"
2. I don't really understand the new tracking state "waiting" and how the driver should decide what state to put the gimbal into

AP_Mount: Topotek image tracking fix

---

libraries/AP_InertialSensor/AP_InertialSensor_tempcal.cpp

Fixes `INSn_ACCSCAL_Z` not being stored in persistent storage when bootloader is flashed.

AP_InertialSensor: Fix persistent storage of parameter INSn_ACCSCAL_Z

---

libraries/AP_HAL_ChibiOS/Util.cpp

This fixes the handling of the newer INSn_* parameters when loading those stored in persistent memory.
The current code does not take into account any IMU greater than INS3.

AP_HAL_ChibiOS: Capture the case where the persistent parameter is the newer format INSn_ACC_ID

---

Tools/environment_install/install-prereqs-arch.sh
Tools/environment_install/install-prereqs-openSUSE-Tumbleweed.sh
Tools/environment_install/install-prereqs-ubuntu.sh

Explicitly upgrade to use newest `packaging` to avoid `packaging` incompatibility with `setuptools>=71.0`
As https://github.com/pypa/setuptools/issues/4496#issuecomment-2240322375 mentions:
> setuptools>=71.0 does not work with packaging<24.0, but will not upgrade it if packaging is already installed
Also relevant: https://github.com/pypa/setuptools/issues/4496

Tools: install-prereqs-ubuntu.sh: fix script after setuptools>=71.0.0 release

---

Tools/AP_Bootloader/board_types.txt

Reserve Board-ID for StingBee Stellar F4
board info on:
https://stingbee.com.ua/flight_controllers/stellarf4

board_types.txt: Reserving board id for Stellar F4

---

libraries/AP_HAL_ChibiOS/hwdef/MatekL431-DShot/hwdef.dat

the PWM expansion boards can also be used for relay control, often combined with PWM output

hwdef: enable relay support in MatekL431-DShot fw

---

Tools/AP_Periph/AP_Periph.cpp
libraries/AP_HAL_ChibiOS/hwdef/common/watchdog.c
libraries/AP_HAL_ChibiOS/hwdef/common/watchdog.h

This allows the watchdog timeout to be adjusted in the hwdef.dat file, so that critical nodes like ESCs can recover more quickly.
I haven't added this to any hwdefs yet. I think that should probably be a separate PR so we can test the specific values that work, and which boards we want to add it to. I think a good contender is the MatekL431-dshot/bdshot/rc, since they don't use a lot of complex features and they are used in pretty time-critical applications. I'm thinking we could probably get away with a 100ms delay on that.
Also, should I add a `#if` to prevent changing this on anything other than AP_Periph?

HAL_ChibiOS: add adjustable wdg timeout for hwdefs

---

Tools/scripts/sitl-on-hardware/sitl-on-hw.py
libraries/SITL/SIM_Aircraft.cpp
libraries/SITL/SIM_Glider.cpp

This is a continuation of https://github.com/ArduPilot/ardupilot/pull/27559.
Up to now, in a typical Simulation in Hardware (SIH) you could not enable glider and balloon simulation on SIH, because `SIM_config.h` would have at its end:
```c++
#ifndef AP_SIM_GLIDER_ENABLED
#define AP_SIM_GLIDER_ENABLED (CONFIG_HAL_BOARD == HAL_BOARD_SITL)
#endif
```
which evaluates to false for SIH.
This PR allows the use of `./Tools/scripts/sitl-on-hardware/sitl-on-hw.py --vehicle plane --simclass Glider --frame Plane` to capture the `simclass` and enable the `AP_SIM_GLIDER_ENABLED` flag.
Additionally, it fixes a bug where the balloon channel would initialize in a negative value, resulting in the balloon getting downwards velocity and going underground, dragging the glider with it.
To test it:
1. Run …

SIH glider improvements

---

ArduCopter/mode.h
ArduCopter/mode_smart_rtl.cpp
libraries/AP_SmartRTL/AP_SmartRTL.h

This resolves issue https://github.com/ArduPilot/ardupilot/issues/27517 by backing up the current destination and then adding it back to the path if the user exits SmartRTL mode while returning.
This has been tested in SITL and resolves the problem.  During testing I created a zig zag mission as shown below and after the vehicle reached the final waypoint on the top-left I repeatedly switched the vehicle back and forth between SmartRTL and Brake mode about 20 times.
In master when finally switched to SmartRTL for the last time, the vehicle simply landed in place.
With this PR applied the vehicle correctly flew the zig-zag pattern home (apologies for mixing MP and MAVProxy views).

Copter: SmartRTL restores last waypoint if users switches to another mode

---

libraries/AP_Mount/AP_Mount_Topotek.cpp

This corrects a potential issue in the Topotek driver (introduced this morning by PR https://github.com/ArduPilot/ardupilot/pull/27568) that could lead to writing past the end of the "version" variable while parsing the version packet received from the gimbal.
This has been lightly tested on real hardware but the exact code path affected is not run due to the hardware I'm using sending the old style version string
Thanks @peterbarker for finding this issue

AP_Mount: Topotek safely parses version packet

---

Tools/AP_Bootloader/AP_Bootloader.cpp
Tools/AP_Bootloader/support.cpp
Tools/AP_Bootloader/support.h

* Disables ecc check for boards without Heap as well

AP_Bootloader: fix build for STM32H7 without heap

---

libraries/AP_ESC_Telem/AP_ESC_Telem.h

This change was needed to get a AP_Periph board to sense analog voltage and current, and forward that as ESC telemetry. 
I had to define ESC_TELEM_MAX_ESCS in the hwdef which was being redefined again, and throwing an error.

AP_ESC_Telem: Add ifndef before defining ESC_TELEM_MAX_ESCS

---

libraries/AP_TemperatureSensor/AP_TemperatureSensor_Analog.cpp
libraries/AP_TemperatureSensor/AP_TemperatureSensor_Analog.h

After collecting some data from a analog temperature sensor, a 5th order polynomial tracked the temperature better.

AP_TemperatureSensor: Extend analog sensor backend to 5th order polynomial

---

ArduCopter/AP_Arming.cpp

I think the preprocessor is getting mixed in with the processing and is difficult to distinguish. I want to clearly identify the preprocessor. The description of the preprocessor in this definition is different only in this file.

Copter: Clearly show the preprocessor

---

libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp

This patch fixes the bug that was preventing copters using GPS yaw from using drag fusion to estimate wind. See https://github.com/ArduPilot/ardupilot/issues/26650 for details
Testing in SITL using the https://github.com/ArduPilot/ardupilot/blob/master/Tools/autotest/default_params/copter-gps-for-yaw.parm parameters results in a wind speed being reported at the ground station with varying readings when EK3_DRAG_MCOEF is also set to a positive value.
The values reported are  large and varying because the default SITL physics model does not model X and Y axis specific forces, however this test does show that that after the patch, wind estimation is active with a GPS yaw source.

AP_NavEKF3: Fix yaw alignment bug preventing copter  wind estimation

---

libraries/AP_Mount/AP_Mount.cpp

Change:
- Wrapped the definition of `serial_instance` with preprocessor directives to ensure it is only defined when necessary.
- This resolves the compile error caused by the unused variable when no features requiring `serial_instance` are enabled.

AP_Mount: Conditionally define `serial_instance` to fix unused variable compile error

---

ArduCopter/Copter.cpp
ArduCopter/RC_Channel.cpp
ArduCopter/mode_circle.cpp
ArduCopter/tuning.cpp
Tools/autotest/arducopter.py
libraries/RC_Channel/RC_Channel.cpp
libraries/RC_Channel/RC_Channel.h

This PR add the ability to choose which RC channel controls the Transmitter Based Tuning, instead of the hard coded channel 6.
If a user want to use channel x for transmitter based tuning, the parameter RCx_OPTION should be set to 177 (Transmitter Tuning), as discussed in issue #25186.
The changes has been tested in SITL after setting parameters:
- `TUNE` 21
- `TUNE_MIN` 0
- `TUNE_MAX` 0.03
- `RC9_OPTION` 177
Changing the PWM value of CH8 results in different `ATC_RAT_RLL_D` values.

Copter: choose RC channel for Transmitter Based Tuning

---

ArduPlane/Parameters.cpp
ArduPlane/altitude.cpp
ArduPlane/defines.h

"Aviation style" climb profile where the aircraft reaches final altitude way before reaching the desired location. 
This has been suggested before in #16248, and I finally got around to giving it a try.

Plane: option to immediately climb in AUTO mode (not doing glide slope)

---

libraries/AP_InertialSensor/AP_InertialSensor.cpp

Discovered on CubeOrangePlus BG3 in a production environment.
On the very first boot of the CubeOrangePlus-BG3 after a parameter wipe, 4 IMU instances are registered. These register under the Parameters with the IDs:
* INS_ACC_ID       3867682
* INS_ACC2_ID      3867938
* INS_ACC3_ID      3867658 **<< This appears to be a legitimate ICM45686 discovered with CHECK_ICM45686_EXT in CHECK_IMU2_PRESENT**
* INS4_ACC_ID      3867658 **<< NOTICE DUPLICATE OF INS_ACC3_ID - This is added when AUX:3867658 is processed**
On subsequent boots, it appears the macro `ADD_BACKEND_AUX` filters the AUX IMU so it is never probed or registered in the first place.
The problem arises if you take the BG3 out of the box, flash AP and go straight into an accelcal on the first boot. Since IMU4 is registered, it …

AP_InertialSensor: Check the gyro/accel id has not been previously registered

---

libraries/AP_Notify/RGBLed.cpp

The two if statements are making the same judgment.
Refactor this code to consolidate the common judgment and clarify the differing judgments.

AP_Notify: Perform common checks first

---

ArduCopter/mode.cpp
libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
libraries/AC_AttitudeControl/AC_AttitudeControl.h

This pr provides the ability to reduce the gains of roll, pitch, and yaw to remove ground oscillation while landed. Each axis has a gain reduction variable that is set when the aircraft is landed. The gain returns to normal in 2 x ATC_INPUT_TC.
This is a common problem on aircraft with flexible landing gear. It is often seen as a yaw oscillation during spool up on more solidly built aircraft also.

Detune to stop ground oscillation

---

ArduSub/GCS_Mavlink.cpp
ArduSub/GCS_Mavlink.h
ArduSub/mode.h
Tools/autotest/ardusub.py

This adds support for MAV_CMD_DO_REPOSITION on COMMAND_INT for Sub. The implementation is basically copied from Copter.
I added an autotest that tests this with 2 frames: MAV_FRAME_GLOBAL_RELATIVE_ALT and MAV_FRAME_GLOBAL_TERRAIN_ALT.
The main benefit is to align with the other vehicle types.
Fixes #14783

Sub: Support MAV_CMD_DO_REPOSITION on COMMAND_INT 

---

Tools/AP_Periph/compass.cpp

I coudn't compile a periph board with a compass and AP_PERIPH_PROBE_CONTIONUS enabled without this change.

AP_Periph: Fix compiling issues with AP_PERIPH_PROBE_CONTIONUS enabled

---

ArduCopter/AP_Arming.cpp

Indent preprocessor directives at the same level as the code they control can make it difficult to distinguish between built-in and non-built-in elements. 
I believe it is better to indent preprocessor directives one column to the left, aligning them with the rest of the code.

Copter: Distinguish preprocessor processing

---

libraries/AP_Mission/AP_Mission.cpp

ArduPilot supports many STM32 FCs.
It is good to process with STM32 in mind.

AP_Mission: Change division to multiplication

---

libraries/AP_Mount/AP_Mount_Siyi.cpp

I would change to a type table with LEN values as indices.
No more decisions will be necessary.

AP_Mount: SWITCH statement to table reference

---

libraries/AP_Camera/AP_Camera_Params.cpp

When users setup a combined camera+gimbal they normally need to set the CAMx_TYPE to 4 (Mount).  This updates the parameter description to name all the possible camera gimbal types it might refer to which now includes Topotek, Viewpro and Xacti.
I've created two commits so we can backport the 1st one (which doesn't include Topotek) into 4.5 if we choose
FYI @laozhou-fujian

AP_Camera: TYPE param description get Topotek, Viewpro, Xacti

---

libraries/AC_AutoTune/AC_AutoTune.cpp
libraries/AC_AutoTune/AC_AutoTune.h
libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
libraries/AC_AutoTune/AC_AutoTune_Multi.h

I have moved the multi only variable declaration variables into the AC_AutoTune_Multi.h.
I removed the "f" from the floats.
I simplified a couple functions.
All these changes should be non-functional.
I am a little disgusted by some of the structures that I made here. This still has some work to do before it could be considered "clean".

AC_Autotune: Clean up Multi Variables and non functional changes

---

libraries/AP_Filesystem/AP_Filesystem_FATFS.cpp

The return value is TRUE or FALSE.
In this case, I think the type of BOOL is appropriate.

AP_Filesystem: BOOL for binary types

---

Tools/scripts/build_options.py
Tools/scripts/extract_features.py
libraries/AP_Frsky_Telem/AP_Frsky_Parameters.cpp
libraries/AP_Frsky_Telem/AP_Frsky_Parameters.h
libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.cpp
libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.h

This allows to build with "define HAL_WITH_FRSKY_TELEM_BIDIRECTIONAL 0".

AP_Frsky_Telem: fix compilation when frsky bidir is disabled

---

Tools/AP_Bootloader/board_types.txt

This PR Adds CBUnmanned-CM405-FC to the board ID list with ID 1301

Tools: Reserve ID for CBUnmanned CM405 Flight Controller

---

.github/workflows/qurt_build.yml

this prevents user repos getting failures
thanks to Pete for the suggestion

CI: only run qurt build on ArduPilot main repo

---

libraries/AP_HAL_ChibiOS/hwdef/FlywooF745/hwdef.dat

No effect as lines have always been commented out, but not useful and EKF2 is not something to encourage.
Verified no compiler output change.

hwdef: remove EKF opinion from FlywooF745

---

Tools/environment_install/install-prereqs-ubuntu.sh

this was only intended to narrow an error being seen with Focal, but appears to fix it instead

Tools: environment_install: fix focal install

---

libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.cpp
libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.h
libraries/SITL/SIM_VectorNav.cpp
libraries/SITL/SIM_VectorNav.h

A few key outputs for logging are missing, and the current structure prevents 800Hz IMU data using TYPE::INS. I would split the messages into:
IMU packet, EKF packet, GNSS packet
There should also be additional logging messages for the new packets coming through
This both aids in debugging, and allows use of VectorNav uncertainty and status information for internal publishing and use

VectorNav: Reorganize message packets

---

AntennaTracker/ReleaseNotes.txt
AntennaTracker/version.h
ArduCopter/ReleaseNotes.txt
ArduCopter/version.h
ArduPlane/ReleaseNotes.txt
ArduPlane/version.h
Rover/ReleaseNotes.txt
Rover/version.h

This the Copter, Rover, Tracker, Plane 4.5.5-beta2 release and includes just a single PR
- https://github.com/ArduPilot/ardupilot/pull/27458
Everything included in 4.5.5 can be seen in [this project](https://github.com/orgs/ArduPilot/projects/8/views/6)

Copter/Plane/Rover/Tracker: 4.5.5-beta2 release

---

Tools/autotest/rover.py

for reasons I can't fathom, defaulting the rangefinder state causes problems with the vehicle orientation in SITL - probably a state update fix somewhere.
This test was kind of broken anyway - the RangeFinder was pointing latterally out from the vehicle, but is displayed forward of the vehicle (ther RANGEFINDER mavlink message conveys no orientation information)

autotest: correct Rover RangeFinder test

---

Tools/autotest/rover.py
libraries/AP_HAL_SITL/RCOutput.h

This allows BRD_SAFETY_DEFLT=1 to work correctly for SITL.

AP_HAL_SITL: initialize rcout safety state

---

libraries/AP_Param/AP_Param.cpp

`param_defaults_data` does not exist if `AP_PARAM_MAX_EMBEDDED_PARAM` is 0.

AP_Param: Fix `ENABLE_DEBUG` enabled error with no embedded param

---

ArduCopter/AP_Arming.cpp

If you want to compare the value of a variable that does not change with a different value multiple times, the SWITCH statement is a good choice.

Copter: Make multiple decisions into a SWITCH statement

---

libraries/AP_Scripting/docs/docs.lua
libraries/AP_Scripting/examples/BQ40Z_bms_shutdown.lua
libraries/AP_Scripting/examples/RM3100_self_test.lua
libraries/AP_Scripting/generator/description/bindings.desc
libraries/AP_Scripting/lua_bindings.cpp
libraries/AP_Scripting/lua_bindings.h

Adds LUA bindings for the I2CDevice `transfer()` function. This is often needed over `write_register()` as I2C devices might not have 8 bit registers or desire some other custom transfer. 
An example script is also added that allows shutdown of a BQ40Z bms chip which would not be possible with LUA without the `transfer()` function. This script has functionality similar to a sibling PR that implements such functionality more generally in the AP_BattMonitor domain.

AP_Scripting: Adds I2C transfer() bindings and an example 

---

libraries/AP_DroneCAN/AP_DroneCAN.cpp
libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.cpp
libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.h

Please see commit messages for details.
Fixes the following issues:
* Correctly annotates and validates the node ID parameter set by the user
* Fix various cases where invalid node IDs could be used or stored
* Fixes 1/256 chance where a node's unique ID could not be registered
* Cleans up the code
Does not yet address the elephant in the room of multiple servers using the same storage. That will come next; this all makes that easier.
Tested on SITL and a Cube Orange on the bench using various configurations of AP_Periph nodes. Tested that the DNA database is preserved and that the DroneCAN GUI tool still works properly as well.

AP_DroneCAN: fix and clean up DNA server

---

libraries/AP_Scripting/AP_Scripting_helpers.cpp
libraries/AP_Scripting/generator/src/main.c
libraries/AP_Scripting/lua_bindings.cpp
libraries/AP_Scripting/lua_boxed_numerics.cpp

A pile of optimizations to the way bindings are generated and used in order to improve the code and reduce flash usage. Please see the commit messages individually for details.
Saves ~4.3K flash on Cube Orange. There are no user visible script changes except for error message text. Tested in SITL and on the bench through my REPL and some example scripts.

AP_Scripting: reduce flash usage

---

Tools/ardupilotwaf/boards.py
libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py

Replaces https://github.com/ArduPilot/ardupilot/pull/18479
```
pbarker@fx:~/rc/ardupilot(master)$ ./waf configure --board=CubeOrange
libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/hwdef.dat includes libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/nope which does not exist
pbarker@fx:~/rc/ardupilot(master)$ git checkout -b pr/include-file-error-better
```

Make chibios_hwdef.py include error clearer

---

ArduPlane/Plane.h
ArduPlane/mode.h
ArduPlane/mode_takeoff.cpp

A little fixup for a unresolved comment from https://github.com/ArduPilot/ardupilot/pull/25875

Plane: move `have_autoenabled_fences` to be private in `ModeTakeoff`

---

ArduCopter/crash_check.cpp
ArduCopter/mode.h
Tools/autotest/vehicle_test_suite.py
libraries/SITL/SITL.cpp

prevents looking for specific modes in the crash checker
Replaces https://github.com/ArduPilot/ardupilot/pull/20000/files
Tested the crash checker works on the bench in Loiter with a CubeOrange.
Can't easily test in SITL because of attitude reset on ground interaction

Copter: add a Mode method to disable crash check

---

Tools/autotest/rover.py
libraries/AP_Scripting/AP_Scripting.h
libraries/AP_Scripting/lua/src/loadlib.c
libraries/AP_Scripting/lua_bindings.cpp
libraries/AP_Scripting/lua_common_defs.h
libraries/AP_Scripting/lua_scripts.cpp
libraries/AP_Scripting/lua_scripts.h
libraries/AP_Scripting/tests/scripting_require_test_2.lua

The `require()` function needs the environment of the currently executing script to get the table of loaded modules. It currently does this by getting the first upvalue of the function currently used to run the script and hoping that is the environment table it needs. However, that function (and hence the upvalues) can change every time the script reschedules, so there is no guarantee that the environment table will be where `require()` needs it, and indeed it is possible to accidentally create a script where `require()` fails with a mysterious Lua error.
Correct the issue by splitting the script reference originally used by `require()` into a reference to the function used to run the script, and a separate reference specifically for the environment table, which `require()` now uses. Also …

AP_Scripting: fix failures with require()

---

libraries/AP_Scripting/lua/src/lstrlib.c
libraries/AP_Scripting/lua_scripts.cpp

In Lua, strings are the only type that come with a default metatable. The metatable must be shared by all string objects, and it is set to be the `string` library table each time that library is opened. In Ardupilot's scripting engine, the last script to load then has access to the string metatable as the library is opened fresh for each script, as its `string` library will have been set to the metatable.
Therefore, if two scripts are loaded, A first and B second, and script B executes e.g. `string.byte = "haha"`, then `string.byte()` and `s:byte()` for script B are broken. Because the metatable is shared, this also breaks `s:byte()` for script A, which violates the integrity of the sandbox.
Fix the issue by disabling the metatable setup functionality when the string libary is opened, …

AP_Scripting: adjust string metatable setup to fix sandbox integrity

---

libraries/AP_BattMonitor/AP_BattMonitor_ESC.cpp
libraries/AP_BattMonitor/AP_BattMonitor_ESC.h

DroneCAN ESCs don't provide consumed mah, so ESC battery backend currently will not calculate it. Tested with the `quad-can` model and `BATT2_MONITOR 9`.
Master:
CurrTot is always 0. 
This PR:
CurrTot is increasing. Slope is constant because the ESCs all report a constant current of 0.8 amps in SITL.

AP_BattMonitor: ESC: integrate consumed mah if not provided by ESC

---

libraries/AP_TemperatureSensor/AP_TemperatureSensor.cpp
libraries/AP_TemperatureSensor/AP_TemperatureSensor.h

If temperature sensors have a source set then there values are logged elsewhere. ESC and motor temp are logged in the ESC message, battery temperature is logged by the battery monitor. This allows those sensors to not be logged individually while keeping logging of any additional sensors, this reduces log size and makes log review less confusing.

AP_TemperatureSensor: add logging option to only log sensors with no source

---

Tools/AP_Bootloader/board_types.txt

Reserve board IDs for some new Easy Aerial boards.

board_types.txt: Reserving board IDs for Easy Aerial

---

.github/workflows/cygwin_build.yml
.github/workflows/test_environment.yml
.github/workflows/test_scripts.yml
Tools/scripts/cygwin_build.sh

A few of the git safe directory calls assume the repo is called `ardupilot`, if your fork happens not to be called that then CI fails. GitHub provides us with a environmental variable to get the correct directory which we already use in most places. The tricky one is cygwin which uses the repo name, but on a different path, so in that case I have to some messing about to extract the repo name from `GITHUB_REPOSITORY` and `GITHUB_REPOSITORY_OWNER` (see https://tom-gallacher.co.uk/articles/how-to-github-actions-repo-name/)
This also ups the timeout for the environment install scripts from 45 mins to 60 mins. These seem to run a bit slower outside of the main repo, I'm not sure why.

Actions: fix tests that don't like repos not called "ardupilot"

---

Tools/autotest/arduplane.py
Tools/autotest/quadplane.py
Tools/autotest/vehicle_test_suite.py

means we don't leave the script lying around in case of test failure

autotest: correct applet-testing scripts to use contexts for scripts

---

libraries/AP_Scripting/generator/description/bindings.desc
libraries/AP_Scripting/lua_bindings.cpp

Serial bindings were dependant on HAL_GCS_ENABLED but this is not ideal, it should be dependant on AP_SERIALMANAGER_ENABLED so that serial can function without GCS.
Tested on: CubePilot-PPPGW running AP_Periph, CubeOrangePlus running Plane

AP_Scripting: Change serial depends HAL_GCS to AP_SERIALMANAGER

---

libraries/AC_PID/AC_P.h
libraries/AC_PID/AC_PID.cpp
libraries/AC_PID/AC_PID.h
libraries/AC_PID/AC_PI_2D.cpp
libraries/AC_PID/AC_PI_2D.h
libraries/AP_Math/quaternion.h

These were unused, thankfully!
These operators let you treat your PID as a function.
So
```
Quaternion q{0,1,2,3};
q(5,6,7,8);
```
... which is just bizarre.
So remove them.
This is a no-compiler-output change on the smaller subset of boards I usually run.  I will be running this on  the larger set of boards.

Remove method operators from Quaternion and PID objects

---

Tools/ardupilotwaf/qurt.py
libraries/AP_HAL_QURT/HAL_QURT_Class.cpp
libraries/AP_HAL_QURT/UARTDriver.cpp
libraries/AP_HAL_QURT/UARTDriver.h
libraries/AP_HAL_QURT/ap_host/src/main.cpp
libraries/AP_HAL_QURT/ap_host/src/protocol.h
libraries/AP_HAL_QURT/replace.cpp

This PR adds a second mavlink instance for the QURT platform to support an onboard stream in addition to the standard ground control stream. The onboard stream is used for VIO, Object Avoidance, offboard mode, etc.

Add QURT onboard mavlink stream

---

libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.cpp

Replaces the check for a CRC of 0 with a check that the hwid is 0. Substantially reduces 1/256 chance that a particular node ID couldn't be stored.
The core locking fix will not be back-port-able so I have decided to get this done now. The storage area is already protected by semaphores in the StorageManager and HAL, the mis-use of the lock in the DNA server is not a few-line fix, and nobody has complained so far.
Tested on plane on CubeOrange using a selection of nodes and GPSes that the DNA server is preserved on upgrade and correctly registers and remembers nodes after the upgrade.

AP_DroneCAN: DNA_Server: fix handling of empty entry

---

libraries/AP_HAL_ChibiOS/GPIO.cpp
libraries/AP_HAL_ChibiOS/RCOutput.cpp
libraries/AP_IOMCU/AP_IOMCU.cpp
libraries/AP_IOMCU/AP_IOMCU.h

https://github.com/ArduPilot/ardupilot/pull/25108 Added logging of relay where it only called set and wrote the log if there would be a state change. However, because pin read was never implemented on IOMCU read would always return 0 and the pin never turn off. 
This fixes that by adding a "virtual read" method to get the commanded state of the IOMCU pin. Much like the DroneCAN pins this is NOT a real read, just a return of the last commanded state. However, this is enough to get relay to work again. 
This also adds a getter for the IOMCU GPIO mask so its state is correctly represented in the `RCOut` send text. EG With `SERVO1_FUNCTION` -1: 
```
RCOut: PWM:2-14
```
This fixes https://github.com/ArduPilot/ardupilot/issues/27648
This has been tested on CubeOrange, however in my testing and …

IOMCU: add virtual GPIO read so relays work again

---

ArduPlane/servos.cpp
ArduPlane/takeoff.cpp
Tools/autotest/arduplane.py

This patches a bug that was introduced via https://github.com/ArduPilot/ardupilot/pull/27174.
It fixes an unhandled case of `TKOFF_THR_MAX=0`, where `THR_MAX` would not be sourced as a value for the minimum throttle limit during takeoff.
The relevant conditions are:
- TKOFF_OPTIONS=0 (default)
- TKOFF_THR_MAX=0 (default)
This would result in incorrect backing-off of the minimum throttle during the climb, which @Hwurzburg spotted:
Now it behaves as it should:
Log: https://www.dropbox.com/scl/fi/akdqr9o5niv3qleexh3yd/122221_TakeoffTakeoff4.bin?rlkey=o9uykk6cm7785oxctkj17txxq&dl=0
---
Side-note:
I notice that there was significant pitch and throttle oscillation in Henry's log.
I don't think this is related to #27174, as the oscillation persists even after TAKEOFF mode has finished climbing, …

Fix for unhandled TKOFF_THR_MAX

---

ArduCopter/tuning.cpp
libraries/AC_AttitudeControl/AC_PosControl.cpp
libraries/AC_AutoTune/AC_AutoTune_Heli.cpp
libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
libraries/AC_PID/AC_P.h
libraries/AC_PID/AC_PID.cpp
libraries/AC_PID/AC_PID.h
libraries/AC_PID/AC_PID_2D.h
libraries/AC_PID/AC_PID_Basic.h
libraries/AC_PID/AC_P_1D.h
libraries/AC_PID/AC_P_2D.h

There are very few places in ArduPilot where we don't have "set_" for setters.
PIDs are one of them - make them uniform.
This is a no-compiler-output change on the smaller set of builds I run.  I will be running the full set of builds.

Rename PID setter methods to include set_

---

Tools/ros2/README.md
Tools/ros2/ardupilot_dds_tests/package.xml
Tools/ros2/ardupilot_sitl/package.xml

Tridge tried out DDS and couldn't echo the topic in the wiki. This was because the message package was not installed.
```ap/geopose/filtered [geographic_msgs/msg/GeoPoseStamped]```
* Depend on all messages used in ardupilot_sitl
* Clarify limitations of wrapping with colcon
* Link github issue to support argument passthrough
Use two terminals.
**Terminal 1:**
```
cd /path/to/your/workspace
source install/setup.bash
rosdep install --from-paths src --ignore-src
```
Expect to get geographic_msgs installed through `apt`: `ros-humble-geographic-msgs`. 
Now, run ArduPilot SITL:
```
ros2 launch ardupilot_sitl sitl_dds_udp.launch.py transport:=udp4  synthetic_clock:=True wipe:=False model:=quad speedup:=1 slave:=0 instance:=0 defaults:=$(ros2 pkg prefix …
```

Tools: ROS2: Add missing dependencies with docs

---

Tools/autotest/arduplane.py
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp

the mavlink standard specifies just one value to do either arm or disarm.  Conform to that standard
Closes https://github.com/ArduPilot/ardupilot/issues/26521

GCS_MAVLink: accept mavlink standard force arm/disarm value for forced arming

---

libraries/AP_Arming/AP_Arming.h
libraries/AP_Scripting/docs/docs.lua
libraries/AP_Scripting/examples/copter_deploy.lua
libraries/AP_Scripting/generator/description/bindings.desc

this monitors climb with raw pressure and force arms in LAND mode on descent
this script was written to help a student project dropping a copter from a rocket, but I have wanted force arm in other places

Scripting: added copter deploy example

---

Tools/AP_Bootloader/can.cpp
Tools/AP_Periph/adsb.cpp
Tools/AP_Periph/airspeed.cpp
Tools/AP_Periph/baro.cpp
Tools/AP_Periph/battery.cpp
Tools/AP_Periph/can.cpp
Tools/AP_Periph/compass.cpp
Tools/AP_Periph/efi.cpp
Tools/AP_Periph/gps.cpp
Tools/AP_Periph/hardpoint.cpp
Tools/AP_Periph/hwing_esc.cpp
Tools/AP_Periph/proximity.cpp
Tools/AP_Periph/rangefinder.cpp
Tools/AP_Periph/rc_in.cpp
Tools/AP_Periph/rpm.cpp
Tools/AP_Periph/serial_tunnel.cpp
Tools/AP_Periph/temperature.cpp

The `<msg>_encode` method always zeros the buffer up to `<msg>_MAX_SIZE` bytes so there is no need to do it before calling the function.
Saves at least 8 bytes per instance, e.g. 136 bytes on MatekL431-GPS. Tested in SITL and on a couple nodes.

Tools: remove redundant DroneCAN packet buffer initialization

---

Blimp/defines.h

these are unused.  Existing as tokens can cause us problems ion the libraries

Blimp: remove ENABLED/DISABLED defines

---

ArduPlane/ArduPlane.cpp
ArduPlane/GCS_Mavlink.cpp
ArduPlane/Log.cpp
ArduPlane/Parameters.cpp
ArduPlane/Parameters.h
ArduPlane/Plane.h
ArduPlane/RC_Channel.cpp
ArduPlane/config.h
ArduPlane/events.cpp
ArduPlane/is_flying.cpp
ArduPlane/mode.cpp
ArduPlane/mode_guided.cpp
ArduPlane/navigation.cpp
ArduPlane/parachute.cpp
ArduPlane/servos.cpp
ArduPlane/system.cpp
Tools/autotest/vehicle_test_suite.py
libraries/AP_HAL_ChibiOS/hwdef/include/minimize_common.inc
libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py

These were being used incorrectly in various places.
Compiler output is indentical apart from the hwdef inclusion

Remove ENABLE/ENABLED from Plane

---

libraries/AP_HAL/Util.h
libraries/AP_Scripting/applets/repl.lua
libraries/AP_Scripting/applets/repl.md
libraries/AP_Scripting/modules/MAVLink/mavlink_msg_SERIAL_CONTROL.lua
libraries/AP_Scripting/modules/mavport.lua
libraries/GCS_MAVLink/GCS_serial_control.cpp

Implements a reasonably comfortable REPL accessible over serial entirely as a loadable script. Also accessible using QGroundControl's MAVLink Console feature, if so configured.
Removes never-implemented `SERIAL_CONSOLE_DEV_SHELL` handling and saves a few dozen bytes on Cube Orange.
Tested in SITL and on the bench with a Cube Orange. Was able to run a couple examples through it.

AP_Scripting: add REPL applet

---

ArduCopter/Copter.h
ArduCopter/land_detector.cpp

Logging is done whenever either the count or the flags change, but not > 50Hz
This is using `test.Copter.Landing`:
```
2024-07-30 17:54:22.905: LDET
TimeUS: 178104563 µs
Flags: 242 
! LANDED
LANDED_MAYBE
! LANDING
! STANDBY_ACTIVE
WOW
RANGEFINDER_BELOW_2M
DESCENT_RATE_LOW
ACCEL_STATIONARY
! LARGE_ANGLE_ERROR
! MOTOR_AT_LOWER_LIMIT
! THROTTLE_MIX_AT_MIN
Count: 361 
2024-07-30 17:54:22.925: LDET
TimeUS: 178124555 µs
Flags: 242 
! LANDED
LANDED_MAYBE
! LANDING
! STANDBY_ACTIVE
WOW
RANGEFINDER_BELOW_2M
DESCENT_RATE_LOW
ACCEL_STATIONARY
! LARGE_ANGLE_ERROR
! MOTOR_AT_LOWER_LIMIT
! THROTTLE_MIX_AT_MIN
Count: 369 
2024-07-30 17:54:22.945: LDET
TimeUS: 178144547 µs
Flags: 242 
! LANDED
LANDED_MAYBE
! LANDING
! STANDBY_ACTIVE
WOW
RANGEFINDER_BELOW_2M
DESCENT_RATE_LOW
ACCEL_STATIONARY
! …
```

ArduCopter: add logging for land detector

---

libraries/AP_SerialManager/AP_SerialManager.cpp

Closes https://github.com/ArduPilot/ardupilot/issues/5318

AP_SerialManager: add warning iffrsky already configured

---

ArduPlane/quadplane.cpp

upgrading from 3.7 to 4.6 will not work as well as it otherwise might after this...

Plane: remove ancient parameter conversion code

---

libraries/AP_ICEngine/AP_ICEngine.cpp

We already force throttle to 0 in E-Stop, so the engine is unlikely to be idling. The key thing is to also stop the ignition and prevent the starter from turning over the engine. Just running the starter can be quite dangerous even if the engine is not going to start it gets the motor going fast and gives no warning. 
I have also added to the `STARTCHN_MIN` description to better describe what it does.

AP_ICEngine: stop engine in E-Stop

---

libraries/AP_HAL_ChibiOS/hwdef/CUAV-Pixhack-v3/hwdef.dat

allows for building this on the custom build server
custom build server doesn't give fmuv3 as an option.  Pixhawk limits the number of sensors
Closes https://github.com/ArduPilot/ardupilot/issues/26697

hwdef: add named Pixhack-v3 board

---

libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
libraries/AC_AutoTune/AC_AutoTune_Multi.h

During the clean up to try to make things easer to understand due to poorly named variables, one of those variables was deleted and another similarly named variable used in it's place.
This fixes this problem.

AC_Autotune: Fix bug introduced in #27370

---

ArduPlane/GCS_Mavlink.cpp
Tools/scripts/build_options.py
Tools/scripts/extract_features.py

This is already off in minimize_features.inc - so this will allow someone to get these back on the custom build server on small boards (or take it out on the bigger boards)
Saves 16 bytes on the smaller boards because the symbol is going away entirely.
Ran it through test_build_options.py (Feature is ~2.2kB)

ArduPlane: add build_option.py entry for Plane offboard-guided control

---

libraries/AP_BLHeli/AP_BLHeli.cpp
libraries/AP_Motors/AP_MotorsMulticopter.cpp
libraries/AP_Motors/AP_Motors_Class.cpp
libraries/AP_Motors/AP_Motors_Class.h
libraries/AR_Motors/AP_MotorsUGV.cpp
libraries/AR_Motors/AP_MotorsUGV.h

Unfortunately we have two enumerations which convey similar information but are different between Copter and Rover.
It would be nice to unify them, but that would require parameter conversion (and change-in-name of the most  critical parameter on Rover, meaning much documenation change!)
In the meantime, add proper namespacing to the enumerations.
Also changed blheli to always return "4" in one of the MSP packets.  We should really not be bearing internal ArduPilot values like this in one of these packets.  Right now in master Copter will put one number in this field and Rover will put a different one - but they're both "DShot150".... if the number is not used we should probably use a flag value rather than a real number so we don't give the wrong impression to any client.
Replaces …

Replace PWM_TYPE* with PWMType::

---

ArduPlane/RC_Channel.cpp

```
MatekF405                           *      *           *       *                 0      *      *
Pixhawk1-1M-bdshot                  *                  *       *                 0      *      *
f103-QiotekPeriph        *                                                       
f303-Universal           * …
```

Plane: move braces to be around entire case in do_aux_function

---

Tools/ardupilotwaf/ardupilotwaf.py
Tools/autotest/arducopter.py
Tools/scripts/build_options.py
Tools/scripts/extract_features.py
libraries/AP_HAL/board/linux.h
libraries/AP_HAL/board/sitl.h
libraries/AP_IBus_Telem/AP_IBus_Telem.cpp
libraries/AP_IBus_Telem/AP_IBus_Telem.h
libraries/AP_OSD/AP_OSD_ParamSetting.cpp
libraries/AP_SerialManager/AP_SerialManager.h
libraries/AP_Vehicle/AP_Vehicle.cpp
libraries/AP_Vehicle/AP_Vehicle.h

Implements: [#9419: Enhancement Request: iBus/MavLink interoperation & compatiblity](https://github.com/ArduPilot/ardupilot/issues/9419)
Wiki PR: https://github.com/ArduPilot/ardupilot_wiki/pull/6154
Originally based on [#16545: Adding ibus telemetry support via serial to arducopter](https://github.com/ArduPilot/ardupilot/pull/16545) but heavily rewritten and expanded. The old PR has not been updated in two years and I offered to take over the implementation with no objections.
I'm an experienced software engineer but C++ is not my wheelhouse and this is my first contribution to ArduPilot, so I welcome maintainer feedback especially around memory and CPU management, and potential for causing crashes. This code is tested on an fmuv3 board and has so far proven to be stable. Builds based on …

Add support for i-BUS telemetry

---

libraries/AP_HAL_SITL/system.cpp

Closes https://github.com/ArduPilot/ardupilot/issues/24245

AP_HAL_SITL: work around bug in dash

---

ArduPlane/Plane.h
ArduPlane/commands_logic.cpp
ArduPlane/mode_rtl.cpp
ArduPlane/navigation.cpp
ArduPlane/quadplane.cpp

also namespace it with the state variable which uses this type
Without this you end up with a valid `RTL` token floating around, which is kind of nasty.
```
Durandal                            *      *           *       *                 0      *      *
KakuteH7-bdshot                     *      *           *       *                 0      *      *
MatekF405                           *      *           *       *                 0      *      *
Pixhawk1-1M-bdshot                  *                  *       *                 0 …
```

Plane: use enum class for VTOL approach stage

---

ArduCopter/APM_Config.h
ArduCopter/Copter.h
ArduCopter/GCS_Mavlink.cpp
ArduCopter/Parameters.cpp
ArduCopter/RC_Channel.cpp
ArduCopter/config.h
ArduCopter/crash_check.cpp
ArduCopter/land_detector.cpp
ArduCopter/mode.h

Last vehicle which uses `PARACHUTE` like this.
Tested for no compiler output change.
Tested with test_build_features.py specifying HAL_PARACHUTE_ENABLED

Copter: use HAL_PARACHUTE_ENABLED in place of PARACHUTE_ENABLED

---

libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
libraries/AP_ESC_Telem/AP_ESC_Telem.h
libraries/AP_MSP/AP_MSP_Telem_DJI.cpp
libraries/AP_OSD/AP_OSD.cpp
libraries/AP_OSD/AP_OSD_Screen.cpp

Motor temp is rarely implemented and was used before.

OSD should display ESC temp rather than motor temp

---

libraries/AP_Motors/AP_MotorsMulticopter.cpp
libraries/AP_Motors/AP_MotorsMulticopter.h
libraries/AP_Motors/AP_Motors_Class.h
libraries/AP_Vehicle/AP_Vehicle.cpp

To enable set the mult-source bit in INS_HNTCx_OPTS and use the throttle notch

Support per-motor throttle-based harmonic notch

---

libraries/AP_DroneCAN/AP_DroneCAN.cpp
libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
libraries/AP_ESC_Telem/AP_ESC_Telem_Backend.h

Power percentage is a field in the standard ESC status DroneCAN message that didn't really have a good place in the existing logging, we now have extended logging for the DroenCAN extended status message which is a better fit.

AP_ESC_Telem: log DroneCAN power percentage in extended ESC message

---

Tools/autotest/arducopter.py
libraries/AP_BattMonitor/AP_BattMonitor.cpp
libraries/AP_BattMonitor/AP_BattMonitor.h
libraries/AP_BattMonitor/AP_BattMonitor_Params.h
libraries/GCS_MAVLink/GCS_Common.cpp

sometimes the information from a backend is very useful for logging, but not via telemetry.

Add and use Battery backend internal-use-only flag 

---

ArduCopter/mode_auto.cpp

There is a missing pos_control->update_z_controller();
Before:
After:

Copter: Fix payload place bug

---

Tools/autotest/vehicle_test_suite.py

also allow for a startup-distance-from-home allowance

Tidy autotests

---

libraries/AP_RPM/AP_RPM.cpp

Allow AP_RPM instances RPM_MAX_INSTANCES up to 9

AP_RPM: Allow more instances

---

ArduPlane/quadplane.cpp

This effectively bypasses the input shaping.
Currently this creates a step change in the position controller.
Removing this allows for the smooth setting.

Plane: do not set desired vel/accel on takeoff for quadplanes

---

ArduCopter/AP_Arming.cpp
ArduCopter/RC_Channel.cpp
ArduCopter/mode.h
ArduCopter/mode_autotune.cpp
ArduPlane/AP_Arming.cpp
ArduPlane/RC_Channel.cpp
libraries/AC_AutoTune/AC_AutoTune.cpp
libraries/AC_AutoTune/AC_AutoTune.h
libraries/AC_AutoTune/AC_AutoTune_Heli.cpp
libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
libraries/RC_Channel/RC_Channel.cpp
libraries/RC_Channel/RC_Channel.h

This adds a switch allowing the user to test gains in any mode once the autotune has been completed. If the user has used the switch they can then disarm in any mode and the gains will be saved if they are active. If the user does not use the switch then they must disarm in autotune to save gains per the current behavior. 
This allows easy testing of the tune in any mode and makes the procedure to save a little simpler. 
The load test gains functions have been updated to ensure they use the same criteria as the saving of gains for the load. Currently they were not checking if a axis had completed, only that the axis was enabled.

Autotune: Add switch to test gains after tune is complete

---

libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.cpp
libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.h

This adds a database class which contains the lock over all high level database operations (as most are read-modify-write) and does the database operations on the storage, and a static instance of it which is shared among all server instances. Please see commits for details.
There should be no behavior or logic changes at all to users using only one driver, for better or worse. Users using multiple won't have duplicate IDs assigned when attaching new nodes to different drivers without rebooting in between. They also won't risk corrupting the database due to race conditions, however unlikely that probably was in practice.
It doesn't look immediately feasible in Ardupilot right now to have the same ID on two different drivers anyway as the parameters which store the GPS node IDs can't …

AP_DroneCAN: DNA_Server: lock all high level database operations

---

libraries/AP_Math/vector3.cpp

This is a bit weird, actually.
Surely this is true of the trig functions in here too.  When we explicitly instantiate `Vector3<double>` and we're using 32-bit maths we'll use the float versions of the trig functions when determining angles and whatnot for that instantiation?
```
2024-08-08T01:51:53.6780446Z ../../libraries/AP_Math/vector3.cpp:432:9: warning: absolute value function 'fabsf' given an argument of type 'const double' but has parameter of type 'float' which may cause truncation of value [-Wabsolute-value]
2024-08-08T01:51:53.6781336Z     if (fabsF(cosv) >= 1) {
2024-08-08T01:51:53.6781583Z         ^
2024-08-08T01:51:53.6781930Z ../../libraries/AP_Math/ftype.h:50:18: note: expanded from macro 'fabsF'
2024-08-08T01:51:53.6782342Z #define fabsF(x) fabsf(x) …
```

AP_Math: correct warning on fabsF

---

libraries/AP_Logger/AP_Logger_Block.cpp

This fixes the issue where log files do not have timestamps when using flash logging

AP_Logger: correctly read file header for block logger

---

libraries/AP_GPS/AP_GPS_UBLOX.cpp

when GPS_GNSS_MODE is zero (the default) we could get stuck trying to configure the GNSS for F9P

AP_GPS: fixed unconfigured uBlox pre-arm

---

libraries/AP_Notify/AP_Notify.cpp

ChibiOS was just setting the same as the default.
now have two ifndef blocks, one of which defaults things on recognized linux boards, the other generically.
Preparation for removing the defaultin for Linux boards in this file

AP_Notify: tidy defaulting of DEFAULT_NTF_LED_TYPES

---

libraries/AP_Terrain/AP_Terrain.h
libraries/AP_Terrain/TerrainGCS.cpp

avoids trying to include headers which have not been generated"
``` …
```

AP_Terrain: gate mavlink includes on HAL_GCS_ENABLED

---

libraries/AP_Compass/AP_Compass.h

.. also MAV_COMM_NUM_BUFFERS
This is intended as a compilation fix.  It does look like we could extend the `COMPASS_CAL_ENABLED` define to cover a bit more code in the header.
Saves few bytes on some periphs as they don't do compass cal:
```
CubeOrange-periph-heavy  -64                                                      …
```

AP_Compass: avoid use of MAV_RESULT if mavlink bindings not used

---

ArduCopter/Copter.cpp
ArduCopter/Copter.h
ArduCopter/Log.cpp
libraries/AP_Motors/AP_MotorsHeli.h
libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
libraries/AP_Motors/AP_MotorsHeli_Dual.h
libraries/AP_Motors/AP_MotorsHeli_Quad.cpp
libraries/AP_Motors/AP_MotorsHeli_Quad.h
libraries/AP_Motors/AP_MotorsHeli_RSC.cpp
libraries/AP_Motors/AP_MotorsHeli_RSC.h
libraries/AP_Motors/AP_MotorsHeli_Single.cpp
libraries/AP_Motors/AP_MotorsHeli_Single.h

Currently we only log variables from AP_MotorsHeli in the HELI log message.  This PR moves the log write function down into the motors library.  This is being proposed for the following reasons:
- We can delete accessor functions in motors that are only used by the logging function.  Making the code a little less difficult to read.
- It makes it easier to add more motors data to the log (I have another PR associated with autorotations coming shortly that will make use of this)
- ~~We get a small saving in flash cost.~~
There is no functional change.
Tested in SITL.  here is an example log output:

Move HELI Logging Down into Motors

---

libraries/AP_HAL/board/qurt.h

this allows for additional compasses on I2C

QURT: allow for external compasses

---

libraries/AP_EFI/AP_EFI_Serial_Hirth.cpp
libraries/AP_EFI/AP_EFI_Serial_Hirth.h

- ThM added to help understand the engine logs better
- Updated the field names to keep the total length 64-characters long.

Adding ThM (modified throttle send to engine) to EFIS log

---

libraries/AP_ICEngine/AP_ICEngine.cpp
libraries/AP_ICEngine/AP_ICEngine.h
libraries/AP_ICEngine/AP_ICEngine_TCA9554.cpp
libraries/AP_ICEngine/AP_ICEngine_TCA9554.h

Added a parameter CRAN_DIR where 0 if forward and 1 or greater is reverse direction for Engine Cranking. This is particular with Hirth Engine where both options are available.

AP_ICEngine: Add CRANK_DIR for direction control of TCA9554 Engine

---

libraries/AP_Scripting/docs/docs.lua
libraries/AP_Scripting/generator/description/bindings.desc

We need this data available for Lua scripts

AP_Scripting: added lua binding get_last_update for efi and esc

---

ArduPlane/ArduPlane.cpp
ArduPlane/Plane.h
libraries/AP_Scripting/docs/docs.lua
libraries/AP_Scripting/examples/crosstrack_restore.lua
libraries/AP_Scripting/generator/description/bindings.desc
libraries/AP_Vehicle/AP_Vehicle.h

As discussed in #27639 on the dev call on 29 Aug 2024, added a way to get the previous WP location prior to switching out of AUTO mode and then restore it again after (in my case) doing some terrain object avoidance. This allows a plane to resume cross tracking mid mission which is required for magnetic field measurements in wilderness areas.
I changed the names proposed by @tridge in the call because:
1. getting the previous WP could conceivably be used for other purposes not just cross tracking, so I'm proposing vehicle:get_previous_location() - REMOVED based on the dev call on 12 Aug 2024
2. Restoring the previous location for crosstracking also requires setting the internal crosstrack boolean to true, so proposing to call this vehicle:set_crosstrack_start() which both sets the …

Plane: Allow a Lua script to return to a previous mission track

---

Tools/AP_Periph/AP_Periph.h
Tools/AP_Periph/Parameters.cpp
Tools/AP_Periph/Parameters.h
Tools/AP_Periph/can.cpp
Tools/AP_Periph/rc_out.cpp
Tools/ardupilotwaf/boards.py
libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
libraries/AP_ESC_Telem/AP_ESC_Telem.h
libraries/AP_ESC_Telem/AP_ESC_Telem_Backend.cpp
libraries/AP_ESC_Telem/AP_ESC_Telem_Backend.h
libraries/AP_ESC_Telem/AP_ESC_Telem_SITL.cpp

This builds on https://github.com/ArduPilot/ardupilot/pull/27771 to allow testing of both it and https://github.com/ArduPilot/ardupilot/pull/27755.
They do work:
On Periph this is not enabled by default. If it is enabled it sends each ESC in turn such that they are each sent at the set `ESC_EXT_TLM_RATE`, by default this is 10 times lower than the default ESC status message rate.  
I had to add getters into AP_ESC_Telem for periph to read the values. I also added some token values to the SITL esc backend. 
I have also added a helper to ESC telem for the get functions to check the type bitmask and if the data is stale in one call.

AP_Periph: add support for extended ESC DroneCAN message. 

---

libraries/AP_Param/AP_Param.cpp

if we can't save a parameter due to the queue size not being large enough then there is a coding error, likely the code trying to save large numbers of parameters from main thread while armed

AP_Param: throw error if we lose parameters

---

ArduCopter/AP_Arming.cpp

This just moves the autotune disarm call down inside the same function. The key thing is to be be after `hal.util->set_soft_armed(false);` so there is more room in the param save queue. See also:  https://github.com/ArduPilot/ardupilot/pull/27820
I also checked quadplane, but it is already doing it in the correct order.

Copter: Disarm: move autotune disarm call after setting soft arm false

---

ArduCopter/GCS_Mavlink.cpp
ArduPlane/GCS_Mavlink.cpp
ArduSub/GCS_Mavlink.cpp
Rover/GCS_Mavlink.cpp
Tools/autotest/arducopter.py

Replaces https://github.com/ArduPilot/ardupilot/pull/14949/files

emit MAV_RESULT_DENIED if start/stop item passed to MAV_CMD_MISSION_START

---

libraries/SRV_Channel/SRV_Channel_aux.cpp

This should speed up the find channel call so its less painful at higher rates. https://github.com/ArduPilot/ardupilot/pull/27843
~~I have not tested this, or had a in depth look to see if its a good idea.~~ 
I think this is OK, there will be slightly more lag when a function is changed, we should not be changing functions at runtime so I think its OK.

SRV_Channels: find_channel: use channel mask remove need for search over all channels

---

libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.cpp
libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.h

Followup to https://github.com/ArduPilot/ardupilot/pull/27750 .
No compiler output change until the last two commits, last two have no size change (at least on CubeOrange).

AP_DroneCAN: DNA_Server: polish db comments and organize

---

libraries/AP_GPS/AP_GPS.cpp

this allows external AHRS GPS to not be presented to AP_GPS as a possible driver

AP_GPS: allow for EAHRS_SENSORS to not include GPS

---

Tools/autotest/rover.py
libraries/GCS_MAVLink/MissionItemProtocol.cpp
libraries/GCS_MAVLink/MissionItemProtocol.h

~these would appear to be identical operations.~  clear differs from a 0-item-upload in the "clear" is only allowed disarmed, and resets a whole bunch of mission state (e.g. the loaded item).
Replaces https://github.com/ArduPilot/ardupilot/pull/15669 .  Like the PR it replaces, this allows a GCS to cancel an upload with a clear-all command as if they'd issues a mission-upload with zero items.

GCS_MAVLink: allow uploading GCS to cancel upload using mission_clear_all

---

libraries/AP_NavEKF2/AP_NavEKF2.cpp
libraries/AP_NavEKF2/AP_NavEKF2.h

this allows for disabling of external navigation data (such as visual odomotry) in EKF2. This is very useful when using EKF2 as a fallback and truth reference when testing visual odomotry on EKF3

AP_NavEKF2: added EK2_OPTIONS

---

libraries/AP_Scripting/applets/revert_param.lua
libraries/AP_Scripting/applets/revert_param.md

makes for safer live TECS tuning

AP_Scripting: added TECS tuning to revert param script

---

Tools/autotest/arducopter.py

This test had erroneous behaviour, now fixed.

autotest: fix FenceFloorEnabledLanding test

---

libraries/AP_Scripting/examples/message_interval.lua

This is a small enhancement to the message_interval lua script that is useful for forcibly setting the rate at which messages are sent to the ground station.
This comes out of the [slung payload project](https://github.com/ArduPilot/ardupilot/pull/27783) where I want to force the payload to send its position to the vehicle at 10hz.
The changes are:
- add more definitions for MAV_SEVERITY, commonly used message ids and serial port used
- add ability to disable a message completely
- added a welcome message
This has been lightly tested in SITL and on a real hardware (a Here4FC on the payload)

AP_Scripting: message_interval example handles 0hz

---

libraries/AP_HAL_ChibiOS/RCOutput.cpp

Split out from https://github.com/ArduPilot/ardupilot/pull/27029
NeoPixel updates are not pushed in the same way that motor values are, they should not be used to control minimum pulse separation. Currently this means that dshot rates are gated on NeoPixel rates.

AP_HAL_ChibiOS: do not include NeoPixel in minimum pulse separation

---

ArduPlane/quadplane.cpp

Resolves issue #27846 .
Looking at the full parameter list for Plane, Q_Frame_Class = 14 (Deca) is a valid option and going over the AP_MotorsMatrix, Deca seems to be supported for types 'Plus' and 'X'.
However when I configure my AP's frame class to be Deca, I get messages saying "Config Error: fix problem then reboot" and "Config Error: Unsupported Q_Frame_Class 14".
The deca frame is properly supported for Copter and as the quadplane vtol setup calls upon the copter frames, it should also be supported for arduplane vtol for anyone who wants to work 10 vertical motors.

Add support for deca frame in QuadPlane::setup

---

libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.cpp

This resolves a small difference between Copter/Rover and Plane/Tracker caused by slightly different versions of PR https://github.com/ArduPilot/ardupilot/pull/27698 being merged to Plane-4.5 vs master

Copter: 4.5.6-beta1 fixup

---

libraries/AC_AttitudeControl/AC_PosControl.cpp

This PR updates the comment in the is_active_xy() and is_active_z() function to accurately reflect the current logic. 
Previously, the comment mentioned that the position controller would return true if it had run in the previous 5 loop times, which was based on an older implementation with a timeout of 5000000 microseconds.
https://github.com/ArduPilot/ardupilot/commit/3c69d282373a42e79b9655d7ebedf924571e9ab3#diff-9fe7f1dfc4ef9b28922f55104d879c4b78656bc70293cde53f3c114dad535eeeR593
However, the current implementation uses a tick-based system and returns true if the position controller has been run in the previous loop (i.e., within 1 tick).
https://github.com/ArduPilot/ardupilot/pull/22766

AC_AttitudeControl: update comment in is_active_xy() (NFC)

---

libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
libraries/AP_InertialSensor/AP_InertialSensor_Backend.h

Split out from https://github.com/ArduPilot/ardupilot/pull/27029
This allows filter updates to happen at a higher rate than gyro/accel value publication

AP_InertialSensor: allow backend filters to be updated independently

---

libraries/AP_GSOF/AP_GSOF.cpp
libraries/AP_GSOF/AP_GSOF.h

Follow up from https://github.com/ArduPilot/ardupilot/pull/27058#discussion_r1691530795
This uses the sparse-endian bit manipulation code rather than the custom stuff in AP_GSOF to save flash.
Start plane, arm, takeoff, and observe it fly around in SITL. 
CI also has some checks that there are no regressions.

AP_GSOF: Use sparse endian instead of custom code

---

Tools/autotest/arducopter.py
libraries/AP_Arming/AP_Arming.cpp
libraries/AP_GPS/AP_GPS.cpp
libraries/AP_GPS/AP_GPS.h
libraries/AP_GPS/AP_GPS_Blended.cpp
libraries/AP_GPS/AP_GPS_Blended.h
libraries/AP_GPS/AP_GPS_config.h

```
Durandal                       352    *           184     304               328    352    360
KakuteH7-bdshot                480    *           496     472               656    472    472
MatekF405                      56     *           128     128               -96    80     104
Pixhawk1-1M-bdshot             96                 120     104               64     104    104
f303-Universal      *                                                                     
iomcu …
```

Make blended backend a real backend

---

libraries/AP_NavEKF3/AP_NavEKF3.cpp

if we are not going to use this value ourselves then we certainly should not add it to the replay log
A similar problem was causing replay to not work correctly.
There's the additional thing that logging may be preventing the EKF from starting, so logging here can cause Logger to throw a fatal error in SITL as it can't log the replay block.

AP_NavEKF3: do not log DefaultAirspeed if logging not started

---

libraries/AP_Mount/AP_Mount_Siyi.cpp

This fixes two problems with the AP_Mount Siyi driver to improve support for the ZT6
1. corrects the Hardware ID.  The manual says it should be '8', '2' but when testing with real hardware it appears to actually be '8','3'    
2. fixes the set-lens method (used when the pilot selects the active lens using an Aux switch or the MP AuxFunctions tab).  The order is now:
- low: RGB
- mid: Thermal
- high: Picture-in-picture RGB / Thermal
This has been tested on real hardware (a ZT6 only, I do not have a ZT30).  Below is a screen shot of MP's messages tab.  Before this change the "Mount: Siyi ZT6" message did not appear.
I think we should backport this to 4.5 because we claimed that we had ZT6 support in an earlier point release.  The ZT6 actually does partially work without this fix in that the …

AP_Mount: Siyi ZT6 hardware id and set-lens fix

---

Tools/ardupilotwaf/ardupilotwaf.py
Tools/ardupilotwaf/chibios.py

This allows automatic upload to BlueOS by running
`./waf sub --upload-blueos http://blueos.local`
Tested with:

Tools: ardupilotwaf: allow automatic upload to BlueOS

---

ArduCopter/mode_auto.cpp

we may neter the config_error_loop before we cann Copter's methods which allocate the wpnav object.
We send mavlink messages in the config error loop, one of which calls this method - so we end up with a nullptr dereference.
We might be able to find a way to stop sending this message in the config error loop, but that's likely to take some time to do....

Copter: avoid nullptr deref in config_error_loop

---

libraries/AP_RangeFinder/AP_RangeFinder.h

we log these so they should be numbered

AP_RangeFinder: number enum entries

---

Tools/autotest/rover.py
libraries/SITL/SIM_GPS.cpp
libraries/SITL/SIM_GPS_MSP.cpp
libraries/SITL/SIM_GPS_NMEA.cpp
libraries/SITL/SIM_GPS_NOVA.cpp
libraries/SITL/SIM_GPS_SBF.cpp
libraries/SITL/SIM_GPS_SBP.cpp
libraries/SITL/SIM_GPS_SBP2.cpp
libraries/SITL/SIM_GPS_Trimble.cpp
libraries/SITL/SIM_GPS_UBLOX.cpp

Replaces https://github.com/ArduPilot/ardupilot/pull/23173/files , which got forgotten and https://github.com/ArduPilot/ardupilot/pull/23173 was merged instead.
The merged PR didn't change the backends to use the information out of the supplied simulated GPS state object, so while position might move around due to jamming the accuracies did not.
Add a test that everything goes wonky.

Correct Jamming simulator use of accuracies

---

libraries/AP_DroneCAN/AP_DroneCAN.cpp
libraries/AP_DroneCAN/AP_DroneCAN.h

This fixes `AP_DRONECAN_VOLZ_FEEDBACK_ENABLED` we had the message handler but no subscribe call so it was never called. This also fixes the logging, the PWM value was logged as a `uint8_t` but the value was a float so the va list was getting confused.

AP_DroneCAN: register handle_actuator_status_Volz callback and fix logging

---

Tools/scripts/build_options.py
Tools/scripts/extract_features.py

also create an IMU category to hold IMU-specific options
``` …
```

Tools: add build option for batchsampler

---

Tools/AP_Bootloader/board_types.txt

Request a new ID for the board , HGLRCF405V4

AP_Bootloader: ID reserve for HGLRCF405V4

---

Tools/AP_Bootloader/board_types.txt

I added two new boards to the file which are 5700 and 5701, and 8 other IDs for DroneBuild drones' boards
which means IDs reserved are from 5700 to 5710

Drone build adding new board

---

ArduPlane/Attitude.cpp
ArduPlane/Parameters.cpp
ArduPlane/quadplane.cpp
ArduPlane/quadplane.h
ArduPlane/servos.cpp
ArduPlane/tailsitter.cpp
ArduPlane/tailsitter.h
ArduPlane/tiltrotor.cpp
ArduPlane/transition.h
Tools/autotest/quadplane.py

This PR applies `TKOFF_THR_MIN` throttle to forward transitions of SLT-type quadplanes.
- Apply `TKOFF_THR_MIN` throttle to transitions of SLT-type quadplanes.
- Split `quadplane.in_transition()` into forward and backward cases. SLT and tiltrotor never go into a back-transition. Tailsitter can return `in_back_transition()==true`.
In SITL the following has been tested:
- In SLT, the `TKOFF_THR_MIN` is applied during the forward transition.
- In SLT, `in_frwd_transition` is never true during a back-transition.
- By default `TKOFF_THR_MIN` is 60%. We had put it thus for classic FW takeoffs. Is it a problem that all SLT-quadplanes will now transition at 60% min throttle?

Plane: TKOFF_THR_MIN is applied to SLT transitions

---

libraries/AP_Notify/GPIO_LED_1.cpp
libraries/AP_Notify/GPIO_LED_1.h

This aligns the single led notification flashes to 2 led for LED-A and adds a Failsafe indication

AP_Notify:correct and expand 1 led flash sequences

---

libraries/AP_Notify/GPIO_LED_1.cpp

There was a space instead of an underscore.
I have no idea how this passed continuous integration.

AP_Notify: Fix compilation error in GPIO_LED_1.cpp

---

libraries/AC_WPNav/AC_WPNav.cpp

We are using ArduSub to run transects close to the seafloor (as low as 75 cm) while timed cameras capture high resolution stills. We get the best results when we move at 10 cm/s.
We are now starting to automate transects using GUIDED mode, but we've run into the lower speed limit of 20 cm/s. This limit seems arbitrary, so I'd like to reduce it to 10 cm/s.

AC_WPNav: reduce WPNAV_SPEED min to 10 cm/s

---

ArduSub/Parameters.cpp

We are running transects close to the seafloor (as low as 75 cm) and using timed cameras to capture high resolution stills. We have found it helpful to move fairly slowly while running SURFTRAK: 10 cm/s fwd, with 20 cm/s up/down.
This PR lowers the minimum for PILOT_SPEED_UP and PILOT_SPEED_DN from 50 cm/s to 20 cm/s. These values are used by SURFTRAK. The code doesn't enforce the minimums, but QGC does bark if you are outside of the range, which is confusing. This PR is a pre-req to updating QGC. (I am not sure what Cockpit does.)
We would also like to reduce the minimums for WPNAV_SPEED values. The WPNAV_SPEED minimums _are_ enforced. I'll do that in a separate PR.

Sub: reduce PILOT_SPEED_ minimums

---

Tools/autotest/arducopter.py

saw an instance where it made it to waypoint four before we registered the RC failsafe

autotest: AutoContinueOnRCFailsafe extend auto leg to avoid race

---

libraries/AP_HAL/board/esp32.h
libraries/AP_Scheduler/PerfInfo.cpp

Sadly it turns out the loop rate is so low in some situations that most/all samples were rejected as invalid and the loop rate converged very slowly or did not change. Increase the margin to be classified as such, and print out such excessively over loop times if the specific scheduling debug flag is enabled.

ESP32: more accurately calculate loop rate

---

Tools/autotest/test_build_options.py
Tools/scripts/build_options.py
Tools/scripts/extract_features.py
libraries/AP_AHRS/AP_AHRS.cpp
libraries/AP_DAL/AP_DAL.cpp
libraries/AP_GPS/AP_GPS_config.h
libraries/AP_InertialSensor/BatchSampler.cpp
libraries/AP_NavEKF3/AP_NavEKF3.cpp
libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
libraries/AP_NavEKF3/AP_NavEKF3_Logging.cpp
libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
libraries/AP_NavEKF3/AP_NavEKF3_OptFlowFusion.cpp
libraries/AP_NavEKF3/AP_NavEKF3_VehicleStatus.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.h
libraries/AP_NavEKF3/AP_NavEKF3_feature.h

This should automatically remove the EKF3 Optical fusion code based on the presence of OpticalFlow sensors.
The builds looks like this:
```
Board              AP_Periph  blimp   bootloader  copter  heli    iofirmware  plane   rover   sub
Durandal                      *       *           *       *                   *       *       *
Hitec-Airspeed     0                                                                          
KakuteH7-bdshot               *       *           *       *                   *       *       *
MatekF405                     -10392  *           -10384  -10392              -10384  -10336  -10392
Pixhawk1-1M                   *       *           *       *                   *       *       * …
```

Add EKF3 feature for optflow fusion

---

libraries/AP_Camera/AP_Camera.cpp
libraries/AP_Camera/AP_Camera.h
libraries/AP_Camera/AP_Camera_Backend.h
libraries/AP_Camera/AP_Camera_Mount.cpp
libraries/AP_Camera/AP_Camera_Mount.h
libraries/AP_Camera/AP_Camera_shareddefs.h
libraries/AP_Mount/AP_Mount.cpp
libraries/AP_Mount/AP_Mount.h
libraries/AP_Mount/AP_Mount_Backend.h
libraries/AP_Mount/AP_Mount_Siyi.cpp
libraries/AP_Mount/AP_Mount_Siyi.h
libraries/AP_Scripting/applets/camera-change-setting.lua
libraries/AP_Scripting/applets/camera-change-settings.md
libraries/AP_Scripting/docs/docs.lua
libraries/AP_Scripting/generator/description/bindings.desc

This adds a new general purpose "change_settings" method to AP_Camera (and AP_Mount) which allows us to add support for various camera settings without creating methods for each.  The vast majority of camera settings are simply a number.
The new method is used to implement three commonly used settings for the Siyi ZT6 and ZT30 thermal cameras:
- Thermal Palette (e.g. WhiteHot, BlackHot, Rainbow, etc)
- Thermal Gain (aka temperature range)
- Thermal Raw Data (stores raw temp data along with thermal images when a picture is taken)
A new change_camera_settings.lua script is also added which creates user visible parameters for these settings.
This has been tested on real hardware and below is a picture of a test where I changed the thermal palette on a ZT6 between "4" (Rainbow) and "10" …

AP_Camera/AP_Mount/AP_Scripting: add change settings method

---

Tools/cameras_gimbals/siyi-download/siyi-download.py

This adds a python script to the Tools/camera_gimbals directory that makes it easy to download images and videos from Siyi camera gimbals.
I'm not a python expert so all suggestions for improvements are very welcome.  ChatGPT has given me a fairly long list of things that could be improved so if people like I could try and improve it further.
This has been tested on a Siyi ZT6 and some sample output is shown below
```
python siyi-download.py --ipaddr 192.168.87.81 --dest images3
siyi-download.py: downloading image files
siyi-download.py: 1 directories
siyi-download.py: 13 files
siyi-download.py: downloading: http://192.168.87.81:82/photo/101SIYI_IMG/IMG_0001.jpg
siyi-download.py: downloading: http://192.168.87.81:82/photo/101SIYI_IMG/IMG_0002.jpg
siyi-download.py: downloading: …
```

Tools: siyi image and video download script

---

libraries/AP_NavEKF3/AP_NavEKF3.cpp
libraries/AP_NavEKF3/AP_NavEKF3.h
libraries/AP_NavEKF3/AP_NavEKF3_OptFlowFusion.cpp
libraries/AP_NavEKF3/AP_NavEKF3_RngBcnFusion.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.h

Saves some bytes and a little bit of time.
Passes the DAL down into the backend for it to use, too.  This will potentially be useful in a future PR - and makes sense as it should be using the same DAL as the frontend.

AP_NavEKF3: use reference for dal in frontend in place of method calls

---

libraries/AP_NavEKF3/AP_NavEKF3_AirDataFusion.cpp
libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp
libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.h

This is upstreaming some changes from Paul in a larger body of work.
Renames some variables to be more appropriate, slight formatting fix.
```
Pixhawk1-1M-bdshot                  *                  *       * …
```

Rename some variables and slight reformatting

---

libraries/AP_ADSB/AP_ADSB_uAvionix_UCP.cpp
libraries/AP_ADSB/AP_ADSB_uAvionix_UCP.h
libraries/AP_Compass/AP_Compass.cpp
libraries/AP_Compass/Compass_learn.h
libraries/AP_DDS/AP_DDS_Client.h
libraries/AP_InertialNav/AP_InertialNav.cpp
libraries/AP_InertialNav/AP_InertialNav.h
libraries/AP_L1_Control/AP_L1_Control.h
libraries/AP_Module/AP_Module.cpp
libraries/AP_Module/AP_Module.h
libraries/AP_Soaring/AP_Soaring.cpp
libraries/AP_Soaring/Variometer.cpp
libraries/AP_Soaring/Variometer.h

AP_TECS.h is the only library header which uses it after this - it needs to know the shape as it makes a method call on the singleton.

Stop including AP_AHRS.h in header files

---

Tools/autotest/ardusub.py
Tools/autotest/vehicle_test_suite.py
libraries/AP_Logger/AP_Logger.h
libraries/AP_Logger/AP_Logger_Backend.h
libraries/AP_Logger/AP_Logger_Block.h
libraries/AP_Logger/AP_Logger_File.cpp
libraries/AP_Logger/AP_Logger_File.h
libraries/AP_Logger/AP_Logger_MAVLink.h
libraries/AP_Logger/AP_Logger_MAVLinkLogTransfer.cpp

_read_fd was never unset from -1 after the log transfer was complete.

Restart logging after transfer complete when LOG_DISARMED=1

---

libraries/AP_RangeFinder/AP_RangeFinder_RDS02UF.cpp

there may be a fragment of another packet in the buffer

AP_RangeFinder: RDS02UF: avoid nuking partial messages after good parse

---

Tools/autotest/fg_plane_view.sh
Tools/autotest/fg_quad_view.sh

When synchronizing with SITL, values that did not exist in the current Flight Gear: "YKRY" were set in the "airport" parameters defined on the each shells below that started the Flight Gear simulator, so the Flight Gear did not start up.
- Tools/autotest/fg_plane_view.sh (for ArduPlane)
- Tools/autotest/fg_quad_view.sh (for ArduCopter)
Because of that, I set the "airport" parameters on the shells to the values that exist in the FlightGear simulator: "KSFO", and modified the Flight Gear to start up normally.

Tools: fixed airport parameters in Flight Gear shell scripts

---

libraries/AP_DAL/AP_DAL.cpp
libraries/AP_DAL/AP_DAL.h
libraries/AP_NavEKF2/AP_NavEKF2.cpp
libraries/AP_NavEKF3/AP_NavEKF3.cpp

```
Durandal                            -8     *           -16     -16               -16    -8     -8
KakuteH7-bdshot                     -16    *           -8      -8                -16    -16    -8
MatekF405                           -8     *           -16     -8                -16    -8     -8
Pixhawk1-1M-bdshot                  -8                 -8      -8                -8     -16    -8
f103-QiotekPeriph        *                                                                     
f303-Universal …
```

Tidy AP_DAL memory allocation and freeing

---

libraries/APM_Control/AP_AutoTune.cpp
libraries/APM_Control/AP_AutoTune.h
libraries/AP_Motors/AP_MotorsHeli_RSC.cpp
libraries/AP_Motors/AP_MotorsHeli_RSC.h
libraries/AP_Motors/AP_MotorsHeli_Swash.cpp
libraries/AP_Motors/AP_MotorsHeli_Swash.h

this pulls in many more headers, we should avoid using it whereever we can
``` …
```

Avoid use of AP_Logger.h in library headers

---

libraries/AP_Common/c++.cpp

@olliw42 this may fix the issue in #27867

AP_Common: fixed cygwin for non-SITL builds

---

libraries/AP_Baro/AP_Baro.h

Since there are already two implementations of the "healthy" method in file "AP_Baro.cpp", and they are both with clear comments, I think that "#ifdef" thing should be removed from the header file :P

AP_Baro: remove unnecessary "#ifdef HAL_BUILD_AP_PERIPH"

---

libraries/AP_Proximity/AP_Proximity_MR72_CAN.cpp

This is a fix for #27216.
I have tested this on bench by connecting an MR72 to my Cube Orange and checking if the Obstacles are being populated in the OA DB.

AP_Proximity: Include database push in MR72 driver

---

ArduCopter/AP_Arming.cpp
ArduCopter/mode.h
ArduCopter/mode_rtl.cpp

removes redundant namespacing as this is enum class
No compiler output change:
``` …
```

Copter: rename RTLAltType enumeration entries

---

libraries/AP_Mission/AP_Mission.cpp

do not modify the return packet value at all upon failure, rather than indicating invalidity with a flag value.  We return boolean for a reason.
Alternative to https://github.com/ArduPilot/ardupilot/pull/28002
Alternative to https://github.com/ArduPilot/ardupilot/pull/21799/files

AP_Mission: do not adjust ret_packet on get_item failure

---

libraries/AP_HAL_ChibiOS/hwdef/KakuteF7/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/OMNIBUSF7V2/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/include/minimize_fpv_osd.inc

I doubt there's a single one of these boards on the planet using stock firmware and smbus batteries.  If they exist, the custom build server can re-add this

hwdef: remove SMBus battery support from all minimize-fpv boards

---

libraries/AP_HAL_ChibiOS/hwdef/GEPRCF745BTHD/hwdef.dat

this is overflowing - it has an onboard baro, that will have to do..
@andyp1per @Hwurzburg @YI-BOYANG this board did not compile for ArduPlane when support was merged in https://github.com/ArduPilot/ardupilot/pull/27491

hwdef: GEPRCF745BTHD: rely on custom builds for non-BMP280 baros

---

.github/workflows/test_chibios.yml
Tools/scripts/build_ci.sh
libraries/APM_Control/AP_AutoTune.cpp
libraries/AP_Camera/AP_Camera_Logging.cpp
libraries/AP_DAL/examples/AP_DAL_Standalone/main.cpp
libraries/AP_HAL/examples/DSP_test/DSP_test.cpp
libraries/AP_InertialSensor/AP_InertialSensor_Logging.cpp
libraries/AP_NavEKF2/AP_NavEKF2.cpp
libraries/AP_NavEKF2/AP_NavEKF2_AirDataFusion.cpp
libraries/AP_NavEKF2/AP_NavEKF2_Control.cpp
libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp
libraries/AP_NavEKF2/AP_NavEKF2_VehicleStatus.cpp
libraries/AP_NavEKF2/AP_NavEKF2_core.cpp
libraries/AP_NavEKF2/AP_NavEKF2_core.h
libraries/AP_NavEKF2/LogStructure.h
libraries/AP_NavEKF3/AP_NavEKF3.cpp
libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
libraries/AP_NavEKF3/AP_NavEKF3_VehicleStatus.cpp
libraries/AP_NavEKF3/AP_NavEKF3_core.h
libraries/AP_NavEKF3/LogStructure.h

it's not needed and will slow compilation down
```
CubeOrange-periph-heavy  *                                                 
Hitec-Airspeed           *                                                 
f103-QiotekPeriph        *                                                 
f303-Universal           * …
```

AP_NavEKF2: stop including AP_DAL.h in header

---

libraries/AP_DDS/AP_DDS_Client.cpp

this is probably a flow of control problem.
But the code block below this resets some state variables before returning, and will also return false in the same case this removed block does.
Resetting that state might be very important to the caller.

AP_DDS: remove instance check for DDS Client

---

Rover/Parameters.h
Rover/defines.h
Rover/mode.cpp

Definition names were prefixed with group names. I can make definition names clearer by making the group name the class name.

Rover: Make the definition name a class type

---

Tools/autotest/param_metadata/ednemit.py
Tools/autotest/param_metadata/emit.py
Tools/autotest/param_metadata/htmlemit.py
Tools/autotest/param_metadata/jsonemit.py
Tools/autotest/param_metadata/mdemit.py
Tools/autotest/param_metadata/param.py
Tools/autotest/param_metadata/rstemit.py
Tools/autotest/param_metadata/xmlemit.py
libraries/AP_GPS/AP_GPS.cpp

Allows a marker to be added to parameter markup so that it isn't emitted to the RST, but is to everywhere else.
In lieu of doing proper parameter versioning on the build server...

Tools: param_metadata: do not emit Legacy fields to rst/Wiki

---

Tools/scripts/build_autotest.sh

our build is taking over 20hrs now, which means it gets killed and restarted at 20 hours, and if another commit has come in it means that AP_Periph may never get built at all
raise to 40 hrs

Tools: raise build time limit

---

libraries/SITL/SIM_Aircraft.cpp
libraries/SITL/SIM_SlungPayload.cpp
libraries/SITL/SIM_SlungPayload.h

This makes a few minor enhancements to our simulated slung payload
- slung payload is affected by wind (also affected by the SIM_SLUP_DRAG parameter)
- slung payload sends position updates to the main vehicle at 10hz (was 5hz)
These have been tested in SITL (and as part of PR https://github.com/ArduPilot/ardupilot/pull/27783) and below is a screen shot when the wind is coming from the East at 4m/s

SITL: slung payload minor enhancements

---

.git-blame-ignore-revs
.github/workflows/colcon.yml
Tools/ros2/ardupilot_dds_tests/ardupilot_dds_tests/plane_waypoint_follower.py
Tools/ros2/ardupilot_sitl/src/ardupilot_sitl/launch.py

Use sequential testing in ROS to prevent multiple tests from communicating traffic.
We also were only testing the test package, rather than ardupilot_sitl and ardupilot_msgs. 
Because pre-commit isn't enforced, we had some style regressions I fixed, and now it's enforced in CI.

Run tests sequentially and enforce tests in ROS 2

---

libraries/GCS_MAVLink/GCS_Signing.cpp

the signing key structure is not marked as packed, which means it has a 4 byte padding between the uint32_t magic and the uint64_t timestamp. This gets written to the database and valgrind warns about a write of uninitialised bytes. It is harmless as when the structure is read the field is not used

GCS_MAVLink: zero signing key structure for valgrind

---

ArduCopter/RC_Channel.cpp
ArduPlane/Parameters.cpp
ArduPlane/RC_Channel.cpp
Tools/autotest/test_build_options.py
libraries/AP_Parachute/AP_Parachute.h
libraries/AP_Parachute/AP_Parachute_config.h
libraries/RC_Channel/RC_Channel.cpp

Moves us closer to being able to remove `default:` clauses.
```
MatekF405                      -16    *           -56     -48               -40    -16    -8
Pixhawk1-1M-bdshot             -16                -16     -16               -16    -16    -16
iomcu                                                           *
revo-mini                      -8     *           -8      -8                -16    -8     -16
real    5m21.096s
user    133m52.460s
sys     18m32.352s
```

Use ifdefs to remove more code around RC option code

---

libraries/AP_HAL_Linux/Storage.cpp

Since we want to do a fsync on "dfd", it can not be closed before that.

AP_HAL_Linux: keep "dfd" open util fsync is done.

---

Tools/autotest/arducopter.py
libraries/Filter/HarmonicNotchFilter.cpp

Bug introduced in https://github.com/ArduPilot/ardupilot/pull/25442
I will note in passing that my review indicated this shouldn't be removed.
I have added a test to make sure this can't regress

Fix Static Notches

---

libraries/AP_AHRS/AP_AHRS_DCM.cpp
libraries/AP_AHRS/AP_AHRS_Logging.cpp
libraries/AP_AHRS/LogStructure.h

these only ever come from DCM.
`DCM` is a relatively new messae, which is why these are still in `ATT`

AP_AHRS: log DCM errrp and erryaw into DCM message

---

libraries/AP_Scripting/lua_scripts.cpp

it is possible to build for boards without storage (so no Posix, no Fatafs), but still have scripts in ROMFS.
In this case we will use the backend AP_Filesystem_backend base class when doing file operations.  This will alway fail to open directories, so when we try to load scripts from SCRIPTS_DIRECTORY it will always fail.
This leads to a warning being emitted:
Lua: State memory usage: 2796 + 5227
AP: Lua: open directory (./scripts) failed
AP: hello, world
Time has wrapped
Which isn't great.
Detect we are working on this filesystem and don't warn.
Alternative to https://github.com/ArduPilot/ardupilot/pull/27404/files
I've tested this on CubeOrange - warning is still emitted there (even if you're running scripts out of ROMFS already!)
```
STABILIZE> Got COMMAND_ACK: SCRIPTING: ACCEPTED …
```

AP_Scripting: no warning if no ./scripts and no real filesystem

---

Tools/autotest/arducopter.py
libraries/AP_AHRS/AP_AHRS.cpp
libraries/AP_AHRS/AP_AHRS.h
libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp
libraries/AP_ExternalAHRS/AP_ExternalAHRS.h
libraries/AP_NavEKF2/AP_NavEKF2.cpp

This ensures that EKF2, EKF3 and ExternalAHRS all have a common origin
Note that the origin will come from the first running backend that gets an origin, even if it is not the active backend. This is needed because EKF2 and EKF3 refuse to change origin once it is set.
The placement of this code in the update function for each backend is done as two backends may get an origin on the same loop, so we must check for an origin as soon as we call the backends update

AHRS: added common origin between backends

---

libraries/AP_Airspeed/AP_Airspeed.cpp

By checking enabled first we can be sure that `i` is a valid instance and don't try and read past the end of the arrays. This is needed if we add a scripting binding without a hard coded range check. https://github.com/ArduPilot/ardupilot/pull/28044

AP_Airspeed: healthy: check enabled first for instance range check

---

AntennaTracker/Log.cpp
ArduCopter/Log.cpp
ArduPlane/Log.cpp
ArduSub/Log.cpp
Rover/Log.cpp
libraries/AP_AHRS/AP_AHRS_Logging.cpp
libraries/AP_AHRS/LogStructure.h

We are artificially quantizing the attitude information in the attitude log message. This makes it very hard to relate to the rate logging which is logged at full resolution. There is really no reason to quantize like this other than to save a little bit of log bandwidth.
Split from https://github.com/ArduPilot/ardupilot/pull/27029

Log attitude information at full resolution

---

libraries/AP_DroneCAN/AP_DroneCAN_serial.cpp

This sets the protocol field in the tunnel.Targetted DroneCAN message, which is used by the AP_DroneCAN_serial class for doing serial over CAN.
This can be useful, e.g., for recipients to check that they get what they expect to get.
Tested on a MatekH743 loaded with ArduPlane.

AP_DroneCAN: Set protocol in tunnel.Targetted message

---

libraries/GCS_MAVLink/GCS_Common.cpp

this is going to be used for changing the rate of a specific instance of a message at some stage
we have to reject it for now so that when the index is used the GCS is told that their message is invalid in this older version of the autopilot

GCS_MAVLink: reject SET_MESSAGE_INTERVAL commands with p3 set

---

libraries/AP_Scripting/AP_Scripting_config.h

AP_FILESYSTEM_READING_ENABLED isn't quite right as we can't read scripts from @SYS.

AP_Scripting: tweak conditions for scripting-requires-filesystem

---

libraries/AP_HAL_ChibiOS/hwdef/MatekL431-Periph/hwdef.dat

Saves enough flash to get it building again (11K now free). These backends are default for other boards and so are built in CI.
Tested that it builds and still works with a ublox GPS. Solution as discussed on dev call and https://github.com/ArduPilot/ardupilot/pull/27659 .

hwdef: remove non-ublox GPSes from MatekL431-Periph

---

Tools/AP_Periph/can.cpp

It is technically legal to receive an "allocation" of the broadcast node ID. Fortunately, this was already ignored by `canardSetLocalNodeID`, though it would trigger an assertion failure if those were enabled.
Fix by rejecting that ID. There is effectively no change in behavior (except possibly fixes using moving baseline GPSes) but the code now correctly ignores that ID and retries the allocation as it did before.
Tested on CubeOrange (with artificially limited DNA database size) and a pile of MatekL431 boards. Costs a handful of bytes.

AP_Periph: reject allocation of broadcast node ID

---

Tools/ardupilotwaf/chibios.py

this fixes an issue when developing for ChibiOS AP_Periph targets where loading the elf file in gdb doesn't allow it to run as it doesn't have the correct AP_Periph signature (crc, board type etc)
This patch modifies the elf file to fill in the signature, so when you load in gdb the bootloader will be able to run the signature checks and load the firmware

waf: fixed app signature in elf files

---

libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.cpp
libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.h

While technically legal, it's unlikely to have been tested and an allocatee might do silly things.
Also makes the logic a bit more clear, improves the failure message, and some other minor savings.
Tested on CubeOrange (with artificially limited DNA database size) and a pile of MatekL431 boards. Saves a couple hundred bytes.

AP_DroneCAN: DNAServer: don't "allocate" broadcast ID

---

Tools/AP_Periph/Parameters.cpp
Tools/AP_Periph/can.cpp

Properly document the range and behavior.
Rename storage variable as it doesn't connect to the DNA preferred ID feature.
Tested on CubeOrange and MatekL431 ensuring that the `CAN_NODE` parameter still works as expected.

AP_Periph: clean up node ID parameter handling

---

Tools/ros2/README.md
Tools/ros2/ardupilot_dds_tests/ardupilot_dds_tests/plane_waypoint_follower.py
Tools/ros2/ardupilot_dds_tests/package.xml
Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_geopose_msg_received.py
Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_time_msg_received.py

* Add geopose test
* Add missing deps
* Reduce some duplication
```bash
source /opt/ros/humble/setup.bash
colcon build --packages-up-to ardupilot_dds_tests
colcon --log-level DEBUG test --packages-select ardupilot_dds_tests --event-handlers=console_direct+
```
The heading reported by ROS2 never matches CMAC's configured heading. It's not clear whether the heading configured in `locations.txt` is magnetic or true north, but it's more off than that.

Tools: ros2: Add geopose test

---

Tools/environment_install/install-prereqs-arch.sh
Tools/environment_install/install-prereqs-openSUSE-Tumbleweed.sh
Tools/environment_install/install-prereqs-ubuntu.sh

If an apt package is available for a python dependency, I think we should try to use that.
Doing `python3 -m pip install pexpect` opens us to completely breaking as soon as the next major version comes out.
Instead, we can rely on our packaging team at canonical to ensure our packages are compatible.
Let's see how CI does. 
If we like this approach, it's an alternative to virtual environments for Ubuntu jammy: https://github.com/ArduPilot/ardupilot/issues/26137
Same for 
* python3-future
* python3-pexpect
* And I propose all the rest of the python packages that we can, we switch to apt, especially setuptools

Tools: Use apt for pexpect and allow system packages in the virtual environment

---

ArduCopter/radio.cpp
ArduPlane/radio.cpp
Blimp/radio.cpp
Rover/radio.cpp
Tools/autotest/arduplane.py
libraries/AP_MSP/AP_MSP_Telem_Backend.cpp
libraries/RC_Channel/RC_Channel.h
libraries/RC_Channel/RC_Channels.cpp

Setting a bad rcmap entry doesn't just hard-fault the autopilot but ensures you have to reset all of your parameters before you have a working autopilot again.
This has been the case for a very long time.  But perhaps we should fix it?
Checking the library return values for nullptr doesn't help if we have already persisted the parameters - next time you boot you'll not populate e.g. `channel_roll` with a valid pointer and will then segfault.  So we use a "dummy channel" instead.
A new record for shortest autotest.

Avoid nullptr dereference on bad rcmap value entry

---

ArduCopter/mode.h
ArduCopter/mode_auto.cpp
ArduCopter/takeoff.cpp

This resolves issue https://github.com/ArduPilot/ardupilot/issues/28060 by resolving the mixup of variable names in _AutoTakeoff::get_position() method.
I've also renamed the method and added some comments in the hope that this makes its purpose a little more clear.
This has been lightly tested in SITL using a simple mission consisting of just a takeoff and a waypoint command.
Below is a screenshot of the target position (in the Easterly direction) and "before" we see a slight jump while "after" it is gone.
Thanks to @peterbarker for helping with the investigation and fix

Copter: auto mode takeoff complete pos fix

---

libraries/GCS_MAVLink/ap_message.h

In ap_message.h we use the flag `AP_MAVLINK_MSG_HIGHRES_IMU_ENABLED` without having it defined yet. This can be solved by either including "GSC_config.h" or removing the flag from the enum definition.
Open to discuss the alternatives!
Referencing comment #27007
May relate to [https://github.com/chobitsfan/mavlink-udp-proxy/issues/3](chobitsfan/mavlink-udp-proxy/issues/3)

GCS_MAVLink: fix includes to ap_message

---

Rover/mode.h
Rover/mode_circle.cpp

Two fixes for circle mode in Rover:
- Correct reporting of target position and distance/bearing to target
- Stop circling (stop the vehicle) if it's unable to properly track the circle. This is usually due to the vehicle not being able to turn fast enough for a given speed/radius circle.

Rover: Circle mode enhancements

---

libraries/AP_ESC_Telem/AP_ESC_Telem.cpp

When the #27755 (well, the original PR that #27755 was based on anyway) was first opened, #26252 had not been merged yet. #26252 refactored a bit, but the change was not applied to #27755. This PR fixes that.
This should not change the behavior of the code, but it might not be binary identical.

AP_ESC_Telem: tidy old calls to _telem_data

---

Tools/ros2/ardupilot_dds_tests/package.xml
Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_geopose_msg_received.py

CI was disabled (realized today). It didn't run this PR before it went in. 
Test pipeline:
*  https://github.com/ArduPilot/ardupilot/actions/runs/10785613485/job/29911116554?pr=28057
* https://github.com/Ryanf55/ardupilot/actions/runs/10785606730/job/29911099966
Issue reported by @tpwrules here: https://github.com/tpwrules/ardupilot/actions/runs/10785398006/job/29910520865

Tools: Hotfix missing 3 in python-scripy

---

Tools/ardupilotwaf/boards.py
Tools/autotest/rover.py
Tools/autotest/sim_vehicle.py
Tools/ros2/ardupilot_sitl/CMakeLists.txt
Tools/scripts/build_ci.sh
Tools/scripts/build_options.py
libraries/AP_Networking/AP_Networking_Config.h
wscript

this makes it easy to configure with any option from build_options.py, with tab completion
Note that the build_options.py table takes an optional enable-XXX label to allow us to replace some of the existing options (eg. --enable-ppp and --disable-ekf3)
we end up with options like this: 
```
--enable-ppp        Enable PPP networking
--disable-ppp       Disable PPP networking
--enable-DISPLAY    Enable I2C Displays
--disable-DISPLAY   Disable I2C Displays
--enable-LED_CONTROL
Enable MAVLink LED Control
--disable-LED_CONTROL
Disable MAVLink LED Control
--enable-NOTIFY_NCP5623
Enable NCP5623 LED
--disable-NOTIFY_NCP5623
Disable NCP5623 LED
--enable-NOTIFY_NEOPIXEL
Enable NeoPixel
--disable-NOTIFY_NEOPIXEL
Disable NeoPixel
--enable-NOTIFY_PROFILED
Enable ProfiLED
--disable-NOTIFY_PROFILED …
```

waf: allow any custom build option to be specified in waf configure

---

libraries/AP_Scripting/docs/docs.lua
libraries/AP_Scripting/generator/description/bindings.desc

can be used for offboard navigation systems
we had this in mavlink but not in lua.

AP_Scripting: add handle_external_position_estimate binding

---

libraries/AP_EFI/AP_EFI.cpp

- Convert temperatures Celsius to match the docs
- Fix format specifier for CHT2

AP_EFI: fix ECYL log message

---

libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.cpp
libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.h

Change the DataFlash log message names in the VectorNav external AHRS driver to make the log messages better indicate they are from the VectorNav driver.

VectorNav: rename dataflash log message names

---

libraries/AP_Scripting/applets/advance-wp.lua
libraries/AP_Scripting/applets/advance-wp.md

Advance Waypoint (`advance-wp.lua`) allows for advancing the current mission waypoint via an RC switch. When the RC switch state is high, the mission waypoint is advanced to the next waypoint (wraps back to WP 1 if the end of the mission is reached).
PR is an evolution of the helper script from [this discussion](https://discuss.ardupilot.org/t/scripted-magfit-flightpath-generation/97536).
Adds configurable parameters and optional features for relocating waypoints using the vehicle (or an ArduPilot enabled survey tool, as described in the markdown).

AP_Scripting: add advance-wp.lua

---

ArduPlane/quadplane.cpp
ArduPlane/quadplane.h

this sets a minimum distance to use the fixed wing approach logic. It is an alternative to just disabling the approach with Q_OPTIONS which some users do to avoid some short distance problems. This allows the approach to still be used for longer distances in QRTL but have it disabled for shorter distances
The approach code is really needed for longer distances to allow the full fixed wing terrain following logic to be used

Plane: added Q_APPROACH_DIST

---

libraries/AP_AHRS/AP_AHRS.cpp
libraries/AP_NavEKF3/AP_NavEKF3.cpp

I think the magic number 255 is the maximum value of UINT8.
I would like to attach meaning to 255.

use UINT8_MAX as flag value in place of 255

---

libraries/AP_MSP/AP_MSP_Telem_Backend.cpp
libraries/AP_MSP/AP_MSP_Telem_Backend.h

source: http://www.multiwii.com/wiki/index.php?title=Multiwii_Serial_Protocol

AP_MSP: MSP_RAW_GPS cog should be decidegrees not centidegrees

---

libraries/AP_EFI/AP_EFI_Serial_Hirth.cpp
libraries/AP_EFI/AP_EFI_Serial_Hirth.h

There is no crankshaft sensor status reported by this EFI. This line is misleading and should be removed. The sensor health bitmask is already logged elsewhere.

AP_EFI: Hirth: fix sensor health flags

---

libraries/AP_ExternalAHRS/AP_ExternalAHRS.h

The GPS week value of 0xFFFF is a hold-over from MSP. None of the EAHRS systems set that value now, and it's not handled in any special way in AP_GPS.

AP_ExternalAHRS: Remove incorrect 0xFFFF default comment

---

libraries/AP_ExternalAHRS/AP_ExternalAHRS_InertialLabs.cpp
libraries/AP_ExternalAHRS/AP_ExternalAHRS_InertialLabs.h
libraries/SITL/SIM_InertialLabs.cpp
libraries/SITL/SIM_InertialLabs.h

Fix bugs and add the new data handling

AP_ExternalAHRS: Actualize handler and simulator of the Inertial Labs EAHRS

---

ArduCopter/failsafe.cpp

In the `init_ardupilot` method, failsafe is forced enabled after initialization. 
If previous settings are used on reboot, this forced enablement seems unnecessary. 
Therefore, assign the failsafe enable flag to a variable area that is initialized to 0 along with a cold reset.

Copter: The failsafe enable flag should be cleared on cold reset

---

Tools/AP_Periph/AP_Periph.h
Tools/AP_Periph/can.cpp

* currently we allow can_printf call from lua threads, which calls canard_broadcast, and is not threadsafe. This PR wraps canard_broadcast and processRx/Tx with mutex lock, so we don't end up corrupting the allocator and hence creating unsafe situation.
Especially needed for CAN PPPGW devices

AP_Periph: make can broadcast threadsafe

---

AntennaTracker/GCS_Mavlink.cpp
ArduCopter/GCS_Mavlink.cpp
ArduPlane/GCS_Mavlink.cpp
ArduSub/GCS_Mavlink.cpp
Blimp/GCS_Mavlink.cpp
Rover/GCS_Mavlink.cpp
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp
libraries/GCS_MAVLink/ap_message.h

This adds support for the new airspeed message. It does not remove the old named value float, maybe we should have them both until we get GCS support.
We need a similar message for baro and then we can remove the three scaled pressure messages.

AP_Airspeed: Add support for new message

---

libraries/AP_OpenDroneID/AP_OpenDroneID.cpp

Based on my report on discord:
Problem arises when:
- ArduPilot compiled with ``--enable-opendroneid``
- ``DID_ENABLE`` set to 0
- init and update functions do not do anything but pre_arm_checks still fail.
Should pre_arm_checks also be skipped or there should be a different error message like DID_ENABLE is not allowed to be 0 when compiled with --enable-opendroneid.
Currently one of the pre_arm_checks will fail but there's no indiciation of what exactly the problem is. A better error message or disabling pre arm checks might save time for users.
This PR adds a better error message to report that ``DID_ENABLE`` is not allowed to be 0 when compiled with ``--enable-opendroneid``.

Copter: Give better error in opendroneid build when DID_ENABLE=0.

---

ArduPlane/radio.cpp
libraries/AP_DroneCAN/AP_DroneCAN.cpp
libraries/AP_HAL/RCOutput.h

Without this, twin motor planes with DroneCAN ESCs need to set a
dummy throttle channel for the `scale_esc_to_unity` to work correctly.
Worse yet, if you don't do this, your ESCs will receive a max throttle command while disarmed as soon as the safety switch is disengaged.
The first commit prevents the max-throttle symptom when esc scaling is unconfigured or misconfigured (costs 16 bytes). The second commit allows the left/right throttle servos to be used to configure esc scaling (costs 24 bytes).
Params to reproduce this bug on CubeOrange, disengage the safety switch and look at RawCommand coming out of the autopilot in DroneCAN GUI
```
CAN_D1_UC_ESC_BM 3
CAN_P1_DRIVER 1
CAN_P2_DRIVER 1
SERIAL6_PROTOCOL 2
SERVO1_FUNCTION 74
SERVO1_MAX 2000
SERVO1_MIN 1000
SERVO2_FUNCTION 73
SERVO2_MAX …
```

DroneCAN: fix dangerous bug for twin-motor Planes

---

Tools/ardupilotwaf/ap_library.py
Tools/ardupilotwaf/chibios.py
Tools/ardupilotwaf/git_submodule.py
wscript

Backport of https://github.com/ArduPilot/ardupilot/pull/26889.

Plane: backport support for Python 3.12 to 4.5

---

libraries/AP_ExternalAHRS/AP_ExternalAHRS_InertialLabs.cpp

The ILABS_UNIT_STATUS2_GNSS_FUSION_OFF flag does not exist in UNITSTATUS.
I think the decision should be made based on the GNSS-related flags in UNITSTATUS and UNITSTATUS2.

AP_ExternalAHRS: Correct the judgment

---

libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
libraries/AC_AttitudeControl/AC_AttitudeControl.h

This PR moves the movement of target position to the first step of the attitude controller where it knows the dt.
Currently we assume the next dt will be the same as the last dt. This causes noise in the rate controllers when dt changes and high rates are being requested.
Limitations in ATT logging has made this difficult to observe previously.
Before:
After:

AC_AttitudeControl: Fix dt update order

---

libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.cpp
libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.h

Avoids confusing the user and removes weirdness with multiple servers sharing the same storage. Does leak the registration for the old ID but in the unlikely event the table fills up the user can simply reset the database.
We keep the check for an existing registration to avoid dirtying the storage every boot unnecessarily. We also factor out the deletion of an existing registration (which is very unlikely but technically possible) to save some flash.
Tested upgrades and node ID changes on CubeOrange with some MatekL431 boards.

AP_DroneCAN: DNAServer: avoid resetting when server node ID changes

---

libraries/AP_HAL_Linux/Storage.cpp

- Fixed the fd leaking issue in "_storage_create" found by @peterbarker
- Remove the unnecessary call of "unlinkat" in "_storage_create"
- Simplify the implementation of "init"

AP_HAL_Linux: file descriptor leaking and other issues in "Storage" of Linux

---

ArduCopter/Copter.cpp
ArduCopter/Log.cpp
ArduPlane/quadplane.cpp
ArduSub/ArduSub.cpp
Tools/autotest/arducopter.py
libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
libraries/AC_AttitudeControl/AC_AttitudeControl.h
libraries/AC_AttitudeControl/AC_AttitudeControl_Logging.cpp
libraries/AC_AttitudeControl/LogStructure.h
libraries/AP_Scheduler/AP_Scheduler.cpp
libraries/AP_Scheduler/AP_Scheduler.h

Introduces a new high rate attitude message - ANG - to replace the use of ATT for the attitude controller.

Attitude Logging (ANG)

---

Tools/scripts/build_options.py
libraries/AP_HAL_ChibiOS/hwdef/f103-GPS/hwdef.dat

this target is overflowing as someone is trying to add a new compass..
this set was determined using `extract_features.py` on a compiled binary

hwdef: f103-GPS: explicltly nominiate compass backends supported

---

Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_geopose_msg_received.py

Add a test to prove the reported heading on the geopose interface is REP-103 compliant.
This matches the proposed clarifications here, and can be used as an example in the REP.
https://github.com/ros-infrastructure/rep/pull/407

Add test for geopose heading

---

libraries/AP_Airspeed/AP_Airspeed_ASP5033.cpp

This prevents a false negative ID check for the cases when the AP is rebooted independently of the sensor, with the latter keeping a temporary ID that was set during initialization

AP_Airspeed: Don't fail on REG_WHOAMI_RECHECK_ID

---

libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.cpp

Please see code for details. There are sure to be a lot of variables but this change demonstrably makes the allocation message count (and therefore real allocation time, though I did not measure this precisely) lower and more consistent.
Number of allocation messages with 3x MatekL431-Periph nodes and Cube Orange (6 trials):
before: 44, 36, 35, 92, 107, 41
after: 28, 28, 28, 28, 26, 28

AP_DroneCAN: DNAServer: optimize allocation strategy

---

Tools/ardupilotwaf/dronecangen.py

Have the build depend on the input message definition files and the generator source code so that the code is regenerated if either change.
Also remove the separate env variable for the compiler path as we want to look through the directory and neither can be set by the user anyway AFAIK.

Tools/ardupilotwaf: improve dronecangen dependency tracking

---

libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.cpp
libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.h

Nothing is known to support it so it can't be tested. Removing it saves flash and reduces complexity.
I would prefer to add support for it to AP_Periph so it can be tested but tridge said he would prefer to just remove support. Saves 168 bytes of flash on Cube Orange. Would consume 32 bytes to add support to AP_Periph.
Tested on the bench that allocation of new and existing nodes works properly still.

AP_DroneCAN: DNAServer: remove preferred allocation support

---

libraries/AP_HAL_ChibiOS/Device.cpp

HI there
This PR description.
-> Check nullptr before using the  'name' variable assigned from malloc()

AP_HAL_ChibiOS: check nullptr 'name' variable

---

libraries/AP_OSD/AP_OSD.h
libraries/AP_OSD/AP_OSD_ParamScreen.cpp

Tested in SITL using `--osd`
Extracted from https://github.com/ArduPilot/ardupilot/pull/28089

AP_OSD: don't go via RCMap singleton to get RPTY RC channels

---

libraries/GCS_MAVLink/GCS_Common.cpp

Fixes builds that includes MAVLink and Airspeed without AHRS, for example periph heavy. This bug was introduced in https://github.com/ArduPilot/ardupilot/pull/22709.

GCS_MAVLink: Fix Airspeed without AHRS

---

Tools/environment_install/install-prereqs-ubuntu.sh

Remove  ubuntu bionic support. This makes https://github.com/ArduPilot/ardupilot/pull/28056 easer because `python3-pygame` is available in Ubuntu focal (20) and onward.
Ubuntu 18.04 (bionic) is EOL.
https://ubuntu.com/18-04

Tools: Remove bionic support for ubuntu setup

---

ArduSub/mode_guided.cpp

This PR slightly improves sub guided mode:
* Test the destination against the fence before changing the submode. With this change, the submode is not changed if we return false. This matches the behavior in copter.
* Initialize `sub.yaw_rate_only` in all `guided_set_*` calls, so that any submode change starts from the same default
* Fix a few comments

Sub: small guided mode fixes

---

.github/workflows/test_chibios.yml
Tools/scripts/build_ci.sh

we really just care that EKF2 builds here, the board really isn't that important

CI: build CubeRed-EKF2 not CubeOrange-EKF2 in CI

---

libraries/AP_HAL_ChibiOS/hwdef/CubePilot-PPPGW/hwdef.dat
libraries/AP_Networking/AP_Networking.h
libraries/AP_Networking/AP_Networking_tests.cpp

Tested working on CubePilot PPPGW

Add support for Connector loopback testing for Ethernet

---

AntennaTracker/tracking.cpp

I'm playing with Olimex g-Link GPS/LTE (Qualcomm EC25) unit for my setup and I've noticed that it seem to be throwing zero coordinates at some stage during the module startup. I can't seem to pinpoint the exact source of the message in my telemetry log, but the dataflash log from the tracker pretty convincingly shows that there were a couple of zero datapoints incoming so it's definitely that can somehow happen in the wild:
Consequently, the tracker wanted to execute a sharp turn since its target jumped about 130° and since it's in the middle of the ocean very far away from me, the minimum tracking distance condition did not help either.
This change prevents such behavior from ever taking place.
I wanted to add this to my [bigger WIP PR on the …

AntennaTracker: refuse to track (0;0)

---

libraries/GCS_MAVLink/GCS_Common.cpp

Since it returns the same result, we'll add it to the condition of the IF statement. 
Regarding memory, the TEXT segment decreases, the BSS segment increases, and the overall size remains unchanged.
AFTER
BUILD SUMMARY
Build directory: /home/parallels/work2/ardupilot/build/fmuv3
Target          Text (B)  Data (B)  BSS (B)  Total Flash Used (B)  Free Flash (B)  External Flash Used (B)
bin/arducopter   1558257      3892   192868               1562149          518604  Not Applicable  
BEFORE
BUILD SUMMARY
Build directory: /home/parallels/work2/ardupilot/build/fmuv3
Target          Text (B)  Data (B)  BSS (B)  Total Flash Used (B)  Free Flash (B)  External Flash Used (B)
bin/arducopter   1558261      3892   192864               1562153          518604  Not Applicable

GCS_MAVLink: Add conditions and delete the same processing

---

libraries/AP_TemperatureSensor/AP_TemperatureSensor_MLX90614.cpp

There was conversion error in the PR #26886 which I fixed here, while testing I haven't used `KELVIN_TO_C` for conversion from kelvin to Celsius degrees.
Correct formula for conversion:
`Temperature_read(in celsius degrees) = _crude_value * 0.02 - 273.15`
I have just tested the corrected one. I apologize for the inconvenience caused.

AP_TemperatureSensor: new MLX90614 sensor backend driver conversion fix

---

Tools/AP_Bootloader/board_types.txt

Reserve bootloader ID FlysparkF4 1361. The hwdef is under development and a new PR will be coming soon

AP_Bootloader: reserve new board ID for FlysparkF4

---

Tools/scripts/build_options.py

Tools: build_options.py: add AP_BATTERY_SUM_ENABLED option

---

ArduCopter/autoyaw.cpp
ArduCopter/mode.cpp
ArduCopter/mode.h
ArduCopter/mode_acro_heli.cpp
ArduCopter/mode_althold.cpp
ArduCopter/mode_autorotate.cpp
ArduCopter/mode_autotune.cpp
ArduCopter/mode_flowhold.cpp
ArduCopter/mode_loiter.cpp
ArduCopter/mode_poshold.cpp
ArduCopter/mode_sport.cpp
ArduCopter/mode_stabilize.cpp
ArduCopter/mode_stabilize_heli.cpp
ArduCopter/mode_systemid.cpp
ArduCopter/mode_zigzag.cpp

We always pass the same value into the function so we can move the getting of the value down.

Copter: don't pass `channel_yaw->norm_input_dz()` into `get_pilot_desired_yaw_rate`

---

AntennaTracker/GCS_Mavlink.cpp
ArduCopter/GCS_Mavlink.cpp
ArduPlane/GCS_Mavlink.cpp
ArduSub/GCS_Mavlink.cpp
Blimp/GCS_Mavlink.cpp
Rover/GCS_Mavlink.cpp

Avoids debug message spam about sending an unknown message on ESP32 where this is disabled.
Issue not caught with https://github.com/ArduPilot/ardupilot/pull/22709

vehicle: only send airspeed when enabled

---

Tools/autotest/ardusub.py
libraries/AP_Scripting/examples/sub_test_synthetic_seafloor.lua

The current test.Sub.SimTerrainSurftrak noise configuration is causing ~more~ test failures ~than we'd like~.
This PR adds `outlier_good_sq_limit` to the configuration. If the error exceeds `outlier_good_sq_limit` then the signal quality drops from 100 (best) to 50 (bad). `Sub::read_rangefinder()` tests for this, so large outliers are rejected. This should ~minimize~ eliminate test failures, and it also exercises the sq test in `Sub::read_rangefinder()`.
Edit: I also fixed some test names and a few typos

autotest: large outliers in sub terrain test have low sq

---

Tools/environment_install/install-prereqs-arch.sh
Tools/environment_install/install-prereqs-openSUSE-Tumbleweed.sh
Tools/environment_install/install-prereqs-ubuntu.sh

Nicer for the users. Split out from https://github.com/ArduPilot/ardupilot/pull/28080/ .

Tools/environment_install: print how to activate venv if not default

---

libraries/AP_CANManager/AP_CANManager.cpp
libraries/AP_CANManager/AP_CANManager.h

this prevented MissionPlanner MAVCAN UI from working reliably as the CANManager could think we are registered when we are not
This particularly impacted MissionPlanner as it does a sequence of registration of CAN forwarding followed by de-registering (ie. sending bus -1) before finally registering fully
Fixes #28175

AP_CANManager: fixed de-registering CAN forwarding

---

libraries/AP_Filesystem/AP_Filesystem_ESP32.cpp
libraries/SITL/SIM_EFI_MegaSquirt.cpp

A couple minor things in other modules split out from https://github.com/ArduPilot/ardupilot/pull/28080

esp32: fix warnings in preparation for ESP-IDF upgrade

---

libraries/AP_GPS/AP_GPS_UBLOX.cpp
libraries/AP_GPS/AP_GPS_UBLOX.h

It's neater and fixes some initialiser-list-order problems

AP_GPS: move initialisation of some members into header

---

ArduCopter/afs_copter.cpp
ArduCopter/mode.h

Another extract from https://github.com/ArduPilot/ardupilot/pull/28110. This removes as mode number switch and replaces with a mode method that returns the advanced failsafe mode category.

Copter: add and use new `afs_mode` mode method

---

libraries/AP_DroneCAN/AP_DroneCAN.h

bad ordering was leading to dronecan dna server getting initialised before canard interface leading to bad index setup
This should have been caught by compiler and by the looks of it, wasn't. Have we got contructor initialise ordering check turned off?

AP_DroneCAN: Fix constructor initialization order

---

libraries/AC_AttitudeControl/AC_AttitudeControl_Sub.cpp
libraries/AC_AttitudeControl/AC_AttitudeControl_Sub.h

makes it look like multi ie. legible
We need to reorder initialisation in the PID iniit method being used in the old code.  This change means one less place to get right.

AC_AttitudeControl: use AC_PID defaults to tidy rate Sub PID initialisation

---

libraries/AP_WheelEncoder/AP_WheelRateControl.h

the existing constructer sets a slew rate limit to 0.2
This is essentially a missing patch from a previous series of PRs which moved dt from being a member variable to being passed into the update call for the PID

AP_WheelEncoder: correct initialisation of WheelRateController object

---

Tools/AP_Bootloader/board_types.txt

the gap between 7,109 and 10,000 may be useful for reserving a range for some other function in the future.  We have vast numbers of IDs in gaps which should be filled instead.

AP_Bootloader: add request to fill gaps rather than add to end

---

ArduPlane/takeoff.cpp

4.5 backport is here: https://github.com/ArduPilot/ardupilot/pull/28179

Plane: correct the ability to disable the takeoff atititude checks

---

libraries/AP_Compass/AP_Compass_HMC5843.cpp

Replaces https://github.com/ArduPilot/ardupilot/pull/24832/files
Tested on a revo-mini (broke it / fixed it to make sure this codepath was crossed)

AP_Compass: use memcmp to check whoami result code from HMC5843 device

---

ArduCopter/precision_landing.cpp
ArduPlane/system.cpp
Rover/precision_landing.cpp
libraries/AC_PrecLand/AC_PrecLand.cpp

this value determines the size of buffers allocated.
Too high and you waste RAM.  Too low and you probably won't store data correctly.
Replaces https://github.com/ArduPilot/ardupilot/pull/13842/files

correct initialisation of PrecLand buffers

---

libraries/AP_Filesystem/AP_Filesystem_config.h
libraries/AP_Mount/AP_Mount_config.h
libraries/AP_SerialManager/AP_SerialManager_config.h
libraries/AP_Terrain/AP_Terrain.h
libraries/AP_Terrain/AP_Terrain_config.h

Having trouble avoiding loops involving filesystem config and logger; adjust includes to prevent unnecessary include paths.

Adjust includes to help prevent loops

---

libraries/AP_Filesystem/posix_compat.h
libraries/AP_HAL_ChibiOS/hwdef/common/stdio.h
libraries/AP_Scripting/lua/src/loslib.c

tmpnam is never linked and not necessary, and naming it/redefining it introduces problems on platforms that do have a definition.
Additionally remove the definition as it was only ever used by Lua.
No compiler output change. Part of #28080

AP_Scripting: remove dependency on tmpnam

---

libraries/AP_DDS/AP_DDS_Client.cpp
libraries/AP_DDS/AP_DDS_Client.h

Add parameters to set the time out and number of retries when the DDS client attempts to ping the XRCE agent. Allows the user to increase the timeout before the client exits.
Currently with a RPi4 companion using a PPP connection to a FC, the DDS client times out and exits before the network, PPP daemon and micro-ROS agent are up after a power cycle. 
Tested in SITL / Gazebo:
```bash
sim_vehicle.py --debug -v ArduCopter -f gazebo-iris --model json --enable-dds --console
```
```bash
STABILIZE>  param show *DDS*
DDS_DOMAIN_ID    0
DDS_ENABLE       1           # Enabled
DDS_IP0          127
DDS_IP1          0
DDS_IP2          0
DDS_IP3          1
DDS_MAX_RETRY    60
DDS_TIMEOUT_MS   1000
DDS_UDP_PORT     2019
```

AP_DDS: add params for ping timeout and max retries

---

ArduCopter/mode_guided.cpp

We init the Z controller when we fist enter the angle sub mode of guided. However if you send throttle commands the Z controller is not used, if you then change to sending climb rate commands while remaining in angle sub mode you trigger this flow of control error in the pos controller:
https://github.com/ArduPilot/ardupilot/blob/a9ea760cadfddf39434cb3b7dbcf8533f6c4fb1a/libraries/AC_AttitudeControl/AC_PosControl.cpp#L961-L969
extract from https://github.com/ArduPilot/ardupilot/pull/28110

Copter: guided: `set_angle` call `init_z_controller` when changing from thrust to climb rate control to avoid flow of control error

---

ArduPlane/GCS_Mavlink.cpp
ArduPlane/Log.cpp
ArduPlane/Plane.h
ArduPlane/mode.cpp
ArduPlane/mode_guided.cpp
Tools/autotest/arduplane.py
Tools/autotest/vehicle_test_suite.py
libraries/AP_Scripting/examples/plane_guided_terrain.lua

This PR changes the c++ code in Plane Guided mode to use Location:AltFrame for internal references to target Frame. 
This only applies for AP_PLANE_OFFBOARD_GUIDED_SLEW_ENABLED - effectively guided mode commands received via MAVLink, which could also be from Lua using the command_int Lua interface.
A very welcome side effect of this change is that it enables plane MAVLink CMD_GUIDED_CHANGE_ALTITUDE to work for  terrain altitudes in addition to the existing GLOBAL/Absolute and RELATIVE/Home altitudes.
Extracted from #27909 as requested by @IamPete1 to fix guided_state.target_alt_frame being a uint8_t whereas it actually stores AltFrame values from Location::AltFrame.
Similar to changes proposed for Sub in #27767 
Mavlink alt frame values (probably) needed for altitude navigation:
``` …
```

ArduPlane: use Location::AltFrame for guided_state target frame references enabling ABOVE_TERRAIN

---

libraries/AP_Motors/AP_MotorsCoax.cpp

With pass-through, processing is combined into one.

AP_Motors: Change to pass-through

---

Tools/Replay/MsgHandler.cpp

I think it's better to get the size using SIZEOF rather than a literal value.

Replay: The number of elements in a char array can be obtained using SIZEOF

---

libraries/AP_Arming/AP_Arming.cpp
libraries/RC_Channel/RC_Channel.h

We have methods which return you the relevant channels (or a dummy if your vehicle is mis-configured).
Use them.
```
Durandal                            -48    *           -48     -48               -48    -48    -48
KakuteH7-bdshot                     -64    *           -56     -64               -64    -64    -64
MatekF405                           -56    *           -56     -64               -56    -56    -56
Pixhawk1-1M-bdshot                  -64                -56     -64               -64    -40    40
f103-QiotekPeriph …
```

Use get_channel_yaw() and friends in AP_Arming

---

ArduCopter/Copter.cpp
ArduCopter/Copter.h
libraries/AP_Scripting/docs/docs.lua
libraries/AP_Scripting/generator/description/bindings.desc
libraries/AP_Vehicle/AP_Vehicle.h

This adds a rate control binding with throttle for scripting, extracted from https://github.com/ArduPilot/ardupilot/pull/28110.
Note that we do already have `set_target_throttle_rate_rpy` which is impended on plane.
https://github.com/ArduPilot/ardupilot/blob/a9ea760cadfddf39434cb3b7dbcf8533f6c4fb1a/libraries/AP_Scripting/docs/docs.lua#L2487-L2492
The core idea is the same. However, the existing method does not return false if the current mode is not valid. We could add a return to the exiting plane method with out a breaking change. However it is nice to keep the forward flight bindings separate to the VTOL ones so in the future we could support this method on quadplane as well as the existing one for forward flight.

Scripting: add `set_target_rate_and_throttle` binding for copter

---

ArduCopter/AP_Arming.cpp
ArduCopter/mode.h

Extract from https://github.com/ArduPilot/ardupilot/pull/28110. This adds a `allows_GCS_arming_with_throttle_high` mode method to remove a switch on mode number.

Copter: add and use new `allows_GCS_arming_with_throttle_high` mode method

---

Tools/AP_Bootloader/flash_from_sd.cpp
libraries/AP_CANManager/AP_SLCANIface.cpp
libraries/AP_Common/AP_Common.cpp
libraries/AP_Common/AP_Common.h

It can be integrated by adding a process to detect illegal values to the char_to_hex method of AP_COMMON.
Integration eliminates the need for a numeric table.

Common: Integrate methods for converting hexadecimal characters to numbers

---

Tools/ros2/README.md
Tools/ros2/ardupilot_dds_tests/package.xml
Tools/ros2/ardupilot_sitl/CMakeLists.txt
Tools/ros2/ardupilot_sitl/package.xml
Tools/ros2/ardupilot_sitl/src/ardupilot_sitl/launch.py
libraries/AP_DDS/AP_DDS_Client.cpp
libraries/AP_DDS/AP_DDS_Client.h
libraries/AP_DDS/tests/test_ap_dds_external_odom.cpp

Backport the following DDS features/fixes that are low-risk and ABI compatible:
They were ported in the following order. A few merge conflicts to resolve were caused by the ABI breaking change to remove the refs file, and the experimental IMU topic that we do not want on 4.5. 
* https://github.com/ArduPilot/ardupilot/pull/25724
* https://github.com/ArduPilot/ardupilot/pull/27010
* https://github.com/ArduPilot/ardupilot/pull/27131
* https://github.com/ArduPilot/ardupilot/pull/27258
* https://github.com/ArduPilot/ardupilot/pull/27140
* https://github.com/ArduPilot/ardupilot/pull/27161
* https://github.com/ArduPilot/ardupilot/pull/27715
* https://github.com/ArduPilot/ardupilot/pull/27520
Many of these were all requested by a commercial user of Ardupilot DDS and have been thoroughly tested on …

DDS Backports to 4.5

---

libraries/AP_GPS/AP_GPS_SBF.cpp

Backport to Copter 4.5 of  [PR 26628 ](https://github.com/ArduPilot/ardupilot/pull/26628): it sets the satellite count to 0 rather than ignoring it

AP_GPS: Backport correct satellite count for SBF DNU NrSv value

---

libraries/AP_HAL_ChibiOS/hwdef/MFT-SEMA100/hwdef.dat

this board uses 2 128kB sectors for storage, meaning it is very short on space
Remove features we are likely to remove for everyone in 4.7
@EternAlmox - those 128kB sectors really do hurt the available flash on these boards. 
We're looking at putting a feature in to use a single page of storage for parameters, but that's problematic from both a migration POV and from a data sanctity POV (there's a race condition when "compacting" storage when it fills up).  We'll see how we go.

hwdef: correct compilation for MFT-SEMA100

---

Tools/autotest/param_metadata/xmlemit.py

make it easy for consumers to get at this data.
leaves the old form, so we don't break older consumers
```
pbarker@fx:~/rc/ardupilot(master)$ ls -l apm.pdef.xml apm.pdef.xml-new 
-rw-rw-r-- 1 pbarker pbarker 2137562 Sep 24 19:41 apm.pdef.xml
-rw-rw-r-- 1 pbarker pbarker 2248139 Sep 24 19:40 apm.pdef.xml-new
pbarker@fx:~/rc/ardupilot(master)$ ls -l apm.pdef.xml apm.pdef.xml-new  --si
-rw-rw-r-- 1 pbarker pbarker 2.2M Sep 24 19:41 apm.pdef.xml
-rw-rw-r-- 1 pbarker pbarker 2.3M Sep 24 19:40 apm.pdef.xml-new
pbarker@fx:~/rc/ardupilot(master)$ 
```
There are only lines added to the XML.
```
--- apm.pdef.xml        2024-09-24 19:41:10.625061443 +1000
+++ apm.pdef.xml-new    2024-09-24 19:40:53.980125704 +1000
@@ -17,6 +17,10 @@
<field name="Increment">1</field>
</param>
<param …
```

autotest: param_metadata.py: emit bitmask as XML sub-element

---

Tools/scripts/build_options.py

NFC cleans up test in some options so everything is consistent when displayed (ie starts with a Cap)

Tools:clean up displayed build options

---

libraries/AP_ICEngine/AP_ICEngine.cpp

If you set the option bit for "allow throttle while disarmed", you can crank the starter even while the safety switch is engaged, and unless you use a servo pwm as your starter motor controller, you can't even configure it to not do that.
Some places use the `allow_throttle_while_disarmed` method, which additionally checks the safety switch. Other places directly check the options bit. So some stuff works with the safety engaged, and other parts don't. This PR just unifies everything to use the same check.

AP_ICEngine: don't run engine with safety engaged

---

libraries/AP_Camera/examples/README.md
libraries/AP_Camera/examples/gst_rtsp_server.py
libraries/AP_Camera/examples/gst_rtsp_to_wx.py
libraries/AP_Camera/examples/gst_udp_to_rtsp.py
libraries/AP_Camera/examples/gst_udp_to_wx.py

Python examples demonstrating how to manipulate UDP and RTSP video streams using GStreamer. 
The UDP to RTSP converter addresses the problem of consuming a simulated video stream from Gazebo in more than one application using standard installations of GStreamer and opencv (no need for a custom build and install of opencv).
- https://github.com/ArduPilot/ardupilot/pull/27773
- https://github.com/ArduPilot/ardupilot/pull/27903
- https://github.com/ArduPilot/ardupilot_gazebo?tab=readme-ov-file#3-streaming-camera-video

AP_Camera: add Python examples for GStreamer UDP and RTSP video streams

---

ArduCopter/Attitude.cpp
ArduPlane/quadplane.cpp
libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
libraries/AC_AttitudeControl/AC_AttitudeControl.h
libraries/AC_AttitudeControl/AC_AttitudeControl_Logging.cpp
libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp
libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.h
libraries/AC_AutoTune/AC_AutoTune_Multi.cpp

Broken out from https://github.com/ArduPilot/ardupilot/pull/27029
The essence of these changes is to make sure that the interaction between the attitude controller and the rate controller are thread safe. This involves avoiding setting object state as intermediate values but instead publishing at the end of a calculation. It also means that changes should be accepted as vectors rather than discrete axes. Experiments were also done using locking but this proved to be moderately expensive at high update rates and did not improve the overall effect of this change.

Refactor attitude control to be thread safe

---

libraries/AP_Camera/AP_Camera_Backend.cpp
libraries/AP_Logger/AP_Logger.h
libraries/AP_Math/AP_Math.h
libraries/AP_Mount/AP_Mount_Siyi.cpp
libraries/AP_Mount/AP_Mount_Topotek.cpp
libraries/AP_Mount/AP_Mount_Viewpro.cpp
libraries/AP_Mount/AP_Mount_Xacti.cpp
libraries/AP_Param/AP_Param.cpp

per-spec
Replaces https://github.com/ArduPilot/ardupilot/pull/25010/files
Creates a global `NaNf` per @rmackay9 's suggestion

Use NaN in camera fields when no value known

---

libraries/AP_DroneCAN/AP_DroneCAN.cpp
libraries/AP_HAL_ChibiOS/UARTDriver.cpp

partial backport of #28218 
this backports all the changes except the mutex in UARTDriver

DroneCAN: backport of lockup fix

---

ArduCopter/GCS_Copter.cpp
ArduCopter/GCS_Mavlink.cpp

This means we don't need to switch on the mode number, extracted from https://github.com/ArduPilot/ardupilot/pull/28110 
This is the first time we will be using these flags for reporting, until now it is used internally only. There are some changes in behaviour, for example you can be landed in auto mode in which case the pos controller may not report as active (i need to check).

Copter: GCS_MAVLink: populate flags using position controller active flags

---

libraries/AP_DroneCAN/AP_DroneCAN.cpp
libraries/AP_HAL_ChibiOS/UARTDriver.cpp

this matches https://github.com/ArduPilot/ardupilot/pull/28219 which is what is in 4.5.7-beta1

DroneCAN: partial application of deadlock fix

---

AntennaTracker/ReleaseNotes.txt
AntennaTracker/version.h
ArduCopter/ReleaseNotes.txt
ArduCopter/version.h
ArduPlane/ReleaseNotes.txt
ArduPlane/takeoff.cpp
ArduPlane/version.h
Rover/ReleaseNotes.txt
Rover/version.h
Tools/ardupilotwaf/ap_library.py
Tools/ardupilotwaf/chibios.py
Tools/ardupilotwaf/git_submodule.py
libraries/AP_DroneCAN/AP_DroneCAN.h
libraries/AP_HAL_ChibiOS/UARTDriver.cpp
libraries/AP_Motors/AP_MotorsHeli_Single.cpp
libraries/AP_Proximity/AP_Proximity_MR72_CAN.cpp
libraries/AP_RCProtocol/AP_RCProtocol_GHST.cpp
wscript

This is the Copter, Plane, Rover and Tracker 4.5.7-beta1 release.
The full list of PRs included can be seen in the 4.5.7-beta1 column of [this project](https://github.com/orgs/ArduPilot/projects/8/views/8?layout=board).
After discussions with @peterbarker and @tridge these three have also been added
Any and all feedback is very welcome!

Copter/Plane/Rover/Tracker: 4.5.7-beta1 release

---

Tools/autotest/quadplane.py
libraries/AP_ICEngine/AP_ICEngine.cpp
libraries/AP_ICEngine/AP_ICEngine.h

As we use a common battery for Avionics and Engine Cranking we would like to have an option to limit the number of retrials so that it doesn't drain that battery completely. Obvious choice is to separate the batteries but I still think there could be some use of this feature.
My Implementation is by adding Param MAX_RETRY which If set 0 then there is no limit to retrials. If set to a value greater than 0 then the engine will retry starting the engine this many times before giving up. Also the counter to track retrials resets to zero on disarm (could be done only on power cycle rather than disarm). If needed to be override can be done by setting the param to 0.
I would like to get more ideas on the method of its implementation. I have not yest tested this code.
Other ways to implement this …

Param for Max Retrial of Engine Cranking.

---

libraries/AP_Mission/AP_Mission.cpp

Multiple decisions are being made for the same variable value.
In this case, the SWITCH statement is better than the IF statement.

AP_Mission: Change the IF statement to a SWITCH statement

---

ArduCopter/AP_Arming.cpp
ArduCopter/motor_test.cpp
libraries/AP_Arming/AP_Arming.cpp

The number of characters in the message exceeds 50 bytes. 
The message array is currently set to 50 bytes. I will submit a PR to change the array to 100 bytes.
ArduPilot has string splitting functionality.
AFTER
BEFORE
THIS SOURCE:

Copter: Set the message buffer size to twice the message size

---

libraries/AP_RangeFinder/AP_RangeFinder_Ainstein_LR_D1.cpp

Move the location where TRUE is set to has_data to the appropriate location.

AP_RangeFinder: Move the flag setting location of has_data

---

libraries/AP_Baro/examples/BARO_generic/BARO_generic.cpp

This fix  a crash running on beaglebone boards reported
https://github.com/ArduPilot/ardupilot/issues/21321

AP_Baro: fix example: fixing missing objects

---

Tools/autotest/arduplane.py
libraries/AP_AHRS/AP_AHRS.cpp
libraries/AP_AHRS/AP_AHRS.h

This adds an AHRS_OPTION to disable the EKF check for innovation that disables airspeed
This is useful where the user wants to trust the airspeed sensor because the EKF innovation check may be unreliable

AHRS: add option to disable EKF innovation check for airspeed

---

.github/workflows/cygwin_build.yml
.github/workflows/esp32_build.yml
.github/workflows/qurt_build.yml
.github/workflows/test_dds.yml
.github/workflows/test_replay.yml
.github/workflows/test_scripting.yml
.github/workflows/test_sitl_blimp.yml
.github/workflows/test_sitl_copter.yml
.github/workflows/test_sitl_plane.yml
.github/workflows/test_sitl_rover.yml
.github/workflows/test_sitl_sub.yml
.github/workflows/test_sitl_tracker.yml
.github/workflows/test_unit_tests.yml

v3 is being deprecated, and this one claims to have advantages including the keyword "faster"

github: move to actions/upload-artifact@v4

---

Tools/autotest/arducopter.py
Tools/autotest/vehicle_test_suite.py

we are starting to get huge downloads for autotest failures. High logging rates rarely help to diagnose an issue, so lower the default rate when in autotest

autotest: lower logging rate

---

.github/problem-matchers/autotestfail.json
.github/workflows/test_sitl_copter.yml
.github/workflows/test_sitl_rover.yml
.github/workflows/test_sitl_sub.yml

.github: use problem matches on Copter SITL

---

Rover/AP_Arming.cpp

it is clear by inspection that this string can never be empty when the called function returns false.  AP_OAPathPlanner::pre_arm_check is not that complicated!
Lightly tested in SITL by setting `OA_TYPE` to an invalid value
Replaces https://github.com/ArduPilot/ardupilot/pull/26963/files

Rover: remove handling of prearm empty-string case

---

libraries/AP_HAL_ChibiOS/UARTDriver.cpp
libraries/AP_HAL_ChibiOS/UARTDriver.h

This fixes a set of issues found on investigating a watchdog from @lthall 
PR depends on: https://github.com/dronecan/libcanard/pull/72
The situation was:
- a H7 with mavlink over serial over DroneCAN setup, MissionPlanner connected to the serial port
- SERIAL1_PROTOCOL set to GPS, with GPS1_TYPE=AUTO, but no GPS plugged in
There were several interacting bugs:
- the canard layer could run out of buffer in its allocator part way through a message send, resulting in sending just some of the frames onto the bus, which results in a corrupt message, wasted bandwidth and broadcast() returning false
- MissionPlanner sends CAN_FORWARD requests on all connections, regardless of type, which on a CAN serial port means it is requesting to send it's own packets over CAN, resulting in an "infinite" …

DroneCAN: fixed deadlock and saturation of CAN bus

---

libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp
libraries/AP_BattMonitor/AP_BattMonitor_Params.h
libraries/AP_BattMonitor/AP_BattMonitor_Sum.cpp

Alternative approach to #28148
This solves the race condition issue and the Wh consumption calculation. Instead of calling `update_consumed` again, it sums the consumption calculation from the other monitors. This is actually much better than integrating it again manually, especially if the underlying monitors are better at calculating the consumption.
I also removed the implementation on the ESC battmon backend (and updated the param docs and comments to match). I don't think it was nearly as important to have this option for the ESC backend and I couldn't use the same trick with that one.

AP_BattMonitor: add option minimum volt option

---

libraries/AP_Scripting/modules/MAVLink/mavlink_msg_COMMAND_LONG.lua
libraries/AP_Scripting/modules/MAVLink/mavlink_msgs.lua
libraries/GCS_MAVLink/GCS_Common.cpp

This allows scripting to receive messages which the flight controller does not understand. Note that more work is needed to allow sending. This uses https://github.com/ArduPilot/pymavlink/pull/983.
Tested new CRC check with MAVLink 1 and 2. Tested unknown messages by changing the CRC extra of command long in ArduPilot so it would fail its CRC check, it still works as normal in the script.

GCS_MAVLink: Common: Allow scripting to receive messages which fail CRC check

---

libraries/SITL/SITL.cpp

now done by having the subgroup in its own file

SITL: remove stale parameter metadata

---

libraries/AP_ExternalAHRS/AP_ExternalAHRS.h
libraries/AP_ExternalAHRS/AP_ExternalAHRS_InertialLabs.cpp
libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain5.cpp
libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain7.cpp
libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.cpp
libraries/AP_GPS/AP_GPS_ExternalAHRS.cpp

... rather than just a uint8_t.
This is supposed to be the conversion from externalahrs concept of fix type into ArduPilot's, so use an ArduPilot type for it.
Replaces https://github.com/ArduPilot/ardupilot/pull/23015/files

Use AP_GPS_FixType in AP_ExternalAHRS

---

ArduCopter/Parameters.cpp

mode is missing from Mission Planner since its not in the metadata

Copter: add turtle mode to flight modes metadata

---

libraries/AP_Scripting/docs/docs.lua
libraries/AP_Scripting/examples/net_test.lua
libraries/AP_Scripting/generator/description/bindings.desc
libraries/AP_Scripting/lua_bindings.cpp
libraries/AP_Scripting/lua_bindings.h

This makes a UDP server that responds back to individual clients possible by allowing recv to know the source address of the sender. It also allows for conversion between the string and uint32_t form of IPv4 addresses

AP_Scripting: added bindings for ipv4 address

---

Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_joy_msg_received.py
libraries/AP_DDS/AP_DDS_Client.cpp
libraries/AP_DDS/README.md

I noticed that this Pull Request has been stuck for one year.
https://github.com/ArduPilot/ardupilot/pull/25334
Tagging @srmainwaring and @Ryanf55.

AP_DDS: Joystick Support 2

---

Tools/environment_install/install-prereqs-openSUSE-Tumbleweed.sh

* We only tested on apt, don't blindly change dev env stuff that's not tested in CI
* The original PR was only for APT, but the dev team thought we should try it on all the scripts for consistency
Motivation: https://github.com/ArduPilot/ardupilot/commit/d18a2b22f922bf9358f39a201010167853bb756e#commitcomment-147393965

Tools: Do not use system packages on openSUSE

---

Tools/autotest/vehicle_test_suite.py
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp

From #28101.
Ardupilot caps the maximum message rate at 80% of ``SCHED_LOOP_RATE``.
If a user requests a rate faster than this via ``MAV_CMD_SET_MESSAGE_INTERVAL``, the command now fails and advises the user to increase ``SCHED_LOOP_RATE``.
This will prevent user confusion as per the linked issue.

GCS_MAVLink: Check if set_message_interval is too fast

---

libraries/AP_HAL_ESP32/GPIO.cpp
libraries/AP_HAL_ESP32/GPIO.h
libraries/AP_HAL_ESP32/HAL_ESP32_Class.cpp
libraries/AP_Notify/AP_Notify.cpp

AP_HAL_ESP32: Add GPIO driver for ESP32

---

ArduPlane/servos.cpp
Tools/autotest/arduplane.py

This PR implements the fix proposed in issue #25851 
The current code to wiggle the servos in mission waypoint option "Altitude_wait" currently does not wiggle left elevon, and none of the VTAIL Servos. This is due to the output mixers summing out to zero from the respective roll/pitch/yaw commands.
This fix stages the wiggles one after the other so nothing sums out to zero. 
I waited to submit this PR until i got around to testing it at least with SITL. 
Here's the test: https://www.youtube.com/watch?v=ryS6fTMAQS0

Plane: Stage servo wiggles one after another

---

ArduPlane/ArduPlane.cpp
ArduPlane/Plane.h
ArduPlane/commands_logic.cpp
ArduPlane/mode_auto.cpp
ArduPlane/mode_takeoff.cpp
ArduPlane/quadplane.cpp
ArduPlane/servos.cpp
ArduPlane/takeoff.cpp
Tools/autotest/arduplane.py
Tools/autotest/vehicle_test_suite.py
libraries/AP_TECS/AP_TECS.cpp
libraries/AP_TECS/AP_TECS.h

This PR fixes TECS oscillations that would occur once mode TAKEOFF would reach `TKOFF_ALT`.
Additionally, it harmonizes the takeoff behaviour between modes AUTO and TAKEOFF.
Finally, it fixes a few bugs.
Many thanks to @Hwurzburg for sharing code for fixing the pitch setpoint.
1. Mode TAKEOFF and AUTO now behave identically during a takeoff.
2. `TKOFF_LVL_ALT` now also affects AUTO mode.
3. TAKEOFF mode now respects the level-off angles, as it approaches altitude. There should now be significantly less overshoot.
4. The behaviour of TKOFF_ROTATION_SPD now works as advertized. It was inactive before.
1. Mode TAKEOFF now spends all of the climb in FlightStage::TAKEOFF, just like AUTO mode did.
2. `TECS::set_pitch_max_limit()` is now split into `TECS::set_pitch_max()` and …

Plane: Takeoff improvements

---

ArduPlane/ArduPlane.cpp

one block was guarded, the second not

Plane: avoid calling quadplane methods if quadplane not available

---

Tools/autotest/run_mission.py
Tools/autotest/test_param_upgrade.py
Tools/autotest/unittest/annotate_params_unittest.py
Tools/autotest/unittest/extract_param_defaults_unittest.py
Tools/scripts/annotate_params.py
Tools/scripts/extract_param_defaults.py
Tools/scripts/generate_pdef.xml_metadata.py

going directly to /usr/bin/python3 means we don't use the venv python

Tools: use /usr/bin/env to find python3

---

.github/workflows/test_sitl_plane.yml
Tools/autotest/arduplane.py
Tools/autotest/autotest.py
Tools/scripts/build_ci.sh

The Plane tests are taking 30 minutes, so past time to split into a tests1a and tests1b.
Will also stop the output being truncated in the github interface, hopefully.

Split Plane tests into two parts for github workflows

---

Tools/autotest/helicopter.py
libraries/AP_Motors/AP_MotorsHeli_RSC.cpp

This PR fixes the ice/turbine cool down feature in Heli RSC.
This also adds an autotest to prevent future regression.

Fix heli ice/turbine cooldown and add autotest 

---

Tools/AP_Bootloader/board_types.txt

I want to add full support for this board:
https://betafpv.com/products/f4-2-3s-20a-aio-fc-v1 
I have all other files ready but want to reserve a board id first

board_types.txt: reservie ID for F4 2-3S 20A AIO FC V1

---

ArduCopter/GCS_Mavlink.cpp
ArduCopter/autoyaw.cpp
ArduCopter/mode.h
ArduCopter/mode_auto.cpp
Tools/autotest/arducopter.py
libraries/AP_Mission/AP_Mission.cpp

The demanded yaw angles in the `MOUNT_CONTROL` and `DO_MOUNT_CONTROL` commands are in body frame (and are handled this way in `AP_Mount`). This fixes the Copter handlers where they were being treated as earth frame.
It also rejects these messages if an invalid mode is provided, as the yaw control is only applicable when the mode is `MAV_MOUNT_MODE_MAVLINK_TARGETING`.
FYI: @rmackay9

Copter: Handle DO_MOUNT_CONTROL yaw angle as body frame 

---

ArduCopter/mode_auto.cpp

This PR improves the `CONDITION_YAW` behavior when `WP_YAW_BEHAVIOR` is set to NONE.
Previously, Yaw Mode would switch to `HOLD` when reaching a waypoint.
This meant that even if `CONDITION_YAW` was used, its effect would be reset upon reaching each WAYPOINT. As a result, the vehicle's yaw could potentially drift due to external factors like wind.
With this change, when `WP_YAW_BEHAVIOR` is NONE and `CONDITION_YAW` has been used (resulting in FIXED mode), the yaw remains in `FIXED` mode even after reaching WAYPOINT, maintaining the desired heading as specified by `CONDITION_YAW`.
Before
After
Settings:
- `WP_YAW_BEHAVIOR=0` (None)
- Used `CONDITION_YAW` with `Deg = 10`, `Speed = 0`, `Dir = 0`, `Abs = 0`.
Testing:
SITL testing was performed to confirm the behavior. To create a challenging …

Copter: Keep FIXED mode when WP_YAW_BEHAVIOR is NONE

---

libraries/AP_DroneCAN/AP_Canard_iface.cpp

The timeout specified for auxiliary driver frames was passed to the driver where a deadline was expected. The transmission was then started after its "deadline", thereby causing it to be canceled and the data lost if the frame could not be sent immediately.
Fix by converting the timeout to a deadline before passing to the driver. The conversion is done in the Canard interface code as it already does other conversions from timeouts to deadlines.
Tested that my setup used to get timeouts registered in `@SYS/can0_stats.txt` and doesn't anymore.

AP_DroneCAN: properly convert timeout to deadline for aux frames

---

libraries/AP_SerialManager/AP_SerialManager.h

The RegisteredPort class in AP_SerialManager derives from the "naked" AP_HAL::UARTDriver class, and therefore provides its bw_in_bytes_per_second() method. This method however returns a default bytes/seconds of 5760 (https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL/UARTDriver.h#L151-L153).
The registered port is used by e.g. the DroneCAN serial class, in order to do e.g. MAVlink via DroneCAN tunneling. The MAVLink flow control of the parameter stream and mavftp however relies on the value returned by bw_in_bytes_per_second() (https://github.com/ArduPilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS_Param.cpp#L56, https://github.com/ArduPilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS_FTP.cpp#L500). Therefore, currently it only works properly if the default of …

AP_SerialManager: RegisteredPort, add bytes_per_second/baudrate methods, proper flow control for MAVLink via DroneCAN

---

libraries/AP_HAL/AP_HAL_Boards.h

we'll now get compilation failures if code is introduced depending on these...

Remove defunct board type defines

---

Tools/AP_Bootloader/can.cpp

It is technically legal to receive an "allocation" of the broadcast node ID. Fortunately, this was already ignored by `canardSetLocalNodeID`, though it would trigger an assertion failure if those were enabled.
Fix by rejecting that ID. There is effectively no change in behavior but the code now correctly ignores that ID and retries the allocation as it did before.
Similar to https://github.com/ArduPilot/ardupilot/pull/28045 . Tested on CubeOrange (with artificially limited DNA database size) and a pile of MatekL431 boards with updated bootloaders. Not sure the policy on bootloader rebuilds.

AP_Bootloader: reject allocation of broadcast node ID

---

ArduPlane/quadplane.h

```
Durandal                            *      *           *       *                 -240   *      *
KakuteH7-bdshot                     *      *           *       *                 -240   *      *
MatekF405                           *      *           *       *                 -216   *      *
Pixhawk1-1M-bdshot                  *                  *       *                 -240   *      *
f103-QiotekPeriph        *                                                                     
f303-Universal …
```

Plane: stop using bit-packing for quadplane state

---

libraries/AP_BLHeli/AP_BLHeli.cpp

NFC....obviously a typo...assume it should refer to the only other BLH mask types

AP_BLHeli:correct RVMASK metadata

---

Tools/ros2/ardupilot_sitl/CMakeLists.txt

* This allows someone using colcon full control over the `waf` build without having to re-learn all of the ardupilot_sitl arguments. 
```bash
colcon build --packages-select ardupilot_sitl --cmake-args -DARDUPILOT_WAF_CONFIGURE_ARGS="--disable-CRSF" --event-handlers=console_cohesion+
```
```bash
$ cat build/ardupilot_sitl/CMakeCache.txt | grep ARDUPILOT_WAF_CONFIGURE_ARGS
ARDUPILOT_WAF_CONFIGURE_ARGS:STRING=--disable-CRSF
```
* Solves https://github.com/ArduPilot/ardupilot/issues/27714

Tools: Expose arbitrary waf configure and build args

---

ArduPlane/mode.cpp
Tools/autotest/quadplane.py

this avoid the AHRS being told we are flying forward - because we are no longer in a VTOL mode - and instantly being told we are not flying forward - because we are providing assistance
The following two plots are plotting the fly-forward flag being shoved into the Replay log.
Before:
After:
This is particularly important when an external wind estimate has been supplied to the vehicle, as setting the FF flag causes EKF3 to completely nuke the wind estimates.  The following graphs are from a different test where the wind estimate is set externally:
Before:
After:
... the EKF wind estimate is still suffering when the FF flag is finally set after FF is *correctly* set - but at least we have transitioned with the flag set!

Plane: evaluate assistance requirements on mode change

---

ArduPlane/quadplane.cpp
Tools/autotest/quadplane.py

This PR ensures that the `bool SLT_Transition::active_frwd()` check does not return true during a back-transition airbrake.
The existing code would cause `active_frwd()` to return true during a back transition.
In turn, `servos.cpp:553` would trigger:
```c++
#if HAL_QUADPLANE_ENABLED
if (quadplane.in_frwd_transition()) {
```
and would set the minimum throttle to the **forwards** transition throttle: `THR_TRIM` or `TKOFF_THR_MIN`.
This would lead to undesired increase in airspeed and eventually altitude during the back transition.
The TECS minimum throttle can be used as a proxy to see the effect of that setting.
This is a snapshot during the airbrake phase.
Before:
After:

Plane: Do not apply minimum throttle during SLT VTOL airbrake

---

libraries/SITL/SIM_Aircraft.cpp

projecting onto an infinite plane can cause exceptionally long rangefinder distances - for now jsut cap the distance that the simulated rangefinder can return to avoid floating point exceptions.
the FPE is caused in the Plane FlyEachFrame autotest when flying quadplane-copter_tailsitter - which ends up with a rangefinder at yaw-minus-180.
This is the FPE:

SITL: avoid floating point exception around rangefinder distance

---

libraries/AP_HAL_ChibiOS/hwdef/scripts/defaults_periph.h

Removed duplication for AP_STATS_ENABLED in AP_Periph defaults

defaults_periph.h: Removed duplication for AP_STATS_ENABLED

---

libraries/AP_KDECAN/AP_KDECAN.cpp
libraries/AP_KDECAN/AP_KDECAN.h

For consistency with other parts of the code.
Turns out there is no compiler output change (unless I change a timeout value); the compiler already does this optimization. But I already wrote the code and spent the CPU to test it... The eventual goal is to make `CANSensor::write_frame` take a 32 bit value.
``` …
```

AP_KDECAN: standardize on 32 bit microsecond CAN timeouts

---

Tools/autotest/sim_vehicle.py

this is useful if you are running under GDB and ArduPilot fails early (eg. parameter sanity checks or SITL device configuration issues)

autotest: restart MAVProxy if it exits when running under gdb

---

Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_battery_msg_received.py
libraries/AP_DDS/AP_DDS_Client.cpp
libraries/AP_DDS/AP_DDS_Topic_Table.h
libraries/AP_DDS/README.md

https://github.com/ArduPilot/ardupilot/issues/28288
- Battery topic renamed to `/ap/battery`
- All the detected batteries are reported to the same topic with different `frame_id` from `'0'` to `'<AP_BATT_MONITOR_MAX_INSTANCES>'`
```
colcon test --packages-select ardupilot_dds_tests \
--event-handlers=console_cohesion+ --pytest-args -k test_battery_msg_received
colcon test-result --all --verbose
```

AP_DDS: battery topic to report all the available batteries

---

ArduCopter/Copter.h
ArduCopter/heli.cpp
ArduCopter/mode.cpp
ArduCopter/mode.h
ArduCopter/mode_autorotate.cpp
ArduSub/mode.cpp
Tools/autotest/helicopter.py
Tools/autotest/vehicle_test_suite.py
libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
libraries/AC_Autorotation/AC_Autorotation.cpp
libraries/AC_Autorotation/AC_Autorotation.h
libraries/AC_Autorotation/RSC_Autorotation.cpp
libraries/AC_Autorotation/RSC_Autorotation.h
libraries/AP_Motors/AP_MotorsHeli.cpp
libraries/AP_Motors/AP_MotorsHeli.h
libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
libraries/AP_Motors/AP_MotorsHeli_Quad.cpp
libraries/AP_Motors/AP_MotorsHeli_RSC.cpp
libraries/AP_Motors/AP_MotorsHeli_RSC.h
libraries/AP_Motors/AP_MotorsHeli_Single.cpp
libraries/AP_Motors/examples/AP_Motors_test/AP_Motors_test.cpp

This PR does the following:
- Removes the linking of autorotation flight mode and the interlock.
- Consolidates the autorotation state into its own class within the RSC.
- Moves the bailout logic out of the autorotation mode and into RSC making it common to both the mode and manual autorotations.
Reasons for this:
- The linking of the flight mode switching and interlock was creating lots of edge cases that were proving to difficult to prevent.  This is simpler and just like any other flight mode **(this is still SITL only)**.
- Removing this link between interlock and flight mode means, in the future, we can add partial power reduction in assisted autorotations via the flight mode which will make initial setup and testing more gradual and less intimidating.
- All bailout out handling for …

Simplify Autorotation Mode Switching and Consolidate Autorotation State in RSC

---

libraries/AP_HAL_ChibiOS/hwdef/common/crashdump.c

* We were running out of memory regions and hence losing dump data even though we had enough flash to record, this PR increases the number of regions and also checks num region overruns for bss and heap

AP_HAL_ChibiOS: increase the number of memory regions for crashdump

---

libraries/AP_Volz_Protocol/AP_Volz_Protocol.cpp
libraries/AP_Volz_Protocol/AP_Volz_Protocol.h

This adds support for logging desired and actual position, primary and secondary voltage, primary and secondary current, motor and PCB temperature. 
The telem data is at quite a low rate because requesting telem takes the place of a position command. So telem does lower the position update rates. A single servo would send commands at 320 Hz and telem requests at 320Hz, there are three messages we request so a full telem update would be at (320/3) 100Hz. For four servos each servo would be updated at 128Hz and telem also at 128Hz. However there are more servos to cycle through so a full telem update for each servo would happen at (128/(3*4)) 10Hz.
Telem is only used for logging, each servo is logged at 5Hz using a new `VOLZ` log with instances for each servo.
Note that we do get position …

AP_Volz_Protocol: add support for telem

---

AntennaTracker/ReleaseNotes.txt
AntennaTracker/version.h
ArduCopter/ReleaseNotes.txt
ArduCopter/version.h
ArduPlane/ReleaseNotes.txt
ArduPlane/version.h
Rover/ReleaseNotes.txt
Rover/version.h
libraries/AP_GPS/AP_GPS_SBF.cpp

This is the Copter, Rover, Tracker, Plane-4.5.7 release.  The contents of that release can be found in the [4.5.7-beta1 column of this project](https://github.com/orgs/ArduPilot/projects/8/views/8?layout=board).
This is the same as the 4.5.7-beta1 release but with PR https://github.com/ArduPilot/ardupilot/pull/27799 reverted.  I have not actually determined if [the user report](https://discuss.ardupilot.org/t/coper-4-5-7-beta1-available-for-testing/124355) is correct but I think at this stage it is best to remove it and proceed with the release.

Copter, Rover, Tracker, Plane-4.5.7 release

---

libraries/AP_PiccoloCAN/AP_PiccoloCAN.cpp
libraries/AP_PiccoloCAN/AP_PiccoloCAN.h
libraries/AP_PiccoloCAN/AP_PiccoloCAN_Device.h

For consistency with other parts of the code. Saves a handful of bytes.
Please see commit messages for caveats with this change; this does change protocol semantics ever so slightly. Needs testing with real hardware.

AP_PiccoloCAN: use 32 bit microsecond timeouts

---

libraries/AP_NavEKF3/AP_NavEKF3_AirDataFusion.cpp

AP_NavEKF3: initialise variables as part of declaration

---

libraries/AP_Logger/LogStructure.h

the rate of CAN servo messages is controlled by the servo. Having this streaming means we can miss logging when there is more than one CAN servo.
In the future we will move to holding the CAN servo data in a data structure like we do for ESCs, and then log at a regular rate, but for now this fixes the issue

AP_Logger: mark CSRV non-streaming

---

libraries/AP_DroneCAN/AP_DroneCAN.cpp

if a user has set CAN_D1_UC_ESC_RV which is the mask of ESCs that are reversible we were sending -8191 when disarmed, which is full reverse throttle. This is the correct output when armed as it is treated as full reverse at "PWM" 1000 and stopped at 1500, but when disarmed we should always send zero or the user may find all ESCs spin up at full reverse when disarmed if the ESC supports reverse throttle (which is rare in DroneCAN ESCs)

AP_DroneCAN: force DroneCAN zero throttle when disarmed

---

libraries/GCS_MAVLink/GCS_MAVLink.h

with CAN serial ports and network serial ports sometimes need more
@lthall hit this with a Durandal with 2 CAN serial ports doing MAVLink

GCS_MAVLink: raise number of MAVLink ports

---

ArduPlane/mode.cpp
ArduPlane/mode.h

For the balloon drop use-case, I've noticed that TECS would initialize on the ground. That meant that the desired altitude (which is under an LPF) would not start close to the actual altitude, rendering itself useless for an RTL:
With this commit TECS starts at the release altitude, resulting in reasonable altitude error:
:warning: Requires https://github.com/ArduPilot/ardupilot/pull/27758 .

Plane: Reset TECS along with the rest of the controllers

---

libraries/AP_Scripting/docs/docs.lua
libraries/AP_Scripting/generator/description/bindings.desc

Add analog:mcu_voltage() to get a reading of the mcu voltage
Tested on CubeOrangePlus

AP_Scripting: Add mcu_voltage

---

libraries/AP_Scripting/examples/ESC_slew_rate.lua

can be used to calculate equivalent cutoff frequency

AP_Scripting: example to test ESC slew limit

---

libraries/AP_AHRS/AP_AHRS.cpp
libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp
libraries/AP_ExternalAHRS/AP_ExternalAHRS.h
libraries/AP_ExternalAHRS/AP_ExternalAHRS_InertialLabs.cpp
libraries/AP_ExternalAHRS/AP_ExternalAHRS_InertialLabs.h
libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain5.cpp
libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain5.h
libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain7.cpp
libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain7.h
libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.cpp
libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.h
libraries/AP_ExternalAHRS/AP_ExternalAHRS_backend.h

simplifies backends, allows GCS to see variances in EKF message, and allows for copter EKF failsafe to work
broken out of #24747

ExternalAHRS: support variances in backends

---

Tools/Frame_params/ModalAI/Starling2Max.parm

Added initial params file for the ModalAI Starling 2 Max drone

Frame_params: Added Starling 2 Max params file

---

libraries/AP_AHRS/AP_AHRS_DCM.cpp

When there are multiple conditions, evaluate them from left to right.
Change it so that you first determine whether to use GPS or not, and then, if using it, decide on the positioning level.

AP_AHRS: Change the order in which you make judgments

---

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py

This fixes a bug where we run GPIO loop through SPI two times per pin as we duplicate MISO and MOSI name with RX and TX as well. So if we have GPIO(x) next to SPI the hwdef fails to compile, and does not allow SPI lines to also be treated as GPIO.

AP_HAL_ChibiOS: do not run through SPI_RX and TX as well

---

libraries/AP_RCProtocol/AP_RCProtocol.h

Fix for compiler warning from clang about unknown warning group -Wswitch-unreachable. This warning is prevalent in both Qurt and MacOS SITL builds.

Fix clang compiler warning

---

wscript

```
$ ./waf configure --extra-hwdef=foo.dat
Setting top to                           : /home/ryan/Dev/ardupilot_ws/src/ardupilot 
Setting out to                           : /home/ryan/Dev/ardupilot_ws/src/ardupilot/build 
Autoconfiguration                        : enabled 
Checking for program 'python'            : /usr/bin/python3 
Checking for python version >= 3.6.9     : 3.10.12 
Setting board to                         : sitl 
Using toolchain                          : native 
Checking for 'g++' (C++ compiler)        : /usr/lib/ccache/g++ 
Checking for 'gcc' (C compiler)          : /usr/lib/ccache/gcc 
Checking for c flags '-MMD'              : yes 
Checking for cxx flags '-MMD'            : yes 
CXX Compiler                             : g++ 11.4.0 
Checking for need to link with …
```

waf: Fail if custom hwdef file doesn't exist

---

libraries/AP_HAL_ESP32/WiFiDriver.cpp
libraries/AP_HAL_ESP32/WiFiUdpDriver.cpp

Switching WIFI task from FASTCPU to SLOWCPU seems to bring more balance between CPUs and thus increasing connection reliabiiity

AP_HAL_ESP32: Switch WIFI task from FASTCPU to SLOWCPU

---

libraries/AP_HAL_ESP32/RCOutput.cpp
libraries/AP_HAL_ESP32/RCOutput.h

Ported RCOutput code to new MCPWM driver
Best regards,
A. Romanov

AP_HAL_ESP32: RCOutput ported to new mcpwm driver

---

Tools/AP_Bootloader/board_types.txt

Boards ids for TBS' upcoming boards

AP_Bootloader: reserve board ids and range for TBS

---

ArduPlane/GCS_Mavlink.h

ArduPlane: Remove unused radio_in_rssi function

---

libraries/AP_ADSB/AP_ADSB_uAvionix_UCP.cpp
libraries/AP_ADSB/AP_ADSB_uAvionix_UCP.h
libraries/AP_ADSB/GDL90_protocol/GDL90_Message_Structs.h
libraries/AP_ADSB/GDL90_protocol/hostGDL90Support.h

Replaces #28411, which targeted the wrong branch.
This PR contains updates to the interface with the ping200X. Co-requisite with the MissionPlanner PR https://github.com/ArduPilot/MissionPlanner/pull/3429
Changes:
- Added parsing for GDL90 Transponder Status V3
- Fixes buggy behavior when ping200X has both UCP and UCP-HD out protocols enabled
- Includes new fields for on-ground state, board temperature, NIC, and NACp.
- Improved behavior when ping200X times out (due to power loss, serial connection error, etc.)
- `UAVIONIX_ADSB_OUT_STATUS_FAULT_STATUS_MESSAGE_UNAVAIL` is now `1` if the GDL90 ownship, transponder status, and heartbeat have been missed for 10 seconds, and is otherwise `0` when one of those messages is received. See the co-requisite MissionPlanner PR for changes to how the …

AP_ADSB: uAvionix Transponder Updates

---

Tools/ros2/README.md
Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_navsat_msg_received.py
libraries/AP_DDS/AP_DDS_Client.cpp
libraries/AP_DDS/AP_DDS_Topic_Table.h
libraries/AP_DDS/README.md

Match battery behavior by setting the GPS instance number in the frame ID.
Remove the `0` from the topic. We are doing multiple GPS's on the same topic now.
```bash
ros2 topic echo /ap/navsat --once
```
```yaml
header:
stamp:
sec: 1729471218
nanosec: 41276000
frame_id: '0'
status:
status: 2
service: 1
latitude: -35.36326217651367
longitude: 149.1652374267578
altitude: 584.0899658203125
position_covariance:
- 0.09000000357627869
- 0.0
- 0.0
- 0.0
- 0.09000000357627869
- 0.0
- 0.0
- 0.0
- 0.09000000357627869
position_covariance_type: 2
---
```
https://github.com/ArduPilot/ardupilot/pull/28291/files#diff-21a2f7a8c86c0d8903e0c8c3e48a7a8ae29fe5afa11878a8cd4b58224f31d94bR307
^ This does the same thing but allows two digits of instance number. I assume we will have less than 10 GPS's.
FYI …

AP_DDS: Set GPS instance ID in the GPS frame ID

---

libraries/APM_Control/AR_AttitudeControl.cpp

For Rover, a correction for calculating the stopping distance - it should use deceleration, not acceleration.

APM_Control: Use deceleration for stopping distance

---

libraries/AP_HAL_ChibiOS/hwdef/common/common_extf.ld
libraries/AP_HAL_ChibiOS/hwdef/common/common_extf_h730.ld
libraries/AP_HAL_ChibiOS/hwdef/common/common_extf_h750.ld

on H730 we are overflowing the ITCM area for SPRacingH7RF and other H750 boards are not far behind.
Step away from the edge by removing this function which should never be in a fast path
I've tested on H750 (`YJUAV_A6SE`) and it still boots.  I do not have SPRacingH7RF to test.

AP_HAL_ChibiOS: exclude chprintf from fastramfunc

---

libraries/AP_Math/matrix3.cpp
libraries/AP_Math/matrix3.h

this method is in ITCM memory on STM32 - which makes small optimisations worthwhile
```
CubeRedPrimary                      -72    *           -72     -64               -72    -72    -64
Durandal                            -64    *           -64     -64               -64    -64    -64
KakuteH7-bdshot                     -64    *           -64     -64               -64    -64    -64
MatekF405                           -48    *           -40     -48               -40    -32    -40
Pixhawk1-1M-bdshot …
```

AP_Math: move zeroing to header, use memset, reuse in identity

---

libraries/AP_NavEKF/AP_Nav_Common.h
libraries/AP_NavEKF3/LogStructure.h

this isn't used for anything but documenting the solution status field, which can be used in the Wiki and in various log analysis tools

Add enumeration to document EKF SolutionStatus

---

.github/workflows/test_scripts.yml
Tools/autotest/logger_metadata/enum_parse.py
Tools/autotest/logger_metadata/parse.py
Tools/scripts/build_ci.sh

Correct logger message documentation parsing, add to CI

---

ArduPlane/quadplane.cpp

I make it easier to recognize patterns by adjusting the grouping of functions to match the style.

Plane: Adjust the grouping of functions to match the style

---

Tools/AP_Bootloader/support.h

```
In file included from ../../libraries/AP_CheckFirmware/AP_CheckFirmware.cpp:13: ../../libraries/AP_CheckFirmware/../../Tools/AP_Bootloader/support.h:57:25: error: "CH_CFG_USE_HEAP" is not defined, evaluates to 0 [-Werror=undef]
57 | #if defined(STM32H7) && CH_CFG_USE_HEAP
|                         ^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

AP_Bootloader: correct compilation when signing enabled

---

ArduPlane/GCS_Mavlink.cpp

When a plane receives an altitude command from mavlink [SET_POSITION_TARGET_GLOBAL_INT](https://mavlink.io/en/messages/common.html#SET_POSITION_TARGET_GLOBAL_INT), we were using the booleans in the Location field to set the frame. This switches to using the altitude setter with the frame which is more explicit. 
We now convert the frames with `mavlink_coordinate_frame_to_location_alt_frame`.
Conveniently, deleting code saves 40b flash.
`./Tools/autotest/autotest.py test.Plane`. 
It seems like this might be covered by `SetpointGlobalPos`, but that test is not run by Plane.
I also used the `changealt`  and `changealt_abs` command in `GUIDED` mode while flying in SITL to verify we can change altitude. Those commands do not use this interface. 
I do not have a great way to test this as is. …

Plane Guided Alt Command: Use frame instead of bools for setting alt frame

---

Tools/AP_Periph/Parameters.cpp
libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp

Parameters are being generated as `INS_` as the group, so `INS_USE` is actually documented as `INS__USE` (note the double underscore). (See: [INS__USE: Use first IMU for attitude, velocity and position estimates](https://ardupilot.org/dev/docs/AP_Periph-Parameters.html#ins-use-use-first-imu-for-attitude-velocity-and-position-estimates)
Also fixes documentation in the battery library where the generated referenced parameter contains double underscores: (see: [BATT2_ARM_MAH: Required arming remaining capacity](https://ardupilot.org/plane/docs/parameters.html#batt2-arm-mah-required-arming-remaining-capacity))

Fix Documentation Generating Parameters Incorrectly

---

libraries/AP_DroneCAN/AP_DroneCAN.cpp
libraries/AP_DroneCAN/AP_DroneCAN.h
libraries/AP_Scripting/docs/docs.lua
libraries/AP_Scripting/examples/FlexDebug.lua
libraries/AP_Scripting/generator/description/bindings.desc
libraries/AP_Scripting/lua_bindings.cpp
libraries/AP_Scripting/lua_bindings.h

This allows lua scripts to receive FlexDebug DroneCAN messages, allowing for flexible arbitrary debug data from peripheral nodes
This was developed for debugging AM32 ESCs, but any vendor can reserve ranges of IDs

DroneCAN: added FlexDebug support

---

libraries/AP_Common/Location.h
libraries/AP_Common/tests/test_location.cpp
libraries/GCS_MAVLink/GCS_Common.cpp

we have get_alt_m already, and there's a bunch of places that *100

AP_Common: Location: add set_alt_m

---

libraries/AP_Scripting/applets/MissionSelector.lua

Ages ago file open would always succeed, we fixed the other scripts and missed this one. Now file can be `nil` so we need to check for that. This fixes the script so we can run the static checkers.

AP_Scripting: Applets: MissionSelector: fix error on file open and checker errors

---

ArduCopter/Copter.cpp
ArduCopter/Copter.h
ArduCopter/system.cpp
libraries/AP_Logger/AP_Logger.cpp
libraries/AP_Logger/AP_Logger.h

Table edited for new iterate-over-cast-structure scheme:
```
CubeRedPrimary                      *      *           -448    -408              *      *      *
Durandal                            *      *           -272    -128              *      *      *
KakuteH7-bdshot                     *      *           -424    -360              *      *      *
MatekF405                           *      *           -376    -352              *      *      *
Pixhawk1-1M-bdshot                  *                  -416    -360              *      *      * …
```

Copter: stop using global ap variable as bitmask 

---

libraries/AP_Camera/AP_RunCam.cpp
libraries/AP_Camera/AP_RunCam.h

Extracted from https://github.com/ArduPilot/ardupilot/pull/28089

AP_Camera: RunCam: get rpty channels directly using convenience functions

---

libraries/AP_Scripting/drivers/mount-djirs2-driver.lua
libraries/AP_Scripting/drivers/mount-djirs2-driver.md

In particular allows the use on a DroneCAN bus. Please see commits for details.
Tested on a DJI RS2 using firmware 01.05.00.20.

AP_Scripting: mount-djirs2: freshen driver

---

ArduCopter/ReleaseNotes.txt

I would like to make the following changes:
1. The Gregorian calendar year is set in the future.
2. There is no beta1 release.

Copter: Correct the typo

---

.github/workflows/colcon.yml
.github/workflows/cygwin_build.yml
.github/workflows/macos_build.yml
.github/workflows/test_chibios.yml
.github/workflows/test_coverage.yml
.github/workflows/test_dds.yml
.github/workflows/test_linux_sbc.yml
.github/workflows/test_replay.yml
.github/workflows/test_sitl_blimp.yml
.github/workflows/test_sitl_copter.yml
.github/workflows/test_sitl_periph.yml
.github/workflows/test_sitl_plane.yml
.github/workflows/test_sitl_rover.yml
.github/workflows/test_sitl_sub.yml
.github/workflows/test_sitl_tracker.yml
.github/workflows/test_size.yml
.github/workflows/test_unit_tests.yml

The following actions use a deprecated Node.js version and will be forced to run on node20: actions/cache@v3.
No change to be expected, only nodejs update according to changelog https://github.com/actions/cache?tab=readme-ov-file#whats-new

.github: update actions/cache to v4 to remove node version warning

---

libraries/AP_DDS/AP_DDS_Client.cpp

I want to use IS_POSITIVE and IS_NEGATIVE instead of comparing with a float value of zero.

AP_DDS: Change the comparison of float value zero to IS_XXXX

---

Dockerfile

[#28348](https://github.com/ArduPilot/ardupilot/issues/28348)
Update to Ardupilot Dockerfile used to build ardupilot code base with --enable-dds flag. The update is an installation of the Micro-XRCE-DDS-Gen dependency to use the enable-dds flag.
* Browse to the `ardupilot` source code folder.
* Build the docker developer image **the first time**:
```bash
docker build . -t ardupilot --build-arg USER_UID=$(id -u) --build-arg USER_GID=$(id -g)
```
* Run the developer container with:
```bash
docker run --rm -it -v "$(pwd):/ardupilot" -u "$(id -u):$(id -g)" ardupilot:latest bash
```
* The container will mount the ardupilot source code as volume. Now configure the target board:
```bash
./waf configure --board <board-name> --enable-dds
```
where `<board-name>` must be one of the supported …

AP_DDS: Added Micro-XRCE-DDS-GEN instal to Dockerfile.

---

ArduPlane/mode_LoiterAltQLand.cpp
libraries/AP_Follow/AP_Follow.cpp

Follow up to https://github.com/ArduPilot/ardupilot/pull/28480/files from a few other places
Testing done: CI

Use set alt m

---

Tools/ardupilotwaf/ardupilotwaf.py

Before:
`Group AP_Periph not found`
After:
```
Group AP_Periph not found, possible groups: ['antennatracker', 'copter', 'heli', 'plane', 'sub', 'blimp', 'rover', 'tool', 'examples', 'replay', 'tests']
```

Tools: ardupilotwaf: Print list of possible groups

---

Tools/AP_Bootloader/board_types.txt

Reserve ID range for TM IT-Systemhaus

AP_Bootloader: Reserve ID range for TM IT-Systemhaus

---

Tools/scripts/board_list.py

Tools: add bebop to Python all-boards list

---

Tools/AP_Bootloader/board_types.txt

This commit reserves the available board IDs within the given range of **189** to **211** for Karshak Drones. Changes are introduced after line 112 of the file **board_types.txt**, which is placed under **Tools/AP_Bootloader/board_types.txt**.

AP_Bootloader: reserve board ids and range for Karshak Drones

---

Tools/environment_install/install-prereqs-ubuntu.sh

* Used in pymavlink to add websocket output
The changes to add wsproto in https://github.com/ArduPilot/pymavlink/pull/967/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R10 do not affect the standard dev workflow.
If you fail to install wsproto, you get this in sim_vehicle.py:
Context: 
https://discord.com/channels/674039678562861068/715368769983348806/1304555852891557971
Relates to https://github.com/ArduPilot/pymavlink/pull/975

Tools: Add wsproto to ubuntu python deps

---

Tools/CodeStyle/astylerc

* It should be called add-braces not add-brackets
* https://astyle.sourceforge.net/astyle.html
* Running newer astyle fails on this option
* Enforcing it has no effect on existing astyle-formatted code
I downloaded the latest version of astyle, rather than the one installed from apt on Ubuntu 22. I ran it on our code. 
It errored out. This PR fixes the error. Code style works the same in the latest astyle as it does with our current version in Ubuntu 22. This is a pre-requisite to installing astyle in our setup scripts and starting to enforce automatically.
I installed the latest `astyle`, version `3.6.4`.
```
ryan@B650-970:~/Dev/ardu_ws/src/ardupilot$ which astyle 
/home/ryan/Dev/ardu_ws/src/astyle/build/AStyle/astyle
ryan@B650-970:~/Dev/ardu_ws/src/ardupilot$ astyle --version
Artistic …
```

Fix incorrect astyle option that breaks in astyle 3.6.4

---

Tools/environment_install/install-prereqs-arch.sh

This will check to see if the tar.bz2 file exists and if it does it will run a checksum and skip redownloading the file if its already there. If the checksum fails or the file doesn't exist it will redownload the file.
I ran into issues with the download taking so long that my sudo permissions timed out and the install failed to complete. When rerunning the script it would redownload the file even if the file was already there. This change solves this issue.

Tools: Checksum for gcc-arm download on arch prereqs

---

Tools/AP_Bootloader/board_types.txt

Reserve an ID for the upcoming MicoAir743AIOv1.

AP_Bootloader: ID reserved for MicoAir743AIOv1

---

ArduPlane/mode_qland.cpp
ArduPlane/quadplane.cpp

This fixes a bug where Qland will never land if it is entered when pilot repositioning is active.
Qland uses `landing_descent_rate_cms` which is called here: 
https://github.com/ArduPilot/ardupilot/blob/863b6222de8a3a2f8b9ffe44ab64e148a337d64e/ArduPlane/mode_qloiter.cpp#L146
This function checks `poscontrol.pilot_correction_active` and prevents descent if true here:
https://github.com/ArduPilot/ardupilot/blob/863b6222de8a3a2f8b9ffe44ab64e148a337d64e/ArduPlane/quadplane.cpp#L1279-L1282
However, `poscontrol.pilot_correction_active` is not reset on mode change, it is normally updated by `update_land_positioning` however this is never called in Qland because it does not support land repositioning.
The fix is to make sure the pilot correction is reset on entry to QLand.

QuadPlane: Fix QLand getting stuck in pilot repositioning

---

ArduPlane/defines.h

This has not been used for ages.

Plane: remove unused `ChannelMixing` enum

---

ArduCopter/mode_poshold.cpp

I can consolidate processing by using a ternary operator.
The free space has increased by 8 bytes.
AFTER
BUILD SUMMARY
Build directory: /home/parallels/work2/ardupilot/build/fmuv3
Target          Text (B)  Data (B)  BSS (B)  Total Flash Used (B)  Free Flash (B)  External Flash Used (B)
bin/arducopter   1567697      3892   192868               1571589          509164  Not Applicable   
BEFORE
BUILD SUMMARY
Build directory: /home/parallels/work2/ardupilot/build/fmuv3
Target          Text (B)  Data (B)  BSS (B)  Total Flash Used (B)  Free Flash (B)  External Flash Used (B)
bin/arducopter   1567705      3892   192868               1571597          509156  Not Applicable

Copter: Consolidate processing

---

libraries/AP_BattMonitor/AP_BattMonitor_FuelLevel_Analog.cpp

The first, second and third order polynomial fit terms and the offset can be negetive.

AP_BattMonitor : update metadata for fuellevel param ranges

---

libraries/AP_Volz_Protocol/AP_Volz_Protocol.cpp
libraries/AP_Volz_Protocol/AP_Volz_Protocol.h

Bugfix to the recent Volz protocol implementation. _motor_temp_deg_ and _pcb_temp_deg_ are both defined as uint16_t which is valid pre-scaling (ie. receiving the message from the buffer) but with scaling being done below (range -49 to +204) this will need to account for signed values.
```
case CMD_ID::TEMPERATURE_RESPONSE:
// Temperature is reported relative to -50 deg C
telem.data[index].motor_temp_deg = -50 + cmd.arg1;
telem.data[index].pcb_temp_deg = -50 + cmd.arg2;
break;
```

AP_Volz_Protocol: bugfix with scaling integer

---

Tools/autotest/helicopter.py
Tools/autotest/vehicle_test_suite.py
libraries/AP_Mount/AP_Mount_Alexmos.cpp
libraries/AP_Mount/AP_Mount_Backend.cpp
libraries/AP_Mount/AP_Mount_Backend.h
libraries/AP_Mount/AP_Mount_Gremsy.cpp
libraries/AP_Mount/AP_Mount_Params.cpp
libraries/AP_Mount/AP_Mount_SToRM32.cpp
libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
libraries/AP_Mount/AP_Mount_Scripting.cpp
libraries/AP_Mount/AP_Mount_Servo.cpp
libraries/AP_Mount/AP_Mount_Siyi.cpp
libraries/AP_Mount/AP_Mount_SoloGimbal.cpp
libraries/AP_Mount/AP_Mount_Topotek.cpp
libraries/AP_Mount/AP_Mount_Viewpro.cpp
libraries/AP_Mount/AP_Mount_Xacti.cpp

Add Mount RC failsafe handling

---

Tools/autotest/logger_metadata/enum_parse.py
libraries/AP_HAL/AP_HAL_Boards.h
libraries/AP_Logger/LogStructure.h
libraries/AP_Vehicle/AP_Vehicle_Type.h

The aim of this PR is to add help text for the VER and FILE log messages (linked to issue #26088).
Implemented by adding the relevant comment tags into AP_Logger.cpp
As well as just adding the field descriptions, I wanted to include the enumeration information for the BT, BST and BU fields of the VER message. As there are sets of #defines and not actual enums, I made the following updates:
* Add support to enum_parse.py to extract #define sets enclosed between @LoggerEnum and @LoggerEnumEnd comment tags.
* Add @LoggerEnum and @LoggerEnumEnd comment tags around HAL_BOARD and HAL_BOARD_SUBTYPE defines in AP_HAL_Boards.h.
* Add @LoggerEnum and @LoggerEnumEnd comment tags around APM_BUILD defines in AP_Vehicle_Type.h.
Tested by running parse.py for each vehicle type, and checking the output. …

AP_Logger: Add enum information to VER log message metadata

---

libraries/AP_Mission/AP_Mission_Commands.cpp

pitch is int8_t, yaw is int16_t
Completely untested.  Well, CI will make sure it compiles.

AP_Mission: do not use float functions on integers

---

Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_parameter_service.py
libraries/AP_DDS/AP_DDS_Client.cpp
libraries/AP_DDS/AP_DDS_Client.h
libraries/AP_DDS/AP_DDS_Service_Table.h
libraries/AP_DDS/AP_DDS_config.h
libraries/AP_DDS/Idl/rcl_interfaces/msg/Parameter.idl
libraries/AP_DDS/Idl/rcl_interfaces/msg/ParameterType.idl
libraries/AP_DDS/Idl/rcl_interfaces/msg/ParameterValue.idl
libraries/AP_DDS/Idl/rcl_interfaces/msg/SetParametersResult.idl
libraries/AP_DDS/Idl/rcl_interfaces/srv/GetParameters.idl
libraries/AP_DDS/Idl/rcl_interfaces/srv/SetParameters.idl

[#28292 ](https://github.com/ArduPilot/ardupilot/issues/28292)
-Add set parameters service call to AP_DDS library
- service is /ap/set_parameters
- Add get parameters service call to AP_DDS library
- service is /ap/get_parameters
Using ros2 CLI, build and launch ardupilot sitl
```
colcon build --packages-up-to ardupilot_sitl
source install/setup.bash
ros2 launch ardupilot_sitl sitl_dds_udp.launch.py transport:=udp4 synthetic_clock:=True wipe:=False model:=quad speedup:=1 slave:=0 instance:=0 defaults:=$(ros2 pkg prefix ardupilot_sitl)/share/ardupilot_sitl/config/default_params/copter.parm,$(ros2 pkg prefix ardupilot_sitl)/share/ardupilot_sitl/config/default_params/dds_udp.parm sim_address:=127.0.0.1 master:=tcp:127.0.0.1:5760 sitl:=127.0.0.1:5501
```
- Check that parameter service is up …

AP_DDS: Parameters service

---

libraries/AP_NavEKF3/AP_NavEKF3.h
libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp

~Merge after https://github.com/ArduPilot/ardupilot/pull/28396/files and change code which checks the options bit~
That PR is currently stalled, this one first, maybe?

AP_NavEKF3: add an option_is_enabled method

---

ArduCopter/AP_Arming.cpp
libraries/AP_Arming/AP_Arming.cpp

Update a clang pragma to check for the proper version of clang that introduces the warning.

Update clang pragma that is causing trouble

---

ArduPlane/GCS_Mavlink.cpp

The MAVLink GUIDED_CHANGE_HEADING command will switch from the default to either HEADING_TYPE_HEADING or HEADING_TYPE_COG, but did not have a way to switch back to "default" this adds the code to implement HEADING_TYPE_DEFAULT which will switch the ArduPilot internal plane.guided_state.target_heading_type back to GUIDED_HEADING_NONE, which is the default value with it's own behavior.
Follow up to the MAVLink PR https://github.com/ArduPilot/mavlink/pull/372 which adds the implementation.
This PR also updates the mavlink submodule reference.

implement GUIDED_HEADING_TYPE default mavlink message

---

Tools/environment_install/install-prereqs-ubuntu.sh

Experimenting to see if we can install `astyle` by default and start enabling astyle cleanlyness on Ubuntu.

Tools: Add astyle dependency

---

libraries/AP_Mount/AP_Mount.cpp
libraries/AP_Mount/AP_Mount_Alexmos.cpp
libraries/AP_Mount/AP_Mount_Alexmos.h
libraries/AP_Mount/AP_Mount_Backend.cpp
libraries/AP_Mount/AP_Mount_Backend_Serial.cpp
libraries/AP_Mount/AP_Mount_Gremsy.cpp
libraries/AP_Mount/AP_Mount_Gremsy.h
libraries/AP_Mount/AP_Mount_SToRM32.cpp
libraries/AP_Mount/AP_Mount_SToRM32.h
libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
libraries/AP_Mount/AP_Mount_SToRM32_serial.h
libraries/AP_Mount/AP_Mount_Scripting.cpp
libraries/AP_Mount/AP_Mount_Scripting.h
libraries/AP_Mount/AP_Mount_Servo.cpp
libraries/AP_Mount/AP_Mount_Servo.h
libraries/AP_Mount/AP_Mount_Siyi.cpp
libraries/AP_Mount/AP_Mount_Siyi.h
libraries/AP_Mount/AP_Mount_Topotek.cpp
libraries/AP_Mount/AP_Mount_Viewpro.cpp
libraries/AP_Mount/AP_Mount_Viewpro.h
libraries/AP_Mount/AP_Mount_Xacti.cpp
libraries/AP_Mount/AP_Mount_Xacti.h
libraries/AP_Mount/AP_Mount_config.h
libraries/AP_Mount/SoloGimbal.cpp
libraries/AP_Mount/SoloGimbalEKF.cpp
libraries/AP_Mount/SoloGimbal_Parameters.cpp

our pattern is to include the config file and then use the relevant define, with nothing in between
``` …
```

AP_Mount: tidy header includes

---

ArduPlane/ArduPlane.cpp
libraries/AP_IOMCU/AP_IOMCU.cpp
libraries/AP_IOMCU/AP_IOMCU.h

Bench-tested using an OrangeRX and a CubeOrangePlus and a servo.  All seems right compared to master.
```
Board,plane
CubeOrangePlus,-32
```

Use RC_Channel to populate IOMCU mappings

---

libraries/AP_HAL_SITL/SITL_State.cpp

this is the loop which ensures the amount of data sent to the mavlink client (usually Python) is limited - if we don't do this then we lose vast amounts of data when running at large speedups.
By attempting to process inbound data we may realise that the TCP connection has been dropped, and in that case we will start to listen for another connection.
This allows you to terminate the sim_vehicle.py MAVProxy and have it automagically restart (when running under GDB).  This is very useful for testing MAVProxy patches with SITL; it's a different workflow to opening an output and connecting a new version of MAVProxy to that outout.

AP_HAL_SITL: process inbound data in outqueue-length delay loop

---

libraries/AP_HAL_SITL/SITL_State.h

AP_HAL_SITL: remove redundant gps state

---

Tools/scripts/powr_change.py

Was looking at Flags values when determining AccFlags output.
Old:
```
2024-11-12 19:56:17.93:  +BRICK_VALID ACCFLAGS+BRICK_VALID +SERVO_VALID ACCFLAGS+SERVO_VALID
2024-11-12 19:56:49.83:  -SERVO_VALID ACCFLAGS-SERVO_VALID +CHANGED ACCFLAGS+CHANGED
2024-11-12 19:56:50.23:  +SERVO_VALID
2024-11-12 19:56:54.93:  -SERVO_VALID ACCFLAGS-SERVO_VALID
2024-11-12 19:56:55.13:  +SERVO_VALID
2024-11-12 19:57:02.23:  -SERVO_VALID ACCFLAGS-SERVO_VALID
2024-11-12 19:57:02.43:  +SERVO_VALID
2024-11-12 19:57:05.43:  -SERVO_VALID ACCFLAGS-SERVO_VALID
2024-11-12 19:57:05.73:  +SERVO_VALID
2024-11-12 19:57:18.73:  -SERVO_VALID ACCFLAGS-SERVO_VALID
2024-11-12 19:57:19.03:  +SERVO_VALID
2024-11-12 19:57:20.93:  -SERVO_VALID ACCFLAGS-SERVO_VALID
2024-11-12 19:57:21.23:  +SERVO_VALID
2024-11-12 19:57:22.23: …
```

Tools: correct powr_change.py output for accumulated flags

---

Tools/autotest/sim_vehicle.py

Add ability to start the mavcesium server in mavproxy.
Depends on https://github.com/ArduPilot/MAVProxy/pull/1480

Tools: Add mavcesium option to sim_vehicle.py

---

Tools/scripts/decode_devid.py
libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.h

Tested on the ARKV6X rev5.
This part is functionally equivalent to the iim42652 but with higher full scale range of 32g and 4000dps.

AP_InertialSensor: added IIM42653

---

libraries/AP_DDS/AP_DDS_Client.cpp

Must be before the closing brace and `status_ok` check.

AP_DDS: move closing #endif for status publisher

---

libraries/AP_DDS/AP_DDS_Client.cpp

The macOS version of `clang`does not support initialisation of variable length arrays. Use `memset` instead.
System:
MacBook Pro M1
macOS Sonoma 14.5
Xcode 15.3 (15E204a)
Compiler details from `./waf configure`
```
% ./waf configure --board sitl --enable-dds --debug
Setting top to                           : /Users/rhys/Code/ros2/rolling/ros2-ardupilot/src/ardupilot 
Setting out to                           : /Users/rhys/Code/ros2/rolling/ros2-ardupilot/src/ardupilot/build 
Autoconfiguration                        : enabled 
Checking for program 'python'            : /Users/rhys/.venv/ros2-rolling/bin/python3 
Checking for python version >= 3.6.9     : 3.12.7 
Setting board to                         : sitl 
Using toolchain                          : native 
Checking for 'g++' (C++ …
```

AP_DDS: use memset to initialise variable size array

---

libraries/AP_Scripting/applets/copter-slung-payload.md

This NFC fixes up the formatting of the copter-sluing-payload.md file
Before:
After:

AP_Scripting: copter-slung-payload minor format fix

---

libraries/AP_VideoTX/AP_Tramp.cpp

This patch fixes a minor bug in the Tramp VTX status propagation.
The flag `_configuration_finished` in class AP_VideoTX is not set by AP_Tramp class.
Therefore VTX Power blinks in OSD forever.

AP_VideoTX: Fix _configuration_finished indication for Tramp VTX

---

AntennaTracker/Tracker.cpp
AntennaTracker/servos.cpp
ArduCopter/Copter.cpp
ArduCopter/compassmot.cpp
ArduCopter/esc_calibration.cpp
ArduCopter/motors.cpp
ArduCopter/radio.cpp
ArduPlane/ArduPlane.cpp
ArduPlane/radio.cpp
ArduPlane/servos.cpp
ArduSub/ArduSub.cpp
ArduSub/motors.cpp
Blimp/Blimp.cpp
Blimp/motors.cpp
Blimp/radio.cpp
Rover/Rover.cpp
Rover/system.cpp
Tools/AP_Periph/rc_out.cpp
libraries/AP_Motors/examples/AP_Motors_test/AP_Motors_test.cpp
libraries/AP_Vehicle/AP_Vehicle.cpp
libraries/AR_Motors/AP_MotorsUGV.cpp
libraries/SRV_Channel/SRV_Channel.h
libraries/SRV_Channel/SRV_Channel_aux.cpp
libraries/SRV_Channel/SRV_Channels.cpp

Primarily to remove the (eg.) `blheli_ptr` hacks we have to make this class work kind-of-sort-of statically.
```
----------------------------  ---------  -----  ----------  ------  ----  ----------  -----  -----  ----
Board                         AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
3DRControlZeroG                          -72    *           -48     -72               -72    -64    -72
ACNS-CM4Pilot                            -8     *           16      -8                -8     0      -16
ACNS-F405AIO                             -8     *           16      0                 -8     0      -16
AIRLink                                  -72    *           -48     -64               -72    -64    -80
AR-F407SmartBat               *
ARKV6X …
```

Create and use AP::srv(), singleton for SRV_Channels

---

AntennaTracker/GCS_Mavlink.cpp
AntennaTracker/GCS_Mavlink.h
AntennaTracker/mode.h
ArduCopter/GCS_Mavlink.cpp
ArduCopter/GCS_Mavlink.h
ArduPlane/GCS_Mavlink.cpp
ArduPlane/GCS_Mavlink.h
ArduSub/GCS_Mavlink.cpp
ArduSub/GCS_Mavlink.h
ArduSub/mode.h
Blimp/GCS_Mavlink.cpp
Blimp/GCS_Mavlink.h
Blimp/mode.h
Rover/GCS_Mavlink.cpp
Rover/GCS_Mavlink.h
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp
libraries/GCS_MAVLink/GCS_Dummy.h
libraries/GCS_MAVLink/ap_message.h

This message allows the GCS to get the list of available modes at runtime. In the future this allows things like https://github.com/ArduPilot/ardupilot/pull/28110
This requires: https://github.com/ArduPilot/mavlink/pull/374
This message is supported by the QGC daily build and has been tested using it.
For example if you connect to a plane without Quadplane enabled it will only show the fixed wing modes:
If you enable quadplane and re-connect you will then see all modes:
Current master shows a preconfigured subset of modes:
Editing a mode name in the cpp proves that it is updated with the new message:
Future work (not for this PR):
- Fillout the message more completely:
- Set `MAV_MODE_PROPERTY` bitmask for each mode.
- Set `MAV_STANDARD_MODE` enum for each mode
- Report the current mode …

MAVLink: add support for the `AVAILABLE_MODES` message

---

libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/hwdef.inc
libraries/AP_HAL_ChibiOS/hwdef/CubeYellow/hwdef.dat

don't probe for old sensor set
Replaces https://github.com/ArduPilot/ardupilot/pull/13135/files as the rebase was non-trivial and I didn't want to force-push that other branch.
I've flashed this onto a CubeOrange here and I still get a mag and three IMUs.
```
MANUAL> BARO1_DEVID: bus_type:SPI(2)  bus:4 address:2(0x2) devtype:11(0xb) BARO_MS5611 (721442)
BARO2_DEVID: bus_type:SPI(2)  bus:1 address:3(0x3) devtype:11(0xb) BARO_MS5611 (721674)
COMPASS_DEV_ID: bus_type:SPI(2)  bus:4 address:1(0x1) devtype:9(0x9) AK09916 (590114)
COMPASS_PRIO1_ID: bus_type:SPI(2)  bus:4 address:1(0x1) devtype:9(0x9) AK09916 (590114)
INS_GYR_ID: bus_type:SPI(2)  bus:4 address:4(0x4) devtype:47(0x2f) INS_ICM20602 (3081250)
INS_GYR2_ID: bus_type:SPI(2)  bus:4 address:1(0x1) devtype:44(0x2c) INS_ICM20948 (2883874) …
```

HAL_ChibiOS: cleanup cube IMUs and compasses

---

Tools/scripts/build_ci.sh
Tools/scripts/run_astyle.py
libraries/AP_DDS/README.md

Tell developers what to do if the astyle check fails. 
https://github.com/ArduPilot/ardupilot_wiki/pull/6292#discussion_r1777897717
This is what a developer will see if they push code and CI fails. 
Specifically, we went from:
```
****** Files needing formatting found.
```
to:
```
****** Files needing formatting found. Please run ./Tools/scripts/run_astyle.py
```
In the screenshot below, I intentionally broke formatting in AP_DDS_Client.h. This is what the script will display in CI.

Tools: Recommend what to do when astyle fails

---

libraries/AP_DDS/AP_DDS_Client.cpp

Follow Up to https://github.com/ArduPilot/ardupilot/pull/28337.
The Status topic is now populated with the function `in_rc_failsafe()`, which is implemented as virtual in the `RC_Channel` class.
Tested in SITL: set the parameter `SIM_RC_FAIL` to 1 and then 0. 
You should see the following texts on the GCS:
And the following result when the status topic is echoed with `ros2 topic echo /ap/status`

AP_DDS: status topic to report RC failsafe with callback function

---

libraries/AP_HAL_QURT/SPIDevice.cpp

Fix the SPI transfer special case where a send buffer is passed in even though it is a read transaction. This happens in the IMU
driver now that it has been optimized. The send buffer is the same as the read buffer even though it's just doing a read. This is
perfectly fine by SPI standards but needs special case handling in the Qurt SPI driver.

AP_HAL_QURT: Fix SPI transfer special case

---

Tools/AP_Periph/GCS_MAVLink.h
Tools/scripts/build_ci.sh

* build was broken as a mandatory virtual method was added under GCS_MAVLink, without update AP_Periph/GCS_Mavlink
* also adds CubeNode-ETH to the CI to ensure that we have a periph firmware built with GCS_MAVLink and scripting enabled.

Fix build for CubeNode ETH

---

ArduPlane/Parameters.cpp

Plane: add missing AccZ bit from GCS_PID_MASK doc

---

libraries/AP_Relay/AP_Relay.cpp

When using DroneCAN Hardpoint on a vehicle to control GPIO/Relay pins on a periph, the periph's default pin param value is ignored. This enables that.

AP_Rely: allow RELAYn_DEFAULT values on DroneCAN Periphs

---

libraries/AP_TECS/AP_TECS.cpp
libraries/AP_TECS/AP_TECS.h

not used outside this one function

AP_TECS: make _EAS a local variable

---

libraries/AP_GPS/AP_GPS_Blended.h

An unused private member variable was removed to get rid of the following Qurt compiler warning:
In file included from ../../libraries/AP_GPS/AP_GPS_Blended.cpp:5:
../../libraries/AP_GPS/AP_GPS_Blended.h:67:10: warning: private field '_output_is_blended' is not used [-Wunused-private-field]
bool _output_is_blended; // true when a blended GPS solution being output
^

Remove unused private member to get rid of compiler warning in Qurt build

---

libraries/AP_CANManager/AP_CANDriver.h
libraries/AP_CANManager/AP_CANSensor.cpp
libraries/AP_CANManager/AP_CANSensor.h
libraries/AP_DroneCAN/AP_Canard_iface.cpp
libraries/AP_DroneCAN/AP_Canard_iface.h
libraries/AP_DroneCAN/AP_DroneCAN.cpp
libraries/AP_DroneCAN/AP_DroneCAN.h

Saves a handful of bytes. 71 minutes ought to be enough for anybody!

AP_CANManager: use 32 bit timeout

---

libraries/AP_Filesystem/AP_Filesystem_Mission.cpp
libraries/AP_Filesystem/AP_Filesystem_Param.cpp

Added conditional compile tags for QURT on errno external declarations since QURT already has this. Fixes the following Qurt compiler warnings:
../../libraries/AP_Filesystem/AP_Filesystem_Param.cpp:32:12: warning: extra qualification on member '_Geterrno' [-Wextra-qualification]
extern int errno;
^
/opt/hexagon-sdk/4.1.0.4-lite/tools/HEXAGON_Tools/8.4.05/Tools/bin/../target/hexagon/include/errno.h:158:25: note: expanded from macro 'errno'
#define errno (*_CSTD _Geterrno())
^
../../libraries/AP_Filesystem/AP_Filesystem_Mission.cpp:33:12: warning: extra qualification on member '_Geterrno' [-Wextra-qualification]
extern int errno;
^
/opt/hexagon-sdk/4.1.0.4-lite/tools/HEXAGON_Tools/8.4.05/Tools/bin/../target/hexagon/include/errno.h:158:25: note: expanded from macro …

Added conditional compiling to errno declarations for QURT

---

libraries/AP_DDS/AP_DDS_Client.cpp
libraries/AP_DDS/AP_DDS_ExternalControl.cpp
libraries/AP_DDS/AP_DDS_ExternalControl.h
libraries/AP_ExternalControl/AP_ExternalControl.cpp
libraries/AP_ExternalControl/AP_ExternalControl.h

Make arming from DDS go through external control. That way, we can prevent a companion computer from arming using https://github.com/ArduPilot/ardupilot/pull/28429
We want all services that control the state of the vehicle to go through external control so we can gate them in a single place.
```
Binary Name      Text [B]       Data [B]     BSS (B)      Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  -------------  -----------  -----------  ----------------------------  -------------------------
arducopter-heli  72 (+0.0040%)  0 (0.0000%)  0 (0.0000%)  72 (+0.0039%)                                    141248
antennatracker   0 (0.0000%)    0 (0.0000%)  0 (0.0000%)  0 (0.0000%)                                      613396
arducopter       72 (+0.0040%)  0 (0.0000%)  0 …
```

Dds arm through external control

---

Tools/ardupilotwaf/boards.py
libraries/AC_Fence/AC_Fence_config.h
libraries/GCS_MAVLink/GCS_config.h

Per our goal of removing support from the codebase:
```
// CODE_REMOVAL
// ArduPilot 4.6 sends deprecation warnings for RALLY_POINT/RALLY_FETCH_POINT
// ArduPilot 4.7 stops compiling them in by default
// ArduPilot 4.8 removes the code entirely
#ifndef AP_MAVLINK_RALLY_POINT_PROTOCOL_ENABLED
#define AP_MAVLINK_RALLY_POINT_PROTOCOL_ENABLED 0
#endif
```
(similarly for fencepoint)

Stop compiling old rally/fencepoint protocols in by default

---

libraries/AP_HAL_ChibiOS/AnalogIn.cpp

need to exclude the changed flag from the comparison!

AP_HAL_ChibiOS: correct logging of MAV_POWER_STATUS_CHANGED

---

libraries/AP_HAL_QURT/UARTDriver.cpp
libraries/AP_HAL_QURT/UARTDriver.h
libraries/AP_HAL_QURT/replace.cpp

Make the receive sequence number checking on Qurt DSP per link to match what is done on the application processor side so that we don't get annoying sequence number mismatch warnings in the mini-dm output. This has no affect on functionality, just cleans up the warning messages.

Fix for Qurt DSP to Apps Proc link message sequence checking

---

ArduPlane/tailsitter.cpp

Tidy up the the tailsitter output method. The scope of the tilt left and right variables can be reduced making the code easier to follow.

Plane: tailsitter: tidy tilt left and right handling

---

libraries/AP_HAL_ChibiOS/hwdef/CubeNode-ETH/hwdef.dat

For some reason enabling GCS is breaking the PPPGW in AP_Periph

AP_HAL_ChibiOS: disable GCS in CubeNode-ETH

---

libraries/AP_Common/Location.cpp
libraries/AP_Common/Location.h
libraries/GCS_MAVLink/GCS_Common.cpp

```
CubeOrange-periph-heavy  0                                                                     
CubeRedPrimary                      -128   *           -128    -120              -128   -120   -128
Durandal                            -112   *           -104    -96               -112   -112   -112
KakuteH7-bdshot                     -112   *           -120    -120              -112   -120   -120
MatekF405                           -136   *           -144    -144              -136   -144   -144
Pixhawk1-1M-bdshot                  -144               -144    -136              -144   -144   -136 …
```

Allow inlining of Location constructor

---

Tools/AP_Bootloader/board_types.txt

AP_Bootloader: Reserve a board ID for MFE_PDB_CAN、MFE_POS3_CAN、MFE_RTK_CAN、MFE_AirSpeed_CAN.
Here are some CAN devices, and hardware definitions will be submitted later.

AP_Bootloader: Reserve 4 boards ID for MFE_PDB_CAN、MFE_POS3_CAN、MFE_RTK_CAN、MFE_AirSpeed_CAN.

---

libraries/AP_RCProtocol/spm_srxl.h

Remove unused array. This array was causing the following Qurt compiler warning:
In file included from ../../libraries/AP_RCProtocol/AP_RCProtocol_Backend.cpp:32:
../../libraries/AP_RCProtocol/spm_srxl.h:61:5: warning: array designators are a C99 extension [-Wc99-designator]
[SrxlDevType_None]              = 0x00,
^~~~~~~~~~~~~~~~~~
That is pointing out that array designators are not part of the C++ standard. They aren't even part of the C99 standard, they are an extension. So, they probably shouldn't be used in ArduPilot. It turns out that that array isn't even used anywhere so I just deleted it.

Remove an unused array

---

libraries/AP_Arming/AP_Arming.cpp

Judging from the context of the code and the error message, the Z component should be checked instead of X which is already checked in the clause above. This would lead to Z component never actually checked and X checked against two differing thresholds.
The correction should not affect the autotests since none seem to be testing for this exact message.

AP_Arming: typo fix in magnetic model check

---

ArduPlane/Plane.h
ArduPlane/servos.cpp

Rather than do the slew calculation for each throttle we can do it once and then set all throttles. Previously throttle left and right were done in a different function, this change means all throttles behave the same in all cases.

Plane: slew limit all throttles in one place

---

libraries/AP_HAL_ESP32/RCInput.cpp
libraries/AP_HAL_ESP32/RCInput.h

Enable UARTs for RC input on esp32.
This is mostly just syncing RCInput for esp32 with the version in AP_HAL_ChibiOS.
Tested on a M5Stampfly using @tpwrules's stampfly branch (https://github.com/tpwrules/ardupilot/tree/stampfly) with a Radiomaster RP2 nano ELRS receiver.
Enable RC protocol in `esp32xx.h`:
```c++
#define AP_RCPROTOCOL_ENABLED 1
```
Leave `HAL_ESP32_RCIN` undefined.
On the M5Stampfly UART1 (black 4 pin Grove connector) corresponds to SERIAL3.
Follow set up for ELRS (https://ardupilot.org/copter/docs/common-tbs-rc.html).
```bash
SERIAL3_BAUD     115
SERIAL3_OPTIONS  0
SERIAL3_PROTOCOL 23
RC_OPTIONS       8992
RSSI_TYPE        3
```
- Loop rate lower than target: ~130 Hz
- Warning about running CRSF on a non-DMA serial port.

AP_HAL_ESP32: enable uart rc

---

libraries/AP_GSOF/AP_GSOF.h

Removed unused private members in GSOF to fix these Qurt compiler warnings:
In file included from ../../libraries/AP_GSOF/AP_GSOF.cpp:4:
../../libraries/AP_GSOF/AP_GSOF.h:131:13: warning: private field 'packetcount' is not used [-Wunused-private-field]
uint8_t packetcount;
^
../../libraries/AP_GSOF/AP_GSOF.h:132:14: warning: private field 'gsofmsg_time' is not used [-Wunused-private-field]
uint32_t gsofmsg_time;
^

Removed unused private members to fix Qurt compiler warnings

---

libraries/AP_RCProtocol/spm_srxl.cpp

Added another set of braces to an initializer for a local variable to get rid of the following Qurt compiler warning:
../../libraries/AP_RCProtocol/spm_srxl.cpp:1307:26: warning: suggest braces around initialization of subobject [-Wmissing-braces]
SrxlFullID retVal = {0};
^
{}

Fixed an explicit initializer to get rid of Qurt compiler warning

---

Tools/AP_Periph/AP_Periph.cpp

Call AP_Periph:prepare_reboot() before rebooting via AP_Periph:reboot(). 
Added as parameters were not being saved in time.
Tested on: CubeNode-ETH, AP_Periph

AP_Periph: Prepare reboot before rebooting via AP_Periph:reboot()

---

libraries/AP_Airspeed/AP_Airspeed.cpp

NFC....old param reference changed to current name

AP_Airspeed:correct metadata ref to old param

---

libraries/SITL/SIM_Precland.cpp

This resolves issue https://github.com/ArduPilot/ardupilot/issues/28697
This has not been tested in any way but from inspection surely it's correct isn't it?

SITL: precland alt and dist limit doc fix

---

libraries/AP_HAL_ESP32/Scheduler.h

Breaking out https://github.com/ArduPilot/ardupilot/commit/2f86e145a83d0c07dfe60880a866aedf0266f41b from @davidbuzz's larger PR https://github.com/ArduPilot/ardupilot/pull/28514 and adding minor alignment formatting.
| name | prev | new | change |
| --- | --- | --- | --- |
| TIMER_SS | 4096 | 1024*3 | -1024 |
| MAIN_SS | 8192 | 1024*5 | -3072 |
| RCIN_SS | 4096 | 1024*3 | -1024 |
| RCOUT_SS | 4096 | 1024*1.5 | -2560 |
| WIFI_SS1 | 6192 | 1024*2.25 | -3888 |
| WIFI_SS2 | 6192 | 1024*2.25 | -3888 |
| UART_SS | 2048 | 1024*2.25 | -256 |
| DEVICE_SS | 4096 | 1024*4 | 0 |
| IO_SS | 4096 | 1024*3.5 | -512 |
| STORAGE_SS | 8192 | 1024*2 | -6144 |
- Tested on esp32 (esp32empty) and esp32s3 (esp32s2stampfly).

AP_HAL_ESP32: reduce scheduler stack sizes

---

libraries/AP_Scripting/examples/plane-callout-alt.lua

Replaces #23368 
So many countries have a limit of 400 feet when flying RPAS/UAV (rc planes). This script provides groundstation messages which can be "called out" by QGroundControl, Mission Planner. etc. to advise the pilot what their current altitude is, warn them when approaching 400 feet (or any other set limit) and call out when they have exceeded the limit.
This may not be required on an OpenTX/EdgeTX radio with something like Crossfire/Express LRS as the radio can be configured to do callouts and Yaapu telemetry has a max altitude alert, but EdgeTX won't provide ongoing altitude updates the way this script can do, and this will work with any controller, not just EdgeTX/Yaapu.
After @peterbarker  challenged me on this one, I rebased and then had to clean up/improve the example to …

Scripting example to provide altitude callouts in feet defaulting to 400ft warnings

---

libraries/AP_Soaring/AP_Soaring.h

Switch to constexpr floats instead of defines which provide better compile time safety and editor support.
You can see it's a float now.

AP_Soaring: Use constexpr instead of define for constants

---

libraries/AP_HAL_ESP32/boards/esp32empty.h

`RMTSigReader` uses the legacy `rmt` library which is repeatedly reporting a `RMT RX BUFFER FULL` error.
Comment the `#define HAL_ESP32_RCIN` line in `esp32empty.h` to provid a temporary resolution. A full fix probably requires updating `RMTSigReader` to use the esp-idf 5.3.1 version of the `rmt` library.
Build for esp32empty
```bash
$ ./waf configure --board esp32empty --debug
$ ESPBAUD=921600 ./waf copter --upload 
```
Inspect console:
```bash
$ screen /dev/cu.usbserial-0001 115200
Init ArduCopter V4.7.0-dev (1b4ac6ae)
Free RAM: 110592
OK created task _main_thread on FASTCPU
OK created task _timer_thread on FASTCPU
OK created task _rcout_thread on SLOWCPU
OK created task _rcin_thread on SLOWCPU
I (1586) wifi:wifi driver task: 3ffe7f30, prio:23, stack:6656, core=1
OK created task …
```

AP_HAL_ESP32: disable define of HAL_ESP32_RCIN on esp32empty

---

libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp

This sorts the list of rangefinders alphabetically which I hope will make it easier for users to find which one they want in the long list.  The only imperfection is perhaps 100:SITL appearing near the bottom instead of right at the bottom.
If people don't like this I could manually re-order them.
<html>
<body>
Before | After
-- | --
0:None | 0:None
1:Analog | 42:Ainstein_LR_D1
2:MaxbotixI2C | 1:Analog
3:LidarLite-I2C | 6:BBB-PRU
5:PWM | 9:Bebop
6:BBB-PRU | 34:Benewake_CAN
7:LightWareI2C | 20:Benewake-Serial
8:LightWareSerial | 19:BenewakeTF02
9:Bebop | 27:BenewakeTF03
10:MAVLink | 25:BenewakeTFminiPlus-I2C
11:USD1_Serial | 23:BlueRoboticsPing
12:LeddarOne | 24:DroneCAN
13:MaxbotixSerial | 31:GYUS42v2
14:TeraRangerI2C | 30:HC-SR04
15:LidarLiteV3-I2C | 41:JRE_Serial
16:VL53L0X or VL53L1X | …

AP_RangeFinder: alphabetise type parm docs

---

libraries/AP_Mission/AP_Mission.cpp
libraries/AP_Mission/AP_Mission.h

If you fill your mission with `DO_RETURN_PATH_START` way-points the best rejoin location calculation will take so long that the flight controller watchdogs.
This adds a worst case limit of 1000 search points. The limit used to be 254 points per `DO_RETURN_PATH_START`, the the new limit is equivalent to four maximum length return path options. This change allows a single path to be longer. 
https://github.com/ArduPilot/ardupilot/pull/28574

AP_Mission: `DO_RETURN_PATH_START` limit worst case runtime

---

libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp

This resolves issue https://github.com/ArduPilot/ardupilot/issues/27729 by using the user defined position or velocity source (e.g. EK3_SRCx_POSXY, EK3_SRCx_VELXY) whenever the caller does not specify the source.
This solution is a minimal-change solution to the problem.  Another possible solution would be to remove ResetVelocity and ResetPosition's xxxResetSoiurce argument completely and instead always just use the user defined source.
This has been lightly tested in SITL to confirm that it resolves the issue.  Below are before and after screen shots of SITL testing where the Vicon has been turned 90degrees from reality.
Before we see terrible behaviour (even worse than described in [the issue](https://github.com/ArduPilot/ardupilot/issues/27729 )) where the lane switches every 7 seconds …

AP_NavEKF3: pos and vel resets default to user defined source

---

libraries/AP_Terrain/AP_Terrain.cpp

Add local const to the AP terrain libraries. Pulled out from another branch. 
* https://isocpp.org/wiki/faq/const-correctness#retrofitting-const
* https://isocpp.org/wiki/faq/const-correctness#const-and-type-safety

AP_Terrain: Add const to locals

---

Tools/AP_Bootloader/board_types.txt

Add:
```
AP_HW_UAV-DEV-PWM-G4                 5227
AP_HW_UAV-DEV-AUAV-H7                5228
AP_HW_UAV-DEV-FC-H7                  5229
```

Tools: Add new board ids for UAV-DEV GmbH

---

Tools/environment_install/install-prereqs-ubuntu.sh

* Used in filter_size_compare_branches_csv.py

Add tabulate dependency

---

ArduPlane/altitude.cpp
Tools/autotest/arduplane.py
libraries/AP_TECS/AP_TECS.cpp
libraries/AP_TECS/AP_TECS.h

In case where the Home altitude is changed, TECS will now not reset, but offset the relevant attributes instead.
Recently one of our partners flying a quadplane reported that while doing a ship landing, their plane would continuously lose altitude.
The reason is that the most minute home altitude changes [trigger a TECS reset](https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/altitude.cpp#L47). This behaviour is about 1 year old.
In the meantime, the ship landing lua script continuously [updates the home location](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/applets/plane_ship_landing.lua#L432).
This code is ~2years old.
The combination results in the TECS constantly switching into a state of rest and becoming effectively paralyzed.
I added a new …

TECS: Correctly handle Home altitude change

---

libraries/AP_NavEKF3/AP_NavEKF3_AirDataFusion.cpp

I noticed this calculation was inconsistent with get_air_density_ratio in AP_Baro, so I checked which one is theoretically correct and AP_Baro is the winner.

AP_NavEKF3: fix computation of rho

---

libraries/AP_InertialSensor/AP_InertialSensor.cpp

if the configured freq changes on any type of notch then A and Q change, so init must be called. This does not affect only Fixed notches
related to this PR for 4.5:
https://github.com/ArduPilot/ardupilot/pull/28765
but the impact in master is much less significant, it only matters if a user changes the configured freq

AP_InertialSensor: fixed check for changes to notch filters

---

Tools/ardupilotwaf/chibios.py

I just got a new Windows 11 computer and did a fresh WSL2 install and could not push a binary to USB because "Python/Python" wasn't in the python.exe path. Not sure why that's in there, maybe it's because I installed 3.13 on the Windows side. Anyways, it's a stricter check that is unnecessary, all we care about is if we can call python.exe.

Tools: update WSL2 use in uploader.py

---

Tools/AP_Periph/AP_Periph.h
Tools/AP_Periph/rc_out.cpp
Tools/ardupilotwaf/ardupilotwaf.py
Tools/scripts/build_options.py
Tools/scripts/extract_features.py
libraries/AP_DroneCAN/AP_DroneCAN.cpp
libraries/AP_DroneCAN/AP_DroneCAN.h
libraries/AP_Logger/AP_Logger.h
libraries/AP_Logger/LogFile.cpp
libraries/AP_Logger/LogStructure.h
libraries/AP_Logger/README.md
libraries/AP_PiccoloCAN/AP_PiccoloCAN.cpp
libraries/AP_PiccoloCAN/AP_PiccoloCAN.h
libraries/AP_Servo_Telem/AP_Servo_Telem.cpp
libraries/AP_Servo_Telem/AP_Servo_Telem.h
libraries/AP_Servo_Telem/AP_Servo_Telem_config.h
libraries/AP_Servo_Telem/LogStructure.h
libraries/AP_Vehicle/AP_Vehicle.cpp
libraries/AP_Vehicle/AP_Vehicle.h
libraries/AP_Volz_Protocol/AP_Volz_Protocol.cpp
libraries/AP_Volz_Protocol/AP_Volz_Protocol.h

This adds a servo telem library. Logging only at this stage. There are some benefits, DroneCAN servo logging can be rate limited, this is currently not possible as each instance is logged when it arrives, so it is rate limited individual rather than as a block of each instance.
In the longer term scripting bindings will be added to get and provide this data. That will allow servo health checking and failsafes.

Add AP_Servo_Telem

---

ArduPlane/AP_Arming.cpp
ArduPlane/GCS_Mavlink.cpp
ArduPlane/Parameters.cpp
ArduPlane/commands_logic.cpp
ArduPlane/defines.h
ArduPlane/mode_rtl.cpp

Adds support for the `DO_RETURN_PATH_START` mission item to plane. Alternate to https://github.com/ArduPilot/ardupilot/pull/28571
`DO_RETURN_PATH_START` is marks that the vehicle can rejoin the mission at any point after that waypoint and before a landing or a `DO_LAND_START`. The mission will be re-joined on the leg which is closest to the vehicles current location. 
I had wanted to get rid of `RTL_AUTOLAND` and have a AUTO RTL mode as we do in copter. But I have not got to that yet.

Plane: support `DO_RETURN_PATH_START` mission item and command

---

libraries/AP_InertialSensor/AP_InertialSensor.cpp
libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
libraries/AP_InertialSensor/AP_InertialSensor_Backend.h

when doing the notch init() we must use the reference frequency, not the current frequency. Using the current frequency leaves us with an incorrect value for Q. If the current frequency is below the reference frequency (which shouldn't happen in 4.5, but has been seen in 4.3) then the Q can be much too low and massive phase lag can happen. I am also not 100% certain a low freq in init() can't happen in 4.5.x, the route it came in for the 4.3.x crash logs is quite complex.
The way the init() works is we call it continuously up until 30s after boot, then we call it only if the user changes the notch parameters. This means the precise state of the aircraft at the 30s after boot mark is critical. Depending on what is happening to the aircraft at 30s after boot the Q value could be a very long …

AP_InertialSensor: fixed Q calculation for notch filters

---

libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
libraries/AC_AutoTune/AC_AutoTune_Multi.h

Issue introduced in https://github.com/ArduPilot/ardupilot/pull/27370 and partially fixed in https://github.com/ArduPilot/ardupilot/pull/27762, though evidently not properly tested. Fixes #28799 .
Failing to track the maximum can result in dangerously low values being calculated for `ATC_ACCEL_[RPY]_MAX` and the vehicle becoming unflyable.
Make the variable a reference so that the maximum value is preserved between function calls.
I have tested tuning in SITL, though I have not tested flyability and I have not tested on a real vehicle. I also have not searched for similar missing reference sigils.
I observed the following tuning result differences after this fix, as compared to Copter 4.5.7 (non-listed results are virtually identical):
* roll/pitch rate D is 50% lower
* yaw E rate P/I are …

AC_AutoTune: fix tracking of maximum angular acceleration

---

libraries/AP_Scripting/examples/message_interval.lua

A new [release](https://github.com/LuaLS/lua-language-server/releases) of the lua language server results in this invalid CI failure:
```
Diagnosis complete, 2 problems found, see /__w/ardupilot/ardupilot/lualogs/check.json
/__w/ardupilot/ardupilot/libraries/AP_Scripting/examples/message_interval.lua:51:30
Code: param-type-mismatch
Cannot assign `number|uint32_t_ud` to parameter `integer`.
- `uint32_t_ud` cannot match `integer`
- Type `uint32_t_ud` cannot match `integer`
/__w/ardupilot/ardupilot/libraries/AP_Scripting/examples/message_interval.lua:49:32
Code: param-type-mismatch
Cannot assign `uint32_t_ud` to parameter `number`.
- `uint32_t_ud` cannot match `number`
- Type `uint32_t_ud` cannot match `number`
```
Previously it would not try and guess the types from a table unpack, so we …

AP_Scripting: Examples: message_interval: give checker a hint about types

---

libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
libraries/AP_InertialSensor/AP_InertialSensor_Backend.h

if the user arms within 30s of startup then stop the re-init of the sensors. This can give less accurate frequency as the sample rate may not have settled yet, but it is better than doing init of the filters while the vehicle may be flying
also fix a 32 bit millis wrap

AP_InertialSensor: stop sensors converging if motors arm

---

libraries/AP_HAL/DSP.cpp

For some reason I see this on 4.6 when using the FFT
Without it you get cnstring_nan on boot
Tested on my 5"

AP_HAL: protect against invalid values when calculating Jain's estimator

---

libraries/AP_HAL_ChibiOS/RCOutput.cpp

Please decide if you want this or #28825

AP_HAL_ChibiOS: don't throw an internal error on mismatched cork/push

---

Tools/autotest/arduplane.py
libraries/AP_Scripting/applets/UniversalAutoLand.lua
libraries/AP_Scripting/applets/UniversalAutoLand.md

Facilitates having an autoland FS mission setup for flying from fields without prior planning(or computers).....sets  up an autolanding sequence based on takeoff direction....
https://youtu.be/Y8Hn5h5h-3s?si=d7UuL5IL1rAcW1ZM

AP_Scripting: add Plane autoland applet

---

libraries/AP_Camera/AP_Camera_Backend.cpp
libraries/AP_Mount/AP_Mount.cpp
libraries/AP_Mount/AP_Mount.h

This makes two improvements to the CAMERA_FOV_STATUS message sent to the GCS:
1. the message is always sent even the gimbal is pointing upwards meaning the image location cannot be calculated
2. the camera's attitude is sent in earth-frame resolving issue https://github.com/ArduPilot/ardupilot/issues/28113
This has been lightly tested in SITL.  I'm quite confident that the first enhancement is all correct and below are some screen shots
I tested the 2nd change using printf debug and it seemed correct but SITL's gimbal simulator is a simple servo gimbal and reports even its roll and pitch in body-frame which made debugging slightly difficult.  So I'd like @robertlong13 to confirm he's happy.

Camera: CAMERA_FOV_STATUS always sent and attitude is earth-frame

---

libraries/AP_Airspeed/Airspeed_Calibration.cpp

we were wasting bandwidth sending this all the time
also fixed to support calibration messages for 2nd airspeed sensor

AP_Airspeed: don't send AIRSPEED_AUTOCAL message when disabled

---

ArduPlane/mode_takeoff.cpp
Tools/autotest/arduplane.py

in TAKEOFF mode with either very poor yaw source or no yaw source we need to use ground vector and wait for sufficient ground speed
fixes https://github.com/ArduPilot/ardupilot/issues/28681

Plane: fixed takeoff direction with no yaw source

---

Tools/autotest/arducopter.py
Tools/autotest/arduplane.py
libraries/AC_Fence/AC_Fence.cpp
libraries/AC_Fence/AC_Fence.h

This fixes 2 regressions in fence behaviour since 4.5.x.
- we had lost the pre-arm check on being inside the polygon fence for FENCE_AUTOENABLE=3
- if the user has both a RCn_OPTION=11 (FENCE) and FENCE_AUTOENABLE=3 then the autoenable did not happen

AC_Fence: fixed 2 regressions from 4.5.x

---

libraries/AP_RCProtocol/spm_srxl.cpp

Extraneous zero initializers for global / static variables were removed to get rid of the following Qurt compiler warnings:
../../libraries/AP_RCProtocol/spm_srxl.cpp:78:36: warning: suggest braces around initialization of subobject [-Wmissing-braces]
SrxlTelemetryData srxlTelemData = {0};
^
{}
../../libraries/AP_RCProtocol/spm_srxl.cpp:83:34: warning: suggest braces around initialization of subobject [-Wmissing-braces]
static SrxlDevice srxlThisDev = {0};
^
{}
../../libraries/AP_RCProtocol/spm_srxl.cpp:91:36: warning: suggest braces around initialization of subobject [-Wmissing-braces]
static SrxlReceiverStats srxlRx = {0};
^
{}
../../libraries/AP_RCProtocol/spm_srxl.cpp:91:36: warning: suggest braces around initialization of subobject [-Wmissing-braces]
static SrxlReceiverStats srxlRx = …

Remove extraneous zero initializers to clean up Qurt compiler warnings

---

libraries/AP_HAL_ESP32/SdCard.cpp

Reduce the `esp_vfs_fat_sdmmc_mount_config_t` `max_files` from 10 to 5 to prevent a malloc failure. 
- Chip: ESP32-D0WD-V3 (revision v3.1) 
- Board: `esp32empty` modified to enable SDCard with
```bash
#define HAL_ESP32_SDCARD 1
#define HAL_ESP32_SDSPI {.host=HSPI_HOST, .dma_ch=1, .mosi=GPIO_NUM_13, .miso=GPIO_NUM_15, .sclk=GPIO_NUM_14, .cs=GPIO_NUM_4}
```
The console trace below illustrates the issue (additional printf's added to `vfs_fat.c`):
```bash
Init ArduCopter V4.7.0-dev (b7ace6c6)
Free RAM: 110592
OK created task _main_thread on FASTCPU
I (2172) wifi:wifi driver task: 3ffe7264, prio:23, stack:6656, core=0
I (2172) wifi:wifi firmware version: ccaebfa
I (2174) wifi:wifi certification version: v7.0
I (2178) wifi:config NVS flash: disabled
I (2182) wifi:config nano formating: disabled …
```

AP_HAL_ESP32: reduce sdcard mount config max_files

---

libraries/AP_HAL_ESP32/targets/esp32/esp-idf/CMakeLists.txt
libraries/AP_HAL_ESP32/targets/esp32s3/esp-idf/CMakeLists.txt

Add targets from `${IDF_PATH}/tools/cmake/project.cmake` to measure the allocation of static memory.
These targets: `size`, `size-components`, `size-files`, may be used in the board build directory. For example if `board=esp32s3empty`:
```bash
$ cd ./build/esp32s3empty/esp-idf_build
$ ninja -v -v size
Total sizes:
Used stat D/IRAM:  243738 bytes (  98022 remain, 71.3% used)
.data size:   14796 bytes
.bss  size:  130256 bytes
.text size:   97659 bytes
.vectors size:    1027 bytes
Used Flash size : 1122994 bytes
.text:  925938 bytes
.rodata:  196800 bytes
Total image size: 1236476 bytes (.bin may be padded larger)
```

AP_HAL_ESP32: add targets to measure static memory sizes

---

libraries/AP_TECS/AP_TECS.cpp

we take the square of this in the only use of it
... note that the code doesn't match up with the description which says it is proportional to `1/cos(bank_angle)` (not what the code is, which is `1/sq(cos(bank_angle))`)
Tested in SITL using these patches:
```
diff --git a/libraries/AP_TECS/AP_TECS.cpp b/libraries/AP_TECS/AP_TECS.cpp
index 8a8f96cc72c..4382dc4f4d2 100644
--- a/libraries/AP_TECS/AP_TECS.cpp
+++ b/libraries/AP_TECS/AP_TECS.cpp
@@ -753,8 +753,13 @@ void AP_TECS::_update_throttle_with_airspeed(void)
// Use the demanded rate of change of total energy as the feed-forward 
demand, but add
// additional component which scales with (1/cos(bank angle) - 1) to co
mpensate for induced
// drag increase during turns.
+        const float old_cosPhi = sqrtf((rotMat.a.y*rotMat.a.y) + …
```

AP_TECS: remove unneccessary sqrtf in Phi calculations

---

libraries/AP_HAL_ChibiOS/hwdef/Sierra-F405/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/Sierra-F412/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/Sierra-F9P/hwdef.dat
libraries/AP_HAL_ChibiOS/hwdef/mRo-M10095/hwdef.dat

this is the default for peripherals
```
Board,AP_Periph
Sierra-F405,*
Sierra-F412,*
Sierra-F9P,*
mRo-M10095,*
```

hwdef: remove 'HAL_WATCHDOG_ENABLED_DEFAULT true' from periphs

---

libraries/AP_CANManager/AP_CANManager.cpp

the AP_CANManager::log_text() gets called from debug logging in AP_DroneCAN. It is a method on a common AP_CANManager object which is shared by multiple AP_DroneCAN threads.
if two threads call the debug log messages at the same time then we can end up with _log_pos greater than LOG_BUFFER_SIZE (1024) and overwrite past the end of the buffer
in the crash_dump we have for this case the next piece of memory was hal.can[0], and the overwrite of the buffer had corrupted the MessageRam_ structurre in the ChibiOS CAN interface code. That led to a hardfault on receive of a CAN message
Note that this issue only happens if CAN_LOGLEVEL is set to greater than zero, and the default is zero. So users can avoid the bug by checking they have not changed CAN_LOGLEVEL.
Also, this is likely an issue that …

AP_CANManager: fixed critical race in log_text()

---

libraries/RC_Channel/RC_Channel.cpp
libraries/RC_Channel/RC_Channel.h

Adds some more scripting aux functions for those with complicated scripts. Now you can send aux functions from the GCS were no longer limited the number of RC channels users have free.

RC_Channel: add another 8 scripting aux functions

---

libraries/AP_BattMonitor/AP_BattMonitor.cpp
libraries/AP_BattMonitor/AP_BattMonitor_AD7091R5.cpp
libraries/AP_BattMonitor/AP_BattMonitor_Analog.cpp
libraries/AP_BattMonitor/AP_BattMonitor_Backend.cpp
libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.cpp
libraries/AP_BattMonitor/AP_BattMonitor_ESC.cpp
libraries/AP_BattMonitor/AP_BattMonitor_FuelLevel_Analog.cpp
libraries/AP_BattMonitor/AP_BattMonitor_INA239.cpp
libraries/AP_BattMonitor/AP_BattMonitor_INA2xx.cpp
libraries/AP_BattMonitor/AP_BattMonitor_INA3221.cpp
libraries/AP_BattMonitor/AP_BattMonitor_SMBus.cpp
libraries/AP_BattMonitor/AP_BattMonitor_Sum.cpp
libraries/AP_BattMonitor/AP_BattMonitor_Synthetic_Current.cpp

Not sure if more files need to be added for other battery monitor types? I suppose as long as the file list has the union of all possible parameters... It doesn't look like the metadata generator deduplicates anyway, c.f. `BATTn_I2C_BUS`.

AP_BattMonitor: make INA3221 parameters visible for metadata gen

---

libraries/AP_TECS/AP_TECS.h

In the Qurt ardupilot build there is a warning for the unused variable. So, I removed it to get rid of the warning.

AP_TECS: Removed an unused variable to get rid of a compiler warning

---

Tools/environment_install/install-prereqs-ubuntu.sh

With these changes a fresh install of Ubuntu 24.10 could use the setup script in 'Tools/environment_install/install-prepreqs-ubuntu.sh'. I tested running the SITL afterwards and everything seems to work.

update install-prepreqs-ubuntu.sh to support Ubuntu 24.10 Oracular

---

Tools/autotest/arduplane.py

Regarding Plane tests on Home Alt change during flight:
- Enabled old disabled test that was already passing, but was malformed.
- Created new test variant, where the altitude change occurs during stable level flight.
The existing test should be passing since https://github.com/ArduPilot/ardupilot/pull/24487, but it was malformed. It should be checking for the absolute altitude to be constant. The relative one is supposed to change.
Additionally, before it would perform an FBWA takeoff and would switch to FBWB/CRUISE/LOITER at an altitude that might not be exactly takeoff alt. Since these modes reset the altitude setpoint upon entry, it would be hard to test for a specific altitude.
Now the takeoff happens upon TAKEOFF mode, waits for the altitude to settle and then switches the mode. …

autotest: Enabled old test and added new test on home alt reset

---

libraries/AP_Filesystem/README.md

When looking into perhaps using Mavlink FTP with the PARAM virtual file system to read params from our mobile app, I noticed some missing details around the "withdefaults" query parameter, and how this changes the structure of the returned data.
This PR updates the README file for AP_Filesystem to include these details.

AP_Filesystem: Add details of withdefaults query param to README

---

ArduPlane/ArduPlane.cpp

This addresses #28704 by passing the external Height Above Ground Level (HAGL) to `Plane::tecs_hgt_afe()`.
None so far. There is one candidate partner who's willing to try it.
I've spent a couple of hours thinking how `Plane::tecs_hgt_afe()` and `Plane::get_landing_height()` are different from each other. They seemed like a good candidate for refactoring/consolidation, and that would save the introduction of these extra lines of code.
But in the end I failed to do so, hence the duplicate code.

Plane: Pass external HAGL to TECS

---

libraries/AC_Avoidance/AC_Avoidance_Logging.cpp

```
../../libraries/AC_Avoidance/AC_Avoidance_Logging.cpp: In member function 'void AP_OABendyRuler::Write_OABendyRuler(uint8_t, bool, float, float, bool, float, const Location&, const Location&) const': ../../libraries/AC_Avoidance/AC_Avoidance_Logging.cpp:23:46: error: 'ahrs' is not a member of 'AP'
23 |         yaw         : (uint16_t)wrap_360(AP::ahrs().yaw_sensor * 0.01f),
|                                              ^~~~
```

AC_Avoidance: add missing include

---

libraries/AP_GPS/AP_GPS.cpp
libraries/GCS_MAVLink/GCS_MAVLink.h

Cast enum to an int to get rid of Qurt compiler warning when max enum value is less than the constant it is being compared to. Here is the warning:
../../libraries/AP_GPS/AP_GPS.cpp:1622:14: warning: result of comparison of constant 8 with expression of type 'mavlink_channel_t' is always false [-Wtautological-constant-out-of-range-compare]
if (chan >= MAVLINK_COMM_NUM_BUFFERS) {
~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~

Cast enum to int to fix Qurt compiler warning

---

libraries/AP_ADSB/AP_ADSB.cpp
libraries/AP_ADSB/AP_ADSB.h
libraries/AP_ADSB/AP_ADSB_Sagetech_MXS.cpp
libraries/AP_ADSB/AP_ADSB_uAvionix_MAVLink.cpp

refactor an enum table to the base class. This is a clean up to help simplify PR https://github.com/ArduPilot/ardupilot/pull/28740 as requested by @peterbarker in PR https://github.com/ArduPilot/ardupilot/pull/28739

AP_ADSB: refactor a table

---

libraries/AP_ADSB/AP_ADSB.cpp
libraries/AP_ADSB/AP_ADSB.h

refactor IDENT so that the two methods cmd_int MAV_CMD_DO_ADSB_OUT_IDENT and handle_out_control() plus add gcs_sendtext feedbacl
This also removes the rfselect check which is not used by uAvionix driver(s) and is unnecessary anyways.

AP_ADSB: refactor IDENT and add gcs_sendtext feedback

---

libraries/AP_ADSB/AP_ADSB.cpp
libraries/AP_ADSB/AP_ADSB.h
libraries/AP_ADSB/AP_ADSB_Sagetech_MXS.cpp
libraries/AP_ADSB/AP_ADSB_uAvionix_UCP.cpp

Add ability to force Mode3AC Only (disable Mode-S aka ADSB). Technically this can be controlled by the GCS via MAVLink but none implement it and it can totally ground your aircraft if you can't do it immediately, no matter what GCS you're running.
variable description says it all:
```
// @Description: Transmit in traditional Mode 3A/C only and inhibit Mode-S and ES (ADSB) transmissions. This is useful when an ATC (Air Traffic control) requests it in certain scenarios.
// @Values: 0:Transmit all Modes (3A 3C S ES), 1:Transmit Mode 3A/C only (no ADSB).
```
I also added a minor refactor.

AP_ADSB: add ability to force Mode3AC Only

---

.github/workflows/esp32_build.yml
libraries/AP_HAL_ESP32/targets/esp32/esp-idf/CMakeLists.txt
libraries/AP_HAL_ESP32/targets/esp32s3/esp-idf/CMakeLists.txt

Use the default Ubuntu package for cmake rather than install the latest from kitware.
- The esp-idf requires a cmake minimum version of 3.16 (https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/build-system.html#mandatory-parts)
- The Ubuntu 22.04 package for cmake installs version 3.22.1 (https://launchpad.net/ubuntu/jammy/+source/cmake).
- => default package from `sudo apt install cmake` meets requirements

.github: esp32_build: use default cmake package

---

libraries/SITL/SIM_Airspeed_DLVR.cpp
libraries/SITL/SIM_BattMonitor_SMBus_Maxell.cpp
libraries/SITL/SIM_BattMonitor_SMBus_Rotoye.cpp
libraries/SITL/SIM_MS5525.cpp
libraries/SITL/SIM_MS5611.cpp
libraries/SITL/SIM_Temperature_MCP9600.cpp
libraries/SITL/SIM_Temperature_TSYS01.cpp

Follow up to https://github.com/ArduPilot/ardupilot/pull/28848 to use standard include pattern.

SITL: follow standard pattern for including ENABLED guards

---

libraries/AP_HAL_QURT/RCOutput.cpp
libraries/AP_HAL_QURT/RCOutput.h
libraries/AP_HAL_QURT/interface.h

Adding in support for the ModalAI IO board. This can be used to interface to PWM ESCs since the VOXL boards have no PWM capability on their own. This code will attempt to detect whether a ModalAI ESC is attached or the ModalAI IO board. Depending on what it detects it will send the appropriate PWM commands.
This has been flight tested with ModalAI ESC to verify that the original functionality has not been impacted.
This has been bench tested with a ModalAI IO board and 4 PWM ESCs. Can arm and spin up motors. RC throttle will control motor spin speed. Still needs an actual flight test but I think the PR is good to go at this time.

AP_HAL_QURT: Add support for the ModalAI IO board to support PWM ESCs

---

libraries/AP_Mount/AP_Mount_Backend.h

We are hoping to pull more target calculations into the frontend.
Having these non-private threatens for calculations to move into the separate backends instead, so privatise them
I'm relying on the autotest suite (compilation...) and inspection for this.

AP_Mount: privatise various fields and methods

---

Tools/AP_Bootloader/board_types.txt

This ID is for a new board developping by JAE.

AP_Bootloader: reserve a board ID for JFB200

---

.github/workflows/cygwin_build.yml
.github/workflows/esp32_build.yml
Tools/environment_install/install-prereqs-alpine.sh
Tools/environment_install/install-prereqs-windows-andAPMSource.ps1
Tools/environment_install/install-prereqs-windows.ps1
libraries/AP_HAL_ESP32/README.md

These were equivalents for installing python-is-python3 packages on Ubuntu.
We really shouldn't need these now - esp. since we don't do this on Ubuntu any more.
If we are invoking Python now we should be doing so as "python3".

Stop making python an alias for python3 in environment setups

---

libraries/AP_Generator/AP_Generator.cpp
libraries/AP_Generator/AP_Generator_Backend.cpp
libraries/AP_Generator/AP_Generator_IE_2400.cpp
libraries/AP_Generator/AP_Generator_IE_650_800.cpp
libraries/AP_Generator/AP_Generator_IE_FuelCell.cpp
libraries/AP_Generator/AP_Generator_RichenPower.cpp

```
CubeBlack                           -656   *           -664    -656              -664   -664   -656
CubeOrangePlus                      -672   *           -664    -672              -672   -672   -664
CubeRedPrimary                      -32    *           -40     -40               -40    -40    -32
Durandal                            -664   *           -672    -664              -672   -672   -664
KakuteH7-bdshot                     -40    *           -32     -40               -40    -32    -32 …
```

AP_Generator: apply -Os to all cpp files

---

libraries/AP_NavEKF2/AP_NavEKF2.cpp
libraries/AP_NavEKF3/AP_NavEKF3.cpp

the core.h file adjusts the optimisation level; use it when including the AP_NavEKFx.h header file
this should be done consistently across the .cpp files to ensure everything is compiled with the same optimisation level.
```
Durandal                            -80    *           -72     -72               -72    -80    -80
KakuteH7-bdshot                     -96    *           -88     -88               -88    -88    -88
MatekF405                           -72    *           -64     -64               -64 …
```

AP_NavEKFx: apply -O2 to AP_NavEKFx.h

---

Rover/GCS_Mavlink.cpp
Rover/GCS_Mavlink.h
Rover/Log.cpp
libraries/GCS_MAVLink/GCS.h
libraries/GCS_MAVLink/GCS_Common.cpp

... and reduce the default rate
this is currently unconditionally streamed at 50Hz, chewing up all available bandwidth on some telemetry radios.

Rover: allow WATER_DEPTH mavlink message rate to be specified

---

libraries/AP_AHRS/AP_AHRS.cpp
libraries/AP_AHRS/AP_AHRS.h
libraries/AP_AHRS/AP_AHRS_Backend.h
libraries/AP_AHRS/AP_AHRS_DCM.cpp
libraries/AP_AHRS/AP_AHRS_DCM.h
libraries/AP_AHRS/AP_AHRS_SIM.cpp
libraries/AP_AHRS/AP_AHRS_SIM.h

This is a no-compiler-output change designed to clarify which sort of airspeed is being used within DCM.
It shows up three places where we use the wrong sort of airspeed - within DCM for drift correction and externally via `airspeed_estimate`
```
MatekF405                           *      *           *       * …
```

Rename airspeed estimate members in AP_AHRS

---

Tools/autotest/vehicle_test_suite.py

need to clear the read buffers before re-polling sensors - just in case we don't need to!

autotest: fix FRSkyPassThroughSensorIDs test

---

Rover/GCS_Mavlink.h

This changes means that if the user or GCS uses the [REQUEST_DATA_STREAM mavlink message](https://ardupilot.org/dev/docs/mavlink-requesting-data.html#using-request-data-stream) to set the desired stream rates, the SRx_xxx parameter changes will not be saved to eeprom.  The parameters are still updated (which is probably not good) but they're not saved so they return to their defaults when the vehicle is rebooted.
This makes Rover consistent with Copter
I can imagine that in the distant past we may have received support requests from user asking, "why isn't my telemetry appearing?" but I think those days are long gone and this is no longer necessary
This has been lightly tested in SITL

Rover: mavlink stream rate requests not saved to params

---

libraries/AC_AttitudeControl/AC_PosControl.cpp
libraries/AC_AttitudeControl/AC_PosControl.h
libraries/AP_Scripting/applets/follow-target-send.lua
libraries/AP_Scripting/applets/follow-target-send.md
libraries/AP_Scripting/docs/docs.lua
libraries/AP_Scripting/generator/description/bindings.desc
libraries/AP_Scripting/modules/MAVLink/mavlink_msg_FOLLOW_TARGET.lua

This adds a follow-target-send.lua applet which can send the [FOLLOW_TARGET](https://github.com/ArduPilot/mavlink/blob/master/message_definitions/v1.0/common.xml#L5532) mavlink message to other vehicles.  This will be used in the cooperative lift and/or copter-ship-landing work.
This has been lightly tested in SITL and below is a screenshot from MP's MAVLink inspector sent from a vehicle flying North at 10m/s in Guided mode
I was hoping to test [Follow mode](https://ardupilot.org/copter/docs/follow-mode.html) with [multiple vehicles in SITL](https://ardupilot.org/dev/docs/using-sitl-for-ardupilot-testing.html#swarming-with-sitl) but it looks like mavlink messages are not passed between them.
BTW the mavlink spec for the [FOLLOW_TARGET](https://github.com/ArduPilot/mavlink/blob/master/messa …

AP_Scripting, AC_PosControl: add follow-target-send.lua applet

---

libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.h

TLDR; this PR allows users to be able to better control how fast we read ICM45686, previously we were only limited to 3.2KHz and 6.4KHz. With this PR 0.8, 1.6, 3.2 and 6.4 KHz will be achievable. And for all boards except CubeRedPrimary, the default Sensor read (FIFO read) rate will be 1.6KHz, which was previously 3.2KHz.
Additional Notes:
* We seem to be always setting ICM45686 backend loop rates atleast at 3.2KHz when fast_sampling was requested. And at 1.6KHz when it isn't.
* This PR modifies the rate at which we read from FIFO depending on requested gyro rates. We still sample at 3.2KHz or 6.4 KHz depending on requested backend loop rates, we just read from FIFO based on what read rate is requested.
When fast sampling is not requested we read FIFO at 0.8KHz
Currently there are 6 …

Do not Read FIFO faster than requested rate for ICM45686

---

libraries/AP_AHRS/AP_AHRS_DCM.cpp

This is based on https://github.com/ArduPilot/ardupilot/pull/28727 .  ~Until that is merged only the top two commits should be looked at in this PR.~ That PR has been merged.
The drift correction code was using EAS when it should be using TAS.
We were returning TAS instead of EAS when no airspeed present.
Ping @luweiagi who dug up these issues in https://github.com/ArduPilot/ardupilot/issues/25846

Correct use of TAS/EAS in DCM backend

---

libraries/AP_Scripting/examples/glide_into_wind.lua

As a response to issue #6145.
A LUA script example enables the requested feature and shows yet an other example of how to build LUA-scripts.
Script will do the following:
- If set up according to instructions, plane will turn into wind via RC-override as soon as FS_LONG has triggered GLIDE (FBWA).

LUA example Glide into wind

---

libraries/AP_Volz_Protocol/AP_Volz_Protocol.h

Moved member variable sent_count definition to proper #define block to prevent unused variable warning.

AP_Volz_Protocol: Moved member variable definition to proper block

---

libraries/AP_Proximity/AP_Proximity_LD06.cpp
libraries/AP_Proximity/AP_Proximity_LD06.h

We're using a value off the wire before it has been validated.  That value is used to limit indexing into a buffer, and that buffer isn't big enough to handle all possible "bad" values that index could take on.  Note that "read" here returns int16_t....
I've tried to simply make minimal changes in this driver to avoid the buffer overrun.

AP_Proximity: prevent buffer overflow in LD06 driver

---

.github/problem-matchers/Lua.json
.github/workflows/test_scripting.yml

This adds a problem matcher for the lua CI check. 
Its not perfect, the lua language server check regex only gets the first line of the message. There is also a limit of 10 annotations per step, so we only get 10 errors. But hopefully its a little easier than what we have now.

Github: add Lua problem matcher

---

Tools/autotest/arducopter.py

This test is to demonstrate a bug that was found in Copter's Smart RTL where if it's left in circle mode for a long time it apparently doesn't always detect the loop, so Smart RTL still runs out of space after a while.
Added as a disabled test, to be enabled by whoever fixes the bug.

autotest: Added Copter Smart RTL repeat detection test

---

libraries/AP_Scripting/applets/VTOL-quicktune.lua
libraries/AP_Scripting/docs/docs.lua
libraries/AP_Scripting/generator/description/bindings.desc

This brings the same attitude error abort protection to the lua VTOL_quicktune script as we have in the C++ version

AP_Scripting: added QUIK_ANGLE_MAX

---

Rover/GCS_Mavlink.cpp
Rover/GCS_Mavlink.h
Tools/autotest/rover.py

Requested in https://github.com/ArduPilot/ardupilot/pull/28875

Rover: cycle through rangefinders when sending WATER_DEPTH

---

Tools/AP_Bootloader/board_types.txt

Reserve Board-ID for StingBee Stellar H7V2
https://github.com/betaflight/config/blob/master/configs/STELLARH7V2/config.h

Board Types: reserve board-id for stellar H7V2

---

Tools/ardupilotwaf/boards.py
Tools/ardupilotwaf/esp32.py
libraries/AP_HAL_ESP32/RCOutput.h
libraries/AP_HAL_ESP32/boards/defaults.parm

And drop broken remnants of code using apj_tool to do it. Now just load the file at `libraries/AP_HAL_ESP32/hwdef/<board>/defaults.parm` until we get hwdef.dat support in.
According to tridge, apj_tool is deprecated anyway. It's difficult to use because the .bin has an XOR checksum and SHA256 checksum that would have to be patched up. So just switch to using the already-working ROMFS.
Tested on the stampfly.

waf: add defaults.parm support to esp32 using ROMFS

---

libraries/AP_BattMonitor/AP_BattMonitor_Analog.cpp
libraries/AP_BattMonitor/AP_BattMonitor_Synthetic_Current.cpp

If you over allocate the number of analog channels this results in a crash. It's easy to trigger this if you have voltage only monitors as we still eat up a current input channel, regarless of if we use it. There are only 16 channels at this time on ChibiOS, so if you have 9 voltage only battery monitors you are out.
This PR improves that situation by only allocating channels when needed, and in the case where we run out we now set a ConfigError, which on a flight controller is much more friendly then a instant segfault the moment we read a battery monitor. NOTE: on AP_Periph this takes the node off the bus, rather then just sitting in the bootloader. This was consideted acceptable as the current behaviour was to segfault and then sit in the bootloader, unless you made new firmware that …

AP_BattMonitor: Handle allocating too many analog channels

---

libraries/AP_RangeFinder/AP_RangeFinder.cpp

AP_RangeFinder: tidy defines around bebop rangefinder inclusion

---

Tools/autotest/arducopter.py
libraries/AP_Scripting/examples/Flip_Mode.lua

This adds a test for custom modes added from scripting.

Add test for scripting flip mode

---

ArduCopter/RC_Channel.cpp
ArduCopter/RC_Channel.h
ArduPlane/RC_Channel.cpp
ArduPlane/RC_Channel.h
Blimp/RC_Channel.cpp
Blimp/RC_Channel.h
Rover/RC_Channel.cpp
Rover/RC_Channel.h
Tools/autotest/logger_metadata/enum_parse.py
Tools/autotest/quadplane.py
libraries/AP_Button/AP_Button.cpp
libraries/AP_ICEngine/AP_ICEngine.cpp
libraries/AP_ICEngine/AP_ICEngine.h
libraries/AP_Mission/AP_Mission_Commands.cpp
libraries/AP_Scripting/generator/description/bindings.desc
libraries/GCS_MAVLink/GCS_Common.cpp
libraries/RC_Channel/RC_Channel.cpp
libraries/RC_Channel/RC_Channel.h

This removes the ICE `STARTCHN_MIN` protections and RC input thresholds instead moving over to those that are applied to all aux functions. 
Aux functions do have a min value of 800. 
https://github.com/ArduPilot/ardupilot/blob/4d75b4477550e3fccb6a1917dd8a49594d3d2c9b/libraries/RC_Channel/RC_Channel.cpp#L1897
This also moves to the aux function threshold values of 1200 and 1800 rather than the 1300 and 1700 that are used now. ICE was also using a longer de-bounce time, 300ms vs 200ms in the RC lib.
This could mean a change in behavior for some users. 
We also loose the low PWM on RC failure protection of `STARTCHN_MIN`.
We gain the ability to trigger the aux function directly from the GCS, so if RC dropout was a issue the recommendation would be to use the MAVLink command. 
I don't really …

Plane: ICE: fully move to aux function 

---

libraries/AP_HAL_QURT/RCOutput.cpp
libraries/AP_HAL_QURT/RCOutput.h

AP_HAL_QURT: Added support for PWM channels 5 to 8 when using the IO board. Currently only channels 1 to 4 are supported.

AP_HAL_QURT: Added support for PWM channels 5 to 8 when using IO board

---

Tools/AP_Periph/Web/scripts/pppgw_webui.lua
libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
libraries/AP_Scripting/applets/Heli_IM_COL_Tune.lua
libraries/AP_Scripting/applets/forward_flight_motor_shutdown.lua
libraries/AP_Scripting/applets/net_webserver.lua
libraries/AP_Scripting/applets/plane_package_place.lua
libraries/AP_Scripting/applets/x-quad-cg-allocation.lua
libraries/AP_Scripting/drivers/EFI_HFE.lua
libraries/AP_Scripting/drivers/EFI_Halo6000.lua
libraries/AP_Scripting/drivers/EFI_SkyPower.lua
libraries/AP_Scripting/examples/LED_matrix_image.lua
libraries/AP_Scripting/examples/LED_matrix_text.lua
libraries/AP_Scripting/examples/LED_roll.lua
libraries/AP_Scripting/examples/NMEA-decode.lua
libraries/AP_Scripting/examples/ahrs-source-gps-optflow.lua
libraries/AP_Scripting/examples/ahrs-source-gps-wheelencoders.lua
libraries/AP_Scripting/examples/ahrs-source.lua
libraries/AP_Scripting/examples/copter-posoffset.lua
libraries/AP_Scripting/examples/copter_deploy.lua
libraries/AP_Scripting/examples/frsky_wp.lua
libraries/AP_Scripting/examples/gen_control.lua
libraries/AP_Scripting/examples/mission-edit-demo.lua
libraries/AP_Scripting/examples/mission-load.lua
libraries/AP_Scripting/examples/plane-wind-failsafe.lua
libraries/AP_Scripting/examples/plane_guided_follow.lua
libraries/AP_Scripting/examples/set-target-location.lua
libraries/AP_Scripting/examples/test_update_target_location.lua

This fixes all the lua check issues, no more `-- luacheck: only 0`. There are still lots of lua language server issues that we should fix.....

AP_Scripting: fix outstanding luacheck issues
