AntennaTracker/mode.h, ArduCopter/mode.h, ArduPlane/mode.h, ArduSub/mode.h, Blimp/mode.h, Rover/mode.h
Reserve mode 30 for offboard so it's the same on all vehicles.
=> Offboard reserve mode ID

Tools/ardupilotwaf/boards.py, libraries/AP_HAL/board/esp32.h
There is no hardware double on esp32.
=> Tools: ardupilotwaf: esp32 does not have hardware double

libraries/AP_Logger/LogStructure.h
```
2024-12-18 02:20:27.446: RFND
TimeUS: 3111687840 µs
Instance: 0 instance
Dist: 0.23 m
Stat: 4 (Good)
Orient: 25 (ROTATION_PITCH_270)
```
(allows ROTATION_PITCH_270 to be filled in)
=> AP_Logger: add metadata giving enum for RFND.Orient

libraries/AP_HAL_ESP32/RCOutput.cpp, libraries/AP_HAL_ESP32/RCOutput.h
This is needed to fly the Stampfly. It's a significant re-engineering from the in-master state and the brushed hack that was used previously (though I've now rebased my stampfly branch to include this for those who want to try).
I tried to match the (somewhat vague) semantics of the ChibiOS HAL with regards to groups and frequencies, and I tested that the PWM output in "normal" mode still doesn't work the same way on the Stampfly, but someone needs to test it more thoroughly.
=> AP_HAL_ESP32: RCOutput: add support for brushed PWM mode

libraries/AP_AHRS/AP_AHRS.h
not associated with relevant state; the relevant state names make things clearer than this comment does
=> AP_AHRS: remove stale comment

Tools/ardupilotwaf/ap_library.py, Tools/ardupilotwaf/ardupilotwaf.py
There might be multiple copies of the flags, so remove all of them. Also pull the setup into a helper function to avoid duplicating the logic. On ChibiOS boards, this fixes SITL (which had issues with position quantization) and affects the SBF GPS driver (which was probably fine before but does change slightly).
Sim on hardware now flies smoothly instead of jittering about all over the place. SBF requires a handful more bytes but I don't think this meaningfully affects the function based on a brief read-through; the important lat/lon casts were already done manually.
Many thanks to tridge for working with me to debug this. Assuming it should be backported so that SBF works as written even if the change in behavior is negligible.
=> ardupilotwaf: properly configure double precision tasks

ArduPlane/AP_Arming.cpp, ArduPlane/GCS_MAVLink_Plane.cpp, ArduPlane/GCS_Plane.cpp, ArduPlane/Parameters.cpp, ArduPlane/Parameters.h, ArduPlane/Plane.cpp, ArduPlane/Plane.h, ArduPlane/commands_logic.cpp, ArduPlane/control_modes.cpp, ArduPlane/defines.h, ArduPlane/events.cpp, ArduPlane/mode.cpp, ArduPlane/mode.h, ArduPlane/mode_autoland.cpp, ArduPlane/mode_takeoff.cpp, ArduPlane/quadplane.h, ArduPlane/takeoff.cpp, Tools/autotest/arduplane.py, Tools/scripts/build_options.py, libraries/AP_Landing/AP_Landing.cpp, libraries/AP_Landing/AP_Landing.h, libraries/AP_Vehicle/ModeReason.h
Captures ground course when gnd speed reaches 5m/s as takeoff direction in NAV_TAKEOFF and Mode Takeoff (if a reliable way to obtain a takeoff direction in other modes is determined, this can be expanded in the future)
Currently valid only for fixed wing configuration, quadplane wont enter mode...
Upon entry creates a final approach waypoint at parameterized distance and alt from home in the opposite direction of autotakeoff direction, flies to it and does a land exactly like NAV_LAND using full landing code for aborts. (Emulates my UniversalAutoLand LUA script #28591)
~~If a DO_LAND_START sequence(s) exist, will jump to them instead~~
If takeoff direction has not been captured then it will just not enter the mode
If not flying it will not enter the mode
Adds it as a long failsafe action …
=> Plane: add Autoland mode

libraries/AP_DAL/AP_DAL.cpp, libraries/AP_NavEKF/AP_Nav_Common.h, libraries/AP_NavEKF3/AP_NavEKF3.h
if you're not including the AP_NavEKF3 header then you don't get this definition and then you won't be able to compile the DAL.
=> AP_NavEKF3: move definition of MAX_EKF_CORES

libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS_Backend.h, libraries/AP_AHRS/AP_AHRS_SIM.cpp, libraries/AP_AHRS/AP_AHRS_SIM.h
```
CubeRedPrimary                      -96    *           -96     -96               -96    -96    -96
Durandal                            -104   *           -104    -104              -104   -104   -104
KakuteH7-bdshot                     -96    *           -96     -96               -96    -96    -96
MatekF405                           -64    *           -72     -64               -64    -64    -64
Pixhawk1-1M-bdshot                  -64                -72     -72               -72    -64    -72
bebop …
```
=> Remove unused AHRS methods

libraries/AP_Filesystem/AP_Filesystem_FATFS.cpp
The delays will be canceled on return by the EXPECT_DELAY_MS(3000) destructor at the start of the function. The current behavior will unexpectedly cancel delays from higher levels up the stack and is likely not what was intended.
Tested that filesystem operations still work on SD card on Cube Orange.
Is it possible to do filesystem ops from the main thread? Should that other EXPECT_DELAY_MS be removed too?
=> AP_Filesystem: FATFS: remove redundant delay expectations

libraries/AP_HAL_ChibiOS/Scheduler.cpp, libraries/AP_HAL_ChibiOS/Scheduler.h, libraries/AP_HAL_ChibiOS/Storage.cpp
The feature to expect delays from the main thread never worked (since introduction in #14063 ) and hasn't been used since #20442 . Remove it to gain back some flash and reduce complexity.
Checked that parameter and mission ops still work on Kakute H7 Mini.
=> AP_HAL_ChibiOS: Scheduler: clean up expected delay functions

Tools/scripts/build_options.py, libraries/AP_DroneCAN/AP_DroneCAN.cpp, libraries/AP_DroneCAN/AP_DroneCAN.h
- lacked dependencies in `build_options.py`
- flat-out syntax error when it does build
```
./Tools/autotest/test_build_options.py --define-match-glob=AP_DRONECAN_VOLZ_FEEDBACK_ENABLED
```
=> Correct compilation VOLZ_FEEDBACK is enabled 

libraries/RC_Channel/RC_Channel.cpp
This fixs a bug added by me in https://github.com/ArduPilot/ardupilot/pull/28655. The init aux function call was replaced by run aux function. Init mostly just calls run, however for invalid options it does not. This fixes the "Invalid channel option (0)" warning.
In the longer term I would like to consolidate the init calls such that each function can decide based on the trigger source.
=> RC_Channel: re-instate init_aux_function call.

Tools/scripts/build_options.py, Tools/scripts/extract_features.py, libraries/AP_Mount/AP_Mount.cpp, libraries/AP_Mount/AP_Mount.h, libraries/AP_Mount/AP_Mount_Backend.cpp, libraries/AP_Mount/AP_Mount_Backend.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_config.h
Removing code as per procedure.
```
-// CODE_REMOVAL
-// ArduPilot 4.5 sends deprecation warnings for MOUNT_CONTROL/MOUNT_CONFIGURE
-// ArduPilot 4.6 stops compiling them in
-// ArduPilot 4.7 removes the code entirely
```
```
KakuteH7-bdshot                     *      *           *       *                 * …
```
=> Remove MOUNT_CONFIGURE and MOUNT_CONTROL support

Tools/autotest/vehicle_test_suite.py
that "f" in front of an f-string is important
=> autotest: corect diagnostic string

Tools/environment_install/install-prereqs-ubuntu.sh
Allow the GDB window in xterm to work in WSL with the correct (default) fonts. This is a workaround for WSL2 missing the default fonts when you just install xterm.
https://discuss.ardupilot.org/t/using-the-gdb-window-on-a-high-dpi-display-wsl/128150/2
=> Tools: Install and update necessary xterm fonts for WSL

Tools/ardupilotwaf/boards.py, libraries/AP_HAL_ESP32/targets/esp32/esp-idf/CMakeLists.txt, libraries/AP_HAL_ESP32/targets/esp32s3/esp-idf/CMakeLists.txt, libraries/AP_MultiHeap/MultiHeap_malloc.cpp
Ensure new_heap is not null before accessing, and initialise current heap usage.
- On ESP32 S3 the heap allocator is failing when attempting to create a new Lua state.
- The variable `current_heap_usage` is not initialised to zero.
=> AP_MultiHeap: initialize only if heap allocation succeeded

libraries/AP_Scripting/tests/scripting_require_test_2.lua
Explain more thoroughly how the test works using lessons learned from studying the compiled bytecode and function data.
Tested that it still fails after reverting the patches in PR #27652.
=> AP_Scripting: demystify require test

libraries/AP_Mount/AP_Mount_Topotek.cpp
This fixes the direction of pitch **rate** control in the Topotek gimbal driver (**angle** control is fine).
This bug has existed since the driver was first created in PR https://github.com/ArduPilot/ardupilot/pull/27053 but we somehow missed it during testing.  If you look closely the bug is fairly obvious from inspection because we can see the [angle control includes the minus](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mount/AP_Mount_Topotek.cpp#L819) while the [rate control does not](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mount/AP_Mount_Topotek.cpp#L848).
This has been tested on real hardware and was discovered during testing of the new Mission Planner Gimbal Control interface (see https://github.com/ArduPilot/MissionPlanner/pull/3386)
=> AP_Mount: Topotek pitch rate direction fix

libraries/AP_Filesystem/AP_Filesystem.cpp
Extract from https://github.com/ArduPilot/ardupilot/pull/28977. Currently only the old name is passed to `backend_by_path`. This function will remove the backed prefix. This means the two file names are no longer comparable. This also disallows trying to rename between two backends.
=> AP_Filesystem: Don't try and rename between backends

libraries/AP_HAL/Semaphores.h
We haven't had non-recursive semaphores since PR #13323 (commits 1284f1bd8a73cc16b1407f89652d68339947caf9).
=> AP_HAL: clarify semaphore recursion

libraries/AP_HAL_SITL/SITL_State_common.cpp, libraries/AP_HAL_SITL/SITL_State_common.h, libraries/SITL/SIM_RF_Ainstein_LR_D1.h, libraries/SITL/SIM_RF_BLping.h, libraries/SITL/SIM_RF_Benewake_TF02.h, libraries/SITL/SIM_RF_Benewake_TF03.h, libraries/SITL/SIM_RF_Benewake_TFmini.h, libraries/SITL/SIM_RF_GYUS42v2.h, libraries/SITL/SIM_RF_JRE.h, libraries/SITL/SIM_RF_Lanbao.h, libraries/SITL/SIM_RF_LeddarOne.h, libraries/SITL/SIM_RF_LightWareSerial.h, libraries/SITL/SIM_RF_LightWareSerialBinary.h, libraries/SITL/SIM_RF_MAVLink.h, libraries/SITL/SIM_RF_MaxsonarSerialLV.h, libraries/SITL/SIM_RF_NMEA.h, libraries/SITL/SIM_RF_NoopLoop.h, libraries/SITL/SIM_RF_RDS02UF.h, libraries/SITL/SIM_RF_TeraRanger_Serial.h, libraries/SITL/SIM_RF_USD1_v0.h, libraries/SITL/SIM_RF_USD1_v1.h, libraries/SITL/SIM_RF_Wasp.h
Uses an array of backends and a structure holding information about how to create a backend for the user-supplied simulation name.
Inadvertently allows you to create multiple rangefinders of the same type...
=> Tidy creation of simulated serial rangefinders

libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/sport_aerobatics.lua, libraries/AP_Scripting/applets/Script_Controller.lua
Luacheck fixes broken out from https://github.com/ArduPilot/ardupilot/pull/28931.
=> AP_Scripting: applets: fix luacheck issues in sport aerobattics and script controller

libraries/AP_Airspeed/AP_Airspeed.cpp
Mission planner reminds me this is spelled wrong every time it boots up. Let's fix it :dancers:
=> AP_Airspeed: Fix spelling in GCS message

libraries/AP_HAL_ESP32/Scheduler.cpp
Resolve issue where an illegal instruction error occurs if a task member function returns.
- FreeRTOS task functions must not return or exit while the task is active.
- vTaskDelete(NULL) deletes the calling task.
See: 
- https://www.freertos.org/Documentation/02-Kernel/04-API-references/01-Task-creation/01-xTaskCreate
- https://www.freertos.org/Documentation/02-Kernel/04-API-references/01-Task-creation/03-vTaskDelete
To replicate the issue:
- Requires https://github.com/ArduPilot/ardupilot/pull/29009.
- Configure `esp32s3empty` with the `--enable-dds` flag, build and flash.
- If the DDS transport initialisation fails, or the `AP_DDS_Client::main_loop` otherwise returns, an illegal instruction occurs.
=> AP_HAL_ESP32: ensure task is deleted if member proc returns

libraries/AP_DDS/AP_DDS_Client.cpp, libraries/AP_DDS/AP_DDS_Client.h, libraries/AP_DDS/AP_DDS_Topic_Table.h
Miscellaneous fixes to ensure that the various enable options in `AP_DDS_config.h` work as intended.
-  Building for ESP32 S3 with minimal capabilities (i.e. only topics `/ap/clock` and `ap/time` enabled) is failing due to indexing errors in to the topic table and unused variables.
- Replace use of #ifdef with #if for `*_ENABLED` options.
- Exclude quaternion helper function when not required.
- Additional exclude option for HAL_BOARD_ESP32.
- Resolve uninitialised variable error observed when compiling with the esp-idf toolchain.
- Standard SITL build and test ok.
- Excluding all topics and services apart from `/ap/clock` and `/ap/time` in an `esp32s3empty` build compiles correctly.
- Note: DDS is not currently running on ESP32 due to other issues (unrelated to this PR).
_Extract from …
=> AP_DDS: configuration fixes

libraries/AP_HAL_ESP32/UARTDriver.cpp, libraries/AP_HAL_ESP32/UARTDriver.h
Add checks that UART driver functions are called on the thread the port is initialised on, and handle a change of thread ownership.
- Fix an issue where calling `UARTDriver::_begin` with a baudrate of zero (for example when changing the thread owning the UART while initialising the AP_MSP_Telem_Backend) causes a core panic due to an integer division by zero exception.
- The implementation follows the equivalent AP_HAL_ChibiOS UART driver. 
- Configure, build and flash `esp32s3empty`.
- Set `SERIAL3_BAUD 115`.
- Set `SERIAL3_PROTOCOL 32`.
- Without this change there is a core panic on the MSP thread.
- With this change a MSP GPS such as the Mateksys M8Q will work (set GPS1_TYPE = 19).
=> AP_HAL_ESP32: check UART thread ownership

libraries/AC_AutoTune/AC_AutoTune_Heli.cpp
The original implementation of this relied on the attitude controller to provide the rate and accel limiting. The rate limiting worked but it can cause square wave behavior as it clips the rate at the rate limit. As for the accel limiting, the attitude controller wasn’t designed with the feedforward turned off to limit accel. It actually reduces the angle P to reduce acceleration.  
So a different approach was taken. Using a sinusoidal input makes it easy to limit the acceleration and rate without causing any clipping.   The attitude amplitude was modified based on the first and second derivative of the amplitude sinusoid chirp. This ensures the desired rate and acceleration are limited. However, the target values maybe smaller or larger based on the error and angle P. In most cases I …
=> Heli AutoTune: fix rate and accel limiting

libraries/SITL/SIM_Frame.cpp, libraries/SITL/SIM_Frame.h
Extracted from https://github.com/ArduPilot/ardupilot/pull/27598
=> SITL: support up to 32 rotors in a frame

libraries/AP_HAL/board/chibios.h
Tested on an F405, there is enough CPU to run the following:
```
INS_GYRO_RATE = 1 (2kHz)
SCHED_LOOP_RATE = 200
FSTRATE_DIV = 2 (1kHz)
SERVO_DSHOT_RATE = 1 (1kHz)
```
=> Allow individual boards to define HAL_INS_RATE_LOOP and enable on F4 with one IMU

libraries/AP_HAL_ChibiOS/hwdef/Airvolute-DCS2/hwdef-bl.dat, libraries/AP_HAL_ChibiOS/hwdef/Airvolute-DCS2/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/NucleoH743/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/NucleoH755/hwdef-bl.dat, libraries/AP_HAL_ChibiOS/hwdef/NucleoH755/hwdef.dat
the original file these were copied from has a lower limit, so deserves this comment.  These hwdefs are making the entire space available, so remove this comment.
=> hwdef: remove bad flashing-last-sector comment

.github/workflows/cygwin_build.yml, Tools/scripts/cygwin_build.sh
There are currently issues where the non-.exe-suffixed files can't be copied into the `artifacts` folder; `cp` claims "File exists". Previously this worked but the suffix was added by Cygwin so all files in `artifacts` had a `.exe` suffix anyway.
This is evidently intended, though non-intuitive, behavior: https://sourceware.org/legacy-ml/cygwin/2009-08/msg00293.html
> On Cygwin, you should avoid having a file "foo" and a file "foo.exe" in the same directory at all cost to avoid puzzeling POSIX borderline behaviour like this.  What you do is essentially in the "not supported" class of problems.
> [...] Cygwin does not check for a file "foo", if the name of the file is explicitely given as "foo.exe".
Apparently something similar was addressed in PR #20926; the current code installs files …
=> Tools: fix Cygwin CI build

libraries/AP_HAL_ChibiOS/GPIO.cpp, libraries/AP_HAL_ChibiOS/RCInput.cpp, libraries/AP_HAL_ChibiOS/RCOutput.cpp, libraries/AP_HAL_ChibiOS/hwdef/scripts/defaults_iofirmware.h, libraries/AP_HAL_ESP32/RCInput.cpp
```
pbarker@threads:~/rc/ardupilot$ ~/rc/ardupilot/Tools/scripts/filter_size_compare_branches_csv.py --hide /tmp/some.csv  
------------------------  ---------  -----  ------  ----  -----  -----  ---
Board                     AP_Periph  blimp  copter  heli  plane  rover  sub
SITL_arm_linux_gnueabihf             0      0       0     0      0      0
SITL_x86_64_linux_gnu                0      0       0     0      0      0
sw-nav-f405               112
------------------------  ---------  -----  ------  ----  -----  -----  ---
pbarker@threads:~/rc/ardupilot$ 
```
Past this the sw-nav-f405 will emit a warning via DroneCAN about any ISR flood that might occur.  That looks unlikely given the hwdef.
=> Use HAL_GCS_ENABLED in place of HAL_NO_UARTDRIVER

libraries/AP_Math/AP_Math.cpp, libraries/AP_Math/control.cpp, libraries/AP_Math/tests/test_control.cpp
Co-authored-by: Leonard Hall <leonardthall@gmail.com>
the  cross-product code can produce something slightly negative.  Stop passing that into safe_sqrt; it isn't *that* safe on SITL!
=> AP_Math: prevent FPE in SITL when limitting accel, vectors

libraries/AP_Common/Bitmask.h, libraries/AP_GPS/AP_GPS_GSOF.cpp, libraries/AP_GPS/AP_GPS_GSOF.h, libraries/AP_GSOF/AP_GSOF.cpp, libraries/AP_GSOF/AP_GSOF.h, libraries/AP_GSOF/tests/test_gsof.cpp
Refactor the GSOF parser to instead return a bitmask of which packets were parsed. Compared to before, where we used a counter for packets, which was not robust to duplicate packets, or flexible to different sets of packets. It now mirrors more commonly accepted ways of parsing such as in the inertial labs EAHRS by using a Bitmask to keep track of received packets. 
The upcoming EAHRS uses this to keep track of the **time_ms** of each required packet, and only reports `healthy` when all tracked packets have arrived recently.
* Removed unused debug macro
* Clean up docs
* The GPS driver's expected packets now has to be set at runtime, since you can't initialize an AP bitmask at compile time
The GSOF GPS driver expects packets 1,2,8,9,12 enabled. 
Previously, if it received packets …
=> Gsof bitmask flexible parser

libraries/AP_HAL_ChibiOS/hwdef/include/minimize_common.inc
```
Board                    AP_Periph  blimp  bootloader  copter  heli   iofirmware  plane  rover  sub
CubeOrange-periph-heavy  *                                                                      
CubeRedPrimary                      *      *           *       *                  *      *      *
Durandal                            *      *           *       *                  *      *      *
Hitec-Airspeed           *                                                                      
KakuteH7-bdshot                     *      *           *       *                  *      *      *
MatekF405                           -680   *           -880    -880               -352   -528   -680
Pixhawk1-1M-bdshot                  -1656              -1536   -1528              -1976  -1488  -1736 …
```
=> hwdef: remove AP_SERVO_TELEM_ENABLED on minimized boards

libraries/AP_Math/AP_Math.cpp, libraries/AP_Math/AP_Math.h
the return-value comment was just flat-out wrong.
Fix the parameter naming to make it clearer what is going on
=> AP_Math: correct description of linear_interpolate

libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_Mount/AP_Mount_Params.cpp
fix param Increment comment for xml metadata use
=> fix param Increment comment

ArduCopter/Parameters.cpp, ArduPlane/quadplane.cpp, ArduSub/Parameters.cpp, Blimp/Parameters.cpp
fix param Increment comment for xml metadata use
Related PR:
https://github.com/ArduPilot/ardupilot/pull/29036
=> Global: fix param increment description

Tools/autotest/pysim/util.py, Tools/autotest/sim_vehicle.py, libraries/AP_HAL/SIMState.cpp, libraries/AP_HAL/SIMState.h, libraries/AP_HAL_SITL/SITL_State.cpp, libraries/AP_HAL_SITL/SITL_State.h, libraries/AP_HAL_SITL/SITL_cmdline.cpp
=> Remove command-line option enabling synthetic clock 

libraries/AP_HAL_SITL/SITL_State.cpp
nullptr is checked for at the top of this function, no need to check it after that
=> AP_HAL_SITL: remove redundant nullptr checks on _sitl member

libraries/AP_RangeFinder/AP_RangeFinder_Ainstein_LR_D1.cpp, libraries/AP_RangeFinder/AP_RangeFinder_Ainstein_LR_D1.h
Multiple alert notifications.
Currently notifies the same alerts as last time.
It would be better to notify alerts that are not originally notified.
=> AP_RangeFinder: Notify different alerts

libraries/AP_DroneCAN/AP_DroneCAN.cpp, libraries/AP_PiccoloCAN/AP_PiccoloCAN.cpp, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/generator/src/main.c, libraries/AP_Servo_Telem/AP_Servo_Telem.cpp, libraries/AP_Servo_Telem/AP_Servo_Telem.h, libraries/AP_Volz_Protocol/AP_Volz_Protocol.cpp
Adds bindings for servo telem, this allows servo checks to be done in lua.
=> AP_Scripting: add bindings for servo telemetry

libraries/AP_BLHeli/AP_BLHeli.cpp
Closes https://github.com/ArduPilot/ardupilot/issues/28807
Tested with the original issue's parameters on a CubeOrangePlus
=> AP_BLHeli: normalize ESC index correctly with iomcu

libraries/AC_Avoidance/LogStructure.h, libraries/AC_Fence/LogStructure.h, libraries/AC_PrecLand/LogStructure.h, libraries/AP_AIS/LogStructure.h, libraries/AP_Beacon/LogStructure.h, libraries/AP_CANManager/LogStructure.h, libraries/AP_Camera/LogStructure.h, libraries/AP_ESC_Telem/LogStructure.h, libraries/AP_HAL/LogStructure.h, libraries/AP_Mount/LogStructure.h, libraries/AP_NavEKF2/LogStructure.h, libraries/AP_RPM/LogStructure.h, libraries/AP_Servo_Telem/LogStructure.h
this continues some work that @peterbarker has started. I ran across one of these while working on a different PR
=> save some log structure flash when features disabled

ArduPlane/Parameters.cpp, ArduPlane/quadplane.cpp
these lines are all present in 4.0.0.
Past this PR we won't convert PIDS correctly if someone attempts to upgrade to 4.7+ from 3.x
```
CubeOrange-periph-heavy  *
CubeRedPrimary                      *      *           *       *                 -1296  *      *
Durandal                            *      *           *       *                 -1504  *      *
Hitec-Airspeed           *
KakuteH7-bdshot                     *      *           *       *                 -1296  *      *
MatekF405                           *      *           *       *                 -1288  *      *
Pixhawk1-1M-bdshot                  *                  *       *                 -1288  *      *
bebop …
```
=> Plane:remove stale conversion code

libraries/AP_Soaring/AP_Soaring.cpp, libraries/AP_Soaring/AP_Soaring_config.h
* This sends the EKF estimate of the thermal to mavproxy_soar so a dev can visualize where AP thinks the thermal is and how big it is
* Useful until we have proper mavlink packets for soaring state
* I threw in the strength, which I may scale the line thickness on color it different colors depending on strength like the thermal estimators on flight instruments do. The strength is not yet used in mavproxy.
Should they be throttled to something like 4HZ? 
See https://github.com/ArduPilot/MAVProxy/pull/1500
Make sure to define HAL_SOARING_NVF_EKF_ENABLED to 1
=> AP_Soaring: Add named value float publisher of soaring thermal EKF state

libraries/AP_Mission/AP_Mission.cpp, libraries/GCS_MAVLink/MissionItemProtocol.cpp, libraries/GCS_MAVLink/MissionItemProtocol_Fence.cpp, libraries/GCS_MAVLink/MissionItemProtocol_Rally.cpp, libraries/GCS_MAVLink/MissionItemProtocol_Waypoints.cpp
Mission does not fill in all fields of the returned item, this means you can get random data. This results in getting bad data via misison ftp or scripting. The mavlink mission item protocol does not use this method. The other mission ftp types are OK because they always fill in the full set of information. 
To reproduce, upload a misison and then read it back again. For example [before.txt](https://github.com/user-attachments/files/18379386/before.txt). Testing shown for SITL but the bug also exists on real hardware.
This is what we upload:
This is what we read back on master:
With the fix we get the same as what is written:
This only shows up in the x,y,z fields of a item without location because the other fields are defaulted here: …
=> AP_Mission: get_item: ensure returned item is clean

Tools/autotest/vehicle_test_suite.py
I needed this to run valgrid locally.
=> Tools: autotest: TestSuite: `reboot_check_valgrind_log` check file exists before trying to stat it.

libraries/AP_DDS/AP_DDS_Client.cpp, libraries/AP_DDS/AP_DDS_Client.h, libraries/AP_DDS/AP_DDS_Topic_Table.h, libraries/AP_Vehicle/AP_Vehicle.h
https://github.com/ArduPilot/ardupilot/pull/29009#discussion_r1903355890
Tests Performed:
```
./waf configure --board sitl --enable-dds --disable-scripting
nice ./waf plane
```
A bit back on `master`, specifically on commit 87b0de79dfacc418ff44e4dd6afe788cfddbac65, if you tried that, you got:
Now, it compiles as expected.
=> Dds goal pub scripting dependency

Tools/AP_Periph/AP_Periph.h, Tools/AP_Periph/can.cpp
There was no acknowledgement for UAVCAN so we add it here.
Tested on: CubeNode, AP_Periph
=> AP_Periph: Add restart acknowledgement for UAVCAN

Tools/autotest/param_metadata/xmlemit.py, libraries/AP_CANManager/AP_CANManager_CANDriver_Params.cpp, libraries/AP_Mount/AP_Mount_Params.cpp, libraries/AP_OpticalFlow/AP_OpticalFlow.cpp, libraries/AP_Proximity/AP_Proximity_Params.cpp, libraries/AP_SerialManager/AP_SerialManager.cpp
This makes a small improvement in user usability by alphabetising the _PROTOCOL and _TYPE values displayed to users in GCS drop-downs.  This does not affect the order displayed in the wiki pages
This change has been tested by running, "./Tools/autotest/autotest.py build.Copter test.Copter.Parameters" and reviewing the output of the "buildlogs/apm.pdef.xml" file before and after.
The only downside of this change is perhaps that sometimes the most common items are no longer near the top.  So for example, with the SERIALx_PROTOCOL parameter, MAVLink2 is in the middle instead of at the top.  If we think this is an issue then I'm happy to manually resort them.  Personally I think the purely alphabetical order is fine but I don't feel strongly about it
Below are the changes found:
- …
=> CANManager, Mount, OpticalFlow, Proximity, SerialManager: alphabetise protocol and type param values

Tools/scripts/build_options.py, Tools/scripts/extract_features.py, libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450/hwdef.dat, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_config.h
As per the schedule:
```
-// CODE_REMOVAL
-// BATTERY2 is slated to be removed:
-// ArduPilot 4.6 stops compiling support in
-// ArduPilot 4.7 removes the code entirely
-#ifndef AP_MAVLINK_BATTERY2_ENABLED
-#define AP_MAVLINK_BATTERY2_ENABLED 0
-#endif
```
=> Remove code for sending of BATTERY2 message

libraries/AP_Camera/AP_RunCam.cpp, libraries/AP_OSD/AP_OSD.h, libraries/AP_OSD/AP_OSD_ParamScreen.cpp, libraries/RC_Channel/RC_Channel.cpp, libraries/RC_Channel/RC_Channel.h
This fixes a long standing bug, where TX stick commands do not obey AP reversal settings
=> Allow reverse channel positions on stick gesture channels

.gitignore
Adds pattern for core dumps and makes existing pattern for stack dumps more lenient, as depending on the environment they could be generated with a filename the old pattern didn't match
=> gitignore: Add correct crash dump patterns

Tools/AP_Bootloader/board_types.txt
reserve bootloader id for Stellar F4V2
=> board_types.txt: reserve bootloader id for Stellar F4V2

libraries/AP_L1_Control/AP_L1_Control.cpp
The default, the description and the wiki all say different defaults. 
https://discord.com/channels/674039678562861068/797952826847920128/1329994998128705607
=> AP_L1_Control: Remove incorrect default in param desc

libraries/AP_DroneCAN/AP_DroneCAN.h
... So Pixhawk1-1M-bdshot seems to have CAN but not xacti, which is convenient for testing this.
```
CubeOrange-periph-heavy  *                 *
Pixhawk1-1M-bdshot                  -40                -32     -32               -40    -32    -40
f103-QiotekPeriph …
```
=> AP_DroneCAN: don't delcare xacti publishers if xacti not compiled in

ArduPlane/tuning.cpp, ArduPlane/tuning.h, libraries/AP_Tuning/AP_Tuning.cpp, libraries/AP_Tuning/AP_Tuning.h
This PR includes:
Displaying the current value of the parameter being tuned
When tuning knob is in the middle (note `>` instead of `:`):
Adding PIDFF tuning sets for FixedWing mode:
1. D and P for Roll and Pitch (for quick post-autotune adjustments)
2. PIDFF for Roll
3. PIDFF for Pitch
These additions are primarily designed for tuning via FPV without requiring MAVLink modems.
I'll add PR for wiki once everything is settled, currently it is here https://github.com/Yury-MonZon/ardupilot_wiki/tree/patch-1
=> Tuning indication on OSD(and GCS)

libraries/AP_InertialSensor/AP_InertialSensor.cpp, libraries/Filter/HarmonicNotchFilter.cpp
My attempt at fixing issue: #28841
Throttle is not "Throttle" in AP_MotorsHeli, it is actually collective position.  Therefore, throttle-based tracking does not make any sense for Heli.
This is a subtly that most users will not appreciate, therefore we should help users to not make this mistake by throwing a config error if selected.
Have also changed the default notch mode for heli.
Tested in SITL only.  This is how it presents to the user upon miss-configuration:
=> Do not allow users to set throttle-based notch in Heli 

Tools/ardupilotwaf/boards.py
Followup to PR #29005 (d9e5f2d8a7581b79430568bc7a8487df6b4f3a85).
=> ardupilotwaf: fix ESP32 memory zero comment

ArduPlane/AP_Arming.cpp, ArduPlane/Plane.cpp, ArduPlane/Plane.h, ArduPlane/commands_logic.cpp, ArduPlane/mode.h, ArduPlane/mode_autoland.cpp, ArduPlane/mode_takeoff.cpp, Tools/autotest/arduplane.py, libraries/AP_Landing/AP_Landing.h
This PR enhances the new AUTOLAND mode. It adds the following new features:
1. Allows takeoff direction capture, and hence autoland direction and use, in ACRO, STABILIZE, FBWA, TRAINING, and MANUAL modes, in addition to Mode TAKEOFF and AUTO NAV_TAKEOFF, using the same criteria as currently used, the first time after arming.
2. Adds an AUTOLAND_OPTIONS option that will set this direction upon arming using a compass, if in use, instead of ground course, allowing the user to set it on the ground arbitrarily as desired, independent of the actual takeoff direction. The option is in the autoland module for future expansion
3.  the "base" leg is actually a WP_LOITER_RAD loiter to alt with tangent exit directly into the final approach waypoint and landing with proper loiter direction.
changes to …
=> Plane:mode AUTOLAND enhancements

libraries/AP_HAL_ChibiOS/hwdef/KakuteH7Mini-Nand/hwdef.dat
It has LittleFS now so it can easily use scripting.
Missed on the LittleFS PR but has worked great for me.
=> AP_HAL_ChibiOS: enable scripting on KakuteH7Mini-Nand

libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
LittleFS does not have this function implemented due to logging bandwidth, so `logger:log_file_content` is nil. Don't call it unless it exists, assuming this logging is not critical.
=> AP_Scripting: only log aerobatic trick file when supported

.vscode/launch.default.json, Tools/ardupilotwaf/vscode_helper.py, wscript
auto generate vscode launch.json for setup stm32 gdb or SITL lldb debug session in VSCODE
waf configure arg "--vs-launch", only active --debug 
example command
```./waf configure --board Pixhawk4 --debug --vs-launch```
STM32 debug need https://github.com/Marus/cortex-debug and STLINK
```./waf configure --board sitl --debug --vs-launch```
=> add vs code launch.json auto generation in waf configure

ArduCopter/AP_Arming.cpp, ArduCopter/Copter.cpp, ArduCopter/Copter.h, ArduCopter/Parameters.cpp, ArduCopter/mode.h, ArduCopter/mode_autorotate.cpp, Tools/autotest/helicopter.py, libraries/AC_Autorotation/AC_Autorotation.cpp, libraries/AC_Autorotation/AC_Autorotation.h, libraries/AC_Autorotation/RSC_Autorotation.cpp, libraries/AC_Autorotation/RSC_Autorotation.h, libraries/AP_Motors/AP_MotorsHeli.cpp, libraries/AP_Motors/AP_MotorsHeli.h, libraries/AP_Motors/AP_MotorsHeli_Dual.cpp, libraries/AP_Motors/AP_MotorsHeli_Quad.cpp, libraries/AP_Motors/AP_MotorsHeli_Single.cpp
This PR is the next step in bringing on the autorotation flight mode.  It builds on the work done in #27786 and is dependant upon it.  Hence, the diff looks very large at the moment.
The following changes have been made:
- A much needed re-structure to move more of the code out of the mode and down into the autorotation library
- Add pre-arm checks specific to the autorotation mode
- Improvement of the speed controller by moving to a full PID instead of just P and FF.  Also, the accel limiting that I had previously implemented was a bit weird, so I have improved that.
- Move from a stabilise style control where pilot has to do both yaw and roll control, to a lateral acceleration controller, whereby pilot requests a lateral accel component and the controller figures out the roll angle and …
=> Heli autorotation restructure mode and improve speed controller

Tools/autotest/sim_vehicle.py
On Windows 11 there is a new networking option  - mirrored - that allows direct access to the NIC which requires that we don't try and connect to the bridge when running simulations
https://learn.microsoft.com/en-us/windows/wsl/wsl-config#main-wsl-settings
=> autotest: allow wsl2 networking bridge to be ignored

Tools/autotest/vehicle_test_suite.py, libraries/SITL/SITL.cpp, libraries/SITL/SITL_Airspeed.cpp
Partially addressing https://github.com/ArduPilot/ardupilot/issues/22903 by adding documentation for ACC_TRIM, ARSPD parameters.
CI check:
=> SITL : ACC, ARSPD Parameter documentation

Tools/autotest/vehicle_test_suite.py
because it is dramatically aesthetically wrong
=> autotest: add missing closing-parenthesis

ArduCopter/RC_Channel_Copter.cpp, ArduCopter/mode_auto.cpp, ArduPlane/commands.cpp, ArduSub/mode_auto.cpp, Rover/RC_Channel_Rover.cpp, Rover/commands.cpp, Rover/mode_auto.cpp, Tools/autotest/arducopter.py, libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Mission/AP_Mission.cpp, libraries/AP_Mission/AP_Mission.h, libraries/GCS_MAVLink/GCS_Common.cpp
This is a result of the discussion on https://github.com/ArduPilot/ardupilot/pull/29039. The two key things are:
- `AP_Mission::add_cmd` will add home if needed and then add the passed in command so that the passed in command is always added and not lost in index 0.
- `AP_Mission::replace_cmd` will not replace the command in index 0, but it does still return true in that case.
- `AP_Mission::write_home_to_storage` will set `_cmd_total` to 1 if it is 0.
There are also a number of clean ups and bug fixes:
- new `present()` method on mission which consolidates all the places that were trying to tell if there was a mission. We had been using `mission.num_commands() > 1` and `mission.num_commands() <= 1` or ` mission.num_commands() < 2`  for not present. This also replaces …
=> AP_Mission: better deal with home being in index 0.

Tools/ardupilotwaf/boards.py
Allows better use of math instructions as opposed to calling library functions to implement math like `sqrt`. This saves flash and increases speed. ArduPilot does not use EDOM or ERANGE anyway.
Might cause issues with malloc errno:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88576 but ArduPilot does not check for ENOMEM or use errno much anyway.
```
Board                    AP_Periph  blimp  bootloader  copter  heli   iofirmware  plane  rover  sub
CubeOrange-periph-heavy  -400              *
Durandal                            -352   *           -1216   -1000              -1344  -744   -640
KakuteH7-bdshot                     368    *           0       208                216    352    400
MatekF405                           16     * …
```
=> ardupilotwaf: add -fno-math-errno to ChibiOS boards

libraries/SRV_Channel/SRV_Channel.cpp
Similar to PR https://github.com/ArduPilot/ardupilot/pull/29075 this alphabetises the SERVOx_FUNCTION parameter description to make selecting from a drop-down easier for the user.  As with previous changes this only affects the apm.pdef.xml file meaning the GCSs show the change but the wiki's full parameter list is not affected
In some ways its not perfect in that "Motor10" appears immediately after "Motor1".  Similarly "Scripting10" appears immediately after "Scripting1".  Still, it's easier to maintain than a fully manual list
After the change:
```
<param humanName="Servo output function" name="SERVO1_FUNCTION" documentation="Function assigned to this servo. Setting this to Disabled(0) will setup this output for control by auto missions or MAVLink servo set commands. any other value …
```
=> SRV_Channel: alphabetise function param desc

libraries/AP_BoardConfig/AP_BoardConfig.cpp, libraries/AP_BoardConfig/AP_BoardConfig.h, libraries/AP_BoardConfig/board_drivers.cpp
Currently four boards support SERIAL7 with flow control, but there is no support for controlling this via BRD_SER7_RTSCTS. This fixes the problem
=> AP_BoardConfig: support flow control control on UARTs 6->8

libraries/AP_Scripting/applets/video-stream-information.lua
This fixes the video-stream-information.lua script's parameter table key so that it doesn't conflict with the [ahrs-set-origin.lua](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/applets/ahrs-set-origin.lua) script
This overlap is my fault but also quite recent (6 weeks ago)
- Nov 29th PR https://github.com/ArduPilot/ardupilot/pull/28770
- Nov 30th PR https://github.com/ArduPilot/ardupilot/pull/28780
I know of 1 partner using the ahrs-set-origin script and at most 2 developers using video-stream-information.lua.  I figure the two developers will be able to handle the change more easily which is why I've chosen to modify the video script.
=> AP_Scripting: video-stream-information param index fix

AntennaTracker/Tracker.cpp, AntennaTracker/Tracker.h, AntennaTracker/sensors.cpp, ArduPlane/Plane.cpp, ArduPlane/Plane.h, Rover/Rover.cpp, Rover/Rover.h, Rover/sensors.cpp, Tools/autotest/arduplane.py, libraries/AP_Compass/AP_Compass.cpp, libraries/AP_Compass/AP_Compass.h
57a3bc1397239cbd66e5b32d59dcc467003e4bad changed the code from "internal" to "in-flight
It seems the old value of "1" was no longer valid
It also changed things so that the learning system saved the offsets.
We have two sorts of compass learning:
- in-flight compass learning, type=3
- copy-values-from-EKF, type=2
Copy-values-from-EKF sets-and-saves offsets on a per-vehicle basis at the moment, eg. https://github.com/ardupilot/ardupilot/blob/master/ArduCopter/AP_Arming.cpp#L814 so it doesn't want or need this code.
The in-flight learning system sets-and-saves the offsets via a called to fixed-mag-cal-yaw code here: https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_Compass/Compass_learn.cpp#L65 (https://github.com/ardupilot/ardupilot/master/libraries/AP_Compass/AP_Compass_Calib …
=> Remove vestiges of LearnType::LEARN_INTERNAL

libraries/AP_Soaring/AP_Soaring.cpp, libraries/AP_Soaring/AP_Soaring.h
Follow up from today's dev call covering https://github.com/ArduPilot/ardupilot/pull/29030, we should rate limit the named value float thermal estimates to avoid flooding the GCS link. 
I chose 4Hz. 
See https://github.com/ArduPilot/MAVProxy/pull/1500 for test instructions.
To test, I checked the packet reception times in mavproxy to see they are ~4hz.
This code block is disabled by default.
```
./Tools/autotest/autotest.py build.Plane test.Plane.Soaring --map --speedup=1 --waf-configure-args "--define HAL_SOARING_NVF_EKF_ENABLED=1"
```
=> AP_Soaring: Rate limit the NVF publishers to 4Hz

ArduPlane/Plane.h, ArduPlane/servos.cpp, ArduPlane/tailsitter.cpp, Tools/AP_Periph/rc_out.cpp, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_ICEngine/AP_ICEngine.cpp, libraries/AP_IOMCU/iofirmware/mixer.cpp, libraries/AP_KDECAN/AP_KDECAN.cpp, libraries/AP_Motors/AP_MotorsHeli_RSC.h, libraries/AP_Motors/AP_MotorsHeli_Swash.cpp, libraries/AP_Motors/AP_MotorsMatrix_6DoF_Scripting.cpp, libraries/AP_Motors/AP_MotorsMulticopter.cpp, libraries/AP_Motors/AP_Motors_Class.cpp, libraries/AP_Mount/AP_Mount_Servo.cpp, libraries/AP_Mount/AP_Mount_Servo.h, libraries/AP_Notify/NeoPixel.cpp, libraries/AP_Notify/ProfiLED.cpp, libraries/AP_PiccoloCAN/AP_PiccoloCAN.cpp, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_SerialLED/AP_SerialLED.cpp, libraries/AP_Torqeedo/AP_Torqeedo_TQBus.cpp, libraries/AR_Motors/AP_MotorsUGV.cpp, libraries/AR_Motors/AP_MotorsUGV.h, libraries/SRV_Channel/SRV_Channel.cpp, libraries/SRV_Channel/SRV_Channel.h, libraries/SRV_Channel/SRV_Channel_aux.cpp
Not only is the new name shorter, it's also more in-keeping with the way we do enum-class names elsewhere in the code.
Additionally, the word "aux" in the old name is completely misleading - this covers all servo functions, not just "auxiliary" functions!
This is a no-compiler-output-change PR:
``` …
```
=> Rename SRV_Channel::Aux_servo_function_t to SRV_Channel::Function

libraries/AP_Scripting/drivers/torqeedo-torqlink.lua, libraries/AP_Scripting/drivers/torqeedo-torqlink.md
This adds basic support for controlling Torqeedo electric boat motors that use the TorqLink protocol which is NMEA 2K with some custom messages.  This closes issue https://github.com/ArduPilot/ardupilot/issues/26617
This has been tested on real hardware and a video of the test can be seen [here](https://www.dropbox.com/scl/fi/07bvarijvf8z1j3k2ydyc/torqlink_lua_test.mp4?rlkey=wb45yoawmfvzjy6t5fpvwt3w4&dl=0)
I plan to add consuming feedback from the motors in the coming weeks but even as it is, this provides an important step forward as users are appearing on the forums asking for how they can use these motors
=> AP_Scripting: Torqeedo TorqLink lua driver

Tools/scripts/create_OEM_board.py
also fix use of global variables from within the class scope
=> Tools: create_OEM_board: use argparse to parse command-line arguments

libraries/AP_HAL_ChibiOS/hwdef/scripts/defaults_periph.h
Part of the series of PRs (like #28127 , #29128) aimed at renaming peripheral defines to the new AP_PERIPH_XX_ENABLED scheme and ensuring that those are assigned some value instead of just being defined.
=> AP_HAL_ChibiOS: create and use AP_PERIPH_AHRS_ENABLED

ArduCopter/Copter.cpp, ArduCopter/Copter.h, ArduCopter/ekf_check.cpp, ArduCopter/system.cpp
this filter is populated but never checked when checking variances
```
../../ArduCopter/ekf_check.cpp:131:5: warning: Value stored to 'height_var' is never read [deadcode.DeadStores]
height_var = hgt_variance_filt.apply(height_var, dt);
^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> Copter: remove unused hgt_variance_filt

libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
most notably this embed the "modules" directory so you can use modules in ROMFS
I've created a branch which shows this working here: https://github.com/ArduPilot/ardupilot/compare/master...peterbarker:ardupilot:DEBUG/demo-pr/modules-in-romfs?expand=1 .  It creates an OEM board which embeds a script and a library for it to use.  Note that there are several drive-by patches in that branch at this point.
=> AP_HAL_ChibiOS: chibios_hwdef.py tidy embedding of files into ROMFS

ArduCopter/AP_Arming_Copter.cpp, ArduCopter/toy_mode.cpp, ArduSub/AP_Arming_Sub.cpp, Blimp/AP_Arming_Blimp.cpp, Tools/AP_Periph/can.cpp, libraries/AP_Compass/AP_Compass.cpp, libraries/AP_Compass/AP_Compass.h, libraries/AP_Compass/AP_Compass_Calibration.cpp, libraries/AP_Compass/Compass_learn.cpp, libraries/AP_Param/AP_Param.h, libraries/AP_Relay/AP_Relay.cpp, libraries/RC_Channel/RC_Channel.cpp, libraries/SRV_Channel/SRV_Channel.h
- also adds set_and_save to AP_Enum and fixes some problems around that increased type safety.
Removes an old unused method with a bug in it.
=> Make compass LearnType enum-class and parameter AP_Enum

libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.cpp
this is falsified at the top of the function
../../libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.cpp:238:13: warning: Value stored to 'packet_ready' is never read [deadcode.DeadStores]
packet_ready = false;
^              ~~~~~
=> AP_Frsky_Telem: remove dead variable write

libraries/GCS_MAVLink/GCS_Common.cpp
this might have worked if parity1 and parity2 were static values - but theyr're not.  I'm guessing the code evolved
```
../../libraries/GCS_MAVLink/GCS_Common.cpp:6847:29: warning: Although the value stored to 'parity1' is used in the enclosing expression, the value is never actually read from 'parity1' [deadcode.DeadStores]
_passthru.parity1 = parity1 = _passthru.port1->get_parity();
^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../libraries/GCS_MAVLink/GCS_Common.cpp:6848:29: warning: Although the value stored to 'parity2' is used in the enclosing expression, the value is never actually read from 'parity2' [deadcode.DeadStores]
_passthru.parity2 = parity2 = _passthru.port2->get_parity();
^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> GCS_MAVLink: correct resetting of parity after passthhru is done

libraries/SITL/SIM_Aircraft.cpp
roll and pitch are unused if !SITL_RANGEFINDER_AS_OBJECT_SENSOR
... so move roll/pitch declaration and manipulation into the #if block where they are used
```
../../libraries/SITL/SIM_Aircraft.cpp:546:13: warning: Value stored to 'roll' is never read [deadcode.DeadStores]
roll = 0;
^      ~
../../libraries/SITL/SIM_Aircraft.cpp:551:13: warning: Value stored to 'roll' is never read [deadcode.DeadStores]
roll = 0;
^      ~
../../libraries/SITL/SIM_Aircraft.cpp:557:13: warning: Value stored to 'pitch' is never read [deadcode.DeadStores]
pitch = 0;
^       ~
../../libraries/SITL/SIM_Aircraft.cpp:562:13: warning: Value stored to 'pitch' is never read [deadcode.DeadStores]
pitch = 0;
```
=> SITL: remove dead stores from rangefinder_range

libraries/AP_ADC/AP_ADC_ADS1115.cpp, libraries/SITL/SIM_Helicopter.cpp
panic doesn't return, so pga is unused.
SIM_Helicopter changes moves a variable declaration closer to the assignments to make it clear that it assigned to.  It's also not hard to see rpm_dot is always assigned to.
=> Remove dead variable stores

Tools/autotest/autotest.py, Tools/scripts/create_OEM_board.py
Need python3 rather than just python
Also fix the help string on the create_EOM script...
=> Correct version of python invoked by clang-scan-build

libraries/AP_L1_Control/AP_L1_Control.cpp
Minor improvements to comment spacing consistency in AP_L1_Control, and fixed a typo in the NAVL1_PERIOD parameter description
=> AP_L1_Control: Fix comments and typos

libraries/AP_Logger/AP_Logger_File.cpp
This one is line noise before this patch:
Failed to create log directory /APM/LOGS : ENOSPC
=> AP_Logger: use GCS_SEND_TEXT for error message rather than stdout

libraries/AP_HAL/I2CDevice.h, libraries/AP_HAL_ChibiOS/I2CDevice.cpp, libraries/AP_HAL_ChibiOS/I2CDevice.h, libraries/AP_HAL_ESP32/I2CDevice.cpp, libraries/AP_HAL_ESP32/I2CDevice.h, libraries/AP_HAL_Empty/I2CDevice.h, libraries/AP_HAL_Linux/I2CDevice.cpp, libraries/AP_HAL_Linux/I2CDevice.h, libraries/AP_HAL_QURT/I2CDevice.cpp, libraries/AP_HAL_QURT/I2CDevice.h, libraries/AP_HAL_SITL/I2CDevice.cpp, libraries/AP_HAL_SITL/I2CDevice.h, libraries/AP_Notify/ToshibaLED_I2C.cpp, libraries/AP_Notify/ToshibaLED_I2C.h
This PR is an alternative path forward for https://github.com/ArduPilot/ardupilot/pull/16138 ; that one's been stalled for many years.
This PR adds an alternate interface for working with I2CDevice objects as allocated by AP_HAL's device manager.
The new method, `get_device_ptr` returns a pointer to an instance of I2CDevice.  This is in contrast to the existing `get_device` method which returns that pointer wrapped in an OwnPtr object.
This new interface allows the code to handle the lifetime in the same way we manage most of our objects in ArduPilot, by `delete`ing what you don't need.
This PR coverts only a single class, the ToshibaLED driver.  This patch saves about 24 bytes.  There are ~150 instances of get_device (both SPI and i2c) in the codebase, so if each use saves this amount of …
=> Add AP_HAL::I2CDeviceManager->get_device_ptr

ArduCopter/Copter.cpp
these would be leaked if the "new" call for the ModeGuidedCustom object failed.
Since resgister_custom_mode may be called multiple times we could leak memory continuously
```
../../ArduCopter/Copter.cpp:450:41: warning: Potential leak of memory pointed to by 'full_name_copy' [unix.Malloc]
mode_guided_custom[i] = NEW_NOTHROW ModeGuidedCustom(number, full_name_copy, short_name_copy);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../libraries/AP_Common/AP_Common.h:192:21: note: expanded from macro 'NEW_NOTHROW'
#define NEW_NOTHROW new(std::nothrow)
^
../../ArduCopter/Copter.cpp:452:17: warning: Potential leak of memory pointed to by 'short_name_copy' [unix.Malloc]
if (mode_guided_custom[i] == nullptr) {
^~~~~~~~~~~~~~~~~~
2 warnings generated.
```
=> Copter: free allocations in case of allocation failure

libraries/AP_AIS/AP_AIS.cpp
the third argument is space remaining in buffer, not size of buffer...
../../libraries/AP_AIS/AP_AIS.cpp:183:71: warning: Potential buffer overflow. Replace with 'sizeof(multi) - strlen(multi) - 1' or use a safer 'strlcat' API [unix.cstring.BadSizeArg]
strncat(multi,_AIVDM_buffer[msg_parts[i]].payload,sizeof(multi));
^~~~~~~~~~~~~
../../libraries/AP_AIS/AP_AIS.cpp:185:49: warning: Potential buffer overflow. Replace with 'sizeof(multi) - strlen(multi) - 1' or use a safer 'strlcat' API [unix.cstring.BadSizeArg]
strncat(multi,_incoming.payload,sizeof(multi));
=> AP_AIS: remove incorrect use of strncat

libraries/AP_Filesystem/AP_Filesystem_ROMFS.cpp, libraries/AP_Filesystem/AP_Filesystem_ROMFS.h
Lua opens scripts to load them into memory, then the logger opens them after to stream them into the dataflash log. When loading multiple large Lua scripts from ROMFS, decompression takes a significant amount of time. This creates the opportunity for the Lua interpreter and logging threads to both be inside `AP_Filesystem_ROMFS::open()` decompressing a file.
If this happens, the function can return the same `fd` for two different calls as the `fd` is chosen before decompression starts, but only marked as being used after that finishes. The read pointers then stomp on each other, so Lua loads garbled scripts (usually resulting in a syntax error) and the logger dumps garbled data.
Fix the issue by locking before searching for a free record (or marking a record as free). Apply the same fix …
=> AP_Filesystem: ROMFS: fix open race conditions

libraries/SITL/SIM_Temperature_TSYS01.cpp, libraries/SITL/SIM_Temperature_TSYS01.h
... if the driver ever asked for prom0 then we would do Very Bad Things here.
File:	build/sitl/../../libraries/SITL/SIM_Temperature_TSYS01.cpp Warning:	line 38, column 13
Assigned value is garbage or undefined
.. this shifts everything along by one to leave room for _k[0], even 'though the driver does not currently ask for it
=> SITL: fix array-bounds warning in tsys01 simulation

ArduCopter/mode_systemid.cpp
This PR addresses a problem found by Peter Barker:
Looking through some static analysis results and came across this one:
../../ArduCopter/mode_systemid.cpp:270:33: warning: The left expression of the compound assignment is an uninitialized value. The computed value will also be garbage [core.uninitialized.Assign]
target_roll += waveform_sample*100.0f;
~~~~~~~~~~~ ^
../../ArduCopter/mode_systemid.cpp:273:34: warning: The left expression of the compound assignment is an uninitialized value. The computed value will also be garbage [core.uninitialized.Assign]
target_pitch += waveform_sample*100.0f;
~~~~~~~~~~~~ ^
../../ArduCopter/mode_systemid.cpp:279:33: warning: The left expression of the compound assignment is an uninitialized value. The computed value will also be garbage …
=> Copter: SystemID: Fix unutilized variables

libraries/GCS_MAVLink/GCS_Common.cpp
another one of our "do nasty thing to autopilot" commands, useful for testing what ground control stations do when the autopilot is in this state
=> GCS_MAVLink: add capability to send autopilot to config error loop

Tools/AP_Bootloader/board_types.txt
Reserving IDs for new Lumenier flight controllers. First new hardware will be LUX F765 NDAA.
=> AP_Bootloader: Reserving IDs for Lumenier

libraries/AP_AIS/AP_AIS.cpp
This bug meant we never re-assembled multi part messages correctly. Tested with the simulator.
=> AP_AIS: fix multi part message decoding

ArduPlane/Plane.h, ArduPlane/altitude.cpp, ArduPlane/takeoff.cpp
I found a bunch of things that were not used in `plane.h`. Takeoff had a `tkoff_option_is_set` helper, but it was not used anywhere, this changes to use it.
=> Plane: remove unused definitions 

ArduSub/Attitude.cpp, ArduSub/Parameters.cpp, ArduSub/Parameters.h, ArduSub/Sub.h, ArduSub/config.h, ArduSub/mode.h, ArduSub/mode_poshold.cpp, ArduSub/mode_surface.cpp, Tools/autotest/ardusub.py
This PR limits horizontal velocity in poshold mode, even when the pilot is using the forward and lateral sticks to reposition the sub. This eliminates the possibility of a PSC-caused bounceback. This is verified by an autotest.
The PR also adds a PILOT_SPEED parameter, so there are now 3 WPNAV_SPEED* parameters and 3 PILOT_SPEED* parameters. Previously, poshold was using WPNAV_SPEED for xy and PILOT_SPEED_UP/DN for z, this PR changes it to use PILOT_SPEED* for both xy and z.
(Circle mode also uses WPNAV_SPEED for xy and PILOT_SPEED_UP/DN for z, but I would argue that it should be using WPNAV_SPEED* for both xy and z. This can be a separate PR.)
There are 2 additional small fixes:
* removes unused variable `Sub::desired_climb_rate`
* `ModePoshold::requires_GPS` returns true, so …
=> Sub: limit poshold xy velocity to PILOT_SPEED to avoid bounceback

ArduSub/ArduSub.cpp, ArduSub/Sub.h
This PR implements LOG_BITMASK bit 18 (IMU_FAST) in Sub.
I tested this on SITL, and it works well (rate per IMU jumps from 25Hz to 400Hz).
=> Sub: support MASK_LOG_IMU_FAST (loop rate logging)

libraries/AP_Baro/AP_Baro_MS5611.cpp
While reviewing #29122 I found that the MS5837_30BA sensor's [current datasheet](https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Data+Sheet%7FMS5837-30BA%7FB1%7Fpdf%7FEnglish%7FENG_DS_MS5837-30BA_B1.pdf%7FCAT-BLPS0017#page=12) has some sections/factors for compensation that seemingly weren't there previously, so aren't yet being considered.
This PR adds in sections for both "high temperature" and "very low temperature" compensation regions, which were previously unhandled.
=> AP_Baro: update MS5837-30BA compensation

Tools/autotest/arduplane.py
the autopilot can instantly reset this back to 0 after we set it, so we never receive the set value:
```
2025-01-30T06:49:04.2029371Z AT-0931.7: COMPASS_LEARN want=3.000000 autopilot=0.0 (attempt=3/10)
2025-01-30T06:49:04.2029876Z AT-0931.7: Sending set (COMPASS_LEARN) to (3.000000) (old=0.000000)
2025-01-30T06:49:04.2030299Z AT-0931.7: AP: CompassLearn: Initialised
2025-01-30T06:49:04.2030653Z AT-0931.7: AP: CompassLearn: Finished
2025-01-30T06:49:04.2031166Z AT-0931.7: Received wanted PARAM_VALUE COMPASS_LEARN=0.000000
2025-01-30T06:49:04.2031653Z AT-0931.7: Received wanted PARAM_VALUE COMPASS_LEARN=3.000000
2025-01-30T06:49:04.2032117Z AT-0931.7: Received wanted PARAM_VALUE COMPASS_LEARN=0.000000
2025-01-30T06:49:04.2032732Z AT-0931.7: COMPASS_LEARN want=3.000000 autopilot=0.0 …
```
=> autotest: do not assert COMPASS_LEARN value after we set it

Tools/autotest/arduplane.py, Tools/autotest/vehicle_test_suite.py, libraries/APM_Control/AP_AutoTune.cpp, libraries/APM_Control/AP_AutoTune.h, libraries/APM_Control/AP_FW_Controller.cpp, libraries/APM_Control/AP_FW_Controller.h, libraries/APM_Control/AP_PitchController.cpp, libraries/APM_Control/AP_PitchController.h, libraries/APM_Control/AP_RollController.cpp, libraries/APM_Control/AP_RollController.h, libraries/APM_Control/examples/AP_FW_Controller_test/AP_FW_Controller_test.cpp, libraries/APM_Control/examples/AP_FW_Controller_test/TestMatrix.sh, libraries/APM_Control/examples/AP_FW_Controller_test/plot_results.py, libraries/APM_Control/examples/AP_FW_Controller_test/wscript, libraries/AP_HAL_SITL/HAL_SITL_Class.h
This moves to a shared base class between the plane roll and pitch controllers, there is lots of shared code which was duplicated. This helps with future tidyups as they now only need to happen in one place.
=> APM_Control: add AP_FW_Controller as common base class to roll and pitch controlers

libraries/AP_ESC_Telem/AP_ESC_Telem.cpp, libraries/AP_ESC_Telem/AP_ESC_Telem.h, libraries/AP_Vehicle/AP_Vehicle.cpp
Alternative approach to #28987.
We don't need to worry about explicitly checking the timestamp in most places; they can just use the `data_valid` flag directly. This eliminates the race without harming the performance of `get_rpm` at all (in fact, it improves it, even if just barely). The only places that need to actually check the timestamp are `update`, where the `data_valid` gets cleared on timeout, and `are_motors_running`, which has a stricter timeout than `data_valid` does. These two run much less frequently than `get_rpm`, so the extra copying shouldn't be a problem.
This might change the timing of when the data is considered stale by a few microseconds, since it's checking the timestamp at 100Hz instead of every time we get RPM, but that should be absolutely fine. The other change …
=> AP_ESC_Telem: fix RPM timeout race

ArduCopter/AP_Arming_Copter.cpp, ArduCopter/Copter.h, ArduCopter/Parameters.cpp, Tools/autotest/arducopter.py, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.h
... also rename it to `REQUIRE_LOCATION_FROM_ARMING` to be more in-line with ArduPilot's distinction between "position" (local position) and "location" (absolute lat/lng)
=> Move REQUIRE_POSITION_FOR_ARMING bit to AP_arming 

ArduPlane/Log.cpp
We have ATT.Pitch, CTUN.Pitch, XKF1.Pitch all reporting the same pitch with PITCH_TRIM added, so there are no two log lines that one can graph showing desired/nav pitch vs reported pitch to check if pitch tuning is closely matching to indicate good tune....
removing PITCH_TRIM_DEG bias from one would allow an easy graphical evaluation of Pitch tune....doing it in ATT is problematic since its in AHRS and spans vehicle types....modifying CTUN.Pitch is easy and only affects FW Plane...the other two pitch logs are unaffected.
This also aligns with HUD artificial horizon visual indication
=> Plane:adjust CTUN.Pitch to remove PITCH_TRIM

ArduPlane/quadplane.cpp
The second assignment, "otherwise cruise" is redundant, so remove it.
```
../../ArduPlane/quadplane.cpp:4260:15: warning: Value stored to 'approach_speed' during its initialization is never read [deadcode.DeadStores]
float approach_speed = cruise_speed;
^~~~~~~~~~~~~~   ~~~~~~~~~~~~
```
=> Plane: remove dead store of cruise_speed

Tools/ardupilotwaf/boards.py
we have two separate blocks, one for setting c flags, one for setting cxx flags.
Move cxx set into correct area
=> waf: move setting of -cl-single-precision-constant into cxx-flags block

libraries/AP_BattMonitor/AP_BattMonitor_INA3221.cpp, libraries/AP_BattMonitor/AP_BattMonitor_INA3221.h
@tpwrules there's no in-tree user of this still :-)
The simulation still finds the device:
=> AP_BattMonitor: remove use of ownptr

Rover/AP_Arming_Rover.cpp, Tools/autotest/arducopter.py, Tools/autotest/rover.py, Tools/autotest/vehicle_test_suite.py, libraries/AP_Arming/AP_Arming.cpp
Extracted from https://github.com/ArduPilot/ardupilot/pull/29066 as it's really a separate feature
Tested in SITL, including autotest
=> Rover: add require-position-for-arming option

.github/workflows/cygwin_build.yml, .github/workflows/qurt_build.yml, .github/workflows/test_replay.yml, .github/workflows/test_sitl_blimp.yml, .github/workflows/test_sitl_copter.yml, .github/workflows/test_sitl_periph.yml, .github/workflows/test_sitl_plane.yml, .github/workflows/test_sitl_rover.yml, .github/workflows/test_sitl_sub.yml, .github/workflows/test_sitl_tracker.yml, .github/workflows/test_unit_tests.yml
as we do ESP32 and ChibiOS when running SITL
@khancyr any idea why we aren't excluding the Linux HAL from these as well?
=> .github: exclude QURT changes when running various workflows

Tools/ardupilotwaf/boards.py
Gets rid of all of these:
```
../../libraries/AP_BattMonitor/AP_BattMonitor_SMBus.cpp:156:18: warning: variable length arrays in C++ are a Clang extension [-Wvla-cxx-extension]
156 |     uint8_t buff[read_size];    // buffer to hold results
|                  ^~~~~~~~~
```
.... which there are a lot of in ArduPilot!
=> waf: stop clang complaining about variable-length stack arrays

libraries/AP_ESC_Telem/AP_ESC_Telem.cpp, libraries/AP_ESC_Telem/AP_ESC_Telem_Backend.cpp, libraries/AP_ESC_Telem/AP_ESC_Telem_Backend.h
Prerequisite PR: #28999
The timeout for non-RPM telemetry is vulnerable to a similar race to the RPM one above. This PR makes the timeout logic consistent between the two, adding a validity flag to track the timeout instead of explicitly subtracting timestamps (one of which is volatile).
I broke this PR into a separate dependent PR in case this is considered too risky of a change. I have an alternative PR ready, mirroring how Pete is binding AP_Servo_Telem in the soon-to-be-merged #28857. That PR would be guaranteed not to change any behavior outside of Lua, however, I think this PR is vastly a better approach.
=> AP_ESC_Telem: fix other timeout race

Tools/autotest/rover.py, Tools/autotest/vehicle_test_suite.py, libraries/GCS_MAVLink/MissionItemProtocol.cpp, libraries/GCS_MAVLink/MissionItemProtocol.h, libraries/GCS_MAVLink/MissionItemProtocol_Fence.cpp, libraries/GCS_MAVLink/MissionItemProtocol_Fence.h, libraries/GCS_MAVLink/MissionItemProtocol_Rally.cpp, libraries/GCS_MAVLink/MissionItemProtocol_Rally.h, libraries/GCS_MAVLink/MissionItemProtocol_Waypoints.cpp, libraries/GCS_MAVLink/MissionItemProtocol_Waypoints.h
stop passing through _link and the original msg, move use to the base class instead.
starts fence and rally also using the "correct the GCS's count" code.
This also corrects the error code when correcting the GCS's count to INVALID_SEQUENCE rather than just ERROR
```
CubeOrange-periph-heavy  144               *
CubeRedPrimary                      24     *           24      24                24     24     24
Durandal                            64     *           64      64                64     64     64
KakuteH7-bdshot                     24     *           24      24                24     24     24
MatekF405                           24     * …
```
=> GCS_MAVLink: simplify MissionItemProtocol get_item interface

Tools/autotest/arducopter.py
if a vehicle magically sets a parameter (eg. via compass learn) then it can persist pat test end and reboots and everything,.
In this case it can randomly cause the next test to fail with a megneti field difference error
=> autotest: set parameter value so context pop resets it

Tools/scripts/uploader.py
- Implement functionality to verify correct firmware installation
- Utilize existing code with an additional argument for verification
=> Tools: uploader.py: verify correct install

libraries/SITL/examples/JSON/C++/minimal.cpp
Clarifying IMU reading value, as noted in #29072.
=> Added comment to clarify IMU acceleration value

libraries/AP_Scripting/applets/RockBlock.lua, libraries/AP_Scripting/applets/RockBlock.md, libraries/AP_Scripting/examples/MAVLinkHL.lua
Updating the RockBlock and MAVLinkHL scripts to take advantage of the new gcs:run_command_int command.
Also added the gcs:run_command_long lua binding
Trying to debug the merge commits this time....
=> Scripting: Update Rockblock and MAVLinkHL scripts

libraries/AP_Mount/AP_Mount_Viewpro.cpp, libraries/AP_Mount/AP_Mount_Viewpro.h
The command should also take negative values
=> AP_Mount: fix object tracking command for ViewPro

libraries/AP_Baro/AP_Baro_BMP581.cpp
Fixed a BMP581 driver initialization error, thanks to @peterbarker pointing out the problem.
https://github.com/ArduPilot/ardupilot/pull/27249#discussion_r1932916640
=> AP_Baro: Fix BMP581 initialization error

Tools/ardupilotwaf/boards.py
Thanks to @peterbarker for finding out that these were broken.
We need to explicitly set these defines to 0 for turning off the features. Just leaving them undefined no longer works.
=> Tools: explicitly set AP_PERIPH_XX_ENABLED defines to 0 for sitl_periph_gps and sitl_periph_battmon

libraries/AP_Scripting/docs/docs.lua
Spotted thanks to some testing and detective work by @olliw42 and twistedwings on discord. 
Que length is the first argument and number of IDs the second.
https://github.com/ArduPilot/ardupilot/blob/0e7e8ba5bf1c7f1e7d9e4782fe56fe50a6aadd19/libraries/AP_Scripting/lua_bindings.cpp#L59-L62
=> AP_Scripting: Docs: correct argument order on `mavlink:init`

libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua, libraries/AP_Scripting/applets/copter-slung-payload.lua, libraries/AP_Scripting/applets/follow-target-send.lua, libraries/AP_Scripting/applets/mount-poi.lua, libraries/AP_Scripting/examples/BQ40Z_bms_shutdown.lua, libraries/AP_Scripting/examples/MAVLink_Commands.lua, libraries/AP_Scripting/modules/mavport.lua, libraries/AP_Scripting/tests/mavlink_test.lua
RX message ID buffer sizes have been shrunk to the amount actually used.
Followup to #29246
=> AP_Scripting: update so mavlink init intent matches behavior

libraries/AP_Logger/AP_Logger.h
It hasn't kept the passed pointer for a while now.
=> AP_Logger: clarify behavior of log_file_content

libraries/GCS_MAVLink/GCS_Common.cpp
Follow up to https://github.com/mavlink/mavlink/pull/2208. The all item does not add any new information so it can be removed. Support for the message was added in https://github.com/ArduPilot/ardupilot/pull/27007
Our version of MAVLink is still not upto date enough for us to switch to the native enum.
=> GCS_MAVLink: highres imu: remove all "bitmask" value

ArduPlane/tiltrotor.cpp
This is one of my bugs, we log `TILT` for all Quadplane types whether or not tilt rotor is enabled. This bug is in 4.6 I have marked for backport, not critical of course, just wasting a little log space.
=> Plane: Quadplane: only log `TILT` on tilt-rotors

libraries/AP_Scripting/lua_bindings.cpp
If the second allocation failed, receiving a MAVLink message could deadlock as the script thread would never release the lock yet the main thread would see the partial initialization.
Also clean up while we are in there.
Tested on Cube Orange using the REPL that the functions still work.
=> AP_Scripting: mavlink: fix potential deadlock and clean up

ArduCopter/Parameters.cpp, ArduCopter/defines.h, ArduCopter/tuning.cpp, Tools/autotest/arducopter.py, libraries/AC_WPNav/AC_Loiter.cpp, libraries/AC_WPNav/AC_Loiter.h
This has been requested a few times in the past as well as in #9782.
This has been tested on SITL(incremented channel 6 by 100 every few seconds), and works well: 
Can't test it on actual copter due to lockdown.
Looking forward to any improvements that can be suggested! 
Fixes #9782
=> Copter: Allow CH6 tuning to change loiter speed

ArduPlane/Parameters.cpp, ArduPlane/Parameters.h, ArduPlane/servos.cpp
Updated the forward throttle battery voltage compensation feature to disable the throttle entirely when the sag-compensated voltage drops below the new parameter FWD_BAT_THR_CUT.
Key changes:
- Added new parameter FWD_BAT_THR_CUT to control the voltage threshold for this feature. The default value of 0 matches the original behavior of never cutting the throttle due to low voltage.
- Modified forward throttle battery voltage compensation logic in the servos code to cut off the throttle if the resting voltage estimate of the FWD_BAT_IDX battery is under FWD_BAT_THR_CUT.
=> Plane: Add fwd. throttle cutoff voltage parameter

libraries/AP_HAL_ESP32/I2CDevice.cpp, libraries/AP_HAL_ESP32/I2CDevice.h, libraries/AP_HAL_ESP32/SPIDevice.cpp
Lessons learned from the stampfly to make ESP32 more similar to ChibiOS. Please see commits for details. These have been tested on there for a while now.
=> AP_HAL_ESP32: fix up I2C and SPI port drivers

libraries/AR_Motors/AP_MotorsUGV.cpp
Fixes an issue where omni motors (BrushedWithRelay/BrushedBiplor) are not configured correctly.
I ran into the same problem another user mentioned [here](https://discuss.ardupilot.org/t/mot-pwm-type-3-brushedwithrelay-doesnt-work-with-frame-type-2-omnix/67182):  OmniX frame using MOT_PWM_TYPE = 3 (BrushedWithRelay) only outputs RC servo pulses instead of a duty cycle PWM.
Proposed fix worked great when tested with [Cytron MDD10A](https://www.cytron.io/p-10amp-5v-30v-dc-motor-driver-2-channels) motor driver.
=> AR_Motors: fix brushed motor support for omni vehicles

ArduPlane/commands_logic.cpp
This code is never used.....do_RTL is, but it changes mode to RTL directly and mission execution is interrupted so is never called by commands_logic....
=> ArduPlane: remove unused verify_RTL code

ArduCopter/mode_rtl.cpp, Tools/autotest/arducopter.py
I didn't know we had this feature, it allows the vehicle to return to the home location but hover at some given altitude above home.
When doing code review I spotted that the `descent_target` location is setup relative to home and then passed to the position controller which is relative to origin. This converts it to above origin and then updates the comparison function to use inertial nav altitude which is also relative to origin. 
I suspect this has been broken for ages, I wonder if anyone uses the feature? Although admittedly the difference between home and origin is typically small so it may not have been obvious. Maybe we could remove the functionality?
But I can understand why you might want this, maybe we should fix it and add a autotest?
=> Cotper: RTL correct height for `RTL_ALT_FINAL` > 0 (home vs origin)

ArduPlane/mode_autoland.cpp, libraries/AP_Airspeed/AP_Airspeed_AUAV.h, libraries/AP_HAL_SITL/HAL_SITL_Class.cpp, libraries/AP_HAL_SITL/RCInput.h, libraries/AP_RangeFinder/AP_RangeFinder_LightWareI2C.cpp, libraries/AP_RangeFinder/AP_RangeFinder_LightWareI2C.h, libraries/AP_Scripting/AP_Scripting.h, libraries/AP_Scripting/lua_bindings.cpp
Unused variables and wrong abs function used.
CI-tested only.  And locally for compilation...
.... also now stops scripting using OwnPtr for i2c devices; this was tested on a ZeroOneX6 with an RM3100 and an example script which triggers a self-test on the device.
=> Fix clang compiler warnings

libraries/AP_TECS/AP_TECS.cpp
=> TECS:correct metadata

libraries/AP_Airspeed/Airspeed_Calibration.cpp
This change disables automatic airspeed calibration when:
airspeed_use == 2 (UseWhenZeroThrottle), and
SRV_Channel::k_throttle != 0.
This prevents calibration issues caused by propeller airflow interfering with airspeed sensors, particularly in gliders.
=> AP_Airspeed: disable airspeed auto calibration in specific cases

libraries/Filter/SlewCalculator2D.cpp
This fixes a typo in the 2D Slew Calculator used by the AC_PID_2D class which is used in Copter, Rover and Blimp's XY velocity controller.  This means it's also used by QuadPlanes in QLoiter, etc but surely it has nothing to do with the recent questions around quad plane attitude control because the bug was in 4.5 as well.
This was added in PR https://github.com/ArduPilot/ardupilot/pull/23981 but it is only used for reporting so I think this does not cause any actual performance issue.  In fact, since this PR went in we've simplified the Rover autotune and we don't use this is anymore so we could potentially backout the slew reporting completely and save some flash and a very small amount of CPU
This resolves issue https://github.com/ArduPilot/ardupilot/issues/29272
I've done some minor …
=> Filter: SlewCalculator2D typo fix

.github/workflows/test_unit_tests.yml, Tools/autotest/autotest.py, Tools/autotest/examples.py
This gives us a bit more coverage, meaning more chance of detecting breakage in CI.
I've adjusted the suite to cope with examples-that-exit, something we didn't do before.  We don't usually "exit" as that's problematic on real hardware.  But here we are.
=> Re-enable examples in CI

Tools/autotest/arducopter.py, Tools/autotest/vehicle_test_suite.py
having a really slow RTL speed should not cause stopping-distance problems, but it does.  The vehicle goes off track as the PSC can't achieve the stopping distance demanded
This test has been added into the "currently fails" list of tests we expect to fail.
=> autotest: add test for Copter stopping distance calculation issue

libraries/AP_BLHeli/AP_BLHeli.cpp, libraries/AP_HAL_ChibiOS/RCOutput.cpp, libraries/AP_HAL_ChibiOS/RCOutput.h
Fixes some issues seen on AM32 passthrough. Tested on AM32 and BLHeli32
=> Fixes for AM32 Passthrough

libraries/GCS_MAVLink/GCS_Common.cpp
```
../../libraries/GCS_MAVLink/GCS_Common.cpp: In member function 'void GCS_MAVLINK::send_highres_imu()': ../../libraries/GCS_MAVLink/GCS_Common.cpp:2184:27: error: unused variable 'HIGHRES_IMU_UPDATED_XMAG' [-Werror=unused-variable]
2184 |     static const uint16_t HIGHRES_IMU_UPDATED_XMAG = 0x40;
|                           ^~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```
=> GCS_MAVLink: correct AP_Periph compilation when GCS enabled and mag not

libraries/AP_Filesystem/AP_Filesystem_ROMFS.cpp, libraries/AP_Filesystem/AP_Filesystem_ROMFS.h
Lua opens scripts to load them into memory, then the logger opens them after to stream them into the dataflash log. When loading multiple large Lua scripts from ROMFS, decompression takes a significant amount of time. This creates the opportunity for the Lua interpreter and logging threads to both be inside `AP_Filesystem_ROMFS::open()` decompressing a file.
If this happens, the function can return the same `fd` for two different calls as the `fd` is chosen before decompression starts, but only marked as being used after that finishes. The read pointers then stomp on each other, so Lua loads garbled scripts (usually resulting in a syntax error) and the logger dumps garbled data.
Fix the issue by locking before searching for a free record (or marking a record as free). Apply the same fix …
=> [backport 4.6] AP_Filesystem: ROMFS: fix open race conditions

libraries/AP_Scripting/lua_bindings.cpp
If the second allocation failed, receiving a MAVLink message could deadlock as the script thread would never release the lock yet the main thread would see the partial initialization.
Also clean up while we are in there.
Tested on Cube Orange using the REPL that the functions still work.
Backport of #29257
=> [backport 4.6] AP_Scripting: mavlink: fix potential deadlock and clean up

libraries/AP_Filesystem/AP_Filesystem_FlashMemory_LittleFS.cpp
lseek must return the current file position. Previously, the littlefs version always returned 0, which broke terrain I/O as it checks that the position returned is the one it seeked to. Fix to return the current position, which is correctly returned from littlefs.
This problem was originally and incorrectly diagnosed as an issue with littlefs seeking past the end of the file, but this functionality works fine and fixing the incorrect return completely fixes terrain.
Terrain functionality was verified using `TERRAIN_DEBUG` on KakuteH7Mini-Nand running sim on HW. Terrain data is correctly downloaded from the GCS and loaded from the filesystem after reboot.
=> AP_Filesystem: littlefs: fix lseek

libraries/AP_Mount/AP_Mount_CADDX.cpp
The CADDX mount driver is fairly new (see https://github.com/ArduPilot/ardupilot/pull/28942) and while it did go through alpha testing we apparently never tested RC rate control.  I think what must have happened is I must have tested rate control using QGC which means rate control was only done using the MAVLINK_TARGETING submode.
This change means that rate targets will always update the angle targets before being passed to the physical gimbal.
I've tested this lightly on real hardware and it works
This bug was found during testing of @peterbarker's backport PR https://github.com/ArduPilot/ardupilot/pull/29296,. thanks!
=> AP_Mount: CADDX RC rate control fix

AntennaTracker/GCS_MAVLink_Tracker.cpp, AntennaTracker/GCS_MAVLink_Tracker.h, ArduCopter/GCS_MAVLink_Copter.cpp, ArduCopter/GCS_MAVLink_Copter.h, ArduPlane/GCS_MAVLink_Plane.cpp, ArduPlane/GCS_MAVLink_Plane.h, ArduSub/GCS_MAVLink_Sub.cpp, ArduSub/GCS_MAVLink_Sub.h, Blimp/GCS_MAVLink_Blimp.cpp, Blimp/GCS_MAVLink_Blimp.h, Rover/GCS_MAVLink_Rover.cpp, Rover/GCS_MAVLink_Rover.h, Tools/AP_Periph/GCS_MAVLink.h, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_Dummy.h
Were putting values not in the `MAV_MODE` enum into it, better to use a uint8_t.
See: https://github.com/mavlink/mavlink/pull/2195
=> GCS_MAVLink: move from `MAV_MODE` enum to `uint8_t`

Tools/scripts/build_autotest.sh, Tools/vagrant/initvagrant-autotest-server.sh, Vagrantfile
```
build_autotest.sh: allow use of more modern timelimit command
command-line has changed (if indeed this is the same command!)
Regardless, autotest server has some grandfathered binary in place in $HOME/bin/timelimit and we do want to move past it at some stage
```
Also adds a Vagrant virtual machine definition which was used to test the changes.
=> Tools: build_autotest.sh Allow use of alternative timelimit program in build_autotest.sh

ArduPlane/Attitude.cpp, ArduPlane/Plane.h, libraries/AP_TECS/AP_TECS.cpp
This is a rebase of https://github.com/ArduPilot/ardupilot/pull/24509, see also https://github.com/ArduPilot/ardupilot/issues/24320 and https://github.com/ArduPilot/ardupilot/pull/29092
Were were passing about the sqrt of the laod factor. This changes to the standard definition.
There is no change in behavior.
=> Plane: Fixed formulas for load factor and roll, also corrected _TASmin in AP_TECS accordingly

Tools/scripts/build_autotest.sh
uses pushd rather than multiple cd calls
indents for clarity
removes unused oldhash assignment
create and make use of intermediate variables
=> Tools: tidy build_autotest.sh script

libraries/AP_RangeFinder/AP_RangeFinder.cpp, libraries/AP_RangeFinder/AP_RangeFinder_MaxsonarI2CXL.cpp, libraries/AP_RangeFinder/AP_RangeFinder_MaxsonarI2CXL.h, libraries/SITL/SIM_Aircraft.cpp, libraries/SITL/SIM_MaxSonarI2CXL.h
```
CubeOrange-periph-heavy  *                 *                               
CubeRedPrimary                      0      *           -88     -88               -88    -88    -88
Durandal                            *      *           -72     -72               -72    -72    -64
Hitec-Airspeed           *                 *                               
KakuteH7-bdshot                     *      *           -88     -88               -88    -88    -88
MatekF405                           *      *           -88     -88               -88    -88    -88
Pixhawk1-1M-bdshot                  *                  -88     -88               -88    -88    -88
f103-QiotekPeriph        *                 * …
```
=> Avoid use of OwnPtr in MaxsonarI2CXL driver

libraries/AP_Filesystem/AP_Filesystem_FATFS.cpp
In Standard C, the first three file descriptors are usually standard in, out, and error. However, ArduPilot doesn't have a concept of this and other backends (such as LittleFS) don't bother to reject them.
Remove this logic to simplify implementation and allow use of more open files.
Tested on Cube Orange that scripting off SD card and logging still work.
=> AP_Filesystem: FATFS: drop tty check logic

libraries/RC_Channel/RC_Channel.cpp
Theses options were added in https://github.com/ArduPilot/ardupilot/pull/13776.
=> RC_Channel: Document EKF lane switch and yaw reset aux functions.

ArduCopter/AP_Arming_Copter.cpp
Inspired by @muramura 's patches here: https://github.com/ArduPilot/ardupilot/pull/28265/files
```
CubeRedPrimary                 *      *           -56     -56               *      *      *
Durandal                       *      *           -88     -88               *      *      *
KakuteH7-bdshot                *      *           -56     -56               *      *      *
MatekF405                      *      *           -56     -56               *      *      *
Pixhawk1-1M-bdshot             *                  -48     -48               *      *      * …
```
=> Copter: save a few bytes in variance check

libraries/AP_Scripting/README.md, libraries/AP_Scripting/lua/Makefile, libraries/AP_Scripting/lua/README, libraries/AP_Scripting/lua/doc/contents.html, libraries/AP_Scripting/lua/doc/manual.html, libraries/AP_Scripting/lua/doc/readme.html, libraries/AP_Scripting/lua/src/Makefile, libraries/AP_Scripting/lua/src/lapi.c, libraries/AP_Scripting/lua/src/lauxlib.c, libraries/AP_Scripting/lua/src/lcode.c, libraries/AP_Scripting/lua/src/ldebug.c, libraries/AP_Scripting/lua/src/liolib.c, libraries/AP_Scripting/lua/src/llex.c, libraries/AP_Scripting/lua/src/lobject.c, libraries/AP_Scripting/lua/src/lparser.c, libraries/AP_Scripting/lua/src/lua.h, libraries/AP_Scripting/lua/src/lundump.c
In particular this fixes some exceedingly rare/impossible use-after-frees. The serious ones aren't actually accessible in our scripting engine.
To maintain our alterations, I applied source patches generated from the source repository manually instead of simply overwriting the code. Please see the commit message for full details.
Tested by flying scripting aerobatics on SITL on HW on Cube Orange.
The size overhead is negligible:
```
CubeOrange-periph-heavy  8                 *                                                   
Durandal                            8      *           8       8                 8      8      8 …
```
=> AP_Scripting: patch vendored Lua to 5.3.6

libraries/AP_BoardConfig/AP_BoardConfig.cpp
This already works for channels above 14 the param is a int32, just never been added to the docs.
=> AP_BoardConfig: `SAFETY_MASK` include full  32 channels in docs

libraries/AP_Airspeed/AP_Airspeed.cpp, libraries/AP_Airspeed/AP_Airspeed.h
this doesn't gain us anything; it's a private function which is only called in one place and replicates checks that the caller already makes (it devolves into a one-liner, essentially!)
This method is also confusing as it sits next to "get_temperature" in the code, which is actually a match for get_differential_pressure, not get_pressure
```
CubeRedPrimary                      *      *           -40     -40               -40    -40    -40
Durandal                            *      *           -80     -80               -72    -80    -72
Hitec-Airspeed           -32               * …
```
=> AP_Airspeed: inline get_pressure

libraries/AP_Camera/AP_Camera_Servo.cpp, libraries/AP_Camera/AP_Camera_Servo.h, libraries/SRV_Channel/SRV_Channel.h, libraries/SRV_Channel/SRV_Channel_aux.cpp
We want to control our camera's focus and pwm through ardupilot.
=> AP_Camera_servo: allow focus and zoom control

libraries/AP_GPS/AP_GPS_UBLOX.cpp, libraries/AP_GPS/AP_GPS_UBLOX.h
we should stop looking for SOL as soon as we know we have PVT, instead of waiting for all others to be cleared
may help with
https://discuss.ardupilot.org/t/fc-tries-to-config-gps-constantly-when-trying-to-arm-in-loiter-mode/129930
=> AP_GPS: fixed the check for disabling CONFIG_RATE_SOL config

libraries/AP_Filesystem/AP_Filesystem_FATFS.cpp
Saves 100-200 bytes and makes the code a bit more straightforward.
Tested on CubeOrange that scripting and logging still work, that I can remove the SD card and get reasonable errors, and that I can put it back in and the use it without rebooting.
=> AP_Filesystem: FATFS: clean up allocations and error handling

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.h, libraries/AP_Scripting/AP_Scripting.cpp
Allows a scripting restart to reset any auxiliary prearms, and clear out all the old previous aux id allocations.
This is very helpful during development of lua scripts that have prearm checks in them, as without this you can only restart a maximum of three times before you run out of aux auth ids ("PreArm: Too many auxiliary authorisers") and have to reboot. Additionally, if a prearm check was failing before the scripting restart, there was no way to clear it without rebooting.
=> AP_Scripting: reset aux auths on start

ArduCopter/RC_Channel_Copter.cpp, ArduCopter/mode.h, Tools/autotest/arducopter.py, libraries/RC_Channel/RC_Channel.h
This:
1. Fixes  bugs in #28881 (aux func was not init'd and auto trim not saved properly)
2. refactors to use an "allows_auto_trim" bool to avoid entering autotrim and then immediately cancelling; and neaten the code a bit
3. Adds Loiter/PosHold to autotrim for hands off trimming
4. Add a warning on attempting to enable autotrim when allowed, but not flying, rather than just entering and exiting immediately leaving a user to wonder why.
5. adjust marginally failing autotest
6. driveby that PeterB requested to fix comment on aux function for autotrim
Flight tested by myself and Peter Barker
=> Copter: allow auto trim in position hold modes

libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp
I wonder if these made there way in there when the pos code was replicated for  the height code?
=> AP_NavEKF3: remove unused assignments of posCheckPassed 

libraries/AP_GPS/AP_GPS_UBLOX.cpp
pointer persists in the object and is re-used, but never freed.
Not really a problem if you're only detecting once, could be a problem if you've got intermittent connectivity to your GPS...
=> AP_GPS: UBLOX: fix memory leak when "F9" GNSS configuration is used

libraries/AP_HAL/utility/Socket.cpp
avoids static analysis failure upon this method failing
=> AP_HAL: Socket: check return value of getsockname

libraries/AP_Proximity/AP_Proximity_LD06.cpp
AP_Rangefinder: LD19/LD06 data length sanity check fix
root cause: number of data points in frame stored only on 5bits. value been used without proper bitmask
to sanity check number of datapoints in frame
=> AP_Proximity: LD19/LD06 data length sanity check fix

libraries/AP_Scripting/applets/RockBlock.lua, libraries/AP_Scripting/applets/RockBlock.md, libraries/AP_Scripting/examples/MAVLinkHL.lua
Another Rockblock scripting update. Makes the mavlink parsing more robust and adds a configurable timeout for automatically going to High Latency mode on GCS loss.
=> AP_Scripting: Better mavlink parsing for MAVLinkHL and Rockblock

Tools/scripts/decode_devid.py, libraries/AP_Baro/AP_Baro_Backend.h, libraries/AP_Baro/AP_Baro_SPL06.cpp, libraries/AP_Math/AP_Math.cpp, libraries/AP_Math/AP_Math.h
Pulls in some bug fixes from betaflight to make the code more understandable.
Enabled background updates by default (which is what the DPS310 driver does)
Uses external temperature sensor as required by the spec.
This results in much more accurate baro updates from this sensor.
Tested on BetaFPV F405
=> Rework SPL06 to do background updates compliant with the spec

ArduPlane/Log.cpp
This adds logging of whether the throttle is suppressed or not into the `STAT` message.
I've created a new field, "Bit" to hold a bitmask of boolean information about the vehicle - saves 40 bytes per message past me adding the new field.
I suggest we remove the old equivalent uint8_t fields in 4.8 - just have them in here for a bit of cross-over.
The new LogStatus class is perhaps overkill - but I think we might be able to templatise it and have a nice, compact way of doing similar bitmasks in log messages.
For this entire PR:
```
CubeRedPrimary                      *      *           *       * …
```
=> Plane: log whether throttle is suppressed or not 

libraries/AP_AccelCal/AP_AccelCal.cpp
At the end of void `AP_AccelCal::update_status()` there is a `return;` that shouldn't be there.
=> AP_AccelCal:Remove an unusable return

libraries/AC_Avoidance/AC_Avoidance_Logging.cpp
=> AC_Avoidance: add missing AP_AHR.h include

Tools/Replay/Replay.cpp, Tools/Replay/Replay.h
when the original log used a firmware without EKF2 compiled in then the format messages are missing
this helps with diagnosis of #29384
=> Replay: fixed --force-ekf2 in Replay

libraries/AP_Math/matrix_alg.cpp
A comparison is made whether `T` is defined as float or double, but the logic here seems to be redundant, there being no need to use `std::is_same`.
=> matrix_alg: Probable redundancy

libraries/AP_Filesystem/AP_Filesystem_FlashMemory_LittleFS.cpp, libraries/AP_Filesystem/AP_Filesystem_FlashMemory_LittleFS.h
Removes some impossible cases and better documents it.
Tested on KakuteH7Mini-Nand that there are no performance regressions or misaligned fsyncs.
=> AP_Filesystem: LittleFS: clarify fsync bytes logic

ArduPlane/tiltrotor.cpp
This fixes a by reported by @jcproulx in https://github.com/ArduPilot/ardupilot/issues/29404.
It was always checking the first motor rather than any motor. The `_have_vtol_motor` bool is used in the `has_vtol_motor` function which is only used here: 
https://github.com/ArduPilot/ardupilot/blob/076951f003703f178523cd2e122fd54fffcaefff/ArduPlane/quadplane.cpp#L1591-L1594
The goal of that code is to smooth the handover of throttle control from VTOL to FW in the transition timer phase on vehicles that had all motors tilting.
=> Plane: Tiltrotor: fix `has_vtol_motor` function

libraries/AP_Generator/AP_Generator_IE_FuelCell.cpp
At some point between when the comment was added on the function and now the generator scheduler rate was dropped to 10Hz. 30 bytes read per call at 10Hz means a max of 300 bytes per second rather than the 600 bytes per second it would have been originally. 
This bumps it up to 255 bytes for a max of 2550 bytes per second. These typically ruin on a serial port at 9600 baud so a max of 960 bytes per second. We could go lower, 50 or 100 bytes per call would be fine for the existing units, but this was a PITA to debug so some headroom is nice.
=> AP_Generator: FuelCell: increase max data rate

ArduPlane/mode.h, ArduPlane/mode_autoland.cpp
This changes autoland's climb first to be a min altitude above ground rather than the current location. The `relative_ground_altitude` function is used. So rangefinder will be used if enabled, otherwise terrain if enabled, otherwise home. 
This is a change in behavior, but the min climb thing has not been in for long.
I couldn't think of a better name for the param so it is unchanged, open to suggestions.
=> Plane: autoland: climb above ground not current location

libraries/AP_GPS/AP_GPS_SBF.cpp
Many thanks to 3DR for supplying the hardware used to debug this!
messages coming in with a size of 24320 bytes.  It takes so long to try to read those bytes in (at the device's message rate) that we time out the GCS and try detecting again
messages coming in with a size of 24320 bytes.  It takes so long to try to read those bytes in (at the device's message rate) that we time out the GCS and try detecting again
@chiara-septentrio this is a MosaicX5 module connected to an ArduPilot periph node.  We're reliably seeing bad bytes in the length field; this fix is necessary in case of true corruption, but it's a bit worrying how reliable this problem is!
=> AP_GPS: discard SBF packets with claimed length > 256 bytes

libraries/AP_HAL_ChibiOS/AnalogIn.cpp
This fixes the regression in the max and min MCU voltage in the logs, as described in this issue: https://github.com/ArduPilot/ardupilot/issues/29147
Tested on CubeOrangePlus and MatekH743 with copter firmware.
Master:
This PR:
Note, however that this does reset it at 20 Hz, whereas MCU only gets logged at 10 Hz (on copter, at any rate).
AFAICT this was the previous behaviour as well though.
=> AP_HAL_ChibiOS: Fix regression in MCU max and min volt logging

ArduPlane/fence.cpp
There is no need for the guided and RTL cases to share,  they are independent. This simplifies https://github.com/ArduPilot/ardupilot/pull/29280
=> Plane: fence: refactor action cases

libraries/AP_OpticalFlow/AP_OpticalFlow_MSP.h
=> AP_OpticalFlow: correct includes for AP_OpticalFlow_MSP

libraries/AP_DDS/AP_DDS_Client.cpp, libraries/AP_DDS/AP_DDS_Client.h
Allow all GPS instances to be published on the `/ap/navsat` topic. All instances are published, each with their `instance` represented in the `header.frame_id` field.
This approach follows what has been already implemented for the `/ap/battery` topic.
Simulation parameters need to be updated in order to enable a second GPS instance to be found.
- `GPS2_TYPE` = 1
- `SIM_GPS2_ENABLE` = 1
- Restart the simulator and micro-ros.
- On another terminal, publish the topic with: `ros2 topic echo /ap/navsat`
```
---
header:
stamp:
sec: 1741022473
nanosec: 424456000
frame_id: '0'
status:
status: 2
service: 1
latitude: -35.36326217651367
longitude: 149.1652374267578
altitude: 584.0899658203125
position_covariance:
- 0.09000000357627869
- 0.0
- 0.0
- 0.0
- 0.09000000357627869
- 0.0
- 0.0
- 0.0
- …
```
=> AP_DDS: Publish all available GPS instances

Tools/AP_Periph/AP_Periph.h
The commit name has changed now. I missed to update it here while submitting the PR that renamed it.
=> Tools: update error message to use new AP_PERIPH_RELAY_ENABLED define

Tools/scripts/build_options.py, libraries/RC_Channel/RC_Channel.cpp
This renames the RCx_OPTION parameter description for value 182 from "In flight AHRS trim adjust" to "AHRS AutoTrim".  Either name is fine of course but this makes it consistent with [what we call it on the wiki](https://ardupilot.org/copter/docs/autotrim.html).  We don't need two names for the same feature
As suggested by @IamPete1 below I've also updated the build option description to match
=> RC_Channel: rename rc option to AutoTrim

libraries/AP_Mount/AP_Mount_CADDX.cpp
This fixes an issue with the CADDX driver that causes the gimbal to move at only 1hz towards its target when the user is controlling the gimbal via RC input.
This has been lightly tested on real hardware
Thanks very much to @boa-pe for finding and reporting this issue!
=> AP_Mount: fix CADDX RC update rate

libraries/AP_Notify/IS31FL3195.cpp, libraries/AP_Notify/IS31FL3195.h
=> AP_Notify: stop using OwnPtr in IS31FL3195

libraries/AP_Mission/AP_Mission.h
This is the alternative to https://github.com/ArduPilot/ardupilot/pull/29435
This has been lightly tested in SITL using the two options that Copter supports:
1. Clear On Boot ---> the mission was correctly cleared after SITL was restarted
2. Continue After Land ---> with this set (and only when this was set) the vehicle was able to fly, land and takeoff again in a single mission
=> AP_Mission: fix option_is_set

libraries/AP_OpticalFlow/AP_OpticalFlow_Pixart_SROM.h, libraries/AP_RangeFinder/AP_RangeFinder.cpp
pixart data and rangefinder init routines can probably go into external flash.
=> Mark more methods as __INITFUNC__

ArduPlane/Plane.cpp
this prevents learning of ARSPD_RATIO when not in fly-forward or not armed
the scenario that happened on a real aircraft was gps glitches in a hanger combined with airspeed offset causing the learning of an ARSPD_RATIO of 4.0, resulting in a stall in an AUTO mission and a crash
=> Plane: prevent learning bad ARSPD_RATIO

Tools/AP_Bootloader/support.cpp, libraries/AP_HAL/AP_HAL_Boards.h, libraries/AP_HAL_ChibiOS/UARTDriver.cpp, libraries/AP_HAL_ChibiOS/UARTDriver.h
This is no longer used with the advent of PPP from CubeRedPrimary to CubeRedSecondary. There is a similar version still in the bootloader which is still useful.
Not using it in the future is beneficial so that OTG2 (SERIAL6) can be used for other purposes. The feature can also be replaced using the serial passthrough options.
=> AP_HAL_ChibiOS: drop HAL_FORWARD_OTG2_SERIAL

Tools/AP_Periph/rc_in.cpp
```
../../Tools/AP_Periph/rc_in.cpp: In member function 'void AP_Periph_FW::rcin_update()':
../../Tools/AP_Periph/rc_in.cpp:117:31: error: 'class AP_RCProtocol' has no member named 'protocol_name'; did you mean 'protocol_enabled'?
117 |     auto new_rc_protocol = rc.protocol_name();
|                               ^~~~~~~~~~~~~
|                               protocol_enabled
```
=> AP_Peript: correct function name for detected protocol name

libraries/AC_Fence/AC_PolyFence_loader.cpp
By setting the initial value to 0, the number of source steps can be reduced.
=> AC_Fence: Remove redundant steps

libraries/AP_InertialSensor/AP_InertialSensor.h
The definitions `AP_INERTIAL_SENSOR_ACCEL_TOT_MAX_OFFSET_CHANGE` and `AP_INERTIAL_SENSOR_ACCEL_MAX_OFFSET` apparently it is no longer used in the library.
=> AP_InertialSensor: Remove two unused defines

libraries/SITL/examples/JSON/readme.md
The previous read me suggested using "-f json" to include the interface in SITL. This was difficult to work with as it replaced the vehicle's frame definition argument and prevented users from accessing the default parameters. By using "--model json" instead, the "-f" argument is left free for the vehicle's frame definition.
=> Swap -f for --model in JSON read me instructions

libraries/AP_Motors/AP_MotorsMulticopter.cpp
This updates the MOT_THST_HOVER parameter descriptions to match the actual limits enforced in the code ([see here](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Motors/AP_MotorsMulticopter.h#L12))
This inconsistency came up in [this discussion during 4.6 beta testing](https://discuss.ardupilot.org/t/copter-4-6-0-beta4-released-for-beta-testing/130471/54)
This change has been tested by running, "./Tools/autotest/autotest.py build.Copter test.Copter.Parameters" and reviewing the output of the "buildlogs/apm.pdef.xml" file before and after.
**BEFORE**
```
<param humanName="Thrust Hover Value" name="MOT_THST_HOVER" documentation="Motor thrust needed to hover expressed as a number from 0 to 1" user="Advanced">
<field name="Range">0.2 0.8</field>
</param>
```
**AFTER**
``` …
```
=> AP_Motors: MOT_THST_HOVER param desc min/max fixed

libraries/AP_Baro/AP_Baro_BMP280.cpp
Modify the description to clarify that no errors occur during data reading from the device.
=> AP_Baro: Determine the result of the device data reading process

libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus/README.md
Tested on Orange Cube Plus today, confirming that DShot works as expected when BRD_IO_DSHOT is set to 1 which is DShot fw
=> [README] Clarify DShot support on MAIN outputs for OrangeCubePlus

ArduPlane/fence.cpp, libraries/AC_Fence/AC_Fence.cpp, libraries/AC_Fence/AC_Fence.h
=> Add Autoland fence action

Tools/scripts/size_compare_branches.py, libraries/AP_HAL/AP_HAL_Boards.h, libraries/AP_HAL/board/esp32.h, libraries/AP_HAL_ESP32/boards/esp32s3m5stampfly.h, libraries/AP_HAL_ESP32/hwdef/esp32s3m5stampfly/defaults.parm
This is a ready-to-flash board definition for the ready-to-fly 55mm M5Stack M5Stamp Fly quadcopter. Hopefully it can serve as an inexpensive reference design for the often-beleaguered ESP32 support. It flies great using the stock parameters and a joystick over MAVLink over WiFi.
The CPU and flash are still slow and I had to limit it to <1/3 of a stock copter's loop rate but for amateur pilots that is not noticeable. Current sensor suite is suitable for non-position-controlled modes (e.g. Stabilize and AltHold). Battery monitoring is also set up and works. Flight time is 4-5 minutes.
Work remains to get the compass driver working so that automated flight is possible with an inexpensive GPS. Then hopefully some day the LEDs, buzzer, optical flow sensor, and chip LiDARs can be made to work …
=> AP_HAL_ESP32: init esp32s3m5stampfly

libraries/AP_HAL/SPIDevice.h, libraries/AP_HAL_ChibiOS/Device.cpp, libraries/AP_HAL_ChibiOS/I2CDevice.h, libraries/AP_HAL_ChibiOS/SPIDevice.cpp, libraries/AP_HAL_ChibiOS/SPIDevice.h, libraries/AP_HAL_ChibiOS/sdcard.cpp, libraries/AP_HAL_ESP32/DeviceBus.cpp, libraries/AP_HAL_ESP32/I2CDevice.h, libraries/AP_HAL_ESP32/SPIDevice.cpp, libraries/AP_HAL_ESP32/SPIDevice.h, libraries/AP_HAL_Empty/I2CDevice.h, libraries/AP_HAL_Empty/SPIDevice.h, libraries/AP_HAL_Linux/I2CDevice.h, libraries/AP_HAL_Linux/SPIDevice.cpp, libraries/AP_HAL_Linux/SPIDevice.h, libraries/AP_HAL_QURT/DeviceBus.cpp, libraries/AP_HAL_QURT/I2CDevice.h, libraries/AP_HAL_QURT/SPIDevice.cpp, libraries/AP_HAL_QURT/SPIDevice.h, libraries/AP_HAL_SITL/I2CDevice.h, libraries/AP_HAL_SITL/SPIDevice.cpp, libraries/AP_HAL_SITL/SPIDevice.h
Similar to what we did the I2CDevice, allow callers to get a pointer not wrapped in OwnPtr.
Tested using QiotekZealotF427 which uses an SPI-connected SD card.  Everything works fine, including ejecting and reinserting.
=> Add get_device_ptr to AP_HAL::SPIDevice

libraries/AP_GPS/AP_GPS_SBP.cpp, libraries/AP_GPS/AP_GPS_SBP.h, libraries/AP_GPS/AP_GPS_SBP2.cpp, libraries/AP_GPS/AP_GPS_SBP2.h, libraries/AP_GPS/LogStructure_SBP.h
takes up flash for everyone
packet definitions are invalid
newer features in ArduPilot which work for all GPS (including replay capability) are better
(this is the Swift Block Packet, not the Septentrio Block Format)
=> AP_GPS: remove SBP raw logging

libraries/AP_HAL/LogStructure.h, libraries/AP_HAL/UARTDriver.cpp, libraries/AP_HAL/UARTDriver.h, libraries/AP_HAL_ChibiOS/UARTDriver.cpp, libraries/AP_HAL_ChibiOS/UARTDriver.h
This adds tracking and logging of dropped incoming data. This is data that we received but could not fit in the receive buffer. This would make tracking down issues such as this one much easier. https://github.com/ArduPilot/ardupilot/pull/29414
We currently log the incoming data rate, but that may not all fit in the read buffer. In that case we will start to see some dropped packets. 
We could do the same with TX bytes, but its not so clear cut, the write call returns the length written, so the individual driver may not loose data, it can retry later. 
UART logging is only 1Hz, so this adds another float, we could add a uint8 flags and just set a bit if any data is lost since the last call.
Currently this is only ChibiOS. SITL is harder because it would need to be worked out for each …
=> HAL: Add logging of dropped incoming serial data 

libraries/AP_RAMTRON/AP_RAMTRON.cpp, libraries/AP_RAMTRON/AP_RAMTRON.h
```
Board,plane
CubeOrange,-144
```
... parameters are still persisted on CubeOrange
=> AP_RAMTRON: stop using OwnPtr

libraries/AP_DroneCAN/AP_DroneCAN_serial.cpp, libraries/AP_DroneCAN/AP_DroneCAN_serial.h, libraries/AP_Networking/AP_Networking.h, libraries/AP_Networking/AP_Networking_port.cpp, libraries/AP_SerialManager/AP_SerialManager.cpp, libraries/AP_SerialManager/AP_SerialManager.h, libraries/AP_Vehicle/AP_Vehicle.cpp
Builds on https://github.com/ArduPilot/ardupilot/pull/29473 to allow logging of the data rates of virtual serial ports. https://github.com/ArduPilot/WebTools/pull/238 Adds support to the HardwareReport WebTool. That results in plots like this:
=> DroneCAN, Networking: Log virtual UART data rates.

ArduPlane/Attitude.cpp, ArduPlane/Parameters.cpp
Description
-----------
Applied the new AIRSPEED_STALL parameter to roll stall prevention, to enable tighter turns at lower airspeeds when this parameter is set. For accurate behavior, it should be set at the stall IAS on level flight at sea level, plus the desired safety margin.
=> Plane: Attitude stall prevention adjustments

libraries/AP_NavEKF3/AP_NavEKF3.cpp, libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.h
if using GPS and our horizontal velocity innovation is high then mark the filter as unhealthy, which causes an arming failure
this helps with #29384
=> AP_NavEKF3: added in a check for high velocity innovation

libraries/AP_HAL_ChibiOS/hwdef/StellarH7V2/hwdef.dat
We need to change the default IMU rotation due to minor differences between the production version and the development sample.
=> HWDEF: Fix IMU rotation for Stellar H7V2

Tools/scripts/size_compare_branches.py
was the Pythoification of the class object, now back to what we used to print when it was a tuple
=> Tools: correct task stringification

ArduPlane/mode_qautotune.cpp, ArduPlane/mode_qhover.cpp, ArduPlane/mode_qloiter.cpp, ArduPlane/mode_qrtl.cpp, ArduPlane/mode_qstabilize.cpp
Currently rudder is not output at all in VTOL modes. This means it is stuck at whatever the output was when the mode was entered. For example full rudder due to stick mixing in guided then switch to QRTL, rudder output remains even after pilot stick is centered.
This results in the vehicle crabbing all the way home.
With this PR the rudder it output as normal in QRTL. This includes the VTOL phases which is inline with what a nav land would do in AUTO.
For the other VTOL modes the rudder is now held centered. Using coordinated turn value seems a bit nonsense when we could be moving backwards or sideways.
=> Plane: Output rudder in VTOL modes

Tools/autotest/test_build_options.py, Tools/scripts/build_options.py, Tools/scripts/extract_features.py
Don't see the point that only one board has this, and any user would need to build locally a new board def and firmware to use it...if its worth having in the code, we should let users access it
=> Tools:add build option for baro thrust correction

Tools/autotest/arducopter.py, Tools/autotest/arduplane.py, Tools/autotest/ardusub.py, Tools/autotest/helicopter.py, Tools/autotest/quadplane.py, Tools/autotest/rover.py, Tools/autotest/sailboat.py, Tools/autotest/vehicle_test_suite.py
we prefer assert_receive_message as it's less verbose than using recv_match all the time, and more consistent in that if you don't receive a message you will get a good error message, as opposed to a lot of places in here which would give you an attribute-on-None exception in case a timeout occurs.  Also means that you *always* get a timeout so won't hang the test in case the message doesn'tcome
=> autotest: change uses of recv_match to assert_receive_message

libraries/AC_Fence/AC_PolyFence_loader.cpp, libraries/AC_Fence/AC_PolyFence_loader.h
... and a plan to get rid of this compatability code
This is why we have these two types (copied from the code):
```
// CIRCLE_INCLUSION_INT stores the radius an a 32-bit integer in
// metres.  This was a bug, and CIRCLE_INCLUSION was created to store
// as a 32-bit float instead.  We save as _INT in the case that the
// radius looks like an integer as a backwards-compatibility measure.
// For 4.2 we might consider only loading _INT and always saving as
// float, and in 4.3 considering _INT invalid
```
I don't think this is a good candidate for build_options.py - we should just auto-fix the thing in storage for a couple of versions.
=> AC_Fence: do not store radius as integers if they look like integers

libraries/AP_HAL_ChibiOS/RCOutput.cpp, libraries/AP_HAL_ChibiOS/RCOutput.h
ensure that period[] array is not updated until we push
this fixes the stuttering motors on tilt quadplanes, and may fix other issues
this is an alternative to #29518
=> HAL_ChibiOS: fixed cork/push

ArduPlane/GCS_MAVLink_Plane.cpp, ArduPlane/Plane.cpp, ArduPlane/mode_guided.cpp, Tools/autotest/arduplane.py, Tools/autotest/quadplane.py
if the GCS commands a guided re-position with an AGL frame and quadplane is in Q_GUIDED_MODE=1 then this prevents us adding the home altitude to the target terrain altitude
we really need auto tests for these
=> Plane: fixed guided VTOL command in terrain mode

ArduPlane/Plane.h, ArduPlane/commands_logic.cpp, ArduPlane/defines.h, ArduPlane/mode_cruise.cpp, ArduPlane/mode_takeoff.cpp
we use GPS_GND_CRS_MIN_SPD  in AUTOLAND, this makes ModeTakeoff and NAV_TAKEOFF consistent with this
=> ArduPlane:make heading lock upon gnd speed consistent

Tools/scripts/battery_fit.py, libraries/AP_Scripting/applets/BattEstimate.lua, libraries/AP_Scripting/applets/BattEstimate.md
Made the SoC model used by the BattEstimate script more flexible by turning the previously fixed parameter p0 into a free coefficient C4. This parameter controls the steepness of the SoC curve transition, so this change allows the model to also fit other battery technologies such as Li-ion.
The battery_fit.py script has also been fixed to support logs that use 'Inst' instead of 'Instance' for battery messages.
=> AP_Scripting: Generalize BattEstimate SoC model for more battery chemistries

libraries/AP_Airspeed/AP_Airspeed.cpp, libraries/AP_Airspeed/AP_Airspeed.h, libraries/AP_Airspeed/AP_Airspeed_Backend.h, libraries/AP_Airspeed/AP_Airspeed_Params.cpp, libraries/AP_Airspeed/AP_Airspeed_SDP3X.cpp, libraries/AP_Arming/AP_Arming.cpp, libraries/GCS_MAVLink/GCS_Common.cpp
Some re-structuring `set_use_zero_offset` now sets the calibration state rather than using a separate bool. If set it will also force return 0.0 in the `get_offset` function. 
Setting skip-cal no longer allows a 0 offset to be healthy. The only way for 0 to be allowed is if the calibration state is the new `NOT_REQUIRED_ZERO_OFFSET`.
Arming checks are moved down to AP_Airspeed and made more verbose.
A new option is added to the skip cal parameter to skip the startup calibration but still require a manual calibration. This can be useful in some operations, especially if heated pitots need some time to warm up. The new arming checks mean you will not be allowed to arm in this case until a manual calibration has been done.
=> AP_Airspeed: allow skipping startup cal but requiring manual cal, improve arming checks.

ArduPlane/GCS_MAVLink_Plane.cpp
Updated the landed_state method in the MAVLink GCS module to accurately reflect the vehicle's status during takeoff and landing in the MAV_LANDED_STATE field of EXTENDED_SYS_STATE. The method now returns MAV_LANDED_STATE_TAKEOFF if the vehicle is taking off and MAV_LANDED_STATE_LANDING if it is landing, matching the ArduCopter and Blimp implementations.
In combination with mavlink/qgroundcontrol#12567, this makes it possible to abort landings in QGroundControl with ArduPilot aircraft.
=> Plane: Add tkoff. and land. to landed_state method

libraries/AP_TemperatureSensor/AP_TemperatureSensor_Backend.h, libraries/AP_TemperatureSensor/AP_TemperatureSensor_MAX31865.cpp, libraries/AP_TemperatureSensor/AP_TemperatureSensor_MCP9600.cpp, libraries/AP_TemperatureSensor/AP_TemperatureSensor_MLX90614.cpp, libraries/AP_TemperatureSensor/AP_TemperatureSensor_SHT3x.cpp, libraries/AP_TemperatureSensor/AP_TemperatureSensor_TSYS01.cpp, libraries/AP_TemperatureSensor/AP_TemperatureSensor_TSYS03.cpp
=> AP_TemperatureSensor: avoid use of OwnPtr

libraries/AP_Scripting/generator/description/bindings.desc
This enables the AP_Scripting bindings for the AP_Follow library for Rovers and Boats as requested [here in the 4.6 forums](https://discuss.ardupilot.org/t/issue-with-follow-object-in-lua-script-for-rover-to-follow-copter/131666).
This has been lightly tested in SITL to confirm that a simple script that calls **follow:have_target()** fails before this change and succeeds aftwards
**BEFORE**
**AFTER**
=> AP_Scripting: Follow binding enabled for Rover

libraries/AP_SerialManager/AP_SerialManager.cpp
This PR adds support for SERIALx_BAUD = 12500 (which is mapped to 12,500,000).  This is important with AP's improved Ethernet support because it is the recommended baud rate to use with PPP (aka serial<->ethernet).  [See the DroneNet setup page](https://ardupilot.org/copter/docs/common-botblox-dronenet.html#autopilot-configuration) for an example of this.
I've tested this change on real hardware to confirm that if SERIALx_BAUD = 12500 the autopilot could connect over PPP
=> AP_SerialManager: support baud rate of "12500"

libraries/AP_RCProtocol/AP_RCProtocol.cpp
Previously it didn't work with ARRAY_SIZE(serial_config) == 1
=> AP_RCProtocol: fix bug that at least two serial configs are needed

libraries/AP_Camera/AP_Camera_Logging.cpp
This resolves issue https://github.com/ArduPilot/ardupilot/issues/29530 by checking that the current_loc has been initialised before attempting to get the altitude from it.
This fix is thanks to @blaab2 and the commit is co-authored with him, thanks!
I've lightly tested this in SITL by performing a before/after test to confirm the issue occurs before this fix and does not afterwards.
BTW, the issue can be reproduced in SITL by doing this:
1. rm eeprom.bin file
2. start SITL
3. param set LOG_DISARMED 1
4. param set GPS1_TYPE 0
5. restart SITL
6. right-mouse-button click on MP's map and select, "Trigger Camera NOW"
Below is a screenshot of what appears in the LOGS which is a mostly zero message
=> AP_Camera: avoid SITL panic if pic taken with no pos estimate

Tools/autotest/arduplane.py, libraries/GCS_MAVLink/GCS.cpp
Logs all named value floats sent.
Includes autotest for same.
```
pbarker@fx:~/rc/ardupilot(pr/log-NVF)$ mavlogdump.py logs/00000003.BIN  --t NVF | head -2
2025-03-13 18:41:21.70: NVF {TimeUS : 2744735, Name : Lua Float, Value : 1.3891880512237549}
2025-03-13 18:41:22.71: NVF {TimeUS : 3759329, Name : Lua Float, Value : 1.6240872144699097}
pbarker@fx:~/rc/ardupilot(pr/log-NVF)$ 
```
=> GCS_MAVLink: log sent named value floats 

libraries/AP_Scripting/docs/docs.lua
I forgot to add the docs for https://github.com/ArduPilot/ardupilot/pull/27322. You can pass booleans to be logged with format `B`.
=> AP_Scripting: Docs: document logging of booleans

libraries/GCS_MAVLink/GCS_config.h
arming may not be present on periph
=> GCS_MAVLink: correct compilation on heavy-periph

libraries/GCS_MAVLink/GCS_DeviceOp.cpp
Tested using MAVProxy on CubeOrange
=> GCS_MAVLink: avoid use of OwnPtry during DeviceOp read/write

Tools/autotest/arduplane.py, Tools/autotest/vehicle_test_suite.py
```
AT-0741.0: Exception caught: RLL_RATE_D expected 0.070284 ± 2.000000% (0.068878 to 0.071690) got 0.09136922657489777 with 29.999993% error
Traceback (most recent call last):
File "/__w/ardupilot/ardupilot/Tools/autotest/vehicle_test_suite.py", line 8915, in run_one_test_attempt
test_function(**test_kwargs)
File "/__w/ardupilot/ardupilot/Tools/autotest/arduplane.py", line 4373, in AUTOTUNE
self.check_parameter_value("RLL_RATE_D", 0.070284024, 2)
File "/__w/ardupilot/ardupilot/Tools/autotest/vehicle_test_suite.py", line 6302, in check_parameter_value
raise ValueError("%s expected %f ± %f%% (%f to %f) got %s with %f%% error" % (
ValueError: RLL_RATE_D expected 0.070284 ± 2.000000% (0.068878 to 0.071690) got 0.09136922657489777 with 29.999993% error
>>>> FAILED STEP: test.PlaneTests1b at …
```
=> autotest: avoid use of non-ascii characters in test output

Tools/ardupilotwaf/embed.py
I don't think this structure in its current form permits zero-length.
Would be nice to have it.
OTOH, including a zero-lengthg defaults.parm (which picked this bug up) would mean you perhaps include a chunk of code to pull that file apart which you might not otherwise need.
```
In file included from ../../libraries/AP_ROMFS/AP_ROMFS.cpp:29: ./ap_romfs_embedded.h:5:55: error: expected primary-expression before ',' token
5 | __EXTFLASHFUNC__ static const uint8_t ap_romfs_1[] = {,0};
|                                                       ^
```
=> waf: embed.py: add sanity check for non-zero-lenght-contents

libraries/AC_Fence/AC_Fence.cpp
In both of those messages, the wording contradicts the actual logical check. The text has been adapted to match.
=> AC_Fence: Fixed wording in error messages

Tools/autotest/arduplane.py
we emit a lot of texts when starting up and getting lock.  Avoid missing our scripting restart message by waiting ready-to-arm before doing the restart
=> autotest: fix race in getting statustext

libraries/SITL/SIM_FlightAxis.cpp, libraries/SITL/SIM_FlightAxis.h
So the existing code was doing a bang-up job of double-buffering... using three pthread mutexes.
We have an ObjectBuffer_TS we can use to get the same effect, but it's simpler and generalises to having more waiting connections.
This *also* doesn't use pthread constructions, meaning it's more portable.
There's no discernible performance difference between this and master.  *Perhaps* a little better when running with a three socket queue - but there's a *lot* of noise!
=> SITL: SIM_FlightAxis: use an objectbuffer for holding connections to FlightAxis

libraries/AP_Logger/AP_Logger_MAVLink.cpp, libraries/AP_Logger/AP_Logger_MAVLink.h, libraries/AP_Logger/LogStructure.h
no user-visible change here.  The log message is DMS (Dataflash MAVLink Stats".  We have another log message "MAV" which logs mavlink statistics, so the current naming is confusing
no compiler output change
=> AP_Logger: retitle LOG_MAV_Stats to log_DMS

libraries/AP_SerialManager/AP_SerialManager.cpp
The first field must be an integer, the second can be a string. Not the other way around
=> AP_SerialManager: fix baudrate metadata

ArduCopter/mode_auto.cpp, ArduPlane/commands_logic.cpp, ArduSub/commands_logic.cpp, Rover/mode_auto.cpp, libraries/AP_Mission/AP_Mission.cpp
This adds basic support for the [DO_SET_ROI_LOCATION](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_SET_ROI_LOCATION) and [DO_SET_ROI_NONE](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_SET_ROI_NONE) mission commands
The support is only "basic" because we don't properly consume "param1" ("Gimbal device ID") so regardless of this argument's value only the first camera gimbal will be controlled (see issue https://github.com/ArduPilot/ardupilot/issues/29566).
This has been lightly tested in SITL on Copter.  We should also test on Rover, Plane and Sub.
This resolves issue https://github.com/ArduPilot/ardupilot/issues/28505
Some ground stations updates are also required to handle the DO_SET_ROI_LOCATION in the same way as we handle DO_SET_ROI.  For example, below is a screen …
=> Copter, Rover, Plane, Sub, Mission: add DO_SET_ROI_LOCATION and DO_SET_ROI_NONE support

libraries/AP_HAL/UARTDriver.h, libraries/AP_HAL_ChibiOS/UARTDriver.h
We have two variables named `_last_options`, meaning updates in the base class wouldn't be seen in the ChibiOS HAL.
=> Fix shadowed-variable problem in ChibiOS HAL

libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/sim_arming_pos.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/SITL/SIM_Aircraft.cpp, libraries/SITL/SIM_Aircraft.h, libraries/SITL/SITL.h
This allows scripting in SITL to override the vehicle position, velocity and attitude. It can be used to reproduce tricky issues in attitude recovery
=> Scripting: added sim:set_pose() binding and example

Tools/completion/completion.zsh
Fix invalid option error in cd command by removing unsupported -q flag.
=> Tools: fix building environment on macos

libraries/AC_Avoidance/AC_Avoidance_Logging.cpp, libraries/AC_Avoidance/LogStructure.h
Changed to using floats.
Inspected lgos for test.Rover.PolyFenceObjectAvoidanceBendyRulerEasierGuided - altitudes are appropriate after this change considering what was in there beforehand.  Which appears to be garbage....
=> AC_Avoidance: avoid use of location.alt in logging

ArduPlane/Plane.cpp, ArduPlane/Plane.h, ArduPlane/servos.cpp, libraries/AP_LandingGear/AP_LandingGear.cpp
if LGR_OPTIONS is set to auto-deploy then deploy
this affects all fixed wing auto-landings
=> Plane: auto-deploy landing gear on fixed wing landing

libraries/AP_Logger/AP_Logger.cpp
This improves the LOG_FILE_BUFSIZE parameter description a little bit by:
1. adding units
2. adding the range of 4~200 which is taken from the comments and the defines at the top of the file
3. removed a reference to Pixhawk which is now just one of more than 200 boards that we support
This resolves issue https://github.com/ArduPilot/ardupilot/issues/29621 which was also discussed here https://discuss.ardupilot.org/t/log-file-bufsize/132358
=> AP_Logger: improve LOG_FILE_BUFSIZE param docs

libraries/AP_GPS/AP_GPS_ExternalAHRS.cpp
=> AP_GPS: sanity-check location before consuming from EAHRS

Tools/autotest/test_build_options.py
AP_PROXIMITY_MR72_ENABLED too
These share a symbol, so we can't leave one of them out of the code and see the symbol disappear!
=> autotest: exempt AP_PROXIMITY_HEXSOONRADAR_ENABLED from sanity checks

libraries/AP_Networking/AP_Networking_address.cpp
This is a tiny fix to the networking parameter docs.  I probably should have caught this as part of PR https://github.com/ArduPilot/ardupilot/pull/28815
I haven't tested this but surely it's fine
=> AP_Networking: parm fix for ipaddr 3rd octet

libraries/AP_BattMonitor/AP_BattMonitor.h, libraries/AP_BattMonitor/AP_BattMonitor_Analog.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Params.h
@andyp1per you might like this one after having to play around with the nasty casting stuff!
Type has to live in Params as Params can't see the AP_BattMonitor class to copy the enum from.
edit: now fixes an issue where we were using the configured type rather than allocated type.  The use of the enumeration made it much clearer what was going on.
=> AP_BattMonitor: use state rather than params for type

Tools/Frame_params/ModalAI/SentinelM0065.parm
The voltage and current readings usually come from the ESC in VOXL 2 based designs. But in the case where the IO board is being used for PWM then voltage and current readings need to come from the external VOXL PM power module. This PR adds the configuration parameters needed to use the VOXL PM with the IO board to the frame params file.
=> Tools: Added INA2xx parameters to ModalAI Sentinel M0065 frame params

libraries/AP_HAL_ChibiOS/RCOutput.cpp, libraries/AP_HAL_ChibiOS/RCOutput_bdshot.cpp
Alternative to https://github.com/ArduPilot/ardupilot/pull/29379 fixes #29370
This ensures dshot_waiter is only manipulated inside a system lock. Tested on a Pavo20Pro
=> Fix dshot cancel race

libraries/SITL/SIM_Aircraft.cpp, libraries/SITL/tests/test_sim_aircraft_filtered_servo_angle.cpp
Fixes #12293. If the servo is disabled (value 0), assign the default trim value of 1500 before applying filtering.
In the filtered_servo_angle function of the Aircraft class, servo signals are expected to range from 1000 to 2000, with a neutral trim position at 1500. However, when a servo is disabled (value 0), the function incorrectly processes it as a valid PWM value, leading to unexpected behavior.
This fix ensures that disabled servos are correctly handled by explicitly setting their value to 1500 before filtering. As a result, the plane no longer goes around in circles in the simulation when the rudder servo is disabled.
Added a unit-test for the modified function that tests it with some input values in the 1000-2000 range and with value 0.
=> SITL: handle case where servo is disabled in servo angle filtering

ArduPlane/tailsitter.cpp
fixes https://github.com/ArduPilot/ardupilot/issues/29555. Thanks to https://github.com/ArduPilot/ardupilot/pull/26249 we were leaving the motors not masked for forward flight to be smoothly ramped back to zero for tiltrotors. However we overlooked the tailsitter case. Because the normal motor output is not called the motors were not being zeroed. The fix is to call the output function.
=> Plane: tailsitter: ensure none-masked motors are zeroed in forward flight

libraries/AP_DDS/AP_DDS_Client.cpp
This fixes a stack overflow on a Raspberry Pi (or any other HAL_Linux) when compiled with `--enable_dds`.
Without this change, the stack fills with recursive calls to `clock_gettime` and `micros64`:
~~~
... etc.
AP_HAL::micros64 system.cpp:69
clock_gettime AP_DDS_Client.cpp:1782
AP_HAL::micros64 system.cpp:69
clock_gettime AP_DDS_Client.cpp:1782
AP_HAL::init system.cpp:28
AP_HAL::HAL::HAL HAL.h:99
HAL_Linux::HAL_Linux HAL_Linux_Class.cpp:299
static_initialization_and_destruction_0 HAL_Linux_Class.cpp:539
_GLOBALsub_I__ZN9HAL_LinuxC2Ev HAL_Linux_Class.cpp:554
~~~
Proposed change is thanks to @peterbarker 
Flipping the compile guard from negative to positive means that all HAL_BOARDs except SITL, ESP32 and CHIBIOS will see a change.
I tested this with ArduSub built with `--enable_dds` …
=> AP_DDS: provide clock_gettime only for HAL_BOARD_CHIBIOS

ArduPlane/Attitude.cpp, ArduPlane/VTOL_Assist.cpp, ArduPlane/VTOL_Assist.h, ArduPlane/mode.cpp, ArduPlane/mode_qhover.cpp, ArduPlane/mode_qloiter.cpp, ArduPlane/quadplane.cpp, ArduPlane/quadplane.h, ArduPlane/tailsitter.cpp, ArduPlane/tiltrotor.cpp, ArduPlane/tiltrotor.h, ArduPlane/transition.h, Tools/autotest/quadplane.py, Tools/autotest/vehicle_test_suite.py, libraries/AC_AttitudeControl/AC_AttitudeControl.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/APM_Control/AP_RollController.cpp, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/sim_arming_pos.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/SITL/SIM_Aircraft.cpp, libraries/SITL/SIM_Aircraft.h, libraries/SITL/SITL.h
This is a rework of #28320 which uses the fixed wing attitude controller for recovery instead of modifying the VTOL controller. This gives much faster attitude recovery and also avoids an issue with the way the quaternion controller may try to pitch down while inverted, leading to a large amount of altitude loss
This approach builds on the way we already use the fixed wing controller during forward transitions, so it is very little code change, and testing shows it produces a very small amount of altitude loss (eg. in the autotest the alt loss is usually around 2m from fully inverted)
Update: this PR now makes the use of the forced fixed wing controller optional using Q_ASSIST_OPTIONS (defaults enabled) and adds spin recovery, also optional.
=> Plane: fast attitude recovery for quadplanes

libraries/AP_GPS/AP_GPS_GSOF.cpp
Saw this when mucking with NET_* ports and GPS. I would prefer to protect against this earlier in the stack, but we can't because it's a switch/case where the backend gets allocated. The nullptr port check in the frontend is currently here: https://github.com/ArduPilot/ardupilot/blob/2a5bc6223ebbec935789b9cabf608dd3469a3afc/libraries/AP_GPS/AP_GPS.cpp#L680
No all GPS's need a port.
=> AP_GPS: Protect against nullptr port

libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp
* Add protections in AP_ExternalAHRS against improperly initialized EAHRS drivers
* Without this, you get faults deep inside DCM that are much less obvious
* An uninitialed origin or location, just after the `have_origin` or `have_location`, is likely a bug
Continuation of https://github.com/ArduPilot/ardupilot/pull/29628
=> AP_ExternalAHRS: Protect against uninitialized location and origin

Tools/autotest/arducopter.py, libraries/AP_Math/SCurve.cpp, libraries/AP_Math/SCurve.h
This addresses the issue in #29509.
=> SCurve: Fix speed and accel checks to include z component when transitioning fast waypoints

libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS_Backend.cpp, libraries/AP_InertialSensor/AP_InertialSensor_SITL.cpp, libraries/SITL/SIM_Aircraft.cpp, libraries/SITL/SITL.cpp, libraries/SITL/SITL.h
we need to get the orientation right before any data is read
=> AHRS: fixed initial attitude for non-zero AHRS_ORIENTATION

libraries/AP_GPS/AP_GPS_UBLOX.cpp
we have a lot more steps now to configure a ublox, and it is taking an annoyingly long time. There is really not a good reason to do the configuration so slowly
on a F9P this reduces the time for configuration from detection of the ublox to fully configured from 35s to 10s
=> AP_GPS: speed up ublox configuration

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_InertialSensor/AP_InertialSensor.cpp, libraries/AP_InertialSensor/AP_InertialSensor.h, libraries/AP_InertialSensor/AP_InertialSensor_Backend.h, libraries/AP_InertialSensor/AP_InertialSensor_Invensense.h, libraries/AP_InertialSensor/AP_InertialSensor_Invensensev2.h, libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.h
This PR adds a prearm check that ensures that we are reading gyro data atleast as fast as we are running our main loop, where all controllers run at. We do this for all the INS sensors that are enabled.
This avoids a situation where user might have set SCHED LOOP RATE faster than gyro poll rate or primary gyro with appropriate backend rate but forgot to do so for the rest.
=> Prearm check to validate backend read rates against scheduler loop rate

libraries/AP_AHRS/AP_AHRS_Logging.cpp, libraries/AP_Common/Location.cpp, libraries/AP_Common/Location.h
I've checked the logs before/after this patch and the same data is present.
DCM doesn't seem to do well with altitude - the discretisation here is weird.
That log was created by right-clicking on a ~600m-high hill to the north-west of CMAC (the quarry) and "set home with height".
Looks like we may not be resetting the barometer zero datum correctly on a set-home.
=> Stop using location.alt field in AHRS logging

libraries/AP_HAL_ESP32/boards/esp32s3devkit.h
Rename ADC defines that were broken at some point. There was a previous pr that was closed, this replaces it.
=> AP_HAL_ESP32: esp32s3devkit - rename ADC defines

ArduCopter/events.cpp, ArduPlane/system.cpp, ArduSub/GCS_MAVLink_Sub.cpp, ArduSub/failsafe.cpp, Blimp/events.cpp, Rover/Rover.cpp, libraries/AP_ADSB/AP_ADSB_uAvionix_UCP.cpp, libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.cpp, libraries/AP_Scripting/generator/description/bindings.desc, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
Mis-spelt.  Probably.
LUA bindings rename this, so nothing should break.
=> Correct myggcs to mygcs

Tools/autotest/arduplane.py, Tools/autotest/vehicle_test_suite.py, libraries/GCS_MAVLink/GCS_Common.cpp
- updates mavlink to reference commit with corrected flags (shifted values not bit offsets)
- add airspeed tests
- random patch to use bitmask attribute on enumerations for sanity checks
-
=> Correct use of AIRSPEED flags 

libraries/AP_Filesystem/AP_Filesystem_FlashMemory_LittleFS.cpp, libraries/AP_Filesystem/AP_Filesystem_FlashMemory_LittleFS.h
Fixes a couple potential bugs and cleans up unused functionality to save a bit of flash.
Tested on KakuteH7Mini and KakuteH7Mini-Nand that logging and scripting still work properly.
=> AP_Filesystem: LittleFS: fix and clean up flash driver

Tools/autotest/arduplane.py, Tools/autotest/autotest.py, Tools/autotest/pysim/util.py, Tools/autotest/rover.py, Tools/autotest/sim_vehicle.py, Tools/scripts/sitl-on-hardware/sitl-on-hw.py
flake8 became more strict
eg.
Tools/autotest/sim_vehicle.py:911:9: F824 `global tracker_serial0` is unused: name is never assigned in scope
global tracker_serial0
=> Tools: flake8 fixes for global keyword

libraries/AP_InertialSensor/AP_InertialSensor_SCHA63T.cpp, libraries/AP_InertialSensor/AP_InertialSensor_SCHA63T.h
This change fixes the temperature conversion issue in the SCHA63T driver.
Previously, the temperature value was calculated using an unsigned data type.
However, since a sensor output of 0 corresponds to 35.5°C, values below that should yield a negative sensor output.
As a result, the temperature values were interpreted as large positive numbers (e.g., 1127.5°C).
Changing the data type from uint16_t to int16_t now correctly processes these negative sensor outputs.
Before
After
=> AP_InertialSensor: Fix temperature conversion for SCHA63T

Tools/environment_install/install-prereqs-ubuntu.sh
As of checking Linux Mint's releases page, there were the following versions of Linux Mint missing translations, which I've appended onto the install script:
| Linux Mint      | Ubuntu        |
|-----------------|---------------|
| Xia (22.1)      | Noble (24.XX) |
| Vera (21.1)     | Jammy (22.XX) |
| Victoria (21.2) | Jammy (22.XX) |
| Virginia (21.3) | Jammy (22.XX) |
For context, I was on Linux Mint Xia, and not having this translation causes the script to assume the release codename of "bullseye", which yields the error "Unable to locate package python-argparse".
As a side-note, I think it would help to add some insight as to why it should default to that specific Debian release instead of fast-failing outright. I understand that there are many flavors of Linux out there but at least …
=> Added Linux Mint translations for Ubuntu Jammy and Noble

libraries/AP_RangeFinder/AP_RangeFinder_HC_SR04.cpp, libraries/AP_RangeFinder/AP_RangeFinder_HC_SR04.h, libraries/AP_RangeFinder/AP_RangeFinder_LightWareI2C.cpp
This was noticed when trying to use Lightware LW20 I2C with AP_Periph. The Rangefinder support inside AP_Periph checks for the backends last update time so that we don't send duplicates: 
https://github.com/ArduPilot/ardupilot/blob/master/Tools/AP_Periph/rangefinder.cpp#L67
I did a drive-through of all the other backend and it looks like only one other backend suffers from the issue. 
This problem has been reported a few times in the past: https://discuss.ardupilot.org/t/ap-periph-not-working-with-lightwarei2c/95913
=> AP_RangeFinder: populate last_reading_ms in the backend for some sensors

libraries/AP_Common/Location.cpp
We probably can't do *too* much better if both are in terrain frame.
=> AP_Common: Location: avoid converting to absolute alt in get_alt_distance

ArduCopter/Copter.cpp, libraries/AP_Math/AP_Math.h
Most `radians` uses give a float argument and use a float return type. On `HAL_WITH_EKF_DOUBLE` boards this results in a bunch of unnecessary conversions. Create separate double and float variants of the function to eliminate the impact. The `DEG_TO_RAD` constant is already a float, therefore there is no loss of precision in the operation.
We also need a variant that takes an `int` argument as these are supplied in several places, primarily as constants, and the `int` conversion is otherwise ambiguous.
Saves a few hundred bytes of flash on such boards.
Prerequisite for candidate fix of #29660 .
=> AP_Math: split `radians` into float and double variants

libraries/AP_Scripting/examples/qnh_alt.lua
useful for BVLOS ops. The one in AFS is only available if AFS is enabled
=> AP_Scripting: added qnh_alt example

ArduPlane/fence.cpp, Tools/environment_install/install-prereqs-mac.sh, libraries/AP_Vehicle/ModeReason.h
If after a fence breach the user commands a WP change to a WP not in the landing sequence in AUTO mode or disables and re-enables the fence then the fence should be re-activated
=> Plane: fixed fence re-enable after fence breach

ArduPlane/altitude.cpp, ArduPlane/mode_LoiterAltQLand.cpp, ArduPlane/mode_autoland.cpp, ArduPlane/mode_qrtl.cpp, libraries/AP_Common/Location.cpp, libraries/AP_Common/Location.h, libraries/AP_Common/tests/test_location.cpp
I'm wondering if we can do better than this.
```
if (current_loc.get_height_above(some_other_loc)
```
No compiler output change:
```
Pixhawk1-1M-bdshot                  *                  *       *                 * …
```
=> Rename get_alt_distance -> get_height_above

libraries/AP_Camera/AP_Camera_Backend.h
Due to the strange casting rules of AP_Float parameters, the parameter value was converted to an integer because the other argument was an integer. Change the other argument to a float to cause the correct float cast instead.
Tested on Cube Orange that the `CAMERA_FOV_STATUS` message now does not truncate the FOV values specified in the corresponding parameters.
=> [4.6] AP_Camera: fix truncation of FOV stored in parameters

AntennaTracker/Tracker.cpp, ArduPlane/Plane.cpp, ArduSub/ArduSub.cpp, Rover/Rover.cpp, libraries/GCS_MAVLink/GCS_Common.cpp
Four of our six vehicles updated their mavlink system ID from the parameter at 1Hz.
Instead, do it for all vehicles at the rate GCS update() is called.  It's a cheap operation.
This is a change in behaviour for Copter and Blimp which previously required a reboot for the parameter change to take effect.
See also https://github.com/mavlink/mavlink/blob/master/message_definitions/v1.0/development.xml#L176 (`MAV_CMD_DO_SET_SYS_CMP_ID`) for a standardised way of changing a vehicle's system ID, rather than setting a parameter.
=> Set mavlink system ID in GCS library on all vehicles

ArduPlane/avoidance_adsb.cpp, ArduPlane/commands.cpp, ArduPlane/commands_logic.cpp, ArduPlane/fence.cpp, ArduPlane/mode_circle.cpp, ArduPlane/mode_qrtl.cpp, ArduPlane/quadplane.cpp
this fixes several places that set the alt field directly. The only one that is a real bug is in CIRCLE where if we were terrain following and change into CIRCLE mode we would climb to current alt + home alt absolute alt
This removes all sets of a alt field in a Location object in plane
This CIRCLE bug is also in 4.5.x
=> Plane: fixed incorrect set of location alt fields

Tools/AP_Periph/battery.cpp
Does what it says on the tin. The DroneCAN message and the battery lib both support state of health we just need to fill it in.
=> AP_Periph: BatteryMonitor: report state of health

libraries/AP_BattMonitor/AP_BattMonitor_Backend.h, libraries/AP_BattMonitor/AP_BattMonitor_Scripting.cpp, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
Allows a script to set state of health for a scripting battery monitor.
=> AP_Scripting: BatteryMonitor: allow setting state of health

libraries/SITL/SIM_Volz.cpp, libraries/SITL/SIM_Volz.h
Including sparse-endian causes redefinition problems.  It shouldn't, but it does.  Just work around the problem by moving the method to the cpp
```
In file included from /usr/include/netinet/in.h:408,
from ../../libraries/AP_HAL_SITL/CAN_Multicast.cpp:14:
/usr/include/x86_64-linux-gnu/bits/byteswap.h:34:1: error: redefinition of ‘__uint16_t __bswap_16(__uint16_t)’
34 | __bswap_16 (__uint16_t __bsx)
| ^~~~~~~~~~
In file included from /usr/include/netinet/in.h:408,
from ../../libraries/AP_HAL_SITL/SITL_State.cpp:20:
/usr/include/x86_64-linux-gnu/bits/byteswap.h:34:1: error: redefinition of ‘__uint16_t __bswap_16(__uint16_t)’
34 | __bswap_16 (__uint16_t __bsx)
| ^~~~~~~~~~
In file included from …
```
=> SITL: correct compilation when doing coverage analysis

Rover/mode.h, Rover/mode_circle.cpp, libraries/AP_Scripting/applets/rover-quicktune.lua, libraries/AP_Scripting/applets/rover-quicktune.md
A set of patches as I go through the rover quicktune process for very small vehicles (https://discuss.ardupilot.org/t/visual-navigation-on-the-cheap/91700).
For reference, I'm running rover quicktune at 0.15m/s velocity and 0.2m radius circle.
Still a few stability issues with the circle mode when tuning speed to investigate.
WIP
=> Rover: Fixes for (very) small vehicles

libraries/SITL/SIM_Vicon.cpp, libraries/SITL/SIM_Vicon.h, libraries/SITL/SITL.cpp, libraries/SITL/SITL.h
Helps with testing non-gps stuff in SITL
=> SITL: Add gausian noise and rate limit to VICON sim

libraries/GCS_MAVLink/GCS_Common.cpp
Even just the first response to a probing message is annoying to the user
=> GCS_MAVLink: remove 'No ap_message for mavlink id' warning

Tools/autotest/arducopter.py, libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.h
Revert to the primary compass if it was changed in flight. The compass might have changed because of landing in an area with high mag interference causing a timeout in the magfusion. 
Its more than likely the user wants to go back to flying on the primary mag on subsequent takeoff.  
Pushed on top of #29299
=> AP_NavEKF3: revert to primary compass on ground

libraries/AP_Mount/AP_Mount_Servo.cpp
afaict, bitwise and (`&`) will always evaluate both sides, logical and (`&&`) will be able to short-circuit evaluate.
we're checking conditions, not bits.
=> AP_Mount: Use logical operator instead of bitwise

Tools/autotest/test_build_options.py
OSD not instaniated on some vehicles
=> autotest: exemptions for AP_MSP_INAV_FONTS_ENABLED

libraries/AP_HAL_ChibiOS/hwdef/ARK_FPV/defaults.parm, libraries/AP_HAL_ChibiOS/hwdef/BROTHERHOBBYH743/defaults.parm, libraries/AP_HAL_ChibiOS/hwdef/BROTHERHOBBYH743/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/LumenierLUXF765-NDAA/defaults.parm, libraries/AP_HAL_ChibiOS/hwdef/LumenierLUXF765-NDAA/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/MicoAir743-AIO/defaults.parm, libraries/AP_HAL_ChibiOS/hwdef/MicoAir743-AIO/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/StellarF4/defaults.parm, libraries/AP_HAL_ChibiOS/hwdef/StellarF4/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/StellarF4V2/defaults.parm, libraries/AP_HAL_ChibiOS/hwdef/StellarF4V2/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/X-MAV-AP-H743v2/defaults.parm, libraries/AP_HAL_ChibiOS/hwdef/X-MAV-AP-H743v2/hwdef.dat
I misunderstood (or forgot) that osd type 5 does not automatically include the analog OSD
in fact, the analog OSD includes MSP type (3) when enabled
this corrects any hwdefs that have both analog OSD and DisplayPort defaults to set OSD type to 1
will also update their wiki pages (including pending for 4.7) to say to enable OSD_TYPE2 to 5
also noted that some bds with no analog OSD define OSD_TYPE 5 correctly in hwdef but also duplicate in their params file, fixed it here also
=> Correct default OSD types

ArduCopter/rate_thread.cpp
Dynamic scaling of the rate loop rate should never go below the main loop rate, however the main loop rate can be lower than 400 Hz. This PR fixes this issue.
Have tested on my Chimera
=> Fast rate should be constrained by actual loop rate

ArduPlane/GCS_MAVLink_Plane.cpp, ArduPlane/GCS_MAVLink_Plane.h, Tools/autotest/arduplane.py
Intended to replace the `handle_guided_change_alt` garbage where we pass in a new altitude using a mission item with a "current" of 3.
This functionality (changing altitude for current waypoint) is used by MAVProxy's "changealt" command.
At some stage I will update that to try the command first and if that fails go back to the mission item way of doing things.  But we probably don't want that until this is merged...
=> Add support for MAV_CMD_DO_CHANGE_ALTITUDE

libraries/AP_Mission/AP_Mission.cpp, libraries/AP_Mission/AP_Mission.h
this is a change of behaviour, but I think more closely aligns with expected behaviour (ie. principle of least surprise)
Should we have a MIS_OPTIONS bit for this?
=> AP_Mission: reset loop counter when loop completed

Tools/scripts/generate_manifest.py
beta-4.3 was removed as a valid tag a couple of weeks ago, but this should yield a warning in the build script.... except there's a bug in that error path....
```
Traceback (most recent call last):
File "/mnt/volume_nyc3_01/autotest/APM/APM/./build_binaries.py", line 771, in
<module>
bb.run()
File "/mnt/volume_nyc3_01/autotest/APM/APM/./build_binaries.py", line 751, in
run
self.generate_manifest()
File "/mnt/volume_nyc3_01/autotest/APM/APM/./build_binaries.py", line 662, in
generate_manifest
generator.run()
File "/mnt/volume_nyc3_01/autotest/APM/APM/generate_manifest.py", line 614, in
run
self.structure, self.features_structure = self.walk_directory(self.basedir)
File "/mnt/volume_nyc3_01/autotest/APM/APM/generate_manifest.py", line 526, in
walk_directory
(tag, os.path.join(vdir)), …
```
=> Tool: generate_manifest: correct output in error path

Tools/autotest/vehicle_test_suite.py
=> autotest: correct output diagnostic in error path

Tools/scripts/extract_features.py
these never had that update symbol
Before:
```
pbarker@crun:~/rc/ardupilot(master)$ ./Tools/scripts/extract_features.py build/MatekH743-bdshot/bin/arduplane | grep AP_BARO
AP_BARO_BMP085_ENABLED
AP_BARO_BMP280_ENABLED
AP_BARO_BMP388_ENABLED
AP_BARO_BMP581_ENABLED
AP_BARO_DPS280_ENABLED
AP_BARO_DRONECAN_ENABLED
AP_BARO_EXTERNALAHRS_ENABLED
AP_BARO_FBM320_ENABLED
!AP_BARO_KELLERLD_ENABLED
AP_BARO_LPS2XH_ENABLED
!AP_BARO_MS5607_ENABLED
!AP_BARO_MS5611_ENABLED
!AP_BARO_MS5637_ENABLED
!AP_BARO_MS5837_ENABLED
AP_BARO_MSP_ENABLED
AP_BARO_PROBE_EXTERNAL_I2C_BUSES
AP_BARO_SPL06_ENABLED
!AP_BARO_THST_COMP_ENABLED
```
After:
```
pbarker@crun:~/rc/ardupilot(pr/ms56xx-feature-extraction-fix)$ ./Tools/scripts/extract_features.py build/MatekH743-bdshot/bin/arduplane | grep AP_BARO
AP_BARO_BMP085_ENABLED …
```
=> Tools: extract_features.py: correct extraction of MS56XX features

libraries/AP_InertialSensor/AP_InertialSensor_SCHA63T.cpp
The variable RES is unused. Remove the code related to the RES variable.
=> AP_InertialSensor: Remove unnecessary processing

libraries/APM_Control/AP_PitchController.cpp
Copy-paste error - the pitch controller controls pitch
=> APM_Control: Correct copy-paste error in roll/pitch param docstring

libraries/AP_Airspeed/AP_Airspeed.cpp
* It's ARSPD_OPTIONS, was missing an S
=> AP_Airspeed: Fix typo in wind max param

.pydevproject
Last modified 11 years ago...
```diff
- <?xml version="1.0" encoding="UTF-8" standalone="no"?>
- <?eclipse-pydev version="1.0"?><pydev_project>
- <pydev_property name="org.python.pydev.PYTHON_PROJECT_INTERPRETER">Default</pydev_property>
- <pydev_property name="org.python.pydev.PYTHON_PROJECT_VERSION">python 2.7</pydev_property>
- </pydev_project>
```
Python 2 died 1,925 days ago on 1/1/2020.
Files modified in the root directory should have a git commit prefix of `waf:`.
* https://github.com/ArduPilot/ardupilot/pull/29733#issuecomment-2791726204
=> waf: Delete `.pydevproject` with legacy Python 2

Tools/autotest/rover.py, libraries/GCS_MAVLink/GCS_Common.cpp
Updates the `MAV_CMD_REQUEST_MESSAGE` handler with a special case for requesting the `MESSAGE_INTERVAL` message. The old method of using `MAV_CMD_GET_MESSAGE_INTERVAL` is deprecated.
Raised in this Discord message: https://discord.com/channels/674039678562861068/728017546313466047/1293342302261219329
=> GCS_MAVLink: Support requesting MESSAGE_INTERVAL via REQUEST_MESSAGE cmd

Tools/scripts/extract_features.py
because we use dummy methods in the AIS library it can appear to be compiled in when it is actually not functional
=> Tools: extract_features.py: changte symbol used to probe for AIS

libraries/AP_Scripting/drivers/EFI_Halo6000.lua
Sets the "is flying" bit of the 1A0 control message to 1. This should force the engine to think the aircraft is in the air and start producing power.
This is based on the following data:
Has been tested by the partner who asked for it. They reported
> I finished testing it and it works fine
thank you
=> AP_Scripting: EFI HALO6000 enable fix

libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp
Currently, the variance for ext nav is never used if a healthy GPS is connected and even if not set as a EK3_SRC_ source. 
EDIT 1: Based on reviewer comments, I have matched the maximum ext nav measurement variances to the GPS values.
EDIT 2: There is also a sneaky "gpsNoiseScaler" being multiplied at the end, depending on the number of GPS satellites that we have. I have disabled that for ext nav. Thanks to @robot-to-society for reporting that issue.  I have rasied a new PR to fix this issue: https://github.com/ArduPilot/ardupilot/pull/29847
=> AP_NavEKF3: Use the correct extnav variances for posvel fusion

libraries/AP_LandingGear/AP_LandingGear.cpp
While understanding recent landing gear changes in Plane for wiki docs, I found that the code can send multiple retract texts while already retracted and that the **_have_changed**  variable is unnecessary..also cleaned up the deploy and retract height code a bit
=> AP_LandingGear: stop dup retract messages, clean up code

libraries/AP_HAL_ChibiOS/AnalogIn.cpp
Tested with PixC4-Jetson, commenting VDD_BRICK_VALID out causes build to break. This change fixes the build.
=> AP_HAL_ChibiOS: Fix using the incorrect pin after checking the correct pin is defined

libraries/AP_Proximity/AP_Proximity.cpp, libraries/AP_Proximity/AP_Proximity.h
We have sensors like the MR72 now that can be put all around the vehicle for 360 coverage
=> AP_Proximity: Add more proximity backends

Tools/cameras_gimbals/xfrobot-download/xfrobot-download.py
This adds a python script to download images from the [XFRobot camera gimbals](https://ardupilot.org/copter/docs/common-xfrobot-gimbal.html) and is very similar to [the script we have for Siyi cameras](https://github.com/ArduPilot/ardupilot/tree/master/Tools/cameras_gimbals/siyi-download)
This has been tested on a Windows PC connected to the XFRobot camera gimbal via Ethernet.  Tests included:
1. downloaded 2 image and 2 video files from the camera gimbal
2. disconnected the ethernet connect and confirmed the script failed gracefully
3. removed the SD card and confirmed the script failed gracefully (it doesn't actually display an error message but does display that zero files were downloaded)
=> Tools: XFRobot image and video download script

Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/conftest.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_plane_airspeed.py
Add a test and the fixtures necessary for testing the DDS interface of plane
Lots of code duplication in the fixtures.... We can fix that later.
=> Tools: ros2: Add airspeed test with new fixtures for testing plane in ROS 2 CI

ArduCopter/AP_Arming_Copter.cpp, ArduPlane/AP_Arming_Plane.cpp, ArduSub/AP_Arming_Sub.cpp, ArduSub/Parameters.h, Blimp/AP_Arming_Blimp.cpp, Rover/AP_Arming_Rover.cpp, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.h, libraries/AP_Logger/LogStructure.h
This is a no-compiler-output change:
```
f103-QiotekPeriph        *                 * …
```
=> Make ArmingChecks enum class AP_Arming::Check

libraries/AP_HAL_ChibiOS/hwdef/ARKV6X/hwdef.dat
Sets the RC serial port to default as RCIN
=> hwdef: arkv6x: add default serial port for RCIN

ArduCopter/mode_follow.cpp, Tools/autotest/arducopter.py, Tools/autotest/quadplane.py, Tools/autotest/vehicle_test_suite.py, libraries/AP_Follow/AP_Follow.cpp, libraries/AP_Follow/AP_Follow.h
This work sponsored by Freespace Operations
In preparation for kinematically-consistent target information.
=> AP_Follow: change to using position-from-origin internally

Tools/autotest/models/skywalker_2013.json, libraries/AP_JSON/AP_JSON.h, libraries/SITL/SIM_Plane.cpp, libraries/SITL/SIM_Plane.h
For simulations, we want to run SITL with our own aero model without recompiling the code.
This makes it easier to maintain than forks with modified coefficients, one for each vehicle.
First, run with the default model which is loaded as JSON now. Arm and takeoff and observe it flies the same.
```bash
./Tools/autotest/sim_vehicle.py -v Plane  --console -DG
arm throttle
mode takeoff
```
Now, specify a json file to load, which loads the same file as the default.
```bash
./Tools/autotest/sim_vehicle.py -v Plane --model plane:@ROMFS/models/skywalker_2013.json  --console -DG
```
Finally, add your own aero model by copying skywalker_2013.json to a new file, and change a value.
```bash
cp Tools/autotest/models/skywalker_2013.json  Tools/autotest/models/custom_plane_aero.json
```
Now, raise the …
=> SITL: Support JSON aero coefficients

libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_AttitudeControl/AC_PosControl.h
This fixes a couple problems:
- get_fwd_pitch_is_limited can be stuck on true if it becomes unsaturated while being true,
- it is only used in quadplane but runs on every loop in Copter,
- it was added to the main update XY position controller loop.
This PR fixes the bug and lest us only run it when called. I also want to remove it at compile time from copter but need some help to do this.
=> Fix and move get_fwd_pitch_is_limited()

libraries/AP_BattMonitor/AP_BattMonitor.cpp
Don't want a bug in a lua script to cause a hard fault.
=> AP_BattMonitor: handle_scripting nullptr check

Tools/autotest/arducopter.py, libraries/AP_NavEKF3/AP_NavEKF3.cpp, libraries/AP_NavEKF3/AP_NavEKF3.h
While doing EKF-based tests, this is helpful. 
When the EK3_OPTIONS second bit is enabled, automatic lane switching will be disabled (unless the core becomes "unhealthy", which is very extreme and we should never be flying with that). And EK3_PRIMIARY core will be enforced. This also means we can select the active core from a Lua Script mid flight.  
Might also have some use cases when lane switches are happening often because of small timing difference in the core. Example, flying with a single baro on a windy day and seeing lane switches isn't uncommon. 
I personally also have a usecase for this PR where I am working on another branch that allows different types of sensors to be used in different lanes, for example GPS on lane 1, Ext Nav on lane 2. For testing Ext Nav, it'll be helpful …
=> AP_NavEKF3: Manual Lane switching 

ArduCopter/AP_Arming_Copter.cpp, ArduCopter/Attitude.cpp, ArduCopter/Copter.h, ArduCopter/mode.cpp, ArduCopter/mode.h, ArduCopter/mode_althold.cpp, ArduCopter/mode_autotune.cpp, ArduCopter/mode_circle.cpp, ArduCopter/mode_flowhold.cpp, ArduCopter/mode_loiter.cpp, ArduCopter/mode_poshold.cpp, ArduCopter/mode_sport.cpp, ArduCopter/mode_zigzag.cpp
these are always the same value, so simplify things
Makes this method look like several other methods which consume data from rc() directly rather than having it passed in eg. `get_pilot_desired_lean_angles`
=> Copter: stop passing control in value to get_pilot_desired_climb_rate

Tools/Frame_params/ModalAI/Starling2Max.parm
This fixes a few issues with the parameter file for the [ModalAI Starling2Max quadcopter](https://www.modalai.com/en-jp/products/starling-2-max?variant=48172375310640)
I've tested this on a real vehicle and they seem OK to me
=> Tools: fix Starling2Max param file

ArduSub/GCS_MAVLink_Sub.cpp, ArduSub/Parameters.h, ArduSub/joystick.cpp, ArduSub/radio.cpp, libraries/SRV_Channel/SRV_Channel.cpp, libraries/SRV_Channel/SRV_Channel.h, libraries/SRV_Channel/SRV_Channel_aux.cpp
This decouples some of the "hard links" we have between input rc channels and functionality
=> Sub: turn lights and video_switch into aux functions

libraries/GCS_MAVLink/GCS_Common.cpp
This commit exists as a separate branch in ArduPilot's mavlink repo on github
=> mavlink: reference commit fixing AIRSPEED bitmask

Tools/environment_install/install-prereqs-ubuntu.sh
... to an Uubntu release.
Saves confusion on newer Mint releases as thje install will fail with a clear message rather than get confused on packages
Closes https://github.com/ardupilot/ardupilot/issues/29710
=> Tools: environment_install: make sure Linux Mint dist is always mapped

libraries/AP_GPS/AP_GPS_GSOF.cpp
Backport of https://github.com/ArduPilot/ardupilot/pull/29642
=> AP_GPS: Protect against nullptr port - Backport of 29642

libraries/AP_GPS/AP_GPS_NOVA.cpp
Required for the ellipsoid height to be broadcast correctly over e.g. MAVLink. Tested on a NovAtel OEM719.
[Geoid information](https://www.unavco.org/software/geodetic-utilities/geoid-height-calculator/geoid-height-calculator.html) using EGM96 from my (approximate) back yard showing an ellipsoid height of 63.364m, an undulation of -28.35m, and a mean sea level height of 91.71m: 
Before this PR, the GPS shows a mean sea level height of 91.664m (correct), but an ellipsoid height of 119.964m (incorrect):
After this PR, the GPS shows a mean sea level height of 86.039m (correct, slightly different day and location), and an ellipsoid height of 57.739m (correct):
=> AP_GPS: NOVA: fix undulation

Tools/autotest/run_in_terminal_window.sh
This allows a method to launch gdbserver from vscode extension
=> autotest: add support for adding prefix while launching tmux new-window

ArduSub/mode.cpp
all mode  changes spam when there is no depth sensor, even on mode changes not requiring one...this just changes the early return order to avoid this....no logic change to the IF statement per see
tested on CubeOrange
=> Sub:stop spammin depth sensor messages

ArduCopter/GCS_MAVLink_Copter.cpp, ArduCopter/autoyaw.cpp, ArduPlane/mode_qloiter.cpp, ArduPlane/mode_thermal.cpp, ArduSub/GCS_MAVLink_Sub.cpp, ArduSub/commands_logic.cpp, ArduSub/mode_auto.cpp, Rover/mode_circle.cpp, libraries/AC_Avoidance/AP_OABendyRuler.cpp, libraries/AC_Avoidance/AP_OADijkstra.cpp, libraries/AC_WPNav/AC_Circle.cpp, libraries/AC_WPNav/AC_WPNav.cpp, libraries/AC_WPNav/AC_WPNav_OA.cpp, libraries/AP_Common/Location.cpp, libraries/AP_Common/Location.h, libraries/AP_Common/tests/test_location.cpp, libraries/AP_Compass/AP_Compass.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/set_target_posvel_circle.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AR_WPNav/AR_WPNav.cpp, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/SITL/SITL.cpp
Moves us closer to using metres in this interface
Several places `*= 0.01`the result of this method already.
```
Durandal                            0      *           8       0                 8      8      8
KakuteH7-bdshot                     0      *           8       8                 8      8      0 …
```
=> Rename Location get-vector-from-origin methods

ArduPlane/system.cpp, libraries/AP_DAL/examples/AP_DAL_Standalone/main.cpp, libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp, libraries/AP_NavEKF2/AP_NavEKF2_OptFlowFusion.cpp, libraries/AP_NavEKF3/AP_NavEKF3_AirDataFusion.cpp, libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp, libraries/AP_NavEKF3/AP_NavEKF3_OptFlowFusion.cpp, libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp, libraries/AP_Param/AP_Param.h, libraries/AP_Param/AP_ParamT.cpp, libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp, libraries/SITL/SIM_ADSB.cpp
Fixes #29660 for floats at least. An expression like `float v = true ? float_param : 0;` would cause `float_param` to be truncated to an integer to match the other type. Fix by only letting `AP_Float` be converted to a float. It is still possible to get truncation with integer parameter types, e.g. `int16_t v = true ? int16_param : (int8_t)0;` but I don't think it's a problem at this point.
There is a bunch of subtlety and some caveats, please see the commit contents and messages for details. The issue contains a list of areas of the code whose behavior will be changed by this, but problems are exclusive to the ternary operator and overloaded functions, not standard arithmetic operators.
Tested on Cube Orange that the `CAMERA_FOV_STATUS` message now does not truncate the FOV values …
=> AP_Param: fix unexpected truncation of AP_Float parameters in expressions

ArduPlane/AP_Arming_Plane.cpp, ArduPlane/Parameters.h, ArduPlane/Plane.h, ArduPlane/radio.cpp
No compiler output change.
Avoids a bunch of casting...
```
Board,plane
MatekF405-Wing,*
```
=> Plane: Use AP_Enum for throttle_fs_enabled

.github/problem-matchers/Lua.json, .github/workflows/test_scripting.yml, Tools/scripts/run_lua_language_check.py, libraries/AP_Scripting/applets/RockBlock.lua, libraries/AP_Scripting/examples/MAVLinkHL.lua
Our lua language server CI has been incorrectly passing thanks to some recent changes to the language server. This updates so it correctly fails (and fixes the issues that crept in)
I can't get the problem matcher to work again, so no nice annotations, `fileLocation` seems to not work. It works fine for the luacheck problem matcher, so I have no idea.
A alternate fix would be to add `--check_format json` to the call to the language server. But the new native error printing is nicer than what I had done in python by parsing the json. Just we loose the problem match.
=> Fixup lua language server CI

libraries/AP_Proximity/AP_Proximity.cpp, libraries/AP_Proximity/AP_Proximity.h, libraries/AP_Proximity/AP_Proximity_DroneCAN.cpp
PROXIMITY devices are optional. 
Recently, the number of devices increased from 4 to 5. 
Therefore, the number of devices will be configurable.
AFTER
BEFORE
=> AP_Proximity: PROXIMITY is optional, so the number of devices can be specified

ArduPlane/GCS_MAVLink_Plane.cpp, ArduPlane/mode.h, ArduPlane/mode_guided.cpp
* Precursor to https://github.com/ArduPilot/ardupilot/pull/29829 to reduce code duplication
=> ArduPlane: Factor out guided airspeed cmd logic from GCS_MAVLinkPlane to ModeGuided

ArduCopter/mode.cpp
I will shorten the lifetime of stack variables.
There is no advantage to prolonging the lifetime of stack variables.
=> Copter: Shorten the lifetime of stack variables

.github/workflows/test_chibios.yml, Tools/scripts/build_ci.sh
Reverts ArduPilot/ardupilot#28128 now that CubeRed is out of flash and CubeOrange has loads free.
=> CI: revert "build CubeRed-EKF2 not CubeOrange-EKF2 in CI"

libraries/AP_GPS/AP_GPS.cpp, libraries/AP_GPS/LogStructure.h
ArduPilot's internal definition of undulation is reversed in sign compared to the accepted convention and this creates confusion: https://github.com/ArduPilot/ardupilot/issues/29199 .
Instead of the internal definition, log the altitude above ellipsoid, which ArduPilot already consistently and correctly calculates and broadcasts over e.g. DroneCAN and MAVLink. Switching the quantity logged allows users to accommodate the problem in old logs (i.e. always flip GPA.Und sign to match the accepted convention) and reduces opportunity for future confusion.
Future work will clean up or replace the internal representation, but this should be a complete fix for the issue from a user perspective.
Tested using u-blox, u-blox over AP_Periph over DroneCAN, and NovAtel.
[Geoid …
=> AP_GPS: log altitude above ellipsoid instead of undulation

libraries/AP_HAL_SITL/SITL_State.cpp, libraries/AP_Notify/examples/ToshibaLED_test/ToshibaLED_test.cpp, libraries/SITL/SIM_Aircraft.cpp
nullptr dereference in some examples.
We shouldn't be using it over there anyway.
Similarly for Scheduler
... and a couple of other issues raised in the ToshbibaLED example specifically
=> Avoid using Baro in SITL library (nullptr deref running examples)

libraries/AP_Scripting/applets/RockBlock.lua, libraries/AP_Scripting/examples/MAVLinkHL.lua
Following on from the discussion in #29889, this PR fixes up a Lua ``cast-local-type`` issue.
=> AP_Scripting: fix cast-local-type in Rockblock and MAVLinkHL

libraries/AP_HAL_Linux/CANSocketIface.cpp, libraries/AP_HAL_SITL/CANSocketIface.cpp
Issue: https://github.com/ArduPilot/ardupilot/issues/23802
PR into master: https://github.com/ArduPilot/ardupilot/pull/23803/commits
=> Rover4.4 builderror patch

Tools/ros2/ardupilot_msgs/CMakeLists.txt, Tools/ros2/ardupilot_msgs/msg/Airspeed.msg, libraries/AP_DDS/AP_DDS_Client.cpp, libraries/AP_DDS/AP_DDS_Client.h, libraries/AP_DDS/AP_DDS_Topic_Table.h, libraries/AP_DDS/Idl/ardupilot_msgs/msg/Airspeed.idl, libraries/AP_DDS/README.md
Current `/ap/airspeed` topic publishes the true airspeed vector, but many user need to operate in Equivalent Airspeed. It is then useful to provide users with the same scale factor that Ardupilot uses internally to obtain the Equivalent Airspeed, rather then asking developers to use their own conversion algorithm which could result in errors.
- Created a new message type `Airspeed`, which contains the same vector as before, plus the scale factor `eas_2_tas`.
```
ros2 topic info /ap/airspeed
Type: ardupilot_msgs/msg/Airspeed
Publisher count: 1
Subscription count: 0
```
```
ros2 topic echo /ap/airspeed --once
header:
stamp:
sec: 1741905800
nanosec: 131471000
frame_id: base_link
true_airspeed:
x: -0.015433487482368946
y: -0.015331915579736233
z: -0.003518373006954789
eas_2_tas: …
```
=> AP_DDS: airspeed message to include eas_2_tas factor

ArduPlane/Parameters.cpp
https://aviation.stackexchange.com/a/89380
If you set `WP_LOITER_RAD` too small, then your achieved loiter radius is `g * tan(ROLL_LIMIT_DEG) / v`
=> ArduPlane: Clarify behavior with small WP_LOITER_RAD

Tools/autotest/arduplane.py, Tools/autotest/vehicle_test_suite.py
... also slip in a few new convenience methods.
If you give the estimators a really long time (by pushing that number out to 6000) weird things start to happen:
=> autotest: allow EKF3 more time to learn wind in DeadreckoningNoAirspeed

libraries/AP_DroneCAN/AP_DroneCAN.cpp
The way the description is phrased is a little confusing since need to map servo outputs and not functions. E.g. for this setup:
```
SERVO1_FUNCTION  19.000000 # Elevator
SERVO2_FUNCTION  0.000000 # Disabled
SERVO3_FUNCTION  0.000000 # Disabled
SERVO4_FUNCTION  0.000000 # Disabled
SERVO5_FUNCTION  4.000000 # Aileron
SERVO6_FUNCTION  4.000000 # Aileron
SERVO7_FUNCTION  0.000000 # Disabled
SERVO8_FUNCTION  0.000000 # Disabled
SERVO9_FUNCTION  33.000000 # Motor1
SERVO10_FUNCTION 34.000000 # Motor2
SERVO11_FUNCTION 35.000000 # Motor3
SERVO12_FUNCTION 36.000000 # Motor4
SERVO13_FUNCTION 70.000000 # Throttle
SERVO14_FUNCTION 0.000000 # Disabled
SERVO15_FUNCTION 0.000000 # Disabled
SERVO16_FUNCTION 0.000000 # Disabled
```
I expect the following:
```
CAN_D1_UC_ESC_BM 3840.000000 #  ESC 9| ESC 10| …
```
=> AP_DroneCAN: ESC bitmask description clarification

libraries/AC_Autorotation/AC_Autorotation.cpp
it's a lot of trouble to go to to create a variable to then not use it!
=> AC_Autorotation: correct logging of reason into AROT

libraries/GCS_MAVLink/GCS_Common.cpp
Replaces https://github.com/ArduPilot/ardupilot/pull/29803/files
=> GCS_MAVLink: add comment to ensure 16-bit maths is preserved

ArduPlane/quadplane.cpp
This docstring is not correct.
https://github.com/ArduPilot/ardupilot/blob/8e9a568a55be2d4129e0b06f460c82bd7dec7953/ArduPlane/mode_auto.cpp#L152-L162
=> Plane: fix Q_OPTION bit 18 docstring

libraries/AP_GPS/AP_GPS_DroneCAN.cpp, libraries/AP_GPS/AP_GPS_DroneCAN.h
AP_Periph sends `ellipsoid == MSL` if the underlying GPS driver can't retrieve an ellipsoid height for whatever reason. Older versions of AP_Periph (including all Here3+ firmwares at the time of writing) always send `MSL == ellipsoid` and never report a valid ellipsoid height.
To accommodate this, only use the ellipsoid height reported over DroneCAN to compute an undulation if we've ever seen it different from the MSL height. This ensures we accurately represent the equipment capability, at least if the GPS is not changed at runtime.
Future work will establish an "unknown" ellipsoid height value in the DroneCAN standard and always ignore it.
Tested on Cube Orange and MatekL431-Periph nodes (running various code versions) connected to a u-blox GPS.
=> AP_GPS: DroneCAN: only trust ellipsoid height if different from MSL

libraries/AP_HAL_ESP32/boards/esp32empty.h, libraries/AP_HAL_ESP32/boards/esp32s3empty.h
Add `AP_MOTORS_FRAME_xxx_ENABLED` guards to `SIM_Frame.cpp` as they are applied in `AP_Motors_Matrix.cpp`. This does not change default behaviour and allows the majority of the motor mixes to be disabled in the `esp32xxempty` boards which frees up RAM.
- https://github.com/ArduPilot/ardupilot/pull/28848
Before
```bash
Total sizes:
Used static DRAM:  147848 bytes (  32888 remain, 81.8% used)
.data size:   19368 bytes
.bss  size:  128480 bytes
Used static IRAM:  113718 bytes (  17354 remain, 86.8% used)
.text size:  112691 bytes
.vectors size:    1027 bytes
Used Flash size : 1856264 bytes
.text: 1548788 bytes
.rodata:  307220 bytes
Total image size: 1989350 bytes (.bin may be padded larger)
```
After
```bash
Total sizes:
Used static DRAM:  120488 bytes (  60248 remain, 66.7% used)
.data …
```
=> AP_HAL_ESP32: add AP_MOTORS_FRAME_xxx_ENABLED guards

Rover/GCS_MAVLink_Rover.cpp, Rover/GCS_MAVLink_Rover.h
Replaces https://github.com/ArduPilot/ardupilot/pull/26955/files which simply factored the check out.
This both factors the check out and stops us accepting the position target if acceleration is set.
We should probably also reject if other bits and pieces are set.
=> Rover: reject position targets if acceleration supplied

Tools/scripts/board_list.py, Tools/scripts/size_compare_branches.py, libraries/AP_HAL_Linux/hwdef/linux/hwdef.dat
This allows for correct stripping of Linux binaries when determining binary-identicalness.
Also removes hack for making elf-diff work.
Create a Result object to handle a compilation result as a gradual-improvement thing
=> Pass toolchain through to tools using board_config.py

libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp
It is believed (see below) that the conversion is wrong and needs to be changed from 100000/3600 = 100/3.6 to 36 = 10*3.6.
(note: 100/3.6 = 28 is quite a bit different from 36 but maybe not enough to be immediately noticed)
The PR also grabs the oportunity to write the factor in floats, like it is done two lines below for the other gps() data.
This came out of a bug report of a mLRS user, https://github.com/olliw42/mLRS/issues/271, where the user observed a signifcant difference for the ground speed reported as FCRSF GSpd telemetry sensor and in MissionPlanner, even though both data items are derived from the same MAVLink message. It was traced back to a bug in the conversion from the mavlink data into crsf data in mLRS.
The same code is used also in ArduPilot howver (actually, it's …
=> AP_RCTelemetry, CRSF ground speed incorrect by some 20%

libraries/AP_TECS/AP_TECS.cpp
`badDescent` prevents an unreasonable airspeed command from causing a dive. This is not needed during transition. If an unreasonable airspeed command is set, you'll eventually fail to transition, not nose-dive.
Additionally, 3 of these conditions are guaranteed to be true through transition, and toward the latter half of transition, when KEdot is small, any noise on KEdot can cause a zero-crossing. Looking back at old logs, I seem to get a `badDescent` flag, and subsequent throttle-back when the commanded airspeed drops to min, somewhere on every outbound transition (on 4.5.7 firmware, in case that's relevant). I don't want my pusher throttling back on outbound transitions.
It seems to me that `badDescent` should get the same treatment as `underspeed`, which is disabled in VTOL.
=> AP_TECS: stop setting badDescent during transition

ArduCopter/mode_drift.cpp, ArduPlane/quadplane.cpp, ArduPlane/tailsitter.cpp, ArduPlane/tiltrotor.cpp, libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.cpp, libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.cpp, libraries/AP_HAL/utility/st24.cpp, libraries/AP_HAL_SITL/SITL_State_common.cpp, libraries/AP_Math/tests/test_geodesic_grid.cpp, libraries/AP_Math/tests/test_rc_in_to_roll_pitch.cpp, libraries/AP_Motors/AP_MotorsMulticopter.cpp, libraries/AP_RCProtocol/AP_RCProtocol_ST24.cpp, libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp, libraries/SITL/SIM_Calibration.cpp
I don't think there is any benefit to omitting the integer part in a floating-point value.
By adding a zero before the decimal point, we can clearly indicate that it is a floating-point value.
=> Global: Clarify the floating point value

Tools/ardupilotwaf/boards.py
Weird things happen if you specify clang++ for your CXX compiler but leave CC as GCC.
=> waf: ensure if you're using clang then you're using clang++ and vice-versa

ArduCopter/radio.cpp, ArduPlane/radio.cpp, Blimp/radio.cpp, Rover/radio.cpp
I discovered this while working on adding RC to Sub...easy to reproduce
Sim vehicle with defaults...happens disarmed or in the air
- SIM_RC_FAIL =0    you get an RC failsafe, prearm or action
- Disable the failsafe  ie FS_THR_ENABLE or THR_FAILSAFE = 0
- SIM_RC_FAIL =1    you enabled RC, but failsafe state is still not cleared...no GCS message...prearms if disarmed on ground
wont clear until reboot or resetting failsafe enable
non fatal but really annoying if you run into it...
hope its doesn't make CI uhappy
=> All vehicles: Fix non fatal rc failsafe bug

libraries/AP_HAL_ChibiOS/hwdef/CUAV-Nora/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/CUAV-X7/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/MFT-SEMA100/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/NarinFC-H7/hwdef.dat
```
Board        blimp  bootloader  copter  heli  plane  rover  sub
CUAV-Nora    *      *           *       *     *      *      *
CUAV-X7      *      *           *       *     *      *      *
MFT-SEMA100  *      *           *       *     *      *      *
NarinFC-H7   *      *           *       *     *      *      *
```
=> hwdef: remove unused USB_HW_ENABLE_HS define

Tools/ardupilotwaf/boards.py
If you expand up you can see we're setting these CXX flags based on `if 'clang' in cfg.env.COMPILER_CC:`  - but that's the C compiler, not the C++ compiler version.
We have a block for adding CXX flags based on C++ compiler version, so use that for these CXX flags!
=> waf: stop setting CXX flags based on C compiler version

libraries/AP_HAL_Linux/CANSocketIface.cpp, libraries/AP_HAL_SITL/CANSocketIface.cpp
With multiple threads sending CAN messages we can get a race with the send mutex. This issue was found in SITL with quadplane-can frame.
=> CAN: fixed race in SITL and Linux HALs

ArduCopter/mode_follow.cpp, Rover/mode_follow.cpp, libraries/AP_Follow/AP_Follow.cpp, libraries/AP_Follow/AP_Follow.h
Work from before my main AP_Follow updates
```
SCB: HACK: Removing (build/CubeOrange/modules/DroneCAN/libcanard/dsdlc_generated)
SCB: Running (./waf configure --board CubeOrange --consistent-builds --bootloader) in (.)
SCB: Running (./waf bootloader) in (.)
SCB: Running (rsync -ap build/ /tmp/tmpn3s6xjeg/out-branch-CubeOrange) in (.)
```
=> AP_Follow axis and unit naming

libraries/AP_Mount/AP_Mount_Siyi.cpp
This adds a check that the Siyi ZT6's camera firmware is at least version 0.1.9 which will encourage users to update the firmware on the camera gimbal and reduce issues like those reported in [this 4.6 beta testing thread](https://discuss.ardupilot.org/t/geotag-images-taken-by-siyi-gimbal-cameras/129664/11).
This has been lightly tested on real-hardware
=> AP_Mount: Siyi ZT6 min cam version is 0.1.9

libraries/AP_TECS/AP_TECS.cpp
Issue https://github.com/ArduPilot/ardupilot/issues/7817 pointed out that the order in which we are retrieving the euler angles from the transformation matrix is incorrect.
Testing shows that there is a discrepancy between these values and the values retrieved directly from the AHRS.
Since we are simply attempting to retrieve the roll angle, extract it directly from the AHRS.
Closes https://github.com/ArduPilot/ardupilot/issues/7817
Ping @luweiagi
=> AP_TECS: avoid use of cosphi_squared dcm matrix trick

Blimp/AP_Arming_Blimp.cpp, Rover/AP_Arming_Rover.cpp, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_MAVLink_Parameters.cpp
btiwise-op stuff; we intentionally use & to avoid short-circuiting.
Also fixes for `-Wunknown-warning-option`
=> Avoid compiler warnings raised by clang++

Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/conftest.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_plane_airspeed.py
Try again for https://github.com/ArduPilot/ardupilot/pull/29832 which broke after merge due to unrelated changes.
Originally reverted in https://github.com/ArduPilot/ardupilot/pull/29957
Tested 5x locally with no issues. I also checked the timeouts in the test report, and bumped this to 20 seconds since it's almost 10 seconds on each test to receive airspeed data from boot.
=> Tools: Add airspeed test and SITL plane fixtures

libraries/RC_Channel/RC_Channel.cpp
omitted in original scripting PR
=> RC_Channel:add Lowheiser metadata to aux functions

ArduCopter/Copter.cpp, ArduCopter/GCS_MAVLink_Copter.cpp, ArduCopter/mode.h, ArduCopter/mode_auto.cpp, ArduCopter/mode_circle.cpp, ArduCopter/mode_follow.cpp, ArduCopter/mode_guided.cpp, ArduCopter/mode_loiter.cpp, ArduCopter/mode_rtl.cpp, ArduCopter/mode_smart_rtl.cpp, ArduCopter/mode_zigzag.cpp, ArduSub/commands_logic.cpp, ArduSub/mode.h, Blimp/mode.h
The distance between WAYPOINTs is in centimeters.
I will add the unit to the method.
=> Global: Add units to the method that calculates the distance meter between waypoin ts

Tools/autotest/arducopter.py, Tools/autotest/vehicle_test_suite.py, libraries/AP_Filesystem/AP_Filesystem_Param.cpp, libraries/AP_Param/AP_Param.cpp, libraries/AP_Param/AP_Param.h, libraries/GCS_MAVLink/GCS_Param.cpp
Closes https://github.com/ardupilot/ardupilot/issues/29985
This work sponsored by Freespace Solutions
=> Disallow setting of readonly/internal parameters via mavftp 

Tools/scripts/configure_all.py
The `ChibiOSHWDef` takes named values, seems to have been broken for ages, maybe by https://github.com/ArduPilot/ardupilot/pull/23732
Without this detection no hwdef is ever passed so nothing is detected as periph. That means configure all trys to build vehicles on periph boards and fails.
=> Tools: scripts: configure all: --build: fix periph detection

ArduSub/AP_Arming_Sub.cpp
for RC only operation without joystick buttons or just gcs aux function commands
=> Sub:add aux func disarm/estop to pre-arm check for disarm function

ArduPlane/AP_ExternalControl_Plane.cpp, ArduPlane/AP_ExternalControl_Plane.h, libraries/AP_DDS/AP_DDS_ExternalControl.cpp, libraries/AP_ExternalControl/AP_ExternalControl.h
I want to control plane's airspeed from DDS while in GUIDED mode, similar to [MAV_CMD_GUIDED_CHANGE_SPEED](https://mavlink.io/en/messages/ardupilotmega.html#MAV_CMD_GUIDED_CHANGE_SPEED).
We already have low level velocity control in the DDS interface, currently implemented on copter. We can use the same topic for airspeed commands, assuming the linear Y and Z components are NaN, and it's in the body frame obeying the [ROS REP-103 FLU convention](https://www.ros.org/reps/rep-0103.html#axis-orientation). I assume that ROS users will want airspeed control in plane rather than local GPS speed control.
The guided code was pulled from GCS_Mavlink_Plane::handle_command_int_guided_slew_commands where it handled MAV_CMD_GUIDED_CHANGE_SPEED: …
=> Add airspeed control to AP_DDS for plane in GUIDED

Tools/autotest/arducopter.py, libraries/AP_Mission/AP_Mission.cpp
Old way of sending fence as MISSION_ITEM and not MISSION_ITEM_INT seems to be broken. This seems to fix it.
This PR orignally broke it: https://github.com/ArduPilot/ardupilot/pull/22593 I think
=> AP_Mission: Include fence and rally point in stored_in_location

libraries/AP_InertialSensor/AP_InertialSensor_L3G4200D.h
It's private and doesn't appear in the C++
=> AP_InertialSensor: remove unused rotation member

libraries/AP_Mount/AP_Mount_Siyi.cpp
By setting the version to bdde2690 , it becomes a single line.
This makes the version easier to visualize.
=> AP_Mount: Adjust the version setting to match ZT6

Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/launch_fixtures.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_battery_msg_received.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_geopose_msg_received.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_joy_msg_received.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_navsat_msg_received.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_prearm_service.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_rc_msg_received.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_time_msg_received.py
* Normally these go in conftest and are auto-imported by pytest, but LaunchPytest requires any fixtures to be statically visible at import time and imported directly
* By moving these fixtures into a common file, we reduce the amount of code duplication for our tests
=> Tools: ros2: Reduce test code duplication with fixture reuse

libraries/AP_Landing/AP_Landing.cpp, libraries/AP_Landing/AP_Landing.h, libraries/AP_Landing/AP_Landing_Slope.cpp
the AP_Landing library assumed AMSL waypoints for both prev_WP_loc and next_WP_loc. This led to an incorrect glide slope for a NAV_LAND fixed wing landing when the landing WP is terrain relative.
This change fixes the code to handle either an AGL or AMSL location, which are the only two location types used in plane
fixes an issue in 4.6.0-beta reported here: https://discuss.ardupilot.org/t/plane-4-6-0-beta/126358/183
tested in SITL
=> AP_Landing: fixed assumption of AMSL WPs

libraries/AP_Scripting/applets/plane_ship_landing.lua
this method can return false if the target is outside the AP_Follow acceptance radius.  So we can be receiving messages from the target, so have_target can be true, but false is returned from get_target_location_and_velocity_ofs, meaning we try to call methods on nil values
We could be a bit more nuanced here with our diagnostics
=> AP_Scripting: plane_ship_landing.lua: add pos/vel sanity check

Tools/autotest/vehicle_test_suite.py, libraries/AP_Relay/AP_Relay.cpp
Also tidy up the writing of the message.
No-compiler-output change:
```
Board,copter
CubeOrange,*
```
=> Document the RELY log message

libraries/AP_Terrain/AP_Terrain.cpp
This fixes #29392. In the calculate_grid_info function and the east_blocks function of AP_Terrain, the TERRAIN_SPACING parameter is used to determine grid spacing and how many blocks are needed in a stride for a given location. 
When this parameter is set to a value less than 1, a division by zero occurs, leading to an arithmetic exception. This fix   ensures that grid_spacing is properly handled when its value is below 1. Specifically, if grid_spacing is less than 1, the system defaults to using a value of 1 instead.
This fix has been tested in SITL environment and seems to be working fine.
=> AP_Terrain: Protect against division by 0 when TERRAIN_SPACING is less then 1

libraries/AP_Common/tests/test_location.cpp
This is a unit test - we run it in CI.
Runs locally.
=> AP_Common: tests: remove un-needed vehicle object

ArduPlane/quadplane.cpp, Tools/autotest/quadplane.py
I'm not sure if you are aware of this, @tridge, but I think this is the correct equation to calculate the stopping speed. From my test, I don't notice any difference. I only test using SITL with Gazebo though.
=> ArduPlane: fix quadplane stopping speed equation

ArduCopter/Copter.cpp
if we are at bind-time values then we still get new radio frames, they're just not something we should use
Tested in SITL by setting a breakpoint within the new clause.  When we're in there having set SIM_RC_FAIL to 2 the channels are definitely using bind-time values.
=> Copter: avoid updating simple-mode values when RC input is invalid

libraries/AP_BattMonitor/AP_BattMonitor.cpp
AP_BattMonitor: add null check to mppt power state
=> AP_BattMonitor: add null check to mppt power state

ArduCopter/mode_loiter.cpp, ArduCopter/mode_zigzag.cpp
.... which they do, for the most part.
This PR removes special-case logic in Loiter and ZigZag which check for radio failsafe before updating the loiter controller with values returned from them (etc.).
Those methods already check that RC input is good (improvements coming there, however!).  So rely on those methods returning sensible values when there's no RC present.  Several other modes already make the assumption that these methods do sensible things (eg. `ModeAltHold`!).
Note that `clear_pilot_desired_acceleration` just sets `(0, 0)`, and `get_pilot_desired_lean_angles` sets target-roll/target-pitch to zero if RC input is bad).
~There is a second fix in here where checks were insufficient when looking at RC values.  This is the `update_simple_mode` method matches.  We not only have …
=> Copter: Trust get-pilot-desired methods check RC input for validity

ArduPlane/Parameters.cpp, ArduPlane/navigation.cpp, libraries/AP_Landing/AP_Landing.cpp, libraries/AP_Landing/AP_Landing.h, libraries/AP_Landing/AP_Landing_Slope.cpp, libraries/AP_TECS/AP_TECS.cpp
This PR allows for lower airspeeds during the landing final while maintaining appropriate limits during other phases of the flight, including the landing approach phase, if AIRSPEED_STALL is set. This enables smoother/slower landings when a conservative AIRSPEED_MIN is used, which previously resulted in fast touchdowns.
- Relaxed target airspeed constraints in navigation.cpp to allow for target airspeeds as low as AIRSPEED_STALL if set. This enables the following changes while maintaining safety, as the TECS further constraints the target airspeed as appropriate.
- Added a method to the landing controller to determine if the aircraft is on landing final.
- Adjusted the TECS airspeed constraints during landing final to allow speeds as low as AIRSPEED_STALL, if set.
- Corrected an …
=> Plane: Allow lower speeds in landing final

libraries/AP_DDS/AP_DDS_Client.cpp, libraries/AP_DDS/AP_DDS_config.h
Make the DDS features that depend on GPS rely on `AP_GPS_ENABLED`. 
Follow up to https://github.com/ArduPilot/ardupilot/pull/28177 where we hard-coded navsatfix enable flag to `1`. 
If you disabled GPS on `master` now and enabled DDS, you would get a compile error,
=> AP_DDS: Make GPS DDS features depend on GPS

Tools/autotest/arducopter.py, libraries/SITL/SIM_RF_NoopLoop.cpp, libraries/SITL/SIM_RF_Wasp.cpp
Vagaries of timing and the terrain database mean that it's not a good idea to run with SIM_TERRAIN on for this test.
Also changes two simulators to not return zero for their distance, ever, as the drivers don't consider 0 a valid reading.
I'm not sure if those drivers *should* accept zero as a valid distance - perhaps @rishabsingh3003 has a datasheet for the NoopLoop.
```
- improve diagnostics
- split tests up to ensure clean state for mavlink and sitl tests
- make arming more reliable in mavlink test
- make use of new infrastructure
- stop using simulated terrain in RangeFinderDrivers test
- we're not actually moving the vehicle, so we really don't need simulated terrain, and because the terrain db isn't always ready to go we get inconsistent results
```
=> Fix RangeFinderDrivers test when running locally

libraries/AP_Scripting/applets/VTOL-quicktune.lua, libraries/AP_Scripting/applets/revert_param.lua, libraries/AP_Scripting/applets/rover-quicktune.lua, libraries/AP_Scripting/examples/gen_control.lua
... tested in another script which uses the same block....
=> AP_Scripting: correct use of pcall in examples and applets

libraries/AP_HAL_ChibiOS/hwdef/common/flash.c
Previously, the routine only read the data back from the data cache, which was guaranteed correct as the cache would be allocated by the test before programming then filled with the correct data during programming.
Invalidate the data cache area containing the just-programmed data to ensure that it is actually read back from the flash memory and the verification does something.
This is not trivial to check, but it can be done. To an unprogrammed (all 1s) 256-bit flash word, program the byte sequence `CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC1CCCCCCCC` followed by (and without erasing) the sequence
`CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC0CCCCCCCC`. This will cause the flash memory (on the tested H743 revision at least) to read …
=> AP_HAL_ChibiOS: correctly verify flash on H7

libraries/AP_Scripting/lua_bindings.cpp, libraries/AP_Scripting/lua_scripts.cpp
Incorrect use of the Lua string conversion functions could cause null pointer dereferences and possible autopilot faults. The simplest example is `error()`, which is guaranteed to cause a dereference if it occurs at the top level of a script, but there are some bindings susceptible to problems too. 
This is just the patches for 4.6 for easy backporting. The `error()` issue is also in 4.5 and probably earlier; that commit could be straightforwardly backported on its own. (The affected bindings are not in 4.5)
Tested on CubeOrange that the affected functions don't dereference null pointers anymore and appropriate errors are given.
=> AP_Scripting: fix non-string-induced null pointer dereferences

libraries/AP_HAL_ChibiOS/Scheduler.cpp, libraries/AP_HAL_ChibiOS/hwdef/common/malloc.c
The hardware can read and write address zero just fine, but doing it through a C null pointer will invoke undefined behavior and may cause the compiler to emit faulting instructions.
Switch to using an assembly instruction to do the actual access, thereby avoiding UB by not having an actual null pointer anywhere. Simplifies the code and reduces flash usage while improving safety 0.1%!
Tested on KakuteH7Mini that using the "nullptr write" mavlink evil command triggers an internal error. And of course that the board still boots otherwise.
=> AP_HAL_ChibiOS: improve H7 low memory zero check

Tools/autotest/vehicle_test_suite.py, libraries/AP_DAL/AP_DAL.h, libraries/AP_DAL/LogStructure.h
I found this very useful when working on replay beacon stuff.
The Flags enumeration values are based off the RFRN log structure:
```
struct log_RFRN {
int32_t lat;
int32_t lng;
int32_t alt;
float EAS2TAS;
uint32_t available_memory;
Vector3f ahrs_trim;
uint8_t vehicle_class;
uint8_t ekf_type;
uint8_t armed:1;
uint8_t unused:1;  // was get_compass_is_null
uint8_t fly_forward:1;
uint8_t ahrs_airspeed_sensor_enabled:1;
uint8_t opticalflow_enabled:1;
uint8_t wheelencoder_enabled:1;
uint8_t takeoff_expected:1;
uint8_t touchdown_expected:1;
uint8_t _end;
};
```
=> Document DAL RFRN message

libraries/AP_CANManager/AP_SLCANIface.cpp, libraries/AP_CANManager/AP_SLCANIface.h
Setting `_port` to nullptr always carries a risk, as we may be interrupting a thread that was about to dereference it. Once we set `_port`, we could avoid setting it to nullptr again, and instead use a flag. This allows us to prevent a hardfault without needing a mutex (and this can be a pretty hot path, so it's probably best to avoid it).
=> AP_SLCANIface: prevent hardfault on arm

Tools/autotest/vehicle_test_suite.py, libraries/AP_GPS/AP_GPS.cpp
.... and remove two messages that have now been documented
=> autotest: add sanity check that greylisted items are not documented

libraries/AP_HAL/hwdef/scripts/hwdef.py, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
This fixes two issues users struggle with on the custom build server, where they end up with a failing build due to incomplete dependencies
=> hwdef: make using custom build a bit easier

ArduCopter/fence.cpp, ArduCopter/mode.cpp, ArduPlane/Parameters.cpp, ArduPlane/fence.cpp, ArduSub/fence.cpp, libraries/AC_Fence/AC_Fence.cpp, libraries/AC_Fence/AC_Fence.h
```
CubeOrange-periph-heavy  *                 *
CubeRedPrimary                      *      *           *       *                 0      *      *
Durandal                            *      *           *       *                 0      *      *
KakuteH7-bdshot                     *      *           *       *                 0      *      *
MatekF405                           *      *           *       *                 0      *      *
Pixhawk1-1M-bdshot                  *                  *       *                 0      *      *
f103-QiotekPeriph        *                 *
f303-Universal           *                 *
iomcu …
```
=> Make fence action enum class

Tools/autotest/arducopter.py, libraries/AP_Param/AP_Param.cpp, libraries/AP_Scripting/applets/param-set.lua, libraries/AP_Scripting/applets/param-set.md, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Param.cpp
~~Add `MAV_OPTION` bit to ignore setting of parameters via MAVLink.~~
State is now ephemeral.
Add a LUA script which will honours `PARAM_SET` - based on a a whitelist of parameter names.
```
STABILIZE> Lua: State memory usage: 4824 + 10598
AP: Scripting: restarted
AP: param-set-filter script loaded
STABILIZE> 
STABILIZE> param set DISARM_DELAY 5
STABILIZE> AP: param-set-filter: param set denied (DISARM_DELAY)
Flight battery 100 percent
AP: param-set-filter: param set denied (DISARM_DELAY)
Failed to set DISARM_DELAY to 5 (invalid returned value 3.0)
STABILIZE> 
```
This work sponsored by Freespace Solutions
=> Add option to ignore parameter sets / LUA applet to handle parameter sets

Tools/autotest/vehicle_test_suite.py, libraries/AP_TemperatureSensor/AP_TemperatureSensor_Backend.cpp, libraries/SITL/SIM_Volz.cpp
Simulated Volz servo and the AP_TemperatureSensor library's log messages.
=> Document SMVZ and TEMP log messages

libraries/AP_Scripting/applets/param-set.lua
We discovered we didn't need to filter to messages just to this system ID, the bindings do that
=> AP_Scripting: param-set.lua: trim out unused MAV_SYSID parameter reference

libraries/GCS_MAVLink/GCS_Common.cpp
This follow-up to https://github.com/ArduPilot/ardupilot/pull/29783 stops another "No ap_message for mavlink id (xxx)" status text message from being sent when a set-message-interval request fails except for on SITL where we continue to send it.
Thanks to @Hwurzburg for finding this
This has been tested in SITL and on real hardware to ensure that the message appears before the change but does not appear afterwards.  For that testing I used Mission Planner's Ctrl-F screen to pull up the "Message Interval" screen and then chose an unsupported message (e.g. ACTUATOR_CONTROL_TARGET) and set the interval to 3hz
Before this change we see the message appear, after the change it does not
=> GCS_MAVLink: set message interval fail msg only sent on SITL

Tools/ardupilotwaf/ardupilotwaf.py, Tools/ardupilotwaf/boards.py, Tools/autotest/sim_vehicle.py, Tools/ros2/ardupilot_sitl/CMakeLists.txt, Tools/scripts/build_ci.sh, Tools/scripts/build_options.py, Tools/scripts/extract_features.py, libraries/AP_DDS/AP_DDS_Serial.cpp, libraries/AP_DDS/README.md, libraries/AP_DDS/gen_config_h.py, libraries/AP_DDS/wscript, libraries/AP_Vehicle/AP_Vehicle.h, wscript
A continuation of @Ryanf55's attempt in #28440.
This allows the DDS (ROS2) feature to be enabled via hwdef. Currently only enabled for the CubeRedPrimary - happy to take advice on which other boards to enable for.
Tested in SITL and on a CubeRed.
=> Build: Allow DDS to be enabled in hwdef

ArduCopter/mode_follow.cpp, libraries/AP_Follow/AP_Follow.cpp, libraries/AP_Follow/AP_Follow.h, libraries/AP_Math/control.cpp, libraries/AP_Math/control.h
This pr provides a kinematic estimate of the target location and heading.
I have added time out's and resets based on the kinematic limits and errors.
We need to decide on how we choose between the different data message sources. Ideally I would like to change the name and extend the _ALT_TYPE parameter to be 0: GPI absolute, 1: GPI relative, 2: Follow Target (GPI = global position int).
We also need to decide what the options and default settings should be. We can leave the kinematic interpolation off by default, we may choose not to process acceleration to reduce noise.
=> Follow kinematic shaping

Blimp/radio.cpp
this was for Copter's transmitter-based-tuning code, which wasn't brought over in Blimp.
=> Blimp: remove pointless set of CH_6 RC deadzone

libraries/GCS_MAVLink/GCS_Common.cpp
Without this patch, ArduPilot replies with 'MAV_RESULT_IN_PROGRESS' instead of 'MAV_RESULT_ACCEPTED' for a barometer calibration with no airspeed sensor.
Copter 4.3 responded with 'MAV_RESULT_ACCEPTED' when a barometer cal was requested.
=> GCS_MAVLink: check airspeed is enabled before trying to calibrate

ArduSub/mode_surftrak.cpp, Tools/autotest/ardusub.py
Reset surftrak when the sub is disarmed. Fixes https://github.com/ArduPilot/ardupilot/issues/30102
=> Sub: reset surftrak if disarmed

libraries/AP_BLHeli/AP_BLHeli.cpp, libraries/AP_BLHeli/AP_BLHeli.h, libraries/AP_HAL/RCOutput.h, libraries/AP_HAL_ChibiOS/RCOutput.cpp, libraries/AP_HAL_ChibiOS/RCOutput.h, libraries/AP_HAL_ChibiOS/RCOutput_bdshot.cpp
soft serial input was both racy and prone to resetting the line mode incorrectly.
soft serial input was decoding input with trailing 1's incorrectly
soft serial input could miss data when timing out and restarting
DMA output could be left in a bad state
=> The Mother of All BLHeli Passthrough Fixes

libraries/AP_HAL_ChibiOS/hwdef/MicoAir743-AIO/defaults.parm, libraries/AP_HAL_ChibiOS/hwdef/MicoAir743-AIO/hwdef.dat
this autopilot does not have an onboard OSD chip and should not have had the correction
=> hwdef:revert osd type change

Tools/autotest/vehicle_test_suite.py, libraries/AC_CustomControl/AC_CustomControl.cpp
```
.. _CC:
CC
~~
Custom Controller data
+--------+------+------------------------------+
| TimeUS |      | Time since system startup    |
+--------+------+------------------------------+
| Type   | enum | controller type              |
|        |      | Values:                      |
|        |      |                              |
|        |      | +------------+---+--+        |
|        |      | | CONT_NONE  | 0 |  |        |
|        |      | +------------+---+--+        |
|        |      | | CONT_EMPTY | 1 |  |        |
|        |      | +------------+---+--+        |
|        |      | | CONT_PID   | 2 |  |        |
|        |      | +------------+---+--+        |
|        |      |                              |
+--------+------+------------------------------+
| Act    |      | true …
```
=> Document CustomController CC message

ArduPlane/quadplane.cpp, ArduPlane/tiltrotor.cpp, ArduPlane/tiltrotor.h, libraries/AP_Motors/AP_MotorsMulticopter.cpp, libraries/AP_Motors/AP_MotorsMulticopter.h, libraries/AP_Motors/AP_Motors_Class.h, libraries/AP_TECS/AP_TECS.cpp, libraries/AP_TECS/AP_TECS.h, libraries/SRV_Channel/SRV_Channel.h, libraries/SRV_Channel/SRV_Channel_aux.cpp
This is a fix for the instant forward motor(s) throttle drop that can occur when a quadplane with tilting rotors completes the transition from VTOL to FW flight. This issue was reported here https://github.com/ArduPilot/ardupilot/issues/28957
This fix:
Extends the functionality of the set_throttle_min function such that the rate that the lower limit releases can be controlled by a TECS_THR_ERATE parameter and the throttle out previous value used by the TECS throttle rate limiter can also be optionally reset. If TECS_THR_ERATE is <=0 the legacy behaviour will be observed, ie the minimum throttle will be held for one TECS frame after the function is called.
Adds a function to the motors library that enables the raw normalised throttle demand to be obtained for a specified motor index.
Adds …
=> Fix FW transition throttle glitch for tilting rotor quadplanes

libraries/AC_PID/AC_P.cpp, libraries/AC_PID/AC_P.h, libraries/AC_PID/AC_PID.cpp, libraries/AC_PID/AC_PID.h, libraries/AC_PID/AC_PID_2D.cpp, libraries/AC_PID/AC_PID_2D.h, libraries/AC_PID/AC_PID_Basic.cpp, libraries/AC_PID/AC_PID_Basic.h, libraries/AC_PID/AC_PI_2D.cpp, libraries/AC_PID/AC_PI_2D.h, libraries/AC_PID/AC_P_1D.cpp, libraries/AC_PID/AC_P_1D.h, libraries/AC_PID/AC_P_2D.cpp, libraries/AC_PID/AC_P_2D.h
I wanted to change the "boost" input variable name to "pd_scale" for better clarity and thought I should do the job properly while I was there. 
- Improved function and inline comments for AC_PID, aligning with ArduPilot PID controller conventions
- Clarified filter reset, derivative calculation, and integrator behavior
- Renamed internal PD_scale to pd_limit_scale to avoid confusion with pd_scale input parameter
- Minor comment corrections and typo fixes across .h and .cpp
No functional changes. Improves readability and maintainability.
```
```
=> Refactor AC_PID comments and internal naming for clarity and consistency

libraries/AP_Scripting/examples/trisonica-mini.lua, libraries/AP_Scripting/examples/trisonicia-mini.md
Bin logger for https://www.licor.com/products/trisonica/LI-550-mini
Dynamically writes log depending on what data outputs you enable.
Here's a uvw velocity plot.
Follow up: 
Fold this data into ArduPilot, share it via MAVLink or DDS outside AP, and use it as the airspeed source for the EKF.
=> AP_Scripting: Add wind decoder for Trisonica LI-550

libraries/AC_AttitudeControl/AC_AttitudeControl.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
This is a no-compiler-output change for the AttitudeController.
This was extracted from some upcoming work from Leonard (https://github.com/ArduPilot/ardupilot/pull/30120).
It corrects some names (particularly some method names), but mostly just adds units to local variables in the AttitudeController.
``` …
```
=> AC_AttitudeControl method and variable renames

Tools/autotest/arducopter.py
Tidies both AutoTune and AutoTuneYawD, which are essentially identical at the moment.
Corrects AutoTuneYawD to verify that the yaw D gain hasn't changed at the end of the test.
I tested that the final assertions still work by modifying the test to landing in autotune mode.  The gains get saved and the test fails.
Added some code that allows the test suite to revert the parameter values.  Given the current working of these AutoTune tests it isn't strictly necessary (they assert these values haven't changed, and we reset parameters in the suite on failure), but I don't want weird tuning values to creep into subsequent tests because someone forgets this code in future tests!
I did consider factoring these two tests but decided against it.  There should be more test clauses in these tests to …
=> Tidy Copter AutoTune tests

ArduSub/Parameters.cpp, ArduSub/Parameters.h, ArduSub/Sub.cpp, ArduSub/mode.cpp, ArduSub/mode.h, ArduSub/mode_surface.cpp, Tools/autotest/ardusub.py
This fixes an issue where SURFACE mode doesn't work on vehicles with no baros for altitude sensor.
=> Sub: allow SURFACE mode to work with no altitude data

Tools/autotest/arducopter.py, libraries/AP_Proximity/AP_Proximity_LD06.cpp, libraries/AP_Proximity/AP_Proximity_LD06.h, libraries/Filter/ModeFilter.cpp
This alternative to PR https://github.com/ArduPilot/ardupilot/pull/30050 adds a mode filter to try and remove the noise from the sensor readings when used outdoors
This PR also includes these fixes:
1. comments are slightly improved
2. fix to the distances pushed to the OA database.  Previously a distance was pushed for each 2 deg sector but this distance was the shortest distance for the "face" (the "face" is the larger 45 degree sector into which the smaller 2 deg sector falls)
3. constify a local variable
4. improve some definitions (add a confidence definition, remove some unused definitions)
This has not yet been tested on real hardware nor in the simulator
[The relevant 4.6.0-beta discussion is here](https://discuss.ardupilot.org/t/looking-to-get-firmware-release-4-6-0-beta2-11-dec-2 …
=> AP_Proximity: LD06/LD19 gets mode filter

Rover/Parameters.cpp, Rover/Rover.h, Rover/failsafe.cpp, Rover/fence.cpp, Tools/autotest/rover.py, libraries/AC_Fence/AC_Fence.cpp, libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp
This is especially useful for boats, as we usually don't want it to drift away with the current once if failsafes
=> Rover: add 'Loiter or Hold' as a failsafe action

Tools/autotest/logger_metadata/emit_html.py, Tools/autotest/logger_metadata/emit_md.py, Tools/autotest/logger_metadata/emit_rst.py, Tools/autotest/logger_metadata/emit_xml.py, Tools/autotest/logger_metadata/emitter.py
This PR updates to the Logger metadata parser Python scripts in Tools/autotest/logger_metadata to be flake8 clean, including adding the "AP_FLAKE8_CLEAN" tag to them. Only minor whitespace changes were required.
Checked by running flake8 locally and also by Ardupilot CI.
=> autotest: Flake8 clean all logger metadata scripts

libraries/AP_RCTelemetry/AP_RCTelemetry.cpp, libraries/AP_RCTelemetry/AP_RCTelemetry.h
the current name doesn't tell you much, and definitely doesn't hint that it's returning you which sensors are present and enabled but not healthy
No compiler output change
```
Board,plane
CubeOrangePlus,*
```
=> AP_RCTelemetry: rename sensor_status_flags to unhealthy_sensors

ArduCopter/motor_test.cpp, ArduCopter/rate_thread.cpp
Motortest currently doesn't work with the fast rate thread and I suspect that it was somewhat accidental that it did before. The issue is synchronization between the fast rate thread and the main thread when dealing with the motor test. This fixes the synchronization issues and allows motor test to work normally with the fast rate thread.
Reported here: https://discuss.ardupilot.org/t/unlocking-the-potential-of-faster-attitude-rates-in-copter-control/120743/54
=> Copter: fix threading issues with motor test and the fast rate thread

libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_MAVLink_Parameters.cpp, libraries/GCS_MAVLink/GCS_Signing.cpp
**Implements issue #28736** (opened by @IdoBuchman).
Instead of using a bitmask as initially suggested in the issue, this implementation integrates the new parameter into the existing GCS_MAVLINK_Parameters group, which I believe is the most suitable place for it. 😊
=> New MAVx_OPTIONS parameter to enable channel-specific signing

ArduCopter/inertia.cpp, ArduPlane/Plane.cpp, Rover/Rover.cpp, libraries/AP_Follow/AP_Follow.cpp, libraries/AP_Follow/AP_Follow.h
This moves the update_estimates call to the main vehicle code and turns all calls to retrieve pos, vel, accel, heading ect, into const.
Still may need a "lock" or what ever that is called.
=> AP_Follow fix for lua calls and threading issue.

libraries/AR_Motors/AP_MotorsUGV.cpp, libraries/AR_Motors/AP_MotorsUGV.h
adds an optional delay when reversing motors for ESCs that need it
this does not yet try to stop integrator windup while reversing. I suspect that is not needed for many ESCs as the required delay is quite small (eg. the ESCs I have need a 0.3s delay)
Also note that all ESCs actually do have a delay on reversal, so we already have the integrator issue, it is just that this makes the delay inherent in the signal sent to the ESC, rather than only being in the internals of the ESC
=> AR_Motors: added MOT_REV_DELAY

ArduCopter/AP_Arming_Copter.cpp, ArduCopter/events.cpp, ArduCopter/inertia.cpp, ArduCopter/mode_throw.cpp, ArduCopter/system.cpp, ArduSub/inertia.cpp, ArduSub/system.cpp, Blimp/AP_Arming_Blimp.cpp, Blimp/events.cpp, Blimp/inertia.cpp, Blimp/system.cpp, libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h, libraries/AP_InertialNav/AP_InertialNav.cpp, libraries/AP_InertialNav/AP_InertialNav.h, libraries/AP_NavEKF/AP_Nav_Common.h, libraries/AP_NavEKF3/LogStructure.h
Replaced with a call of "get_status" on the AHRS library instead.
More work after this (already done, but more than needs to be done immediately):
- replace uses of `AP_AHRS::get_filter_status`
- make DCM fill in and return the filter status
- cache `get_filter_status` in `AP_AHRS::state`
More work not yet done:
- return filter status in the backend_results object from DCM, SIM, External etc
-
=> Remove get_filter_status from inertialnav

libraries/GCS_MAVLink/GCS_Common.cpp
Treat all negative interval values like -1. This is preferable to the current behavior, where we treat those like 1000Hz requests.
=> GCS_Common: better handle negative intervals

AntennaTracker/Tracker.cpp, ArduCopter/Copter.cpp, Rover/Rover.cpp, libraries/AP_Scheduler/examples/Scheduler_test/Scheduler_test.cpp
Confused me for a minute. Figured it's worth a quick rename.
A couple places got missed during the original refactor ages ago, and Copter got accidentally reverted to the old name later.
=> Global: fix SCHED_TASK rate_hz name

libraries/AC_Fence/AC_PolyFence_loader.cpp, libraries/AP_BoardConfig/board_drivers.cpp, libraries/AP_Camera/AP_RunCam.cpp, libraries/AP_Compass/AP_Compass_Calibration.cpp, libraries/AP_GPS/AP_GPS_SBP2.cpp, libraries/AP_Generator/AP_Generator_RichenPower.h, libraries/AP_GyroFFT/AP_GyroFFT.cpp, libraries/AP_ONVIF/AP_ONVIF.cpp, libraries/AP_OSD/AP_OSD_MAX7456.cpp, libraries/RC_Channel/RC_Channel.cpp, libraries/SITL/SIM_Glider.cpp, libraries/SITL/SIM_RF_LightWareSerial.cpp, libraries/SITL/SIM_SPI.cpp
these often make their way in when moving from some other printf-style debugging...
=> Remove line feeds from GCS_SEND_TEXT calls

ArduCopter/AP_Arming_Copter.cpp, ArduCopter/Attitude.cpp, ArduCopter/Copter.cpp, ArduCopter/Copter.h, ArduCopter/GCS_MAVLink_Copter.cpp, ArduCopter/Log.cpp, ArduCopter/autoyaw.cpp, ArduCopter/baro_ground_effect.cpp, ArduCopter/crash_check.cpp, ArduCopter/heli.cpp, ArduCopter/inertia.cpp, ArduCopter/land_detector.cpp, ArduCopter/mode.cpp, ArduCopter/mode.h, ArduCopter/toy_mode.cpp, ArduCopter/wscript, libraries/AC_AttitudeControl/AC_PosControl.h, libraries/AC_WPNav/AC_Circle.h, libraries/AC_WPNav/AC_Loiter.h, libraries/AC_WPNav/AC_WPNav.h, libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_AHRS/AP_AHRS.h, libraries/AP_SurfaceDistance/AP_SurfaceDistance.cpp, libraries/AP_SurfaceDistance/AP_SurfaceDistance.h
This is the final PR to remove INAV from Copter completly.
CubeOrange,0,*,32,56,*,*,0
=> Remove INAV from Copter

Tools/ardupilotwaf/chibios.py
the specs were preventing cacheing ChibiOS builds
=> waf: make ccache effective for ChibiOS builds

libraries/GCS_MAVLink/GCS.cpp, libraries/GCS_MAVLink/GCS.h
nothing says get_sensor_status_flags can't be called from multiple threads.
If it is called from multiple threads then there's a reasonably obvious race where the mask can be cleared while some other process is already updating the flags.  That can cause a caller to report something as unhealthy when it isn't.
=> GCS_MAVLink: protect control sensor flag bitmasks with a semaphore

ArduCopter/Parameters.cpp, ArduCopter/defines.h, ArduCopter/ekf_check.cpp, ArduCopter/mode_turtle.cpp, ArduCopter/motor_test.cpp
This changes to always trigger the notify library and send a message in EKF fail-safes if armed, this should make it clear to the user that there is a issue. For example if flying in stabilize currently it would not be clear to the pilot that the vehicle is in a EKF failsafe, they would just find they can't switch to position control for some reason.
One disadvantage of this is that EKF failsafes will get more annoying which might lead to complaints.
It also adds a report only option for that will only trigger the notify state and a send text. In such a case the the pilot can decide what the best course of action is. The default value of the parameter is Land from position control modes.
=> Copter: add FS_EKF_ACTION report only and notify in all cases

ArduCopter/mode.h, ArduCopter/mode_auto.cpp
This allows using the height above a landing waypoint if it is available. This is used only on land commands in auto. Rangefinder takes priority if available. 
This altitude is used for the transition to slow landing, landing gear deploy, min nav altitude.
This is a change in behavior with no rangefinder. Copter will currently use the height above terrain if available, if not the height above home.
The disadvantage is that currently the land altitude is never used, its quite easy when using mission planner to endup with the landing at the same altitude as the mission because of the default altitude functionality. 
The advantage is that you can set the landing altitude in whatever alt frame you like. This is especially important if landing away from home.
Quadplane already does this, …
=> copter: auto: provide alt above landing location if landing

libraries/AP_Scripting/drivers/SIM7600.lua, libraries/AP_Scripting/drivers/SIM7600.md
provides a MAVLink connection over LTE without needing a companion computer.
Tested on a SIM7600E-H modem from AliExpress
This is ideally paired with a port on the ArduPilot support server https://support.ardupilot.org. The flight controller will stream a mavlink connection onto the support server and the user can connect a GCS as a support engineer.
=> AP_Scripting: LTE driver using SIM7600 AT commands

libraries/AP_Scheduler/AP_Scheduler.cpp
On SITL at least the values of loop period and friend get initialized early before init() has been run leading to incorrect values.
=> AP_Scheduler: prevent aggressive initialization of loop period

libraries/AP_GPS/AP_GPS_DroneCAN.cpp
Process `num_sats` for all incoming `gnss.Fix2` messages
See #30241.
=> AP_GPS: Satellites count zeroed when no fix in gnss.Fix2 message

Tools/autotest/arduplane.py, libraries/AP_Camera/AP_Camera_Backend.cpp, libraries/AP_Camera/AP_Camera_Backend.h
Added an autotest to make sure this comes through
We really should be adjusting the values returned into this message if we know the camera's orientation (eg. it is on a mount)
=> AP_Camera: avoid using cd when sending camera feedback message

Rover/RC_Channel_Rover.cpp, Rover/commands.cpp, Rover/crash_check.cpp, Rover/cruise_learn.cpp, Rover/ekf_check.cpp, Rover/failsafe.cpp, Rover/mode_auto.cpp, Rover/mode_circle.cpp, Rover/mode_dock.cpp, Rover/mode_guided.cpp, Rover/mode_rtl.cpp, Rover/mode_smart_rtl.cpp, Rover/sailboat.cpp, Rover/system.cpp
Both GCS().SEND_TEXT and GCS_SEND_TEXT are being used.
I think it would be better to standardize the notation.
=> Rover: Change to GCS_SEND_TEXT

ArduPlane/Parameters.cpp
This PR adds additional information to the description of the RTL_RADIUS parameter for quadplane users:
"For quadplanes with Q_RTL_MODE set to 1 (Enabled), this value is used to set the radius at which the plane will transition from fixed-wing to VTOL mode for landing."
(As discussed @MichelleRos)
=> ArduPlane: Add info for quadplane to RTL_RADIUS description

libraries/AP_Scripting/AP_Scripting_SerialAccess.cpp, libraries/AP_Scripting/AP_Scripting_SerialAccess.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
Adds Lua scripting support to configure UART parity and stop bits through the AP_Scripting_SerialAccess interface.
Changes
Added configure_parity(uint8_t) and set_stop_bits(uint8_t) methods to AP_Scripting_SerialAccess
Updated bindings.desc with proper type validation and range limits
Updated docs.lua for Lua API documentation
Needs further testing. If someone can test on my behalf I would be very grateful, as I am on vacation now.
=> AP_Serial: Provide bindings for parity and stop bits

Tools/scripts/build_options.py, Tools/scripts/decode_devid.py
the driver supports three different compasses with similar names
From @rmackay9 's comment on https://github.com/ArduPilot/ardupilot/pull/30068
Patch also required in MAVProxy
=> Tools: tweak AK09916 to AK0991x

Tools/autotest/param_metadata/param.py, libraries/AP_Logger/AP_Logger.cpp
This value is converted to bytes using 1024 as the divisor. Therefore, the unit is KiB.
WIKI:
https://en.wikipedia.org/wiki/Kilobyte
=> AP_Logger: Ensure that the units are specified accurately

ArduCopter/Attitude.cpp, ArduCopter/autoyaw.cpp, ArduCopter/mode.cpp, ArduCopter/mode_circle.cpp, ArduCopter/mode_land.cpp, ArduCopter/mode_rtl.cpp, ArduCopter/mode_turtle.cpp, ArduCopter/system.cpp, ArduCopter/toy_mode.cpp, ArduCopter/tuning.cpp
in the case the user is supplying RC input via RC overrides (from the GCS), the Radio failsafe will never be true.
If the GCS stops sending messages then we do not want to use stale data!
Problem description from Discord:
```
Hi all,
Can anyone clarify what the expected behaviour is if a GCS controlled drone (no RC receiver) goes into GCS failsafe (triggering RTL)?
I am testing in SITL and it continues to replay the last manual_control message received.
e.g. if manual_control message was to pitch forwards immediately before GCS failsafe, the drone pitches forward in the descent phase of RTL.
Is there a way to make it go to a neutral, or stop value?
```
=> Copter: do not use RC input if it is not valid

.github/workflows/cygwin_build.yml, Tools/ardupilotwaf/git_submodule.py
Apparently this can move around, so assume /c/d isn't great
Extracted from: https://github.com/ArduPilot/ardupilot/pull/30250/commits
=> Use cygpath to get working directory for cygwin build job

libraries/AP_Baro/AP_Baro.cpp, libraries/AP_Compass/AP_Compass.cpp, libraries/AP_InertialSensor/AP_InertialSensor.cpp
The boards that use these PX4_BOARD types specify their sensor sets, so they don't get into these blocks.
This is a no-compiler-output-change for mindpx-v2 and DrotekP3Pro but other boards that do `AP_FEATURE_BOARD_DETECT` save a little bit of flash:
```
DrotekP3Pro                         *      *           *       *                 *      *      *
Durandal                            -272   *           -280    -280              -280   -280   -272 …
```
=> Remove dead sensor detection code

libraries/AP_OSD/AP_OSD_Screen.cpp
Tested in `sim_vehicle.py` with `--osd`
=> AP_OSD_Screen: avoid use of ahrs.roll_sensor and ahrs.pitch_sensor

.github/workflows/test_scripts.yml, Tools/scripts/board_list.py, Tools/scripts/build_ci.sh, Tools/scripts/param_check.py, Tools/scripts/param_check_all.py, Tools/scripts/param_check_unittests.py
We don't automatically check our parameter files for correctness (name typos, param renames/removals, etc.). This adds the following, bare minimum checks (links take you to existing failures in the repo):
- [Every line in the parameter file has valid syntax](https://github.com/ArduPilot/ardupilot/blob/8fe927c1d3eb6be9da8544ac48f7ec210abf5789/Tools/autotest/default_params/motorboat.parm#L2)
- [Every parameter actually exists](https://github.com/ArduPilot/ardupilot/blob/8fe927c1d3eb6be9da8544ac48f7ec210abf5789/libraries/AP_HAL_ChibiOS/hwdef/SkystarsH7HD/defaults.parm#L7)
- [Every parameter appears in a file only once](https://github.com/ArduPilot/ardupilot/blob/8fe927c1d3eb6be9da8544ac48f7ec210abf5789/Tools/autotest/default_params/sub.parm#L5) (helps find copy/paste errors)
- [We don't try …
=> CI: validate parameter files

libraries/AP_Beacon/AP_Beacon_config.h
ArduPilot doesn't have room for every feature it can have, and hasn't for some time.
=> AP_Beacon: disable feature due to flash space constraints

libraries/RC_Channel/RC_Channel.cpp
Fixes CubeOrange-periph-heavy build
=> RC_Channel: correct compile when Arming and/or AHRS not available

libraries/AC_Fence/AC_Fence.cpp
We were not clearing margin breaches in landing even though the actual breach (alt min) had been cleared
=> AC_Fence: ensure that margin breaches are reset on landing

AntennaTracker/ReleaseNotes.txt, AntennaTracker/version.h, ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, ArduPlane/ReleaseNotes.txt, ArduPlane/version.h, Rover/ReleaseNotes.txt, Rover/version.h
This is the 4.6.1-beta1 release PR.
This beta release includes only a single change to allow for a short beta period and speed release to avoid the firmware-erase-on-restart issue that has affected some boards that store parameters in flash
- https://github.com/ArduPilot/ardupilot/pull/30310
All feedback is very welcome!
=> ArduPilot 4.6.1-beta1 release

Tools/AP_Bootloader/board_types.txt
@Hwurzburg is working with this vendor, so moving the existing board ID is OK.
=> board_types.txt: reserve board IDs for Aerium

libraries/AP_Networking/AP_Networking_PPP.cpp, libraries/AP_Networking/config/lwipopts.h
this fixes two key issues with PPP:
- if we lost the link (eg. serial cable unplugged) then it did not properly restart the link when the cable is plugged back in
- if using hardware flow control and the UART write buffer fills up then we would sleep with the TCPIP lock held, which means if the main thread tries to send an IPv4 packet then it would block on the TCPIP lock, and we would watchdog
=> AP_Networking: make PPP much more robust

libraries/AP_Scripting/drivers/LTE_modem.lua, libraries/AP_Scripting/drivers/LTE_modem.md
This adds GSM 07.10 muxing to the LTE modem driver, allowing it to maintain separate AT command streams and data streams for PPP or transparent TCP
This allows us to query the signal strength and other information about the link while running PPP.
It also allows for auto-baudrate changing, so the user can set LTE_BAUD to a higher baud rate without having to pre-configure the modem.
=> AP_Scripting: add CMUX to LTE modem driver

ArduCopter/mode.h, ArduCopter/mode_poshold.cpp, ArduCopter/mode_zigzag.cpp
This is a zero compiler change:
```
```
=> Add unit extensions for variables in  PosHold and ZigZag units

ArduCopter/mode.cpp, ArduCopter/mode.h, ArduCopter/mode_auto.cpp
Minor follow up to https://github.com/ArduPilot/ardupilot/pull/30195, the method can be const.
=> Copter: modes: get_alt_above_ground_cm to const

Tools/AP_Periph/AP_Periph.h, Tools/AP_Periph/Parameters.cpp, Tools/AP_Periph/Parameters.h, Tools/AP_Periph/can.cpp, Tools/AP_Periph/rc_out.cpp
fixes #30345 
This adds a servo command timeout to match the existing ESC one. If no commands are received for longer than the timeout 0 PWM is output, this should stops ESCs and relax servos (depending on brand). 
This PR results from a real incident on a heli where CAN communication was lost due to a bad connection, but the periph device remained powered (lucky on the ground).  The RSC output for the head held at the last value and it stayed at full head speed. Independent of what the main flight controller did. The only way to stop the head was to wait for the battery to run out or to disconnect the power to the periph device or motor.
The existing ESC commands only really make scene for things which use the motor 1 to motor 32 servo functions. Although you theoretically could use them …
=> AP_Periph: add servo command timeout

libraries/AP_Logger/AP_Logger_File.cpp, libraries/SITL/SITL.cpp
If you start a sim without setting param SIM_SPEEDUP then it will default to -1. That can't be good. Luckily, what's actually used in the SITL code is target_speedup that can be fetched via get_speedup() within the Airplane class and that set_speedup() at boot does a sanity check on the param. However, AP_Logger looks directly at the param value and sets a timeout depending on that. 
When it's negative it hangs the logio thread.
This PR does two things:
change SIM_SPEEDUP default from -1 to +1
sanity check sitl->speedup in logger. It's the only place in the code that uses it
=> SITL: Fix SIM_SPEEDUP -1

Tools/AP_Bootloader/board_types.txt
Reserve range IDs 7120-7129 for Accton Godwit
And add id 7120 for Accton-Godwit, product model: GA1
Please visit for more: https://www.accton-iot.com/godwit/index.html
=> board_types.txt: Reserve board IDs for Accton Godwit.

libraries/AC_Avoidance/AP_OADatabase.cpp, libraries/AC_Avoidance/AP_OADatabase.h, libraries/AP_AIS/AP_AIS.cpp, libraries/AP_AIS/AP_AIS.h, libraries/AP_HAL_SITL/SITL_State_common.cpp, libraries/AP_HAL_SITL/SITL_State_common.h, libraries/AP_Proximity/AP_Proximity_Backend.cpp, libraries/SITL/SIM_AIS.cpp, libraries/SITL/SIM_AIS.h, libraries/SITL/SITL.cpp, libraries/SITL/SITL.h
This adds support for AIS vessels as a source for avoidance data. This allows a vehicle to navigate around them. It also does some minor fix-ups to both AIS and the OADatabase.
Features: 
- This converts the timeout parameter from a int8 to a int16, this allows longer timeouts. AIS messages can be quite low update-rates, anchored vessels are only required to update every 3 mins. So the timeout must be longer than 180 seconds, 127 was the maximum with the int8. A timeout of 10 minutes (600 seconds) might be a good value for AIS avoidance.
- The item refresh code now updates position, the current behavior is to just change the timeout, but not the position. This means the avoidance item will not update position until it is has changed by one radius, which here could be >100m.
- It is now …
=> AP_AIS: Populate OADatabase for avoidance

ArduCopter/mode.h, ArduCopter/mode_acro.cpp, ArduCopter/mode_acro_heli.cpp, ArduCopter/mode_drift.cpp, ArduCopter/mode_flowhold.cpp, ArduCopter/mode_sport.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl_Sub.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl_Sub.h, libraries/AC_AttitudeControl/AC_AttitudeControl_TS.cpp
No compiler change fixing units and comments.
To go in after #30120
`
`
=> Copter: Add and fix variable units

AntennaTracker/ReleaseNotes.txt, AntennaTracker/version.h, ArduCopter/ReleaseNotes.txt, ArduCopter/version.h, ArduPlane/ReleaseNotes.txt, ArduPlane/version.h, Rover/ReleaseNotes.txt, Rover/version.h
this updates the Plane, Copter, Rover and Tracker release notes and version for the 4.6.1 official release
There is actually one code change that's been merged to the [ArduPilot-4.6 branch ](https://github.com/ArduPilot/ardupilot/commits/ArduPilot-4.6/) but I think it is non-functional so it's not in the release notes
=> Plane/Copter/Rover/Tracker: 4.6.1 release

ArduSub/Parameters.cpp, ArduSub/failsafe.cpp, ArduSub/joystick.cpp
Pilot input failsafes historically forced RC overrides, which clears itself and leads to repeated re-entries. (BUG)
With the addition of RC failsafe,if  Pilot input failsafe(no rc, no manual control or rc override MAVLink messages) is also enabled, this leads to cycling RC failsafe clears and enters (in addition to the repeating Pilot input failsafe) .
The main issue was that pilot input failsafe sets RC overrides (clearing the pilot input failsafe) instead of just setting the channel RC values to trim like other vehicles do in RC failsafe. This PR fixes the **set_neutral_controls** function to not use rc overrides, but directly set the channel value to the trim value (this also allows unidirectional motors to be used)
the WARN ONLY RC failsafe action was slightly modified to not only …
=> Sub:correct operation of pilot input and rc failsafes

ArduCopter/mode.h, ArduCopter/mode_turtle.cpp, libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.h
This is similar in nature to the bug fix required for motor test in the fast rate loop (FYI @rmackay9). Races between the threads can cause uncontrolled motor output when switching modes.
There is still a bug with arming on a switch that I need to debug
=> Ensure atomic access to turtle mode state from rate thread

libraries/GCS_MAVLink/GCS_FTP.cpp
https://mavlink.io/en/services/ftp.html#reading-a-file-burstreadfile
Per the docs, `burst_complete` should be set to `1` on the last burst packet.
Currently, it's only being set on the 500th (hard-coded server-limit) packet. 
This change adjusts it so it's also set on the final burst packet if there are less than 500 response packets.
Note that an EOF NAK will still be sent afterwards, which isn't specified in the docs. This can be prevented by adding a `break;` to the check on line 533. However, I was hesitant to propose that in fear of breaking existing systems for detecting the end of a burst file read.
=> GCS_MAVLink: fix FTP burst complete indicator

.github/workflows/colcon.yml
This GitHub Action fails occasionally, so let's upgrade its MAVProxy to see if that provides more stable runs.
* https://pypi.org/project/MAVProxy --> v1.8.71
Given the changes in MAVProxy, should we upgrade?
* https://github.com/ArduPilot/MAVProxy/releases
* https://github.com/ArduPilot/ardupilot/pull/30369#issuecomment-2975476125
---
`pip install -U` can be quite opaque to readers because `pip install` currently has six `--u*` options.
% `python3 -m pip install --help | grep "\-\-u"`
```
--user                      Install to the Python user install directory for
-U, --upgrade               Upgrade all specified packages to the newest
--upgrade-strategy <upgrade_strategy>
--use-pep517                Use PEP 517 for building source distributions
--use-feature <feature>     Enable new …
```
=> colcon: Use current MAVProxy in GitHub Action

libraries/AP_GPS/AP_GPS.h, libraries/AP_Scripting/applets/net-ntrip.lua, libraries/AP_Scripting/applets/net-ntrip.md, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/lua_bindings.cpp, libraries/AP_Scripting/lua_bindings.h
Makes `AP_GPS::inject_data()` public and adds a Lua binding to it.
`net-ntrip.lua` applet makes use of that binding via a direct connection to an unsecure (http) NTRIP caster.
Tested on CUAV 7-Nano and Pixhawk v6X.
EDIT:
Failing a few chibios build tasks - perhaps I need an `#ifdef` guard - just not sure which to employ.
=> AP_Scripting: add gps:inject_data binding and NTRIP applet

libraries/AP_Scripting/tests/docs_check.py
... also avoid catching bare exception, handle the case where the regex isn't matching
```
pbarker@crun:~/rc/ardupilot(pr/docs-check-flake8)$ flake8 libraries/AP_Scripting/tests/docs_check.py
pbarker@crun:~/rc/ardupilot(pr/docs-check-flake8)$ 
```
Extracted from https://github.com/ArduPilot/ardupilot/pull/30272/files
=> AP_Scripting: docs_check.py: flake8 correctness

.github/workflows/colcon.yml, Tools/ros2/ardupilot_dds_tests/setup.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/conftest.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/launch_fixtures.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_battery_msg_received.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_geopose_msg_received.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_joy_msg_received.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_navsat_msg_received.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_parameter_service.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_plane_airspeed.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_prearm_service.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_rc_msg_received.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_time_msg_received.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_virtual_ports.py
Ongoing attempt to improve stability in the DDS `colcon` CI tests.
- The tests that run the `micro_ros_agent` with `serial` transport require a temporary directory for the virtual devices `tty0` and `tty1` managed by `socat`. This changes the fixture that creates the temp `dev` folder to have `function` rather than `module` scope. This ensures that the directory is torn down after every test.
- Other fixtures use `function` scope by default, this makes that explicit.
- Use `extras_require` in `setup.py` as `tests_require` is removed from newer versions of setuptools. See discussion and suggestions in: https://github.com/ros2/ros2_documentation/issues/4727
- Increase `pytest` verbosity and run stepwise.
- Increase the timeout while waiting for processes to start and synchronise
- Ensure …
=> Tools: ros2: improve stability of DDS CI tests

Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_virtual_ports.py
https://github.com/ArduPilot/ardupilot/pull/30396 includes a change with invalid `black` formatting. Was not reported in CI but is being picked up by precommit hook.
Further discussion here: 
- https://github.com/ArduPilot/ardupilot/pull/30427#discussion_r2160420068
- https://discord.com/channels/674039678562861068/850924523610963988/1386408054823719165
=> Tools: ros2: satisfy formatter

Tools/scripts/build_tests/test_ccache.py
`Tools/scripts/build_tests/test_ccache.py` has a filename that will make Pytest Discovery think that it should be tested.
* https://docs.pytest.org/en/stable/explanation/goodpractices.html#conventions-for-python-test-discovery
This script also has code ___at global scope___ that will fail if certain command line arguments are not provided.
The proposed change is to put that code under `if __name__ == "__main__":` so it will not be run at test time.
* https://docs.python.org/3/library/__main__.html
Search for `test_ccache`:
* https://github.com/search?q=repo%3AArduPilot%2Fardupilot%20test_ccache&type=code
How was this tested?
1. `pytest Tools/scripts/build_tests/test_ccache.py`
2. `pytest Tools`
Both of the above find no tests instead of crashing with a long, confusing error.
=> Tools: Fix `test_ccache.py` to not confuse pytest discovery

Tools/scripts/decode_devid.py
This adds the AUAV baro and speed sensor to the decode devid script.
https://github.com/ArduPilot/ardupilot/blob/589708df48bb76302d9a725ae2b0f7e36f69475b/libraries/AP_Baro/AP_Baro_Backend.h#L58
https://github.com/ArduPilot/ardupilot/blob/589708df48bb76302d9a725ae2b0f7e36f69475b/libraries/AP_Airspeed/AP_Airspeed_Backend.h#L119
https://github.com/ArduPilot/WebTools/pull/255
=> Tools: scripts: decode devid: add latest airspeed and baro devices

Tools/AP_Bootloader/support.cpp, Tools/AP_Bootloader/support.h, libraries/AP_HAL_ChibiOS/hwdef/common/flash.c, libraries/AP_HAL_ChibiOS/hwdef/common/flash.h
Two different bugs here:
- Single ECC errors are not fatal and can occur fairly frequently. There is no need to erase the flash.
- We were checking the *whole* of flash but then only erasing the flash image if there was a problem, so if you had a problem in parameter storage the cure was worse than the disease.
=> Don't erase flash with single ECC errors and only erase checked flash

Tools/autotest/arducopter.py
we only emit the hearbeats at 1Hz, so reasonably easy to see that vagaries of scheduling might mean you won't see it on a 1s timeout!
2025-06-22T13:44:02.4408668Z AT-1949.5: Connect to the other serial port on the peripheral, which should also be talking mavlink 2025-06-22T13:44:03.4206967Z AT-1950.5: Exception caught: Did not get HEARTBEAT after 1.0033669471740723 seconds 2025-06-22T13:44:03.4207939Z Traceback (most recent call last):
2025-06-22T13:44:03.4209915Z   File "/__w/Leonard_ardupilot/Leonard_ardupilot/Tools/autotest/vehicle_test_suite.py", line 9028, in run_one_test_attempt
2025-06-22T13:44:03.4211111Z     test_function(**test_kwargs)
2025-06-22T13:44:03.4214559Z   File "/__w/Leonard_ardupilot/Leonard_ardupilot/Tools/autotest/arducopter.py", line 14148, in PeriphMultiUARTTunnel …
=> autotest: PeriphMultiUARTTunnel: allow more time for heartbeats to arrrive

libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp
If you are not using passthrough the version bootstrap never completes.
=> Make sure CRSF bootstrap completes when not using passthrough

libraries/AP_HAL_ChibiOS/hwdef/DroneerF405/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/FoxeerF405v2/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/MambaF405v2/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/SuccexF4/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/airbotf4/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/skyviper-f412-rev1/hwdef.dat, libraries/AP_HAL_ChibiOS/hwdef/skyviper-journey/hwdef.dat
this was never a Thing.  I'm sure we could track a lineage back to a single board and see them all copied from that....
this string doesn't exist in the codebase past this PR.
edit: now removes `HAL_CHIBIOS_ARCH_F412` too
=> hwdef: remove HAL_CHIBIOS_ARCH_F405 defines

Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_battery_msg_received.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_geopose_msg_received.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_navsat_msg_received.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_plane_airspeed.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_rc_msg_received.py, Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_time_msg_received.py
The event used to verify a message is received only needs to be set once in the test fixture subscriber callback.
=> Tools: ros2: set event once in test fixture callbacks

libraries/AP_Follow/AP_Follow.cpp, libraries/AP_Follow/AP_Follow.h
this removes the dual-use of the _alt_type parameter.
This parameter was changing both which input we accepted from the other vehicle (eg. GLOBAL_POSITION_INT.alt vs GLOBAL_POSITION_INT.relative_alt, but it was also specifying the return frame for the Location object returned from various methods.  This was somewhat confusing and unnecessary.
- all lua scripts in-tree canonicalise this to absolute altitude
- there are only two callers to these.  One is logging, meaning we will always now log in relative-to-origin numbers.  The secon is mavlink-reporting which canonicalises the altitude.  Many other `get_wp()` methods can return absolute-altitude locations.
=> AP_Follow: stop adjusting frame of return location based on parameter

libraries/AP_HAL_ChibiOS/hwdef/MatekL431-Periph/hwdef.dat
Matek's website says L431-Periph support NeoPixel, but since commit [e736d5ecb78bb6a5eb9bec4732a69bbbdf2336de](https://github.com/villivateur/ardupilot/commit/e736d5ecb78bb6a5eb9bec4732a69bbbdf2336de) , NeoPixel is not supported by default.
=> AP_HAL_ChibiOS: fix NeoPixel support for MatekL431-Periph

Tools/autotest/arducopter.py, libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp, libraries/AP_NavEKF3/AP_NavEKF3_core.h
The added autotest fails in master.
The problem is that EK3 will fuse in ExtNav Vertical Velocity even if it has been disabled in EK3_SRCx_VELZ which can cause a spectacular crash.
=> AP_NavEKF3: Allow extnav to work without vertical velocity

ArduPlane/Attitude.cpp, ArduPlane/Parameters.cpp, ArduPlane/defines.h, ArduPlane/mode.cpp
The current implementation of pitch stick mixing is unsafe, as it introduces an attitude override that is decoupled from the TECS, and also lacks any stall and overspeed prevention mechanisms. This means that if a pitch nudge is held long enough, an overspeed or a stall will occur.
This commit introduces a "FBW style (roll only)" setting to the STICK_MIXING parameter. It behaves like the current "FBWMixing" option for roll, but doesn't provide any pitch mixing. This is set as the default for improved safety.
Pitch stick mixing can be re-enabled by setting STICK_MIXING to "FBW-A style". This option replaces the removed "Direct" stick mixing mode in the enum. A warning about the lack of flight envelope protections in this mode has also been added to the description.
Related issue: …
=> Plane: Add roll-only stick mixing

libraries/RC_Channel/RC_Channel.cpp
this doesn't actually really fix a bug at the moment as ADSB is required for AVOID_ADSB.  But it is currently wrong
Board,copter
CubeOrange,*
=> RC_Channel: correct define gating AUX_FUNC::AVOID_ADSB

libraries/AP_TECS/AP_TECS.cpp
just whitespace changes
```
Board,plane
CubeOrange,*
```
Made it easier to look at a TECS problem at some stage.
=> AP_TECS: rearrange TEC3 log message field formatting

ArduSub/Parameters.h
0 is just the base value set in AP_Baro.cpp
See `HAL_BARO_PROBE_EXT_DEFAULT`
Hopefully we can move these defaults into a defaults.parm next to the navigator hwdef at some stage.
=> Sub: remove parameter default which is the base default anyway

.pre-commit-config.yaml
Locks in the changes made in:
* #30340
Completes step 2 of:
* https://github.com/ArduPilot/ardupilot/pull/30288#discussion_r2136752562
=> pre-commit: Remove the flake8 Tools-only restriction

libraries/AC_AutoTune/AC_AutoTune.cpp, libraries/AC_AutoTune/AC_AutoTune_Heli.cpp, libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
I have added an autotest that doesn't do the check but creates the abort. I have added events in the load sections so you can see which set of parameters are being used in the log.
The last commit should be removed before merging.
=> Quick Fix for Autotune in Copter 4.6

libraries/AP_Motors/AP_Motors_Class.h, libraries/AP_Motors/AP_Motors_config.h
TRI was already in the right place, move everything else
```
CubeOrange-periph-heavy  *                 *
Pixracer                            *      *           *       * …
```
=> AP_Motors: move defaulting of defines info AP_Motors_config.h

ArduPlane/Attitude.cpp
when assisting with VTOL motors we want to ensure the speed scaler is low to prevent reversed ailerons during a VTOL recovery
In recovery we can get negative airspeeds, we need to lower speed scalers
=> Plane: reduce speed scaler in assisted flight at low airspeed

libraries/AC_AttitudeControl/AC_PosControl.cpp
I've seen this on a few copters now - excellent attitude control but very poor position control because of oscillation. Seems to occur in somewhat underpowered or heavier copters. In discussions with @lthall it seems that 0.25 is a better default and has certainly fixed the problem in all cases that I have seen.
=> AC_AttitudeControl: change default for PSC_VELXY_D to 0.25 for better position control

libraries/AP_Mount/AP_Mount_SToRM32.cpp
This relaxes the SToRM32 mavlink gimbal driver's "find_gimbal" check so that instead of giving up after 60 seconds, it continues searching until the vehicle is armed.  This is consistent with the similar Gremsy mavlink gimbal ([see gremsy code here](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Mount/AP_Mount_Gremsy.cpp#L139))
This has not been tested because I do not have one of the gimbals myself.  Still, from inspection I'm fairly confident that it must be correct.
This was requested by one of the AP Partner companies
=> AP_Mount: SToRM32 search continues while disarmed

ArduPlane/AP_Arming.cpp, ArduPlane/GCS_Mavlink.cpp, ArduPlane/Parameters.cpp, ArduPlane/commands_logic.cpp, ArduPlane/defines.h, ArduPlane/mode_rtl.cpp, libraries/AP_Mission/AP_Mission.cpp, libraries/AP_Mission/AP_Mission.h
backport of https://github.com/ArduPilot/ardupilot/pull/28574
this brings the feature to plane. Copter already supports this in 4.6.x
this feature is very important for complex BVLOS missions
=> Plane: backport DO_RETURN_PATH_START to 4.6.x

libraries/AP_Airspeed/AP_Airspeed_Params.cpp
Pixhawk 6x has three external busses
=> AP_Airspeed:add I2C3 to metadata

ArduPlane/GCS_Plane.cpp, ArduPlane/Parameters.cpp, ArduPlane/Plane.h, ArduPlane/VTOL_Assist.cpp, ArduPlane/altitude.cpp, ArduPlane/defines.h, ArduPlane/mode_qland.cpp, ArduPlane/mode_qloiter.cpp, ArduPlane/mode_qrtl.cpp, ArduPlane/mode_takeoff.cpp, ArduPlane/parachute.cpp, ArduPlane/quadplane.cpp, ArduPlane/takeoff.cpp
this gives greater control of when the rangefinder will be used. A particularly important one is the ability to disable it for VTOL assist as false positives can be quite common and drains the battery
backport of https://github.com/ArduPilot/ardupilot/pull/30458
=> Plane: make RNGFND_LANDING a bitmask (4.6 backport)

libraries/AP_Camera/AP_Camera_MAVLinkCamV2.cpp
This modifies ArduPilto's AP_Camera MAVLinkV2 backend so that it specifies the camera's sysid and compid when sending commands instead of using the broadcast address (e.g. sysid=0, compid=0).
This issue was discovered while testing the [AirPixel TAG-E](https://shop.airpixel.cz/product/tag-e/) but will also affect the Gremsy camera gimbals with built-in cameras (e.g. the ZIO).
Without this fix, we can be sure that two mavlink enabled cameras will not work correctly because both cameras will likely respond to the broadcast messages.  In fact, the TAG-E does not current accept the commands unless this fix is made.
BTW there are 4 commands that the driver may send within [COMMAND_LONG](https://mavlink.io/en/messages/common.html#COMMAND_LONG) messages:
- …
=> AP_Camera: mavlink commands use target sysid and compid

libraries/SITL/SIM_GPS_SBP_Common.cpp
Since it is a pointer variable, I think using nullptr is better.
=> SITL: Since it is a pointer variable, it is compared with nullptr

Tools/autotest/arducopter.py
already have these in the base class, slightly differently named
base-class implementation also checks the new state
=> autotest: remove duplicate safetyswitch functions

libraries/AP_AccelCal/AP_AccelCal.cpp, libraries/AP_AccelCal/AP_AccelCal.h, libraries/GCS_MAVLink/GCS_Common.cpp
when AP is connected with a gremsy gimbal, and attempting to do an accel calibration, the calibration will fail based on the acceptance of mavlink ACK's from the gimbal, without the user having time to physically rotate the Autopilot
=> AP_AccelCal: accept ack only from initial source sysid/compid

libraries/AP_HAL_ChibiOS/hwdef/SkystarsH7HDv2/hwdef.dat
already present from files this one includes
```
SkystarsH7HD,*,*,*,*,*,*,*
SkystarsH7HD-bdshot,*,*,*,*,*,*,*
SkystarsH7HDv2,0,*,0,-8,-8,-8,-8
```
bytes saved from romfs.  No compiler output if the hwdef is left out
=> hwdef: SkystarsHD: remove pin defaults which are inherited

ArduCopter/Attitude.cpp, ArduCopter/Copter.cpp, ArduCopter/GCS_MAVLink_Copter.cpp, ArduCopter/RC_Channel_Copter.cpp, ArduCopter/autoyaw.cpp, ArduCopter/crash_check.cpp, ArduCopter/land_detector.cpp, ArduCopter/mode.h, ArduCopter/mode_acro.cpp, ArduCopter/mode_auto.cpp, ArduCopter/mode_circle.cpp, ArduCopter/mode_follow.cpp, ArduCopter/mode_guided.cpp, ArduCopter/mode_loiter.cpp, ArduCopter/mode_rtl.cpp, ArduCopter/mode_smart_rtl.cpp, ArduCopter/mode_zigzag.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.h, libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_AttitudeControl/AC_PosControl.h, libraries/AC_WPNav/AC_Circle.h, libraries/AC_WPNav/AC_Loiter.h, libraries/AC_WPNav/AC_WPNav.cpp, libraries/AC_WPNav/AC_WPNav.h, libraries/AC_WPNav/AC_WPNav_OA.cpp, libraries/AC_WPNav/AC_WPNav_OA.h, libraries/AP_Math/location.cpp, libraries/AP_Math/location.h
To follow #30412
```
CubeOrange,*,*,-16,16,40,*,40
```
=> Copter: Remove most of the remaining _cd() functions

Tools/scripts/param_check.py
… argument
```diff
- parts = re.split(r'[,=\s]+', processed_line, 1)
+ parts = re.split(r'[,=\s]+', processed_line, maxsplit=1)
```
Pytest: `DeprecationWarning: 'maxsplit' is passed as positional argument`
* https://docs.python.org/3/library/re.html#re.split
> Deprecated since version 3.13: Passing maxsplit and flags as positional arguments is deprecated. In future Python versions they will be [keyword-only parameters](https://docs.python.org/3/glossary.html#keyword-only-parameter).
Localhost testing...
% `python -m pytest --ignore=Tools/ros2`
```
========================================== test session starts ==========================================
platform darwin -- Python 3.13.5, pytest-8.4.1, pluggy-1.6.0
rootdir: /Users/cclauss/Python/ardupilot
configfile: pyproject.toml
collected …
```
=> Tools: Fix pytest DeprecationWarning: 'maxsplit' is passed as positional

Tools/Replay/examples/rewrite-RFND-values-to-floats.py
% `uvx --with=pep8-naming flake8 --disable-noqa --select=N805 .`
https://pypi.org/project/pep8-naming:
> N805 first argument of a method should be named ‘self’
Should this be a standalone function or a @staticmethod because it does not attempt to access to `self`?
* https://docs.python.org/3/library/functions.html#staticmethod
* https://docs.astral.sh/ruff/rules/invalid-first-argument-name-for-method
=> Tools: First argument of a method should be named 'self'

.github/workflows/test_branch_conventions.yml
This fixes a problem where the list of commits being checked was incorrect.
We were testing all of the commits between the PR head commit and the user's repository's master commit (where they'd branched their PR).
This was because the use of ref: changes origin.
I've fixed this and we're now printing the list of commits we are testing as part of the checks.
=> .github: correct list of commits being checked for sanity

Tools/autotest/arduplane.py, libraries/AP_Param/AP_Param.cpp, libraries/AP_Scripting/applets/UniversalAutoLand.lua
This adds a check for adding duplicated param names from scripting. Duplicate param names confuse GCS's. This checks against all existing params, so you cannot add a param that conflicts with a C++ one, you also cannot add a param that would conflict with another param added by a script either in the same script or in another script. Scripting restarts still work.
This is loading plane aerobatics on master (CubeOrangePlus):
811853us is 0.81 seconds.
On this branch:
824554us is 0.82 seconds
Plane aerobatics loads on the order of 40 params, it seems to be in the noise of the measurement. The script already does a fetch by name when adding the parameter to get the object into the script, we now do another one per param. This script does lots of other setup stuff in its first call, I'm sure …
=> AP_Param: check for duplicate names when adding scripting params

ArduPlane/Parameters.cpp, ArduPlane/Plane.h, ArduPlane/defines.h, ArduPlane/reverse_thrust.cpp
fixes https://github.com/ArduPilot/ardupilot/issues/30530
There was a early return for the `USE_REV_THRUST` 0 case which should not have been there. `USE_REV_THRUST` defaults to 2 so we have never noticed this before as the parameter is rarely changed.
This also updates the enum to a enum class and adds a helper.
=> Plane: rework `allow_reverse_thrust` to allow reverse thrust in manual modes with `USE_REV_THRUST` 0

libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
Negative RPM's being sent by DroneCAN ESC's are shown as "0" in GCS since in the mavlink message ESC_TELEMETRY_1_TO_4, the "rpm" field is a uint16_t. 
This patch correctly sends the RPM again.
=> AP_ESC_Telem: Handle negative RPM

Tools/autotest/rover.py, libraries/AP_HAL_SITL/SITL_State.cpp, libraries/SITL/SIM_Rover.cpp
It isn't hard to replicate this in SITL; `arm throttle` followed by `arm safetyon` is sufficient.  The vehicle starts going in circles really, really fast.
=> SITL: correct safety switch behaviour in SITL for Rover

ArduCopter/AP_ExternalControl_Copter.cpp, ArduCopter/Copter.cpp, ArduCopter/GCS_MAVLink_Copter.cpp, ArduCopter/autoyaw.cpp, ArduCopter/mode.h, ArduCopter/mode_auto.cpp, ArduCopter/mode_guided.cpp
This PR replaces centi-degrees with radians.
I also found that mavlink uses radians rather than degrees in most key areas so I changed the two auto_yaw functions that use degrees to use radians instead. This keeps the code consistent and leaves the inconsistency where it is introduced.
```
CubeOrange,*,*,-128,-128,*,*,*
```
=> Change guided mode to use radians instead of centidegrees

Tools/ardupilotwaf/boards.py, wscript
This makes `./waf configure --board=MatekF405 --enable-volz` and `./waf configure --board=MatekF405 --enable-Volz` behave the same.
edit: now also replaces underscores with dashes, so
```
./waf configure --board=MatekF405 --enable-nmea-unicore`
```
works
=> waf: accept entirely lower case values for BUILD_OPTIONS options

ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduCopter/mode_circle.cpp, ArduCopter/tuning.cpp
hopefully a clearer name.
This is a no-compiler-output change:
```
Pixhawk1-1M-bdshot                  * …
```
=> Copter: rename radio_tuning to rc_tuning_param

ArduPlane/Plane.h, ArduPlane/navigation.cpp
TECS is very sensitive to oscillation when it has a changing airspeed target which results from triggering of MIN_GROUNDSPEED. To avoid this we quantise the target and apply a hysteresis. This greatly reduces the oscillation, although it isn't completely eliminated
Tested in SITL with high wind. Before the PR:
after:
SITL logs here:
https://uav.tridgell.net/tmp/MIN_GROUNDSPEED/
=> Plane: quantise the airspeed target from MIN_GROUNDSPEED

Tools/environment_install/install-prereqs-ubuntu.sh
Fixes issue #30477 
```diff
- SCRIPT_DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))
+ SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
=> Tools: Fix for failing preq ubuntu script due to whitespace in directory

Tools/scripts/board_list.py
stops SITL arm builds from being stripped for comparison
reinstates testing of sizes for SITL builds via `size_compare_branches.py`.
Before:
```
```
After:
```
SITL_arm_linux_gnueabihf,0,,0,0,0,0,0
SITL_x86_64_linux_gnu,0,,0,0,0,0,0
```
=> Tools: SITL toolchain names

libraries/AP_Scripting/drivers/LTE_modem.lua
avoid setting band and network if not wanted. On some modems even setting the "all bands" command can cause the modem to fail to register, so default to not changing existing modem settings unless the user asks to change them.
=> AP_Scripting: changed LTE_BAND and LTE_MCCMNC to no-change by default

ArduCopter/GCS_MAVLink_Copter.cpp, ArduSub/mode.h, libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_AttitudeControl/AC_PosControl.h, libraries/AC_AttitudeControl/AC_PosControl_Logging.cpp, libraries/AC_PID/AC_P_2D.h, libraries/AC_WPNav/AC_Loiter.cpp, libraries/AP_Math/control.cpp, libraries/AP_Math/control.h, libraries/AP_Math/location.cpp
This PR converts the AC_PosControl library from centimeters to meters for all internal state, inputs, and outputs.
The only exceptions are the PID objects that use IMAX, which continue operating in centimeters. This is intentional: IMAX limits the output of the integrator and is defined in the same units as the controller output. Changing it would require adjusting all associated parameter values, which is outside the scope of this PR.
This conversion introduces some code size overhead due to the need to support both *_cm and *_m interfaces during the transition. A follow-up PR will remove the centimeter-based interfaces and update core consumers of AC_PosControl (e.g. Loiter, RTL, Guided) to use the new meter-based API directly, recovering the added size and simplifying usage.
Plane is …
=> Copter: Change the position controller to m

libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_FTP.cpp
The pr solves the following problem:
In [mavsdk](https://github.com/mavlink/MAVSDK) ftp client message size is presented taking into account terminating null, but ardupilot compare file name len with message size not considering terminating null and return error.
Tested in sitl with [ftp client](https://github.com/mavlink/MAVSDK/tree/main/examples/ftp_client)
=> GCS_MAVLink: ftp receiving messages where size takes into account terminating null

libraries/AP_Networking/AP_Networking.cpp, libraries/AP_Networking/AP_Networking.h, libraries/AP_Networking/AP_Networking_Backend.cpp, libraries/AP_Networking/AP_Networking_Backend.h, libraries/AP_Networking/AP_Networking_PPP.cpp, libraries/AP_Networking/AP_Networking_PPP.h, libraries/AP_Networking/config/lwipopts.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
This allows for up to 3 PPP interfaces, allowing for both a ethernet adapter (such as a BotBloxDroneNet) and a LTE modem.
It also adds support for custom routes, which is needed to control the routing for multiple PPP interfaces
=> AP_Networking: support multiple PPP interfaces

ArduPlane/GCS_Plane.cpp, ArduPlane/Parameters.cpp, ArduPlane/Plane.h, ArduPlane/VTOL_Assist.cpp, ArduPlane/altitude.cpp, ArduPlane/defines.h, ArduPlane/mode_autoland.cpp, ArduPlane/mode_qland.cpp, ArduPlane/mode_qloiter.cpp, ArduPlane/mode_qrtl.cpp, ArduPlane/mode_takeoff.cpp, ArduPlane/parachute.cpp, ArduPlane/quadplane.cpp, ArduPlane/takeoff.cpp
this gives greater control of when the rangefinder will be used. A particularly important one is the ability to disable it for VTOL assist as false positives can be quite common and drains the battery
main question is if we should also rename to  RNGFND_USE or RNGFND_USE_MASK. I didn't for this PR, but could discuss
=> Plane: make RNGFND_LANDING a bitmask

libraries/AP_Scripting/lua/src/lobject.c
Using a builtin instruction (on Cortex M3/M4/M7) saves 268 bytes.
Tested that the result is the same for all values:
```c
#include <stdio.h>
#include <limits.h>
#include <inttypes.h>
int cl2_new(unsigned int x) {
const int bitwidth = CHAR_BIT*sizeof(x);
x--;
const int clz = x ? __builtin_clz(x) : bitwidth; // clz(0) is undefined
return bitwidth-clz;
}
int cl2_old(unsigned int x) {
static const uint8_t log_2[256] = {  /* log_2[i] = ceil(log2(i - 1)) */
0,1,2,2,3,3,3,3,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,
6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,
7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,
8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8, …
```
=> AP_Scripting: use native implementation of luaO_ceillog2

.github/dependabot.yml
* ArduPilot/pymavlink#1065
* —> ArduPilot/pymavlink#1077 
* [Keeping your software supply chain secure with Dependabot](https://docs.github.com/en/code-security/dependabot)
* [Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)
* [Configuration options for the  file - package-ecosystem](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem)
GitHub Actions are only used at CI test-time, while most other dependencies are also used at runtime.  This means that if the CI tests pass, maintainers have more confidence that the proposed changes will not break runtime.  
GitHub Actions …
=> .github: Keep Actions up to date with GitHub's Dependabot

libraries/AP_Scripting/lua/src/linit.c, libraries/AP_Scripting/lua/src/llex.c, libraries/AP_Scripting/lua/src/lobject.c, libraries/AP_Scripting/lua_scripts.cpp, libraries/AP_Scripting/tests/check.json
Removes the `utf8` library, the `\u{xxxx}` string escape, and the `%U` string formatting operator.
None of these are used by any of our examples and it's difficult to imagine a case where they would be used in the context of ArduPilot. They are also easy to substitute and implement in Lua itself. Removing them leaves error messages that directly say the operation is invalid so if there are any existing users they will get an obvious error and hopefully complain.
This doesn't change the ability to print or store utf8 sequences in any way (although the exact escape sequences used may need changing), so this shouldn't compromise existing or future language support, for example. The thing I can think that might be impaired is something that edits utf8 text, but I maintain the only applet that …
=> AP_Scripting: remove utf8 assistance code

libraries/AP_Param/AP_Param.cpp
It turns out that `find_by_name` is very slow so this switches to use `find`. Rather than doing a compare using the token this compares the param pointers. Functionality it the same. https://github.com/ArduPilot/ardupilot/pull/30636 https://github.com/ArduPilot/ardupilot/pull/30523
=> AP_Param: `add_param` rework `find_by_name` and token compare to `find` with pointer compare

libraries/AP_HAL_Linux/RCInput_RPI.cpp
The `fprintf` for the `LINUX_BOARD_TYPE` fails due to the format specifier that is incompatible with enums:
```
../../libraries/AP_HAL_Linux/RCInput_RPI.cpp: In member function ‘void Linux::RCInput_RPI::set_physical_addresses()’:
../../libraries/AP_HAL_Linux/RCInput_RPI.cpp:293:56: error: format ‘%i’ expects argument of type ‘int’, but argument 3 has type ‘Linux::LINUX_BOARD_TYPE’ [-Werror=format=]
293 |         fprintf(stderr,"Unknown Linux Board version!: %i\n", _version);
|                                                       ~^     ~~~~~~~~
|                                                        |     |
|                                                        int   Linux::LINUX_BOARD_TYPE
cc1plus: some warnings being treated as errors …
```
=> fix enum format

libraries/AP_BattMonitor/AP_BattMonitor.cpp, libraries/AP_BattMonitor/AP_BattMonitor.h
This removes a user of `AP_Param::find_by_name`.
=> AP_BattMonitor: remove param conversion to dynamic tables required for update from 4.1 to 4.2

libraries/AP_Param/AP_Param.cpp
the >= 0 for strncasecmp was incorrect
noticed during a dev call discussion
=> AP_Param: fixed find_by_name()

ArduCopter/mode_auto.cpp, ArduCopter/mode_guided.cpp, ArduCopter/mode_smart_rtl.cpp, ArduSub/mode_auto.cpp, ArduSub/mode_guided.cpp, libraries/AC_WPNav/AC_Circle.cpp, libraries/AC_WPNav/AC_Circle.h, libraries/AC_WPNav/AC_WPNav.cpp, libraries/AC_WPNav/AC_WPNav.h, libraries/AC_WPNav/AC_WPNav_OA.cpp, libraries/AC_WPNav/AC_WPNav_OA.h, libraries/AP_Math/location.h
=> Copter: AC_WPNav: No compiler change to fix naming conventions

Tools/autotest/arduplane.py
The test has always learned a marginal compass value (25-30, with failure at 35) and since commit `a52f911b` it has usually failed on my machine with a value of 40-45 presumably due to a small change in the flight path. It also occasionally fails in CI with similar values; presumably different machine speeds select a different part of the flight during which learning occurs.
Fix the issue by flying a straight level path to allow time for the GSF to converge, as that is used as the reference for learning according to the code. This results in a learned value of 5-10 which is much closer to the target and hopefully less sensitive to the particular machine.
=> autotest: improve `test.Plane.CompassLearnInFlight` robustness

ArduCopter/Copter.cpp, ArduCopter/Copter.h, ArduCopter/Parameters.cpp, ArduCopter/Parameters.h, ArduCopter/system.cpp, ArduPlane/Parameters.cpp, ArduPlane/Parameters.h, ArduPlane/Plane.cpp, ArduPlane/Plane.h, ArduPlane/system.cpp, ArduSub/Parameters.cpp, ArduSub/Parameters.h, ArduSub/Sub.cpp, ArduSub/Sub.h, ArduSub/system.cpp, Rover/Parameters.cpp, Rover/Parameters.h, Rover/Rover.cpp, Rover/Rover.h, Rover/system.cpp, libraries/AP_Param/AP_Param.cpp, libraries/AP_Param/AP_Param.h, libraries/AP_RPM/AP_RPM.cpp, libraries/AP_RPM/AP_RPM.h, libraries/AP_Vehicle/AP_Vehicle.cpp, libraries/AP_Vehicle/AP_Vehicle.h
This moves AP_RPM out of copter, plane, rover and sub to AP_Vehicle and runs at 50Hz. Copter was running at 40Hz, other vehicles were running at 10Hz. RPM can be a source for notch tracking, fast updates are important.
Tested param conversion with:
```
./Tools/autotest/test_param_upgrade.py --vehicle=arduplane --vehicle=arducopter --vehicle=rover --vehicle=ardusub --param "RPM1_TYPE=1" --param "RPM1_SCALING=2" --param "RPM1_MAX=3" --param "RPM1_MIN=4" --param "RPM1_MIN_QUAL=5" --param "RPM1_PIN=6" --param "RPM1_ESC_MASK=7" --param "RPM2_TYPE=8" --param "RPM2_SCALING=9" --param "RPM2_MAX=10" --param "RPM2_MIN=11" --param "RPM2_MIN_QUAL=12" --param "RPM2_PIN=13" --param "RPM2_ESC_MASK=14"
```
=> AP_RPM: move to vehicle and run at 50hz

ArduCopter/Parameters.cpp, ArduCopter/mode.cpp
This stops applying  `WP_NAVALT_MIN` during landings. Incorrect ground altitude estimates can mean we stop navigating too high and end up drifting a long way. This is not a problem for takeoff because the altitude is measured relative to where the takeoff is started.
A alternate might be to add a flight option bit to enable this behavior (but I think it should be disabled by defualt).
=> Copter: `WP_NAVALT_MIN` only apply to takeoff

Tools/autotest/arduplane.py
An ArduPilot partner reported that VFR_HUD.climbrate was all sorts of weird when soaring was engaged using an RC channel option.
This autotest reproduces the problem.  It seems to believe every ounce of airspeed is in Z:
```
// @Field: aspd_filt: filtered and constrained airspeed
// @Field: alt: AHRS altitude
// @Field: roll: AHRS roll
// @Field: raw: estimated air vertical speed
```
That seems to be coming from `calculate_aircraft_sinkrate`.
Results from that method:
```
AT-0004.5: AP: sinkrate(0.001175)=29.47827
AT-0004.5: AP: sinkrate(0.000952)=29.47533
AT-0004.5: AP: sinkrate(0.000836)=29.47239
```
=> autotest: reproduce soaring climb rate reporting bug

libraries/AP_OpticalFlow/AP_OpticalFlow.cpp, libraries/AP_OpticalFlow/AP_OpticalFlow.h, libraries/AP_OpticalFlow/AP_OpticalFlow_Backend.h, libraries/AP_OpticalFlow/AP_OpticalFlow_MAV.cpp, libraries/AP_OpticalFlow/AP_OpticalFlow_MAV.h
This is a simplified version of https://github.com/ArduPilot/ardupilot/pull/29355 and adds the following features:
1. MAVLink backend consumes the [OPTICAL_FLOW message's](https://mavlink.io/en/messages/common.html#OPTICAL_FLOW) flow_rates_x and flow_rates_y fields if they are ever non-zero.  I considered adding an options bit to allow the user to specify this to reduce the chance of a false positive but I think this will work
2. FLOW_OPTIONS parameter added with a single bit defined as "Stabilised" to allow users to specify their flow sensor is mounted on a gimbal.  For now this is only implemented for the MAVLink backend but it could potentially be extended to other backends.  BTW, sensors with built-in IMUs (like the Hereflow) do not need this bit set even if they are mounted on a …
=> AP_OpticalFlow: MAVLink backend accepts rad/s and supports roll/pitch stabilised sensor

AntennaTracker/tracking.cpp, ArduCopter/autoyaw.cpp, ArduCopter/mode_auto.cpp, ArduPlane/GCS_MAVLink_Plane.cpp, ArduPlane/Log.cpp, ArduPlane/Plane.h, ArduPlane/commands.cpp, ArduPlane/commands_logic.cpp, ArduPlane/mode_guided.cpp, ArduPlane/mode_qrtl.cpp, ArduPlane/mode_takeoff.cpp, ArduPlane/quadplane.cpp, ArduSub/commands.cpp, ArduSub/commands_logic.cpp, ArduSub/mode_auto.cpp, Blimp/commands.cpp, Rover/mode_auto.cpp, libraries/AC_PrecLand/AC_PrecLand.cpp, libraries/AP_AHRS/AP_AHRS.cpp, libraries/AP_Common/Location.h, libraries/AP_DAL/AP_DAL.h, libraries/AP_DAL/AP_DAL_GPS.cpp, libraries/AP_GPS/AP_GPS_Blended.cpp, libraries/AP_Landing/AP_Landing_Deepstall.cpp, libraries/AP_Landing/AP_Landing_Slope.cpp, libraries/AP_Mission/AP_Mission.cpp, libraries/AP_NavEKF2/AP_NavEKF2_PosVelFusion.cpp, libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp, libraries/GCS_MAVLink/GCS_Common.cpp
various changes to avoid use of the Location .alt field, which should be private.
Introduces several new helper functions on Location to help with this
Prevents access to `.alt` on some location objects, which should be private.
=> Apply various methods to avoid use of .alt in the Location object

ArduPlane/AP_Arming_Plane.cpp, ArduPlane/Plane.cpp, ArduPlane/commands_logic.cpp, ArduPlane/mode_LoiterAltQLand.cpp, ArduPlane/mode_guided.cpp, ArduPlane/mode_qhover.cpp, ArduPlane/mode_qland.cpp, ArduPlane/mode_qloiter.cpp, ArduPlane/mode_qrtl.cpp, ArduPlane/mode_rtl.cpp, ArduPlane/navigation.cpp, ArduPlane/qautotune.cpp, ArduPlane/quadplane.cpp, ArduPlane/quadplane.h
=> Add units and axis to quadplane code before doing PosControl meters conversion

libraries/AP_Scripting/examples/checksum_firmware.lua
Simply emits the CRC for the running firmware 10 seconds after boot.
```
AP: RCOut: PWM:1-14
AP: checksum_firmware: 0x7C7954E6
MANUAL> 
MANUAL> ftp crc @SYS/flash.bin
MANUAL> Getting CRC for @SYS/flash.bin
crc: @SYS/flash.bin 0x7c7954e6 in 0.1s
AP: PreArm: Hardware safety switch
```
=> AP_Scripting: add example which prints checksum of @SYS/flash.bin

libraries/AP_Mount/AP_Mount_XFRobot.cpp
This resolves an issue with the XFRobot Z-1 mini camera gimbal's pitch drifting if it is pointed straight down for more than about 30 seconds.  The cause of the problem is we were sending the earth-frame Z-axis acceleration incorrectly.  Not only was the direction wrong but we also need to subtract gravity.
This has been tested on real hardware
=> AP_Mount: fix accels sent to XFRobot camera gimbal

libraries/AP_NavEKF3/AP_NavEKF3.cpp
This renames the EK3_MAX_FLOW parameter to EK3_FLOW_MAX so that it appears with other EK3_FLOW_xxx parameters and improves "discoverability" by users.
**Before**
**After**
This is a very rarely used parameter and I don't see it in any of our parameter files so I don't think we need to worry too much about users being surprised by the name change.
=> AP_NavEKF3: rename EK3_MAX_FLOW to EK3_FLOW_MAX

ArduCopter/mode.cpp, libraries/AC_WPNav/AC_Circle.cpp, libraries/AC_WPNav/AC_Circle.h, libraries/AC_WPNav/AC_WPNav.cpp, libraries/AC_WPNav/AC_WPNav.h, libraries/AC_WPNav/AC_WPNav_OA.cpp, libraries/AC_WPNav/AC_WPNav_OA.h
This PR refactors the AC_WPNav library to use meters as the internal unit for all waypoint navigation calculations, aligning it with the rest of the position control stack. The existing centimeter-based functions have been preserved as wrappers for compatibility but marked clearly with *_cm suffixes and updated comments.
Key changes:
- All internal NEU vectors and related calculations now operate in meters
- Added parallel *_m versions of all public cm-based methods
- Updated all function comments:
- cm-version comments now reference the meter version and list units only
- m-version comments provide the full behavioral description
- Parameter and macro comments reviewed and corrected for clarity and unit consistency
- Internal comments updated throughout AC_WPNav.cpp for improved …
=> Convert AC_WPNav library from centimeters to meters with backward-compatible cm interfaces

ArduSub/Attitude.cpp
It doesn't seem to make sense to apply reasonableness limits _after_ using the value - that would mean the first call doesn't use the limits.
=> ArduSub: Attitude.cpp: limit throttle deadzone before use

Tools/CPUInfo/CPUInfo.cpp, Tools/ardupilotwaf/ardupilotwaf.py, libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain5.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain7.cpp, libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.cpp, libraries/AP_ExternalAHRS/MicroStrain_common.cpp, libraries/AP_GPS/AP_GPS_GSOF.cpp, libraries/AP_GSOF/AP_GSOF.cpp, libraries/AP_HAL/AP_HAL_Macros.h, libraries/AP_HAL/utility/sparse-endian.h, libraries/AP_JSON/AP_JSON.cpp, libraries/AP_Math/AP_Math.cpp, libraries/AP_Math/AP_Math.h, libraries/AP_Math/definitions.h, libraries/AP_Math/examples/location/location.cpp, libraries/AP_Math/ftype.h, libraries/AP_Math/location_double.cpp, libraries/AP_NMEA_Output/AP_NMEA_Output.cpp
```
f103-QiotekPeriph        *                 *                                                   
f303-Universal …
```
=> replace ALLOW_DOUBLE_MATH_FUNCTIONS with AP_MATH_ALLOW_DOUBLE_FUNCTIONS

Tools/AP_Bootloader/board_types.txt
board_types.txt : add board ID for AP_HW_NarinX3.
=> board_types.txt : add board ID for AP_HW_NarinX3.

Tools/environment_install/install-prereqs-ubuntu.sh
Linux Mint Xia reports its distribution name as "Linuxmint" rather than "LinuxMint."
This PR forces lowercase comparison to avoid having to differentiate between the two.
=> Tools: environment_install: fix Linux Mint case mismatch

libraries/SITL/SIM_JSON.cpp, libraries/SITL/SIM_JSON.h, libraries/SITL/examples/JSON/pybullet/robot.py, libraries/SITL/examples/JSON/readme.md
extend with more data fields, and fixes for time sync control from JSON server. This avoids the need for a custom firmware for SimNet, allowing users to fly master/stable/beta etc.
Note: for this to work SimNet must be changed to send no_time_sync as true in the JSON.
This also fixes our pybullet example code to work with just pyBullet, removing the dependency on the defunct pyrobolearn package. It only supports the Iris and Racecar examples for now
=> SITL: support SimNet simulator

Tools/environment_install/install-prereqs-ubuntu.sh
Update for initial fix #30582 for bug #30477. Initial fix partially handled whitespace except during optional tool installs, wherein bug would still cause malformed $PATH to break Ubuntu PAM login.
=> Tools: Additional fix for ubuntu prereq script $PATH whitespace bug

ArduSub/GCS_MAVLink_Sub.cpp, ArduSub/failsafe.cpp, Rover/Rover.cpp, libraries/GCS_MAVLink/GCS.cpp, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp
this allows for multiple MAVLink source system IDs to be treated as valid GCS nodes, allowing for multiple ground stations for GCS failsafe handling
In more complex operations with handover between GCS operators or redundant GCS operators this helps ensure each GCS can use its own system ID
=> GCS_MAVLink: added MAV_GCS_SYSID_HI

ArduCopter/mode.h
This does depend a little on how you define `is_autopilot` of course. The thinking here is that there is no pilot input possible in brake mode, so it must be a autopilot mode.
This is only used in two places. One for notify:
https://github.com/ArduPilot/ardupilot/blob/46b1b35d59c453830611cd8105f19584e8821db0/ArduCopter/mode.cpp#L461-L466
The other for GCS failsafe:
https://github.com/ArduPilot/ardupilot/blob/46b1b35d59c453830611cd8105f19584e8821db0/ArduCopter/events.cpp#L223-L224
This is a change in behavior. Currently a GCS failsafe in Brake mode will result in no action if the failsafe bit is set (which it is by defualt). After this change it will take the specified action. The bit is described as:
"Continue if in pilot controlled modes on GCS failsafe"
I don't think anyone would expect …
=> Copter: Brake mode is a autopilot mode as there is no pilot input

ArduPlane/GCS_MAVLink_Plane.cpp, ArduPlane/Plane.cpp, ArduPlane/VTOL_Assist.cpp, ArduPlane/commands_logic.cpp, ArduPlane/mode_qhover.cpp, ArduPlane/mode_qloiter.cpp, ArduPlane/mode_qrtl.cpp, ArduPlane/qautotune.cpp, ArduPlane/quadplane.cpp, ArduPlane/quadplane.h
Reclaim lost space by moving all AC_PosControl  and AC_WPNav accessors to m. We should get a little more back as I restructure both to compile out any cm accessors in the .h file.
```
CubeOrange,*,*,*,*,-1232,*,*
```
=> Plane: integrate AC_PosControl and AC_WPNav move to meters

Tools/AP_Bootloader/bl_protocol.cpp, Tools/AP_Bootloader/support.cpp, Tools/AP_Bootloader/support.h, libraries/AP_HAL_ChibiOS/GPIO.cpp, libraries/AP_HAL_ChibiOS/GPIO.h, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Saves ~500 bytes mostly by removing unused GPIO interrupt support. Please see commits for details.
Tested on CubeOrange that this boots and can accept a USB flash.
=> Tools/AP_Bootloader: save flash

libraries/AP_HAL/tests/test_vsnprintf.cpp, libraries/AP_HAL/utility/ftoa_engine.cpp
Alternative to #30754 to close #30722 . I have been severely nerd-sniped but here goes... Please see the commit messages for further detail.
This applies to anything that uses `%f` with `hal.util->snprintf` or the things we use linker wraps (augh) to point to that.
Resolves two problems. Out of the ~4.2 billion floats:
* Subnormal numbers are printed as half their true value. e.g. `0.<sufficient zeros>2` was printed as `0.<same zeros>1`. This affects the ~16.7 million non-zero values `fabsf(v) < 1.175494e-38f` (FLT_MIN).
* The 26 smallest non-zero floats (`fabsf(v) <= 2e-44f`) will get stuck in an infinite loop if formatted, causing a watchdog reboot even in flight if executed on the main thread!
Notices and does not resolve two additional problems:
* The requested number of digits is not …
=> AP_HAL: fix up `ftoa_engine` to avoid wrong results and hangs

Rover/mode_follow.cpp
Fix for #29786.
Changes to the behaviour of Follow mode to ignore small velocities.
=> Rover: Better handling of stopped leader in Follow mode

ArduPlane/Parameters.cpp, ArduPlane/Parameters.h, ArduPlane/altitude.cpp
Description
-----------
Slope treatment for a flight leg was conditioned to a minimum height of 20m (which was a hardcoded value and only documented in a comment in the code), below which an immediate altitude change was performed for that leg. This caused unpredictable results for flight plans with waypoints at exactly 20m followed by a climb, as the aircraft could, depending on chance, be above or below the height demand, resulting in very different trajectories.
This commit addresses that issue with the following changes:
- Added a parameter to control the minimum height at which a gradual climb slope can be performed. This documents the original feature and retains the safety aspect of it.
- Changed the behavior when below said minimum height to only immediately climb up to the safe …
=> Plane: Add climb slope minimum height parameter

ArduPlane/Attitude.cpp, ArduPlane/Parameters.cpp, ArduPlane/config.h
I can't help but think maybe I'm missing something here.....
Two of my Planes run non-standard defaults.  One at 60% and the other at 30% vs the 45% default...
=> Plane: use parameterised trim_throttle in place of constant value of TRIM_THROTTLE

libraries/AC_WPNav/AC_Loiter.cpp, libraries/AC_WPNav/AC_Loiter.h, libraries/AC_WPNav/AC_WPNav_OA.cpp, libraries/AC_WPNav/AC_WPNav_OA.h
```
CubeOrange,*,0,40,40,-264,*,-208
```
=> Convert WP_Nav (5): WPNav Object Avoidance library from centimetres to meters with backward-compatible cm interfaces

Tools/autotest/arduplane.py
we're really only after gross changes here, and that's taken care of by the three cases which are tested.
CI is getting values of 82 or 83 vs what I get on my machine here.  Vagaries of race conditions getting into this state, I believe.
May stop Plane-tests1a flapping.
=> autotest: loosen constrain on DO_CHANGE_SPEED

libraries/AP_Param/AP_Param.cpp, libraries/GCS_MAVLink/GCS.h, libraries/GCS_MAVLink/GCS_Common.cpp, libraries/GCS_MAVLink/GCS_FTP.cpp, libraries/GCS_MAVLink/GCS_FTP.h
This makes our MAVFTP server implementation multi-session, allowing multiple ground stations to be doing FTP operations at the same time, or even multiple sessions with a single GCS (if the GCS implements that)
This will make ftp more reliable from companion computers, and make running with more than one GCS more reliable
It is broken into two commits:
- one to move the FTP code to its own GCS_FTP class
- then 2nd commit to implement multi-session
=> GCS_MAVLink: support multiple MAVFTP sessions

.github/workflows/test_size.yml, Tools/scripts/build_ci.sh, Tools/scripts/size_compare_branches.py
5f76ae9e331c9cbd2e363e0c107dc68eafffc7a9 allowed us to retrieve the bootloader version at runtime.
Unfortunately the new `GIT_VERSION_EXTENDED` define was unique to every git commit, so we'd always end up with changes reported by `size_compare_branches.py`.
This PR just adds in another dummy variable value as we do for several others just like it
bootloader builds are repeatable again after this:
```
Board,bootloader
CubeOrange,*
```
=> Make bootloader builds repeatable again

libraries/AP_Vehicle/AP_Vehicle.cpp
This moves msp init down to after CAN manager. This means it now comes after:
- External AHRS
- Generator
- Stats
- Board config
- CAN manager
The result is that MSP serial protocols work over DroneCAN. Currently the serial port is not found because its not registered until DroneCAN init is done from CAN manager init.
Prior to this I was getting:
```
MSP DisplayPort uart not available
```
After this fix display port OSD works over a DroneCAN serial port.
=> AP_Vehicle: init msp after CAN manager

libraries/AP_Param/AP_Param.cpp
top level parameters don't have flags, but we need to fill in the flags return field as otherwise we can refuse to set a parameter based on it being internal and the allow_set_via_mavlink() check
backported from https://github.com/ArduPilot/ardupilot/pull/30628
=> AP_Param: ensure flags is filled in for find()

libraries/AP_Networking/AP_Networking.h, libraries/AP_Networking/AP_Networking_port.cpp
AP_Networking: cache port type in init. Without this you can change the Network port type at runtime and that could potentially be very bad.
=> AP_Networking: cache port type in init

libraries/AP_Mount/AP_Mount_Alexmos.cpp, libraries/AP_Mount/AP_Mount_Backend.cpp, libraries/AP_Mount/AP_Mount_Backend.h, libraries/AP_Mount/AP_Mount_CADDX.cpp, libraries/AP_Mount/AP_Mount_Gremsy.cpp, libraries/AP_Mount/AP_Mount_SToRM32.cpp, libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp, libraries/AP_Mount/AP_Mount_Scripting.cpp, libraries/AP_Mount/AP_Mount_Servo.cpp, libraries/AP_Mount/AP_Mount_Servo.h, libraries/AP_Mount/AP_Mount_Siyi.cpp, libraries/AP_Mount/AP_Mount_SoloGimbal.cpp, libraries/AP_Mount/AP_Mount_Topotek.cpp, libraries/AP_Mount/AP_Mount_Viewpro.cpp
Spiritual successor to #26944. This allows the mount retraction servo to be used regardless of the mount backend. Useful for e.g. a Storm32 gimbal that is itself being pulled into the fuselage by a servo.
I wanted to fix the branch first, but I realized the implementation can be much more compact. Unlike the other PR, this makes sure that **all** the corresponding servos are activated which allows for multi-servo setup. Only saps time at the mount mode changes so will not introduce any overhead (and if the servo function isn't configured the servo move method immediately quits anyway).
SITL-tested, will backport to a stable commit and test in a real aircraft in a couple of days.
=> AP_Mount: retract servo(s) operation for all backends

libraries/AC_PID/AC_PID.cpp, libraries/AC_PID/AC_PID.h, libraries/APM_Control/AP_FW_Controller.cpp, libraries/APM_Control/AP_YawController.cpp
Based on our discussion about the ArduPlane PID diagram with @IamPete1, it was noticed that there might be an issue with the feedforward scaling. 
Currently, the FF scaling takes into account FF+DFF, but it only updates the FF. This results in: 
1. DFF component is "unscaled"
2. FF component is "scaled" and updated with the contribution of the DFF term (i.e., FF+DFF)
3. The step 2 affects the logging info of the FF component
This aims to update the FF and DFF components by scaling them separately.
=> Update feedforward scaling for plane controllers

Tools/autotest/arducopter.py, Tools/autotest/vehicle_test_suite.py, libraries/AP_Param/AP_Param.cpp, libraries/AP_Param/AP_Param.h
Gaps have their entries marked as "hidden" - but we don't unset that flag when we register a parameter in that gap.
New test fails before and passes afterwards.
This work sponsored by Freespace Solutions.
=> Correct LUA parameter registration for out-of-order indexes

ArduPlane/Attitude.cpp, ArduPlane/Parameters.cpp, ArduPlane/Plane.h, ArduPlane/defines.h
Aerodynamic load factor-based roll demand limits were only applied down to ±25º to keep the aircraft maneuverable with a bad airspeed estimate. However, with the addition of the AIRSPEED_STALL parameter, this is unsafe if the aircraft is actually flying very close to its stall speed, and can result in a spin (this has actually happened to us in a real flight flying with a bit of wind and turbulence with the airspeed target set to AIRSPEED_MIN).
This PR makes it possible for the roll demand limits to go all the way down to 0º if an airspeed sensor is fitted and in use and the AIRSPEED_STALL parameter is set, as under these conditions, the airspeed estimate is accurate and there is very little bank angle overhead to prevent a stall.
=> Plane: Use accurate roll limits if airspd. sensor

libraries/GCS_MAVLink/GCS_MAVLink.h
new release of pymavlink with some important fixes
this is failing to build due to a new dependency on python3-dev
ping @robertlong13
=> mavlink: update to master of pymavlink

libraries/AP_Arming/AP_Arming.cpp, libraries/AP_Arming/AP_Arming.h
when ICE motors are running (and they are commonly started before arming) the IMU noise can overwhelm the IMU consistency checks, preventing arming. This gives the user a way to disable that check
alternative to #25905
=> AP_Arming: added option to disable IMU check with ICE running

Tools/scripts/build_options.py, Tools/scripts/extract_features.py, libraries/AP_Networking/AP_Networking.cpp, libraries/AP_Networking/AP_Networking.h, libraries/AP_Networking/AP_Networking_Backend.cpp, libraries/AP_Networking/AP_Networking_Backend.h, libraries/AP_Networking/AP_Networking_ChibiOS.cpp, libraries/AP_Networking/AP_Networking_ChibiOS.h, libraries/AP_Networking/AP_Networking_Config.h, libraries/AP_Networking/AP_Networking_PPP.cpp, libraries/AP_Networking/AP_Networking_PPP.h, libraries/AP_Networking/config/lwipopts.h
This allows capturing of all packets (ethernet or PPP) to a pcap file which can be read by wireshark
this is very useful for debugging tricky networking issues
tested on CubeOrange with BotbloxDroneNet and on Pixhawk6X
depends on: https://github.com/ArduPilot/lwip/pull/4
this also includes a new set of buffered write operations for logging in AP_Filesystem, based on stdio-like API calls
=> Networking: support capturing all packets to a pcap file

libraries/GCS_MAVLink/GCS_MAVLink.h
We use this same technique in GCS_Common.cpp
=> GCS_MAVLink: avoid stringop warning

Tools/autotest/arducopter.py
calling the mavutil method slurps a bunch of messages which we don't want ot have happen here; we want to see a nice 5Hz update rate on the distance countdowns
=> autotest: create mav location from message cache

libraries/AP_HAL_SITL/SITL_State.cpp, libraries/SITL/SIM_Aircraft.cpp
... and a minor fix for clamps while we're at it.
=> Stop initialising Copter pwm output values in AP_HAL_SITL 

Tools/autotest/arducopter.py, Tools/autotest/vehicle_test_suite.py
I think something must have changed on the github servers to make this one semi-reliably fail now - but the logic here was always flawed.
Viewing this patch-wise or ignoring whitespace changes would work well - I took the opportunity to remove some no-longer-required infrastructure.
=> Fix flapping AC_Avoidance_Proximity_AVOID_ALT_MIN

ArduPlane/AP_Arming_Plane.cpp, ArduPlane/Parameters.cpp, ArduPlane/Parameters.h, ArduPlane/Plane.cpp, ArduPlane/Plane.h, ArduPlane/events.cpp, ArduPlane/radio.cpp, ArduPlane/system.cpp
Hi,
I tested the short failsafe feature, but found that it is currently not working as expected. It appears that others have encountered the same issue - short failsafe triggered immediately without `FS_SHORT_TIMEOUT`:
https://discuss.ardupilot.org/t/fs-short-timeout-not-changing-rc-failsafe-timeout/119625
This PR fixes the `FS_SHORT_TIMEOUT` handling logic to ensure that the failsafe trigger responds correctly.
It just uses the same mechanism that long failsafe did. And since [arm check](https://github.com/ArduPilot/ardupilot/blob/966588f7142919482efc342cceebf0927366e65c/ArduPlane/AP_Arming_Plane.cpp#L78) will ask `FS_SHORT_TIMEOUT` < `FS_LONG_TIMEOUT`, they are not treated as relatively timeout usage anymore. (We don't need to know when short failsafe happened for long failsafe)
In …
=> Plane: fix short failsafe

libraries/AP_HAL_SITL/SITL_State.cpp
the simulator specifically handles the zero case.  Probably not correctly (it zeroes the servo angle), but it is handled.
=> AP_HAL_SITL: Blimp: stop initialising pwm_output to 1000

libraries/AP_AHRS/AP_AHRS.h
This removes an extra dependency from the AP_AHRS.h file.  AP_NavCommon.h was being included twice within a few lines of each other
=> AP_AHRS: remove duplicate dependency

libraries/AP_Param/AP_Param.cpp
this should properly fix the issue Peter raises in this PR:
https://github.com/ArduPilot/ardupilot/pull/30897
note that I'm avoiding a mutex as the load() is expensive
=> AP_Param: fixed data race in param creation

Tools/autotest/autotest.py, Tools/autotest/vehicle_test_suite.py
This is disabled unless you
```
export AP_AUTOTEST_MOVE_LOGS_ON_FAILURE=0
```
... until it's been tested a bit.
=> autotest: do not move failed-test logs if not running on autotest server

Tools/autotest/arducopter.py, Tools/autotest/arduplane.py, Tools/autotest/quadplane.py, Tools/autotest/vehicle_test_suite.py, libraries/AP_Rally/AP_Rally.cpp, libraries/AP_Rally/AP_Rally.h, libraries/AP_Scripting/applets/arming-checks.lua, libraries/AP_Scripting/applets/arming-checks.md, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
This adds a Lua Applet for scripted arming checks. Each check can be set as mandatory (generates a prearm fail), warning (displays a message, but allows arming) or disabled by setting a parameter.
There is a set of standard checks that I find useful, of course new ones can be added. Any suggestions appreciated. I've just added a check for Rally Point further than RALLY_LIMIT_KM from the home location.
This is designed to get around the controversy that often arises about adding arming checks to c++. To some people particular checks are essential, while to others they are unnecessary or annoying. 
This works for plane, copter and rover for now, but as a base could easily be extended to other vehicles.
=> Scripted Arming Checks

libraries/AP_DAL/examples/AP_DAL_Standalone/main.cpp, libraries/AP_HAL/HAL.h, libraries/AP_HAL/SIMState.cpp, libraries/AP_HAL/SIMState.h, libraries/AP_HAL_SITL/HAL_SITL_Class.cpp, libraries/AP_HAL_SITL/SITL_State.cpp, libraries/AP_HAL_SITL/SITL_State.h
The implementations had drifted a little bit here; the stuff we use in SITL had been improved in a couple of ways which the SIMState stuff lacked.
=> Make wind simulation code common between AP_HAL_SITL and SimOnHW

Tools/autotest/quadplane.py
the tune on the aircraft causes sinusoidal oscilation which means we miss
=> autotest: make error on quadplane ship landing larger

Tools/autotest/quadplane.py
lock the servo in the pitched condition rather than bringing back to neutral
New:
master:
=> autotest: tweak qassist test servo output to more closely match scenario

libraries/AP_Motors/AP_MotorsHeli_Single.cpp
No functional change.
Just adding some clarification to the yaw trim parameter metadata, following a conversation with a user on discord.
=> AP_MotorsHeli: Add clarifying comments to yaw trim parameter metadata.

ArduPlane/quadplane.cpp, libraries/APM_Control/AP_RollController.cpp, libraries/APM_Control/AP_RollController.h
When we are recovering a VTOL plane from an upset attitude we use the fixed wing attitude controller. The roll rate limit RLL2SRV_RMAX can severely limit the speed of recovery as it also applies to the VTOL rate controller rate demand.
After discussions with @priseborough we decided it is best to just remove the limit when in a recovery operation. Getting the aircraft back upright very quickly is critical, if we take too long then the aircraft can get into a state where recovery becomes impossible.
=> Plane: remove the roll rate limit in fixed wing recovery

ArduPlane/Log.cpp, ArduPlane/Plane.cpp, ArduPlane/Plane.h
this was requested by the developers of FlightCoach to improve the display of the ribbon by ensuring that all the data they use is time aligned.
=> Plane: added BBX messages for blackbox logging

libraries/AP_GPS/AP_GPS_Blended.cpp
if a GPS loses fix then we do not necessarily become unhealthy - there's a health counter which updates and must pass a threshold to be unhealthy.
If we zero the blended weights when a GPS loses fix *and* the other has a fix then we will end up not only having a bad location but also having zero velocities and accuracies as we multiply by the weights to find a blended number.
Using stale eights would seem to be the only option if we want to have hysteresis on the blended health even when a GPS loses its fix
=> AP_GPS: do not zero blended weights if no-fix from a GPS

Tools/autotest/autotest.py
Stacking individual tests on the one line isn't the same as running the entire suite as we fire up a new vehicle_test_suite for each test.  This change uses the same suite to run multiple specified tests.
e.g. ./Tools/autotest/autotest.py test.QuadPlane.DCMClimbRate,RTL_AUTOLAND_1  --show-test
=> autotest: allow running multiple tests in one runner

Tools/scripts/size_compare_branches.py, libraries/AP_HAL_ESP32/boards/esp32s3m5stampfly.h, libraries/AP_HAL_ESP32/hwdef/esp32s3m5stampfly/hwdef.dat, libraries/AP_HAL_ESP32/hwdef/scripts/esp32_hwdef.py
I've only changed the stampfly over, but it does compile :-)
New generated table:
```
// SPI bus table
#define HAL_ESP32_SPI_BUSES \
{ .host=SPI2_HOST, .dma_ch=SPI_DMA_CH_AUTO, .mosi=GPIO_NUM_14, .miso=GPIO_NUM_43, .sclk=GPIO_NUM_44 },
// SPI device table
#define HAL_ESP32_SPI_DEVICES \
{.name= "bmi270", .bus=0, .device=0, .cs=GPIO_NUM_46, .mode=3, .lspeed=10*MHZ, .hspeed=10*MHZ},\
{.name= "no_pixart", .bus=0, .device=1, .cs=GPIO_NUM_12, .mode=3, .lspeed=2*MHZ, .hspeed=2*MHZ}
```
vs
```
-#define HAL_ESP32_SPI_BUSES \
-    {.host=SPI2_HOST, .dma_ch=SPI_DMA_CH_AUTO, .mosi=GPIO_NUM_14, .miso=GPIO_NUM_43, .sclk=GPIO_NUM_44}
```
and
```
-#define HAL_ESP32_SPI_DEVICES \
-    {.name= "bmi270", .bus=0, .device=0, .cs=GPIO_NUM_46, .mode=3, .lspeed=10*MHZ, .hspeed=10*MHZ}, \
- …
```
=> AP_HAL_ESP32: allow SPI buses and devices to come from hwdef.dat files

libraries/AP_Motors/AP_MotorsHeli_RSC.cpp
This PR adds a safety barrier before declaring run-up complete if RSC mode 4 is used.
Currently the code would only look at the timer run-up to be completed, not considering the governor status. This would allow a take-off in Auto even if the governor has not succesfully engaged.
=> AP_Motors: add governor engage condition to rotor runup complete check

Tools/environment_install/install-prereqs-windows-andAPMSource.ps1, Tools/environment_install/install-prereqs-windows.ps1
It is impossible to install due to the dependency on fastcrc, which requires Rust, which cannot be built in Cygwin.
Fortunately, waf sets up its own local copy and a slower alternative is used if fastcrc is not available, so we can simply avoid trying to install it.
This setup script otherwise works and properly installs an environment which can at least build and run SITL.
=> Tools/environment_install: drop pymavlink from cygwin

libraries/AP_HAL/hwdef/scripts/hwdef.py, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py, libraries/AP_HAL_ESP32/hwdef/scripts/esp32_hwdef.py, libraries/AP_HAL_Linux/hwdef/scripts/linux_hwdef.py
No compiler output change
```
SITL_x86_64_linux_gnu               0                  0       0                 0      0 …
```
=> Add and use a write_device_table method for hwdef.py's to use

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, Tools/gittools/pre_commit_copyright.py, tests/test_pre_commit_copyright.py
Add a local pre-commit hook to verify the copyright notice is in all Python files in `Tools/ros2`.
% `pre-commit run check-copyright --verbose --all-files`
Make exceptions for:
```bash
Tools/gittools/pre_commit_copyright.py \
--ignore=Tools/ros2/ardupilot_dds_tests/setup.py \
--ignore=Tools/ros2/ardupilot_dds_tests/test/test_pep257.py \
--ignore=Tools/ros2/ardupilot_dds_tests/test/test_copyright.py
```
% `Tools/gittools/pre_commit_copyright.py`
```
Usage: python pre_commit_copyright.py file_path [...]
```
% `Tools/gittools/pre_commit_copyright.py README.md`
```
Copyright not found in: README.md
```
% `Tools/gittools/pre_commit_copyright.py README.md COPYING.txt`
```
Copyright not found in: COPYING.txt, README.md
```
% `Tools/gittools/pre_commit_copyright.py …
=> Tools: Add pre-commit hook to check copyright in ros2 files

.github/workflows/test_sitl_rover.yml, Tools/scripts/build_ci.sh
Avoids the tests failing after a while when pppd is not found.
Now the same as the install necessary for signing.
=> CI: fail fast on rover PPP install

libraries/AP_Scripting/AP_Scripting_SerialAccess.cpp, libraries/AP_Scripting/AP_Scripting_SerialAccess.h, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/examples/TraxxasVelineon.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/tests/luacheck.lua
This adds a script which uses a serial port to control a Traxxas Velineon ESC and receive ESC telem. The protocol is not documented, this is based on snooping on a receiver with a logic analyser. Its likely possible to get other data, but I only needed RPM.
This is a half duplex protocol, I could not get native half duplex working (possibly due to the input protection on the CubeOrange which I know can cause issues with the FrSky protocols). The work around is to just connect the RX and TX together and filter out our own messages in the script.
There is a bit of a annoying handshake to kick the ESC output of normal PWM mode, to get this working smoothly I added a binding for `set_unbuffered_writes` so the port sends immediately. 
I also found that the `esc_telem:update_rpm` method was …
=> AP_Scripting: add example script for Traxxas Velineon ESC's

.github/workflows/test_environment.yml, Tools/environment_install/install-prereqs-ubuntu.sh
Adds Debian 13 (Trixie) support to install script.
- Increments SFML libs to v2.6 for Trixie. `./waf configure --enable-sfml --enable-sfml-audio` builds succeed.
- Replaces `software-properties-common` with `ca-certificates` in Debian CI workflow.
- Fixes redundant install of git in Ubuntu CI workflow.
- Fixes cosmetic typos in CI workflow  ("SITL" was spelled, "STIL").
=> Tools/environment_install: add Debian Trixie

libraries/AP_HAL_ChibiOS/hwdef/scripts/defaults_periph.h
Means you can have defualt serial protocols in your hwdef and still build.
=> AP_HAL_ChibiOS: periph: check for existing define for serial protocols

Tools/autotest/arducopter.py, libraries/AC_WPNav/AC_Loiter.cpp, libraries/AC_WPNav/AC_Loiter.h
This provides automated coordinated turns to loiter.
WIKI TEXT:
Loiter Parameters
LOIT_OPTIONS: Loiter mode options
This parameter enables additional Loiter mode behaviours through a bit-mask.
Bit 0 – Enable Coordinated Turns:
When set, Loiter mode will automatically include coordinated turn logic. This adjusts the requested roll and pitch accelerations so that the vehicle’s motion matches both the horizontal velocity vector and the commanded yaw rate. The effect is that during turns in Loiter mode, the aircraft will naturally bank and pitch into the turn in a way that maintains coordinated flight, rather than skidding or sliding outward.
Coordinated Turns in Loiter
When Coordinated Turns are enabled (via the LOIT_OPTIONS parameter, Bit 0), the aircraft modifies its commanded …
=> AC_WPNav: Coordinated_Turn_Loiter

Tools/autotest/arduplane.py, Tools/autotest/run_mission.py
... otherwise we fail to read mission files correctly as we try to construct mission items with too many parameters
=> autotest: run_mission.py: set mavlink20 in environment

libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.cpp, libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.h
Currently, if there is a loss comm., the aircraft will always fly to the mission item specified with AFS_WP_COMMS.
I added an option so that if we have already passed AFS_WP_COMMS and got a loss. We should not go back to AFS_WP_COMMS. 
This is useful, for example, if the aircraft is already in the landing sequence. If there is a loss during a landing attempt, it should just land instead of starting the landing sequence again. 
I tested the change with Gazebo SITL.
=> AP_AdvancedFailsafe: option to not go back to the loss comm mission item if we are already in the return path

libraries/AC_AttitudeControl/AC_WeatherVane.cpp, libraries/AC_AttitudeControl/AC_WeatherVane.h
Weathervaning can change direction while still active, for example when transitioning into or out of takeoff/landing. This changes to send a second GCS message with the new direction in that case. Currently only the start of the weathervaning would get a message. 
EG:
```
Weathervane Active: nose in
Weathervane Active: side in
```
This will also happen if you were to change the parameter value while weathervaning is active.
=> AC_AttitudeControl: WeatherVane: emit active message for change of direction

Rover/GCS_MAVLink_Rover.cpp, libraries/GCS_MAVLink/GCS_Common.cpp
In the MAVLINK message RC_CHANNELS_SCALED, the RSSI is represented as UINT8_MAX. I changed 255 to UINT8_MAX.
https://mavlink.io/en/messages/common.html#RC_CHANNELS_SCALED
=> Rover: Convert a literal value into a defined value

ArduCopter/mode_loiter.cpp, ArduCopter/tuning.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.cpp, libraries/AC_AttitudeControl/AC_AttitudeControl.h, libraries/AC_AttitudeControl/AC_PosControl.cpp, libraries/AC_AttitudeControl/AC_PosControl.h, libraries/AC_WPNav/AC_Circle.cpp, libraries/AC_WPNav/AC_Circle.h, libraries/AC_WPNav/AC_Loiter.cpp, libraries/AC_WPNav/AC_Loiter.h, libraries/AC_WPNav/AC_WPNav.cpp, libraries/AC_WPNav/AC_WPNav.h
Just what the name suggests.
```
CubeOrange,*,*,-64,-72,-120,*,-112
```
=> Convert Copter to meters (8): Remove unused functions

Tools/AP_Periph/AP_Periph.h, Tools/AP_Periph/can.cpp, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc
AP_Periph: fix notify vehicle_state bit-length bug
The CAN notify message value is a uint64 value which the main `vehicle_state` variable is so thats correct but the accessors for it is uint32. Whoops! While I was tripped up on that I also thought the `last_vehicle_state` was a backup to check for change but it was a ms timer and so the uint32 was correct so I renamed it to `last_vehicle_state_ms` for clarity.
=> AP_Periph: fix notify vehicle_state bit-length bug

ArduPlane/Plane.cpp, libraries/AP_Scheduler/AP_Scheduler.cpp, libraries/AP_Scheduler/AP_Scheduler.h
This PR follows up on #31138 and #30305 and should close #30234 
**Changes:**
- Simplify `get_loop_rate_hz`, `get_loop_period_us`, `get_loop_period_s` getters
- Removed lazy initialization logic
- Marked as `const`
- Updated comment to clarify initialization occurs only in `init()`
- Changed `_active_loop_rate_hz` type from `AP_Int16` to `uint16_t`
- Removed redundant scheduler validation in `ArduPlane`
These changes are only cleanup / style improvements, no functional behavior is changed.
**Tests**
- Build succesfully for sitl
=> AP_Scheduler: cleanup after  #31138  (remove redundant checks, clarify comments)

libraries/AP_Scripting/lua_scripts.cpp
This corrupts other MAVLink messages going out at the same time, particularly in CI, causing tests to fail because scripting restart and script initial startup messages are destroyed.
Instead use a MAVLink debug statustext, but only send it if the runtime measurement debug bit is on to avoid an obvious change in behavior and unnecessary appearance of a new message.
Tested on Cube Orange that the message appears at the right time. I don't love that it now requires an extra step and additional messages to see this but the CI fix is important. Closes #26478 .
We also still use `DEV_PRINTF` [here](https://github.com/ArduPilot/ardupilot/blob/a3041bd10f8b62e8157dbf68e55783577a8096c9/libraries/AP_Scripting/lua_scripts.cpp#L127) but that is probably less likely to cause a CI problem since we …
=> AP_Scripting: avoid `DEV_PRINTF` for initial memory usage

libraries/AP_Compass/AP_Compass.cpp, libraries/AP_Compass/AP_Compass_MSP.cpp, libraries/AP_Compass/AP_Compass_MSP.h
currently registering an MSP backend can't fail, so if we fail to register (e.g. out of slots) then we can end up overwriting other's data.
Add a probe method which can return nullptr on failure
=> AP_Compass: add a MSP probe method which can fail

libraries/AC_AttitudeControl/AC_PosControl.cpp
Addresses #31184.
This will have the side-effect that the parameter documentation will likely not be available to MP, when it connects to old firmwares who still have this parameter (pre 2022).
=> AC_AttitudeControl: Removed old reference to PSC_ACC_XY_FILT

libraries/AP_Scripting/drivers/VSPeak_flow_meter.lua, libraries/AP_Scripting/drivers/VSPeak_flow_meter.md
This PR as support for the [VSPeak Modell flow meter](https://www.vspeak-modell.de/en/flow-meter), in the form of a Lua script.
The manufacturer has sent me a sensor with developmental software, able to speak a plain binary packet that the script can easily receive and interpret.
It is unknown to me currently if this software is already in general production or only our partner who asked for it has the correct binary. FWIW The manufacturer does advertise compatibility with ArduPilot, thanks to this here script.
I have used a scripting battery backend sensor to fill in only the battery current and potentially the current consumed.
I make the convention that "current" stands of liters of fuel per hour.
See the attached instructions.
I have employed a hack in the parser to get out of a buggy …
=> AP_Scripting: Added VSPeak Modell flow meter driver

Tools/autotest/logger_metadata/parse.py
I noticed that for a few log messages on the [wiki](https://ardupilot.org/plane/docs/logmessages.html#gpa) and with MavExplorer's "logmessage help" commands give the incorrect unit for some fields, e.g.:
```
MAV> logmessage help GPA
GPS accuracy information
I      [μs]       : GPS instance number
TimeUS [instance] : Time since system startup
...
```
This is caused by a mismatch in the ordering of the fields in the logger help comments vs the true ordering of the fields, e.g.:
```
// @LoggerMessage: GPA
// @Description: GPS accuracy information
// @Field: I: GPS instance number
// @Field: TimeUS: Time since system startup
```
```
{ LOG_GPA_MSG,  sizeof(log_GPA), \
"GPA",  "QBCCCCfBIHeHH", "TimeUS,I,VDop,HAcc,VAcc,SAcc,YAcc,VV,SMS,Delta,AEl,RTCMFU,RTCMFD", "s#-mmnd-ssm--", "F-BBBB0-CCB--" , …
```
=> autotest: Ensure log message fields are in the correct order

libraries/AP_GPS/AP_GPS_Params.cpp, libraries/AP_GPS/AP_GPS_UBLOX.cpp, libraries/AP_GPS/AP_GPS_UBLOX.h
Added support for Navigation with Indian Constellation (NAVIC) to the u-blox GPS driver:
- Added NAVIC as GNSS identifier with value 0x07
- Added ConfigKey values for NAVIC signal enable and L5 band
- Updated GNSS mode parameter description to include NAVIC (bit 7)
- Added NAVIC configuration in F9 GNSS configuration
=> AP_GPS: Add support for NAVIC constellation in UBLOX driver

libraries/AP_HAL_ChibiOS/hwdef/3DRControlZeroG/README.md, libraries/AP_HAL_ChibiOS/hwdef/ACNS-CM4Pilot/README.md, libraries/AP_HAL_ChibiOS/hwdef/ACNS-F405AIO/README.md, libraries/AP_HAL_ChibiOS/hwdef/AET-H743-Basic/README.md, libraries/AP_HAL_ChibiOS/hwdef/ARK_FPV/README.md, libraries/AP_HAL_ChibiOS/hwdef/BROTHERHOBBYF405v3/README.md, libraries/AP_HAL_ChibiOS/hwdef/GEPRCF745BTHD/README.md, libraries/AP_HAL_ChibiOS/hwdef/GEPRC_TAKER_H743/README.md, libraries/AP_HAL_ChibiOS/hwdef/MFT-SEMA100/README.md, libraries/AP_HAL_ChibiOS/hwdef/MicoAir405Mini/README.md, libraries/AP_HAL_ChibiOS/hwdef/MicoAir405v2/README.md, libraries/AP_HAL_ChibiOS/hwdef/MicoAir743-AIO/README.md, libraries/AP_HAL_ChibiOS/hwdef/MicoAir743/README.md, libraries/AP_HAL_ChibiOS/hwdef/MicoAir743v2/README.md, libraries/AP_HAL_ChibiOS/hwdef/NxtPX4v2/README.md, libraries/AP_HAL_ChibiOS/hwdef/X-MAV-AP-H743v2/README.md
the hwdef define and param name are not the same (probably should be), so coders assume its the param name in the readmes...
=> hwdef: rename BATT_CURR_SCALE to BATT_AMP_PERVLT in board READMEs

Tools/ardupilotwaf/chibios.py, Tools/ardupilotwaf/esp32.py, Tools/ardupilotwaf/hal_common.py, Tools/ardupilotwaf/linux.py, Tools/scripts/run_flake8.py, libraries/AP_HAL/hwdef/scripts/hwdef.py, libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py, libraries/AP_HAL_ESP32/hwdef/scripts/esp32_hwdef.py, libraries/AP_HAL_Linux/hwdef/scripts/linux_hwdef.py
This removes a wart in the build system where environment variables from the hwdef generator were written to a Python Pickle file (not a Python source file as the name suggests) then read back in. This cleans that up to just pass the data directly. Unlike the implication in the source code, it was never really possible to use this file to add custom environment variables as it is unconditionally overwritten every compile. Please see the commits for details.
It also uncovers some more warts (for which fixes will be PRed later)
* The whole `load_env_vars` thing needs rethinking, it was not optional for a long time and can probably be cleaned up
* There should be no need to rerun the hwdef generator at build time, waf has mechanisms to preserve files
Tested that there is no compiler output …
=> ardupilotwaf: kill `env.py`

libraries/AP_Networking/AP_Networking.cpp
same option bit was being used in both cases
completely untested.  I reckon this will at least compile in CI.
=> AP_Networking: correct starting of CAN multicast server

Tools/autotest/arduplane.py, libraries/AP_Follow/AP_Follow.cpp, libraries/AP_Follow/AP_Follow.h, libraries/AP_Scripting/applets/plane_follow.lua, libraries/AP_Scripting/applets/plane_follow.md, libraries/AP_Scripting/docs/docs.lua, libraries/AP_Scripting/generator/description/bindings.desc, libraries/AP_Scripting/modules/mavlink_attitude.lua, libraries/AP_Scripting/modules/pid.lua
This creates a new Lua Script applet that implements "plane follow" - a fixed wing follow/chase functionality that runs in guided mode. The code uses the core AP_Follow library functionality and therefore uses most of the documented FOLL_ parameters that are used in Copter and Rover FOLLOW mode.
The kinematic extrapolation improvements made by @lthall significantly improved the quality and smoothness of the follow. 
I've made one small enhancement to make the follow Altitude sensitive as this was required by the partner who I worked with through this process. If FOLL_ALT_TYPE =  3:terrain then the follow altitude will be terrain relative. There is also a scripted FOLLP_OVR_ALT that forces the follow vehicle to use a specific altitude overriding the altitude it receives from the lead plane …
=> Plane follow lua applet

libraries/AP_DDS/AP_DDS_Client.cpp
This fixes a bug where the DDS initialisation silently fails if it's using UDP transport and the networking has not finished initialised.
This is noticeable on boards using PPP connections, where the PPP can take 5-10 seconds to come up. It was a bit tricky to track down, as it's sometimes networking would come up before DDS and vice versa.
Tested on CubeOrange with PPP connection to Raspberry Pi companion computer.
I also added in a commit for the IMU topic, changing the covariance for -1 to 0 (covariance unknown), which is more in line with ROS definition at https://docs.ros2.org/foxy/api/sensor_msgs/msg/Imu.html
=> DDS: Fix initialisation on UDP transport

.github/workflows/esp32_build.yml
A recent change has broken ESP-IDF. Downgrade until upstream fixes.
Also smooths the installation a little bit by removing redundant steps.
=> .github: downgrade pydantic for ESP-IDF install
